flow: "AffiliateInclude"
kind: "include"

entries:
  - id: "StartNode1"
    name: "UpdateCount"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode0"
    type: "call"
    ref: "ProcessAffiliatesABTest-CheckForRelatedABTests"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessAffiliate-GetProgramByRequest"
  - id: "CreateAffiliateSession1"
    type: "pipelet"
    ref: "CreateAffiliateSession"
  - id: "DecisionNode0"
    type: "decision"
    condition: "NewAffliatedSession"
  - id: "DecisionNode3"
    type: "decision"
    condition: "AffiliateProgram"
  - id: "DecisionNode4"
    type: "decision"
    condition: "AffiliatePartner"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "JoinNode0"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "ProgramUUID"
    bindings:
      SaveObject: "AffiliateSession:ProgramUUID"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "PartnerUUID"
    bindings:
      SaveObject: "AffiliateSession:PartnerUUID"

links:
  - from: "CallNode0"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "CreateAffiliateSession1"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "CreateAffiliateSession1"
    via: "next"
    to: "DecisionNode0"
    into: "in"
  - from: "DecisionNode0"
    via: "no"
    to: "JoinNode0"
    into: "in1"
  - from: "DecisionNode0"
    via: "yes"
    to: "CallNode0"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode4"
    via: "yes"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode0"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "CreateAffiliateSession1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
