flow: "ApprovalEscalation"
kind: "process"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Escalation"
    mode: "private"
    strict: false
    inputs:
      - key: "WorkflowActivity"
        type: "com.intershop.beehive.core.capi.workflow.WorkflowActivity"
        required: false

steps:
  - id: "Call1"
    type: "call"
  - id: "Decision1"
    type: "decision"
    condition: "WorkflowActivity:TimerPipeline"
  - id: "Decision2"
    type: "decision"
    condition: "WorkflowActivity:TimerDeadline"
  - id: "Decision4"
    type: "decision"
    condition: "WorkflowActivity:TimerDeadline:Time"
  - id: "DetermineUnit1"
    type: "pipelet"
    ref: "DetermineUnit"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "GetApprovalActivities1"
    type: "pipelet"
    ref: "GetApprovalActivities"
    bindings:
      Activities: "WorkflowActivities"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Loop1"
    type: "loop"
  - id: "RecalculateNextApprovalStep1"
    type: "pipelet"
    ref: "RecalculateNextApprovalStep"
    bindings:
      CurrentActivity: "WorkflowActivity"

links:
  - from: "Start1"
    via: "next"
    to: "DetermineUnit1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join4"
    into: "in1"
  - from: "Decision2"
    via: "yes"
    to: "Decision4"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Join2"
    into: "in3"
  - from: "Decision1"
    via: "no"
    to: "Join3"
    into: "in2"
  - from: "RecalculateNextApprovalStep1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "RecalculateNextApprovalStep1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Call1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Loop1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "DetermineUnit1"
    via: "next"
    to: "GetApprovalActivities1"
    into: "in"
  - from: "GetApprovalActivities1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Decision4"
    via: "yes"
    to: "Decision1"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Decision4"
    via: "no"
    to: "Join4"
    into: "in2"
  - from: "Loop1"
    via: "do"
    to: "Decision2"
    into: "in"
