flow: "BatchProcessPriceList"
kind: "process"

entries:
  - id: "StartNode1"
    name: "DeletePriceLists"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "ErrorProductBatchProcessing"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "PostBatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "DeletePriceScaleTables"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "InitBatch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      Object: "PriceScaleTableAssignment:ProductUUID"
      OutVector: "ScaledProductUUIDs"
      Iterator: "ProductUUIDIterator"
      InVector: "ScaledProductUUIDs"
      Objects: "null"
  - id: "Call7"
    type: "call"
    ref: "ProcessProductHistory-SaveProductSnapShot"
  - id: "CallNode1"
    type: "call"
    ref: "BatchProcessPriceList-Delete"
  - id: "CallNode13"
    type: "call"
    ref: "ViewChannelPriceListPrices-UnlockProduct"
  - id: "CallNode2"
    type: "call"
    ref: "BatchProcessPriceList-DeletePriceScaleTables"
  - id: "CallNode29"
    type: "call"
    ref: "ProcessPriceList-Delete"
  - id: "CallNode3"
    type: "call"
    ref: "BatchProcessPriceList-Prefix"
  - id: "CallNode32"
    type: "call"
    ref: "BatchProcessLog-CleanLogger"
  - id: "CallNode39"
    type: "call"
    ref: "BatchProcessLog-PrepareLogger"
  - id: "CallNode9"
    type: "call"
    ref: "ViewChannelPriceListPrices-LockProduct"
  - id: "CreateLogEntry1"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Error"
      Message: "Failed to process product with given SKU."
    bindings:
      Object0: "Product:SKU"
      Object1: "ErrorText"
  - id: "DecisionNode3"
    type: "decision"
    condition: "SelectCurrencyMnemonic"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "EndNode5"
    type: "end"
    strict: false
  - id: "EndNode6"
    type: "end"
    strict: false
  - id: "EndNode8"
    type: "end"
    strict: false
  - id: "GetCurrency3"
    type: "pipelet"
    ref: "GetCurrency"
    bindings:
      Mnemonic: "SelectCurrencyMnemonic"
  - id: "GetCurrency4"
    type: "pipelet"
    ref: "GetCurrency"
    bindings:
      Mnemonic: "CurrentSession:CurrencyCode"
  - id: "GetPriceScaleTablesByProduct1"
    type: "pipelet"
    ref: "GetPriceScaleTablesByProduct"
    config:
      Type: "All"
    bindings:
      CurrencyCode: "Currency:Mnemonic"
  - id: "GetProductByUUID2"
    type: "pipelet"
    ref: "GetProductByUUID"
    bindings:
      ProductDomain: "CurrentProductRepository:RepositoryDomain"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      UUID: "CurrentProductRepositoryUUID"
      Repository: "CurrentProductRepository"
  - id: "GetRepositoryByUUID2"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      UUID: "ChannelRepositoryUUID"
      Repository: "ChannelRepository"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "PriceList:UUID"
      OutValue_1: "PriceListUUID"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "ProductUUID"
      OutValue_1: "ProductID"
  - id: "Loop2"
    type: "loop"
  - id: "Loop3"
    type: "loop"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ErrorMap"
      OutMap: "ErrorMap"
      Keys: "LockErrorKeys"
      Key: "ProductUUID"
      Value: "\"ProductLocked\""
  - id: "RemovePriceScaleTable2"
    type: "pipelet"
    ref: "RemovePriceScaleTable"
    bindings:
      Table: "PriceScaleTable"

links:
  - from: "StartNode4"
    via: "next"
    to: "CallNode32"
    into: "in"
  - from: "Loop3"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "GetRepositoryByUUID2"
    via: "error"
    to: "EndNode3"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "CallNode1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "GetRepositoryByUUID2"
    via: "next"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "error"
    to: "EndNode3"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "AddObjectToVector1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CreateLogEntry1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "GetRepositoryByUUID2"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "GetPriceScaleTablesByProduct1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "RemovePriceScaleTable2"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "GetProductByUUID2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "JoinNode14"
    into: "in1"
  - from: "Loop2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "LoopNode2"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "GetPriceScaleTablesByProduct1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CreateLogEntry1"
    into: "in"
  - from: "RemovePriceScaleTable2"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "JoinNode14"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "GetProductByUUID2"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "Loop2"
    via: "do"
    to: "GetProductByUUID2"
    into: "in"
  - from: "CallNode9"
    via: "ERROR"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode14"
    into: "in3"
  - from: "GetCurrency4"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Loop3"
    via: "do"
    to: "CallNode2"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "CallNode39"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CallNode29"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Loop2"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "GetCurrency4"
    into: "in"
  - from: "GetCurrency3"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "GetCurrency3"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "CallNode32"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "CallNode39"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Loop3"
    into: "in"
  - from: "CallNode29"
    via: "next"
    to: "Loop3"
    into: "loop"
