flow: "BatchProcessPageAssignments"
kind: "job"

entries:
  - id: "StartNode1"
    name: "UnassignPages"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "InitUnassignPages"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "PostUnassignPages"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "InitEditVisibilityPeriod"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "EditVisibilityPeriod"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "PostEditVisibilityPeriod"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "BatchProcessLog-CleanLogger"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessDate-ConvertPeriodToDate"
    bindings:
      ValidFromDate: "ValidFrom"
      ValidToDate: "ValidTo"
  - id: "CallNode2"
    type: "call"
    ref: "BatchProcessLog-PrepareLogger"
  - id: "CallNode25"
    type: "call"
    ref: "BatchProcessLog-LogPageletResult"
  - id: "CallNode26"
    type: "call"
    ref: "BatchProcessLog-LogPageletResult"
  - id: "CallNode3"
    type: "call"
    ref: "BatchProcessLog-CleanLogger"
  - id: "CallNode4"
    type: "call"
    ref: "BatchProcessLog-PrepareLogger"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessPagelet-UpdatePageletAssignment"
    bindings:
      Active: "OnlineFlagBoolean"
      Assignment: "Assignment"
      ValidFrom: "ValidFrom"
      ValidTo: "ValidTo"
      Position: "Object:Position"
  - id: "DecisionNode1"
    type: "decision"
    condition: "OnlineFlag"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Assignment:DomainID"
  - id: "DecisionNode6"
    type: "decision"
    condition: "Assignment:DomainID"
  - id: "DeleteAssignment1"
    type: "pipelet"
    ref: "DeleteAssignment"
    bindings:
      Assignment: "Assignment"
      AssignmentFactory: "AssignmentStrategy:getAssignmentFactoryByTo(Assignment:To)"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "EndNode5"
    type: "end"
    strict: false
  - id: "EndNode6"
    type: "end"
    strict: false
  - id: "GetAssignmentStrategy1"
    type: "pipelet"
    ref: "GetAssignmentStrategy"
    config:
      FromClass: "com.intershop.component.pmc.capi.pagelet.Pagelet"
      ToClass: "com.intershop.component.pmc.capi.pagelet.PageletEntryPoint"
    bindings:
      Site: "JobConfiguration:Domain:Site"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "JobConfiguration:Domain"
      OutValue_1: "ContextDomain"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "JobConfiguration:Domain"
      OutValue_1: "ContextDomain"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "Result"
  - id: "Pipelet40"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "Result"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Result"
      Value: "Shared"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Result"
      Value: "Shared"
      ValueType: "Dictionary Value"
  - id: "VerifyBoolean1"
    type: "pipelet"
    ref: "VerifyBoolean"
    bindings:
      NoneLocalizedString: "OnlineFlag"
      BooleanValue: "OnlineFlagBoolean"

links:
  - from: "CallNode4"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "GetAssignmentStrategy1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "DeleteAssignment1"
    into: "in"
  - from: "DeleteAssignment1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "CallNode25"
    into: "in"
  - from: "CallNode26"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode7"
    into: "in3"
  - from: "LoopNode2"
    via: "do"
    to: "DecisionNode6"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "CallNode5"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "CallNode26"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "VerifyBoolean1"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "VerifyBoolean1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "VerifyBoolean1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "Pipelet40"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "StartNode5"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "LoopNode2"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "DecisionNode2"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetAssignmentStrategy1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "CallNode25"
    via: "next"
    to: "Pipelet40"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode6"
    into: "in3"
