flow: "BatchProcessPage"
kind: "process"

entries:
  - id: "Start2"
    name: "Init"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Finish"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Process"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "BatchProcessLog-PrepareLogger"
  - id: "CallNode10"
    type: "call"
    ref: "BatchProcessPageComponentAssignment-CreateLogEntry"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessAnalyzeTables-AnalyzeTables"
  - id: "CallNode4"
    type: "call"
    ref: "BatchProcessLog-CleanLogger"
  - id: "CloseJDBCConnection1"
    type: "pipelet"
    ref: "CloseJDBCConnection"
  - id: "CreateBatchProcessor1"
    type: "pipelet"
    ref: "CreateBatchProcessor"
    config:
      BatchProcessorClassName: "com.intershop.component.pmc.capi.batch.ReplacePageBatchProcessor"
      ConstructorParameterClassName_05: "com.intershop.beehive.core.capi.profile.Profile"
      ConstructorParameterClassName_04: "com.intershop.beehive.core.capi.domain.Domain"
      ConstructorParameterClassName_03: "com.intershop.component.pmc.capi.definition.pagelet.PageletDefinition"
      ConstructorParameterClassName_01: "java.sql.Connection"
      ConstructorParameterClassName_02: "com.intershop.beehive.core.capi.user.User"
    bindings:
      ConstructorParameter_01: "Connection"
      ConstructorParameter_05: "AuthorProfile"
      ConstructorParameter_04: "TargetDomain"
      ConstructorParameter_03: "PageletDefinition"
      ConstructorParameter_02: "JobConfiguration:CurrentProcess:User"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PageletQualifiedName"
  - id: "DecisionNode2"
    type: "decision"
    condition: "BatchErrors"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "ExecuteBatchProcessor1"
    type: "pipelet"
    ref: "ExecuteBatchProcessor"
  - id: "GetDomainByUUID1"
    type: "pipelet"
    ref: "GetDomainByUUID"
    bindings:
      Domain: "TargetDomain"
      DomainUUID: "TargetDomainUUID"
  - id: "GetDomainByUUID2"
    type: "pipelet"
    ref: "GetDomainByUUID"
    bindings:
      Domain: "Site"
      DomainUUID: "SiteUUID"
  - id: "GetProfile1"
    type: "pipelet"
    ref: "GetProfile"
    bindings:
      ProfileID: "AuthorProfileID"
      Profile: "AuthorProfile"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "LoadPageletDefinition1"
    type: "pipelet"
    ref: "LoadPageletDefinition"
    bindings:
      QualifiedName: "PageletQualifiedName"
  - id: "LoopNode1"
    type: "loop"
  - id: "OpenJDBCConnection1"
    type: "pipelet"
    ref: "OpenJDBCConnection"
    config:
      AutoCommit: false
      ConnectionCartridge: "core"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "RefreshCache"
    config:
      PersistentClassName_1: "com.intershop.component.pmc.internal.pagelet.PageletPO"
      PersistentClassName_2: "com.intershop.component.pmc.internal.pagelet.ConfigurationParameterPO"
      PersistentClassName_4: "com.intershop.component.pmc.internal.pagelet.SlotPO"
      PersistentClassName_5: "com.intershop.component.pmc.internal.pagelet.SlotPageletAssignmentPO"
      PersistentClassName_0: "com.intershop.component.pmc.internal.pagelet.assignment.AbstractPageletAssignmentPO"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "TableNames"
      ValueType: "Dictionary Value"
      Value: "catalogcategory_pa;pagelet;pagelet_av;configurationparameter;slot;slot_av;slotpageletassignment"

links:
  - from: "Start2"
    via: "next"
    to: "GetDomainByUUID1"
    into: "in"
  - from: "ExecuteBatchProcessor1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "GetDomainByUUID2"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "ExecuteBatchProcessor1"
    into: "in"
  - from: "OpenJDBCConnection1"
    via: "next"
    to: "CreateBatchProcessor1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "CallNode10"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "GetProfile1"
    via: "next"
    to: "OpenJDBCConnection1"
    into: "in"
  - from: "CreateBatchProcessor1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetDomainByUUID1"
    via: "next"
    to: "GetDomainByUUID2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode4"
    via: "next"
    to: "CloseJDBCConnection1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "Pipelet8"
    via: "next"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CloseJDBCConnection1"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode4"
    into: "in2"
  - from: "DecisionNode1"
    via: "yes"
    to: "LoadPageletDefinition1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "GetProfile1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "JoinNode5"
    into: "in1"
  - from: "LoopNode1"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "DecisionNode2"
    via: "no"
    to: "LoopNode1"
    into: "in"
  - from: "GetDomainByUUID2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "LoadPageletDefinition1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CreateBatchProcessor1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "CallNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "GetDomainByUUID1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "GetProfile1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
