flow: "BatchProcessSyndication"
kind: "process"

entries:
  - id: "Start1"
    name: "Internal"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Initialize"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Syndicate"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Finish"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "GetAssignedProducts"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "SyndicatedProducts"
      Object: "null"
      Objects: "AllObjects"
      OutVector: "SyndicatedProducts"
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "SyndicatedProducts"
      Iterator: "SyndicatedProducts"
      Object: "null"
      Objects: "null"
  - id: "Call1"
    type: "call"
    ref: "BatchProcessSyndication-Internal"
  - id: "CallNode1"
    type: "call"
    ref: "BatchProcessLog-PrepareLogger"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessAnalyzeTables-AnalyzeTables"
  - id: "CallNode3"
    type: "call"
    ref: "BatchProcessSyndication-Initialize"
  - id: "CallNode4"
    type: "call"
    ref: "BatchProcessLog-CleanLogger"
  - id: "CombineIterators1"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Concatenate Iterators"
    bindings:
      Iterator1: "ProductDataMappingRules"
      Iterator2: "ContentMappingRules"
      Iterator: "ProductDataMappingRules"
  - id: "CombineIterators2"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Concatenate Iterators and Remove Duplicates"
    bindings:
      Iterator: "AllObjects"
      Iterator1: "BundledAndMasteredProducts"
      Iterator2: "AllObjects"
  - id: "CreateSyndicationProcessor1"
    type: "pipelet"
    ref: "CreateSyndicationProcessor"
    bindings:
      RuleProcessors: "RuleProcessorsIterator"
      SyndicationRules: "ProductDataMappingRules"
  - id: "Decision1"
    type: "decision"
    condition: "Objects:ElementCount"
  - id: "Decision10"
    type: "decision"
    condition: "SelectedCategoryUUIDIterator"
  - id: "Decision2"
    type: "decision"
    condition: "SyndicatedProducts"
  - id: "DecisionNode1"
    type: "decision"
    condition: "JournalState"
  - id: "DecisionNode2"
    type: "decision"
    condition: "BundledAndMasteredProducts"
  - id: "DecisionNode3"
    type: "decision"
    condition: "FullRefreshNeeded"
  - id: "DecisionNode7"
    type: "decision"
    condition: "SyndicationErrors"
  - id: "DecisionNode8"
    type: "decision"
    condition: "SyndicationErrorMap:get(FailedProductUUID):ErrorCode"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "End5"
    type: "end"
    strict: false
  - id: "End6"
    type: "end"
    strict: false
  - id: "EndNode5"
    type: "end"
    strict: false
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      DefaultPageSize: 15
      Datasource: "default"
      ParameterName_01: "DomainID"
      QueryName: "product/GetAssignedProductsForCatalogs"
      ParameterName_02: "Categories"
    bindings:
      ParameterValue_01: "SourceDomainUUID"
      SearchResult: "Objects"
      ParameterValue_02: "SelectedCategoryUUIDIterator"
  - id: "GetDomainByUUID1"
    type: "pipelet"
    ref: "GetDomainByUUID"
    bindings:
      Domain: "TargetDomain"
      DomainUUID: "TargetDomainUUID"
  - id: "GetDomainByUUID2"
    type: "pipelet"
    ref: "GetDomainByUUID"
    bindings:
      Domain: "SourceDomain"
      DomainUUID: "SourceDomainUUID"
  - id: "GetOffersBySupplierProducts1"
    type: "pipelet"
    ref: "GetOffersBySupplierProducts"
    bindings:
      Products: "Objects"
      OfferRepositoryDomain: "TargetRepository:RepositoryDomain"
      OfferMap: "null"
      Offers: "null"
      ResidualProducts: "AllObjects"
  - id: "GetOffersBySupplierProducts2"
    type: "pipelet"
    ref: "GetOffersBySupplierProducts"
    bindings:
      Products: "AllObjects"
      OfferRepositoryDomain: "TargetRepository:RepositoryDomain"
      OfferMap: "null"
      Offers: "null"
      ResidualProducts: "AllObjects"
  - id: "GetPageable2"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "SelectedCategoryUUIDIterator"
  - id: "GetProductDataMappingRules1"
    type: "pipelet"
    ref: "GetProductDataMappingRules"
    bindings:
      DeclaringDomain: "TargetRepository:RepositoryDomain"
      ProvidingDomain: "SourceRepository:RepositoryDomain"
      TypeCode: "null"
  - id: "GetProductDataMappingRules2"
    type: "pipelet"
    ref: "GetProductDataMappingRules"
    config:
      DefaultTypeCode: 6
    bindings:
      DeclaringDomain: "TargetRepository:OwningDomain"
      ProvidingDomain: "SourceRepository:RepositoryDomain"
      TypeCode: "null"
      ProductDataMappingRules: "ContentMappingRules"
  - id: "GetRepositoryByRepositoryDomain1"
    type: "pipelet"
    ref: "GetRepositoryByRepositoryDomain"
    bindings:
      Repository: "SourceRepository"
      RepositoryDomain: "SourceDomain"
  - id: "GetRepositoryByRepositoryDomain2"
    type: "pipelet"
    ref: "GetRepositoryByRepositoryDomain"
    bindings:
      Repository: "TargetRepository"
      RepositoryDomain: "TargetDomain"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "LoopNode2"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "RefreshCache"
    config:
      PersistentClassName_0: "com.intershop.beehive.xcs.internal.product.ProductPO"
      PersistentClassName_1: "com.intershop.beehive.xcs.internal.catalog.ProductCategoryAssignmentPO"
      PersistentClassName_2: "com.intershop.beehive.xcs.internal.price.ProductListPricePO"
      PersistentClassName_3: "com.intershop.component.pricing.internal.definition.PriceDefinitionProductAssignmentPO"
      PersistentClassName_4: "com.intershop.component.pricing.internal.scale.PriceScaleTablePO"
      PersistentClassName_5: "com.intershop.component.pricing.internal.scale.PriceScaleEntryPO"
      PersistentClassName_6: "com.intershop.beehive.xcs.internal.product.ProductLinkPO"
      PersistentClassName_7: "com.intershop.beehive.xcs.internal.product.BundleAssignmentPO"
      PersistentClassName_8: "com.intershop.beehive.xcs.internal.productvariation.ProductVariationAssignmentPO"
      PersistentClassName_9: "com.intershop.beehive.xcs.internal.productvariation.VariableVariationAttributePO"
  - id: "Pipelet12"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Error"
      Message: "Bla"
      MessageKey: "bc_mvc.batch.Unknown"
    bindings:
      Object0: "SyndicationErrorMap:get(FailedProductUUID):SourceProduct:Name"
      Object1: "SyndicationErrorMap:get(FailedProductUUID):Exception"
      Object2: "SyndicationErrorMap:get(FailedProductUUID):ErrorCode"
  - id: "Pipelet13"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Error"
      MessageKey: "bc_mvc.batch.ProductIDToLarge"
    bindings:
      Object0: "SyndicationErrorMap:get(FailedProductUUID):SourceProduct:Name"
      Object1: "SyndicationErrorMap:get(FailedProductUUID):Exception"
      Object2: "SyndicationErrorMap:get(FailedProductUUID):ErrorCode"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "null"
      Iterator: "RuleProcessorsIterator"
      Object: "ProductJournalEntryMappingRule"
      Objects: "null"
      OutVector: "RuleProcessors"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      InVector: "null"
      Iterator: "RuleProcessorsIterator"
      Object: "null"
      Objects: "null"
      OutVector: "null"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "CreateMappingRuleProcessor"
    bindings:
      ClassName: "\"com.intershop.component.mvc.internal.mapping.SyndProductJournalEntryMappingRule\""
      MappingRule: "ProductJournalEntryMappingRule"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "JournalState"
      Type: "Integer"
    bindings:
      PreferenceDomain: "TargetRepository:Domain"
      PreferenceIntValue: "JournalState"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "RefreshCache"
    config:
      PersistentClassName_0: "com.intershop.beehive.xcs.internal.productvariation.ProductVariationPO"
      PersistentClassName_1: "com.intershop.beehive.xcs.internal.productvariation.ProductVariationValuePO"
  - id: "RefreshOfferRelation1"
    type: "pipelet"
    ref: "RefreshOfferRelation"
    bindings:
      DomainUUID: "null"
      ProductUUIDs: "null"
      Products: "SyndicatedProducts"
  - id: "RefreshVariationRelation1"
    type: "pipelet"
    ref: "RefreshVariationRelation"
    bindings:
      DomainUUID: "TargetDomainUUID"
      ProductUUIDs: "null"
      Products: "null"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "ResidualProducts"
  - id: "RemoveDictionaryValue2"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "Objects"
  - id: "RemoveDictionaryValue3"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "Products"
  - id: "RemoveDictionaryValue5"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "BundledAndMasteredProducts"
  - id: "ResolveBundlesAndMasters1"
    type: "pipelet"
    ref: "ResolveBundlesAndMasters"
    bindings:
      Products: "AllObjects"
      BundledProducts: "null"
      MasteredProducts: "null"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "FullRefreshNeeded"
      Value: true
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "TableNames"
      ValueType: "Dictionary Value"
      Value: "product;productcategoryassignment;productlistprice;productlink;bundleassignment;PriceScaleTable_AV;productcostprice;variablevariationatt_av;variablevariationattribute;productvariation"
  - id: "SyndicateProducts1"
    type: "pipelet"
    ref: "SyndicateProducts"
    bindings:
      SourceProducts: "AllObjects"
      SyndicationTarget: "TargetRepository:RepositoryDomain"

links:
  - from: "Start2"
    via: "next"
    to: "GetDomainByUUID1"
    into: "in"
  - from: "JoinNode13"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "End4"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode7"
    into: "in2"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "Decision10"
    via: "yes"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "GetPageable2"
    via: "next"
    to: "Decision10"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "GetPageable2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "Pipelet4"
    into: "in"
  - from: "GetRepositoryByRepositoryDomain1"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "JoinNode2"
    via: "next"
    to: "End5"
    into: "in"
  - from: "GetDomainByUUID1"
    via: "next"
    to: "GetRepositoryByRepositoryDomain2"
    into: "in"
  - from: "GetRepositoryByRepositoryDomain1"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "SyndicateProducts1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Start4"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "GetProductDataMappingRules1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "AddObjectToVector1"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "RefreshVariationRelation1"
    into: "in"
  - from: "GetDomainByUUID2"
    via: "error"
    to: "Join3"
    into: "in2"
  - from: "Decision2"
    via: "yes"
    to: "AddObjectToVector2"
    into: "in"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Pipelet5"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "Pipelet4"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "Join4"
    into: "in3"
  - from: "RemoveDictionaryValue3"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Join4"
    into: "in1"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "GetDomainByUUID1"
    via: "error"
    to: "Join2"
    into: "in1"
  - from: "Pipelet3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetDomainByUUID2"
    via: "next"
    to: "GetRepositoryByRepositoryDomain1"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "JoinNode7"
    into: "in1"
  - from: "GetRepositoryByRepositoryDomain2"
    via: "next"
    to: "GetDomainByUUID2"
    into: "in"
  - from: "GetPageable2"
    via: "error"
    to: "End3"
    into: "in"
  - from: "RemoveDictionaryValue5"
    via: "next"
    to: "End6"
    into: "in"
  - from: "SyndicateProducts1"
    via: "error"
    to: "CallNode3"
    into: "in"
  - from: "CombineIterators1"
    via: "next"
    to: "CreateSyndicationProcessor1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet3"
    into: "in"
  - from: "RefreshVariationRelation1"
    via: "next"
    to: "RefreshOfferRelation1"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "error"
    to: "End3"
    into: "in"
  - from: "Decision10"
    via: "no"
    to: "End3"
    into: "in"
  - from: "CombineIterators2"
    via: "next"
    to: "GetOffersBySupplierProducts2"
    into: "in"
  - from: "ResolveBundlesAndMasters1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "GetOffersBySupplierProducts2"
    via: "next"
    to: "RemoveDictionaryValue5"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "RemoveDictionaryValue2"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "GetProductDataMappingRules2"
    via: "next"
    to: "CombineIterators1"
    into: "in"
  - from: "RemoveDictionaryValue2"
    via: "next"
    to: "RemoveDictionaryValue3"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "GetOffersBySupplierProducts1"
    into: "in"
  - from: "GetOffersBySupplierProducts1"
    via: "next"
    to: "ResolveBundlesAndMasters1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode6"
    into: "in2"
  - from: "JoinNode6"
    via: "next"
    to: "CombineIterators2"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "Decision2"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "CreateSyndicationProcessor1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetProductDataMappingRules1"
    via: "next"
    to: "GetProductDataMappingRules2"
    into: "in"
  - from: "SyndicateProducts1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "End1"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "JoinNode13"
    into: "in1"
  - from: "LoopNode2"
    via: "do"
    to: "DecisionNode8"
    into: "in"
  - from: "JoinNode12"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "DecisionNode7"
    via: "yes"
    to: "JoinNode13"
    into: "in1"
  - from: "DecisionNode7"
    via: "no"
    to: "LoopNode2"
    into: "in"
  - from: "Pipelet12"
    via: "next"
    to: "JoinNode12"
    into: "in3"
  - from: "DecisionNode8"
    via: "yes"
    to: "Pipelet13"
    into: "in"
  - from: "Pipelet13"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "GetRepositoryByRepositoryDomain2"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "DecisionNode8"
    via: "no"
    to: "Pipelet12"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "DecisionNode7"
    into: "in"
  - from: "RefreshOfferRelation1"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode9"
    via: "next"
    to: "End2"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JoinNode8"
    into: "in3"
