flow: "BatchProcessLog"
kind: "process"

entries:
  - id: "Start18"
    name: "PrepareLogger"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "LogResult"
    mode: "private"
    strict: false
    inputs:
      - key: "Product"
        type: "com.intershop.beehive.orm.capi.common.ORMObject"
        required: false
      - key: "Result"
        type: "java.lang.String"
        required: false
  - id: "StartNode2"
    name: "CleanLogger"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "LogPageletResult"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "LogPageletEntryPointResult"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "GetLogStatistics"
    mode: "private"
    strict: true
    inputs:
      - key: "JobConfiguration"
        type: "com.intershop.beehive.core.capi.job.JobConfiguration"
        required: true

steps:
  - id: "CloseProcessLogAppender1"
    type: "pipelet"
    ref: "CloseProcessLogAppender"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "JobConfiguration:UUID"
      String1: "\"-BatchEntries.log\""
      Concatenated: "FileName"
  - id: "CreateLogEntry1"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Error"
      Message: "Error."
    bindings:
      Object0: "Product:Name"
  - id: "CreateProcessFileLogAppender1"
    type: "pipelet"
    ref: "CreateProcessFileLogAppender"
    config:
      Level: "Info"
      FileType: "XML"
    bindings:
      ProcessType: "\"Batch\""
      ProcessID: "JobConfiguration:UUID"
      LogFileDirectory: "\"batch/log\""
      LogFileName: "FileName"
      MaxLogFileSize: "\"(Integer)10000\""
      LogFileUnit: "JobConfiguration:Domain"
      LogInformationHolder: "JobConfiguration:CurrentProcess"
  - id: "Decision1"
    type: "decision"
    condition: "Result"
  - id: "Decision2"
    type: "decision"
    condition: "Result"
  - id: "Decision8"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode10"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode11"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode12"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode13"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode14"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode15"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode16"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode17"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode18"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode19"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode20"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode21"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode22"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode23"
    type: "decision"
    condition: "Component"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode5"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode6"
    type: "decision"
    condition: "ProcessLogAppender"
  - id: "DecisionNode7"
    type: "decision"
    condition: "JobConfiguration"
  - id: "DecisionNode8"
    type: "decision"
    condition: "Result"
  - id: "DecisionNode9"
    type: "decision"
    condition: "Result"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "EndNode5"
    type: "end"
    strict: false
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "LogStatistics"
        type: "com.intershop.beehive.core.capi.log.LogStatistics"
        guaranteed: false
  - id: "GetLogStatistics1"
    type: "pipelet"
    ref: "GetLogStatistics"
    bindings:
      StatisticsHolder: "JobConfiguration:CurrentProcess"
  - id: "GetPageletModelUtils1"
    type: "pipelet"
    ref: "GetPageletModelUtils"
  - id: "Join20"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode15"
    type: "join"
  - id: "JoinNode16"
    type: "join"
  - id: "JoinNode17"
    type: "join"
  - id: "JoinNode18"
    type: "join"
  - id: "JoinNode19"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode20"
    type: "join"
  - id: "JoinNode21"
    type: "join"
  - id: "JoinNode22"
    type: "join"
  - id: "JoinNode23"
    type: "join"
  - id: "JoinNode24"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Info"
      Message: "Unknown."
    bindings:
      Object0: "Product:Name"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Error"
      MessageKey: "bc_pmc.batch.PageComponentValidToIncorrect"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Error"
      MessageKey: "bc_pmc.batch.PageComponentValidFromIncorrect"
  - id: "Pipelet12"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Warn"
      MessageKey: "bc_pmc.batch.InvalidPageletToPageAssignment"
    bindings:
      Object0: "Pagelet:DisplayName"
      Object1: "PageletEntryPoint:DisplayName"
  - id: "Pipelet14"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Error"
      MessageKey: "bc_pmc.batch.PageletEntryPointLocked"
    bindings:
      Object0: "PageletEntryPoint:DisplayName"
  - id: "Pipelet15"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Warn"
      MessageKey: "bc_pmc.batch.PageletEntryPointShared"
    bindings:
      Object0: "PageletEntryPoint:DisplayName"
  - id: "Pipelet16"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Warn"
      MessageKey: "bc_pmc.batch.PageletEntryPointSystemPage"
    bindings:
      Object0: "PageletEntryPoint:DisplayName"
  - id: "Pipelet17"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      MessageKey: "bc_pmc.batch.PageletEntryPointIncorrectParent"
      LogLevel: "Warn"
    bindings:
      Object1: "PageletEntryPoint:DisplayName"
      Object0: "Parent:DisplayName"
  - id: "Pipelet18"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Error"
      Message: "Error."
    bindings:
      Object0: "PageletEntryPoint:DisplayName"
  - id: "Pipelet19"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Warn"
      MessageKey: "bc_pmc.batch.PageletEntryPointSystemInclude"
    bindings:
      Object0: "PageletEntryPoint:DisplayName"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Error"
      MessageKey: "bc_mvc.batch.ProductLocked"
    bindings:
      Object0: "Product:Name"
  - id: "Pipelet20"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Error"
      Message: "Unknown."
    bindings:
      Object0: "PageletEntryPoint:DisplayName"
  - id: "Pipelet21"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Warn"
      MessageKey: "bc_pmc.batch.PageletEntryPointViewContextFallback"
    bindings:
      Object0: "PageletEntryPoint:DisplayName"
  - id: "Pipelet22"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Error"
      MessageKey: "bc_pmc.batch.InvalidComponentToSlotAssignment"
    bindings:
      Object0: "Component:DisplayName"
      Object1: "PageletModelUtils:DisplayName(Slot:SlotDefinition,CurrentSession:Locale)"
      Object2: "ParentPagelet:DisplayName"
  - id: "Pipelet23"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Error"
      MessageKey: "bc_pmc.batch.InvalidComponentToSlotAssignment"
    bindings:
      Object0: "PageletAssignment:Pagelet:DisplayName"
      Object1: "PageletModelUtils:DisplayName(Slot:SlotDefinition,CurrentSession:Locale)"
      Object2: "ParentPagelet:DisplayName"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Info"
      MessageKey: "bc_mvc.batch.OfferExist"
    bindings:
      Object0: "Product:Name"
  - id: "Pipelet34"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Info"
      Message: "Skipped."
    bindings:
      Object0: "Product:Name"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Info"
      MessageKey: "bc_mvc.batch.ProductReferencesExist"
    bindings:
      Object0: "Product:Name"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Error"
      MessageKey: "bc_pmc.batch.PageComponentLocked"
    bindings:
      Object0: "Pagelet:DisplayName"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Info"
      MessageKey: "bc_pmc.batch.PageComponentShared"
    bindings:
      Object0: "Pagelet:DisplayName"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Info"
      Message: "Unknown."
    bindings:
      Object0: "Pagelet:DisplayName"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Error"
      MessageKey: "bc_pmc.batch.PageComponentPeriodIncorrect"
  - id: "Pipelet9"
    type: "pipelet"
    ref: "CreateLogEntry"
    config:
      LogLevel: "Error"
      Message: "Error."
    bindings:
      Object0: "Pagelet:DisplayName"

links:
  - from: "DecisionNode3"
    via: "yes"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode10"
    via: "yes"
    to: "DecisionNode11"
    into: "in"
  - from: "Pipelet21"
    via: "next"
    to: "JoinNode20"
    into: "in2"
  - from: "JoinNode19"
    via: "next"
    to: "JoinNode20"
    into: "in1"
  - from: "DecisionNode22"
    via: "yes"
    to: "JoinNode17"
    into: "in1"
  - from: "DecisionNode22"
    via: "no"
    to: "DecisionNode21"
    into: "in"
  - from: "GetLogStatistics1"
    via: "error"
    to: "JoinNode22"
    into: "in2"
  - from: "Pipelet20"
    via: "next"
    to: "JoinNode17"
    into: "in2"
  - from: "DecisionNode21"
    via: "yes"
    to: "DecisionNode16"
    into: "in"
  - from: "GetLogStatistics1"
    via: "next"
    to: "JoinNode22"
    into: "in1"
  - from: "StartNode5"
    via: "next"
    to: "GetLogStatistics1"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode6"
    into: "in2"
  - from: "Pipelet22"
    via: "next"
    to: "JoinNode23"
    into: "in1"
  - from: "JoinNode23"
    via: "next"
    to: "JoinNode24"
    into: "in2"
  - from: "DecisionNode23"
    via: "yes"
    to: "Pipelet22"
    into: "in"
  - from: "Pipelet23"
    via: "next"
    to: "JoinNode24"
    into: "in1"
  - from: "DecisionNode23"
    via: "no"
    to: "Pipelet23"
    into: "in"
  - from: "Pipelet34"
    via: "next"
    to: "Join20"
    into: "in2"
  - from: "Decision8"
    via: "yes"
    to: "DecisionNode9"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Pipelet7"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode9"
    via: "yes"
    to: "DecisionNode3"
    into: "in"
  - from: "CreateLogEntry1"
    via: "next"
    to: "Join20"
    into: "in3"
  - from: "DecisionNode9"
    via: "no"
    to: "Pipelet34"
    into: "in"
  - from: "Decision8"
    via: "no"
    to: "CreateLogEntry1"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "DecisionNode2"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Pipelet9"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "Decision8"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "Pipelet2"
    into: "in"
  - from: "DecisionNode10"
    via: "no"
    to: "Pipelet5"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "DecisionNode3"
    via: "no"
    to: "Pipelet3"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "Pipelet3"
    via: "next"
    to: "JoinNode4"
    into: "in2"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode4"
    via: "no"
    to: "Pipelet4"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "JoinNode7"
    into: "in2"
  - from: "JoinNode4"
    via: "next"
    to: "Join20"
    into: "in1"
  - from: "Join20"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Pipelet7"
    via: "next"
    to: "JoinNode8"
    into: "in2"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode8"
    via: "yes"
    to: "JoinNode8"
    into: "in1"
  - from: "CloseProcessLogAppender1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode6"
    via: "yes"
    to: "CloseProcessLogAppender1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "End1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "CreateProcessFileLogAppender1"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "EndNode5"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "Start18"
    via: "next"
    to: "DecisionNode7"
    into: "in"
  - from: "Pipelet9"
    via: "next"
    to: "JoinNode9"
    into: "in2"
  - from: "CreateProcessFileLogAppender1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "DecisionNode11"
    via: "no"
    to: "Pipelet6"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "GetPageletModelUtils1"
    via: "next"
    to: "DecisionNode23"
    into: "in"
  - from: "DecisionNode8"
    via: "no"
    to: "DecisionNode12"
    into: "in"
  - from: "DecisionNode12"
    via: "yes"
    to: "DecisionNode13"
    into: "in"
  - from: "DecisionNode13"
    via: "yes"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "DecisionNode10"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "Pipelet8"
    into: "in"
  - from: "DecisionNode13"
    via: "no"
    to: "Pipelet10"
    into: "in"
  - from: "DecisionNode12"
    via: "no"
    to: "Pipelet11"
    into: "in"
  - from: "Pipelet11"
    via: "next"
    to: "JoinNode11"
    into: "in3"
  - from: "Pipelet8"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "Pipelet4"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Pipelet10"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "JoinNode10"
    into: "in3"
  - from: "DecisionNode11"
    via: "yes"
    to: "DecisionNode14"
    into: "in"
  - from: "JoinNode22"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode23"
    into: "in1"
  - from: "JoinNode24"
    via: "next"
    to: "JoinNode12"
    into: "in2"
  - from: "DecisionNode14"
    via: "yes"
    to: "DecisionNode15"
    into: "in"
  - from: "DecisionNode15"
    via: "yes"
    to: "Decision1"
    into: "in"
  - from: "Pipelet12"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "DecisionNode14"
    via: "no"
    to: "Pipelet12"
    into: "in"
  - from: "JoinNode12"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "DecisionNode17"
    via: "no"
    to: "Pipelet16"
    into: "in"
  - from: "Pipelet16"
    via: "next"
    to: "JoinNode14"
    into: "in2"
  - from: "JoinNode20"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "DecisionNode18"
    via: "yes"
    to: "DecisionNode17"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "Pipelet20"
    into: "in"
  - from: "JoinNode21"
    via: "next"
    to: "JoinNode19"
    into: "in1"
  - from: "DecisionNode19"
    via: "no"
    to: "Pipelet17"
    into: "in"
  - from: "Pipelet17"
    via: "next"
    to: "JoinNode15"
    into: "in2"
  - from: "DecisionNode21"
    via: "no"
    to: "Pipelet21"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode14"
    via: "next"
    to: "JoinNode21"
    into: "in1"
  - from: "DecisionNode20"
    via: "no"
    to: "Pipelet19"
    into: "in"
  - from: "DecisionNode19"
    via: "yes"
    to: "Decision2"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Pipelet18"
    into: "in"
  - from: "DecisionNode16"
    via: "no"
    to: "Pipelet14"
    into: "in"
  - from: "DecisionNode16"
    via: "yes"
    to: "DecisionNode18"
    into: "in"
  - from: "DecisionNode18"
    via: "no"
    to: "Pipelet15"
    into: "in"
  - from: "JoinNode16"
    via: "next"
    to: "JoinNode15"
    into: "in1"
  - from: "Pipelet19"
    via: "next"
    to: "JoinNode18"
    into: "in2"
  - from: "Pipelet18"
    via: "next"
    to: "JoinNode16"
    into: "in2"
  - from: "StartNode3"
    via: "next"
    to: "DecisionNode8"
    into: "in"
  - from: "Pipelet14"
    via: "next"
    to: "JoinNode19"
    into: "in2"
  - from: "Pipelet15"
    via: "next"
    to: "JoinNode21"
    into: "in2"
  - from: "DecisionNode17"
    via: "yes"
    to: "DecisionNode20"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DecisionNode22"
    into: "in"
  - from: "DecisionNode20"
    via: "yes"
    to: "DecisionNode19"
    into: "in"
  - from: "JoinNode15"
    via: "next"
    to: "JoinNode18"
    into: "in1"
  - from: "JoinNode18"
    via: "next"
    to: "JoinNode14"
    into: "in1"
  - from: "JoinNode17"
    via: "next"
    to: "JoinNode16"
    into: "in1"
  - from: "DecisionNode15"
    via: "no"
    to: "GetPageletModelUtils1"
    into: "in"
