flow: "BatchProcessPagelets"
kind: "job"

entries:
  - id: "StartNode2"
    name: "UpdatePublishingPeriod"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Init"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "Post"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "DeletePagelets"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode10"
    type: "call"
    ref: "BatchProcessLog-LogPageletResult"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessContentWizard-ResolvePagelet"
  - id: "CallNode18"
    type: "call"
    ref: "ProcessPageletLock-Check"
    bindings:
      PreferenceDomain: "ContextDomain"
      LockingDomain: "ContextDomain"
      User: "JobCreator"
      Pagelet: "Pagelet"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessDate-ConvertPeriodToDate"
    bindings:
      ValidFromDate: "ValidFrom"
      ValidToDate: "ValidTo"
  - id: "CallNode3"
    type: "call"
    ref: "BatchProcessLog-LogPageletResult"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessContentWizard-ResolvePagelet"
  - id: "CallNode5"
    type: "call"
    ref: "BatchProcessLog-PrepareLogger"
  - id: "CallNode6"
    type: "call"
    ref: "BatchProcessLog-CleanLogger"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessPagelet-Delete"
  - id: "CallNode9"
    type: "call"
    ref: "ProcessPageletLock-CheckUnlocked"
    bindings:
      Pagelet: "Pagelet"
      CheckedUserID: "JobCreator:ID"
      LockingDomain: "ContextDomain"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Pagelet:DomainID"
  - id: "DecisionNode5"
    type: "decision"
    condition: "OnlineFlag"
  - id: "DecisionNode6"
    type: "decision"
    condition: "Pagelet:DomainID"
  - id: "DetermineUser1"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "JobCreatorUserID"
      User: "JobCreator"
  - id: "DetermineUser2"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "JobCreatorUserID"
      User: "JobCreator"
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode5"
    type: "end"
    strict: false
  - id: "EndNode6"
    type: "end"
    strict: false
  - id: "EndNode7"
    type: "end"
    strict: false
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "JobConfiguration:Domain"
      OutValue_1: "ContextDomain"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "JobConfiguration:Domain"
      OutValue_1: "ContextDomain"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Pagelet:Online"
      OutValue_1: "OnlineFlagBoolean"
  - id: "Loop1"
    type: "loop"
  - id: "Loop5"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Result"
      ValueType: "Dictionary Value"
      Value: "Locked"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "Result"
  - id: "Pipelet40"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "Result"
  - id: "Pipelet43"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Result"
      ValueType: "Dictionary Value"
      Value: "Locked"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Result"
      Value: "Shared"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Result"
      Value: "Shared"
      ValueType: "Dictionary Value"
  - id: "UpdatePagelet1"
    type: "pipelet"
    ref: "UpdatePagelet"
    bindings:
      Author: "JobCreator"
      Pagelet: "Pagelet"
      DisplayName: "null"
      Locale: "null"
      PageFlag: "Pagelet:Page"
      OnlineFlag: "OnlineFlagBoolean"
  - id: "VerifyBoolean1"
    type: "pipelet"
    ref: "VerifyBoolean"
    bindings:
      NoneLocalizedString: "OnlineFlag"
      BooleanValue: "OnlineFlagBoolean"

links:
  - from: "Pipelet40"
    via: "next"
    to: "Loop5"
    into: "loop"
  - from: "CallNode2"
    via: "next"
    to: "DetermineUser1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Pipelet43"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "Loop5"
    via: "do"
    to: "CallNode11"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "CallNode4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "CallNode18"
    into: "in"
  - from: "CallNode18"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Loop5"
    into: "in"
  - from: "UpdatePagelet1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "Pipelet40"
    into: "in"
  - from: "DetermineUser1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Loop5"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "DetermineUser2"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "CallNode9"
    via: "LOCKED"
    to: "Pipelet1"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DetermineUser2"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode9"
    into: "in3"
  - from: "CallNode8"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "KeyMapper4"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "VerifyBoolean1"
    via: "error"
    to: "JoinNode8"
    into: "in2"
  - from: "KeyMapper5"
    via: "next"
    to: "JoinNode7"
    into: "in3"
  - from: "DecisionNode5"
    via: "yes"
    to: "VerifyBoolean1"
    into: "in"
  - from: "VerifyBoolean1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "UpdatePagelet1"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "CallNode9"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "Pipelet2"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "CallNode10"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "CallNode18"
    via: "NO_LOCK"
    to: "Pipelet43"
    into: "in"
