flow: "CheckOutdatedBasketsJob"
kind: "job"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call10"
    type: "call"
    ref: "GetRepositories-GetLeafOrganizations"
  - id: "CheckTimeBasedBaskets1"
    type: "pipelet"
    ref: "CheckTimeBasedBaskets"
    config:
      BasketType: "REQUISITION"
    bindings:
      LeafOrganizationDomain: "LeafOrganization:OrganizationDomain"
      MaxNoOfBaskets: "JobConfiguration:String(\"MaxNumberOfBaskets\")"
  - id: "CreateStack1"
    type: "pipelet"
    ref: "CreateStack"
    bindings:
      Stack: "LeafOrganizationStack"
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "GetJobConfiguration1"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobDomain: "CurrentDomain"
      JobUUID: "JobConfigurationUUID"
  - id: "GetOrganizationByName1"
    type: "pipelet"
    ref: "GetOrganizationByName"
    config:
      DefaultName: "Operations"
    bindings:
      Organization: "Operations"
      OrganizationDomain: "OperationsDomain"
  - id: "GetOrganizations1"
    type: "pipelet"
    ref: "GetOrganizations"
    bindings:
      Owner: "OperationsDomain"
      Organizations: "Enterprises"
  - id: "JoinNode1"
    type: "join"
  - id: "LoopNode1"
    type: "loop"
  - id: "ManipulateStack3"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "POP"
    bindings:
      Stack: "LeafOrganizationStack"
      GetElement: "LeafOrganization"

links:
  - from: "GetOrganizations1"
    via: "next"
    to: "CreateStack1"
    into: "in"
  - from: "GetOrganizationByName1"
    via: "next"
    to: "GetJobConfiguration1"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "next"
    to: "GetOrganizations1"
    into: "in"
  - from: "ManipulateStack3"
    via: "error"
    to: "EndNode2"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "Call10"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "ManipulateStack3"
    via: "next"
    to: "CheckTimeBasedBaskets1"
    into: "in"
  - from: "CreateStack1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "ManipulateStack3"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "StartNode1"
    via: "next"
    to: "GetOrganizationByName1"
    into: "in"
  - from: "CheckTimeBasedBaskets1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
