flow: "ContentSynchronizationJob"
kind: "process"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call10"
    type: "call"
    ref: "GetRepositories-ChannelsReverse"
  - id: "CreateStack1"
    type: "pipelet"
    ref: "CreateStack"
    bindings:
      Stack: "ReverseChannelStack"
  - id: "CreateStack2"
    type: "pipelet"
    ref: "CreateStack"
    bindings:
      Stack: "OrganizationStack"
  - id: "CreateStack3"
    type: "pipelet"
    ref: "CreateStack"
    bindings:
      Stack: "ChannelStack"
  - id: "EndNode1"
    type: "end"
  - id: "EndNode2"
    type: "end"
  - id: "EndNode3"
    type: "end"
  - id: "ExecuteCartridgePipelines1"
    type: "pipelet"
    ref: "ExecuteCartridgePipelines"
    config:
      Asynchronous: false
      PipelinePropertyName: "ContentSynchronizationHook"
      ProcessReversely: false
  - id: "GetJobConfiguration1"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobDomainName: "\"SLDSystem\""
      JobName: "\"Synchronize Content\""
  - id: "GetOrganizationByName1"
    type: "pipelet"
    ref: "GetOrganizationByName"
    config:
      DefaultName: "Operations"
    bindings:
      Name: "null"
      Organization: "Operations"
      OrganizationDomain: "OperationsDomain"
  - id: "GetOrganizations1"
    type: "pipelet"
    ref: "GetOrganizations"
    bindings:
      Organizations: "Enterprises"
      Owner: "OperationsDomain"
  - id: "Join4"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "Loop3"
    type: "loop"
  - id: "ManipulateStack5"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "PUSH"
    bindings:
      AddElement: "Enterprise"
      Stack: "OrganizationStack"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "POP"
    bindings:
      GetElement: "Repository"
      Stack: "ChannelStack"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "POP"
    bindings:
      GetElement: "Repository"
      Stack: "ReverseChannelStack"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "PUSH"
    bindings:
      Stack: "ReverseChannelStack"
      AddElement: "Repository"

links:
  - from: "Pipelet2"
    via: "error"
    to: "EndNode1"
    into: "in"
  - from: "Pipelet3"
    via: "error"
    to: "EndNode3"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "Join4"
    into: "in1"
  - from: "CreateStack1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "GetOrganizationByName1"
    via: "next"
    to: "GetOrganizations1"
    into: "in"
  - from: "GetOrganizations1"
    via: "next"
    to: "CreateStack2"
    into: "in"
  - from: "Loop3"
    via: "do"
    to: "ManipulateStack5"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "ManipulateStack5"
    via: "next"
    to: "Loop3"
    into: "loop"
  - from: "Start1"
    via: "next"
    to: "GetJobConfiguration1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Join4"
    into: "in2"
  - from: "Loop3"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "ExecuteCartridgePipelines1"
    into: "in"
  - from: "CreateStack2"
    via: "next"
    to: "CreateStack3"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "next"
    to: "GetOrganizationByName1"
    into: "in"
  - from: "CreateStack3"
    via: "next"
    to: "Loop3"
    into: "in"
  - from: "GetOrganizationByName1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "ExecuteCartridgePipelines1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "ExecuteCartridgePipelines1"
    via: "error"
    to: "JoinNode3"
    into: "in3"
  - from: "GetJobConfiguration1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "CreateStack1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "JoinNode2"
    into: "in2"
