flow: "CreateSystemOrganizationExtension"
kind: "extension"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true
      - key: "AdminUser"
        type: "com.intershop.beehive.core.capi.user.User"
        required: true
      - key: "Site"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true

steps:
  - id: "AssignUserToUserGroup1"
    type: "pipelet"
    ref: "AssignUserToUserGroup"
    config:
      UserGroupID: "SLD_AR_10_ADMINISTRATOR"
    bindings:
      CurrentDomain: "Organization:Domain"
      CurrentUser: "AdminUser"
  - id: "AssignUserToUserGroup2"
    type: "pipelet"
    ref: "AssignUserToUserGroup"
    config:
      UserGroupID: "SLD_AR_10_SMCADMINISTRATOR"
    bindings:
      CurrentDomain: "Organization:Domain"
      CurrentUser: "AdminUser"
  - id: "Call1"
    type: "call"
    ref: "AccessRoles-Create"
    bindings:
      OrganizationTypeCode: "Organization:TypeCode"
  - id: "CreateApplicationDomainRelation3"
    type: "pipelet"
    ref: "CreateApplicationDomainRelation"
    bindings:
      RelationName: "\"OrganizationBORepository\""
      Domain: "Organization:Domain"
      Application: "Organization:Domain:Site:DefaultApplication"
  - id: "CreateDomainRelation1"
    type: "pipelet"
    ref: "CreateDomainRelation"
    config:
      DefaultRelationName: "SITE"
      DefaultRoleName: "Role A"
    bindings:
      Source: "Site"
      Target: "Organization:Domain"
  - id: "Decision1"
    type: "decision"
    condition: "Organization:TypeCode"
  - id: "End1"
    type: "end"
    strict: true
  - id: "End2"
    type: "end"
    strict: true
  - id: "End3"
    type: "end"
    strict: true
  - id: "Join2"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "TextNode1"
    type: "text"

links:
  - from: "AssignUserToUserGroup1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "AssignUserToUserGroup1"
    via: "next"
    to: "AssignUserToUserGroup2"
    into: "in"
  - from: "AssignUserToUserGroup2"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "AssignUserToUserGroup2"
    via: "next"
    to: "CreateDomainRelation1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "AssignUserToUserGroup1"
    into: "in"
  - from: "CreateApplicationDomainRelation3"
    via: "next"
    to: "End2"
    into: "in"
  - from: "CreateDomainRelation1"
    via: "error"
    to: "Join2"
    into: "in1"
  - from: "CreateDomainRelation1"
    via: "next"
    to: "CreateApplicationDomainRelation3"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "End1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Call1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "End3"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "Decision1"
    into: "in"
