flow: "CreateSalesOrganizationWarrantyExtension"
kind: "extension"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true

steps:
  - id: "CallNode2"
    type: "call"
    ref: "ProcessServiceTypeCatalog-CreateCategory"
    bindings:
      ParentCategory: "Catalog:Root"
      Id: "\"ES_Warranty_Dependent\""
      DisplayName: "\"Dependent Warranty\""
      Description: "\"Dependent Warranty\""
  - id: "Decision1"
    type: "decision"
    condition: "Organization:TypeCode"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorCode"
        type: "java.lang.String"
        guaranteed: false
  - id: "GetCatalog1"
    type: "pipelet"
    ref: "GetCatalog"
    config:
      DefaultCatalogID: "ServiceTypes"
    bindings:
      OrganizationDomain: "Organization:Domain"
  - id: "JoinNode1"
    type: "join"
  - id: "LogMessage1"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Level: "Error"
    bindings:
      MessageText: "\"could not get catalog {} for organization {} within domain {}\""
      MessageParam0: "\"ServiceTypes\""
      MessageParam1: "Organization:ID"
      MessageParam2: "Organization:Domain:UUID"
  - id: "SetDictionaryValue7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Value: "CatalogNotFound"
      Name: "ErrorCode"
  - id: "TextNode1"
    type: "text"
  - id: "TextNode2"
    type: "text"
  - id: "TextNode3"
    type: "text"
  - id: "UpdateCustomAttributes2"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "ExcludeFromSearchIndex"
      Attribute_1_Type: "Boolean"
      Attribute_2_Name: "OrderableAsDependentOnly"
      Attribute_2_Type: "Boolean"
      Attribute_3_Name: "ExcludeFromShipping"
      Attribute_3_Type: "Boolean"
    bindings:
      ExtensibleObject: "Category"
      Attribute_1_Value: "\"(Boolean)true\""
      Attribute_2_Value: "\"(Boolean)true\""
      Attribute_3_Value: "\"(Boolean)true\""

links:
  - from: "UpdateCustomAttributes2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetCatalog1"
    via: "error"
    to: "SetDictionaryValue7"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "SetDictionaryValue7"
    via: "next"
    to: "LogMessage1"
    into: "in"
  - from: "LogMessage1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "CallNode2"
    via: "next"
    to: "UpdateCustomAttributes2"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "GetCatalog1"
    into: "in"
  - from: "GetCatalog1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Decision1"
    into: "in"
