flow: "CreateSiteHook"
kind: "process"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CreateDomainRelation1"
    type: "pipelet"
    ref: "CreateDomainRelation"
    config:
      DefaultRelationName: "TAX_JURISDICTION"
      DefaultRoleName: "Role B"
    bindings:
      Source: "SiteDomain"
      Target: "TAX_Domain"
  - id: "CreateDomainRelation2"
    type: "pipelet"
    ref: "CreateDomainRelation"
    config:
      DefaultRelationName: "TAX_CLASS"
      DefaultRoleName: "Role B"
    bindings:
      Source: "SiteDomain"
      Target: "TAX_Domain"
  - id: "Decision1"
    type: "decision"
    condition: "ApplicationType:ApplicationTypeCode"
  - id: "Decision2"
    type: "decision"
    condition: "ApplicationType:ApplicationTypeCode"
  - id: "Decision3"
    type: "decision"
    condition: "ApplicationType:ApplicationTypeCode"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "End5"
    type: "end"
    strict: false
  - id: "End6"
    type: "end"
    strict: false
  - id: "GetDomain1"
    type: "pipelet"
    ref: "GetDomain"
    bindings:
      StagingDomain: "TAX_Domain"
      StagingDomainName: "\"Operations\""
  - id: "Join4"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "SetDomainBusinessModel"
    config:
      BusinessModel: "sell-side"
    bindings:
      Domain: "SiteDomain"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_Channel"
      Value: "CouldNotCreateDomainRelation TAX_CLASS"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_Channel"
      Value: "CouldNotCreateDomainRelation TAX_JURISDICTION"
  - id: "SetDomainPreference1"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "TaxRateProvider"
      DefaultPreferenceValue: "BasicTaxRateProviderImpl"
      Type: "String"
    bindings:
      PreferenceDomain: "SiteDomain"
  - id: "SetDomainPreference4"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "SitePrefixPipelineName"
      DefaultPreferenceValue: "Prefix"
      Type: "String"
    bindings:
      PreferenceDomain: "SiteDomain"

links:
  - from: "Decision3"
    via: "yes"
    to: "Decision1"
    into: "in"
  - from: "SetDomainPreference1"
    via: "error"
    to: "Join4"
    into: "in2"
  - from: "CreateDomainRelation1"
    via: "next"
    to: "CreateDomainRelation2"
    into: "in"
  - from: "GetDomain1"
    via: "next"
    to: "CreateDomainRelation1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "GetDomain1"
    into: "in"
  - from: "CreateDomainRelation1"
    via: "error"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "CreateDomainRelation2"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "CreateDomainRelation2"
    via: "next"
    to: "SetDomainPreference1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Decision1"
    via: "no"
    to: "Pipelet2"
    into: "in"
  - from: "SetDomainPreference4"
    via: "error"
    to: "Join8"
    into: "in2"
  - from: "SetDomainPreference4"
    via: "next"
    to: "End3"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "End5"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "End6"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "Decision3"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "End4"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "Pipelet2"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "SetDomainPreference1"
    via: "next"
    to: "SetDomainPreference4"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "Join8"
    into: "in1"
