flow: "CreateSalesChannelProfanityCheckExtension"
kind: "extension"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      - key: "Repository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true

steps:
  - id: "AssignProfanityCheckConfiguration1"
    type: "pipelet"
    ref: "AssignProfanityCheckConfiguration"
    bindings:
      Domain: "ChannelDomain"
      LocaleID: "ProfanityCheckConfigurationAssignment:LocaleID"
      ProfanityCheckConfiguration: "ProfanityCheckConfigurationAssignment:ProfanityCheckConfiguration"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ProfanityCheckConfigurationAssignment:ProfanityCheckConfigurationID"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Repository:TypeCode"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "GetProfanityCheckConfigurationAssignmentsByDomain1"
    type: "pipelet"
    ref: "GetProfanityCheckConfigurationAssignmentsByDomain"
    bindings:
      Domain: "Channel:OwningDomain"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Repository"
      OutValue_1: "Channel"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Channel:Domain"
      OutValue_1: "ChannelDomain"
  - id: "LoopNode2"
    type: "loop"

links:
  - from: "LoopNode2"
    via: "do"
    to: "DecisionNode1"
    into: "in"
  - from: "AssignProfanityCheckConfiguration1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "GetProfanityCheckConfigurationAssignmentsByDomain1"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "GetProfanityCheckConfigurationAssignmentsByDomain1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "DecisionNode2"
    via: "yes"
    to: "KeyMapper1"
    into: "in"
  - from: "AssignProfanityCheckConfiguration1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "LoopNode2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "AssignProfanityCheckConfiguration1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "KeyMapper1"
    via: "next"
    to: "GetProfanityCheckConfigurationAssignmentsByDomain1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode3"
    into: "in2"
