flow: "CreatePartnerOrganizationExtension"
kind: "extension"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true
      - key: "AdminUser"
        type: "com.intershop.beehive.core.capi.user.User"
        required: false
      - key: "Owner"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false

steps:
  - id: "AssignUserGroupToUserGroup1"
    type: "pipelet"
    ref: "AssignUserGroupToUserGroup"
    bindings:
      ChildUserGroup: "OrganizationUserGroup"
      UserGroup: "ChannelUserGroup"
  - id: "AssignUserToUserGroup1"
    type: "pipelet"
    ref: "AssignUserToUserGroup"
    config:
      UserGroupID: "SLD_AR_30_ADMINISTRATOR"
    bindings:
      CurrentDomain: "Organization:Domain"
      CurrentUser: "AdminUser"
  - id: "Call1"
    type: "call"
    ref: "AccessRoles-Create"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessRepository-Create"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessRepository-Create"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessInitializeImages-CreateInstances"
    bindings:
      Domain: "Organization:Domain"
      ImageViewBORepository: "ApplicationBO:Extension(\"Image\"):ImageViewBORepository(Organization)"
      ImageTypeBORepository: "ApplicationBO:Extension(\"Image\"):ImageTypeBORepository(Organization)"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessInitializeImages-CreateDefinitionDomainPreference"
    bindings:
      Domain: "Organization:Domain"
  - id: "CallNode6"
    type: "call"
    ref: "CreateSalesOrganizationExtension-CreateAttributeGroup"
    bindings:
      ID: "\"BACKOFFICE_SEARCH_ATTRIBUTES\""
      FixedFlag: "\"(Boolean)true\""
      Domain: "Organization:Domain"
      LocaleId: "null"
      Description: "null"
      DisplayName: "null"
      TypeCode: "null"
  - id: "CopyCustomAttributes1"
    type: "pipelet"
    ref: "CopyCustomAttributes"
    bindings:
      CustomAttributes: "ClassificationCatalog:CustomAttributes"
      ExtensibleObject: "Proxy"
  - id: "CreateAccessRoleID1"
    type: "pipelet"
    ref: "CreateAccessRoleID"
    config:
      DefaultPrefix: "SLD_AR"
      DefaultSeparator: "_"
      DefaultSuffix: "CATALOG_VIEWER"
    bindings:
      AccessRoleID: "ChannelUserGroupID"
      TypeCode: "ChannelRepository:TypeCode"
  - id: "CreateApplicationDomainRelation1"
    type: "pipelet"
    ref: "CreateApplicationDomainRelation"
    bindings:
      RelationName: "\"RecycleBinRepository\""
      Domain: "Repository:RepositoryDomain"
      Application: "ApplicationBO:Extension(\"PersistentObjectBOExtension\"):PersistentObject"
  - id: "CreateApplicationDomainRelation2"
    type: "pipelet"
    ref: "CreateApplicationDomainRelation"
    bindings:
      RelationName: "\"DefaultRepository\""
      Domain: "Repository:RepositoryDomain"
      Application: "ApplicationBO:Extension(\"PersistentObjectBOExtension\"):PersistentObject"
  - id: "CreateDomainRelation1"
    type: "pipelet"
    ref: "CreateDomainRelation"
    config:
      DefaultRelationName: "MANAGED_SERVICE"
      DefaultRoleName: "Role B"
    bindings:
      Source: "Organization:Domain"
      Target: "Organization:OwningDomain"
  - id: "CreateDomainRelation2"
    type: "pipelet"
    ref: "CreateDomainRelation"
    config:
      DefaultRelationName: "TAX_JURISDICTION"
      DefaultRoleName: "Role B"
    bindings:
      Source: "Organization:Domain"
      Target: "TAX_Domain"
  - id: "CreateDomainRelation3"
    type: "pipelet"
    ref: "CreateDomainRelation"
    config:
      DefaultRelationName: "TAX_CLASS"
      DefaultRoleName: "Role B"
    bindings:
      Source: "Organization:Domain"
      Target: "TAX_Domain"
  - id: "CreateDomainRelation4"
    type: "pipelet"
    ref: "CreateDomainRelation"
    config:
      DefaultRelationName: "PAYMENT_METHOD"
      DefaultRoleName: "Role B"
    bindings:
      Source: "Organization:Domain"
      Target: "TAX_Domain"
  - id: "CreateDomainRelation5"
    type: "pipelet"
    ref: "CreateDomainRelation"
    config:
      DefaultRelationName: "SHIPPING_METHOD"
      DefaultRoleName: "Role B"
    bindings:
      Source: "Organization:Domain"
      Target: "Repository:Domain"
  - id: "CreateProxyCatalog1"
    type: "pipelet"
    ref: "CreateProxyCatalog"
    bindings:
      CatalogID: "\"ServiceTypes\""
      CatalogType: "Catalog:TypeCode"
      Domain: "Organization:Domain"
      Proxy: "SharedCatalogProxy"
  - id: "CreateProxyCatalog2"
    type: "pipelet"
    ref: "CreateProxyCatalog"
    config:
      DefaultCatalogID: "eclass"
      DefaultCatalogType: 2
    bindings:
      Catalog: "ClassificationCatalog"
      Domain: "Organization:Domain"
      CatalogID: "ClassificationCatalog:Id"
      CatalogType: "ClassificationCatalog:TypeCode"
  - id: "Decision1"
    type: "decision"
    condition: "Organization:TypeCode"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Catalog:ClassificationSystem"
  - id: "DetermineUnit1"
    type: "pipelet"
    ref: "DetermineUnit"
  - id: "End1"
    type: "end"
    strict: true
  - id: "End3"
    type: "end"
    strict: true
  - id: "End4"
    type: "end"
    strict: true
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "GetApplicationBO1"
    type: "pipelet"
    ref: "GetApplicationBO"
  - id: "GetCatalog1"
    type: "pipelet"
    ref: "GetCatalog"
    config:
      DefaultCatalogID: "ServiceTypes"
    bindings:
      OrganizationDomain: "ChannelRepository:OwningDomain"
  - id: "GetCatalogs1"
    type: "pipelet"
    ref: "GetCatalogs"
    config:
      CatalogType: "Classification Catalog"
      ProxyFilter: "ON - Exclude Proxy Catalogs"
    bindings:
      OrganizationDomain: "Unit"
      Catalogs: "ClassificationCatalogs"
  - id: "GetDomain2"
    type: "pipelet"
    ref: "GetDomain"
    bindings:
      StagingDomain: "TAX_Domain"
      StagingDomainName: "TAX_DomainName"
  - id: "GetRepositoryByRepositoryDomain1"
    type: "pipelet"
    ref: "GetRepositoryByRepositoryDomain"
    bindings:
      Repository: "ChannelRepository"
      RepositoryDomain: "Organization:OwningDomain"
  - id: "GetUserGroupByID1"
    type: "pipelet"
    ref: "GetUserGroupByID"
    config:
      DefaultUserGroupID: "SLD_AR_32_CATALOG_VIEWER"
    bindings:
      Domain: "Owner"
      UserGroup: "ChannelUserGroup"
  - id: "GetUserGroupByID2"
    type: "pipelet"
    ref: "GetUserGroupByID"
    config:
      DefaultUserGroupID: "Everyone"
    bindings:
      Domain: "Organization:Domain"
      UserGroup: "OrganizationUserGroup"
  - id: "Join1"
    type: "join"
  - id: "Join16"
    type: "join"
  - id: "Join17"
    type: "join"
  - id: "Join18"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode26"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "LoopNode2"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "RepositoryID"
      Value: "RecycleBin"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "RepositoryTypeCode"
      Value: 22
  - id: "Pipelet3"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString2: "-RecycleBin"
    bindings:
      Concatenated: "DisplayName"
      String1: "Organization:Domain:DomainName"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "RepositoryTypeCode"
      Value: 21
  - id: "Pipelet5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "RepositoryID"
      Value: "MasterRepository"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "CopyCustomAttributes"
    bindings:
      ExtensibleObject: "SharedCatalogProxy"
      CustomAttributes: "Catalog:AttributeValues"
  - id: "SetCatalogClassificationSystem1"
    type: "pipelet"
    ref: "SetCatalogClassificationSystem"
    bindings:
      Catalog: "SharedCatalogProxy"
      ClassificationSystem: "Catalog:ClassificationSystem"
  - id: "SetCatalogClassificationSystem2"
    type: "pipelet"
    ref: "SetCatalogClassificationSystem"
    bindings:
      Catalog: "Proxy"
      ClassificationSystem: "ClassificationCatalog:ClassificationSystem"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_Channel"
      Value: "CouldNotCreateDomainRelation MANAGED_SERVICE"
  - id: "SetDictionaryValue14"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_Channel"
      Value: "CouldNotCreateDomainRelation SHIPPING_METHOD"
  - id: "SetDictionaryValue15"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_Channel"
      Value: "CouldNotCreateDomainRelation PAYMENT_METHOD"
  - id: "SetDictionaryValue16"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_Channel"
      Value: "CouldNotCreateDomainPreference 'ShippingCosts'"
  - id: "SetDictionaryValue5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "FileName"
      Value: "b2b_partner_site_default_branding.zip"
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_Channel"
      Value: "CouldNotCreateDomainRelation TAX_CLASS"
  - id: "SetDictionaryValue7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "TAX_DomainName"
      Value: "Operations"
  - id: "SetDictionaryValue8"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_Channel"
      Value: "CouldNotCreateDomainRelation TAX_JURISDICTION"
  - id: "SetDictionaryValue9"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "UnitName"
      Value: "Operations"
  - id: "SetDomainPreference1"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "ShippingCosts"
      DefaultPreferenceValue: "Provided"
      Type: "String"
    bindings:
      PreferenceDomain: "Organization:Domain"
  - id: "SetDomainPreference7"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "InactivityPeriod"
      Type: "Integer"
      DefaultPreferenceValue: 90
    bindings:
      PreferenceDomain: "Organization:OrganizationDomain"
      PreferenceIntValue: "null"
      PreferenceDoubleValue: "null"
      PreferenceKey: "null"
      PreferenceStringValue: "null"
      PreferenceValue: "null"
  - id: "TextNode3"
    type: "text"

links:
  - from: "Pipelet1"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Join18"
    via: "next"
    to: "Join17"
    into: "in1"
  - from: "SetDomainPreference1"
    via: "error"
    to: "SetDictionaryValue16"
    into: "in"
  - from: "AssignUserToUserGroup1"
    via: "error"
    to: "End3"
    into: "in"
  - from: "CreateDomainRelation3"
    via: "error"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "GetRepositoryByRepositoryDomain1"
    into: "in"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "Start1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "SetCatalogClassificationSystem2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "SetDictionaryValue7"
    via: "next"
    to: "GetDomain2"
    into: "in"
  - from: "JoinNode26"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "SetDictionaryValue5"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "SetDictionaryValue15"
    via: "next"
    to: "Join17"
    into: "in2"
  - from: "Pipelet3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CreateDomainRelation2"
    via: "error"
    to: "SetDictionaryValue8"
    into: "in"
  - from: "CreateAccessRoleID1"
    via: "error"
    to: "Join7"
    into: "in1"
  - from: "LoopNode2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "GetRepositoryByRepositoryDomain1"
    via: "next"
    to: "GetCatalog1"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "SetCatalogClassificationSystem1"
    into: "in"
  - from: "GetApplicationBO1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CreateApplicationDomainRelation2"
    via: "next"
    to: "CreateAccessRoleID1"
    into: "in"
  - from: "CreateDomainRelation5"
    via: "next"
    to: "CreateDomainRelation4"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "Pipelet5"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "DetermineUnit1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "SetDomainPreference7"
    into: "in"
  - from: "SetDomainPreference1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetUserGroupByID2"
    via: "next"
    to: "GetUserGroupByID1"
    into: "in"
  - from: "DetermineUnit1"
    via: "next"
    to: "GetCatalogs1"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "CreateProxyCatalog2"
    via: "error"
    to: "JoinNode2"
    into: "in3"
  - from: "CreateProxyCatalog1"
    via: "error"
    to: "JoinNode26"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "CreateApplicationDomainRelation2"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "End4"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Join16"
    into: "in1"
  - from: "CreateApplicationDomainRelation1"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "End1"
    into: "in"
  - from: "CreateDomainRelation1"
    via: "next"
    to: "SetDomainPreference1"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "GetCatalogs1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "SetDictionaryValue14"
    via: "next"
    to: "Join18"
    into: "in2"
  - from: "Join2"
    via: "next"
    to: "Join18"
    into: "in1"
  - from: "CreateDomainRelation2"
    via: "next"
    to: "CreateDomainRelation3"
    into: "in"
  - from: "SetCatalogClassificationSystem1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Join17"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode26"
    into: "in2"
  - from: "CreateAccessRoleID1"
    via: "next"
    to: "GetUserGroupByID2"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "GetUserGroupByID1"
    via: "error"
    to: "Join8"
    into: "in2"
  - from: "SetDomainPreference7"
    via: "next"
    to: "SetDictionaryValue9"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "Pipelet6"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "SetDictionaryValue9"
    via: "next"
    to: "DetermineUnit1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "GetApplicationBO1"
    into: "in"
  - from: "AssignUserGroupToUserGroup1"
    via: "next"
    to: "SetDictionaryValue7"
    into: "in"
  - from: "CreateDomainRelation3"
    via: "next"
    to: "CreateDomainRelation5"
    into: "in"
  - from: "CreateProxyCatalog1"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "CreateProxyCatalog2"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "SetDictionaryValue5"
    into: "in"
  - from: "CreateDomainRelation1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "AssignUserToUserGroup1"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "GetDomain2"
    via: "next"
    to: "CreateDomainRelation2"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "CallNode4"
    into: "in"
  - from: "SetDictionaryValue8"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "CreateDomainRelation4"
    via: "error"
    to: "SetDictionaryValue15"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CreateProxyCatalog2"
    via: "next"
    to: "CopyCustomAttributes1"
    into: "in"
  - from: "GetCatalog1"
    via: "next"
    to: "CreateProxyCatalog1"
    into: "in"
  - from: "GetUserGroupByID2"
    via: "error"
    to: "Join7"
    into: "in2"
  - from: "CreateDomainRelation5"
    via: "error"
    to: "SetDictionaryValue14"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CopyCustomAttributes1"
    via: "next"
    to: "SetCatalogClassificationSystem2"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "AssignUserToUserGroup1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CreateApplicationDomainRelation1"
    into: "in"
  - from: "Join16"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "SetDictionaryValue16"
    via: "next"
    to: "Join16"
    into: "in2"
  - from: "GetUserGroupByID1"
    via: "next"
    to: "AssignUserGroupToUserGroup1"
    into: "in"
  - from: "CreateDomainRelation4"
    via: "next"
    to: "CreateDomainRelation1"
    into: "in"
