flow: "CreateSalesOrganizationCatalogExtension"
kind: "extension"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessServiceTypeCatalog-Start"
    bindings:
      OrganizationDomain: "Organization:Domain"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessServiceTypeCatalog-CreateCategory"
    bindings:
      ParentCategory: "Catalog:Root"
      Id: "\"ES_Proxy\""
      DisplayName: "\"Proxy Product\""
      Description: "\"Proxy Product\""
  - id: "CallNode3"
    type: "call"
    ref: "ProcessServiceTypeCatalog-CreateCategory"
    bindings:
      ParentCategory: "Catalog:Root"
      Id: "\"CustomizationSKU\""
      DisplayName: "\"Customization SKU\""
      Description: "\"Customization SKU\""
      Category: "CustomizationSkuCategory"
  - id: "Decision1"
    type: "decision"
    condition: "Organization:TypeCode"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "JoinNode1"
    type: "join"
  - id: "TextNode1"
    type: "text"
  - id: "UpdateCustomAttributes1"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "IsNotOrderable"
      Attribute_1_Type: "Boolean"
      Attribute_2_Name: "ExcludeFromSearchIndex"
      Attribute_2_Type: "Boolean"
    bindings:
      ExtensibleObject: "CustomizationSkuCategory"
      Attribute_1_Value: "\"(Boolean)true\""
      Attribute_2_Value: "\"(Boolean)true\""

links:
  - from: "Decision1"
    via: "yes"
    to: "CallNode1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "UpdateCustomAttributes1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "StartNode1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "UpdateCustomAttributes1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
