flow: "CreateSalesOrganizationExtension"
kind: "extension"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true
      - key: "AdminUser"
        type: "com.intershop.beehive.core.capi.user.User"
        required: false
      - key: "Site"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
  - id: "StartNode1"
    name: "CreateAttributeGroup"
    mode: "private"
    strict: true
    inputs:
      - key: "FixedFlag"
        type: "java.lang.Boolean"
        required: false
      - key: "ID"
        type: "java.lang.String"
        required: true
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "TypeCode"
        type: "java.lang.Integer"
        required: false
      - key: "DisplayName"
        type: "java.lang.String"
        required: false
      - key: "Description"
        type: "java.lang.String"
        required: false
      - key: "LocaleId"
        type: "java.lang.String"
        required: false
  - id: "StartNode2"
    name: "UpdateAttributeGroup"
    mode: "private"
    strict: true
    inputs:
      - key: "AttributeGroup"
        type: "com.intershop.component.foundation.capi.attributegroup.AttributeGroup"
        required: true
      - key: "FixedFlag"
        type: "java.lang.Boolean"
        required: false
      - key: "Description"
        type: "java.lang.String"
        required: false
      - key: "LocaleId"
        type: "java.lang.String"
        required: false
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "TypeCode"
        type: "java.lang.Integer"
        required: false
      - key: "DisplayName"
        type: "java.lang.String"
        required: false

steps:
  - id: "AssignUserToUserGroup1"
    type: "pipelet"
    ref: "AssignUserToUserGroup"
    config:
      UserGroupID: "SLD_AR_20_ADMINISTRATOR"
    bindings:
      CurrentDomain: "Organization:Domain"
      CurrentUser: "AdminUser"
  - id: "Call1"
    type: "call"
    ref: "AccessRoles-Create"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessRepository-Create"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessRepository-Create"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessInitializeImages-CreateInstances"
    bindings:
      Domain: "Organization:Domain"
      ImageTypeBORepository: "ApplicationBO:Repository(\"ImageTypeBORepository\", Organization:Domain:UUID)"
      ImageViewBORepository: "ApplicationBO:Repository(\"ImageViewBORepository\", Organization:Domain:UUID)"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessInitializeImages-CreateDefinitionDomainPreference"
    bindings:
      Domain: "Organization:Domain"
  - id: "CallNode5"
    type: "call"
    ref: "ManufacturerAliasesCleanUp-Create"
    bindings:
      Domain: "Organization:Domain"
  - id: "CallNode6"
    type: "call"
    ref: "CreateSalesOrganizationExtension-CreateAttributeGroup"
    bindings:
      ID: "\"BACKOFFICE_SEARCH_ATTRIBUTES\""
      FixedFlag: "\"(Boolean)true\""
      Domain: "Organization:Domain"
      LocaleId: "null"
      TypeCode: "null"
      Description: "null"
      DisplayName: "null"
  - id: "CopyCustomAttributes1"
    type: "pipelet"
    ref: "CopyCustomAttributes"
    bindings:
      CustomAttributes: "ClassificationCatalog:CustomAttributes"
      ExtensibleObject: "Proxy"
  - id: "CreateApplicationDomainRelation1"
    type: "pipelet"
    ref: "CreateApplicationDomainRelation"
    bindings:
      RelationName: "\"RecycleBinRepository\""
      Domain: "Repository:RepositoryDomain"
      Application: "ApplicationBO:Extension(\"PersistentObjectBOExtension\"):PersistentObject"
  - id: "CreateApplicationDomainRelation2"
    type: "pipelet"
    ref: "CreateApplicationDomainRelation"
    bindings:
      RelationName: "\"DefaultRepository\""
      Domain: "Repository:RepositoryDomain"
      Application: "ApplicationBO:Extension(\"PersistentObjectBOExtension\"):PersistentObject"
  - id: "CreateDomainRelation1"
    type: "pipelet"
    ref: "CreateDomainRelation"
    config:
      DefaultRelationName: "MANAGED_SERVICE"
      DefaultRoleName: "Role B"
    bindings:
      Source: "Organization:Domain"
      Target: "TAX_Domain"
  - id: "CreateDomainRelation2"
    type: "pipelet"
    ref: "CreateDomainRelation"
    config:
      DefaultRelationName: "TAX_CLASS"
      DefaultRoleName: "Role B"
    bindings:
      Source: "Organization:Domain"
      Target: "TAX_Domain"
  - id: "CreateDomainRelation3"
    type: "pipelet"
    ref: "CreateDomainRelation"
    config:
      DefaultRelationName: "TAX_JURISDICTION"
      DefaultRoleName: "Role B"
    bindings:
      Source: "Organization:Domain"
      Target: "TAX_Domain"
  - id: "CreateDomainRelation4"
    type: "pipelet"
    ref: "CreateDomainRelation"
    config:
      DefaultRelationName: "SHIPPING_METHOD"
      DefaultRoleName: "Role B"
    bindings:
      Source: "Organization:Domain"
      Target: "TAX_Domain"
  - id: "CreateDomainRelation5"
    type: "pipelet"
    ref: "CreateDomainRelation"
    config:
      DefaultRelationName: "PAYMENT_METHOD"
      DefaultRoleName: "Role B"
    bindings:
      Source: "Organization:Domain"
      Target: "TAX_Domain"
  - id: "CreateProxyCatalog2"
    type: "pipelet"
    ref: "CreateProxyCatalog"
    config:
      DefaultCatalogID: "eclass"
      DefaultCatalogType: 2
    bindings:
      Catalog: "ClassificationCatalog"
      Domain: "Organization:Domain"
      CatalogID: "ClassificationCatalog:Id"
      CatalogType: "ClassificationCatalog:TypeCode"
  - id: "Decision1"
    type: "decision"
    condition: "Organization:TypeCode"
  - id: "DecisionNode1"
    type: "decision"
    condition: "LocaleId"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ClassificationCatalog:ClassificationSystem:Name"
  - id: "DetermineUnit1"
    type: "pipelet"
    ref: "DetermineUnit"
  - id: "End1"
    type: "end"
    strict: true
  - id: "End3"
    type: "end"
    strict: true
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "AttributeGroup"
        type: "com.intershop.component.foundation.capi.attributegroup.AttributeGroup"
        guaranteed: false
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "AttributeGroup"
        type: "com.intershop.component.foundation.capi.attributegroup.AttributeGroup"
        guaranteed: false
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "EndNode5"
    type: "end"
    strict: true
  - id: "GetApplicationBO1"
    type: "pipelet"
    ref: "GetApplicationBO"
  - id: "GetCatalogs1"
    type: "pipelet"
    ref: "GetCatalogs"
    config:
      CatalogType: "Classification Catalog"
      ProxyFilter: "ON - Exclude Proxy Catalogs"
    bindings:
      OrganizationDomain: "Unit"
      Catalogs: "ClassificationCatalogs"
  - id: "GetDomain2"
    type: "pipelet"
    ref: "GetDomain"
    bindings:
      StagingDomain: "TAX_Domain"
      StagingDomainName: "TAX_DomainName"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
  - id: "Join10"
    type: "join"
  - id: "Join11"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode17"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "LoopNode2"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "UpdateAttributeGroup"
    bindings:
      ID: "null"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "UpdateAttributeGroup"
    bindings:
      ID: "null"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "CreateAttributeGroup"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "RepositoryTypeCode"
      Value: 22
  - id: "Pipelet4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "RepositoryID"
      Value: "RecycleBin"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString2: "-RecycleBin"
    bindings:
      Concatenated: "DisplayName"
      String1: "Organization:Domain:DomainName"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "CreateDomainRelation"
    config:
      DefaultRelationName: "SITE"
      DefaultRoleName: "Role A"
    bindings:
      Source: "Site"
      Target: "Organization:Domain"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "RepositoryID"
      Value: "MasterRepository"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "RepositoryTypeCode"
      Value: 21
  - id: "Pipelet9"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString2: "-MasterRepository"
    bindings:
      Concatenated: "DisplayName"
      String1: "Organization:Domain:DomainName"
  - id: "SetCatalogClassificationSystem2"
    type: "pipelet"
    ref: "SetCatalogClassificationSystem"
    bindings:
      Catalog: "Proxy"
      ClassificationSystem: "ClassificationCatalog:ClassificationSystem"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_Channel"
      Value: "CouldNotCreateDomainRelation MANAGED_SERVICE"
  - id: "SetDictionaryValue12"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "UnitName"
      Value: "Operations"
  - id: "SetDictionaryValue13"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_Channel"
      Value: "CouldNotCreateDomainRelation SHIPPING_METHOD"
  - id: "SetDictionaryValue14"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_Channel"
      Value: "CouldNotCreateDomainRelation PAYMENT_METHOD"
  - id: "SetDictionaryValue15"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_Channel"
      Value: "CouldNotCreateDomainPreference 'ShippingCosts'"
  - id: "SetDictionaryValue5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_Channel"
      Value: "CouldNotCreateDomainRelation TAX_JURISDICTION"
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "TAX_DomainName"
      Value: "Operations"
  - id: "SetDictionaryValue7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_Channel"
      Value: "CouldNotCreateDomainRelation TAX_CLASS"
  - id: "SetDomainPreference1"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "ShippingCosts"
      DefaultPreferenceValue: "Provided"
      Type: "String"
    bindings:
      PreferenceDomain: "Organization:Domain"
  - id: "SetDomainPreference7"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "InactivityPeriod"
      Type: "Integer"
      DefaultPreferenceValue: 90
    bindings:
      PreferenceDomain: "Organization:OrganizationDomain"
      PreferenceIntValue: "null"
      PreferenceDoubleValue: "null"
      PreferenceKey: "null"
      PreferenceStringValue: "null"
      PreferenceValue: "null"
  - id: "TextNode1"
    type: "text"
  - id: "TextNode2"
    type: "text"

links:
  - from: "Pipelet9"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "AssignUserToUserGroup1"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "End1"
    into: "in"
  - from: "SetCatalogClassificationSystem2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Pipelet10"
    via: "error"
    to: "EndNode5"
    into: "in"
  - from: "CreateDomainRelation1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CreateDomainRelation2"
    via: "next"
    to: "CreateDomainRelation4"
    into: "in"
  - from: "CreateDomainRelation4"
    via: "next"
    to: "CreateDomainRelation5"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "CreateDomainRelation3"
    via: "next"
    to: "CreateDomainRelation2"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "SetDictionaryValue5"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Decision1"
    via: "yes"
    to: "CallNode4"
    into: "in"
  - from: "GetApplicationBO1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "SetDomainPreference7"
    via: "next"
    to: "SetDictionaryValue12"
    into: "in"
  - from: "DetermineUnit1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "Join11"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "Pipelet4"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "CreateDomainRelation2"
    via: "error"
    to: "SetDictionaryValue7"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "GetApplicationBO1"
    into: "in"
  - from: "AssignUserToUserGroup1"
    via: "error"
    to: "End3"
    into: "in"
  - from: "SetDictionaryValue12"
    via: "next"
    to: "DetermineUnit1"
    into: "in"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "GetDomain2"
    into: "in"
  - from: "CreateApplicationDomainRelation1"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetLocale1"
    into: "in"
  - from: "SetDictionaryValue13"
    via: "next"
    to: "Join9"
    into: "in2"
  - from: "DetermineUnit1"
    via: "next"
    to: "GetCatalogs1"
    into: "in"
  - from: "Pipelet7"
    via: "next"
    to: "Pipelet9"
    into: "in"
  - from: "CreateDomainRelation5"
    via: "next"
    to: "CreateDomainRelation1"
    into: "in"
  - from: "Join10"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GetLocale1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "CreateProxyCatalog2"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "AssignUserToUserGroup1"
    into: "in"
  - from: "Join9"
    via: "next"
    to: "Join10"
    into: "in1"
  - from: "Pipelet8"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "JoinNode17"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "SetDictionaryValue14"
    via: "next"
    to: "Join10"
    into: "in2"
  - from: "CreateDomainRelation5"
    via: "error"
    to: "SetDictionaryValue14"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "SetDomainPreference7"
    into: "in"
  - from: "CreateApplicationDomainRelation2"
    via: "next"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Join11"
    into: "in1"
  - from: "SetDomainPreference1"
    via: "error"
    to: "SetDictionaryValue15"
    into: "in"
  - from: "CreateDomainRelation1"
    via: "next"
    to: "SetDomainPreference1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "CreateProxyCatalog2"
    via: "next"
    to: "CopyCustomAttributes1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "CreateDomainRelation4"
    via: "error"
    to: "SetDictionaryValue13"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode17"
    into: "in2"
  - from: "CreateDomainRelation3"
    via: "error"
    to: "SetDictionaryValue5"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "GetCatalogs1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "SetDictionaryValue15"
    via: "next"
    to: "Join11"
    into: "in2"
  - from: "SetDomainPreference1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CreateProxyCatalog2"
    via: "error"
    to: "JoinNode17"
    into: "in1"
  - from: "LoopNode2"
    via: "do"
    to: "DecisionNode2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CreateApplicationDomainRelation1"
    into: "in"
  - from: "SetDictionaryValue7"
    via: "next"
    to: "Join3"
    into: "in2"
  - from: "CallNode2"
    via: "next"
    to: "CreateApplicationDomainRelation2"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "CopyCustomAttributes1"
    via: "next"
    to: "SetCatalogClassificationSystem2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode6"
    into: "in2"
  - from: "Pipelet1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "Pipelet2"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "Pipelet2"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet10"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "GetLocale2"
    via: "next"
    to: "Pipelet10"
    into: "in"
  - from: "GetDomain2"
    via: "next"
    to: "CreateDomainRelation3"
    into: "in"
