flow: "CreatePartnerChannelExtension"
kind: "extension"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      - key: "Repository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true

steps:
  - id: "CreateApplication0"
    type: "pipelet"
    ref: "CreateApplication"
    bindings:
      Site: "Repository:Domain:Site"
      OwningDomain: "Repository:Domain"
      UrlIdentifier: "\"partnersystem\""
  - id: "CreateApplicationDomainRelation0"
    type: "pipelet"
    ref: "CreateApplicationDomainRelation"
    bindings:
      Domain: "Repository:Domain"
      RelationName: "\"OrganizationBORepository\""
  - id: "Decision1"
    type: "decision"
    condition: "Repository:TypeCode"
  - id: "End3"
    type: "end"
    strict: true
  - id: "GetApp0"
    type: "pipelet"
    ref: "GetApp"
    bindings:
      AppID: "\"intershop.EnterpriseBackoffice\""
  - id: "JoinNode0"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"

links:
  - from: "CreateApplication0"
    via: "error"
    to: "JoinNode0"
    into: "in1"
  - from: "CreateApplication0"
    via: "next"
    to: "CreateApplicationDomainRelation0"
    into: "in"
  - from: "CreateApplicationDomainRelation0"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Decision1"
    via: "no"
    to: "JoinNode1"
    into: "in1"
  - from: "Decision1"
    via: "yes"
    to: "GetApp0"
    into: "in"
  - from: "GetApp0"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetApp0"
    via: "next"
    to: "CreateApplication0"
    into: "in"
  - from: "JoinNode0"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "End3"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Decision1"
    into: "in"
