flow: "CreateSalesOrganizationGiftCardExtension"
kind: "extension"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessServiceTypeCatalog-CreateCategory"
    bindings:
      ParentCategory: "GiftCardCategory"
      Id: "\"ES_PhysicalGiftCard\""
      DisplayName: "\"Gift Cards\""
      Description: "\"Gift Cards\""
      Category: "ES_PhysicalGiftCard"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessServiceTypeCatalog-CreateCategory"
    bindings:
      ParentCategory: "GiftCardCategory"
      Id: "\"ES_DigitalGiftCard\""
      DisplayName: "\"Gift Certificates\""
      Description: "\"Gift Certificates\""
      Category: "ES_DigitalGiftCard"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessServiceTypeCatalog-CreateCategory"
    bindings:
      ParentCategory: "Catalog:Root"
      Id: "\"ES_GiftCard\""
      DisplayName: "\"Gift Cards & Certificates\""
      Description: "\"Gift Cards & Certificates\""
      Category: "GiftCardCategory"
  - id: "CreateProductType1"
    type: "pipelet"
    ref: "CreateProductType"
    bindings:
      ID: "ES_DigitalGiftCard:Name"
      OwningDomain: "ES_DigitalGiftCard:Domain"
  - id: "CreateProductType3"
    type: "pipelet"
    ref: "CreateProductType"
    bindings:
      ID: "ES_PhysicalGiftCard:Name"
      OwningDomain: "ES_PhysicalGiftCard:Domain"
  - id: "CreateProductTypeAttribute1"
    type: "pipelet"
    ref: "CreateProductTypeAttribute"
    bindings:
      ID: "\"GC_ORDER_REQUIRED_GiftCardService\""
      LocalizedFlag: "\"(Boolean)0\""
      ValueType: "\"(Integer)3\""
  - id: "CreateProductTypeAttribute3"
    type: "pipelet"
    ref: "CreateProductTypeAttribute"
    bindings:
      ID: "\"GC_ORDER_REQUIRED_GiftCardService\""
      LocalizedFlag: "\"(Boolean)0\""
      ValueType: "\"(Integer)3\""
  - id: "Decision1"
    type: "decision"
    condition: "Organization:TypeCode"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorCode"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "GetCatalog1"
    type: "pipelet"
    ref: "GetCatalog"
    config:
      DefaultCatalogID: "ServiceTypes"
    bindings:
      OrganizationDomain: "Organization:Domain"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "LogMessage1"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Level: "Error"
    bindings:
      MessageText: "\"{} could not get catalog {} for organization {} within domain {}\""
      MessageParam3: "Organization:Domain:UUID"
      MessageParam2: "Organization:ID"
      MessageParam1: "\"ServiceTypes\""
      MessageParam0: "CurrentPipelineName"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: 1
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: 1
  - id: "SetDictionaryValue5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: 1
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: 1
  - id: "SetDictionaryValue7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Value: "CatalogNotFound"
      Name: "ErrorCode"
  - id: "TextNode1"
    type: "text"
  - id: "UpdateProductTypeAttribute2"
    type: "pipelet"
    ref: "UpdateProductTypeAttribute"
    config:
      AlwaysRemoveDefaultValue: true
    bindings:
      DisplayName: "\"GC_ORDER_REQUIRED_GiftCardService\""
      ID: "\"GC_ORDER_REQUIRED_GiftCardService\""
      DefaultValue: "\"Standard GiftCard\""
  - id: "UpdateProductTypeAttribute3"
    type: "pipelet"
    ref: "UpdateProductTypeAttribute"
    config:
      AlwaysRemoveDefaultValue: true
    bindings:
      DisplayName: "\"GC_ORDER_REQUIRED_GiftCardService\""
      ID: "\"GC_ORDER_REQUIRED_GiftCardService\""
      DefaultValue: "\"Standard GiftCard\""

links:
  - from: "UpdateProductTypeAttribute2"
    via: "error"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "UpdateProductTypeAttribute2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "UpdateProductTypeAttribute3"
    via: "error"
    to: "SetDictionaryValue5"
    into: "in"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "Join3"
    into: "in2"
  - from: "CallNode1"
    via: "next"
    to: "CreateProductType3"
    into: "in"
  - from: "CreateProductTypeAttribute1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "Join3"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CreateProductTypeAttribute3"
    via: "error"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "CreateProductType3"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "CreateProductType1"
    into: "in"
  - from: "CreateProductType1"
    via: "next"
    to: "CreateProductTypeAttribute1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Join4"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "UpdateProductTypeAttribute3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CreateProductTypeAttribute1"
    via: "next"
    to: "UpdateProductTypeAttribute2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "Join4"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CreateProductTypeAttribute3"
    via: "next"
    to: "UpdateProductTypeAttribute3"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "GetCatalog1"
    via: "error"
    to: "SetDictionaryValue7"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "GetLocale1"
    into: "in"
  - from: "LogMessage1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "SetDictionaryValue7"
    via: "next"
    to: "LogMessage1"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "GetCatalog1"
    into: "in"
  - from: "CreateProductType1"
    via: "error"
    to: "Join4"
    into: "in1"
  - from: "SetDictionaryValue5"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "StartNode1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "GetCatalog1"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "CreateProductType3"
    via: "next"
    to: "CreateProductTypeAttribute3"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "JoinNode5"
    into: "in1"
