flow: "CSRFGuardToken"
kind: "include"

entries:
  - id: "StartNode1"
    name: "JavaScript"
    mode: "include"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "FormField"
    mode: "include"
    strict: false
    inputs:
      []

steps:
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"

links:
  - from: "StartNode1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "InteractionNode2"
    into: "in"
