flow: "CSRFAlertRecovery"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "error1"
    type: "interaction"

links:
  - from: "StartNode1"
    via: "next"
    to: "error1"
    into: "in"
