flow: "CustomAddressAttributes"
kind: "process"

entries:
  - id: "StartNode1"
    name: "Add"
    mode: "private"
    strict: true
    inputs:
      - key: "Address"
        type: "com.intershop.beehive.core.capi.profile.Address"
        required: true
      - key: "AddressForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        required: true
  - id: "StartNode3"
    name: "Update"
    mode: "private"
    strict: true
    inputs:
      - key: "Address"
        type: "com.intershop.beehive.core.capi.profile.Address"
        required: true
      - key: "AddressForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        required: true

steps:
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "Address"
        type: "com.intershop.beehive.core.capi.profile.Address"
        guaranteed: true
  - id: "JoinNode2"
    type: "join"

links:
  - from: "StartNode3"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
