flow: "Default"
kind: "view"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Jump1"
    type: "jump"
    ref: "ViewApplication-DisplayLogin"

links:
  - from: "Start1"
    via: "next"
    to: "Jump1"
    into: "in"
