flow: "DeleteDomainReferencesCore"
kind: "process"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "RemoveOrganizationProfile"
    mode: "private"
    strict: true
    inputs:
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
    ref: "DeleteDomainReferencesCore-RemoveOrganizationProfile"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Domain:DomainName"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Domain:ProfileID"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "ExecuteStoredProcedure0"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deleteServicesByDomain"
  - id: "ExecuteStoredProcedure2"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deleteUserDataByDomain"
  - id: "ExecuteStoredProcedure3"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deletePreferencesByDomain"
  - id: "ExecuteStoredProcedure5"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deleteRegSettingsByDomain"
  - id: "ExecuteStoredProcedure6"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deleteEventsByDomain"
  - id: "ExecuteStoredProcedure7"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deleteExchangeRatesByDomain"
  - id: "ExecuteStoredProcedure9"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deleteJobsByDomain"
  - id: "GetProfile1"
    type: "pipelet"
    ref: "GetProfile"
    bindings:
      ProfileID: "Domain:ProfileID"
  - id: "JoinNode0"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode15"
    type: "join"
  - id: "JoinNode16"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deleteProcessesByDomain"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deleteReplTasksByDomain"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deleteWorkflowsByDomain"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deleteApplicationByDomain"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deleteLocalizationByDomain"
  - id: "RemoveDomain1"
    type: "pipelet"
    ref: "RemoveDomain"
  - id: "RemoveDomainFileStructure1"
    type: "pipelet"
    ref: "RemoveDomainFileStructure"
  - id: "RemoveProfile1"
    type: "pipelet"
    ref: "RemoveProfile"

links:
  - from: "CallNode1"
    via: "error"
    to: "JoinNode14"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode15"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "RemoveProfile1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "GetProfile1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "JoinNode13"
    into: "in1"
  - from: "ExecuteStoredProcedure0"
    via: "error"
    to: "JoinNode0"
    into: "in1"
  - from: "ExecuteStoredProcedure0"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "ExecuteStoredProcedure2"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "ExecuteStoredProcedure2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "ExecuteStoredProcedure3"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "ExecuteStoredProcedure3"
    via: "next"
    to: "ExecuteStoredProcedure2"
    into: "in"
  - from: "ExecuteStoredProcedure5"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "ExecuteStoredProcedure5"
    via: "next"
    to: "ExecuteStoredProcedure3"
    into: "in"
  - from: "ExecuteStoredProcedure6"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "ExecuteStoredProcedure6"
    via: "next"
    to: "ExecuteStoredProcedure5"
    into: "in"
  - from: "ExecuteStoredProcedure7"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "ExecuteStoredProcedure7"
    via: "next"
    to: "ExecuteStoredProcedure6"
    into: "in"
  - from: "ExecuteStoredProcedure9"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "ExecuteStoredProcedure9"
    via: "next"
    to: "ExecuteStoredProcedure7"
    into: "in"
  - from: "GetProfile1"
    via: "error"
    to: "JoinNode13"
    into: "in1"
  - from: "GetProfile1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode0"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode12"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "JoinNode13"
    via: "next"
    to: "JoinNode15"
    into: "in1"
  - from: "JoinNode14"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode15"
    via: "next"
    to: "JoinNode16"
    into: "in1"
  - from: "JoinNode16"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode14"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "Pipelet1"
    via: "error"
    to: "JoinNode8"
    into: "in1"
  - from: "Pipelet1"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet2"
    via: "error"
    to: "JoinNode9"
    into: "in1"
  - from: "Pipelet2"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet3"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "Pipelet3"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "Pipelet4"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "Pipelet4"
    via: "next"
    to: "RemoveDomainFileStructure1"
    into: "in"
  - from: "Pipelet5"
    via: "error"
    to: "JoinNode12"
    into: "in1"
  - from: "Pipelet5"
    via: "next"
    to: "ExecuteStoredProcedure0"
    into: "in"
  - from: "RemoveDomain1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "RemoveDomain1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "RemoveDomainFileStructure1"
    via: "error"
    to: "JoinNode11"
    into: "in1"
  - from: "RemoveDomainFileStructure1"
    via: "next"
    to: "RemoveDomain1"
    into: "in"
  - from: "RemoveProfile1"
    via: "error"
    to: "EndNode2"
    into: "in"
  - from: "RemoveProfile1"
    via: "next"
    to: "JoinNode16"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "ExecuteStoredProcedure9"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
