flow: "DetermineMetaTags"
kind: "process"

entries:
  - id: "StartNode1"
    name: "ProductMetaTags"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductUUID"
        type: "java.lang.String"
        required: false
  - id: "StartNode2"
    name: "CategoryMetaTags"
    mode: "private"
    strict: false
    inputs:
      - key: "CategoryBO"
        type: "com.intershop.component.catalog.capi.CatalogCategoryBO"
        required: true

steps:
  - id: "CallNode19"
    type: "call"
    ref: "ProcessSearchEngineAttributes-CreateCategorytMetaTags"
  - id: "CallNode28"
    type: "call"
    ref: "ProcessSearchEngineAttributes-CreateProductMetaTags"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ConTitle"
        type: "java.lang.String"
        guaranteed: false
      - key: "ConKeywords"
        type: "java.lang.String"
        guaranteed: false
      - key: "ConDescription"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "GetApplicationBO1"
    type: "pipelet"
    ref: "GetApplicationBO"
  - id: "GetApplicationBO2"
    type: "pipelet"
    ref: "GetApplicationBO"
  - id: "GetApplicationByUUID1"
    type: "pipelet"
    ref: "GetApplicationByUUID"
    bindings:
      ApplicationUUID: "ApplicationBO:ID"
      Application: "TargetApplication"
  - id: "GetApplicationByUUID2"
    type: "pipelet"
    ref: "GetApplicationByUUID"
    bindings:
      ApplicationUUID: "ApplicationBO:ID"
      Application: "TargetApplication"
  - id: "GetProductBOByID1"
    type: "pipelet"
    ref: "GetProductBOByID"
    bindings:
      ID: "ProductUUID"
      Domain: "ProductDomain"
  - id: "GetValuesFromRequest1"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "Application"
    bindings:
      Key: "\"CurrentOrganization\""
      Namespace: "null"
  - id: "GetValuesFromRequest2"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "ApplicationRepository"
    bindings:
      Namespace: "null"
      Key: "null"
  - id: "GetValuesFromRequest3"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "ApplicationRepository"
    bindings:
      Namespace: "null"
      Key: "null"
  - id: "GetValuesFromRequest4"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "Application"
    bindings:
      Key: "\"CurrentOrganization\""
      Namespace: "null"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "KeyMapper0"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CategoryBO:Extension(\"PersistentObjectBOExtension\"):PersistentObject"
      OutValue_1: "ExtensibleObject"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentSession:Locale"
      InValue_2: "CurrentDomain:DomainName"
      InValue_3: "Repository:Domain"
      InValue_4: "ExtensibleObject"
      OutValue_1: "Locale"
      OutValue_2: "DomainName"
      OutValue_3: "ProductDomain"
      OutValue_4: "Category"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_2: "CurrentDomain:DomainName"
      InValue_1: "CurrentSession:Locale"
      InValue_3: "Repository:Domain"
      InValue_4: "ApplicationBO:Extension(\"Product\"):getProductBORepository(Repository:Domain:UUID)"
      OutValue_2: "DomainName"
      OutValue_1: "Locale"
      OutValue_3: "ProductDomain"
      OutValue_4: "ProductBORepository"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ProductBO:ProductPO"
      InValue_2: "ProductBO:DefaultCatalogCategoryID"
      InValue_3: "ProductBO:ProductPO"
      InValue_4: "ApplicationBO:Extension(\"Product\"):getProductBORepository(CurrentOrganization)"
      OutValue_1: "ExtensibleObject"
      OutValue_2: "CatalogCategoryID"
      OutValue_3: "Product"
      OutValue_4: "ProductBORepository"

links:
  - from: "CallNode19"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "CallNode28"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "GetApplicationBO1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "GetApplicationBO2"
    via: "next"
    to: "KeyMapper0"
    into: "in"
  - from: "GetApplicationByUUID1"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "GetApplicationByUUID1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GetApplicationByUUID2"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "GetApplicationByUUID2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "GetProductBOByID1"
    via: "error"
    to: "EndNode3"
    into: "in"
  - from: "GetProductBOByID1"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "GetValuesFromRequest1"
    via: "error"
    to: "GetValuesFromRequest3"
    into: "in"
  - from: "GetValuesFromRequest1"
    via: "next"
    to: "GetValuesFromRequest3"
    into: "in"
  - from: "GetValuesFromRequest2"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetValuesFromRequest2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetValuesFromRequest3"
    via: "error"
    to: "GetApplicationBO1"
    into: "in"
  - from: "GetValuesFromRequest3"
    via: "next"
    to: "GetApplicationBO1"
    into: "in"
  - from: "GetValuesFromRequest4"
    via: "error"
    to: "GetValuesFromRequest2"
    into: "in"
  - from: "GetValuesFromRequest4"
    via: "next"
    to: "GetValuesFromRequest2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "GetApplicationBO2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "CallNode19"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "CallNode28"
    into: "in"
  - from: "KeyMapper0"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "GetApplicationByUUID1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "GetProductBOByID1"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "GetApplicationByUUID2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetValuesFromRequest1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetValuesFromRequest4"
    into: "in"
