flow: "DetermineProduct_32"
kind: "process"

entries:
  - id: "StartNode1"
    name: "ChannelProduct"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "RecycleBinProduct"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "MasterRepositoryProduct"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "ParentChannelRepositoryProduct"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "CallNode2"
    type: "call"
    ref: "DetermineRepositories-ParentChannel"
  - id: "CallNode3"
    type: "call"
    ref: "DetermineRepositories-ChannelRecycleBin"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Product:DomainID"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Product:DomainID"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Product:DomainID"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Product:DomainID"
  - id: "DecisionNode5"
    type: "decision"
    condition: "ParentChannelRepository"
  - id: "End4"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "EndNode5"
    type: "end"
    strict: false
  - id: "EndNode6"
    type: "end"
    strict: false
  - id: "EndNode7"
    type: "end"
    strict: false
  - id: "GetProductByUUID2"
    type: "pipelet"
    ref: "GetProductByUUID"
    bindings:
      ProductUUID: "ProductID"
      ProductDomain: "CurrentProductRepository:RepositoryDomain"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "InteractionNode3"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "product/ProductNotAvailable_32"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorProductWrongDomain"
      Value: true
      ValueType: "Dictionary Value"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductNotAvailable_32"
  - id: "Pipelet12"
    type: "pipelet"
    ref: "GetProductByUUID"
    bindings:
      ProductUUID: "ProductID"
      ProductDomain: "RecycleBin:RepositoryDomain"
  - id: "Pipelet13"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorProductNotAvailable"
      Value: true
      ValueType: "Dictionary Value"
  - id: "Pipelet14"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorProductWrongDomain"
      Value: true
      ValueType: "Dictionary Value"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorProductNotAvailable"
      Value: true
      ValueType: "Dictionary Value"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "GetProductByUUID"
    bindings:
      ProductUUID: "ProductID"
      ProductDomain: "Repository:RepositoryDomain"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorProductWrongDomain"
      Value: true
      ValueType: "Dictionary Value"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorProductWrongDomain"
      Value: true
      ValueType: "Dictionary Value"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorProductNotAvailable"
      Value: true
      ValueType: "Dictionary Value"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "product/ProductNotAvailable_32"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "GetProductByUUID"
    bindings:
      ProductUUID: "ProductID"
      ProductDomain: "ParentChannelRepository:RepositoryDomain"
  - id: "Pipelet9"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorProductNotAvailable"
      Value: true
      ValueType: "Dictionary Value"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductNotAvailable_32"

links:
  - from: "StartNode1"
    via: "next"
    to: "GetProductByUUID2"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "Pipelet3"
    via: "error"
    to: "Pipelet2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "EndNode2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "Pipelet5"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet9"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "Pipelet10"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "End4"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "Pipelet8"
    via: "error"
    to: "Pipelet9"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "Pipelet7"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "EndNode4"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Pipelet13"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "Pipelet14"
    via: "next"
    to: "Pipelet11"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Pipelet12"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "Pipelet12"
    via: "error"
    to: "Pipelet13"
    into: "in"
  - from: "Pipelet12"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "Pipelet14"
    into: "in"
  - from: "Pipelet11"
    via: "next"
    to: "InteractionNode3"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "EndNode6"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "Pipelet10"
    into: "in"
  - from: "GetProductByUUID2"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "EndNode1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "Pipelet4"
    into: "in"
  - from: "GetProductByUUID2"
    via: "error"
    to: "Pipelet6"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
