flow: "DetermineRepositories"
kind: "process"

entries:
  - id: "Start1"
    name: "All"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "SelectedChannel"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "ParentChannel"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Master"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "ForSynchronization"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "ByUUID"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "RecycleBin"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "ChannelRecycleBin"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "ChannelByID"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Suppliers"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Iterator: "TypeCodes"
      Object: "\"2\""
  - id: "AddObjectToVector11"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Iterator: "Repositories"
      Object: "RecycleBin"
      InVector: "null"
      Objects: "null"
      OutVector: "null"
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Iterator: "Repositories"
      Object: "ParentChannelRepository"
      InVector: "null"
      Objects: "null"
      OutVector: "null"
  - id: "AddObjectToVector3"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Iterator: "Repositories"
      Object: "Repository"
      InVector: "null"
      Objects: "null"
      OutVector: "null"
  - id: "AddObjectToVector4"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Iterator: "null"
      Object: "ParentChannelRepository"
      InVector: "null"
      Objects: "null"
  - id: "AddObjectToVector5"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Iterator: "Repositories"
      Object: "Repository"
      InVector: "null"
      Objects: "null"
      OutVector: "null"
  - id: "AddObjectToVector6"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "OutVector"
      Iterator: "Repositories"
      Object: "Repository"
      Objects: "null"
      OutVector: "null"
  - id: "AddObjectToVector7"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Iterator: "Repositories"
      Object: "Repository"
      InVector: "null"
      Objects: "null"
      OutVector: "null"
  - id: "AddObjectToVector8"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      Iterator: "SupplierRepositories"
      Object: "ProductRepository"
      OutVector: "InVector"
      Objects: "null"
  - id: "AddObjectToVector9"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Iterator: "Repositories"
      Object: "RecycleBin"
      InVector: "null"
      Objects: "null"
      OutVector: "null"
  - id: "CreateIteratorFromConfigValues1"
    type: "pipelet"
    ref: "CreateIteratorFromConfigValues"
    config:
      Values: ";"
    bindings:
      ValuesIterator: "Repositories"
      ValuesString: "null"
  - id: "CreateIteratorFromConfigValues3"
    type: "pipelet"
    ref: "CreateIteratorFromConfigValues"
    config:
      Values: ";"
    bindings:
      ValuesIterator: "SupplierRepositories"
      ValuesString: "null"
  - id: "Decision1"
    type: "decision"
    condition: "Organization"
  - id: "Decision2"
    type: "decision"
    condition: "Organization:TypeCode"
  - id: "Decision3"
    type: "decision"
    condition: "Organization:TypeCode"
  - id: "Decision5"
    type: "decision"
    condition: "Organization"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End11"
    type: "end"
    strict: false
  - id: "End14"
    type: "end"
    strict: false
  - id: "End15"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "End5"
    type: "end"
    strict: false
  - id: "End6"
    type: "end"
    strict: false
  - id: "End7"
    type: "end"
    strict: false
  - id: "End8"
    type: "end"
    strict: false
  - id: "End9"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "ExecuteObjectsQuery1"
    type: "pipelet"
    ref: "ExecuteObjectsQuery"
    config:
      Datasource: "default"
      ParameterName_01: "OwningDomain"
      QueryName: "organization/GetOrganizationsByOwningDomain"
      ParameterName_02: "TypeCodes"
    bindings:
      SearchResult: "Suppliers"
      ParameterValue_01: "Organization:Domain"
      ParameterValue_02: "TypeCodes"
  - id: "GetOrganizationByUser1"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      User: "CurrentUser"
  - id: "GetOrganizationByUser2"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      User: "CurrentUser"
  - id: "GetOrganizationByUser3"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      User: "CurrentUser"
  - id: "GetOrganizationByUser4"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      User: "CurrentUser"
  - id: "GetOrganizationByUser7"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      User: "CurrentUser"
  - id: "GetRecycleBinByRepository1"
    type: "pipelet"
    ref: "GetRecycleBinByRepository"
    bindings:
      Repository: "MasterRepository"
  - id: "GetRecycleBinByRepository2"
    type: "pipelet"
    ref: "GetRecycleBinByRepository"
    bindings:
      Repository: "CurrentChannel"
  - id: "GetRepositories1"
    type: "pipelet"
    ref: "GetRepositories"
  - id: "GetRepository1"
    type: "pipelet"
    ref: "GetRepository"
    config:
      CustomRepositoryTypeCode: 21
      Type: "Custom Repository"
  - id: "GetRepository2"
    type: "pipelet"
    ref: "GetRepository"
    config:
      CustomRepositoryTypeCode: 21
      Type: "Custom Repository"
  - id: "GetRepository3"
    type: "pipelet"
    ref: "GetRepository"
    config:
      CustomRepositoryTypeCode: 21
      Type: "Custom Repository"
  - id: "GetRepository4"
    type: "pipelet"
    ref: "GetRepository"
    config:
      Type: "Product Repository"
    bindings:
      OrganizationDomain: "Supplier:OrganizationDomain"
      Repository: "ProductRepository"
  - id: "GetRepository5"
    type: "pipelet"
    ref: "GetRepository"
    config:
      CustomRepositoryTypeCode: 21
      Type: "Custom Repository"
    bindings:
      Repository: "MasterRepository"
  - id: "GetRepositoryByRepositoryDomain1"
    type: "pipelet"
    ref: "GetRepositoryByRepositoryDomain"
    bindings:
      Repository: "ParentChannelRepository"
      RepositoryDomain: "Organization:OwningDomain"
  - id: "GetRepositoryByRepositoryDomain3"
    type: "pipelet"
    ref: "GetRepositoryByRepositoryDomain"
    bindings:
      Repository: "ParentChannelRepository"
      RepositoryDomain: "Organization:OwningDomain"
  - id: "GetRepositoryByUUID3"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "Repository"
      UUID: "RepositoryUUID"
  - id: "GetRepositoryByUUID4"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "ChannelRepository"
      UUID: "ChannelID"
  - id: "Join1"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Loop1"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Iterator: "Repositories"
      Object: "CurrentChannel"
      InVector: "null"
      Objects: "null"
      OutVector: "null"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      Iterator: "SupplierRepositories"
      Object: "null"
      OutVector: "InVector"
      InVector: "null"
      Objects: "null"

links:
  - from: "Start1"
    via: "next"
    to: "GetOrganizationByUser3"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Join1"
    into: "in1"
  - from: "GetOrganizationByUser1"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "Join1"
    via: "next"
    to: "GetRepository3"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "End5"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "GetOrganizationByUser2"
    into: "in"
  - from: "GetOrganizationByUser2"
    via: "next"
    to: "CreateIteratorFromConfigValues1"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "End6"
    into: "in"
  - from: "GetRepositoryByUUID3"
    via: "next"
    to: "AddObjectToVector5"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "GetRepositoryByUUID3"
    into: "in"
  - from: "AddObjectToVector5"
    via: "next"
    to: "End8"
    into: "in"
  - from: "GetOrganizationByUser3"
    via: "next"
    to: "GetRepositories1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "GetOrganizationByUser4"
    into: "in"
  - from: "GetRepository1"
    via: "next"
    to: "AddObjectToVector6"
    into: "in"
  - from: "AddObjectToVector6"
    via: "next"
    to: "End9"
    into: "in"
  - from: "AddObjectToVector4"
    via: "next"
    to: "GetRepository1"
    into: "in"
  - from: "GetOrganizationByUser4"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "GetRepository2"
    via: "next"
    to: "AddObjectToVector7"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "GetRepository2"
    into: "in"
  - from: "AddObjectToVector7"
    via: "next"
    to: "End7"
    into: "in"
  - from: "GetRepositoryByRepositoryDomain1"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetRepositoryByUUID4"
    into: "in"
  - from: "GetRepositories1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "GetRepositoryByUUID4"
    via: "error"
    to: "EndNode3"
    into: "in"
  - from: "GetRepositoryByUUID4"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "ExecuteObjectsQuery1"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CreateIteratorFromConfigValues3"
    into: "in"
  - from: "CreateIteratorFromConfigValues3"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "ExecuteObjectsQuery1"
    into: "in"
  - from: "GetRepository3"
    via: "error"
    to: "End2"
    into: "in"
  - from: "GetRepository3"
    via: "next"
    to: "AddObjectToVector3"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "GetRepositoryByRepositoryDomain1"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "GetRepositoryByRepositoryDomain3"
    into: "in"
  - from: "GetRepositoryByRepositoryDomain3"
    via: "next"
    to: "AddObjectToVector4"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "AddObjectToVector8"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "Loop1"
    via: "do"
    to: "GetRepository4"
    into: "in"
  - from: "GetRepository4"
    via: "next"
    to: "AddObjectToVector8"
    into: "in"
  - from: "GetRepository4"
    via: "error"
    to: "Join4"
    into: "in3"
  - from: "AddObjectToVector3"
    via: "next"
    to: "End4"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "End11"
    into: "in"
  - from: "CreateIteratorFromConfigValues1"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "GetRepository5"
    via: "next"
    to: "GetRecycleBinByRepository1"
    into: "in"
  - from: "AddObjectToVector9"
    via: "next"
    to: "End14"
    into: "in"
  - from: "Decision5"
    via: "no"
    to: "GetOrganizationByUser7"
    into: "in"
  - from: "Decision5"
    via: "yes"
    to: "Join6"
    into: "in1"
  - from: "GetOrganizationByUser7"
    via: "next"
    to: "Join6"
    into: "in3"
  - from: "Join6"
    via: "next"
    to: "GetRepository5"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "Decision5"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "GetRecycleBinByRepository1"
    via: "next"
    to: "AddObjectToVector9"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "GetRecycleBinByRepository2"
    into: "in"
  - from: "GetRecycleBinByRepository2"
    via: "next"
    to: "AddObjectToVector11"
    into: "in"
  - from: "AddObjectToVector11"
    via: "next"
    to: "End15"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "GetOrganizationByUser1"
    into: "in"
