flow: "EClassCatalog"
kind: "view"

entries:
  - id: "Start1"
    name: "PageProducts"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "CategoryPaging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Browse"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "PageCategories"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "ProductPaging"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "GetCategories-ByEClassParent"
  - id: "Call2"
    type: "call"
    ref: "GetAssignedProducts-ByCategory"
  - id: "Call3"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "Call4"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "Call5"
    type: "call"
    ref: "EClassCatalog-PageProducts"
  - id: "Call6"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "Call7"
    type: "call"
    ref: "EClassCatalog-PageCategories"
  - id: "CreateProductIdentifierLookupHelper1"
    type: "pipelet"
    ref: "CreateProductIdentifierLookupHelper"
    config:
      LookupType: "ProductDomainLookup"
    bindings:
      ProductDomain: "CurrentMasterRepository:RepositoryDomain"
  - id: "Decision1"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision2"
    type: "decision"
    condition: "SubCategories"
  - id: "Decision3"
    type: "decision"
    condition: "SubCategories:ElementCount"
  - id: "Decision4"
    type: "decision"
    condition: "PageLocator"
  - id: "Decision5"
    type: "decision"
    condition: "PageLocator"
  - id: "Decision6"
    type: "decision"
    condition: "Products"
  - id: "Decision7"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision8"
    type: "decision"
    condition: "Filter"
  - id: "Decision9"
    type: "decision"
    condition: "Filter"
  - id: "DetermineCatalogCategoriesPath1"
    type: "pipelet"
    ref: "DetermineCatalogCategoriesPath"
  - id: "DetermineCatalogCategoriesPath2"
    type: "pipelet"
    ref: "DetermineCatalogCategoriesPath"
  - id: "DetermineCatalogCategoriesPath3"
    type: "pipelet"
    ref: "DetermineCatalogCategoriesPath"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "GetCategoryByUUID1"
    type: "pipelet"
    ref: "GetCategoryByUUID"
  - id: "GetCategoryByUUID2"
    type: "pipelet"
    ref: "GetCategoryByUUID"
  - id: "GetCategoryByUUID3"
    type: "pipelet"
    ref: "GetCategoryByUUID"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "SubCategoryList"
      RestorePageLocatorDictionary: "True"
  - id: "GetPageLocator2"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ProductList"
      RestorePageLocatorDictionary: "True"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "SubCategories"
      PageableID: "PageLocator:PageableID"
  - id: "GetPageable2"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Products"
      PageableID: "PageLocator:PageableID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join10"
    type: "join"
  - id: "Join11"
    type: "join"
  - id: "Join12"
    type: "join"
  - id: "Join13"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Catalogs"
      WorkingTemplate: "catalog/BrowseeclassCatalog"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "DetermineRepositoriesPipeline"
      Value: "DetermineRepositories-Master"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "SubCategories"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "SubCategories"
  - id: "SetPage3"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Products"
  - id: "SetPage4"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Products"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "EClassCatalog-CategoryPaging"
      DefaultPageLocatorName: "SubCategoryList"
    bindings:
      Pageable: "SubCategories"
  - id: "SetPageLocator2"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "EClassCatalog-ProductPaging"
      DefaultPageLocatorName: "ProductList"
    bindings:
      Pageable: "Products"
  - id: "SetPageLocatorParameter1"
    type: "pipelet"
    ref: "SetPageLocatorParameter"
    config:
      DefaultParameterName: "CatalogCategoryID"
    bindings:
      ParameterValue: "Category:UUID"
  - id: "SetPageLocatorParameter2"
    type: "pipelet"
    ref: "SetPageLocatorParameter"
    config:
      DefaultParameterName: "CatalogCategoryID"
    bindings:
      ParameterValue: "Category:UUID"
  - id: "SetPageLocatorParameter3"
    type: "pipelet"
    ref: "SetPageLocatorParameter"
    config:
      DefaultParameterName: "Filter"
    bindings:
      ParameterValue: "Filter"
  - id: "SetPageLocatorParameter4"
    type: "pipelet"
    ref: "SetPageLocatorParameter"
    config:
      DefaultParameterName: "Filter"
    bindings:
      ParameterValue: "Filter"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"
  - id: "VerifyInteger2"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "DetermineCatalogCategoriesPath1"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Decision7"
    via: "no"
    to: "Decision5"
    into: "in"
  - from: "Decision5"
    via: "yes"
    to: "SetPage4"
    into: "in"
  - from: "Decision7"
    via: "yes"
    to: "VerifyInteger2"
    into: "in"
  - from: "VerifyInteger2"
    via: "next"
    to: "SetPage3"
    into: "in"
  - from: "SetPage3"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "VerifyInteger2"
    via: "error"
    to: "Join9"
    into: "in3"
  - from: "Join10"
    via: "next"
    to: "SetPageLocator2"
    into: "in"
  - from: "Join9"
    via: "next"
    to: "Join10"
    into: "in1"
  - from: "Decision3"
    via: "no"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "SetPage4"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "Decision5"
    via: "no"
    to: "Join8"
    into: "in3"
  - from: "Join8"
    via: "next"
    to: "Join10"
    into: "in3"
  - from: "Decision6"
    via: "yes"
    to: "Decision7"
    into: "in"
  - from: "Decision6"
    via: "no"
    to: "Join13"
    into: "in1"
  - from: "SetPageLocator2"
    via: "next"
    to: "SetPageLocatorParameter2"
    into: "in"
  - from: "SetPageLocatorParameter2"
    via: "next"
    to: "Decision9"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Decision6"
    into: "in"
  - from: "Join11"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "CreateProductIdentifierLookupHelper1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "GetPageable1"
    via: "next"
    to: "GetCategoryByUUID1"
    into: "in"
  - from: "GetCategoryByUUID1"
    via: "next"
    to: "DetermineCatalogCategoriesPath2"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "DetermineCatalogCategoriesPath2"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "Decision1"
    via: "no"
    to: "Decision4"
    into: "in"
  - from: "Decision4"
    via: "yes"
    to: "SetPage1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "GetCategoryByUUID2"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage2"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join5"
    into: "in3"
  - from: "Join2"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "SetPage1"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Decision4"
    via: "no"
    to: "Join6"
    into: "in3"
  - from: "Join6"
    via: "next"
    to: "Join2"
    into: "in3"
  - from: "Decision2"
    via: "yes"
    to: "Decision1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join3"
    into: "in1"
  - from: "Decision3"
    via: "yes"
    to: "Join1"
    into: "in1"
  - from: "SetPageLocator1"
    via: "next"
    to: "SetPageLocatorParameter1"
    into: "in"
  - from: "SetPageLocatorParameter1"
    via: "next"
    to: "Decision8"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "End2"
    into: "in"
  - from: "GetPageable2"
    via: "next"
    to: "GetCategoryByUUID3"
    into: "in"
  - from: "GetCategoryByUUID3"
    via: "next"
    to: "DetermineCatalogCategoriesPath3"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "GetPageLocator2"
    into: "in"
  - from: "GetPageLocator2"
    via: "next"
    to: "GetPageable2"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Join12"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Join12"
    into: "in1"
  - from: "DetermineCatalogCategoriesPath3"
    via: "next"
    to: "Join12"
    into: "in3"
  - from: "Call7"
    via: "next"
    to: "Join4"
    into: "in2"
  - from: "SetPageLocatorParameter3"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "SetPageLocatorParameter4"
    via: "next"
    to: "Join11"
    into: "in1"
  - from: "Call4"
    via: "next"
    to: "GetCategoryByUUID2"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Join7"
    into: "in3"
  - from: "Decision8"
    via: "no"
    to: "Join3"
    into: "in2"
  - from: "Decision8"
    via: "yes"
    to: "SetPageLocatorParameter3"
    into: "in"
  - from: "Decision9"
    via: "yes"
    to: "SetPageLocatorParameter4"
    into: "in"
  - from: "Join13"
    via: "next"
    to: "Join11"
    into: "in3"
  - from: "Call1"
    via: "next"
    to: "DetermineCatalogCategoriesPath1"
    into: "in"
  - from: "Decision9"
    via: "no"
    to: "Join13"
    into: "in2"
  - from: "CreateProductIdentifierLookupHelper1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call4"
    into: "in"
