flow: "ExecutePreparerOnStartup"
kind: "process"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "ExecuteDatabasePreparer1"
    type: "pipelet"
    ref: "ExecuteDatabasePreparer"
    config:
      Param1: "-"
      PreparerClass: "com.intershop.beehive.core.dbinit.preparer.currency.PrepareActiveCurrencies"
  - id: "ExecuteDatabasePreparer2"
    type: "pipelet"
    ref: "ExecuteDatabasePreparer"
    config:
      Param1: "-"
      PreparerClass: "com.intershop.beehive.core.dbinit.preparer.currency.PrepareExchangeRates"
  - id: "ExecuteDatabasePreparer4"
    type: "pipelet"
    ref: "ExecuteDatabasePreparer"
    config:
      Param1: "-"
      PreparerClass: "com.intershop.beehive.core.dbinit.preparer.localization.LocaleInformationPreparer"
      Param2: "LEADLOCALE"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "ExecuteDatabasePreparer"
    config:
      Param1: "-"
      PreparerClass: "com.intershop.beehive.core.dbinit.preparer.localization.LocaleInformationPreparer"
      Param2: "REGIONALSETTINGS"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "ExecuteDatabasePreparer"
    config:
      Param1: "-"
      PreparerClass: "com.intershop.beehive.core.dbinit.preparer.user.UserCredentialPreferencePreparer"

links:
  - from: "Join2"
    via: "next"
    to: "ExecuteDatabasePreparer4"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "ExecuteDatabasePreparer2"
    into: "in"
  - from: "ExecuteDatabasePreparer2"
    via: "error"
    to: "Join2"
    into: "in3"
  - from: "ExecuteDatabasePreparer1"
    via: "error"
    to: "Join1"
    into: "in3"
  - from: "ExecuteDatabasePreparer4"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "Join4"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "ExecuteDatabasePreparer1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "ExecuteDatabasePreparer4"
    via: "error"
    to: "Join4"
    into: "in3"
  - from: "ExecuteDatabasePreparer2"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Pipelet2"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "Pipelet1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "ExecuteDatabasePreparer1"
    via: "next"
    to: "Join1"
    into: "in1"
