flow: "ExportUsers"
kind: "backoffice"

entries:
  - id: "Start2"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AccessControl1"
    type: "pipelet"
    ref: "AccessControl"
    config:
      AccessControlPermission: "MANAGE_USERS"
      PerformAccessControl: true
      PerformIPRangeCheck: false
      PerformUserLoginCheck: true
      RequireHTTPS: false
  - id: "CloseFile1"
    type: "pipelet"
    ref: "CloseFile"
    config:
      PipeletID: "CloseXMLFile1"
      StreamID: "target"
      UIDescription: "CloseExportFile"
  - id: "CloseFile2"
    type: "pipelet"
    ref: "CloseFile"
    config:
      PipeletID: "CloseXMLFile2"
      StreamID: "target"
      UIDescription: "CloseExportFile"
      Delete: true
  - id: "CloseFilter1"
    type: "pipelet"
    ref: "CloseFilter"
    config:
      FilterID: "targetfilter"
      PipeletID: "CloseFilter1"
  - id: "CloseFilter2"
    type: "pipelet"
    ref: "CloseFilter"
    config:
      FilterID: "targetfilter"
      PipeletID: "CloseFilter2"
  - id: "CloseLoggers1"
    type: "pipelet"
    ref: "CloseLoggers"
    config:
      PipeletID: "CloseLoggers1"
      UIDescription: "CloseLoggers"
  - id: "CloseLoggers2"
    type: "pipelet"
    ref: "CloseLoggers"
    config:
      PipeletID: "CloseLoggers2"
      UIDescription: "Close Loggers"
  - id: "CreateExportIterator1"
    type: "pipelet"
    ref: "CreateExportIterator"
    config:
      Iterator.Name: "exportObjects"
      PipeletID: "CreateExportIterator1"
      StatisticsID: "statistics"
      UIDescription: "CreateExportIterator"
  - id: "CreateFileLogger1"
    type: "pipelet"
    ref: "CreateFileLogger"
    config:
      BufferSize: 1024
      Facility: "default"
      File: "UserExport.log"
      FlushTime: 0
      Level: "ERROR | WARN"
      PipeletID: "CreateFileLogger1"
      RolloverSize: 102400
      UIDescription: "CreateFileLogger"
  - id: "CreateImpexUnitFileStructure1"
    type: "pipelet"
    ref: "CreateImpexUnitFileStructure"
  - id: "DetermineConfiguration1"
    type: "pipelet"
    ref: "DetermineConfiguration"
    config:
      CartridgeName: "core"
      Controller.Class: "com.intershop.beehive.core.capi.impex.Controller"
      File: "ExportUsers.properties"
      PipeletID: "DetermineConfiguration1"
      UIDescription: "DetermineConfiguration"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "End5"
    type: "end"
    strict: false
  - id: "End6"
    type: "end"
    strict: false
  - id: "End7"
    type: "end"
    strict: false
  - id: "Export1"
    type: "pipelet"
    ref: "Export"
    config:
      PipeletID: "Export1"
      TargetID: "targetfilter"
      Template: "ExportUsers.isml"
      UIDescription: "XMLExport"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "OpenFile1"
    type: "pipelet"
    ref: "OpenFile"
    config:
      File: "UserExport.xml"
      FileID: "targetfile"
      PipeletID: "OpenXMLFile1"
      StreamID: "target"
      Type: "TARGET"
      UIDescription: "OpenExportFile"
  - id: "OpenFilter1"
    type: "pipelet"
    ref: "OpenFilter"
    config:
      Filter.Class: "com.intershop.beehive.core.internal.impex.XMLExportFilter"
      FilterID: "targetfilter"
      PipeletID: "OpenFilter1"
      TargetID: "target"
  - id: "WriteImpexLogMessage1"
    type: "pipelet"
    ref: "WriteImpexLogMessage"
    config:
      PipeletID: "LogTemplateError"
    bindings:
      MessageKey: "\"core.impex.pipelet.Export_E_TEMPLATEPROCESSOR\""
      Level: "\"ERROR\""
      Parameter0: "Exception"

links:
  - from: "CloseFile1"
    via: "next"
    to: "CloseLoggers1"
    into: "in"
  - from: "CreateImpexUnitFileStructure1"
    via: "error"
    to: "End2"
    into: "in"
  - from: "AccessControl1"
    via: "next"
    to: "CreateImpexUnitFileStructure1"
    into: "in"
  - from: "CreateImpexUnitFileStructure1"
    via: "next"
    to: "DetermineConfiguration1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "AccessControl1"
    into: "in"
  - from: "AccessControl1"
    via: "error"
    to: "End3"
    into: "in"
  - from: "DetermineConfiguration1"
    via: "error"
    to: "End4"
    into: "in"
  - from: "CloseFile2"
    via: "next"
    to: "WriteImpexLogMessage1"
    into: "in"
  - from: "CreateExportIterator1"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "OpenFilter1"
    via: "error"
    to: "Join3"
    into: "in2"
  - from: "Export1"
    via: "error"
    to: "CloseFilter2"
    into: "in"
  - from: "CloseFilter1"
    via: "next"
    to: "CloseFile1"
    into: "in"
  - from: "CloseFilter2"
    via: "error"
    to: "Join3"
    into: "in3"
  - from: "CloseFilter2"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Join3"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "CloseFile2"
    into: "in"
  - from: "OpenFile1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "WriteImpexLogMessage1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CloseLoggers2"
    via: "error"
    to: "End5"
    into: "in"
  - from: "CloseLoggers2"
    via: "next"
    to: "End6"
    into: "in"
  - from: "CloseFilter1"
    via: "error"
    to: "Join2"
    into: "in3"
  - from: "CloseLoggers1"
    via: "error"
    to: "End7"
    into: "in"
  - from: "CloseLoggers1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "CloseLoggers2"
    into: "in"
  - from: "CreateExportIterator1"
    via: "next"
    to: "OpenFilter1"
    into: "in"
  - from: "CreateFileLogger1"
    via: "next"
    to: "OpenFile1"
    into: "in"
  - from: "DetermineConfiguration1"
    via: "next"
    to: "CreateFileLogger1"
    into: "in"
  - from: "Export1"
    via: "next"
    to: "CloseFilter1"
    into: "in"
  - from: "OpenFile1"
    via: "next"
    to: "CreateExportIterator1"
    into: "in"
  - from: "OpenFilter1"
    via: "next"
    to: "Export1"
    into: "in"
