flow: "ExportConfigurationJob"
kind: "job"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "DecisionNode1"
    type: "decision"
    condition: "DomainName"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "GetDomainByName1"
    type: "pipelet"
    ref: "GetDomainByName"
    bindings:
      Domain: "SelectedDomain"
      DomainName: "DomainName"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "StopNode1"
    type: "stop"
  - id: "WriteConfigurationToFile1"
    type: "pipelet"
    ref: "WriteConfigurationToFile"
    config:
      Ordering: "Ascending"
    bindings:
      ConfigurationContext: "null"
      Domain: "SelectedDomain"

links:
  - from: "GetDomainByName1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "WriteConfigurationToFile1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "WriteConfigurationToFile1"
    via: "error"
    to: "StopNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "WriteConfigurationToFile1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetDomainByName1"
    into: "in"
  - from: "GetDomainByName1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
