flow: "GetOrders"
kind: "process"

entries:
  - id: "Start10"
    name: "CreateBasicQuery"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start11"
    name: "CreateDocumentNoCondition"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start12"
    name: "CreateDateCondition"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start13"
    name: "CreatePriceCondition"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start14"
    name: "ByAdvancedSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "BySimpleSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "CreateRepositoryCondition"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "CreateCustomerCondition"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "BuyerRelation"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "ProductRelation"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call13"
    type: "call"
  - id: "Call14"
    type: "call"
    ref: "GetOrders-CreateDocumentNoCondition"
  - id: "Call15"
    type: "call"
  - id: "Call16"
    type: "call"
    ref: "GetOrders-CreateRepositoryCondition"
  - id: "Call17"
    type: "call"
  - id: "Call18"
    type: "call"
  - id: "Call19"
    type: "call"
    ref: "GetOrders-CreateDateCondition"
  - id: "Call20"
    type: "call"
    ref: "GetOrders-CreateBasicQuery"
  - id: "Call21"
    type: "call"
  - id: "Call22"
    type: "call"
    ref: "GetOrders-CreatePriceCondition"
  - id: "Call7"
    type: "call"
    ref: "GetOrders-CreateBasicQuery"
  - id: "CallNode2"
    type: "call"
    ref: "This:CreateCustomerCondition"
  - id: "CallNode4"
    type: "call"
  - id: "CheckForEmptyString2"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "ProductSKU"
  - id: "Decision10"
    type: "decision"
    condition: "CreateUserRelationPipeline"
  - id: "Decision12"
    type: "decision"
    condition: "CreateProductRelationPipeline"
  - id: "Decision13"
    type: "decision"
    condition: "CreateUserRelationPipeline"
  - id: "Decision6"
    type: "decision"
    condition: "CreateUserRelationPipeline"
  - id: "Decision7"
    type: "decision"
    condition: "Repositories"
  - id: "Decision8"
    type: "decision"
    condition: "CreateOrderStatesConditionPipeline"
  - id: "Decision9"
    type: "decision"
    condition: "CreateUserConditionPipeline"
  - id: "DecisionNode10"
    type: "decision"
    condition: "MinPrice"
  - id: "DecisionNode12"
    type: "decision"
    condition: "Available"
  - id: "DecisionNode7"
    type: "decision"
    condition: "MaxDate"
  - id: "DecisionNode8"
    type: "decision"
    condition: "MinDate"
  - id: "DecisionNode9"
    type: "decision"
    condition: "MaxPrice"
  - id: "End11"
    type: "end"
    strict: false
  - id: "End12"
    type: "end"
    strict: false
  - id: "End18"
    type: "end"
    strict: false
  - id: "End19"
    type: "end"
    strict: false
  - id: "End20"
    type: "end"
    strict: false
  - id: "End21"
    type: "end"
    strict: false
  - id: "End22"
    type: "end"
    strict: false
  - id: "End23"
    type: "end"
    strict: false
  - id: "End24"
    type: "end"
    strict: false
  - id: "End7"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode10"
    type: "end"
    strict: true
  - id: "EndNode11"
    type: "end"
    strict: false
  - id: "EndNode12"
    type: "end"
    strict: false
  - id: "EndNode13"
    type: "end"
    strict: false
  - id: "EndNode14"
    type: "end"
    strict: false
  - id: "EndNode15"
    type: "end"
    strict: true
  - id: "EndNode8"
    type: "end"
    strict: false
  - id: "EndNode9"
    type: "end"
    strict: false
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      DefaultPageSize: 15
      QueryName: "order/AdvancedOrderSearch"
      ParameterName_01: "OrderDomain"
      ParameterName_02: "SortAttribute"
      ParameterName_03: "SortDirection"
    bindings:
      SearchResult: "Orders"
      Parameters: "OrderSearchParameters"
      ParameterValue_01: "OrderDomain"
      ParameterValue_02: "SortAttribute"
      ParameterValue_03: "SortDirection"
  - id: "ExecutePageableQuery2"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      DefaultPageSize: 10
      QueryName: "order/AdvancedOrderSearch"
      ParameterName_01: "OrderDomain"
    bindings:
      SearchResult: "Orders"
      Parameters: "OrderSearchParameters"
      ParameterValue_01: "OrderDomain"
  - id: "Join11"
    type: "join"
  - id: "Join15"
    type: "join"
  - id: "Join16"
    type: "join"
  - id: "Join18"
    type: "join"
  - id: "Join19"
    type: "join"
  - id: "Join20"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode21"
    type: "join"
  - id: "JoinNode22"
    type: "join"
  - id: "JoinNode23"
    type: "join"
  - id: "JoinNode24"
    type: "join"
  - id: "JoinNode25"
    type: "join"
  - id: "JoinNode26"
    type: "join"
  - id: "JoinNode27"
    type: "join"
  - id: "JoinNode28"
    type: "join"
  - id: "JoinNode29"
    type: "join"
  - id: "JoinNode30"
    type: "join"
  - id: "JoinNode31"
    type: "join"
  - id: "JoinNode32"
    type: "join"
  - id: "JoinNode33"
    type: "join"
  - id: "JoinNode34"
    type: "join"
  - id: "JoinNode35"
    type: "join"
  - id: "JoinNode36"
    type: "join"
  - id: "JoinNode37"
    type: "join"
  - id: "JoinNode38"
    type: "join"
  - id: "JoinNode39"
    type: "join"
  - id: "JoinNode40"
    type: "join"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "DocumentNo"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "CustomerName"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "CustomerName"
  - id: "UpdateDictionary1"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "StartDate"
    bindings:
      OutDictionary: "OrderSearchParameters"
      InDictionary: "OrderSearchParameters"
      Value_01: "MinDate"
  - id: "UpdateDictionary10"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "ProductItemStatus"
    bindings:
      OutDictionary: "OrderSearchParameters"
      InDictionary: "OrderSearchParameters"
      Value_01: "AvailableInt"
  - id: "UpdateDictionary2"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "OrderNumberExpression"
    bindings:
      OutDictionary: "OrderSearchParameters"
      InDictionary: "OrderSearchParameters"
      Value_01: "OrderNumberExpression"
  - id: "UpdateDictionary3"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "EndDate"
    bindings:
      OutDictionary: "OrderSearchParameters"
      InDictionary: "OrderSearchParameters"
      Value_01: "MaxDate"
  - id: "UpdateDictionary4"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "OrderDomains"
    bindings:
      OutDictionary: "OrderSearchParameters"
      InDictionary: "OrderSearchParameters"
      Value_01: "Repositories"
  - id: "UpdateDictionary5"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "PriceTotalFrom"
    bindings:
      OutDictionary: "OrderSearchParameters"
      InDictionary: "OrderSearchParameters"
      Value_01: "MinPrice"
  - id: "UpdateDictionary6"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "PriceTotalTo"
    bindings:
      OutDictionary: "OrderSearchParameters"
      InDictionary: "OrderSearchParameters"
      Value_01: "MaxPrice"
  - id: "UpdateDictionary7"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "CustomerExpression"
    bindings:
      OutDictionary: "OrderSearchParameters"
      InDictionary: "OrderSearchParameters"
      Value_01: "CustomerExpression"
  - id: "UpdateDictionary8"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "CustomerExpression"
    bindings:
      OutDictionary: "OrderSearchParameters"
      InDictionary: "OrderSearchParameters"
      Value_01: "CustomerExpression"
  - id: "UpdateDictionary9"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "ProductExpression"
    bindings:
      OutDictionary: "OrderSearchParameters"
      InDictionary: "OrderSearchParameters"
      Value_01: "ProductExpression"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "AvailableInt"
      LocalizedString: "Available"
  - id: "VerifySearchTerm1"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowWildcards: "Multi & Single"
      AllowFuzzySearch: "default"
    bindings:
      UserSearchTerm: "CustomerName"
      SearchExpression: "CustomerExpression"
  - id: "VerifySearchTerm2"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowWildcards: "Multi & Single"
      AllowFuzzySearch: "default"
    bindings:
      UserSearchTerm: "DocumentNo"
      SearchExpression: "OrderNumberExpression"
  - id: "VerifySearchTerm3"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowWildcards: "Multi & Single"
      AllowFuzzySearch: "default"
    bindings:
      UserSearchTerm: "CustomerName"
      SearchExpression: "CustomerExpression"
  - id: "VerifySearchTerm4"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowWildcards: "Multi & Single"
      AllowFuzzySearch: "default"
    bindings:
      UserSearchTerm: "ProductSKU"
      SearchExpression: "ProductExpression"

links:
  - from: "JoinNode40"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Decision6"
    via: "yes"
    to: "JoinNode22"
    into: "in1"
  - from: "JoinNode34"
    via: "next"
    to: "EndNode12"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Decision6"
    into: "in"
  - from: "Decision7"
    via: "no"
    to: "End12"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Call13"
    via: "ERROR"
    to: "JoinNode21"
    into: "in1"
  - from: "Decision7"
    via: "yes"
    to: "UpdateDictionary4"
    into: "in"
  - from: "Call13"
    via: "next"
    to: "JoinNode22"
    into: "in3"
  - from: "ExecutePageableQuery1"
    via: "error"
    to: "JoinNode33"
    into: "in2"
  - from: "Call7"
    via: "ERROR"
    to: "JoinNode21"
    into: "in1"
  - from: "JoinNode21"
    via: "next"
    to: "JoinNode33"
    into: "in1"
  - from: "Decision6"
    via: "no"
    to: "Call13"
    into: "in"
  - from: "JoinNode33"
    via: "next"
    to: "End11"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "End7"
    into: "in"
  - from: "UpdateDictionary4"
    via: "next"
    to: "End18"
    into: "in"
  - from: "JoinNode22"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "Call16"
    via: "next"
    to: "Decision8"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "Decision7"
    into: "in"
  - from: "JoinNode26"
    via: "next"
    to: "Call14"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "JoinNode25"
    via: "next"
    to: "End19"
    into: "in"
  - from: "Call18"
    via: "ERROR"
    to: "Join16"
    into: "in1"
  - from: "Call14"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Decision9"
    via: "no"
    to: "Call17"
    into: "in"
  - from: "Call18"
    via: "next"
    to: "Call16"
    into: "in"
  - from: "Call17"
    via: "next"
    to: "JoinNode26"
    into: "in3"
  - from: "Call16"
    via: "ERROR"
    to: "Join16"
    into: "in2"
  - from: "Pipelet6"
    via: "next"
    to: "VerifySearchTerm3"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "UpdateDictionary3"
    into: "in"
  - from: "Decision8"
    via: "yes"
    to: "JoinNode23"
    into: "in1"
  - from: "Call15"
    via: "ERROR"
    to: "Join11"
    into: "in2"
  - from: "Join16"
    via: "next"
    to: "Join11"
    into: "in1"
  - from: "Join15"
    via: "next"
    to: "JoinNode24"
    into: "in1"
  - from: "Decision9"
    via: "yes"
    to: "JoinNode26"
    into: "in1"
  - from: "StartNode5"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "JoinNode23"
    via: "next"
    to: "Decision9"
    into: "in"
  - from: "Call17"
    via: "ERROR"
    to: "Join15"
    into: "in2"
  - from: "Call14"
    via: "ERROR"
    to: "JoinNode24"
    into: "in2"
  - from: "Join18"
    via: "next"
    to: "End21"
    into: "in"
  - from: "Decision8"
    via: "no"
    to: "Call15"
    into: "in"
  - from: "JoinNode24"
    via: "next"
    to: "JoinNode25"
    into: "in1"
  - from: "CallNode2"
    via: "ERROR"
    to: "JoinNode25"
    into: "in2"
  - from: "Join11"
    via: "next"
    to: "Join15"
    into: "in1"
  - from: "Start10"
    via: "next"
    to: "Call18"
    into: "in"
  - from: "JoinNode27"
    via: "next"
    to: "End20"
    into: "in"
  - from: "Pipelet4"
    via: "error"
    to: "Join18"
    into: "in1"
  - from: "DecisionNode8"
    via: "yes"
    to: "UpdateDictionary1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "End23"
    into: "in"
  - from: "Start11"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "VerifySearchTerm2"
    into: "in"
  - from: "VerifySearchTerm2"
    via: "next"
    to: "UpdateDictionary2"
    into: "in"
  - from: "UpdateDictionary2"
    via: "next"
    to: "Join18"
    into: "in1"
  - from: "UpdateDictionary1"
    via: "next"
    to: "JoinNode28"
    into: "in1"
  - from: "DecisionNode9"
    via: "yes"
    to: "UpdateDictionary6"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "JoinNode27"
    into: "in2"
  - from: "UpdateDictionary3"
    via: "next"
    to: "JoinNode27"
    into: "in1"
  - from: "DecisionNode9"
    via: "no"
    to: "JoinNode29"
    into: "in2"
  - from: "JoinNode28"
    via: "next"
    to: "DecisionNode7"
    into: "in"
  - from: "DecisionNode10"
    via: "yes"
    to: "UpdateDictionary5"
    into: "in"
  - from: "Start12"
    via: "next"
    to: "DecisionNode8"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "VerifySearchTerm1"
    into: "in"
  - from: "DecisionNode8"
    via: "no"
    to: "JoinNode28"
    into: "in2"
  - from: "UpdateDictionary5"
    via: "next"
    to: "JoinNode30"
    into: "in1"
  - from: "UpdateDictionary6"
    via: "next"
    to: "JoinNode29"
    into: "in1"
  - from: "Decision10"
    via: "no"
    to: "JoinNode32"
    into: "in2"
  - from: "VerifySearchTerm1"
    via: "error"
    to: "EndNode10"
    into: "in"
  - from: "DecisionNode10"
    via: "no"
    to: "JoinNode30"
    into: "in2"
  - from: "Decision10"
    via: "yes"
    to: "Pipelet5"
    into: "in"
  - from: "JoinNode29"
    via: "next"
    to: "End22"
    into: "in"
  - from: "Start13"
    via: "next"
    to: "DecisionNode10"
    into: "in"
  - from: "JoinNode30"
    via: "next"
    to: "DecisionNode9"
    into: "in"
  - from: "VerifySearchTerm1"
    via: "next"
    to: "UpdateDictionary7"
    into: "in"
  - from: "UpdateDictionary7"
    via: "next"
    to: "JoinNode31"
    into: "in1"
  - from: "StartNode4"
    via: "next"
    to: "Decision10"
    into: "in"
  - from: "JoinNode31"
    via: "next"
    to: "EndNode9"
    into: "in"
  - from: "Pipelet5"
    via: "error"
    to: "JoinNode32"
    into: "in1"
  - from: "JoinNode32"
    via: "next"
    to: "JoinNode31"
    into: "in1"
  - from: "VerifySearchTerm2"
    via: "error"
    to: "EndNode11"
    into: "in"
  - from: "Call15"
    via: "next"
    to: "JoinNode23"
    into: "in3"
  - from: "VerifySearchTerm3"
    via: "next"
    to: "UpdateDictionary8"
    into: "in"
  - from: "VerifySearchTerm3"
    via: "error"
    to: "EndNode13"
    into: "in"
  - from: "Pipelet6"
    via: "error"
    to: "JoinNode34"
    into: "in1"
  - from: "UpdateDictionary8"
    via: "next"
    to: "JoinNode34"
    into: "in1"
  - from: "CheckForEmptyString2"
    via: "next"
    to: "VerifySearchTerm4"
    into: "in"
  - from: "JoinNode37"
    via: "next"
    to: "EndNode14"
    into: "in"
  - from: "JoinNode36"
    via: "next"
    to: "DecisionNode12"
    into: "in"
  - from: "CheckForEmptyString2"
    via: "error"
    to: "JoinNode36"
    into: "in2"
  - from: "VerifySearchTerm4"
    via: "next"
    to: "UpdateDictionary9"
    into: "in"
  - from: "Start14"
    via: "next"
    to: "Call20"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CheckForEmptyString2"
    into: "in"
  - from: "VerifySearchTerm4"
    via: "error"
    to: "EndNode15"
    into: "in"
  - from: "Join20"
    via: "next"
    to: "JoinNode35"
    into: "in1"
  - from: "Call21"
    via: "ERROR"
    to: "JoinNode35"
    into: "in1"
  - from: "ExecutePageableQuery2"
    via: "next"
    to: "End24"
    into: "in"
  - from: "CallNode4"
    via: "ERROR"
    to: "JoinNode40"
    into: "in2"
  - from: "Call21"
    via: "next"
    to: "JoinNode38"
    into: "in3"
  - from: "Decision13"
    via: "no"
    to: "Call21"
    into: "in"
  - from: "UpdateDictionary10"
    via: "next"
    to: "JoinNode37"
    into: "in1"
  - from: "UpdateDictionary9"
    via: "next"
    to: "JoinNode36"
    into: "in1"
  - from: "Decision12"
    via: "no"
    to: "CallNode4"
    into: "in"
  - from: "JoinNode35"
    via: "next"
    to: "JoinNode40"
    into: "in1"
  - from: "JoinNode39"
    via: "next"
    to: "ExecutePageableQuery2"
    into: "in"
  - from: "Call19"
    via: "ERROR"
    to: "Join19"
    into: "in2"
  - from: "JoinNode38"
    via: "next"
    to: "Decision12"
    into: "in"
  - from: "Decision13"
    via: "yes"
    to: "JoinNode38"
    into: "in1"
  - from: "Call20"
    via: "next"
    to: "Call19"
    into: "in"
  - from: "Call20"
    via: "ERROR"
    to: "Join19"
    into: "in1"
  - from: "Call19"
    via: "next"
    to: "Call22"
    into: "in"
  - from: "Call22"
    via: "ERROR"
    to: "Join20"
    into: "in2"
  - from: "Decision12"
    via: "yes"
    to: "JoinNode39"
    into: "in2"
  - from: "Join19"
    via: "next"
    to: "Join20"
    into: "in1"
  - from: "CallNode4"
    via: "next"
    to: "JoinNode39"
    into: "in1"
  - from: "Call22"
    via: "next"
    to: "Decision13"
    into: "in"
  - from: "ExecutePageableQuery2"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "DecisionNode12"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "UpdateDictionary10"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "EndNode1"
    into: "in"
  - from: "DecisionNode12"
    via: "no"
    to: "JoinNode37"
    into: "in2"
