flow: "GetProductData"
kind: "view"

entries:
  - id: "StartNode1"
    name: "FormatProduct"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductUUID"
        type: "java.lang.String"
        required: false
      - key: "SKU"
        type: "java.lang.String"
        required: false
      - key: "Format"
        type: "java.lang.String"
        required: true
      - key: "Reviews"
        type: "java.lang.Integer"
        required: false
      - key: "ReturnVariable"
        type: "java.lang.String"
        required: false
  - id: "StartNode2"
    name: "FormatProducts"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductUUID"
        type: "java.lang.String"
        required: false
      - key: "SKU"
        type: "java.lang.String"
        required: false
      - key: "Format"
        type: "java.lang.String"
        required: true
      - key: "Reviews"
        type: "java.lang.Integer"
        required: false
      - key: "ReturnVariable"
        type: "java.lang.String"
        required: false
  - id: "StartNode3"
    name: "FormatProductsByCategory"
    mode: "private"
    strict: true
    inputs:
      - key: "Format"
        type: "java.lang.String"
        required: true
      - key: "CatalogCategoryUUID"
        type: "java.lang.String"
        required: true
      - key: "Reviews"
        type: "java.lang.Integer"
        required: false

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Iterator: "ProductBOs"
      OutVector: "ProductBOsVector"
      Object: "ProductBO"
      Objects: "null"
      InVector: "ProductBOsVector"
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Iterator: "ProductBOs"
      OutVector: "ProductBOsVector"
      Object: "ProductBO"
      Objects: "null"
      InVector: "ProductBOsVector"
  - id: "AddObjectToVector3"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Iterator: "ProductBOs"
      OutVector: "ProductBOsVector"
      Object: "ProductBO"
      Objects: "null"
      InVector: "ProductBOsVector"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessB2CProduct-GetProductBOByProductUUIDOrSKU"
    bindings:
      ProductDomain: "CurrentProductRepository:RepositoryDomain"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessB2CProduct-GetProductBOByProductUUIDOrSKU"
    bindings:
      ProductDomain: "CurrentProductRepository:RepositoryDomain"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessChannelCatalog-GetAssignedProducts"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessB2CProduct-GetProductBOByProductUUIDOrSKU"
    bindings:
      ProductDomain: "CurrentProductRepository:RepositoryDomain"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessB2CProduct-GetProductBOByProductUUIDOrSKU"
    bindings:
      ProductDomain: "CurrentProductRepository:RepositoryDomain"
      ProductUUID: "Product:UUID"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ProductUUID"
  - id: "DecisionNode2"
    type: "decision"
    condition: "SKU"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Format"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Format"
  - id: "DecisionNode5"
    type: "decision"
    condition: "Format"
  - id: "DecisionNode6"
    type: "decision"
    condition: "Format"
  - id: "DecisionNode7"
    type: "decision"
    condition: "ReturnVariable"
  - id: "DecisionNode8"
    type: "decision"
    condition: "ReturnVariable"
  - id: "GetCategoryByUUID1"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "CatalogCategoryUUID"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SKU"
    bindings:
      Selection: "SKUIterator"
  - id: "GetFormSelection4"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "ProductUUID"
    bindings:
      Selection: "ProductUUIDIterator"
  - id: "GetValuesFromRequest2"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "ApplicationRepository"
    bindings:
      Namespace: "null"
      Key: "null"
  - id: "GetValuesFromRequest4"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "Application"
    bindings:
      Key: "\"CurrentOrganization\""
      Namespace: "null"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "InteractionNode3"
    type: "interaction"
  - id: "InteractionNode4"
    type: "interaction"
  - id: "InteractionNode5"
    type: "interaction"
  - id: "InteractionNode6"
    type: "interaction"
  - id: "InteractionNode7"
    type: "interaction"
  - id: "InteractionNode8"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "LoopNode3"
    type: "loop"

links:
  - from: "LoopNode2"
    via: "do"
    to: "CallNode4"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "InteractionNode2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetFormSelection4"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "GetFormSelection1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "DecisionNode4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "InteractionNode3"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "InteractionNode4"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "GetFormSelection1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "LoopNode3"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "CallNode2"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "DecisionNode8"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "InteractionNode6"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "InteractionNode7"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "AddObjectToVector3"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "DecisionNode1"
    via: "no"
    to: "DecisionNode2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "GetCategoryByUUID1"
    via: "next"
    to: "GetValuesFromRequest4"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "DecisionNode7"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetCategoryByUUID1"
    into: "in"
  - from: "GetValuesFromRequest4"
    via: "next"
    to: "GetValuesFromRequest2"
    into: "in"
  - from: "LoopNode3"
    via: "do"
    to: "CallNode5"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "AddObjectToVector3"
    into: "in"
  - from: "GetValuesFromRequest4"
    via: "error"
    to: "GetValuesFromRequest2"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "InteractionNode1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "CallNode2"
    into: "in"
  - from: "DecisionNode8"
    via: "no"
    to: "InteractionNode5"
    into: "in"
  - from: "DecisionNode8"
    via: "yes"
    to: "InteractionNode8"
    into: "in"
  - from: "GetValuesFromRequest2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "GetValuesFromRequest2"
    via: "error"
    to: "CallNode3"
    into: "in"
  - from: "GetFormSelection4"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "AddObjectToVector1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "CallNode1"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
