flow: "GetPageletData"
kind: "view"

entries:
  - id: "StartNode1"
    name: "FormatPagelet"
    mode: "private"
    strict: true
    inputs:
      - key: "Format"
        type: "java.lang.String"
        required: true
      - key: "PageletUUID"
        type: "java.lang.String"
        required: true
  - id: "StartNode12"
    name: "GetPageletByUUID"
    mode: "private"
    strict: true
    inputs:
      - key: "PageletUUID"
        type: "java.lang.String"
        required: true
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: true
  - id: "StartNode2"
    name: "FormatPagelets"
    mode: "private"
    strict: true
    inputs:
      - key: "Format"
        type: "java.lang.String"
        required: true
      - key: "PageletUUID"
        type: "java.lang.String"
        required: true

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "PageletsVector"
      Object: "Pagelet"
      Objects: "null"
      Iterator: "Pagelets"
      OutVector: "PageletsVector"
  - id: "CallNode1"
    type: "call"
    ref: "GetPageletData-GetPageletByUUID"
    bindings:
      Locale: "CurrentSession:Locale"
  - id: "CallNode2"
    type: "call"
    ref: "GetPageletData-GetPageletByUUID"
    bindings:
      Locale: "CurrentSession:Locale"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Format"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Format"
  - id: "DecisionNode5"
    type: "decision"
    condition: "Format"
  - id: "DecisionNode6"
    type: "decision"
    condition: "Format"
  - id: "EndNode20"
    type: "end"
    strict: true
    outputs:
      - key: "Pagelet"
        type: "com.intershop.component.pmc.capi.pagelet.Pagelet"
        guaranteed: false
      - key: "PageletConfigurationParameters"
        type: "java.util.Map"
        guaranteed: false
  - id: "GetConfigurationParametersAsMap1"
    type: "pipelet"
    ref: "GetConfigurationParametersAsMap"
    bindings:
      ConfigurationParameterCtnr: "Pagelet"
      ConfigurationParameterMap: "PageletConfigurationParameters"
  - id: "GetFormSelection4"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "PageletUUID"
    bindings:
      Selection: "PageletUUIDIterator"
  - id: "GetPageletByUUID1"
    type: "pipelet"
    ref: "GetPageletByUUID"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode3"
    type: "interaction"
  - id: "InteractionNode4"
    type: "interaction"
  - id: "InteractionNode5"
    type: "interaction"
  - id: "InteractionNode6"
    type: "interaction"
  - id: "InteractionNode7"
    type: "interaction"
  - id: "JoinNode4"
    type: "join"
  - id: "LoopNode1"
    type: "loop"
  - id: "PutConfigurationParameters4"
    type: "pipelet"
    ref: "PutConfigurationParameters"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "PageletConfigurationParameters"

links:
  - from: "LoopNode1"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "InteractionNode1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "InteractionNode3"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "InteractionNode4"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "InteractionNode5"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "InteractionNode6"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "InteractionNode7"
    into: "in"
  - from: "StartNode12"
    via: "next"
    to: "GetPageletByUUID1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode20"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetFormSelection4"
    into: "in"
  - from: "PutConfigurationParameters4"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "GetPageletByUUID1"
    via: "next"
    to: "PutConfigurationParameters4"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "GetConfigurationParametersAsMap1"
    into: "in"
  - from: "GetConfigurationParametersAsMap1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "GetPageletByUUID1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "LoopNode1"
    via: "do"
    to: "CallNode2"
    into: "in"
  - from: "GetFormSelection4"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
