flow: "GetReplicationProcesses"
kind: "process"

entries:
  - id: "StartNode1"
    name: "ByState"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "replication/GetReplicationProcesses"
      DefaultPageSize: 10
      ParameterName_01: "State"
    bindings:
      ParameterValue_01: "State"
      SearchResult: "ReplicationProcesses"

links:
  - from: "ExecutePageableQuery1"
    via: "error"
    to: "EndNode1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "EndNode3"
    into: "in"
