flow: "GetRequisitions"
kind: "process"

entries:
  - id: "Start2"
    name: "ApprovalStatusQO"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "CreateBuyerNoQueryObject"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "OrderStatusQO"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "BySearch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call5"
    type: "call"
    ref: "GetRequisitions-ApprovalStatusQO"
  - id: "Call6"
    type: "call"
    ref: "GetRequisitions-CreateBuyerNoQueryObject"
  - id: "Call7"
    type: "call"
    ref: "GetRequisitions-OrderStatusQO"
  - id: "Decision2"
    type: "decision"
    condition: "CreationBuyerNo"
  - id: "Decision5"
    type: "decision"
    condition: "ApprovalStatus"
  - id: "Decision6"
    type: "decision"
    condition: "OrderStatus"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End10"
    type: "end"
    strict: false
  - id: "End11"
    type: "end"
    strict: false
  - id: "End12"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End8"
    type: "end"
    strict: false
  - id: "End9"
    type: "end"
    strict: false
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "requisition/GetRequisitions"
      DefaultPageSize: 15
      ParameterName_01: "DomainUUID"
      ParameterName_02: "UserID"
      ParameterName_03: "Status"
      ParameterName_04: "LocaleInformation"
    bindings:
      SearchResult: "Requisitions"
      ParameterValue_01: "DomainUUID"
      ParameterValue_02: "UserID"
      ParameterValue_03: "Status"
      Parameters: "QueryParameters"
      ParameterValue_04: "CurrentRequest:Locale"
  - id: "UpdateDictionary1"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "ApprovalStateGroup"
    bindings:
      Value_01: "ApprovalStatus"
      InDictionary: "QueryParameters"
      OutDictionary: "QueryParameters"
  - id: "UpdateDictionary2"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "OrderStateGroup"
    bindings:
      InDictionary: "QueryParameters"
      OutDictionary: "QueryParameters"
      Value_01: "OrderStatus"
  - id: "UpdateDictionary3"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "CreationBuyerNo"
    bindings:
      InDictionary: "QueryParameters"
      OutDictionary: "QueryParameters"
      Value_01: "CreationBuyerNo"

links:
  - from: "Decision6"
    via: "yes"
    to: "UpdateDictionary2"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "End8"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Decision5"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "UpdateDictionary3"
    into: "in"
  - from: "Decision5"
    via: "no"
    to: "End2"
    into: "in"
  - from: "Decision5"
    via: "yes"
    to: "UpdateDictionary1"
    into: "in"
  - from: "UpdateDictionary2"
    via: "next"
    to: "End10"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Decision6"
    into: "in"
  - from: "Decision6"
    via: "no"
    to: "End9"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "UpdateDictionary3"
    via: "next"
    to: "End1"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "error"
    to: "End11"
    into: "in"
  - from: "UpdateDictionary1"
    via: "next"
    to: "End3"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "End12"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "Call5"
    into: "in"
