flow: "IncludeBranding"
kind: "include"

entries:
  - id: "Start12"
    name: "StyleSheetHook"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start15"
    name: "ImageHook"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "GetBrandingInstallation"
    mode: "private"
    strict: true
    inputs:
      - key: "Hook_Image_Name"
        type: "java.lang.String"
        required: false

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessBranding-GetBrandingInstallationByApplication"
    bindings:
      Locale: "CurrentSession:Locale"
      Unit: "CurrentOrganization:OrganizationDomain"
      Application: "CurrentApplication"
  - id: "CallNode2"
    type: "call"
    ref: "DetermineOrganizations-Current"
  - id: "CallNode3"
    type: "call"
    ref: "DetermineOrganizations-Current"
  - id: "CallNode4"
    type: "call"
    ref: "DetermineOrganizations-Current"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessBranding-GetBrandingInstallationByApplication"
    bindings:
      Locale: "CurrentSession:Locale"
      Unit: "CurrentOrganization:OrganizationDomain"
      Application: "CurrentApplication"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessBranding-GetBrandingInstallationByApplication"
    bindings:
      Locale: "CurrentSession:Locale"
      Unit: "CurrentOrganization:OrganizationDomain"
      Application: "CurrentApplication"
  - id: "EndNode1"
    type: "end"
    strict: false
    outputs:
      - key: "BrandingInstallation"
        type: "com.intershop.component.foundation.capi.branding.BrandingInstallation"
        guaranteed: false
      - key: "Hook_Image_Name"
        type: "java.lang.String"
        guaranteed: true
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd11"
    type: "interaction"
  - id: "InteractionEnd14"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"

links:
  - from: "CallNode3"
    via: "ERROR"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "CallNode1"
    via: "ERROR"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "InteractionEnd11"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Start12"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode5"
    via: "ERROR"
    to: "JoinNode1"
    into: "in1"
  - from: "Start15"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "InteractionEnd14"
    into: "in"
  - from: "CallNode4"
    via: "ERROR"
    to: "JoinNode2"
    into: "in1"
