flow: "IncludeBrandingContent"
kind: "include"

entries:
  - id: "Start1"
    name: "ImageHook"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "BuildTemplatePath"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "TemplateHook"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "StyleSheetHook"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToString1"
    type: "pipelet"
    ref: "AddObjectToString"
    config:
      DefaultSeparator: "branding/"
    bindings:
      InObject: "OrganizationDomain:DomainName"
  - id: "AddObjectToString2"
    type: "pipelet"
    ref: "AddObjectToString"
    config:
      DefaultSeparator: "/"
    bindings:
      InObject: "Hook_Template_Name"
      InString: "OutString"
      OutString: "Template"
  - id: "Call1"
    type: "call"
    ref: "IncludeBrandingContent-BuildTemplatePath"
  - id: "End1"
    type: "end"
    strict: false
  - id: "GetBrandingInstallationByApplication1"
    type: "pipelet"
    ref: "GetBrandingInstallationByApplication"
    bindings:
      LocaleID: "CurrentSession:Locale:LocaleID"
      Unit: "OrganizationDomain"
      Application: "CurrentApplication"
  - id: "GetBrandingInstallationBySite1"
    type: "pipelet"
    ref: "GetBrandingInstallationBySite"
    bindings:
      Locale: "CurrentSession:Locale"
      Site: "CurrentDomain"
      Unit: "OrganizationDomain"
      AppID: "CurrentAppContext:App:Id"
  - id: "GetBrandingInstallationBySite3"
    type: "pipelet"
    ref: "GetBrandingInstallationBySite"
    bindings:
      Locale: "CurrentSession:Locale"
      Site: "CurrentDomain"
      Unit: "OrganizationDomain"
      AppID: "CurrentAppContext:App:Id"
  - id: "GetOrganizationByUser1"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      User: "CurrentUser"
  - id: "GetOrganizationByUser2"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      User: "CurrentUser"
  - id: "GetOrganizationByUser3"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      User: "CurrentUser"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "InteractionEnd4"
    type: "interaction"
  - id: "InteractionEnd5"
    type: "interaction"
  - id: "InteractionEnd6"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "InString"
      Value: "/"
      ValueType: "Dictionary Value"

links:
  - from: "Start1"
    via: "next"
    to: "GetOrganizationByUser1"
    into: "in"
  - from: "GetOrganizationByUser2"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "GetOrganizationByUser3"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "GetBrandingInstallationByApplication1"
    via: "next"
    to: "InteractionEnd5"
    into: "in"
  - from: "GetOrganizationByUser3"
    via: "next"
    to: "GetBrandingInstallationBySite3"
    into: "in"
  - from: "GetBrandingInstallationBySite3"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "InteractionEnd4"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "AddObjectToString1"
    into: "in"
  - from: "AddObjectToString1"
    via: "next"
    to: "AddObjectToString2"
    into: "in"
  - from: "AddObjectToString2"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "GetOrganizationByUser3"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "GetOrganizationByUser2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "GetBrandingInstallationBySite1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "GetOrganizationByUser1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "InteractionEnd6"
    into: "in"
  - from: "GetBrandingInstallationBySite1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "GetOrganizationByUser1"
    via: "next"
    to: "GetBrandingInstallationBySite1"
    into: "in"
  - from: "GetBrandingInstallationByApplication1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "GetOrganizationByUser2"
    via: "next"
    to: "GetBrandingInstallationByApplication1"
    into: "in"
  - from: "GetBrandingInstallationBySite3"
    via: "error"
    to: "JoinNode3"
    into: "in1"
