flow: "MaintainBonusPoints_52"
kind: "process"

entries:
  - id: "StartNode1"
    name: "ActivatePendingPoints"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentChannel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
  - id: "StartNode2"
    name: "ActivateEntries"
    mode: "private"
    strict: true
    inputs:
      - key: "AccountEntriesForActivation"
        type: "java.util.Iterator"
        required: true
      - key: "CurrentChannel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: false
  - id: "StartNode3"
    name: "GetNextExpirationDate"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentChannel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
  - id: "StartNode4"
    name: "PurgeAccountEntries"
    mode: "private"
    strict: true
    inputs:
      - key: "AccountEntriesForPurging"
        type: "java.util.Iterator"
        required: true
  - id: "StartNode5"
    name: "PurgeOutdatedData"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentChannel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
  - id: "StartNode6"
    name: "PurgeTransactions"
    mode: "private"
    strict: true
    inputs:
      - key: "TransactionsForPurging"
        type: "java.util.Iterator"
        required: false

steps:
  - id: "CalculateDate1"
    type: "pipelet"
    ref: "CalculateDate"
    config:
      CalculationMethod: "Subtract"
    bindings:
      Date: "CurrentDate"
      Days: "BonusPointActivationTime"
      Hours: "null"
      Milliseconds: "null"
      Minutes: "null"
      Seconds: "null"
      CalculatedDate: "LastActivationDate"
  - id: "CalculateDate2"
    type: "pipelet"
    ref: "CalculateDate"
    config:
      CalculationMethod: "Subtract"
    bindings:
      Date: "CurrentDate"
      Days: "BonusPointAccountEntryLifeTimeExtention"
      Hours: "null"
      Milliseconds: "null"
      Minutes: "null"
      Seconds: "null"
      CalculatedDate: "LastPurgingDate"
  - id: "CalculateDate3"
    type: "pipelet"
    ref: "CalculateDate"
    config:
      CalculationMethod: "Subtract"
    bindings:
      Date: "CurrentDate"
      Days: "BonusPointAccountTransactionLifeTime"
      Hours: "null"
      Milliseconds: "null"
      Minutes: "null"
      Seconds: "null"
      CalculatedDate: "LastPurgingDate"
  - id: "CalculateDouble3"
    type: "pipelet"
    ref: "CalculateDouble"
    config:
      Operation: "*"
      Operand2: -1
    bindings:
      Operand1: "Entry:UnusedValue"
      Result: "Value"
      Operand2: "null"
  - id: "CallNode1"
    type: "call"
    ref: "This:GetNextExpirationDate"
  - id: "CallNode2"
    type: "call"
    ref: "This:ActivateEntries"
  - id: "CallNode3"
    type: "call"
    ref: "BonusPointUtil-CalculateNextExpirationDate"
    bindings:
      MinimumRedeemingDays: "BonusPointExpirationTime"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessBonusPointTransactions-CreateTransaction"
    bindings:
      TransactionComment: "null"
      TransactionType: "\"62\""
      TransactionValue: "Order:BonusPointsValue_Total"
      TransactionOrderNo: "Order:DocumentNo"
      BonusPointAccount: "Entry:BonusPointAccount"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessBonusPointTransactions-CreateTransaction"
    bindings:
      TransactionComment: "null"
      TransactionType: "\"63\""
      TransactionValue: "Value"
      TransactionOrderNo: "Order:DocumentNo"
      BonusPointAccount: "Entry:BonusPointAccount"
  - id: "CallNode6"
    type: "call"
    ref: "This:PurgeAccountEntries"
  - id: "CallNode7"
    type: "call"
    ref: "This:PurgeTransactions"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString1: "@SellerOrder@"
    bindings:
      String0: "Entry:Reference"
      String1: "null"
      String2: "CurrentChannel:RepositoryDomain:DomainName"
      Concatenated: "OrderRefID"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Order:BonusPointsValue_Total"
  - id: "DecisionNode2"
    type: "decision"
    condition: "BonusPointExpirationTime"
  - id: "DecisionNode3"
    type: "decision"
    condition: "BonusPointAccountEntryLifeTimeExtention"
  - id: "DecisionNode4"
    type: "decision"
    condition: "BonusPointAccountTransactionLifeTime"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "ExpirationDate"
        type: "java.util.Date"
        guaranteed: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "EndNode5"
    type: "end"
    strict: true
  - id: "EndNode6"
    type: "end"
    strict: true
  - id: "EndNode7"
    type: "end"
    strict: true
  - id: "ExecuteObjectsQuery1"
    type: "pipelet"
    ref: "ExecuteObjectsQuery"
    config:
      QueryName: "bonuspoint/GetPendingPointsForActivation_52"
      Datasource: "current ORM connection"
      ParameterName_01: "ChannelDomain"
      ParameterName_02: "LastActivationDate"
    bindings:
      Connection: "null"
      Parameters: "null"
      ParameterValue_01: "CurrentChannel:RepositoryDomain"
      Query: "null"
      SearchResult: "AccountEntriesForActivation"
      ParameterValue_02: "LastActivationDate"
  - id: "ExecuteObjectsQuery2"
    type: "pipelet"
    ref: "ExecuteObjectsQuery"
    config:
      QueryName: "bonuspoint/GetAccountEntriesForPurging_52"
      Datasource: "current ORM connection"
      ParameterName_01: "ChannelDomain"
      ParameterName_02: "LastPurgingDate"
    bindings:
      Connection: "null"
      Parameters: "null"
      ParameterValue_01: "CurrentChannel:RepositoryDomain"
      Query: "null"
      SearchResult: "AccountEntriesForPurging"
      ParameterValue_02: "LastPurgingDate"
  - id: "ExecuteObjectsQuery3"
    type: "pipelet"
    ref: "ExecuteObjectsQuery"
    config:
      QueryName: "bonuspoint/GetTransactionForPurging_52"
      Datasource: "current ORM connection"
      ParameterName_01: "ChannelDomain"
      ParameterName_02: "LastPurgingDate"
    bindings:
      Connection: "null"
      Parameters: "null"
      ParameterValue_01: "CurrentChannel:RepositoryDomain"
      Query: "null"
      SearchResult: "TransactionsForPurging"
      ParameterValue_02: "LastPurgingDate"
  - id: "GetCurrentDate1"
    type: "pipelet"
    ref: "GetCurrentDate"
  - id: "GetCurrentDate2"
    type: "pipelet"
    ref: "GetCurrentDate"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "Integer"
      DefaultPreferenceKey: "BonusPointActivationTime"
    bindings:
      PreferenceDomain: "CurrentChannel:RepositoryDomain"
      PreferenceKey: "null"
      Preference: "null"
      PreferenceDoubleValue: "null"
      PreferenceStringValue: "null"
      PreferenceIntValue: "BonusPointActivationTime"
  - id: "GetDomainPreference2"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "Integer"
      DefaultPreferenceKey: "BonusPointAccountEntryLifeTimeExtention"
    bindings:
      PreferenceDomain: "CurrentChannel:RepositoryDomain"
      PreferenceKey: "null"
      Preference: "null"
      PreferenceDoubleValue: "null"
      PreferenceStringValue: "null"
      PreferenceIntValue: "BonusPointAccountEntryLifeTimeExtention"
  - id: "GetDomainPreference3"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "Integer"
      DefaultPreferenceKey: "BonusPointExpirationTime"
    bindings:
      PreferenceDomain: "CurrentChannel:RepositoryDomain"
      PreferenceKey: "null"
      Preference: "null"
      PreferenceDoubleValue: "null"
      PreferenceStringValue: "null"
      PreferenceIntValue: "BonusPointExpirationTime"
  - id: "GetDomainPreference4"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "Integer"
      DefaultPreferenceKey: "BonusPointAccountTransactionLifeTime"
    bindings:
      PreferenceDomain: "CurrentChannel:RepositoryDomain"
      PreferenceKey: "null"
      Preference: "null"
      PreferenceDoubleValue: "null"
      PreferenceStringValue: "null"
      PreferenceIntValue: "BonusPointAccountTransactionLifeTime"
  - id: "GetOrderByID1"
    type: "pipelet"
    ref: "GetOrderByID"
    bindings:
      OrderID: "null"
      OrderIDs: "null"
      OrderRefIDs: "null"
      Orders: "null"
      OrderRefID: "OrderRefID"
  - id: "GrantRedeemableBonusPoints1"
    type: "pipelet"
    ref: "GrantRedeemableBonusPoints"
    bindings:
      BonusPointAccount: "Entry:BonusPointAccount"
      ExpirationDate: "ExpirationDate"
      Points: "Order:BonusPointsValue_Total"
      BonusPointAccountEntry: "null"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "LoopNode3"
    type: "loop"
  - id: "RemoveAccountTransaction1"
    type: "pipelet"
    ref: "RemoveAccountTransaction"
    bindings:
      AccountTransaction: "Transaction"
  - id: "RemoveBonusPointAccountEntry1"
    type: "pipelet"
    ref: "RemoveBonusPointAccountEntry"
    bindings:
      BonusPointAccountEntry: "Entry"
  - id: "RemoveBonusPointAccountEntry2"
    type: "pipelet"
    ref: "RemoveBonusPointAccountEntry"
    bindings:
      BonusPointAccountEntry: "Entry"

links:
  - from: "GrantRedeemableBonusPoints1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "GetOrderByID1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "GetOrderByID1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "RemoveBonusPointAccountEntry1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "StartNode5"
    via: "next"
    to: "GetCurrentDate2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "GrantRedeemableBonusPoints1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "CalculateDouble3"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "RemoveBonusPointAccountEntry1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "ExecuteObjectsQuery1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "GetDomainPreference3"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "GetCurrentDate1"
    via: "next"
    to: "CalculateDate1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "CallNode5"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "GetDomainPreference3"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "EndNode4"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "CalculateDouble3"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "GetDomainPreference2"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "GetCurrentDate2"
    via: "next"
    to: "GetDomainPreference2"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "CalculateDate2"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "CallNode3"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode3"
    into: "in2"
  - from: "JoinNode3"
    via: "next"
    to: "GetDomainPreference4"
    into: "in"
  - from: "CalculateDate3"
    via: "next"
    to: "ExecuteObjectsQuery3"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "CalculateDate2"
    via: "next"
    to: "ExecuteObjectsQuery2"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode4"
    into: "in2"
  - from: "DecisionNode4"
    via: "yes"
    to: "CalculateDate3"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "GetDomainPreference4"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "ExecuteObjectsQuery2"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "LoopNode2"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "RemoveBonusPointAccountEntry2"
    into: "in"
  - from: "RemoveBonusPointAccountEntry2"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "RemoveBonusPointAccountEntry2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "ExecuteObjectsQuery3"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "CalculateDate1"
    via: "next"
    to: "ExecuteObjectsQuery1"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "LoopNode3"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "LoopNode3"
    via: "do"
    to: "RemoveAccountTransaction1"
    into: "in"
  - from: "RemoveAccountTransaction1"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "GetDomainPreference1"
    via: "next"
    to: "GetCurrentDate1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "GetOrderByID1"
    into: "in"
