flow: "MaintainSearchIndexes"
kind: "process"

entries:
  - id: "StartNode1"
    name: "Rebuild"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode5"
    name: "GetAllSearchIndexes"
    mode: "private"
    strict: true
    inputs:
      []

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "AllSearchIndexesVector"
      Objects: "PipelineResult:PipelineDictionary:SearchIndexes"
      Object: "null"
      OutVector: "AllSearchIndexesVector"
      Iterator: "AllSearchIndexes"
  - id: "CallNode1"
    type: "call"
    ref: "MaintainSearchIndexes-GetAllSearchIndexes"
  - id: "CallNode3"
    type: "call"
    ref: "MaintainSearchIndexes-GetAllSearchIndexes"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "AllSearchIndexes"
        type: "java.util.Iterator"
        guaranteed: false
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "EndNode5"
    type: "end"
    strict: true
  - id: "EndNode6"
    type: "end"
    strict: true
  - id: "EndNode7"
    type: "end"
    strict: true
  - id: "EndNode8"
    type: "end"
    strict: true
  - id: "ExecuteObjectsQuery2"
    type: "pipelet"
    ref: "ExecuteObjectsQuery"
    config:
      QueryName: "channel/GetChannelsByTypeCode"
      Datasource: "current ORM connection"
      ParameterName_01: "TypeCodes"
    bindings:
      Connection: "null"
      Parameters: "null"
      ParameterValue_01: "\"52 42\""
      Query: "null"
      SearchResult: "Channels"
  - id: "ExecutePipeline0"
    type: "pipelet"
    ref: "ExecutePipeline"
    config:
      Asynchronous: false
      PipelineStartNode: "GetIndexes"
      PipelineName: "ProcessSearchIndex"
  - id: "GetApplication0"
    type: "pipelet"
    ref: "GetApplication"
    bindings:
      UrlIdentifier: "CurrentChannel:Id"
      Site: "CurrentChannel:OwningDomain:Site"
  - id: "JoinNode0"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "KeyMapper0"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "CurrentChannel:OwningDomain:Site"
      OutValue_1: "Domain"
  - id: "LoopNode1"
    type: "loop"
  - id: "MaintainSearchIndexes1"
    type: "pipelet"
    ref: "MaintainSearchIndexes"
    config:
      RebuildMode: "FULL_UPDATE_OR_REBUILD"
    bindings:
      SearchIndexes: "AllSearchIndexes"
  - id: "MaintainSearchIndexes3"
    type: "pipelet"
    ref: "MaintainSearchIndexes"
    config:
      RebuildMode: "FULL_REBUILD"
    bindings:
      SearchIndexes: "AllSearchIndexes"
  - id: "RemoveDictionaryValue0"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "PipelineResult"

links:
  - from: "AddObjectToVector1"
    via: "next"
    to: "RemoveDictionaryValue0"
    into: "in"
  - from: "CallNode1"
    via: "ERROR"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "MaintainSearchIndexes3"
    into: "in"
  - from: "CallNode3"
    via: "ERROR"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "MaintainSearchIndexes1"
    into: "in"
  - from: "ExecuteObjectsQuery2"
    via: "error"
    to: "EndNode8"
    into: "in"
  - from: "ExecuteObjectsQuery2"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "ExecutePipeline0"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "ExecutePipeline0"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "GetApplication0"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "GetApplication0"
    via: "next"
    to: "KeyMapper0"
    into: "in"
  - from: "JoinNode0"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "KeyMapper0"
    via: "next"
    to: "ExecutePipeline0"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "GetApplication0"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "MaintainSearchIndexes1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "MaintainSearchIndexes1"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "MaintainSearchIndexes3"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "MaintainSearchIndexes3"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "RemoveDictionaryValue0"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "ExecuteObjectsQuery2"
    into: "in"
