flow: "OrderInjectionService"
kind: "process"

entries:
  - id: "Start1"
    name: "CreateOrder"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "OrderStatus"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessOrder-CreateOrders"
  - id: "Call2"
    type: "call"
    ref: "ProcessOrderRequiredAttributes-CopyReqProductsAttributes"
  - id: "CheckDOrder1"
    type: "pipelet"
    ref: "CheckDOrder"
  - id: "CopyDLineItemAddresses1"
    type: "pipelet"
    ref: "CopyDLineItemAddresses"
    bindings:
      SourceLI: "SourceLineItem"
      TargetLI: "TargetLineItem"
  - id: "CopyDLineItemAddresses2"
    type: "pipelet"
    ref: "CopyDLineItemAddresses"
    bindings:
      SourceLI: "SourceLineItem"
      TargetLI: "TargetLineItem"
  - id: "CopyDOrderAddressesToBasket1"
    type: "pipelet"
    ref: "CopyDOrderAddressesToBasket"
    bindings:
      Basket: "Requisition"
  - id: "CopyDOrderAttributesToBasket1"
    type: "pipelet"
    ref: "CopyDOrderAttributesToBasket"
    bindings:
      Basket: "Requisition"
  - id: "CopyDProductLineItemToBasket1"
    type: "pipelet"
    ref: "CopyDProductLineItemToBasket"
    bindings:
      Basket: "Requisition"
      CreatedPLI: "TargetLineItem"
      SourcePLI: "SourceLineItem"
  - id: "CopyDProductLineItemToBasket2"
    type: "pipelet"
    ref: "CopyDProductLineItemToBasket"
    bindings:
      Basket: "Requisition"
      CreatedPLI: "TargetLineItem"
      SourcePLI: "SourceLineItem"
  - id: "CopyDShippingMethodToBasket1"
    type: "pipelet"
    ref: "CopyDShippingMethodToBasket"
    bindings:
      Basket: "Requisition"
  - id: "CreateBasket2"
    type: "pipelet"
    ref: "CreateBasket"
    config:
      BasketType: "REQUISITION"
    bindings:
      Basket: "Requisition"
      CurrentDomain: "OrganizationDomain"
  - id: "End1"
    type: "end"
  - id: "End2"
    type: "end"
  - id: "GetOrganizationByUser1"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      User: "CurrentUser"
  - id: "Join10"
    type: "join"
  - id: "Join11"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "Requisition:ProductLineItems"
      OutValue_1: "NewProductLineItems"
  - id: "Loop1"
    type: "loop"
  - id: "Loop2"
    type: "loop"
  - id: "RemoveRequisitionFromSession1"
    type: "pipelet"
    ref: "RemoveRequisitionFromSession"
  - id: "RemoveRequisitionFromSession2"
    type: "pipelet"
    ref: "RemoveRequisitionFromSession"
  - id: "SetDOrderStatus1"
    type: "pipelet"
    ref: "SetDOrderStatus"
    config:
      DefaultErrorCode: "PLI1"
      DefaultErrorDescription: "Creating ProductLineItem failed"
    bindings:
      ErrorValue: "SourceLineItem:ProductName"
  - id: "SetDOrderStatus2"
    type: "pipelet"
    ref: "SetDOrderStatus"
    config:
      DefaultErrorCode: "PLI2"
      DefaultErrorDescription: "Creating address for ProductLineItem failed"
    bindings:
      ErrorValue: "SourceLineItem:ProductName"
  - id: "SetDOrderStatus3"
    type: "pipelet"
    ref: "SetDOrderStatus"
    config:
      DefaultErrorCode: "SLI2"
      DefaultErrorDescription: "Creating address for ServiceLineItem failed"
    bindings:
      ErrorValue: "SourceLineItem:Name"
  - id: "SetDOrderStatus4"
    type: "pipelet"
    ref: "SetDOrderStatus"
    config:
      DefaultErrorCode: "SLI1"
      DefaultErrorDescription: "Creating ServiceLineItem failed"
    bindings:
      ErrorValue: "SourceLineItem:Name"
  - id: "SetDOrderStatus5"
    type: "pipelet"
    ref: "SetDOrderStatus"
    config:
      DefaultErrorCode: "Order1"
      DefaultErrorDescription: "Copying addresses failed"
  - id: "SetDOrderStatus6"
    type: "pipelet"
    ref: "SetDOrderStatus"
    config:
      DefaultErrorCode: "Order12"
      DefaultErrorDescription: "Copying order attributes failed"
  - id: "SetDOrderStatus7"
    type: "pipelet"
    ref: "SetDOrderStatus"
    config:
      DefaultErrorCode: "Order3"
      DefaultErrorDescription: "Copying shipping method failed"
  - id: "SetDOrderStatus8"
    type: "pipelet"
    ref: "SetDOrderStatus"
    config:
      DefaultOrderStatus: 3000
  - id: "SetDOrderStatus9"
    type: "pipelet"
    ref: "SetDOrderStatus"
    config:
      DefaultOrderStatus: -1
  - id: "UpdateLineItemStatus1"
    type: "pipelet"
    ref: "UpdateLineItemStatus"
    config:
      StatusGroup: "Requisition"
      StatusID: 3
  - id: "UpdateRequisitionStatus1"
    type: "pipelet"
    ref: "UpdateRequisitionStatus"
    config:
      StatusGroup: "ApprovalStateGroup"
      StatusID: 300
    bindings:
      InputStatusGroup: "not"
      InputStatusID: "not"
  - id: "UpdateRequisitionStatus2"
    type: "pipelet"
    ref: "UpdateRequisitionStatus"
    config:
      StatusGroup: "OrderStateGroup"
      StatusID: 1000
    bindings:
      InputStatusGroup: "not"
      InputStatusID: "not"
  - id: "UpdateRequisitionStatus3"
    type: "pipelet"
    ref: "UpdateRequisitionStatus"
    config:
      StatusGroup: "DeliveryStateGroup"
      StatusID: 10000
    bindings:
      InputStatusGroup: "not"
      InputStatusID: "not"
  - id: "UpdateRequisitionStatus4"
    type: "pipelet"
    ref: "UpdateRequisitionStatus"
    config:
      StatusGroup: "RequisitionStateGroup"
      StatusID: 40
    bindings:
      InputStatusGroup: "not"
      InputStatusID: "not"
  - id: "UpdateRequisitionStatus5"
    type: "pipelet"
    ref: "UpdateRequisitionStatus"
    config:
      StatusGroup: "OrderStateGroup"
      StatusID: 3000
    bindings:
      InputStatusGroup: "not"
      InputStatusID: "not"

links:
  - from: "Start2"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "GetOrganizationByUser1"
    into: "in"
  - from: "GetOrganizationByUser1"
    via: "error"
    to: "Join2"
    into: "in1"
  - from: "CheckDOrder1"
    via: "next"
    to: "CreateBasket2"
    into: "in"
  - from: "UpdateRequisitionStatus1"
    via: "next"
    to: "UpdateRequisitionStatus2"
    into: "in"
  - from: "UpdateRequisitionStatus2"
    via: "next"
    to: "UpdateRequisitionStatus3"
    into: "in"
  - from: "RemoveRequisitionFromSession2"
    via: "next"
    to: "Join11"
    into: "in1"
  - from: "UpdateRequisitionStatus3"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "UpdateLineItemStatus1"
    via: "next"
    to: "UpdateRequisitionStatus4"
    into: "in"
  - from: "UpdateRequisitionStatus4"
    via: "next"
    to: "UpdateRequisitionStatus1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "UpdateRequisitionStatus5"
    into: "in"
  - from: "UpdateRequisitionStatus5"
    via: "next"
    to: "SetDOrderStatus8"
    into: "in"
  - from: "GetOrganizationByUser1"
    via: "next"
    to: "CheckDOrder1"
    into: "in"
  - from: "CheckDOrder1"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "CopyDOrderAddressesToBasket1"
    via: "next"
    to: "CopyDOrderAttributesToBasket1"
    into: "in"
  - from: "CopyDOrderAttributesToBasket1"
    via: "next"
    to: "CopyDShippingMethodToBasket1"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Join7"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Loop1"
    via: "do"
    to: "CopyDProductLineItemToBasket1"
    into: "in"
  - from: "CopyDProductLineItemToBasket1"
    via: "next"
    to: "CopyDLineItemAddresses1"
    into: "in"
  - from: "Loop2"
    via: "do"
    to: "CopyDProductLineItemToBasket2"
    into: "in"
  - from: "CopyDProductLineItemToBasket2"
    via: "next"
    to: "CopyDLineItemAddresses2"
    into: "in"
  - from: "CreateBasket2"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "CopyDShippingMethodToBasket1"
    via: "next"
    to: "UpdateLineItemStatus1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Join11"
    into: "in3"
  - from: "Loop2"
    via: "next"
    to: "CopyDOrderAddressesToBasket1"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "CopyDLineItemAddresses1"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Join5"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "Join8"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "CopyDLineItemAddresses2"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "Join9"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "CopyDProductLineItemToBasket1"
    via: "error"
    to: "SetDOrderStatus1"
    into: "in"
  - from: "CopyDLineItemAddresses1"
    via: "error"
    to: "SetDOrderStatus2"
    into: "in"
  - from: "SetDOrderStatus2"
    via: "next"
    to: "Join5"
    into: "in2"
  - from: "CopyDProductLineItemToBasket2"
    via: "error"
    to: "SetDOrderStatus4"
    into: "in"
  - from: "CopyDLineItemAddresses2"
    via: "error"
    to: "SetDOrderStatus3"
    into: "in"
  - from: "SetDOrderStatus4"
    via: "next"
    to: "Join8"
    into: "in2"
  - from: "SetDOrderStatus3"
    via: "next"
    to: "Join9"
    into: "in2"
  - from: "CopyDOrderAddressesToBasket1"
    via: "error"
    to: "SetDOrderStatus5"
    into: "in"
  - from: "SetDOrderStatus5"
    via: "next"
    to: "Join7"
    into: "in2"
  - from: "CopyDOrderAttributesToBasket1"
    via: "error"
    to: "SetDOrderStatus6"
    into: "in"
  - from: "CopyDShippingMethodToBasket1"
    via: "error"
    to: "SetDOrderStatus7"
    into: "in"
  - from: "SetDOrderStatus6"
    via: "next"
    to: "Join6"
    into: "in2"
  - from: "SetDOrderStatus7"
    via: "next"
    to: "Join3"
    into: "in2"
  - from: "SetDOrderStatus1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Join11"
    via: "next"
    to: "SetDOrderStatus9"
    into: "in"
  - from: "SetDOrderStatus9"
    via: "next"
    to: "Join10"
    into: "in3"
  - from: "SetDOrderStatus8"
    via: "next"
    to: "RemoveRequisitionFromSession1"
    into: "in"
  - from: "RemoveRequisitionFromSession1"
    via: "next"
    to: "Join10"
    into: "in1"
  - from: "Join10"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "RemoveRequisitionFromSession2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Loop2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call2"
    into: "in"
