flow: "ORG_RemoveDomainReferences"
kind: "process"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: false

steps:
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "ExecuteStoredProcedure5"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deleteDepartmentByDomain"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deleteCostCenterByDomain"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deleteAccountByDomain"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deleteBudgetByDomain"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deleteUserDelegateByDomain"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deleteChannelByDomain"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "ToBeRemovedDomainID=string"
      StoredProcedure: "sp_deleteOrganizationByDomain"
  - id: "Text1"
    type: "text"

links:
  - from: "Start1"
    via: "next"
    to: "ExecuteStoredProcedure5"
    into: "in"
  - from: "ExecuteStoredProcedure5"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "Pipelet2"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Pipelet3"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "Pipelet4"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Pipelet5"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "Pipelet6"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "Pipelet1"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "ExecuteStoredProcedure5"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
