flow: "PaymentServiceAssignmentHook"
kind: "process"

entries:
  - id: "StartNode2"
    name: "OnUnassign"
    mode: "private"
    strict: true
    inputs:
      - key: "PaymentServiceAssignmentDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "PaymentServiceID"
        type: "java.lang.String"
        required: true

steps:
  - id: "DecisionNode1"
    type: "decision"
    condition: "Organization:TypeCode"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Organization:TypeCode"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "ExecuteCartridgePipelines2"
    type: "pipelet"
    ref: "ExecuteCartridgePipelines"
    config:
      Asynchronous: false
      PipelinePropertyName: "PaymentServiceAssignmentDeletionHook"
      ProcessReversely: false
  - id: "ExecuteObjectsQuery1"
    type: "pipelet"
    ref: "ExecuteObjectsQuery"
    config:
      Datasource: "default"
      QueryName: "channel/GetAllChannels"
      ParameterName_01: "Domain"
      ParameterName_02: "LocaleInformation"
    bindings:
      ParameterValue_01: "Organization:OrganizationDomain"
      ParameterValue_02: "CurrentRequest:Locale"
      SearchResult: "Repositories"
      CurrentDomain: "Organization:OrganizationDomain:Site"
  - id: "GetOrganizationByDomain1"
    type: "pipelet"
    ref: "GetOrganizationByDomain"
    bindings:
      OrganizationDomain: "PaymentServiceAssignmentDomain"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Repository:RepositoryDomain"
      OutValue_1: "PaymentServiceAssignmentDomain"
  - id: "LoopNode1"
    type: "loop"
  - id: "UnassignPaymentService2"
    type: "pipelet"
    ref: "UnassignPaymentService"
    bindings:
      AssignedDomain: "Repository:RepositoryDomain"

links:
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode2"
    into: "in3"
  - from: "ExecuteObjectsQuery1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "ExecuteCartridgePipelines2"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "StartNode2"
    via: "next"
    to: "GetOrganizationByDomain1"
    into: "in"
  - from: "GetOrganizationByDomain1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "UnassignPaymentService2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "ExecuteCartridgePipelines2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "DecisionNode1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "UnassignPaymentService2"
    into: "in"
  - from: "GetOrganizationByDomain1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "DecisionNode2"
    via: "yes"
    to: "JoinNode2"
    into: "in1"
  - from: "LoopNode1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "ExecuteCartridgePipelines2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "ExecuteObjectsQuery1"
    into: "in"
  - from: "ExecuteObjectsQuery1"
    via: "next"
    to: "LoopNode1"
    into: "in"
