flow: "PreviewLinks"
kind: "process"

entries:
  - id: "StartNode1"
    name: "GetPreviewRepository"
    mode: "private"
    strict: true
    inputs:
      - key: "OrganizationDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode3"
    name: "Preview"
    mode: "private"
    strict: true
    inputs:
      - key: "CallTargetObject"
        type: "java.lang.Object"
        required: true
      - key: "Repository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
      - key: "Parameters"
        type: "java.util.Map<String,String>"
        required: false
      - key: "PreviewContextBO"
        type: "com.intershop.component.preview.capi.context.PreviewContextBO"
        required: true
      - key: "TargetApplicationBO"
        type: "com.intershop.component.application.capi.ApplicationBO"
        required: true
      - key: "ApplicationBO"
        type: "com.intershop.component.application.capi.ApplicationBO"
        required: true
      - key: "CurrentOrganization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true
      - key: "ContentRepositoryUUID"
        type: "java.lang.String"
        required: true

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      OutVector: "PermittedRepositories"
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      Object: "Repository"
      InVector: "PermittedRepositories"
      OutVector: "PermittedRepositories"
  - id: "CallNode51"
    type: "call"
    ref: "ProcessPreviewContext-SetTargetUrl"
    bindings:
      ApplicationBO: "SelectedApplicationBO"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ApplicationAttribute"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ApplicationAttribute:Selected"
  - id: "DecisionNode3"
    type: "decision"
    condition: "ContentSharingChannelPreference"
  - id: "DecisionNode4"
    type: "decision"
    condition: "PermittedRepositories:Size"
  - id: "DecisionNode5"
    type: "decision"
    condition: "RepositoryPermissionMap:KeySet"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "Repository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "GetApplicationBOByID1"
    type: "pipelet"
    ref: "GetApplicationBOByID"
    bindings:
      ApplicationBORepository: "ApplicationBO:getRepository(\"ApplicationBORepository\",Repository:RepositoryDomain:Site:UUID)"
      ApplicationID: "ApplicationAttribute:SelectedValue:ValueObject:UUID"
      ApplicationBO: "SelectedApplicationBO"
  - id: "GetDomainByName1"
    type: "pipelet"
    ref: "GetDomainByName"
    bindings:
      DomainName: "ContentRepositoryDomainName"
      Domain: "ContentRepositoryDomain"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "String"
    bindings:
      PreferenceDomain: "OrganizationDomain"
      PreferenceKey: "\"ContentSharingChannel\""
      Preference: "ContentSharingChannelPreference"
  - id: "GetPermissionsByUser1"
    type: "pipelet"
    ref: "GetPermissionsByUser"
    config:
      Permission_Prefix: "SLD"
    bindings:
      AuthorizationObject: "Repository:RepositoryDomain"
      User: "CurrentUser"
      Organization: "null"
      PermissionMap: "RepositoryPermissionMap"
  - id: "GetPreviewConfigurationAttribute1"
    type: "pipelet"
    ref: "GetPreviewConfigurationAttribute"
    config:
      AttributeSet: "com.intershop.component.preview.capi.configuration.PreviewConfigurationAttributeSet"
      AttributeSetValue: "PreviewApplication"
    bindings:
      PreviewConfigurationAttribute: "ApplicationAttribute"
  - id: "GetRepositories1"
    type: "pipelet"
    ref: "GetRepositories"
    config:
      CustomRepositoryTypeCode: 52
  - id: "GetRepositoryByRepositoryDomain1"
    type: "pipelet"
    ref: "GetRepositoryByRepositoryDomain"
    bindings:
      RepositoryDomain: "ContentRepositoryDomain"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JumpNode7"
    type: "jump"
    ref: "EditView-DirectItemStart"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "PermittedRepositories:First"
      OutValue_1: "Repository"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ContentSharingChannelPreference:StringValue"
      OutValue_1: "ContentRepositoryDomainName"
  - id: "KeyMapper7"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Repository:RepositoryDomain:Site:DomainID"
      OutValue_1: "TargetSiteUUID"
  - id: "LoopNode1"
    type: "loop"

links:
  - from: "AddObjectToVector1"
    via: "next"
    to: "GetRepositories1"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode51"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "GetApplicationBOByID1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "KeyMapper5"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode4"
    via: "no"
    to: "EndNode2"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "KeyMapper1"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode5"
    via: "yes"
    to: "AddObjectToVector2"
    into: "in"
  - from: "GetApplicationBOByID1"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "GetApplicationBOByID1"
    via: "next"
    to: "CallNode51"
    into: "in"
  - from: "GetDomainByName1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetDomainByName1"
    via: "next"
    to: "GetRepositoryByRepositoryDomain1"
    into: "in"
  - from: "GetDomainPreference1"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "GetDomainPreference1"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "GetPermissionsByUser1"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "GetPreviewConfigurationAttribute1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetRepositories1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "GetRepositoryByRepositoryDomain1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetRepositoryByRepositoryDomain1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JumpNode7"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "KeyMapper5"
    via: "next"
    to: "GetDomainByName1"
    into: "in"
  - from: "KeyMapper7"
    via: "next"
    to: "GetPreviewConfigurationAttribute1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "GetPermissionsByUser1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "KeyMapper7"
    into: "in"
