flow: "ProcessUserList_52"
kind: "Process"

entries:
  - id: "StartNode0"
    name: "VerifyCreationDates"
    mode: "private"
    strict: true
    inputs:
      - key: "CreationDateFromDateString"
        type: "java.lang.String"
        required: false
      - key: "CreationDateFromTimeString"
        type: "java.lang.String"
        required: false
      - key: "CreationDateToDateString"
        type: "java.lang.String"
        required: false
      - key: "CreationDateToTimeString"
        type: "java.lang.String"
        required: false

steps:
  - id: "CalculateDate0"
    type: "pipelet"
    ref: "CalculateDate"
    config:
      DefaultDays: 1
    bindings:
      Date: "CreationDateTo"
      CalculatedDate: "CreationDateTo"
  - id: "ConcatenateStrings0"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "CreationDateFromDateString"
      String2: "CreationDateFromTimeString"
      String1: "\" \""
      Concatenated: "CreationDateFromString"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "CreationDateToDateString"
      String1: "\" \""
      String2: "CreationDateToTimeString"
      Concatenated: "CreationDateToString"
  - id: "DecisionNode0"
    type: "decision"
    condition: "CreationDateTo_Time"
  - id: "DecisionNode1"
    type: "decision"
    condition: "CreationDateFrom"
  - id: "DecisionNode2"
    type: "decision"
    condition: "CreationDateTo"
  - id: "DecisionNode3"
    type: "decision"
    condition: "CreationDateToString"
  - id: "DecisionNode4"
    type: "decision"
    condition: "CreationDateFromString"
  - id: "DecisionNode5"
    type: "decision"
    condition: "CreationDateFrom:Time"
  - id: "DecisionNode6"
    type: "decision"
    condition: "CreationDateFromError"
  - id: "EndNode0"
    type: "end"
    strict: true
    outputs:
      - key: "CreationDateFrom"
        type: "java.util.Date"
        guaranteed: false
      - key: "CreationDateTo"
        type: "java.util.Date"
        guaranteed: false
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "CreationDateFromError"
        type: "java.lang.String"
        guaranteed: false
      - key: "CreationDateToError"
        type: "java.lang.String"
        guaranteed: false
      - key: "CreationDateError"
        type: "java.lang.String"
        guaranteed: false
  - id: "JoinNode0"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "SetDictionaryValue0"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "CreationDateError"
      Value: true
  - id: "VerifyDate0"
    type: "pipelet"
    ref: "VerifyDate"
    bindings:
      DateString: "CreationDateToString"
      ErrorCode: "CreationDateToError"
      Date: "CreationDateTo"
  - id: "VerifyDate1"
    type: "pipelet"
    ref: "VerifyDate"
    bindings:
      DateString: "CreationDateFromString"
      ErrorCode: "CreationDateFromError"
      Date: "CreationDateFrom"

links:
  - from: "CalculateDate0"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "ConcatenateStrings0"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode0"
    via: "no"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode0"
    via: "yes"
    to: "CalculateDate0"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode0"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "VerifyDate0"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "JoinNode9"
    into: "in1"
  - from: "DecisionNode4"
    via: "no"
    to: "VerifyDate1"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode5"
    via: "no"
    to: "SetDictionaryValue0"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "JoinNode10"
    into: "in1"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode6"
    via: "yes"
    to: "DecisionNode2"
    into: "in"
  - from: "JoinNode0"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode10"
    via: "next"
    to: "EndNode0"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode9"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "SetDictionaryValue0"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "StartNode0"
    via: "next"
    to: "ConcatenateStrings0"
    into: "in"
  - from: "VerifyDate0"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "VerifyDate0"
    via: "next"
    to: "DecisionNode0"
    into: "in"
  - from: "VerifyDate1"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "VerifyDate1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
