flow: "ProcessReplicationGroupAssignment_32"
kind: "process"

entries:
  - id: "Start1"
    name: "Products"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start14"
    name: "ProductRecycleBin"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start16"
    name: "Labels"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start17"
    name: "Localizations"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "ProductAttributeGroups"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "ProductPrices"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Catalogs"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "Global"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "ImageDefinitions"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "ImageReferences"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddStagingGroupToReplicationTask1"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "Catalog:Domain"
      StagingGroupName: "\"ProductTypes\""
  - id: "AddStagingGroupToReplicationTask11"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "LocalizationDomain"
      StagingGroupName: "\"Domains\""
  - id: "AddStagingGroupToReplicationTask12"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "LocalizationDomain"
      StagingGroupName: "\"Localizations\""
  - id: "AddStagingGroupToReplicationTask15"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "ChannelRepository:Domain"
      StagingGroupName: "\"Products\""
  - id: "AddStagingGroupToReplicationTask19"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "RecycleBin:RepositoryDomain"
      StagingGroupName: "\"Products\""
  - id: "AddStagingGroupToReplicationTask2"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "SystemDomain"
      StagingGroupName: "\"Relations\""
  - id: "AddStagingGroupToReplicationTask23"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "ChannelRepository:Domain"
      StagingGroupName: "\"Prices\""
  - id: "AddStagingGroupToReplicationTask24"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "SystemDomain"
      StagingGroupName: "\"ClassificationCounter\""
  - id: "AddStagingGroupToReplicationTask25"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "ChannelRepository:Domain"
      StagingGroupName: "\"FND_AttributeGroup\""
  - id: "AddStagingGroupToReplicationTask29"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
      StagingGroupName: "\"PRICING_PriceScale\""
  - id: "AddStagingGroupToReplicationTask3"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "ChannelRepository:Domain"
      StagingGroupName: "\"MVC_Catalog\""
  - id: "AddStagingGroupToReplicationTask31"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "RecycleBin:RepositoryDomain"
      StagingGroupName: "\"Prices\""
  - id: "AddStagingGroupToReplicationTask4"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "Catalog:Domain"
      StagingGroupName: "\"Domains\""
  - id: "AddStagingGroupToReplicationTask49"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
      StagingGroupName: "\"FND_SearchIndexes\""
  - id: "AddStagingGroupToReplicationTask5"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "Catalog:Domain"
      StagingGroupName: "\"Categories\""
  - id: "AddStagingGroupToReplicationTask56"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "Catalog:Domain"
      StagingGroupName: "\"SLD_Labels\""
  - id: "AddStagingGroupToReplicationTask6"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "Catalog:Domain"
      StagingGroupName: "\"UnitStatic\""
  - id: "AddStagingGroupToReplicationTask61"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "ChannelRepository:Domain"
      StagingGroupName: "\"FND_ImageDefinitions\""
  - id: "AddStagingGroupToReplicationTask62"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "ChannelRepository:Domain"
      StagingGroupName: "\"ImageSetCategoryAssignments\""
  - id: "AddStagingGroupToReplicationTask63"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "ChannelRepository:Domain"
      StagingGroupName: "\"FND_ImageReferences\""
  - id: "AddStagingGroupToReplicationTask7"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "Catalog:Domain"
      StagingGroupName: "\"Preferences\""
  - id: "AddStagingGroupToReplicationTask8"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "ChannelRepository:Domain"
      StagingGroupName: "\"UnitStatic\""
  - id: "AddStagingGroupToReplicationTask9"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "ChannelRepository:Domain"
      StagingGroupName: "\"SLD_Labels\""
  - id: "Call1"
    type: "call"
    ref: "ProcessReplicationGroupAssignment_32-ProductAttributeGroups"
  - id: "Call18"
    type: "call"
    ref: "ProcessReplicationGroupAssignment_32-ImageDefinitions"
  - id: "Call19"
    type: "call"
    ref: "ProcessReplicationGroupAssignment_32-ImageReferences"
  - id: "Call3"
    type: "call"
    ref: "ProcessReplicationGroupAssignment_32-ProductPrices"
  - id: "Call4"
    type: "call"
    ref: "ProcessReplicationGroupAssignment_32-Catalogs"
  - id: "Call5"
    type: "call"
    ref: "ProcessReplicationGroupAssignment_32-Products"
  - id: "Call6"
    type: "call"
    ref: "ProcessReplicationGroupAssignment_32-Global"
  - id: "Call7"
    type: "call"
    ref: "ProcessReplicationGroupAssignment_32-ProductPrices"
  - id: "Call8"
    type: "call"
    ref: "ProcessReplicationGroupAssignment_32-Localizations"
  - id: "Call9"
    type: "call"
    ref: "ProcessReplicationGroupAssignment_32-Labels"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessReplicationGroupAssignment_32-ProductRecycleBin"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessReplicationGroupAssignment_32-ImageReferences"
  - id: "Decision1"
    type: "decision"
    condition: "ReplicationGroup"
  - id: "Decision15"
    type: "decision"
    condition: "ReplicationGroup"
  - id: "Decision16"
    type: "decision"
    condition: "ReplicationGroup"
  - id: "Decision2"
    type: "decision"
    condition: "ReplicationGroup"
  - id: "Decision3"
    type: "decision"
    condition: "ReplicationGroup"
  - id: "Decision4"
    type: "decision"
    condition: "ReplicationGroup"
  - id: "Decision5"
    type: "decision"
    condition: "Catalog:isProxy"
  - id: "Decision6"
    type: "decision"
    condition: "ReplicationGroup"
  - id: "Decision7"
    type: "decision"
    condition: "ReplicationGroup"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End14"
    type: "end"
    strict: false
  - id: "End16"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "End5"
    type: "end"
    strict: false
  - id: "End7"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "GetCatalogs1"
    type: "pipelet"
    ref: "GetCatalogs"
    config:
      CatalogType: "All"
    bindings:
      OrganizationDomain: "ChannelRepository:Domain"
  - id: "GetCatalogs3"
    type: "pipelet"
    ref: "GetCatalogs"
    config:
      CatalogType: "All"
    bindings:
      OrganizationDomain: "ChannelRepository:Domain"
  - id: "GetDomain1"
    type: "pipelet"
    ref: "GetDomain"
    bindings:
      StagingDomain: "SystemDomain"
      StagingDomainName: "\"system\""
  - id: "GetDomain2"
    type: "pipelet"
    ref: "GetDomain"
    bindings:
      StagingDomainName: "\"system\""
      StagingDomain: "SystemDomain"
  - id: "GetLocalizationDomainsByRepositoryDomain1"
    type: "pipelet"
    ref: "GetLocalizationDomainsByRepositoryDomain"
    bindings:
      RepositoryDomain: "ChannelRepository:Domain"
  - id: "GetRecycleBinByRepository1"
    type: "pipelet"
    ref: "GetRecycleBinByRepository"
    bindings:
      Repository: "CurrentChannel"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Loop1"
    type: "loop"
  - id: "Loop2"
    type: "loop"
  - id: "Loop9"
    type: "loop"
  - id: "LoopNode1"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "ChannelRepository:Domain"
      StagingGroupName: "\"FND_Attachments\""
  - id: "Pipelet2"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      StagingGroupName: "\"PreferenceDefinitions\""
      Domain: "SystemDomain"

links:
  - from: "Start1"
    via: "next"
    to: "AddStagingGroupToReplicationTask15"
    into: "in"
  - from: "Loop2"
    via: "next"
    to: "End5"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "Decision7"
    via: "yes"
    to: "Call1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Join7"
    into: "in2"
  - from: "Decision7"
    via: "no"
    to: "Decision6"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "AddStagingGroupToReplicationTask12"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "Decision1"
    via: "no"
    to: "Decision7"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Decision1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "Start3"
    via: "next"
    to: "AddStagingGroupToReplicationTask23"
    into: "in"
  - from: "AddStagingGroupToReplicationTask11"
    via: "next"
    to: "AddStagingGroupToReplicationTask12"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "AddStagingGroupToReplicationTask25"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "AddStagingGroupToReplicationTask25"
    into: "in"
  - from: "GetLocalizationDomainsByRepositoryDomain1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "AddStagingGroupToReplicationTask11"
    into: "in"
  - from: "Start17"
    via: "next"
    to: "GetLocalizationDomainsByRepositoryDomain1"
    into: "in"
  - from: "AddStagingGroupToReplicationTask24"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "Call5"
    into: "in"
  - from: "AddStagingGroupToReplicationTask23"
    via: "next"
    to: "AddStagingGroupToReplicationTask29"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Decision3"
    into: "in"
  - from: "GetCatalogs1"
    via: "next"
    to: "AddStagingGroupToReplicationTask3"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "End3"
    into: "in"
  - from: "AddStagingGroupToReplicationTask5"
    via: "next"
    to: "AddStagingGroupToReplicationTask1"
    into: "in"
  - from: "AddStagingGroupToReplicationTask1"
    via: "next"
    to: "AddStagingGroupToReplicationTask6"
    into: "in"
  - from: "AddStagingGroupToReplicationTask6"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Loop1"
    via: "do"
    to: "Decision5"
    into: "in"
  - from: "Decision5"
    via: "yes"
    to: "AddStagingGroupToReplicationTask4"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Decision2"
    via: "yes"
    to: "Call4"
    into: "in"
  - from: "Decision5"
    via: "no"
    to: "Join5"
    into: "in3"
  - from: "AddStagingGroupToReplicationTask3"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "AddStagingGroupToReplicationTask4"
    via: "next"
    to: "AddStagingGroupToReplicationTask7"
    into: "in"
  - from: "Loop2"
    via: "do"
    to: "Decision2"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "AddStagingGroupToReplicationTask7"
    via: "next"
    to: "AddStagingGroupToReplicationTask5"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "AddStagingGroupToReplicationTask63"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "GetDomain1"
    into: "in"
  - from: "GetDomain1"
    via: "next"
    to: "AddStagingGroupToReplicationTask2"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "AddStagingGroupToReplicationTask2"
    via: "next"
    to: "End7"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "AddStagingGroupToReplicationTask8"
    via: "next"
    to: "GetDomain2"
    into: "in"
  - from: "GetDomain2"
    via: "next"
    to: "AddStagingGroupToReplicationTask24"
    into: "in"
  - from: "AddStagingGroupToReplicationTask15"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "AddStagingGroupToReplicationTask29"
    via: "next"
    to: "AddStagingGroupToReplicationTask49"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "AddStagingGroupToReplicationTask8"
    into: "in"
  - from: "Start14"
    via: "next"
    to: "GetRecycleBinByRepository1"
    into: "in"
  - from: "AddStagingGroupToReplicationTask19"
    via: "next"
    to: "AddStagingGroupToReplicationTask31"
    into: "in"
  - from: "GetRecycleBinByRepository1"
    via: "next"
    to: "AddStagingGroupToReplicationTask19"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "AddStagingGroupToReplicationTask49"
    via: "next"
    to: "End2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "End4"
    into: "in"
  - from: "Start16"
    via: "next"
    to: "AddStagingGroupToReplicationTask9"
    into: "in"
  - from: "Loop9"
    via: "do"
    to: "AddStagingGroupToReplicationTask56"
    into: "in"
  - from: "AddStagingGroupToReplicationTask56"
    via: "next"
    to: "Loop9"
    into: "loop"
  - from: "Loop9"
    via: "next"
    to: "End16"
    into: "in"
  - from: "AddStagingGroupToReplicationTask31"
    via: "next"
    to: "End14"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Call3"
    into: "in"
  - from: "GetCatalogs3"
    via: "next"
    to: "Loop9"
    into: "in"
  - from: "AddStagingGroupToReplicationTask9"
    via: "next"
    to: "GetCatalogs3"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "Join4"
    into: "in2"
  - from: "Decision4"
    via: "yes"
    to: "Call8"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "Decision15"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "Decision6"
    via: "yes"
    to: "Call9"
    into: "in"
  - from: "Decision6"
    via: "no"
    to: "Decision4"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "Call6"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "GetCatalogs1"
    into: "in"
  - from: "AddStagingGroupToReplicationTask62"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Loop2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "AddStagingGroupToReplicationTask61"
    into: "in"
  - from: "AddStagingGroupToReplicationTask61"
    via: "next"
    to: "AddStagingGroupToReplicationTask62"
    into: "in"
  - from: "AddStagingGroupToReplicationTask63"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "Decision15"
    via: "no"
    to: "Decision16"
    into: "in"
  - from: "Call19"
    via: "next"
    to: "JoinNode8"
    into: "in2"
  - from: "Decision15"
    via: "yes"
    to: "Call18"
    into: "in"
  - from: "Call18"
    via: "next"
    to: "JoinNode7"
    into: "in2"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "Decision16"
    via: "yes"
    to: "Call19"
    into: "in"
  - from: "Decision16"
    via: "no"
    to: "JoinNode1"
    into: "in1"
