flow: "ProcessPayment_52"
kind: "process"

entries:
  - id: "Start1"
    name: "RemoveAllPaymentMethodAssignments"
    mode: "private"
    strict: true
    inputs:
      - key: "PaymentConfiguration"
        type: "com.intershop.beehive.bts.capi.payment.PaymentConfiguration"
        required: true
  - id: "StartNode1"
    name: "AssignPaymentServiceToEveryone"
    mode: "private"
    strict: true
    inputs:
      - key: "ChannelRepository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
      - key: "CurrentChannel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
      - key: "PaymentConfiguration"
        type: "com.intershop.beehive.bts.capi.payment.PaymentConfiguration"
        required: true
  - id: "StartNode3"
    name: "GetPaymentMethodAssignmentType"
    mode: "private"
    strict: true
    inputs:
      - key: "PaymentConfiguration"
        type: "com.intershop.beehive.bts.capi.payment.PaymentConfiguration"
        required: true

steps:
  - id: "CallNode2"
    type: "call"
    ref: "ProcessOrganization_52-GetConsumerOrg"
  - id: "CreatePaymentConfigurationUserGroupAssignment1"
    type: "pipelet"
    ref: "CreatePaymentConfigurationUserGroupAssignment"
  - id: "Decision2"
    type: "decision"
    condition: "PaymentConfiguration:AssignedUserGroups"
  - id: "DecisionNode1"
    type: "decision"
    condition: "UserGroup:ID"
  - id: "DecisionNode3"
    type: "decision"
    condition: "AssignedUserGroup:ID"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Assigned"
  - id: "DetermineUserGroup1"
    type: "pipelet"
    ref: "DetermineUserGroup"
    config:
      Config_UserGroupID: "Everyone"
    bindings:
      CurrentDomain: "Organization:OrganizationDomain"
      UserGroupID: "null"
  - id: "End2"
    type: "end"
    strict: true
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "AssignmentType"
        type: "java.lang.String"
        guaranteed: true
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Loop1"
    type: "loop"
  - id: "Loop3"
    type: "loop"
  - id: "Loop4"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Assigned"
      Value: true
  - id: "Pipelet2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "AssignmentType"
      Value: "AssignmentToSelected"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "AssignmentType"
      Value: "AssignmentToNoOne"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "AssignmentType"
      Value: "AssignmentToAll"
  - id: "RemovePaymentConfigurationUserGroupAssignment1"
    type: "pipelet"
    ref: "RemovePaymentConfigurationUserGroupAssignment"
    bindings:
      UserGroup: "AssignedUserGroup"
  - id: "RemovePaymentConfigurationUserGroupAssignment2"
    type: "pipelet"
    ref: "RemovePaymentConfigurationUserGroupAssignment"
    bindings:
      UserGroup: "AssignedUserGroup"
  - id: "Text1"
    type: "text"
  - id: "TextNode1"
    type: "text"

links:
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet4"
    into: "in"
  - from: "RemovePaymentConfigurationUserGroupAssignment2"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Loop1"
    via: "do"
    to: "RemovePaymentConfigurationUserGroupAssignment2"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "RemovePaymentConfigurationUserGroupAssignment1"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Pipelet3"
    into: "in"
  - from: "DetermineUserGroup1"
    via: "next"
    to: "CreatePaymentConfigurationUserGroupAssignment1"
    into: "in"
  - from: "RemovePaymentConfigurationUserGroupAssignment1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Loop3"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "CreatePaymentConfigurationUserGroupAssignment1"
    via: "next"
    to: "JoinNode8"
    into: "in2"
  - from: "DecisionNode4"
    via: "yes"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "Loop3"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode7"
    into: "in2"
  - from: "DecisionNode3"
    via: "yes"
    to: "Pipelet1"
    into: "in"
  - from: "Loop4"
    via: "do"
    to: "DecisionNode3"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "Loop4"
    into: "loop"
  - from: "Loop4"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "Loop3"
    via: "do"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "DetermineUserGroup1"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "Loop3"
    into: "loop"
  - from: "StartNode3"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "Pipelet3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "Loop4"
    into: "in"
