flow: "ProcessABTestGroupPromotion_52"
kind: "process"

entries:
  - id: "StartNode2"
    name: "RemovePromotion"
    mode: "private"
    strict: false
    inputs:
      - key: "ABTestGroup<com.intershop.component.marketing.capi.abtest.ABTestGroup>"
        type: "com.intershop.component.marketing.capi.abtest.ABTestGroup"
        required: false
  - id: "StartNode3"
    name: "RemoveAllPromotions"
    mode: "private"
    strict: false
    inputs:
      - key: "ABTest<com.intershop.component.marketing.capi.abtest.ABTest>"
        type: "com.intershop.component.marketing.capi.abtest.ABTest"
        required: false
  - id: "StartNode4"
    name: "UpdatePromotion"
    mode: "private"
    strict: false
    inputs:
      - key: "ABTestGroup<com.intershop.component.marketing.capi.rebate.Promotion>"
        type: "com.intershop.component.marketing.capi.abtest.ABTestGroup"
        required: false
  - id: "StartNode5"
    name: "UpdateAllPromotions"
    mode: "private"
    strict: false
    inputs:
      - key: "ABTest<com.intershop.component.marketing.capi.abtest.ABTest>"
        type: "com.intershop.component.marketing.capi.abtest.ABTest"
        required: false

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessABTestGroupPromotion_52-RemovePromotion"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessABTestGroupPromotion_52-UpdatePromotion"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessPromotionContentRelation-UnassignAllContent"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "ABTestGroup:Test:DisplayName"
      String1: "\" - \""
      String2: "ABTestGroup:DisplayName"
      Concatenated: "PromotionName"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ABTestGroup:Promotion"
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "EndNode5"
    type: "end"
    strict: false
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Lead Locale"
    bindings:
      LocaleId: "null"
      Locale: "LeadLocale"
  - id: "JoinNode1"
    type: "join"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "Pipelet27"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "ABTestGroup:Promotion"
      OutValue_1: "Promotion"
  - id: "RemovePromotion1"
    type: "pipelet"
    ref: "RemovePromotion"
    config:
      RemoveOnlyIfNoRebates: false
      RemoveOnlyIfNotEnabled: false
    bindings:
      Promotion: "ABTestGroup:Promotion"
      ERROR_Promotion: "null"
  - id: "UpdatePromotion2"
    type: "pipelet"
    ref: "UpdatePromotion"
    bindings:
      DisplayName: "PromotionName"
      Enabled: "ABTestGroup:Test:isEnabled"
      EndDate: "ABTestGroup:Test:EndDate"
      Locale: "LeadLocale"
      Promotion: "ABTestGroup:Promotion"
      StartDate: "ABTestGroup:Test:StartDate"
      Type: "\"DISCOUNT\""
      Description: "null"

links:
  - from: "LoopNode1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "RemovePromotion1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "UpdatePromotion2"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "CallNode2"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "UpdatePromotion2"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet27"
    into: "in"
  - from: "Pipelet27"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "RemovePromotion1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetLocale1"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
