flow: "ProcessBatchJob"
kind: "process"

entries:
  - id: "Start1"
    name: "StartInternal"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "GetPageableSequence"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      - key: "ProcessOwningDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
      - key: "ProcessExecutionDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
      - key: "ProcessDescription"
        type: "java.lang.String"
        required: false
      - key: "JobName"
        type: "java.lang.String"
        required: false
      - key: "JobPipelineName"
        type: "java.lang.String"
        required: false
      - key: "JobPipelineStartNode"
        type: "java.lang.String"
        required: false
      - key: "ProcessApplication"
        type: "com.intershop.beehive.core.capi.domain.Application"
        required: false
  - id: "Start5"
    name: "Error"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "DetermineProcessApplication"
    mode: "private"
    strict: true
    inputs:
      - key: "ProcessApplication"
        type: "com.intershop.beehive.core.capi.domain.Application"
        required: false
      - key: "ProcessExecutionDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
      - key: "ProcessOwningDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
      - key: "CurrentApplication"
        type: "com.intershop.beehive.core.capi.domain.Application"
        required: true

steps:
  - id: "Call1"
    type: "call"
  - id: "Call2"
    type: "call"
  - id: "Call3"
    type: "call"
  - id: "Call4"
    type: "call"
    ref: "ProcessBatchJob-GetPageableSequence"
  - id: "Call5"
    type: "call"
  - id: "Call6"
    type: "call"
  - id: "Call7"
    type: "call"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessBatchJob-DetermineProcessApplication"
  - id: "CopyFormValuesIntoJobConfiguration1"
    type: "pipelet"
    ref: "CopyFormValuesIntoJobConfiguration"
  - id: "CreateJobConfiguration1"
    type: "pipelet"
    ref: "CreateJobConfiguration"
    bindings:
      Domain: "ProcessOwningDomain"
      Application: "ProcessApplication"
  - id: "CreatePageableSequence1"
    type: "pipelet"
    ref: "CreatePageableSequence"
    bindings:
      PageableIterator: "Objects"
      PageableSequence: "Objects"
  - id: "CreatePageableSequence2"
    type: "pipelet"
    ref: "CreatePageableSequence"
    bindings:
      PageableIterator: "Objects"
      PageableSequence: "Objects"
  - id: "Decision1"
    type: "decision"
    condition: "InitPipeline"
  - id: "Decision2"
    type: "decision"
    condition: "PostPipeline"
  - id: "Decision3"
    type: "decision"
    condition: "ErrorPipeline"
  - id: "Decision4"
    type: "decision"
    condition: "ProcessExecutionDomain"
  - id: "Decision5"
    type: "decision"
    condition: "ProcessExecutionDomain"
  - id: "Decision6"
    type: "decision"
    condition: "DeterminePageablePipeline"
  - id: "Decision7"
    type: "decision"
    condition: "PostPipeline"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ProcessApplication"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ProcessApplication"
  - id: "DecisionNode3"
    type: "decision"
    condition: "CurrentApplication:Site:UUID"
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "End5"
    type: "end"
    strict: false
  - id: "End6"
    type: "end"
    strict: false
  - id: "End9"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ProcessApplication"
        type: "com.intershop.beehive.core.capi.domain.Application"
        guaranteed: false
  - id: "ExecuteJob1"
    type: "pipelet"
    ref: "ExecuteJob"
  - id: "GetJobConfiguration1"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Objects"
  - id: "Join1"
    type: "join"
  - id: "Join10"
    type: "join"
  - id: "Join11"
    type: "join"
  - id: "Join12"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "ProcessBatchJob-Error"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "JobConfiguration:JobCreatorUserID"
      OutValue_1: "CheckedUserID"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentApplication"
      OutValue_1: "ProcessApplication"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ProcessExecutionDomain:Site:DefaultApplication"
      OutValue_1: "ProcessApplication"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ProcessOwningDomain:Site:DefaultApplication"
      OutValue_1: "ProcessApplication"
  - id: "LogMessage1"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Level: "Error"
    bindings:
      MessageText: "\"Error getting objects to be processed by Job {} (UUID: '{}') in domain {} (UUID: '{}')\""
      MessageParam0: "JobConfiguration:Name"
      MessageParam1: "JobConfiguration:UUID"
      MessageParam2: "JobConfiguration:Domain:DomainName"
      MessageParam3: "JobConfiguration:DomainID"
  - id: "LogMessage2"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Level: "Error"
    bindings:
      MessageText: "\"Error during initialization of Job {} (UUID: '{}') in domain {} (UUID: '{}')\""
      MessageParam0: "JobConfiguration:Name"
      MessageParam1: "JobConfiguration:UUID"
      MessageParam2: "JobConfiguration:Domain:DomainName"
      MessageParam3: "JobConfiguration:DomainID"
  - id: "LogMessage3"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Level: "Error"
    bindings:
      MessageText: "\"Error during post processing of Job {} (UUID: '{}') in domain {} (UUID: '{}')\""
      MessageParam0: "JobConfiguration:Name"
      MessageParam1: "JobConfiguration:UUID"
      MessageParam2: "JobConfiguration:Domain:DomainName"
      MessageParam3: "JobConfiguration:DomainID"
  - id: "LogMessage4"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Level: "Error"
    bindings:
      MessageText: "\"Error during processing of Job {} (UUID: '{}') in domain {} (UUID: '{}')\""
      MessageParam0: "JobConfiguration:Name"
      MessageParam1: "JobConfiguration:UUID"
      MessageParam2: "JobConfiguration:Domain:DomainName"
      MessageParam3: "JobConfiguration:DomainID"
  - id: "MonitorPageable1"
    type: "pipelet"
    ref: "MonitorPageable"
    bindings:
      PageableIterator: "Objects"
      ProgressMonitor: "JobConfiguration:CurrentProcess"
  - id: "SwitchToNextPage1"
    type: "pipelet"
    ref: "SwitchToNextPage"
    bindings:
      PageableIterator: "Objects"
  - id: "UpdateCustomAttributes2"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "JobConfigurationUUID"
      Attribute_1_Type: "String"
      Attribute_2_Name: "JobCreatorUserID"
      Attribute_2_Type: "String"
    bindings:
      Attribute_1_Value: "JobConfiguration:UUID"
      ExtensibleObject: "JobConfiguration"
      Attribute_2_Value: "CurrentUser:ID"
  - id: "UpdateCustomAttributes4"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "JobExecutionDomainID"
      Attribute_1_Type: "String"
    bindings:
      Attribute_1_Value: "ProcessExecutionDomain:UUID"
      ExtensibleObject: "JobConfiguration"
  - id: "UpdateJobConfiguration1"
    type: "pipelet"
    ref: "UpdateJobConfiguration"
    config:
      EnableJob: false
      Interval: 1
      Name: "Process"
      PipelineName: "ProcessBatchJob"
      PipelineStartNode: "Start"
      Unit: "Years"
    bindings:
      JobDescription: "ProcessDescription"
      JobDate: "null"
      JobDomain: "null"
      JobDomainName: "null"
      JobEnable: "null"
      JobInterval: "null"
      JobJavaDate: "null"
      JobName: "JobName"
      JobUnit: "null"
      JobUUID: "null"
      JobServerGroup: "null"

links:
  - from: "MonitorPageable1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Call1"
    via: "Error"
    to: "LogMessage4"
    into: "in"
  - from: "LogMessage3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "LogMessage2"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "Call3"
    via: "next"
    to: "Join6"
    into: "in3"
  - from: "Call3"
    via: "Error"
    to: "LogMessage3"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Call3"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "Join6"
    into: "in1"
  - from: "CreatePageableSequence2"
    via: "next"
    to: "End4"
    into: "in"
  - from: "Call4"
    via: "Error"
    to: "Join10"
    into: "in1"
  - from: "Call1"
    via: "next"
    to: "SwitchToNextPage1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "CreatePageableSequence2"
    into: "in"
  - from: "CreateJobConfiguration1"
    via: "next"
    to: "UpdateJobConfiguration1"
    into: "in"
  - from: "UpdateJobConfiguration1"
    via: "next"
    to: "CopyFormValuesIntoJobConfiguration1"
    into: "in"
  - from: "CopyFormValuesIntoJobConfiguration1"
    via: "next"
    to: "UpdateCustomAttributes2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "Decision5"
    into: "in"
  - from: "CreateJobConfiguration1"
    via: "error"
    to: "Join7"
    into: "in1"
  - from: "UpdateJobConfiguration1"
    via: "error"
    to: "Join7"
    into: "in2"
  - from: "Join7"
    via: "next"
    to: "Join11"
    into: "in1"
  - from: "Join11"
    via: "next"
    to: "End6"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "MonitorPageable1"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "End3"
    into: "in"
  - from: "ExecuteJob1"
    via: "next"
    to: "End5"
    into: "in"
  - from: "ExecuteJob1"
    via: "error"
    to: "Join11"
    into: "in2"
  - from: "KeyMapper4"
    via: "next"
    to: "JoinNode8"
    into: "in3"
  - from: "UpdateCustomAttributes2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Decision4"
    via: "yes"
    to: "UpdateCustomAttributes4"
    into: "in"
  - from: "UpdateCustomAttributes4"
    via: "next"
    to: "Join12"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode5"
    into: "in2"
  - from: "Start1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "GetJobConfiguration1"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "Decision7"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "JoinNode6"
    into: "in2"
  - from: "KeyMapper3"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "Join12"
    via: "next"
    to: "ExecuteJob1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "Decision3"
    via: "yes"
    to: "Call5"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Decision3"
    via: "no"
    to: "Join8"
    into: "in3"
  - from: "Decision6"
    via: "no"
    to: "Call4"
    into: "in"
  - from: "Decision6"
    via: "yes"
    to: "Call6"
    into: "in"
  - from: "SwitchToNextPage1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Call4"
    via: "next"
    to: "Join9"
    into: "in3"
  - from: "CreatePageableSequence1"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "Call6"
    via: "next"
    to: "CreatePageableSequence1"
    into: "in"
  - from: "Join9"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Call6"
    via: "Error"
    to: "Join10"
    into: "in2"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "error"
    to: "Join10"
    into: "in3"
  - from: "JoinNode2"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "LogMessage1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "Decision1"
    via: "no"
    to: "Call2"
    into: "in"
  - from: "SwitchToNextPage1"
    via: "error"
    to: "Decision2"
    into: "in"
  - from: "Decision7"
    via: "yes"
    to: "Call7"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "End9"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Decision6"
    into: "in"
  - from: "Decision7"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "Join10"
    via: "next"
    to: "LogMessage1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "LogMessage4"
    via: "next"
    to: "JoinNode4"
    into: "in2"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "Decision1"
    via: "yes"
    to: "Join2"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "Decision4"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "Join12"
    into: "in3"
  - from: "Decision5"
    via: "no"
    to: "KeyMapper4"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CreateJobConfiguration1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Decision5"
    via: "yes"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "KeyMapper2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Join2"
    into: "in3"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "DecisionNode3"
    via: "no"
    to: "KeyMapper3"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode9"
    into: "in3"
  - from: "Call2"
    via: "Error"
    to: "LogMessage2"
    into: "in"
