flow: "ProcessPageletEntryPointLock"
kind: "process"

entries:
  - id: "StartNode1"
    name: "Check"
    mode: "private"
    strict: true
    inputs:
      - key: "PageletEntryPoint"
        type: "com.intershop.component.pmc.capi.pagelet.ConfigurationParameterCtnr"
        required: true
      - key: "User"
        type: "com.intershop.beehive.core.capi.user.User"
        required: true
      - key: "PreferenceDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "LockingDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode2"
    name: "GetLockPreference"
    mode: "private"
    strict: true
    inputs:
      - key: "PreferenceDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode3"
    name: "Lock"
    mode: "private"
    strict: true
    inputs:
      - key: "PageletEntryPoint"
        type: "com.intershop.component.pmc.capi.pagelet.ConfigurationParameterCtnr"
        required: false
      - key: "PreferenceDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "User"
        type: "com.intershop.beehive.core.capi.user.User"
        required: true
      - key: "ProcessName"
        type: "java.lang.String"
        required: false
      - key: "LockingDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode4"
    name: "Unlock"
    mode: "private"
    strict: true
    inputs:
      - key: "PageletEntryPoint"
        type: "com.intershop.component.pmc.capi.pagelet.ConfigurationParameterCtnr"
        required: false
      - key: "User"
        type: "com.intershop.beehive.core.capi.user.User"
        required: true
      - key: "LockingDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
  - id: "StartNode5"
    name: "CheckUnlocked"
    mode: "private"
    strict: true
    inputs:
      - key: "PageletEntryPoint"
        type: "com.intershop.beehive.core.capi.domain.PersistentObject"
        required: true
      - key: "CheckedUserID"
        type: "java.lang.String"
        required: false
      - key: "LockingDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
  - id: "StartNode6"
    name: "Lookup"
    mode: "private"
    strict: true
    inputs:
      - key: "PageletEntryPoint"
        type: "com.intershop.component.pmc.capi.pagelet.ConfigurationParameterCtnr"
        required: false
      - key: "User"
        type: "com.intershop.beehive.core.capi.user.User"
        required: true
      - key: "PreferenceDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "LockingDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessPageletEntryPointLock-GetLockPreference"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessPageletEntryPointLock-Lookup"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessPageletEntryPointLock-GetLockPreference"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessPageletEntryPointLock-GetLockPreference"
    bindings:
      PageletEntryPointLockLifetime: "null"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessPageletEntryPointLock-Lock"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PageletEntryPoint"
  - id: "DecisionNode10"
    type: "decision"
    condition: "PageletEntryPointLockLifetime"
  - id: "DecisionNode11"
    type: "decision"
    condition: "PageletEntryPointLockLifetime"
  - id: "DecisionNode12"
    type: "decision"
    condition: "PageletEntryPointLockedForMe"
  - id: "DecisionNode13"
    type: "decision"
    condition: "PageletEntryPoint"
  - id: "DecisionNode14"
    type: "decision"
    condition: "PageletEntryPoint"
  - id: "DecisionNode15"
    type: "decision"
    condition: "PageletEntryPoint"
  - id: "DecisionNode19"
    type: "decision"
    condition: "PageletEntryPointLockedForOther"
  - id: "DecisionNode2"
    type: "decision"
    condition: "CheckedUserID"
  - id: "DecisionNode3"
    type: "decision"
    condition: "PageletEntryPointLockLifetime"
  - id: "DecisionNode4"
    type: "decision"
    condition: "PageletEntryPointLockOwner:ID"
  - id: "DecisionNode5"
    type: "decision"
    condition: "PageletEntryPointLockLifetime"
  - id: "DecisionNode6"
    type: "decision"
    condition: "PageletEntryPointLockOwner"
  - id: "DecisionNode7"
    type: "decision"
    condition: "PageletEntryPointLockLifetime"
  - id: "DecisionNode8"
    type: "decision"
    condition: "PageletEntryPointLockLifetime"
  - id: "DecisionNode9"
    type: "decision"
    condition: "CheckedUserID"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode10"
    type: "end"
    strict: true
  - id: "EndNode11"
    type: "end"
    strict: true
    outputs:
      - key: "PageletEntryPointLockLifetime"
        type: "java.lang.Integer"
        guaranteed: true
      - key: "PageletEntryPointLocking"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode12"
    type: "end"
    strict: true
  - id: "EndNode13"
    type: "end"
    strict: true
    outputs:
      - key: "PageletEntryPointLockCreationDate"
        type: "java.util.Date"
        guaranteed: false
      - key: "PageletEntryPointLockExpirationDate"
        type: "java.util.Date"
        guaranteed: false
      - key: "PageletEntryPointLockLifetime"
        type: "java.lang.Integer"
        guaranteed: false
      - key: "PageletEntryPointLockOwner"
        type: "com.intershop.beehive.core.capi.user.User"
        guaranteed: false
      - key: "Resource"
        type: "com.intershop.beehive.core.capi.locking.Resource"
        guaranteed: false
      - key: "PageletEntryPointLockedForMe"
        type: "java.lang.String"
        guaranteed: false
      - key: "PageletEntryPointLocking"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode14"
    type: "end"
    strict: true
  - id: "EndNode15"
    type: "end"
    strict: true
  - id: "EndNode17"
    type: "end"
    strict: true
  - id: "EndNode18"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "PageletEntryPointLockCreationDate"
        type: "java.util.Date"
        guaranteed: false
      - key: "PageletEntryPointLockExpirationDate"
        type: "java.util.Date"
        guaranteed: false
      - key: "PageletEntryPointLockLifetime"
        type: "java.lang.Integer"
        guaranteed: false
      - key: "PageletEntryPointLockOwner"
        type: "com.intershop.beehive.core.capi.user.User"
        guaranteed: false
      - key: "Resource"
        type: "com.intershop.beehive.core.capi.locking.Resource"
        guaranteed: false
      - key: "PageletEntryPointLockedForMe"
        type: "java.lang.String"
        guaranteed: false
      - key: "Process"
        type: "com.intershop.beehive.core.capi.locking.Process"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "PageletEntryPointLockCreationDate"
        type: "java.util.Date"
        guaranteed: false
      - key: "PageletEntryPointLockExpirationDate"
        type: "java.util.Date"
        guaranteed: false
      - key: "PageletEntryPointLockLifetime"
        type: "java.lang.Integer"
        guaranteed: false
      - key: "PageletEntryPointLockOwner"
        type: "com.intershop.beehive.core.capi.user.User"
        guaranteed: false
      - key: "Resource"
        type: "com.intershop.beehive.core.capi.locking.Resource"
        guaranteed: false
      - key: "Process"
        type: "com.intershop.beehive.core.capi.locking.Process"
        guaranteed: false
      - key: "PageletEntryPointLockLost"
        type: "java.lang.String"
        guaranteed: false
      - key: "PageletEntryPointLockedForOther"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "PageletEntryPointLocking"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "PageletEntryPointLockCreationDate"
        type: "java.util.Date"
        guaranteed: false
      - key: "PageletEntryPointLockExpirationDate"
        type: "java.util.Date"
        guaranteed: false
      - key: "PageletEntryPointLockLifetime"
        type: "java.lang.Integer"
        guaranteed: false
      - key: "PageletEntryPointLockOwner"
        type: "com.intershop.beehive.core.capi.user.User"
        guaranteed: false
      - key: "Resource"
        type: "com.intershop.beehive.core.capi.locking.Resource"
        guaranteed: false
      - key: "PageletEntryPointLockedForOther"
        type: "java.lang.String"
        guaranteed: false
      - key: "PageletEntryPointLocking"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "Process"
        type: "com.intershop.beehive.core.capi.locking.Process"
        guaranteed: true
  - id: "EndNode7"
    type: "end"
    strict: true
  - id: "EndNode8"
    type: "end"
    strict: true
    outputs:
      - key: "PageletEntryPointLocking"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode9"
    type: "end"
    strict: true
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode15"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"(Integer)1800\""
      OutValue_1: "PageletEntryPointLockLifetime"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "PageletEntryPointLockLost"
      ValueType: "Dictionary Value"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "PageletEntryPointLockedForOther"
      ValueType: "Dictionary Value"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "PageletEntryPointLocking"
      ValueType: "Dictionary Value"
      Value: true
  - id: "Pipelet12"
    type: "pipelet"
    ref: "LookupInstanceResource"
    bindings:
      PersistentObject: "PageletEntryPoint"
      Lifetime: "PageletEntryPointLockLifetime"
  - id: "Pipelet13"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "PageletEntryPointLocking"
      ValueType: "Dictionary Value"
      Value: false
  - id: "Pipelet3"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "PageletLockTimeout"
      Type: "Integer"
    bindings:
      PreferenceIntValue: "PageletEntryPointLockLifetime"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "AcquireInstanceResource"
    config:
      ProcessDescription: "Pagelet Entry Point locked for editing."
      ProcessName: "PageletEntryPoint Editing"
    bindings:
      CurrentDomain: "LockingDomain"
      Lifetime: "PageletEntryPointLockLifetime"
      PersistentObject: "PageletEntryPoint"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "LookupInstanceResource"
    bindings:
      PersistentObject: "PageletEntryPoint"
      CreationDate: "PageletEntryPointLockCreationDate"
      ExpirationDate: "PageletEntryPointLockExpirationDate"
      Lifetime: "PageletEntryPointLockLifetime"
      Owner: "PageletEntryPointLockOwner"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "ReleaseInstanceResource"
    bindings:
      PersistentObject: "PageletEntryPoint"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "AcquireInstanceResource"
    config:
      ProcessDescription: "PageletEntryPoint is locked for editing."
      ProcessName: "PageletEntryPoint Editing"
    bindings:
      CurrentDomain: "LockingDomain"
      PersistentObject: "PageletEntryPoint"
      Lifetime: "PageletEntryPointLockLifetime"
  - id: "Pipelet9"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "PageletEntryPointLockedForMe"
      ValueType: "Dictionary Value"

links:
  - from: "Pipelet6"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode7"
    via: "yes"
    to: "DecisionNode2"
    into: "in"
  - from: "Pipelet10"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "DecisionNode11"
    via: "no"
    to: "Pipelet13"
    into: "in"
  - from: "JoinNode13"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode10"
    via: "yes"
    to: "DecisionNode11"
    into: "in"
  - from: "DecisionNode9"
    via: "yes"
    to: "JoinNode7"
    into: "in3"
  - from: "CallNode5"
    via: "next"
    to: "EndNode18"
    into: "in"
  - from: "Pipelet4"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "Pipelet9"
    via: "next"
    to: "EndNode13"
    into: "in"
  - from: "DecisionNode13"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "Pipelet11"
    via: "next"
    to: "EndNode11"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "DecisionNode4"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "Pipelet11"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode11"
    into: "in2"
  - from: "DecisionNode7"
    via: "no"
    to: "JoinNode8"
    into: "in2"
  - from: "DecisionNode13"
    via: "yes"
    to: "Pipelet6"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode6"
    into: "in1"
  - from: "Pipelet7"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode10"
    into: "in"
  - from: "CallNode3"
    via: "LOCKING_DISABLED"
    to: "EndNode14"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet7"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "EndNode9"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "DecisionNode3"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "DecisionNode19"
    via: "yes"
    to: "JoinNode15"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode9"
    into: "in3"
  - from: "DecisionNode15"
    via: "no"
    to: "EndNode15"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "DecisionNode9"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode6"
    into: "in2"
  - from: "Pipelet12"
    via: "next"
    to: "DecisionNode8"
    into: "in"
  - from: "Pipelet3"
    via: "error"
    to: "JoinNode10"
    into: "in2"
  - from: "DecisionNode8"
    via: "yes"
    to: "DecisionNode7"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "Pipelet9"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "DecisionNode10"
    into: "in"
  - from: "DecisionNode12"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode10"
    via: "no"
    to: "JoinNode10"
    into: "in1"
  - from: "CallNode5"
    via: "ERROR"
    to: "JoinNode15"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "JoinNode7"
    into: "in1"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode15"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "DecisionNode19"
    via: "no"
    to: "CallNode5"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "Pipelet10"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode4"
    into: "in2"
  - from: "CallNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Pipelet13"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "DecisionNode9"
    via: "no"
    to: "JoinNode5"
    into: "in2"
  - from: "StartNode5"
    via: "next"
    to: "DecisionNode14"
    into: "in"
  - from: "DecisionNode12"
    via: "yes"
    to: "Pipelet4"
    into: "in"
  - from: "DecisionNode11"
    via: "yes"
    to: "JoinNode9"
    into: "in1"
  - from: "DecisionNode14"
    via: "no"
    to: "JoinNode13"
    into: "in2"
  - from: "StartNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode14"
    via: "yes"
    to: "Pipelet12"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "DecisionNode6"
    into: "in"
  - from: "DecisionNode15"
    via: "yes"
    to: "Pipelet5"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DecisionNode13"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "DecisionNode15"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "JoinNode11"
    via: "next"
    to: "EndNode17"
    into: "in"
  - from: "DecisionNode8"
    via: "no"
    to: "JoinNode13"
    into: "in1"
  - from: "Pipelet7"
    via: "error"
    to: "EndNode12"
    into: "in"
  - from: "Pipelet6"
    via: "error"
    to: "EndNode1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "DecisionNode12"
    into: "in"
  - from: "CallNode1"
    via: "LOCKING_DISABLED"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "DecisionNode19"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "KeyMapper2"
    into: "in"
