flow: "ProcessRebateServiceLineItems"
kind: "process"

entries:
  - id: "StartNode6"
    name: "PrepareBasketRebatesView"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "DecisionNode2"
    type: "decision"
    condition: "ServiceLineItem:RuleActionType"
  - id: "DecisionNode5"
    type: "decision"
    condition: "ServiceLineItem:RuleActionType"
  - id: "DecisionNode9"
    type: "decision"
    condition: "ServiceLineItem:RuleActionType"
  - id: "EndNode6"
    type: "end"
  - id: "GetProductByProductRef1"
    type: "pipelet"
    ref: "GetProductByProductRef"
    bindings:
      ProductRef: "null"
      ProductRefID: "ServiceLineItem:RuleActionBonusProductRef"
      ProductRefIDs: "null"
      ProductRefs: "null"
      Products: "null"
      ProductsHash: "null"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "LoopNode7"
    type: "loop"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      InVector: "BonusItemsServiceLineItems"
      Object: "ServiceLineItem"
      Objects: "null"
      OutVector: "BonusItemsServiceLineItems"
      Iterator: "null"
  - id: "Pipelet18"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      InVector: "OrderDiscountServiceLineItems"
      Object: "ServiceLineItem"
      Objects: "null"
      OutVector: "OrderDiscountServiceLineItems"
      Iterator: "null"
  - id: "Pipelet22"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "ItemRebateServiceNameSplitter:getEnd(ServiceLineItem:Name)"
  - id: "Pipelet23"
    type: "pipelet"
    ref: "CreateStringSplitter"
    config:
      Mode: "First Occurrence"
      Separator: "ItemRebate-"
    bindings:
      Splitter: "ItemRebateServiceNameSplitter"
  - id: "Pipelet24"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "null"
      Key: "null"
      Value: "null"
      Keys: "null"
      OutMap: "PLI2SLIsMap"
      Values: "null"
  - id: "Pipelet25"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "ServiceLineItem:ProductLineItemUUID"
  - id: "Pipelet26"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      InVector: "PLI2SLIsMap:get(ServiceLineItem:ProductLineItemUUID)"
      Object: "ServiceLineItem"
      Objects: "null"
      Iterator: "null"
      OutVector: "Values"
  - id: "Pipelet27"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "PLI2SLIsMap"
      Key: "ServiceLineItem:ProductLineItemUUID"
      Value: "Values"
      Keys: "null"
      OutMap: "PLI2SLIsMap"
      Values: "null"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      InVector: "null"
      Object: "null"
      Objects: "null"
      OutVector: "FreeShippingServiceLineItems"
      Iterator: "null"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ProductRef2ProductMap"
      Key: "ServiceLineItem:RuleActionBonusProductRef"
      Value: "Product"
      Keys: "null"
      OutMap: "ProductRef2ProductMap"
      Values: "null"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      InVector: "null"
      Object: "null"
      Objects: "null"
      OutVector: "OrderDiscountServiceLineItems"
      Iterator: "null"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      InVector: "null"
      Object: "null"
      Objects: "null"
      OutVector: "BonusItemsServiceLineItems"
      Iterator: "null"
  - id: "Pipelet9"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      InVector: "FreeShippingServiceLineItems"
      Object: "ServiceLineItem"
      Objects: "null"
      OutVector: "FreeShippingServiceLineItems"
      Iterator: "null"
  - id: "SortIteratorByComparator2"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingAttribute: "Position"
    bindings:
      Iterator: "CurrentBasket:ServiceLineItems"
      SortingAttribute: "null"
      SortingOrder: "null"
      SortedIterator: "CurrentBasketServiceLineItems"
  - id: "TextNode5"
    type: "text"

links:
  - from: "Pipelet23"
    via: "next"
    to: "SortIteratorByComparator2"
    into: "in"
  - from: "Pipelet25"
    via: "next"
    to: "Pipelet26"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "Pipelet7"
    via: "next"
    to: "Pipelet24"
    into: "in"
  - from: "SortIteratorByComparator2"
    via: "next"
    to: "LoopNode7"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "DecisionNode2"
    into: "in"
  - from: "GetProductByProductRef1"
    via: "error"
    to: "JoinNode12"
    into: "in1"
  - from: "Pipelet10"
    via: "next"
    to: "GetProductByProductRef1"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "DecisionNode9"
    via: "no"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode11"
    into: "in3"
  - from: "GetProductByProductRef1"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "Pipelet10"
    into: "in"
  - from: "DecisionNode9"
    via: "yes"
    to: "Pipelet18"
    into: "in"
  - from: "Pipelet25"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode7"
    into: "in3"
  - from: "Pipelet18"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "LoopNode7"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "LoopNode7"
    via: "do"
    to: "Pipelet22"
    into: "in"
  - from: "Pipelet24"
    via: "next"
    to: "Pipelet23"
    into: "in"
  - from: "Pipelet22"
    via: "next"
    to: "Pipelet25"
    into: "in"
  - from: "Pipelet26"
    via: "next"
    to: "Pipelet27"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "Pipelet27"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "LoopNode7"
    into: "loop"
  - from: "Pipelet22"
    via: "error"
    to: "DecisionNode9"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet9"
    into: "in"
  - from: "Pipelet9"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "JoinNode12"
    into: "in3"
  - from: "Pipelet6"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode12"
    via: "next"
    to: "JoinNode8"
    into: "in3"
