flow: "ProcessSearchIndexConfiguration"
kind: "process"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "UpdatePreferences"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessSearchIndexFeature-GetSearchIndexFeatures"
    bindings:
      Domain: "RepositoryDomain"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessSearchIndexFeature-GetEnabledFeatureIDs"
    bindings:
      Domain: "RepositoryDomain"
  - id: "Decision1"
    type: "decision"
    condition: "Record:Integer"
  - id: "Decision2"
    type: "decision"
    condition: "Record:Double"
  - id: "Decision3"
    type: "decision"
    condition: "Record:String"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PreferenceName"
  - id: "DecisionNode2"
    type: "decision"
    condition: "PreferenceName"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "Integer"
      DefaultPreferenceKey: "BrowseBySearchCategoryLevel"
    bindings:
      PreferenceDomain: "RepositoryDomain:Site"
      PreferenceKey: "\"BrowseBySearchCategoryLevel\""
      PreferenceIntValue: "BrowseBySearchCategoryLevel"
  - id: "GetDomainPreferenceNamesByPreferenceGroup1"
    type: "pipelet"
    ref: "GetDomainPreferenceNamesByPreferenceGroup"
    bindings:
      PreferenceDomain: "PreferenceDomain"
      PreferenceGroup: "\"SearchIndexPreferences\""
  - id: "GetFormRecord1"
    type: "pipelet"
    ref: "GetFormRecord"
    bindings:
      FormRecord: "Record"
      RecordID: "PreferenceName"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"(Integer)-1\""
      OutValue_1: "BrowseBySearchCategoryLevel"
  - id: "Loop1"
    type: "loop"
  - id: "SetDomainPreference3"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      Type: "Double"
    bindings:
      PreferenceDomain: "PreferenceDomain"
      PreferenceDoubleValue: "DoubleValue"
      PreferenceIntValue: "null"
      PreferenceKey: "PreferenceName"
      PreferenceStringValue: "null"
      PreferenceValue: "null"
  - id: "SetDomainPreference4"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      Type: "Integer"
    bindings:
      PreferenceDomain: "PreferenceDomain"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "IntValue"
      PreferenceKey: "PreferenceName"
      PreferenceStringValue: "null"
      PreferenceValue: "null"
  - id: "SetDomainPreference5"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      Type: "String"
      DefaultPreferenceValue: false
    bindings:
      PreferenceDomain: "PreferenceDomain"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceKey: "PreferenceName"
      PreferenceStringValue: "Record:String"
      PreferenceValue: "null"
  - id: "VerifyDouble1"
    type: "pipelet"
    ref: "VerifyDouble"
    bindings:
      LocalizedString: "Record:Double"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    config:
      MaxValue: 2147483647
      MinValue: -2147483648
    bindings:
      IntegerObject: "IntValue"
      LocalizedString: "Record:Integer"

links:
  - from: "Decision3"
    via: "yes"
    to: "SetDomainPreference5"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "GetDomainPreference1"
    via: "error"
    to: "KeyMapper1"
    into: "in"
  - from: "GetDomainPreference1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "GetDomainPreferenceNamesByPreferenceGroup1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "JoinNode4"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join2"
    into: "in3"
  - from: "StartNode3"
    via: "next"
    to: "GetDomainPreferenceNamesByPreferenceGroup1"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "VerifyDouble1"
    into: "in"
  - from: "SetDomainPreference3"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Decision1"
    via: "no"
    to: "Decision2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetDomainPreference4"
    into: "in"
  - from: "SetDomainPreference4"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "GetFormRecord1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Join6"
    into: "in1"
  - from: "VerifyDouble1"
    via: "next"
    to: "SetDomainPreference3"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode4"
    into: "in2"
  - from: "Decision2"
    via: "no"
    to: "Decision3"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Join6"
    into: "in2"
  - from: "SetDomainPreference5"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "VerifyDouble1"
    via: "error"
    to: "Join3"
    into: "in3"
  - from: "DecisionNode2"
    via: "no"
    to: "GetFormRecord1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "CallNode1"
    into: "in"
