flow: "ProcessPaging"
kind: "process"

entries:
  - id: "Start1"
    name: "PreparePage"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "SetPageNumber"
    mode: "private"
    strict: true
    inputs:
      - key: "PageNumber"
        type: "java.lang.String"
        required: false
      - key: "PageLocator"
        type: "com.intershop.component.foundation.capi.paging.PageLocator"
        required: false
      - key: "Pageable"
        type: "com.intershop.beehive.core.capi.paging.PageableIterator"
        required: false
  - id: "StartNode2"
    name: "SetPageSize"
    mode: "private"
    strict: true
    inputs:
      - key: "PageSize"
        type: "java.lang.String"
        required: false
      - key: "Pageable"
        type: "com.intershop.beehive.core.capi.paging.PageableIterator"
        required: false
  - id: "StartNode3"
    name: "GetPageLocatorPageable"
    mode: "private"
    strict: true
    inputs:
      - key: "PageLocatorName"
        type: "java.lang.String"
        required: false

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessPaging-SetPageNumber"
  - id: "Decision2"
    type: "decision"
    condition: "PageSize"
  - id: "Decision3"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision4"
    type: "decision"
    condition: "PageLocator"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "Pageable"
        type: "com.intershop.beehive.core.capi.paging.PageableIterator"
        guaranteed: false
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "Pageable"
        type: "com.intershop.beehive.core.capi.paging.PageableIterator"
        guaranteed: false
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "PageLocator"
        type: "com.intershop.component.foundation.capi.paging.PageLocator"
        guaranteed: false
      - key: "Pageable"
        type: "com.intershop.beehive.core.capi.paging.PageableIterator"
        guaranteed: false
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      RestorePageLocatorDictionary: "True"
  - id: "GetPageLocator3"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      RestorePageLocatorDictionary: "False"
      UsePageLocatorHistory: false
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      PageableID: "PageLocator:PageableID"
  - id: "GetPageable3"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      PageableID: "PageLocator:PageableID"
  - id: "Join1"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "Jump1"
    type: "jump"
  - id: "SetPage3"
    type: "pipelet"
    ref: "SetPage"
  - id: "SetPage4"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
  - id: "UpdatePageSize2"
    type: "pipelet"
    ref: "UpdatePageSize"
    bindings:
      PageSize: "PageSizeInteger"
      PageableIterator: "Pageable"
  - id: "VerifyInteger2"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageSizeInteger"
      LocalizedString: "PageSize"
  - id: "VerifyInteger3"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"

links:
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "GetPageable1"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "Join3"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "UpdatePageSize2"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "GetPageLocator1"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "Decision3"
    via: "no"
    to: "Decision4"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "VerifyInteger3"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "Join8"
    into: "in3"
  - from: "SetPage3"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "SetPage4"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "VerifyInteger3"
    via: "next"
    to: "SetPage3"
    into: "in"
  - from: "VerifyInteger3"
    via: "error"
    to: "Join9"
    into: "in3"
  - from: "Decision4"
    via: "yes"
    to: "SetPage4"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "Join9"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "GetPageLocator3"
    via: "error"
    to: "JoinNode14"
    into: "in2"
  - from: "GetPageable3"
    via: "error"
    to: "JoinNode14"
    into: "in1"
  - from: "GetPageLocator3"
    via: "next"
    to: "GetPageable3"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetPageLocator3"
    into: "in"
  - from: "GetPageable3"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "JoinNode14"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join7"
    into: "in1"
  - from: "VerifyInteger2"
    via: "error"
    to: "Join7"
    into: "in2"
  - from: "Decision2"
    via: "yes"
    to: "VerifyInteger2"
    into: "in"
  - from: "VerifyInteger2"
    via: "next"
    to: "UpdatePageSize2"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
