flow: "ProcessReplicationTask"
kind: "process"

entries:
  - id: "Start1"
    name: "Publish"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Discard"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Remove"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Create"
    mode: "private"
    strict: true
    inputs:
      - key: "Description"
        type: "java.lang.String"
        required: false
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "DueTime"
        type: "java.util.Date"
        required: false
      - key: "ID"
        type: "java.lang.String"
        required: true
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: false
      - key: "Requester"
        type: "com.intershop.beehive.core.capi.user.User"
        required: false
      - key: "StartTime"
        type: "java.util.Date"
        required: false
      - key: "State"
        type: "java.lang.String"
        required: false
  - id: "StartNode1"
    name: "CreateAndAssign"
    mode: "private"
    strict: true
    inputs:
      - key: "OrganizationID"
        type: "java.lang.String"
        required: true
      - key: "ChannelID"
        type: "java.lang.String"
        required: false
      - key: "TaskDescription"
        type: "java.lang.String"
        required: false
      - key: "RequesterLoginName"
        type: "java.lang.String"
        required: false
      - key: "ReplicationGroups"
        type: "java.util.Collection"
        required: true
      - key: "TaskID"
        type: "java.lang.String"
        required: true
      - key: "ReplicationProcess"
        type: "com.intershop.beehive.core.capi.replication.ReplicationProcess"
        required: true
  - id: "StartNode2"
    name: "Error"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode3"
    name: "Assign"
    mode: "private"
    strict: true
    inputs:
      - key: "ReplicationTask"
        type: "com.intershop.beehive.core.capi.replication.ReplicationTask"
        required: true

steps:
  - id: "AddReplicationTaskToReplicationProcess2"
    type: "pipelet"
    ref: "AddReplicationTaskToReplicationProcess"
  - id: "Call1"
    type: "call"
    ref: "ProcessReplicationTask-Create"
  - id: "CallNode1"
    type: "call"
  - id: "CallNode2"
    type: "call"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      Concatenated: "PageCachePipeline"
      String1: "CurrentChannel:TypeCode"
      String0: "\"ProcessReplicationPageCache_\""
      String2: "\"-Start\""
  - id: "ConcatenateStrings3"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      Concatenated: "GroupAssignmentPipeline"
      String1: "CurrentChannel:TypeCode"
      String0: "\"ProcessReplicationGroupAssignment_\""
      String2: "\"-Start\""
  - id: "CreateStringSplitter1"
    type: "pipelet"
    ref: "CreateStringSplitter"
    config:
      Mode: "First Occurrence"
      Separator: "-"
  - id: "Decision1"
    type: "decision"
    condition: "ReplicationTask:ReplicationGroups"
  - id: "Decision2"
    type: "decision"
    condition: "CurrentDate:Time"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ReplicationTask:State"
  - id: "DecisionNode10"
    type: "decision"
    condition: "RequesterLoginName"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ReplicationTask:State"
  - id: "DecisionNode3"
    type: "decision"
    condition: "ReplicationTask:State"
  - id: "DecisionNode4"
    type: "decision"
    condition: "ReplicationTask:State"
  - id: "DecisionNode5"
    type: "decision"
    condition: "ReplicationTask:State"
  - id: "DecisionNode6"
    type: "decision"
    condition: "ReplicationTask:State"
  - id: "DecisionNode7"
    type: "decision"
    condition: "ReplicationTask:State"
  - id: "DecisionNode8"
    type: "decision"
    condition: "ChannelID"
  - id: "DecisionNode9"
    type: "decision"
    condition: "ReplicationProcess"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: true
  - id: "End4"
    type: "end"
    strict: false
  - id: "End5"
    type: "end"
    strict: false
  - id: "End6"
    type: "end"
    strict: true
    outputs:
      - key: "ReplicationTask"
        type: "com.intershop.beehive.core.capi.replication.ReplicationTask"
        guaranteed: true
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ReplicationTask"
        type: "com.intershop.beehive.core.capi.replication.ReplicationTask"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "GetCurrentDate1"
    type: "pipelet"
    ref: "GetCurrentDate"
  - id: "GetCurrentDate2"
    type: "pipelet"
    ref: "GetCurrentDate"
    bindings:
      CurrentDate: "StartTime"
  - id: "GetOrganizationByName1"
    type: "pipelet"
    ref: "GetOrganizationByName"
    bindings:
      Name: "OrganizationID"
      OrganizationDomain: "null"
      Organization: "CurrentOrganization"
  - id: "GetOrganizationByName2"
    type: "pipelet"
    ref: "GetOrganizationByName"
    bindings:
      Name: "ReplicationTask:Domain:DomainName"
      Organization: "CurrentOrganization"
  - id: "GetOrganizationByName3"
    type: "pipelet"
    ref: "GetOrganizationByName"
    bindings:
      Name: "Splitter:Begin(ReplicationTask:Domain:DomainName)"
      Organization: "CurrentOrganization"
  - id: "GetRepositoryByID1"
    type: "pipelet"
    ref: "GetRepositoryByID"
    bindings:
      Repository: "CurrentChannel"
      Domain: "CurrentOrganization:OrganizationDomain"
      RepositoryID: "ChannelID"
  - id: "GetRepositoryByID2"
    type: "pipelet"
    ref: "GetRepositoryByID"
    bindings:
      Repository: "CurrentChannel"
      Domain: "CurrentOrganization:Domain"
      RepositoryID: "Splitter:End(ReplicationTask:Domain:DomainName)"
  - id: "GetUserByLogin1"
    type: "pipelet"
    ref: "GetUserByLogin"
    config:
      CheckPassword: "FALSE"
    bindings:
      Domain: "CurrentOrganization:Domain"
      Login: "RequesterLoginName"
      Password: "null"
      User: "Requester"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "LoopNode3"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetReplicationTaskByUUID"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentOrganization:OrganizationDomain"
      OutValue_1: "Domain"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentChannel:RepositoryDomain"
      OutValue_1: "Domain"
  - id: "Pipelet12"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "TaskID"
      InValue_3: "TaskDescription"
      OutValue_1: "ID"
      OutValue_3: "Description"
      InValue_2: "CurrentOrganization"
      OutValue_2: "Organization"
      InValue_4: "\"WAITING\""
      OutValue_4: "State"
  - id: "Pipelet13"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_2: "\"ProcessReplicationGroupAssignment-Start\""
      OutValue_2: "GroupAssignmentPipeline"
      InValue_3: "\"ProcessReplicationPageCache-Start\""
      OutValue_3: "PageCachePipeline"
      InValue_1: "CurrentOrganization"
      OutValue_1: "Organization"
      InValue_4: "ReplicationTask:ReplicationGroups"
      OutValue_4: "ReplicationGroups"
  - id: "Pipelet14"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentChannel:RepositoryDomain"
      OutValue_1: "Domain"
      InValue_2: "ReplicationTask:ReplicationGroups"
      OutValue_2: "ReplicationGroups"
      InValue_3: "CurrentChannel"
      OutValue_3: "ChannelRepository"
      InValue_4: "CurrentOrganization"
      OutValue_4: "Organization"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "UpdateReplicationTask"
    bindings:
      Description: "null"
      DueTime: "null"
      Locale: "null"
      Requester: "null"
      StartTime: "null"
      State: "\"PENDING\""
  - id: "Pipelet3"
    type: "pipelet"
    ref: "UpdateReplicationTask"
    bindings:
      Description: "null"
      DueTime: "null"
      Locale: "null"
      Requester: "null"
      StartTime: "null"
      State: "\"CANCELED\""
  - id: "Pipelet4"
    type: "pipelet"
    ref: "GetReplicationTaskByUUID"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "GetReplicationTaskByUUID"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "RemoveReplicationTask"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "UpdateReplicationTask"
    config:
      SetDueTimeNull: true
    bindings:
      State: "null"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "CreateReplicationTask"
  - id: "Pipelet9"
    type: "pipelet"
    ref: "UpdateReplicationTask"
  - id: "RemoveStagingGroupsFromReplicationTask1"
    type: "pipelet"
    ref: "RemoveStagingGroupsFromReplicationTask"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorReplicationGroups"
      Value: "Missing"
      ValueType: "Dictionary Value"
  - id: "UpdateCustomAttribute1"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    config:
      DefaultAttributeName: "ReplicationGroups"
      DefaultAttributeType: "MultipleString"
    bindings:
      AttributeName: "null"
      AttributeType: "null"
      AttributeValue: "ReplicationGroups"
      ExtensibleObject: "ReplicationTask"
      LocaleInformation: "null"
  - id: "UpdateReplicationTask1"
    type: "pipelet"
    ref: "UpdateReplicationTask"
    bindings:
      Description: "null"
      DueTime: "null"
      Locale: "null"
      Requester: "null"
      StartTime: "null"
      State: "\"WAITING\""

links:
  - from: "Decision1"
    via: "yes"
    to: "GetCurrentDate1"
    into: "in"
  - from: "LoopNode3"
    via: "next"
    to: "End5"
    into: "in"
  - from: "Pipelet8"
    via: "error"
    to: "End3"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "Pipelet4"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "Join8"
    into: "in1"
  - from: "DecisionNode4"
    via: "yes"
    to: "Join8"
    into: "in3"
  - from: "Join8"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet4"
    via: "error"
    to: "Join7"
    into: "in1"
  - from: "DecisionNode4"
    via: "no"
    to: "Join7"
    into: "in2"
  - from: "Start5"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Join7"
    via: "next"
    to: "Join6"
    into: "in3"
  - from: "Join6"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "DecisionNode3"
    via: "no"
    to: "DecisionNode7"
    into: "in"
  - from: "Pipelet5"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "DecisionNode6"
    via: "yes"
    to: "JoinNode2"
    into: "in2"
  - from: "DecisionNode3"
    via: "yes"
    to: "Join4"
    into: "in1"
  - from: "Pipelet9"
    via: "next"
    to: "End6"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "Pipelet7"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Start4"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet7"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "Join3"
    into: "in3"
  - from: "Join3"
    via: "next"
    to: "End4"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Join2"
    into: "in3"
  - from: "Join2"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "DecisionNode1"
    via: "no"
    to: "Join1"
    into: "in2"
  - from: "DecisionNode1"
    via: "yes"
    to: "Decision1"
    into: "in"
  - from: "GetCurrentDate1"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "UpdateReplicationTask1"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "Join9"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Decision1"
    via: "no"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Join9"
    into: "in3"
  - from: "DecisionNode6"
    via: "no"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "Pipelet6"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "Join4"
    into: "in1"
  - from: "Decision2"
    via: "yes"
    to: "UpdateReplicationTask1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "Pipelet8"
    via: "next"
    to: "Pipelet9"
    into: "in"
  - from: "Pipelet10"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "UpdateCustomAttribute1"
    via: "next"
    to: "DecisionNode9"
    into: "in"
  - from: "DecisionNode8"
    via: "yes"
    to: "GetRepositoryByID1"
    into: "in"
  - from: "GetRepositoryByID1"
    via: "next"
    to: "Pipelet11"
    into: "in"
  - from: "LoopNode3"
    via: "do"
    to: "Pipelet5"
    into: "in"
  - from: "Pipelet11"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "GetOrganizationByName1"
    into: "in"
  - from: "GetOrganizationByName2"
    via: "next"
    to: "Pipelet13"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "UpdateCustomAttribute1"
    into: "in"
  - from: "DecisionNode9"
    via: "yes"
    to: "AddReplicationTaskToReplicationProcess2"
    into: "in"
  - from: "GetOrganizationByName1"
    via: "next"
    to: "DecisionNode8"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "RemoveStagingGroupsFromReplicationTask1"
    into: "in"
  - from: "RemoveStagingGroupsFromReplicationTask1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "DecisionNode10"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "DecisionNode8"
    via: "no"
    to: "Pipelet10"
    into: "in"
  - from: "DecisionNode9"
    via: "no"
    to: "JoinNode4"
    into: "in2"
  - from: "GetUserByLogin1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "GetOrganizationByName3"
    via: "next"
    to: "GetRepositoryByID2"
    into: "in"
  - from: "GetCurrentDate2"
    via: "next"
    to: "Pipelet12"
    into: "in"
  - from: "AddReplicationTaskToReplicationProcess2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Pipelet12"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "DecisionNode10"
    via: "no"
    to: "JoinNode6"
    into: "in2"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "ConcatenateStrings3"
    via: "next"
    to: "Pipelet14"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "ConcatenateStrings3"
    into: "in"
  - from: "Pipelet14"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "Pipelet13"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode10"
    via: "yes"
    to: "GetUserByLogin1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "GetRepositoryByID2"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "GetOrganizationByName2"
    via: "error"
    to: "CreateStringSplitter1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetOrganizationByName2"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "GetCurrentDate2"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "CreateStringSplitter1"
    via: "next"
    to: "GetOrganizationByName3"
    into: "in"
