flow: "ProcessApprovalCustomized"
kind: "process"

entries:
  - id: "Start1"
    name: "PreProcessStartApproval"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "AWFCompletion"
    mode: "private"
    strict: false
    inputs:
      - key: "WorkflowActivity"
        type: "com.intershop.beehive.core.capi.workflow.WorkflowActivity"
        required: false
  - id: "Start3"
    name: "MakeStaticAddresses"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "CreateApprovalObject"
    mode: "private"
    strict: false
    inputs:
      - key: "Requisition"
        type: "com.intershop.beehive.bts.capi.orderprocess.basket.Basket"
        required: false
      - key: "ApprovalCompound"
        type: "com.intershop.component.approval.capi.ApprovalCompoundObject"
        required: false

steps:
  - id: "CreateApprovalPipelineActions1"
    type: "pipelet"
    ref: "CreateApprovalPipelineActions"
    config:
      OnApprovePipeline: "RequisitionApproveRejectActions"
      OnApprovePipeline_StartNode: "OnApprove"
      OnRejectPipeline: "RequisitionApproveRejectActions"
      OnRejectPipeline_StartNode: "OnReject"
    bindings:
      PipelineDomain: "Requisition:Domain:Site"
  - id: "CreateRequisitionAWFStrategy1"
    type: "pipelet"
    ref: "CreateRequisitionAWFStrategy"
    bindings:
      BuyerDepartment: "Department"
  - id: "CreateRequsisitionAWFApprovalObject1"
    type: "pipelet"
    ref: "CreateRequsisitionAWFApprovalObject"
    config:
      ApprovalDetailPipelineName: "ViewRequisitionApprovalTaskDetails"
      ApprovalDetailPipelineNode: "Start"
      NotificationTemplate: "RequisitionAWFTaskMail"
      SubjectTemplate: "RequisitionDescription"
      TimerPipelineName: "ProcessApproval"
      TimerPipelineNode: "Recalculate"
    bindings:
      Requisition: "Requisition"
  - id: "Decision8"
    type: "decision"
    condition: "CurrentDelegator"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Requisition:DelegatorBusinessPartnerNo"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "ExchangeSessionObject3"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "Delegation"
    bindings:
      LoadObject: "CurrentDelegator"
  - id: "FreezeRequisitionAWFStrategy1"
    type: "pipelet"
    ref: "FreezeRequisitionAWFStrategy"
  - id: "GetApprovalObjects1"
    type: "pipelet"
    ref: "GetApprovalObjects"
    bindings:
      CurrentActivity: "WorkflowActivity"
  - id: "GetDepartment1"
    type: "pipelet"
    ref: "GetDepartment"
    config:
      Source: "PipelineDictionary"
    bindings:
      DepartmentUUID: "Requisition:DepartmentUUID"
  - id: "GetLineItemsFromApprovalObject1"
    type: "pipelet"
    ref: "GetLineItemsFromApprovalObject"
    bindings:
      ProductLineItem: "CompletedProductLineItem"
      ProductLineItems: "CompletedProductLineItems"
      Requisition: "CompletedRequisition"
  - id: "GetUserByBusinessPartnerNo1"
    type: "pipelet"
    ref: "GetUserByBusinessPartnerNo"
    bindings:
      BusinessPartnerNo: "Requisition:DelegatorBusinessPartnerNo"
      Domain: "Requisition:Domain"
      User: "CurrentDelegator"
  - id: "Join1"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "CurrentUser"
      OutValue_1: "CurrentDelegator"
  - id: "MakeStaticAddress1"
    type: "pipelet"
    ref: "MakeStaticAddress"
    config:
      IsInvoiceToAddress: true
      IsShipFromAddress: false
      IsShipToAddress: true
    bindings:
      LineItemCtnr: "Requisition"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "Delegation"
    bindings:
      SaveObject: "CurrentDelegator"
  - id: "RemoveOwnedRequisitionAWFDefinitions1"
    type: "pipelet"
    ref: "RemoveOwnedRequisitionAWFDefinitions"
    bindings:
      AWFOwner: "CompletedRequisition"
  - id: "Text1"
    type: "text"
  - id: "Text3"
    type: "text"

links:
  - from: "FreezeRequisitionAWFStrategy1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Start3"
    via: "next"
    to: "MakeStaticAddress1"
    into: "in"
  - from: "MakeStaticAddress1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "RemoveOwnedRequisitionAWFDefinitions1"
    via: "next"
    to: "End3"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "GetApprovalObjects1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "GetUserByBusinessPartnerNo1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "CreateApprovalPipelineActions1"
    into: "in"
  - from: "GetUserByBusinessPartnerNo1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "Pipelet3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CreateRequsisitionAWFApprovalObject1"
    via: "next"
    to: "End4"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "KeyMapper1"
    into: "in"
  - from: "FreezeRequisitionAWFStrategy1"
    via: "error"
    to: "Join1"
    into: "in3"
  - from: "ExchangeSessionObject3"
    via: "next"
    to: "Decision8"
    into: "in"
  - from: "Decision8"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Decision8"
    via: "yes"
    to: "DecisionNode2"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "ExchangeSessionObject3"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "FreezeRequisitionAWFStrategy1"
    into: "in"
  - from: "CreateRequisitionAWFStrategy1"
    via: "next"
    to: "CreateRequsisitionAWFApprovalObject1"
    into: "in"
  - from: "GetDepartment1"
    via: "next"
    to: "CreateRequisitionAWFStrategy1"
    into: "in"
  - from: "CreateApprovalPipelineActions1"
    via: "next"
    to: "GetDepartment1"
    into: "in"
  - from: "GetApprovalObjects1"
    via: "next"
    to: "GetLineItemsFromApprovalObject1"
    into: "in"
  - from: "GetLineItemsFromApprovalObject1"
    via: "next"
    to: "RemoveOwnedRequisitionAWFDefinitions1"
    into: "in"
