flow: "ProcessPageletAssignmentProperties"
kind: "process"

entries:
  - id: "StartNode1"
    name: "Validate"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode47"
    type: "call"
    ref: "ProcessDate-VerifyPeriod"
    bindings:
      ValidFrom_Day: "AssignmentValidFrom_Day"
      ValidFrom_Time: "AssignmentValidFrom_Time"
      ValidTo_Day: "AssignmentValidTo_Day"
      ValidTo_Time: "AssignmentValidTo_Time"
      PeriodFlag: "AssignmentFlag"
      ValidFrom: "AssignmentFrom"
      ValidTo: "AssignmentTo"
      ErrorPeriodIncorrect: "AssignmentPeriodIncorrect"
      ErrorValidFromIncorrect: "AssignmentFromIncorrect"
      ErrorValidToIncorrect: "AssignmentToIncorrect"
  - id: "DecisionNode1"
    type: "decision"
    condition: "AssignmentPosition"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "VerifyInteger2"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      LocalizedString: "AssignmentPosition"
      ErrorCode: "AssignmentPositionInvalid"

links:
  - from: "VerifyInteger2"
    via: "next"
    to: "JoinNode13"
    into: "in1"
  - from: "CallNode47"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "VerifyInteger2"
    via: "error"
    to: "JoinNode1"
    into: "in3"
  - from: "JoinNode13"
    via: "next"
    to: "CallNode47"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "VerifyInteger2"
    into: "in"
  - from: "CallNode47"
    via: "ERROR"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode13"
    into: "in2"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
