flow: "ProcessProductConfigurationOptionSelection"
kind: "process"

entries:
  - id: "StartNode1"
    name: "Create"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductConfigurationBO"
        type: "com.intershop.component.productconfiguration.capi.configuration.AbstractProductConfigurationBO"
        required: true
      - key: "ProductConfigurationOptionBO"
        type: "com.intershop.component.productconfiguration.capi.set.ProductConfigurationOptionBO"
        required: true
  - id: "StartNode2"
    name: "Remove"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductConfigurationBO"
        type: "com.intershop.component.productconfiguration.capi.configuration.AbstractProductConfigurationBO"
        required: true
      - key: "ProductConfigurationOptionSelectionBO"
        type: "com.intershop.component.productconfiguration.capi.configuration.AbstractProductConfigurationOptionSelectionBO"
        required: true
  - id: "StartNode3"
    name: "Update"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductConfigurationOptionSelectionBO"
        type: "com.intershop.component.productconfiguration.capi.configuration.AbstractProductConfigurationOptionSelectionBO"
        required: true
      - key: "SelectedQuantity"
        type: "java.math.BigDecimal"
        required: false
      - key: "Value"
        type: "java.lang.Object"
        required: false
  - id: "StartNode4"
    name: "CreateForValue"
    mode: "private"
    strict: true
    inputs:
      - key: "Value"
        type: "java.lang.String"
        required: true
      - key: "Customization"
        type: "com.intershop.component.productconfiguration.capi.configuration.AbstractProductConfigurationBO"
        required: true
      - key: "Option"
        type: "com.intershop.component.productconfiguration.capi.set.ProductConfigurationOptionBO"
        required: false
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode5"
    name: "DetermineOptionSelectionValue"
    mode: "private"
    strict: true
    inputs:
      - key: "Option"
        type: "com.intershop.component.productconfiguration.capi.set.ProductConfigurationOptionBO"
        required: true
      - key: "Value"
        type: "java.lang.String"
        required: false

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessProductConfigurationOptionSelection-DetermineOptionSelectionValue"
    bindings:
      Value: "Value"
      Option: "Option"
  - id: "CreateProductConfigurationOptionSelection1"
    type: "pipelet"
    ref: "CreateProductConfigurationOptionSelection"
  - id: "CreateProductConfigurationOptionSelection2"
    type: "pipelet"
    ref: "CreateProductConfigurationOptionSelection"
    bindings:
      ProductConfigurationBO: "Customization"
      ProductConfigurationOptionBO: "Option"
      ProductConfigurationOptionSelectionBO: "OptionSelection"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Value"
  - id: "DecisionNode12"
    type: "decision"
    condition: "Value"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Value"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Option:Values"
  - id: "DecisionNode5"
    type: "decision"
    condition: "Value"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ProductConfigurationOptionSelectionBO"
        type: "com.intershop.component.productconfiguration.capi.configuration.AbstractProductConfigurationOptionSelectionBO"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "ProductConfigurationOptionSelectionBO"
        type: "com.intershop.component.productconfiguration.capi.configuration.AbstractProductConfigurationOptionSelectionBO"
        guaranteed: true
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "OptionSelection"
        type: "com.intershop.component.productconfiguration.capi.configuration.AbstractProductConfigurationOptionSelectionBO"
        guaranteed: false
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "Value"
        type: "java.lang.String"
        guaranteed: false
      - key: "ObjValue"
        type: "java.lang.Object"
        guaranteed: false
      - key: "CustomizationValue"
        type: "com.intershop.component.productconfiguration.capi.set.ProductConfigurationValueBO"
        guaranteed: false
  - id: "EndNode7"
    type: "end"
    strict: true
  - id: "EndNode8"
    type: "end"
    strict: true
    outputs:
      - key: "ERROR_UPDATE"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode9"
    type: "end"
    strict: true
    outputs:
      - key: "ERROR_UPDATE"
        type: "java.lang.String"
        guaranteed: true
  - id: "GetProductConfigurationValueByID2"
    type: "pipelet"
    ref: "GetProductConfigurationValueByID"
    bindings:
      ID: "Value"
      ProductConfigurationOption: "Option"
      ProductConfigurationValue: "CustomizationValue"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CustomizationValue:Value"
      OutValue_1: "ObjValue"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "Value"
      RemoveFormValues: true
  - id: "RemoveProductConfigurationOptionSelection1"
    type: "pipelet"
    ref: "RemoveProductConfigurationOptionSelection"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_UPDATE"
      Value: "Invalid valid for option"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_UPDATE"
      Value: "OptionSelection could not be created"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_UPDATE"
      Value: "Option value is not a number"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_UPDATE"
      Value: "Option value is not a number"
  - id: "UpdateProductConfigurationOptionSelection1"
    type: "pipelet"
    ref: "UpdateProductConfigurationOptionSelection"
  - id: "UpdateProductConfigurationOptionSelection2"
    type: "pipelet"
    ref: "UpdateProductConfigurationOptionSelection"
    bindings:
      ProductConfigurationOptionSelectionBO: "OptionSelection"
      StringValue: "Value"
      Value: "ObjValue"
      Domain: "Domain"
      ConfigurationValue: "CustomizationValue"

links:
  - from: "CreateProductConfigurationOptionSelection1"
    via: "error"
    to: "EndNode2"
    into: "in"
  - from: "CreateProductConfigurationOptionSelection2"
    via: "next"
    to: "UpdateProductConfigurationOptionSelection2"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "JoinNode7"
    into: "in2"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode6"
    into: "in2"
  - from: "StartNode5"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "CallNode1"
    via: "next"
    to: "DecisionNode12"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "CreateProductConfigurationOptionSelection2"
    into: "in"
  - from: "CallNode1"
    via: "ERROR"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CreateProductConfigurationOptionSelection1"
    into: "in"
  - from: "GetProductConfigurationValueByID2"
    via: "error"
    to: "EndNode7"
    into: "in"
  - from: "DecisionNode12"
    via: "yes"
    to: "DecisionNode5"
    into: "in"
  - from: "CreateProductConfigurationOptionSelection2"
    via: "error"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "GetProductConfigurationValueByID2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "UpdateProductConfigurationOptionSelection2"
    via: "error"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode12"
    via: "no"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CreateProductConfigurationOptionSelection1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "EndNode9"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "DecisionNode3"
    into: "in"
  - from: "UpdateProductConfigurationOptionSelection1"
    via: "error"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "GetProductConfigurationValueByID2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode4"
    into: "in2"
  - from: "UpdateProductConfigurationOptionSelection2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "DecisionNode1"
    via: "yes"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "RemoveProductConfigurationOptionSelection1"
    into: "in"
  - from: "RemoveProductConfigurationOptionSelection1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "UpdateProductConfigurationOptionSelection1"
    into: "in"
  - from: "UpdateProductConfigurationOptionSelection1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode6"
    into: "in1"
