flow: "ProcessImmediateOrderExport"
kind: "process"

entries:
  - id: "StartNode1"
    name: "StartExport"
    mode: "private"
    strict: true
    inputs:
      - key: "OrderBO"
        type: "com.intershop.component.order.capi.OrderBO"
        required: true
      - key: "ExportScenarioDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "ApplicationBO"
        type: "com.intershop.component.application.capi.ApplicationBO"
        required: true

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      InVector: "ExportScenarios"
      Object: "Config"
      Objects: "null"
      OutVector: "ExportScenarios"
      Iterator: "null"
  - id: "CallNode1"
    type: "call"
    ref: "Super:Export"
    bindings:
      ExportScenarios: "OrderedExportScenarios"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessOrderExportJob-GetExportConfig"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Config:ExecuteOnOrderCreation"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ExportScenarios"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "GetAllJobConfigurations1"
    type: "pipelet"
    ref: "GetAllJobConfigurations"
    config:
      DefaultJobNamePrefix: "ExportOrder_"
      DefaultJobState: "None"
    bindings:
      JobConfigurations: "JobConfigurations"
      Domain: "ExportScenarioDomain"
      JobNamePrefix: "null"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "LoopNode1"
    type: "loop"
  - id: "SortIteratorByComparator1"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingOrder: true
      DefaultSortingAttribute: "Name"
    bindings:
      Comparator: "null"
      Iterator: "ExportScenarios:Iterator"
      SortingAttribute: "null"
      SortingOrder: "null"
      SortedIterator: "OrderedExportScenarios"

links:
  - from: "StartNode1"
    via: "next"
    to: "GetAllJobConfigurations1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "SortIteratorByComparator1"
    into: "in"
  - from: "SortIteratorByComparator1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "GetAllJobConfigurations1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "LoopNode1"
    via: "do"
    to: "CallNode2"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "AddObjectToVector1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
