flow: "ProcessChannelApplication"
kind: "process"

entries:
  - id: "StartNode1"
    name: "Create"
    mode: "private"
    strict: true
    inputs:
      - key: "Repository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: false
  - id: "StartNode2"
    name: "PostCreation"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode3"
    name: "Remove"
    mode: "private"
    strict: true
    inputs:
      - key: "Repository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
  - id: "CreateApplicationDomainRelation1"
    type: "pipelet"
    ref: "CreateApplicationDomainRelation"
    bindings:
      Application: "ChannelApplication"
      Domain: "Organization:Domain"
      RelationName: "\"OrganizationBORepository\""
  - id: "CreateApplicationDomainRelation2"
    type: "pipelet"
    ref: "CreateApplicationDomainRelation"
    bindings:
      Application: "ChannelApplication"
      Domain: "Repository:Domain"
      RelationName: "\"ApplicationBORepository\""
  - id: "CreateChannelApplication2"
    type: "pipelet"
    ref: "CreateChannelApplication"
    bindings:
      Application: "ChannelApplication"
      ApplicationType: "ChannelApplicationTypeID"
  - id: "DetermineChannelApplication1"
    type: "pipelet"
    ref: "DetermineChannelApplication"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ChannelApplication"
        type: "com.intershop.beehive.core.capi.domain.Application"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode5"
    type: "end"
    strict: true
  - id: "EndNode6"
    type: "end"
    strict: true
  - id: "ExecutePipeline1"
    type: "pipelet"
    ref: "ExecutePipeline"
    config:
      PipelineName: "ProcessChannelApplication"
      PipelineStartNode: "PostCreation"
    bindings:
      Application: "ChannelApplication"
  - id: "GetApplicationBO1"
    type: "pipelet"
    ref: "GetApplicationBO"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "Pipelet12"
    type: "pipelet"
    ref: "GetOrganizationByDomain"
    bindings:
      OrganizationDomain: "Repository:OwningDomain"
  - id: "RemoveApplication1"
    type: "pipelet"
    ref: "RemoveApplication"

links:
  - from: "CreateApplicationDomainRelation2"
    via: "next"
    to: "ExecutePipeline1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetApplicationBO1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "GetApplicationBO1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "DetermineChannelApplication1"
    into: "in"
  - from: "DetermineChannelApplication1"
    via: "next"
    to: "RemoveApplication1"
    into: "in"
  - from: "RemoveApplication1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "RemoveApplication1"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "DetermineChannelApplication1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "ExecutePipeline1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "CreateApplicationDomainRelation1"
    via: "next"
    to: "CreateApplicationDomainRelation2"
    into: "in"
  - from: "Pipelet12"
    via: "next"
    to: "CreateChannelApplication2"
    into: "in"
  - from: "CreateChannelApplication2"
    via: "next"
    to: "CreateApplicationDomainRelation1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Pipelet12"
    into: "in"
  - from: "ExecutePipeline1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Pipelet12"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode2"
    into: "in"
