flow: "ProcessRequisitionTemplate"
kind: "process"

entries:
  - id: "Start10"
    name: "Remove"
    mode: "private"
    strict: false
    inputs:
      - key: "ProductListID"
        type: "java.lang.String"
        required: false
  - id: "Start11"
    name: "AddProducts"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "New"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CreateProductList1"
    type: "pipelet"
    ref: "CreateProductList"
    config:
      DefaultTypeCode: 3
    bindings:
      Domain: "OrganizationDomain"
      ProductList: "ReqTemplate"
      Scope: "CurrentUser:Profile"
  - id: "CreateProductListItem1"
    type: "pipelet"
    ref: "CreateProductListItem"
    bindings:
      ProductList: "ReqTemplate"
  - id: "End10"
    type: "end"
    strict: false
  - id: "End11"
    type: "end"
    strict: false
  - id: "End12"
    type: "end"
    strict: false
  - id: "End13"
    type: "end"
    strict: false
  - id: "End8"
    type: "end"
    strict: false
  - id: "GetFormRecord2"
    type: "pipelet"
    ref: "GetFormRecord"
    config:
      DefaultRecordID: "Quantity"
    bindings:
      FormRecord: "Quantities"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "ProductUUIDs"
    bindings:
      Selection: "SelectedUUIDs"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Lead Locale"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Lead Locale"
  - id: "GetLocale3"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Lead Locale"
  - id: "GetOrganizationByUser4"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      User: "CurrentUser"
  - id: "GetOrganizationByUser6"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      User: "CurrentUser"
  - id: "GetProductListByUUID1"
    type: "pipelet"
    ref: "GetProductListByUUID"
    bindings:
      ProductList: "ReqTemplate"
      ProductListUUID: "ReqTemplateID"
  - id: "GetProductListByUUID2"
    type: "pipelet"
    ref: "GetProductListByUUID"
    bindings:
      ProductListUUID: "ReqTemplateID"
  - id: "GetProductListByUUID3"
    type: "pipelet"
    ref: "GetProductListByUUID"
    bindings:
      ProductList: "ReqTemplate"
      ProductListUUID: "ReqTemplateID"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Product:MinOrderQuantity"
      OutValue_1: "QuantityValue"
  - id: "LoopNode1"
    type: "loop"
  - id: "RemoveProductList1"
    type: "pipelet"
    ref: "RemoveProductList"
  - id: "ToString3"
    type: "pipelet"
    ref: "ToString"
    bindings:
      Object1: "Product:ProductRef"
      String1: "ProductRefString"
  - id: "UpdateProductList1"
    type: "pipelet"
    ref: "UpdateProductList"
    bindings:
      DisplayName: "ReqTemplateForm_Name"
      ProductList: "ReqTemplate"
      ShortDescription: "ReqTemplateForm_Description"
  - id: "UpdateProductList2"
    type: "pipelet"
    ref: "UpdateProductList"
    bindings:
      DisplayName: "ReqTemplateForm_Name"
      IsPublic: "NULL"
      ProductList: "ReqTemplate"
      ShortDescription: "ReqTemplateForm_Description"
      TypeCode: "NULL"
  - id: "UpdateProductListItem1"
    type: "pipelet"
    ref: "UpdateProductListItem"
    bindings:
      Description: "Product:ShortDescription"
      DisplayName: "Product:Name"
      Quantity: "QuantityValue"
  - id: "VerifyQuantity3"
    type: "pipelet"
    ref: "VerifyQuantity"
    bindings:
      LocalizedString: "Quantities:get(ProductRefString)"

links:
  - from: "Join3"
    via: "next"
    to: "End8"
    into: "in"
  - from: "UpdateProductList2"
    via: "next"
    to: "End10"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "GetProductListByUUID1"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "End11"
    into: "in"
  - from: "GetProductListByUUID2"
    via: "error"
    to: "Join4"
    into: "in3"
  - from: "GetProductListByUUID2"
    via: "next"
    to: "RemoveProductList1"
    into: "in"
  - from: "RemoveProductList1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "Start10"
    via: "next"
    to: "GetProductListByUUID2"
    into: "in"
  - from: "GetProductListByUUID3"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "CreateProductListItem1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "End12"
    into: "in"
  - from: "CreateProductList1"
    via: "error"
    to: "Join3"
    into: "in3"
  - from: "UpdateProductListItem1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "Start11"
    via: "next"
    to: "GetOrganizationByUser6"
    into: "in"
  - from: "GetOrganizationByUser6"
    via: "next"
    to: "GetProductListByUUID3"
    into: "in"
  - from: "GetProductListByUUID3"
    via: "error"
    to: "End13"
    into: "in"
  - from: "GetLocale3"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "GetFormRecord2"
    into: "in"
  - from: "GetFormRecord2"
    via: "next"
    to: "GetLocale3"
    into: "in"
  - from: "ToString3"
    via: "next"
    to: "VerifyQuantity3"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "UpdateProductListItem1"
    into: "in"
  - from: "VerifyQuantity3"
    via: "error"
    to: "KeyMapper1"
    into: "in"
  - from: "UpdateProductList1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "Join5"
    into: "in3"
  - from: "CreateProductListItem1"
    via: "next"
    to: "ToString3"
    into: "in"
  - from: "VerifyQuantity3"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "GetLocale1"
    via: "next"
    to: "CreateProductList1"
    into: "in"
  - from: "CreateProductList1"
    via: "next"
    to: "UpdateProductList1"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "GetOrganizationByUser4"
    into: "in"
  - from: "GetOrganizationByUser4"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "GetProductListByUUID1"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "GetLocale2"
    via: "next"
    to: "UpdateProductList2"
    into: "in"
