flow: "ProcessGlobalRequisitionTemplate"
kind: "process"

entries:
  - id: "Start2"
    name: "Remove"
    mode: "private"
    strict: false
    inputs:
      - key: "ProductListID"
        type: "java.lang.String"
        required: false
  - id: "Start3"
    name: "AddProducts"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "GetRTUserOfOrg"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "New"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "UpdateQuantity"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call7"
    type: "call"
    ref: "ProcessGlobalRequisitionTemplate-GetRTUserOfOrg"
  - id: "CreateProductList1"
    type: "pipelet"
    ref: "CreateProductList"
    config:
      DefaultTypeCode: 3
    bindings:
      Domain: "OrganizationDomain"
      ProductList: "ReqTemplate"
      Scope: "GlobalRTUserOfOrganization:Profile"
  - id: "CreateProductListItem1"
    type: "pipelet"
    ref: "CreateProductListItem"
    bindings:
      ProductList: "ReqTemplate"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ProductDomain"
  - id: "DecisionNode2"
    type: "decision"
    condition: "CurrentProductRepository"
  - id: "DetermineUser1"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      User: "GlobalRTUserOfOrganization"
      UserID: "Organization:Profile:ProfileID"
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End5"
    type: "end"
    strict: false
  - id: "End6"
    type: "end"
    strict: false
  - id: "End7"
    type: "end"
    strict: false
  - id: "End8"
    type: "end"
    strict: false
  - id: "GetFormRecord1"
    type: "pipelet"
    ref: "GetFormRecord"
    bindings:
      RecordID: "ProductListItemUUID"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "ProductUUIDs"
    bindings:
      Selection: "SelectedUUIDs"
  - id: "GetFormSelection3"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "ProductListItemUUIDs"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Lead Locale"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Lead Locale"
  - id: "GetLocale3"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Lead Locale"
  - id: "GetLocale4"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Lead Locale"
  - id: "GetOrganizationByUser4"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      User: "CurrentUser"
  - id: "GetProductListByUUID1"
    type: "pipelet"
    ref: "GetProductListByUUID"
    bindings:
      ProductListUUID: "ReqTemplateID"
  - id: "GetProductListByUUID2"
    type: "pipelet"
    ref: "GetProductListByUUID"
    bindings:
      ProductList: "ReqTemplate"
      ProductListUUID: "ReqTemplateID"
  - id: "GetProductListByUUID3"
    type: "pipelet"
    ref: "GetProductListByUUID"
    bindings:
      ProductList: "ReqTemplate"
      ProductListUUID: "ReqTemplateID"
  - id: "GetProductListByUUID4"
    type: "pipelet"
    ref: "GetProductListByUUID"
    bindings:
      ProductList: "ReqTemplate"
      ProductListUUID: "ReqTemplateID"
  - id: "GetProductListItemByUUID1"
    type: "pipelet"
    ref: "GetProductListItemByUUID"
  - id: "GetProductRefsByBaseProductUUIDs1"
    type: "pipelet"
    ref: "GetProductRefsByBaseProductUUIDs"
    bindings:
      ProductUUIDs: "SelectedUUIDs"
  - id: "GetProductRefsByProductUUIDs1"
    type: "pipelet"
    ref: "GetProductRefsByProductUUIDs"
    bindings:
      ProductUUIDs: "SelectedUUIDs"
  - id: "GetProductRefsByProductUUIDs2"
    type: "pipelet"
    ref: "GetProductRefsByProductUUIDs"
    bindings:
      ProductUUIDs: "SelectedUUIDs"
      ProductDomain: "CurrentProductRepository:RepositoryDomain"
  - id: "Join1"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ProductListItem:Quantity"
      OutValue_1: "QuantityValue"
  - id: "Loop1"
    type: "loop"
  - id: "LoopNode1"
    type: "loop"
  - id: "RemoveProductList1"
    type: "pipelet"
    ref: "RemoveProductList"
  - id: "UpdateProductList1"
    type: "pipelet"
    ref: "UpdateProductList"
    bindings:
      DisplayName: "ReqTemplateForm_Name"
      ProductList: "ReqTemplate"
      ShortDescription: "ReqTemplateForm_Description"
  - id: "UpdateProductList2"
    type: "pipelet"
    ref: "UpdateProductList"
    bindings:
      DisplayName: "ReqTemplateForm_Name"
      IsPublic: "NULL"
      ProductList: "ReqTemplate"
      ShortDescription: "ReqTemplateForm_Description"
      TypeCode: "NULL"
  - id: "UpdateProductListItem1"
    type: "pipelet"
    ref: "UpdateProductListItem"
    bindings:
      Description: "Product:ShortDescription"
      DisplayName: "Product:Name"
      Quantity: "Product:MinOrderQuantity"
  - id: "UpdateProductListItem2"
    type: "pipelet"
    ref: "UpdateProductListItem"
    bindings:
      Quantity: "QuantityValue"
      ProductLineItem: "ProductListItem:ProductLineItem"
  - id: "VerifyQuantity1"
    type: "pipelet"
    ref: "VerifyQuantity"
    bindings:
      LocalizedString: "FormRecord:QUANTITY"

links:
  - from: "Join1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "GetProductListByUUID1"
    via: "next"
    to: "RemoveProductList1"
    into: "in"
  - from: "RemoveProductList1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "GetProductListByUUID2"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "GetLocale2"
    via: "next"
    to: "UpdateProductList2"
    into: "in"
  - from: "GetProductListByUUID3"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "GetProductRefsByBaseProductUUIDs1"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "LoopNode1"
    via: "do"
    to: "CreateProductListItem1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "End3"
    into: "in"
  - from: "CreateProductListItem1"
    via: "next"
    to: "UpdateProductListItem1"
    into: "in"
  - from: "UpdateProductListItem1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "Start6"
    via: "next"
    to: "GetOrganizationByUser4"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "GetLocale3"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "DecisionNode2"
    into: "in"
  - from: "UpdateProductList2"
    via: "next"
    to: "End5"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "GetProductListByUUID3"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "GetProductListByUUID1"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "GetProductListByUUID2"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "CreateProductList1"
    into: "in"
  - from: "CreateProductList1"
    via: "next"
    to: "UpdateProductList1"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "GetProductListByUUID4"
    into: "in"
  - from: "GetOrganizationByUser4"
    via: "next"
    to: "DetermineUser1"
    into: "in"
  - from: "GetFormSelection3"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "GetFormRecord1"
    via: "next"
    to: "VerifyQuantity1"
    into: "in"
  - from: "GetProductListByUUID4"
    via: "next"
    to: "GetLocale4"
    into: "in"
  - from: "GetLocale4"
    via: "next"
    to: "GetFormSelection3"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetProductListItemByUUID1"
    into: "in"
  - from: "GetProductListItemByUUID1"
    via: "next"
    to: "GetFormRecord1"
    into: "in"
  - from: "UpdateProductListItem2"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Loop1"
    via: "next"
    to: "End8"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Join5"
    into: "in3"
  - from: "VerifyQuantity1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "DetermineUser1"
    via: "next"
    to: "End6"
    into: "in"
  - from: "VerifyQuantity1"
    via: "error"
    to: "KeyMapper1"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "UpdateProductListItem2"
    into: "in"
  - from: "GetLocale3"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetProductRefsByProductUUIDs1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "GetProductRefsByProductUUIDs2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "GetProductRefsByBaseProductUUIDs1"
    into: "in"
  - from: "GetProductRefsByProductUUIDs1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "GetProductRefsByProductUUIDs2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "Join3"
    via: "next"
    to: "End7"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "CreateProductList1"
    via: "error"
    to: "Join3"
    into: "in3"
  - from: "UpdateProductList1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "GetProductListByUUID1"
    via: "error"
    to: "Join1"
    into: "in3"
