flow: "ProcessCatalogExtension"
kind: "extension"

entries:
  - id: "StartNode0"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true
      - key: "OrganizationDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true

steps:
  - id: "Decision1"
    type: "decision"
    condition: "Organization:TypeCode"
  - id: "Decision2"
    type: "decision"
    condition: "Organization:TypeCode"
  - id: "End6"
    type: "end"
    strict: false
  - id: "EndNode0"
    type: "end"
    strict: true
    outputs:
      - key: "Repository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        guaranteed: true
  - id: "GetRepository1"
    type: "pipelet"
    ref: "GetRepository"
    config:
      Type: "Offer Repository"
  - id: "GetRepository2"
    type: "pipelet"
    ref: "GetRepository"
    config:
      Type: "Product Repository"
  - id: "Join7"
    type: "join"
  - id: "JoinNode1"
    type: "join"

links:
  - from: "Decision1"
    via: "yes"
    to: "Join7"
    into: "in1"
  - from: "GetRepository2"
    via: "error"
    to: "End6"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Decision2"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "GetRepository2"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "Join7"
    into: "in3"
  - from: "Join7"
    via: "next"
    to: "GetRepository1"
    into: "in"
  - from: "GetRepository2"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "GetRepository1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode0"
    into: "in"
  - from: "GetRepository1"
    via: "error"
    to: "End6"
    into: "in"
  - from: "StartNode0"
    via: "next"
    to: "Decision1"
    into: "in"
