flow: "ProcessForgotLoginData"
kind: "process"

entries:
  - id: "StartNode3"
    name: "SendMail"
    mode: "private"
    strict: true
    inputs:
      - key: "User"
        type: "com.intershop.beehive.core.capi.user.User"
        required: true
      - key: "CurrentOrganization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true
      - key: "WaitForResult"
        type: "java.lang.String"
        required: false
      - key: "TargetApplicationBO"
        type: "com.intershop.component.application.capi.ApplicationBO"
        required: false

steps:
  - id: "CalculateDate2"
    type: "pipelet"
    ref: "CalculateDate"
    config:
      CalculationMethod: "Add"
    bindings:
      Date: "CurrentDate"
      CalculatedDate: "NewPasswordExpiry"
      Hours: "PasswordReminderLinkLifeTime"
  - id: "DecisionNode1"
    type: "decision"
    condition: "WaitForResult"
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "SecureHash"
        type: "java.lang.String"
        guaranteed: false
      - key: "PasswordReminderLinkLifeTime"
        type: "java.lang.Integer"
        guaranteed: false
      - key: "MailResult"
        type: "java.lang.String"
        guaranteed: false
  - id: "GetCurrentDate1"
    type: "pipelet"
    ref: "GetCurrentDate"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "PasswordReminderEmailTemplate"
      Type: "String"
    bindings:
      PreferenceStringValue: "PasswordReminderEmailTemplate"
      PreferenceDomain: "ChannelRepository:Domain"
  - id: "GetDomainPreference2"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "PasswordReminderEmailSubject"
      Type: "String"
    bindings:
      PreferenceStringValue: "PasswordReminderEmailSubject"
      PreferenceDomain: "ChannelRepository:Domain"
  - id: "GetDomainPreference3"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "PasswordReminderEmailFrom"
      Type: "String"
    bindings:
      PreferenceStringValue: "PasswordReminderEmailFrom"
      PreferenceDomain: "ChannelRepository:Domain"
  - id: "GetDomainPreference7"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "PasswordReminderLinkLifeTime"
      Type: "Integer"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceIntValue: "PasswordReminderLinkLifeTime"
  - id: "GetRepositoryByRepositoryDomain1"
    type: "pipelet"
    ref: "GetRepositoryByRepositoryDomain"
    bindings:
      RepositoryDomain: "CurrentOrganization:OwningDomain"
      Repository: "ChannelRepository"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "SecureHash"
      InValue_1: "User:Profile:Credentials:PasswordReminder"
  - id: "ProcessMail1"
    type: "pipelet"
    ref: "ProcessMail"
    config:
      WaitForResult: true
    bindings:
      LocaleID: "User:Profile:DataSheet:PreferredLocale"
      MailFrom: "PasswordReminderEmailFrom"
      MailSubject: "PasswordReminderEmailSubject"
      MailTemplate: "PasswordReminderEmailTemplate"
      MailTo: "User:Profile:Credentials:ReminderEmail"
      Domain: "ChannelRepository:Domain"
  - id: "ProcessMail2"
    type: "pipelet"
    ref: "ProcessMail"
    bindings:
      LocaleID: "User:Profile:DataSheet:PreferredLocale"
      MailFrom: "PasswordReminderEmailFrom"
      MailSubject: "PasswordReminderEmailSubject"
      MailTemplate: "PasswordReminderEmailTemplate"
      MailTo: "User:Profile:Credentials:ReminderEmail"
      Domain: "ChannelRepository:Domain"
  - id: "UpdateUserCredentials3"
    type: "pipelet"
    ref: "UpdateUserCredentials"
    bindings:
      NewPasswordExpiry: "NewPasswordExpiry"
      IsActive: "\"true\""

links:
  - from: "ProcessMail1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "GetRepositoryByRepositoryDomain1"
    into: "in"
  - from: "GetDomainPreference7"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "ProcessMail2"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "GetDomainPreference2"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "UpdateUserCredentials3"
    via: "next"
    to: "GetDomainPreference3"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "CalculateDate2"
    via: "next"
    to: "UpdateUserCredentials3"
    into: "in"
  - from: "GetRepositoryByRepositoryDomain1"
    via: "next"
    to: "GetCurrentDate1"
    into: "in"
  - from: "GetDomainPreference3"
    via: "next"
    to: "GetDomainPreference2"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetDomainPreference1"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "ProcessMail2"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "GetDomainPreference7"
    via: "next"
    to: "CalculateDate2"
    into: "in"
  - from: "GetCurrentDate1"
    via: "next"
    to: "GetDomainPreference7"
    into: "in"
  - from: "JoinNode11"
    via: "next"
    to: "JoinNode10"
    into: "in2"
  - from: "GetRepositoryByRepositoryDomain1"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "UpdateUserCredentials3"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "GetDomainPreference3"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "GetDomainPreference2"
    via: "error"
    to: "JoinNode8"
    into: "in2"
  - from: "KeyMapper4"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "GetDomainPreference1"
    via: "error"
    to: "JoinNode9"
    into: "in2"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "ProcessMail1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "ProcessMail2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "ProcessMail1"
    via: "error"
    to: "JoinNode11"
    into: "in2"
