flow: "ProcessAffiliate"
kind: "process"

entries:
  - id: "StartNode1"
    name: "GetProgramByRequest"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "GetProgramBySession"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "BookLead"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "RemoveRevenue"
    mode: "private"
    strict: true
    inputs:
      - key: "Order"
        type: "com.intershop.beehive.bts.capi.orderprocess.fulfillment.Order"
        required: false
  - id: "StartNode6"
    name: "BookRevenue"
    mode: "private"
    strict: false
    inputs:
      - key: "ApplicationBO"
        type: "com.intershop.component.application.capi.ApplicationBO"
        required: true

steps:
  - id: "BindAccountTransaction1"
    type: "pipelet"
    ref: "BindAccountTransaction"
    bindings:
      Account: "AffiliateProgramAccount"
  - id: "CallNode12"
    type: "call"
    ref: "ProcessAffiliate-GetProgramBySession"
  - id: "CreateAccountTransaction2"
    type: "pipelet"
    ref: "CreateAccountTransaction"
    config:
      DefaultTypeCode: 50
    bindings:
      TypeCode: "null"
      Owner: "AffiliatePartnerAccount:Domain"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PartnerUUID"
  - id: "DecisionNode15"
    type: "decision"
    condition: "AffiliateProgram"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ProgramUUID"
  - id: "DecisionNode3"
    type: "decision"
    condition: "ProgramUUID"
  - id: "DecisionNode4"
    type: "decision"
    condition: "PartnerUUID"
  - id: "DecisionNode5"
    type: "decision"
    condition: "AffiliateProgram:isEnabled"
  - id: "DecisionNode6"
    type: "decision"
    condition: "AffiliateProgram:isExpired"
  - id: "DecisionNode7"
    type: "decision"
    condition: "Order:AffiliatePartnerAccountID"
  - id: "DecisionNode8"
    type: "decision"
    condition: "Order:AffiliateProgramAccountID"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode12"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "EndNode5"
    type: "end"
    strict: false
  - id: "EndNode6"
    type: "end"
    strict: false
  - id: "ExchangeSessionObject4"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ProgramUUID"
    bindings:
      LoadObject: "ProgramUUID"
  - id: "ExchangeSessionObject5"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "PartnerUUID"
    bindings:
      LoadObject: "PartnerUUID"
  - id: "GetAccountByOwner1"
    type: "pipelet"
    ref: "GetAccountByOwner"
    config:
      DefaultTypeCode: 50
    bindings:
      Owner: "AffiliateProgram"
      Account: "AffiliateProgramAccount"
      TypeCode: "null"
  - id: "GetAccountByUUID1"
    type: "pipelet"
    ref: "GetAccountByUUID"
    bindings:
      AccountUUID: "Order:AffiliatePartnerAccountID"
  - id: "GetAccountByUUID2"
    type: "pipelet"
    ref: "GetAccountByUUID"
    bindings:
      AccountUUID: "Order:AffiliateProgramAccountID"
  - id: "GetAccountTransactionByUUID1"
    type: "pipelet"
    ref: "GetAccountTransactionByUUID"
    bindings:
      AccountTransactionUUID: "Order:AffiliatePartnerTransactionID"
  - id: "GetAffiliateSession1"
    type: "pipelet"
    ref: "GetAffiliateSession"
  - id: "GetOrderBO1"
    type: "pipelet"
    ref: "GetOrderBO"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode23"
    type: "join"
  - id: "JoinNode24"
    type: "join"
  - id: "JoinNode25"
    type: "join"
  - id: "JoinNode26"
    type: "join"
  - id: "JoinNode27"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "AffiliateProgram:AffiliatePartner"
      OutValue_1: "AffiliatePartner"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Order\"):getOrderBORepository(Order)"
      OutValue_1: "OrderBORepository"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetAffiliateProgramByUUID"
    bindings:
      AffiliateProgramUUID: "ProgramUUID"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "GetAffiliatePartnerByUUID"
    bindings:
      AffiliatePartnerUUID: "PartnerUUID"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "GetAffiliateProgramByUUID"
    bindings:
      AffiliateProgramUUID: "ProgramUUID"
  - id: "Pipelet34"
    type: "pipelet"
    ref: "BindAccountTransaction"
    bindings:
      Account: "AffiliatePartnerAccount"
  - id: "Pipelet35"
    type: "pipelet"
    ref: "GetAccountByOwner"
    config:
      DefaultTypeCode: 50
    bindings:
      Owner: "AffiliatePartner"
      Account: "AffiliatePartnerAccount"
      TypeCode: "null"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "AffiliateProgram:AffiliatePartner"
      OutValue_1: "AffiliatePartner"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "GetAffiliatePartnerByUUID"
    bindings:
      AffiliatePartnerUUID: "PartnerUUID"
  - id: "UnbindAccountTransaction1"
    type: "pipelet"
    ref: "UnbindAccountTransaction"
  - id: "UnbindAccountTransaction2"
    type: "pipelet"
    ref: "UnbindAccountTransaction"
  - id: "UpdateAccountTransaction1"
    type: "pipelet"
    ref: "UpdateAccountTransaction"
    config:
      AmountUpdatePolicy: "Default"
    bindings:
      Amount: "OrderBO:SubtotalAmount"
      AmountCurrency: "null"
      AmountValue: "null"
      TimeStamp: "null"
  - id: "UpdateAffiliateSession1"
    type: "pipelet"
    ref: "UpdateAffiliateSession"
    bindings:
      RegisteredUser: "CurrentUser"
  - id: "UpdateCustomAttributes1"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "AffiliatePartnerAccountID"
      Attribute_1_Type: "String"
      Attribute_2_Type: "String"
      Attribute_2_Name: "AffiliatePartnerTransactionID"
      Attribute_3_Name: "AffiliateProgramAccountID"
      Attribute_3_Type: "String"
    bindings:
      Attribute_1_Value: "AffiliatePartnerAccount:UUID"
      Attribute_2_Value: "AccountTransaction:UUID"
      ExtensibleObject: "Order"
      Attribute_3_Value: "AffiliateProgramAccount:UUID"

links:
  - from: "Pipelet2"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet5"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "Pipelet4"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "Pipelet2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode4"
    into: "in1"
  - from: "Pipelet3"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode24"
    via: "next"
    to: "JoinNode23"
    into: "in2"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "ExchangeSessionObject5"
    into: "in"
  - from: "Pipelet3"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet5"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "StartNode2"
    via: "next"
    to: "ExchangeSessionObject4"
    into: "in"
  - from: "ExchangeSessionObject4"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "ExchangeSessionObject5"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode27"
    via: "next"
    to: "EndNode12"
    into: "in"
  - from: "CreateAccountTransaction2"
    via: "error"
    to: "JoinNode26"
    into: "in2"
  - from: "StartNode6"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DecisionNode7"
    into: "in"
  - from: "CreateAccountTransaction2"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "Pipelet35"
    via: "next"
    to: "CreateAccountTransaction2"
    into: "in"
  - from: "GetAccountByOwner1"
    via: "error"
    to: "JoinNode24"
    into: "in2"
  - from: "Pipelet35"
    via: "error"
    to: "JoinNode25"
    into: "in2"
  - from: "GetAccountByOwner1"
    via: "next"
    to: "BindAccountTransaction1"
    into: "in"
  - from: "Pipelet34"
    via: "next"
    to: "DecisionNode15"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode23"
    via: "next"
    to: "UpdateCustomAttributes1"
    into: "in"
  - from: "JoinNode25"
    via: "next"
    to: "JoinNode26"
    into: "in1"
  - from: "DecisionNode5"
    via: "yes"
    to: "DecisionNode6"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode8"
    into: "in2"
  - from: "CallNode12"
    via: "ERROR"
    to: "JoinNode25"
    into: "in1"
  - from: "CallNode12"
    via: "next"
    to: "Pipelet35"
    into: "in"
  - from: "JoinNode26"
    via: "next"
    to: "JoinNode27"
    into: "in3"
  - from: "UpdateAccountTransaction1"
    via: "next"
    to: "Pipelet34"
    into: "in"
  - from: "GetAffiliateSession1"
    via: "next"
    to: "UpdateAffiliateSession1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetAffiliateSession1"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "Pipelet1"
    into: "in"
  - from: "GetAffiliateSession1"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "UpdateAffiliateSession1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "DecisionNode15"
    via: "yes"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode15"
    via: "no"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode6"
    via: "yes"
    to: "GetAccountByOwner1"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode9"
    into: "in2"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode24"
    into: "in1"
  - from: "UpdateCustomAttributes1"
    via: "next"
    to: "JoinNode27"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "DecisionNode8"
    via: "yes"
    to: "GetAccountByUUID2"
    into: "in"
  - from: "GetAccountByUUID2"
    via: "next"
    to: "UnbindAccountTransaction2"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "GetAccountByUUID1"
    into: "in"
  - from: "GetAccountByUUID1"
    via: "next"
    to: "GetAccountTransactionByUUID1"
    into: "in"
  - from: "GetAccountTransactionByUUID1"
    via: "next"
    to: "UnbindAccountTransaction1"
    into: "in"
  - from: "UnbindAccountTransaction1"
    via: "next"
    to: "DecisionNode8"
    into: "in"
  - from: "BindAccountTransaction1"
    via: "next"
    to: "JoinNode23"
    into: "in1"
  - from: "DecisionNode8"
    via: "no"
    to: "JoinNode11"
    into: "in2"
  - from: "UnbindAccountTransaction2"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode10"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "GetAccountByUUID1"
    via: "error"
    to: "JoinNode12"
    into: "in2"
  - from: "GetAccountByUUID2"
    via: "error"
    to: "JoinNode14"
    into: "in2"
  - from: "DecisionNode7"
    via: "no"
    to: "JoinNode12"
    into: "in1"
  - from: "GetAccountTransactionByUUID1"
    via: "error"
    to: "JoinNode13"
    into: "in2"
  - from: "JoinNode12"
    via: "next"
    to: "JoinNode13"
    into: "in1"
  - from: "JoinNode13"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "JoinNode14"
    into: "in1"
  - from: "JoinNode14"
    via: "next"
    to: "JoinNode10"
    into: "in2"
  - from: "GetOrderBO1"
    via: "next"
    to: "UpdateAccountTransaction1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "GetOrderBO1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode1"
    into: "in1"
