flow: "ProcessABTesting"
kind: "process"

entries:
  - id: "StartNode1"
    name: "LogPromotionAppliedToBasketEvents"
    mode: "private"
    strict: true
    inputs:
      - key: "Cart"
        type: "com.intershop.beehive.bts.capi.orderprocess.basket.Basket"
        required: true
  - id: "StartNode2"
    name: "GetAssignedPromotions"
    mode: "private"
    strict: true
    inputs:
      - key: "Basket"
        type: "com.intershop.beehive.bts.capi.orderprocess.basket.Basket"
        required: true
  - id: "StartNode22"
    name: "LogOrderEvents"
    mode: "private"
    strict: true
    inputs:
      - key: "Basket"
        type: "com.intershop.beehive.bts.capi.orderprocess.basket.Basket"
        required: true
      - key: "Order"
        type: "com.intershop.beehive.bts.capi.orderprocess.fulfillment.Order"
        required: true

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "null"
      Objects: "null"
      Object: "null"
      OutVector: "Promotions"
      Iterator: "PromotionsIterator"
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "Promotions"
      OutVector: "Promotions"
      Iterator: "PromotionsIterator"
      Object: "AppliedRebateBO:Rebate:Promotion:Extension(\"PersistentObjectBOExtension\"):PersistentObject"
      Objects: "null"
  - id: "CalculateDouble1"
    type: "pipelet"
    ref: "CalculateDouble"
    config:
      Operation: "+"
    bindings:
      Operand1: "ItemCount"
      Operand2: "PLI:Quantity:Value"
      Result: "ItemCount"
  - id: "CalculateDouble4"
    type: "pipelet"
    ref: "CalculateDouble"
    config:
      Operand2: 0
      Operation: "+"
    bindings:
      Operand1: "PLI:Quantity:Value"
      Result: "DoubleValue"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessABTesting-GetAssignedPromotions"
    bindings:
      Basket: "Cart"
      PromotionsIterator: "Promotions"
  - id: "CallNode23"
    type: "call"
    ref: "ProcessABTesting-GetCurrentAssignedABTestGroupsFromSession"
    bindings:
      CurrentAssignedABTestGroups: "CurrentAssignedABTestGroups"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessABTesting-GetCurrentAssignedABTestGroupsFromSession"
    bindings:
      CurrentAssignedABTestGroups: "CurrentAssignedABTestGroups"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessABTesting-GetCurrentABTestGroupsFromSession"
    bindings:
      CurrentABTestGroups: "CurrentABTestGroups"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessABTesting-LogApplyEvent"
    bindings:
      ABTestGroup: "AssignedABTestGroup"
      TestObject: "Promotion"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PromotionsIterator"
  - id: "DecisionNode2"
    type: "decision"
    condition: "AppliedRebateBO:Rebate"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode26"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "PromotionsIterator"
        type: "java.util.Iterator"
        guaranteed: true
  - id: "GetABTestGroupsByObjectAssignment1"
    type: "pipelet"
    ref: "GetABTestGroupsByObjectAssignment"
    bindings:
      ABTestGroups: "CurrentAssignedABTestGroups"
      TestObject: "Promotion"
      AssignedABTestGroups: "AssignedABTestGroups"
  - id: "GetApplicationBO2"
    type: "pipelet"
    ref: "GetApplicationBO"
  - id: "GetBasketBO2"
    type: "pipelet"
    ref: "GetBasketBO"
    bindings:
      Basket: "Basket"
      BasketBO: "CartBO"
      BasketBORepository: "ApplicationBO:Extension(\"Basket\"):getBasketBORepository(CurrentDomain)"
  - id: "GetProductByProductRef1"
    type: "pipelet"
    ref: "GetProductByProductRef"
    bindings:
      ProductRef: "PLI:SellerProductRef"
      ProductRefID: "null"
      ProductRefIDs: "null"
      ProductRefs: "null"
      Product: "Product"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"(Double)0\""
      OutValue_1: "ItemCount"
  - id: "LogABTestEvent3"
    type: "pipelet"
    ref: "LogABTestEvent"
    config:
      Type: "ItemsOrderedEvent"
    bindings:
      ABTestGroup: "null"
      ABTestGroups: "CurrentABTestGroups"
      CurrentSession: "CurrentSession"
      CurrentUser: "CurrentUser"
      DoubleValue: "DoubleValue"
      MoneyValue: "PLI:SingleBasePricePC"
      TestObject: "Product"
  - id: "LogABTestEvent8"
    type: "pipelet"
    ref: "LogABTestEvent"
    config:
      Type: "OrderCreatedEvent"
    bindings:
      ABTestGroup: "null"
      ABTestGroups: "CurrentABTestGroups"
      CurrentSession: "CurrentSession"
      CurrentUser: "CurrentUser"
      DoubleValue: "null"
      MoneyValue: "Order:GrandTotalGrossPricePC"
      TestObject: "null"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode3"
    type: "loop"
  - id: "LoopNode4"
    type: "loop"
  - id: "LoopNode7"
    type: "loop"

links:
  - from: "LoopNode1"
    via: "do"
    to: "GetABTestGroupsByObjectAssignment1"
    into: "in"
  - from: "LoopNode3"
    via: "next"
    to: "JoinNode12"
    into: "in2"
  - from: "CallNode1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "LoopNode7"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode1"
    via: "EMPTY"
    to: "JoinNode1"
    into: "in2"
  - from: "LoopNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode26"
    into: "in"
  - from: "CallNode3"
    via: "ERROR"
    to: "JoinNode1"
    into: "in1"
  - from: "CalculateDouble4"
    via: "next"
    to: "GetProductByProductRef1"
    into: "in"
  - from: "JoinNode12"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "CallNode23"
    via: "next"
    to: "LogABTestEvent8"
    into: "in"
  - from: "LogABTestEvent8"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "GetProductByProductRef1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "StartNode22"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "CallNode23"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetApplicationBO2"
    into: "in"
  - from: "GetApplicationBO2"
    via: "next"
    to: "GetBasketBO2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "LoopNode7"
    via: "do"
    to: "CalculateDouble1"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "AddObjectToVector1"
    via: "next"
    to: "LoopNode4"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "LoopNode4"
    into: "loop"
  - from: "LoopNode4"
    via: "do"
    to: "DecisionNode2"
    into: "in"
  - from: "GetBasketBO2"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "LoopNode4"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "AddObjectToVector2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "EndNode2"
    into: "in"
  - from: "GetProductByProductRef1"
    via: "next"
    to: "LogABTestEvent3"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "LoopNode7"
    into: "in"
  - from: "LogABTestEvent3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CalculateDouble1"
    via: "next"
    to: "CalculateDouble4"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "LoopNode7"
    into: "loop"
  - from: "GetABTestGroupsByObjectAssignment1"
    via: "error"
    to: "JoinNode12"
    into: "in1"
  - from: "GetABTestGroupsByObjectAssignment1"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "LoopNode3"
    via: "do"
    to: "CallNode7"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "CallNode23"
    via: "ERROR"
    to: "JoinNode4"
    into: "in2"
