flow: "ProcessGlobalNavigationBar"
kind: "process"

entries:
  - id: "Start11"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "GetChannelPermissions"
    mode: "private"
    strict: false
    inputs:
      - key: "Repository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: false

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "null"
      Object: "null"
      Objects: "AuthorizedChannels"
      OutVector: "AuthorizedChannels"
      Iterator: "null"
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "AuthorizedChannels"
      Object: "Repository"
      Objects: "null"
      OutVector: "AuthorizedChannels"
      Iterator: "null"
  - id: "Call3"
    type: "call"
    ref: "ProcessChannelList-ListAll"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessGlobalNavigationBar-GetChannelPermissions"
  - id: "CombineMaps1"
    type: "pipelet"
    ref: "CombineMaps"
    config:
      ProcessMethod: "Concatenate HashMaps"
    bindings:
      Map1: "RepositoryPermissionMap"
      Map2: "RepositoryCMPermissionMap"
      Map: "RepositoryPermissionMap"
  - id: "DecisionNode1"
    type: "decision"
    condition: "RepositoryPermissionMap:isEmpty"
  - id: "DecisionNode2"
    type: "decision"
    condition: "AuthorizedChannels"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "FromString1"
    type: "pipelet"
    ref: "FromString"
    config:
      Type: "Double"
    bindings:
      StringValue: "MaxChannelLinks"
      AdditionalStringValue: "null"
      Object: "MaxChannelLinks"
  - id: "GetPermissionsByUser1"
    type: "pipelet"
    ref: "GetPermissionsByUser"
    config:
      Permission_Prefix: "SLD"
    bindings:
      AuthorizationObject: "Repository:RepositoryDomain"
      PermissionMap: "RepositoryPermissionMap"
      User: "CurrentUser"
      Organization: "null"
      PermissionList: "null"
  - id: "GetPermissionsByUser2"
    type: "pipelet"
    ref: "GetPermissionsByUser"
    config:
      Permission_Prefix: "CM_USER"
    bindings:
      AuthorizationObject: "Repository:RepositoryDomain"
      PermissionMap: "RepositoryCMPermissionMap"
      User: "CurrentUser"
      Organization: "null"
      PermissionList: "null"
  - id: "GetPropertyValue1"
    type: "pipelet"
    ref: "GetPropertyValue"
    config:
      PropertyName: "intershop.cartridges.sld_enterprise_app.channelbar.MaxChannelLinks"
      PropertyType: "Global"
      DefaultPropertyValue: 4
    bindings:
      PropertyValue: "MaxChannelLinks"
  - id: "Join8"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "Loop1"
    type: "loop"
  - id: "SortIteratorByComparator1"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingAttribute: "Id"
      DefaultSortingOrder: true
    bindings:
      Iterator: "AuthorizedChannels:Iterator"
      SortingAttribute: "null"
      SortingOrder: "null"
      SortedIterator: "AuthorizedChannels"

links:
  - from: "Start11"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "Join8"
    into: "in3"
  - from: "DecisionNode1"
    via: "yes"
    to: "AddObjectToVector2"
    into: "in"
  - from: "GetPermissionsByUser1"
    via: "next"
    to: "GetPermissionsByUser2"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "CombineMaps1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "GetPropertyValue1"
    via: "next"
    to: "FromString1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "GetPropertyValue1"
    into: "in"
  - from: "SortIteratorByComparator1"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "AddObjectToVector2"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "FromString1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "SortIteratorByComparator1"
    into: "in"
  - from: "GetPermissionsByUser2"
    via: "next"
    to: "CombineMaps1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetPermissionsByUser1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Loop1"
    via: "do"
    to: "CallNode1"
    into: "in"
