flow: "ProcessReplicationProcess"
kind: "process"

entries:
  - id: "StartNode1"
    name: "Create"
    mode: "private"
    strict: true
    inputs:
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true
      - key: "Description"
        type: "java.lang.String"
        required: true
      - key: "ReplicationProcessID"
        type: "java.lang.String"
        required: true
      - key: "TargetCluster"
        type: "com.intershop.beehive.core.capi.staging.TargetSystem"
        required: true
      - key: "ReplicationType"
        type: "java.lang.String"
        required: true
      - key: "StartTime"
        type: "java.lang.String"
        required: false
  - id: "StartNode2"
    name: "Remove"
    mode: "private"
    strict: true
    inputs:
      - key: "ReplicationProcess"
        type: "com.intershop.beehive.core.capi.replication.ReplicationProcess"
        required: true
  - id: "StartNode3"
    name: "CreateFromConfiguration"
    mode: "private"
    strict: true
    inputs:
      - key: "ReplicationProcessID"
        type: "java.lang.String"
        required: true
  - id: "StartNode5"
    name: "Error"
    mode: "private"
    strict: true
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessReplicationProcess-Create"
  - id: "CreateReplicationProcess1"
    type: "pipelet"
    ref: "CreateReplicationProcess"
    bindings:
      Domain: "Organization:Domain"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "ReplicationProcess"
        type: "com.intershop.beehive.core.capi.replication.ReplicationProcess"
        guaranteed: true
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "ReplicationProcess"
        type: "com.intershop.beehive.core.capi.replication.ReplicationProcess"
        guaranteed: true
  - id: "EndNode7"
    type: "end"
    strict: true
  - id: "ExecutePipeline1"
    type: "pipelet"
    ref: "ExecutePipeline"
    config:
      Asynchronous: false
      PipelineName: "ProcessReplicationTask"
      PipelineStartNode: "CreateAndAssign"
    bindings:
      PipelineDomain: "ReplicationTaskOrganization:Domain:Site"
  - id: "GetOrganizationByName1"
    type: "pipelet"
    ref: "GetOrganizationByName"
    bindings:
      Name: "OrganizationID"
      Organization: "ReplicationTaskOrganization"
  - id: "GetOrganizationByName2"
    type: "pipelet"
    ref: "GetOrganizationByName"
    bindings:
      Name: "\"Operations\""
  - id: "GetReplicationProcessConfig1"
    type: "pipelet"
    ref: "GetReplicationProcessConfig"
  - id: "GetReplicationTaskConfig1"
    type: "pipelet"
    ref: "GetReplicationTaskConfig"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ProcessReplicationProcess-Error"
  - id: "LogMessage1"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Level: "Error"
    bindings:
      MessageText: "\"Error finding organization with name: {}\""
      MessageParam0: "OrganizationID"
  - id: "LogMessage2"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Level: "Error"
    bindings:
      MessageParam0: "ReplicationTaskName"
      MessageText: "\"Error creating replication task with name: {}\""
  - id: "LoopNode1"
    type: "loop"
  - id: "ReloadReplicationConfiguration1"
    type: "pipelet"
    ref: "ReloadReplicationConfiguration"
  - id: "RemoveReplicationProcess1"
    type: "pipelet"
    ref: "RemoveReplicationProcess"
  - id: "UpdateReplicationProcess1"
    type: "pipelet"
    ref: "UpdateReplicationProcess"
    bindings:
      Description: "Description"
      Locale: "CurrentSession:Locale"
      ProcessID: "ReplicationProcessID"
      State: "\"WAITING\""
      TargetSystem: "TargetSystem:Name"
      Type: "ReplicationType"

links:
  - from: "CreateReplicationProcess1"
    via: "next"
    to: "UpdateReplicationProcess1"
    into: "in"
  - from: "LogMessage1"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "GetReplicationProcessConfig1"
    via: "next"
    to: "GetOrganizationByName2"
    into: "in"
  - from: "GetReplicationTaskConfig1"
    via: "next"
    to: "GetOrganizationByName1"
    into: "in"
  - from: "GetOrganizationByName1"
    via: "next"
    to: "ExecutePipeline1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "GetReplicationTaskConfig1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "ExecutePipeline1"
    via: "error"
    to: "LogMessage2"
    into: "in"
  - from: "LogMessage2"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CreateReplicationProcess1"
    into: "in"
  - from: "GetOrganizationByName2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "ExecutePipeline1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetOrganizationByName1"
    via: "error"
    to: "LogMessage1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "ReloadReplicationConfiguration1"
    into: "in"
  - from: "UpdateReplicationProcess1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "ReloadReplicationConfiguration1"
    via: "next"
    to: "GetReplicationProcessConfig1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "GetReplicationTaskConfig1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "RemoveReplicationProcess1"
    into: "in"
  - from: "RemoveReplicationProcess1"
    via: "next"
    to: "EndNode1"
    into: "in"
