flow: "ProcessProductConfigurationSectionTemplate"
kind: "process"

entries:
  - id: "StartNode1"
    name: "Create"
    mode: "private"
    strict: true
    inputs:
      - key: "ID"
        type: "java.lang.String"
        required: true
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "SectionGroup"
        type: "java.lang.String"
        required: false
      - key: "Description"
        type: "java.lang.String"
        required: false
      - key: "MessageType"
        type: "java.lang.String"
        required: false
  - id: "StartNode10"
    name: "MultipleRemove"
    mode: "private"
    strict: true
    inputs:
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "SectionTemplateIDs"
        type: "java.util.Iterator"
        required: true
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: true
    inputs:
      - key: "ID"
        type: "java.lang.String"
        required: false
      - key: "SectionGroup"
        type: "java.lang.String"
        required: false
      - key: "Description"
        type: "java.lang.String"
        required: false
      - key: "MessageType"
        type: "java.lang.String"
        required: false
      - key: "ProductConfigurationSectionTemplate"
        type: "com.intershop.component.productconfiguration.capi.orm.template.ProductConfigurationSectionTemplate"
        required: true
  - id: "StartNode3"
    name: "GetSectionTemplatesSorted"
    mode: "private"
    strict: true
    inputs:
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "SortAttribute"
        type: "java.lang.String"
        required: false
      - key: "SortOrder"
        type: "java.lang.String"
        required: false
      - key: "PageSize"
        type: "java.lang.Integer"
        required: false
  - id: "StartNode4"
    name: "Remove"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductConfigurationSectionTemplate"
        type: "com.intershop.component.productconfiguration.capi.orm.template.ProductConfigurationSectionTemplate"
        required: false
  - id: "StartNode5"
    name: "Copy"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductConfigurationSectionTemplate"
        type: "com.intershop.component.productconfiguration.capi.orm.template.ProductConfigurationSectionTemplate"
        required: true
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
  - id: "StartNode6"
    name: "MultipleCopy"
    mode: "private"
    strict: true
    inputs:
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "SectionTemplateIDs"
        type: "java.util.Iterator"
        required: true
      - key: "TargetDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessProductConfigurationSectionTemplate-Remove"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessProductConfigurationSectionTemplate-Copy"
    bindings:
      Domain: "TargetDomain"
  - id: "CheckForEmptyString1"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "SortAttribute"
  - id: "CopyProductConfigurationSectionTemplate1"
    type: "pipelet"
    ref: "CopyProductConfigurationSectionTemplate"
  - id: "CreateProductConfigurationSectionTemplate1"
    type: "pipelet"
    ref: "CreateProductConfigurationSectionTemplate"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ProductConfigurationSectionTemplate"
        type: "com.intershop.component.productconfiguration.capi.orm.template.ProductConfigurationSectionTemplate"
        guaranteed: true
  - id: "EndNode12"
    type: "end"
    strict: true
  - id: "EndNode17"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "CopiedProductConfigurationSectionTemplate"
        type: "com.intershop.component.productconfiguration.capi.orm.template.ProductConfigurationSectionTemplate"
        guaranteed: true
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "ProductConfigurationSectionTemplate"
        type: "com.intershop.component.productconfiguration.capi.orm.template.ProductConfigurationSectionTemplate"
        guaranteed: true
  - id: "EndNode5"
    type: "end"
    strict: true
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "SectionTemplates"
        type: "java.util.Iterator"
        guaranteed: true
  - id: "EndNode7"
    type: "end"
    strict: true
  - id: "EndNode8"
    type: "end"
    strict: true
  - id: "ExecutePageableQuery2"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      DefaultPageSize: 15
      QueryName: "productconfiguration/template/SearchAllSectionTemplatesSorted"
    bindings:
      SearchResult: "SectionTemplates"
      Parameters: "ImageViewSearchParameters"
      ErrorCode: "SearchError"
  - id: "GetProductConfigurationSectionTemplateByID1"
    type: "pipelet"
    ref: "GetProductConfigurationSectionTemplateByID"
    bindings:
      ID: "SectionTemplateID"
  - id: "GetProductConfigurationSectionTemplateByID2"
    type: "pipelet"
    ref: "GetProductConfigurationSectionTemplateByID"
    bindings:
      ID: "SectionTemplateID"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"id\""
      OutValue_1: "SortAttribute"
      InValue_2: "\"asc\""
      OutValue_2: "SortOrder"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode4"
    type: "loop"
  - id: "RemoveProductConfigurationSectionTemplate1"
    type: "pipelet"
    ref: "RemoveProductConfigurationSectionTemplate"
  - id: "UpdateCustomAttribute1"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    config:
      DefaultAttributeName: "MessageType"
      DefaultAttributeType: "String"
    bindings:
      AttributeName: "null"
      AttributeType: "null"
      ExtensibleObject: "ProductConfigurationSectionTemplate"
      AttributeValue: "MessageType"
  - id: "UpdateCustomAttribute2"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    config:
      DefaultAttributeName: "MessageType"
      DefaultAttributeType: "String"
    bindings:
      AttributeName: "null"
      AttributeType: "null"
      ExtensibleObject: "ProductConfigurationSectionTemplate"
      AttributeValue: "MessageType"
  - id: "UpdateDictionary2"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "Domain"
      Name_02: "SortOrder"
      Name_03: "SortAttribute"
    bindings:
      Value_01: "Domain"
      OutDictionary: "ImageViewSearchParameters"
      InDictionary: "null"
      Value_02: "SortOrder"
      Value_03: "SortAttribute"
  - id: "UpdateProductConfigurationSectionTemplate1"
    type: "pipelet"
    ref: "UpdateProductConfigurationSectionTemplate"
    bindings:
      ID: "null"
  - id: "UpdateProductConfigurationSectionTemplate2"
    type: "pipelet"
    ref: "UpdateProductConfigurationSectionTemplate"

links:
  - from: "StartNode1"
    via: "next"
    to: "CreateProductConfigurationSectionTemplate1"
    into: "in"
  - from: "LoopNode4"
    via: "next"
    to: "EndNode12"
    into: "in"
  - from: "LoopNode4"
    via: "do"
    to: "GetProductConfigurationSectionTemplateByID1"
    into: "in"
  - from: "GetProductConfigurationSectionTemplateByID1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "RemoveProductConfigurationSectionTemplate1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "GetProductConfigurationSectionTemplateByID1"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "UpdateCustomAttribute2"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "UpdateProductConfigurationSectionTemplate2"
    via: "next"
    to: "UpdateCustomAttribute2"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "error"
    to: "KeyMapper1"
    into: "in"
  - from: "CreateProductConfigurationSectionTemplate1"
    via: "next"
    to: "UpdateProductConfigurationSectionTemplate1"
    into: "in"
  - from: "UpdateDictionary2"
    via: "next"
    to: "ExecutePageableQuery2"
    into: "in"
  - from: "ExecutePageableQuery2"
    via: "error"
    to: "EndNode17"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "UpdateProductConfigurationSectionTemplate2"
    into: "in"
  - from: "ExecutePageableQuery2"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "CopyProductConfigurationSectionTemplate1"
    via: "error"
    to: "EndNode7"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CopyProductConfigurationSectionTemplate1"
    into: "in"
  - from: "GetProductConfigurationSectionTemplateByID2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CopyProductConfigurationSectionTemplate1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "LoopNode1"
    via: "do"
    to: "GetProductConfigurationSectionTemplateByID2"
    into: "in"
  - from: "StartNode10"
    via: "next"
    to: "LoopNode4"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetProductConfigurationSectionTemplateByID2"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CheckForEmptyString1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "CheckForEmptyString1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "UpdateDictionary2"
    into: "in"
  - from: "CreateProductConfigurationSectionTemplate1"
    via: "error"
    to: "EndNode2"
    into: "in"
  - from: "UpdateProductConfigurationSectionTemplate1"
    via: "next"
    to: "UpdateCustomAttribute1"
    into: "in"
  - from: "UpdateCustomAttribute1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "LoopNode4"
    into: "loop"
  - from: "RemoveProductConfigurationSectionTemplate1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode4"
    via: "next"
    to: "RemoveProductConfigurationSectionTemplate1"
    into: "in"
