flow: "ProcessPageletEntryPointFilters"
kind: "process"

entries:
  - id: "StartNode2"
    name: "UpdateProductSearchParameters"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "GetQueryParamsFromSubmittedSelection"
    mode: "private"
    strict: true
    inputs:
      - key: "AssignmentSelection"
        type: "java.lang.String"
        required: false
      - key: "AssignedToContentEntryPointDefinitionInclusion"
        type: "java.lang.String"
        required: false
      - key: "NotAssignedToContentEntryPointDefinitionInclusion"
        type: "java.lang.String"
        required: false
  - id: "StartNode4"
    name: "GetAssignmentDefinitionNamesFromSubmittedSelection"
    mode: "private"
    strict: true
    inputs:
      - key: "SelectedContextObjectRelationExtension"
        type: "java.lang.String"
        required: false
  - id: "StartNode5"
    name: "UpdatePageletSearchParameters"
    mode: "private"
    strict: true
    inputs:
      - key: "SearchParameters"
        type: "java.util.Map"
        required: true

steps:
  - id: "CallNode3"
    type: "call"
    ref: "This:GetQueryParamsFromSubmittedSelection"
    bindings:
      AssignmentSelection: "WFAdvancedSearch_PageAssignments"
      AssignedToContentEntryPointDefinitionInclusion: "WFAdvancedSearch_AssignedToPageType"
      NotAssignedToContentEntryPointDefinitionInclusion: "WFAdvancedSearch_NotAssignedToPageType"
      SelectedContentEntryPointDefinitionInclusion: "PageEntryPointDefinitionInclusion"
  - id: "CallNode4"
    type: "call"
    ref: "This:GetQueryParamsFromSubmittedSelection"
    bindings:
      AssignmentSelection: "WFAdvancedSearch_IncludeAssignments"
      NotAssignedToContentEntryPointDefinitionInclusion: "WFAdvancedSearch_NotAssignedToIncludeType"
      AssignedToContentEntryPointDefinitionInclusion: "WFAdvancedSearch_AssignedToIncludeType"
      SelectedContentEntryPointDefinitionInclusion: "ComponentEntryPointDefinitionInclusion"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessPageletEntryPointFilters-GetAssignmentDefinitionNamesFromSubmittedSelection"
    bindings:
      SelectedContextObjectRelationExtension: "SearchParameters:AssignedToProductPageIncludeType"
      SelectedCotentViewDefinition: "AssignedToProductContextObjectRelation"
      SelectedPageletEntryPointDefinition: "AssignedToProductPageletEntryPointDefinition"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessPageletEntryPointFilters-GetAssignmentDefinitionNamesFromSubmittedSelection"
    bindings:
      SelectedContextObjectRelationExtension: "SearchParameters:AssignedToCategoryPageIncludeType"
      SelectedCotentViewDefinition: "AssignedToCategoryContextObjectRelation"
      SelectedPageletEntryPointDefinition: "AssignedToCategoryPageletEntryPointDefinition"
  - id: "CreateStringSplitter1"
    type: "pipelet"
    ref: "CreateStringSplitter"
    config:
      Mode: "First Occurrence"
      Separator: "::"
    bindings:
      Splitter: "SelectedDefinitionSplitter"
  - id: "DecisionNode2"
    type: "decision"
    condition: "AssignmentSelection"
  - id: "DecisionNode3"
    type: "decision"
    condition: "SelectedContextObjectRelationExtension"
  - id: "DecisionNode4"
    type: "decision"
    condition: "SelectedContextObjectRelationExtension"
  - id: "DecisionNode5"
    type: "decision"
    condition: "AssignmentSelection"
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "SelectedContentEntryPointDefinitionInclusion"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "SelectedCotentViewDefinition"
        type: "java.lang.String"
        guaranteed: false
      - key: "SelectedPageletEntryPointDefinition"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode5"
    type: "end"
    strict: true
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "AssignedToContentEntryPointDefinitionInclusion"
      OutValue_1: "SelectedContentEntryPointDefinitionInclusion"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "NotAssignedToContentEntryPointDefinitionInclusion"
      OutValue_1: "SelectedContentEntryPointDefinitionInclusion"
  - id: "KeyMapper7"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "SelectedDefinitionSplitter:Begin(SelectedContextObjectRelationExtension)"
      InValue_2: "SelectedDefinitionSplitter:End(SelectedContextObjectRelationExtension)"
      OutValue_1: "SelectedCotentViewDefinition"
      OutValue_2: "SelectedPageletEntryPointDefinition"
  - id: "UpdateDictionary1"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "PageAssignmentsSelection"
      Name_02: "PageEntryPointDefinitionInclusion"
      Name_04: "IncludeAssignmentsSelection"
      Name_05: "ComponentEntryPointDefinitionInclusion"
    bindings:
      OutDictionary: "AdvancedSearchParameters"
      Value_04: "WFAdvancedSearch_IncludeAssignments"
      Value_01: "WFAdvancedSearch_PageAssignments"
      Value_02: "PageEntryPointDefinitionInclusion"
      Value_05: "ComponentEntryPointDefinitionInclusion"
      InDictionary: "AdvancedSearchParameters"
  - id: "UpdateDictionary13"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_03: "AssignedToCategoryContextObjectRelation"
      Name_04: "AssignedToCategoryPageletEntryPointDefinition"
      Name_01: "AssignedToProductContextObjectRelation"
      Name_02: "AssignedToProductPageletEntryPointDefinition"
    bindings:
      InDictionary: "SearchParameters"
      Value_03: "AssignedToCategoryContextObjectRelation"
      Value_04: "AssignedToCategoryPageletEntryPointDefinition"
      Value_01: "AssignedToProductContextObjectRelation"
      Value_02: "AssignedToProductPageletEntryPointDefinition"

links:
  - from: "CallNode3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "CreateStringSplitter1"
    via: "next"
    to: "KeyMapper7"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "CreateStringSplitter1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "UpdateDictionary1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode3"
    into: "in2"
  - from: "KeyMapper7"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode5"
    via: "yes"
    to: "KeyMapper2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "UpdateDictionary1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "UpdateDictionary13"
    into: "in"
  - from: "UpdateDictionary13"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "KeyMapper1"
    into: "in"
