flow: "ProcessDate"
kind: "process"

entries:
  - id: "StartNode1"
    name: "VerifyDatePeriod"
    mode: "private"
    strict: true
    inputs:
      - key: "ValidFrom_Day"
        type: "java.lang.String"
        required: false
      - key: "ValidTo_Day"
        type: "java.lang.String"
        required: false
  - id: "StartNode10"
    name: "VerifyPeriod"
    mode: "private"
    strict: true
    inputs:
      - key: "DatePattern"
        type: "java.lang.String"
        required: false
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: false
      - key: "PeriodFlag"
        type: "java.lang.String"
        required: true
      - key: "ValidFrom_Day"
        type: "java.lang.String"
        required: false
      - key: "ValidFrom_Time"
        type: "java.lang.String"
        required: false
      - key: "ValidTo_Day"
        type: "java.lang.String"
        required: false
      - key: "ValidTo_Time"
        type: "java.lang.String"
        required: false
  - id: "StartNode2"
    name: "ConvertPeriodToString"
    mode: "private"
    strict: true
    inputs:
      - key: "ValidFromDate"
        type: "java.util.Date"
        required: false
      - key: "ValidToDate"
        type: "java.util.Date"
        required: false
  - id: "StartNode3"
    name: "ConvertPeriodToDate"
    mode: "private"
    strict: true
    inputs:
      - key: "ValidFromString"
        type: "java.lang.String"
        required: false
      - key: "ValidToString"
        type: "java.lang.String"
        required: false

steps:
  - id: "CalculateDate1"
    type: "pipelet"
    ref: "CalculateDate"
    config:
      DefaultDays: 1
    bindings:
      Date: "ValidTo"
      CalculatedDate: "ValidTo"
  - id: "CalculateDate2"
    type: "pipelet"
    ref: "CalculateDate"
    config:
      CalculationMethod: "Subtract"
    bindings:
      Date: "ValidTo"
      CalculatedDate: "ValidTo"
      Minutes: "ValidTo:TimezoneOffset"
  - id: "CalculateDate3"
    type: "pipelet"
    ref: "CalculateDate"
    config:
      CalculationMethod: "Subtract"
    bindings:
      Date: "ValidFrom"
      CalculatedDate: "ValidFrom"
      Minutes: "ValidFrom:TimezoneOffset"
  - id: "CheckForEmptyString1"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "ValidFrom_Day"
  - id: "CheckForEmptyString2"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "ValidFrom_Time"
  - id: "CheckForEmptyString3"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "ValidTo_Time"
  - id: "CheckForEmptyString4"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "ValidTo_Day"
  - id: "CheckForEmptyString5"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "ValidFrom_Day"
  - id: "CheckForEmptyString6"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "ValidTo_Day"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "ValidFrom_Day"
      String2: "ValidFrom_Time"
      String1: "\",\""
      Concatenated: "ValidFrom"
  - id: "ConcatenateStrings2"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "ValidTo_Day"
      String2: "ValidTo_Time"
      String1: "\",\""
      Concatenated: "ValidTo"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ValidFrom:Time"
  - id: "DecisionNode10"
    type: "decision"
    condition: "ValidToString"
  - id: "DecisionNode11"
    type: "decision"
    condition: "ValidFromString"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ValidTo:Time"
  - id: "DecisionNode3"
    type: "decision"
    condition: "ValidFrom:Time"
  - id: "DecisionNode4"
    type: "decision"
    condition: "PeriodFlag"
  - id: "DecisionNode5"
    type: "decision"
    condition: "ValidFrom:Time"
  - id: "DecisionNode6"
    type: "decision"
    condition: "ValidTo:Time"
  - id: "DecisionNode7"
    type: "decision"
    condition: "ValidFrom:Time"
  - id: "DecisionNode8"
    type: "decision"
    condition: "ValidFromDate"
  - id: "DecisionNode9"
    type: "decision"
    condition: "ValidToDate"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ValidFrom"
        type: "java.util.Date"
        guaranteed: false
      - key: "ValidTo"
        type: "java.util.Date"
        guaranteed: false
  - id: "EndNode10"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorPeriodIncorrect"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode11"
    type: "end"
    strict: true
    outputs:
      - key: "ValidFromDate"
        type: "java.util.Date"
        guaranteed: false
      - key: "ValidToDate"
        type: "java.util.Date"
        guaranteed: false
  - id: "EndNode12"
    type: "end"
    strict: true
    outputs:
      - key: "ValidFromString"
        type: "java.lang.String"
        guaranteed: false
      - key: "ValidToString"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorValidFromIncorrect"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "PeriodFlag"
        type: "java.lang.Boolean"
        guaranteed: true
      - key: "ValidFrom"
        type: "java.util.Date"
        guaranteed: false
      - key: "ValidTo"
        type: "java.util.Date"
        guaranteed: false
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorValidToIncorrect"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "PeriodFlag"
        type: "java.lang.Boolean"
        guaranteed: true
      - key: "ValidFrom_Day"
        type: "java.lang.String"
        guaranteed: false
      - key: "ValidFrom_Time"
        type: "java.lang.String"
        guaranteed: false
      - key: "ValidTo_Day"
        type: "java.lang.String"
        guaranteed: false
      - key: "ValidTo_Time"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorPeriodIncorrect"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode7"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorCode"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode8"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorValidFromIncorrect"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode9"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorValidToIncorrect"
        type: "java.lang.String"
        guaranteed: true
  - id: "GetFormattedDate1"
    type: "pipelet"
    ref: "GetFormattedDate"
    config:
      Pattern: "yyyyMMddHHmmss"
    bindings:
      InDate: "ValidFromDate"
      FormattedDate: "ValidFromString"
  - id: "GetFormattedDate2"
    type: "pipelet"
    ref: "GetFormattedDate"
    config:
      Pattern: "yyyyMMddHHmmss"
    bindings:
      InDate: "ValidToDate"
      FormattedDate: "ValidToString"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode15"
    type: "join"
  - id: "JoinNode16"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "DatePattern"
      InValue_1: "CurrentSession:Locale:DefaultRegionalSettings:inputDatePattern"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "\"\""
      InValue_3: "\"\""
      InValue_4: "\"\""
      OutValue_4: "ValidTo_Day"
      OutValue_3: "ValidTo_Time"
      OutValue_2: "ValidFrom_Time"
      OutValue_1: "ValidFrom_Day"
      InValue_2: "\"\""
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"\""
      InValue_3: "\"\""
      InValue_4: "\"\""
      OutValue_4: "ValidTo_Day"
      OutValue_3: "ValidTo_Time"
      OutValue_2: "ValidFrom_Time"
      OutValue_1: "ValidFrom_Day"
      InValue_2: "\"\""
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "ValidFromString"
      OutValue_1: "ValidFromString"
      InValue_2: "ValidToString"
      OutValue_2: "ValidToString"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorPeriodIncorrect"
      Value: true
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorPeriodIncorrect"
      Value: true
  - id: "TextNode1"
    type: "text"
  - id: "VerifyBoolean1"
    type: "pipelet"
    ref: "VerifyBoolean"
    bindings:
      NoneLocalizedString: "PeriodFlag"
      BooleanValue: "PeriodFlag"
  - id: "VerifyDate1"
    type: "pipelet"
    ref: "VerifyDate"
    bindings:
      DateString: "ValidFrom"
      Date: "ValidFrom"
      DateIncorrect: "ErrorValidFromIncorrect"
      Locale: "CurrentRequest:Locale"
  - id: "VerifyDate2"
    type: "pipelet"
    ref: "VerifyDate"
    bindings:
      DateString: "ValidTo"
      Date: "ValidTo"
      DateIncorrect: "ErrorValidToIncorrect"
      Locale: "CurrentRequest:Locale"
  - id: "VerifyDate3"
    type: "pipelet"
    ref: "VerifyDate"
    bindings:
      DateString: "ValidFrom_Day"
      Date: "ValidFrom"
      DateIncorrect: "ErrorValidFromIncorrect"
      Locale: "CurrentSession:Locale"
  - id: "VerifyDate4"
    type: "pipelet"
    ref: "VerifyDate"
    bindings:
      DateString: "ValidTo_Day"
      Date: "ValidTo"
      DateIncorrect: "ErrorValidToIncorrect"
      Locale: "CurrentSession:Locale"
  - id: "VerifyDate5"
    type: "pipelet"
    ref: "VerifyDate"
    bindings:
      DatePattern: "\"yyyyMMddHHmmss\""
      DateString: "ValidFromString"
      Locale: "null"
      Date: "ValidFromDate"
  - id: "VerifyDate6"
    type: "pipelet"
    ref: "VerifyDate"
    bindings:
      DatePattern: "\"yyyyMMddHHmmss\""
      DateString: "ValidToString"
      Locale: "null"
      Date: "ValidToDate"

links:
  - from: "ConcatenateStrings1"
    via: "next"
    to: "VerifyDate1"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "VerifyBoolean1"
    via: "error"
    to: "EndNode7"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "DecisionNode7"
    into: "in"
  - from: "JoinNode12"
    via: "next"
    to: "CheckForEmptyString4"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode15"
    into: "in2"
  - from: "ConcatenateStrings2"
    via: "next"
    to: "VerifyDate2"
    into: "in"
  - from: "VerifyDate2"
    via: "next"
    to: "JoinNode13"
    into: "in1"
  - from: "JoinNode14"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "error"
    to: "CheckForEmptyString2"
    into: "in"
  - from: "VerifyBoolean1"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode15"
    into: "in1"
  - from: "JoinNode15"
    via: "next"
    to: "JoinNode14"
    into: "in2"
  - from: "VerifyDate1"
    via: "error"
    to: "EndNode8"
    into: "in"
  - from: "JoinNode13"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "JoinNode14"
    into: "in1"
  - from: "CheckForEmptyString3"
    via: "next"
    to: "JoinNode11"
    into: "in3"
  - from: "DecisionNode5"
    via: "yes"
    to: "DecisionNode6"
    into: "in"
  - from: "JoinNode11"
    via: "next"
    to: "ConcatenateStrings2"
    into: "in"
  - from: "CheckForEmptyString2"
    via: "error"
    to: "JoinNode12"
    into: "in3"
  - from: "DecisionNode4"
    via: "no"
    to: "KeyMapper2"
    into: "in"
  - from: "VerifyDate2"
    via: "error"
    to: "EndNode4"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "CheckForEmptyString4"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "CheckForEmptyString3"
    via: "error"
    to: "JoinNode13"
    into: "in3"
  - from: "StartNode1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "CheckForEmptyString5"
    via: "next"
    to: "VerifyDate3"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "CheckForEmptyString5"
    into: "in"
  - from: "CheckForEmptyString5"
    via: "error"
    to: "JoinNode3"
    into: "in3"
  - from: "CheckForEmptyString6"
    via: "next"
    to: "VerifyDate4"
    into: "in"
  - from: "CheckForEmptyString4"
    via: "error"
    to: "CheckForEmptyString3"
    into: "in"
  - from: "VerifyDate4"
    via: "next"
    to: "CalculateDate1"
    into: "in"
  - from: "VerifyDate3"
    via: "error"
    to: "EndNode2"
    into: "in"
  - from: "CalculateDate1"
    via: "next"
    to: "CalculateDate2"
    into: "in"
  - from: "VerifyDate4"
    via: "error"
    to: "EndNode9"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "DecisionNode3"
    via: "no"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "EndNode10"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "DecisionNode3"
    into: "in"
  - from: "VerifyDate1"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "CalculateDate2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "JoinNode1"
    into: "in1"
  - from: "CheckForEmptyString6"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "VerifyDate5"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "CheckForEmptyString6"
    into: "in"
  - from: "VerifyDate3"
    via: "next"
    to: "CalculateDate3"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CalculateDate3"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode4"
    via: "yes"
    to: "CheckForEmptyString1"
    into: "in"
  - from: "DecisionNode11"
    via: "yes"
    to: "VerifyDate5"
    into: "in"
  - from: "DecisionNode8"
    via: "yes"
    to: "GetFormattedDate1"
    into: "in"
  - from: "DecisionNode8"
    via: "no"
    to: "JoinNode6"
    into: "in2"
  - from: "DecisionNode10"
    via: "no"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode9"
    via: "no"
    to: "JoinNode5"
    into: "in2"
  - from: "DecisionNode10"
    via: "yes"
    to: "VerifyDate6"
    into: "in"
  - from: "VerifyDate6"
    via: "next"
    to: "JoinNode16"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "DecisionNode11"
    into: "in"
  - from: "GetFormattedDate2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode8"
    into: "in"
  - from: "StartNode10"
    via: "next"
    to: "VerifyBoolean1"
    into: "in"
  - from: "JoinNode16"
    via: "next"
    to: "EndNode11"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "DecisionNode9"
    into: "in"
  - from: "GetFormattedDate1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "KeyMapper4"
    via: "next"
    to: "EndNode12"
    into: "in"
  - from: "DecisionNode11"
    via: "no"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode10"
    into: "in2"
  - from: "VerifyDate6"
    via: "error"
    to: "JoinNode8"
    into: "in2"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode16"
    into: "in2"
  - from: "VerifyDate5"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "JoinNode9"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "DecisionNode9"
    via: "yes"
    to: "GetFormattedDate2"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "DecisionNode10"
    into: "in"
  - from: "CheckForEmptyString2"
    via: "next"
    to: "JoinNode9"
    into: "in3"
