flow: "ProcessTimeZones"
kind: "include"

entries:
  - id: "StartNode0"
    name: "IsTimeZoneSettingEnabled"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode1"
    name: "GetTimeZoneBORepository"
    mode: "private"
    strict: true
    inputs:
      - key: "ApplicationBO"
        type: "com.intershop.component.application.capi.ApplicationBO"
        required: false
  - id: "StartNode2"
    name: "DetermineSessionTimeZoneBO"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentSession"
        type: "com.intershop.beehive.core.capi.request.Session"
        required: true
      - key: "CurrentUser"
        type: "com.intershop.beehive.core.capi.user.User"
        required: true
      - key: "TimeZoneBORepository"
        type: "com.intershop.component.i18n.capi.timezone.TimeZoneBORepository"
        required: true
  - id: "StartNode3"
    name: "SetUserTimeZone"
    mode: "private"
    strict: true
    inputs:
      - key: "User"
        type: "com.intershop.beehive.core.capi.user.User"
        required: true
      - key: "TimeZoneBORepository"
        type: "com.intershop.component.i18n.capi.timezone.TimeZoneBORepository"
        required: false
      - key: "TimeZoneID"
        type: "java.lang.String"
        required: false
  - id: "StartNode4"
    name: "SetSessionTimeZone"
    mode: "private"
    strict: true
    inputs:
      - key: "TimeZoneID"
        type: "java.lang.String"
        required: true
      - key: "CurrentUser"
        type: "com.intershop.beehive.core.capi.user.User"
        required: true
      - key: "TimeZoneBORepository"
        type: "com.intershop.component.i18n.capi.timezone.TimeZoneBORepository"
        required: false
  - id: "StartNode5"
    name: "InitializeUserTimeZone"
    mode: "private"
    strict: true
    inputs:
      - key: "User"
        type: "com.intershop.beehive.core.capi.user.User"
        required: true
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true
  - id: "StartNode6"
    name: "AddServerTimeZoneToAllUsers"
    mode: "private"
    strict: true
    inputs:
      []

steps:
  - id: "CallNode0"
    type: "call"
    ref: "This:GetTimeZoneBORepository"
  - id: "CallNode1"
    type: "call"
    ref: "This:GetTimeZoneBORepository"
  - id: "CallNode2"
    type: "call"
    ref: "This:SetUserTimeZone"
    bindings:
      User: "CurrentUser"
  - id: "CallNode3"
    type: "call"
    ref: "This:SetUserTimeZone"
  - id: "DecisionNode0"
    type: "decision"
    condition: "IsTimeZoneSettingEnabled"
  - id: "DecisionNode1"
    type: "decision"
    condition: "TimeZoneBORepository"
  - id: "DecisionNode2"
    type: "decision"
    condition: "TimeZoneID"
  - id: "DecisionNode3"
    type: "decision"
    condition: "TimeZoneBORepository"
  - id: "DecisionNode4"
    type: "decision"
    condition: "ApplicationBO"
  - id: "DecisionNode5"
    type: "decision"
    condition: "Organization:TypeCode"
  - id: "DecisionNode6"
    type: "decision"
    condition: "Organization:TypeCode"
  - id: "EndNode0"
    type: "end"
    strict: true
    outputs:
      - key: "IsTimeZoneSettingEnabled"
        type: "java.lang.Boolean"
        guaranteed: true
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "TimeZoneBORepository"
        type: "com.intershop.component.i18n.capi.timezone.TimeZoneBORepository"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "TimeZoneBO"
        type: "com.intershop.component.i18n.capi.timezone.TimeZoneBO"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "IsTimeZoneSettingEnabled"
        type: "java.lang.Boolean"
        guaranteed: true
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "TimeZoneBO"
        type: "com.intershop.component.i18n.capi.timezone.TimeZoneBO"
        guaranteed: true
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "TimeZoneBO"
        type: "com.intershop.component.i18n.capi.timezone.TimeZoneBO"
        guaranteed: true
  - id: "EndNode6"
    type: "end"
    strict: true
  - id: "EndNode7"
    type: "end"
    strict: true
  - id: "ExecuteUpdateQuery0"
    type: "pipelet"
    ref: "ExecuteUpdateQuery"
    config:
      QueryName: "user/AddTimeZoneToAllUsers"
      ParameterName_01: "TimeZoneID"
    bindings:
      ParameterValue_01: "ServerTimeZoneBO:ID"
  - id: "GetApplicationBO0"
    type: "pipelet"
    ref: "GetApplicationBO"
  - id: "GetApplicationBO1"
    type: "pipelet"
    ref: "GetApplicationBO"
  - id: "GetServerTimeZoneBO0"
    type: "pipelet"
    ref: "GetServerTimeZoneBO"
    bindings:
      ServerTimeZoneBO: "TimeZoneBO"
  - id: "GetServerTimeZoneBO1"
    type: "pipelet"
    ref: "GetServerTimeZoneBO"
    bindings:
      ServerTimeZoneBO: "TimeZoneBO"
  - id: "GetServerTimeZoneBO2"
    type: "pipelet"
    ref: "GetServerTimeZoneBO"
    bindings:
      TimeZoneBORepository: "ApplicationBO:Repository(\"TimeZoneBORepository\")"
  - id: "GetSessionTimeZoneBO0"
    type: "pipelet"
    ref: "GetSessionTimeZoneBO"
    bindings:
      Session: "CurrentSession"
  - id: "GetTimeZoneBOByID1"
    type: "pipelet"
    ref: "GetTimeZoneBOByID"
  - id: "GetUserTimeZoneBO0"
    type: "pipelet"
    ref: "GetUserTimeZoneBO"
    bindings:
      User: "CurrentUser"
  - id: "JoinNode0"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Repository(\"TimeZoneBORepository\")"
      InValue_2: "null"
      InValue_10: "null"
      InValue_3: "null"
      InValue_4: "null"
      InValue_5: "null"
      InValue_6: "null"
      InValue_7: "null"
      InValue_8: "null"
      InValue_9: "null"
      OutValue_1: "TimeZoneBORepository"
      OutValue_10: "null"
      OutValue_2: "null"
      OutValue_4: "null"
      OutValue_3: "null"
      OutValue_5: "null"
      OutValue_6: "null"
      OutValue_7: "null"
      OutValue_8: "null"
      OutValue_9: "null"
  - id: "SetSessionTimeZoneBO0"
    type: "pipelet"
    ref: "SetSessionTimeZoneBO"
    bindings:
      Session: "CurrentSession"
  - id: "SetSessionTimeZoneBO1"
    type: "pipelet"
    ref: "SetSessionTimeZoneBO"
    bindings:
      Session: "CurrentSession"
  - id: "SetUserTimeZoneBO0"
    type: "pipelet"
    ref: "SetUserTimeZoneBO"
    bindings:
      User: "User"
  - id: "Text3"
    type: "text"
  - id: "Text4"
    type: "text"
  - id: "VerifyBoolean0"
    type: "pipelet"
    ref: "VerifyBoolean"
    bindings:
      NoneLocalizedString: "CurrentDomain:Configuration:String(\"intershop.feature.timezone.enabled\",\"false\")"
      BooleanValue: "IsTimeZoneSettingEnabled"

links:
  - from: "CallNode0"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "SetSessionTimeZoneBO1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "DecisionNode0"
    via: "no"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode0"
    via: "yes"
    to: "EndNode0"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "CallNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "GetTimeZoneBOByID1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "CallNode0"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode4"
    via: "no"
    to: "GetApplicationBO0"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode5"
    via: "no"
    to: "DecisionNode6"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode9"
    into: "in1"
  - from: "DecisionNode6"
    via: "yes"
    to: "JoinNode8"
    into: "in1"
  - from: "ExecuteUpdateQuery0"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "GetApplicationBO0"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetApplicationBO1"
    via: "next"
    to: "GetServerTimeZoneBO2"
    into: "in"
  - from: "GetServerTimeZoneBO0"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetServerTimeZoneBO1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "GetServerTimeZoneBO2"
    via: "next"
    to: "ExecuteUpdateQuery0"
    into: "in"
  - from: "GetSessionTimeZoneBO0"
    via: "error"
    to: "GetUserTimeZoneBO0"
    into: "in"
  - from: "GetSessionTimeZoneBO0"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "GetTimeZoneBOByID1"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "GetTimeZoneBOByID1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "GetUserTimeZoneBO0"
    via: "error"
    to: "GetServerTimeZoneBO0"
    into: "in"
  - from: "GetUserTimeZoneBO0"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode0"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "SetSessionTimeZoneBO0"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "SetUserTimeZoneBO0"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "GetServerTimeZoneBO1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "DecisionNode0"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "SetSessionTimeZoneBO0"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "SetSessionTimeZoneBO1"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "SetUserTimeZoneBO0"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "StartNode0"
    via: "next"
    to: "VerifyBoolean0"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetSessionTimeZoneBO0"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "GetApplicationBO1"
    into: "in"
  - from: "VerifyBoolean0"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "VerifyBoolean0"
    via: "next"
    to: "JoinNode7"
    into: "in1"
