flow: "ProcessProductConfigurationUtils"
kind: "process"

entries:
  - id: "StartNode15"
    name: "AddCurrenciesToForm"
    mode: "private"
    strict: true
    inputs:
      - key: "TheForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        required: true
      - key: "Currencies"
        type: "java.util.Iterator"
        required: false
  - id: "StartNode17"
    name: "GetPricesFromForm"
    mode: "private"
    strict: true
    inputs:
      - key: "TheForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        required: true
      - key: "Currencies"
        type: "java.util.Iterator"
        required: false
  - id: "StartNode18"
    name: "PutPricesToForm"
    mode: "private"
    strict: true
    inputs:
      - key: "TheForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        required: true
      - key: "Prices"
        type: "java.util.Iterator"
        required: false
  - id: "StartNode20"
    name: "GetValueFromForm"
    mode: "private"
    strict: true
    inputs:
      - key: "TheForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        required: true
      - key: "TheType"
        type: "java.lang.String"
        required: true
      - key: "TypeValueMapper"
        type: "java.util.Map"
        required: true
  - id: "StartNode21"
    name: "PutValueToFormParameters"
    mode: "private"
    strict: true
    inputs:
      - key: "TheType"
        type: "java.lang.String"
        required: true
      - key: "ConfigurationValue"
        type: "java.lang.Object"
        required: true
      - key: "FormParameters"
        type: "java.util.Map"
        required: false
      - key: "TypeValueMapper"
        type: "java.util.Map"
        required: true
      - key: "TheForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        required: false
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: false
  - id: "StartNode33"
    name: "isLocalized"
    mode: "private"
    strict: false
    inputs:
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: false
      - key: "TheForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        required: true
      - key: "FormParameters"
        type: "java.util.Map"
        required: true

steps:
  - id: "AddFormFieldDefinition1"
    type: "pipelet"
    ref: "AddFormFieldDefinition"
    bindings:
      Name: "\"PriceCurrency\""
      FormParameter: "TheForm:get(FormParameterName)"
  - id: "AddFormFieldDefinition2"
    type: "pipelet"
    ref: "AddFormFieldDefinition"
    bindings:
      Name: "\"PriceValue\""
      FormParameter: "TheForm:get(FormParameterName)"
  - id: "AddFormParameterDefinition2"
    type: "pipelet"
    ref: "AddFormParameterDefinition"
    config:
      Optional: true
      Type: "com.intershop.beehive.foundation.quantity.Money"
    bindings:
      Form: "TheForm"
      Name: "FormParameterName"
      ValidateProperties: "ParameterBindings"
      Validator: "\"GlobalValidators-money\""
  - id: "AddMultipleEntriesToMap20"
    type: "pipelet"
    ref: "AddMultipleEntriesToMap"
    config:
      Mode: "OverwriteValue"
      ValueSeparatorChar: ","
    bindings:
      OutMap: "FormParameters"
      InMap: "FormParameters"
      Key1: "TheForm:Localizable"
      Value1: "\"true\""
  - id: "AddMultipleEntriesToMap7"
    type: "pipelet"
    ref: "AddMultipleEntriesToMap"
    config:
      Mode: "OverwriteValue"
    bindings:
      InMap: "ParameterBindings"
      Key1: "\"currency\""
      Key2: "\"value\""
      Value1: "\"PriceCurrency\""
      Value2: "\"PriceValue\""
      OutMap: "ParameterBindings"
  - id: "AddMultipleEntriesToMap9"
    type: "pipelet"
    ref: "AddMultipleEntriesToMap"
    config:
      Mode: "OverwriteValue"
      ValueSeparatorChar: ","
    bindings:
      OutMap: "FormParameters"
      InMap: "FormParameters"
      Value1: "TheValue"
      Key1: "TheForm:get(ParameterName)"
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "null"
      Object: "null"
      Objects: "null"
      OutVector: "Prices"
      Iterator: "PricesIterator"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessProductConfigurationUtils-isLocalized"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "Price_"
    bindings:
      String1: "Currency:Mnemonic"
      Concatenated: "FormParameterName"
  - id: "ConcatenateStrings2"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "Price_"
    bindings:
      String1: "Currency:Mnemonic"
      Concatenated: "FormParameterName"
  - id: "ConcatenateStrings3"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "Price_"
    bindings:
      String1: "Price:CurrencyMnemonic"
      Concatenated: "FormParameterName"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ConfigurationValue:Value(Locale)"
  - id: "DecisionNode11"
    type: "decision"
    condition: "TheType"
  - id: "DecisionNode38"
    type: "decision"
    condition: "CurrentSession:Locale:LocaleID"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode11"
    type: "end"
    strict: true
    outputs:
      - key: "FormParameters"
        type: "java.util.Map"
        guaranteed: true
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "TheForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        guaranteed: true
  - id: "EndNode7"
    type: "end"
    strict: true
    outputs:
      - key: "PricesIterator"
        type: "java.util.Iterator"
        guaranteed: true
  - id: "EndNode8"
    type: "end"
    strict: true
    outputs:
      - key: "TheForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        guaranteed: true
  - id: "EndNode9"
    type: "end"
    strict: true
    outputs:
      - key: "TheValue"
        type: "java.lang.Object"
        guaranteed: false
  - id: "GetEntryFromMap1"
    type: "pipelet"
    ref: "GetEntryFromMap"
    bindings:
      InMap: "TypeValueMapper"
      Key: "TheType"
      Value: "ValueAttribute"
  - id: "GetEntryFromMap2"
    type: "pipelet"
    ref: "GetEntryFromMap"
    bindings:
      InMap: "TypeValueMapper"
      Key: "TheType"
      Value: "ParameterName"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode49"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "ConfigurationValue:Value(Locale)"
      OutValue_1: "TheValue"
  - id: "KeyMapper10"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "ConfigurationValue:Value"
      OutValue_1: "TheValue"
  - id: "KeyMapper11"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "TheForm:get(FormParameterName):Value"
      OutValue_1: "Price"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "ConfigurationValue:Value"
      OutValue_1: "TheValue"
  - id: "KeyMapper20"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "TheForm:get(ValueAttribute):Value"
      OutValue_1: "TheValue"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "LoopNode3"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "Prices"
      OutVector: "Prices"
      Iterator: "PricesIterator"
      Object: "Price"
  - id: "SetFormParameterValue4"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      FormParameter: "TheForm:get(FormParameterName)"
      Value: "Price"

links:
  - from: "AddMultipleEntriesToMap9"
    via: "next"
    to: "EndNode11"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode11"
    via: "no"
    to: "KeyMapper10"
    into: "in"
  - from: "StartNode21"
    via: "next"
    to: "GetEntryFromMap2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "KeyMapper1"
    into: "in"
  - from: "GetEntryFromMap2"
    via: "next"
    to: "DecisionNode11"
    into: "in"
  - from: "KeyMapper10"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode38"
    via: "yes"
    to: "JoinNode49"
    into: "in1"
  - from: "KeyMapper20"
    via: "next"
    to: "EndNode9"
    into: "in"
  - from: "GetEntryFromMap1"
    via: "next"
    to: "KeyMapper20"
    into: "in"
  - from: "StartNode20"
    via: "next"
    to: "GetEntryFromMap1"
    into: "in"
  - from: "LoopNode3"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "ConcatenateStrings3"
    via: "next"
    to: "SetFormParameterValue4"
    into: "in"
  - from: "SetFormParameterValue4"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "StartNode18"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "LoopNode3"
    via: "do"
    to: "ConcatenateStrings3"
    into: "in"
  - from: "AddFormFieldDefinition1"
    via: "next"
    to: "AddFormFieldDefinition2"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "AddFormParameterDefinition2"
    into: "in"
  - from: "JoinNode49"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "AddFormFieldDefinition2"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "StartNode15"
    via: "next"
    to: "AddMultipleEntriesToMap7"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "AddMultipleEntriesToMap7"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "AddFormParameterDefinition2"
    via: "next"
    to: "AddFormFieldDefinition1"
    into: "in"
  - from: "KeyMapper11"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "AddObjectToVector1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "StartNode17"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "AddMultipleEntriesToMap20"
    via: "next"
    to: "JoinNode49"
    into: "in3"
  - from: "LoopNode2"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "ConcatenateStrings2"
    via: "next"
    to: "KeyMapper11"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "ConcatenateStrings2"
    into: "in"
  - from: "DecisionNode38"
    via: "no"
    to: "AddMultipleEntriesToMap20"
    into: "in"
  - from: "DecisionNode11"
    via: "yes"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "AddMultipleEntriesToMap9"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "KeyMapper2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode33"
    via: "next"
    to: "DecisionNode38"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "CallNode1"
    into: "in"
