flow: "ProcessImpexJobSchedule"
kind: "process"

entries:
  - id: "StartNode1"
    name: "Configure"
    mode: "private"
    strict: true
    inputs:
      - key: "ImpexRootDirectoryPath"
        type: "java.lang.String"
        required: true
      - key: "ImpexJobName"
        type: "java.lang.String"
        required: true
      - key: "ImpexProcessPipelineName"
        type: "java.lang.String"
        required: true
      - key: "ImpexProcessPipelineStartNode"
        type: "java.lang.String"
        required: true
      - key: "ImpexJobDescription"
        type: "java.lang.String"
        required: true
      - key: "ImpexImportMode"
        type: "java.lang.String"
        required: false
      - key: "JobConfiguration"
        type: "com.intershop.beehive.core.capi.job.JobConfiguration"
        required: true
  - id: "StartNode2"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      - key: "JobConfigurationUUID"
        type: "java.lang.String"
        required: true
  - id: "StartNode3"
    name: "Create"
    mode: "private"
    strict: true
    inputs:
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "JobDescription"
        type: "java.lang.String"
        required: false
      - key: "JobName"
        type: "java.lang.String"
        required: false
      - key: "JobInterval"
        type: "java.lang.String"
        required: false
      - key: "JobEnable"
        type: "java.lang.String"
        required: false
      - key: "JobUnit"
        type: "java.lang.String"
        required: false
      - key: "JobDate"
        type: "java.util.Date"
        required: false
  - id: "StartNode4"
    name: "ConstructDirectoryPathNames"
    mode: "private"
    strict: true
    inputs:
      - key: "ImpexRootDirectoryPath"
        type: "java.lang.String"
        required: true

steps:
  - id: "BrowseDirectory1"
    type: "pipelet"
    ref: "BrowseDirectory"
    config:
      Recursive: true
      UnitDirectory: "IMPEX_SRC_DIR"
    bindings:
      Locale: "null"
      Directory: "ImpexDir"
      UnitDomain: "ProcessOwningDomain"
      DirectoryPath: "SourceDirectoryPath"
  - id: "Call2"
    type: "call"
    ref: "ProcessImpexJob-Create"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessImpexJobSchedule-ConstructDirectoryPathNames"
    bindings:
      ImpexRootDirectoryPath: "OuterJobConfiguration:ImpexRootDirectoryPath"
  - id: "ConcatenateStrings2"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "ImpexRootDirectoryPath"
      Concatenated: "ImpexSourceDirectoryPath"
  - id: "ConcatenateStrings4"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "\"archive\""
      String1: "\"/\""
      Concatenated: "ImpexArchiveDirectoryPath"
      String2: "ImpexRootDirectoryPath"
  - id: "ConcatenateStrings5"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "ImpexArchiveDirectoryPath"
      String1: "\"/\""
      String2: "\"success\""
      Concatenated: "ImpexArchiveSuccessDirectoryPath"
  - id: "ConcatenateStrings6"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "ImpexArchiveDirectoryPath"
      String1: "\"/\""
      String2: "\"failure\""
      Concatenated: "ImpexArchiveFailureDirectoryPath"
  - id: "CreateJobChain1"
    type: "pipelet"
    ref: "CreateJobChain"
    config:
      ExecutionMode: "Sequential"
    bindings:
      ExecutionDomain: "ProcessOwningDomain"
      Description: "JobDescription"
      Locale: "null"
      Name: "JobName"
  - id: "DecisionNode1"
    type: "decision"
    condition: "JobConfigurations"
  - id: "DecisionNode3"
    type: "decision"
    condition: "ImpexImportMode"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "JobConfiguration"
        type: "com.intershop.beehive.core.capi.job.JobConfiguration"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "EndNode5"
    type: "end"
    strict: true
  - id: "EndNode7"
    type: "end"
    strict: true
    outputs:
      - key: "ImpexArchiveSuccessDirectoryPath"
        type: "java.lang.String"
        guaranteed: true
      - key: "ImpexArchiveFailureDirectoryPath"
        type: "java.lang.String"
        guaranteed: true
      - key: "ImpexSourceDirectoryPath"
        type: "java.lang.String"
        guaranteed: true
  - id: "ExecuteProcessChain1"
    type: "pipelet"
    ref: "ExecuteProcessChain"
    bindings:
      ProcessChain: "JobChain"
      Process: "null"
  - id: "GetJobConfiguration2"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
      JobConfiguration: "OuterJobConfiguration"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "File:FullName"
      OutValue_1: "SelectedFile"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "OuterJobConfiguration:ImpexJobName"
      OutValue_1: "JobName"
      OutValue_2: "ProcessPipelineName"
      InValue_2: "OuterJobConfiguration:ImpexProcessPipelineName"
      InValue_3: "OuterJobConfiguration:ImpexProcessPipelineStartNode"
      OutValue_3: "ProcessPipelineStartNode"
      InValue_4: "OuterJobConfiguration:ImpexJobDescription"
      OutValue_4: "JobDescription"
      InValue_5: "ImpexSourceDirectoryPath"
      OutValue_5: "SourceDirectoryPath"
      InValue_7: "ImpexArchiveSuccessDirectoryPath"
      OutValue_7: "ArchiveSuccessDirectoryPath"
      InValue_8: "ImpexArchiveFailureDirectoryPath"
      OutValue_8: "ArchiveFailureDirectoryPath"
      InValue_9: "ImpexSourceDirectoryPath"
      OutValue_9: "TargetDirectoryPath"
      InValue_10: "OuterJobConfiguration:ImpexImportMode"
      OutValue_10: "ImportMode"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "OuterJobConfiguration:Domain"
      OutValue_1: "ProcessOwningDomain"
  - id: "LoopNode1"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "ImpexRootDirectoryPath"
      Attribute_1_Type: "String"
      Attribute_10_Name: "ImpexJobName"
      Attribute_10_Type: "String"
      Attribute_2_Name: "ImpexProcessPipelineName"
      Attribute_2_Type: "String"
      Attribute_3_Name: "ImpexProcessPipelineStartNode"
      Attribute_3_Type: "String"
      Attribute_4_Name: "ImpexJobDescription"
      Attribute_4_Type: "String"
    bindings:
      Attribute_1_Value: "ImpexRootDirectoryPath"
      ExtensibleObject: "JobConfiguration"
      Attribute_10_Value: "ImpexJobName"
      Attribute_2_Value: "ImpexProcessPipelineName"
      Attribute_3_Value: "ImpexProcessPipelineStartNode"
      Attribute_4_Value: "ImpexJobDescription"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "JobConfigurations"
      Object: "JobConfiguration"
      Objects: "null"
      Iterator: "null"
      OutVector: "JobConfigurations"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "JobExecutionDomainID"
      Attribute_1_Type: "String"
      Attribute_2_Name: "DomainName"
      Attribute_2_Type: "String"
    bindings:
      Attribute_1_Value: "CurrentDomain:UUID"
      Attribute_2_Value: "ProcessOwningDomain:DomainName"
      ExtensibleObject: "JobConfiguration"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "CreateJobConfiguration"
    config:
      DomainName: ""
  - id: "Pipelet8"
    type: "pipelet"
    ref: "UpdateJobConfiguration"
    config:
      EnableJob: false
      Interval: 60
      Name: "ProcessPriceListImportSchedule"
      PipelineName: "ProcessImpexJobSchedule"
      PipelineStartNode: "Start"
      Unit: "Minutes"
      Descript: "Triggers scheduled impex actions."
    bindings:
      JobJavaDate: "JobDate"
      JobDate: "null"
  - id: "UpdateCustomAttribute1"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    config:
      DefaultAttributeName: "ImpexImportMode"
      DefaultAttributeType: "String"
    bindings:
      AttributeName: "null"
      AttributeType: "null"
      AttributeValue: "ImpexImportMode"
      ExtensibleObject: "JobConfiguration"
      LocaleInformation: "null"

links:
  - from: "JoinNode1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "GetJobConfiguration2"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CreateJobChain1"
    via: "next"
    to: "ExecuteProcessChain1"
    into: "in"
  - from: "GetJobConfiguration2"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "ConcatenateStrings6"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "ConcatenateStrings2"
    into: "in"
  - from: "ExecuteProcessChain1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "BrowseDirectory1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "CreateJobChain1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "BrowseDirectory1"
    into: "in"
  - from: "ConcatenateStrings5"
    via: "next"
    to: "ConcatenateStrings6"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "KeyMapper2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "StartNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "UpdateCustomAttribute1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode5"
    into: "in2"
  - from: "UpdateCustomAttribute1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Pipelet7"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "Pipelet8"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "Pipelet7"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "ConcatenateStrings2"
    via: "next"
    to: "ConcatenateStrings4"
    into: "in"
  - from: "BrowseDirectory1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "ConcatenateStrings4"
    via: "next"
    to: "ConcatenateStrings5"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetJobConfiguration2"
    into: "in"
