flow: "ProcessPreviewAttributeContext"
kind: "process"

entries:
  - id: "StartNode8"
    name: "CreateConfigurationAttributesMap"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddMultipleEntriesToMap2"
    type: "pipelet"
    ref: "AddMultipleEntriesToMap"
    config:
      Mode: "AppendToValue"
    bindings:
      InMap: "ConfigurationAttributeMap"
      Value1: "TargetApplication"
      OutMap: "ConfigurationAttributeMap"
      Key1: "\"TargetApplication\""
      Key2: "\"RepositoryId\""
      Value2: "Repository:Id"
      Key3: "\"CurrentUser\""
      Value3: "CurrentUser"
      Key4: "\"RepositoryDomain\""
      Value4: "Repository:RepositoryDomain"
      Key5: "\"CurrentChannel\""
      Value5: "Repository"
  - id: "DecisionNode2"
    type: "decision"
    condition: "TargetApplicationBO"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Repository"
  - id: "DecisionNode4"
    type: "decision"
    condition: "CurrentUser"
  - id: "EndNode14"
    type: "end"
    strict: true
    outputs:
      - key: "ConfigurationAttributeMap"
        type: "java.util.Map"
        guaranteed: true
  - id: "EndNode15"
    type: "end"
    strict: true
  - id: "GetApplication1"
    type: "pipelet"
    ref: "GetApplication"
    bindings:
      Site: "TargetApplicationBO:Site"
      UrlIdentifier: "TargetApplicationBO:UrlIdentifier"
      Application: "TargetApplication"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "TextNode1"
    type: "text"

links:
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode8"
    into: "in2"
  - from: "DecisionNode2"
    via: "yes"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "GetApplication1"
    into: "in"
  - from: "GetApplication1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "AddMultipleEntriesToMap2"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "DecisionNode4"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "EndNode15"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode6"
    into: "in2"
  - from: "GetApplication1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode8"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "AddMultipleEntriesToMap2"
    via: "next"
    to: "EndNode14"
    into: "in"
