flow: "ProcessStaticContent"
kind: "process"

entries:
  - id: "Start1"
    name: "RenameFile"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "CreateDirectory"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "DeleteFile"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Browse"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "ShowSecureFile"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "BrowseDirectory1"
    type: "pipelet"
    ref: "BrowseDirectory"
    config:
      UnitDirectory: "STATIC_CONTENT_DIR"
  - id: "BrowseDirectory2"
    type: "pipelet"
    ref: "BrowseDirectory"
    config:
      UnitDirectory: "SECURE_STATIC_DIR"
  - id: "CheckStaticContent1"
    type: "pipelet"
    ref: "CheckStaticContent"
  - id: "CreateDirectory1"
    type: "pipelet"
    ref: "CreateDirectory"
    config:
      UnitDirectory: "SECURE_STATIC_DIR"
  - id: "CreateDirectory2"
    type: "pipelet"
    ref: "CreateDirectory"
    config:
      UnitDirectory: "STATIC_CONTENT_DIR"
  - id: "Decision10"
    type: "decision"
    condition: "Secure"
  - id: "Decision11"
    type: "decision"
    condition: "Secure"
  - id: "Decision12"
    type: "decision"
    condition: "Secure"
  - id: "Decision3"
    type: "decision"
    condition: "Secure"
  - id: "Decision4"
    type: "decision"
    condition: "Secure"
  - id: "Decision7"
    type: "decision"
    condition: "Secure"
  - id: "Decision8"
    type: "decision"
    condition: "Secure"
  - id: "Decision9"
    type: "decision"
    condition: "Secure"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ExpandedDirectoriesMap"
  - id: "DeleteFile2"
    type: "pipelet"
    ref: "DeleteFile"
    config:
      UnitDirectory: "SECURE_STATIC_DIR"
  - id: "DeleteFile3"
    type: "pipelet"
    ref: "DeleteFile"
    config:
      UnitDirectory: "STATIC_CONTENT_DIR"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End10"
    type: "end"
    strict: false
  - id: "End12"
    type: "end"
    strict: false
  - id: "End13"
    type: "end"
    strict: false
  - id: "End14"
    type: "end"
    strict: false
  - id: "End15"
    type: "end"
    strict: false
  - id: "End16"
    type: "end"
    strict: false
  - id: "End17"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "End5"
    type: "end"
    strict: false
  - id: "End6"
    type: "end"
    strict: false
  - id: "End8"
    type: "end"
    strict: false
  - id: "End9"
    type: "end"
    strict: false
  - id: "ExchangeSessionObject5"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ExpandedDirectoriesMap"
    bindings:
      LoadObject: "ExpandedDirectoriesMap"
  - id: "GetBinaryFileContent1"
    type: "pipelet"
    ref: "GetBinaryFileContent"
    config:
      UnitDirectory: "SECURE_STATIC_DIR"
  - id: "Join10"
    type: "join"
  - id: "Join11"
    type: "join"
  - id: "Join12"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "RenameFile1"
    type: "pipelet"
    ref: "RenameFile"
    config:
      UnitDirectory: "SECURE_STATIC_DIR"
  - id: "RenameFile2"
    type: "pipelet"
    ref: "RenameFile"
    config:
      UnitDirectory: "STATIC_CONTENT_DIR"
  - id: "UpdateMapping1"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ExpandedDirectoriesMap"
      OutMap: "ExpandedDirectoriesMap"

links:
  - from: "CheckStaticContent1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "ExchangeSessionObject5"
    via: "next"
    to: "UpdateMapping1"
    into: "in"
  - from: "UpdateMapping1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "Decision3"
    via: "yes"
    to: "Decision4"
    into: "in"
  - from: "BrowseDirectory2"
    via: "error"
    to: "End12"
    into: "in"
  - from: "Decision4"
    via: "yes"
    to: "BrowseDirectory2"
    into: "in"
  - from: "BrowseDirectory2"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Join5"
    via: "next"
    to: "End10"
    into: "in"
  - from: "BrowseDirectory1"
    via: "next"
    to: "Join5"
    into: "in3"
  - from: "Decision3"
    via: "no"
    to: "Join4"
    into: "in2"
  - from: "Decision4"
    via: "no"
    to: "Join4"
    into: "in1"
  - from: "DeleteFile2"
    via: "error"
    to: "End5"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "BrowseDirectory1"
    into: "in"
  - from: "DeleteFile3"
    via: "error"
    to: "End13"
    into: "in"
  - from: "Decision7"
    via: "yes"
    to: "Decision8"
    into: "in"
  - from: "Decision7"
    via: "no"
    to: "Join7"
    into: "in2"
  - from: "Decision8"
    via: "no"
    to: "Join7"
    into: "in1"
  - from: "Start3"
    via: "next"
    to: "Decision7"
    into: "in"
  - from: "Decision8"
    via: "yes"
    to: "DeleteFile2"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "DeleteFile3"
    into: "in"
  - from: "DeleteFile2"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "DeleteFile3"
    via: "next"
    to: "Join8"
    into: "in3"
  - from: "BrowseDirectory1"
    via: "error"
    to: "End4"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "End9"
    into: "in"
  - from: "CreateDirectory1"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "Join9"
    via: "next"
    to: "End3"
    into: "in"
  - from: "CreateDirectory2"
    via: "error"
    to: "End14"
    into: "in"
  - from: "Decision9"
    via: "yes"
    to: "Decision10"
    into: "in"
  - from: "Decision9"
    via: "no"
    to: "Join10"
    into: "in2"
  - from: "Decision10"
    via: "no"
    to: "Join10"
    into: "in1"
  - from: "Start2"
    via: "next"
    to: "Decision9"
    into: "in"
  - from: "Decision10"
    via: "yes"
    to: "CreateDirectory1"
    into: "in"
  - from: "Join10"
    via: "next"
    to: "CreateDirectory2"
    into: "in"
  - from: "CreateDirectory1"
    via: "error"
    to: "End2"
    into: "in"
  - from: "CreateDirectory2"
    via: "next"
    to: "Join9"
    into: "in3"
  - from: "RenameFile2"
    via: "error"
    to: "End15"
    into: "in"
  - from: "RenameFile1"
    via: "next"
    to: "Join11"
    into: "in1"
  - from: "Join11"
    via: "next"
    to: "End6"
    into: "in"
  - from: "RenameFile2"
    via: "next"
    to: "Join11"
    into: "in3"
  - from: "Decision11"
    via: "yes"
    to: "Decision12"
    into: "in"
  - from: "Decision11"
    via: "no"
    to: "Join12"
    into: "in2"
  - from: "Decision12"
    via: "no"
    to: "Join12"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "Decision11"
    into: "in"
  - from: "Decision12"
    via: "yes"
    to: "RenameFile1"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "CheckStaticContent1"
    into: "in"
  - from: "Join12"
    via: "next"
    to: "RenameFile2"
    into: "in"
  - from: "CheckStaticContent1"
    via: "error"
    to: "End1"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "GetBinaryFileContent1"
    into: "in"
  - from: "GetBinaryFileContent1"
    via: "next"
    to: "End16"
    into: "in"
  - from: "GetBinaryFileContent1"
    via: "error"
    to: "End17"
    into: "in"
  - from: "RenameFile1"
    via: "error"
    to: "End8"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "ExchangeSessionObject5"
    into: "in"
