flow: "ProcessLineItems"
kind: "process"

entries:
  - id: "Start1"
    name: "RecalculateRequisition"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "DetermineLineItemChilds"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "CancelLineItem"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "UpdateStatus"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Calculate"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "RecalculateOrderStatus"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "QueryLineItemChilds"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "RecalculateTotals"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessLineItems-Calculate"
  - id: "Call2"
    type: "call"
    ref: "ProcessLineItems-QueryLineItemChilds"
  - id: "Call3"
    type: "call"
    ref: "ProcessLineItems-DetermineLineItemChilds"
  - id: "Call4"
    type: "call"
    ref: "ProcessLineItems-UpdateStatus"
  - id: "Call5"
    type: "call"
    ref: "ProcessAccountTransactions-OnCancelLineItem"
  - id: "Call6"
    type: "call"
    ref: "ProcessLineItems-RecalculateOrderStatus"
  - id: "CallNode1"
    type: "call"
    ref: "RequisitionProcessCalculation-Start"
  - id: "CallNode3"
    type: "call"
    ref: "RequisitionProcessCalculation-Start"
  - id: "Decision1"
    type: "decision"
    condition: "LineItemChild:UUID"
  - id: "Decision10"
    type: "decision"
    condition: "Order"
  - id: "Decision2"
    type: "decision"
    condition: "Order:OrderType"
  - id: "Decision3"
    type: "decision"
    condition: "LineItemSupplierOrder"
  - id: "Decision4"
    type: "decision"
    condition: "LineItemSellerOrder"
  - id: "Decision5"
    type: "decision"
    condition: "PLI:Status"
  - id: "Decision6"
    type: "decision"
    condition: "SelectDelegatorID"
  - id: "Decision7"
    type: "decision"
    condition: "SellerOrder"
  - id: "Decision9"
    type: "decision"
    condition: "NoCancelation"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Requisition:SubtotalGrossPricePC:Value"
  - id: "DetermineOrderByID1"
    type: "pipelet"
    ref: "DetermineOrderByID"
    bindings:
      OrderID: "LineItemChild:LineItemCtnrID"
      OrderIDs: "NULL"
      OrderRefID: "NULL"
      OrderRefIDs: "NULL"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "End5"
    type: "end"
    strict: false
  - id: "End6"
    type: "end"
    strict: false
  - id: "End7"
    type: "end"
    strict: false
  - id: "End8"
    type: "end"
    strict: false
  - id: "End9"
    type: "end"
    strict: false
  - id: "ExecuteObjectsQuery1"
    type: "pipelet"
    ref: "ExecuteObjectsQuery"
    config:
      QueryName: "requisition/GetLineItemChilds"
      Datasource: "current ORM connection"
      ParameterName_01: "LineItemUUID"
    bindings:
      SearchResult: "LineItemChilds"
      ParameterValue_01: "LineItem:UUID"
  - id: "GetBasketByID1"
    type: "pipelet"
    ref: "GetBasketByID"
    config:
      CurrentUserOnly: false
    bindings:
      Basket: "Requisition"
      BasketID: "LineItem:LineItemCtnrID"
  - id: "GetBasketByID3"
    type: "pipelet"
    ref: "GetBasketByID"
    bindings:
      Basket: "Requisition"
      BasketID: "LineItem:LineItemCtnrID"
  - id: "GetLineItemByUUID1"
    type: "pipelet"
    ref: "GetLineItemByUUID"
    bindings:
      LineItemUUID: "LineItemID"
  - id: "Join1"
    type: "join"
  - id: "Join10"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ProcessLineItems-Calculate"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "SellerOrder"
      OutValue_1: "RecalcOrder"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"true\""
      OutValue_1: "DisabledProductPriceDetermination"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "LineItemChild"
      InValue_2: "Order"
      OutValue_1: "LineItemSupplierOrder"
      OutValue_2: "SupplierOrder"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "LineItemChild"
      InValue_2: "Order"
      OutValue_1: "LineItemSellerOrder"
      OutValue_2: "SellerOrder"
  - id: "Loop1"
    type: "loop"
  - id: "Loop2"
    type: "loop"
  - id: "NoticeProductLineItemElements1"
    type: "pipelet"
    ref: "NoticeProductLineItemElements"
    config:
      States: "4;6"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "NoCancelation"
  - id: "RestoreProcuctLineItemElements1"
    type: "pipelet"
    ref: "RestoreProcuctLineItemElements"
  - id: "RestoreProcuctLineItemElements2"
    type: "pipelet"
    ref: "RestoreProcuctLineItemElements"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "NoCancelation"
      Value: true
      ValueType: "Dictionary Value"
  - id: "SetupCalculationTarget1"
    type: "pipelet"
    ref: "SetupCalculationTarget"
    config:
      Name: "Requisition"
  - id: "UpdateLineItemStatus1"
    type: "pipelet"
    ref: "UpdateLineItemStatus"
    config:
      StatusGroup: "Requisition"
      StatusID: 7
    bindings:
      InputStatusGroup: "NotAvailable"
      InputStatusID: "NotAvailable"
      LineItemID: "NotAvailable"
      LineItemIDs: "NotAvailable"
      Requisition: "NotAvailable"
  - id: "UpdateLineItemStatus2"
    type: "pipelet"
    ref: "UpdateLineItemStatus"
    config:
      StatusGroup: "Order"
      StatusID: 22
      StatusType: "Status"
    bindings:
      InputStatusGroup: "NULL"
      InputStatusID: "NULL"
      LineItemID: "LineItemSupplierOrder:UUID"
      LineItemIDs: "NULL"
      Order: "NULL"
      Requisition: "NULL"
  - id: "UpdateLineItemStatus3"
    type: "pipelet"
    ref: "UpdateLineItemStatus"
    config:
      StatusGroup: "Order"
      StatusID: 22
      StatusType: "Status"
    bindings:
      InputStatusGroup: "NULL"
      InputStatusID: "NULL"
      LineItemID: "LineItemSellerOrder:UUID"
      LineItemIDs: "NULL"
      Order: "NULL"
      Requisition: "NULL"
  - id: "UpdateLineItemStatus4"
    type: "pipelet"
    ref: "UpdateLineItemStatus"
    config:
      StatusGroup: "Delivery"
      StatusID: 7
    bindings:
      InputStatusGroup: "NULL"
      InputStatusID: "NULL"
      LineItemID: "NULL"
      LineItemIDs: "NULL"
      Order: "NULL"
  - id: "UpdateOrderStatus1"
    type: "pipelet"
    ref: "UpdateOrderStatus"
    config:
      StateGroup: "OrderStatus"
      StateName: "CANCELLED"
    bindings:
      Order: "RecalcOrder"
  - id: "UpdateProductLineItemStatus1"
    type: "pipelet"
    ref: "UpdateProductLineItemStatus"
    config:
      StateGroup: "REQUISITIONProductLineItemStatus"
      StateName: "CANCELLED"
    bindings:
      ProductLineItem: "LineItem"

links:
  - from: "DetermineOrderByID1"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "KeyMapper3"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "KeyMapper4"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "KeyMapper4"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Call3"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "GetLineItemByUUID1"
    into: "in"
  - from: "GetLineItemByUUID1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "SetupCalculationTarget1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "NoticeProductLineItemElements1"
    via: "next"
    to: "SetupCalculationTarget1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "JoinNode1"
    into: "in1"
  - from: "Start6"
    via: "next"
    to: "NoticeProductLineItemElements1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "End4"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Join2"
    into: "in3"
  - from: "CallNode3"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "Call1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Join1"
    into: "in1"
  - from: "Decision4"
    via: "no"
    to: "Join1"
    into: "in2"
  - from: "Start1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "DetermineOrderByID1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "Decision6"
    via: "yes"
    to: "GetBasketByID3"
    into: "in"
  - from: "Decision6"
    via: "no"
    to: "GetBasketByID1"
    into: "in"
  - from: "GetBasketByID1"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "GetBasketByID1"
    via: "error"
    to: "Join6"
    into: "in3"
  - from: "GetBasketByID3"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "Loop2"
    via: "next"
    to: "End2"
    into: "in"
  - from: "GetBasketByID3"
    via: "error"
    to: "Join7"
    into: "in3"
  - from: "Join6"
    via: "next"
    to: "Join5"
    into: "in3"
  - from: "Join7"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Join5"
    via: "next"
    to: "UpdateLineItemStatus4"
    into: "in"
  - from: "UpdateProductLineItemStatus1"
    via: "next"
    to: "Decision6"
    into: "in"
  - from: "UpdateLineItemStatus4"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "Join9"
    via: "next"
    to: "End5"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "Loop1"
    via: "do"
    to: "Decision5"
    into: "in"
  - from: "Decision5"
    via: "yes"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Decision5"
    via: "no"
    to: "Join3"
    into: "in3"
  - from: "Join3"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Loop1"
    via: "next"
    to: "Decision9"
    into: "in"
  - from: "Decision9"
    via: "yes"
    to: "End8"
    into: "in"
  - from: "Decision9"
    via: "no"
    to: "UpdateOrderStatus1"
    into: "in"
  - from: "UpdateOrderStatus1"
    via: "next"
    to: "End7"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Join10"
    into: "in1"
  - from: "Join10"
    via: "next"
    to: "UpdateProductLineItemStatus1"
    into: "in"
  - from: "Decision10"
    via: "no"
    to: "Join10"
    into: "in2"
  - from: "UpdateLineItemStatus1"
    via: "next"
    to: "Decision7"
    into: "in"
  - from: "Decision10"
    via: "yes"
    to: "UpdateLineItemStatus1"
    into: "in"
  - from: "Decision4"
    via: "yes"
    to: "UpdateLineItemStatus3"
    into: "in"
  - from: "UpdateLineItemStatus3"
    via: "next"
    to: "Decision10"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "UpdateLineItemStatus2"
    into: "in"
  - from: "UpdateLineItemStatus2"
    via: "next"
    to: "Decision4"
    into: "in"
  - from: "Loop2"
    via: "do"
    to: "Decision1"
    into: "in"
  - from: "Decision7"
    via: "no"
    to: "Join4"
    into: "in3"
  - from: "Start2"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "RestoreProcuctLineItemElements1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "Decision7"
    via: "yes"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "Join9"
    into: "in2"
  - from: "RestoreProcuctLineItemElements1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "End6"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "RestoreProcuctLineItemElements2"
    into: "in"
  - from: "RestoreProcuctLineItemElements2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Call2"
    via: "next"
    to: "Loop2"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "ExecuteObjectsQuery1"
    into: "in"
  - from: "ExecuteObjectsQuery1"
    via: "next"
    to: "End9"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "DetermineOrderByID1"
    into: "in"
