flow: "ProcessUserAccessRoles"
kind: "process"

entries:
  - id: "Start1"
    name: "Show"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "RemoveRole"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "AddRole"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "UpdatePrefix"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AssignUserToOrganizationRole1"
    type: "pipelet"
    ref: "AssignUserToOrganizationRole"
  - id: "DetermineUser1"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "USER_UUID"
  - id: "DetermineUser2"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "USER_UUID"
  - id: "DetermineUserProfile1"
    type: "pipelet"
    ref: "DetermineUserProfile"
    bindings:
      CurrentUser: "User"
  - id: "DetermineUserProfile2"
    type: "pipelet"
    ref: "DetermineUserProfile"
    bindings:
      CurrentUser: "User"
  - id: "End1"
    type: "end"
  - id: "End2"
    type: "end"
  - id: "End3"
    type: "end"
  - id: "End4"
    type: "end"
  - id: "End5"
    type: "end"
  - id: "FilterRolesByPrefix1"
    type: "pipelet"
    ref: "FilterRolesByPrefix"
    config:
      FilterPrefix1: "SLD_AR_"
    bindings:
      FilteredRoles: "Roles"
      SourceRoles: "DomainRoles"
  - id: "GetAssignedUserGroups1"
    type: "pipelet"
    ref: "GetAssignedUserGroups"
    config:
      Membership: "Direct"
    bindings:
      UserGroups: "DirectRoles"
      UserGroupsHash: "DirectRolesHash"
  - id: "GetAssignedUserGroups2"
    type: "pipelet"
    ref: "GetAssignedUserGroups"
    config:
      Membership: "Indirect"
    bindings:
      UserGroups: "IndirectRoles"
      UserGroupsHash: "IndirectRolesHash"
  - id: "GetOrganizationRole1"
    type: "pipelet"
    ref: "GetOrganizationRole"
  - id: "GetOrganizationRole2"
    type: "pipelet"
    ref: "GetOrganizationRole"
  - id: "GetRolesByDomain1"
    type: "pipelet"
    ref: "GetRolesByDomain"
    bindings:
      DomainID: "Organization:DomainID"
  - id: "RemoveUserFromOrganizationRole1"
    type: "pipelet"
    ref: "RemoveUserFromOrganizationRole"

links:
  - from: "DetermineUser2"
    via: "next"
    to: "DetermineUserProfile2"
    into: "in"
  - from: "DetermineUser1"
    via: "next"
    to: "DetermineUserProfile1"
    into: "in"
  - from: "GetOrganizationRole2"
    via: "next"
    to: "AssignUserToOrganizationRole1"
    into: "in"
  - from: "DetermineUserProfile1"
    via: "next"
    to: "End4"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "GetOrganizationRole2"
    into: "in"
  - from: "AssignUserToOrganizationRole1"
    via: "next"
    to: "End3"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "GetOrganizationRole1"
    into: "in"
  - from: "GetOrganizationRole1"
    via: "next"
    to: "RemoveUserFromOrganizationRole1"
    into: "in"
  - from: "RemoveUserFromOrganizationRole1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "GetAssignedUserGroups1"
    via: "next"
    to: "GetAssignedUserGroups2"
    into: "in"
  - from: "GetAssignedUserGroups2"
    via: "next"
    to: "End5"
    into: "in"
  - from: "DetermineUserProfile2"
    via: "next"
    to: "GetRolesByDomain1"
    into: "in"
  - from: "GetRolesByDomain1"
    via: "next"
    to: "FilterRolesByPrefix1"
    into: "in"
  - from: "GetRolesByDomain1"
    via: "error"
    to: "End1"
    into: "in"
  - from: "FilterRolesByPrefix1"
    via: "next"
    to: "GetAssignedUserGroups1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "DetermineUser1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "DetermineUser2"
    into: "in"
