flow: "ProcessOrderStatusImportJob"
kind: "job"

entries:
  - id: "StartNode6"
    name: "GetAllPermittedDomains"
    mode: "private"
    strict: true
    inputs:
      - key: "Config"
        type: "com.intershop.component.orderimpex.capi.impexscenario.ImpexScenario"
        required: true
  - id: "StartNode9"
    name: "GetOrderBORepository"
    mode: "private"
    strict: true
    inputs:
      - key: "Config"
        type: "com.intershop.component.orderimpex.capi.impexscenario.ImpexScenario"
        required: true

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      Object: "Config:JobConfiguration:Domain"
      Iterator: "null"
      InVector: "null"
      Objects: "null"
      OutVector: "OrderDomains"
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      Object: "Repository:RepositoryDomain"
      Iterator: "null"
      InVector: "OrderDomains"
      Objects: "null"
      OutVector: "OrderDomains"
  - id: "AddObjectToVector3"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      OutVector: "OrderDomains"
      Iterator: "null"
      Objects: "null"
      Object: "null"
      InVector: "null"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessChannelList-ListAll"
  - id: "EndNode7"
    type: "end"
    strict: true
    outputs:
      - key: "OrderDomains"
        type: "java.util.Collection"
        guaranteed: true
  - id: "EndNode9"
    type: "end"
    strict: true
    outputs:
      - key: "OrderBORepository"
        type: "com.intershop.component.order.capi.OrderBORepository"
        guaranteed: true
  - id: "GetApplicationBO1"
    type: "pipelet"
    ref: "GetApplicationBO"
  - id: "GetOrganizationByDomain1"
    type: "pipelet"
    ref: "GetOrganizationByDomain"
    bindings:
      OrganizationDomain: "Config:JobConfiguration:Domain"
      Organization: "CurrentOrganization"
  - id: "JoinNode1"
    type: "join"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "OrderBORepository"
      InValue_1: "ApplicationBO:Extension(\"Order\"):OrderBORepositoryOfOwningRepository"
  - id: "LoopNode1"
    type: "loop"

links:
  - from: "GetApplicationBO1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "GetOrganizationByDomain1"
    into: "in"
  - from: "AddObjectToVector3"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "AddObjectToVector2"
    into: "in"
  - from: "GetOrganizationByDomain1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "AddObjectToVector3"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "GetApplicationBO1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "EndNode9"
    into: "in"
  - from: "GetOrganizationByDomain1"
    via: "error"
    to: "AddObjectToVector1"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "LoopNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "AddObjectToVector1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
