flow: "ProcessAccount"
kind: "process"

entries:
  - id: "Start1"
    name: "ObtainUserAccount"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "ObtainDepartmentAccount"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "ObtainCostCenterAccount"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "BindTransaction"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "GetTransactionsByAccount"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "BindAccountTransaction1"
    type: "pipelet"
    ref: "BindAccountTransaction"
  - id: "BindAccountTransaction2"
    type: "pipelet"
    ref: "BindAccountTransaction"
  - id: "BindAccountTransaction3"
    type: "pipelet"
    ref: "BindAccountTransaction"
  - id: "Call1"
    type: "call"
    ref: "ProcessAccount-ObtainCostCenterAccount"
  - id: "Call2"
    type: "call"
    ref: "ProcessAccount-ObtainDepartmentAccount"
  - id: "Call3"
    type: "call"
    ref: "ProcessAccount-ObtainUserAccount"
  - id: "CheckForEmptyString1"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "DepartmentUUID"
  - id: "CheckForEmptyString2"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "CostCenterUUID"
  - id: "CreateAccount1"
    type: "pipelet"
    ref: "CreateAccount"
    config:
      DefaultTypeCode: 1
    bindings:
      Owner: "Profile"
  - id: "CreateAccount2"
    type: "pipelet"
    ref: "CreateAccount"
    config:
      DefaultTypeCode: 2
    bindings:
      Owner: "Department"
      TypeCode: "null"
  - id: "CreateAccount3"
    type: "pipelet"
    ref: "CreateAccount"
    config:
      DefaultTypeCode: 3
    bindings:
      Owner: "CostCenter"
  - id: "Decision1"
    type: "decision"
    condition: "User"
  - id: "DetermineUserProfile1"
    type: "pipelet"
    ref: "DetermineUserProfile"
    bindings:
      CurrentUser: "User"
  - id: "DetermineUserProfile2"
    type: "pipelet"
    ref: "DetermineUserProfile"
    bindings:
      CurrentUser: "User"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End10"
    type: "end"
    strict: false
  - id: "End11"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "End5"
    type: "end"
    strict: false
  - id: "End6"
    type: "end"
    strict: false
  - id: "End7"
    type: "end"
    strict: false
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "account/GetAccountTransactionListByAccountID"
      DefaultPageSize: 15
      ParameterName_01: "AccountUUID"
    bindings:
      ParameterValue_01: "Account:UUID"
      SearchResult: "Transactions"
  - id: "GetAccountByOwner1"
    type: "pipelet"
    ref: "GetAccountByOwner"
    config:
      DefaultTypeCode: 1
    bindings:
      Owner: "Profile"
      TypeCode: "null"
  - id: "GetAccountByOwner2"
    type: "pipelet"
    ref: "GetAccountByOwner"
    config:
      DefaultTypeCode: 2
    bindings:
      Owner: "Department"
      TypeCode: "null"
  - id: "GetAccountByOwner3"
    type: "pipelet"
    ref: "GetAccountByOwner"
    config:
      DefaultTypeCode: 3
    bindings:
      Owner: "CostCenter"
      TypeCode: "null"
  - id: "GetCostCenter1"
    type: "pipelet"
    ref: "GetCostCenter"
  - id: "GetDepartment1"
    type: "pipelet"
    ref: "GetDepartment"
    config:
      Source: "PipelineDictionary"
  - id: "Join1"
    type: "join"
  - id: "Join10"
    type: "join"
  - id: "Join11"
    type: "join"
  - id: "Join12"
    type: "join"
  - id: "Join13"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"

links:
  - from: "Start1"
    via: "next"
    to: "DetermineUserProfile1"
    into: "in"
  - from: "GetAccountByOwner2"
    via: "error"
    to: "CreateAccount2"
    into: "in"
  - from: "GetAccountByOwner2"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "Join4"
    via: "next"
    to: "End4"
    into: "in"
  - from: "CreateAccount2"
    via: "next"
    to: "Join4"
    into: "in3"
  - from: "Start2"
    via: "next"
    to: "GetAccountByOwner2"
    into: "in"
  - from: "CreateAccount2"
    via: "error"
    to: "End3"
    into: "in"
  - from: "GetAccountByOwner3"
    via: "error"
    to: "CreateAccount3"
    into: "in"
  - from: "GetAccountByOwner3"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Join3"
    via: "next"
    to: "End5"
    into: "in"
  - from: "CreateAccount3"
    via: "next"
    to: "Join3"
    into: "in3"
  - from: "DetermineUserProfile1"
    via: "next"
    to: "GetAccountByOwner1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "GetAccountByOwner3"
    into: "in"
  - from: "CreateAccount3"
    via: "error"
    to: "End6"
    into: "in"
  - from: "GetDepartment1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "BindAccountTransaction2"
    into: "in"
  - from: "BindAccountTransaction2"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "GetDepartment1"
    via: "error"
    to: "Join10"
    into: "in2"
  - from: "Join10"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Call2"
    via: "Error"
    to: "Join5"
    into: "in2"
  - from: "Join5"
    via: "next"
    to: "Join6"
    into: "in3"
  - from: "Call1"
    via: "next"
    to: "BindAccountTransaction1"
    into: "in"
  - from: "GetAccountByOwner1"
    via: "error"
    to: "CreateAccount1"
    into: "in"
  - from: "BindAccountTransaction1"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "Join8"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "Call1"
    via: "Error"
    to: "Join7"
    into: "in2"
  - from: "Join7"
    via: "next"
    to: "Join9"
    into: "in3"
  - from: "CheckForEmptyString1"
    via: "next"
    to: "GetDepartment1"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "error"
    to: "Join10"
    into: "in1"
  - from: "Join6"
    via: "next"
    to: "CheckForEmptyString2"
    into: "in"
  - from: "CheckForEmptyString2"
    via: "next"
    to: "GetCostCenter1"
    into: "in"
  - from: "CheckForEmptyString2"
    via: "error"
    to: "Join8"
    into: "in1"
  - from: "GetCostCenter1"
    via: "error"
    to: "Join8"
    into: "in2"
  - from: "GetAccountByOwner1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "GetCostCenter1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Join9"
    via: "next"
    to: "End7"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "BindAccountTransaction3"
    into: "in"
  - from: "BindAccountTransaction3"
    via: "next"
    to: "Join12"
    into: "in1"
  - from: "Join11"
    via: "next"
    to: "Join13"
    into: "in1"
  - from: "Call3"
    via: "Error"
    to: "Join13"
    into: "in2"
  - from: "Join13"
    via: "next"
    to: "Join12"
    into: "in3"
  - from: "Start4"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "DetermineUserProfile2"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join11"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "DetermineUserProfile2"
    via: "error"
    to: "Join11"
    into: "in2"
  - from: "DetermineUserProfile2"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Join12"
    via: "next"
    to: "CheckForEmptyString1"
    into: "in"
  - from: "CreateAccount1"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "ExecutePageableQuery1"
    via: "error"
    to: "End10"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "End11"
    into: "in"
  - from: "DetermineUserProfile1"
    via: "error"
    to: "Join2"
    into: "in1"
  - from: "CreateAccount1"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "Join2"
    via: "next"
    to: "End2"
    into: "in"
