flow: "ProcessPageletEntryPointPreview"
kind: "process"

entries:
  - id: "StartNode1"
    name: "IsPreviewAvailable"
    mode: "private"
    strict: true
    inputs:
      - key: "PageletEntryPoint"
        type: "com.intershop.component.pmc.capi.pagelet.PageletEntryPoint"
        required: true
      - key: "ContentRepository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
  - id: "StartNode2"
    name: "ContentSharingExists"
    mode: "private"
    strict: true
    inputs:
      - key: "MasterRepositoryDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "ChannelDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode7"
    name: "ErrorMessages"
    mode: "private"
    strict: true
    inputs:
      - key: "ContainerName"
        type: "java.lang.String"
        required: true
      - key: "ErrorMessageKey"
        type: "java.lang.String"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessPreviewApplication-GetPreferredPreviewApplication"
    bindings:
      User: "CurrentUser"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessPageletEntryPointPreview-ContentSharingExists"
    bindings:
      MasterRepositoryDomain: "ContentRepository:RepositoryDomain"
      ChannelDomain: "ChannelRepository:RepositoryDomain"
  - id: "CallNode60"
    type: "call"
    ref: "PreviewLinks-GetPreviewRepository"
    bindings:
      Repository: "ChannelRepository"
  - id: "ContainsElement1"
    type: "pipelet"
    ref: "ContainsElement"
    bindings:
      Collection: "ContentSharingProvider:SharingPath(ChannelDomain)"
      Element: "MasterRepositoryDomain"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PageletEntryPoint:PageletAssignments(ContentRepository:RepositoryDomain)"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ContentRepository:TypeCode"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "PreviewAvailable"
        type: "java.lang.Boolean"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode8"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorMessage"
        type: "java.lang.String"
        guaranteed: false
  - id: "GetApplicationBO2"
    type: "pipelet"
    ref: "GetApplicationBO"
    bindings:
      ApplicationBO: "BackofficeApplicationBO"
  - id: "GetApplicationBOCallInterfaceExtension2"
    type: "pipelet"
    ref: "GetApplicationBOCallInterfaceExtension"
  - id: "GetCallTarget1"
    type: "pipelet"
    ref: "GetCallTarget"
    bindings:
      Object: "PageletEntryPoint"
  - id: "GetContentSharingProvider1"
    type: "pipelet"
    ref: "GetContentSharingProvider"
  - id: "GetFormRecord1"
    type: "pipelet"
    ref: "GetFormRecord"
    config:
      DefaultRecordID: "AAA"
  - id: "GetValuesFromContainer1"
    type: "pipelet"
    ref: "GetValuesFromContainer"
    config:
      OverwriteBehavior: false
      Prefix: "AAA_"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"(Boolean)true\""
      OutValue_1: "PreviewAvailable"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"(Boolean)false\""
      OutValue_1: "PreviewAvailable"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ContentRepository"
      OutValue_1: "ChannelRepository"
  - id: "Pipelet22"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      Organization: "CurrentOrganization"
      User: "CurrentUser"
  - id: "RemoveValuesContainer1"
    type: "pipelet"
    ref: "RemoveValuesContainer"
  - id: "SetIndirectDictValue1"
    type: "pipelet"
    ref: "SetIndirectDictValue"
    bindings:
      KeyNameHolder: "\"ErrorMessage\""
      MappedEntry: "FormRecord:get(ErrorMessageKey)"

links:
  - from: "Pipelet22"
    via: "next"
    to: "CallNode60"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "GetCallTarget1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "KeyMapper3"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode4"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "GetApplicationBOCallInterfaceExtension2"
    via: "next"
    to: "GetCallTarget1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet22"
    into: "in"
  - from: "CallNode2"
    via: "No"
    to: "JoinNode6"
    into: "in1"
  - from: "GetApplicationBO2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Pipelet22"
    via: "error"
    to: "JoinNode8"
    into: "in2"
  - from: "CallNode1"
    via: "ERROR"
    to: "JoinNode9"
    into: "in2"
  - from: "StartNode2"
    via: "next"
    to: "GetContentSharingProvider1"
    into: "in"
  - from: "ContainsElement1"
    via: "error"
    to: "EndNode3"
    into: "in"
  - from: "CallNode60"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "GetContentSharingProvider1"
    via: "next"
    to: "ContainsElement1"
    into: "in"
  - from: "GetApplicationBOCallInterfaceExtension2"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "ContainsElement1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode60"
    via: "ERROR"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "StartNode7"
    via: "next"
    to: "GetValuesFromContainer1"
    into: "in"
  - from: "RemoveValuesContainer1"
    via: "next"
    to: "GetFormRecord1"
    into: "in"
  - from: "GetValuesFromContainer1"
    via: "next"
    to: "RemoveValuesContainer1"
    into: "in"
  - from: "SetIndirectDictValue1"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "GetApplicationBO2"
    into: "in"
  - from: "GetFormRecord1"
    via: "next"
    to: "SetIndirectDictValue1"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "GetValuesFromContainer1"
    via: "error"
    to: "JoinNode10"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "GetApplicationBOCallInterfaceExtension2"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode4"
    into: "in2"
  - from: "GetCallTarget1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
