flow: "ProcessShipping"
kind: "process"

entries:
  - id: "StartNode0"
    name: "IsDigitalOnly"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentCartBO"
        type: "com.intershop.component.basket.capi.BasketBO"
        required: true
  - id: "StartNode1"
    name: "PrepareShippingMethodUUID"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode10"
    name: "ProcessGiftOptionMarkers"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode12"
    name: "DefaultSettings"
    mode: "private"
    strict: true
    inputs:
      - key: "Cart"
        type: "com.intershop.beehive.bts.capi.orderprocess.basket.Basket"
        required: true
      - key: "User"
        type: "com.intershop.beehive.core.capi.user.User"
        required: true
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "CurrentAppContext"
        type: "com.intershop.beehive.app.capi.AppContext"
        required: false
      - key: "BasketBORepository"
        type: "com.intershop.component.basket.capi.BasketBORepository"
        required: true
  - id: "StartNode13"
    name: "CheckDefaultSettings"
    mode: "private"
    strict: true
    inputs:
      - key: "Cart"
        type: "com.intershop.beehive.bts.capi.orderprocess.basket.Basket"
        required: true
      - key: "BasketBORepository"
        type: "com.intershop.component.basket.capi.BasketBORepository"
        required: true
  - id: "StartNode2"
    name: "SetShippingMethod"
    mode: "private"
    strict: true
    inputs:
      - key: "ShippingMethodUUID"
        type: "java.lang.String"
        required: true
      - key: "ShippingInstruction"
        type: "java.lang.String"
        required: false
      - key: "RequestedDeliveryDate"
        type: "java.lang.String"
        required: false
      - key: "ProductLineItemIDs"
        type: "java.util.HashMap$KeySet"
        required: true
  - id: "StartNode3"
    name: "CreateShippingForm"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "PrepareShippingInstruction"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "PrepareRequestedDeliveryDate"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "ValidateShippingForm"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "SetDefaultShippingMethod"
    mode: "private"
    strict: true
    inputs:
      - key: "Basket"
        type: "com.intershop.beehive.bts.capi.orderprocess.basket.Basket"
        required: true
  - id: "StartNode8"
    name: "SetShippingMethods"
    mode: "private"
    strict: false
    inputs:
      - key: "CurrentCartBO"
        type: "com.intershop.component.basket.capi.BasketBO"
        required: false
  - id: "StartNode9"
    name: "StartHook"
    mode: "private"
    strict: true
    inputs:
      - key: "Basket"
        type: "com.intershop.beehive.bts.capi.orderprocess.basket.Basket"
        required: false

steps:
  - id: "AddEntryToMap4"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      Key: "\"maxLength\""
      Value: "\"180\""
      OutMap: "textLengthRule"
  - id: "AddFormParameterDefinition1"
    type: "pipelet"
    ref: "AddFormParameterDefinition"
    config:
      Type: "java.lang.String"
      Optional: true
    bindings:
      Form: "ShippingForm"
      Validator: "\"ProfanityCheckWebform-ProfanityChecker\""
      Name: "ShippingInstructionFormFieldName"
      ValidateProperties: "ProfanityCheckValidatorParameterMap"
  - id: "AddMultipleEntriesToMap2"
    type: "pipelet"
    ref: "AddMultipleEntriesToMap"
    config:
      Mode: "OverwriteValue"
    bindings:
      Value1: "\"CurrentOrganization:OwningDomain\""
      InMap: "ProfanityCheckValidatorParameterMap"
      Key1: "\"ProfanityCheckConfigurationDomainDictionaryKey\""
      Key2: "\"ProfanityCheckConfigurationID\""
      Value2: "\"Default\""
      OutMap: "ProfanityCheckValidatorParameterMap"
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      Object: "ProductLineItem"
      InVector: "ProductLineItemsVector"
      Iterator: "ProductLineItems"
      OutVector: "ProductLineItemsVector"
  - id: "AddValidateDefinition1"
    type: "pipelet"
    ref: "AddValidateDefinition"
    bindings:
      Target: "ShippingForm:getParameter(ShippingInstructionFormFieldName)"
      Validator: "\"GlobalValidators-maxlength\""
      ValidationProperties: "textLengthRule"
  - id: "CallNode0"
    type: "call"
    ref: "ProcessShipping-IsDigitalOnly"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessShipping-PrepareShippingMethodUUID"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessShipping-PrepareShippingInstruction"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessShipping-PrepareRequestedDeliveryDate"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessShipping-SetShippingMethod"
    bindings:
      ProductLineItemIDs: "ProductLineItemIDMap:KeySet"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessShipping-SetDefaultShippingMethod"
    bindings:
      Basket: "Cart"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessShipping-CheckDefaultSettings"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessShipping-CreateShippingForm"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "\"ShippingInstruction_\""
      String1: "Bucket:ID"
      Concatenated: "ShippingInstructionFormFieldName"
  - id: "ConcatenateStrings2"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "\"ShippingMethodUUID_\""
      String1: "Bucket:ID"
      Concatenated: "ShippingMethodUUIDKey"
  - id: "ConcatenateStrings3"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "\"ShippingForm_ShippingInstruction_\""
      String1: "Bucket:ID"
      Concatenated: "ShippingInstructionKey"
  - id: "ConcatenateStrings6"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "giftOption_"
    bindings:
      String1: "PLI:ID"
      Concatenated: "giftOptionMarkerKey"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "ShippingForm"
      FormResource: "Shipping"
    bindings:
      Form: "ShippingForm"
  - id: "DecisionNode0"
    type: "decision"
    condition: "Bucket:SelectedBasketShippingMethodBO"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ProductLineItemIDs"
  - id: "DecisionNode10"
    type: "decision"
    condition: "Bucket:SelectedBasketShippingMethodBO:DigitalDelivery"
  - id: "DecisionNode2"
    type: "decision"
    condition: "toGiftingOption"
  - id: "DecisionNode3"
    type: "decision"
    condition: "ShippingMethodUUID"
  - id: "DecisionNode4"
    type: "decision"
    condition: "PLI:ShippingMethod"
  - id: "DecisionNode5"
    type: "decision"
    condition: "PackSlipMessage_Switch"
  - id: "DecisionNode6"
    type: "decision"
    condition: "giftOptionMarker"
  - id: "DecisionNode7"
    type: "decision"
    condition: "SkipGifting"
  - id: "DecisionNode8"
    type: "decision"
    condition: "SkipGifting"
  - id: "DecisionNode9"
    type: "decision"
    condition: "PLI:Extension(\"Gifting\"):GiftOptionMarked"
  - id: "EndNode0"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode10"
    type: "end"
    strict: false
  - id: "EndNode11"
    type: "end"
    strict: false
  - id: "EndNode12"
    type: "end"
    strict: false
  - id: "EndNode13"
    type: "end"
    strict: true
  - id: "EndNode14"
    type: "end"
    strict: true
  - id: "EndNode15"
    type: "end"
    strict: true
  - id: "EndNode16"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode22"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "EndNode5"
    type: "end"
    strict: false
  - id: "EndNode6"
    type: "end"
    strict: false
  - id: "EndNode7"
    type: "end"
    strict: false
  - id: "EndNode8"
    type: "end"
    strict: true
  - id: "EndNode9"
    type: "end"
    strict: true
  - id: "GetBasketBO1"
    type: "pipelet"
    ref: "GetBasketBO"
    bindings:
      Basket: "Cart"
  - id: "GetFormRecord6"
    type: "pipelet"
    ref: "GetFormRecord"
    bindings:
      AllFormValues: "null"
      RecordID: "Bucket:ID"
      FormRecord: "ProductLineItemIDMap"
  - id: "GetIndirectDictValue1"
    type: "pipelet"
    ref: "GetIndirectDictValue"
    bindings:
      KeyNameHolder: "ShippingInstructionFormFieldName"
      MappedEntry: "ShippingInstructionMappedValue"
  - id: "GetIndirectDictValue2"
    type: "pipelet"
    ref: "GetIndirectDictValue"
    bindings:
      KeyNameHolder: "ShippingMethodUUIDKey"
      MappedEntry: "ShippingMethodUUID"
  - id: "GetIndirectDictValue3"
    type: "pipelet"
    ref: "GetIndirectDictValue"
    bindings:
      KeyNameHolder: "ShippingInstructionKey"
      MappedEntry: "ShippingInstruction"
  - id: "GetIndirectDictValue6"
    type: "pipelet"
    ref: "GetIndirectDictValue"
    bindings:
      KeyNameHolder: "giftOptionMarkerKey"
      MappedEntry: "giftOptionMarker"
  - id: "GetLineItemByUUID1"
    type: "pipelet"
    ref: "GetLineItemByUUID"
    bindings:
      LineItemUUID: "ProductLineItemID"
      LineItem: "ProductLineItem"
  - id: "GetShippingMethodByID1"
    type: "pipelet"
    ref: "GetShippingMethodByID"
    bindings:
      ID: "ShippingMethodUUID"
      Domain: "CurrentDomain"
  - id: "JoinNode0"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "PLI:Extension(\"Gifting\"):GiftOptionMarked"
      OutValue_1: "OldGiftOptionMarker"
  - id: "LoopNode0"
    type: "loop"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "LoopNode3"
    type: "loop"
  - id: "LoopNode4"
    type: "loop"
  - id: "LoopNode6"
    type: "loop"
  - id: "SetDefaultShippingMethod2"
    type: "pipelet"
    ref: "SetDefaultShippingMethod"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "toGiftingOption"
      ValueType: "Dictionary Value"
      Value: true
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "recalculateCart"
      ValueType: "Dictionary Value"
      Value: true
  - id: "SetFormParameterValue2"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      Value: "ShippingInstructionMappedValue"
      FormParameter: "ShippingForm:get(ShippingInstructionFormFieldName)"
  - id: "SetGiftOptionMarker1"
    type: "pipelet"
    ref: "SetGiftOptionMarker"
    config:
      GiftOptionMarker: true
    bindings:
      ProductLineItem: "PLI"
      BasketProductLineItemBO: "PLI"
  - id: "SetGiftOptionMarker2"
    type: "pipelet"
    ref: "SetGiftOptionMarker"
    config:
      GiftOptionMarker: false
    bindings:
      ProductLineItem: "PLI"
      BasketProductLineItemBO: "PLI"
  - id: "SetSelectedShippingMethod1"
    type: "pipelet"
    ref: "SetSelectedShippingMethod"
    bindings:
      SpecialShippingInstructions: "ShippingInstruction"
  - id: "ValidateForm2"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "ShippingForm"
  - id: "VerifyShippingMethods1"
    type: "pipelet"
    ref: "VerifyShippingMethods"

links:
  - from: "AddEntryToMap4"
    via: "next"
    to: "AddValidateDefinition1"
    into: "in"
  - from: "AddFormParameterDefinition1"
    via: "next"
    to: "AddEntryToMap4"
    into: "in"
  - from: "AddMultipleEntriesToMap2"
    via: "next"
    to: "AddFormParameterDefinition1"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "AddValidateDefinition1"
    via: "next"
    to: "SetFormParameterValue2"
    into: "in"
  - from: "CallNode0"
    via: "isDigital"
    to: "JoinNode10"
    into: "in1"
  - from: "CallNode0"
    via: "next"
    to: "EndNode14"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "LoopNode4"
    into: "loop"
  - from: "CallNode5"
    via: "next"
    to: "EndNode15"
    into: "in"
  - from: "CallNode6"
    via: "ERROR"
    to: "CallNode5"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "EndNode22"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "ValidateForm2"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "GetIndirectDictValue1"
    into: "in"
  - from: "ConcatenateStrings2"
    via: "next"
    to: "GetIndirectDictValue2"
    into: "in"
  - from: "ConcatenateStrings3"
    via: "next"
    to: "GetIndirectDictValue3"
    into: "in"
  - from: "ConcatenateStrings6"
    via: "next"
    to: "GetIndirectDictValue6"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "DecisionNode0"
    via: "no"
    to: "JoinNode0"
    into: "in1"
  - from: "DecisionNode0"
    via: "yes"
    to: "DecisionNode10"
    into: "in"
  - from: "DecisionNode10"
    via: "no"
    to: "JoinNode0"
    into: "in1"
  - from: "DecisionNode10"
    via: "yes"
    to: "LoopNode0"
    into: "loop"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "LoopNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode3"
    via: "yes"
    to: "GetShippingMethodByID1"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode4"
    via: "yes"
    to: "LoopNode2"
    into: "loop"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode5"
    via: "yes"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode6"
    via: "no"
    to: "SetGiftOptionMarker2"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "DecisionNode8"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "JoinNode7"
    into: "in1"
  - from: "DecisionNode8"
    via: "no"
    to: "JoinNode7"
    into: "in1"
  - from: "DecisionNode8"
    via: "yes"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode9"
    via: "no"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode9"
    via: "yes"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "GetBasketBO1"
    via: "next"
    to: "VerifyShippingMethods1"
    into: "in"
  - from: "GetFormRecord6"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetIndirectDictValue1"
    via: "next"
    to: "AddMultipleEntriesToMap2"
    into: "in"
  - from: "GetIndirectDictValue2"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "GetIndirectDictValue3"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "GetIndirectDictValue6"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "GetLineItemByUUID1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetLineItemByUUID1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetShippingMethodByID1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "GetShippingMethodByID1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode0"
    via: "next"
    to: "EndNode16"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "EndNode13"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "CallNode0"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "DecisionNode9"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode9"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "LoopNode6"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "LoopNode6"
    into: "loop"
  - from: "KeyMapper1"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "LoopNode0"
    via: "do"
    to: "DecisionNode0"
    into: "in"
  - from: "LoopNode0"
    via: "next"
    to: "EndNode0"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "GetLineItemByUUID1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "SetSelectedShippingMethod1"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "DecisionNode4"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "GetBasketBO1"
    into: "in"
  - from: "LoopNode3"
    via: "do"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "LoopNode3"
    via: "next"
    to: "EndNode10"
    into: "in"
  - from: "LoopNode4"
    via: "do"
    to: "GetFormRecord6"
    into: "in"
  - from: "LoopNode4"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "LoopNode6"
    via: "do"
    to: "ConcatenateStrings6"
    into: "in"
  - from: "LoopNode6"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "SetDefaultShippingMethod2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "SetGiftOptionMarker1"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "SetFormParameterValue2"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "SetGiftOptionMarker1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "SetGiftOptionMarker2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "SetSelectedShippingMethod1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "StartNode0"
    via: "next"
    to: "LoopNode0"
    into: "in"
  - from: "StartNode10"
    via: "next"
    to: "DecisionNode7"
    into: "in"
  - from: "StartNode12"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "StartNode13"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "ConcatenateStrings2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "ConcatenateStrings3"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "SetDefaultShippingMethod2"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "LoopNode4"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "ValidateForm2"
    via: "error"
    to: "EndNode12"
    into: "in"
  - from: "ValidateForm2"
    via: "next"
    to: "EndNode11"
    into: "in"
  - from: "VerifyShippingMethods1"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "VerifyShippingMethods1"
    via: "next"
    to: "EndNode8"
    into: "in"
