flow: "ProcessReplicateObjects"
kind: "process"

entries:
  - id: "StartNode1"
    name: "Process"
    mode: "private"
    strict: true
    inputs:
      - key: "JobConfiguration"
        type: "com.intershop.beehive.core.capi.domain.ExtensibleObject"
        required: false
      - key: "Objects"
        type: "java.util.Iterator"
        required: true
      - key: "TargetClusterID"
        type: "java.lang.String"
        required: true
  - id: "StartNode2"
    name: "Init"
    mode: "private"
    strict: true
    inputs:
      - key: "Objects"
        type: "java.util.Iterator"
        required: false
      - key: "JobConfiguration"
        type: "com.intershop.beehive.core.capi.job.JobConfiguration"
        required: false
  - id: "StartNode3"
    name: "GetTargetClusters"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode5"
    name: "Post"
    mode: "private"
    strict: true
    inputs:
      - key: "LogScope"
        type: "com.intershop.beehive.core.capi.log.LogScope"
        required: false
      - key: "JobConfiguration"
        type: "com.intershop.beehive.core.capi.job.JobConfiguration"
        required: false
      - key: "ProcessLogAppender"
        type: "com.intershop.beehive.core.capi.log.ProcessAppender"
        required: false

steps:
  - id: "AddEntryToMap1"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      Key: "\"IgnoreParentPagelet\""
      InMap: "Parameters"
      OutMap: "Parameters"
      Value: "\"\""
  - id: "AddEntryToMap2"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      Key: "\"DomainID\""
      Value: "JobConfiguration:DomainID"
      OutMap: "Parameters"
  - id: "CallNode1"
    type: "call"
    ref: "BatchProcessLog-LogResult"
    bindings:
      Product: "ORMObject"
      Result: "Error"
  - id: "CallNode3"
    type: "call"
    ref: "BatchProcessLog-PrepareLogger"
  - id: "CallNode4"
    type: "call"
    ref: "BatchProcessLog-CleanLogger"
  - id: "DecisionNode1"
    type: "decision"
    condition: "JobConfiguration:Name"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode11"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "Objects"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "LogScope"
        type: "com.intershop.beehive.core.capi.log.LogScope"
        guaranteed: false
      - key: "ProcessLogAppender"
        type: "com.intershop.beehive.core.capi.log.ProcessAppender"
        guaranteed: false
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "TargetClusters"
        type: "java.util.Collection"
        guaranteed: true
  - id: "GetTargetCluster1"
    type: "pipelet"
    ref: "GetTargetCluster"
  - id: "GetTargetClusters2"
    type: "pipelet"
    ref: "GetTargetClusters"
  - id: "GrantStagingDatabasePrivsToTargetCluster1"
    type: "pipelet"
    ref: "GrantStagingDatabasePrivsToTargetCluster"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "ReplicateORMObjects1"
    type: "pipelet"
    ref: "ReplicateORMObjects"
    bindings:
      ORMObjects: "Objects"

links:
  - from: "ReplicateORMObjects1"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "AddEntryToMap2"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetTargetClusters2"
    into: "in"
  - from: "GetTargetClusters2"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "GrantStagingDatabasePrivsToTargetCluster1"
    via: "next"
    to: "ReplicateORMObjects1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "AddEntryToMap1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "AddEntryToMap1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "StartNode2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "GetTargetCluster1"
    into: "in"
  - from: "ReplicateORMObjects1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode4"
    via: "next"
    to: "EndNode11"
    into: "in"
  - from: "AddEntryToMap2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "JoinNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetTargetCluster1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "GetTargetCluster1"
    via: "next"
    to: "GrantStagingDatabasePrivsToTargetCluster1"
    into: "in"
