flow: "ProcessUser"
kind: "process"

entries:
  - id: "StartNode1"
    name: "GetLoginType"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode2"
    name: "CheckLoggedIn"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode3"
    name: "IsProductVisibleToCurrentUser"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentUser"
        type: "com.intershop.beehive.core.capi.user.User"
        required: true
      - key: "ProductBO"
        type: "com.intershop.component.product.capi.ProductBO"
        required: true
  - id: "StartNode8"
    name: "GetProfile"
    mode: "private"
    strict: true
    inputs:
      - key: "User"
        type: "com.intershop.beehive.core.capi.user.User"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
    ref: "Super:GetProfile"
  - id: "CallNode52"
    type: "call"
    ref: "GetCatalogFilters-IsProductVisible"
  - id: "CallNode53"
    type: "call"
    ref: "GetCatalogFilters-GetFiltersByUser"
    bindings:
      CatalogFilterDomain: "CurrentOrganization:OwningDomain"
      UseFallbackToEveryoneDomain: "\"true\""
      EveryoneDomain: "CurrentOrganization:OrganizationDomain"
  - id: "CallNode54"
    type: "call"
    ref: "DetermineRepositories-Channel"
  - id: "CallNode56"
    type: "call"
    ref: "DetermineOrganizations-Current"
  - id: "CheckUserLoggedIn2"
    type: "pipelet"
    ref: "CheckUserLoggedIn"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Product:Online"
  - id: "DecisionNode4"
    type: "decision"
    condition: "LoginType"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode10"
    type: "end"
    strict: true
  - id: "EndNode15"
    type: "end"
    strict: true
    outputs:
      - key: "Profile"
        type: "com.intershop.beehive.core.capi.profile.Profile"
        guaranteed: true
  - id: "EndNode16"
    type: "end"
    strict: true
    outputs:
      - key: "ERROR_User"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "EndNode9"
    type: "end"
    strict: true
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "UserRegistrationLoginType"
      Type: "String"
    bindings:
      PreferenceDomain: "CurrentDomain"
      PreferenceKey: "null"
      PreferenceStringValue: "LoginType"
  - id: "GetProductBySKU2"
    type: "pipelet"
    ref: "GetProductBySKU"
    bindings:
      SKU: "ProductBO:SKU"
      Domain: "Repository:RepositoryDomain"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode9"
    type: "join"

links:
  - from: "StartNode8"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CheckUserLoggedIn2"
    via: "error"
    to: "EndNode4"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CheckUserLoggedIn2"
    into: "in"
  - from: "CheckUserLoggedIn2"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "EndNode10"
    into: "in"
  - from: "GetProductBySKU2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetProductBySKU2"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode56"
    via: "next"
    to: "CallNode53"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode56"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "EndNode15"
    into: "in"
  - from: "CallNode54"
    via: "next"
    to: "GetProductBySKU2"
    into: "in"
  - from: "CallNode53"
    via: "next"
    to: "CallNode52"
    into: "in"
  - from: "CallNode52"
    via: "NOT_VISIBLE"
    to: "JoinNode7"
    into: "in2"
  - from: "CallNode52"
    via: "next"
    to: "EndNode9"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode54"
    into: "in"
  - from: "CallNode1"
    via: "ERROR"
    to: "EndNode16"
    into: "in"
  - from: "GetDomainPreference1"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode9"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "GetDomainPreference1"
    via: "error"
    to: "JoinNode9"
    into: "in2"
