flow: "ProcessCachingForStorefrontEditing"
kind: "extension"

entries:
  - id: "StartNode6"
    name: "ProcessCaching"
    mode: "private"
    strict: true
    inputs:
      []

steps:
  - id: "CreateUUID1"
    type: "pipelet"
    ref: "CreateUUID"
  - id: "DecisionNode1"
    type: "decision"
    condition: "CurrentRequest:ServletRequest:Parameter(\"rerender\")"
  - id: "DecisionNode11"
    type: "decision"
    condition: "CurrentSession:getObject(\"T_StorefrontEditingContext\")"
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "UpdatePersonalizationGroup1"
    type: "pipelet"
    ref: "UpdatePersonalizationGroup"
    bindings:
      PGID: "UUID"

links:
  - from: "DecisionNode1"
    via: "yes"
    to: "CreateUUID1"
    into: "in"
  - from: "UpdatePersonalizationGroup1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CreateUUID1"
    via: "next"
    to: "UpdatePersonalizationGroup1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "DecisionNode11"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "StartNode6"
    via: "next"
    to: "DecisionNode11"
    into: "in"
  - from: "DecisionNode11"
    via: "yes"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in2"
