flow: "ProcessCategoriesImages"
kind: "process"

entries:
  - id: "Error"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessImageView-GetOrganizationPrimaryViewID"
    bindings:
      Domain: "Repository:OwningDomain:Site"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "ExecuteStoredProcedure1"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      StoredProcedure: "SP_UPDATE_CATEGORYIMAGES"
      ParameterDefinition: "CatalogUUID=string;PrimaryViewID=string"
      AllowNullParameter: false
  - id: "GetCatalogs1"
    type: "pipelet"
    ref: "GetCatalogs"
    config:
      CatalogType: "Product Catalog"
      OnlineOnly: "True"
      ProxyFilter: "OFF - All Catalogs"
    bindings:
      OrganizationDomain: "Domain"
  - id: "GetDomainByName1"
    type: "pipelet"
    ref: "GetDomainByName"
    bindings:
      DomainName: "RepositoryDomainName"
  - id: "GetRepositoryByRepositoryDomain1"
    type: "pipelet"
    ref: "GetRepositoryByRepositoryDomain"
    bindings:
      RepositoryDomain: "Domain"
  - id: "GetStringSubstitution1"
    type: "pipelet"
    ref: "GetStringSubstitution"
    config:
      DefaultPattern: "-Site"
    bindings:
      InputString: "CurrentDomain:DomainName"
      OutputString: "RepositoryDomainName"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      OutValue_1: "CatalogUUID"
      InValue_1: "Catalog:UUID"
      OutValue_2: "PrimaryViewID"
      InValue_2: "PrimaryImageViewID"
  - id: "LoopNode1"
    type: "loop"
  - id: "RefreshCache1"
    type: "pipelet"
    ref: "RefreshCache"
    config:
      PersistentClassName_0: "com.intershop.beehive.xcs.internal.catalog.CatalogCategoryPO"

links:
  - from: "GetStringSubstitution1"
    via: "next"
    to: "GetDomainByName1"
    into: "in"
  - from: "GetDomainByName1"
    via: "next"
    to: "GetCatalogs1"
    into: "in"
  - from: "GetRepositoryByRepositoryDomain1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "ExecuteStoredProcedure1"
    into: "in"
  - from: "GetRepositoryByRepositoryDomain1"
    via: "error"
    to: "LoopNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "GetStringSubstitution1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "RefreshCache1"
    into: "in"
  - from: "ExecuteStoredProcedure1"
    via: "error"
    to: "JoinNode1"
    into: "in3"
  - from: "Error"
    via: "next"
    to: "GetStringSubstitution1"
    into: "in"
  - from: "ExecuteStoredProcedure1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "RefreshCache1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "KeyMapper1"
    into: "in"
  - from: "GetCatalogs1"
    via: "next"
    to: "GetRepositoryByRepositoryDomain1"
    into: "in"
  - from: "GetDomainByName1"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "LoopNode1"
    into: "in"
