flow: "ProcessSearchFilterGroup"
kind: "process"

entries:
  - id: "StartNode1"
    name: "GetFilterAttributesByCategory"
    mode: "private"
    strict: false
    inputs:
      - key: "CategoryID"
        type: "java.lang.String"
        required: true
  - id: "StartNode9"
    name: "UnassignFilters"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CreateStringSplitter1"
    type: "pipelet"
    ref: "CreateStringSplitter"
    config:
      Mode: "First Occurrence"
      Separator: "@"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "CategoryFilterAttributes"
        type: "java.util.Iterator"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "GetCatalogByCategory1"
    type: "pipelet"
    ref: "GetCatalogByCategory"
  - id: "GetCategoryByName1"
    type: "pipelet"
    ref: "GetCategoryByName"
    bindings:
      CategoryName: "Splitter:Begin(CategoryName)"
      Category: "CatalogCategory"
      CategoryDomainName: "Splitter:End(CategoryName)"
  - id: "GetFilterAttributesForCatalogCategory1"
    type: "pipelet"
    ref: "GetFilterAttributesForCatalogCategory"
    bindings:
      FilterAttributes: "CategoryFilterAttributes"
      CatalogId: "Catalog:Id"
      CurrentDomain: "Domain"
  - id: "GetOnlineSearchIndexByFeatureID1"
    type: "pipelet"
    ref: "GetOnlineSearchIndexByFeatureID"
    bindings:
      FeatureID: "\"SFProductSearch\""
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "removeFilter"
      InValue_1: "SearchIndex:Configuration:AttributeByName(AttributeName)"
  - id: "LoopNode2"
    type: "loop"
  - id: "UpdateFilterGroup2"
    type: "pipelet"
    ref: "UpdateFilterGroup"
    bindings:
      GroupID: "null"
      Threshhold: "null"
      AddFilter: "null"
      DisplayName: "null"

links:
  - from: "GetCategoryByName1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "StartNode1"
    via: "next"
    to: "CreateStringSplitter1"
    into: "in"
  - from: "CreateStringSplitter1"
    via: "next"
    to: "GetCategoryByName1"
    into: "in"
  - from: "UpdateFilterGroup2"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "LoopNode2"
    via: "do"
    to: "KeyMapper2"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "GetFilterAttributesForCatalogCategory1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "UpdateFilterGroup2"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "GetCategoryByName1"
    via: "next"
    to: "GetCatalogByCategory1"
    into: "in"
  - from: "GetCatalogByCategory1"
    via: "next"
    to: "GetOnlineSearchIndexByFeatureID1"
    into: "in"
  - from: "GetOnlineSearchIndexByFeatureID1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "GetCatalogByCategory1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "GetOnlineSearchIndexByFeatureID1"
    via: "next"
    to: "GetFilterAttributesForCatalogCategory1"
    into: "in"
