flow: "ProcessOrganizationEnterprise"
kind: "process"

entries:
  - id: "Start1"
    name: "Remove"
    mode: "private"
    strict: false
    inputs:
      - key: "DeleteOrganizationEnterprise"
        type: "com.intershop.component.organization.capi.Organization"
        required: false
  - id: "Start6"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector7"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Object: "\"20\""
      Iterator: "TypeCodes"
  - id: "Call1"
    type: "call"
    ref: "Organization-Remove"
    bindings:
      RemoveOrganizationDomainSite: "\"true\""
  - id: "Call4"
    type: "call"
    ref: "Organization-CreateSite"
  - id: "Call5"
    type: "call"
    ref: "Organization-Create"
  - id: "CheckForEmptyString1"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "OrganizationState"
  - id: "Decision1"
    type: "decision"
    condition: "OrganizationID"
  - id: "Decision2"
    type: "decision"
    condition: "AdminPassword"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      Datasource: "default"
      DefaultPageSize: 10
      QueryName: "organization/GetOrganizationsByOwningDomain"
      ParameterName_01: "OwningDomain"
      ParameterName_02: "TypeCodes"
      ParameterName_03: "SortBy"
    bindings:
      ParameterValue_01: "CurrentOrganization:Domain"
      ParameterValue_02: "TypeCodes"
      ParameterValue_03: "\"ID\""
      SearchResult: "EnterpriseOrganizations"
  - id: "GetOrganization1"
    type: "pipelet"
    ref: "GetOrganization"
    config:
      Source: "PipelineDictionary"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "SiteDomain"
      InValue_2: "Organization:Domain"
      OutValue_1: "Site"
      OutValue_2: "Owner"
  - id: "RemoveDomainFileStructure1"
    type: "pipelet"
    ref: "RemoveDomainFileStructure"
    bindings:
      Domain: "SiteDomain"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: "PasswordConfirmationDoesNotMatchWithPassword"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ParentDomainName"
      Value: "root"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ORG_VALIDATION_ERROR"
      Value: "Sitenname EQ OrganizationID"
  - id: "SetDictionaryValue5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "OrganizationState"
      Value: 0
  - id: "SetDictionaryValue8"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "SITE_CREATION_ERROR"
      Value: "ID in use"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      LocalizedString: "ApplicationTypeID"
      IntegerObject: "ApplicationTypeID"
  - id: "VerifyInteger2"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      LocalizedString: "OrganizationType"
      IntegerObject: "OrganizationType"
  - id: "VerifyInteger3"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      LocalizedString: "OrganizationState"
      IntegerObject: "OrganizationState"

links:
  - from: "AddObjectToVector7"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "Call1"
    via: "ERROR"
    to: "Join7"
    into: "in1"
  - from: "Call1"
    via: "next"
    to: "End3"
    into: "in"
  - from: "Call4"
    via: "ERROR"
    to: "SetDictionaryValue8"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "Call5"
    via: "ERROR"
    to: "RemoveDomainFileStructure1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "End2"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "error"
    to: "SetDictionaryValue5"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Decision1"
    via: "no"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "CheckForEmptyString1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "error"
    to: "EndNode2"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "GetOrganization1"
    via: "error"
    to: "Join7"
    into: "in1"
  - from: "GetOrganization1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "End4"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Join4"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "Join5"
    via: "next"
    to: "VerifyInteger3"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "Join7"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join9"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "KeyMapper4"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "RemoveDomainFileStructure1"
    via: "error"
    to: "Join8"
    into: "in1"
  - from: "RemoveDomainFileStructure1"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "SetDictionaryValue5"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "SetDictionaryValue8"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "GetOrganization1"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "AddObjectToVector7"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "VerifyInteger1"
    via: "next"
    to: "VerifyInteger2"
    into: "in"
  - from: "VerifyInteger2"
    via: "error"
    to: "Join6"
    into: "in1"
  - from: "VerifyInteger2"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "VerifyInteger3"
    via: "error"
    to: "Join9"
    into: "in1"
  - from: "VerifyInteger3"
    via: "next"
    to: "SetDictionaryValue3"
    into: "in"
