flow: "ProcessChannelCategorySorting"
kind: "process"

entries:
  - id: "Start1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "UpdateProductSorting"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "UpdateSubCategorySorting"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "GetExtensibleObject"
    mode: "private"
    strict: true
    inputs:
      - key: "Catalog"
        type: "com.intershop.component.mvc.capi.catalog.Catalog"
        required: true
      - key: "Category"
        type: "com.intershop.beehive.xcs.capi.catalog.CatalogCategory"
        required: true

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessChannelCategorySorting-Prefix"
  - id: "Call2"
    type: "call"
    ref: "ProcessChannelCategorySorting-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ProcessChannelCategorySorting-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ProcessCatalogSorting-UpdateCustomProductSorting"
  - id: "Call5"
    type: "call"
    ref: "ProcessCatalogSorting-UpdateCustomSubCategorySorting"
  - id: "Call8"
    type: "call"
    ref: "ViewCatalog-GetCatalog"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessChannelCategorySorting-GetExtensibleObject"
    bindings:
      Catalog: "Catalog"
      Category: "Category"
      ExtensibleObject: "ExtensibleObject"
  - id: "CheckForEmptyString1"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "ProductSortingCustomValue"
  - id: "CheckForEmptyString2"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "SubCategorySortingCustomValue"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "ProductSortingAttribute"
      param.1.required: false
      param.2.name: "ProductSortingStandardValue"
      param.2.required: false
      param.3.name: "ProductSortingCustomValue"
      param.3.required: false
      param.4.name: "ProductSortingDirection"
      param.4.required: true
      webform-id: "RegFormProductSorting"
      param.1.rule: ""
      param.2.rule: ""
      param.3.rule: ""
      param.4.rule: ""
      param.5.name: "ProductSortingType"
      param.5.rule: ""
      param.5.required: true
      param.6.name: "ProductSortingCustomValueType"
      param.6.rule: ""
      param.6.required: false
      param.7.name: "ProductSortingCustomLocalizableFlag"
      param.7.rule: ""
      param.7.required: false
    bindings:
      WebForm: "RegFormProductSorting"
  - id: "CreateWebForm2"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "SubCategorySortingAttribute"
      param.1.required: false
      param.2.name: "SubCategorySortingStandardValue"
      param.2.required: false
      param.3.name: "SubCategorySortingDirection"
      param.3.required: true
      param.4.name: "SubCategorySortingType"
      param.4.required: true
      webform-id: "RegFormSubCategorySorting"
      param.1.rule: ""
      param.2.rule: ""
      param.3.rule: ""
      param.4.rule: ""
      param.5.name: "SubCategorySortingCustomValue"
      param.5.rule: ""
      param.5.required: false
      param.6.name: "SubCategorySortingCustomValueType"
      param.6.rule: ""
      param.6.required: false
      param.7.name: "SubCategorySortingCustomLocalizableFlag"
      param.7.rule: ""
      param.7.required: false
    bindings:
      WebForm: "RegFormSubCategorySorting"
  - id: "Decision1"
    type: "decision"
    condition: "SubCategorySortingAttribute"
  - id: "Decision2"
    type: "decision"
    condition: "ProductSortingAttribute"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ProductSortingType"
  - id: "DecisionNode2"
    type: "decision"
    condition: "SubCategorySortingType"
  - id: "DecisionNode3"
    type: "decision"
    condition: "RegFormProductSorting_ProductSortingCustomLocalizableFlag"
  - id: "DecisionNode4"
    type: "decision"
    condition: "RegFormSubCategorySorting_SubCategorySortingCustomLocalizableFlag"
  - id: "DecisionNode5"
    type: "decision"
    condition: "CatalogCategoryID"
  - id: "DecisionNode6"
    type: "decision"
    condition: "Category:isRootCategory"
  - id: "DecisionNode7"
    type: "decision"
    condition: "CatalogID"
  - id: "DecisionNode8"
    type: "decision"
    condition: "Catalog"
  - id: "DecisionNode9"
    type: "decision"
    condition: "CatalogCategoryID"
  - id: "DetermineCatalogCategoriesPath1"
    type: "pipelet"
    ref: "DetermineCatalogCategoriesPath"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ProcessChannelCategorySorting-UpdateProductSorting"
      OutValue_1: "ProcessChannelCategorySorting-UpdateSubCategorySorting"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "updateProductSorting"
      Key_1: "updateSubCategorySorting"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "ExtensibleObject"
        type: "com.intershop.beehive.core.capi.domain.ExtensibleObject"
        guaranteed: true
  - id: "GetCategoryByUUID2"
    type: "pipelet"
    ref: "GetCategoryByUUID"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "RegFormProductSorting"
    bindings:
      WebForm: "RegFormProductSorting"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "RegFormSubCategorySorting"
    bindings:
      WebForm: "RegFormSubCategorySorting"
  - id: "Join5"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewChannelCatalogList_52-ListAll"
  - id: "Jump3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump4"
    type: "jump"
    ref: "ProcessChannelCategorySorting-Start"
  - id: "Jump6"
    type: "jump"
    ref: "ProcessChannelCategorySorting-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "RegFormProductSorting_ProductSortingAttribute"
      InValue_2: "RegFormProductSorting_ProductSortingDirection"
      InValue_3: "RegFormProductSorting_ProductSortingStandardValue"
      InValue_4: "RegFormProductSorting_ProductSortingCustomValue"
      OutValue_1: "ProductSortingAttribute"
      OutValue_2: "ProductSortingDirection"
      OutValue_3: "ProductSortingStandardValue"
      OutValue_4: "ProductSortingCustomValue"
      InValue_5: "RegFormProductSorting_ProductSortingType"
      OutValue_5: "ProductSortingType"
      InValue_6: "ExtensibleObject"
      OutValue_6: "ExtensibleObject"
      InValue_7: "RegFormProductSorting_ProductSortingCustomValueType"
      OutValue_7: "ProductSortingCustomValueType"
      InValue_8: "RegFormProductSorting_ProductSortingCustomLocalizableFlag"
      OutValue_8: "ProductSortingCustomLocalizableFlag"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "RegFormSubCategorySorting_SubCategorySortingAttribute"
      InValue_2: "RegFormSubCategorySorting_SubCategorySortingDirection"
      InValue_3: "RegFormSubCategorySorting_SubCategorySortingStandardValue"
      InValue_4: "RegFormSubCategorySorting_SubCategorySortingCustomValue"
      OutValue_1: "SubCategorySortingAttribute"
      OutValue_2: "SubCategorySortingDirection"
      OutValue_3: "SubCategorySortingStandardValue"
      OutValue_4: "SubCategorySortingCustomValue"
      InValue_5: "RegFormSubCategorySorting_SubCategorySortingType"
      OutValue_5: "SubCategorySortingType"
      InValue_6: "ExtensibleObject"
      OutValue_6: "ExtensibleObject"
      InValue_7: "RegFormSubCategorySorting_SubCategorySortingCustomValueType"
      OutValue_7: "SubCategorySortingCustomValueType"
      OutValue_8: "SubCategorySortingCustomLocalizableFlag"
      InValue_8: "RegFormSubCategorySorting_SubCategorySortingCustomLocalizableFlag"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "RegFormProductSorting_ProductSortingAttribute"
      InValue_2: "RegFormProductSorting_ProductSortingDirection"
      InValue_3: "RegFormProductSorting_ProductSortingStandardValue"
      InValue_4: "RegFormProductSorting_ProductSortingCustomValue"
      OutValue_1: "ProductSortingAttribute"
      OutValue_2: "ProductSortingDirection"
      OutValue_3: "ProductSortingStandardValue"
      OutValue_4: "ProductSortingCustomValue"
      InValue_5: "RegFormProductSorting_ProductSortingType"
      OutValue_5: "ProductSortingType"
      InValue_6: "ExtensibleObject"
      OutValue_6: "ExtensibleObject"
      InValue_7: "RegFormProductSorting_ProductSortingCustomValueType"
      OutValue_7: "ProductSortingCustomValueType"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentSelectedChannel:Domain"
      OutValue_1: "CatalogOrganizationDomain"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "RegFormSubCategorySorting_SubCategorySortingAttribute"
      InValue_2: "RegFormSubCategorySorting_SubCategorySortingDirection"
      InValue_3: "RegFormSubCategorySorting_SubCategorySortingStandardValue"
      InValue_4: "RegFormSubCategorySorting_SubCategorySortingCustomValue"
      OutValue_1: "SubCategorySortingAttribute"
      OutValue_2: "SubCategorySortingDirection"
      OutValue_3: "SubCategorySortingStandardValue"
      OutValue_4: "SubCategorySortingCustomValue"
      InValue_5: "RegFormSubCategorySorting_SubCategorySortingType"
      OutValue_5: "SubCategorySortingType"
      InValue_6: "ExtensibleObject"
      OutValue_6: "ExtensibleObject"
      InValue_7: "RegFormSubCategorySorting_SubCategorySortingCustomValueType"
      OutValue_7: "SubCategorySortingCustomValueType"
  - id: "KeyMapper6"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Catalog:Root"
      OutValue_1: "Category"
  - id: "KeyMapper7"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Catalog"
      OutValue_1: "ExtensibleObject"
  - id: "KeyMapper8"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Category"
      OutValue_1: "ExtensibleObject"
  - id: "UpdateCustomAttribute1"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    config:
      DefaultAttributeName: "SUBCATEGORY_SORTING_TYPE"
      DefaultAttributeType: "String"
    bindings:
      AttributeValue: "SubCategorySortingType"
  - id: "UpdateCustomAttribute6"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    config:
      DefaultAttributeName: "PRODUCT_SORTING_TYPE"
      DefaultAttributeType: "String"
    bindings:
      AttributeValue: "ProductSortingType"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "RegFormProductSorting"
    bindings:
      WebForm: "RegFormProductSorting"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "RegFormSubCategorySorting"
    bindings:
      WebForm: "RegFormSubCategorySorting"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "RegFormProductSorting"
  - id: "ValidateWebForm2"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "RegFormSubCategorySorting"

links:
  - from: "Start1"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "Decision2"
    into: "in"
  - from: "UpdateCustomAttribute6"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CreateWebForm1"
    via: "next"
    to: "CreateWebForm2"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "ValidateWebForm1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "Start4"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "DetermineCatalogCategoriesPath1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "Join5"
    into: "in2"
  - from: "CreateWebForm2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "UpdateCustomAttribute6"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "ValidateWebForm2"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "CheckForEmptyString1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode5"
    via: "yes"
    to: "KeyMapper6"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Call4"
    into: "in"
  - from: "CheckForEmptyString2"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "GetWebForm2"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "UpdateWebForm2"
    via: "next"
    to: "ValidateWebForm2"
    into: "in"
  - from: "ValidateWebForm1"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "DecisionNode9"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "JoinNode7"
    into: "in2"
  - from: "KeyMapper4"
    via: "next"
    to: "DecisionNode8"
    into: "in"
  - from: "ValidateWebForm2"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "UpdateCustomAttribute1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "Jump6"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "Decision1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "CheckForEmptyString2"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Call5"
    into: "in"
  - from: "GetCategoryByUUID2"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "KeyMapper7"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "Call8"
    via: "ERROR"
    to: "JoinNode7"
    into: "in1"
  - from: "DecisionNode3"
    via: "yes"
    to: "KeyMapper1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "KeyMapper3"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "KeyMapper5"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "UpdateCustomAttribute6"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "KeyMapper2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "UpdateCustomAttribute1"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "UpdateCustomAttribute1"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "CheckForEmptyString2"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "KeyMapper8"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "KeyMapper7"
    into: "in"
  - from: "KeyMapper6"
    via: "next"
    to: "DetermineCatalogCategoriesPath1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "GetCategoryByUUID2"
    via: "next"
    to: "DetermineCatalogCategoriesPath1"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "KeyMapper8"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "JoinNode8"
    into: "in3"
  - from: "Start2"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "Call8"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode8"
    via: "no"
    to: "DecisionNode7"
    into: "in"
  - from: "DecisionNode8"
    via: "yes"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode9"
    via: "yes"
    to: "KeyMapper6"
    into: "in"
  - from: "DecisionNode9"
    via: "no"
    to: "GetCategoryByUUID2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "Jump4"
    into: "in"
