flow: "ProcessAnalyzeTables"
kind: "process"

entries:
  - id: "StartNode1"
    name: "GetProcess"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "AnalyzeTables"
    mode: "private"
    strict: false
    inputs:
      - key: "TableNames"
        type: "java.util.Iterator"
        required: false
      - key: "Controller"
        type: "com.intershop.beehive.core.capi.impex.Controller"
        required: false

steps:
  - id: "AcquireResourcesForProcess1"
    type: "pipelet"
    ref: "AcquireResourcesForProcess"
    bindings:
      AcquisitionTimeout: "\"(Integer)300\""
      ResourceIDs: "TableNames"
  - id: "AnalyzeTable1"
    type: "pipelet"
    ref: "AnalyzeTable"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessAnalyzeTables-GetProcess"
  - id: "CreateDatabaseTableResources1"
    type: "pipelet"
    ref: "CreateDatabaseTableResources"
    bindings:
      TableNames: "TableNamesIterator"
  - id: "CreateIteratorFromConfigValues1"
    type: "pipelet"
    ref: "CreateIteratorFromConfigValues"
    config:
      Delimiters: ";"
    bindings:
      ValuesString: "TableNames"
      ValuesIterator: "TableNamesIterator"
  - id: "CreateProcess1"
    type: "pipelet"
    ref: "CreateProcess"
    config:
      InitialState: "starting"
      ProcessDescription: "Analyzing tables."
      ProcessName: "Analyze Tables"
      Type: "TableAnalyzer"
  - id: "DecisionNode1"
    type: "decision"
    condition: "TableName"
  - id: "DecisionNode2"
    type: "decision"
    condition: "CurrentProcess"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Process:Name"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Process"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode5"
    type: "end"
    strict: false
  - id: "FinishProcess1"
    type: "pipelet"
    ref: "FinishProcess"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentProcess"
      OutValue_1: "Process"
  - id: "LoopNode1"
    type: "loop"
  - id: "ReleaseResourcesForProcess1"
    type: "pipelet"
    ref: "ReleaseResourcesForProcess"

links:
  - from: "DecisionNode4"
    via: "no"
    to: "DecisionNode2"
    into: "in"
  - from: "AcquireResourcesForProcess1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode2"
    into: "in2"
  - from: "CallNode1"
    via: "next"
    to: "CreateIteratorFromConfigValues1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "DecisionNode1"
    via: "no"
    to: "AnalyzeTable1"
    into: "in"
  - from: "AnalyzeTable1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "KeyMapper1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "ReleaseResourcesForProcess1"
    into: "in"
  - from: "CreateIteratorFromConfigValues1"
    via: "next"
    to: "CreateDatabaseTableResources1"
    into: "in"
  - from: "CreateProcess1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "FinishProcess1"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "DecisionNode3"
    via: "no"
    to: "FinishProcess1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "CreateDatabaseTableResources1"
    via: "next"
    to: "AcquireResourcesForProcess1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "CreateProcess1"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "JoinNode3"
    into: "in1"
  - from: "AcquireResourcesForProcess1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "JoinNode1"
    into: "in2"
  - from: "LoopNode1"
    via: "do"
    to: "DecisionNode1"
    into: "in"
  - from: "ReleaseResourcesForProcess1"
    via: "next"
    to: "DecisionNode3"
    into: "in"
