flow: "ProcessFile"
kind: "process"

entries:
  - id: "StartNode3"
    name: "CopyFile"
    mode: "private"
    strict: true
    inputs:
      - key: "UnitDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "TargetDirectoryPath"
        type: "java.lang.String"
        required: false
      - key: "Secure"
        type: "java.lang.String"
        required: false
      - key: "FileNames"
        type: "java.util.Iterator"
        required: true
  - id: "StartNode4"
    name: "UploadFile"
    mode: "private"
    strict: true
    inputs:
      - key: "UnitDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true

steps:
  - id: "AddObjectToVector3"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "ExistingFilesVector"
      OutVector: "ExistingFilesVector"
      Iterator: "ExistingFiles"
      Objects: "ExistingFiles"
  - id: "AddObjectToVector4"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      OutVector: "ExistingFilesVector"
      Iterator: "ExistingFiles"
  - id: "CheckForExistingFiles1"
    type: "pipelet"
    ref: "CheckForExistingFiles"
    config:
      Recursive: false
      SourceDirectoryPath: "upload"
      SourceUnitDirectory: "IMPEX_DIR"
    bindings:
      Locale: "null"
      Files: "ExistingFiles"
      SourceDirectoryPath: "null"
      SourceUnitDirectory: "null"
      SourceUnitDomain: "UnitDomain"
      TargetUnitDomain: "UnitDomain"
      TargetUnitDirectory: "TargetUnitDirectoryName"
  - id: "DecisionNode1"
    type: "decision"
    condition: "File:Extension"
  - id: "DecisionNode10"
    type: "decision"
    condition: "File:Size"
  - id: "DecisionNode11"
    type: "decision"
    condition: "File:Extension"
  - id: "DecisionNode13"
    type: "decision"
    condition: "Secure"
  - id: "DecisionNode14"
    type: "decision"
    condition: "Secure"
  - id: "DecisionNode8"
    type: "decision"
    condition: "Secure"
  - id: "DecisionNode9"
    type: "decision"
    condition: "ExistingFiles"
  - id: "DetermineLocales3"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorCode"
        type: "java.lang.String"
        guaranteed: false
      - key: "Secure"
        type: "java.lang.String"
        guaranteed: false
      - key: "DirectoryPath"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorCode"
        type: "java.lang.String"
        guaranteed: false
      - key: "Secure"
        type: "java.lang.String"
        guaranteed: false
      - key: "DirectoryPath"
        type: "java.lang.String"
        guaranteed: false
      - key: "FileNames"
        type: "java.util.Iterator"
        guaranteed: false
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "DirectoryPath"
        type: "java.lang.String"
        guaranteed: false
      - key: "Secure"
        type: "java.lang.String"
        guaranteed: false
      - key: "FileNames"
        type: "java.util.Iterator"
        guaranteed: true
      - key: "Upload"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "ExistingFiles"
        type: "java.util.Iterator"
        guaranteed: true
      - key: "FileName"
        type: "java.lang.String"
        guaranteed: true
      - key: "Secure"
        type: "java.lang.String"
        guaranteed: false
      - key: "DirectoryPath"
        type: "java.lang.String"
        guaranteed: false
      - key: "Upload"
        type: "java.lang.String"
        guaranteed: false
      - key: "FileNames"
        type: "java.util.Iterator"
        guaranteed: false
  - id: "GetLocale3"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode24"
    type: "join"
  - id: "JoinNode25"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "DirectoryPath"
      OutValue_1: "TargetDirectoryPath"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode4"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "CopyFile"
    config:
      DefaultSourceDirectoryPath: "upload"
      DefaultSourceUnitDirectory: "IMPEX_DIR"
      DefaultTargetUnitDirectory: "SECURE_STATIC_DIR"
    bindings:
      SourceFileName: "FileName"
      SourceUnitDomain: "UnitDomain"
      TargetFileName: "FileName"
      TargetUnitDomain: "UnitDomain"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "VerifyZipFile"
    config:
      DefaultDirectoryPath: "upload"
      DefaultUnitDirectory: "IMPEX_DIR"
    bindings:
      UnitDomain: "UnitDomain"
      UnitDirectory: "null"
      DirectoryPath: "null"
      Locale: "null"
      ZipFile: "FileName"
  - id: "Pipelet12"
    type: "pipelet"
    ref: "ExtractCompressedFile"
    config:
      Overwrite: true
    bindings:
      SourceUnitDomain: "UnitDomain"
      TargetUnitDomain: "UnitDomain"
      FileName: "FileName"
      SourceDirectoryPath: "\"upload\""
      SourceUnitDirectory: "\"IMPEX_DIR\""
      TargetUnitDirectory: "\"SECURE_STATIC_DIR\""
  - id: "Pipelet13"
    type: "pipelet"
    ref: "ProcessMultipartRequest"
    config:
      DirectoryPath: "upload"
      MaxFileSize: 100
      UnitDirectory: "IMPEX_DIR"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "CopyFile"
    config:
      DefaultSourceDirectoryPath: "upload"
      DefaultSourceUnitDirectory: "IMPEX_DIR"
      DefaultTargetUnitDirectory: "STATIC_CONTENT_DIR"
    bindings:
      SourceFileName: "FileName"
      SourceUnitDomain: "UnitDomain"
      TargetFileName: "FileName"
      TargetUnitDomain: "UnitDomain"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "DeleteFile"
    config:
      DefaultDirectoryPath: "upload"
      UnitDirectory: "IMPEX_DIR"
    bindings:
      FileName: "FileName"
      Locale: "void"
      DirectoryPath: "null"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "ExtractCompressedFile"
    config:
      Overwrite: true
    bindings:
      SourceUnitDomain: "UnitDomain"
      TargetUnitDomain: "UnitDomain"
      FileName: "FileName"
      SourceDirectoryPath: "\"upload\""
      SourceUnitDirectory: "\"IMPEX_DIR\""
      TargetUnitDirectory: "\"STATIC_CONTENT_DIR\""
  - id: "ResolveFilename1"
    type: "pipelet"
    ref: "ResolveFilename"
    config:
      UnitDirectory: "IMPEX_DIR"
    bindings:
      DirectoryPath: "\"upload\""
  - id: "SetDictionaryValue10"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "TargetUnitDirectoryName"
      Value: "SECURE_STATIC_DIR"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue11"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "TargetUnitDirectoryName"
      Value: "STATIC_CONTENT_DIR"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: "ZeroFileLenght"
  - id: "SetDictionaryValue9"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: "FileUploadError"
  - id: "VerifyZipFile1"
    type: "pipelet"
    ref: "VerifyZipFile"
    config:
      DefaultDirectoryPath: "upload"
      DefaultUnitDirectory: "IMPEX_DIR"
    bindings:
      UnitDirectory: "null"
      DirectoryPath: "null"
      Locale: "null"
      ZipFile: "FileName"

links:
  - from: "SetDictionaryValue11"
    via: "next"
    to: "JoinNode25"
    into: "in3"
  - from: "DecisionNode11"
    via: "no"
    to: "JoinNode12"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "DetermineLocales3"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode9"
    via: "no"
    to: "EndNode3"
    into: "in"
  - from: "Pipelet13"
    via: "error"
    to: "EndNode2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "Pipelet13"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "DecisionNode14"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode24"
    into: "in1"
  - from: "VerifyZipFile1"
    via: "next"
    to: "Pipelet12"
    into: "in"
  - from: "Pipelet2"
    via: "error"
    to: "SetDictionaryValue9"
    into: "in"
  - from: "SetDictionaryValue7"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet11"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode13"
    into: "in2"
  - from: "DecisionNode13"
    via: "no"
    to: "JoinNode4"
    into: "in2"
  - from: "JoinNode24"
    via: "next"
    to: "JoinNode13"
    into: "in1"
  - from: "DecisionNode11"
    via: "yes"
    to: "VerifyZipFile1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "CheckForExistingFiles1"
    via: "next"
    to: "AddObjectToVector3"
    into: "in"
  - from: "DetermineLocales3"
    via: "next"
    to: "GetLocale3"
    into: "in"
  - from: "AddObjectToVector3"
    via: "next"
    to: "LoopNode4"
    into: "loop"
  - from: "DecisionNode13"
    via: "yes"
    to: "DecisionNode8"
    into: "in"
  - from: "DecisionNode9"
    via: "yes"
    to: "EndNode6"
    into: "in"
  - from: "Pipelet13"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "DecisionNode8"
    via: "yes"
    to: "DecisionNode11"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "GetLocale3"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "AddObjectToVector4"
    via: "next"
    to: "LoopNode4"
    into: "in"
  - from: "DecisionNode8"
    via: "no"
    to: "JoinNode4"
    into: "in1"
  - from: "LoopNode4"
    via: "do"
    to: "CheckForExistingFiles1"
    into: "in"
  - from: "JoinNode25"
    via: "next"
    to: "AddObjectToVector4"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "ResolveFilename1"
    via: "next"
    to: "DecisionNode10"
    into: "in"
  - from: "SetDictionaryValue10"
    via: "next"
    to: "JoinNode25"
    into: "in1"
  - from: "DecisionNode10"
    via: "yes"
    to: "DecisionNode13"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "LoopNode1"
    via: "do"
    to: "ResolveFilename1"
    into: "in"
  - from: "LoopNode4"
    via: "next"
    to: "DecisionNode9"
    into: "in"
  - from: "JoinNode13"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Pipelet12"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "VerifyZipFile1"
    via: "error"
    to: "JoinNode12"
    into: "in2"
  - from: "Pipelet5"
    via: "next"
    to: "JoinNode24"
    into: "in2"
  - from: "Pipelet11"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "JoinNode12"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "DecisionNode14"
    via: "yes"
    to: "SetDictionaryValue10"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "Pipelet12"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "Pipelet5"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "SetDictionaryValue9"
    into: "in"
  - from: "Pipelet11"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "DecisionNode10"
    via: "no"
    to: "SetDictionaryValue7"
    into: "in"
  - from: "SetDictionaryValue9"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode14"
    via: "no"
    to: "SetDictionaryValue11"
    into: "in"
