flow: "ProcessOrderSearchExtension"
kind: "extension"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      - key: "OrderSearchParameters"
        type: "java.util.Map"
        required: true
      - key: "Repository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true

steps:
  - id: "DecisionNode18"
    type: "decision"
    condition: "Repository:TypeCode"
  - id: "DecisionNode19"
    type: "decision"
    condition: "Repository:TypeCode"
  - id: "DecisionNode20"
    type: "decision"
    condition: "Repository:TypeCode"
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "OrderSearchParameters"
        type: "java.util.Map"
        guaranteed: true
  - id: "JoinNode19"
    type: "join"
  - id: "JoinNode20"
    type: "join"
  - id: "JoinNode24"
    type: "join"
  - id: "TextNode1"
    type: "text"
  - id: "TextNode2"
    type: "text"
  - id: "TextNode3"
    type: "text"
  - id: "UpdateDictionary10"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "OrderSearchType"
    bindings:
      OutDictionary: "OrderSearchParameters"
      InDictionary: "OrderSearchParameters"
      Value_01: "\"Customer\""
  - id: "UpdateDictionary11"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "OrderSearchType"
    bindings:
      OutDictionary: "OrderSearchParameters"
      InDictionary: "OrderSearchParameters"
      Value_01: "\"Consumer\""

links:
  - from: "DecisionNode19"
    via: "no"
    to: "DecisionNode20"
    into: "in"
  - from: "JoinNode20"
    via: "next"
    to: "JoinNode19"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "DecisionNode18"
    into: "in"
  - from: "JoinNode19"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "DecisionNode19"
    via: "yes"
    to: "JoinNode24"
    into: "in1"
  - from: "JoinNode24"
    via: "next"
    to: "UpdateDictionary10"
    into: "in"
  - from: "DecisionNode20"
    via: "no"
    to: "JoinNode19"
    into: "in2"
  - from: "UpdateDictionary11"
    via: "next"
    to: "JoinNode20"
    into: "in2"
  - from: "DecisionNode18"
    via: "no"
    to: "DecisionNode19"
    into: "in"
  - from: "DecisionNode20"
    via: "yes"
    to: "UpdateDictionary11"
    into: "in"
  - from: "DecisionNode18"
    via: "yes"
    to: "JoinNode24"
    into: "in1"
  - from: "UpdateDictionary10"
    via: "next"
    to: "JoinNode20"
    into: "in1"
