flow: "ProcessWhiteStoreCMSContent"
kind: "process"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      - key: "Repository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true

steps:
  - id: "AddObjectToString2"
    type: "pipelet"
    ref: "AddObjectToString"
    config:
      DefaultSeparator: "-"
    bindings:
      InObject: "Repository:Id"
      InString: "Organization:Domain:DomainName"
      OutString: "TargetDomainName"
  - id: "BrowseDirectory1"
    type: "pipelet"
    ref: "BrowseDirectory"
    config:
      UnitDirectory: "IMPEX_SRC_DIR"
      DefaultDirectoryPath: "whitestore"
      Recursive: false
      IncludeParentDirectories: false
    bindings:
      UnitDomain: "SourceDomain"
  - id: "CreateZipFile1"
    type: "pipelet"
    ref: "CreateZipFile"
    config:
      DefaultSourceUnitDirectory: "IMPEX_SRC_DIR"
      DefaultTargetUnitDirectory: "IMPEX_SRC_DIR"
      DefaultTargetFileName: "whitestore-democontent.zip"
      DefaultSourceDirectoryPath: "whitestore"
      Compression: true
    bindings:
      TargetUnitDomain: "TargetDomain"
      SourceUnitDomain: "SourceDomain"
      TargetDirectoryPath: "null"
      SourceDirectoryPath: "null"
      SourceFileName: "null"
      TargetFileName: "null"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Directory:Directories"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Repository:TypeCode"
  - id: "DecisionNode3"
    type: "decision"
    condition: "SourceDomain:DomainName"
  - id: "DecisionNode4"
    type: "decision"
    condition: "CurrentDomain:Configuration:String(\"whitestore.democontent.sourcedomain\")"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "GetDomainByName1"
    type: "pipelet"
    ref: "GetDomainByName"
    bindings:
      DomainName: "CurrentDomain:Configuration:String(\"whitestore.democontent.sourcedomain\")"
      Domain: "SourceDomain"
  - id: "GetDomainByName2"
    type: "pipelet"
    ref: "GetDomainByName"
    bindings:
      DomainName: "TargetDomainName"
      Domain: "TargetDomain"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"

links:
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "GetDomainByName1"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GetDomainByName2"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode7"
    into: "in2"
  - from: "CreateZipFile1"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "CreateZipFile1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "AddObjectToString2"
    into: "in"
  - from: "GetDomainByName2"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode3"
    via: "yes"
    to: "CreateZipFile1"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "GetDomainByName1"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode4"
    into: "in2"
  - from: "GetDomainByName1"
    via: "next"
    to: "BrowseDirectory1"
    into: "in"
  - from: "BrowseDirectory1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "BrowseDirectory1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "AddObjectToString2"
    via: "next"
    to: "GetDomainByName2"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode8"
    into: "in2"
