flow: "ProcessWebforms"
kind: "process"

entries:
  - id: "StartNode1"
    name: "CreateCountrySpecificForm"
    mode: "private"
    strict: true
    inputs:
      - key: "FormName"
        type: "java.lang.String"
        required: true
      - key: "FormAlias"
        type: "java.lang.String"
        required: false
      - key: "CountryCode"
        type: "java.lang.String"
        required: false
      - key: "WebformPrefix"
        type: "java.lang.String"
        required: true
      - key: "ConfigurationPrefix"
        type: "java.lang.String"
        required: true
  - id: "StartNode2"
    name: "GetStates"
    mode: "private"
    strict: true
    inputs:
      - key: "CountryCode"
        type: "java.lang.String"
        required: false
  - id: "StartNode23"
    name: "GetWebFormInfosForCountry"
    mode: "private"
    strict: true
    inputs:
      - key: "CountryCode"
        type: "java.lang.String"
        required: false
      - key: "AddressFormPrefix"
        type: "java.lang.String"
        required: true
      - key: "ConfigurationPrefix"
        type: "java.lang.String"
        required: true
  - id: "StartNode3"
    name: "CreateRegisterFullAddressForm"
    mode: "private"
    strict: true
    inputs:
      - key: "FormName"
        type: "java.lang.String"
        required: true
      - key: "FormAlias"
        type: "java.lang.String"
        required: false
      - key: "Dictionary"
        type: "com.intershop.beehive.core.capi.pipeline.PipelineDictionary"
        required: true
  - id: "StartNode4"
    name: "CreateAccountAddressForm"
    mode: "private"
    strict: true
    inputs:
      - key: "FormName"
        type: "java.lang.String"
        required: true
      - key: "FormAlias"
        type: "java.lang.String"
        required: false
      - key: "Dictionary"
        type: "com.intershop.beehive.core.capi.pipeline.PipelineDictionary"
        required: true
  - id: "StartNode5"
    name: "CreateAddressForm"
    mode: "private"
    strict: true
    inputs:
      - key: "FormName"
        type: "java.lang.String"
        required: true
      - key: "FormAlias"
        type: "java.lang.String"
        required: false
      - key: "Dictionary"
        type: "com.intershop.beehive.core.capi.pipeline.PipelineDictionary"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
    ref: "This:GetWebFormInfosForCountry"
    bindings:
      AddressFormPrefix: "WebformPrefix"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessWebforms-GetStates"
    bindings:
      CountryCode: "CountryCode"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessWebforms-CreateCountrySpecificForm"
    bindings:
      WebformPrefix: "\"Address\""
      ConfigurationPrefix: "\"WebFormSelectorSuffix\""
  - id: "CallNode3"
    type: "call"
    ref: "ProcessWebforms-CreateCountrySpecificForm"
    bindings:
      WebformPrefix: "\"RegistrationAddress\""
      ConfigurationPrefix: "\"WebFormSelectorSuffix\""
  - id: "CallNode4"
    type: "call"
    ref: "ProcessWebforms-CreateCountrySpecificForm"
    bindings:
      WebformPrefix: "\"AccountAddress\""
      ConfigurationPrefix: "\"WebFormSelectorSuffix\""
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString1: "."
    bindings:
      String0: "ConfigurationPrefix"
      String2: "CountryCode"
      Concatenated: "WebFormSelectorName"
  - id: "ConcatenateStrings2"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString2: "_CountryCode"
      DefaultString0: "Dictionary:"
    bindings:
      String1: "FormAlias"
      Concatenated: "CountryCodeName"
  - id: "ConcatenateStrings3"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String1: "WebFormSelectorSuffix"
      String0: "AddressFormPrefix"
      Concatenated: "WebFormFileName"
  - id: "ConcatenateStrings4"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString2: "_CountryCode"
      DefaultString0: "Dictionary:"
    bindings:
      String1: "FormAlias"
      Concatenated: "CountryCodeName"
  - id: "ConcatenateStrings5"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString2: "_CountryCode"
      DefaultString0: "Dictionary:"
    bindings:
      String1: "FormAlias"
      Concatenated: "CountryCodeName"
  - id: "CreateForm2"
    type: "pipelet"
    ref: "CreateForm"
    bindings:
      FormResource: "WebFormFileName"
  - id: "DecisionNode1"
    type: "decision"
    condition: "CountryCode"
  - id: "DecisionNode16"
    type: "decision"
    condition: "StatesProvinces"
  - id: "DecisionNode17"
    type: "decision"
    condition: "CountryCode"
  - id: "DecisionNode2"
    type: "decision"
    condition: "CountryCode"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Dictionary:Address"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Dictionary:Address"
  - id: "DecisionNode5"
    type: "decision"
    condition: "CountryCode"
  - id: "DecisionNode9"
    type: "decision"
    condition: "WebFormSelectorSuffix"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "Form"
        type: "com.intershop.beehive.core.capi.webform.Form"
        guaranteed: true
      - key: "WebFormFileName"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode13"
    type: "end"
    strict: true
    outputs:
      - key: "WebFormFileName"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode14"
    type: "end"
    strict: true
    outputs:
      - key: "Form"
        type: "com.intershop.beehive.core.capi.webform.Form"
        guaranteed: true
      - key: "ShippingCountries"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "WebFormFileName"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "StatesProvinces"
        type: "com.intershop.beehive.core.capi.paging.PageableIterator"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "Form"
        type: "com.intershop.beehive.core.capi.webform.Form"
        guaranteed: true
      - key: "ShippingCountries"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "WebFormFileName"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "Form"
        type: "com.intershop.beehive.core.capi.webform.Form"
        guaranteed: true
      - key: "ShippingCountries"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "WebFormFileName"
        type: "java.lang.String"
        guaranteed: true
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "geoobject/GetStateProvinceByCountryAndParameter"
      DefaultPageSize: 0
      Datasource: "current ORM connection"
    bindings:
      Parameters: "SearchParameters"
      SearchResult: "StatesProvinces"
  - id: "GetCountryByID1"
    type: "pipelet"
    ref: "GetCountryByID"
    bindings:
      ID: "CountryCode"
  - id: "GetCountryByID2"
    type: "pipelet"
    ref: "GetCountryByID"
    bindings:
      ID: "\"US\""
  - id: "GetIndirectDictValue1"
    type: "pipelet"
    ref: "GetIndirectDictValue"
    bindings:
      KeyNameHolder: "CountryCodeName"
      MappedEntry: "CountryCode"
  - id: "GetIndirectDictValue2"
    type: "pipelet"
    ref: "GetIndirectDictValue"
    bindings:
      KeyNameHolder: "CountryCodeName"
      MappedEntry: "CountryCode"
  - id: "GetIndirectDictValue3"
    type: "pipelet"
    ref: "GetIndirectDictValue"
    bindings:
      KeyNameHolder: "CountryCodeName"
      MappedEntry: "CountryCode"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
  - id: "GetShippingEngine0"
    type: "pipelet"
    ref: "GetShippingEngine"
  - id: "GetShippingEngine1"
    type: "pipelet"
    ref: "GetShippingEngine"
  - id: "GetShippingEngine2"
    type: "pipelet"
    ref: "GetShippingEngine"
  - id: "GetShippingEngine3"
    type: "pipelet"
    ref: "GetShippingEngine"
  - id: "GetSortedShippingDestinationCountries0"
    type: "pipelet"
    ref: "GetSortedShippingDestinationCountries"
    bindings:
      ShippingDestinationCountriesProvider: "ShippingEngine:ShippingDestinationCountriesProvider"
      Countries: "ShippingCountries"
  - id: "GetSortedShippingDestinationCountries1"
    type: "pipelet"
    ref: "GetSortedShippingDestinationCountries"
    bindings:
      ShippingDestinationCountriesProvider: "ShippingEngine:ShippingDestinationCountriesProvider"
      Countries: "ShippingCountries"
  - id: "GetSortedShippingDestinationCountries2"
    type: "pipelet"
    ref: "GetSortedShippingDestinationCountries"
    bindings:
      ShippingDestinationCountriesProvider: "ShippingEngine:ShippingDestinationCountriesProvider"
      Countries: "ShippingCountries"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Dictionary:Address:CountryCode"
      OutValue_1: "CountryCode"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ShippingEngine:RegionRepository"
      OutValue_1: "RegionRepository"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentDomain:Configuration:String(WebFormSelectorName)"
      OutValue_1: "WebFormSelectorSuffix"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Dictionary:Address:CountryCode"
      OutValue_1: "CountryCode"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "WebFormSelectorSuffix"
      Value: "DefaultNoState"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "WebFormSelectorSuffix"
      Value: "DefaultNoState"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue9"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "WebFormSelectorSuffix"
      Value: "Default"
      ValueType: "Dictionary Value"
  - id: "UpdateDictionary1"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "Domain"
      Name_02: "Locale"
      Name_03: "Country"
      Name_04: "ParameterName"
      Name_05: "ParameterValue"
    bindings:
      Value_01: "RegionRepository:GeoObjectsDomain"
      Value_03: "Country"
      Value_02: "Locale"
      Value_04: "\"displayName\""
      OutDictionary: "SearchParameters"

links:
  - from: "DecisionNode9"
    via: "yes"
    to: "CallNode11"
    into: "in"
  - from: "DecisionNode9"
    via: "no"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode11"
    via: "next"
    to: "DecisionNode16"
    into: "in"
  - from: "DecisionNode16"
    via: "yes"
    to: "SetDictionaryValue9"
    into: "in"
  - from: "DecisionNode16"
    via: "no"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode6"
    into: "in2"
  - from: "CallNode1"
    via: "next"
    to: "CreateForm2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "GetShippingEngine1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "GetShippingEngine0"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "GetShippingEngine3"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "ConcatenateStrings2"
    via: "next"
    to: "GetIndirectDictValue1"
    into: "in"
  - from: "ConcatenateStrings3"
    via: "next"
    to: "EndNode13"
    into: "in"
  - from: "ConcatenateStrings4"
    via: "next"
    to: "GetIndirectDictValue2"
    into: "in"
  - from: "ConcatenateStrings5"
    via: "next"
    to: "GetIndirectDictValue3"
    into: "in"
  - from: "CreateForm2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "DecisionNode17"
    via: "no"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "DecisionNode17"
    via: "yes"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "GetCountryByID2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetCountryByID1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode3"
    via: "yes"
    to: "KeyMapper1"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode4"
    via: "yes"
    to: "KeyMapper4"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode5"
    via: "yes"
    to: "DecisionNode4"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "GetCountryByID1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetCountryByID1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetCountryByID2"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetCountryByID2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetIndirectDictValue1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "GetIndirectDictValue2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "GetIndirectDictValue3"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "GetLocale2"
    via: "next"
    to: "UpdateDictionary1"
    into: "in"
  - from: "GetShippingEngine0"
    via: "next"
    to: "GetSortedShippingDestinationCountries2"
    into: "in"
  - from: "GetShippingEngine1"
    via: "next"
    to: "GetSortedShippingDestinationCountries0"
    into: "in"
  - from: "GetShippingEngine2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "GetShippingEngine3"
    via: "next"
    to: "GetSortedShippingDestinationCountries1"
    into: "in"
  - from: "GetSortedShippingDestinationCountries0"
    via: "next"
    to: "EndNode14"
    into: "in"
  - from: "GetSortedShippingDestinationCountries1"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "GetSortedShippingDestinationCountries2"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "JoinNode11"
    via: "next"
    to: "ConcatenateStrings3"
    into: "in"
  - from: "JoinNode12"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "DecisionNode9"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "SetDictionaryValue9"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode23"
    via: "next"
    to: "DecisionNode17"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetShippingEngine2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "ConcatenateStrings4"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "ConcatenateStrings5"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "ConcatenateStrings2"
    into: "in"
  - from: "UpdateDictionary1"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
