flow: "ProcessOrganizationSearch_32"
kind: "process"

entries:
  - id: "StartNode1"
    name: "BySimpleSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "ByParametricSearch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Iterator: "TypeCodes"
      Object: "\"30\""
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Iterator: "TypeCodes"
      Object: "\"30\""
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      Datasource: "default"
      DefaultPageSize: 15
      QueryName: "organization/GetOrganizationsByOwningDomain"
      ParameterName_01: "OwningDomain"
      ParameterName_02: "SimpleSearchTermExp"
      ParameterName_03: "TypeCodes"
    bindings:
      ParameterValue_02: "SimpleSearchTermExp"
      ParameterValue_01: "CurrentChannel:RepositoryDomain"
      SearchResult: "FilteredOrganizations"
      ParameterValue_03: "TypeCodes"
  - id: "ExecutePageableQuery2"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      Datasource: "default"
      DefaultPageSize: 15
      QueryName: "organization/GetOrganizationsByOwningDomain"
    bindings:
      SearchResult: "FilteredOrganizations"
      Parameters: "OrganizationSearchParameters"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "UpdateDictionary2"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "OwningDomain"
      Name_02: "Locale"
      Name_03: "ID"
      Name_04: "Name"
      Name_05: "Description"
      Name_06: "TypeCodes"
    bindings:
      OutDictionary: "OrganizationSearchParameters"
      InDictionary: "null"
      Value_01: "CurrentChannel:RepositoryDomain"
      Value_02: "CurrentRequest:Locale"
      Value_03: "OrganizationIDExp"
      Value_04: "OrganizationDisplayNameExp"
      Value_05: "OrganizationDescriptionExp"
      Value_06: "TypeCodes"
  - id: "VerifySearchTerm1"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowFuzzySearch: false
      DefaultOperator: "AND"
    bindings:
      UserSearchTerm: "OrganizationDisplayName"
      SearchExpression: "OrganizationDisplayNameExp"
      ErrorCode: "OrganizationDisplayNameError"
  - id: "VerifySearchTerm2"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowFuzzySearch: false
      DefaultOperator: "OR"
    bindings:
      UserSearchTerm: "OrganizationID"
      SearchExpression: "OrganizationIDExp"
      ErrorCode: "OrganizationIDError"
  - id: "VerifySearchTerm3"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowFuzzySearch: true
    bindings:
      UserSearchTerm: "OrganizationDescription"
      SearchExpression: "OrganizationDescriptionExp"
      ErrorCode: "OrganizationDescriptionError"
  - id: "VerifySearchTerm6"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowFuzzySearch: true
      DefaultOperator: "AND"
      AllowWildcards: "default"
      AllowSubOperator: "default"
    bindings:
      UserSearchTerm: "SearchTerm"
      SearchExpression: "SimpleSearchTermExp"
      ErrorCode: "SimpleSearchTermError"

links:
  - from: "StartNode1"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "VerifySearchTerm3"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "VerifySearchTerm1"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "ExecutePageableQuery1"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "VerifySearchTerm6"
    into: "in"
  - from: "ExecutePageableQuery2"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "VerifySearchTerm2"
    via: "next"
    to: "VerifySearchTerm1"
    into: "in"
  - from: "VerifySearchTerm1"
    via: "next"
    to: "VerifySearchTerm3"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "VerifySearchTerm2"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "VerifySearchTerm6"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "VerifySearchTerm3"
    via: "next"
    to: "UpdateDictionary2"
    into: "in"
  - from: "UpdateDictionary2"
    via: "next"
    to: "ExecutePageableQuery2"
    into: "in"
  - from: "VerifySearchTerm6"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "VerifySearchTerm2"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "ExecutePageableQuery2"
    via: "error"
    to: "JoinNode1"
    into: "in1"
