flow: "ProcessPipelineInvocation"
kind: "process"

entries:
  - id: "StartNode15"
    name: "InvokeTargetPipeline"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode11"
    type: "call"
    ref: "Prefix-Start"
  - id: "CreateStringSplitter1"
    type: "pipelet"
    ref: "CreateStringSplitter"
    config:
      Separator: "-"
      Mode: "First Occurrence"
  - id: "FilterPipelineDictionary1"
    type: "pipelet"
    ref: "FilterPipelineDictionary"
    bindings:
      FilterSet: "FilterMap:KeySet"
  - id: "JumpNode6"
    type: "jump"
  - id: "KeyMapper7"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Splitter:Begin(ContextPipeline)"
      OutValue_1: "CurrentPipelineName"
      OutValue_2: "CurrentStartNodeName"
      InValue_2: "Splitter:End(ContextPipeline)"
  - id: "LoopNode2"
    type: "loop"
  - id: "SetIndirectDictValue1"
    type: "pipelet"
    ref: "SetIndirectDictValue"
    bindings:
      KeyNameHolder: "Key"
      MappedEntry: "ContextPipelineMap:get(Key)"
  - id: "UpdateDictionary1"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "ContextPipelineMap"
      Name_02: "ContextPipeline"
      Name_03: "DialogMode"
      Name_04: "PageLocatorName"
      Name_05: "CurrentApplication"
    bindings:
      OutDictionary: "FilterMap"
      Value_01: "\"\""
      Value_02: "\"\""
      Value_03: "\"\""
      Value_04: "\"\""
      Value_05: "\"\""

links:
  - from: "CreateStringSplitter1"
    via: "next"
    to: "KeyMapper7"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "JumpNode6"
    into: "in"
  - from: "SetIndirectDictValue1"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "LoopNode2"
    via: "next"
    to: "CreateStringSplitter1"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "SetIndirectDictValue1"
    into: "in"
  - from: "StartNode15"
    via: "next"
    to: "UpdateDictionary1"
    into: "in"
  - from: "KeyMapper7"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "UpdateDictionary1"
    via: "next"
    to: "FilterPipelineDictionary1"
    into: "in"
  - from: "FilterPipelineDictionary1"
    via: "next"
    to: "LoopNode2"
    into: "in"
