flow: "ProcessChannel"
kind: "process"

entries:
  - id: "Start1"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Error"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "DBInit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Get"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToString1"
    type: "pipelet"
    ref: "AddObjectToString"
    config:
      DefaultSeparator: "-"
    bindings:
      InObject: "Suffix"
      InString: "DomainName"
      OutString: "DomainName"
  - id: "AddObjectToString2"
    type: "pipelet"
    ref: "AddObjectToString"
    config:
      DefaultSeparator: "-"
    bindings:
      InObject: "RepositoryID"
      InString: "Organization:Domain:DomainName"
      OutString: "DomainName"
  - id: "Call1"
    type: "call"
    ref: "Organization-CreateSite"
  - id: "Call3"
    type: "call"
    ref: "ProcessChannel-Get"
  - id: "Call4"
    type: "call"
    ref: "ProcessRepository-Create"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessPageletEntryPointSynchronization-SynchronizeSite"
    bindings:
      Site: "Repository:Domain:Site"
  - id: "CallNode2"
    type: "call"
    bindings:
      Repository: "Repository"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessChannelApplication-Remove"
    bindings:
      Repository: "DeleteRepository"
  - id: "CreateDomainRelation1"
    type: "pipelet"
    ref: "CreateDomainRelation"
    config:
      DefaultRelationName: "SITE"
      DefaultRoleName: "Role A"
    bindings:
      Source: "Repository:Domain"
      Target: "SiteDomain"
  - id: "DecisionNode1"
    type: "decision"
    condition: "RepositoryID"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End12"
    type: "end"
    strict: false
  - id: "End6"
    type: "end"
    strict: false
  - id: "End7"
    type: "end"
    strict: false
  - id: "End9"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "ExecuteCartridgePipelines1"
    type: "pipelet"
    ref: "ExecuteCartridgePipelines"
    config:
      Asynchronous: false
      PipelinePropertyName: "ChannelDeletionHook"
      ProcessReversely: true
  - id: "GetApplications1"
    type: "pipelet"
    ref: "GetApplications"
    bindings:
      Domain: "DeleteRepository:Domain"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "String"
    bindings:
      PreferenceDomain: "OrganizationDomain"
      PreferenceKey: "\"ContentSharingChannel\""
      PreferenceStringValue: "RepositoryID"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
  - id: "GetOrganizationByName1"
    type: "pipelet"
    ref: "GetOrganizationByName"
    bindings:
      Name: "OrganizationName"
  - id: "GetRecycleBinByRepository1"
    type: "pipelet"
    ref: "GetRecycleBinByRepository"
    bindings:
      RecycleBin: "DeleteRecycleBin"
      Repository: "DeleteRepository"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      UUID: "RepositoryUUID"
  - id: "GetRepositoryByUUID2"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "DeleteRepository"
      UUID: "RepositoryUUID"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ProcessChannel-Error"
  - id: "Jump4"
    type: "jump"
    ref: "ProcessChannel-Error"
  - id: "Jump5"
    type: "jump"
    ref: "ProcessChannel-Error"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "SiteDomain"
      OutValue_1: "Site"
  - id: "LoopNode1"
    type: "loop"
  - id: "RemoveApplicationWithoutDefaultSiteCheck1"
    type: "pipelet"
    ref: "RemoveApplicationWithoutDefaultSiteCheck"
  - id: "RemoveDomainPreference1"
    type: "pipelet"
    ref: "RemoveDomainPreference"
    bindings:
      PreferenceDomain: "OrganizationDomain"
      PreferenceKey: "\"ContentSharingChannel\""
  - id: "RemoveRepository1"
    type: "pipelet"
    ref: "RemoveRepository"
    bindings:
      Repository: "DeleteRepository"
      RepositoryDomain: "DeleteRepositoryDomain"
  - id: "RemoveRepository2"
    type: "pipelet"
    ref: "RemoveRepository"
    bindings:
      Repository: "DeleteRecycleBin"
      RepositoryDomain: "null"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_Channel"
      Value: "CouldNotGetRepository"
  - id: "SetDictionaryValue10"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_Channel"
      Value: "CouldNotUpdateRepository"
  - id: "SetDictionaryValue5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ParentDomainName"
      Value: "root"
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Suffix"
      Value: "Site"
      ValueType: "Dictionary Value"
  - id: "SetDomainStatus1"
    type: "pipelet"
    ref: "SetDomainStatus"
    config:
      DefaultStatus: "ToBeDeleted"
    bindings:
      Domain: "DeleteRepositoryDomain:Site"
  - id: "TextNode1"
    type: "text"
  - id: "UpdateRepository1"
    type: "pipelet"
    ref: "UpdateRepository"
  - id: "UpdateRepository2"
    type: "pipelet"
    ref: "UpdateRepository"

links:
  - from: "Start1"
    via: "next"
    to: "Join8"
    into: "in3"
  - from: "GetRepositoryByUUID2"
    via: "next"
    to: "ExecuteCartridgePipelines1"
    into: "in"
  - from: "Join9"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Start7"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "AddObjectToString2"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "GetDomainPreference1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "GetApplications1"
    into: "in"
  - from: "RemoveRepository2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Start4"
    via: "next"
    to: "GetRepositoryByUUID2"
    into: "in"
  - from: "UpdateRepository2"
    via: "next"
    to: "End12"
    into: "in"
  - from: "ExecuteCartridgePipelines1"
    via: "next"
    to: "GetRecycleBinByRepository1"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "CreateDomainRelation1"
    into: "in"
  - from: "CreateDomainRelation1"
    via: "next"
    to: "UpdateRepository1"
    into: "in"
  - from: "GetRepositoryByUUID2"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "Call1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "End1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "AddObjectToString1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "ExecuteCartridgePipelines1"
    via: "error"
    to: "Join5"
    into: "in2"
  - from: "Call1"
    via: "ERROR"
    to: "Join4"
    into: "in1"
  - from: "SetDictionaryValue10"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "Start5"
    via: "next"
    to: "GetOrganizationByName1"
    into: "in"
  - from: "UpdateRepository2"
    via: "error"
    to: "SetDictionaryValue10"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "End9"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "SetDictionaryValue5"
    into: "in"
  - from: "UpdateRepository1"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "GetLocale2"
    via: "next"
    to: "UpdateRepository2"
    into: "in"
  - from: "AddObjectToString2"
    via: "next"
    to: "AddObjectToString1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetOrganizationByName1"
    via: "next"
    to: "Join8"
    into: "in2"
  - from: "CreateDomainRelation1"
    via: "error"
    to: "Join9"
    into: "in2"
  - from: "GetRecycleBinByRepository1"
    via: "next"
    to: "RemoveRepository2"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Call4"
    via: "ERROR"
    to: "Join4"
    into: "in2"
  - from: "GetRecycleBinByRepository1"
    via: "error"
    to: "JoinNode1"
    into: "in3"
  - from: "Join5"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "RemoveDomainPreference1"
    into: "in"
  - from: "RemoveDomainPreference1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "Call3"
    via: "ERROR"
    to: "Join2"
    into: "in1"
  - from: "RemoveRepository1"
    via: "next"
    to: "SetDomainStatus1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "End6"
    into: "in"
  - from: "UpdateRepository1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "SetDomainStatus1"
    via: "next"
    to: "End7"
    into: "in"
  - from: "GetApplications1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "RemoveApplicationWithoutDefaultSiteCheck1"
    into: "in"
  - from: "RemoveApplicationWithoutDefaultSiteCheck1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "LoopNode1"
    via: "next"
    to: "RemoveRepository1"
    into: "in"
  - from: "SetDictionaryValue5"
    via: "next"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "GetRepositoryByUUID1"
    into: "in"
