flow: "ProcessInitializeDefaultAddress"
kind: "process"

entries:
  - id: "StartNode1"
    name: "MakeContactAddress"
    mode: "private"
    strict: false
    inputs:
      - key: "AddressProfile<com.intershop.beehive.core.capi.profile.Profile>"
        type: "com.intershop.beehive.core.capi.profile.Profile"
        required: false

steps:
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Lead Locale"
    bindings:
      LocaleId: "null"
      Locale: "LeadLocale"
  - id: "GetLocalizedResources1"
    type: "pipelet"
    ref: "GetLocalizedResources"
    bindings:
      Locale: "LeadLocale"
      Resources: "AddressNames"
      ResourceBundleName: "\"resources.address.DefaultAddress\""
  - id: "UpdateAddress1"
    type: "pipelet"
    ref: "UpdateAddress"
    bindings:
      AddressName: "AddressNames:ContactAddressName"
      Address: "AddressProfile:DefaultAddress"
      AddressNr: "null"
      City: "null"
      Company: "null"
      CompanyTranscription: "null"
      ConfirmFax: "null"
      ConfirmMail: "null"
      Country: "null"
      CountryCode: "null"
      County: "null"
      Email: "null"
      Fax: "null"
      FirstName: "null"
      FirstNameTranscription: "null"
      Homepage: "null"
      Honorific: "null"
      JobTitle: "null"
      LastName: "null"
      LastNameTranscription: "null"
      Mobile: "null"
      PhoneBusiness: "null"
      PhoneBusinessDirect: "null"
      PhoneHome: "null"
      PostBox: "null"
      PostalCode: "null"
      Prefecture: "null"
      Profile: "AddressProfile"
      Province: "null"
      Region: "null"
      SecondLastName: "null"
      SecondName: "null"
      State: "null"
      StreetTranscription: "null"
      Street: "null"
      Street2: "null"
      Suffix: "null"
      Title: "null"
      UseForInvoiceTo: "null"
      UseForShipTo: "null"

links:
  - from: "StartNode1"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "GetLocalizedResources1"
    via: "next"
    to: "UpdateAddress1"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "GetLocalizedResources1"
    into: "in"
  - from: "UpdateAddress1"
    via: "next"
    to: "EndNode1"
    into: "in"
