flow: "ProcessRelatedCatalogs"
kind: "process"

entries:
  - id: "Start1"
    name: "GetRelatedClassificationCatalogs"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "GetRelatedStandardCatalogs"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      InVector: "FilteredStandardCatalogs"
      Iterator: "StandardCatalogs"
      Object: "StandardCatalog"
      OutVector: "FilteredStandardCatalogs"
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      InVector: "FilteredClassificationCatalogs"
      Iterator: "ClassificationCatalogs"
      Object: "ClassificationCatalog"
      OutVector: "FilteredClassificationCatalogs"
  - id: "CheckUserPermission1"
    type: "pipelet"
    ref: "CheckUserPermission"
    config:
      DefaultPermissionID: "SLD_VIEW_CATALOG"
    bindings:
      AuthorizationObject: "StandardCatalog:Domain"
  - id: "CheckUserPermission2"
    type: "pipelet"
    ref: "CheckUserPermission"
    config:
      DefaultPermissionID: "SLD_VIEW_CATALOG"
    bindings:
      AuthorizationObject: "ClassificationCatalog:Domain"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "GetCatalogs1"
    type: "pipelet"
    ref: "GetCatalogs"
    config:
      CatalogType: "Product Catalog"
    bindings:
      Catalogs: "ReleatedStandardCatalogs"
  - id: "GetCatalogs2"
    type: "pipelet"
    ref: "GetCatalogs"
    config:
      CatalogType: "Classification Catalog"
    bindings:
      Catalogs: "ReleatedClassificationCatalogs"
  - id: "GetPermissionsByUser1"
    type: "pipelet"
    ref: "GetPermissionsByUser"
    bindings:
      AuthorizationObject: "StandardCatalog:Domain"
      User: "CurrentUser"
  - id: "GetPermissionsByUser2"
    type: "pipelet"
    ref: "GetPermissionsByUser"
    bindings:
      AuthorizationObject: "ClassificationCatalog:Domain"
      User: "CurrentUser"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Loop1"
    type: "loop"
  - id: "Loop2"
    type: "loop"

links:
  - from: "GetCatalogs1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Loop2"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "CheckUserPermission2"
    via: "error"
    to: "Join2"
    into: "in3"
  - from: "CheckUserPermission2"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Loop2"
    via: "do"
    to: "GetPermissionsByUser2"
    into: "in"
  - from: "GetPermissionsByUser2"
    via: "next"
    to: "CheckUserPermission2"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "GetCatalogs2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "GetCatalogs1"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "CheckUserPermission1"
    via: "error"
    to: "Join1"
    into: "in3"
  - from: "CheckUserPermission1"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Loop1"
    via: "do"
    to: "GetPermissionsByUser1"
    into: "in"
  - from: "GetPermissionsByUser1"
    via: "next"
    to: "CheckUserPermission1"
    into: "in"
  - from: "GetCatalogs2"
    via: "next"
    to: "Loop2"
    into: "in"
