flow: "ProcessReplicationPageCache"
kind: "process"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "GetAllSites"
    mode: "private"
    strict: true
    inputs:
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true
  - id: "StartNode2"
    name: "GetOrganizationSites"
    mode: "private"
    strict: true
    inputs:
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "null"
      Iterator: "null"
      Object: "Organization:OrganizationDomain:Site:DomainName"
      Objects: "null"
      OutVector: "SiteNames"
  - id: "AddObjectToVector6"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "SiteNames"
      Iterator: "null"
      Object: "null"
      Objects: "ChannelSiteNames"
      OutVector: "SiteNames"
  - id: "CallNode1"
    type: "call"
    ref: "This:GetAllSites"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessChannelList-ListAll"
  - id: "CallNode3"
    type: "call"
    bindings:
      SiteNames: "ChannelSiteNames"
  - id: "CallNode4"
    type: "call"
    ref: "This:GetOrganizationSites"
  - id: "ConcatenateStrings3"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "\"ProcessReplicationPageCache_\""
      String1: "Channel:TypeCode"
      String2: "\"-GetAllSites\""
      Concatenated: "ChannelSitesPipeline"
  - id: "CreateIteratorFromPageable1"
    type: "pipelet"
    ref: "CreateIteratorFromPageable"
    bindings:
      PageableIterator: "Repositories"
      ResettableIterator: "Channels"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "SiteNames"
        type: "java.util.Collection"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "SiteNames"
        type: "java.util.Collection"
        guaranteed: true
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Organization"
      OutValue_1: "CurrentOrganization"
  - id: "Loop1"
    type: "loop"
  - id: "UpdateCustomAttribute1"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    config:
      DefaultAttributeName: "PageCacheSiteNames"
      DefaultAttributeType: "MultipleString"
    bindings:
      AttributeName: "null"
      AttributeType: "null"
      AttributeValue: "SiteNames:Iterator"
      ExtensibleObject: "ReplicationTask"
      LocaleInformation: "null"

links:
  - from: "Start1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "UpdateCustomAttribute1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "AddObjectToVector6"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "ConcatenateStrings3"
    into: "in"
  - from: "ConcatenateStrings3"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CreateIteratorFromPageable1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CreateIteratorFromPageable1"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "AddObjectToVector6"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "CallNode1"
    via: "next"
    to: "UpdateCustomAttribute1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
