flow: "ProcessApproval"
kind: "process"

entries:
  - id: "Start1"
    name: "StartApproval"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "PreviewApproval"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Submit"
    mode: "private"
    strict: false
    inputs:
      - key: "Requisition"
        type: "com.intershop.beehive.bts.capi.orderprocess.basket.Basket"
        required: false
  - id: "Start4"
    name: "CheckCompletion"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "Recalculate"
    mode: "private"
    strict: false
    inputs:
      - key: "WorkflowActivity"
        type: "com.intershop.beehive.core.capi.workflow.WorkflowActivity"
        required: false

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessApproval-StartApproval"
  - id: "Call2"
    type: "call"
    ref: "ProcessApprovalCustomized-CreateApprovalObject"
  - id: "Call3"
    type: "call"
    ref: "ProcessApprovalCustomized-CreateApprovalObject"
  - id: "Call4"
    type: "call"
    ref: "ProcessApproval-CheckCompletion"
  - id: "Call5"
    type: "call"
    ref: "ProcessApprovalCustomized-MakeStaticAddresses"
  - id: "Call6"
    type: "call"
    ref: "ProcessApprovalCustomized-AWFCompletion"
  - id: "Call7"
    type: "call"
    ref: "ProcessApprovalCustomized-PreProcessStartApproval"
  - id: "Call8"
    type: "call"
    ref: "ProcessApproval-CheckCompletion"
  - id: "CreateApprovalPreviews1"
    type: "pipelet"
    ref: "CreateApprovalPreviews"
    bindings:
      CompoundObject: "ApprovalCompound"
      CurrentUser: "CurrentDelegator"
  - id: "Decision1"
    type: "decision"
    condition: "WorkflowActivity:State"
  - id: "DetermineUserProfile1"
    type: "pipelet"
    ref: "DetermineUserProfile"
  - id: "DetermineUserProfile2"
    type: "pipelet"
    ref: "DetermineUserProfile"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "End6"
    type: "end"
    strict: false
  - id: "GetBasket1"
    type: "pipelet"
    ref: "GetBasket"
    config:
      BasketType: "REQUISITION"
    bindings:
      Basket: "Requisition"
      CurrentDomain: "Profile:Domain"
  - id: "Join1"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "RecalculateNextApprovalStep1"
    type: "pipelet"
    ref: "RecalculateNextApprovalStep"
    bindings:
      CurrentActivity: "WorkflowActivity"
  - id: "RemoveRequisitionFromSession1"
    type: "pipelet"
    ref: "RemoveRequisitionFromSession"
    bindings:
      Requisition: "Requisition"
  - id: "StartApproval1"
    type: "pipelet"
    ref: "StartApproval"
    config:
      Type: 2
    bindings:
      ApprovalActivity: "WorkflowActivity"
      CompoundObject: "ApprovalCompound"
      CurrentUser: "Requisition:User"
      WorkflowUnit: "Requisition:Domain"
  - id: "Text1"
    type: "text"
  - id: "UpdateCustomAttributes1"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "ApprovalWorkflowActivityUUID"
      Attribute_1_Type: "String"
    bindings:
      Attribute_1_Value: "WorkflowActivity:UUID"
      ExtensibleObject: "Requisition"
  - id: "UpdateLineItemStatus1"
    type: "pipelet"
    ref: "UpdateLineItemStatus"
    config:
      StatusGroup: "Approval"
      StatusID: 2
  - id: "UpdateRequisitionStatus1"
    type: "pipelet"
    ref: "UpdateRequisitionStatus"
    config:
      StatusID: 11
    bindings:
      InputStatusID: "StatusID"

links:
  - from: "Start1"
    via: "next"
    to: "DetermineUserProfile1"
    into: "in"
  - from: "DetermineUserProfile2"
    via: "next"
    to: "GetBasket1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "DetermineUserProfile2"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "RecalculateNextApprovalStep1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "UpdateLineItemStatus1"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Decision1"
    via: "yes"
    to: "Call6"
    into: "in"
  - from: "StartApproval1"
    via: "next"
    to: "UpdateCustomAttributes1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join1"
    into: "in3"
  - from: "Start4"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "End4"
    into: "in"
  - from: "RecalculateNextApprovalStep1"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "End6"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Call3"
    via: "next"
    to: "CreateApprovalPreviews1"
    into: "in"
  - from: "CreateApprovalPreviews1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "StartApproval1"
    into: "in"
  - from: "UpdateRequisitionStatus1"
    via: "next"
    to: "UpdateLineItemStatus1"
    into: "in"
  - from: "RemoveRequisitionFromSession1"
    via: "next"
    to: "End3"
    into: "in"
  - from: "DetermineUserProfile1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "UpdateRequisitionStatus1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "RemoveRequisitionFromSession1"
    into: "in"
  - from: "UpdateCustomAttributes1"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "GetBasket1"
    via: "next"
    to: "Call3"
    into: "in"
