flow: "ProcessWishlist"
kind: "process"

entries:
  - id: "Start1"
    name: "SendInvitationMail"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode12"
    name: "GetProductsToAdd"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode16"
    name: "ProcessAddProducts"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductUUIDs"
        type: "java.util.Iterator"
        required: false
      - key: "SKUs"
        type: "java.util.Iterator"
        required: false
      - key: "Quantities"
        type: "java.util.Map"
        required: true
      - key: "ProductRefIDs"
        type: "java.util.Iterator"
        required: false
      - key: "DependentSKUMap"
        type: "java.util.Map"
        required: false
      - key: "WishlistBO"
        type: "com.intershop.component.wishlist.capi.WishlistBO"
        required: true
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "ProductBORepository"
        type: "com.intershop.component.product.capi.ProductBORepository"
        required: true
  - id: "StartNode4"
    name: "AddWishlistItem"
    mode: "private"
    strict: true
    inputs:
      - key: "WishlistBO"
        type: "com.intershop.component.wishlist.capi.WishlistBO"
        required: true
      - key: "ProductBO"
        type: "com.intershop.component.product.capi.ProductBO"
        required: true
      - key: "QuantityValue"
        type: "java.lang.String"
        required: false
  - id: "StartNode5"
    name: "PrepareLoginParameters"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductUUIDs"
        type: "java.util.Iterator"
        required: false
      - key: "SKUs"
        type: "java.util.Iterator"
        required: false
      - key: "Quantities"
        type: "java.util.Map"
        required: true
      - key: "ProductRefIDs"
        type: "java.util.Iterator"
        required: false
  - id: "StartNode7"
    name: "MoveAllWishlistItems"
    mode: "private"
    strict: true
    inputs:
      - key: "SourceWishlistBO"
        type: "com.intershop.component.wishlist.capi.WishlistBO"
        required: true
      - key: "TargetWishlistBO"
        type: "com.intershop.component.wishlist.capi.WishlistBO"
        required: true

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Object: "Quantity"
      InVector: "QuantitiesVector"
      OutVector: "QuantitiesVector"
  - id: "AddProductToWishlistBO2"
    type: "pipelet"
    ref: "AddProductToWishlistBO"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessUser-IsProductVisibleToCurrentUser"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessUser-IsProductVisibleToCurrentUser"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessUser-IsProductVisibleToCurrentUser"
  - id: "CallNode4"
    type: "call"
    ref: "This:AddWishlistItem"
  - id: "CallNode5"
    type: "call"
    ref: "This:AddWishlistItem"
    bindings:
      QuantityValue: "Quantities:get(SKU)"
  - id: "CallNode6"
    type: "call"
    ref: "This:AddWishlistItem"
  - id: "CreateIteratorFromConfigValues2"
    type: "pipelet"
    ref: "CreateIteratorFromConfigValues"
    config:
      Delimiters: ";"
    bindings:
      ValuesString: "MailTo"
      ValuesIterator: "UserEmailIterator"
  - id: "CreateQuantity1"
    type: "pipelet"
    ref: "CreateQuantity"
    config:
      DefaultValue: 1
    bindings:
      Value: "QuantityValue"
      Unit: "\"\""
  - id: "DecisionNode15"
    type: "decision"
    condition: "SKUs"
  - id: "DecisionNode16"
    type: "decision"
    condition: "ProductUUIDs"
  - id: "DecisionNode4"
    type: "decision"
    condition: "ProductRefIDs"
  - id: "DecisionNode5"
    type: "decision"
    condition: "SKUs"
  - id: "DecisionNode6"
    type: "decision"
    condition: "ProductRefIDs"
  - id: "DecisionNode7"
    type: "decision"
    condition: "ProductUUIDs"
  - id: "End2"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode26"
    type: "end"
    strict: true
    outputs:
      - key: "ProductUUIDs"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "SKUs"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "Quantities"
        type: "java.util.Map"
        guaranteed: true
      - key: "ProductRefIDs"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "DependentSKUMap"
        type: "java.util.Map"
        guaranteed: false
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode32"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "CSProducts"
        type: "java.lang.String"
        guaranteed: true
      - key: "CSQuantities"
        type: "java.lang.String"
        guaranteed: true
      - key: "ProductKeyName"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode8"
    type: "end"
    strict: true
  - id: "GetDomainPreference4"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "WishlistEmailTemplate"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceStringValue: "MailTemplate"
  - id: "GetDomainPreference5"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "WishlistEmailSubject"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceStringValue: "MailSubject"
  - id: "GetEntryFromMap1"
    type: "pipelet"
    ref: "GetEntryFromMap"
    bindings:
      InMap: "Quantities"
      Key: "Product"
      Value: "Quantity"
  - id: "GetFormRecord1"
    type: "pipelet"
    ref: "GetFormRecord"
    config:
      DefaultRecordID: "Quantity"
    bindings:
      AllFormValues: "null"
      RecordID: "null"
      FormRecord: "Quantities"
  - id: "GetFormRecord3"
    type: "pipelet"
    ref: "GetFormRecord"
    config:
      DefaultRecordID: "DependentSKU"
    bindings:
      AllFormValues: "null"
      RecordID: "null"
      FormRecord: "DependentSKUMap"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SKU"
    bindings:
      ParameterName: "null"
      Selection: "SKUs"
  - id: "GetFormSelection2"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "ProductUUID"
    bindings:
      ParameterName: "null"
      Selection: "ProductUUIDs"
  - id: "GetFormSelection3"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "ProductRefID"
    bindings:
      ParameterName: "null"
      Selection: "ProductRefIDs"
  - id: "GetIndirectDictValue1"
    type: "pipelet"
    ref: "GetIndirectDictValue"
    bindings:
      KeyNameHolder: "ProductKeyName"
      MappedEntry: "ProductIterator"
  - id: "GetOrganizationByDomain1"
    type: "pipelet"
    ref: "GetOrganizationByDomain"
    bindings:
      OrganizationDomain: "ChannelRepository:OwningDomain"
      Organization: "EnterpriseOrganization"
  - id: "GetProductBOByID1"
    type: "pipelet"
    ref: "GetProductBOByID"
    bindings:
      ID: "Product:UUID"
  - id: "GetProductBOByID3"
    type: "pipelet"
    ref: "GetProductBOByID"
    bindings:
      ID: "ProductUUID"
  - id: "GetProductBOBySKU2"
    type: "pipelet"
    ref: "GetProductBOBySKU"
  - id: "GetProductByProductRef2"
    type: "pipelet"
    ref: "GetProductByProductRef"
  - id: "GetRepositoryByRepositoryDomain1"
    type: "pipelet"
    ref: "GetRepositoryByRepositoryDomain"
    bindings:
      RepositoryDomain: "CurrentOrganization:OwningDomain"
      Repository: "ChannelRepository"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode32"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "JoinString1"
    type: "pipelet"
    ref: "JoinString"
    config:
      SeparatorChar: ","
    bindings:
      StringIterator: "ProductUUIDs"
      JoinedString: "CSProducts"
  - id: "JoinString2"
    type: "pipelet"
    ref: "JoinString"
    config:
      SeparatorChar: ","
    bindings:
      StringIterator: "SKUs"
      JoinedString: "CSProducts"
  - id: "JoinString3"
    type: "pipelet"
    ref: "JoinString"
    config:
      SeparatorChar: ","
    bindings:
      StringIterator: "ProductRefIDs"
      JoinedString: "CSProducts"
  - id: "JoinString4"
    type: "pipelet"
    ref: "JoinString"
    config:
      SeparatorChar: ","
    bindings:
      StringCollection: "QuantitiesVector"
      JoinedString: "CSQuantities"
  - id: "Loop4"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "LoopNode3"
    type: "loop"
  - id: "LoopNode5"
    type: "loop"
  - id: "LoopNode8"
    type: "loop"
  - id: "LoopNode9"
    type: "loop"
  - id: "MoveWishlistItemBO1"
    type: "pipelet"
    ref: "MoveWishlistItemBO"
    bindings:
      Quantity: "WishlistItemBO:DesiredQuantity"
      SourceWishlistItemBO: "WishlistItemBO"
  - id: "ProcessMail1"
    type: "pipelet"
    ref: "ProcessMail"
    config:
      UseErrorConnector: true
      WaitForResult: true
    bindings:
      MailTo: "UserEmail"
      Domain: "CurrentOrganization:OwningDomain"
  - id: "RemoveDuplicates1"
    type: "pipelet"
    ref: "RemoveDuplicates"
    bindings:
      InputIterator: "SKUs"
      OutputIterator: "SKUs"
  - id: "RemoveDuplicates2"
    type: "pipelet"
    ref: "RemoveDuplicates"
    bindings:
      InputIterator: "ProductUUIDs"
      OutputIterator: "ProductUUIDs"
  - id: "RemoveDuplicates3"
    type: "pipelet"
    ref: "RemoveDuplicates"
    bindings:
      InputIterator: "ProductRefIDs"
      OutputIterator: "ProductRefIDs"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ProductKeyName"
      Value: "ProductUUIDs"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ProductKeyName"
      Value: "SKUs"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ProductKeyName"
      Value: "ProductRefIDs"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "EmailSendError"
      Value: "\"true\""

links:
  - from: "AddObjectToVector1"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "AddProductToWishlistBO2"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "CallNode1"
    via: "NOT_VISIBLE"
    to: "JoinNode9"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode2"
    via: "NOT_VISIBLE"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode3"
    via: "NOT_VISIBLE"
    to: "JoinNode12"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "LoopNode9"
    into: "loop"
  - from: "CallNode5"
    via: "next"
    to: "LoopNode8"
    into: "loop"
  - from: "CallNode6"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "CreateIteratorFromConfigValues2"
    via: "next"
    to: "GetRepositoryByRepositoryDomain1"
    into: "in"
  - from: "CreateQuantity1"
    via: "next"
    to: "AddProductToWishlistBO2"
    into: "in"
  - from: "DecisionNode15"
    via: "no"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode15"
    via: "yes"
    to: "LoopNode8"
    into: "in"
  - from: "DecisionNode16"
    via: "no"
    to: "DecisionNode15"
    into: "in"
  - from: "DecisionNode16"
    via: "yes"
    to: "LoopNode9"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode4"
    via: "yes"
    to: "LoopNode2"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "DecisionNode6"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode13"
    into: "in1"
  - from: "DecisionNode6"
    via: "yes"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "GetDomainPreference4"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "GetDomainPreference4"
    via: "next"
    to: "Loop4"
    into: "in"
  - from: "GetDomainPreference5"
    via: "next"
    to: "GetDomainPreference4"
    into: "in"
  - from: "GetEntryFromMap1"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "GetFormRecord1"
    via: "next"
    to: "GetFormRecord3"
    into: "in"
  - from: "GetFormRecord3"
    via: "next"
    to: "EndNode26"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "RemoveDuplicates1"
    into: "in"
  - from: "GetFormSelection2"
    via: "next"
    to: "RemoveDuplicates2"
    into: "in"
  - from: "GetFormSelection3"
    via: "next"
    to: "RemoveDuplicates3"
    into: "in"
  - from: "GetIndirectDictValue1"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "GetOrganizationByDomain1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetOrganizationByDomain1"
    via: "next"
    to: "GetDomainPreference5"
    into: "in"
  - from: "GetProductBOByID1"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "GetProductBOByID1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "GetProductBOByID3"
    via: "error"
    to: "JoinNode12"
    into: "in1"
  - from: "GetProductBOByID3"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "GetProductBOBySKU2"
    via: "error"
    to: "JoinNode9"
    into: "in1"
  - from: "GetProductBOBySKU2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetProductByProductRef2"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "GetProductByProductRef2"
    via: "next"
    to: "GetProductBOByID1"
    into: "in"
  - from: "GetRepositoryByRepositoryDomain1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetRepositoryByRepositoryDomain1"
    via: "next"
    to: "GetOrganizationByDomain1"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "GetIndirectDictValue1"
    into: "in"
  - from: "JoinNode12"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode13"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "End2"
    into: "in"
  - from: "JoinNode32"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "Loop4"
    into: "loop"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "EndNode32"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "JoinString1"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinString2"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinString3"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinString4"
    via: "next"
    to: "JoinNode13"
    into: "in1"
  - from: "Loop4"
    via: "do"
    to: "ProcessMail1"
    into: "in"
  - from: "Loop4"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "LoopNode2"
    via: "do"
    to: "GetProductByProductRef2"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "JoinNode32"
    into: "in1"
  - from: "LoopNode3"
    via: "do"
    to: "GetEntryFromMap1"
    into: "in"
  - from: "LoopNode3"
    via: "next"
    to: "JoinString4"
    into: "in"
  - from: "LoopNode5"
    via: "do"
    to: "MoveWishlistItemBO1"
    into: "in"
  - from: "LoopNode5"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "LoopNode8"
    via: "do"
    to: "GetProductBOBySKU2"
    into: "in"
  - from: "LoopNode8"
    via: "next"
    to: "JoinNode32"
    into: "in1"
  - from: "LoopNode9"
    via: "do"
    to: "GetProductBOByID3"
    into: "in"
  - from: "LoopNode9"
    via: "next"
    to: "JoinNode32"
    into: "in1"
  - from: "MoveWishlistItemBO1"
    via: "next"
    to: "LoopNode5"
    into: "loop"
  - from: "ProcessMail1"
    via: "error"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "ProcessMail1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "RemoveDuplicates1"
    via: "next"
    to: "GetFormSelection2"
    into: "in"
  - from: "RemoveDuplicates2"
    via: "next"
    to: "GetFormSelection3"
    into: "in"
  - from: "RemoveDuplicates3"
    via: "next"
    to: "GetFormRecord1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinString1"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinString2"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinString3"
    into: "in"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "CreateIteratorFromConfigValues2"
    into: "in"
  - from: "StartNode12"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "StartNode16"
    via: "next"
    to: "DecisionNode16"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CreateQuantity1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "DecisionNode7"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "LoopNode5"
    into: "in"
