flow: "ProcessPromotionBudget"
kind: "process"

entries:
  - id: "StartNode1"
    name: "OnCreateOrder"
    mode: "private"
    strict: true
    inputs:
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true
      - key: "ApplicationBO"
        type: "com.intershop.component.application.capi.ApplicationBO"
        required: true
      - key: "OrderBO"
        type: "com.intershop.component.order.capi.OrderBO"
        required: true
  - id: "StartNode2"
    name: "CreateAccountTransaction"
    mode: "private"
    strict: true
    inputs:
      - key: "OrderBO"
        type: "com.intershop.component.order.capi.OrderBO"
        required: true
      - key: "AppliedRebateBO"
        type: "com.intershop.component.promotion.capi.AppliedRebateBO"
        required: true
      - key: "TransactionMode"
        type: "java.lang.String"
        required: false
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode3"
    name: "OnCancelOrder"
    mode: "private"
    strict: true
    inputs:
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true
      - key: "ApplicationBO"
        type: "com.intershop.component.application.capi.ApplicationBO"
        required: true
      - key: "OrderBO"
        type: "com.intershop.component.order.capi.OrderBO"
        required: true
  - id: "StartNode4"
    name: "SendBudgetNotificationMail"
    mode: "private"
    strict: true
    inputs:
      - key: "AppliedRebateBO"
        type: "com.intershop.component.promotion.capi.AppliedRebateBO"
        required: true
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true
      - key: "OrderBO"
        type: "com.intershop.component.order.capi.OrderBO"
        required: true
      - key: "ApplicationBO"
        type: "com.intershop.component.application.capi.ApplicationBO"
        required: true

steps:
  - id: "AddMultipleEntriesToMap2"
    type: "pipelet"
    ref: "AddMultipleEntriesToMap"
    config:
      Mode: "OverwriteValue"
    bindings:
      Key1: "\"{{PROMOTION}}\""
      Key2: "\"{{BUDGET}}\""
      Key3: "\"{{THRESHOLD}}\""
      Value1: "AppliedRebateBO:Rebate:Promotion:DisplayName"
      Value2: "AppliedRebateBO:Rebate:Promotion:BudgetAmount"
      Value3: "AppliedRebateBO:Rebate:Promotion:BudgetNotificationThreshold"
      OutMap: "Placeholders"
  - id: "CallNode3"
    type: "call"
    ref: "This:CreateAccountTransaction"
    bindings:
      Domain: "Organization:OwningDomain"
      AppliedRebateBO: "AppliedRebateBO"
  - id: "CallNode4"
    type: "call"
    ref: "This:SendBudgetNotificationMail"
  - id: "CheckForEmptyString1"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "MailTemplate"
  - id: "CheckForEmptyString2"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "MailTemplate"
  - id: "CheckForEmptyString5"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "RawMailSubject:DomainValue"
  - id: "CheckForEmptyString6"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "RawMailSubject:DomainValue"
  - id: "CheckForEmptyString8"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "AppliedRebateBO:Rebate:Promotion:BudgetNotificationEmail"
  - id: "CheckPromotionBudgetNotificationRequired1"
    type: "pipelet"
    ref: "CheckPromotionBudgetNotificationRequired"
    bindings:
      PromotionBO: "AppliedRebateBO"
  - id: "CheckPromotionBudgetNotificationRequired2"
    type: "pipelet"
    ref: "CheckPromotionBudgetNotificationRequired"
    config:
      Scope: "BudgetPercentage"
    bindings:
      PromotionBO: "AppliedRebateBO"
  - id: "CheckPromotionBudgetNotificationRequired3"
    type: "pipelet"
    ref: "CheckPromotionBudgetNotificationRequired"
    config:
      Scope: "BudgetExhausted"
    bindings:
      PromotionBO: "AppliedRebateBO"
  - id: "CreateAccountTransaction1"
    type: "pipelet"
    ref: "CreateAccountTransaction"
    bindings:
      Owner: "Domain"
      TypeCode: "TransactionTypeCode"
  - id: "DecisionNode1"
    type: "decision"
    condition: "TransactionMode"
  - id: "DecisionNode2"
    type: "decision"
    condition: "AppliedRebateBO:Rebate:Promotion:Budget"
  - id: "DisablePromotionByBudgetEvent1"
    type: "pipelet"
    ref: "DisablePromotionByBudgetEvent"
    config:
      BudgetEvent: "BudgetReached"
    bindings:
      PromotionBO: "AppliedRebateBO:Rebate:Promotion"
  - id: "End21"
    type: "end"
    strict: true
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "FormatString1"
    type: "pipelet"
    ref: "FormatString"
    bindings:
      InputString: "RawMailSubject:DomainValue"
      OutputString: "MailSubject"
  - id: "FormatString3"
    type: "pipelet"
    ref: "FormatString"
    bindings:
      InputString: "RawMailSubject:DomainValue"
      OutputString: "MailSubject"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "TaxationPolicy"
      Type: "Integer"
    bindings:
      PreferenceDomain: "Organization:OwningDomain"
      PreferenceIntValue: "TaxationPolicy"
  - id: "GetDomainPreference2"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "BudgetNotificationEmailTemplatePercentage"
      Type: "String"
    bindings:
      PreferenceStringValue: "MailTemplate"
      PreferenceDomain: "Organization:OwningDomain"
      PreferenceKey: "null"
  - id: "GetDomainPreference3"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "BudgetNotificationEmailTemplateExhausted"
      Type: "String"
    bindings:
      PreferenceStringValue: "MailTemplate"
      PreferenceDomain: "Organization:OwningDomain"
      PreferenceKey: "null"
  - id: "GetDomainPreference4"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "BudgetNotificationEmailFrom"
      Type: "String"
    bindings:
      PreferenceStringValue: "MailFrom"
      PreferenceDomain: "Organization:OwningDomain"
      PreferenceKey: "null"
  - id: "GetFirstElementOfIterator1"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      Iterator: "MailSubjects"
      FirstElement: "RawMailSubject"
  - id: "GetFirstElementOfIterator2"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      Iterator: "MailSubjects"
      FirstElement: "RawMailSubject"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Lead Locale"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode15"
    type: "join"
  - id: "JoinNode16"
    type: "join"
  - id: "JoinNode17"
    type: "join"
  - id: "JoinNode18"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "LoopNode1"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "CreateLocalizationContextFromApplication"
    bindings:
      Application: "ApplicationBO:Extension(\"PersistentObjectBOExtension\"):PersistentObject"
      LocaleInformation: "Locale"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "DetermineLocalizedTextByLocale"
    bindings:
      SearchedKey: "\"promotion.budget.threshold.email.subject\""
      LocalizationTexts: "MailSubjects"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "DetermineLocalizedTextByLocale"
    bindings:
      SearchedKey: "\"promotion.budget.exhausted.email.subject\""
      LocalizationTexts: "MailSubjects"
  - id: "Pipelet34"
    type: "pipelet"
    ref: "BindAccountTransaction"
    bindings:
      Account: "AppliedRebateBO:Rebate:Promotion:Budget:Account"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "CreateLocalizationContextFromApplication"
    bindings:
      Application: "ApplicationBO:Extension(\"PersistentObjectBOExtension\"):PersistentObject"
      LocaleInformation: "Locale"
  - id: "ProcessMail1"
    type: "pipelet"
    ref: "ProcessMail"
    config:
      WaitForResult: true
      UseErrorConnector: true
    bindings:
      MailTo: "AppliedRebateBO:Rebate:Promotion:BudgetNotificationEmail"
      Domain: "Organization:OwningDomain"
      LocaleID: "Locale:LocaleID"
      MailSubject: "MailSubject"
  - id: "ProcessMail2"
    type: "pipelet"
    ref: "ProcessMail"
    config:
      WaitForResult: true
      UseErrorConnector: true
    bindings:
      MailTo: "AppliedRebateBO:Rebate:Promotion:BudgetNotificationEmail"
      Domain: "Organization:OwningDomain"
      LocaleID: "Locale:LocaleID"
      MailSubject: "MailSubject"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "TransactionMode"
      Value: "credit"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "TransactionMode"
      Value: "debit"
      ValueType: "Dictionary Value"
  - id: "UpdateAccountTransaction1"
    type: "pipelet"
    ref: "UpdateAccountTransaction"
    config:
      AmountUpdatePolicy: "AlwaysNegative"
    bindings:
      Amount: "AppliedRebateBO:Amount"
      AmountCurrency: "null"
      AmountValue: "null"
      TimeStamp: "null"
  - id: "UpdateAccountTransaction4"
    type: "pipelet"
    ref: "UpdateAccountTransaction"
    config:
      AmountUpdatePolicy: "AlwaysPositive"
    bindings:
      Amount: "AppliedRebateBO:Amount"
      AmountCurrency: "null"
      TimeStamp: "null"
      AmountValue: "null"
  - id: "UpdateCustomAttributes4"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "OrderUUID"
      Attribute_1_Type: "String"
      Attribute_2_Name: "PromotionUUID"
      Attribute_2_Type: "String"
    bindings:
      Attribute_1_Value: "OrderBO:ID"
      ExtensibleObject: "AccountTransaction"
      Attribute_2_Value: "AppliedRebateBO:Rebate:Promotion:Extension(\"PersistentObjectBOExtension\"):PersistentObject:UUID"

links:
  - from: "StartNode3"
    via: "next"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "AddMultipleEntriesToMap2"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "GetDomainPreference1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "GetDomainPreference4"
    via: "next"
    to: "CheckForEmptyString8"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "DecisionNode2"
    into: "in"
  - from: "CheckPromotionBudgetNotificationRequired3"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CreateAccountTransaction1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "StartNode1"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "CreateAccountTransaction1"
    via: "error"
    to: "End21"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetLocale1"
    via: "next"
    to: "CheckPromotionBudgetNotificationRequired2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode3"
    into: "in2"
  - from: "UpdateCustomAttributes4"
    via: "next"
    to: "Pipelet34"
    into: "in"
  - from: "Pipelet34"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "GetDomainPreference1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "JoinNode4"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "CheckForEmptyString6"
    via: "error"
    to: "JoinNode17"
    into: "in2"
  - from: "JoinNode6"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "UpdateCustomAttributes4"
    into: "in"
  - from: "ProcessMail1"
    via: "error"
    to: "JoinNode11"
    into: "in2"
  - from: "JoinNode5"
    via: "next"
    to: "CheckPromotionBudgetNotificationRequired3"
    into: "in"
  - from: "ProcessMail1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "CheckPromotionBudgetNotificationRequired1"
    into: "in"
  - from: "GetFirstElementOfIterator2"
    via: "next"
    to: "CheckForEmptyString5"
    into: "in"
  - from: "CheckForEmptyString8"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "CheckForEmptyString5"
    via: "next"
    to: "GetDomainPreference3"
    into: "in"
  - from: "CheckForEmptyString8"
    via: "next"
    to: "AddMultipleEntriesToMap2"
    into: "in"
  - from: "GetFirstElementOfIterator2"
    via: "error"
    to: "JoinNode8"
    into: "in2"
  - from: "GetDomainPreference4"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "UpdateAccountTransaction1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode4"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "StartNode4"
    via: "next"
    to: "GetDomainPreference4"
    into: "in"
  - from: "CheckPromotionBudgetNotificationRequired1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CheckPromotionBudgetNotificationRequired1"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "CheckForEmptyString6"
    via: "next"
    to: "GetDomainPreference2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "CallNode3"
    into: "in"
  - from: "DisablePromotionByBudgetEvent1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GetFirstElementOfIterator1"
    via: "error"
    to: "JoinNode14"
    into: "in1"
  - from: "GetDomainPreference2"
    via: "next"
    to: "CheckForEmptyString2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "UpdateAccountTransaction4"
    into: "in"
  - from: "JoinNode14"
    via: "next"
    to: "JoinNode17"
    into: "in1"
  - from: "CheckPromotionBudgetNotificationRequired2"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "JoinNode17"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "Pipelet3"
    via: "next"
    to: "GetFirstElementOfIterator2"
    into: "in"
  - from: "CheckForEmptyString2"
    via: "error"
    to: "JoinNode16"
    into: "in2"
  - from: "CheckPromotionBudgetNotificationRequired3"
    via: "error"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "CheckForEmptyString5"
    via: "error"
    to: "JoinNode15"
    into: "in2"
  - from: "ProcessMail2"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "UpdateAccountTransaction4"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "CheckForEmptyString2"
    via: "next"
    to: "FormatString1"
    into: "in"
  - from: "JoinNode13"
    via: "next"
    to: "JoinNode12"
    into: "in2"
  - from: "ProcessMail2"
    via: "error"
    to: "JoinNode13"
    into: "in2"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode15"
    into: "in1"
  - from: "JoinNode12"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "JoinNode15"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "GetDomainPreference3"
    via: "next"
    to: "CheckForEmptyString1"
    into: "in"
  - from: "GetDomainPreference2"
    via: "error"
    to: "JoinNode9"
    into: "in2"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode16"
    into: "in1"
  - from: "CheckForEmptyString1"
    via: "error"
    to: "JoinNode18"
    into: "in2"
  - from: "CreateAccountTransaction1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetDomainPreference3"
    via: "error"
    to: "JoinNode10"
    into: "in2"
  - from: "GetFirstElementOfIterator1"
    via: "next"
    to: "CheckForEmptyString6"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "CheckPromotionBudgetNotificationRequired2"
    via: "error"
    to: "JoinNode14"
    into: "in1"
  - from: "JoinNode16"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode18"
    into: "in1"
  - from: "JoinNode18"
    via: "next"
    to: "JoinNode13"
    into: "in1"
  - from: "CheckForEmptyString1"
    via: "next"
    to: "FormatString3"
    into: "in"
  - from: "FormatString3"
    via: "next"
    to: "ProcessMail2"
    into: "in"
  - from: "FormatString1"
    via: "next"
    to: "ProcessMail1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "UpdateAccountTransaction1"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "GetFirstElementOfIterator1"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "DisablePromotionByBudgetEvent1"
    into: "in"
