flow: "ProcessProductSiteMap"
kind: "process"

entries:
  - id: "StartNode1"
    name: "DeterminePageable"
    mode: "private"
    strict: true
    inputs:
      - key: "JobConfigurationUUID"
        type: "java.lang.String"
        required: false
      - key: "Syndication"
        type: "java.lang.String"
        required: false
  - id: "StartNode2"
    name: "Init"
    mode: "private"
    strict: true
    inputs:
      - key: "Syndication"
        type: "com.intershop.component.foundation.capi.syndication.Syndication"
        required: true
      - key: "Objects"
        type: "java.util.Iterator"
        required: false
      - key: "JobConfiguration"
        type: "com.intershop.beehive.core.capi.job.JobConfiguration"
        required: false
  - id: "StartNode3"
    name: "Process"
    mode: "private"
    strict: true
    inputs:
      - key: "Syndication"
        type: "com.intershop.component.foundation.capi.syndication.Syndication"
        required: false
      - key: "Objects"
        type: "java.util.Iterator"
        required: false
  - id: "StartNode4"
    name: "FindOnlineCatalogs"
    mode: "private"
    strict: true
    inputs:
      - key: "CatalogDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "SitemapObjects"
        type: "java.util.Vector"
        required: true
  - id: "StartNode5"
    name: "Post"
    mode: "private"
    strict: true
    inputs:
      - key: "JobConfiguration"
        type: "com.intershop.beehive.core.capi.job.JobConfiguration"
        required: false
      - key: "ProcessLogAppender"
        type: "com.intershop.beehive.core.capi.log.ProcessAppender"
        required: false
      - key: "Syndication"
        type: "com.intershop.component.foundation.capi.syndication.Syndication"
        required: true
  - id: "StartNode6"
    name: "FindOnlineProducts"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "SitemapObjects"
        type: "java.util.Vector"
        required: true
  - id: "StartNode7"
    name: "FindPageletEntryPoints"
    mode: "private"
    strict: true
    inputs:
      - key: "Syndication"
        type: "com.intershop.component.foundation.capi.syndication.Syndication"
        required: true
      - key: "SitemapObjects"
        type: "java.util.Vector"
        required: true

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      OutVector: "SitemapObjects"
      Iterator: "SitemapObjectsIterator"
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      OutVector: "SitemapObjects"
      Objects: "Products"
      Object: "null"
      InVector: "SitemapObjects"
  - id: "AddObjectToVector3"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      OutVector: "SitemapObjects"
      Objects: "Catalogs"
      Object: "null"
      InVector: "SitemapObjects"
  - id: "AddObjectToVector4"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      OutVector: "SitemapObjects"
      Objects: "PageletEntryPointContainers"
      Object: "null"
      InVector: "SitemapObjects"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessProductOutboundSyndication-Init"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessProductSiteMap-FindOnlineProducts"
    bindings:
      ProductDomain: "SearchDomain"
      SitemapObjects: "SitemapObjects"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessProductSiteMap-FindOnlineCatalogs"
    bindings:
      CatalogDomain: "SearchDomain"
      SitemapObjects: "SitemapObjects"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessProductOutboundSyndication-Post"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessProductSiteMap-FindPageletEntryPoints"
  - id: "CreatePageableFromCollection1"
    type: "pipelet"
    ref: "CreatePageableFromCollection"
    bindings:
      Collection: "SitemapObjects"
      Pageable: "Objects"
  - id: "DecisionNode1"
    type: "decision"
    condition: "JobConfigurationUUID"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Syndication:IncludeProducts"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Syndication:IncludeCategories"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Syndication:PingSearchEngines"
  - id: "DecisionNode6"
    type: "decision"
    condition: "Syndication:IncludeStaticPages"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorCode"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode11"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "Objects"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "ProcessLogAppender"
        type: "com.intershop.beehive.core.capi.log.ProcessAppender"
        guaranteed: false
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "SitemapObjects"
        type: "java.util.Vector"
        guaranteed: true
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "Objects"
        type: "com.intershop.beehive.core.capi.paging.PageableIterator"
        guaranteed: false
      - key: "Syndication"
        type: "java.lang.Object"
        guaranteed: false
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorCode"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode7"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorCode"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode8"
    type: "end"
    strict: true
    outputs:
      - key: "SitemapObjects"
        type: "java.util.Vector"
        guaranteed: true
  - id: "EndNode9"
    type: "end"
    strict: true
    outputs:
      - key: "SitemapObjects"
        type: "java.util.Vector"
        guaranteed: true
  - id: "ExecuteObjectsQuery1"
    type: "pipelet"
    ref: "ExecuteObjectsQuery"
    config:
      QueryName: "sitemap/GetProductsForSitemap"
      ParameterName_01: "AdvancedProductSearchParameters"
      ParameterName_02: "ProductDomain"
    bindings:
      SearchResult: "Products"
      ParameterValue_01: "ProductSearchParameters"
      ParameterValue_02: "ProductDomain"
  - id: "ExecuteObjectsQuery2"
    type: "pipelet"
    ref: "ExecuteObjectsQuery"
    config:
      QueryName: "sitemap/GetCategoriesForSitemap"
      ParameterName_01: "AdvancedProductSearchParameters"
      ParameterName_02: "CatalogDomain"
      ParameterName_03: "ProductDomain"
    bindings:
      SearchResult: "Catalogs"
      ParameterValue_01: "ProductSearchParameters"
      ParameterValue_02: "CatalogDomain"
      ParameterValue_03: "CatalogDomain"
      ParameterValue_04: "ProductSearchParameters"
      ParameterValue_05: "CatalogDomain"
  - id: "GetCurrentDate1"
    type: "pipelet"
    ref: "GetCurrentDate"
  - id: "GetCurrentDate2"
    type: "pipelet"
    ref: "GetCurrentDate"
  - id: "GetDomainByUUID1"
    type: "pipelet"
    ref: "GetDomainByUUID"
    bindings:
      Domain: "SearchDomain"
      DomainUUID: "JobConfiguration:DomainID"
  - id: "GetJobConfiguration1"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "GetSitemapPageletEntryPointContainers1"
    type: "pipelet"
    ref: "GetSitemapPageletEntryPointContainers"
  - id: "GetSyndications1"
    type: "pipelet"
    ref: "GetSyndications"
    bindings:
      Domain: "JobConfiguration:Domain"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "aSyndication"
      OutValue_1: "Syndication"
  - id: "LoopNode1"
    type: "loop"
  - id: "MarshalObjects1"
    type: "pipelet"
    ref: "MarshalObjects"
  - id: "PingSearchEngines1"
    type: "pipelet"
    ref: "PingSearchEngines"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "CurrentDate"
      Name_02: "ProductDomain"
    bindings:
      OutDictionary: "ProductSearchParameters"
      InDictionary: "ProductSearchParameters"
      Value_01: "CurrentDate"
      Value_02: "ProductDomain"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "LocaleInformation"
    bindings:
      OutDictionary: "ProductSearchParameters"
      InDictionary: "ProductSearchParameters"
      Value_01: "CurrentSession:Locale"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "Currency"
    bindings:
      OutDictionary: "ProductSearchParameters"
      InDictionary: "ProductSearchParameters"
      Value_01: "CurrentSession:CurrencyCode"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "Currency"
    bindings:
      OutDictionary: "ProductSearchParameters"
      InDictionary: "ProductSearchParameters"
      Value_01: "CurrentSession:CurrencyCode"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "CurrentDate"
      Name_02: "ProductDomain"
    bindings:
      OutDictionary: "ProductSearchParameters"
      InDictionary: "ProductSearchParameters"
      Value_01: "CurrentDate"
      Value_02: "CatalogDomain"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "LocaleInformation"
    bindings:
      OutDictionary: "ProductSearchParameters"
      InDictionary: "ProductSearchParameters"
      Value_01: "CurrentSession:Locale"
  - id: "SetSessionLocale1"
    type: "pipelet"
    ref: "SetSessionLocale"
    bindings:
      LocaleID: "Syndication:LocaleID"
  - id: "TextNode1"
    type: "text"
  - id: "UpdateDictionary1"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "Online"
    bindings:
      Value_01: "\"(Integer)1\""
      OutDictionary: "ProductSearchParameters"
  - id: "UpdateDictionary2"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "Online"
    bindings:
      Value_01: "\"(Integer)1\""
      OutDictionary: "ProductSearchParameters"

links:
  - from: "StartNode1"
    via: "next"
    to: "GetJobConfiguration1"
    into: "in"
  - from: "ExecuteObjectsQuery1"
    via: "error"
    to: "EndNode7"
    into: "in"
  - from: "GetDomainByUUID1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "MarshalObjects1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "next"
    to: "GetDomainByUUID1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GetCurrentDate1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "GetDomainByUUID1"
    via: "next"
    to: "GetSyndications1"
    into: "in"
  - from: "ExecuteObjectsQuery1"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "DecisionNode1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "ExecuteObjectsQuery2"
    via: "error"
    to: "EndNode6"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "KeyMapper2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode4"
    into: "in2"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "SetSessionLocale1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "UpdateDictionary2"
    via: "next"
    to: "GetCurrentDate2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "MarshalObjects1"
    into: "in"
  - from: "GetSyndications1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "GetCurrentDate2"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "CreatePageableFromCollection1"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "CallNode2"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "DecisionNode3"
    via: "yes"
    to: "CallNode3"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode5"
    into: "in2"
  - from: "UpdateDictionary1"
    via: "next"
    to: "GetCurrentDate1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "UpdateDictionary2"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "ExecuteObjectsQuery2"
    via: "next"
    to: "AddObjectToVector3"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "AddObjectToVector3"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "PingSearchEngines1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "Pipelet4"
    via: "next"
    to: "ExecuteObjectsQuery2"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode6"
    into: "in2"
  - from: "DecisionNode4"
    via: "yes"
    to: "PingSearchEngines1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "EndNode11"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "CallNode5"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "CreatePageableFromCollection1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "SetSessionLocale1"
    into: "in"
  - from: "AddObjectToVector4"
    via: "next"
    to: "EndNode9"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "GetSitemapPageletEntryPointContainers1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "GetSitemapPageletEntryPointContainers1"
    via: "next"
    to: "AddObjectToVector4"
    into: "in"
  - from: "SetSessionLocale1"
    via: "error"
    to: "JoinNode8"
    into: "in2"
  - from: "JoinNode8"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "ExecuteObjectsQuery1"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "UpdateDictionary1"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
