flow: "ProcessB2CProduct"
kind: "process"

entries:
  - id: "StartNode1"
    name: "GetProduct"
    mode: "private"
    strict: true
    inputs:
      - key: "SKU"
        type: "java.lang.String"
        required: false
      - key: "ProductUUID"
        type: "java.lang.String"
        required: false
      - key: "ProductDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode2"
    name: "GetProductPrice"
    mode: "private"
    strict: true
    inputs:
      - key: "User"
        type: "com.intershop.beehive.core.capi.user.User"
        required: true
      - key: "Product"
        type: "com.intershop.beehive.xcs.capi.product.Product"
        required: true
  - id: "StartNode3"
    name: "GetProductBOs"
    mode: "private"
    strict: true
    inputs:
      - key: "Products"
        type: "java.util.Iterator"
        required: false
  - id: "StartNode5"
    name: "GetTopLevelProduct"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "ProductUUID"
        type: "java.lang.String"
        required: false
      - key: "SKU"
        type: "java.lang.String"
        required: false
  - id: "StartNode6"
    name: "GetProductBO"
    mode: "private"
    strict: true
    inputs:
      - key: "Product"
        type: "com.intershop.beehive.xcs.capi.product.Product"
        required: false
      - key: "ProductRef"
        type: "com.intershop.beehive.xcs.common.ProductRef"
        required: false
      - key: "SelectedAttributesMap"
        type: "java.lang.Object"
        required: false
  - id: "StartNode7"
    name: "GetProductBOByProductUUIDOrSKU"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "ProductUUID"
        type: "java.lang.String"
        required: false
      - key: "SKU"
        type: "java.lang.String"
        required: false

steps:
  - id: "CallNode2"
    type: "call"
    ref: "ProcessB2CProduct-GetProduct"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessB2CProduct-GetProductBO"
    bindings:
      ProductRef: "Product:ProductRef"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessB2CProduct-GetProduct"
  - id: "CheckInstanceOf1"
    type: "pipelet"
    ref: "CheckInstanceOf"
    config:
      Type1: "com.intershop.beehive.core.capi.paging.PageableIterator"
    bindings:
      Object: "Products"
  - id: "CreateBOMappingIterator1"
    type: "pipelet"
    ref: "CreateBOMappingIterator"
    bindings:
      BOFactoryID: "\"com.intershop.component.product.ProductBOFactory\""
      SourceIterator: "Products"
      TargetIterator: "ProductBOs"
      Domain: "CurrentDomain"
  - id: "CreatePageableFromIterator1"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    bindings:
      Iterator: "ProductBOs"
      Pageable: "ProductBOs"
  - id: "Decision2"
    type: "decision"
    condition: "Product:Mastered"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ProductUUID"
  - id: "DecisionNode2"
    type: "decision"
    condition: "SKU"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Product"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "Product"
        type: "com.intershop.beehive.xcs.capi.product.Product"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "ProductPrices"
        type: "com.intershop.beehive.xcs.capi.price.ProductPriceMapping"
        guaranteed: true
      - key: "ProductListPrice"
        type: "com.intershop.beehive.xcs.capi.price.ProductListPrice"
        guaranteed: false
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "Product"
        type: "com.intershop.beehive.xcs.capi.product.Product"
        guaranteed: true
  - id: "EndNode5"
    type: "end"
    strict: true
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "ProductBO"
        type: "com.intershop.component.product.capi.ProductBO"
        guaranteed: false
  - id: "EndNode7"
    type: "end"
    strict: true
    outputs:
      - key: "ProductBO"
        type: "com.intershop.component.product.capi.ProductBO"
        guaranteed: false
  - id: "EndNode8"
    type: "end"
    strict: true
    outputs:
      - key: "ProductBOs"
        type: "java.util.Iterator"
        guaranteed: false
  - id: "GetApplicationBO2"
    type: "pipelet"
    ref: "GetApplicationBO"
  - id: "GetProductBOByID1"
    type: "pipelet"
    ref: "GetProductBOByID"
    bindings:
      ID: "Product:UUID"
      Domain: "Product:Domain"
  - id: "GetProductByProductRef1"
    type: "pipelet"
    ref: "GetProductByProductRef"
    bindings:
      ProductRefIDs: "null"
      ProductRefs: "null"
  - id: "GetProductBySKU1"
    type: "pipelet"
    ref: "GetProductBySKU"
    bindings:
      Domain: "ProductDomain"
  - id: "GetProductByUUID1"
    type: "pipelet"
    ref: "GetProductByUUID"
  - id: "GetProductListPrice1"
    type: "pipelet"
    ref: "GetProductListPrice"
    bindings:
      CurrencyMnemonic: "CurrentSession:CurrencyCode"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Product:ProductMaster"
      OutValue_1: "Product"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Product\"):getProductBORepository(Product:Domain:UUID)"
      OutValue_1: "ProductBORepository"
  - id: "Pipelet20"
    type: "pipelet"
    ref: "DetermineProductPrices"
    bindings:
      CurrentUser: "User"

links:
  - from: "DecisionNode1"
    via: "yes"
    to: "GetProductByUUID1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetProductListPrice1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode3"
    into: "in2"
  - from: "GetProductBySKU1"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "GetProductListPrice1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "GetProductListPrice1"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "GetProductBySKU1"
    into: "in"
  - from: "CallNode5"
    via: "ERROR"
    to: "EndNode5"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "GetProductByUUID1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "KeyMapper2"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "JoinNode5"
    into: "in2"
  - from: "StartNode5"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "GetProductBOByID1"
    via: "error"
    to: "JoinNode9"
    into: "in2"
  - from: "StartNode6"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "GetProductByProductRef1"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "GetProductByProductRef1"
    via: "next"
    to: "JoinNode6"
    into: "in3"
  - from: "StartNode7"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CreateBOMappingIterator1"
    into: "in"
  - from: "CreateBOMappingIterator1"
    via: "next"
    to: "CheckInstanceOf1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "GetApplicationBO2"
    into: "in"
  - from: "CreatePageableFromIterator1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "GetProductByProductRef1"
    via: "error"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "CheckInstanceOf1"
    via: "next"
    to: "CreatePageableFromIterator1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "Pipelet20"
    into: "in"
  - from: "CheckInstanceOf1"
    via: "error"
    to: "JoinNode8"
    into: "in2"
  - from: "JoinNode7"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "GetProductBOByID1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "GetApplicationBO2"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "GetProductBOByID1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetProductByUUID1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetProductBySKU1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Pipelet20"
    via: "next"
    to: "EndNode3"
    into: "in"
