flow: "ProcessCheckoutMultipleAddresses"
kind: "process"

entries:
  - id: "StartNode10"
    name: "GenerateForm"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode11"
    name: "ValidateForm"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode13"
    name: "GetSplitProductLineItems"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentCartBO"
        type: "com.intershop.component.basket.capi.BasketBO"
        required: false
  - id: "StartNode14"
    name: "SetMergedProductLineItems"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentCartBO"
        type: "com.intershop.component.basket.capi.BasketBO"
        required: true
      - key: "PLISplitInfoMap"
        type: "com.intershop.component.basket.capi.BasketProductLineItemSplitInfoMap"
        required: true
  - id: "StartNode2"
    name: "UpdateShipToAddressID"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "GenerateFormIterator"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentCartBO"
        type: "com.intershop.component.basket.capi.BasketBO"
        required: true
      - key: "PLISplitInfoMap"
        type: "com.intershop.component.basket.capi.BasketProductLineItemSplitInfoMap"
        required: false

steps:
  - id: "AddEntryToMap3"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "FormKeys"
      OutMap: "FormKeys"
      Keys: "FormKeyIterator"
      Key: "PLISplitInfo:ID"
      Value: "\"\""
  - id: "AddEntryToMap6"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "FormKeys"
      OutMap: "FormKeys"
      Keys: "FormKeyIterator"
      Key: "\"Splitting\""
      Value: "\"\""
  - id: "CallNode13"
    type: "call"
    ref: "ProcessCheckoutAddresses-CheckAddressOwner"
    bindings:
      AddressID: "Subform:ShipToAddressID:Value"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessCheckoutMultipleAddresses-GenerateFormIterator"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessCheckoutMultipleAddresses-GenerateForm"
  - id: "CreateListForm1"
    type: "pipelet"
    ref: "CreateListForm"
    config:
      FormName: "MultipleAddressesForm"
      ResourceName: "MultipleAddresses"
      ObjectIDMethod: "toString"
    bindings:
      PageableObject: "Pageable"
      Form: "MultipleAddressesForm"
  - id: "CreatePageableFromIterator1"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    bindings:
      Iterator: "FormKeyIterator"
  - id: "DecisionNode10"
    type: "decision"
    condition: "PLISplitInfoMap"
  - id: "DecisionNode11"
    type: "decision"
    condition: "Subform:ShipToAddressID:Value"
  - id: "DecisionNode35"
    type: "decision"
    condition: "FormError"
  - id: "EndNode13"
    type: "end"
    strict: false
  - id: "EndNode14"
    type: "end"
    strict: false
  - id: "EndNode15"
    type: "end"
    strict: false
  - id: "EndNode17"
    type: "end"
    strict: true
    outputs:
      - key: "PLISplitInfoMap"
        type: "com.intershop.component.basket.capi.BasketProductLineItemSplitInfoMap"
        guaranteed: false
  - id: "EndNode18"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "FormKeyIterator"
        type: "java.util.Iterator"
        guaranteed: false
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "GetBasketProductLineItemSplitInfo1"
    type: "pipelet"
    ref: "GetBasketProductLineItemSplitInfo"
    config:
      strategyName: "ShippingPLISplitInfoSplitStrategy"
    bindings:
      Basket: "CurrentCartBO"
  - id: "GetBasketProductLineItemSplitInfo2"
    type: "pipelet"
    ref: "GetBasketProductLineItemSplitInfo"
    config:
      strategyName: "GiftingPLISplitInfoSplitStrategy"
    bindings:
      Basket: "CurrentCartBO"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode20"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "MultipleAddressesForm:get(PLISplitInfo:ID)"
      OutValue_1: "Subform"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode12"
    type: "loop"
  - id: "LoopNode13"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "LoopNode6"
    type: "loop"
  - id: "SetBasketProductLineItemSplitInfo1"
    type: "pipelet"
    ref: "SetBasketProductLineItemSplitInfo"
    config:
      strategyName: "ShippingPLISplitInfoMergeStrategy"
    bindings:
      Basket: "CurrentCartBO"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "FormError"
      Value: true
      ValueType: "Dictionary Value"
  - id: "SetSplitShipToAddress1"
    type: "pipelet"
    ref: "SetSplitShipToAddress"
    bindings:
      ShipToAddressID: "Subform:ShipToAddressID:Value"
  - id: "ValidateForm2"
    type: "pipelet"
    ref: "ValidateForm"
    config:
      Trim: true
    bindings:
      Form: "Subform"

links:
  - from: "StartNode13"
    via: "next"
    to: "GetBasketProductLineItemSplitInfo1"
    into: "in"
  - from: "CallNode13"
    via: "ERROR"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "DecisionNode11"
    via: "yes"
    to: "CallNode13"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "CallNode13"
    via: "OK"
    to: "SetSplitShipToAddress1"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CreatePageableFromIterator1"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "StartNode14"
    via: "next"
    to: "SetBasketProductLineItemSplitInfo1"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "KeyMapper2"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "LoopNode2"
    into: "in"
  - from: "CreateListForm1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "SetBasketProductLineItemSplitInfo1"
    via: "next"
    to: "EndNode18"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode13"
    into: "in"
  - from: "CreateListForm1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "StartNode10"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "AddEntryToMap3"
    via: "next"
    to: "LoopNode13"
    into: "loop"
  - from: "LoopNode6"
    via: "do"
    to: "LoopNode13"
    into: "in"
  - from: "LoopNode13"
    via: "do"
    to: "AddEntryToMap3"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "LoopNode12"
    into: "loop"
  - from: "GetBasketProductLineItemSplitInfo1"
    via: "next"
    to: "EndNode17"
    into: "in"
  - from: "GetBasketProductLineItemSplitInfo2"
    via: "next"
    to: "JoinNode20"
    into: "in3"
  - from: "LoopNode13"
    via: "next"
    to: "LoopNode6"
    into: "loop"
  - from: "JoinNode20"
    via: "next"
    to: "LoopNode6"
    into: "in"
  - from: "LoopNode6"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "AddEntryToMap6"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "LoopNode12"
    into: "in"
  - from: "DecisionNode10"
    via: "yes"
    to: "JoinNode20"
    into: "in1"
  - from: "DecisionNode10"
    via: "no"
    to: "GetBasketProductLineItemSplitInfo2"
    into: "in"
  - from: "DecisionNode35"
    via: "yes"
    to: "EndNode15"
    into: "in"
  - from: "DecisionNode35"
    via: "no"
    to: "EndNode14"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "AddEntryToMap6"
    via: "next"
    to: "DecisionNode10"
    into: "in"
  - from: "StartNode11"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "ValidateForm2"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "LoopNode12"
    via: "next"
    to: "DecisionNode35"
    into: "in"
  - from: "ValidateForm2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "LoopNode12"
    via: "do"
    to: "ValidateForm2"
    into: "in"
  - from: "DecisionNode11"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "SetSplitShipToAddress1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CreatePageableFromIterator1"
    via: "next"
    to: "CreateListForm1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "DecisionNode11"
    into: "in"
