flow: "ProcessUserExport"
kind: "process"

entries:
  - id: "Start1"
    name: "Error"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Run"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Cleanup"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Export"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Prepare"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessImpexJob-Finish"
  - id: "Call2"
    type: "call"
    ref: "ProcessUserExport-Error"
  - id: "Call3"
    type: "call"
    ref: "ProcessImpexJob-Finish"
  - id: "Call4"
    type: "call"
    ref: "ProcessUserExport-Prepare"
  - id: "Call5"
    type: "call"
    ref: "ProcessUserExport-Run"
  - id: "Call6"
    type: "call"
    ref: "ProcessUserExport-Cleanup"
  - id: "Call7"
    type: "call"
    ref: "ProcessUserExport-Error"
  - id: "CloseFile1"
    type: "pipelet"
    ref: "CloseFile"
    config:
      PipeletID: "CloseXMLFile1"
      StreamID: "target"
      UIDescription: "CloseExportFile"
  - id: "CloseFile2"
    type: "pipelet"
    ref: "CloseFile"
    config:
      PipeletID: "CloseXMLFile1"
      StreamID: "target"
      UIDescription: "CloseFile"
      Delete: true
  - id: "CloseFilter1"
    type: "pipelet"
    ref: "CloseFilter"
    config:
      FilterID: "targetfilter"
      PipeletID: "CloseFilter1"
      UIDescription: "CloseFilter"
  - id: "CloseFilter2"
    type: "pipelet"
    ref: "CloseFilter"
    config:
      FilterID: "targetfilter"
      PipeletID: "CloseFilter1"
      UIDescription: "CloseFilter"
  - id: "CloseLoggers1"
    type: "pipelet"
    ref: "CloseLoggers"
    config:
      PipeletID: "CloseLoggers1"
      UIDescription: "CloseLoggers"
  - id: "CloseLoggers2"
    type: "pipelet"
    ref: "CloseLoggers"
    config:
      PipeletID: "CloseLoggers1"
      UIDescription: "CloseLoggers"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString2: ".log"
    bindings:
      Concatenated: "LogFile"
      String1: "JobConfiguration:UUID"
  - id: "ConcatenateStrings2"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString2: "/"
    bindings:
      Concatenated: "ExportPath"
      String1: "ExportDirectory"
      String3: "SelectedFile"
  - id: "CreateDirectory1"
    type: "pipelet"
    ref: "CreateDirectory"
    config:
      DefaultDirectoryPath: "export"
      UnitDirectory: "IMPEX_DIR"
    bindings:
      DirectoryName: "ExportDirectory"
      UnitDomain: "JobConfiguration:Domain"
  - id: "CreateFileLogger1"
    type: "pipelet"
    ref: "CreateFileLogger"
    config:
      BufferSize: 1024
      Facility: "default"
      FlushTime: 0
      Level: "ERROR | WARN"
      PipeletID: "CreateFileLogger1"
      RolloverSize: 1024000000
      UIDescription: "CreateFileLogger"
    bindings:
      File: "LogFile"
  - id: "CreateImpexUnitFileStructure1"
    type: "pipelet"
    ref: "CreateImpexUnitFileStructure"
  - id: "CreateJobInteractor1"
    type: "pipelet"
    ref: "CreateJobInteractor"
  - id: "Decision1"
    type: "decision"
    condition: "JobConfiguration"
  - id: "Decision4"
    type: "decision"
    condition: "JobConfiguration"
  - id: "DetermineConfiguration2"
    type: "pipelet"
    ref: "DetermineConfiguration"
    config:
      CartridgeName: "bc_foundation"
      Controller.Class: "com.intershop.beehive.core.capi.impex.Controller"
      File: "UserExport.properties"
      PerformAccessControl: false
      PipeletID: "DetermineConfiguration1"
      UIDescription: "DetermineConfiguration"
  - id: "End1"
    type: "end"
  - id: "End2"
    type: "end"
  - id: "End3"
    type: "end"
  - id: "End4"
    type: "end"
  - id: "End5"
    type: "end"
  - id: "Export1"
    type: "pipelet"
    ref: "Export"
    config:
      PipeletID: "Export1"
      TargetID: "targetfilter"
      UIDescription: "Export"
  - id: "GetJobConfiguration1"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      PageableID: "ObjectsID"
      Pageable: "Objects"
  - id: "Join10"
    type: "join"
  - id: "Join11"
    type: "join"
  - id: "Join12"
    type: "join"
  - id: "Join13"
    type: "join"
  - id: "Join14"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "OpenFile1"
    type: "pipelet"
    ref: "OpenFile"
    config:
      PipeletID: "OpenXMLFileOrderExport1"
      StreamID: "target"
      Type: "TARGET"
      UIDescription: "OpenFile"
    bindings:
      File: "ExportPath"
  - id: "OpenFilter1"
    type: "pipelet"
    ref: "OpenFilter"
    config:
      Filter.Class: "com.intershop.beehive.core.internal.impex.XMLExportFilter"
      FilterID: "targetfilter"
      PipeletID: "OpenFilter1"
      TargetID: "target"
      UIDescription: "OpenFilter"
  - id: "RemoveJobInteractor1"
    type: "pipelet"
    ref: "RemoveJobInteractor"
  - id: "RemoveJobInteractor2"
    type: "pipelet"
    ref: "RemoveJobInteractor"
  - id: "Stop1"
    type: "stop"
  - id: "Stop2"
    type: "stop"
  - id: "UpdateCustomAttribute1"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    config:
      DefaultAttributeName: "FinishedWithError"
      DefaultAttributeType: "String"
      DefaultAttributeValue: true
    bindings:
      ExtensibleObject: "JobConfiguration"
  - id: "WriteImpexLogMessage1"
    type: "pipelet"
    ref: "WriteImpexLogMessage"
    config:
      PipeletID: "LogTemplateError"
    bindings:
      MessageKey: "\"core.impex.pipelet.Export_E_TEMPLATEPROCESSOR\""
      Level: "\"ERROR\""
      Parameter0: "Exception"

links:
  - from: "CloseFilter1"
    via: "next"
    to: "CloseFile1"
    into: "in"
  - from: "CloseFilter1"
    via: "error"
    to: "Join2"
    into: "in3"
  - from: "OpenFile1"
    via: "next"
    to: "OpenFilter1"
    into: "in"
  - from: "WriteImpexLogMessage1"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "CloseFile2"
    via: "next"
    to: "WriteImpexLogMessage1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "OpenFile1"
    into: "in"
  - from: "CloseFile1"
    via: "next"
    to: "End3"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "GetJobConfiguration1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Export1"
    via: "next"
    to: "CloseFilter1"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "End4"
    into: "in"
  - from: "CreateJobInteractor1"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "next"
    to: "CreateImpexUnitFileStructure1"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "Join13"
    into: "in2"
  - from: "OpenFile1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "CreateFileLogger1"
    via: "next"
    to: "ConcatenateStrings2"
    into: "in"
  - from: "ConcatenateStrings2"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "error"
    to: "Join11"
    into: "in1"
  - from: "CreateDirectory1"
    via: "next"
    to: "CreateFileLogger1"
    into: "in"
  - from: "Join14"
    via: "next"
    to: "Join13"
    into: "in1"
  - from: "OpenFilter1"
    via: "next"
    to: "Export1"
    into: "in"
  - from: "CreateDirectory1"
    via: "error"
    to: "Join14"
    into: "in2"
  - from: "Join12"
    via: "next"
    to: "Join14"
    into: "in1"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "CreateDirectory1"
    into: "in"
  - from: "Join11"
    via: "next"
    to: "Join12"
    into: "in1"
  - from: "CreateImpexUnitFileStructure1"
    via: "error"
    to: "Join11"
    into: "in2"
  - from: "CloseLoggers2"
    via: "next"
    to: "Join10"
    into: "in1"
  - from: "Call3"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "Join10"
    via: "next"
    to: "RemoveJobInteractor2"
    into: "in"
  - from: "CloseLoggers2"
    via: "error"
    to: "Join10"
    into: "in3"
  - from: "Start3"
    via: "next"
    to: "CloseLoggers2"
    into: "in"
  - from: "OpenFilter1"
    via: "error"
    to: "Join3"
    into: "in2"
  - from: "Decision4"
    via: "yes"
    to: "Call3"
    into: "in"
  - from: "Join9"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "Join9"
    into: "in3"
  - from: "JoinNode1"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "End5"
    into: "in"
  - from: "Join13"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Stop1"
    into: "in"
  - from: "Export1"
    via: "error"
    to: "CloseFilter2"
    into: "in"
  - from: "CloseLoggers1"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Call1"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "CloseLoggers1"
    via: "error"
    to: "Join6"
    into: "in3"
  - from: "Join7"
    via: "next"
    to: "End1"
    into: "in"
  - from: "UpdateCustomAttribute1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "UpdateCustomAttribute1"
    via: "error"
    to: "Join4"
    into: "in3"
  - from: "Decision1"
    via: "yes"
    to: "UpdateCustomAttribute1"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Stop2"
    into: "in"
  - from: "CreateImpexUnitFileStructure1"
    via: "next"
    to: "DetermineConfiguration2"
    into: "in"
  - from: "CloseFilter2"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "DetermineConfiguration2"
    via: "next"
    to: "CreateJobInteractor1"
    into: "in"
  - from: "DetermineConfiguration2"
    via: "error"
    to: "Join12"
    into: "in2"
  - from: "Join4"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join7"
    into: "in3"
  - from: "Start1"
    via: "next"
    to: "CloseLoggers1"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "RemoveJobInteractor1"
    into: "in"
  - from: "RemoveJobInteractor1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "RemoveJobInteractor2"
    via: "next"
    to: "Decision4"
    into: "in"
  - from: "CloseFilter2"
    via: "error"
    to: "Join3"
    into: "in3"
  - from: "Join3"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "CloseFile2"
    into: "in"
