flow: "ProcessOrderInjection"
kind: "process"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "PrepareDictValues"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessOrderInjection-PrepareDictValues"
  - id: "CreateDOrderFromOrder1"
    type: "pipelet"
    ref: "CreateDOrderFromOrder"
  - id: "Decision1"
    type: "decision"
    condition: "Organization:OJ_HOSTNAME"
  - id: "DetermineUnit1"
    type: "pipelet"
    ref: "DetermineUnit"
    bindings:
      Unit: "CurrentDomain1"
  - id: "End1"
    type: "end"
  - id: "End2"
    type: "end"
  - id: "End3"
    type: "end"
  - id: "GetOrders1"
    type: "pipelet"
    ref: "GetOrders"
    config:
      DefaultStatus: 3
    bindings:
      Domain: "CurrentDomain1"
  - id: "GetOrganizationByDomain1"
    type: "pipelet"
    ref: "GetOrganizationByDomain"
    bindings:
      OrganizationDomain: "CurrentDomain1"
  - id: "GetService1"
    type: "pipelet"
    ref: "GetService"
    bindings:
      RemoteSystemID: "Organization:OJ_HOSTNAME"
  - id: "InjectOrder1"
    type: "pipelet"
    ref: "InjectOrder"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Loop1"
    type: "loop"
  - id: "ObtainServiceConnection1"
    type: "pipelet"
    ref: "ObtainServiceConnection"
    bindings:
      Hostname: "Organization:OJ_HOSTNAME"
      Id: "Organization:OJ_HOSTNAME"
      Login: "Organization:OJ_LOGIN"
      Password: "Organization:OJ_PASSWD"
      RegistrationDomain: "Organization:OJ_REGDOMAIN"
      RegistrationSite: "Organization:OJ_REGSITE"
      ServerGroup: "Organization:OJ_SERVERGROUP"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Status"
      Value: 3
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "EnableHttps"
      Value: false
  - id: "UpdateOrderStatus1"
    type: "pipelet"
    ref: "UpdateOrderStatus"
    config:
      StateGroup: "OrderStatus"
      StateName: "COMPLETED"

links:
  - from: "DetermineUnit1"
    via: "next"
    to: "GetOrganizationByDomain1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "End3"
    into: "in"
  - from: "GetOrders1"
    via: "error"
    to: "Join1"
    into: "in3"
  - from: "Join2"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "ObtainServiceConnection1"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "GetOrganizationByDomain1"
    via: "error"
    to: "Join3"
    into: "in2"
  - from: "Join3"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "DetermineUnit1"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "InjectOrder1"
    via: "next"
    to: "UpdateOrderStatus1"
    into: "in"
  - from: "UpdateOrderStatus1"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "GetOrders1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "DetermineUnit1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "ObtainServiceConnection1"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Decision1"
    via: "no"
    to: "Join4"
    into: "in2"
  - from: "Loop1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "GetOrganizationByDomain1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "ObtainServiceConnection1"
    via: "next"
    to: "GetService1"
    into: "in"
  - from: "GetService1"
    via: "next"
    to: "GetOrders1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "CreateDOrderFromOrder1"
    into: "in"
  - from: "CreateDOrderFromOrder1"
    via: "next"
    to: "InjectOrder1"
    into: "in"
  - from: "GetService1"
    via: "error"
    to: "Join1"
    into: "in1"
