flow: "ProcessUserList"
kind: "process"

entries:
  - id: "Start2"
    name: "BySimpleSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "List"
    mode: "private"
    strict: false
    inputs:
      - key: "Filter"
        type: "java.lang.String"
        required: true
      - key: "UserDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode1"
    name: "ByFilter"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "ByParametricSearch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector3"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Objects: "Roles"
      Iterator: "UserRoles"
  - id: "AddObjectToVector4"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Object: "Role"
      Objects: "Roles"
      Iterator: "UserRoles"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Role"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "ExecutePageableQuery3"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      Datasource: "default"
      DefaultPageSize: 10
      QueryName: "user/GetUsersByParametricSearch"
    bindings:
      Parameters: "UserSearchParameters"
      SearchResult: "Users"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "UpdateDictionary1"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "CostCenterNameExp"
      Name_02: "SimpleSearchTermExp"
      Name_03: "UserRoles"
      Name_04: "UserGroups"
      Name_05: "PermissionID"
      Name_06: "OrganizationUUID"
      Name_07: "CreationDateFrom"
      Name_08: "CreationDateTo"
    bindings:
      InDictionary: "UserSearchParameters"
      Value_01: "CostCenterNameExp"
      Value_02: "SimpleSearchTermExp"
      Value_04: "UserGroups"
      Value_03: "UserRoles"
      Value_05: "PermissionID"
      Value_06: "Organization:UUID"
      Value_07: "CreationDateFrom"
      Value_08: "CreationDateTo"
      OutDictionary: "UserSearchParameters"
  - id: "UpdateDictionary2"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "DomainID"
      Name_02: "BusinessPartnerNoExp"
      Name_03: "FirstNameExp"
      Name_04: "LastNameExp"
      Name_05: "LoginExp"
      Name_06: "DisabledFlag"
      Name_07: "ReminderEmailExp"
      Name_08: "AccessRoleID"
      Name_09: "LocaleInformation"
      Name_10: "DepartmentNameExp"
    bindings:
      InDictionary: "null"
      Value_01: "UserDomain:UUID"
      Value_02: "BusinessPartnerNoExp"
      Value_03: "FirstNameExp"
      Value_04: "LastNameExp"
      Value_05: "LoginExp"
      Value_06: "DisabledFlag"
      Value_07: "ReminderEmailExp"
      Value_08: "AccessRoleID"
      Value_09: "CurrentRequest:Locale"
      Value_10: "DepartmentNameExp"
      OutDictionary: "UserSearchParameters"
  - id: "VerifySearchTerm1"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowFuzzySearch: false
      DefaultOperator: "OR"
    bindings:
      UserSearchTerm: "FirstName"
      SearchExpression: "FirstNameExp"
      ErrorCode: "FirstNameError"
  - id: "VerifySearchTerm2"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowFuzzySearch: false
      DefaultOperator: "OR"
    bindings:
      UserSearchTerm: "BusinessPartnerNo"
      SearchExpression: "BusinessPartnerNoExp"
      ErrorCode: "BusinessPartnerNoError"
  - id: "VerifySearchTerm3"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowFuzzySearch: false
      DefaultOperator: "OR"
    bindings:
      UserSearchTerm: "LastName"
      SearchExpression: "LastNameExp"
      ErrorCode: "LastNameError"
  - id: "VerifySearchTerm4"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowFuzzySearch: false
      DefaultOperator: "OR"
    bindings:
      UserSearchTerm: "Login"
      SearchExpression: "LoginExp"
      ErrorCode: "LoginError"
  - id: "VerifySearchTerm5"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowFuzzySearch: false
      DefaultOperator: "OR"
      AllowWildcards: "Multi"
    bindings:
      UserSearchTerm: "ReminderEmail"
      SearchExpression: "ReminderEmailExp"
      ErrorCode: "ReminderEmailError"
  - id: "VerifySearchTerm6"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowFuzzySearch: true
      DefaultOperator: "OR"
      AllowWildcards: "default"
      AllowSubOperator: "default"
    bindings:
      UserSearchTerm: "SearchTerm"
      SearchExpression: "SimpleSearchTermExp"
      ErrorCode: "SimpleSearchTermError"
  - id: "VerifySearchTerm7"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowFuzzySearch: false
      DefaultOperator: "OR"
    bindings:
      UserSearchTerm: "DepartmentName"
      SearchExpression: "DepartmentNameExp"
      ErrorCode: "DepartmentNameError"
  - id: "VerifySearchTerm8"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowFuzzySearch: false
      DefaultOperator: "OR"
    bindings:
      UserSearchTerm: "CostCenterName"
      SearchExpression: "CostCenterNameExp"
      ErrorCode: "CostCenterNameError"

links:
  - from: "AddObjectToVector3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "AddObjectToVector4"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "AddObjectToVector3"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "AddObjectToVector4"
    into: "in"
  - from: "ExecutePageableQuery3"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "ExecutePageableQuery3"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode12"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "UpdateDictionary2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "Start2"
    via: "next"
    to: "VerifySearchTerm6"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "VerifySearchTerm2"
    into: "in"
  - from: "UpdateDictionary1"
    via: "next"
    to: "ExecutePageableQuery3"
    into: "in"
  - from: "UpdateDictionary2"
    via: "next"
    to: "UpdateDictionary1"
    into: "in"
  - from: "VerifySearchTerm1"
    via: "error"
    to: "JoinNode11"
    into: "in1"
  - from: "VerifySearchTerm1"
    via: "next"
    to: "VerifySearchTerm3"
    into: "in"
  - from: "VerifySearchTerm2"
    via: "error"
    to: "JoinNode12"
    into: "in1"
  - from: "VerifySearchTerm2"
    via: "next"
    to: "VerifySearchTerm1"
    into: "in"
  - from: "VerifySearchTerm3"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "VerifySearchTerm3"
    via: "next"
    to: "VerifySearchTerm4"
    into: "in"
  - from: "VerifySearchTerm4"
    via: "error"
    to: "JoinNode9"
    into: "in1"
  - from: "VerifySearchTerm4"
    via: "next"
    to: "VerifySearchTerm5"
    into: "in"
  - from: "VerifySearchTerm5"
    via: "error"
    to: "JoinNode8"
    into: "in1"
  - from: "VerifySearchTerm5"
    via: "next"
    to: "VerifySearchTerm8"
    into: "in"
  - from: "VerifySearchTerm6"
    via: "error"
    to: "JoinNode12"
    into: "in1"
  - from: "VerifySearchTerm6"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "VerifySearchTerm7"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "VerifySearchTerm7"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "VerifySearchTerm8"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "VerifySearchTerm8"
    via: "next"
    to: "VerifySearchTerm7"
    into: "in"
