flow: "ProcessProductType"
kind: "process"

entries:
  - id: "StartNode1"
    name: "GetProductTypeByClassificationCategory"
    mode: "private"
    strict: true
    inputs:
      - key: "Category"
        type: "com.intershop.beehive.xcs.capi.catalog.CatalogCategory"
        required: true
      - key: "Catalog"
        type: "com.intershop.component.mvc.capi.catalog.Catalog"
        required: true
  - id: "StartNode2"
    name: "GetClassificationCategoryByProductType"
    mode: "private"
    strict: true
    inputs:
      - key: "Catalog"
        type: "com.intershop.component.mvc.capi.catalog.Catalog"
        required: true
      - key: "ProductType"
        type: "com.intershop.beehive.xcs.capi.producttype.ProductType"
        required: true

steps:
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "eclass_"
    bindings:
      String1: "Category:Name"
      Concatenated: "ProductTypeName"
  - id: "Decision1"
    type: "decision"
    condition: "IndexOf"
  - id: "Decision15"
    type: "decision"
    condition: "IndexOf"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Catalog:ClassificationSystem"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Catalog:ClassificationSystem"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "Category"
        type: "com.intershop.beehive.xcs.capi.catalog.CatalogCategory"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "ProductType"
        type: "com.intershop.beehive.xcs.capi.producttype.ProductType"
        guaranteed: true
  - id: "GetCategoryByName1"
    type: "pipelet"
    ref: "GetCategoryByName"
    bindings:
      CategoryDomainName: "Catalog:Domain:DomainName"
      CategoryName: "CategoryName"
      Category: "Category"
  - id: "GetProductType1"
    type: "pipelet"
    ref: "GetProductType"
    bindings:
      ProductType: "ProductType"
      ProductTypeName: "ProductTypeName"
      ProductTypeDomainName: "Category:Domain:DomainName"
      ProductTypeUUID: "null"
  - id: "GetStringIndexOf1"
    type: "pipelet"
    ref: "GetStringIndexOf"
    bindings:
      MainString: "Catalog:ClassificationSystem:Name"
      SubString: "\"eCl@ss\""
  - id: "GetStringIndexOf2"
    type: "pipelet"
    ref: "GetStringIndexOf"
    bindings:
      MainString: "Catalog:ClassificationSystem:Name"
      SubString: "\"eCl@ss\""
  - id: "GetStringSubstitution1"
    type: "pipelet"
    ref: "GetStringSubstitution"
    config:
      DefaultPattern: "^eclass_"
    bindings:
      InputString: "ProductType:Name"
      Pattern: "null"
      SubstitutionPattern: "null"
      OutputString: "CategoryName"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ProductType:Name"
      OutValue_1: "CategoryName"
  - id: "KeyMapper6"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "ProductTypeName"
      InValue_1: "Category:Name"

links:
  - from: "GetProductType1"
    via: "error"
    to: "EndNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetStringIndexOf1"
    into: "in"
  - from: "GetStringIndexOf1"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "GetStringSubstitution1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetStringSubstitution1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "GetCategoryByName1"
    into: "in"
  - from: "GetCategoryByName1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "GetCategoryByName1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode4"
    via: "yes"
    to: "GetStringIndexOf2"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "Decision15"
    via: "no"
    to: "JoinNode4"
    into: "in2"
  - from: "GetStringIndexOf2"
    via: "next"
    to: "Decision15"
    into: "in"
  - from: "Decision15"
    via: "yes"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "KeyMapper6"
    into: "in"
  - from: "GetStringIndexOf1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "GetStringSubstitution1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode6"
    into: "in1"
  - from: "Decision1"
    via: "no"
    to: "JoinNode7"
    into: "in2"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "KeyMapper6"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "GetStringIndexOf2"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "JoinNode5"
    via: "next"
    to: "GetProductType1"
    into: "in"
  - from: "GetProductType1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
