flow: "ProcessConfigurationParameter"
kind: "process"

entries:
  - id: "StartNode2"
    name: "UpdateConfigurationParameters"
    mode: "private"
    strict: true
    inputs:
      - key: "ConfigurationParameterDefinitions"
        type: "java.lang.Object"
        required: false
      - key: "ConfigurationParameterCtnr"
        type: "com.intershop.component.pmc.capi.pagelet.ConfigurationParameterCtnr"
        required: true
      - key: "FormParameters"
        type: "java.util.Map"
        required: true
      - key: "PreProcessingPipelinesMap"
        type: "java.util.HashMap"
        required: true
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: false
      - key: "Site"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode25"
    name: "RemoveConfigurationParameterValue"
    mode: "private"
    strict: true
    inputs:
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: false
      - key: "ConfigurationParameter"
        type: "com.intershop.component.pmc.capi.pagelet.ConfigurationParameter"
        required: true
  - id: "StartNode26"
    name: "UpdateConfigurationParameterValue"
    mode: "private"
    strict: true
    inputs:
      - key: "ConfigurationParameterDefinition"
        type: "com.intershop.component.pmc.capi.definition.pagelet.ConfigurationParameterDefinition"
        required: true
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: false
      - key: "ConfigurationParameterCtnr"
        type: "com.intershop.component.pmc.capi.pagelet.ConfigurationParameterCtnr"
        required: true
      - key: "ConfigurationParameterValue"
        type: "java.lang.Object"
        required: false
  - id: "StartNode3"
    name: "GetLocales"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode4"
    name: "RevertConfigurationParameters"
    mode: "private"
    strict: true
    inputs:
      - key: "ConfigurationParameterDefinitions"
        type: "java.lang.Object"
        required: false
      - key: "ConfigurationParameterCtnr"
        type: "com.intershop.component.pmc.capi.pagelet.ConfigurationParameterCtnr"
        required: true
      - key: "FormParameters"
        type: "java.util.Map"
        required: true
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: false
  - id: "StartNode5"
    name: "InheritConfigurationParameterValue"
    mode: "private"
    strict: true
    inputs:
      - key: "ConfigurationParameterDefinition"
        type: "com.intershop.component.pmc.capi.definition.pagelet.ConfigurationParameterDefinition"
        required: true
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: false
      - key: "ConfigurationParameterCtnr"
        type: "com.intershop.component.pmc.capi.pagelet.ConfigurationParameterCtnr"
        required: true
  - id: "StartNode6"
    name: "GetProductIndexAttributesByAttributeGroupID"
    mode: "private"
    strict: true
    inputs:
      - key: "AttributeGroupID"
        type: "java.lang.String"
        required: true
      - key: "RepositoryUUID"
        type: "java.lang.String"
        required: true
  - id: "StartNode7"
    name: "GetFileReferences"
    mode: "private"
    strict: true
    inputs:
      - key: "UnitDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: false
      - key: "FileExtension"
        type: "java.lang.String"
        required: false

steps:
  - id: "BrowseDirectory1"
    type: "pipelet"
    ref: "BrowseDirectory"
    config:
      UnitDirectory: "STATIC_CONTENT_DIR"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessConfigurationParameter-InheritConfigurationParameterValue"
  - id: "CallNode14"
    type: "call"
    ref: "ProcessIndexPage-GetProductIndexAttributesByAttributeGroupID"
    bindings:
      Domain: "Repository:Domain"
  - id: "CallNode2"
    type: "call"
  - id: "CallNode27"
    type: "call"
    ref: "ProcessConfigurationParameterCtnrWebForm-ValidateForm"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessConfigurationParameter-InheritConfigurationParameterValue"
    bindings:
      ConfigurationParameterCtnr: "ConfigurationParameterCtnr"
      ConfigurationParameterDefinition: "ConfigurationParameterDefinition"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessConfigurationParameterCtnrWebForm-GetForm"
  - id: "CallNode43"
    type: "call"
    ref: "ProcessConfigurationParameter-UpdateConfigurationParameterValue"
    bindings:
      ConfigurationParameterValue: "ConfigurationParameterCtnrWebForm:Parameter(ConfigurationParameterDefinition:Name):Value"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessConfigurationParameterCtnrWebForm-GetForm"
  - id: "CreateConfigurationParameter1"
    type: "pipelet"
    ref: "CreateConfigurationParameter"
  - id: "DecisionNode11"
    type: "decision"
    condition: "ConfigurationParameterCtnr:ConfigurationParameter(ConfigurationParameterDefinition:QualifiedName)"
  - id: "DecisionNode13"
    type: "decision"
    condition: "ConfigurationParameterCtnr:Author"
  - id: "DecisionNode2"
    type: "decision"
    condition: "PreProcessingPipelinesMap:get(ConfigurationParameterDefinition:Name)"
  - id: "DecisionNode27"
    type: "decision"
    condition: "ConfigurationParameterCtnr:ConfigurationParameter(ConfigurationParameterDefinition:QualifiedName)"
  - id: "DecisionNode3"
    type: "decision"
    condition: "FormParameters:get(FormParameter:RevertFlagQualifiedName)"
  - id: "DecisionNode4"
    type: "decision"
    condition: "ConfigurationParameterCtnrWebForm:Parameter(ConfigurationParameterDefinition:Name):Overloading"
  - id: "DecisionNode5"
    type: "decision"
    condition: "ConfigurationParameterCtnr:ConfigurationParameter(ConfigurationParameterDefinition:QualifiedName)"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "Locales"
        type: "java.util.Iterator"
        guaranteed: false
  - id: "EndNode10"
    type: "end"
    strict: true
  - id: "EndNode13"
    type: "end"
    strict: true
    outputs:
      - key: "Files"
        type: "java.util.Iterator"
        guaranteed: false
  - id: "EndNode20"
    type: "end"
    strict: true
  - id: "EndNode22"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "EndNode5"
    type: "end"
    strict: true
  - id: "EndNode7"
    type: "end"
    strict: true
  - id: "EndNode9"
    type: "end"
    strict: true
    outputs:
      - key: "ProductIndexAttributes"
        type: "java.util.Iterator"
        guaranteed: false
  - id: "FilterFileList1"
    type: "pipelet"
    ref: "FilterFileList"
    bindings:
      Files: "Directory:FileList:Iterator"
      FilteredFiles: "Files"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      UUID: "RepositoryUUID"
  - id: "InheritConfigurationParameterValue2"
    type: "pipelet"
    ref: "InheritConfigurationParameterValue"
    bindings:
      LocaleInformation: "Locale"
      ConfigurationParameter: "ConfigurationParameterCtnr:ConfigurationParameter(ConfigurationParameterDefinition:QualifiedName)"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode36"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ConfigurationParameterCtnrWebForm:Parameter(ConfigurationParameterDefinition:Name)"
      OutValue_1: "FormParameter"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "LoopNode4"
    type: "loop"
  - id: "RemovePageletParameterValue2"
    type: "pipelet"
    ref: "RemoveConfigurationParameterValue"
    bindings:
      LocaleInformation: "Locale"
  - id: "Touch1"
    type: "pipelet"
    ref: "Touch"
    bindings:
      Objects: "null"
      Object: "ConfigurationParameterCtnr"
  - id: "UpdateConfigurationParameterValue1"
    type: "pipelet"
    ref: "UpdateConfigurationParameterValue"
    config:
      updateMode: "overwrite"
    bindings:
      ConfigurationParameter: "ConfigurationParameterCtnr:ConfigurationParameter(ConfigurationParameterDefinition:QualifiedName)"
      LocaleInformation: "Locale"
      Value: "ConfigurationParameterValue"
  - id: "UpdateConfigurationParameterValue2"
    type: "pipelet"
    ref: "UpdateConfigurationParameterValue"
    config:
      updateMode: "overwrite"
    bindings:
      LocaleInformation: "Locale"
      Value: "ConfigurationParameterValue"
  - id: "UpdatePagelet1"
    type: "pipelet"
    ref: "UpdatePagelet"
    bindings:
      Author: "CurrentUser"
      Pagelet: "ConfigurationParameterCtnr"
      DisplayName: "null"
      Locale: "null"
      OnlineFlag: "null"
      ValidFrom: "ConfigurationParameterCtnr:ValidFrom"
      ValidTo: "ConfigurationParameterCtnr:ValidTo"
  - id: "VerifySearchTerm1"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowFuzzySearch: true
      AllowWildcards: "default"
      AllowExclusions: false
      DefaultOperator: "OR"
    bindings:
      UserSearchTerm: "FileExtension"

links:
  - from: "StartNode2"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "CallNode2"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode7"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "CallNode27"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode27"
    via: "Error"
    to: "EndNode5"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "LoopNode4"
    into: "in"
  - from: "CreateConfigurationParameter1"
    via: "next"
    to: "UpdateConfigurationParameterValue2"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "BrowseDirectory1"
    into: "in"
  - from: "DecisionNode27"
    via: "no"
    to: "CreateConfigurationParameter1"
    into: "in"
  - from: "UpdateConfigurationParameterValue2"
    via: "next"
    to: "JoinNode36"
    into: "in1"
  - from: "RemovePageletParameterValue2"
    via: "next"
    to: "EndNode10"
    into: "in"
  - from: "CreateConfigurationParameter1"
    via: "error"
    to: "EndNode22"
    into: "in"
  - from: "UpdateConfigurationParameterValue1"
    via: "next"
    to: "JoinNode36"
    into: "in1"
  - from: "StartNode25"
    via: "next"
    to: "RemovePageletParameterValue2"
    into: "in"
  - from: "DecisionNode27"
    via: "yes"
    to: "UpdateConfigurationParameterValue1"
    into: "in"
  - from: "JoinNode36"
    via: "next"
    to: "EndNode20"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "StartNode26"
    via: "next"
    to: "DecisionNode27"
    into: "in"
  - from: "FilterFileList1"
    via: "next"
    to: "EndNode13"
    into: "in"
  - from: "BrowseDirectory1"
    via: "next"
    to: "VerifySearchTerm1"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "CallNode1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "CallNode43"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "LoopNode4"
    into: "loop"
  - from: "JoinNode2"
    via: "next"
    to: "DecisionNode11"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode11"
    via: "no"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode4"
    via: "yes"
    to: "CallNode43"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "LoopNode2"
    via: "do"
    to: "KeyMapper2"
    into: "in"
  - from: "LoopNode4"
    via: "do"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "InheritConfigurationParameterValue2"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "StartNode4"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode6"
    into: "in1"
  - from: "DetermineLocales1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "InheritConfigurationParameterValue2"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "StartNode5"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode11"
    via: "yes"
    to: "CallNode3"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "LoopNode4"
    via: "next"
    to: "DecisionNode13"
    into: "in"
  - from: "UpdatePagelet1"
    via: "next"
    to: "Touch1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "CallNode27"
    into: "in"
  - from: "DecisionNode13"
    via: "no"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "DecisionNode13"
    via: "yes"
    to: "UpdatePagelet1"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "Touch1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode14"
    via: "next"
    to: "EndNode9"
    into: "in"
  - from: "VerifySearchTerm1"
    via: "next"
    to: "FilterFileList1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "DecisionNode2"
    into: "in"
