flow: "ProcessProductConfigurationValueTemplate"
kind: "process"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      []

steps:
  - id: "EndNode1"
    type: "end"
    strict: true

links:
  - from: "StartNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
