flow: "ProcessCategoryProductFilter"
kind: "process"

entries:
  - id: "StartNode1"
    name: "UpdateProductFilter"
    mode: "private"
    strict: true
    inputs:
      - key: "Category"
        type: "com.intershop.beehive.xcs.capi.catalog.CatalogCategory"
        required: true
      - key: "ProductAssignmentMode"
        type: "java.lang.String"
        required: false
      - key: "Repository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
      - key: "SQDForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        required: true
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: true
  - id: "StartNode12"
    name: "GetProductFilter"
    mode: "private"
    strict: true
    inputs:
      - key: "Category"
        type: "com.intershop.beehive.xcs.capi.catalog.CatalogCategory"
        required: true
      - key: "ProductFilter"
        type: "com.intershop.component.search.capi.querydefinition.SearchQueryDefinition"
        required: false
      - key: "Repository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: true

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessProductFilter-Create"
    bindings:
      Domain: "Repository:Domain"
  - id: "CallNode0"
    type: "call"
    ref: "ProcessSearchQueryDefinitionBySearchIndex-GetCategorySQDByName"
    bindings:
      Name: "Category:SearchQueryDefinitionName"
      InclInactive: "\"(Boolean)false\""
  - id: "CallNode1"
    type: "call"
    ref: "ProcessSearchQueryDefinitionBySearchIndex-GetCategorySQDByName"
    bindings:
      InclInactive: "\"(Boolean)true\""
      SearchQueryDefinition: "ProductFilter"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessSearchQueryDefinitionBySearchIndex-GetCategorySQDByName"
    bindings:
      Name: "SQDName"
      InclInactive: "\"(Boolean)true\""
      SearchQueryDefinition: "ProductFilter"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "SQDForm"
      FormResourceFile: "ShippingMethodForm"
      FormResource: "SearchQueryDefinition"
    bindings:
      CurrentDomain: "CurrentDomain"
      Form: "SQDForm"
  - id: "DecisionNode0"
    type: "decision"
    condition: "Category:SearchQueryDefinitionName"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ProductAssignmentMode"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Category:SearchQueryDefinitionName"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Category:SearchQueryDefinitionName"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Category:SearchQueryDefinitionName"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ProductFilter"
        type: "com.intershop.component.search.capi.querydefinition.SearchQueryDefinition"
        guaranteed: false
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "ProductFilter"
        type: "com.intershop.component.search.capi.querydefinition.SearchQueryDefinition"
        guaranteed: false
      - key: "SQDForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        guaranteed: false
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "JoinNode0"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "KeyMapper0"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Category:UUID"
      OutValue_1: "SQDName"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Category:Name"
      OutValue_1: "Name"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Category:SearchQueryDefinitionName"
      OutValue_1: "Name"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Category:SearchQueryDefinitionName"
      OutValue_1: "SQDName"
  - id: "PrepareSearchQueryDefinitionForm1"
    type: "pipelet"
    ref: "PrepareSearchQueryDefinitionForm"
    bindings:
      Form: "SQDForm"
      SearchQueryDefinition: "ProductFilter"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "ProductFilter"
  - id: "RemoveSearchQueryDefinition0"
    type: "pipelet"
    ref: "RemoveSearchQueryDefinition"
  - id: "UpdateCatalogCategory3"
    type: "pipelet"
    ref: "UpdateCatalogCategory"
    bindings:
      Description: "null"
      DisplayName: "null"
      Id: "null"
      Locale: "null"
      ParentCategory: "null"
      Template: "null"
      SearchQueryDefinitionName: "\"\""
  - id: "UpdateCatalogCategory4"
    type: "pipelet"
    ref: "UpdateCatalogCategory"
    bindings:
      Description: "null"
      DisplayName: "null"
      Id: "null"
      Locale: "null"
      ParentCategory: "null"
      Template: "null"
      SearchQueryDefinitionName: "SQDName"
  - id: "UpdateSearchQueryDefinition2"
    type: "pipelet"
    ref: "UpdateSearchQueryDefinition"
    bindings:
      Name: "SQDName"
      SearchQueryDefinition: "ProductFilter"
      Form: "SQDForm"

links:
  - from: "StartNode12"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "CallNode4"
    via: "NotFound"
    to: "Call1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "UpdateCatalogCategory4"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "KeyMapper2"
    into: "in"
  - from: "UpdateCatalogCategory4"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "UpdateSearchQueryDefinition2"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode1"
    via: "NotFound"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "Call1"
    via: "ERROR"
    to: "JoinNode3"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "UpdateSearchQueryDefinition2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "UpdateCatalogCategory4"
    via: "next"
    to: "UpdateSearchQueryDefinition2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "PrepareSearchQueryDefinitionForm1"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "PrepareSearchQueryDefinitionForm1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "KeyMapper1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "UpdateCatalogCategory4"
    into: "in"
  - from: "CallNode0"
    via: "NotFound"
    to: "JoinNode7"
    into: "in1"
  - from: "CallNode0"
    via: "next"
    to: "RemoveSearchQueryDefinition0"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode0"
    via: "no"
    to: "KeyMapper3"
    into: "in"
  - from: "DecisionNode0"
    via: "yes"
    to: "KeyMapper0"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "DecisionNode0"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode7"
    into: "in1"
  - from: "DecisionNode4"
    via: "yes"
    to: "CallNode0"
    into: "in"
  - from: "JoinNode0"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "UpdateCatalogCategory3"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "KeyMapper0"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "KeyMapper3"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "RemoveSearchQueryDefinition0"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "UpdateCatalogCategory3"
    via: "error"
    to: "EndNode2"
    into: "in"
  - from: "UpdateCatalogCategory3"
    via: "next"
    to: "JoinNode5"
    into: "in1"
