flow: "ProcessApplication"
kind: "process"

entries:
  - id: "StartNode1"
    name: "DeleteApplication"
    mode: "private"
    strict: true
    inputs:
      - key: "Application"
        type: "com.intershop.beehive.core.capi.domain.Application"
        required: true
      - key: "CurrentOrganization"
        type: "com.intershop.component.organization.capi.Organization"
        required: false
  - id: "StartNode2"
    name: "UpdateApplication"
    mode: "private"
    strict: true
    inputs:
      - key: "Application"
        type: "com.intershop.beehive.core.capi.domain.Application"
        required: true
      - key: "Enabled"
        type: "java.lang.Boolean"
        required: false
      - key: "UrlIdentifier"
        type: "java.lang.String"
        required: false
      - key: "DisplayName"
        type: "java.lang.String"
        required: false
      - key: "Description"
        type: "java.lang.String"
        required: false
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: false
      - key: "Default"
        type: "java.lang.Boolean"
        required: false
      - key: "DefaultCurrencyMnemonic"
        type: "java.lang.String"
        required: false
      - key: "CurrencyMnemonics"
        type: "java.util.Collection<java.lang.String>"
        required: false
      - key: "DefaultLocaleID"
        type: "java.lang.String"
        required: false
      - key: "LocaleIDs"
        type: "java.util.Collection<java.lang.String>"
        required: false
  - id: "StartNode3"
    name: "GetApplications"
    mode: "private"
    strict: true
    inputs:
      - key: "ChannelRepository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
      - key: "Pattern"
        type: "java.lang.String"
        required: false
  - id: "StartNode4"
    name: "Create"
    mode: "private"
    strict: true
    inputs:
      - key: "ChannelRepository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
      - key: "AppID"
        type: "java.lang.String"
        required: true
      - key: "UrlIdentifier"
        type: "java.lang.String"
        required: true
      - key: "DisplayName"
        type: "java.lang.String"
        required: true
      - key: "Description"
        type: "java.lang.String"
        required: false
      - key: "Enabled"
        type: "java.lang.Boolean"
        required: false
      - key: "Default"
        type: "java.lang.Boolean"
        required: false
      - key: "DefaultCurrencyMnemonic"
        type: "java.lang.String"
        required: false
      - key: "CurrencyMnemonics"
        type: "java.util.Collection<java.lang.String>"
        required: false
      - key: "DefaultLocaleID"
        type: "java.lang.String"
        required: false
      - key: "LocaleIDs"
        type: "java.util.Collection<java.lang.String>"
        required: false
  - id: "StartNode6"
    name: "Sort"
    mode: "private"
    strict: true
    inputs:
      - key: "Applications"
        type: "java.util.Iterator"
        required: true
      - key: "SortBy"
        type: "java.lang.String"
        required: false
      - key: "SortDirection"
        type: "java.lang.String"
        required: false
  - id: "StartNode7"
    name: "GetAppIDs"
    mode: "private"
    strict: true
    inputs:
      - key: "AppRegistryName"
        type: "java.lang.String"
        required: true

steps:
  - id: "AddObjectToVector3"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "AppIDs"
      Object: "App:ID"
      OutVector: "AppIDs"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessApplication-UpdateApplication"
    bindings:
      Application: "Application"
      Description: "Description"
      DisplayName: "DisplayName"
      Enabled: "Enabled"
      UrlIdentifier: "UrlIdentifier"
      Locale: "CurrentRequest:Locale"
  - id: "CleanupApplicationPromotionAssignments2"
    type: "pipelet"
    ref: "CleanupApplicationPromotionAssignments"
  - id: "CleanupApplicationServiceAssignments1"
    type: "pipelet"
    ref: "CleanupApplicationServiceAssignments"
  - id: "CleanupPreferredPreviewApplicationSettings1"
    type: "pipelet"
    ref: "CleanupPreferredPreviewApplicationSettings"
    bindings:
      Organization: "CurrentOrganization"
  - id: "CreateApplication1"
    type: "pipelet"
    ref: "CreateApplication"
    bindings:
      App: "App"
      OwningDomain: "ChannelRepository:Domain"
      Site: "ChannelRepository:Domain:Site"
      UrlIdentifier: "UrlIdentifier"
  - id: "CreateApplicationDomainRelation1"
    type: "pipelet"
    ref: "CreateApplicationDomainRelation"
    bindings:
      Domain: "Application:Domain"
      RelationName: "\"DefaultRepository\""
  - id: "DecisionNode0"
    type: "decision"
    condition: "UrlIdentifier"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Pattern"
  - id: "DecisionNode10"
    type: "decision"
    condition: "UrlIdentifier"
  - id: "DecisionNode13"
    type: "decision"
    condition: "SortBy"
  - id: "DecisionNode16"
    type: "decision"
    condition: "SortDirection"
  - id: "DecisionNode2"
    type: "decision"
    condition: "SortDirection"
  - id: "DecisionNode3"
    type: "decision"
    condition: "SortBy"
  - id: "DecisionNode5"
    type: "decision"
    condition: "Apps"
  - id: "DecisionNode6"
    type: "decision"
    condition: "SortDirection"
  - id: "DecisionNode7"
    type: "decision"
    condition: "SortDirection"
  - id: "DecisionNode9"
    type: "decision"
    condition: "UrlIdentifier"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ERROR_Delete"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode11"
    type: "end"
    strict: true
  - id: "EndNode12"
    type: "end"
    strict: true
    outputs:
      - key: "AppIDs"
        type: "java.util.Vector"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "ERROR_UrlIdentifier"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "Application"
        type: "com.intershop.beehive.core.capi.domain.Application"
        guaranteed: true
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "Applications"
        type: "java.util.Iterator"
        guaranteed: true
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "Applications"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "SortBy"
        type: "java.lang.String"
        guaranteed: false
      - key: "SortDirection"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode7"
    type: "end"
    strict: true
    outputs:
      - key: "Application"
        type: "com.intershop.beehive.core.capi.domain.Application"
        guaranteed: true
  - id: "EndNode8"
    type: "end"
    strict: true
    outputs:
      - key: "ERROR_UrlIdentifier"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode9"
    type: "end"
    strict: false
  - id: "ExecuteObjectsQuery1"
    type: "pipelet"
    ref: "ExecuteObjectsQuery"
    config:
      QueryName: "apps/SimpleAppSearch"
    bindings:
      Parameters: "QueryParameters"
      Query: "null"
      Connection: "null"
      ErrorCode: "SearchExecutionError"
      SearchResult: "Applications"
  - id: "GetApp1"
    type: "pipelet"
    ref: "GetApp"
    bindings:
      AppID: "AppID"
  - id: "GetApplication1"
    type: "pipelet"
    ref: "GetApplication"
    bindings:
      Site: "Application:Site"
      UrlIdentifier: "UrlIdentifier"
      Application: "anApplication"
  - id: "GetApplications1"
    type: "pipelet"
    ref: "GetApplications"
    bindings:
      Domain: "ChannelRepository:Domain"
      Applications: "ApplicationsCollection"
  - id: "GetApps1"
    type: "pipelet"
    ref: "GetApps"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Request Locale"
  - id: "JoinNode0"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode15"
    type: "join"
  - id: "JoinNode17"
    type: "join"
  - id: "JoinNode20"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationsCollection:Iterator"
      OutValue_1: "Applications"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"This URL identifier already exists.\""
      OutValue_1: "ERROR_UrlIdentifier"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"An application with this URL identifier already exists\""
      OutValue_1: "ERROR_UrlIdentifier"
  - id: "LoopNode2"
    type: "loop"
  - id: "RemoveApplication2"
    type: "pipelet"
    ref: "RemoveApplication"
    bindings:
      Application: "Application"
  - id: "RemoveDictionaryValue0"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "UrlIdentifier"
  - id: "SortIteratorByComparator1"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingAttribute: "AppID"
      DefaultSortingOrder: true
    bindings:
      Iterator: "Applications"
      SortedIterator: "Applications"
  - id: "SortIteratorByComparator2"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingAttribute: "AppID"
      DefaultSortingOrder: false
    bindings:
      Iterator: "Applications"
      SortedIterator: "Applications"
  - id: "SortIteratorByComparator3"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingAttribute: "DisplayName"
      DefaultSortingOrder: true
    bindings:
      Iterator: "Applications"
      SortedIterator: "Applications"
  - id: "SortIteratorByComparator4"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingAttribute: "DisplayName"
      DefaultSortingOrder: false
    bindings:
      Iterator: "Applications"
      SortedIterator: "Applications"
  - id: "Text0"
    type: "text"
  - id: "TextNode3"
    type: "text"
  - id: "TextNode4"
    type: "text"
  - id: "UpdateApplication1"
    type: "pipelet"
    ref: "UpdateApplication"
  - id: "UpdateDictionary1"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "ChannelRepositoryDomain"
      Name_02: "SimpleSearchExpression"
      Name_03: "LocaleID"
    bindings:
      InDictionary: "QueryParameters"
      Value_01: "ChannelRepository:Domain"
      Value_03: "Locale:LocaleID"
      Value_02: "SimpleSearchExpression"
      OutDictionary: "QueryParameters"
  - id: "VerifySearchTerm1"
    type: "pipelet"
    ref: "VerifySearchTerm"
    bindings:
      UserSearchTerm: "Pattern"
      SearchExpression: "SimpleSearchExpression"
      ErrorCode: "SearchTermError"

links:
  - from: "AddObjectToVector3"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "CallNode1"
    via: "ERROR"
    to: "JoinNode7"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "CleanupApplicationPromotionAssignments2"
    via: "next"
    to: "CleanupApplicationServiceAssignments1"
    into: "in"
  - from: "CleanupApplicationServiceAssignments1"
    via: "next"
    to: "RemoveApplication2"
    into: "in"
  - from: "CleanupPreferredPreviewApplicationSettings1"
    via: "next"
    to: "CleanupApplicationPromotionAssignments2"
    into: "in"
  - from: "CreateApplication1"
    via: "error"
    to: "KeyMapper3"
    into: "in"
  - from: "CreateApplication1"
    via: "next"
    to: "CreateApplicationDomainRelation1"
    into: "in"
  - from: "CreateApplicationDomainRelation1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "DecisionNode0"
    via: "no"
    to: "DecisionNode10"
    into: "in"
  - from: "DecisionNode0"
    via: "yes"
    to: "RemoveDictionaryValue0"
    into: "in"
  - from: "DecisionNode10"
    via: "no"
    to: "JoinNode10"
    into: "in1"
  - from: "DecisionNode10"
    via: "yes"
    to: "GetApplication1"
    into: "in"
  - from: "DecisionNode13"
    via: "no"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode13"
    via: "yes"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode16"
    via: "no"
    to: "JoinNode17"
    into: "in1"
  - from: "DecisionNode16"
    via: "yes"
    to: "SortIteratorByComparator4"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "GetApplications1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "VerifySearchTerm1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "DecisionNode6"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "SortIteratorByComparator1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode15"
    into: "in1"
  - from: "DecisionNode3"
    via: "yes"
    to: "DecisionNode7"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "EndNode11"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "LoopNode2"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode20"
    into: "in1"
  - from: "DecisionNode6"
    via: "yes"
    to: "SortIteratorByComparator2"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "DecisionNode16"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "SortIteratorByComparator3"
    into: "in"
  - from: "DecisionNode9"
    via: "no"
    to: "JoinNode0"
    into: "in1"
  - from: "DecisionNode9"
    via: "yes"
    to: "DecisionNode0"
    into: "in"
  - from: "ExecuteObjectsQuery1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "ExecuteObjectsQuery1"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "GetApp1"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "GetApp1"
    via: "next"
    to: "CreateApplication1"
    into: "in"
  - from: "GetApplication1"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "GetApplication1"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "GetApplications1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "GetApps1"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "UpdateDictionary1"
    into: "in"
  - from: "JoinNode0"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode10"
    via: "next"
    to: "UpdateApplication1"
    into: "in"
  - from: "JoinNode13"
    via: "next"
    to: "JoinNode20"
    into: "in1"
  - from: "JoinNode15"
    via: "next"
    to: "JoinNode17"
    into: "in1"
  - from: "JoinNode17"
    via: "next"
    to: "JoinNode13"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode9"
    into: "in"
  - from: "JoinNode20"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "KeyMapper4"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "LoopNode2"
    via: "do"
    to: "AddObjectToVector3"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "EndNode12"
    into: "in"
  - from: "RemoveApplication2"
    via: "error"
    to: "EndNode1"
    into: "in"
  - from: "RemoveApplication2"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "RemoveDictionaryValue0"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "SortIteratorByComparator1"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "SortIteratorByComparator2"
    via: "next"
    to: "JoinNode20"
    into: "in1"
  - from: "SortIteratorByComparator3"
    via: "next"
    to: "JoinNode13"
    into: "in1"
  - from: "SortIteratorByComparator4"
    via: "next"
    to: "JoinNode17"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "CleanupPreferredPreviewApplicationSettings1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode9"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "GetApp1"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "DecisionNode13"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "GetApps1"
    into: "in"
  - from: "UpdateApplication1"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "UpdateApplication1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "UpdateDictionary1"
    via: "next"
    to: "ExecuteObjectsQuery1"
    into: "in"
  - from: "VerifySearchTerm1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "VerifySearchTerm1"
    via: "next"
    to: "GetLocale1"
    into: "in"
