flow: "ProcessPageViewContextCategory"
kind: "process"

entries:
  - id: "StartNode1"
    name: "GetPageletEntryPoint"
    mode: "private"
    strict: true
    inputs:
      - key: "ViewContext"
        type: "com.intershop.component.pmc.capi.viewcontext.ViewContext"
        required: true
      - key: "CategoryBO"
        type: "com.intershop.component.catalog.capi.CatalogCategoryBO"
        required: true
      - key: "ListNavigationVO"
        type: "java.lang.Object"
        required: false

steps:
  - id: "DecisionNode1"
    type: "decision"
    condition: "CategoryBO:SubCategories(CurrentUser,CurrentOrganization):Empty"
  - id: "DecisionNode10"
    type: "decision"
    condition: "ListNavigationVO:NonCategoryFilterSelected"
  - id: "DecisionNode9"
    type: "decision"
    condition: "ListNavigationVO"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "PageletEntryPoint"
        type: "com.intershop.component.pmc.capi.pagelet.PageletEntryPoint"
        guaranteed: true
  - id: "EndNode18"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "GetPageletEntryPointByViewContext1"
    type: "pipelet"
    ref: "GetPageletEntryPointByViewContext"
    config:
      Strategy: "Category"
    bindings:
      Site: "CurrentDomain:Site"
      Domain: "Repository:RepositoryDomain"
  - id: "GetValuesFromRequest1"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "Application"
    bindings:
      Key: "\"CurrentOrganization\""
      Namespace: "null"
  - id: "GetValuesFromRequest3"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "ApplicationRepository"
    bindings:
      Namespace: "null"
      Key: "null"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ViewContextInclusionName"
      Value: "pageCategory"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ViewContextInclusionName"
      Value: "pageFamily"

links:
  - from: "DecisionNode10"
    via: "yes"
    to: "JoinNode10"
    into: "in3"
  - from: "GetPageletEntryPointByViewContext1"
    via: "error"
    to: "EndNode2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "GetPageletEntryPointByViewContext1"
    into: "in"
  - from: "GetPageletEntryPointByViewContext1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "GetValuesFromRequest3"
    via: "error"
    to: "EndNode18"
    into: "in"
  - from: "DecisionNode9"
    via: "no"
    to: "DecisionNode10"
    into: "in"
  - from: "DecisionNode10"
    via: "no"
    to: "JoinNode9"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "GetValuesFromRequest3"
    into: "in"
  - from: "GetValuesFromRequest3"
    via: "next"
    to: "GetValuesFromRequest1"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "GetValuesFromRequest1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode9"
    via: "yes"
    to: "JoinNode10"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode9"
    into: "in2"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode9"
    via: "next"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "DecisionNode9"
    into: "in"
