flow: "ProcessRemoveContentSharing"
kind: "process"

entries:
  - id: "Start3"
    name: "Process"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Init"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "End5"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "ExecuteUpdateQuery1"
    type: "pipelet"
    ref: "ExecuteUpdateQuery"
    config:
      QueryName: "content/RemovePageletLabelAssignments"
    bindings:
      Parameters: "QueryParameters"
  - id: "ExecuteUpdateQuery2"
    type: "pipelet"
    ref: "ExecuteUpdateQuery"
    config:
      QueryName: "content/RemoveSlotPageletAssignments"
    bindings:
      ParameterValue_01: "ChannelRepository"
      ParameterValue_02: "MasterRepository"
      ParameterValue_03: "Organization"
      Parameters: "QueryParameters"
  - id: "ExecuteUpdateQuery3"
    type: "pipelet"
    ref: "ExecuteUpdateQuery"
    config:
      QueryName: "content/RemovePageletEntryPointRelation"
    bindings:
      ParameterValue_01: "ChannelRepository"
      ParameterValue_02: "MasterRepository"
      ParameterValue_03: "Organization"
      Parameters: "QueryParameters"
  - id: "ExecuteUpdateQuery4"
    type: "pipelet"
    ref: "ExecuteUpdateQuery"
    config:
      QueryName: "content/RemovePageletEntryPointRedirectAction"
    bindings:
      Parameters: "QueryParameters"
  - id: "GetRepositoriesContainingSharedRepository2"
    type: "pipelet"
    ref: "GetRepositoriesContainingSharedRepository"
    bindings:
      SharingRepository: "OwningRepository"
      SharingOrganization: "null"
      SharedRepository: "SharedMasterRepository"
      Repositories: "RepositoriesWithProxy"
  - id: "GetRepositoryByUUID2"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      UUID: "RepositoryUUID"
      Repository: "OwningRepository"
  - id: "GetRepositoryByUUID3"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      UUID: "SharedMasterRepositoryUUID"
      Repository: "SharedMasterRepository"
  - id: "Loop1"
    type: "loop"
  - id: "LoopNode1"
    type: "loop"
  - id: "RefreshCache1"
    type: "pipelet"
    ref: "RefreshCache"
    config:
      PersistentClassName_0: "com.intershop.component.mvc.internal.catalog.RepositoryPO"
      PersistentClassName_1: "com.intershop.component.pmc.internal.pagelet.SlotPageletAssignmentPO"
      PersistentClassName_2: "com.intershop.component.pmc.internal.pagelet.SlotPO"
  - id: "UpdateContentSharingHelperCache1"
    type: "pipelet"
    ref: "UpdateContentSharingHelperCache"
    bindings:
      Repositories: "RepositoriesWithProxy"
  - id: "UpdateDictionary1"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "OwningRepository"
      Name_02: "SharedMasterRepository"
    bindings:
      Value_01: "RepositoryWithProxy"
      Value_02: "SharedMasterRepository"
      OutDictionary: "QueryParameters"

links:
  - from: "ExecuteUpdateQuery3"
    via: "next"
    to: "ExecuteUpdateQuery4"
    into: "in"
  - from: "GetRepositoryByUUID3"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "UpdateDictionary1"
    into: "in"
  - from: "UpdateDictionary1"
    via: "next"
    to: "ExecuteUpdateQuery1"
    into: "in"
  - from: "ExecuteUpdateQuery1"
    via: "next"
    to: "ExecuteUpdateQuery2"
    into: "in"
  - from: "ExecuteUpdateQuery4"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "UpdateContentSharingHelperCache1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "ExecuteUpdateQuery2"
    via: "next"
    to: "ExecuteUpdateQuery3"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetRepositoryByUUID2"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "RefreshCache1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetRepositoryByUUID3"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "RefreshCache1"
    via: "next"
    to: "End5"
    into: "in"
  - from: "GetRepositoriesContainingSharedRepository2"
    via: "next"
    to: "UpdateContentSharingHelperCache1"
    into: "in"
  - from: "GetRepositoryByUUID2"
    via: "next"
    to: "GetRepositoriesContainingSharedRepository2"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "Loop1"
    into: "loop"
