flow: "ProcessOrderRequiredAttributes"
kind: "process"

entries:
  - id: "Start1"
    name: "CopyReqProductsAttributes"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "CopyReqProductsAttributesByAttributeGroup"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CopyCategoryAttributeToLineItem1"
    type: "pipelet"
    ref: "CopyCategoryAttributeToLineItem"
    config:
      DefaultAttributeName: "ExcludeFromShipping"
    bindings:
      LineItem: "NewProductLineItem"
      CatalogCategory: "ServiceTypeCategory"
  - id: "CopyCategoryAttributeToLineItem2"
    type: "pipelet"
    ref: "CopyCategoryAttributeToLineItem"
    config:
      DefaultAttributeName: "ExcludeFromShipping"
    bindings:
      LineItem: "NewProductLineItem"
      CatalogCategory: "ServiceTypeCategory"
  - id: "CopyProductAttributeToBundledProductLineItem1"
    type: "pipelet"
    ref: "CopyProductAttributeToBundledProductLineItem"
    bindings:
      AttributeName: "OrderRequiredAttributeDescriptor:ID"
      LineItem: "NewBundledProductLineItem"
      Product: "NewBundledProduct"
  - id: "CopyProductAttributeToLineItem1"
    type: "pipelet"
    ref: "CopyProductAttributeToLineItem"
    bindings:
      AttributeName: "OrderRequiredAttributeName"
      LineItem: "NewProductLineItem"
      Product: "NewProduct"
  - id: "CopyProductAttributeToLineItem2"
    type: "pipelet"
    ref: "CopyProductAttributeToLineItem"
    bindings:
      AttributeName: "OrderRequiredAttributeDescriptor:ID"
      LineItem: "NewProductLineItem"
      Product: "NewProduct"
  - id: "CopyProductIdentifiers1"
    type: "pipelet"
    ref: "CopyProductIdentifiers"
    bindings:
      Source: "NewProduct"
      Target: "NewProductLineItem"
  - id: "CopyProductIdentifiers2"
    type: "pipelet"
    ref: "CopyProductIdentifiers"
    config:
      DefaultIdentifierType: "SellerID"
    bindings:
      Source: "NewProduct"
      Target: "NewProductLineItem"
  - id: "CopyProductIdentifiers3"
    type: "pipelet"
    ref: "CopyProductIdentifiers"
    bindings:
      Source: "NewProduct"
      Target: "NewProductLineItem"
  - id: "CopyProductIdentifiers4"
    type: "pipelet"
    ref: "CopyProductIdentifiers"
    config:
      DefaultIdentifierType: "SellerID"
    bindings:
      Source: "NewProduct"
      Target: "NewProductLineItem"
  - id: "CopyProductIdentifiers5"
    type: "pipelet"
    ref: "CopyProductIdentifiers"
    bindings:
      Source: "NewBundledProduct"
      Target: "NewBundledProductLineItem"
  - id: "CopyProductIdentifiers6"
    type: "pipelet"
    ref: "CopyProductIdentifiers"
    config:
      DefaultIdentifierType: "SellerID"
    bindings:
      Source: "NewBundledProduct"
      Target: "NewBundledProductLineItem"
  - id: "CopyProductIdentifiers7"
    type: "pipelet"
    ref: "CopyProductIdentifiers"
    bindings:
      Source: "NewBundledProduct"
      Target: "NewBundledProductLineItem"
  - id: "CopyProductIdentifiers8"
    type: "pipelet"
    ref: "CopyProductIdentifiers"
    config:
      DefaultIdentifierType: "SellerID"
    bindings:
      Source: "NewBundledProduct"
      Target: "NewBundledProductLineItem"
  - id: "CopyProductNativeAttributesToLineItem1"
    type: "pipelet"
    ref: "CopyProductNativeAttributesToLineItem"
    config:
      NativeAttributeNames: "TypeCode,Image,Thumbnail,Unit,Template,SKU,Online,ManufacturerName,ManufacturerSKU,MinOrderQuantityValue,PriceQuantityValue,StepQuantityValue"
    bindings:
      AttributeGroup: "OrderRequiredAttributeGroup"
      LineItem: "NewProductLineItem"
      Product: "NewProduct"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ServiceTypeCategory:ExcludeFromShipping"
  - id: "DecisionNode2"
    type: "decision"
    condition: "NewProduct:ProductMaster"
  - id: "DecisionNode3"
    type: "decision"
    condition: "ServiceTypeCategory:ExcludeFromShipping"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "GetAttributeGroupByID1"
    type: "pipelet"
    ref: "GetAttributeGroupByID"
    bindings:
      ID: "\"ORDER_REQUIRED_ATTRIBUTES\""
      AttributeGroup: "OrderRequiredAttributeGroup"
  - id: "GetOrderRequiredAttributes1"
    type: "pipelet"
    ref: "GetOrderRequiredAttributes"
    bindings:
      AttributeNames: "OrderRequiredAttributeNames"
      Domain: "Organization:OwningDomain"
  - id: "GetProductByProductRef1"
    type: "pipelet"
    ref: "GetProductByProductRef"
    bindings:
      ProductRefID: "null"
      ProductRefIDs: "null"
      ProductRefs: "null"
      ProductRef: "NewProductLineItem:OfferProductRef"
      Product: "NewProduct"
      Products: "null"
      ProductsHash: "null"
  - id: "GetProductByProductRef2"
    type: "pipelet"
    ref: "GetProductByProductRef"
    bindings:
      ProductRefID: "null"
      ProductRefIDs: "null"
      ProductRefs: "null"
      ProductRef: "NewProductLineItem:OfferProductRef"
      Product: "NewProduct"
      Products: "null"
      ProductsHash: "null"
  - id: "GetProductByProductRef3"
    type: "pipelet"
    ref: "GetProductByProductRef"
    bindings:
      ProductRefID: "null"
      ProductRefIDs: "null"
      ProductRefs: "null"
      ProductRef: "NewBundledProductLineItem:OfferProductRef"
      Product: "NewBundledProduct"
      Products: "null"
      ProductsHash: "null"
  - id: "GetProductByProductRef4"
    type: "pipelet"
    ref: "GetProductByProductRef"
    bindings:
      ProductRefID: "null"
      ProductRefIDs: "null"
      ProductRefs: "null"
      ProductRef: "NewBundledProductLineItem:OfferProductRef"
      Product: "NewBundledProduct"
      Products: "null"
      ProductsHash: "null"
  - id: "GetProductServiceType1"
    type: "pipelet"
    ref: "GetProductServiceType"
    bindings:
      Product: "NewProduct"
  - id: "GetProductServiceType2"
    type: "pipelet"
    ref: "GetProductServiceType"
    bindings:
      Product: "NewProduct"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "Loop1"
    type: "loop"
  - id: "Loop2"
    type: "loop"
  - id: "Loop3"
    type: "loop"
  - id: "Loop4"
    type: "loop"
  - id: "Loop5"
    type: "loop"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "LoopNode3"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "CopyProductAttributeToLineItem"
    bindings:
      AttributeName: "VVA:Name"
      LineItem: "NewProductLineItem"
      Product: "NewProduct"

links:
  - from: "Loop3"
    via: "next"
    to: "End1"
    into: "in"
  - from: "GetOrderRequiredAttributes1"
    via: "next"
    to: "Loop3"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "LoopNode1"
    into: "in"
  - from: "Loop4"
    via: "do"
    to: "CopyProductAttributeToLineItem2"
    into: "in"
  - from: "CopyProductIdentifiers1"
    via: "next"
    to: "GetProductServiceType1"
    into: "in"
  - from: "GetAttributeGroupByID1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "CopyProductIdentifiers2"
    via: "next"
    to: "CopyProductIdentifiers1"
    into: "in"
  - from: "Loop3"
    via: "do"
    to: "GetProductByProductRef1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "GetAttributeGroupByID1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "LoopNode1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "GetOrderRequiredAttributes1"
    into: "in"
  - from: "GetProductByProductRef2"
    via: "next"
    to: "GetProductServiceType2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Loop1"
    via: "do"
    to: "GetProductByProductRef2"
    into: "in"
  - from: "GetProductServiceType1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CopyProductAttributeToLineItem2"
    via: "next"
    to: "Loop4"
    into: "loop"
  - from: "LoopNode1"
    via: "do"
    to: "Pipelet1"
    into: "in"
  - from: "CopyProductIdentifiers4"
    via: "next"
    to: "CopyProductIdentifiers3"
    into: "in"
  - from: "GetProductByProductRef3"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "Loop1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "GetProductByProductRef1"
    via: "next"
    to: "CopyProductIdentifiers2"
    into: "in"
  - from: "GetAttributeGroupByID1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode4"
    into: "in2"
  - from: "GetProductByProductRef2"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "Loop5"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "CopyProductIdentifiers6"
    via: "next"
    to: "CopyProductIdentifiers5"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "GetProductByProductRef3"
    into: "in"
  - from: "GetProductByProductRef3"
    via: "next"
    to: "CopyProductIdentifiers6"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "Loop4"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "LoopNode3"
    via: "do"
    to: "GetProductByProductRef4"
    into: "in"
  - from: "Loop2"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "CopyProductIdentifiers8"
    via: "next"
    to: "CopyProductIdentifiers7"
    into: "in"
  - from: "GetProductByProductRef4"
    via: "next"
    to: "CopyProductIdentifiers8"
    into: "in"
  - from: "CopyProductIdentifiers7"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "GetProductByProductRef1"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "LoopNode3"
    via: "next"
    to: "Loop2"
    into: "in"
  - from: "Loop5"
    via: "do"
    to: "CopyProductAttributeToBundledProductLineItem1"
    into: "in"
  - from: "CopyProductAttributeToBundledProductLineItem1"
    via: "next"
    to: "Loop5"
    into: "loop"
  - from: "CopyProductIdentifiers5"
    via: "next"
    to: "Loop5"
    into: "in"
  - from: "Loop4"
    via: "next"
    to: "CopyProductNativeAttributesToLineItem1"
    into: "in"
  - from: "GetProductByProductRef4"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "CopyProductNativeAttributesToLineItem1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode6"
    into: "in2"
  - from: "CopyCategoryAttributeToLineItem1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "CopyCategoryAttributeToLineItem1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "GetProductServiceType2"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "CopyCategoryAttributeToLineItem2"
    into: "in"
  - from: "CopyCategoryAttributeToLineItem2"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode7"
    into: "in2"
  - from: "JoinNode7"
    via: "next"
    to: "CopyProductIdentifiers4"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Loop3"
    into: "loop"
  - from: "Loop2"
    via: "do"
    to: "CopyProductAttributeToLineItem1"
    into: "in"
  - from: "CopyProductAttributeToLineItem1"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "CopyProductIdentifiers3"
    via: "next"
    to: "LoopNode2"
    into: "in"
