flow: "ProcessConfigurationPanelWebform"
kind: "process"

entries:
  - id: "StartNode1"
    name: "Create"
    mode: "private"
    strict: true
    inputs:
      - key: "ApplicationBO"
        type: "com.intershop.component.application.capi.ApplicationBO"
        required: true
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: true
      - key: "PreviewContextBO"
        type: "com.intershop.component.preview.capi.context.PreviewContextBO"
        required: false
      - key: "ConfigurationAttributeMap"
        type: "java.util.Map<String,String>"
        required: false
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      - key: "PreviewContextBO"
        type: "com.intershop.component.preview.capi.context.PreviewContextBO"
        required: true
      - key: "PreviewWebform"
        type: "com.intershop.beehive.core.capi.webform.Form"
        required: true

steps:
  - id: "AddFormParameterDefinition1"
    type: "pipelet"
    ref: "AddFormParameterDefinition"
    config:
      Type: "java.lang.Boolean"
      Optional: true
      Name: "PreviewSummaryVisible"
      MessageID: "PreviewSummaryVisible"
    bindings:
      Form: "PreviewWebform"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessPreviewContext-Create"
    bindings:
      PreviewContextID: "CurrentSession:SessionID"
      ConfigurationAttributeMap: "ConfigurationAttributeMap"
      ApplicationBO: "ApplicationBO"
  - id: "CreateConfigurationPanelWebform1"
    type: "pipelet"
    ref: "CreateConfigurationPanelWebform"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PreviewContextBO"
  - id: "DecisionNode2"
    type: "decision"
    condition: "PreviewWebform:PreviewSummaryVisible:Value"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "PreviewWebform"
        type: "com.intershop.beehive.core.capi.webform.Form"
        guaranteed: true
      - key: "PreviewContextBO"
        type: "com.intershop.component.preview.capi.context.PreviewContextBO"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "PreviewWebform"
        type: "com.intershop.beehive.core.capi.webform.Form"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "ERROR_CODE"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "ExchangeSessionObject1"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "PreviewSummaryVisible"
    bindings:
      SessionObjectName: "null"
      TargetSession: "null"
      TargetSessionDomain: "null"
      TargetSessionID: "null"
      SaveObject: "PreviewSummaryVisible"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "ERROR_CODE"
      InValue_1: "\"ErrorCreateWebform\""
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "ERROR_CODE"
      InValue_1: "\"ErrorGetPreviewExtension\""
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"(Boolean)false\""
      OutValue_1: "PreviewSummaryVisible"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"(Boolean)true\""
      OutValue_1: "PreviewSummaryVisible"
  - id: "ValidateConfigurationPanelWebform1"
    type: "pipelet"
    ref: "ValidateConfigurationPanelWebform"

links:
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode1"
    into: "in2"
  - from: "DecisionNode2"
    via: "yes"
    to: "KeyMapper4"
    into: "in"
  - from: "ExchangeSessionObject1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "KeyMapper3"
    into: "in"
  - from: "ValidateConfigurationPanelWebform1"
    via: "error"
    to: "EndNode4"
    into: "in"
  - from: "CreateConfigurationPanelWebform1"
    via: "error"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "KeyMapper4"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CreateConfigurationPanelWebform1"
    via: "next"
    to: "AddFormParameterDefinition1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "ExchangeSessionObject1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "AddFormParameterDefinition1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "ValidateConfigurationPanelWebform1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "ValidateConfigurationPanelWebform1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "CreateConfigurationPanelWebform1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "ERROR"
    to: "KeyMapper2"
    into: "in"
