flow: "ProcessLocalizationImpex"
kind: "job"

entries:
  - id: "StartNode1"
    name: "Validate"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Export"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Import"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessImpexJob-Finish"
  - id: "Call6"
    type: "call"
    ref: "ProcessImpexJob-Finish"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ExportedFile"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "EndNode5"
    type: "end"
    strict: false
  - id: "EndNode6"
    type: "end"
    strict: false
  - id: "ExecuteLocalizationExport1"
    type: "pipelet"
    ref: "ExecuteLocalizationExport"
    bindings:
      ModifiedLocalesIterator: "Pageable"
  - id: "ExecuteLocalizationImport1"
    type: "pipelet"
    ref: "ExecuteLocalizationImport"
    bindings:
      ModifiedLocalesIterator: "Pageable"
  - id: "GetDomainByUUID1"
    type: "pipelet"
    ref: "GetDomainByUUID"
    bindings:
      DomainUUID: "JobConfiguration:LocalizationDomainUUID"
  - id: "GetDomainByUUID2"
    type: "pipelet"
    ref: "GetDomainByUUID"
    bindings:
      DomainUUID: "JobConfiguration:LocalizationDomainUUID"
  - id: "GetDomainByUUID3"
    type: "pipelet"
    ref: "GetDomainByUUID"
    bindings:
      DomainUUID: "JobConfiguration:LocalizationDomainUUID"
  - id: "GetJobConfiguration1"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "GetJobConfiguration2"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "GetJobConfiguration3"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
  - id: "GetPageable2"
    type: "pipelet"
    ref: "GetPageable"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DeserializeFromString"
    bindings:
      SerializedValue: "LocalizationContextSerial"
      DeserializedObject: "LocalizationContext"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "DeserializeFromString"
    bindings:
      SerializedValue: "LocalizationContextSerial"
      DeserializedObject: "LocalizationContext"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "FireReloadLocalizationEvent"
  - id: "RemoveCustomAttribute1"
    type: "pipelet"
    ref: "RemoveCustomAttribute"
    config:
      DefaultAttributeName: "ValidationError"
    bindings:
      ExtensibleObject: "JobConfiguration"
  - id: "UpdateCustomAttributes1"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "SelectedFile"
      Attribute_1_Type: "String"
    bindings:
      Attribute_1_Value: "ExportedFile:Name"
      ExtensibleObject: "JobConfiguration"
  - id: "UpdateCustomAttributes2"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Type: "String"
      Attribute_1_Name: "ValidationError"
    bindings:
      ExtensibleObject: "JobConfiguration"
      Attribute_1_Value: "Error"
  - id: "UpdateCustomAttributes3"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Type: "Integer"
      Attribute_1_Name: "LocalesNumber"
      Attribute_2_Name: "EntriesNumber"
      Attribute_2_Type: "Integer"
    bindings:
      ExtensibleObject: "JobConfiguration"
      Attribute_1_Value: "VerificationResult:TargetLanguages:Size"
      Attribute_2_Value: "VerificationResult:EntriesNumber"
  - id: "UpdateCustomAttributes4"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Type: "String"
      Attribute_1_Name: "XLIFFError"
    bindings:
      ExtensibleObject: "JobConfiguration"
      Attribute_1_Value: "Error"
  - id: "UpdateCustomAttributes5"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Type: "String"
      Attribute_1_Name: "XLIFFError"
    bindings:
      ExtensibleObject: "JobConfiguration"
      Attribute_1_Value: "Error"
  - id: "XLIFFValidate1"
    type: "pipelet"
    ref: "XLIFFValidate"

links:
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetJobConfiguration1"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "GetJobConfiguration1"
    via: "next"
    to: "GetDomainByUUID2"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "JoinNode10"
    into: "in2"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "UpdateCustomAttributes1"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode9"
    into: "in2"
  - from: "ExecuteLocalizationExport1"
    via: "error"
    to: "UpdateCustomAttributes4"
    into: "in"
  - from: "GetDomainByUUID1"
    via: "next"
    to: "XLIFFValidate1"
    into: "in"
  - from: "GetJobConfiguration2"
    via: "next"
    to: "GetDomainByUUID1"
    into: "in"
  - from: "UpdateCustomAttributes3"
    via: "next"
    to: "RemoveCustomAttribute1"
    into: "in"
  - from: "GetDomainByUUID2"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "StartNode1"
    via: "next"
    to: "GetJobConfiguration2"
    into: "in"
  - from: "GetDomainByUUID1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "GetJobConfiguration2"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "UpdateCustomAttributes2"
    via: "next"
    to: "JoinNode4"
    into: "in2"
  - from: "XLIFFValidate1"
    via: "error"
    to: "UpdateCustomAttributes2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "XLIFFValidate1"
    via: "next"
    to: "UpdateCustomAttributes3"
    into: "in"
  - from: "GetJobConfiguration3"
    via: "next"
    to: "GetDomainByUUID3"
    into: "in"
  - from: "RemoveCustomAttribute1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "GetDomainByUUID2"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetJobConfiguration3"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "GetDomainByUUID3"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "GetJobConfiguration3"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "GetPageable2"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "GetDomainByUUID3"
    via: "next"
    to: "GetPageable2"
    into: "in"
  - from: "Pipelet2"
    via: "error"
    to: "JoinNode11"
    into: "in2"
  - from: "GetPageable1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode9"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "Pipelet5"
    via: "error"
    to: "JoinNode12"
    into: "in2"
  - from: "Call6"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "ExecuteLocalizationImport1"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "UpdateCustomAttributes4"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "UpdateCustomAttributes5"
    via: "next"
    to: "JoinNode8"
    into: "in2"
  - from: "Pipelet1"
    via: "next"
    to: "ExecuteLocalizationExport1"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetPageable2"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "ExecuteLocalizationImport1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "Pipelet5"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "JoinNode12"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "ExecuteLocalizationExport1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "ExecuteLocalizationImport1"
    via: "error"
    to: "UpdateCustomAttributes5"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "UpdateCustomAttributes1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetJobConfiguration1"
    into: "in"
