flow: "ProcessOrganizationEnterpriseServiceGroup"
kind: "process"

entries:
  - id: "StartNode1"
    name: "CreateServiceIterator"
    mode: "private"
    strict: true
    inputs:
      - key: "ServiceIDsIterator"
        type: "java.util.Iterator"
        required: false

steps:
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "ServiceInformationObjects"
      Iterator: "ServiceInformationsIterator"
      Object: "Service"
      OutVector: "ServiceInformationObjects"
  - id: "AddObjectToVector3"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "null"
      Object: "null"
      OutVector: "ServiceInformationObjects"
      Iterator: "ServiceInformationsIterator"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ServiceIDsIterator"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ServiceIDsIterator"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ServiceInformationsIterator"
        type: "java.util.Iterator"
        guaranteed: true
  - id: "GetServiceByID1"
    type: "pipelet"
    ref: "GetServiceByID"
  - id: "JoinNode1"
    type: "join"
  - id: "LoopNode1"
    type: "loop"

links:
  - from: "DecisionNode1"
    via: "yes"
    to: "DecisionNode2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "AddObjectToVector3"
    into: "in"
  - from: "AddObjectToVector3"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "GetServiceByID1"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "LoopNode1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "GetServiceByID1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "EndNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "EndNode1"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetServiceByID1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
