flow: "ProcessAssignments"
kind: "process"

entries:
  - id: "StartNode1"
    name: "CreateAssignment"
    mode: "private"
    strict: true
    inputs:
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "From"
        type: "java.lang.Object"
        required: false
      - key: "To"
        type: "java.lang.Object"
        required: false
      - key: "AdditionalProperties"
        type: "java.util.Map"
        required: false
      - key: "Site"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode2"
    name: "UpdateAssignment"
    mode: "private"
    strict: true
    inputs:
      - key: "Assignment"
        type: "com.intershop.component.foundation.capi.assignment.Assignment"
        required: true
      - key: "From"
        type: "java.lang.Object"
        required: false
      - key: "To"
        type: "java.lang.Object"
        required: false
      - key: "Site"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "AdditionalProperties"
        type: "java.util.Map<java.lang.String, java.lang.Object>"
        required: false
  - id: "StartNode3"
    name: "HasAssignments"
    mode: "private"
    strict: true
    inputs:
      - key: "ContextObject"
        type: "java.lang.Object"
        required: true
      - key: "Site"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "AssignmentStrategy"
        type: "com.intershop.component.foundation.capi.assignment.AssignmentLookupStrategy"
        required: true
  - id: "StartNode4"
    name: "GetAssignments"
    mode: "private"
    strict: true
    inputs:
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
      - key: "From"
        type: "java.lang.Object"
        required: false
      - key: "To"
        type: "java.lang.Object"
        required: false
      - key: "Site"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
      - key: "AssignmentStrategy"
        type: "com.intershop.component.foundation.capi.assignment.AssignmentStrategy"
        required: true
  - id: "StartNode5"
    name: "GetAssignment"
    mode: "private"
    strict: true
    inputs:
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "From"
        type: "java.lang.Object"
        required: false
      - key: "To"
        type: "java.lang.Object"
        required: false
      - key: "Site"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
      - key: "AssignmentStrategy"
        type: "com.intershop.component.foundation.capi.assignment.AssignmentStrategy"
        required: true
  - id: "StartNode6"
    name: "GetSelectedAssignments"
    mode: "private"
    strict: true
    inputs:
      - key: "SelectedAssignmentUUIDs"
        type: "java.util.Iterator"
        required: true
      - key: "ToObject"
        type: "java.lang.Object"
        required: false
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "FromObject"
        type: "java.lang.Object"
        required: false
      - key: "Site"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "AssignmentStrategy"
        type: "com.intershop.component.foundation.capi.assignment.AssignmentStrategy"
        required: true
  - id: "StartNode9"
    name: "DeleteAssignment"
    mode: "private"
    strict: true
    inputs:
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
      - key: "Assignment"
        type: "com.intershop.component.foundation.capi.assignment.Assignment"
        required: false
      - key: "Site"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "SelectedAssignments"
      Object: "Assignment"
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      OutVector: "SelectedAssignments"
  - id: "CallNode1"
    type: "call"
    ref: "This:GetAssignments"
  - id: "CreateAssignment1"
    type: "pipelet"
    ref: "CreateAssignment"
    config:
      DefaultName_0: "from"
      DefaultName_1: "to"
    bindings:
      AssignmentFactory: "AssignmentStrategy:AssignmentFactory(From,To)"
      Value_0: "From"
      Value_1: "To"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Assignments:Size"
  - id: "DecisionNode2"
    type: "decision"
    condition: "From"
  - id: "DecisionNode3"
    type: "decision"
    condition: "FromObject"
  - id: "DecisionNode4"
    type: "decision"
    condition: "To"
  - id: "DecisionNode5"
    type: "decision"
    condition: "ToObject"
  - id: "DeleteAssignment1"
    type: "pipelet"
    ref: "DeleteAssignment"
    bindings:
      AssignmentFactory: "AssignmentStrategy:AssignmentFactory(Assignment:From,Assignment:To)"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "Assignment"
        type: "com.intershop.component.foundation.capi.assignment.Assignment"
        guaranteed: false
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "UpdatedAssignment"
        type: "com.intershop.component.foundation.capi.assignment.Assignment"
        guaranteed: false
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "Assignments"
        type: "java.util.Collection"
        guaranteed: false
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "EndNode5"
    type: "end"
    strict: true
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "Assignments"
        type: "java.util.Collection"
        guaranteed: false
  - id: "EndNode7"
    type: "end"
    strict: true
    outputs:
      - key: "Assignment"
        type: "java.lang.Object"
        guaranteed: false
  - id: "EndNode8"
    type: "end"
    strict: true
    outputs:
      - key: "SelectedAssignments"
        type: "java.util.Collection"
        guaranteed: false
  - id: "GetAssignmentByUUID1"
    type: "pipelet"
    ref: "GetAssignmentByUUID"
    bindings:
      AssignmentLookup: "AssignmentStrategy:getAssignmentLookupStrategyByFrom(FromObject)"
      UUID: "AssignmentUUID"
  - id: "GetAssignmentByUUID2"
    type: "pipelet"
    ref: "GetAssignmentByUUID"
    bindings:
      AssignmentLookup: "AssignmentStrategy:getAssignmentLookupStrategy(FromObject,ToObject)"
      UUID: "AssignmentUUID"
  - id: "GetAssignmentByUUID3"
    type: "pipelet"
    ref: "GetAssignmentByUUID"
    bindings:
      AssignmentLookup: "AssignmentStrategy:getAssignmentLookupStrategyByTo(ToObject)"
      UUID: "AssignmentUUID"
  - id: "GetAssignmentStrategy1"
    type: "pipelet"
    ref: "GetAssignmentStrategy"
  - id: "GetAssignmentStrategy2"
    type: "pipelet"
    ref: "GetAssignmentStrategy"
    bindings:
      From: "Assignment:From"
      To: "Assignment:To"
  - id: "GetAssignmentStrategy3"
    type: "pipelet"
    ref: "GetAssignmentStrategy"
    bindings:
      From: "Assignment:From"
      To: "Assignment:To"
  - id: "GetAssignments1"
    type: "pipelet"
    ref: "GetAssignments"
    bindings:
      To: "ContextObject"
      AssignmentLookup: "AssignmentStrategy:AssignmentLookupStrategyByTo(ContextObject)"
  - id: "GetAssignments2"
    type: "pipelet"
    ref: "GetAssignments"
    bindings:
      AssignmentLookup: "AssignmentStrategy:AssignmentLookupStrategy(From,To)"
  - id: "GetAssignments3"
    type: "pipelet"
    ref: "GetAssignments"
    bindings:
      AssignmentLookup: "AssignmentStrategy:AssignmentLookupStrategyByTo(To)"
  - id: "GetAssignments4"
    type: "pipelet"
    ref: "GetAssignments"
    bindings:
      AssignmentLookup: "AssignmentStrategy:AssignmentLookupStrategyByFrom(From)"
  - id: "GetFirstElementOfIterator1"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      Iterator: "Assignments:Iterator"
      FirstElement: "Assignment"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "LoopNode1"
    type: "loop"
  - id: "UpdateAssignment1"
    type: "pipelet"
    ref: "UpdateAssignment"
    config:
      DefaultName_0: "from"
      DefaultName_1: "to"
    bindings:
      AssignmentFactory: "AssignmentStrategy:AssignmentFactory(Assignment:From,Assignment:To)"
      Value_0: "From"
      Value_1: "To"

links:
  - from: "StartNode1"
    via: "next"
    to: "GetAssignmentStrategy1"
    into: "in"
  - from: "GetAssignmentByUUID3"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "GetAssignments1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetAssignmentByUUID3"
    via: "error"
    to: "JoinNode8"
    into: "in3"
  - from: "DecisionNode1"
    via: "no"
    to: "EndNode5"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "GetAssignments3"
    into: "in"
  - from: "GetAssignments4"
    via: "next"
    to: "JoinNode6"
    into: "in2"
  - from: "StartNode3"
    via: "next"
    to: "GetAssignments1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetFirstElementOfIterator1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetAssignmentStrategy1"
    via: "next"
    to: "CreateAssignment1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "GetFirstElementOfIterator1"
    into: "in"
  - from: "GetFirstElementOfIterator1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "GetAssignmentByUUID2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "DecisionNode4"
    into: "in"
  - from: "GetAssignments2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "GetAssignments2"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "GetAssignmentByUUID1"
    into: "in"
  - from: "CreateAssignment1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "DecisionNode3"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "GetAssignments4"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "GetAssignmentByUUID3"
    into: "in"
  - from: "GetAssignmentByUUID2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "GetAssignmentByUUID1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "AddObjectToVector1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "GetAssignmentStrategy2"
    via: "next"
    to: "UpdateAssignment1"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "GetAssignments3"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "DecisionNode3"
    via: "yes"
    to: "DecisionNode5"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "GetAssignmentByUUID2"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "GetAssignmentByUUID1"
    via: "error"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode7"
    into: "in2"
  - from: "StartNode2"
    via: "next"
    to: "GetAssignmentStrategy2"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "GetAssignmentStrategy3"
    into: "in"
  - from: "UpdateAssignment1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "DeleteAssignment1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "GetAssignmentStrategy3"
    via: "next"
    to: "DeleteAssignment1"
    into: "in"
