flow: "ProcessChannelCatalog_32"
kind: "process"

entries:
  - id: "Start1"
    name: "BrowseStandardCatalog"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "GetClassificationCatalogs"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "GetAccessRole"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "BrowseeClassCatalog"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "BrowseUNSPSCCatalog"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "GetStandardCatalogs"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "GetSharedCatalogs"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessCatalog-CatalogBrowse"
  - id: "Call10"
    type: "call"
    ref: "GetAssignedProducts-ByCategory"
  - id: "Call11"
    type: "call"
    ref: "GetCategories-ByUNSPSCParent"
  - id: "Call2"
    type: "call"
    ref: "ProcessCatalogSorting-PrepareProductSorting"
  - id: "Call4"
    type: "call"
    ref: "GetAssignedProducts-ByCategory"
  - id: "Call5"
    type: "call"
    ref: "GetCategories-ByEClassParent"
  - id: "Call6"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "Call9"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "CombineIterators1"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Concatenate Iterators"
    bindings:
      Iterator1: "SharedStandardCatalogs"
      Iterator2: "LocalStandardCatalogs"
      Iterator: "StandardCatalogs"
  - id: "CreateAccessRoleID1"
    type: "pipelet"
    ref: "CreateAccessRoleID"
    config:
      DefaultPrefix: "SLD_AR"
      DefaultSeparator: "_"
      DefaultSuffix: "CATALOG_VIEWER"
    bindings:
      AccessRoleID: "UserGroupID"
      TypeCode: "Repository:TypeCode"
  - id: "Decision1"
    type: "decision"
    condition: "CatalogID"
  - id: "Decision4"
    type: "decision"
    condition: "SubCategories:ElementCount"
  - id: "Decision5"
    type: "decision"
    condition: "SubCategories:ElementCount"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Catalog:isProxy"
  - id: "DetermineCatalogCategoriesPath1"
    type: "pipelet"
    ref: "DetermineCatalogCategoriesPath"
  - id: "DetermineCatalogCategoriesPath2"
    type: "pipelet"
    ref: "DetermineCatalogCategoriesPath"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End10"
    type: "end"
    strict: false
  - id: "End11"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "End7"
    type: "end"
    strict: false
  - id: "End8"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "catalog/GetCatalogByDomainIDWithProxyflag"
      Datasource: "default"
      ParameterName_01: "CatalogDomainID"
    bindings:
      PageSize: "null"
      ParameterValue_01: "Catalog:DomainID"
      SearchResult: "SharedCatalogs"
  - id: "ExecutePageableQuery2"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "catalog/GetCatalogByUUIDWithProxyflag"
      Datasource: "default"
      ParameterName_01: "CatalogUUID"
    bindings:
      PageSize: "null"
      SearchResult: "SharedCatalogs"
      ParameterValue_01: "Catalog:UUID"
  - id: "GetCatalog1"
    type: "pipelet"
    ref: "GetCatalog"
    bindings:
      OrganizationDomain: "CurrentChannel:RepositoryDomain"
  - id: "GetCatalogByCategory2"
    type: "pipelet"
    ref: "GetCatalogByCategory"
    bindings:
      CatalogCategory: "Category"
      OwningDomain: "CurrentChannel:RepositoryDomain"
  - id: "GetCatalogs1"
    type: "pipelet"
    ref: "GetCatalogs"
    config:
      CatalogType: "Classification Catalog"
      OnlineOnly: "False"
      ProxyFilter: "ON - Proxy Catalogs only"
    bindings:
      Catalogs: "SharedClassificationCatalogs"
      OrganizationDomain: "CurrentChannel:Domain"
  - id: "GetCatalogs4"
    type: "pipelet"
    ref: "GetCatalogs"
    config:
      CatalogType: "Product Catalog"
      OnlineOnly: "False"
      ProxyFilter: "ON - Proxy Catalogs only"
    bindings:
      Catalogs: "SharedStandardCatalogs"
      OrganizationDomain: "CurrentChannel:Domain"
  - id: "GetCategoryByUUID2"
    type: "pipelet"
    ref: "GetCategoryByUUID"
  - id: "GetCategoryByUUID3"
    type: "pipelet"
    ref: "GetCategoryByUUID"
  - id: "GetCategoryByUUID4"
    type: "pipelet"
    ref: "GetCategoryByUUID"
  - id: "GetPermissionGroupByID1"
    type: "pipelet"
    ref: "GetPermissionGroupByID"
    bindings:
      PermissionGroupID: "UserGroupID"
  - id: "GetUserGroupByID1"
    type: "pipelet"
    ref: "GetUserGroupByID"
    bindings:
      Domain: "Repository:Domain"
      UserGroup: "AccessRole"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "CurrentChannel:RepositoryDomain"
      OutValue_1: "PreferenceDomain"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetCatalogs"
    config:
      CatalogType: "Product Catalog"
      OnlineOnly: "False"
      ProxyFilter: "ON - Exclude Proxy Catalogs"
    bindings:
      Catalogs: "LocalStandardCatalogs"
      OrganizationDomain: "CurrentChannel:Domain"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "GetCatalogs"
    config:
      CatalogType: "Classification Catalog"
      OnlineOnly: "False"
      ProxyFilter: "ON - Exclude Proxy Catalogs"
    bindings:
      Catalogs: "LocalClassificationCatalogs"
      OrganizationDomain: "CurrentChannel:Domain"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Concatenate Iterators"
    bindings:
      Iterator1: "SharedClassificationCatalogs"
      Iterator2: "LocalClassificationCatalogs"
      Iterator: "ClassificationCatalogs"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "DetermineRepositoriesPipeline"
      Value: "DetermineRepositories-SelectedChannel"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "DetermineRepositoriesPipeline"
      Value: "DetermineRepositories-SelectedChannel"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "DetermineRepositoriesPipeline"
      Value: "DetermineRepositories-SelectedChannel"
  - id: "TextNode1"
    type: "text"
  - id: "TextNode2"
    type: "text"

links:
  - from: "Start3"
    via: "next"
    to: "CreateAccessRoleID1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "ExecutePageableQuery2"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "ExecutePageableQuery2"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "DecisionNode1"
    via: "yes"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "DetermineCatalogCategoriesPath1"
    via: "next"
    to: "Decision4"
    into: "in"
  - from: "Decision4"
    via: "yes"
    to: "Join8"
    into: "in1"
  - from: "Call4"
    via: "next"
    to: "Join8"
    into: "in3"
  - from: "Decision4"
    via: "no"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "CreateAccessRoleID1"
    via: "next"
    to: "GetPermissionGroupByID1"
    into: "in"
  - from: "GetCategoryByUUID2"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "DetermineCatalogCategoriesPath1"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "End7"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "GetCategoryByUUID2"
    into: "in"
  - from: "DetermineCatalogCategoriesPath2"
    via: "next"
    to: "Decision5"
    into: "in"
  - from: "Decision5"
    via: "yes"
    to: "Join9"
    into: "in1"
  - from: "Call10"
    via: "next"
    to: "Join9"
    into: "in3"
  - from: "Decision5"
    via: "no"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "Call11"
    via: "next"
    to: "DetermineCatalogCategoriesPath2"
    into: "in"
  - from: "GetPermissionGroupByID1"
    via: "next"
    to: "GetUserGroupByID1"
    into: "in"
  - from: "Join9"
    via: "next"
    to: "End8"
    into: "in"
  - from: "GetCategoryByUUID3"
    via: "next"
    to: "Call11"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "GetCategoryByUUID3"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "GetUserGroupByID1"
    via: "next"
    to: "End4"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "GetCatalogs4"
    into: "in"
  - from: "GetCatalogs4"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "GetCatalogs1"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "CombineIterators1"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "GetCatalogs1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "End11"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "End2"
    into: "in"
  - from: "GetPermissionGroupByID1"
    via: "error"
    to: "Join2"
    into: "in1"
  - from: "Call1"
    via: "ERROR"
    to: "Join3"
    into: "in2"
  - from: "Join1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "GetCategoryByUUID4"
    into: "in"
  - from: "GetCatalog1"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "GetCatalogByCategory2"
    via: "next"
    to: "Join6"
    into: "in3"
  - from: "Join6"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "GetCategoryByUUID4"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "GetCategoryByUUID4"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "GetCatalog1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "GetCatalogByCategory2"
    into: "in"
  - from: "GetUserGroupByID1"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "GetCatalogByCategory2"
    via: "error"
    to: "Join1"
    into: "in3"
  - from: "GetCatalog1"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "End3"
    into: "in"
  - from: "CombineIterators1"
    via: "next"
    to: "End10"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call2"
    into: "in"
