flow: "ProcessCategoryOrProductPage"
kind: "process"

entries:
  - id: "StartNode6"
    name: "DeterminePageEntryPointForSearchResults"
    mode: "private"
    strict: true
    inputs:
      - key: "Products"
        type: "java.util.Iterator<E>"
        required: false
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "SearchIndexResult"
        type: "com.intershop.component.search.capi.SearchResult"
        required: false
      - key: "SearchIndexContentResult"
        type: "com.intershop.component.search.capi.SearchResult"
        required: false

steps:
  - id: "DecisionNode1"
    type: "decision"
    condition: "SearchIndexContentResult"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Products"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Products"
  - id: "DecisionNode4"
    type: "decision"
    condition: "SearchIndexContentResult:Results"
  - id: "DecisionNode5"
    type: "decision"
    condition: "SearchIndexContentResult"
  - id: "DecisionNode6"
    type: "decision"
    condition: "SearchIndexContentResult:Results"
  - id: "DecisionNode7"
    type: "decision"
    condition: "SearchIndexResult"
  - id: "DecisionNode8"
    type: "decision"
    condition: "SearchIndexResult:SpellCorrected"
  - id: "EndNode10"
    type: "end"
    strict: true
    outputs:
      - key: "PageletEntryPoint"
        type: "com.intershop.component.pmc.capi.pagelet.PageletEntryPoint"
        guaranteed: true
  - id: "EndNode11"
    type: "end"
    strict: true
  - id: "EndNode15"
    type: "end"
    strict: true
    outputs:
      - key: "PageletEntryPoint"
        type: "com.intershop.component.pmc.capi.pagelet.PageletEntryPoint"
        guaranteed: true
  - id: "EndNode16"
    type: "end"
    strict: true
  - id: "EndNode17"
    type: "end"
    strict: true
  - id: "EndNode18"
    type: "end"
    strict: true
    outputs:
      - key: "PageletEntryPoint"
        type: "com.intershop.component.pmc.capi.pagelet.PageletEntryPoint"
        guaranteed: true
  - id: "GetPageletEntryPointByID4"
    type: "pipelet"
    ref: "GetPageletEntryPointByID"
    bindings:
      ID: "\"systempage.search.result.pagelet2-systempage.search.result\""
  - id: "GetPageletEntryPointByID5"
    type: "pipelet"
    ref: "GetPageletEntryPointByID"
    bindings:
      ID: "\"systempage.search.noResult.pagelet2-systempage.search.noResult\""
  - id: "GetPageletEntryPointByID9"
    type: "pipelet"
    ref: "GetPageletEntryPointByID"
    bindings:
      ID: "\"systempage.search.didYouMean.pagelet2-systempage.search.didYouMean\""
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"

links:
  - from: "DecisionNode8"
    via: "yes"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "GetPageletEntryPointByID5"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "GetPageletEntryPointByID9"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "DecisionNode6"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "DecisionNode6"
    via: "no"
    to: "GetPageletEntryPointByID9"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "DecisionNode7"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "GetPageletEntryPointByID4"
    via: "next"
    to: "EndNode10"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode1"
    into: "in1"
  - from: "GetPageletEntryPointByID4"
    via: "error"
    to: "EndNode11"
    into: "in"
  - from: "GetPageletEntryPointByID5"
    via: "next"
    to: "EndNode15"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "DecisionNode2"
    into: "in"
  - from: "GetPageletEntryPointByID5"
    via: "error"
    to: "EndNode16"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "JoinNode4"
    into: "in2"
  - from: "DecisionNode8"
    via: "no"
    to: "GetPageletEntryPointByID4"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "DecisionNode8"
    into: "in"
  - from: "GetPageletEntryPointByID9"
    via: "next"
    to: "EndNode18"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "DecisionNode4"
    into: "in"
  - from: "GetPageletEntryPointByID9"
    via: "error"
    to: "EndNode17"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "GetPageletEntryPointByID4"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode3"
    into: "in2"
