flow: "ProcessProductDetails"
kind: "process"

entries:
  - id: "Start3"
    name: "GetProductDetails"
    mode: "private"
    strict: true
    inputs:
      - key: "LocaleID"
        type: "java.lang.String"
        required: false
      - key: "Product"
        type: "com.intershop.beehive.xcs.capi.product.Product"
        required: false
  - id: "StartNode1"
    name: "ProcessGenerateThumbnail"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode17"
    name: "DeterminePrimaryView"
    mode: "private"
    strict: true
    inputs:
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "Product"
        type: "com.intershop.beehive.xcs.capi.product.Product"
        required: false
      - key: "ImageViewBORepository"
        type: "com.intershop.component.image.capi.ImageViewBORepository"
        required: false
  - id: "StartNode2"
    name: "ProcessGenerateProductThumbnail"
    mode: "private"
    strict: true
    inputs:
      - key: "Product"
        type: "com.intershop.beehive.xcs.capi.product.Product"
        required: false
      - key: "Width"
        type: "java.lang.Integer"
        required: false
      - key: "Height"
        type: "java.lang.Integer"
        required: false
      - key: "OrganizationDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "ImageTypeBORepository"
        type: "com.intershop.component.image.capi.ImageTypeBORepository"
        required: true
      - key: "ImageViewBORepository"
        type: "com.intershop.component.image.capi.ImageViewBORepository"
        required: false

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "ImageTypes"
      Object: "Image:ImageType"
      Objects: "null"
      OutVector: "ImageTypes"
  - id: "Call1"
    type: "call"
    ref: "MVCProcessProduct-Start"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessProductDetails-DeterminePrimaryView"
    bindings:
      Domain: "OrganizationDomain"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessImage-GenerateThumbnail"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessImageView-GetOrganizationPrimaryViewID"
    bindings:
      PrimaryImageViewID: "ImageViewID"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessProductSearch-GetProductLinksByProductUUID"
  - id: "CreateImageThumbnail1"
    type: "pipelet"
    ref: "CreateImageThumbnail"
    config:
      height: 100
      OutputMethod: "ServletResponse"
      width: 100
      pagecacheTTL: 0
    bindings:
      Source: "AbsoluteFileName"
  - id: "CreateProductIdentifierLookupHelper1"
    type: "pipelet"
    ref: "CreateProductIdentifierLookupHelper"
    config:
      LookupType: "ProductDomainLookup"
    bindings:
      ProductDomain: "Product:Domain"
  - id: "CreateStringSplitter2"
    type: "pipelet"
    ref: "CreateStringSplitter"
    config:
      Separator: ":"
      Mode: "Last Occurrence"
    bindings:
      Splitter: "ContentURLSplitter"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Product"
  - id: "DecisionNode2"
    type: "decision"
    condition: "FileName"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Product:PrimaryViewID"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Product:ImageReferences"
  - id: "DecisionNode5"
    type: "decision"
    condition: "Image:ImageView:ID"
  - id: "DecisionNode6"
    type: "decision"
    condition: "ImageTypes"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DetermineMatchingImageType1"
    type: "pipelet"
    ref: "DetermineMatchingImageType"
    bindings:
      Height: "\"(Integer)100\""
      Width: "\"(Integer)100\""
      MatchingImageType: "ImageType"
      MatchingImageTypeBO: "ImageType"
      ImageTypeBOs: "ImageTypes"
  - id: "DetermineUnit1"
    type: "pipelet"
    ref: "DetermineUnit"
    bindings:
      Unit: "UnitDomain"
      UnitName: "ContentURLSplitter:Begin(ImageType:Prefix)"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "Locales"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "LookupHelper"
        type: "com.intershop.component.mvc.capi.product.ProductIdentifierLookupHelper"
        guaranteed: false
      - key: "Product"
        type: "com.intershop.beehive.xcs.capi.product.Product"
        guaranteed: false
      - key: "ProductLinks"
        type: "com.intershop.beehive.core.capi.paging.PageableIterator"
        guaranteed: false
      - key: "AdditionalContentMap"
        type: "java.util.HashMap"
        guaranteed: false
      - key: "Currencies"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        guaranteed: false
      - key: "CustomAttributeNames"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "CustomAttributeValues"
        type: "java.util.HashMap"
        guaranteed: false
      - key: "CustomAttributes"
        type: "java.util.Iterator"
        guaranteed: false
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorStatus"
        type: "java.lang.String"
        guaranteed: false
      - key: "ProductLinkSearchError"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "PrimaryView"
        type: "com.intershop.component.image.capi.ImageViewBO"
        guaranteed: true
  - id: "EndNode7"
    type: "end"
    strict: true
  - id: "GetAdditionalContents1"
    type: "pipelet"
    ref: "GetAdditionalContents"
    bindings:
      AdditionalContentIterator: "Additionals"
      ExtensibleObject: "Product"
  - id: "GetApplicationBO2"
    type: "pipelet"
    ref: "GetApplicationBO"
  - id: "GetCurrencies1"
    type: "pipelet"
    ref: "GetCurrencies"
    config:
      Method: "Active Currencies"
    bindings:
      Domain: "OrganizationDomain"
  - id: "GetImageViewByID1"
    type: "pipelet"
    ref: "GetImageViewByID"
    bindings:
      ImageView: "PrimaryView"
      ImageViewBO: "PrimaryView"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
    bindings:
      LocaleId: "LocaleID"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetSortedAttributes1"
    type: "pipelet"
    ref: "GetSortedAttributes"
    config:
      Prefix: "Attrib"
    bindings:
      AttributeNames: "CustomAttributeNames"
      AttributeValues: "CustomAttributeValues"
      ExtensibleObject: "Product"
  - id: "Join3"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode17"
    type: "join"
  - id: "JoinNode18"
    type: "join"
  - id: "JoinNode19"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode20"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ProductBO:Extension(\"Image\"):ImageContainerBO"
      OutValue_1: "ImageContainer"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "AbsoluteFileName"
      InValue_1: "\"/\""
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Product\"):getProductBORepository(Product:Domain:UUID)"
      OutValue_1: "ProductBORepository"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "ImageContainer:Image(ImageType:ID,PrimaryView:ID):ImageBaseName"
      OutValue_1: "FileName"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "Product:PrimaryViewID"
      OutValue_1: "ImageViewID"
  - id: "LoopNode4"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetProductBOByID"
    bindings:
      ID: "Product:UUID"
      Domain: "Product:Domain"
  - id: "ResolveFilename3"
    type: "pipelet"
    ref: "ResolveFilename"
    config:
      UnitDirectory: "STATIC_CONTENT_DIR"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ContentType"
      Value: "All"
  - id: "ToString1"
    type: "pipelet"
    ref: "ToString"
    bindings:
      Object1: "Width"
      String1: "Width"
      Object10: "Height"
      String10: "Height"

links:
  - from: "GetLocale1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "JoinNode17"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CreateProductIdentifierLookupHelper1"
    into: "in"
  - from: "CreateProductIdentifierLookupHelper1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "DetermineUnit1"
    via: "next"
    to: "ResolveFilename3"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "DecisionNode4"
    via: "yes"
    to: "CallNode1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode7"
    into: "in2"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode18"
    into: "in3"
  - from: "Call1"
    via: "ERROR"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode6"
    via: "ERROR"
    to: "JoinNode6"
    into: "in2"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "GetAdditionalContents1"
    into: "in"
  - from: "ResolveFilename3"
    via: "next"
    to: "JoinNode18"
    into: "in1"
  - from: "DetermineUnit1"
    via: "error"
    to: "JoinNode17"
    into: "in2"
  - from: "AddObjectToVector1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "GetAdditionalContents1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "GetCurrencies1"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "CallNode2"
    via: "ERROR"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "DecisionNode4"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "GetSortedAttributes1"
    into: "in"
  - from: "GetSortedAttributes1"
    via: "next"
    to: "GetCurrencies1"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode1"
    via: "ERROR"
    to: "JoinNode8"
    into: "in2"
  - from: "CreateStringSplitter2"
    via: "next"
    to: "DetermineUnit1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "CreateImageThumbnail1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "GetLocale2"
    via: "next"
    to: "CreateStringSplitter2"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode9"
    into: "in2"
  - from: "CreateImageThumbnail1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "CallNode3"
    via: "ERROR"
    to: "JoinNode20"
    into: "in1"
  - from: "DecisionNode3"
    via: "no"
    to: "CallNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "KeyMapper5"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "JoinNode19"
    into: "in1"
  - from: "StartNode17"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "JoinNode19"
    via: "next"
    to: "GetImageViewByID1"
    into: "in"
  - from: "GetImageViewByID1"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "GetImageViewByID1"
    via: "error"
    to: "JoinNode20"
    into: "in2"
  - from: "CallNode3"
    via: "next"
    to: "JoinNode19"
    into: "in3"
  - from: "JoinNode20"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "GetLocale2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode17"
    into: "in1"
  - from: "JoinNode18"
    via: "next"
    to: "ToString1"
    into: "in"
  - from: "ToString1"
    via: "next"
    to: "CreateImageThumbnail1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "LoopNode4"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "DetermineMatchingImageType1"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "LoopNode4"
    via: "do"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "AddObjectToVector1"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "LoopNode4"
    into: "loop"
  - from: "Pipelet1"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "LoopNode4"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "DetermineMatchingImageType1"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "GetApplicationBO2"
    into: "in"
  - from: "GetApplicationBO2"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "GetAdditionalContents1"
    via: "error"
    to: "Join3"
    into: "in3"
