flow: "ProcessAuditReportGetDomains"
kind: "process"

entries:
  - id: "StartNode1"
    name: "GetDomains"
    mode: "private"
    strict: true
    inputs:
      - key: "Channels"
        type: "java.util.Collection<java.lang.String>"
        required: true
      - key: "CurrentApplication"
        type: "com.intershop.beehive.core.capi.domain.Application"
        required: true
      - key: "CurrentOrganization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "DomainsVector"
      OutVector: "DomainsVector"
      Object: "Domain"
  - id: "CheckUserPermission3"
    type: "pipelet"
    ref: "CheckUserPermission"
    config:
      DefaultPermissionID: "SLD_VIEW_AUDIT_REPORTS"
    bindings:
      AuthorizationObject: "Domain"
  - id: "CheckUserPermission4"
    type: "pipelet"
    ref: "CheckUserPermission"
    config:
      DefaultPermissionID: "SLD_VIEW_AUDIT_REPORTS"
    bindings:
      AuthorizationObject: "Organization"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "Domains"
        type: "java.util.Collection<com.intershop.beehive.core.capi.domain.Domain>"
        guaranteed: false
  - id: "GetDomainByUUID1"
    type: "pipelet"
    ref: "GetDomainByUUID"
  - id: "GetOrganizationByDomain1"
    type: "pipelet"
    ref: "GetOrganizationByDomain"
    bindings:
      OrganizationDomain: "Domain"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "DomainsVector"
      OutValue_1: "Domains"
  - id: "LoopNode1"
    type: "loop"
  - id: "TextNode1"
    type: "text"

links:
  - from: "StartNode1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "CheckUserPermission3"
    via: "error"
    to: "GetOrganizationByDomain1"
    into: "in"
  - from: "GetOrganizationByDomain1"
    via: "next"
    to: "CheckUserPermission4"
    into: "in"
  - from: "CheckUserPermission3"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "GetOrganizationByDomain1"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "LoopNode1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "GetDomainByUUID1"
    into: "in"
  - from: "GetDomainByUUID1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "GetDomainByUUID1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "CheckUserPermission3"
    into: "in"
  - from: "CheckUserPermission4"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "CheckUserPermission4"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "KeyMapper1"
    via: "next"
    to: "EndNode1"
    into: "in"
