flow: "ProcessPasswordReminder"
kind: "process"

entries:
  - id: "Start"
    name: "Send"
    mode: "private"
    strict: false
    inputs:
      - key: "Login"
        type: "java.lang.String"
        required: false

steps:
  - id: "DetermineMailAddressData"
    type: "pipelet"
    ref: "DetermineMailAddressData"
    config:
      DefaultEmailFrom: "EnfinitySuite@test.intershop.de"
      DefaultEmailSubject: "Your Password Description"
      EmailTemplate: "password_reminder_mail"
  - id: "DeterminePasswordReminder"
    type: "pipelet"
    ref: "DeterminePasswordReminder"
    bindings:
      Login: "ReminderForm:Login:Value"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "SendMail"
    type: "pipelet"
    ref: "SendMail"

links:
  - from: "DeterminePasswordReminder"
    via: "next"
    to: "DetermineMailAddressData"
    into: "in"
  - from: "DetermineMailAddressData"
    via: "next"
    to: "SendMail"
    into: "in"
  - from: "SendMail"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Start"
    via: "next"
    to: "DeterminePasswordReminder"
    into: "in"
  - from: "DeterminePasswordReminder"
    via: "error"
    to: "End2"
    into: "in"
