flow: "ProcessCatalogChannel"
kind: "process"

entries:
  - id: "Start12"
    name: "Remove"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "RemoveClipboard"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "UpdateClipboard"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "Sort"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "PrepareCatalogID"
    mode: "private"
    strict: true
    inputs:
      - key: "CatalogID"
        type: "java.lang.String"
        required: true
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode2"
    name: "RemovePEPs"
    mode: "private"
    strict: true
    inputs:
      - key: "CatalogDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "PEPDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode3"
    name: "RemoveProductCategoryBindings"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "CheckIfCatalogIDExists"
    mode: "private"
    strict: true
    inputs:
      - key: "CatalogID"
        type: "java.lang.String"
        required: true
      - key: "SelectedChannels"
        type: "java.util.Iterator"
        required: true

steps:
  - id: "CalculateInteger1"
    type: "pipelet"
    ref: "CalculateInteger"
    config:
      Operation: "+"
    bindings:
      Result: "Counter"
      Operand1: "Counter"
      Operand2: "\"(Integer)1\""
  - id: "CallNode1"
    type: "call"
    ref: "ProcessCatalogChannel-CheckIfCatalogIDExists"
    bindings:
      CatalogID: "Catalog:Id"
  - id: "CallNode19"
    type: "call"
    ref: "ProcessPageletEntryPoint-DeletePageletEntryPoint"
    bindings:
      Domain: "PEPDomain"
      Site: "PEPDomain:Site"
      PageletEntryPoint: "PEP"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessCatalogChannel-RemovePEPs"
    bindings:
      CatalogDomain: "Catalog:Domain"
      PEPDomain: "Channel:RepositoryDomain"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessCategoryConfigurationParameters-ProcessUnshare"
    bindings:
      Catalog: "Catalog"
      TargetDomain: "Channel:RepositoryDomain"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessCatalogChannel-RemoveProductCategoryBindings"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "OriginalCatalogID"
      String1: "Counter"
      Concatenated: "CatalogID"
  - id: "CreateProxyCatalog1"
    type: "pipelet"
    ref: "CreateProxyCatalog"
    bindings:
      CatalogID: "Catalog:Id"
      CatalogType: "Catalog:TypeCode"
      Domain: "Channel:Domain"
      Proxy: "SharedCatalogProxy"
  - id: "Decision1"
    type: "decision"
    condition: "AssignedChannels"
  - id: "Decision2"
    type: "decision"
    condition: "UnassignedChannels"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ProxyCatalogSharesCount"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ProxyCatalog"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Catalog:ClassificationSystem"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End13"
    type: "end"
    strict: false
  - id: "End6"
    type: "end"
    strict: false
  - id: "End7"
    type: "end"
    strict: false
  - id: "End8"
    type: "end"
    strict: false
  - id: "End9"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "CatalogID"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "SearchError"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "EndNode6"
    type: "end"
    strict: true
  - id: "EndNode7"
    type: "end"
    strict: true
  - id: "EndNode8"
    type: "end"
    strict: false
  - id: "ExecuteCountQuery1"
    type: "pipelet"
    ref: "ExecuteCountQuery"
    config:
      QueryName: "catalog/GetProxyCatalogSharedCatalogsCount"
      ParameterName_01: "Catalog"
      ParameterName_02: "Channel"
      Datasource: "current ORM connection"
    bindings:
      ParameterValue_01: "Catalog"
      ParameterValue_02: "Channel"
      Count: "ProxyCatalogSharesCount"
  - id: "ExecuteObjectsQuery1"
    type: "pipelet"
    ref: "ExecuteObjectsQuery"
    config:
      QueryName: "catalog/GetCatalogPEPs"
      Datasource: "current ORM connection"
      ParameterName_01: "CatalogDomain"
      ParameterName_02: "PEPDomain"
    bindings:
      SearchResult: "PEPs"
      ParameterValue_01: "CatalogDomain"
      ParameterValue_02: "PEPDomain"
  - id: "ExecuteObjectsQuery2"
    type: "pipelet"
    ref: "ExecuteObjectsQuery"
    config:
      QueryName: "catalog/GetProxyCatalog"
      Datasource: "current ORM connection"
      ParameterName_01: "Catalog"
      ParameterName_02: "DomainID"
    bindings:
      SearchResult: "ProxyCatalog"
      ParameterValue_01: "Catalog"
      ParameterValue_02: "Channel:DomainID"
  - id: "ExecuteObjectsQuery3"
    type: "pipelet"
    ref: "ExecuteObjectsQuery"
    config:
      QueryName: "catalog/GetProxyCatalog"
      Datasource: "current ORM connection"
      ParameterName_01: "Catalog"
      ParameterName_02: "DomainID"
    bindings:
      SearchResult: "ProxyCatalog"
      ParameterValue_01: "Catalog"
      ParameterValue_02: "Channel:DomainID"
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "catalog/GetAssignableChannels"
      DefaultPageSize: 15
      ParameterName_01: "Catalog"
      ParameterName_02: "SortFieldName"
      ParameterName_03: "SortDirection"
      ParameterName_04: "LocaleInformation"
    bindings:
      ParameterValue_02: "SortingAttribute"
      ParameterValue_03: "SortingOrder"
      SearchResult: "UnassignedChannels"
      ParameterValue_01: "Catalog"
      ParameterValue_04: "CurrentSession:Locale"
      ErrorCode: "SearchError"
  - id: "GetCatalog1"
    type: "pipelet"
    ref: "GetCatalog"
    bindings:
      OrganizationDomain: "Domain"
      CatalogID: "CatalogID"
  - id: "GetCatalog2"
    type: "pipelet"
    ref: "GetCatalog"
    bindings:
      OrganizationDomain: "Channel:Domain"
      CatalogID: "CatalogID"
  - id: "GetCategoryProducts1"
    type: "pipelet"
    ref: "GetCategoryProducts"
    config:
      Online: "All"
    bindings:
      Category: "SubCategoryToRemove"
      ProductDomain: "Channel:Domain"
      Products: "ProductsToRemove"
  - id: "GetFirstElementOfIterator1"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      Iterator: "ProxyCatalog"
      FirstElement: "ProxyCatalog"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedChannelUUID"
    bindings:
      Selection: "SelectedChannelUUIDs"
  - id: "GetFormSelection2"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "ListChannelUUID"
    bindings:
      Selection: "ListChannelUUIDs"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "Channel"
      UUID: "Selection"
  - id: "GetRepositoryByUUID3"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "Channel"
      UUID: "Selection"
  - id: "GetRepositoryByUUID4"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "Channel"
      UUID: "Selection"
  - id: "GetSubCategories1"
    type: "pipelet"
    ref: "GetSubCategories"
    config:
      Online: "All"
    bindings:
      Category: "ProxyCatalog:Root"
      SubCategories: "SubCategoriesToRemove"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"(Integer)0\""
      OutValue_1: "Counter"
      InValue_2: "CatalogID"
      OutValue_2: "OriginalCatalogID"
  - id: "KeyMapper19"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Repository(\"SearchQueryDefinition\", Channel:Domain:Site:DomainID)"
      OutValue_1: "SearchQueryDefinitionBORepository"
  - id: "Loop1"
    type: "loop"
  - id: "Loop4"
    type: "loop"
  - id: "Loop6"
    type: "loop"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "LoopNode3"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "CopyCustomAttributes"
    bindings:
      ExtensibleObject: "SharedCatalogProxy"
      CustomAttributes: "Catalog:AttributeValues"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "sharingCheck"
      Value: "error"
  - id: "RemoveCatalog1"
    type: "pipelet"
    ref: "RemoveCatalog"
    bindings:
      Catalog: "ProxyCatalog"
      OrganizationDomain: "Channel:Domain"
  - id: "RemoveClipboard1"
    type: "pipelet"
    ref: "RemoveClipboard"
    config:
      SessionRegistrationID: "ChannelClipboard"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "ChannelClipboard"
  - id: "RemoveProductCategoryBinding1"
    type: "pipelet"
    ref: "RemoveProductCategoryBinding"
    bindings:
      CatalogCategory: "SubCategoryToRemove"
      Product: "ProductToRemove"
  - id: "RemoveSearchQueryDefinitionBOCategoryAssignments1"
    type: "pipelet"
    ref: "RemoveSearchQueryDefinitionBOCategoryAssignments"
    bindings:
      CategoryDomain: "Catalog:Domain"
      CategoryName: "Catalog:Id"
  - id: "SetCatalogClassificationSystem1"
    type: "pipelet"
    ref: "SetCatalogClassificationSystem"
    bindings:
      Catalog: "SharedCatalogProxy"
      ClassificationSystem: "Catalog:ClassificationSystem"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_CATALOGID_EXISTS"
      Value: "CatalogID"
  - id: "SortIteratorByComparator1"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    bindings:
      Iterator: "AssignedChannels"
      SortedIterator: "AssignedChannels"
  - id: "TextNode1"
    type: "text"
  - id: "TextNode3"
    type: "text"
  - id: "TextNode4"
    type: "text"
  - id: "UpdateClipboard1"
    type: "pipelet"
    ref: "UpdateClipboard"
    config:
      SessionRegistrationID: "ChannelClipboard"
      StoreFormValues: "No"
    bindings:
      AllObjectUUIDs: "ListChannelUUIDs"
      Clipboard: "ChannelClipboard"
      SelectedObjectUUIDs: "SelectedChannelUUIDs"
      UUIDIterator: "SelectedChannels"

links:
  - from: "CreateProxyCatalog1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "GetFormSelection2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "KeyMapper19"
    into: "in"
  - from: "KeyMapper19"
    via: "next"
    to: "RemoveSearchQueryDefinitionBOCategoryAssignments1"
    into: "in"
  - from: "UpdateClipboard1"
    via: "next"
    to: "End6"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "RemoveClipboard1"
    into: "in"
  - from: "RemoveClipboard1"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "SortIteratorByComparator1"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "SortIteratorByComparator1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Decision1"
    via: "no"
    to: "Join5"
    into: "in3"
  - from: "Join5"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "GetFirstElementOfIterator1"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "Join6"
    via: "next"
    to: "End9"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join6"
    into: "in3"
  - from: "ExecutePageableQuery1"
    via: "error"
    to: "EndNode2"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "End7"
    into: "in"
  - from: "Loop4"
    via: "next"
    to: "End8"
    into: "in"
  - from: "CallNode1"
    via: "CatalogIDNotExisting"
    to: "Loop4"
    into: "in"
  - from: "Loop4"
    via: "do"
    to: "GetRepositoryByUUID3"
    into: "in"
  - from: "GetRepositoryByUUID3"
    via: "next"
    to: "ExecuteObjectsQuery3"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "JoinNode6"
    into: "in2"
  - from: "RemoveCatalog1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet3"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Loop6"
    into: "loop"
  - from: "ExecuteCountQuery1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode2"
    via: "Error"
    to: "JoinNode13"
    into: "in2"
  - from: "RemoveSearchQueryDefinitionBOCategoryAssignments1"
    via: "error"
    to: "JoinNode14"
    into: "in1"
  - from: "Loop6"
    via: "next"
    to: "End13"
    into: "in"
  - from: "Start12"
    via: "next"
    to: "Loop6"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "ExecuteObjectsQuery2"
    via: "next"
    to: "GetFirstElementOfIterator1"
    into: "in"
  - from: "ExecuteCountQuery1"
    via: "error"
    to: "JoinNode11"
    into: "in1"
  - from: "ExecuteObjectsQuery2"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "GetRepositoryByUUID4"
    via: "next"
    to: "ExecuteObjectsQuery2"
    into: "in"
  - from: "Loop6"
    via: "do"
    to: "GetRepositoryByUUID4"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "GetCatalog1"
    via: "error"
    to: "EndNode1"
    into: "in"
  - from: "CalculateInteger1"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode4"
    via: "yes"
    to: "SetCatalogClassificationSystem1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetCatalog1"
    via: "next"
    to: "CalculateInteger1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "GetCatalog1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "ExecuteObjectsQuery1"
    into: "in"
  - from: "ExecuteObjectsQuery3"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "CreateProxyCatalog1"
    into: "in"
  - from: "ExecuteObjectsQuery3"
    via: "error"
    to: "JoinNode9"
    into: "in1"
  - from: "CreateProxyCatalog1"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "Join7"
    via: "next"
    to: "Loop4"
    into: "loop"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode8"
    into: "in2"
  - from: "Pipelet1"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "GetFirstElementOfIterator1"
    via: "next"
    to: "ExecuteCountQuery1"
    into: "in"
  - from: "SetCatalogClassificationSystem1"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "Join7"
    into: "in3"
  - from: "GetRepositoryByUUID3"
    via: "error"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "GetRepositoryByUUID4"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode19"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "CallNode2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "LoopNode2"
    via: "do"
    to: "CallNode19"
    into: "in"
  - from: "GetSubCategories1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "CallNode1"
    via: "CatalogIDExists"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode14"
    into: "in1"
  - from: "LoopNode2"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "GetCategoryProducts1"
    into: "in"
  - from: "GetCategoryProducts1"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "LoopNode3"
    via: "do"
    to: "RemoveProductCategoryBinding1"
    into: "in"
  - from: "LoopNode3"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "RemoveProductCategoryBinding1"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "GetFormSelection2"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "ExecuteObjectsQuery1"
    via: "error"
    to: "EndNode4"
    into: "in"
  - from: "RemoveCatalog1"
    via: "error"
    to: "JoinNode13"
    into: "in1"
  - from: "JoinNode13"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "ExecuteObjectsQuery1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetSubCategories1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "RemoveCatalog1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "UpdateClipboard1"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "RemoveSearchQueryDefinitionBOCategoryAssignments1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "GetCatalog2"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "GetCatalog2"
    via: "error"
    to: "JoinNode12"
    into: "in1"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "GetCatalog2"
    into: "in"
  - from: "JoinNode12"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "GetRepositoryByUUID1"
    via: "error"
    to: "JoinNode12"
    into: "in2"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "JoinNode14"
    via: "next"
    to: "JoinNode3"
    into: "in1"
