flow: "ProcessStorefrontEditing"
kind: "process"

entries:
  - id: "StartNode1"
    name: "GetWorkingContextTime"
    mode: "private"
    strict: true
    inputs:
      - key: "ContentRepository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
  - id: "StartNode4"
    name: "GetContentSharingChannel"
    mode: "private"
    strict: true
    inputs:
      - key: "OrganizationDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true

steps:
  - id: "DecisionNode2"
    type: "decision"
    condition: "UUID"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "WorkingContextTime"
        type: "java.util.Date"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "ContentSharingChannel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        guaranteed: true
  - id: "GetApplicationBO2"
    type: "pipelet"
    ref: "GetApplicationBO"
  - id: "GetCurrentDate1"
    type: "pipelet"
    ref: "GetCurrentDate"
    bindings:
      CurrentDate: "WorkingContextTime"
  - id: "GetDomainPreference2"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "String"
    bindings:
      PreferenceDomain: "OrganizationDomain"
      PreferenceKey: "\"ContentSharingChannel\""
      PreferenceStringValue: "UUID"
  - id: "GetPreferredPreviewApplicationBO1"
    type: "pipelet"
    ref: "GetPreferredPreviewApplicationBO"
    bindings:
      User: "CurrentUser"
      ApplicationBO: "TargetApplicationBO"
      ApplicationBORepository: "ApplicationBO:getRepository(\"ApplicationBORepository\",ContentRepository:RepositoryDomain:Site:UUID)"
      Repository: "ContentRepository"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "ContentSharingChannel"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "TargetApplicationBO:Extension(\"DateTime\"):CurrentDate"
      OutValue_1: "WorkingContextTime"

links:
  - from: "StartNode1"
    via: "next"
    to: "GetApplicationBO2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "GetDomainPreference2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "GetDomainPreference2"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "GetApplicationBO2"
    via: "next"
    to: "GetPreferredPreviewApplicationBO1"
    into: "in"
  - from: "GetPreferredPreviewApplicationBO1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "GetPreferredPreviewApplicationBO1"
    via: "error"
    to: "GetCurrentDate1"
    into: "in"
  - from: "GetCurrentDate1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "JoinNode4"
    into: "in2"
  - from: "GetDomainPreference2"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode2"
    into: "in"
