flow: "ProcessLocalizations"
kind: "process"

entries:
  - id: "StartNode1"
    name: "CreateForm"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "GetForm"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "CreatePageable"
    mode: "private"
    strict: true
    inputs:
      - key: "SearchedKey"
        type: "java.lang.String"
        required: false
      - key: "SearchedValue"
        type: "java.lang.String"
        required: false
      - key: "SearchType"
        type: "java.lang.String"
        required: false
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: true
      - key: "LocalizationContext"
        type: "com.intershop.beehive.core.capi.localization.context.LocalizationContext"
        required: true
  - id: "StartNode4"
    name: "UpdateTexts"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "GetLocalizationRepositories"
    mode: "private"
    strict: true
    inputs:
      - key: "DomainUUID"
        type: "java.lang.String"
        required: false
  - id: "StartNode6"
    name: "GetContextApp"
    mode: "private"
    strict: true
    inputs:
      - key: "AppId"
        type: "java.lang.String"
        required: false
      - key: "LocalizationRepositories"
        type: "java.util.Iterator"
        required: true
  - id: "StartNode7"
    name: "SetPage"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "GetContextLocalizationRepository"
    mode: "private"
    strict: true
    inputs:
      - key: "LocalizationRepositories"
        type: "java.util.Iterator"
        required: true
      - key: "ContextApp"
        type: "com.intershop.beehive.app.capi.App"
        required: true
  - id: "StartNode9"
    name: "GetContextApplication"
    mode: "private"
    strict: true
    inputs:
      - key: "ApplicationUUID"
        type: "java.lang.String"
        required: false
      - key: "ChannelRepository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
      - key: "Pattern"
        type: "java.lang.String"
        required: false

steps:
  - id: "CallNode11"
    type: "call"
    ref: "ProcessApplication-GetApplications"
    bindings:
      Applications: "Applications"
  - id: "DecisionNode1"
    type: "decision"
    condition: "DomainCurrentValue"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ApplicationUUID"
  - id: "DecisionNode3"
    type: "decision"
    condition: "AppId"
  - id: "DecisionNode4"
    type: "decision"
    condition: "ContextLocalizationRepository:AppID"
  - id: "DecisionNode5"
    type: "decision"
    condition: "ContextApplication:Default"
  - id: "DecisionNode8"
    type: "decision"
    condition: "PageNumber"
  - id: "DecisionNode9"
    type: "decision"
    condition: "PageLocator"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "LocalizationTexts"
        type: "com.intershop.beehive.core.capi.paging.PageableIterator"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "LocalizationRepositories"
        type: "java.util.Iterator"
        guaranteed: true
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "ContextApplication"
        type: "com.intershop.beehive.core.capi.domain.Application"
        guaranteed: true
      - key: "Applications"
        type: "java.util.Iterator"
        guaranteed: true
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "ContextApp"
        type: "com.intershop.beehive.app.capi.App"
        guaranteed: true
  - id: "EndNode7"
    type: "end"
    strict: true
    outputs:
      - key: "ContextLocalizationRepository"
        type: "com.intershop.beehive.core.capi.localization.LocalizationRepository"
        guaranteed: true
  - id: "EndNode9"
    type: "end"
    strict: false
  - id: "GetFormRecord1"
    type: "pipelet"
    ref: "GetFormRecord"
    bindings:
      RecordID: "Key"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    bindings:
      ParameterName: "\"keyName\""
      Selection: "KeyNames"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "Error-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "Error-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "Error-Start"
  - id: "JumpNode4"
    type: "jump"
    ref: "Error-Start"
  - id: "JumpNode6"
    type: "jump"
    ref: "Error-Start"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_2: "FormRecord:domainValue"
      OutValue_2: "DomainValue"
      InValue_1: "FormRecord:domainCurrentValue"
      OutValue_1: "DomainCurrentValue"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "LoopNode3"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "search"
    bindings:
      WebForm: "search"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "GetLocalizedTextByLocalizationRepository"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "IntegerPageNumber"
      LocalizedString: "PageNumber"
  - id: "Pipelet12"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "LocalizationTexts"
  - id: "Pipelet13"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultPageLocatorName: "LocalizationTextsLocator"
      UsePageLocatorHistory: false
    bindings:
      Pageable: "LocalizationTexts"
  - id: "Pipelet14"
    type: "pipelet"
    ref: "UpdateLocalizedText"
  - id: "Pipelet16"
    type: "pipelet"
    ref: "GetApplicationByUUID"
    bindings:
      ApplicationUUID: "ApplicationUUID"
      Application: "ContextApplication"
  - id: "Pipelet18"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      Iterator: "LocalizationRepositories"
      FirstElement: "LocalizationRepository"
  - id: "Pipelet19"
    type: "pipelet"
    ref: "GetApp"
    bindings:
      AppID: "AppId"
      App: "ContextApp"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      webform-id: "search"
      mode: "update"
    bindings:
      WebForm: "search"
  - id: "Pipelet20"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "LocalizationRepository:AppID"
      OutValue_1: "AppId"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "search:searchedKey:Value"
      OutValue_1: "SearchedKey"
      InValue_2: "search:searchedValue:Value"
      OutValue_2: "SearchedValue"
      InValue_3: "search:Type:Value"
      OutValue_3: "SearchType"
      InValue_4: "search:LocaleId:Value"
      OutValue_4: "LocaleId"
      InValue_5: "search:ApplicationId:Value"
      OutValue_5: "ApplicationId"
      InValue_6: "search:AppId:Value"
      OutValue_6: "AppId"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      webform-id: "search"
      param.1.name: "Login"
      param.1.rule: ""
      param.1.required: false
    bindings:
      WebForm: "search"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "search"
    bindings:
      WebForm: "search"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "RegisterPageable"
    bindings:
      PageableName: "\"LocalizationTexts\""
      see PageableName: "LocalizationTexts"
      PageableID: "\"LocalizationTextsPageableID\""
  - id: "Pipelet7"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    config:
      PageableName: "LocalizationTexts"
      Pagesize: 10
    bindings:
      Iterator: "LocalizationTexts"
      Pageable: "LocalizationTexts"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "IntegerPageNumber"
      Pageable: "LocalizationTexts"
  - id: "Pipelet9"
    type: "pipelet"
    ref: "GetLocalizationRepositoriesByDomainId"
    bindings:
      DomainUUID: "DomainUUID"

links:
  - from: "StartNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Pipelet9"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "Pipelet18"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "StartNode3"
    via: "next"
    to: "Pipelet10"
    into: "in"
  - from: "Pipelet7"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "Pipelet10"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "Pipelet6"
    via: "error"
    to: "JumpNode1"
    into: "in"
  - from: "Pipelet13"
    via: "next"
    to: "EndNode9"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "Pipelet11"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "DecisionNode9"
    via: "no"
    to: "JoinNode8"
    into: "in3"
  - from: "DecisionNode9"
    via: "yes"
    to: "Pipelet12"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "Pipelet13"
    into: "in"
  - from: "Pipelet11"
    via: "error"
    to: "JoinNode10"
    into: "in3"
  - from: "StartNode7"
    via: "next"
    to: "DecisionNode8"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode9"
    into: "in3"
  - from: "Pipelet12"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode8"
    via: "no"
    to: "DecisionNode9"
    into: "in"
  - from: "DecisionNode8"
    via: "yes"
    to: "Pipelet11"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "Pipelet5"
    via: "error"
    to: "JumpNode2"
    into: "in"
  - from: "GetFormRecord1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "GetFormRecord1"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "Pipelet14"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode6"
    into: "in2"
  - from: "LoopNode2"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "Pipelet9"
    into: "in"
  - from: "Pipelet9"
    via: "error"
    to: "JumpNode3"
    into: "in"
  - from: "Pipelet19"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet19"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "Pipelet5"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "DecisionNode3"
    via: "yes"
    to: "JoinNode4"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Pipelet14"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet16"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "JoinNode11"
    into: "in3"
  - from: "Pipelet16"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "Pipelet1"
    via: "error"
    to: "Pipelet4"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode7"
    into: "in1"
  - from: "StartNode9"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "LoopNode3"
    via: "next"
    to: "JumpNode6"
    into: "in"
  - from: "LoopNode3"
    via: "do"
    to: "DecisionNode5"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "Pipelet19"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "Pipelet20"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "DecisionNode5"
    via: "no"
    to: "LoopNode3"
    into: "loop"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode6"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "Pipelet18"
    into: "in"
  - from: "Pipelet16"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "DecisionNode4"
    via: "no"
    to: "LoopNode1"
    into: "loop"
  - from: "LoopNode1"
    via: "do"
    to: "DecisionNode4"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode4"
    via: "yes"
    to: "JoinNode5"
    into: "in2"
  - from: "JoinNode11"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet18"
    via: "next"
    to: "Pipelet20"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
