flow: "ProcessProductFilter"
kind: "process"

entries:
  - id: "Start1"
    name: "Remove"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Create"
    mode: "private"
    strict: true
    inputs:
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "ID"
        type: "java.lang.String"
        required: false
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: true
      - key: "DisplayName"
        type: "java.lang.String"
        required: false
      - key: "Description"
        type: "java.lang.String"
        required: false
      - key: "SQDForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        required: false
  - id: "Start3"
    name: "Get"
    mode: "private"
    strict: false
    inputs:
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "Start5"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "UpdateClipboard"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "RemoveClipboard"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "GetAll"
    mode: "private"
    strict: true
    inputs:
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode2"
    name: "GetSearchIndex"
    mode: "private"
    strict: true
    inputs:
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode3"
    name: "GetSearchIndexByLocale"
    mode: "private"
    strict: true
    inputs:
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessSearchIndex-GetIndexes"
    bindings:
      Domain: "Domain"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessSearchIndex-GetIndexes"
    bindings:
      Domain: "Domain"
  - id: "CreateSearchQueryDefinition1"
    type: "pipelet"
    ref: "CreateSearchQueryDefinition"
    bindings:
      ID: "ID"
      SearchQueryDefinition: "ProductFilter"
  - id: "DecisionNode1"
    type: "decision"
    condition: "SearchIndex:SearchIndexFeature:FeatureID"
  - id: "DecisionNode2"
    type: "decision"
    condition: "SearchIndex:Configuration:Online"
  - id: "DecisionNode3"
    type: "decision"
    condition: "SearchIndex:SearchIndexFeature:FeatureID"
  - id: "DecisionNode4"
    type: "decision"
    condition: "SearchIndex:Configuration:Online"
  - id: "DecisionNode5"
    type: "decision"
    condition: "SearchIndex:Configuration:Locale:LocaleID"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End12"
    type: "end"
    strict: false
  - id: "End17"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: true
    outputs:
      - key: "ProductFilter"
        type: "com.intershop.component.search.capi.querydefinition.SearchQueryDefinition"
        guaranteed: true
  - id: "End3"
    type: "end"
    strict: true
    outputs:
      - key: "ProductFilters"
        type: "java.util.Iterator"
        guaranteed: true
  - id: "End4"
    type: "end"
    strict: false
  - id: "End5"
    type: "end"
    strict: true
  - id: "End6"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "SearchIndex"
        type: "com.intershop.component.search.capi.SearchIndex"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "SearchIndex"
        type: "com.intershop.component.search.capi.SearchIndex"
        guaranteed: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "AllProductFilterUUID"
    bindings:
      Selection: "AllProductFiltersUUIDs"
  - id: "GetFormSelection2"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedProductFilterUUID"
    bindings:
      Selection: "SelectedProductFiltersUUIDs"
  - id: "GetSearchQueryDefinition1"
    type: "pipelet"
    ref: "GetSearchQueryDefinition"
    bindings:
      SearchQueryDefinition: "ProductFilter"
      UUID: "ProductFilterUUID"
  - id: "GetSearchQueryDefinitions1"
    type: "pipelet"
    ref: "GetSearchQueryDefinitions"
    bindings:
      SearchQueryDefinitions: "ProductFilters"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "RemoveClipboard1"
    type: "pipelet"
    ref: "RemoveClipboard"
    config:
      SessionRegistrationID: "ProductFiltersClipboard"
  - id: "RemoveSearchQueryDefinition1"
    type: "pipelet"
    ref: "RemoveSearchQueryDefinition"
    bindings:
      SearchQueryDefinition: "ProductFilter"
  - id: "UpdateClipboard1"
    type: "pipelet"
    ref: "UpdateClipboard"
    config:
      SessionRegistrationID: "ProductFiltersClipboard"
      StoreFormValues: "No"
    bindings:
      AllObjectUUIDs: "AllProductFiltersUUIDs"
      Clipboard: "ProductFiltersClipboard"
      SelectedObjectUUIDs: "SelectedProductFiltersUUIDs"
      UUIDIterator: "SelectedProductFilters"
  - id: "UpdateSearchQueryDefinition1"
    type: "pipelet"
    ref: "UpdateSearchQueryDefinition"
    bindings:
      Form: "SQDForm"
      Name: "null"
      SearchQueryDefinition: "ProductFilter"

links:
  - from: "CreateSearchQueryDefinition1"
    via: "next"
    to: "UpdateSearchQueryDefinition1"
    into: "in"
  - from: "RemoveSearchQueryDefinition1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "RemoveClipboard1"
    into: "in"
  - from: "GetSearchQueryDefinition1"
    via: "next"
    to: "End4"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetSearchQueryDefinitions1"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "GetSearchQueryDefinitions1"
    via: "next"
    to: "End3"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "JoinNode1"
    into: "in3"
  - from: "CreateSearchQueryDefinition1"
    via: "error"
    to: "End5"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode1"
    into: "in1"
  - from: "UpdateSearchQueryDefinition1"
    via: "error"
    to: "End5"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "EndNode2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "DecisionNode4"
    via: "yes"
    to: "JoinNode2"
    into: "in3"
  - from: "JoinNode2"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "LoopNode2"
    via: "do"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "UpdateClipboard1"
    via: "next"
    to: "End12"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "JoinNode2"
    into: "in1"
  - from: "LoopNode2"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "EndNode3"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "End6"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "DecisionNode4"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "GetFormSelection2"
    into: "in"
  - from: "UpdateSearchQueryDefinition1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "CreateSearchQueryDefinition1"
    into: "in"
  - from: "GetFormSelection2"
    via: "next"
    to: "UpdateClipboard1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "GetSearchQueryDefinition1"
    into: "in"
  - from: "RemoveClipboard1"
    via: "next"
    to: "End17"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "RemoveSearchQueryDefinition1"
    into: "in"
