flow: "ProcessPromotionCodeForBasket"
kind: "process"

entries:
  - id: "StartNode1"
    name: "PromotionTargetGroupsEmpty"
    mode: "private"
    strict: true
    inputs:
      - key: "Promotion"
        type: "com.intershop.component.marketing.capi.rebate.Promotion"
        required: true
  - id: "StartNode2"
    name: "AssignOrderToPromotion"
    mode: "private"
    strict: true
    inputs:
      - key: "AppliedRebateBOs"
        type: "java.util.Collection<com.intershop.component.promotion.capi.AppliedRebateBO>"
        required: true
      - key: "Order"
        type: "com.intershop.beehive.bts.capi.orderprocess.fulfillment.Order"
        required: true
  - id: "StartNode3"
    name: "AssignOrderToPromotionCode"
    mode: "private"
    strict: true
    inputs:
      - key: "Order"
        type: "com.intershop.beehive.bts.capi.orderprocess.fulfillment.Order"
        required: true
      - key: "PromotionCode"
        type: "com.intershop.component.marketing.capi.code.PromotionCode"
        required: true
      - key: "CurrentUserUserGroups"
        type: "java.util.Iterator"
        required: true
  - id: "StartNode30"
    name: "OnCreateOrder"
    mode: "private"
    strict: true
    inputs:
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true
      - key: "Order"
        type: "com.intershop.beehive.bts.capi.orderprocess.fulfillment.Order"
        required: true
      - key: "CurrentUserUserGroups"
        type: "java.util.Iterator"
        required: true
      - key: "ApplicationBO"
        type: "com.intershop.component.application.capi.ApplicationBO"
        required: true

steps:
  - id: "AddOrderToPromotion2"
    type: "pipelet"
    ref: "AddOrderToPromotion"
    bindings:
      PromotionBO: "AppliedRebateBO:Rebate:Promotion"
  - id: "AddOrderToPromotionCode1"
    type: "pipelet"
    ref: "AddOrderToPromotionCode"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessPromotionCodeForBasket-AssignOrderToPromotion"
    bindings:
      AppliedRebateBOs: "OrderBO:Extension(\"AppliedRebate\"):AppliedPromotions(Code)"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessPromotionCodeForBasket-AssignOrderToPromotionCode"
  - id: "CallNode23"
    type: "call"
    ref: "ProcessOrders-GetOrderBO"
  - id: "DecisionNode1"
    type: "decision"
    condition: "UserGroups"
  - id: "DecisionNode11"
    type: "decision"
    condition: "CurrentSession:getObject(\"T_StorefrontEditingContext\")"
  - id: "DecisionNode33"
    type: "decision"
    condition: "UserCount"
  - id: "End18"
    type: "end"
    strict: true
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode36"
    type: "end"
    strict: true
  - id: "ExecuteCountQuery10"
    type: "pipelet"
    ref: "ExecuteCountQuery"
    config:
      QueryName: "promotion/CountPromotionTargetGroupUsers"
      ParameterName_01: "DomainID"
      ParameterName_02: "PromotionUUID"
      ParameterName_03: "TargetGroupID"
    bindings:
      Count: "UserCount"
      ParameterValue_01: "Promotion:TargetGroup:DomainID"
      ParameterValue_02: "Promotion:UUID"
      ParameterValue_03: "Promotion:TargetGroup:ID"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "TaxationPolicy"
      Type: "Integer"
    bindings:
      PreferenceDomain: "Organization:OwningDomain"
      PreferenceIntValue: "TaxationPolicy"
  - id: "GetPromotionCodeByCode1"
    type: "pipelet"
    ref: "GetPromotionCodeByCode"
  - id: "GetPromotionTargetGroupUserGroups1"
    type: "pipelet"
    ref: "GetPromotionTargetGroupUserGroups"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Order\"):getOrderBORepository(Order)"
      OutValue_1: "OrderBORepository"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode4"
    type: "loop"

links:
  - from: "LoopNode4"
    via: "do"
    to: "AddOrderToPromotion2"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "GetPromotionCodeByCode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "LoopNode4"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "GetPromotionCodeByCode1"
    via: "error"
    to: "CallNode1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetPromotionTargetGroupUserGroups1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "ExecuteCountQuery10"
    into: "in"
  - from: "GetPromotionTargetGroupUserGroups1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode33"
    via: "yes"
    to: "JoinNode1"
    into: "in3"
  - from: "DecisionNode33"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "AddOrderToPromotion2"
    via: "next"
    to: "LoopNode4"
    into: "loop"
  - from: "ExecuteCountQuery10"
    via: "next"
    to: "DecisionNode33"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "ExecuteCountQuery10"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "End18"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "StartNode3"
    via: "next"
    to: "AddOrderToPromotionCode1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "StartNode30"
    via: "next"
    to: "DecisionNode11"
    into: "in"
  - from: "DecisionNode11"
    via: "yes"
    to: "GetDomainPreference1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "EndNode36"
    into: "in"
  - from: "GetDomainPreference1"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "LoopNode4"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "CallNode23"
    into: "in"
  - from: "CallNode23"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "AddOrderToPromotionCode1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "GetPromotionCodeByCode1"
    into: "in"
  - from: "DecisionNode11"
    via: "no"
    to: "JoinNode6"
    into: "in2"
