flow: "ProcessSyndicationRule"
kind: "process"

entries:
  - id: "StartNode1"
    name: "GetDataDeclarationList"
    mode: "private"
    strict: true
    inputs:
      - key: "Syndication"
        type: "com.intershop.component.foundation.capi.syndication.Syndication"
        required: true
      - key: "Name"
        type: "java.lang.String"
        required: true
  - id: "StartNode2"
    name: "GetRuleSet"
    mode: "private"
    strict: true
    inputs:
      - key: "Syndication"
        type: "com.intershop.component.foundation.capi.syndication.Syndication"
        required: true
      - key: "Name"
        type: "java.lang.String"
        required: true
  - id: "StartNode3"
    name: "RemoveSyndicationRule"
    mode: "private"
    strict: true
    inputs:
      - key: "SyndicationRule"
        type: "com.intershop.component.foundation.capi.syndication.SyndicationRule"
        required: false

steps:
  - id: "CreateSyndicationDataDeclarationList1"
    type: "pipelet"
    ref: "CreateSyndicationDataDeclarationList"
    bindings:
      Domain: "Syndication:Domain"
  - id: "CreateSyndicationRuleSet1"
    type: "pipelet"
    ref: "CreateSyndicationRuleSet"
    bindings:
      Domain: "Syndication:Domain"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "SyndicationDataDeclarationList"
        type: "com.intershop.component.foundation.capi.syndication.SyndicationDataDeclarationList"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "SyndicationRuleSet"
        type: "com.intershop.component.foundation.capi.syndication.SyndicationRuleSet"
        guaranteed: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "EndNode5"
    type: "end"
    strict: false
  - id: "EndSafeChangesBlock1"
    type: "pipelet"
    ref: "EndSafeChangesBlock"
  - id: "EndSafeChangesBlock2"
    type: "pipelet"
    ref: "EndSafeChangesBlock"
  - id: "EndSafeChangesBlock3"
    type: "pipelet"
    ref: "EndSafeChangesBlock"
  - id: "EndSafeChangesBlock4"
    type: "pipelet"
    ref: "EndSafeChangesBlock"
  - id: "GetSyndicationDataDeclarationList1"
    type: "pipelet"
    ref: "GetSyndicationDataDeclarationList"
  - id: "GetSyndicationRuleSet1"
    type: "pipelet"
    ref: "GetSyndicationRuleSet"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "RemoveSyndicationRule1"
    type: "pipelet"
    ref: "RemoveSyndicationRule"
  - id: "StartSafeChangesBlock1"
    type: "pipelet"
    ref: "StartSafeChangesBlock"
  - id: "StartSafeChangesBlock2"
    type: "pipelet"
    ref: "StartSafeChangesBlock"

links:
  - from: "StartNode1"
    via: "next"
    to: "GetSyndicationDataDeclarationList1"
    into: "in"
  - from: "GetSyndicationRuleSet1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "GetSyndicationDataDeclarationList1"
    via: "error"
    to: "StartSafeChangesBlock2"
    into: "in"
  - from: "RemoveSyndicationRule1"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "RemoveSyndicationRule1"
    into: "in"
  - from: "GetSyndicationRuleSet1"
    via: "error"
    to: "StartSafeChangesBlock1"
    into: "in"
  - from: "StartSafeChangesBlock1"
    via: "next"
    to: "CreateSyndicationRuleSet1"
    into: "in"
  - from: "EndSafeChangesBlock1"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "EndSafeChangesBlock2"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "StartSafeChangesBlock2"
    via: "next"
    to: "CreateSyndicationDataDeclarationList1"
    into: "in"
  - from: "CreateSyndicationDataDeclarationList1"
    via: "error"
    to: "EndSafeChangesBlock4"
    into: "in"
  - from: "EndSafeChangesBlock3"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "EndSafeChangesBlock4"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "CreateSyndicationDataDeclarationList1"
    via: "next"
    to: "EndSafeChangesBlock3"
    into: "in"
  - from: "GetSyndicationDataDeclarationList1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetSyndicationRuleSet1"
    into: "in"
  - from: "CreateSyndicationRuleSet1"
    via: "error"
    to: "EndSafeChangesBlock2"
    into: "in"
  - from: "CreateSyndicationRuleSet1"
    via: "next"
    to: "EndSafeChangesBlock1"
    into: "in"
