flow: "ProcessOrganization_32"
kind: "process"

entries:
  - id: "Start1"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start10"
    name: "RemoveAttributeClipboard"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start11"
    name: "UpdateAttributeClipboard"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Remove"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Get"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "UpdateClipboard"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "RemoveClipboard"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToString1"
    type: "pipelet"
    ref: "AddObjectToString"
    config:
      DefaultSeparator: "-"
    bindings:
      InObject: "\"Site\""
      InString: "OrganizationID"
      OutString: "DomainName"
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Object: "\"30\""
      Iterator: "TypeCodes"
  - id: "Call1"
    type: "call"
    ref: "Organization-Create"
  - id: "Call3"
    type: "call"
    ref: "Organization-CreateSite"
  - id: "Call4"
    type: "call"
    ref: "Organization-Remove"
  - id: "Decision1"
    type: "decision"
    condition: "PrivateApplication"
  - id: "Decision2"
    type: "decision"
    condition: "Organization:Domain:Site:DomainID"
  - id: "Decision4"
    type: "decision"
    condition: "PrivateApplication"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Organization:OrganizationDomain:Site:DomainID"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End12"
    type: "end"
    strict: false
  - id: "End17"
    type: "end"
    strict: false
  - id: "End18"
    type: "end"
    strict: false
  - id: "End19"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "End6"
    type: "end"
    strict: false
  - id: "End8"
    type: "end"
    strict: false
  - id: "End9"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      Datasource: "default"
      DefaultPageSize: 10
      QueryName: "organization/GetOrganizationsByOwningDomain"
    bindings:
      Parameters: "OrganizationSearchParameters"
      SearchResult: "FilteredOrganizations"
  - id: "GetChannelTypeByID1"
    type: "pipelet"
    ref: "GetChannelTypeByID"
    bindings:
      ChannelTypeID: "CurrentChannel:TypeCode"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "HTTPSRequired"
      Type: "String"
    bindings:
      PreferenceDomain: "Organization:OrganizationDomain:Site"
      PreferenceStringValue: "HTTPSPreference"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "OrganizationID"
    bindings:
      Selection: "OrganizationUUIDs"
  - id: "GetFormSelection2"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedOrganizationUUID"
    bindings:
      Selection: "SelectedOrganizationUUIDs"
  - id: "GetFormSelection3"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedOrganizationAttributeName"
    bindings:
      Selection: "SelectedOrganizationAttributeNames"
  - id: "GetFormSelection4"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "OrganizationAttributeName"
    bindings:
      Selection: "OrganizationAttributeNames"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Lead Locale"
  - id: "GetOrganization1"
    type: "pipelet"
    ref: "GetOrganization"
    config:
      Source: "PipelineDictionary"
  - id: "GetOrganization2"
    type: "pipelet"
    ref: "GetOrganization"
    config:
      Source: "PipelineDictionary"
  - id: "GetOrganizationByName1"
    type: "pipelet"
    ref: "GetOrganizationByName"
    bindings:
      Name: "OrganizationID"
      Organization: "null"
      OrganizationDomain: "null"
  - id: "GetProperties1"
    type: "pipelet"
    ref: "GetProperties"
    config:
      PropertyName1: "intershop.cartridges.sld_ch_partner_plugin.PrivateApplication"
      DictionaryKey1: "PrivateApplication"
      DefaultValue1: false
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentChannel:RepositoryDomain:Site"
      InValue_2: "CurrentChannel:RepositoryDomain"
      OutValue_1: "Site"
      OutValue_2: "Owner"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "SiteDomain"
      InValue_2: "CurrentChannel:RepositoryDomain"
      OutValue_1: "Site"
      OutValue_2: "Owner"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ChannelType:DefaultChannelApplication:ApplicationTypeCode"
      OutValue_1: "ApplicationTypeID"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Organization:OrganizationDomain:Site"
      OutValue_1: "PrivateApplication"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "OrganizationID"
      OutValue_1: "UrlIdentifier"
      OutValue_2: "Owner"
  - id: "RemoveClipboard1"
    type: "pipelet"
    ref: "RemoveClipboard"
    config:
      SessionRegistrationID: "OrganizationClipboard"
  - id: "RemoveClipboard2"
    type: "pipelet"
    ref: "RemoveClipboard"
    config:
      SessionRegistrationID: "OrganizationAttributeClipboard"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: "OrganizationIDNotUnique"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ParentDomainName"
      Value: "root"
  - id: "SetDomainStatus1"
    type: "pipelet"
    ref: "SetDomainStatus"
    config:
      DefaultStatus: "ToBeDeleted"
    bindings:
      Domain: "PrivateApplication"
  - id: "UpdateClipboard1"
    type: "pipelet"
    ref: "UpdateClipboard"
    config:
      SessionRegistrationID: "OrganizationClipboard"
      StoreFormValues: "No"
    bindings:
      AllObjectUUIDs: "OrganizationUUIDs"
      SelectedObjectUUIDs: "SelectedOrganizationUUIDs"
      Clipboard: "OrganizationClipboard"
      UUIDIterator: "SelectedOrganizations"
  - id: "UpdateClipboard2"
    type: "pipelet"
    ref: "UpdateClipboard"
    config:
      SessionRegistrationID: "OrganizationAttributeClipboard"
      StoreFormValues: "No"
    bindings:
      AllObjectUUIDs: "OrganizationAttributeNames"
      SelectedObjectUUIDs: "SelectedOrganizationAttributeNames"
      Clipboard: "OrganizationAttributeClipboard"
      UUIDIterator: "SelectedOrganizationAttributes"
  - id: "UpdateDictionary2"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "OwningDomain"
      Name_02: "Locale"
      Name_03: "TypeCodes"
      Name_04: "SortBy"
      Name_05: "SortDirection"
    bindings:
      InDictionary: "null"
      Value_01: "CurrentChannel:RepositoryDomain"
      Value_02: "CurrentRequest:Locale"
      Value_03: "TypeCodes"
      Value_04: "SortingAttribute"
      Value_05: "SortDirection"
      OutDictionary: "OrganizationSearchParameters"
  - id: "UpdateOrganization2"
    type: "pipelet"
    ref: "UpdateOrganization"

links:
  - from: "AddObjectToString1"
    via: "next"
    to: "GetChannelTypeByID1"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "UpdateDictionary2"
    into: "in"
  - from: "Call1"
    via: "ERROR"
    to: "JoinNode3"
    into: "in1"
  - from: "Call1"
    via: "next"
    to: "End6"
    into: "in"
  - from: "Call3"
    via: "ERROR"
    to: "JoinNode1"
    into: "in1"
  - from: "Call3"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "Call4"
    via: "ERROR"
    to: "Join1"
    into: "in1"
  - from: "Call4"
    via: "next"
    to: "Decision4"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "GetOrganizationByName1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "KeyMapper1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join4"
    into: "in1"
  - from: "Decision2"
    via: "yes"
    to: "GetDomainPreference1"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "Join7"
    into: "in1"
  - from: "Decision4"
    via: "yes"
    to: "SetDomainStatus1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "KeyMapper4"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "error"
    to: "EndNode2"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "GetChannelTypeByID1"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "GetDomainPreference1"
    via: "error"
    to: "Join4"
    into: "in1"
  - from: "GetDomainPreference1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "GetFormSelection1"
    via: "next"
    to: "GetFormSelection2"
    into: "in"
  - from: "GetFormSelection2"
    via: "next"
    to: "UpdateClipboard1"
    into: "in"
  - from: "GetFormSelection3"
    via: "next"
    to: "UpdateClipboard2"
    into: "in"
  - from: "GetFormSelection4"
    via: "next"
    to: "GetFormSelection3"
    into: "in"
  - from: "GetLocale2"
    via: "next"
    to: "UpdateOrganization2"
    into: "in"
  - from: "GetOrganization1"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "GetOrganization1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetOrganization2"
    via: "error"
    to: "End4"
    into: "in"
  - from: "GetOrganization2"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "GetOrganizationByName1"
    via: "error"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "GetOrganizationByName1"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "GetProperties1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "End3"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Join7"
    via: "next"
    to: "End1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "End8"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "KeyMapper3"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "KeyMapper5"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "RemoveClipboard1"
    via: "next"
    to: "End17"
    into: "in"
  - from: "RemoveClipboard2"
    via: "next"
    to: "End19"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "AddObjectToString1"
    into: "in"
  - from: "SetDomainStatus1"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "Start10"
    via: "next"
    to: "RemoveClipboard2"
    into: "in"
  - from: "Start11"
    via: "next"
    to: "GetFormSelection4"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "GetProperties1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "GetOrganization1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "GetOrganization2"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "RemoveClipboard1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "UpdateClipboard1"
    via: "next"
    to: "End12"
    into: "in"
  - from: "UpdateClipboard2"
    via: "next"
    to: "End18"
    into: "in"
  - from: "UpdateDictionary2"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "UpdateOrganization2"
    via: "next"
    to: "End9"
    into: "in"
