flow: "ProcessEvent"
kind: "process"

entries:
  - id: "Start1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "End1"
    type: "end"
  - id: "Text1"
    type: "text"

links:
  - from: "Start1"
    via: "next"
    to: "End1"
    into: "in"
