flow: "ProcessAddress"
kind: "process"

entries:
  - id: "StartNode1"
    name: "GetAddress"
    mode: "private"
    strict: true
    inputs:
      - key: "AddressID"
        type: "java.lang.String"
        required: true
      - key: "Profile"
        type: "com.intershop.beehive.core.capi.profile.Profile"
        required: true
  - id: "StartNode10"
    name: "GetAddressBOs"
    mode: "private"
    strict: true
    inputs:
      - key: "AddressesCollection"
        type: "java.util.Collection"
        required: false
      - key: "AddressesIterator"
        type: "java.util.Iterator"
        required: false
      - key: "AddressBORepository"
        type: "com.intershop.component.address.capi.AddressBORepository"
        required: true
  - id: "StartNode2"
    name: "DeleteAddress"
    mode: "private"
    strict: true
    inputs:
      - key: "Profile"
        type: "com.intershop.beehive.core.capi.profile.Profile"
        required: true
      - key: "AddressID"
        type: "java.lang.String"
        required: true
  - id: "StartNode3"
    name: "UpdateAddress"
    mode: "private"
    strict: true
    inputs:
      - key: "Address"
        type: "com.intershop.beehive.core.capi.profile.Address"
        required: true
      - key: "City"
        type: "java.lang.String"
        required: false
      - key: "State"
        type: "java.lang.String"
        required: false
      - key: "Street"
        type: "java.lang.String"
        required: false
      - key: "Street2"
        type: "java.lang.String"
        required: false
      - key: "Title"
        type: "java.lang.String"
        required: false
      - key: "FirstName"
        type: "java.lang.String"
        required: false
      - key: "LastName"
        type: "java.lang.String"
        required: false
      - key: "PhoneHome"
        type: "java.lang.String"
        required: false
      - key: "PostalCode"
        type: "java.lang.String"
        required: false
      - key: "User"
        type: "com.intershop.beehive.core.capi.user.User"
        required: true
      - key: "PreferredBillingAddress"
        type: "java.lang.Boolean"
        required: false
      - key: "PreferredShippingAddress"
        type: "java.lang.Boolean"
        required: false
      - key: "CountryCode"
        type: "java.lang.String"
        required: false
      - key: "Street3"
        type: "java.lang.String"
        required: false
      - key: "Company"
        type: "java.lang.String"
        required: false
      - key: "SecondName"
        type: "java.lang.String"
        required: false
      - key: "Mobile"
        type: "java.lang.String"
        required: false
      - key: "AddressNr"
        type: "java.lang.String"
        required: false
  - id: "StartNode4"
    name: "Create"
    mode: "private"
    strict: true
    inputs:
      - key: "City"
        type: "java.lang.String"
        required: false
      - key: "State"
        type: "java.lang.String"
        required: false
      - key: "Street"
        type: "java.lang.String"
        required: false
      - key: "Street2"
        type: "java.lang.String"
        required: false
      - key: "Title"
        type: "java.lang.String"
        required: false
      - key: "FirstName"
        type: "java.lang.String"
        required: false
      - key: "LastName"
        type: "java.lang.String"
        required: false
      - key: "PhoneHome"
        type: "java.lang.String"
        required: false
      - key: "PostalCode"
        type: "java.lang.String"
        required: false
      - key: "User"
        type: "com.intershop.beehive.core.capi.user.User"
        required: true
      - key: "PreferredBillingAddress"
        type: "java.lang.Boolean"
        required: false
      - key: "PreferredShippingAddress"
        type: "java.lang.Boolean"
        required: false
      - key: "CountryCode"
        type: "java.lang.String"
        required: true
      - key: "Street3"
        type: "java.lang.String"
        required: false
      - key: "SecondName"
        type: "java.lang.String"
        required: false
      - key: "Mobile"
        type: "java.lang.String"
        required: false
      - key: "Company"
        type: "java.lang.String"
        required: false
      - key: "AddressNr"
        type: "java.lang.String"
        required: false
      - key: "AddressName"
        type: "java.lang.String"
        required: false
  - id: "StartNode5"
    name: "GetDefaultAddress"
    mode: "private"
    strict: true
    inputs:
      - key: "Profile"
        type: "com.intershop.beehive.core.capi.profile.Profile"
        required: true
  - id: "StartNode7"
    name: "SetDefaultShippingInvoiceAddress"
    mode: "private"
    strict: true
    inputs:
      - key: "PreferredBillingAddress"
        type: "java.lang.Boolean"
        required: false
      - key: "PreferredShippingAddress"
        type: "java.lang.Boolean"
        required: false
      - key: "Address"
        type: "com.intershop.beehive.core.capi.profile.Address"
        required: true
  - id: "StartNode8"
    name: "GetWebFormSelectorSuffix"
    mode: "private"
    strict: true
    inputs:
      - key: "WebFormSelector"
        type: "java.lang.String"
        required: false
      - key: "WebFormFileNamePrefix"
        type: "java.lang.String"
        required: false

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Object: "AddressBO"
      InVector: "AddressBOVector"
      OutVector: "AddressBOVector"
      Iterator: "AddressBOIterator"
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "AddressBOVector"
      Object: "AddressBO"
      OutVector: "AddressBOVector"
      Iterator: "AddressBOIterator"
  - id: "CallNode1"
    type: "call"
    ref: "Super:Get"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessAddress-GetAddress"
  - id: "CallNode3"
    type: "call"
    ref: "Super:GetDefaultAddress"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessAddress-SetPreferredAddress"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessAddress-SetPreferredAddress"
  - id: "CallNode7"
    type: "call"
    ref: "This:SetDefaultShippingInvoiceAddress"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "WebFormSelectorSuffix."
    bindings:
      String1: "WebFormSelector"
      Concatenated: "WebFormSelectorName"
  - id: "ConcatenateStrings3"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "Address"
    bindings:
      String1: "WebFormSelectorSuffix"
      String0: "WebFormFileNamePrefix"
      Concatenated: "WebFormFileName"
  - id: "CreateAddress1"
    type: "pipelet"
    ref: "CreateAddress"
    bindings:
      Fax: "null"
      County: "null"
      CompanyTranscription: "null"
      ConfirmFax: "null"
      ConfirmMail: "null"
      CustomAddressTypeCode: "null"
      FirstNameTranscription: "null"
      Homepage: "null"
      Honorific: "null"
      JobTitle: "null"
      LastNameTranscription: "null"
      PhoneBusiness: "null"
      PhoneBusinessDirect: "null"
      PostBox: "null"
      Prefecture: "null"
      Province: "null"
      Region: "null"
      SecondLastName: "null"
      StreetTranscription: "null"
      Suffix: "null"
      UseForInstallTo: "null"
      UseForServiceTo: "null"
      UseForShipFrom: "null"
      Profile: "User:Profile"
  - id: "DecisionNode22"
    type: "decision"
    condition: "WebFormSelector"
  - id: "DecisionNode3"
    type: "decision"
    condition: "AddressesCollection"
  - id: "DecisionNode5"
    type: "decision"
    condition: "AddressesIterator"
  - id: "DecisionNode6"
    type: "decision"
    condition: "PreferredBillingAddress"
  - id: "DecisionNode7"
    type: "decision"
    condition: "PreferredShippingAddress"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "Address"
        type: "com.intershop.beehive.core.capi.profile.Address"
        guaranteed: true
  - id: "EndNode11"
    type: "end"
    strict: true
    outputs:
      - key: "AddressBOIterator"
        type: "java.util.Iterator"
        guaranteed: false
  - id: "EndNode13"
    type: "end"
    strict: true
    outputs:
      - key: "WebFormSelectorSuffix"
        type: "java.lang.String"
        guaranteed: true
      - key: "WebFormFileName"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "ERROR_Address"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "Address"
        type: "com.intershop.beehive.core.capi.profile.Address"
        guaranteed: true
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "ERROR_Address"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "Address"
        type: "com.intershop.beehive.core.capi.profile.Address"
        guaranteed: true
  - id: "EndNode7"
    type: "end"
    strict: true
    outputs:
      - key: "PreferredBillingAddress"
        type: "java.lang.Boolean"
        guaranteed: false
      - key: "PreferredShippingAddress"
        type: "java.lang.Boolean"
        guaranteed: false
      - key: "UseForInvoiceTo"
        type: "java.lang.Boolean"
        guaranteed: true
      - key: "UseForShipTo"
        type: "java.lang.Boolean"
        guaranteed: true
      - key: "Address"
        type: "com.intershop.beehive.core.capi.profile.Address"
        guaranteed: true
  - id: "EndNode9"
    type: "end"
    strict: true
    outputs:
      - key: "Address"
        type: "com.intershop.beehive.core.capi.profile.Address"
        guaranteed: true
  - id: "GetAddressBO1"
    type: "pipelet"
    ref: "GetAddressBO"
    bindings:
      AddressID: "Address:AddressID"
  - id: "GetAddressBO2"
    type: "pipelet"
    ref: "GetAddressBO"
    bindings:
      AddressID: "Address:AddressID"
  - id: "GetPropertyValue1"
    type: "pipelet"
    ref: "GetPropertyValue"
    config:
      DefaultPropertyValue: "Default"
      PropertyType: "Global"
    bindings:
      PropertyName: "WebFormSelectorName"
      PropertyValue: "WebFormSelectorSuffix"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "Error-Page"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "\"NoAddressFound\""
      OutValue_1: "ERROR_Address"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"(Boolean)false\""
      OutValue_1: "UseForInvoiceTo"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"(Boolean)false\""
      OutValue_1: "UseForShipTo"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "PreferredBillingAddress"
      OutValue_1: "UseForInvoiceTo"
  - id: "KeyMapper6"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "PreferredShippingAddress"
      OutValue_1: "UseForShipTo"
  - id: "KeyMapper7"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "PreferredBillingAddress"
      InValue_2: "PreferredShippingAddress"
      OutValue_1: "UseForInvoiceTo"
      OutValue_2: "UseForShipTo"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "RemoveAddress1"
    type: "pipelet"
    ref: "RemoveAddress"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "WebFormSelectorSuffix"
      Value: "default"
      ValueType: "Dictionary Value"
  - id: "UpdateAddress1"
    type: "pipelet"
    ref: "UpdateAddress"
    bindings:
      Profile: "User:Profile"

links:
  - from: "StartNode5"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "RemoveAddress1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "GetPropertyValue1"
    into: "in"
  - from: "CallNode2"
    via: "ERROR"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode22"
    via: "no"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "DecisionNode22"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "GetAddressBO1"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "KeyMapper2"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "GetAddressBO2"
    into: "in"
  - from: "GetAddressBO2"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "JoinNode12"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "GetAddressBO1"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "UpdateAddress1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "KeyMapper6"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "StartNode4"
    via: "next"
    to: "KeyMapper7"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JumpNode1"
    into: "in"
  - from: "RemoveAddress1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "RemoveAddress1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "ConcatenateStrings3"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CreateAddress1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "StartNode10"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "DecisionNode5"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "UpdateAddress1"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "LoopNode1"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "EndNode9"
    into: "in"
  - from: "GetPropertyValue1"
    via: "error"
    to: "JoinNode12"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "LoopNode2"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "CallNode1"
    via: "ERROR"
    to: "KeyMapper1"
    into: "in"
  - from: "GetPropertyValue1"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "KeyMapper7"
    via: "next"
    to: "CreateAddress1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode11"
    into: "in"
  - from: "ConcatenateStrings3"
    via: "next"
    to: "EndNode13"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "EndNode11"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "KeyMapper5"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "DecisionNode7"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "KeyMapper6"
    into: "in"
  - from: "DecisionNode22"
    via: "yes"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "KeyMapper3"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode11"
    into: "in1"
