flow: "ProcessProductConfiguration"
kind: "process"

entries:
  - id: "StartNode1"
    name: "UpdateProductConfiguration"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductConfigurationBO"
        type: "com.intershop.component.productconfiguration.capi.configuration.ProductConfigurationBO"
        required: true
      - key: "Fixed"
        type: "java.lang.Boolean"
        required: false
      - key: "Temporary"
        type: "java.lang.Boolean"
        required: false
  - id: "StartNode2"
    name: "CreateProductConfiguration"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductBO"
        type: "com.intershop.component.product.capi.ProductBO"
        required: true
      - key: "ProductConfigurationSetBO"
        type: "com.intershop.component.productconfiguration.capi.set.ProductConfigurationSetBO"
        required: true
      - key: "User"
        type: "com.intershop.beehive.core.capi.user.User"
        required: true
      - key: "ProductConfigurationBORepository"
        type: "com.intershop.component.productconfiguration.capi.configuration.ProductConfigurationBORepository"
        required: false
  - id: "StartNode3"
    name: "RemoveProductConfiguration"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductConfigurationBO"
        type: "com.intershop.component.productconfiguration.capi.configuration.ProductConfigurationBO"
        required: true
      - key: "ProductConfigurationBORepository"
        type: "com.intershop.component.productconfiguration.capi.configuration.ProductConfigurationBORepository"
        required: true
  - id: "StartNode4"
    name: "CreatePreConfiguration"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductBO"
        type: "com.intershop.component.product.capi.ProductBO"
        required: true
      - key: "ProductConfigurationSetBO"
        type: "com.intershop.component.productconfiguration.capi.set.ProductConfigurationSetBO"
        required: true
      - key: "Name"
        type: "java.lang.String"
        required: false
      - key: "ProductPreConfigurationBORepository"
        type: "ProductPreConfigurationBORepository"
        required: false
  - id: "StartNode5"
    name: "UpdatePreConfiguration"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductPreConfigurationBO"
        type: "com.intershop.component.productconfiguration.capi.configuration.ProductPreConfigurationBO"
        required: true
      - key: "Name"
        type: "java.lang.String"
        required: false
  - id: "StartNode6"
    name: "RemovePreConfiguration"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductPreConfigurationBO"
        type: "com.intershop.component.productconfiguration.capi.configuration.ProductPreConfigurationBO"
        required: true
      - key: "ProductPreConfigurationBORepository"
        type: "com.intershop.component.productconfiguration.capi.configuration.ProductPreConfigurationBORepository"
        required: true
  - id: "StartNode7"
    name: "CreateCustomConfiguration"
    mode: "private"
    strict: true
    inputs:
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "SectionMap"
        type: "java.util.Map"
        required: true
      - key: "ProductBO"
        type: "com.intershop.component.product.capi.ProductBO"
        required: true
      - key: "LayoutID"
        type: "java.lang.String"
        required: true
      - key: "User"
        type: "com.intershop.beehive.core.capi.user.User"
        required: false
      - key: "ProductConfigurationBORepository"
        type: "com.intershop.component.productconfiguration.capi.configuration.ProductConfigurationBORepository"
        required: false
      - key: "ProductConfigurationSetBORepository"
        type: "com.intershop.component.productconfiguration.capi.set.ProductConfigurationSetBORepository"
        required: false

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessProductConfiguration-CreateProductConfiguration"
    bindings:
      ProductConfigurationBO: "ProductConfiguration"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessProductConfigurationOptionSelection-CreateForValue"
    bindings:
      Option: "ProductConfigurationOption"
      Customization: "ProductConfiguration"
  - id: "CreateProductConfiguration1"
    type: "pipelet"
    ref: "CreateProductConfiguration"
  - id: "CreateProductPreConfiguration1"
    type: "pipelet"
    ref: "CreateProductPreConfiguration"
  - id: "DecisionNode1"
    type: "decision"
    condition: "BaseProduct_ConfigurationSetBORepository"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ProductConfigurationBORepository"
  - id: "DecisionNode3"
    type: "decision"
    condition: "ProductPreConfigurationBORepository"
  - id: "DecisionNode4"
    type: "decision"
    condition: "ProductConfigurationBORepository"
  - id: "DecisionNode5"
    type: "decision"
    condition: "ProductConfigurationSetBORepository"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ProductConfigurationBO"
        type: "com.intershop.component.productconfiguration.capi.configuration.ProductConfigurationBO"
        guaranteed: true
  - id: "EndNode10"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "ProductConfigurationBO"
        type: "com.intershop.component.productconfiguration.capi.configuration.ProductConfigurationBO"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "ProductPreConfigurationBO"
        type: "com.intershop.component.productconfiguration.capi.configuration.ProductPreConfigurationBO"
        guaranteed: true
  - id: "EndNode6"
    type: "end"
    strict: true
  - id: "EndNode7"
    type: "end"
    strict: true
    outputs:
      - key: "ProductPreConfigurationBO"
        type: "com.intershop.component.productconfiguration.capi.configuration.ProductPreConfigurationBO"
        guaranteed: true
  - id: "EndNode8"
    type: "end"
    strict: true
  - id: "EndNode9"
    type: "end"
    strict: true
    outputs:
      - key: "ProductConfiguration"
        type: "com.intershop.component.productconfiguration.capi.configuration.ProductConfigurationBO"
        guaranteed: true
  - id: "GetApplicationBO1"
    type: "pipelet"
    ref: "GetApplicationBO"
  - id: "GetEntryFromMap1"
    type: "pipelet"
    ref: "GetEntryFromMap"
    bindings:
      InMap: "OptionMap"
      Key: "OptionID"
  - id: "GetProductConfigurationSetBOByID1"
    type: "pipelet"
    ref: "GetProductConfigurationSetBOByID"
    bindings:
      SetID: "LayoutID"
      ProductConfigurationSetBORepository: "BaseProduct_ConfigurationSetBORepository"
  - id: "GetProductConfigurationSetBOByID2"
    type: "pipelet"
    ref: "GetProductConfigurationSetBOByID"
    bindings:
      SetID: "LayoutID"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ProductConfigurationSection:OptionByID(OptionID)"
      OutValue_1: "ProductConfigurationOption"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ProductConfigurationSetBO:SectionByID(SectionID)"
      OutValue_1: "ProductConfigurationSection"
      InValue_2: "SectionMap:get(SectionID)"
      OutValue_2: "OptionMap"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Repository(\"ProductConfigurationSetBORepository\", ProductBO:BaseProduct:Repository:RepositoryID)"
      OutValue_1: "BaseProduct_ConfigurationSetBORepository"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "RemoveProductConfiguration1"
    type: "pipelet"
    ref: "RemoveProductConfiguration"
  - id: "RemoveProductPreConfiguration1"
    type: "pipelet"
    ref: "RemoveProductPreConfiguration"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_KEY"
      ValueType: "Dictionary Value"
      Value: "Mandatory Repository not found in dictionary."
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_KEY"
      ValueType: "Dictionary Value"
      Value: "Mandatory Repository not found in dictionary."
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_KEY"
      ValueType: "Dictionary Value"
      Value: "Mandatory Repository not found in dictionary."
  - id: "UpdateProductConfiguration1"
    type: "pipelet"
    ref: "UpdateProductConfiguration"
  - id: "UpdateProductPreConfiguration1"
    type: "pipelet"
    ref: "UpdateProductPreConfiguration"

links:
  - from: "StartNode3"
    via: "next"
    to: "RemoveProductConfiguration1"
    into: "in"
  - from: "CreateProductPreConfiguration1"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode3"
    into: "in2"
  - from: "StartNode5"
    via: "next"
    to: "UpdateProductPreConfiguration1"
    into: "in"
  - from: "UpdateProductPreConfiguration1"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "RemoveProductPreConfiguration1"
    into: "in"
  - from: "RemoveProductPreConfiguration1"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "KeyMapper3"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "GetApplicationBO1"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "CreateProductConfiguration1"
    via: "error"
    to: "EndNode4"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "GetEntryFromMap1"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "EndNode9"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "LoopNode2"
    via: "do"
    to: "KeyMapper2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "GetEntryFromMap1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "GetProductConfigurationSetBOByID1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "GetProductConfigurationSetBOByID1"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "CreateProductPreConfiguration1"
    via: "error"
    to: "EndNode6"
    into: "in"
  - from: "GetProductConfigurationSetBOByID2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetProductConfigurationSetBOByID1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode10"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetProductConfigurationSetBOByID2"
    via: "error"
    to: "GetApplicationBO1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "CreateProductConfiguration1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "CreateProductPreConfiguration1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "EndNode10"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode4"
    via: "yes"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "GetProductConfigurationSetBOByID2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "CreateProductConfiguration1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "UpdateProductConfiguration1"
    into: "in"
  - from: "UpdateProductConfiguration1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "RemoveProductConfiguration1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "SetDictionaryValue2"
    into: "in"
