flow: "ProcessActionConfiguration"
kind: "process"

entries:
  - id: "StartNode1"
    name: "UpdateConfigurationParameters"
    mode: "private"
    strict: true
    inputs:
      - key: "EditAction"
        type: "com.intershop.beehive.core.capi.domain.ExtensibleObject"
        required: true
      - key: "ActionForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        required: true
      - key: "ActionDescriptorRegistry"
        type: "com.intershop.component.foundation.capi.action.ActionDescriptorRegistry"
        required: false
  - id: "StartNode15"
    name: "CreateActionForm"
    mode: "private"
    strict: false
    inputs:
      - key: "EditAction"
        type: "com.intershop.component.foundation.capi.action.Action"
        required: false
      - key: "ActionDescriptorRegistry"
        type: "com.intershop.component.foundation.capi.action.ActionDescriptorRegistry"
        required: true
      - key: "AddValidators"
        type: "java.lang.String"
        required: false
      - key: "FormName"
        type: "java.lang.String"
        required: false
      - key: "FormResource"
        type: "java.lang.String"
        required: false
  - id: "StartNode2"
    name: "PrepareDescriptors"
    mode: "private"
    strict: true
    inputs:
      - key: "ActionDescriptorRegistry"
        type: "com.intershop.component.foundation.capi.action.ActionDescriptorRegistry"
        required: true
  - id: "StartNode3"
    name: "RemoveAction"
    mode: "private"
    strict: true
    inputs:
      - key: "ActionRepository"
        type: "com.intershop.component.foundation.capi.action.ActionRepository"
        required: false
      - key: "SelectedActions"
        type: "java.util.Iterator"
        required: false
  - id: "StartNode4"
    name: "ResolveActionDescriptor"
    mode: "private"
    strict: true
    inputs:
      - key: "ActionForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        required: true
      - key: "ActionDescriptors"
        type: "java.util.Iterator"
        required: true
      - key: "ActionDescriptorRegistry"
        type: "com.intershop.component.foundation.capi.action.ActionDescriptorRegistry"
        required: true
  - id: "StartNode5"
    name: "CreateAction"
    mode: "private"
    strict: true
    inputs:
      - key: "ActionDescriptorRegistry"
        type: "com.intershop.component.foundation.capi.action.ActionDescriptorRegistry"
        required: false
      - key: "ActionForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        required: false
      - key: "ActionRepository"
        type: "com.intershop.component.foundation.capi.action.ActionRepository"
        required: false
      - key: "Owner"
        type: "com.intershop.beehive.core.capi.domain.PersistentObject"
        required: true

steps:
  - id: "AddEntryToMap1"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "ActionDescriptorMap"
      Key: "ActionDescriptor:ID"
      Value: "ActionDescriptor"
      OutMap: "ActionDescriptorMap"
  - id: "AddEntryToMap2"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "FormParameterValuesMap"
      OutMap: "FormParameterValuesMap"
      Key: "ActionForm:get(Param:Name)"
      Value: "EditAction:getAttribute(Param:Name)"
  - id: "AddEntryToMap5"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "ActionTypesMap"
      Key: "ActionDescriptor:Type"
      Value: "ActionDescriptor:TypeName"
      OutMap: "ActionTypesMap"
      Keys: "ActionTypes"
  - id: "AddFormFieldDefinition1"
    type: "pipelet"
    ref: "AddFormFieldDefinition"
    bindings:
      FormParameter: "ActionForm:get(Param:Name)"
      Name: "Field:Name"
  - id: "AddFormParameterDefinition1"
    type: "pipelet"
    ref: "AddFormParameterDefinition"
    config:
      Optional: true
    bindings:
      Form: "ActionForm"
      FormatProperties: "Param:FormatProperties"
      Formatter: "Param:Formatter"
      MessageID: "Param:MessageID"
      Name: "Param:Name"
      Type: "Param:Type"
      ValidateProperties: "null"
      Validator: "null"
  - id: "AddFormParameterDefinition2"
    type: "pipelet"
    ref: "AddFormParameterDefinition"
    config:
      Optional: true
    bindings:
      Form: "ActionForm"
      FormatProperties: "Param:FormatProperties"
      Formatter: "Param:Formatter"
      MessageID: "Param:MessageID"
      Name: "Param:Name"
      Type: "Param:Type"
      ValidateProperties: "Param:ValidateProperties"
      Validator: "Param:Validator"
  - id: "AddMultipleEntriesToMap1"
    type: "pipelet"
    ref: "AddMultipleEntriesToMap"
    config:
      Mode: "OverwriteValue"
    bindings:
      OutMap: "FormParameterValuesMap"
      Key1: "ActionForm:ActionType"
      Key2: "ActionForm:ActionDescriptorID"
      Key3: "ActionForm:ActionID"
      Value1: "EditAction:Descriptor:Type"
      Value2: "EditAction:ActionDescriptorID"
      Value3: "EditAction:UUID"
  - id: "AddValidateDefinition1"
    type: "pipelet"
    ref: "AddValidateDefinition"
    bindings:
      Target: "ActionForm:get(Param:Name)"
      Validator: "ValidatorID"
      ValidationProperties: "Param:ValidatorProperties(ValidatorID)"
  - id: "AddValidateDefinition2"
    type: "pipelet"
    ref: "AddValidateDefinition"
    bindings:
      Target: "ActionForm:get(Param:Name):get(Field:Name)"
      Validator: "ValidatorID"
      ValidationProperties: "Field:ValidatorProperties(ValidatorID)"
  - id: "CallNode1"
    type: "call"
    ref: "This:ResolveActionDescriptor"
  - id: "CreateAction1"
    type: "pipelet"
    ref: "CreateAction"
  - id: "CreateForm4"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormResource: "ActionConfiguration"
      FormName: "ActionConfiguration"
    bindings:
      Form: "ActionForm"
  - id: "DecisionNode1"
    type: "decision"
    condition: "AddValidators"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ActionForm:ActionDescriptorID:ValueMissing"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Size"
  - id: "DecisionNode5"
    type: "decision"
    condition: "ActionDescriptor"
  - id: "DecisionNode7"
    type: "decision"
    condition: "EditAction:ActionDescriptorID"
  - id: "DecisionNode9"
    type: "decision"
    condition: "EditAction:getAttribute(Param:Name)"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "ActionDescriptor"
        type: "com.intershop.component.foundation.capi.action.ActionDescriptor"
        guaranteed: false
  - id: "EndNode4"
    type: "end"
    strict: false
    outputs:
      - key: "ActionForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        guaranteed: true
      - key: "FormParameterValuesMap"
        type: "java.util.Map"
        guaranteed: true
  - id: "EndNode5"
    type: "end"
    strict: true
  - id: "EndNode6"
    type: "end"
    strict: true
  - id: "EndNode7"
    type: "end"
    strict: true
    outputs:
      - key: "Action"
        type: "com.intershop.component.foundation.capi.action.Action"
        guaranteed: true
  - id: "EndNode8"
    type: "end"
    strict: true
    outputs:
      - key: "ActionDescriptorMap"
        type: "java.util.Map"
        guaranteed: false
      - key: "ActionDescriptors"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "ActionTypes"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "ActionTypesMap"
        type: "java.util.Map"
        guaranteed: true
  - id: "GetActionByID1"
    type: "pipelet"
    ref: "GetActionByID"
  - id: "GetActionDescriptorByID1"
    type: "pipelet"
    ref: "GetActionDescriptorByID"
    bindings:
      ActionDescriptorID: "EditAction:ActionDescriptorID"
  - id: "GetActionDescriptorByID3"
    type: "pipelet"
    ref: "GetActionDescriptorByID"
    bindings:
      ActionDescriptorID: "EditAction:ActionDescriptorID"
  - id: "GetActionDescriptorByID4"
    type: "pipelet"
    ref: "GetActionDescriptorByID"
    bindings:
      ActionDescriptorID: "ActionForm:ActionDescriptorID:Value"
  - id: "GetActionDescriptorByID5"
    type: "pipelet"
    ref: "GetActionDescriptorByID"
    bindings:
      ActionDescriptorID: "ActionForm:ActionDescriptorID:Value"
  - id: "GetActionDescriptors1"
    type: "pipelet"
    ref: "GetActionDescriptors"
    config:
      SortByName: true
  - id: "GetFilterIterator1"
    type: "pipelet"
    ref: "GetFilterIterator"
    config:
      FilterConditionClassName: "com.intershop.component.foundation.internal.application.ConfigurationDescriptorTypeFilter"
    bindings:
      FilterConditionParam1: "ActionForm:ActionType:Value"
      Iterator: "ActionDescriptors"
  - id: "GetFirstElementOfIterator1"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      Iterator: "FilterIterator"
      FirstElement: "ActionDescriptor"
  - id: "GetIteratorSize1"
    type: "pipelet"
    ref: "GetIteratorSize"
    bindings:
      Iterator: "FilterIterator"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode10"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "LoopNode3"
    type: "loop"
  - id: "LoopNode4"
    type: "loop"
  - id: "LoopNode8"
    type: "loop"
  - id: "MapFormToObject2"
    type: "pipelet"
    ref: "MapFormToObject"
    config:
      NameFilterType: "exclude"
      NameFilterList: "ActionID, ActionDescriptorID, TargetActionID, ActionType, ActionDomainID"
    bindings:
      TargetObject: "EditAction"
      Form: "ActionForm"
      NameFilterList: "null"
  - id: "RemoveAction1"
    type: "pipelet"
    ref: "RemoveAction"
  - id: "SetFormParameterValue1"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      FormParameter: "ActionForm:ActionDescriptorID"
      Value: "ActionDescriptor:ID"
  - id: "UpdateConfigurationParameters2"
    type: "pipelet"
    ref: "UpdateConfigurationParameters"
    bindings:
      ConfigurationDescriptor: "ActionDescriptor"
      ExtensibleObject: "Action"
      Form: "ActionForm"
  - id: "ValidateForm5"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "ActionForm"

links:
  - from: "DecisionNode7"
    via: "yes"
    to: "GetActionDescriptorByID1"
    into: "in"
  - from: "CallNode1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "AddMultipleEntriesToMap1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "CallNode1"
    into: "in"
  - from: "ValidateForm5"
    via: "error"
    to: "JoinNode11"
    into: "in2"
  - from: "LoopNode3"
    via: "do"
    to: "AddValidateDefinition1"
    into: "in"
  - from: "LoopNode3"
    via: "next"
    to: "JoinNode8"
    into: "in2"
  - from: "AddValidateDefinition1"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "AddEntryToMap2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "AddFormParameterDefinition1"
    into: "in"
  - from: "GetActionDescriptorByID1"
    via: "next"
    to: "AddMultipleEntriesToMap1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "LoopNode10"
    via: "do"
    to: "AddFormFieldDefinition1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "GetFilterIterator1"
    into: "in"
  - from: "AddFormParameterDefinition2"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "GetActionDescriptorByID3"
    via: "next"
    to: "MapFormToObject2"
    into: "in"
  - from: "MapFormToObject2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "LoopNode4"
    into: "loop"
  - from: "JoinNode11"
    via: "next"
    to: "DecisionNode7"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetActionDescriptorByID3"
    into: "in"
  - from: "AddValidateDefinition2"
    via: "next"
    to: "LoopNode8"
    into: "loop"
  - from: "JoinNode8"
    via: "next"
    to: "LoopNode10"
    into: "in"
  - from: "GetActionDescriptors1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "AddEntryToMap1"
    into: "in"
  - from: "AddEntryToMap1"
    via: "next"
    to: "AddEntryToMap5"
    into: "in"
  - from: "AddEntryToMap5"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "StartNode2"
    via: "next"
    to: "GetActionDescriptors1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "GetActionDescriptorByID4"
    into: "in"
  - from: "ValidateForm5"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "GetActionDescriptorByID4"
    via: "next"
    to: "CreateAction1"
    into: "in"
  - from: "CreateAction1"
    via: "next"
    to: "UpdateConfigurationParameters2"
    into: "in"
  - from: "CreateAction1"
    via: "error"
    to: "EndNode6"
    into: "in"
  - from: "GetActionByID1"
    via: "next"
    to: "RemoveAction1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "GetActionByID1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "StartNode3"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "GetActionByID1"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "UpdateConfigurationParameters2"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "CreateForm4"
    via: "next"
    to: "ValidateForm5"
    into: "in"
  - from: "RemoveAction1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "LoopNode10"
    via: "next"
    to: "DecisionNode9"
    into: "in"
  - from: "LoopNode4"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "LoopNode8"
    via: "do"
    to: "AddValidateDefinition2"
    into: "in"
  - from: "AddFormFieldDefinition1"
    via: "next"
    to: "LoopNode8"
    into: "in"
  - from: "LoopNode8"
    via: "next"
    to: "LoopNode10"
    into: "loop"
  - from: "DecisionNode2"
    via: "yes"
    to: "GetActionDescriptorByID5"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "GetIteratorSize1"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "GetFilterIterator1"
    via: "next"
    to: "GetIteratorSize1"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "LoopNode4"
    into: "in"
  - from: "GetFilterIterator1"
    via: "error"
    to: "JoinNode9"
    into: "in1"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode9"
    into: "in2"
  - from: "LoopNode4"
    via: "do"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "AddFormParameterDefinition2"
    into: "in"
  - from: "AddFormParameterDefinition1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode3"
    via: "yes"
    to: "GetFirstElementOfIterator1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "GetFirstElementOfIterator1"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "DecisionNode9"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "GetFirstElementOfIterator1"
    via: "next"
    to: "SetFormParameterValue1"
    into: "in"
  - from: "GetActionDescriptorByID5"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "SetFormParameterValue1"
    via: "next"
    to: "JoinNode7"
    into: "in3"
  - from: "DecisionNode9"
    via: "yes"
    to: "AddEntryToMap2"
    into: "in"
  - from: "StartNode15"
    via: "next"
    to: "CreateForm4"
    into: "in"
