flow: "ProcessOnEdit_comp_search"
kind: "process"

entries:
  - id: "StartNode3"
    name: "SearchBox"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode10"
    type: "call"
    ref: "ProcessConfigurationParameterCtnrWebForm-RemoveFormParameterValues"
    bindings:
      ParameterValues: "CategoryReferences"
      ConfigurationParameterName: "SelectedConfigurationParameterName"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessConfigurationParameterCtnrWebForm-AddFormParameterValue"
    bindings:
      ConfigurationParameterName: "SelectedConfigurationParameterName"
      ParameterValues: "CategoryReferences"
  - id: "DecisionNode1"
    type: "decision"
    condition: "CategoryReferences"
  - id: "DecisionNode2"
    type: "decision"
    condition: "CurrentChannel"
  - id: "DecisionNode3"
    type: "decision"
    condition: "SelectedConfigurationParameterName"
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentChannel:RepositoryDomain:Site"
      OutValue_1: "Site"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentDomain"
      OutValue_1: "Site"

links:
  - from: "CallNode7"
    via: "next"
    to: "JoinNode4"
    into: "in2"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "StartNode3"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode10"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode3"
    via: "yes"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "DecisionNode2"
    into: "in"
