flow: "ProcessProductSynchronization"
kind: "process"

entries:
  - id: "Start1"
    name: "AddAvailableParent"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "SynchronizeRepository"
    mode: "private"
    strict: false
    inputs:
      - key: "Repository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: false
  - id: "Start5"
    name: "GetParentRepositories"
    mode: "private"
    strict: false
    inputs:
      - key: "SourceObjectUUIDs"
        type: "java.util.Iterator"
        required: false

steps:
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "ParentReps"
      Iterator: "ParentRepositories"
      Object: "ParentRepository"
      Objects: "null"
      OutVector: "ParentReps"
  - id: "Call1"
    type: "call"
    ref: "ProcessProductSynchronization-AddAvailableParent"
  - id: "Call2"
    type: "call"
    ref: "BatchProcessSynchronization-Initialize"
  - id: "Call3"
    type: "call"
    ref: "BatchProcessSynchronization-Synchronize"
  - id: "Call4"
    type: "call"
    ref: "GetSyncProducts-ByRepositories"
  - id: "Call6"
    type: "call"
    ref: "ProcessProductSynchronization-GetParentRepositories"
  - id: "Call7"
    type: "call"
    ref: "BatchProcessSynchronization-Finish"
  - id: "CheckForSynchronization1"
    type: "pipelet"
    ref: "CheckForSynchronization"
    bindings:
      TargetObject: "Repository"
  - id: "CreatePageableFromIterator1"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    bindings:
      Iterator: "ParentRepositories"
      Pageable: "ParentRepositoriesPageable"
  - id: "CreatePageableSequence1"
    type: "pipelet"
    ref: "CreatePageableSequence"
    bindings:
      PageableIterator: "Products"
      PageableSequence: "Objects"
  - id: "Decision1"
    type: "decision"
    condition: "JobConfiguration:Status"
  - id: "Decision2"
    type: "decision"
    condition: "JobConfiguration"
  - id: "Decision3"
    type: "decision"
    condition: "SyncRecord:JobUUID"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ParentRepositories"
  - id: "DecisionNode2"
    type: "decision"
    condition: "SyncRecord:JobUUID"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "End7"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "GetJobConfiguration1"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobDomain: "null"
      JobDomainName: "null"
      JobName: "null"
      JobUUID: "SyncRecord:JobUUID"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "ParentRepository"
  - id: "GetSyncRecord1"
    type: "pipelet"
    ref: "GetSyncRecord"
    bindings:
      SourceObject: "ParentRepository"
      TargetObject: "Repository"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Repository:UUID"
      InValue_2: "ParentRepositoriesPageable:ID"
      OutValue_1: "CurrentRepositoryUUID"
      OutValue_2: "ParentRepositoriesID"
  - id: "Loop3"
    type: "loop"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "Parents"
  - id: "SwitchToNextPage1"
    type: "pipelet"
    ref: "SwitchToNextPage"
    bindings:
      PageableIterator: "Objects"

links:
  - from: "Start2"
    via: "next"
    to: "CheckForSynchronization1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "Start1"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "Decision1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join2"
    into: "in2"
  - from: "Join2"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Decision1"
    via: "yes"
    to: "DecisionNode2"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "DecisionNode2"
    via: "yes"
    to: "JoinNode1"
    into: "in1"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "GetSyncRecord1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Loop3"
    into: "in"
  - from: "GetSyncRecord1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "error"
    to: "Join7"
    into: "in1"
  - from: "Join7"
    via: "next"
    to: "Join6"
    into: "in3"
  - from: "Call1"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "GetSyncRecord1"
    via: "error"
    to: "Join7"
    into: "in2"
  - from: "Decision3"
    via: "yes"
    to: "GetJobConfiguration1"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Join9"
    into: "in1"
  - from: "Join9"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "GetJobConfiguration1"
    via: "error"
    to: "Join9"
    into: "in2"
  - from: "CreatePageableFromIterator1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Loop3"
    via: "do"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "CreatePageableSequence1"
    into: "in"
  - from: "Call2"
    via: "Error"
    to: "Join5"
    into: "in3"
  - from: "Call7"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Call3"
    via: "next"
    to: "SwitchToNextPage1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "Join4"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "SwitchToNextPage1"
    via: "next"
    to: "Join4"
    into: "in2"
  - from: "SwitchToNextPage1"
    via: "error"
    to: "Call7"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "Loop3"
    into: "loop"
  - from: "Join5"
    via: "next"
    to: "End4"
    into: "in"
  - from: "CreatePageableSequence1"
    via: "next"
    to: "CreatePageableFromIterator1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "Call4"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "Loop3"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "End7"
    into: "in"
  - from: "CheckForSynchronization1"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "CheckForSynchronization1"
    via: "error"
    to: "End3"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join1"
    into: "in2"
