flow: "ProcessAddressSearch"
kind: "process"

entries:
  - id: "StartNode17"
    name: "ParametricSearch"
    mode: "private"
    strict: true
    inputs:
      - key: "Profile"
        type: "com.intershop.beehive.core.capi.profile.Profile"
        required: false
      - key: "TypeCode"
        type: "java.lang.Integer"
        required: false
      - key: "AddressSearchParameters"
        type: "java.util.Map"
        required: false
      - key: "SortDirection"
        type: "java.lang.String"
        required: false
      - key: "SortByAddress"
        type: "java.lang.String"
        required: false
      - key: "Search_AddressName"
        type: "java.lang.String"
        required: false
      - key: "Country"
        type: "java.lang.String"
        required: false
      - key: "Search_State"
        type: "java.lang.String"
        required: false
      - key: "Search_ZIP"
        type: "java.lang.String"
        required: false
      - key: "Search_City"
        type: "java.lang.String"
        required: false
      - key: "Search_Street"
        type: "java.lang.String"
        required: false
      - key: "Search_AddressNr"
        type: "java.lang.String"
        required: false
      - key: "CountryCode"
        type: "java.lang.String"
        required: false

steps:
  - id: "DecisionNode11"
    type: "decision"
    condition: "Search_City"
  - id: "DecisionNode12"
    type: "decision"
    condition: "Search_Street"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Search_AddressName"
  - id: "DecisionNode5"
    type: "decision"
    condition: "Search_AddressNr"
  - id: "DecisionNode8"
    type: "decision"
    condition: "Search_State"
  - id: "DecisionNode9"
    type: "decision"
    condition: "Search_ZIP"
  - id: "EndNode10"
    type: "end"
    strict: false
  - id: "EndNode11"
    type: "end"
    strict: false
  - id: "EndNode12"
    type: "end"
    strict: false
  - id: "EndNode13"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "Addresses"
        type: "com.intershop.beehive.core.capi.paging.PageableIterator"
        guaranteed: false
  - id: "EndNode7"
    type: "end"
    strict: false
  - id: "EndNode9"
    type: "end"
    strict: false
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      DefaultPageSize: 15
      QueryName: "address/SearchAddressesByProfile"
    bindings:
      Parameters: "AddressSearchParameters"
      SearchResult: "Addresses"
  - id: "JoinNode19"
    type: "join"
  - id: "JoinNode20"
    type: "join"
  - id: "JoinNode23"
    type: "join"
  - id: "JoinNode24"
    type: "join"
  - id: "JoinNode26"
    type: "join"
  - id: "JoinNode27"
    type: "join"
  - id: "UpdateDictionary1"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "AddressNrExpression"
    bindings:
      InDictionary: "AddressSearchParameters"
      Value_01: "AddressNrExpression"
      OutDictionary: "AddressSearchParameters"
  - id: "UpdateDictionary11"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "StreetExpression"
    bindings:
      InDictionary: "AddressSearchParameters"
      Value_01: "StreetExpression"
      OutDictionary: "AddressSearchParameters"
  - id: "UpdateDictionary2"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "AddressNameExpression"
    bindings:
      InDictionary: "AddressSearchParameters"
      Value_01: "AddressNameExpression"
      OutDictionary: "AddressSearchParameters"
  - id: "UpdateDictionary3"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "Profile"
      Name_02: "AddressTypeCode"
      Name_09: "SortDirection"
      Name_10: "SortByAddress"
      Name_03: "Country"
      Name_04: "CountryCode"
    bindings:
      Value_01: "Profile"
      InDictionary: "AddressSearchParameters"
      Value_09: "SortDirection"
      Value_10: "SortByAddress"
      Value_02: "TypeCode"
      Value_03: "Country"
      Value_04: "CountryCode"
      OutDictionary: "AddressSearchParameters"
  - id: "UpdateDictionary7"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "StateExpression"
    bindings:
      InDictionary: "AddressSearchParameters"
      Value_01: "StateExpression"
      OutDictionary: "AddressSearchParameters"
  - id: "UpdateDictionary8"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "ZIPExpression"
    bindings:
      InDictionary: "AddressSearchParameters"
      Value_01: "ZIPExpression"
      OutDictionary: "AddressSearchParameters"
  - id: "UpdateDictionary9"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "CityExpression"
    bindings:
      InDictionary: "AddressSearchParameters"
      Value_01: "CityExpression"
      OutDictionary: "AddressSearchParameters"
  - id: "VerifySearchTerm2"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowWildcards: "Multi & Single"
      AllowFuzzySearch: "default"
    bindings:
      UserSearchTerm: "Search_AddressName"
      SearchExpression: "AddressNameExpression"
  - id: "VerifySearchTerm3"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowWildcards: "Multi & Single"
      AllowFuzzySearch: "default"
    bindings:
      UserSearchTerm: "Search_AddressNr"
      SearchExpression: "AddressNrExpression"
  - id: "VerifySearchTerm5"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowWildcards: "Multi & Single"
      AllowFuzzySearch: "default"
    bindings:
      UserSearchTerm: "Search_State"
      SearchExpression: "StateExpression"
  - id: "VerifySearchTerm6"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowWildcards: "Multi & Single"
      AllowFuzzySearch: "default"
    bindings:
      UserSearchTerm: "Search_ZIP"
      SearchExpression: "ZIPExpression"
  - id: "VerifySearchTerm7"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowWildcards: "Multi & Single"
      AllowFuzzySearch: "default"
    bindings:
      UserSearchTerm: "Search_City"
      SearchExpression: "CityExpression"
  - id: "VerifySearchTerm9"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowWildcards: "Multi & Single"
      AllowFuzzySearch: "default"
    bindings:
      UserSearchTerm: "Search_Street"
      SearchExpression: "StreetExpression"

links:
  - from: "StartNode17"
    via: "next"
    to: "UpdateDictionary3"
    into: "in"
  - from: "VerifySearchTerm2"
    via: "next"
    to: "UpdateDictionary2"
    into: "in"
  - from: "VerifySearchTerm2"
    via: "error"
    to: "EndNode3"
    into: "in"
  - from: "UpdateDictionary2"
    via: "next"
    to: "JoinNode19"
    into: "in1"
  - from: "DecisionNode4"
    via: "yes"
    to: "JoinNode19"
    into: "in1"
  - from: "JoinNode27"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "VerifySearchTerm2"
    into: "in"
  - from: "UpdateDictionary3"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "VerifySearchTerm3"
    into: "in"
  - from: "VerifySearchTerm3"
    via: "next"
    to: "UpdateDictionary1"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "JoinNode20"
    into: "in1"
  - from: "UpdateDictionary1"
    via: "next"
    to: "JoinNode20"
    into: "in1"
  - from: "JoinNode20"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "VerifySearchTerm5"
    via: "next"
    to: "UpdateDictionary7"
    into: "in"
  - from: "DecisionNode8"
    via: "yes"
    to: "JoinNode23"
    into: "in1"
  - from: "VerifySearchTerm5"
    via: "error"
    to: "EndNode9"
    into: "in"
  - from: "UpdateDictionary7"
    via: "next"
    to: "JoinNode23"
    into: "in1"
  - from: "DecisionNode8"
    via: "no"
    to: "VerifySearchTerm5"
    into: "in"
  - from: "VerifySearchTerm6"
    via: "next"
    to: "UpdateDictionary8"
    into: "in"
  - from: "VerifySearchTerm3"
    via: "error"
    to: "EndNode7"
    into: "in"
  - from: "DecisionNode9"
    via: "yes"
    to: "JoinNode24"
    into: "in1"
  - from: "VerifySearchTerm6"
    via: "error"
    to: "EndNode10"
    into: "in"
  - from: "UpdateDictionary8"
    via: "next"
    to: "JoinNode24"
    into: "in1"
  - from: "DecisionNode9"
    via: "no"
    to: "VerifySearchTerm6"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "error"
    to: "EndNode12"
    into: "in"
  - from: "VerifySearchTerm7"
    via: "next"
    to: "UpdateDictionary9"
    into: "in"
  - from: "DecisionNode11"
    via: "yes"
    to: "JoinNode26"
    into: "in1"
  - from: "VerifySearchTerm7"
    via: "error"
    to: "EndNode11"
    into: "in"
  - from: "UpdateDictionary9"
    via: "next"
    to: "JoinNode26"
    into: "in1"
  - from: "DecisionNode11"
    via: "no"
    to: "VerifySearchTerm7"
    into: "in"
  - from: "JoinNode23"
    via: "next"
    to: "DecisionNode9"
    into: "in"
  - from: "JoinNode24"
    via: "next"
    to: "DecisionNode11"
    into: "in"
  - from: "JoinNode26"
    via: "next"
    to: "DecisionNode12"
    into: "in"
  - from: "VerifySearchTerm9"
    via: "next"
    to: "UpdateDictionary11"
    into: "in"
  - from: "DecisionNode12"
    via: "yes"
    to: "JoinNode27"
    into: "in1"
  - from: "DecisionNode12"
    via: "no"
    to: "VerifySearchTerm9"
    into: "in"
  - from: "UpdateDictionary11"
    via: "next"
    to: "JoinNode27"
    into: "in1"
  - from: "VerifySearchTerm9"
    via: "error"
    to: "EndNode13"
    into: "in"
  - from: "JoinNode19"
    via: "next"
    to: "DecisionNode8"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "EndNode4"
    into: "in"
