flow: "ProductSynchronizationJob"
kind: "process"

entries:
  - id: "Start2"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CreateStack1"
    type: "pipelet"
    ref: "CreateStack"
    bindings:
      Stack: "OrganizationStack"
  - id: "CreateStack3"
    type: "pipelet"
    ref: "CreateStack"
    bindings:
      Stack: "RepositorySynchronizationStack"
  - id: "Decision1"
    type: "decision"
    condition: "Repository:TypeCode"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Repository:TypeCode"
  - id: "End2"
    type: "end"
  - id: "End4"
    type: "end"
  - id: "ExecuteCartridgePipelines1"
    type: "pipelet"
    ref: "ExecuteCartridgePipelines"
    config:
      Asynchronous: false
      PipelinePropertyName: "RepositorySynchronizationHook"
      ProcessReversely: false
  - id: "GetOrganizationByName1"
    type: "pipelet"
    ref: "GetOrganizationByName"
    config:
      DefaultName: "Operations"
    bindings:
      Organization: "Operations"
      OrganizationDomain: "OperationsDomain"
  - id: "GetOrganizations1"
    type: "pipelet"
    ref: "GetOrganizations"
    bindings:
      Owner: "OperationsDomain"
  - id: "GetRepositories2"
    type: "pipelet"
    ref: "GetRepositories"
    bindings:
      OrganizationDomain: "Organization:OrganizationDomain"
      Repositories: "Repositories"
  - id: "GetRepository3"
    type: "pipelet"
    ref: "GetRepository"
    config:
      CustomRepositoryTypeCode: 21
      Type: "Custom Repository"
    bindings:
      OrganizationDomain: "Organization:OrganizationDomain"
  - id: "Join2"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "Loop10"
    type: "loop"
  - id: "Loop3"
    type: "loop"
  - id: "ManipulateStack1"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "PUSH"
    bindings:
      AddElement: "Organizations"
      Stack: "OrganizationStack"
  - id: "ManipulateStack2"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "PEEK"
    bindings:
      GetElement: "Organizations"
      Stack: "OrganizationStack"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "PEEK"
    bindings:
      Stack: "RepositorySynchronizationStack"
      GetElement: "Repositories"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "POP"
    bindings:
      Stack: "RepositorySynchronizationStack"
      GetElement: "Repositories"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "POP"
    bindings:
      Stack: "OrganizationStack"
      GetElement: "Organizations"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "PUSH"
    bindings:
      AddElement: "Repositories"
      Stack: "RepositorySynchronizationStack"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "ExecuteCartridgePipelines"
    config:
      Asynchronous: false
      PipelinePropertyName: "RepositorySynchronizationHook"
      ProcessReversely: false
  - id: "TextNode1"
    type: "text"
  - id: "TextNode2"
    type: "text"

links:
  - from: "ExecuteCartridgePipelines1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "GetOrganizationByName1"
    via: "error"
    to: "End4"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "ExecuteCartridgePipelines1"
    into: "in"
  - from: "GetOrganizationByName1"
    via: "next"
    to: "CreateStack3"
    into: "in"
  - from: "ManipulateStack1"
    via: "next"
    to: "Loop3"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "ManipulateStack2"
    into: "in"
  - from: "CreateStack3"
    via: "next"
    to: "CreateStack1"
    into: "in"
  - from: "GetRepository3"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "GetRepository3"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "Pipelet5"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "ManipulateStack2"
    via: "next"
    to: "Loop3"
    into: "loop"
  - from: "GetOrganizations1"
    via: "next"
    to: "ManipulateStack1"
    into: "in"
  - from: "Loop3"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "End2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "GetRepositories2"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "Decision1"
    via: "yes"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "ExecuteCartridgePipelines1"
    via: "error"
    to: "Join2"
    into: "in3"
  - from: "Loop10"
    via: "do"
    to: "Decision1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Loop10"
    into: "loop"
  - from: "Pipelet5"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "Loop3"
    via: "do"
    to: "GetRepository3"
    into: "in"
  - from: "GetRepositories2"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "Loop10"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "Loop10"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "GetOrganizationByName1"
    into: "in"
  - from: "CreateStack1"
    via: "next"
    to: "GetOrganizations1"
    into: "in"
