flow: "Redirect"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      - key: "TargetURL"
        type: "java.lang.String"
        required: false
      - key: "TargetPipeline"
        type: "java.lang.String"
        required: false
      - key: "TargetSite"
        type: "java.lang.String"
        required: false
      - key: "Protocol"
        type: "java.lang.String"
        required: false
      - key: "Parameter1_Name"
        type: "java.lang.String"
        required: false
      - key: "Parameter2_Name"
        type: "java.lang.String"
        required: false
      - key: "Parameter3_Name"
        type: "java.lang.String"
        required: false
      - key: "Parameter1_Value"
        type: "java.lang.String"
        required: false
      - key: "Parameter2_Value"
        type: "java.lang.String"
        required: false
      - key: "Parameter3_Value"
        type: "java.lang.String"
        required: false
      - key: "Parameter4_Name"
        type: "java.lang.String"
        required: false
      - key: "Parameter4_Value"
        type: "java.lang.String"
        required: false
      - key: "Parameter5_Name"
        type: "java.lang.String"
        required: false
      - key: "Parameter5_Value"
        type: "java.lang.String"
        required: false
      - key: "Parameter6_Name"
        type: "java.lang.String"
        required: false
      - key: "Parameter6_Value"
        type: "java.lang.String"
        required: false
      - key: "TargetURLFragment"
        type: "java.lang.String"
        required: false

steps:
  - id: "InteractionNode1"
    type: "interaction"

links:
  - from: "StartNode1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
