flow: "RemovePartnerOrganizationExtension"
kind: "extension"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true

steps:
  - id: "CreateStack1"
    type: "pipelet"
    ref: "CreateStack"
    bindings:
      Stack: "DeletionStack"
  - id: "Decision1"
    type: "decision"
    condition: "DeletionStack"
  - id: "Decision2"
    type: "decision"
    condition: "Organization:TypeCode"
  - id: "Decision3"
    type: "decision"
    condition: "DeleteRepository:TypeCode"
  - id: "Decision4"
    type: "decision"
    condition: "DeleteRepository:TypeCode"
  - id: "Decision5"
    type: "decision"
    condition: "DeleteRepository:Domain"
  - id: "Decision6"
    type: "decision"
    condition: "Catalog:isProxy"
  - id: "End1"
    type: "end"
    strict: true
  - id: "End2"
    type: "end"
    strict: true
  - id: "ExecuteCartridgePipelines1"
    type: "pipelet"
    ref: "ExecuteCartridgePipelines"
    config:
      Asynchronous: false
      PipelinePropertyName: "ChannelDeletionHook"
      ProcessReversely: true
  - id: "GetCatalogs1"
    type: "pipelet"
    ref: "GetCatalogs"
    config:
      CatalogType: "All"
      OnlineOnly: "False"
    bindings:
      OrganizationDomain: "Organization:Domain"
  - id: "GetRepositories1"
    type: "pipelet"
    ref: "GetRepositories"
    bindings:
      OrganizationDomain: "Organization:Domain"
      Repositories: "DeleteRepositories"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Loop1"
    type: "loop"
  - id: "Loop2"
    type: "loop"
  - id: "ManipulateStack1"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "POP"
    bindings:
      GetElement: "Organization"
      Stack: "DeletionStack"
  - id: "ManipulateStack2"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "PUSH"
    bindings:
      AddElement: "Organization"
      Stack: "DeletionStack"
  - id: "ManipulateStack3"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "POP"
    bindings:
      GetElement: "DeleteRepositories"
      Stack: "DeletionStack"
  - id: "ManipulateStack4"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "PEEK"
    bindings:
      GetElement: "DeleteRepositories"
      Stack: "DeletionStack"
  - id: "ManipulateStack5"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "PUSH"
    bindings:
      AddElement: "DeleteRepositories"
      Stack: "DeletionStack"
  - id: "SetDomainStatus1"
    type: "pipelet"
    ref: "SetDomainStatus"
    config:
      DefaultStatus: "ToBeDeleted"
    bindings:
      Domain: "Catalog:Domain"
  - id: "SetDomainStatus2"
    type: "pipelet"
    ref: "SetDomainStatus"
    config:
      DefaultStatus: "ToBeDeleted"
    bindings:
      Domain: "DeleteRepository:Domain"
  - id: "SetDomainStatus3"
    type: "pipelet"
    ref: "SetDomainStatus"
    config:
      DefaultStatus: "ToBeDeleted"
    bindings:
      Domain: "DeleteRepository:Domain:Site"
  - id: "Text1"
    type: "text"

links:
  - from: "Decision3"
    via: "no"
    to: "Join7"
    into: "in1"
  - from: "Decision3"
    via: "yes"
    to: "Decision4"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "End2"
    into: "in"
  - from: "Decision4"
    via: "yes"
    to: "SetDomainStatus3"
    into: "in"
  - from: "SetDomainStatus3"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "ManipulateStack3"
    via: "next"
    to: "ManipulateStack1"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "ManipulateStack3"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "ExecuteCartridgePipelines1"
    into: "in"
  - from: "Decision6"
    via: "yes"
    to: "SetDomainStatus1"
    into: "in"
  - from: "ManipulateStack5"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "Join7"
    into: "in2"
  - from: "Join3"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "Decision2"
    via: "yes"
    to: "Decision1"
    into: "in"
  - from: "Decision5"
    via: "yes"
    to: "SetDomainStatus2"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "ManipulateStack2"
    via: "next"
    to: "GetRepositories1"
    into: "in"
  - from: "Loop2"
    via: "next"
    to: "End1"
    into: "in"
  - from: "ExecuteCartridgePipelines1"
    via: "next"
    to: "ManipulateStack4"
    into: "in"
  - from: "GetRepositories1"
    via: "next"
    to: "ManipulateStack5"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join2"
    into: "in3"
  - from: "SetDomainStatus2"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Decision5"
    via: "no"
    to: "Join1"
    into: "in3"
  - from: "Join7"
    via: "next"
    to: "Decision5"
    into: "in"
  - from: "CreateStack1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "ManipulateStack4"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "CreateStack1"
    into: "in"
  - from: "SetDomainStatus1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "ManipulateStack2"
    into: "in"
  - from: "ManipulateStack1"
    via: "next"
    to: "GetCatalogs1"
    into: "in"
  - from: "Loop2"
    via: "do"
    to: "Decision6"
    into: "in"
  - from: "Decision6"
    via: "no"
    to: "Join3"
    into: "in3"
  - from: "GetCatalogs1"
    via: "next"
    to: "Loop2"
    into: "in"
