flow: "RemoveChannelHook"
kind: "process"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CreateStack1"
    type: "pipelet"
    ref: "CreateStack"
    bindings:
      Stack: "DeletionStack"
  - id: "Decision2"
    type: "decision"
    condition: "ApplicationState:ChannelID"
  - id: "Decision3"
    type: "decision"
    condition: "DeleteRepository:TypeCode"
  - id: "Decision4"
    type: "decision"
    condition: "DeletionStack"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Organization:Domain:Site:DomainID"
  - id: "End2"
    type: "end"
  - id: "End4"
    type: "end"
  - id: "ExecuteCartridgePipelines5"
    type: "pipelet"
    ref: "ExecuteCartridgePipelines"
    config:
      Asynchronous: false
      PipelinePropertyName: "OrganizationDeletionHook"
      ProcessReversely: true
  - id: "GetApplicationState1"
    type: "pipelet"
    ref: "GetApplicationState"
  - id: "GetOrganizations1"
    type: "pipelet"
    ref: "GetOrganizations"
    bindings:
      OrganizationType: "null"
      Owner: "DeleteRepository:Domain"
  - id: "Join13"
    type: "join"
  - id: "Join14"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "Loop1"
    type: "loop"
  - id: "ManipulateStack1"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "PUSH"
    bindings:
      AddElement: "DeleteRepository"
      Stack: "DeletionStack"
  - id: "ManipulateStack3"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "PEEK"
    bindings:
      GetElement: "Organizations"
      Stack: "DeletionStack"
  - id: "ManipulateStack4"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "POP"
    bindings:
      GetElement: "Organizations"
      Stack: "DeletionStack"
  - id: "ManipulateStack5"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "PUSH"
    bindings:
      AddElement: "Organizations"
      Stack: "DeletionStack"
  - id: "ManipulateStack6"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "POP"
    bindings:
      GetElement: "DeleteRepository"
      Stack: "DeletionStack"
  - id: "RemoveStringValueFromApplicationState1"
    type: "pipelet"
    ref: "RemoveStringValueFromApplicationState"
    config:
      DefaultKey: "ChannelID"
  - id: "SetDomainStatus1"
    type: "pipelet"
    ref: "SetDomainStatus"
    config:
      DefaultStatus: "ToBeDeleted"
    bindings:
      Domain: "Organization:Domain:Site"

links:
  - from: "Decision3"
    via: "no"
    to: "End4"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "ManipulateStack4"
    into: "in"
  - from: "GetApplicationState1"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "CreateStack1"
    via: "next"
    to: "Join14"
    into: "in1"
  - from: "Join14"
    via: "next"
    to: "ManipulateStack1"
    into: "in"
  - from: "ManipulateStack1"
    via: "next"
    to: "GetOrganizations1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "ExecuteCartridgePipelines5"
    into: "in"
  - from: "ManipulateStack3"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "RemoveStringValueFromApplicationState1"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "ManipulateStack4"
    via: "next"
    to: "ManipulateStack6"
    into: "in"
  - from: "ManipulateStack6"
    via: "next"
    to: "GetApplicationState1"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "RemoveStringValueFromApplicationState1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join13"
    into: "in2"
  - from: "GetApplicationState1"
    via: "error"
    to: "Join13"
    into: "in1"
  - from: "Join13"
    via: "next"
    to: "Join8"
    into: "in3"
  - from: "Decision3"
    via: "yes"
    to: "Decision4"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "SetDomainStatus1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Decision4"
    via: "yes"
    to: "CreateStack1"
    into: "in"
  - from: "ManipulateStack5"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "End2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "SetDomainStatus1"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "Join14"
    into: "in3"
  - from: "GetOrganizations1"
    via: "next"
    to: "ManipulateStack5"
    into: "in"
  - from: "ExecuteCartridgePipelines5"
    via: "next"
    to: "ManipulateStack3"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "DecisionNode1"
    via: "no"
    to: "Join3"
    into: "in2"
  - from: "ExecuteCartridgePipelines5"
    via: "error"
    to: "Join3"
    into: "in1"
