flow: "RemoveOrganizationProfanityCheckExtension"
kind: "extension"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true

steps:
  - id: "CallNode2"
    type: "call"
    ref: "ProcessProfanityCheckPreferences-RemoveConfigurationAssignment"
    bindings:
      Domain: "OneAssignment:Domain"
      LocaleID: "OneAssignment:LocaleID"
      ProfanityCheckConfigurationID: "OneAssignment:ProfanityCheckConfigurationID"
  - id: "CombineIterators1"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Concatenate Iterators"
    bindings:
      Iterator2: "CustomAssignments"
      Iterator1: "DefaultAssignments"
      Iterator: "AllAssignments"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Organization:Domain"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "GetProfanityCheckConfigurationAssignmentsByDomainAndConfigID1"
    type: "pipelet"
    ref: "GetProfanityCheckConfigurationAssignmentsByDomainAndConfigID"
    config:
      AssignmentType: "Default"
    bindings:
      ProfanityCheckConfigurationAssignments: "DefaultAssignments"
      Domain: "Organization:Domain"
  - id: "GetProfanityCheckConfigurationAssignmentsByDomainAndConfigID2"
    type: "pipelet"
    ref: "GetProfanityCheckConfigurationAssignmentsByDomainAndConfigID"
    config:
      AssignmentType: "Custom"
    bindings:
      Domain: "Organization:Domain"
      ProfanityCheckConfigurationAssignments: "CustomAssignments"
  - id: "GetProfanityCheckConfigurationAssignmentsByDomainAndConfigID3"
    type: "pipelet"
    ref: "GetProfanityCheckConfigurationAssignmentsByDomainAndConfigID"
    config:
      AssignmentType: "Custom"
    bindings:
      Domain: "Organization:Domain"
      ProfanityCheckConfigurationAssignments: "CustomAssignments"
  - id: "GetProfanityCheckConfigurationsByDomain1"
    type: "pipelet"
    ref: "GetProfanityCheckConfigurationsByDomain"
    bindings:
      Domain: "Organization:Domain"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "DefaultAssignments"
      OutValue_1: "AllAssignments"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CustomAssignments"
      OutValue_1: "AllAssignments"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "RemoveProfanityCheckConfiguration1"
    type: "pipelet"
    ref: "RemoveProfanityCheckConfiguration"

links:
  - from: "GetProfanityCheckConfigurationAssignmentsByDomainAndConfigID2"
    via: "error"
    to: "KeyMapper1"
    into: "in"
  - from: "RemoveProfanityCheckConfiguration1"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "GetProfanityCheckConfigurationsByDomain1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "Start1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetProfanityCheckConfigurationAssignmentsByDomainAndConfigID3"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "CombineIterators1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetProfanityCheckConfigurationsByDomain1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetProfanityCheckConfigurationAssignmentsByDomainAndConfigID1"
    into: "in"
  - from: "GetProfanityCheckConfigurationAssignmentsByDomainAndConfigID3"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "GetProfanityCheckConfigurationsByDomain1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "LoopNode1"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "GetProfanityCheckConfigurationAssignmentsByDomainAndConfigID1"
    via: "next"
    to: "GetProfanityCheckConfigurationAssignmentsByDomainAndConfigID2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GetProfanityCheckConfigurationAssignmentsByDomainAndConfigID2"
    via: "next"
    to: "CombineIterators1"
    into: "in"
  - from: "GetProfanityCheckConfigurationAssignmentsByDomainAndConfigID1"
    via: "error"
    to: "GetProfanityCheckConfigurationAssignmentsByDomainAndConfigID3"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "EndNode1"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "LoopNode1"
    via: "do"
    to: "CallNode2"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "RemoveProfanityCheckConfiguration1"
    into: "in"
