flow: "ReplaceDBContent"
kind: "java.lang.String"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      - key: "StagingProcessID"
        type: "java.lang.String"
        required: false
  - id: "StartNode2"
    name: "Error"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call15"
    type: "call"
    ref: "StagingProcessCustomization-OnPostInitialReplication"
  - id: "Call16"
    type: "call"
    ref: "StagingProcessCustomization-OnPreInitialReplication"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "JoinNode2"
    type: "join"
  - id: "LogException1"
    type: "pipelet"
    ref: "LogException"
    config:
      LogScope: "staging"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "SetStagingState"
    config:
      StagingState: "ErrorInitialReplication"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "SetStagingState"
    config:
      StagingState: "StartingInitialReplication"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "SetStagingState"
    config:
      StagingState: "InitialReplicationSuccessfullyFinished"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "GetStagingProcess"
  - id: "ReplicateEntireDBSchema1"
    type: "pipelet"
    ref: "ReplicateEntireDBSchema"

links:
  - from: "StartNode1"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "Call16"
    into: "in"
  - from: "LogException1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "Call15"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "ReplicateEntireDBSchema1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "Pipelet2"
    via: "next"
    to: "LogException1"
    into: "in"
  - from: "Call16"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "ReplicateEntireDBSchema1"
    into: "in"
  - from: "ReplicateEntireDBSchema1"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "Call15"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
