flow: "ReplicationTaskStateSynchronizationJob"
kind: "process"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "SynchronizeStates"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "GetReplicationTasks-ByState"
  - id: "Call2"
    type: "call"
    ref: "ReplicationTaskStateSynchronizationJob-SynchronizeStates"
  - id: "CreatePageableSequence1"
    type: "pipelet"
    ref: "CreatePageableSequence"
    bindings:
      PageableIterator: "ReplicationTasks"
      PageableSequence: "ReplicationTasks"
  - id: "Decision1"
    type: "decision"
    condition: "CurrentDate:Time"
  - id: "End1"
    type: "end"
  - id: "End2"
    type: "end"
  - id: "GetCurrentDate1"
    type: "pipelet"
    ref: "GetCurrentDate"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Loop1"
    type: "loop"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "State"
      Value: "PENDING"
  - id: "SwitchToNextPage1"
    type: "pipelet"
    ref: "SwitchToNextPage"
    bindings:
      PageableIterator: "ReplicationTasks"
  - id: "UpdateReplicationTask1"
    type: "pipelet"
    ref: "UpdateReplicationTask"
    bindings:
      Description: "null"
      DueTime: "null"
      Locale: "null"
      Requester: "null"
      StartTime: "null"
      State: "\"WAITING\""

links:
  - from: "Start1"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "CreatePageableSequence1"
    into: "in"
  - from: "CreatePageableSequence1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Call2"
    via: "next"
    to: "SwitchToNextPage1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "SwitchToNextPage1"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "SwitchToNextPage1"
    via: "error"
    to: "End1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "UpdateReplicationTask1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Decision1"
    via: "yes"
    to: "UpdateReplicationTask1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join2"
    into: "in3"
  - from: "Loop1"
    via: "do"
    to: "GetCurrentDate1"
    into: "in"
  - from: "GetCurrentDate1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Loop1"
    into: "loop"
