flow: "ReplicateRepositoryHook"
kind: "process"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddStagingGroupToReplicationTask1"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "Repository:RepositoryDomain"
      StagingGroupName: "\"UnitStatic\""
  - id: "AddStagingGroupToReplicationTask16"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "LocalizationDomain"
      StagingGroupName: "\"Localizations\""
  - id: "AddStagingGroupToReplicationTask17"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "LocalizationDomain"
      StagingGroupName: "\"Domains\""
  - id: "AddStagingGroupToReplicationTask4"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "Repository:RepositoryDomain"
      StagingGroupName: "\"Domains\""
  - id: "AddStagingGroupToReplicationTask6"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "Repository:RepositoryDomain"
      StagingGroupName: "\"Preferences\""
  - id: "AddStagingGroupToReplicationTask9"
    type: "pipelet"
    ref: "AddStagingGroupToReplicationTask"
    bindings:
      Domain: "Repository:RepositoryDomain"
      StagingGroupName: "\"UserGroups\""
  - id: "Decision1"
    type: "decision"
    condition: "Repository:TypeCode"
  - id: "Decision2"
    type: "decision"
    condition: "Repository:TypeCode"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "GetLocalizationDomainsByRepositoryDomain1"
    type: "pipelet"
    ref: "GetLocalizationDomainsByRepositoryDomain"
    bindings:
      RepositoryDomain: "Repository:RepositoryDomain"
  - id: "Join1"
    type: "join"
  - id: "LoopNode1"
    type: "loop"

links:
  - from: "Start1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "AddStagingGroupToReplicationTask9"
    via: "next"
    to: "GetLocalizationDomainsByRepositoryDomain1"
    into: "in"
  - from: "AddStagingGroupToReplicationTask17"
    via: "next"
    to: "AddStagingGroupToReplicationTask16"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "AddStagingGroupToReplicationTask17"
    into: "in"
  - from: "AddStagingGroupToReplicationTask16"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "GetLocalizationDomainsByRepositoryDomain1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "End3"
    into: "in"
  - from: "AddStagingGroupToReplicationTask4"
    via: "next"
    to: "AddStagingGroupToReplicationTask6"
    into: "in"
  - from: "AddStagingGroupToReplicationTask6"
    via: "next"
    to: "AddStagingGroupToReplicationTask1"
    into: "in"
  - from: "AddStagingGroupToReplicationTask1"
    via: "next"
    to: "AddStagingGroupToReplicationTask9"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Join1"
    into: "in1"
  - from: "Decision1"
    via: "no"
    to: "Decision2"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "AddStagingGroupToReplicationTask4"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "Join1"
    into: "in3"
  - from: "Decision2"
    via: "no"
    to: "End1"
    into: "in"
