flow: "RequisitionProcessCalculation"
kind: "process"

entries:
  - id: "Start2"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CalculateExchangeRates2"
    type: "pipelet"
    ref: "CalculateExchangeRates"
  - id: "CalculateGrandTotals2"
    type: "pipelet"
    ref: "CalculateGrandTotals"
    config:
      Mode: "SumLineItems"
  - id: "CalculateProductPrices2"
    type: "pipelet"
    ref: "CalculateProductPrices"
  - id: "CalculateServicePrices2"
    type: "pipelet"
    ref: "CalculateServicePrices"
  - id: "CalculateTax2"
    type: "pipelet"
    ref: "CalculateTax"
  - id: "End2"
    type: "end"
    strict: false
  - id: "PrcCalculateProductSingleBasePrices2"
    type: "pipelet"
    ref: "PrcCalculateProductSingleBasePrices"
    config:
      DefaultTaxationPolicy: "Net"
  - id: "TextNode1"
    type: "text"
  - id: "UpdateServiceLineItemByTaxPolicy1"
    type: "pipelet"
    ref: "UpdateServiceLineItemByTaxPolicy"
    config:
      DefaultTaxationPolicy: "Net"

links:
  - from: "CalculateProductPrices2"
    via: "next"
    to: "UpdateServiceLineItemByTaxPolicy1"
    into: "in"
  - from: "CalculateExchangeRates2"
    via: "next"
    to: "CalculateProductPrices2"
    into: "in"
  - from: "PrcCalculateProductSingleBasePrices2"
    via: "next"
    to: "CalculateExchangeRates2"
    into: "in"
  - from: "CalculateServicePrices2"
    via: "next"
    to: "CalculateTax2"
    into: "in"
  - from: "CalculateTax2"
    via: "next"
    to: "CalculateGrandTotals2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "PrcCalculateProductSingleBasePrices2"
    into: "in"
  - from: "CalculateGrandTotals2"
    via: "next"
    to: "End2"
    into: "in"
  - from: "UpdateServiceLineItemByTaxPolicy1"
    via: "next"
    to: "CalculateServicePrices2"
    into: "in"
