flow: "RequisitionApproveRejectActions"
kind: "process"

entries:
  - id: "Start1"
    name: "OnApprove"
    mode: "private"
    strict: true
    inputs:
      - key: "ApprovalObject"
        type: "com.intershop.component.approval.capi.ApprovalObject"
        required: true
  - id: "Start2"
    name: "OnReject"
    mode: "private"
    strict: true
    inputs:
      - key: "ApprovalObject"
        type: "com.intershop.component.approval.capi.ApprovalObject"
        required: true
  - id: "Start3"
    name: "CheckApprovalFinished"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessOrder-CreateOrders"
  - id: "Call2"
    type: "call"
    ref: "RequisitionApprovalNotification-NotifyBuyer"
  - id: "Call3"
    type: "call"
    ref: "ProcessLineItems-RecalculateTotals"
  - id: "Call4"
    type: "call"
    ref: "ProcessAccountTransactions-OnRejectLineItem"
  - id: "Call5"
    type: "call"
    ref: "ProcessAccountTransactions-OnRejectRequisition"
  - id: "CheckRequisitionStatus1"
    type: "pipelet"
    ref: "CheckRequisitionStatus"
    bindings:
      InputStatusGroup: "null"
      InputStatusID: "null"
  - id: "CheckRequisitionStatus2"
    type: "pipelet"
    ref: "CheckRequisitionStatus"
    bindings:
      InputStatusGroup: "null"
      InputStatusID: "null"
  - id: "Decision1"
    type: "decision"
    condition: "OutputStatusID"
  - id: "Decision2"
    type: "decision"
    condition: "OutputStatusID"
  - id: "Decision3"
    type: "decision"
    condition: "OutputStatusID"
  - id: "Decision4"
    type: "decision"
    condition: "Requisition:Express"
  - id: "Decision5"
    type: "decision"
    condition: "OutputStatusID"
  - id: "End1"
    type: "end"
    strict: true
  - id: "End2"
    type: "end"
    strict: true
  - id: "GetLineItemsFromApprovalObject1"
    type: "pipelet"
    ref: "GetLineItemsFromApprovalObject"
    bindings:
      ApprovalObjects: "null"
  - id: "GetLineItemsFromApprovalObject2"
    type: "pipelet"
    ref: "GetLineItemsFromApprovalObject"
    bindings:
      ApprovalObjects: "null"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "RequisitionApproveRejectActions-CheckApprovalFinished"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ProductLineItem"
      OutValue_1: "LineItem"
  - id: "TextNode1"
    type: "text"
  - id: "TextNode2"
    type: "text"
  - id: "UpdateLineItemStatus1"
    type: "pipelet"
    ref: "UpdateLineItemStatus"
    config:
      StatusGroup: "Product"
      StatusID: 3
    bindings:
      InputStatusGroup: "null"
      InputStatusID: "null"
      LineItemID: "ProductLineItem:UUID"
      LineItemIDs: "null"
      Order: "null"
      Requisition: "null"
  - id: "UpdateLineItemStatus2"
    type: "pipelet"
    ref: "UpdateLineItemStatus"
    config:
      StatusGroup: "Product"
      StatusID: 4
    bindings:
      InputStatusGroup: "null"
      InputStatusID: "null"
      LineItemID: "ProductLineItem:UUID"
      LineItemIDs: "null"
      Order: "null"
      Requisition: "null"
  - id: "UpdateRequisitionStatus1"
    type: "pipelet"
    ref: "UpdateRequisitionStatus"
    bindings:
      InputStatusGroup: "OutputStatusGroup"
      InputStatusID: "OutputStatusID"
  - id: "UpdateRequisitionStatus2"
    type: "pipelet"
    ref: "UpdateRequisitionStatus"
    bindings:
      InputStatusGroup: "OutputStatusGroup"
      InputStatusID: "OutputStatusID"
  - id: "UpdateRequisitionStatus3"
    type: "pipelet"
    ref: "UpdateRequisitionStatus"
    config:
      StatusID: 14
    bindings:
      InputStatusGroup: "notDef"
      InputStatusID: "notDef"

links:
  - from: "Start1"
    via: "next"
    to: "GetLineItemsFromApprovalObject1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Join1"
    into: "in1"
  - from: "Decision2"
    via: "yes"
    to: "Join1"
    into: "in3"
  - from: "Join2"
    via: "next"
    to: "End2"
    into: "in"
  - from: "UpdateRequisitionStatus1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "Decision4"
    via: "yes"
    to: "Call1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Decision3"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "GetLineItemsFromApprovalObject1"
    via: "next"
    to: "UpdateLineItemStatus1"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "Join4"
    into: "in3"
  - from: "Decision3"
    via: "no"
    to: "End1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Decision5"
    into: "in"
  - from: "Decision5"
    via: "no"
    to: "Decision4"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Decision4"
    via: "no"
    to: "Join2"
    into: "in3"
  - from: "Call4"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Decision5"
    via: "yes"
    to: "UpdateRequisitionStatus3"
    into: "in"
  - from: "UpdateRequisitionStatus2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "GetLineItemsFromApprovalObject2"
    via: "next"
    to: "UpdateLineItemStatus2"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "UpdateRequisitionStatus3"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "Start2"
    via: "next"
    to: "GetLineItemsFromApprovalObject2"
    into: "in"
  - from: "UpdateLineItemStatus2"
    via: "next"
    to: "CheckRequisitionStatus2"
    into: "in"
  - from: "UpdateLineItemStatus1"
    via: "next"
    to: "CheckRequisitionStatus1"
    into: "in"
  - from: "CheckRequisitionStatus1"
    via: "next"
    to: "UpdateRequisitionStatus1"
    into: "in"
  - from: "CheckRequisitionStatus2"
    via: "next"
    to: "UpdateRequisitionStatus2"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Decision2"
    into: "in"
