flow: "RequisitionApprovalNotification"
kind: "process"

entries:
  - id: "Start1"
    name: "GetApprovers"
    mode: "private"
    strict: false
    inputs:
      - key: "CurrentActivity"
        type: "com.intershop.beehive.core.capi.workflow.WorkflowActivity"
        required: false
  - id: "Start2"
    name: "NotifyApprovers"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "NotifyBuyer"
    mode: "private"
    strict: false
    inputs:
      - key: "Requisition"
        type: "com.intershop.beehive.bts.capi.orderprocess.basket.Basket"
        required: false
  - id: "Start4"
    name: "NotifyApproversB2B"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "RequisitionApprovalNotification-GetApprovers"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessUserActivationCheck-FilterForActiveUsers"
  - id: "CombineIterators1"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Subtract Iterators and Remove Duplicates"
    bindings:
      Iterator: "NewUsers"
      Iterator1: "Users"
      Iterator2: "NotifiedUsers"
  - id: "CombineIterators2"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Concatenate Iterators and Remove Duplicates"
    bindings:
      Iterator: "Users"
      Iterator1: "Users"
      Iterator2: "DelegatedUsers"
  - id: "Decision1"
    type: "decision"
    condition: "CurrentActivity:NotificationTemplate"
  - id: "Decision2"
    type: "decision"
    condition: "EMailNotification"
  - id: "DecisionNode1"
    type: "decision"
    condition: "NewUsers"
  - id: "DetermineMailNotificationData2"
    type: "pipelet"
    ref: "DetermineMailNotificationData"
    config:
      DefaultEmailFrom: "INTERSHOP_Enfinity_MultiSite"
      Mode: "Multiple"
    bindings:
      Users: "NewUsers"
      WorkflowActivity: "CurrentActivity"
  - id: "DetermineUnit1"
    type: "pipelet"
    ref: "DetermineUnit"
  - id: "DetermineUsersForNotification2"
    type: "pipelet"
    ref: "DetermineUsersForNotification"
    bindings:
      WorkflowActivity: "CurrentActivity"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "End5"
    type: "end"
    strict: false
  - id: "GetActiveUserDelegationUsers1"
    type: "pipelet"
    ref: "GetActiveUserDelegationUsers"
    config:
      DelegationType: 2
      GetMethod: "Get Delegated"
    bindings:
      Users: "DelegatedUsers"
  - id: "GetApprovalActivities1"
    type: "pipelet"
    ref: "GetApprovalActivities"
    config:
      DefaultApprovalType: 2
  - id: "GetApprovalLastNotifiedUsers1"
    type: "pipelet"
    ref: "GetApprovalLastNotifiedUsers"
  - id: "GetApprovalObjects1"
    type: "pipelet"
    ref: "GetApprovalObjects"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "EMailNotification"
      Type: "String"
    bindings:
      PreferenceStringValue: "EMailNotification"
  - id: "GetDomainPreference13"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "EMailNotificationFromAddress"
      Type: "String"
    bindings:
      PreferenceStringValue: "MailFrom"
  - id: "GetDomainPreference2"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "EMailNotificationFromAddress"
      Type: "String"
    bindings:
      PreferenceStringValue: "MailFrom"
      PreferenceDomain: "Unit"
  - id: "GetLineItemsFromApprovalObject1"
    type: "pipelet"
    ref: "GetLineItemsFromApprovalObject"
  - id: "GetOrganizationByUser1"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      OrganizationDomain: "PreferenceDomain"
      User: "Requisition:User"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Users"
      OutValue_1: "DirectUsers"
  - id: "Loop1"
    type: "loop"
  - id: "Loop2"
    type: "loop"
  - id: "ProcessMail1"
    type: "pipelet"
    ref: "ProcessMail"
    bindings:
      Domain: "CurrentOrganization:OwningDomain"
  - id: "ProcessMail2"
    type: "pipelet"
    ref: "ProcessMail"
    bindings:
      MailTo: "Requisition:User:Profile:AddressBook:DefaultAddress:EMail"
      Domain: "CurrentOrganization:OwningDomain"
  - id: "SetApprovalLastNotifiedUsers1"
    type: "pipelet"
    ref: "SetApprovalLastNotifiedUsers"
    bindings:
      NotifiedUsers: "Users"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "MailTo"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "MailFrom"
      Value: "INTERSHOP_Procurement_Solution"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "MailTemplate"
      Value: "RequisitionAWFCompletedMail"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "MailFrom"
      Value: "INTERSHOP_Procurement_Solution"

links:
  - from: "Start2"
    via: "next"
    to: "DetermineUnit1"
    into: "in"
  - from: "GetApprovalLastNotifiedUsers1"
    via: "next"
    to: "CombineIterators1"
    into: "in"
  - from: "SetApprovalLastNotifiedUsers1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "GetApprovalObjects1"
    via: "next"
    to: "GetLineItemsFromApprovalObject1"
    into: "in"
  - from: "GetLineItemsFromApprovalObject1"
    via: "next"
    to: "ProcessMail1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Call1"
    into: "in"
  - from: "DetermineUsersForNotification2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "DetermineUsersForNotification2"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "GetApprovalLastNotifiedUsers1"
    into: "in"
  - from: "CombineIterators1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Loop2"
    into: "in"
  - from: "GetApprovalActivities1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Loop2"
    via: "do"
    to: "GetActiveUserDelegationUsers1"
    into: "in"
  - from: "GetActiveUserDelegationUsers1"
    via: "next"
    to: "CombineIterators2"
    into: "in"
  - from: "CombineIterators2"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "ProcessMail2"
    into: "in"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "ProcessMail2"
    via: "next"
    to: "End3"
    into: "in"
  - from: "GetDomainPreference1"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "GetOrganizationByUser1"
    into: "in"
  - from: "GetOrganizationByUser1"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "GetDomainPreference13"
    via: "error"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "Decision2"
    via: "no"
    to: "End4"
    into: "in"
  - from: "GetOrganizationByUser1"
    via: "error"
    to: "End5"
    into: "in"
  - from: "DetermineUnit1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "GetApprovalActivities1"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Join2"
    into: "in3"
  - from: "Loop2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "ProcessMail1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "DetermineMailNotificationData2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "SetApprovalLastNotifiedUsers1"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "GetDomainPreference13"
    into: "in"
  - from: "GetDomainPreference2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GetDomainPreference2"
    via: "error"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "GetDomainPreference13"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DetermineMailNotificationData2"
    via: "next"
    to: "GetDomainPreference2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "GetApprovalObjects1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "Decision1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "Decision1"
    via: "no"
    to: "Join1"
    into: "in3"
  - from: "Join1"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "DecisionNode1"
    via: "yes"
    to: "SetDictionaryValue1"
    into: "in"
