flow: "ShowSiteMaintenanceStatus"
kind: "view"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "InteractionEnd1"
    type: "interaction"

links:
  - from: "Start1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
