flow: "SLDMaintainCatalogFilters"
kind: "process"

entries:
  - id: "Start1"
    name: "Refresh"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start11"
    name: "RecurseChannels"
    mode: "private"
    strict: false
    inputs:
      - key: "OrganizationStack"
        type: "java.util.Stack"
        required: false
      - key: "ExcludeOrganizations"
        type: "java.lang.String"
        required: false
  - id: "Start12"
    name: "PerformTask"
    mode: "private"
    strict: false
    inputs:
      - key: "ChannelTask"
        type: "java.lang.String"
        required: false
      - key: "OrganizationTask"
        type: "java.lang.String"
        required: false
      - key: "ExcludeOrganizations"
        type: "java.lang.String"
        required: false
  - id: "Start2"
    name: "Purge"
    mode: "private"
    strict: false
    inputs:
      - key: "ExcludeOrganizations"
        type: "java.lang.String"
        required: false
  - id: "Start3"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      - key: "ExcludeOrganizations"
        type: "java.lang.String"
        required: false
  - id: "StartNode1"
    name: "PublishChannelFilter"
    mode: "private"
    strict: false
    inputs:
      - key: "Channel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: false
      - key: "Role"
        type: "com.intershop.beehive.core.capi.security.Role"
        required: false
  - id: "StartNode2"
    name: "GetChannelOrganizations"
    mode: "private"
    strict: false
    inputs:
      - key: "Channel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: false
      - key: "ExcludeOrganizations"
        type: "java.lang.String"
        required: false
  - id: "StartNode3"
    name: "PurgeChannelFilters"
    mode: "private"
    strict: false
    inputs:
      - key: "Channel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: false
  - id: "StartNode4"
    name: "PurgeOrganizationFilters"
    mode: "private"
    strict: false
    inputs:
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: false
  - id: "StartNode5"
    name: "PurgeDomainFilters"
    mode: "private"
    strict: false
    inputs:
      - key: "PurgeDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      InVector: "null"
      Object: "null"
      Objects: "Filters"
      OutVector: "FilterVector"
      Iterator: "Filters"
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "null"
      Object: "Channel:RepositoryDomain:Site"
      Objects: "null"
      OutVector: "SiteVector"
      Iterator: "null"
  - id: "Call1"
    type: "call"
    ref: "SLDMaintainCatalogFilters-Purge"
  - id: "Call10"
    type: "call"
    ref: "SLDMaintainCatalogFilters-RecurseChannels"
  - id: "Call2"
    type: "call"
    ref: "SLDMaintainCatalogFilters-Refresh"
  - id: "Call9"
    type: "call"
    ref: "PublishCatalogFilter-Multiple"
  - id: "CallNode1"
    type: "call"
  - id: "CallNode2"
    type: "call"
    ref: "SLDMaintainCatalogFilters-PerformTask"
  - id: "CallNode3"
    type: "call"
    ref: "GetOrganizations-Start"
  - id: "CallNode4"
    type: "call"
  - id: "CallNode5"
    type: "call"
    ref: "SLDMaintainCatalogFilters-GetChannelOrganizations"
  - id: "CallNode6"
    type: "call"
    ref: "SLDMaintainCatalogFilters-PerformTask"
  - id: "CallNode7"
    type: "call"
    ref: "SLDMaintainCatalogFilters-PurgeDomainFilters"
  - id: "CallNode8"
    type: "call"
    ref: "SLDMaintainCatalogFilters-PurgeDomainFilters"
  - id: "DecisionNode0"
    type: "decision"
    condition: "ExcludeOrganizations"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Channel:Proxy"
  - id: "DecisionNode2"
    type: "decision"
    condition: "OrganizationTask"
  - id: "DecisionNode3"
    type: "decision"
    condition: "ChannelTask"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Filter:UpdateInterval"
  - id: "DecisionNode7"
    type: "decision"
    condition: "Channel:TypeCode"
  - id: "DecisionNode8"
    type: "decision"
    condition: "Channel:TypeCode"
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode10"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "EndNode5"
    type: "end"
    strict: false
  - id: "EndNode6"
    type: "end"
    strict: false
  - id: "EndNode7"
    type: "end"
    strict: false
  - id: "EndNode8"
    type: "end"
    strict: false
  - id: "EndNode9"
    type: "end"
    strict: false
  - id: "GetCatalogFiltersByDomain1"
    type: "pipelet"
    ref: "GetCatalogFiltersByDomain"
    config:
      DefaultState: "Deleted"
    bindings:
      Domain: "PurgeDomain"
      State: "null"
  - id: "GetCatalogFiltersByDomain2"
    type: "pipelet"
    ref: "GetCatalogFiltersByDomain"
    config:
      DefaultState: "All"
    bindings:
      Domain: "PurgeDomain"
      State: "null"
  - id: "GetExpiredCatalogFilters1"
    type: "pipelet"
    ref: "GetExpiredCatalogFilters"
    config:
      State: "Online"
    bindings:
      OrganizationDomain: "Channel:RepositoryDomain"
  - id: "GetOrganizationByName1"
    type: "pipelet"
    ref: "GetOrganizationByName"
    config:
      DefaultName: "Operations"
    bindings:
      Name: "null"
      Organization: "Operations"
      OrganizationDomain: "OperationsDomain"
  - id: "GetOrganizations4"
    type: "pipelet"
    ref: "GetOrganizations"
    bindings:
      Owner: "OperationsDomain"
      Organizations: "Enterprises"
  - id: "Join3"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Channel"
      OutValue_1: "Repository"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Channel:RepositoryDomain"
      OutValue_1: "PurgeDomain"
  - id: "Loop4"
    type: "loop"
  - id: "Loop5"
    type: "loop"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "LoopNode3"
    type: "loop"
  - id: "ManipulateStack2"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "PUSH"
    bindings:
      AddElement: "Enterprise"
      Stack: "OrganizationStack"
      AddElements: "null"
  - id: "ManipulateStack3"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "POP"
    bindings:
      Stack: "OrganizationStack"
      GetElement: "Organization"
  - id: "ManipulateStack4"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "PUSH"
    bindings:
      AddElement: "Organization"
      Stack: "OrganizationStack"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetRepositories"
    bindings:
      OrganizationDomain: "Organization:Domain"
      Repositories: "Channels"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "CreatePageableSequence"
    bindings:
      PageableIterator: "Organizations"
      PageableSequence: "Organizations"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Channel:RepositoryDomain"
      OutValue_1: "OwningDomain"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "ChannelTask"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "CreateStack"
    bindings:
      Stack: "OrganizationStack"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"SLDMaintainCatalogFilters-PurgeChannelFilters\""
      InValue_10: "\"SLDMaintainCatalogFilters-PurgeOrganizationFilters\""
      OutValue_10: "OrganizationTask"
      OutValue_1: "ChannelTask"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "OrganizationTask"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Organization:OrganizationDomain"
      OutValue_1: "PurgeDomain"
  - id: "PurgeCatalogFilter1"
    type: "pipelet"
    ref: "PurgeCatalogFilter"
  - id: "RemoveDeadCatalogFilterRules1"
    type: "pipelet"
    ref: "RemoveDeadCatalogFilterRules"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "ChannelTask"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Value: "SLDMaintainCatalogFilters-PublishChannelFilter"
      Name: "ChannelTask"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "PermissionGroupID"
      Value: "SLD_AR_42_CATALOG_VIEWER"
  - id: "SetDictionaryValue5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "PermissionGroupID"
      Value: "SLD_AR_52_CATALOG_VIEWER"
  - id: "SwitchToNextPage2"
    type: "pipelet"
    ref: "SwitchToNextPage"
    bindings:
      PageableIterator: "Organizations"
  - id: "TextNode1"
    type: "text"

links:
  - from: "AddObjectToVector1"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "Call1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "End3"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode5"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode6"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "EndNode9"
    into: "in"
  - from: "DecisionNode0"
    via: "no"
    to: "EndNode10"
    into: "in"
  - from: "DecisionNode0"
    via: "yes"
    to: "Pipelet3"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "CallNode1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode3"
    via: "yes"
    to: "CallNode4"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode4"
    via: "yes"
    to: "RemoveDeadCatalogFilterRules1"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "SetDictionaryValue5"
    into: "in"
  - from: "DecisionNode8"
    via: "no"
    to: "DecisionNode7"
    into: "in"
  - from: "DecisionNode8"
    via: "yes"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "GetCatalogFiltersByDomain1"
    via: "next"
    to: "Loop4"
    into: "in"
  - from: "GetCatalogFiltersByDomain2"
    via: "next"
    to: "Loop5"
    into: "in"
  - from: "GetExpiredCatalogFilters1"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "GetOrganizationByName1"
    via: "next"
    to: "GetOrganizations4"
    into: "in"
  - from: "GetOrganizations4"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Loop4"
    into: "loop"
  - from: "JoinNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "ManipulateStack3"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "JoinNode4"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "GetExpiredCatalogFilters1"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "Loop5"
    into: "loop"
  - from: "KeyMapper1"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "Loop4"
    via: "do"
    to: "PurgeCatalogFilter1"
    into: "in"
  - from: "Loop4"
    via: "next"
    to: "GetCatalogFiltersByDomain2"
    into: "in"
  - from: "Loop5"
    via: "do"
    to: "DecisionNode4"
    into: "in"
  - from: "Loop5"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "Pipelet5"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "DecisionNode1"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "LoopNode3"
    via: "do"
    to: "ManipulateStack4"
    into: "in"
  - from: "LoopNode3"
    via: "next"
    to: "SwitchToNextPage2"
    into: "in"
  - from: "ManipulateStack2"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "ManipulateStack3"
    via: "error"
    to: "EndNode6"
    into: "in"
  - from: "ManipulateStack3"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "ManipulateStack4"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "Pipelet1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "ManipulateStack2"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "Pipelet7"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "PurgeCatalogFilter1"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "PurgeCatalogFilter1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "RemoveDeadCatalogFilterRules1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "End4"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "SetDictionaryValue5"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "Start11"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Start12"
    via: "next"
    to: "GetOrganizationByName1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode8"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode0"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "GetCatalogFiltersByDomain1"
    into: "in"
  - from: "SwitchToNextPage2"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "SwitchToNextPage2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
