flow: "StagingCleanUp"
kind: "process"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CloseDatabaseConnections1"
    type: "pipelet"
    ref: "CloseDatabaseConnections"
  - id: "End1"
    type: "end"

links:
  - from: "Start1"
    via: "next"
    to: "CloseDatabaseConnections1"
    into: "in"
  - from: "CloseDatabaseConnections1"
    via: "next"
    to: "End1"
    into: "in"
