flow: "StagingResources"
kind: "process"

entries:
  - id: "StartNode1"
    name: "Acquire"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Release"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Convert1"
    type: "pipelet"
    ref: "Convert"
    config:
      ResultClass: "java.lang.Integer"
    bindings:
      Object1: "AcquisitionTimeoutString"
      ResultObject: "AcquisitionTimeout"
  - id: "DecisionNode1"
    type: "decision"
    condition: "StagingProcess"
  - id: "DecisionNode2"
    type: "decision"
    condition: "StagingProcess"
  - id: "DecisionNode3"
    type: "decision"
    condition: "StagingProcessID"
  - id: "DecisionNode4"
    type: "decision"
    condition: "StagingProcessID"
  - id: "DecisionNode5"
    type: "decision"
    condition: "Resources"
  - id: "EndNode1"
    type: "end"
  - id: "EndNode2"
    type: "end"
  - id: "EndNode3"
    type: "end"
  - id: "EndNode4"
    type: "end"
  - id: "EndNode5"
    type: "end"
  - id: "GetProperties1"
    type: "pipelet"
    ref: "GetProperties"
    config:
      PropertyName1: "staging.locking.acquisition.timeout"
      DictionaryKey1: "AcquisitionTimeoutString"
      DefaultValue1: 1200
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "AcquireResourcesForProcess"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "GetStagingProcess"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "GetResourcesOfStagingProcess"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "GetStagingProcess"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "ReleaseResourcesForProcess"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "GetResourcesOfStagingProcess"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "PutValuesIntoPipelineDictionary"
    config:
      key.1: "AcquisitionResult"
      value.1: "Failed"
      UseStaticValues: true
  - id: "PutValuesIntoPipelineDictionary1"
    type: "pipelet"
    ref: "PutValuesIntoPipelineDictionary"
    config:
      key.1: "AcquisitionResult"
      value.1: "Succeed"
      UseStaticValues: true
  - id: "StartStagingResourceWorker1"
    type: "pipelet"
    ref: "StartStagingResourceWorker"

links:
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "EndNode4"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Pipelet6"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "Pipelet2"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "EndNode5"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "Pipelet4"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "Pipelet2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "Pipelet7"
    into: "in"
  - from: "Pipelet7"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "StartStagingResourceWorker1"
    into: "in"
  - from: "GetProperties1"
    via: "next"
    to: "Convert1"
    into: "in"
  - from: "StartStagingResourceWorker1"
    via: "next"
    to: "PutValuesIntoPipelineDictionary1"
    into: "in"
  - from: "PutValuesIntoPipelineDictionary1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Convert1"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode3"
    into: "in2"
  - from: "DecisionNode5"
    via: "yes"
    to: "Pipelet1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet6"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetProperties1"
    into: "in"
