flow: "StagingProcess"
kind: "process"

entries:
  - id: "Start1"
    name: "Init"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start10"
    name: "ProcessPublication"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start11"
    name: "Publication"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start12"
    name: "Replication"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Finish"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Undo"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "ProcessReplication"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "ProcessUndo"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "ProcessInitialPublication"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "Error"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "start1"
    name: "ReplicationPublication"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "StagingProcessCustomization-OnPostPublication"
  - id: "Call10"
    type: "call"
    ref: "StagingProcessCustomization-OnPostSaveNoneUndoContent"
  - id: "Call11"
    type: "call"
    ref: "StagingProcessCustomization-OnPrePublication"
  - id: "Call12"
    type: "call"
    ref: "StagingProcessCustomization-OnPreCompletion"
  - id: "Call2"
    type: "call"
    ref: "StagingProcess-ProcessReplication"
  - id: "Call3"
    type: "call"
    ref: "StagingProcess-ProcessPublication"
  - id: "Call4"
    type: "call"
    ref: "StagingProcessCustomization-OnPrePublication"
  - id: "Call5"
    type: "call"
    ref: "StagingProcessCustomization-OnPreSaveNoneUndoContent"
  - id: "Call6"
    type: "call"
    ref: "StagingCleanUp-Start"
  - id: "Call7"
    type: "call"
    ref: "StagingProcessCustomization-OnPreReplication"
  - id: "Call8"
    type: "call"
    ref: "StagingProcessCustomization-OnPostReplication"
  - id: "Call9"
    type: "call"
    ref: "StagingProcessCustomization-OnPostPublication"
  - id: "CallNode1"
    type: "call"
    ref: "StagingResources-Release"
  - id: "CallNode2"
    type: "call"
    ref: "StagingProcess-ProcessPublication"
  - id: "CallNode3"
    type: "call"
    ref: "StagingProcess-ProcessReplication"
  - id: "CallNode4"
    type: "call"
    ref: "StagingProcess-ProcessInitialPublication"
  - id: "CallNode5"
    type: "call"
    ref: "StagingProcess-ProcessPublication"
  - id: "CallNode6"
    type: "call"
    ref: "StagingProcess-ProcessUndo"
  - id: "Decision5"
    type: "decision"
    condition: "StagingProcessMode"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End11"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End21"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "ExecuteStoredProcedure1"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      StoredProcedure: "sp_compile_invalid_objects"
  - id: "ExecuteStoredProcedure2"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      StoredProcedure: "sp_compile_invalid_objects"
  - id: "Join1"
    type: "join"
  - id: "Join10"
    type: "join"
  - id: "Join11"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "StagingProcess-Error"
  - id: "Jump2"
    type: "jump"
    ref: "StagingProcess-Error"
  - id: "Jump3"
    type: "jump"
    ref: "StagingProcess-Error"
  - id: "Jump4"
    type: "jump"
    ref: "StagingProcess-Error"
  - id: "Jump5"
    type: "jump"
    ref: "StagingProcess-Error"
  - id: "Jump7"
    type: "jump"
    ref: "StagingProcess-Finish"
  - id: "Jump8"
    type: "jump"
    ref: "StagingProcess-Finish"
  - id: "Jump9"
    type: "jump"
    ref: "StagingProcess-Finish"
  - id: "JumpNode1"
    type: "jump"
    ref: "StagingProcess-Finish"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetStagingProcess"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "SetStagingState"
    config:
      StagingState: "ErrorUpdatingDeletionTrackingInLiveSystem"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "SetUndoStagingState"
    config:
      UndoComponentsState: "StagingUndoCompleted"
      NoneUndoComponentsState: "StagingProcessCompleted"
  - id: "Pipelet12"
    type: "pipelet"
    ref: "SetUndoStagingState"
    config:
      UndoComponentsState: "ErrorUndoStaging"
      NoneUndoComponentsState: "ErrorCompletingStagingProcess"
  - id: "Pipelet13"
    type: "pipelet"
    ref: "SetStagingState"
    config:
      StagingState: "StagingInitialized"
  - id: "Pipelet15"
    type: "pipelet"
    ref: "SetStagingState"
    config:
      StagingState: "ErrorInternalInLiveSystem"
  - id: "Pipelet16"
    type: "pipelet"
    ref: "ProcessRestoreUndoContent"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "GetStagingProcess"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "GetStagingProcess"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "GetStagingProcess"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "SetStagingState"
    config:
      StagingState: "StagingProcessCompleted"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      StoredProcedure: "sp_update_deletion_tracking"
      Parameters: "'DeltaDomainSpecificStagingProcessor'"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "SetStagingState"
    config:
      StagingState: "ReplicationProcessCompleted"
  - id: "Pipelet9"
    type: "pipelet"
    ref: "SetStagingState"
    config:
      StagingState: "StagingProcessCompleted"
  - id: "PrepareStagingTables1"
    type: "pipelet"
    ref: "PrepareStagingTables"
  - id: "PrepareStagingTables2"
    type: "pipelet"
    ref: "PrepareStagingTables"
  - id: "ProcessPublication1"
    type: "pipelet"
    ref: "ProcessPublication"
  - id: "ProcessPublication2"
    type: "pipelet"
    ref: "ProcessPublication"
  - id: "ProcessRefreshCache1"
    type: "pipelet"
    ref: "ProcessRefreshCache"
  - id: "ProcessRefreshCache2"
    type: "pipelet"
    ref: "ProcessRefreshCache"
  - id: "ProcessReplication1"
    type: "pipelet"
    ref: "ProcessReplication"
  - id: "ProcessSaveNoneUndoContent2"
    type: "pipelet"
    ref: "ProcessSaveNoneUndoContent"
  - id: "ProcessSynchronization1"
    type: "pipelet"
    ref: "ProcessSynchronization"
  - id: "Stop2"
    type: "stop"
  - id: "WaitForStagingProcessState1"
    type: "pipelet"
    ref: "WaitForStagingProcessState"
    config:
      PollInterval: 10
      Timeout: 3600
      WaitForStagingState: "StartRefreshCache"
      TimeoutPropertyKey: "staging.timeout.waitingForState"
  - id: "WaitForStagingProcessState2"
    type: "pipelet"
    ref: "WaitForStagingProcessState"
    config:
      PollInterval: 10
      Timeout: 3600
      WaitForStagingState: "StartPublication"
      TimeoutPropertyKey: "staging.timeout.waitingForState"

links:
  - from: "Pipelet15"
    via: "next"
    to: "JoinNode6"
    into: "in2"
  - from: "ProcessSynchronization1"
    via: "error"
    to: "Join11"
    into: "in2"
  - from: "ExecuteStoredProcedure2"
    via: "error"
    to: "JoinNode10"
    into: "in2"
  - from: "Call1"
    via: "error"
    to: "Join7"
    into: "in2"
  - from: "Join7"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "ProcessPublication2"
    into: "in"
  - from: "ProcessReplication1"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "Pipelet8"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "Join10"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "ProcessRefreshCache1"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "ProcessPublication1"
    via: "error"
    to: "Join8"
    into: "in2"
  - from: "Call6"
    via: "next"
    to: "Stop2"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "Pipelet15"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "Pipelet13"
    via: "next"
    to: "Jump7"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Pipelet9"
    into: "in"
  - from: "CallNode6"
    via: "error"
    to: "Pipelet12"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "ProcessPublication2"
    via: "next"
    to: "ProcessRefreshCache2"
    into: "in"
  - from: "Call4"
    via: "error"
    to: "Join6"
    into: "in1"
  - from: "Call1"
    via: "next"
    to: "End3"
    into: "in"
  - from: "ProcessRefreshCache1"
    via: "next"
    to: "ExecuteStoredProcedure1"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "End21"
    into: "in"
  - from: "Start10"
    via: "next"
    to: "Call11"
    into: "in"
  - from: "Call11"
    via: "next"
    to: "WaitForStagingProcessState2"
    into: "in"
  - from: "start1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "ProcessPublication1"
    via: "next"
    to: "WaitForStagingProcessState1"
    into: "in"
  - from: "WaitForStagingProcessState1"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "WaitForStagingProcessState2"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "Join9"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "Call9"
    via: "error"
    to: "Join9"
    into: "in2"
  - from: "Start4"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "ProcessReplication1"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "End11"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "ProcessSynchronization1"
    into: "in"
  - from: "Join10"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "PrepareStagingTables2"
    into: "in"
  - from: "Call8"
    via: "error"
    to: "Join10"
    into: "in2"
  - from: "Join11"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Call7"
    via: "error"
    to: "Join11"
    into: "in1"
  - from: "Call12"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "Start12"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "JoinNode3"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "PrepareStagingTables1"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "Pipelet13"
    into: "in"
  - from: "Call11"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "Jump9"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "Start11"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "ExecuteStoredProcedure1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "ExecuteStoredProcedure1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "PrepareStagingTables1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "PrepareStagingTables2"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "Pipelet7"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Pipelet7"
    via: "error"
    to: "Pipelet10"
    into: "in"
  - from: "Pipelet10"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "WaitForStagingProcessState1"
    via: "next"
    to: "ProcessRefreshCache1"
    into: "in"
  - from: "WaitForStagingProcessState2"
    via: "next"
    to: "ProcessPublication1"
    into: "in"
  - from: "Pipelet9"
    via: "next"
    to: "Jump8"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Decision5"
    into: "in"
  - from: "Decision5"
    via: "yes"
    to: "Pipelet8"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "Decision5"
    via: "no"
    to: "CallNode5"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Pipelet11"
    into: "in"
  - from: "Pipelet11"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "ProcessRefreshCache2"
    via: "error"
    to: "Join4"
    into: "in2"
  - from: "ProcessSynchronization1"
    via: "next"
    to: "ProcessReplication1"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Pipelet12"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Call5"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "Join5"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "ProcessSaveNoneUndoContent2"
    via: "error"
    to: "Join5"
    into: "in2"
  - from: "JoinNode6"
    via: "next"
    to: "Call12"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Pipelet16"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "Call10"
    via: "error"
    to: "Join3"
    into: "in2"
  - from: "Pipelet4"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "ProcessSaveNoneUndoContent2"
    via: "next"
    to: "Pipelet16"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "ExecuteStoredProcedure2"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "Call5"
    via: "next"
    to: "ProcessSaveNoneUndoContent2"
    into: "in"
  - from: "ProcessPublication2"
    via: "error"
    to: "Join6"
    into: "in2"
  - from: "Pipelet16"
    via: "error"
    to: "JoinNode8"
    into: "in2"
  - from: "Start5"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "ProcessRefreshCache2"
    via: "next"
    to: "ExecuteStoredProcedure2"
    into: "in"
