flow: "SynchronizePages"
kind: "job"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "null"
      Objects: "null"
      Iterator: "null"
      OutVector: "TypeCodes"
      Object: "\"(Integer)42\""
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Object: "\"(Integer)52\""
      InVector: "TypeCodes"
      Objects: "null"
      Iterator: "null"
      OutVector: "TypeCodes"
  - id: "AddObjectToVector3"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Object: "\"(Integer)21\""
      InVector: "TypeCodes"
      Objects: "null"
      Iterator: "TypeCodes"
      OutVector: "null"
  - id: "CallNode1"
    type: "call"
    ref: "SynchronizePagelets-Start"
    bindings:
      Site: "Repository:RepositoryDomain:Site"
      RepositoryDomain: "Repository:RepositoryDomain"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "ExecuteObjectsQuery1"
    type: "pipelet"
    ref: "ExecuteObjectsQuery"
    config:
      QueryName: "catalog/GetRepositoriesByTypeCodes"
      ParameterName_01: "TypeCodes"
      ParameterName_02: "ProxyFlag"
      Datasource: "current ORM connection"
    bindings:
      Connection: "null"
      Parameters: "null"
      Query: "null"
      ParameterValue_05: "null"
      ParameterValue_04: "null"
      ParameterValue_03: "null"
      SearchResult: "Repositories"
      ParameterValue_01: "TypeCodes"
      ParameterValue_02: "\"(Integer)0\""
  - id: "LoopNode1"
    type: "loop"

links:
  - from: "StartNode1"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "ExecuteObjectsQuery1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "AddObjectToVector1"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "AddObjectToVector3"
    into: "in"
  - from: "AddObjectToVector3"
    via: "next"
    to: "ExecuteObjectsQuery1"
    into: "in"
