flow: "TriggerReplicationProcess"
kind: "process"

entries:
  - id: "Start5"
    name: "Start"
    mode: "private"
    strict: true
    inputs:
      - key: "ReplicationProcess"
        type: "com.intershop.beehive.core.capi.replication.ReplicationProcess"
        required: false
      - key: "Synchronously"
        type: "java.lang.String"
        required: false
  - id: "Start6"
    name: "Schedule"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "Start7"
    name: "Error"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "SetState"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "StartReplicationProcessById"
    mode: "private"
    strict: true
    inputs:
      - key: "ReplicationProcessID"
        type: "java.lang.String"
        required: false
  - id: "StartNode3"
    name: "Trigger"
    mode: "private"
    strict: true
    inputs:
      - key: "ReplicationProcess"
        type: "com.intershop.beehive.core.capi.replication.ReplicationProcess"
        required: true
      - key: "Synchronously"
        type: "java.lang.String"
        required: false
  - id: "StartNode4"
    name: "CreateAndStart"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddEntryToMap1"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      OutMap: "Parameters"
      Key: "\"CurrentDate\""
      Value: "CurrentDate"
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "Sites"
      Iterator: "SiteNames"
      Object: "null"
      Objects: "ReplicationTask:PageCacheSiteNames"
      OutVector: "Sites"
  - id: "AddReplicationTaskToReplicationProcess1"
    type: "pipelet"
    ref: "AddReplicationTaskToReplicationProcess"
  - id: "Call1"
    type: "call"
    ref: "TriggerReplicationProcess-CreateAndStart"
  - id: "Call10"
    type: "call"
    ref: "TriggerReplicationProcess-Start"
  - id: "Call11"
    type: "call"
    ref: "TriggerReplicationProcess-SetState"
  - id: "Call14"
    type: "call"
    ref: "TriggerUndoProcess-Start"
  - id: "Call16"
    type: "call"
    ref: "TriggerStagingProcess-Start"
  - id: "Call17"
    type: "call"
    ref: "TriggerReplicationProcess-SetState"
  - id: "Call18"
    type: "call"
    ref: "TriggerPublicationProcess-Start"
  - id: "Call19"
    type: "call"
    ref: "TriggerInitialStagingProcess-Start"
  - id: "CallNode1"
    type: "call"
    ref: "TriggerStagingProcess-Error"
  - id: "CallNode2"
    type: "call"
    ref: "TriggerReplicationProcess-Trigger"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessReplicationProcess-CreateFromConfiguration"
    bindings:
      ReplicationProcess: "PredefinedReplicationProcess"
  - id: "CallNode4"
    type: "call"
    ref: "TriggerReplicationProcess-Start"
    bindings:
      Synchronously: "\"true\""
      ReplicationProcess: "PredefinedReplicationProcess"
  - id: "CreateIteratorFromPageable1"
    type: "pipelet"
    ref: "CreateIteratorFromPageable"
    bindings:
      PageableIterator: "Processes"
      ResettableIterator: "Processes"
  - id: "CreateReplicationProcess1"
    type: "pipelet"
    ref: "CreateReplicationProcess"
    bindings:
      Domain: "OldReplicationProcess:Domain"
  - id: "CreateStringSplitter1"
    type: "pipelet"
    ref: "CreateStringSplitter"
    config:
      Mode: "First Occurrence"
      Separator: "-"
  - id: "DecisionNode1"
    type: "decision"
    condition: "StagingProcess:EndDate"
  - id: "DecisionNode10"
    type: "decision"
    condition: "ReplicationProcess:PublicationScheduleDate:Time"
  - id: "DecisionNode11"
    type: "decision"
    condition: "Synchronously"
  - id: "DecisionNode12"
    type: "decision"
    condition: "ReplicationProcess:ReplicationTasksState"
  - id: "DecisionNode13"
    type: "decision"
    condition: "ReplicationProcess:PublicationScheduleDate"
  - id: "DecisionNode2"
    type: "decision"
    condition: "StagingProcess"
  - id: "DecisionNode3"
    type: "decision"
    condition: "ReplicationProcess:Type"
  - id: "DecisionNode4"
    type: "decision"
    condition: "StagingProcessMode"
  - id: "DecisionNode5"
    type: "decision"
    condition: "StagingProcessMode"
  - id: "DecisionNode6"
    type: "decision"
    condition: "StagingProcessMode"
  - id: "DecisionNode8"
    type: "decision"
    condition: "ReplicationProcess:Type"
  - id: "DecisionNode9"
    type: "decision"
    condition: "ReplicationProcess:State"
  - id: "End11"
    type: "end"
    strict: true
  - id: "End9"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "ReplicationProcess"
        type: "com.intershop.beehive.core.capi.replication.ReplicationProcess"
        guaranteed: true
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "EndNode5"
    type: "end"
    strict: false
  - id: "EndNode6"
    type: "end"
    strict: true
  - id: "EndNode7"
    type: "end"
    strict: true
  - id: "EndNode8"
    type: "end"
    strict: true
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "replication/GetAllReplicationProcesses"
      DefaultPageSize: 10
      Datasource: "default"
    bindings:
      SearchResult: "Processes"
  - id: "ExecutePipeline1"
    type: "pipelet"
    ref: "ExecutePipeline"
    config:
      PipelineName: "TriggerReplicationProcess"
      PipelineStartNode: "Trigger"
      Asynchronous: true
      PipelineDomainName: "CurrentDomain"
  - id: "ExecutePipeline2"
    type: "pipelet"
    ref: "ExecutePipeline"
    config:
      PipelineName: "TriggerReplicationProcess"
      PipelineStartNode: "Trigger"
      Asynchronous: true
      PipelineDomainName: "CurrentDomain"
  - id: "ExecutePipeline3"
    type: "pipelet"
    ref: "ExecutePipeline"
    config:
      Asynchronous: false
    bindings:
      PipelineDomain: "ReplicationTaskOrganizationDomain:Site"
      PipelineName: "\"ProcessReplicationTask\""
      PipelineStartNode: "\"Assign\""
  - id: "GetCurrentDate1"
    type: "pipelet"
    ref: "GetCurrentDate"
  - id: "GetCurrentDate2"
    type: "pipelet"
    ref: "GetCurrentDate"
  - id: "GetCurrentDate3"
    type: "pipelet"
    ref: "GetCurrentDate"
  - id: "GetCurrentDate4"
    type: "pipelet"
    ref: "GetCurrentDate"
  - id: "GetCurrentReplicationProcess1"
    type: "pipelet"
    ref: "GetCurrentReplicationProcess"
    bindings:
      TargetSystemName: "TargetSystem:Name"
  - id: "GetDomain1"
    type: "pipelet"
    ref: "GetDomain"
    bindings:
      StagingDomainName: "Splitter:Begin(ReplicationTask:Domain:DomainName)"
      StagingDomain: "ReplicationTaskOrganizationDomain"
  - id: "GetReplicationProcessByUUID1"
    type: "pipelet"
    ref: "GetReplicationProcessByUUID"
    bindings:
      UUID: "Process:UUID"
  - id: "GetTargetClusters1"
    type: "pipelet"
    ref: "GetTargetClusters"
  - id: "GrantStagingDatabasePrivsToTargetCluster1"
    type: "pipelet"
    ref: "GrantStagingDatabasePrivsToTargetCluster"
  - id: "Join10"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ReplicationProcess:Type"
      InValue_2: "ReplicationProcess:TargetSystem"
      OutValue_1: "StagingProcessMode"
      OutValue_2: "TargetSystemName"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ReplicationProcess"
      OutValue_1: "StagingContentProvider"
      InValue_2: "ReplicationProcess"
      OutValue_2: "ErrorHandler"
      InValue_3: "ReplicationProcess:Type"
      OutValue_3: "StagingProcessMode"
      InValue_4: "ReplicationProcess:TargetCluster"
      OutValue_4: "TargetCluster"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_2: "ReplicationProcess:TargetSystem"
      OutValue_2: "TargetSystemName"
      InValue_3: "ReplicationProcess"
      OutValue_3: "OldReplicationProcess"
  - id: "Loop1"
    type: "loop"
  - id: "Loop2"
    type: "loop"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetStagingProcess"
    bindings:
      StagingProcessID: "StagingProcess:UUID"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "Wait"
    config:
      MillisecondsToWait: 10000
  - id: "Pipelet3"
    type: "pipelet"
    ref: "UpdateReplicationProcessState"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "StagingProcessMode"
      Value: "Publication"
      ValueType: "Dictionary Value"
  - id: "TextNode1"
    type: "text"
  - id: "TextNode2"
    type: "text"
  - id: "TextNode4"
    type: "text"
  - id: "UpdateReplicationProcess1"
    type: "pipelet"
    ref: "UpdateReplicationProcess"
    bindings:
      Description: "null"
      Locale: "null"
      ProcessID: "null"
      ScheduleTime: "null"
      State: "\"FAILED\""
      TargetSystem: "null"
      Type: "null"
      StartTime: "null"
      EndTime: "CurrentDate"
  - id: "UpdateReplicationProcess2"
    type: "pipelet"
    ref: "UpdateReplicationProcess"
    bindings:
      Description: "null"
      Locale: "null"
      ProcessID: "null"
      ScheduleTime: "null"
      StartTime: "CurrentDate"
      State: "\"RUNNING\""
      TargetSystem: "null"
      Type: "null"
  - id: "UpdateReplicationProcess3"
    type: "pipelet"
    ref: "UpdateReplicationProcess"
    bindings:
      Description: "OldReplicationProcess:Description"
      Locale: "null"
      ProcessID: "OldReplicationProcess:ProcessID"
      ScheduleTime: "null"
      StartTime: "null"
      State: "\"WAITING\""
      TargetSystem: "OldReplicationProcess:TargetSystem"
      Type: "StagingProcessMode"
      EndTime: "null"
      PublicationScheduleTime: "OldReplicationProcess:PublicationScheduleDate"
      TargetCluster: "OldReplicationProcess:TargetCluster"
  - id: "UpdateReplicationProcess4"
    type: "pipelet"
    ref: "UpdateReplicationProcess"
    bindings:
      Description: "null"
      Locale: "null"
      ProcessID: "null"
      ScheduleTime: "null"
      StartTime: "CurrentDate"
      State: "\"RUNNING\""
      TargetSystem: "null"
      Type: "null"
      EndTime: "null"
  - id: "UpdateReplicationProcess5"
    type: "pipelet"
    ref: "UpdateReplicationProcess"
    bindings:
      Description: "null"
      EndTime: "null"
      Locale: "null"
      ProcessID: "null"
      PublicationScheduleTime: "null"
      ReplicationProcess: "OldReplicationProcess"
      ScheduleTime: "null"
      StartTime: "null"
      State: "null"
      TargetSystem: "null"
      Type: "null"

links:
  - from: "GrantStagingDatabasePrivsToTargetCluster1"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "Call18"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "GetTargetClusters1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "DecisionNode6"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "Call14"
    into: "in"
  - from: "Call19"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Call14"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "Call18"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "Call16"
    via: "next"
    to: "JoinNode6"
    into: "in2"
  - from: "DecisionNode6"
    via: "no"
    to: "Call16"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "GetCurrentDate3"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "Call17"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "GetCurrentDate1"
    into: "in"
  - from: "AddEntryToMap1"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "Join10"
    into: "in1"
  - from: "GetCurrentReplicationProcess1"
    via: "next"
    to: "DecisionNode8"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "GetCurrentDate2"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "GetTargetClusters1"
    into: "in"
  - from: "Join10"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "GetReplicationProcessByUUID1"
    via: "error"
    to: "Join10"
    into: "in3"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode3"
    into: "in2"
  - from: "StartNode2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "DecisionNode8"
    via: "yes"
    to: "DecisionNode9"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "CreateIteratorFromPageable1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetReplicationProcessByUUID1"
    into: "in"
  - from: "CreateIteratorFromPageable1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "GetReplicationProcessByUUID1"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "GetCurrentReplicationProcess1"
    into: "in"
  - from: "DecisionNode9"
    via: "yes"
    to: "DecisionNode13"
    into: "in"
  - from: "ExecutePipeline3"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "UpdateReplicationProcess1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Loop2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "CreateReplicationProcess1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "Start7"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode1"
    into: "in1"
  - from: "GetCurrentDate1"
    via: "next"
    to: "UpdateReplicationProcess1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet3"
    into: "in"
  - from: "CreateReplicationProcess1"
    via: "next"
    to: "UpdateReplicationProcess3"
    into: "in"
  - from: "GetCurrentDate4"
    via: "next"
    to: "CreateReplicationProcess1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "UpdateReplicationProcess2"
    via: "next"
    to: "DecisionNode11"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "UpdateReplicationProcess3"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "ExecutePipeline1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode7"
    into: "in2"
  - from: "StartNode3"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "ExecutePipeline1"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "AddReplicationTaskToReplicationProcess1"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "GrantStagingDatabasePrivsToTargetCluster1"
    into: "in"
  - from: "AddReplicationTaskToReplicationProcess1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "LoopNode1"
    via: "next"
    to: "UpdateReplicationProcess4"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "GetCurrentDate4"
    into: "in"
  - from: "UpdateReplicationProcess4"
    via: "next"
    to: "UpdateReplicationProcess5"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "GetDomain1"
    via: "next"
    to: "ExecutePipeline3"
    into: "in"
  - from: "DecisionNode11"
    via: "no"
    to: "ExecutePipeline2"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "GetCurrentDate3"
    via: "next"
    to: "UpdateReplicationProcess2"
    into: "in"
  - from: "DecisionNode11"
    via: "yes"
    to: "CallNode2"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "Loop2"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "error"
    to: "EndNode8"
    into: "in"
  - from: "Loop2"
    via: "do"
    to: "CreateStringSplitter1"
    into: "in"
  - from: "Call17"
    via: "next"
    to: "End11"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "ExecutePipeline2"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode12"
    via: "yes"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "Call11"
    into: "in"
  - from: "Call11"
    via: "next"
    to: "End9"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "Call19"
    into: "in"
  - from: "GetCurrentReplicationProcess1"
    via: "error"
    to: "JoinNode13"
    into: "in2"
  - from: "Call1"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode9"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "DecisionNode12"
    via: "no"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode9"
    into: "in2"
  - from: "DecisionNode10"
    via: "no"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "JoinNode10"
    into: "in2"
  - from: "DecisionNode9"
    via: "no"
    to: "JoinNode12"
    into: "in1"
  - from: "DecisionNode13"
    via: "no"
    to: "JoinNode14"
    into: "in2"
  - from: "DecisionNode8"
    via: "no"
    to: "JoinNode13"
    into: "in1"
  - from: "DecisionNode4"
    via: "no"
    to: "DecisionNode5"
    into: "in"
  - from: "JoinNode13"
    via: "next"
    to: "JoinNode12"
    into: "in2"
  - from: "DecisionNode13"
    via: "yes"
    to: "DecisionNode10"
    into: "in"
  - from: "JoinNode12"
    via: "next"
    to: "JoinNode14"
    into: "in1"
  - from: "JoinNode14"
    via: "next"
    to: "JoinNode11"
    into: "in2"
  - from: "UpdateReplicationProcess5"
    via: "next"
    to: "ExecutePipeline1"
    into: "in"
  - from: "DecisionNode10"
    via: "yes"
    to: "DecisionNode12"
    into: "in"
  - from: "CreateStringSplitter1"
    via: "next"
    to: "GetDomain1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "GetCurrentDate2"
    via: "next"
    to: "AddEntryToMap1"
    into: "in"
