flow: "TriggerDeleteDomainReferences"
kind: "process"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "DecisionNode1"
    type: "decision"
    condition: "Domains"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Domains"
  - id: "DecisionNode3"
    type: "decision"
    condition: "JobConfigurationUUID"
  - id: "DetermineDefaultRepositoryDomainFromJobConfigurationApplication1"
    type: "pipelet"
    ref: "DetermineDefaultRepositorySiteFromJobConfigurationApplication"
    bindings:
      DefaultRepositorySite: "CurrentDomain"
  - id: "DetermineToBeDeletedDomains1"
    type: "pipelet"
    ref: "DetermineToBeDeletedDomains"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "ExecuteCartridgePipelines1"
    type: "pipelet"
    ref: "ExecuteCartridgePipelines"
    config:
      Asynchronous: false
      PipelinePropertyName: "DomainDeletionPipeline"
      ProcessReversely: true
      FailOn: "error"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "Loop1"
    type: "loop"
  - id: "PrepareDeleteDomain1"
    type: "pipelet"
    ref: "PrepareDeleteDomain"
  - id: "RefreshCache1"
    type: "pipelet"
    ref: "RefreshCache"
  - id: "TextNode1"
    type: "text"
  - id: "TextNode2"
    type: "text"

links:
  - from: "Loop1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode3"
    into: "in2"
  - from: "DecisionNode1"
    via: "yes"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "DetermineDefaultRepositoryDomainFromJobConfigurationApplication1"
    into: "in"
  - from: "ExecuteCartridgePipelines1"
    via: "next"
    to: "RefreshCache1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "End1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "Loop1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "DetermineDefaultRepositoryDomainFromJobConfigurationApplication1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "DetermineToBeDeletedDomains1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "PrepareDeleteDomain1"
    into: "in"
  - from: "RefreshCache1"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "DetermineToBeDeletedDomains1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "ExecuteCartridgePipelines1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "PrepareDeleteDomain1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "PrepareDeleteDomain1"
    via: "next"
    to: "ExecuteCartridgePipelines1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in1"
