flow: "UpdateObjectStatisticsRealtime"
kind: "view"

entries:
  - id: "StartNode1"
    name: "UpdateAsync"
    mode: "private"
    strict: true
    inputs:
      - key: "GroupName"
        type: "java.lang.String"
        required: true
      - key: "ObjectDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode3"
    name: "ExecuteUpdate"
    mode: "private"
    strict: true
    inputs:
      - key: "ObjectStatisticsGroup"
        type: "com.intershop.component.foundation.capi.objectstatistics.ObjectStatisticsGroup"
        required: true
  - id: "StartNode4"
    name: "Error"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "GetResource"
    mode: "private"
    strict: true
    inputs:
      - key: "ObjectStatisticsGroup"
        type: "com.intershop.component.foundation.capi.objectstatistics.ObjectStatisticsGroup"
        required: true
  - id: "StartNode6"
    name: "Update"
    mode: "private"
    strict: true
    inputs:
      - key: "GroupName"
        type: "java.lang.String"
        required: true
      - key: "ObjectDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode7"
    name: "ObtainGroup"
    mode: "private"
    strict: true
    inputs:
      - key: "GroupName"
        type: "java.lang.String"
        required: true
      - key: "ObjectDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true

steps:
  - id: "AcquireResourcesForProcess1"
    type: "pipelet"
    ref: "AcquireResourcesForProcess"
    bindings:
      AcquisitionTimeout: "\"(Integer)0\""
      ResourceIDs: "null"
      Resources: "Resources"
      Acquisitions: "null"
      Process: "ObjectStatisticsUpdateProcess"
  - id: "AcquireResourcesForProcess2"
    type: "pipelet"
    ref: "AcquireResourcesForProcess"
    bindings:
      AcquisitionTimeout: "\"(Integer)300\""
      ResourceIDs: "null"
      Resources: "Resources"
      Acquisitions: "null"
      Process: "ObjectStatisticsUpdateProcess"
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      InVector: "null"
      Object: "Resource"
      Objects: "null"
      Iterator: "null"
      OutVector: "Resources"
  - id: "AddObjectToVector4"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      InVector: "null"
      Object: "\"OBJECTSTATISTICSGROUP\""
      Objects: "null"
      Iterator: "TableNames"
      OutVector: "null"
  - id: "CallNode1"
    type: "call"
    ref: "UpdateObjectStatisticsRealtime-GetResource"
  - id: "CallNode2"
    type: "call"
    ref: "UpdateObjectStatisticsRealtime-ExecuteUpdate"
  - id: "CallNode3"
    type: "call"
    ref: "UpdateObjectStatisticsRealtime-ObtainGroup"
  - id: "CallNode4"
    type: "call"
    ref: "UpdateObjectStatisticsRealtime-ObtainGroup"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "\"Update object statistics \""
      String1: "ObjectStatisticsGroup:GroupName"
      String2: "\"@\""
      String3: "ObjectStatisticsGroup:Domain:DomainName"
      Concatenated: "ProcessName"
  - id: "ConcatenateStrings3"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "\"Update object statistics for '\""
      String1: "ObjectStatisticsGroup:GroupName"
      String2: "\"' of domain '\""
      String3: "ObjectStatisticsGroup:Domain:DomainName"
      String4: "\"'\""
      Concatenated: "ProcessDescription"
  - id: "CreateDatabaseTableResources2"
    type: "pipelet"
    ref: "CreateDatabaseTableResources"
    bindings:
      TableNames: "TableNames"
      Resources: "ParentResource"
  - id: "CreateObjectStatisticsGroup1"
    type: "pipelet"
    ref: "CreateObjectStatisticsGroup"
  - id: "CreateProcess1"
    type: "pipelet"
    ref: "CreateProcess"
    config:
      Type: "ObjectStatisticsUpdate"
      InitialState: "running"
    bindings:
      ProcessName: "ProcessName"
      User: "null"
      Type: "null"
      Process: "ObjectStatisticsUpdateProcess"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ObjectStatisticsGroup"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ObjectStatisticsUpdateProcess"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Resource:ResourceOwner"
  - id: "DecisionNode4"
    type: "decision"
    condition: "ResourceAcquisitionResult:ContentionProcess:Type"
  - id: "DecisionNode5"
    type: "decision"
    condition: "ResourceAcquisitionResult:ContentionProcess:Type"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode10"
    type: "end"
    strict: true
  - id: "EndNode11"
    type: "end"
    strict: true
  - id: "EndNode12"
    type: "end"
    strict: true
    outputs:
      - key: "ObjectStatisticsGroup"
        type: "com.intershop.component.foundation.capi.objectstatistics.ObjectStatisticsGroup"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "Resource"
        type: "com.intershop.beehive.core.capi.locking.Resource"
        guaranteed: true
      - key: "Resources"
        type: "java.util.Vector"
        guaranteed: true
  - id: "EndNode7"
    type: "end"
    strict: false
  - id: "EndNode8"
    type: "end"
    strict: true
    outputs:
      - key: "Resource"
        type: "com.intershop.beehive.core.capi.locking.Resource"
        guaranteed: true
      - key: "Resources"
        type: "java.util.Vector"
        guaranteed: true
  - id: "EndNode9"
    type: "end"
    strict: true
    outputs:
      - key: "Resource"
        type: "com.intershop.beehive.core.capi.locking.Resource"
        guaranteed: true
      - key: "Resources"
        type: "java.util.Vector"
        guaranteed: true
  - id: "ExecutePipeline1"
    type: "pipelet"
    ref: "ExecutePipeline"
    config:
      Asynchronous: true
      PipelineName: "UpdateObjectStatisticsRealtime"
      PipelineStartNode: "ExecuteUpdate"
    bindings:
      PipelineDomain: "CurrentDomain"
  - id: "FinishProcess1"
    type: "pipelet"
    ref: "FinishProcess"
    config:
      EndState: "skipped"
    bindings:
      Process: "ObjectStatisticsUpdateProcess"
  - id: "FinishProcess2"
    type: "pipelet"
    ref: "FinishProcess"
    bindings:
      Process: "ObjectStatisticsUpdateProcess"
  - id: "FinishProcess3"
    type: "pipelet"
    ref: "FinishProcess"
    config:
      EndState: "error"
    bindings:
      Process: "ObjectStatisticsUpdateProcess"
  - id: "FinishProcess4"
    type: "pipelet"
    ref: "FinishProcess"
    config:
      EndState: "ResourceAcquiringFailed"
    bindings:
      Process: "ObjectStatisticsUpdateProcess"
  - id: "GetObjectStatisticsGroup2"
    type: "pipelet"
    ref: "GetObjectStatisticsGroup"
    bindings:
      ObjectDomain: "ObjectDomain"
      ObjectStatisticsGroup: "ObjectStatisticsGroup"
  - id: "GetResourceByName1"
    type: "pipelet"
    ref: "GetResourceByName"
    bindings:
      Domain: "ObjectStatisticsGroup:Domain"
      ParentResource: "ParentResource:First"
      ResourceName: "ObjectStatisticsGroup:GroupName"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "QueryAndUpdateObjectStatisticsGroup1"
    type: "pipelet"
    ref: "QueryAndUpdateObjectStatisticsGroup"
    bindings:
      GroupName: "ObjectStatisticsGroup:GroupName"
      ObjectDomain: "ObjectStatisticsGroup:Domain"
  - id: "ReleaseResourcesForProcess1"
    type: "pipelet"
    ref: "ReleaseResourcesForProcess"
    bindings:
      Acquisitions: "null"
      Process: "ObjectStatisticsUpdateProcess"
  - id: "ReleaseResourcesForProcess2"
    type: "pipelet"
    ref: "ReleaseResourcesForProcess"
    bindings:
      Acquisitions: "null"
      Process: "ObjectStatisticsUpdateProcess"

links:
  - from: "AcquireResourcesForProcess1"
    via: "error"
    to: "DecisionNode4"
    into: "in"
  - from: "AcquireResourcesForProcess1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "AcquireResourcesForProcess2"
    via: "error"
    to: "FinishProcess4"
    into: "in"
  - from: "AcquireResourcesForProcess2"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "AddObjectToVector1"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "AddObjectToVector4"
    via: "next"
    to: "CreateDatabaseTableResources2"
    into: "in"
  - from: "CallNode1"
    via: "Running"
    to: "EndNode10"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CreateProcess1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "EndNode11"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "ExecutePipeline1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "ConcatenateStrings3"
    into: "in"
  - from: "ConcatenateStrings3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CreateDatabaseTableResources2"
    via: "next"
    to: "GetResourceByName1"
    into: "in"
  - from: "CreateObjectStatisticsGroup1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CreateProcess1"
    via: "next"
    to: "AcquireResourcesForProcess1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "CreateObjectStatisticsGroup1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "ReleaseResourcesForProcess2"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "EndNode8"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "AcquireResourcesForProcess2"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "FinishProcess1"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "EndNode5"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "EndNode9"
    into: "in"
  - from: "ExecutePipeline1"
    via: "error"
    to: "EndNode4"
    into: "in"
  - from: "ExecutePipeline1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "FinishProcess1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "FinishProcess2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "FinishProcess3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "FinishProcess4"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "GetObjectStatisticsGroup2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetResourceByName1"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode12"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "QueryAndUpdateObjectStatisticsGroup1"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "QueryAndUpdateObjectStatisticsGroup1"
    via: "next"
    to: "ReleaseResourcesForProcess1"
    into: "in"
  - from: "ReleaseResourcesForProcess1"
    via: "next"
    to: "FinishProcess2"
    into: "in"
  - from: "ReleaseResourcesForProcess2"
    via: "next"
    to: "FinishProcess3"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "AddObjectToVector4"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "GetObjectStatisticsGroup2"
    into: "in"
