flow: "UpdateProductOnlineStatusJob"
kind: "process"

entries:
  - id: "Start12"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call10"
    type: "call"
    ref: "GetRepositories-ChannelsReverse"
  - id: "CreateStack2"
    type: "pipelet"
    ref: "CreateStack"
    bindings:
      Stack: "OrganizationStack"
  - id: "CreateStack3"
    type: "pipelet"
    ref: "CreateStack"
    bindings:
      Stack: "ChannelStack"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "ExecuteStoredProcedure1"
    type: "pipelet"
    ref: "ExecuteStoredProcedure"
    config:
      AllowNullParameter: false
      ParameterDefinition: "CurrentDate=date;DomainID=string"
      StoredProcedure: "sp_updateProductOnlineStatus"
  - id: "GetCurrentDate1"
    type: "pipelet"
    ref: "GetCurrentDate"
  - id: "GetOrganizationByName1"
    type: "pipelet"
    ref: "GetOrganizationByName"
    config:
      DefaultName: "Operations"
    bindings:
      Name: "null"
      Organization: "Operations"
      OrganizationDomain: "OperationsDomain"
  - id: "GetOrganizations4"
    type: "pipelet"
    ref: "GetOrganizations"
    bindings:
      Organizations: "Enterprises"
      Owner: "OperationsDomain"
  - id: "Join4"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Channel:RepositoryDomain:DomainID"
      OutValue_1: "DomainID"
  - id: "Loop3"
    type: "loop"
  - id: "ManipulateStack2"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "PUSH"
    bindings:
      AddElement: "Enterprise"
      Stack: "OrganizationStack"
  - id: "ManipulateStack5"
    type: "pipelet"
    ref: "ManipulateStack"
    config:
      ProcessMethod: "POP"
    bindings:
      GetElement: "Channel"
      Stack: "ChannelStack"
  - id: "RefreshCache1"
    type: "pipelet"
    ref: "RefreshCache"
    config:
      PersistentClassName_1: "com.intershop.beehive.xcs.internal.catalog.ProductCategoryAssignmentPO"
      PersistentClassName_0: "com.intershop.beehive.xcs.internal.product.ProductPO"
      PersistentClassName_2: "com.intershop.beehive.xcs.internal.product.DerivedProductPO"

links:
  - from: "ManipulateStack2"
    via: "next"
    to: "Loop3"
    into: "loop"
  - from: "GetOrganizations4"
    via: "next"
    to: "CreateStack2"
    into: "in"
  - from: "ManipulateStack5"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Join4"
    into: "in2"
  - from: "GetCurrentDate1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "ExecuteStoredProcedure1"
    via: "error"
    to: "JoinNode1"
    into: "in3"
  - from: "ManipulateStack5"
    via: "error"
    to: "RefreshCache1"
    into: "in"
  - from: "RefreshCache1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CreateStack2"
    via: "next"
    to: "CreateStack3"
    into: "in"
  - from: "Loop3"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "GetOrganizationByName1"
    via: "next"
    to: "GetOrganizations4"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "GetCurrentDate1"
    into: "in"
  - from: "CreateStack3"
    via: "next"
    to: "Loop3"
    into: "in"
  - from: "Loop3"
    via: "do"
    to: "ManipulateStack2"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "ManipulateStack5"
    into: "in"
  - from: "ExecuteStoredProcedure1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Start12"
    via: "next"
    to: "GetOrganizationByName1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "ExecuteStoredProcedure1"
    into: "in"
