flow: "UpdateStatusSupplierOrder"
kind: "process"

entries:
  - id: "Start1"
    name: "Order"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Confirmation"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Delivery"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Shipped"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "UpdateStatusSupplierOrder-Confirmation"
  - id: "Call2"
    type: "call"
    ref: "UpdateStatusSupplierOrder-Order"
  - id: "Call3"
    type: "call"
    ref: "UpdateStatusSupplierOrder-Shipped"
  - id: "End1"
    type: "end"
  - id: "End2"
    type: "end"
  - id: "End3"
    type: "end"
  - id: "End4"
    type: "end"
  - id: "End5"
    type: "end"
  - id: "PrepareOrderSubStatus1"
    type: "pipelet"
    ref: "PrepareOrderSubStatus"
    config:
      StateGroup: "OrderShippingStatus"
      StatusType: "Status2"
  - id: "PrepareOrderSubStatus2"
    type: "pipelet"
    ref: "PrepareOrderSubStatus"
    config:
      StateGroup: "OrderDeliveryStatus"
      StatusType: "Status2"
  - id: "PrepareOrderSubStatus3"
    type: "pipelet"
    ref: "PrepareOrderSubStatus"
    config:
      StateGroup: "OrderConfirmationStatus"
      StatusType: "Status2"
  - id: "PrepareOrderSubStatus4"
    type: "pipelet"
    ref: "PrepareOrderSubStatus"
    config:
      StateGroup: "OrderStatus"
  - id: "UpdateOrderStatus1"
    type: "pipelet"
    ref: "UpdateOrderStatus"
    bindings:
      InputStateGroup: "InStateGroup"
      InputStateName: "InStateName"
  - id: "UpdateOrderStatus2"
    type: "pipelet"
    ref: "UpdateOrderStatus"
    bindings:
      InputStateGroup: "InStateGroup"
      InputStateName: "InStateName"
  - id: "UpdateOrderStatus3"
    type: "pipelet"
    ref: "UpdateOrderStatus"
    bindings:
      InputStateGroup: "InStateGroup"
      InputStateName: "InStateName"
  - id: "UpdateOrderStatus4"
    type: "pipelet"
    ref: "UpdateOrderStatus"
    bindings:
      InputStateGroup: "InStateGroup"
      InputStateName: "InStateName"

links:
  - from: "Start5"
    via: "next"
    to: "PrepareOrderSubStatus1"
    into: "in"
  - from: "PrepareOrderSubStatus1"
    via: "next"
    to: "UpdateOrderStatus4"
    into: "in"
  - from: "UpdateOrderStatus4"
    via: "next"
    to: "End4"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "PrepareOrderSubStatus2"
    into: "in"
  - from: "PrepareOrderSubStatus2"
    via: "next"
    to: "UpdateOrderStatus3"
    into: "in"
  - from: "UpdateOrderStatus3"
    via: "next"
    to: "End3"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "PrepareOrderSubStatus3"
    into: "in"
  - from: "PrepareOrderSubStatus3"
    via: "next"
    to: "UpdateOrderStatus2"
    into: "in"
  - from: "UpdateOrderStatus2"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "PrepareOrderSubStatus4"
    into: "in"
  - from: "UpdateOrderStatus1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "PrepareOrderSubStatus4"
    via: "next"
    to: "UpdateOrderStatus1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "End5"
    into: "in"
