flow: "UserASCIIImport"
kind: "process"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      - key: "StoreName"
        type: "java.lang.String"
        required: false
      - key: "Interactor"
        type: "com.intershop.beehive.core.capi.impex.ImpexInteractor"
        required: false
  - id: "Start2"
    name: "Error"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "ASCIIConvert1"
    type: "pipelet"
    ref: "ASCIIConvert"
    config:
      FieldDelimiter: ";"
      FormatLine: 1
      Iterator.Name: "data"
      PipeletID: "ASCIIConvert1"
      SkipLines: 1
      SourceID: "source"
      TargetID: "temp"
      UIDescription: "ASCIIConvert"
  - id: "AccessControl1"
    type: "pipelet"
    ref: "AccessControl"
    config:
      AccessControlPermission: "MANAGE_USERS"
      PerformAccessControl: true
      PerformIPRangeCheck: false
      RequireHTTPS: false
  - id: "CloseFile11"
    type: "pipelet"
    ref: "CloseFile"
    config:
      PipeletID: "CloseXMLFileStatisticsVerify1"
      StreamID: "temp"
      UIDescription: "CloseXMLFile"
  - id: "CloseFile12"
    type: "pipelet"
    ref: "CloseFile"
    config:
      PipeletID: "CloseXMLFileVerifyError1"
      StreamID: "temp"
      UIDescription: "CloseXMLFile"
  - id: "CloseFile13"
    type: "pipelet"
    ref: "CloseFile"
    config:
      PipeletID: "CloseXMLFileStatisticsVerifyError1"
      StreamID: "temp"
      UIDescription: "CloseXMLFile"
  - id: "CloseFile14"
    type: "pipelet"
    ref: "CloseFile"
    config:
      PipeletID: "CloseXMLFileVerify1"
      StreamID: "temp"
      UIDescription: "CloseXMLFile"
  - id: "CloseFile2"
    type: "pipelet"
    ref: "CloseFile"
    config:
      PipeletID: "CloseXMLFile1"
      StreamID: "temp"
      UIDescription: "CloseXMLFile"
  - id: "CloseFile3"
    type: "pipelet"
    ref: "CloseFile"
    config:
      PipeletID: "CloseASCIIFile1"
      StreamID: "source"
      UIDescription: "CloseASCIIFile"
  - id: "CloseFile4"
    type: "pipelet"
    ref: "CloseFile"
    config:
      PipeletID: "CloseXMLFile2"
      StreamID: "temp"
      UIDescription: "CloseXMLFile"
  - id: "CloseFile5"
    type: "pipelet"
    ref: "CloseFile"
    config:
      PipeletID: "CloseTempXMLFile1"
      StreamID: "temp"
      UIDescription: "CloseXMLFile"
  - id: "CloseFile6"
    type: "pipelet"
    ref: "CloseFile"
    config:
      PipeletID: "CloseXMLFileASCIIError1"
      StreamID: "temp"
      UIDescription: "CloseXMLFile"
  - id: "CloseFile7"
    type: "pipelet"
    ref: "CloseFile"
    config:
      PipeletID: "CloseXMLFileASCIIError2"
      StreamID: "source"
      UIDescription: "CloseASCIIFile"
  - id: "CloseFile8"
    type: "pipelet"
    ref: "CloseFile"
    config:
      PipeletID: "CloseXMLFileStatisticError1"
      StreamID: "temp"
      UIDescription: "CloseXMLFile"
  - id: "CloseFile9"
    type: "pipelet"
    ref: "CloseFile"
    config:
      PipeletID: "CloseXMLFileParseBuyerError1"
      StreamID: "temp"
      UIDescription: "CloseXMLFile"
  - id: "CloseLoggers1"
    type: "pipelet"
    ref: "CloseLoggers"
    config:
      PipeletID: "CloseLoggers1"
      UIDescription: "CloseLoggers"
  - id: "CloseLoggers2"
    type: "pipelet"
    ref: "CloseLoggers"
    config:
      PipeletID: "CloseLoggers2"
      UIDescription: "Close Loggers"
  - id: "CollectXMLStatistics1"
    type: "pipelet"
    ref: "CollectXMLStatistics"
    config:
      PipeletID: "CollectXMLStatistics1"
      SourceID: "temp"
      StatisticsID: "statistics"
      UIDescription: "CollectXMLStatistics"
  - id: "CollectXMLStatistics2"
    type: "pipelet"
    ref: "CollectXMLStatistics"
    config:
      PipeletID: "CollectXMLStatisticsVerify1"
      SourceID: "temp"
      StatisticsID: "statisticsVerify"
      UIDescription: "CollectXMLStatistics"
  - id: "CreateFileLogger1"
    type: "pipelet"
    ref: "CreateFileLogger"
    config:
      BufferSize: 1024
      Facility: "default"
      FlushTime: 0
      Level: "ERROR | WARN"
      PipeletID: "CreateFileLogger1"
      RolloverSize: 102400
      UIDescription: "CreateFileLogger"
  - id: "CreateImpexUnitFileStructure1"
    type: "pipelet"
    ref: "CreateImpexUnitFileStructure"
  - id: "Decision1"
    type: "decision"
    condition: "runVerification"
  - id: "DetermineConfiguration1"
    type: "pipelet"
    ref: "DetermineConfiguration"
    config:
      CartridgeName: "core"
      Controller.Class: "com.intershop.beehive.core.capi.impex.Controller"
      File: "UserASCIIImport.properties"
      PerformAccessControl: true
      PipeletID: "DetermineConfiguration1"
      UIDescription: "DetermineConfiguration"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "End5"
    type: "end"
    strict: false
  - id: "End6"
    type: "end"
    strict: false
  - id: "End7"
    type: "end"
    strict: false
  - id: "Join1"
    type: "join"
  - id: "Join10"
    type: "join"
  - id: "Join13"
    type: "join"
  - id: "Join14"
    type: "join"
  - id: "Join19"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join24"
    type: "join"
  - id: "Join25"
    type: "join"
  - id: "Join27"
    type: "join"
  - id: "Join28"
    type: "join"
  - id: "Join29"
    type: "join"
  - id: "Join31"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "LockImport1"
    type: "pipelet"
    ref: "LockImport"
    config:
      PipeletID: "LockImport1"
      Timeout: 60
      UIDescription: "LockImport"
  - id: "OpenFile2"
    type: "pipelet"
    ref: "OpenFile"
    config:
      FileID: "sourcefile"
      PipeletID: "OpenASCIIFile1"
      StreamID: "source"
      Type: "SOURCE"
      UIDescription: "OpenASCIIFile"
  - id: "OpenFile3"
    type: "pipelet"
    ref: "OpenFile"
    config:
      FileID: "tempfile"
      PipeletID: "OpenXMLFile1"
      StreamID: "temp"
      Type: "TEMP_OUT"
      UIDescription: "OpenXMLFile"
  - id: "OpenFile4"
    type: "pipelet"
    ref: "OpenFile"
    config:
      FileID: "tempfile"
      PipeletID: "OpenXMLFile2"
      StreamID: "temp"
      Type: "TEMP_IN"
      UIDescription: "OpenXMLFile"
  - id: "OpenFile5"
    type: "pipelet"
    ref: "OpenFile"
    config:
      FileID: "tempfile"
      PipeletID: "OpenXMLFile3"
      StreamID: "temp"
      Type: "TEMP_IN"
      UIDescription: "OpenXMLFile"
  - id: "OpenFile6"
    type: "pipelet"
    ref: "OpenFile"
    config:
      FileID: "tempfile"
      PipeletID: "OpenXMLFileVerify1"
      StreamID: "temp"
      Type: "TEMP_IN"
      UIDescription: "OpenXMLFile"
  - id: "OpenFile7"
    type: "pipelet"
    ref: "OpenFile"
    config:
      FileID: "tempfile"
      PipeletID: "OpenXMLFileStatisticsVerify1"
      StreamID: "temp"
      Type: "TEMP_IN"
      UIDescription: "OpenXMLFile"
  - id: "RefreshCache1"
    type: "pipelet"
    ref: "RefreshCache"
    config:
      PersistentClassName_0: "com.intershop.beehive.core.internal.profile.BasicCredentialsPO"
      PersistentClassName_1: "com.intershop.beehive.core.internal.profile.BasicProfilePO"
      PersistentClassName_2: "com.intershop.beehive.core.internal.profile.BasicAddressPO"
      PersistentClassName_3: "com.intershop.beehive.core.internal.user.UserGroupUserAssignmentPO"
  - id: "SQLLDRFinish2"
    type: "pipelet"
    ref: "SQLLDRFinish"
    config:
      DrainID: "drain"
      DumpFiles.Delete: "tue"
      LogFiles.Delete: "flase"
      PipeletID: "SQLLDRFinish1"
      ScriptFiles.Delete: true
      UIDescription: "SQLLDRFinish"
  - id: "SQLLDRImport2"
    type: "pipelet"
    ref: "SQLLDRImport"
    config:
      Bulker.Class: "com.intershop.beehive.core.internal.user.impex.ElementBulkerSQLLDRUser"
      Bulker.DirectMode: false
      ContentHandler.Class: "com.intershop.beehive.core.internal.user.impex.XMLParseContentHandlerUser"
      DefaultImportMode: "OMIT"
      DrainID: "drain"
      IgnoreXMLVersion: false
      ImportManager.Class: "com.intershop.beehive.core.internal.impex.sqlloader.SQLLDRImportMgr"
      MaximumErrorsAllowed: 0
      PipeletID: "SQLLDRImport1"
      SessionLocalized: true
      SourceID: "temp"
      StatisticsID: "statistics"
      UIDescription: "SQLLDRImport"
      Validator.Class: "com.intershop.beehive.core.internal.user.impex.ElementValidatorUser"
  - id: "SQLLDRPrepare2"
    type: "pipelet"
    ref: "SQLLDRPrepare"
    config:
      DrainID: "drain"
      PipeletID: "SQLLDRPrepare1"
      UIDescription: "SQLLDRPrepare"
  - id: "SQLLDRRun2"
    type: "pipelet"
    ref: "SQLLDRRun"
    config:
      DataSourceSpec: "beehive:comp/env/jdbc/core/defaultDB"
      DrainID: "drain"
      PipeletID: "SQLLDRRun1"
      UIDescription: "SQLLDRRun"
  - id: "Text1"
    type: "text"
  - id: "UnlockImport1"
    type: "pipelet"
    ref: "UnlockImport"
    config:
      PipeletID: "UnlockImport1"
      UIDescription: "UnlockImport"
  - id: "XMLVerify1"
    type: "pipelet"
    ref: "XMLVerify"
    config:
      PipeletID: "XMLVerify1"
      SourceID: "temp"
      StatisticsID: "statisticsVerify"
      UIDescription: "XMLVerify"

links:
  - from: "ASCIIConvert1"
    via: "next"
    to: "CloseFile2"
    into: "in"
  - from: "CloseFile7"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "CloseFile8"
    via: "next"
    to: "Join6"
    into: "in2"
  - from: "CloseFile9"
    via: "next"
    to: "Join10"
    into: "in2"
  - from: "CloseLoggers1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "CloseLoggers1"
    via: "error"
    to: "End6"
    into: "in"
  - from: "CloseLoggers2"
    via: "error"
    to: "Join19"
    into: "in3"
  - from: "CloseLoggers2"
    via: "next"
    to: "Join19"
    into: "in1"
  - from: "CollectXMLStatistics1"
    via: "next"
    to: "CloseFile4"
    into: "in"
  - from: "CollectXMLStatistics1"
    via: "error"
    to: "CloseFile8"
    into: "in"
  - from: "CollectXMLStatistics2"
    via: "next"
    to: "CloseFile11"
    into: "in"
  - from: "ASCIIConvert1"
    via: "error"
    to: "CloseFile6"
    into: "in"
  - from: "CollectXMLStatistics2"
    via: "error"
    to: "CloseFile13"
    into: "in"
  - from: "CreateFileLogger1"
    via: "next"
    to: "LockImport1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join31"
    into: "in3"
  - from: "Decision1"
    via: "yes"
    to: "OpenFile7"
    into: "in"
  - from: "DetermineConfiguration1"
    via: "next"
    to: "CreateFileLogger1"
    into: "in"
  - from: "DetermineConfiguration1"
    via: "error"
    to: "End3"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join13"
    via: "next"
    to: "Join14"
    into: "in3"
  - from: "Join19"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Join24"
    via: "next"
    to: "UnlockImport1"
    into: "in"
  - from: "Join25"
    via: "next"
    to: "Join29"
    into: "in1"
  - from: "Join28"
    via: "next"
    to: "Join27"
    into: "in1"
  - from: "Join31"
    via: "next"
    to: "OpenFile4"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Join8"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "Join9"
    via: "next"
    to: "Join10"
    into: "in1"
  - from: "LockImport1"
    via: "error"
    to: "End5"
    into: "in"
  - from: "LockImport1"
    via: "next"
    to: "OpenFile2"
    into: "in"
  - from: "OpenFile2"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "OpenFile2"
    via: "next"
    to: "OpenFile3"
    into: "in"
  - from: "CloseFile11"
    via: "next"
    to: "OpenFile6"
    into: "in"
  - from: "OpenFile3"
    via: "next"
    to: "ASCIIConvert1"
    into: "in"
  - from: "OpenFile3"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "OpenFile4"
    via: "next"
    to: "CollectXMLStatistics1"
    into: "in"
  - from: "OpenFile4"
    via: "error"
    to: "Join5"
    into: "in2"
  - from: "OpenFile5"
    via: "error"
    to: "Join9"
    into: "in2"
  - from: "OpenFile5"
    via: "next"
    to: "SQLLDRImport2"
    into: "in"
  - from: "OpenFile6"
    via: "error"
    to: "Join28"
    into: "in2"
  - from: "OpenFile6"
    via: "next"
    to: "XMLVerify1"
    into: "in"
  - from: "OpenFile7"
    via: "next"
    to: "CollectXMLStatistics2"
    into: "in"
  - from: "OpenFile7"
    via: "error"
    to: "Join25"
    into: "in2"
  - from: "CloseFile12"
    via: "next"
    to: "Join27"
    into: "in2"
  - from: "SQLLDRFinish2"
    via: "error"
    to: "Join13"
    into: "in2"
  - from: "SQLLDRFinish2"
    via: "next"
    to: "Join14"
    into: "in1"
  - from: "SQLLDRPrepare2"
    via: "error"
    to: "Join8"
    into: "in2"
  - from: "SQLLDRPrepare2"
    via: "next"
    to: "OpenFile5"
    into: "in"
  - from: "SQLLDRRun2"
    via: "error"
    to: "Join13"
    into: "in1"
  - from: "SQLLDRRun2"
    via: "next"
    to: "SQLLDRFinish2"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "AccessControl1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "CloseLoggers2"
    into: "in"
  - from: "UnlockImport1"
    via: "next"
    to: "CloseLoggers1"
    into: "in"
  - from: "UnlockImport1"
    via: "error"
    to: "End7"
    into: "in"
  - from: "CloseFile14"
    via: "next"
    to: "Join31"
    into: "in1"
  - from: "SQLLDRImport2"
    via: "next"
    to: "CloseFile5"
    into: "in"
  - from: "SQLLDRImport2"
    via: "error"
    to: "CloseFile9"
    into: "in"
  - from: "XMLVerify1"
    via: "error"
    to: "CloseFile12"
    into: "in"
  - from: "XMLVerify1"
    via: "next"
    to: "CloseFile14"
    into: "in"
  - from: "CloseFile6"
    via: "next"
    to: "CloseFile7"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Join25"
    into: "in1"
  - from: "Join29"
    via: "next"
    to: "Join28"
    into: "in1"
  - from: "Join27"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Join6"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "CloseFile13"
    via: "next"
    to: "Join29"
    into: "in2"
  - from: "CloseFile2"
    via: "next"
    to: "CloseFile3"
    into: "in"
  - from: "CreateImpexUnitFileStructure1"
    via: "error"
    to: "End4"
    into: "in"
  - from: "AccessControl1"
    via: "next"
    to: "CreateImpexUnitFileStructure1"
    into: "in"
  - from: "CreateImpexUnitFileStructure1"
    via: "next"
    to: "DetermineConfiguration1"
    into: "in"
  - from: "CloseFile5"
    via: "next"
    to: "SQLLDRRun2"
    into: "in"
  - from: "RefreshCache1"
    via: "next"
    to: "Join24"
    into: "in1"
  - from: "Join14"
    via: "next"
    to: "RefreshCache1"
    into: "in"
  - from: "Join10"
    via: "next"
    to: "Join24"
    into: "in3"
  - from: "CloseFile3"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "CloseFile4"
    via: "next"
    to: "SQLLDRPrepare2"
    into: "in"
