flow: "UserLDAPImport"
kind: "process"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      - key: "StoreName"
        type: "java.lang.String"
        required: false
      - key: "Interactor"
        type: "com.intershop.beehive.core.capi.impex.ImpexInteractor"
        required: false
  - id: "Start2"
    name: "Error"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AccessControl1"
    type: "pipelet"
    ref: "AccessControl"
    config:
      AccessControlPermission: "MANAGE_USERS"
      PerformAccessControl: true
      PerformIPRangeCheck: false
      RequireHTTPS: false
  - id: "CloseLoggers1"
    type: "pipelet"
    ref: "CloseLoggers"
    config:
      PipeletID: "CloseLoggersError"
      UIDescription: "Close Loggers"
  - id: "CloseLoggers2"
    type: "pipelet"
    ref: "CloseLoggers"
    config:
      PipeletID: "CloseLoggers"
      UIDescription: "CloseLoggers"
  - id: "CreateFileLogger1"
    type: "pipelet"
    ref: "CreateFileLogger"
    config:
      BufferSize: 1024
      Facility: "default"
      FlushTime: 0
      Level: "ERROR | WARN"
      PipeletID: "CreateFileLogger"
      RolloverSize: 102400
      UIDescription: "CreateFileLogger"
  - id: "CreateImpexUnitFileStructure1"
    type: "pipelet"
    ref: "CreateImpexUnitFileStructure"
  - id: "DetermineConfiguration1"
    type: "pipelet"
    ref: "DetermineConfiguration"
    config:
      CartridgeName: "core"
      Controller.Class: "com.intershop.beehive.core.capi.impex.Controller"
      File: "UserLDAPImport.properties"
      PerformAccessControl: true
      PipeletID: "DetermineConfiguration"
      PropertyMapping: "CreateFileLogger.File=FileLogger.File;CreateFileLogger.RolloverSize=FileLogger.RolloverSize;CreateFileLogger.Truncate=FileLogger.Truncate;CreateFileLogger.Level=FileLogger.Level;DetermineConfiguration.SessionLocale=SessionLocale;DetermineConfiguration.File=PropertyFileName;SQLLDRFinish.DumpFiles.Delete=LoaderCleanup.DumpFiles.Delete;SQLLDRFinish.LogFiles.Delete=LoaderCleanup.LogFiles.Delete;SQLLDRFinish.ScriptFiles.Delete=LoaderCleanup.LogFiles.Delete;SQLLDRFinish.ControlFiles.Delete=LoaderCleanup.LogFiles.Delete"
      UIDescription: "DetermineConfiguration"
  - id: "End2"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "End5"
    type: "end"
    strict: false
  - id: "End6"
    type: "end"
    strict: false
  - id: "End7"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "Join1"
    type: "join"
  - id: "Join10"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "UserLDAPImport-Error"
  - id: "LDAPRetrieve1"
    type: "pipelet"
    ref: "LDAPRetrieve"
    config:
      Bulker.Class: "com.intershop.beehive.core.internal.user.impex.ElementBulkerSQLLDRUser"
      Bulker.DirectMode: false
      ContentHandler.Class: "com.intershop.beehive.core.internal.user.impex.LDAPRetrieveContentHandlerUser"
      DefaultImportMode: "OMIT"
      DrainID: "drain"
      PageSize: 100
      PipeletID: "LDAPRetrieve"
      SearchFilter: "(objectclass=*)"
      UIDescription: "LDAPRetrieve"
      Validator.Class: "com.intershop.beehive.core.internal.user.impex.ElementValidatorUser"
  - id: "LockImport1"
    type: "pipelet"
    ref: "LockImport"
    config:
      PipeletID: "LockImport"
      Timeout: 60
      UIDescription: "LockImport"
  - id: "RefreshCache1"
    type: "pipelet"
    ref: "RefreshCache"
    config:
      PersistentClassName_0: "com.intershop.beehive.core.internal.profile.BasicCredentialsPO"
      PersistentClassName_1: "com.intershop.beehive.core.internal.profile.BasicProfilePO"
      PersistentClassName_2: "com.intershop.beehive.core.internal.profile.BasicAddressPO"
      PersistentClassName_3: "com.intershop.beehive.core.internal.user.UserGroupUserAssignmentPO"
  - id: "SQLLDRFinish1"
    type: "pipelet"
    ref: "SQLLDRFinish"
    config:
      DrainID: "drain"
      DumpFiles.Delete: false
      LogFiles.Delete: false
      PipeletID: "SQLLDRFinish"
      ScriptFiles.Delete: false
      UIDescription: "SQLLDRFinish"
  - id: "SQLLDRPrepare1"
    type: "pipelet"
    ref: "SQLLDRPrepare"
    config:
      DrainID: "drain"
      PipeletID: "SQLLDRPrepare"
      UIDescription: "SQLLDRPrepare"
  - id: "SQLLDRRun1"
    type: "pipelet"
    ref: "SQLLDRRun"
    config:
      DataSourceSpec: "beehive:comp/env/jdbc/core/defaultDB"
      DrainID: "drain"
      PipeletID: "SQLLDRRun"
      UIDescription: "SQLLDRRun"
  - id: "UnlockImport1"
    type: "pipelet"
    ref: "UnlockImport"
    config:
      PipeletID: "UnlockImport"
      UIDescription: "UnlockImport"

links:
  - from: "AccessControl1"
    via: "error"
    to: "EndNode1"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "UnlockImport1"
    into: "in"
  - from: "Join9"
    via: "next"
    to: "Join10"
    into: "in3"
  - from: "LDAPRetrieve1"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "LockImport1"
    via: "next"
    to: "SQLLDRPrepare1"
    into: "in"
  - from: "SQLLDRFinish1"
    via: "next"
    to: "Join10"
    into: "in1"
  - from: "SQLLDRFinish1"
    via: "error"
    to: "Join9"
    into: "in2"
  - from: "SQLLDRPrepare1"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "SQLLDRPrepare1"
    via: "next"
    to: "LDAPRetrieve1"
    into: "in"
  - from: "SQLLDRRun1"
    via: "error"
    to: "Join9"
    into: "in1"
  - from: "SQLLDRRun1"
    via: "next"
    to: "SQLLDRFinish1"
    into: "in"
  - from: "CloseLoggers1"
    via: "error"
    to: "Join5"
    into: "in3"
  - from: "Start1"
    via: "next"
    to: "AccessControl1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "CloseLoggers1"
    into: "in"
  - from: "CreateImpexUnitFileStructure1"
    via: "error"
    to: "End4"
    into: "in"
  - from: "AccessControl1"
    via: "next"
    to: "CreateImpexUnitFileStructure1"
    into: "in"
  - from: "CreateImpexUnitFileStructure1"
    via: "next"
    to: "DetermineConfiguration1"
    into: "in"
  - from: "LDAPRetrieve1"
    via: "next"
    to: "SQLLDRRun1"
    into: "in"
  - from: "Join10"
    via: "next"
    to: "RefreshCache1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Join6"
    into: "in3"
  - from: "RefreshCache1"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "LockImport1"
    via: "error"
    to: "Jump1"
    into: "in"
  - from: "CloseLoggers1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "UnlockImport1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "CloseLoggers2"
    into: "in"
  - from: "UnlockImport1"
    via: "error"
    to: "Join2"
    into: "in3"
  - from: "CloseLoggers2"
    via: "error"
    to: "End2"
    into: "in"
  - from: "CloseLoggers2"
    via: "next"
    to: "End7"
    into: "in"
  - from: "CreateFileLogger1"
    via: "next"
    to: "LockImport1"
    into: "in"
  - from: "DetermineConfiguration1"
    via: "next"
    to: "CreateFileLogger1"
    into: "in"
  - from: "DetermineConfiguration1"
    via: "error"
    to: "End5"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "End6"
    into: "in"
