flow: "VanityDomainMapping"
kind: "process"

entries:
  - id: "Start1"
    name: "ResolveOld"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "CheckLinkDate"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Resolve"
    mode: "public"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "VanityDomainMapping-CheckLinkDate"
  - id: "Call2"
    type: "call"
    ref: "VanityDomainMapping-CheckLinkDate"
  - id: "Decision1"
    type: "decision"
    condition: "CurrentDate:Time"
  - id: "Decision2"
    type: "decision"
    condition: "ShortLink:EndDate"
  - id: "Decision3"
    type: "decision"
    condition: "CurrentDate:Time"
  - id: "Decision4"
    type: "decision"
    condition: "ShortLink:StartDate"
  - id: "Decision5"
    type: "decision"
    condition: "ShortLink:Enabled"
  - id: "DetermineRequestString1"
    type: "pipelet"
    ref: "DetermineRequestString"
  - id: "DetermineRequestString2"
    type: "pipelet"
    ref: "DetermineRequestString"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "GetCurrentDate1"
    type: "pipelet"
    ref: "GetCurrentDate"
  - id: "GetDefaultShortLinkForDomain1"
    type: "pipelet"
    ref: "GetDefaultShortLinkForDomain"
    bindings:
      DefaultShortLink: "ShortLink"
      Domain: "ShortLink:Domain"
  - id: "GetShortLinkByURL1"
    type: "pipelet"
    ref: "GetShortLinkByURL"
    bindings:
      ShortURL: "RequestString"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ShortLink:TargetURL"
      OutValue_1: "TargetURL"
  - id: "ResolveShortLink1"
    type: "pipelet"
    ref: "ResolveShortLink"
    bindings:
      TargetLinkObject: "ShortLink"
      TargetLink: "TargetURL"
  - id: "ResolveShortLink2"
    type: "pipelet"
    ref: "ResolveShortLink"
    bindings:
      ShortLink: "RequestString"
      TargetLink: "TargetURL"
  - id: "Text1"
    type: "text"
  - id: "Text2"
    type: "text"
  - id: "Text3"
    type: "text"

links:
  - from: "Start1"
    via: "next"
    to: "DetermineRequestString1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "End2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Decision5"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "Join4"
    into: "in1"
  - from: "Join4"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "GetCurrentDate1"
    via: "next"
    to: "Decision4"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join3"
    into: "in3"
  - from: "Decision2"
    via: "yes"
    to: "Decision1"
    into: "in"
  - from: "ResolveShortLink2"
    via: "next"
    to: "GetShortLinkByURL1"
    into: "in"
  - from: "GetShortLinkByURL1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "ResolveShortLink1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "DetermineRequestString1"
    via: "next"
    to: "ResolveShortLink2"
    into: "in"
  - from: "ResolveShortLink1"
    via: "next"
    to: "JoinNode4"
    into: "in2"
  - from: "Call1"
    via: "next"
    to: "Join6"
    into: "in2"
  - from: "GetDefaultShortLinkForDomain1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "Join5"
    into: "in2"
  - from: "GetShortLinkByURL1"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Decision5"
    via: "yes"
    to: "GetCurrentDate1"
    into: "in"
  - from: "Decision5"
    via: "no"
    to: "End4"
    into: "in"
  - from: "GetDefaultShortLinkForDomain1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "DetermineRequestString2"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "Join1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DetermineRequestString2"
    into: "in"
  - from: "Call2"
    via: "ERROR"
    to: "Join1"
    into: "in3"
  - from: "Join5"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "DetermineRequestString1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "DetermineRequestString2"
    via: "next"
    to: "ResolveShortLink1"
    into: "in"
  - from: "Call1"
    via: "ERROR"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "GetDefaultShortLinkForDomain1"
    into: "in"
  - from: "ResolveShortLink2"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "Join6"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "Join4"
    into: "in3"
  - from: "Decision3"
    via: "no"
    to: "End3"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Join3"
    into: "in1"
  - from: "Decision4"
    via: "yes"
    to: "Decision3"
    into: "in"
