flow: "ViewPromotionPreferenceBudgetSource"
kind: "view"

entries:
  - id: "Start1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Add"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "List"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Update"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "Create"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "DeleteSingle"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddMultipleEntriesToMap1"
    type: "pipelet"
    ref: "AddMultipleEntriesToMap"
    config:
      Mode: "OverwriteValue"
    bindings:
      InMap: "null"
      Key1: "BudgetSourceForm:BSID"
      Key2: "BudgetSourceForm:Name"
      Key3: "BudgetSourceForm:Description"
      OutMap: "FormParameterValuesMap"
      Value1: "BudgetSource:ID"
      Value2: "BudgetSource:DisplayName(SelectedLocale)"
      Value3: "BudgetSource:Description(SelectedLocale)"
  - id: "Call411"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call71"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "CallNode1"
    type: "call"
    ref: "ViewPromotionPreferenceBudgetSource-Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "ViewPromotionPreferenceBudgetSource-Prefix"
  - id: "CallNode23"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "CallNode3"
    type: "call"
    ref: "ViewPromotionPreferenceBudgetSource-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessPromotion-GetPromotionDomainByChannel"
    bindings:
      Channel: "CurrentChannel"
  - id: "CallNode5"
    type: "call"
    ref: "ViewPromotionPreferenceBudgetSource-Prefix"
  - id: "CallNode6"
    type: "call"
    ref: "ViewPromotionPreferenceBudgetSource-Prefix"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessPromotion-GetPromotionDomainByChannel"
    bindings:
      Channel: "CurrentChannel"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormResource: "BudgetSource"
      FormName: "BudgetSource"
    bindings:
      Form: "BudgetSourceForm"
  - id: "CreateForm2"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormResource: "BudgetSource"
      FormName: "BudgetSource"
    bindings:
      Form: "BudgetSourceForm"
  - id: "CreateForm3"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormResource: "BudgetSource"
      FormName: "BudgetSource"
    bindings:
      Form: "BudgetSourceForm"
  - id: "CreateForm6"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormResource: "BudgetSource"
      FormName: "BudgetSource"
    bindings:
      Form: "BudgetSourceForm"
  - id: "CreatePromotionBudgetSource1"
    type: "pipelet"
    ref: "CreatePromotionBudgetSource"
    bindings:
      Domain: "PromotionDomain"
      ID: "BudgetSourceForm:BSID:Value"
  - id: "Decision1"
    type: "decision"
    condition: "BudgetSources"
  - id: "Decision3"
    type: "decision"
    condition: "PageLocator"
  - id: "Decision4"
    type: "decision"
    condition: "PageNumber"
  - id: "DetermineLocales2"
    type: "pipelet"
    ref: "DetermineLocales"
    bindings:
      Locales: "AllLocales"
  - id: "DispatchFormAction4"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPromotionPreferenceBudgetSource-Add"
      OutValue_1: "ViewPromotionPreferenceBudgetSource-Paging"
      OutValue_2: "ViewPromotionPreferenceBudgetSource-Delete"
      OutValue_3: "ViewPromotionPreferenceBudgetSource-List"
      OutValue_4: "ViewPromotionPreferenceBudgetSource-Create"
      OutValue_5: "ViewPromotionPreferenceBudgetSource-Update"
      OutValue_6: "ViewPromotionPreferenceBudgetSource-Edit"
      OutValue_7: "ViewPromotionPreferenceBudgetSource-DeleteSingle"
      OutValue_8: "ViewPromotionPreferenceBudgetSource-Edit"
    bindings:
      Key_0: "add"
      SelectionKey: "JumpTarget"
      Key_1: "confirmDelete"
      Key_2: "delete"
      Key_3: "cancelDelete"
      Key_4: "create"
      Key_5: "apply"
      Key_6: "confirmDeleteSingle"
      Key_7: "deleteSingle"
      Key_8: "cancelDeleteSingle"
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "budget/GetBudgetSources"
      ParameterName_01: "Domain"
      Datasource: "default"
      DefaultPageSize: 15
      ParameterName_02: "Locale"
    bindings:
      SearchResult: "BudgetSources"
      ParameterValue_01: "PromotionDomain"
      ParameterValue_02: "SelectedLocale"
  - id: "GetLocale3"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
    bindings:
      Locale: "SelectedLocale"
      LocaleId: "LocaleID"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "BudgetSourceList"
      RestorePageLocatorDictionary: "False"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "BudgetSources"
      PageableID: "PageLocator:PageableID"
  - id: "GetPersistentObjectByUUID2"
    type: "pipelet"
    ref: "GetPersistentObjectByUUID"
    config:
      PersistentObjectPOClass: "com.intershop.component.marketing.internal.rebate.PromotionBudgetSourcePO"
    bindings:
      UUID: "UUID"
      PersistentObject: "BudgetSource"
  - id: "GetPersistentObjectByUUID3"
    type: "pipelet"
    ref: "GetPersistentObjectByUUID"
    config:
      PersistentObjectPOClass: "com.intershop.component.marketing.internal.rebate.PromotionBudgetSourcePO"
    bindings:
      UUID: "BudgetSourceUUID"
      PersistentObject: "BudgetSource"
  - id: "GetPersistentObjectByUUID4"
    type: "pipelet"
    ref: "GetPersistentObjectByUUID"
    config:
      PersistentObjectPOClass: "com.intershop.component.marketing.internal.rebate.PromotionBudgetSourcePO"
    bindings:
      UUID: "BudgetSourceUUID"
      PersistentObject: "BudgetSource"
  - id: "GetPersistentObjectByUUID5"
    type: "pipelet"
    ref: "GetPersistentObjectByUUID"
    config:
      PersistentObjectPOClass: "com.intershop.component.marketing.internal.rebate.PromotionBudgetSourcePO"
    bindings:
      UUID: "BudgetSourceUUID"
      PersistentObject: "BudgetSource"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "InteractionEnd5"
    type: "interaction"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode111"
    type: "jump"
    ref: "ViewPromotionPreferenceBudgetSource-List"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewPromotionPreferenceBudgetSource-Edit"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewPromotionPreferenceBudgetSource-List"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentChannel:AttributeValue(\"BudgetSources\",SelectedLocale):Object"
      OutValue_1: "BudgetSources"
  - id: "Loop1"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "marketing/PromotionBudgetSource"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "marketing/PromotionPreferenceBudgetSource"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "marketing/PromotionBudgetSource"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"
  - id: "PrepareApplicationView5"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "marketing/PromotionBudgetSource"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"
  - id: "RemoveORMObject1"
    type: "pipelet"
    ref: "RemoveORMObject"
    bindings:
      ORMObject: "BudgetSource"
  - id: "RemoveORMObject2"
    type: "pipelet"
    ref: "RemoveORMObject"
    bindings:
      ORMObject: "BudgetSource"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewPromotionPreferenceBudgetSource-List"
      ValueType: "Dictionary Value"
  - id: "SetFormParameterValues1"
    type: "pipelet"
    ref: "SetFormParameterValues"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "BudgetSources"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "BudgetSources"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewPromotionPreferenceBudgetSource_52-Paging"
      DefaultPageLocatorName: "BudgetSourceList"
    bindings:
      Pageable: "BudgetSources"
      HandlerPipeline: "null"
      PageLocatorName: "null"
  - id: "UpdateCustomAttributes1"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "displayName"
      Attribute_1_Type: "String"
      Attribute_2_Name: "description"
      Attribute_2_Type: "String"
    bindings:
      ExtensibleObject: "BudgetSource"
      LocaleInformation: "SelectedLocale"
      Attribute_1_Value: "BudgetSourceForm:Name:Value"
      Attribute_2_Value: "BudgetSourceForm:Description:Value"
  - id: "UpdateCustomAttributes2"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "displayName"
      Attribute_1_Type: "String"
      Attribute_2_Name: "description"
      Attribute_2_Type: "String"
    bindings:
      ExtensibleObject: "BudgetSource"
      LocaleInformation: "SelectedLocale"
      Attribute_1_Value: "BudgetSourceForm:Name:Value"
      Attribute_2_Value: "BudgetSourceForm:Description:Value"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "BudgetSourceForm"
  - id: "ValidateForm5"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "BudgetSourceForm"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"
      Locale: "null"
      Pattern: "null"

links:
  - from: "CallNode2"
    via: "next"
    to: "CreateForm2"
    into: "in"
  - from: "RemoveORMObject1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "RemoveORMObject1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "JoinNode9"
    into: "in3"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "DispatchFormAction4"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "GetPageable1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "GetPageLocator1"
    via: "error"
    to: "JoinNode8"
    into: "in2"
  - from: "GetPageable1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Decision4"
    into: "in"
  - from: "JoinNode14"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "error"
    to: "JoinNode14"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "DispatchFormAction4"
    into: "in"
  - from: "GetLocale3"
    via: "next"
    to: "DetermineLocales2"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "CallNode23"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "Call411"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode23"
    via: "next"
    to: "JumpNode111"
    into: "in"
  - from: "GetPersistentObjectByUUID2"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "JoinNode14"
    into: "in2"
  - from: "SetFormParameterValues1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "PrepareApplicationView5"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CreateForm3"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CreateForm6"
    into: "in"
  - from: "PrepareApplicationView5"
    via: "next"
    to: "InteractionEnd5"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Call71"
    into: "in"
  - from: "Call71"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "StartNode5"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "SetPage2"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "ValidateForm1"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "CreateForm2"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "DetermineLocales2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "GetPersistentObjectByUUID5"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "GetPersistentObjectByUUID2"
    via: "next"
    to: "RemoveORMObject1"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "UpdateCustomAttributes2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CreatePromotionBudgetSource1"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "SetPageLocator1"
    via: "next"
    to: "JoinNode14"
    into: "in1"
  - from: "Join4"
    via: "next"
    to: "Join6"
    into: "in3"
  - from: "ValidateForm5"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join5"
    into: "in3"
  - from: "SetPage1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Decision4"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "GetLocale3"
    into: "in"
  - from: "UpdateCustomAttributes1"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Join4"
    into: "in3"
  - from: "CreateForm1"
    via: "next"
    to: "GetPersistentObjectByUUID5"
    into: "in"
  - from: "CreateForm6"
    via: "next"
    to: "ValidateForm5"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "Decision3"
    into: "in"
  - from: "Call411"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "GetPersistentObjectByUUID5"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "CreatePromotionBudgetSource1"
    via: "next"
    to: "UpdateCustomAttributes2"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "ValidateForm1"
    via: "next"
    to: "UpdateCustomAttributes1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "DispatchFormAction4"
    via: "error"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "GetPersistentObjectByUUID4"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "CreateForm3"
    via: "next"
    to: "GetPersistentObjectByUUID3"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "GetPersistentObjectByUUID4"
    into: "in"
  - from: "GetPersistentObjectByUUID3"
    via: "next"
    to: "AddMultipleEntriesToMap1"
    into: "in"
  - from: "AddMultipleEntriesToMap1"
    via: "next"
    to: "SetFormParameterValues1"
    into: "in"
  - from: "GetPersistentObjectByUUID4"
    via: "next"
    to: "RemoveORMObject2"
    into: "in"
  - from: "RemoveORMObject2"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "RemoveORMObject2"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage1"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "GetPersistentObjectByUUID3"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode5"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "ValidateForm5"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "CreatePromotionBudgetSource1"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetPersistentObjectByUUID2"
    into: "in"
