flow: "ViewChannelUserAccessRoles"
kind: "view"

entries:
  - id: "Start1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Show"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "AddRoles"
    mode: "private"
    strict: false
    inputs:
      - key: "RoleID_Add_Iterator<java.util.Iterator>"
        type: "java.util.Iterator"
        required: false
      - key: "RoleID_Remove_Iterator<java.util.Iterator>"
        type: "java.util.Iterator"
        required: false
  - id: "Start5"
    name: "RemoveRoles"
    mode: "private"
    strict: false
    inputs:
      - key: "RoleID_Add_Iterator<java.util.Iterator>"
        type: "java.util.Iterator"
        required: false
      - key: "RoleID_Remove_Iterator<java.util.Iterator>"
        type: "java.util.Iterator"
        required: false
  - id: "Start6"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessUserAccessRoles-Show"
  - id: "Call2"
    type: "call"
    ref: "ProcessUserAccessRoles-RemoveRole"
  - id: "Call3"
    type: "call"
    ref: "ProcessUserAccessRoles-UpdatePrefix"
  - id: "Call4"
    type: "call"
    ref: "ProcessUserAccessRoles-AddRole"
  - id: "Call5"
    type: "call"
    ref: "ViewChannelUserAccessRoles-RemoveRoles"
  - id: "Call6"
    type: "call"
    ref: "ViewChannelUserAccessRoles-AddRoles"
  - id: "CallNode2"
    type: "call"
    ref: "ViewChannelUserAccessRoles-Prefix"
  - id: "CallNode3"
    type: "call"
    ref: "ViewChannelUserAccessRoles-Prefix"
  - id: "CallNode6"
    type: "call"
  - id: "CombineIterators1"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Subtract Iterators"
    bindings:
      Iterator1: "RoleID_Remove_Iterator"
      Iterator: "Remove_Iterator"
      Iterator2: "RoleID_Add_Iterator"
  - id: "CombineIterators2"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Subtract Iterators"
    bindings:
      Iterator1: "RoleID_Add_Iterator"
      Iterator: "Add_Iterator"
      Iterator2: "RoleID_Remove_Iterator"
  - id: "ConcatenateStrings2"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "\"ProcessOrganization_\""
      String1: "CurrentChannel:TypeCode"
      String2: "\"-Get\""
      Concatenated: "GetOrganization"
  - id: "CreateIteratorForPrefix3"
    type: "pipelet"
    ref: "CreateIteratorForPrefix"
    config:
      Prefix: "RemoveRole"
    bindings:
      PrefixIterator: "RoleID_Remove_Iterator"
  - id: "CreateIteratorForPrefix4"
    type: "pipelet"
    ref: "CreateIteratorForPrefix"
    config:
      Prefix: "AddRole"
    bindings:
      PrefixIterator: "RoleID_Add_Iterator"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelUserAccessRoles-Update"
      OutValue_1: "ViewChannelUserAccessRoles-Show"
      OutValue_2: "ViewUserList-List"
    bindings:
      Key_0: "update"
      Key_1: "reset"
      Key_2: "back"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Jump4"
    type: "jump"
    ref: "ViewChannelUserAccessRoles-Show"
  - id: "Jump5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Loop1"
    type: "loop"
  - id: "Loop2"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelUser"
      WorkingTemplate: "user/ChannelUserAccessRoles"

links:
  - from: "Start3"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Start4"
    via: "next"
    to: "CombineIterators2"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "CombineIterators1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "Loop2"
    via: "do"
    to: "Call4"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "CombineIterators2"
    via: "next"
    to: "Loop2"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "CreateIteratorForPrefix3"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "End3"
    into: "in"
  - from: "CreateIteratorForPrefix4"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "ConcatenateStrings2"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "ConcatenateStrings2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "CombineIterators1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CreateIteratorForPrefix3"
    via: "next"
    to: "CreateIteratorForPrefix4"
    into: "in"
  - from: "Loop2"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "Call2"
    into: "in"
