flow: "ViewUserGroup_52"
kind: "view"

entries:
  - id: "Start1"
    name: "New"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start10"
    name: "Back"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "UpdateUserGroup"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "RemovePageletUserGroupAssignments"
    mode: "private"
    strict: true
    inputs:
      - key: "UserGroup"
        type: "com.intershop.beehive.core.capi.user.UserGroup"
        required: true
      - key: "Repository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true

steps:
  - id: "Call2"
    type: "call"
    ref: "ViewUserGroup_52-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ViewUserGroup_52-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ViewUserGroup_52-Prefix"
  - id: "Call5"
    type: "call"
    ref: "ViewUserGroup_52-Prefix"
  - id: "Call6"
    type: "call"
    ref: "ViewUserGroup_52-Prefix"
  - id: "Call7"
    type: "call"
    ref: "ViewUserGroup_52-UpdateUserGroup"
  - id: "Call9"
    type: "call"
    ref: "ViewUserGroup_52-UpdateUserGroup"
  - id: "CallNode1"
    type: "call"
    ref: "ViewUserGroup_52-RemovePageletUserGroupAssignments"
    bindings:
      Repository: "CurrentChannel"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessOrganization_52-GetConsumerOrg"
  - id: "CallNode21"
    type: "call"
    ref: "ProcessOrganization_52-GetConsumerOrg"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessUserGroupConfigurationParameters-ProcessDelete"
    bindings:
      UserGroup: "UserGroup"
      RepositoryDomain: "ChannelRepository:RepositoryDomain"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessPriceListUserGroups_52-RemoveUserGroupFromPriceLists"
    bindings:
      CurrentChannelDomain: "CurrentChannel:Domain"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "Name"
      param.1.required: true
      param.1.rule: ""
      param.2.name: "Description"
      param.2.required: false
      param.2.rule: ""
      param.3.name: "UserGroupID"
      param.3.required: true
      param.3.rule: ""
      webform-id: "UserGroupForm"
    bindings:
      WebForm: "UserGroupForm"
  - id: "CreateWebForm11"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "Name"
      param.1.required: true
      param.1.rule: ""
      param.2.required: false
      param.2.rule: ""
      param.3.name: "Description"
      param.3.required: false
      param.3.rule: ""
      webform-id: "UserGroupForm"
    bindings:
      WebForm: "UserGroupForm"
  - id: "Decision1"
    type: "decision"
    condition: "UserGroup"
  - id: "Decision2"
    type: "decision"
    condition: "UserGroupID"
  - id: "Decision3"
    type: "decision"
    condition: "UserGroup"
  - id: "DetermineLocales2"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DetermineLocales4"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewUserGroup_52-Back"
      OutValue_1: "ViewUserGroup_52-Create"
      OutValue_2: "ViewUserGroup_52-Update"
      OutValue_3: "ViewUserGroup_52-Edit"
      OutValue_4: "ViewUserGroup_52-Delete"
      OutValue_5: "ViewUserGroup_52-Edit"
      OutValue_6: "ViewUserGroup_52-Back"
    bindings:
      Key_0: "cancelCreate"
      Key_1: "create"
      Key_2: "update"
      Key_3: "confirmDelete"
      Key_4: "delete"
      Key_5: "cancelDelete"
      Key_6: "backToList"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "pagelet/SearchPageletUserGroupAssignmentsByUserGroup"
      DefaultPageSize: 0
      ParameterName_01: "Repository"
      ParameterName_02: "UserGroupID"
      ParameterName_03: "pagelet/SearchPageletUserGroupAssignmentsByUserGroup:Repository"
      ParameterName_04: "pagelet/SearchPageletUserGroupAssignmentsByUserGroup:UserGroupID"
    bindings:
      SearchResult: "PageletUserGroupAssignments"
      ErrorCode: "QueryExecutionError"
      ParameterValue_01: "Repository"
      ParameterValue_02: "UserGroup:ID"
      ParameterValue_03: "CurrentChannel"
      ParameterValue_04: "UserGroup:ID"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetLocale3"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetLocale4"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetLocale5"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "UserGroups"
      RestorePageLocatorDictionary: "True"
  - id: "GetPaymentConfigurationsByDomain1"
    type: "pipelet"
    ref: "GetPaymentConfigurationsByDomain"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "UserGroupForm"
    bindings:
      WebForm: "UserGroupForm"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "UserGroupForm"
    bindings:
      WebForm: "UserGroupForm"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InvalidatePageLocatorPageable1"
    type: "pipelet"
    ref: "InvalidatePageLocatorPageable"
    config:
      DefaultPageLocatorName: "UserGroups"
  - id: "InvalidatePageLocatorPageable2"
    type: "pipelet"
    ref: "InvalidatePageLocatorPageable"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewUserGroup_52-Edit"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump3"
    type: "jump"
    ref: "ViewUserGroup_52-Edit"
  - id: "Jump4"
    type: "jump"
    ref: "ViewUserGroup_52-Back"
  - id: "Jump5"
    type: "jump"
  - id: "Jump6"
    type: "jump"
    ref: "ViewUserGroupList_52-ListAll"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ConsumerGroup:UserGroup"
      OutValue_1: "UserGroup"
  - id: "Loop1"
    type: "loop"
  - id: "LoopNode1"
    type: "loop"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "DetermineUserGroup"
    bindings:
      CurrentDomain: "Organization:OrganizationDomain:Domain"
      UserGroupID: "UserGroupID"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "UpdateRole"
    config:
      Type: "Custom Role"
    bindings:
      Description: "UserGroupForm:Description:Value"
      Name: "UserGroupForm:Name:Value"
      Role: "UserGroup"
      LocaleInformation: "Locale"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "CG_"
    bindings:
      Concatenated: "NewUserGroupID"
      String0: "null"
      String1: "UserGroupForm:UserGroupID:Value"
      String2: "null"
      String3: "null"
      String4: "null"
      String5: "null"
      String6: "null"
      String7: "null"
      String8: "null"
      String9: "null"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "CreateConsumerGroup"
    bindings:
      ConsumerGroupID: "NewUserGroupID"
      Domain: "Organization:OrganizationDomain:Domain"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "GetConsumerGroupFromUserGroup"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "RemoveConsumerGroup"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelUserGroup"
      WorkingTemplate: "user/NewUserGroup_52"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelUserGroup"
      WorkingTemplate: "user/UserGroup_52"
  - id: "RemovePageletUserGroupAssignmentByAssignmentUUID1"
    type: "pipelet"
    ref: "RemovePageletUserGroupAssignmentByAssignmentUUID"
    bindings:
      AssignmentUUID: "UserGroupAssignment:UUID"
  - id: "RemovePaymentConfigurationUserGroupAssignment1"
    type: "pipelet"
    ref: "RemovePaymentConfigurationUserGroupAssignment"
  - id: "RemovePromotionCodeGroupUserGroupAssignments1"
    type: "pipelet"
    ref: "RemovePromotionCodeGroupUserGroupAssignments"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: "UserGroupIDIsNotUnique"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "UserGroupForm"
    bindings:
      WebForm: "UserGroupForm"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "UserGroupForm"
    bindings:
      WebForm: "UserGroupForm"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "UserGroupForm"
  - id: "ValidateWebForm2"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "UserGroupForm"

links:
  - from: "Call5"
    via: "next"
    to: "GetLocale5"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "GetLocale3"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "CreateWebForm1"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Pipelet3"
    via: "next"
    to: "InvalidatePageLocatorPageable1"
    into: "in"
  - from: "GetWebForm2"
    via: "error"
    to: "Join8"
    into: "in2"
  - from: "Start1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "UpdateWebForm2"
    via: "next"
    to: "ValidateWebForm2"
    into: "in"
  - from: "InvalidatePageLocatorPageable1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "ValidateWebForm2"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Pipelet6"
    via: "error"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "End1"
    into: "in"
  - from: "GetPageLocator1"
    via: "error"
    to: "Jump6"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "InvalidatePageLocatorPageable2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join2"
    into: "in3"
  - from: "Start6"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "DetermineLocales4"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "Start10"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "GetWebForm2"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "Join4"
    into: "in2"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "ValidateWebForm1"
    via: "next"
    to: "CallNode21"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Join3"
    into: "in3"
  - from: "Start4"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "ValidateWebForm2"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "DetermineLocales2"
    via: "next"
    to: "GetLocale4"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Pipelet7"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "CreateWebForm11"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "ValidateWebForm1"
    via: "error"
    to: "Join6"
    into: "in2"
  - from: "Decision2"
    via: "yes"
    to: "CallNode2"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "Decision3"
    via: "yes"
    to: "Decision2"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "InvalidatePageLocatorPageable2"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Pipelet2"
    via: "next"
    to: "Join3"
    into: "in2"
  - from: "Join6"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Decision2"
    via: "no"
    to: "Join3"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "GetLocale3"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "CreateWebForm11"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "Pipelet7"
    via: "next"
    to: "GetPaymentConfigurationsByDomain1"
    into: "in"
  - from: "GetPaymentConfigurationsByDomain1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "RemovePaymentConfigurationUserGroupAssignment1"
    into: "in"
  - from: "RemovePaymentConfigurationUserGroupAssignment1"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "JoinNode1"
    via: "next"
    to: "DetermineLocales4"
    into: "in"
  - from: "RemovePromotionCodeGroupUserGroupAssignments1"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "DetermineLocales2"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "CallNode21"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "GetLocale4"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "GetLocale2"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "GetLocale5"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "RemovePageletUserGroupAssignmentByAssignmentUUID1"
    into: "in"
  - from: "RemovePageletUserGroupAssignmentByAssignmentUUID1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "CallNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "RemovePromotionCodeGroupUserGroupAssignments1"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
