flow: "ViewABTestGoingLiveTargetGroupUserGroupSelection_52"
kind: "view"

entries:
  - id: "Start1"
    name: "ShowAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start31"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call5"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call7"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode1"
    type: "call"
    ref: "ViewABTestTargetGroupUserGroupSelection_52-Search"
  - id: "CallNode15"
    type: "call"
    ref: "ViewABTestGoingLiveTargetGroup_52-GetConsumerGroups"
  - id: "CallNode2"
    type: "call"
    ref: "ViewABTestGoingLiveTargetGroup_52-PutConsumerGroupsToSession"
    bindings:
      ConsumerGroups: "TargetGroupConsumerGroups"
      ABTestGroupID: "ABTestGroup:UUID"
  - id: "CallNode29"
    type: "call"
    ref: "ProcessOrganization_52-GetConsumerOrg"
  - id: "CallNode3"
    type: "call"
    ref: "ViewABTestGoingLiveTargetGroupUserGroupSelection_52-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ViewABTestGoingLiveTargetGroupUserGroupSelection_52-Prefix"
  - id: "CallNode5"
    type: "call"
    ref: "ViewABTestGoingLiveTargetGroupUserGroupSelection_52-Prefix"
  - id: "CallNode6"
    type: "call"
    ref: "ViewABTestGoingLiveTargetGroup_52-GetUserGroupsFromIDs"
    bindings:
      Domain: "Organization:OrganizationDomain:Domain"
      IDs: "UUIDIterator"
      UserGroups: "NewConsumerGroups"
  - id: "CallNode7"
    type: "call"
    ref: "ViewABTestGoingLiveTargetGroup_52-GetConsumerGroups"
    bindings:
      PageNumber: "null"
  - id: "CheckForEmptyIterator1"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "UUIDIterator"
  - id: "CombineIterators1"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Concatenate Iterators and Remove Duplicates"
    bindings:
      Iterator1: "TargetGroupConsumerGroups"
      Iterator2: "NewConsumerGroups"
      Iterator: "TargetGroupConsumerGroups"
  - id: "Decision1"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision2"
    type: "decision"
    condition: "ABTestGroup"
  - id: "DispatchFormAction11"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewABTestGoingLiveTargetGroup_52-ShowAllConsumerGroups"
      OutValue_1: "ViewABTestGoingLiveTargetGroupUserGroupSelection_52-Create"
      PagingPipeline: "ViewABTestGoingLiveTargetGroupUserGroupSelection_52-Paging"
    bindings:
      Key_0: "cancel"
      Key_1: "assign"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "GetABTestGroupByUUID1"
    type: "pipelet"
    ref: "GetABTestGroupByUUID"
    bindings:
      UUID: "ABTestGroupUUID"
      ABTestGroup: "ABTestGroup"
  - id: "GetPageLocator11"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ABTestGoingLiveTargetGroupUserGroupSelection"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocatorName: "null"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "UserGroups"
      PageableID: "PageLocator:PageableID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump21"
    type: "jump"
    ref: "ViewABTestGoingLiveTargetGroup_52-ShowAllConsumerGroups"
  - id: "Jump22"
    type: "jump"
    ref: "ViewABTestGoingLiveTargetGroupUserGroupSelection_52-Paging"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "CurrentPageNumber"
      OutValue_1: "PageNumber"
  - id: "PrepareApplicationView12"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/ABTestGoingLiveTargetGroupSelectUserGroups_52"
  - id: "PutValuesIntoPipelineDictionary1"
    type: "pipelet"
    ref: "PutValuesIntoPipelineDictionary"
    config:
      UseStaticValues: false
      key.1: "ABTest"
      value.1: "ABTestGroup:Test"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "UserGroups"
  - id: "SetPage3"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "UserGroups"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewABTestTargetGroupUserGroupSelection_52-Paging"
      DefaultPageLocatorName: "ABTestGoingLiveTargetGroupUserGroupSelection"
    bindings:
      HandlerPipeline: "null"
      PageLocatorName: "null"
      Pageable: "UserGroups"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      Locale: "null"
      LocalizedString: "PageNumber"
      Pattern: "null"

links:
  - from: "Start31"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join5"
    into: "in3"
  - from: "CallNode4"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "next"
    to: "CallNode15"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Jump21"
    into: "in"
  - from: "GetABTestGroupByUUID1"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "Start2"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "CheckForEmptyIterator1"
    via: "error"
    to: "KeyMapper2"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "GetPageLocator11"
    into: "in"
  - from: "PutValuesIntoPipelineDictionary1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "PutValuesIntoPipelineDictionary1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join2"
    into: "in3"
  - from: "CallNode15"
    via: "next"
    to: "CallNode29"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CombineIterators1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "SetPage2"
    into: "in"
  - from: "SetPage3"
    via: "next"
    to: "Join5"
    into: "in2"
  - from: "Start5"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "DispatchFormAction11"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "GetPageLocator11"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "CallNode29"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage3"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "PrepareApplicationView12"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "KeyMapper2"
    via: "next"
    to: "Jump22"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "GetABTestGroupByUUID1"
    into: "in"
  - from: "CombineIterators1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "PrepareApplicationView12"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "CallNode5"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction11"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "CheckForEmptyIterator1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "SetPageLocator1"
    via: "next"
    to: "CallNode7"
    into: "in"
