flow: "ViewWarrantyPrices_32"
kind: "view"

entries:
  - id: "StartNode1"
    name: "View"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode10"
    name: "StoreScaledPriceConfig"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode11"
    name: "AddScaledPrice"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode12"
    name: "DeleteScaledPrices"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "StorePriceProvider"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "StorePercentageConfig"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "DispatchPercentage"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "DispatchScaledPrice"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "StoreFixedPriceConfig"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "AddFixedPrice"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "DeleteFixedPrices"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "DispatchFixedPrice"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessWarranty-GetWarrantyBO"
  - id: "CallNode10"
    type: "call"
    ref: "ProcessWarrantyPrices-StoreScaledPriceConfig"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode12"
    type: "call"
    ref: "ProcessWarranty-GetWarrantyBO"
  - id: "CallNode13"
    type: "call"
    ref: "ProcessWarranty-GetWarrantyBO"
  - id: "CallNode14"
    type: "call"
    ref: "ProcessWarrantyPrices-AddScaledPrice"
  - id: "CallNode15"
    type: "call"
    ref: "ProcessWarranty-GetWarrantyBO"
  - id: "CallNode16"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode17"
    type: "call"
    ref: "ProcessWarrantyPrices-DeleteScaledPrices"
    bindings:
      ScaleIDs: "UUIDIterator"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessWarrantyPrices-StorePriceProvider"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessWarranty-GetWarrantyBO"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessWarrantyPrices-StorePercentageConfig"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessWarrantyPrices-StoreFixedPriceConfig"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessWarranty-GetWarrantyBO"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessWarrantyPrices-AddFixedPrice"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode9"
    type: "call"
    ref: "ProcessWarrantyPrices-DeleteFixedPrices"
    bindings:
      Currencies: "UUIDIterator"
  - id: "DecisionNode1"
    type: "decision"
    condition: "UUIDIterator"
  - id: "DecisionNode2"
    type: "decision"
    condition: "UUIDIterator"
  - id: "DecisionNode5"
    type: "decision"
    condition: "Locale"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewWarrantyPrices_32-StorePercentageConfig"
    bindings:
      Key_0: "apply"
      SelectionKey: "JumpTarget"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewWarrantyPrices_32-StoreScaledPriceConfig"
      OutValue_1: "ViewWarrantyPrices_32-AddScaledPrice"
      OutValue_2: "ViewWarrantyPrices_32-DeleteScaledPrices"
    bindings:
      Key_0: "apply"
      SelectionKey: "JumpTarget"
      Key_1: "add"
      Key_2: "delete"
  - id: "DispatchFormAction3"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewWarrantyPrices_32-StoreFixedPriceConfig"
      OutValue_1: "ViewWarrantyPrices_32-AddFixedPrice"
      OutValue_2: "ViewWarrantyPrices_32-DeleteFixedPrices"
    bindings:
      Key_0: "apply"
      SelectionKey: "JumpTarget"
      Key_1: "add"
      Key_2: "delete"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Request Locale"
    bindings:
      LocaleId: "null"
  - id: "GetWarrantyBO1"
    type: "pipelet"
    ref: "GetWarrantyBO"
    bindings:
      SKU: "Product:SKU"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewProductPrices_32-View"
  - id: "JumpNode10"
    type: "jump"
    ref: "ViewProductPrices_32-View"
  - id: "JumpNode11"
    type: "jump"
    ref: "ViewProductPrices_32-View"
  - id: "JumpNode12"
    type: "jump"
    ref: "ViewProductPrices_32-View"
  - id: "JumpNode14"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode15"
    type: "jump"
    ref: "ViewProduct_32-ErrorProductNotAvailable"
  - id: "JumpNode16"
    type: "jump"
    ref: "ViewProductPrices_32-View"
  - id: "JumpNode17"
    type: "jump"
    ref: "ViewProductPrices_32-View"
  - id: "JumpNode18"
    type: "jump"
    ref: "ViewProductPrices_32-View"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewProduct_32-ErrorProductNotAvailable"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewProduct_32-ErrorProductNotAvailable"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewProductPrices_32-View"
  - id: "JumpNode5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode7"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode9"
    type: "jump"
    ref: "ViewProduct_32-ErrorProductNotAvailable"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:getRepository(\"WarrantyBORepository\")"
      OutValue_1: "WarrantyBORepository"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:getRepository(\"WarrantyBORepository\")"
      OutValue_1: "WarrantyBORepository"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:getRepository(\"WarrantyBORepository\")"
      OutValue_1: "WarrantyBORepository"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:getRepository(\"WarrantyBORepository\")"
      OutValue_1: "WarrantyBORepository"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:getRepository(\"WarrantyBORepository\")"
      OutValue_1: "WarrantyBORepository"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:getRepository(\"WarrantyBORepository\")"
      OutValue_1: "WarrantyBORepository"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:getRepository(\"WarrantyBORepository\")"
      OutValue_1: "WarrantyBORepository"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:getRepository(\"WarrantyBORepository\")"
      OutValue_1: "WarrantyBORepository"
  - id: "Pipelet9"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:getRepository(\"WarrantyBORepository\")"
      OutValue_1: "WarrantyBORepository"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "warranty/WarrantyPrices_32"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Value: "ViewProductPrices_32-View"
      Name: "JumpTarget"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Value: "ViewProductPrices_32-View"
      Name: "JumpTarget"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Value: "ViewProductPrices_32-View"
      Name: "JumpTarget"
      ValueType: "Dictionary Value"
  - id: "TextNode1"
    type: "text"
  - id: "TextNode2"
    type: "text"
  - id: "TextNode3"
    type: "text"

links:
  - from: "StartNode5"
    via: "next"
    to: "DispatchFormAction2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "CallNode12"
    via: "error_no_product"
    to: "JumpNode15"
    into: "in"
  - from: "StartNode10"
    via: "next"
    to: "Pipelet9"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "CallNode15"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "JumpNode10"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode1"
    via: "error_no_product"
    to: "JumpNode2"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet3"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode6"
    via: "error_no_product"
    to: "JumpNode9"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "StartNode12"
    via: "next"
    to: "CallNode16"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "CallNode16"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode17"
    via: "next"
    to: "JumpNode18"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet4"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JumpNode12"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "JumpNode16"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "CallNode14"
    via: "next"
    to: "JumpNode17"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "JumpNode12"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "DispatchFormAction3"
    into: "in"
  - from: "CallNode3"
    via: "error_no_product"
    to: "JumpNode3"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode11"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "DispatchFormAction2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "DispatchFormAction3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode11"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "GetWarrantyBO1"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "CallNode17"
    into: "in"
  - from: "Pipelet7"
    via: "next"
    to: "CallNode15"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "Pipelet9"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "GetLocale1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "JoinNode5"
    into: "in1"
  - from: "DispatchFormAction3"
    via: "error"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JumpNode14"
    into: "in"
  - from: "GetWarrantyBO1"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "DispatchFormAction2"
    via: "error"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JumpNode7"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "JumpNode11"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JumpNode18"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "Pipelet8"
    into: "in"
