flow: "ViewDomainPreferences_32"
kind: "view"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreferences"
      WorkingTemplate: "channel/ChannelDomainPreferences_32"

links:
  - from: "Start1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
