flow: "ViewForgotLoginData"
kind: "view"

entries:
  - id: "StartNode1"
    name: "ForgotPassword"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode11"
    name: "Error"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode13"
    name: "GetNewPasswordForm"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "GetForgotPasswordFormStep1"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode4"
    name: "Step2"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "SendPassword"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "GetForgotPasswordFormStep2"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode8"
    name: "NewPassword"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "UpdatePassword"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewForgotLoginData-GetForgotPasswordFormStep1"
  - id: "CallNode13"
    type: "call"
    ref: "ViewForgotLoginData-GetNewPasswordForm"
  - id: "CallNode14"
    type: "call"
    ref: "ViewForgotLoginData-GetNewPasswordForm"
  - id: "CallNode16"
    type: "call"
    ref: "ProcessForgotLoginData-UpdatePassword"
    bindings:
      Password: "NewPasswordForm:Password:Value"
      NewPasswordExpiry: "CurrentDate"
      PasswordConfirmation: "NewPasswordForm:ConfirmPassword:Value"
  - id: "CallNode17"
    type: "call"
    ref: "ProcessForgotLoginData-CheckHashValue"
  - id: "CallNode18"
    type: "call"
    ref: "ProcessForgotLoginData-CheckForTimeout"
  - id: "CallNode19"
    type: "call"
    ref: "ProcessForgotLoginData-CheckForTimeout"
  - id: "CallNode2"
    type: "call"
    ref: "ViewForgotLoginData-GetForgotPasswordFormStep1"
  - id: "CallNode20"
    type: "call"
    ref: "ProcessForgotLoginData-CheckForDisabledUser"
    bindings:
      UserID: "uid"
  - id: "CallNode21"
    type: "call"
    ref: "ProcessForgotLoginData-CheckForDisabledUser"
  - id: "CallNode22"
    type: "call"
    ref: "ProcessForgotLoginData-CheckHashValue"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessUser-GetLoginType"
  - id: "CallNode4"
    type: "call"
    ref: "ViewForgotLoginData-GetForgotPasswordFormStep2"
  - id: "CallNode5"
    type: "call"
    ref: "ViewForgotLoginData-GetForgotPasswordFormStep2"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessForgotLoginData-CheckUserInput"
    bindings:
      Organization: "CurrentOrganization"
      Login: "ForgotPasswordFormStep1:Login:Value"
      FirstName: "ForgotPasswordFormStep1:FirstName:Value"
      LastName: "ForgotPasswordFormStep1:LastName:Value"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessForgotLoginData-CheckAnswer"
    bindings:
      PasswordReminder: "ForgotPasswordFormStep2:Answer:Value"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessForgotLoginData-SendMail"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "NewPassword"
      FormResource: "NewPassword"
    bindings:
      Form: "NewPasswordForm"
  - id: "CreateForm2"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormResource: "ForgotPassword"
      FormName: "ForgotPasswordStep1Email"
    bindings:
      Form: "ForgotPasswordFormStep1"
  - id: "CreateForm3"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormResource: "ForgotPassword"
      FormName: "ForgotPasswordStep1Username"
    bindings:
      Form: "ForgotPasswordFormStep1"
  - id: "CreateForm4"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormResource: "ForgotPassword"
      FormName: "ForgotPasswordStep2"
    bindings:
      Form: "ForgotPasswordFormStep2"
  - id: "DetermineUser2"
    type: "pipelet"
    ref: "DetermineUser"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewForgotLoginData-Step2"
      OutValue_1: "ViewForgotLoginData-SendPassword"
      OutValue_2: "ViewForgotLoginData-UpdatePassword"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "Step2"
      Key_1: "SendPassword"
      Key_2: "UpdatePassword"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ForgotPasswordFormStep2"
        type: "com.intershop.beehive.core.capi.webform.Form"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "ForgotPasswordFormStep1"
        type: "com.intershop.beehive.core.capi.webform.Form"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "NewPasswordForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        guaranteed: true
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewForgotLoginData-ForgotPassword"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewPage-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewPage-Start"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewPage-Start"
  - id: "JumpNode6"
    type: "jump"
    ref: "ViewPage-Start"
  - id: "JumpNode7"
    type: "jump"
    ref: "ViewForgotLoginData-Error"
  - id: "JumpNode8"
    type: "jump"
    ref: "ViewPage-Start"
  - id: "JumpNode9"
    type: "jump"
    ref: "ViewHomepage-DisplayCachedHomepage"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "CurrentRequest:PipelineDictionary"
      OutValue_1: "Dictionary"
      InValue_3: "\"systempage.account.forgotPassword.pagelet2-systempage.account.forgotPassword\""
      OutValue_3: "PageletEntryPointID"
      InValue_2: "\"account/forgotlogindata/ForgotPasswordStep1\""
      OutValue_2: "WorkingTemplate"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "CurrentRequest:PipelineDictionary"
      OutValue_1: "Dictionary"
      InValue_3: "\"systempage.account.forgotPassword.pagelet2-systempage.account.forgotPassword\""
      OutValue_3: "PageletEntryPointID"
      InValue_2: "\"account/forgotlogindata/ForgotPasswordStep2\""
      OutValue_2: "WorkingTemplate"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "CurrentRequest:PipelineDictionary"
      OutValue_1: "Dictionary"
      InValue_3: "\"systempage.account.forgotPassword.pagelet2-systempage.account.forgotPassword\""
      OutValue_3: "PageletEntryPointID"
      InValue_2: "\"account/forgotlogindata/SendPassword\""
      OutValue_2: "WorkingTemplate"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "CurrentRequest:PipelineDictionary"
      OutValue_1: "Dictionary"
      InValue_3: "\"systempage.account.newPassword.pagelet2-systempage.account.newPassword\""
      OutValue_3: "PageletEntryPointID"
      InValue_2: "\"account/forgotlogindata/NewPassword\""
      OutValue_2: "WorkingTemplate"
  - id: "KeyMapper6"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "CurrentRequest:PipelineDictionary"
      OutValue_1: "Dictionary"
      InValue_3: "\"systempage.account.forgotPassword.pagelet2-systempage.account.forgotPassword\""
      OutValue_3: "PageletEntryPointID"
      InValue_2: "\"account/forgotlogindata/ErrorPasswordReminder\""
      OutValue_2: "WorkingTemplate"
  - id: "KeyMapper7"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "UserID"
      OutValue_1: "uid"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "ForgotPasswordFormStep2"
  - id: "ValidateForm2"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "ForgotPasswordFormStep1"
  - id: "ValidateForm3"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "NewPasswordForm"

links:
  - from: "KeyMapper2"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "JumpNode1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CreateForm4"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CreateForm4"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode7"
    via: "ERROR"
    to: "JoinNode4"
    into: "in2"
  - from: "CallNode2"
    via: "next"
    to: "ValidateForm2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode6"
    via: "ERROR"
    to: "JoinNode3"
    into: "in2"
  - from: "CallNode16"
    via: "next"
    to: "JumpNode9"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "ValidateForm2"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "CreateForm3"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "ValidateForm1"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "ValidateForm3"
    via: "error"
    to: "KeyMapper7"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "JumpNode6"
    into: "in"
  - from: "KeyMapper7"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "CreateForm2"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "CallNode14"
    via: "next"
    to: "ValidateForm3"
    into: "in"
  - from: "CallNode20"
    via: "next"
    to: "CallNode18"
    into: "in"
  - from: "CallNode18"
    via: "next"
    to: "CallNode17"
    into: "in"
  - from: "CallNode19"
    via: "TIMEOUT"
    to: "JoinNode8"
    into: "in2"
  - from: "CallNode17"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "CallNode20"
    via: "DISABLED"
    to: "JoinNode9"
    into: "in3"
  - from: "StartNode9"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "KeyMapper6"
    via: "next"
    to: "JumpNode8"
    into: "in"
  - from: "CallNode3"
    via: "LOGINISEMAIL"
    to: "CreateForm2"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "CallNode17"
    via: "ERROR"
    to: "JoinNode7"
    into: "in1"
  - from: "StartNode11"
    via: "next"
    to: "KeyMapper6"
    into: "in"
  - from: "CallNode16"
    via: "ERROR"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode21"
    via: "next"
    to: "CallNode19"
    into: "in"
  - from: "ValidateForm3"
    via: "next"
    to: "CallNode21"
    into: "in"
  - from: "CallNode21"
    via: "DISABLED"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "JumpNode7"
    into: "in"
  - from: "CallNode22"
    via: "ERROR"
    to: "JoinNode7"
    into: "in1"
  - from: "CallNode13"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode6"
    into: "in3"
  - from: "ValidateForm1"
    via: "error"
    to: "DetermineUser2"
    into: "in"
  - from: "CallNode18"
    via: "TIMEOUT"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode7"
    into: "in3"
  - from: "JoinNode5"
    via: "next"
    to: "CallNode20"
    into: "in"
  - from: "CallNode19"
    via: "next"
    to: "CallNode22"
    into: "in"
  - from: "DetermineUser2"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "CallNode22"
    via: "next"
    to: "CallNode16"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CreateForm3"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "ValidateForm2"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "StartNode13"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "EndNode3"
    into: "in"
