flow: "ViewData"
kind: "view"

entries:
  - id: "StartNode4"
    name: "SecureForBrowserBack"
    mode: "private"
    strict: false
    inputs:
      - key: "JumpTarget"
        type: "java.lang.String"
        required: false
  - id: "StartNode5"
    name: "CheckForValidContinuation"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentRequest"
        type: "com.intershop.beehive.core.capi.request.Request"
        required: false

steps:
  - id: "CallNode6"
    type: "call"
    ref: "ViewData-CheckForValidContinuation"
  - id: "DecisionNode1"
    type: "decision"
    condition: "JumpTarget"
  - id: "DecisionNode3"
    type: "decision"
    condition: "SecureForBrowserBack"
  - id: "DecisionNode5"
    type: "decision"
    condition: "CallStackEntry:StartNode:Name"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "GetClipboard2"
    type: "pipelet"
    ref: "GetClipboard"
    config:
      SessionRegistrationID: "SecureForBrowserBack_FormParameterStorage"
      SetFormValues: "Yes"
    bindings:
      SessionRegistrationID: "null"
      Clipboard: "null"
      UUIDIterator: "null"
  - id: "InteractionContinueNode1"
    type: "interaction_continue"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "LoopNode1"
    type: "loop"
  - id: "RemoveClipboard1"
    type: "pipelet"
    ref: "RemoveClipboard"
    config:
      SessionRegistrationID: "SecureForBrowserBack_FormParameterStorage"
    bindings:
      SessionRegistrationID: "null"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "SecureForBrowserBack"
      Value: true
      ValueType: "Form Value"
  - id: "StopNode1"
    type: "stop"
  - id: "UpdateClipboard1"
    type: "pipelet"
    ref: "UpdateClipboard"
    config:
      SessionRegistrationID: "SecureForBrowserBack_FormParameterStorage"
      StoreFormValues: "Yes"
    bindings:
      AllObjectUUIDs: "null"
      SelectedObjectUUIDs: "null"
      SessionRegistrationID: "null"
      Clipboard: "null"
      UUIDIterator: "null"

links:
  - from: "StartNode4"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "StopNode1"
    into: "in"
  - from: "CallNode6"
    via: "yes"
    to: "GetClipboard2"
    into: "in"
  - from: "GetClipboard2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "UpdateClipboard1"
    via: "next"
    to: "InteractionContinueNode1"
    into: "in"
  - from: "CallNode6"
    via: "no"
    to: "JumpNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "LoopNode1"
    into: "loop"
  - from: "DecisionNode5"
    via: "no"
    to: "EndNode4"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "EndNode2"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "RemoveClipboard1"
    into: "in"
  - from: "InteractionContinueNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "RemoveClipboard1"
    via: "next"
    to: "UpdateClipboard1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "DecisionNode5"
    into: "in"
