flow: "ViewChannelCatalogFilterList"
kind: "view"

entries:
  - id: "Start2"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Refresh"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Publish"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Search"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "FilterVector"
      Iterator: "Filters"
      Object: "Filter"
      Objects: "none"
      OutVector: "FilterVector"
  - id: "Call10"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "Call6"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call8"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "Call9"
    type: "call"
    ref: "PublishCatalogFilter-Multiple"
  - id: "CallNode1"
    type: "call"
    ref: "GetCatalogFilters-GetEditableFilters"
  - id: "CallNode2"
    type: "call"
    ref: "ViewChannelCatalogFilter-InvalidatePageCaches"
  - id: "CallNode3"
    type: "call"
    ref: "ViewChannelCatalogFilter-GetSites"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessPaging-SetPageNumber"
    bindings:
      Pageable: "CatalogFilters"
  - id: "CheckForEmptyIterator1"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "UUIDIterator"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "\"SLD_AR_\""
      String1: "CurrentChannel:TypeCode"
      String2: "\"_CATALOG_VIEWER\""
      Concatenated: "PermissionGroupID"
  - id: "DecisionNode1"
    type: "decision"
    condition: "UUIDIterator"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelCatalogFilter-New"
      OutValue_1: "ViewChannelCatalogFilterList-Paging"
      OutValue_2: "ViewChannelCatalogFilterList-Publish"
      OutValue_3: "ViewChannelCatalogFilterList-Paging"
      OutValue_4: "ViewChannelCatalogFilterList-Paging"
      OutValue_5: "ViewChannelCatalogFilterList-Delete"
      PagingPipeline: "ViewChannelCatalogFilterList-Paging"
    bindings:
      Key_0: "new"
      Key_1: "refresh"
      Key_2: "publish"
      Key_3: "confirmDelete"
      Key_4: "cancelDelete"
      Key_5: "delete"
      SelectionKey: "JumpTarget"
  - id: "GetCatalogFilter1"
    type: "pipelet"
    ref: "GetCatalogFilter"
    bindings:
      FilterID: "CatalogFilterUUID"
  - id: "GetCatalogFilter2"
    type: "pipelet"
    ref: "GetCatalogFilter"
    bindings:
      FilterID: "CatalogFilterUUID"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      RestorePageLocatorDictionary: "True"
  - id: "GetPageLocator2"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      RestorePageLocatorDictionary: "True"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "CatalogFilters"
      PageableID: "PageLocator:PageableID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump3"
    type: "jump"
    ref: "ViewChannelCatalogFilterList-Refresh"
  - id: "Jump4"
    type: "jump"
    ref: "ViewChannelCatalogFilterList-ListAll"
  - id: "Jump5"
    type: "jump"
    ref: "ViewChannelCatalogFilterList-Paging"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentChannel"
      OutValue_1: "Repository"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentChannel:RepositoryDomain"
      OutValue_1: "FilterDomain"
  - id: "Loop1"
    type: "loop"
  - id: "Loop2"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "CatalogFilters"
      WorkingTemplate: "filter/ChannelCatalogFilterList"
  - id: "RemoveCatalogFilter1"
    type: "pipelet"
    ref: "RemoveCatalogFilter"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "Clipboard"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "FindPerformed"
      Value: true
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewChannelCatalogFilterList-Paging"
      DefaultPageLocatorName: "CatalogFilterList"
    bindings:
      Pageable: "CatalogFilters"

links:
  - from: "Start5"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Loop2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "GetCatalogFilter1"
    via: "next"
    to: "RemoveCatalogFilter1"
    into: "in"
  - from: "RemoveCatalogFilter1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "GetCatalogFilter1"
    via: "error"
    to: "Join3"
    into: "in3"
  - from: "Loop1"
    via: "do"
    to: "GetCatalogFilter1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode2"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Loop2"
    via: "do"
    to: "GetCatalogFilter2"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "GetCatalogFilter2"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetCatalogFilter2"
    via: "error"
    to: "Join4"
    into: "in3"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "CheckForEmptyIterator1"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "next"
    to: "Loop2"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "error"
    to: "Jump5"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "Join1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join6"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "GetPageLocator2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "CallNode4"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "SetPageLocator1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "GetPageLocator2"
    via: "next"
    to: "Join6"
    into: "in2"
  - from: "AddObjectToVector1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Start6"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
