flow: "ViewChannelLabel"
kind: "view"

entries:
  - id: "Start5"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "UpdateClipboard"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "List"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode10"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode11"
    name: "GetLocale"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "New"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Update"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "UpdateWebForm"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "Create"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "SingleDelete"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewChannelLabel-Prefix"
  - id: "CallNode10"
    type: "call"
    ref: "ProcessPaging-SetPageNumber"
    bindings:
      Pageable: "Labels"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessPaging-GetPageLocatorPageable"
    bindings:
      PageLocatorName: "\"LabelList\""
      Pageable: "Labels"
  - id: "CallNode12"
    type: "call"
    ref: "ProcessLabel-Create"
    bindings:
      Domain: "CurrentChannel:Domain"
      LabelDescription: "LabelForm:Description:Value"
      LabelDisplayName: "LabelForm:DisplayName:Value"
      LabelName: "LabelForm:Name:Value"
      User: "CurrentUser"
  - id: "CallNode13"
    type: "call"
    ref: "ProcessLabel-GetLabelsByDomain"
    bindings:
      Domain: "CurrentChannel:Domain"
  - id: "CallNode14"
    type: "call"
    ref: "ProcessPaging-SetPageSize"
    bindings:
      Pageable: "Labels"
      PageSize: "\"15\""
  - id: "CallNode2"
    type: "call"
    ref: "ViewChannelLabel-UpdateWebForm"
  - id: "CallNode3"
    type: "call"
    ref: "ViewChannelLabel-UpdateWebForm"
  - id: "CallNode4"
    type: "call"
    ref: "ViewChannelLabel-UpdateClipboard"
  - id: "CallNode5"
    type: "call"
    ref: "ViewChannelLabel-UpdateWebForm"
  - id: "CallNode6"
    type: "call"
    ref: "ViewChannelLabel-Prefix"
  - id: "CallNode7"
    type: "call"
    ref: "ViewChannelLabel-GetLocale"
  - id: "CallNode8"
    type: "call"
    ref: "ViewChannelLabel-GetLocale"
  - id: "CallNode9"
    type: "call"
    ref: "ViewChannelLabel-GetLocale"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      webform-id: "LabelForm"
      param.1.name: "DisplayName"
      param.1.rule: ""
      param.1.required: false
      param.2.name: "Name"
      param.2.rule: ""
      param.2.required: true
      param.3.name: "Description"
      param.3.rule: ""
      param.3.required: false
    bindings:
      WebForm: "LabelForm"
  - id: "CreateWebForm3"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      webform-id: "LabelForm"
      param.1.name: "DisplayName"
      param.1.rule: ""
      param.1.required: false
      param.2.name: "Name"
      param.2.rule: ""
      param.2.required: true
      param.3.name: "Description"
      param.3.rule: ""
      param.3.required: false
    bindings:
      WebForm: "LabelForm"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ApplicationState:LastButOneBreadcrumb:Pipeline"
  - id: "DetermineLocales4"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelLabel-New"
      PagingPipeline: "ViewChannelLabel-Paging"
      OutValue_1: "ViewChannelLabel-Create"
      OutValue_2: "ViewChannelLabel-Delete"
      OutValue_3: "ViewChannelLabel-Update"
      OutValue_4: "ViewChannelLabel-Paging"
      OutValue_5: "ViewChannelLabel-Update"
      OutValue_6: "ViewChannelLabel-SingleDelete"
      OutValue_7: "ViewChannelLabel-Edit"
      OutValue_8: "ViewChannelLabel-Edit"
      OutValue_9: "ViewChannelLabel-New"
    bindings:
      Key_0: "new"
      Key_1: "create"
      SelectionKey: "JumpTarget"
      Key_2: "delete"
      Key_3: "update"
      Key_4: "confirmDelete"
      Key_5: "confirmSingleDelete"
      Key_6: "singleDelete"
      Key_7: "cancelUpdate"
      Key_8: "selectLocale"
      Key_9: "selectLocaleNew"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelLabelAction-SelectAction"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "selectAction"
  - id: "End2"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "EndNode5"
    type: "end"
    strict: false
  - id: "GetClipboard1"
    type: "pipelet"
    ref: "GetClipboard"
    config:
      SessionRegistrationID: "CB_Labels"
      SetFormValues: "No"
    bindings:
      UUIDIterator: "SelectedLabels"
      Clipboard: "null"
  - id: "GetFormSelection3"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "LabelUUID"
    bindings:
      Selection: "LabelUUIDIterator"
  - id: "GetFormSelection4"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedLabelUUID"
    bindings:
      Selection: "SelectedLabelUUIDIterator"
  - id: "GetLabel1"
    type: "pipelet"
    ref: "GetLabel"
  - id: "GetLabel2"
    type: "pipelet"
    ref: "GetLabel"
  - id: "GetLabel3"
    type: "pipelet"
    ref: "GetLabel"
  - id: "GetLocale3"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetPageLocator2"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "LabelList"
      RestorePageLocatorDictionary: "False"
      UsePageLocatorHistory: false
    bindings:
      PageLocatorName: "null"
  - id: "GetWebForm3"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "LabelForm"
    bindings:
      WebForm: "LabelForm"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd5"
    type: "interaction"
  - id: "InvalidatePageLocatorPageable1"
    type: "pipelet"
    ref: "InvalidatePageLocatorPageable"
    config:
      DefaultPageLocatorName: "LabelList"
    bindings:
      PageLocatorName: "null"
  - id: "InvalidatePageLocatorPageable2"
    type: "pipelet"
    ref: "InvalidatePageLocatorPageable"
    config:
      DefaultPageLocatorName: "LabelList"
    bindings:
      PageLocatorName: "null"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "Error-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewChannelObjectLabels-Assign"
  - id: "JumpNode5"
    type: "jump"
    ref: "This:List"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationState:LastButOneBreadcrumb:LinkParameter:ProductID"
      OutValue_1: "ProductID"
      InValue_10: "ApplicationState:LastButOneBreadcrumb:LinkParameter:LabelObjectType"
      OutValue_10: "LabelObjectType"
      InValue_2: "ApplicationState:LastButOneBreadcrumb:LinkParameter:CatalogCategoryID"
      OutValue_2: "CatalogCategoryID"
  - id: "LoopNode1"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "MassDataTasks"
      WorkingTemplate: "labeling/ChannelLabelList"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "MassDataTasks"
      WorkingTemplate: "labeling/ChannelLabelNew"
  - id: "PrepareApplicationView5"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "MassDataTasks"
      WorkingTemplate: "labeling/ChannelLabelUpdate"
  - id: "RemoveClipboard1"
    type: "pipelet"
    ref: "RemoveClipboard"
    config:
      SessionRegistrationID: "CB_Labels"
    bindings:
      SessionRegistrationID: "null"
  - id: "RemoveLabel1"
    type: "pipelet"
    ref: "RemoveLabel"
  - id: "RemoveLabel2"
    type: "pipelet"
    ref: "RemoveLabel"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: "LabelExists"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewChannelLabel-Paging"
      ValueType: "Dictionary Value"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewChannelLabel-Paging"
      DefaultPageLocatorName: "LabelList"
    bindings:
      Pageable: "Labels"
      HandlerPipeline: "null"
      PageLocatorName: "null"
  - id: "UpdateClipboard2"
    type: "pipelet"
    ref: "UpdateClipboard"
    config:
      SessionRegistrationID: "CB_Labels"
      StoreFormValues: "No"
    bindings:
      AllObjectUUIDs: "LabelUUIDIterator"
      SelectedObjectUUIDs: "SelectedLabelUUIDIterator"
      SessionRegistrationID: "null"
  - id: "UpdateLabel1"
    type: "pipelet"
    ref: "UpdateLabel"
    bindings:
      LabelDescription: "LabelForm:Description:Value"
      LabelDisplayName: "LabelForm:DisplayName:Value"
  - id: "UpdateWebForm3"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      webform-id: "LabelForm"
      mode: "update"
    bindings:
      WebForm: "LabelForm"
  - id: "ValidateWebForm3"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "LabelForm"

links:
  - from: "CallNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode11"
    via: "Error"
    to: "JoinNode8"
    into: "in1"
  - from: "CallNode12"
    via: "next"
    to: "InvalidatePageLocatorPageable2"
    into: "in"
  - from: "CallNode12"
    via: "Error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "DetermineLocales4"
    via: "next"
    to: "GetLocale3"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "UpdateLabel1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "RemoveClipboard1"
    into: "in"
  - from: "PrepareApplicationView5"
    via: "next"
    to: "InteractionEnd5"
    into: "in"
  - from: "RemoveClipboard1"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "SetPageLocator1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CreateWebForm1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CreateWebForm3"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode6"
    into: "in3"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "GetLabel2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "DispatchFormAction2"
    via: "next"
    to: "JoinNode13"
    into: "in2"
  - from: "CallNode5"
    via: "next"
    to: "JoinNode12"
    into: "in2"
  - from: "CallNode14"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "UpdateLabel1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "JumpNode5"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "KeyMapper1"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode3"
    via: "Invalid"
    to: "JoinNode3"
    into: "in1"
  - from: "StartNode7"
    via: "next"
    to: "GetClipboard1"
    into: "in"
  - from: "GetPageLocator2"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "GetLabel2"
    via: "error"
    to: "JumpNode1"
    into: "in"
  - from: "GetPageLocator2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "UpdateClipboard2"
    via: "next"
    to: "End2"
    into: "in"
  - from: "CallNode3"
    via: "Created"
    to: "JoinNode3"
    into: "in3"
  - from: "JoinNode6"
    via: "next"
    to: "PrepareApplicationView5"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "DispatchFormAction2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "GetFormSelection3"
    via: "next"
    to: "UpdateClipboard2"
    into: "in"
  - from: "GetFormSelection4"
    via: "next"
    to: "GetFormSelection3"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "GetFormSelection4"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "DispatchFormAction2"
    via: "error"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "UpdateWebForm3"
    via: "next"
    to: "ValidateWebForm3"
    into: "in"
  - from: "ValidateWebForm3"
    via: "error"
    to: "EndNode3"
    into: "in"
  - from: "GetWebForm3"
    via: "error"
    to: "CreateWebForm3"
    into: "in"
  - from: "GetWebForm3"
    via: "next"
    to: "UpdateWebForm3"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "GetWebForm3"
    into: "in"
  - from: "ValidateWebForm3"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "GetClipboard1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "GetLabel1"
    into: "in"
  - from: "GetLabel1"
    via: "next"
    to: "RemoveLabel1"
    into: "in"
  - from: "GetLabel1"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "RemoveLabel1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "InvalidatePageLocatorPageable1"
    via: "next"
    to: "GetPageLocator2"
    into: "in"
  - from: "GetLabel3"
    via: "error"
    to: "JoinNode11"
    into: "in2"
  - from: "CallNode13"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "GetLabel3"
    via: "next"
    to: "RemoveLabel2"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "GetLabel3"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode10"
    via: "next"
    to: "InvalidatePageLocatorPageable1"
    into: "in"
  - from: "RemoveLabel2"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "JoinNode10"
    into: "in3"
  - from: "CallNode6"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "StartNode10"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode2"
    via: "Created"
    to: "JoinNode12"
    into: "in1"
  - from: "JoinNode12"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode11"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "StartNode11"
    via: "next"
    to: "DetermineLocales4"
    into: "in"
  - from: "GetLocale3"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "InvalidatePageLocatorPageable2"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "GetLabel2"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode13"
    into: "in1"
  - from: "JoinNode13"
    via: "next"
    to: "Jump3"
    into: "in"
