flow: "ViewChannelProductAssignmentMapping"
kind: "view"

entries:
  - id: "Start2"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Prefix"
    mode: "private"
    strict: true
    inputs:
      - key: "ProviderID"
        type: "java.lang.String"
        required: true
      - key: "CurrentChannel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true

steps:
  - id: "Call1"
    type: "call"
    ref: "This:Prefix"
  - id: "Call5"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode1"
    type: "call"
    ref: "ViewProductAssignmentMapping-GetProductDataMappingRule"
    bindings:
      TypeCode: "\"10\""
  - id: "CallNode2"
    type: "call"
    ref: "ViewProductAssignmentMapping-SetMappingsEnabled"
  - id: "CallNode5"
    type: "call"
    ref: "ViewProductAssignmentMapping-VerifyMappingEnabledValue"
    bindings:
      MappingEnabledValue: "MappingEnabled"
  - id: "End2"
    type: "end"
    strict: true
    outputs:
      - key: "ProductDataMappingRuleSet"
        type: "com.intershop.component.mvc.capi.mapping.ProductDataMappingRuleSet"
        guaranteed: true
      - key: "ProvidingRepository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        guaranteed: true
  - id: "GetProductDataMappingRuleSet2"
    type: "pipelet"
    ref: "GetProductDataMappingRuleSet"
    bindings:
      DeclaringDomain: "CurrentChannel:RepositoryDomain"
      ProvidingDomain: "ProvidingRepository:Domain"
  - id: "GetRepositoryByUUID2"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "ProvidingRepository"
      UUID: "ProviderID"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/ChannelProductAssignmentMapping.isml"

links:
  - from: "GetProductDataMappingRuleSet2"
    via: "next"
    to: "End2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "GetRepositoryByUUID2"
    into: "in"
  - from: "GetRepositoryByUUID2"
    via: "next"
    to: "GetProductDataMappingRuleSet2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode1"
    into: "in3"
