flow: "ViewManufacturerAliasList_32"
kind: "view"

entries:
  - id: "StartNode0"
    name: "List"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "ListAllKeepSelection"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call5"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "CreatePageableFromIterator1"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    config:
      PageableName: "ManufacturerAliases"
    bindings:
      Iterator: "ManufacturerAliasesIterator"
      Pageable: "Aliases"
  - id: "Decision1"
    type: "decision"
    condition: "PageNumber"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewManufacturerAlias_32-New"
      OutValue_1: "ViewManufacturerAliasList_32-Paging"
      OutValue_2: "ViewManufacturerAliasList_32-Paging"
      PagingPipeline: "ViewManufacturerAliasList_32-Paging"
      OutValue_3: "ViewManufacturerAliasList_32-Delete"
      OutValue_4: "ViewManufacturerAliasList_32-ListAll"
    bindings:
      Key_0: "New"
      Key_1: "ConfirmDelete"
      Key_2: "CancelDelete"
      Key_3: "Delete"
      Key_4: "BackToList"
      SelectionKey: "JumpTarget"
  - id: "GetManufacturerNameAlias4"
    type: "pipelet"
    ref: "GetManufacturerNameAlias"
    bindings:
      ManufacturerNameAliasUUID: "SelectedAliasUUID"
      Domain: "CurrentChannel:RepositoryDomain"
      AliasName: "ManufacturerNameAliasName"
  - id: "GetManufacturerNameAliases1"
    type: "pipelet"
    ref: "GetManufacturerNameAliases"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
      ManufacturerNameAliases: "ManufacturerAliases"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      RestorePageLocatorDictionary: "True"
      DefaultPageLocatorName: "AliasesList"
  - id: "GetPageLocator2"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      RestorePageLocatorDictionary: "True"
      DefaultPageLocatorName: "AliasesList"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      PageableID: "PageLocator:PageableID"
      Pageable: "Aliases"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InvalidatePageLocatorPageable1"
    type: "pipelet"
    ref: "InvalidatePageLocatorPageable"
    config:
      DefaultPageLocatorName: "AliasesList"
  - id: "Join1"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "Jump5"
    type: "jump"
    ref: "ViewManufacturerAliasList_32-ListAll"
  - id: "JumpNode0"
    type: "jump"
    ref: "This:Paging"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Loop1"
    type: "loop"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "manufacturer/alias/ManufacturerAliasList_32"
      SelectedMenuItem: "ChannelCatalogs"
  - id: "RemoveManufacturerNameAlias1"
    type: "pipelet"
    ref: "RemoveManufacturerNameAlias"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
      AliasName: "ManufacturerNameAlias:NameAlias"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Aliases"
  - id: "SetPage3"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Aliases"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewManufacturerNameAliases-Paging"
      DefaultPageLocatorName: "AliasesList"
    bindings:
      Pageable: "Aliases"
  - id: "SortIteratorByComparator1"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingAttribute: "NameAlias"
    bindings:
      Iterator: "ManufacturerAliases:Iterator"
      Comparator: "null"
      SortedIterator: "ManufacturerAliasesIterator"
  - id: "UpdatePageSize1"
    type: "pipelet"
    ref: "UpdatePageSize"
    config:
      DefaultPageSize: 15
    bindings:
      PageSize: "null"
      PageableIterator: "Aliases"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      Locale: "null"
      LocalizedString: "PageNumber"
      Pattern: "null"
      IntegerObject: "PageNumber"

links:
  - from: "StartNode0"
    via: "next"
    to: "GetPageLocator2"
    into: "in"
  - from: "GetPageLocator2"
    via: "next"
    to: "InvalidatePageLocatorPageable1"
    into: "in"
  - from: "InvalidatePageLocatorPageable1"
    via: "next"
    to: "JumpNode0"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "CreatePageableFromIterator1"
    via: "next"
    to: "UpdatePageSize1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "SetPage2"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetManufacturerNameAlias4"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "GetManufacturerNameAlias4"
    via: "next"
    to: "RemoveManufacturerNameAlias1"
    into: "in"
  - from: "GetManufacturerNameAliases1"
    via: "next"
    to: "SortIteratorByComparator1"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetPageable1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Join5"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "GetManufacturerNameAliases1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetManufacturerNameAlias4"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "RemoveManufacturerNameAlias1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "SetPage2"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "SetPage3"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "SetPageLocator1"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "SortIteratorByComparator1"
    via: "next"
    to: "CreatePageableFromIterator1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "UpdatePageSize1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage3"
    into: "in"
