flow: "ViewPreviewConfiguration"
kind: "view"

entries:
  - id: "StartNode1"
    name: "UpdateSession"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode18"
    name: "EndPreview"
    mode: "private"
    strict: true
    inputs:
      - key: "PreviewContextID"
        type: "java.lang.String"
        required: true
  - id: "StartNode2"
    name: "FinishPreview"
    mode: "private"
    strict: true
    inputs:
      - key: "PreviewContextBO"
        type: "com.intershop.component.preview.capi.context.PreviewContextBO"
        required: true
  - id: "StartNode3"
    name: "ModifyUpdateUrl"
    mode: "private"
    strict: true
    inputs:
      - key: "UpdateUrl"
        type: "java.lang.String"
        required: true
      - key: "UrlIdentifier"
        type: "java.lang.String"
        required: false
      - key: "TargetSite"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
      - key: "URLParameters"
        type: "java.util.Map"
        required: false
      - key: "CurrencyID"
        type: "java.lang.String"
        required: false
      - key: "LocaleID"
        type: "java.lang.String"
        required: false

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessPreviewContext-Create"
    bindings:
      PreviewContextID: "CurrentSession:SessionID"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessPreviewContext-GetByID"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessPreviewContext-RestorePreviewContext"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessPreviewAttributeContext-CreateConfigurationAttributesMap"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessPreviewContext-GetByID"
  - id: "CallNode5"
    type: "call"
    ref: "EditView-InitializeStorefrontEditingContext"
    bindings:
      BackofficeUserID: "transferablePrefix_BackofficeUserID"
      ContextDate: "DateAttribute:SelectedValue:ValueObject"
      SecureURL: "transferablePrefix_SecureURL"
      InsecureURL: "transferablePrefix_InsecureURL"
      ContentRepositoryUUID: "transferablePrefix_ContentRepositoryUUID"
  - id: "CallNode6"
    type: "call"
    ref: "ViewPreviewConfiguration-FinishPreview"
  - id: "CallNode7"
    type: "call"
    ref: "EditView-InitializeStorefrontEditingContext"
    bindings:
      BackofficeUserID: "transferablePrefix_BackofficeUserID"
      SecureURL: "transferablePrefix_SecureURL"
      InsecureURL: "transferablePrefix_InsecureURL"
      ContentRepositoryUUID: "transferablePrefix_ContentRepositoryUUID"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "PreviewContext4_"
    bindings:
      String1: "ApplicationValue:ValueObject:UUID"
      Concatenated: "PreviewContextID"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PreviewContextID"
  - id: "DecisionNode2"
    type: "decision"
    condition: "transferablePrefix_ContentRepositoryUUID"
  - id: "DecisionNode3"
    type: "decision"
    condition: "transferablePrefix_BackofficeUserID"
  - id: "DecisionNode4"
    type: "decision"
    condition: "DateAttribute:Selected"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "UpdateUrl"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "GetCurrentDate1"
    type: "pipelet"
    ref: "GetCurrentDate"
    bindings:
      CurrentDate: "ContextDate"
  - id: "GetPreviewConfigurationAttribute1"
    type: "pipelet"
    ref: "GetPreviewConfigurationAttribute"
    config:
      AttributeSet: "com.intershop.component.preview.capi.configuration.PreviewConfigurationAttributeSet"
      AttributeSetValue: "PreviewDate"
    bindings:
      PreviewConfigurationAttribute: "DateAttribute"
  - id: "GetPreviewConfigurationAttribute2"
    type: "pipelet"
    ref: "GetPreviewConfigurationAttribute"
    config:
      AttributeSet: "com.intershop.component.preview.capi.configuration.PreviewConfigurationAttributeSet"
      AttributeSetValue: "PreviewApplication"
    bindings:
      PreviewConfigurationAttribute: "PreviewApplicationAttribute"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "LoopNode1"
    type: "loop"
  - id: "ModifyURL1"
    type: "pipelet"
    ref: "ModifyURL"
    config:
      URLParameterHandling: "Append"
    bindings:
      URLString: "UpdateUrl"
      TemplateSet: "UrlIdentifier"
      PipelineName: "null"
      SiteName: "TargetSite:DomainName"
      StartNodeName: "null"
      ServerGroup: "null"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "T_CurrentUserUserGroupKeys"
    bindings:
      SaveObject: "null"
      SessionObjectName: "null"
      TargetSessionDomain: "null"
      TargetSessionID: "null"
  - id: "RemovePreviewContext1"
    type: "pipelet"
    ref: "RemovePreviewContext"
  - id: "RemovePreviewContext2"
    type: "pipelet"
    ref: "RemovePreviewContext"

links:
  - from: "CallNode11"
    via: "ERROR"
    to: "JoinNode12"
    into: "in1"
  - from: "CallNode11"
    via: "next"
    to: "RemovePreviewContext2"
    into: "in"
  - from: "CallNode1"
    via: "ERROR"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode4"
    via: "ERROR"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode4"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode6"
    via: "next"
    to: "RemovePreviewContext1"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode11"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode3"
    via: "yes"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "GetCurrentDate1"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "CallNode5"
    into: "in"
  - from: "GetCurrentDate1"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "GetPreviewConfigurationAttribute1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "GetPreviewConfigurationAttribute2"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "JoinNode12"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "LoopNode1"
    via: "do"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "ModifyURL1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "ModifyURL1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Pipelet4"
    via: "error"
    to: "GetPreviewConfigurationAttribute1"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "GetPreviewConfigurationAttribute1"
    into: "in"
  - from: "RemovePreviewContext1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "RemovePreviewContext2"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "StartNode18"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetPreviewConfigurationAttribute2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "ModifyURL1"
    into: "in"
