flow: "ViewContentSharing_32"
kind: "view"

entries:
  - id: "StartNode1"
    name: "New"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode2"
    type: "call"
    ref: "ViewContentSharingList_32-GetMasterRepository"
    bindings:
      OrganizationUUID: "SelectedOrganizationUUID"
  - id: "CallNode3"
    type: "call"
    ref: "ViewContentSharingList_32-GetMasterRepository"
    bindings:
      OrganizationUUID: "SelectedOrganizationUUID"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString1: "-"
      DefaultString3: "-"
      DefaultString5: "-Proxy"
    bindings:
      Concatenated: "ProxyRepositoryID"
      String4: "MasterRepository:Id"
      String2: "Organization:ID"
      String0: "PartnerOrganization:ID"
  - id: "CreateProxyRepository1"
    type: "pipelet"
    ref: "CreateProxyRepository"
    bindings:
      Repository: "MasterRepository"
      RepositoryType: "MasterRepository:TypeCode"
      Domain: "PartnerMasterRepository:RepositoryDomain"
      RepositoryID: "ProxyRepositoryID"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PageLocator"
  - id: "DecisionNode2"
    type: "decision"
    condition: "PageNumber"
  - id: "DecisionNode3"
    type: "decision"
    condition: "SelectedObjectUUIDs"
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "content/GetPartnersWithSharedContent"
      DefaultPageSize: 15
    bindings:
      Connection: "null"
      Parameters: "QueryParameter"
      Query: "null"
      ErrorCode: "SearchError"
      SearchResult: "PartnersWithoutSharedContent"
  - id: "GetOrganization1"
    type: "pipelet"
    ref: "GetOrganization"
    config:
      Source: "PipelineDictionary"
    bindings:
      OrganizationUUID: "PartnerUUID"
      Organization: "PartnerOrganization"
  - id: "GetRepository1"
    type: "pipelet"
    ref: "GetRepository"
    config:
      Type: "Custom Repository"
      CustomRepositoryTypeCode: 21
    bindings:
      OrganizationDomain: "PartnerOrganization:OrganizationDomain"
      Repository: "PartnerMasterRepository"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewContentSharing_32-Paging"
  - id: "JumpNode2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewContentSharingList_32-Start"
  - id: "LoopNode1"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      PagingPipeline: "ViewContentSharing_32-Paging"
      OutValue_0: "ViewContentSharing_32-Paging"
      OutValue_1: "ViewContentSharing_32-Create"
      OutValue_2: "ViewContentSharingList_32-Start"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "Paging"
      Key_1: "Create"
      Key_2: "Cancel"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"
  - id: "Pipelet16"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "PartnersWithoutSharedContent"
      PageableID: "PageLocator:PageableID"
  - id: "Pipelet17"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "PartnersWithoutSharedContent"
  - id: "Pipelet18"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewContentPartnerSharing_32-Paging"
      DefaultPageLocatorName: "ContentSharingAssignmentPageLocator"
    bindings:
      Pageable: "PartnersWithoutSharedContent"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ContentSharingAssignmentPageLocator"
      RestorePageLocatorDictionary: "True"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "PartnersWithoutSharedContent"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      RenderingType: "HTML"
      SelectedMenuItem: "ContentSharing"
      WorkingTemplate: "content/ContentSharing_32.isml"
  - id: "UpdateDictionary1"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "MasterRepository"
      Name_02: "PartnerChannel"
      Name_03: "WithoutSharedContent"
      Name_06: "Locale"
      Name_04: "SortBy"
      Name_05: "SortDirection"
    bindings:
      InDictionary: "null"
      OutDictionary: "QueryParameter"
      Value_01: "MasterRepository"
      Value_02: "CurrentChannel"
      Value_03: "\"(Boolean)true\""
      Value_04: "SortBy"
      Value_05: "SortDirection"
      Value_06: "CurrentSession:Locale"

links:
  - from: "JoinNode3"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet17"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "Pipelet5"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode3"
    via: "no"
    to: "JumpNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet5"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "Pipelet16"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "Pipelet3"
    via: "next"
    to: "Pipelet16"
    into: "in"
  - from: "Pipelet16"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "DecisionNode3"
    via: "yes"
    to: "CallNode3"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "DecisionNode1"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet11"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Pipelet3"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "UpdateDictionary1"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode8"
    into: "in3"
  - from: "CreateProxyRepository1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "CallNode8"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "Pipelet18"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "UpdateDictionary1"
    into: "in"
  - from: "Pipelet11"
    via: "error"
    to: "JoinNode6"
    into: "in3"
  - from: "LoopNode1"
    via: "do"
    to: "GetOrganization1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "CreateProxyRepository1"
    into: "in"
  - from: "GetOrganization1"
    via: "next"
    to: "GetRepository1"
    into: "in"
  - from: "GetRepository1"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "Pipelet18"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "LoopNode1"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "Pipelet11"
    via: "next"
    to: "Pipelet17"
    into: "in"
