flow: "ViewPageletAssignment"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Prefix"
    mode: "private"
    strict: true
    inputs:
      - key: "ContentRepositoryUUID"
        type: "java.lang.String"
        required: true
      - key: "PageletAssignmentUUID"
        type: "java.lang.String"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode16"
    type: "call"
    ref: "ProcessPageletAssignments-HandlePosition"
    bindings:
      Position: "CalculatedPosition"
      Domain: "ContentRepository:RepositoryDomain"
      Assignment: "PageletAssignment"
  - id: "CallNode17"
    type: "call"
    ref: "ProcessPagelet-UpdatePageletAssignment"
    bindings:
      Active: "AssignmentOnline"
      Position: "CalculatedPosition"
      Assignment: "PageletAssignment"
  - id: "CallNode3"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessPageletAssignments-ProcessAssignmentPositioning"
    bindings:
      Domain: "ContentRepository:RepositoryDomain"
      ToObject: "PageletAssignment:To"
      AssignmentPositioning: "null"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessPageletAssignments-DetermineContextObjectType"
    bindings:
      ContextObject: "PageletAssignment:To"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessDate-VerifyPeriod"
    bindings:
      PeriodFlag: "AssignmentOnline"
  - id: "DecisionNode1"
    type: "decision"
    condition: "DialogMode"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ContextObjectType"
  - id: "DecisionNode3"
    type: "decision"
    condition: "ContextObjectType"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "This:Edit"
      OutValue_1: "This:Update"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "Edit"
      Key_1: "Update"
      Key_2: "New"
  - id: "DispatchFormActionByBreadcrumb1"
    type: "pipelet"
    ref: "DispatchFormActionByBreadcrumb"
    config:
      SplitMode: "PipelineAndParameter"
    bindings:
      Key_0: "Cancel"
      SelectionKey: "JumpTarget"
      OutValue_0: "ApplicationState:LastListView"
  - id: "DispatchFormActionByBreadcrumb2"
    type: "pipelet"
    ref: "DispatchFormActionByBreadcrumb"
    config:
      SplitMode: "PipelineAndParameter"
    bindings:
      Key_0: "\"Cancel\""
      SelectionKey: "JumpTarget"
      OutValue_0: "ApplicationState:LastListView"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ContentRepository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        guaranteed: true
      - key: "PageletAssignment"
        type: "com.intershop.component.pmc.capi.pagelet.assignment.PageletAssignment"
        guaranteed: true
  - id: "GetAssignmentByUUID1"
    type: "pipelet"
    ref: "GetAssignmentByUUID"
    config:
      DefaultAssignmentLookup: "com.intershop.component.pmc.internal.pagelet.entrypoint.assignment.PageletPageletEntryPointAssignmentLookup"
    bindings:
      UUID: "PageletAssignmentUUID"
      Assignment: "PageletAssignment"
      AssignmentLookup: "Assignment"
  - id: "GetAssignmentByUUID2"
    type: "pipelet"
    ref: "GetAssignmentByUUID"
    config:
      DefaultAssignmentLookup: "com.intershop.component.pmc.internal.pagelet.SlotPageletAssignmentLookup"
    bindings:
      UUID: "PageletAssignmentUUID"
      Assignment: "PageletAssignment"
  - id: "GetAssignmentByUUID3"
    type: "pipelet"
    ref: "GetAssignmentByUUID"
    config:
      DefaultAssignmentLookup: "com.intershop.component.pmc.internal.pagelet.template.assignment.PageletPlaceholderAssignmentLookup"
    bindings:
      UUID: "PageletAssignmentUUID"
      Assignment: "PageletAssignment"
      AssignmentLookup: "Assignment"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "ContentRepository"
      UUID: "ContentRepositoryUUID"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewSlotEditing-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewPageletEntryPointEditing-Start"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewEditing-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "ApplicationState:LastSelectedMenuItem"
      OutValue_1: "SelectedMenuItem"
      InValue_2: "PageletAssignment:To:PageletAssignments(ContentRepository:RepositoryDomain)"
      OutValue_2: "SortedPageletAssignments"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "PageletAssignment:To:UUID"
      OutValue_1: "PageletEntryPointUUID"
      OutValue_2: "SelectedTab"
      InValue_2: "\"Variants\""
  - id: "Pipelet2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "PageletAssignment:To:UUID"
      OutValue_1: "SlotUUID"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "content/PageletAssignmentProperties"
      Dynamic: false

links:
  - from: "StartNode3"
    via: "next"
    to: "DispatchFormActionByBreadcrumb1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "GetAssignmentByUUID1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "GetAssignmentByUUID3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "CallNode6"
    via: "ERROR"
    to: "JoinNode1"
    into: "in2"
  - from: "DispatchFormActionByBreadcrumb1"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "CallNode17"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "DispatchFormActionByBreadcrumb2"
    into: "in"
  - from: "CallNode16"
    via: "next"
    to: "CallNode17"
    into: "in"
  - from: "DispatchFormActionByBreadcrumb2"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "CallNode16"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "DecisionNode3"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "DispatchFormActionByBreadcrumb1"
    via: "error"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "Pipelet1"
    into: "in"
  - from: "CallNode5"
    via: "FALLBACK_MODE"
    to: "JoinNode5"
    into: "in2"
  - from: "DecisionNode1"
    via: "no"
    to: "CallNode5"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "GetAssignmentByUUID2"
    into: "in"
  - from: "GetAssignmentByUUID1"
    via: "error"
    to: "GetAssignmentByUUID3"
    into: "in"
  - from: "GetAssignmentByUUID2"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "GetAssignmentByUUID3"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "GetAssignmentByUUID2"
    via: "error"
    to: "GetAssignmentByUUID1"
    into: "in"
