flow: "ViewPromotionActionAndCondition"
kind: "view"

entries:
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode11"
    name: "CreateCondition"
    mode: "private"
    strict: true
    inputs:
      - key: "Rebate"
        type: "com.intershop.component.marketing.capi.rebate.Rebate"
        required: true
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode2"
    name: "CreateAction"
    mode: "private"
    strict: true
    inputs:
      - key: "Rebate"
        type: "com.intershop.component.marketing.capi.rebate.Rebate"
        required: true
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewPromotionActionAndCondition-CreateAction"
    bindings:
      Domain: "Promotion:Domain"
  - id: "CallNode2"
    type: "call"
    ref: "ViewPromotionActionAndCondition-Prefix"
  - id: "CallNode3"
    type: "call"
    ref: "ViewPromotionActionAndCondition-CreateCondition"
    bindings:
      Domain: "Promotion:Domain"
  - id: "CreateAction1"
    type: "pipelet"
    ref: "CreateAction"
    bindings:
      Action: "RebateAction"
      Owner: "Rebate"
  - id: "CreateCondition1"
    type: "pipelet"
    ref: "CreateCondition"
    config:
      TypeGroupCondition: false
    bindings:
      ConditionDescriptorID: "\"OrderMinValueAction\""
      Owner: "Rebate"
      CurrentDomain: "Domain"
      Condition: "RebateCondition"
  - id: "Decision2"
    type: "decision"
    condition: "PromotionUUID"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Rebate:Action"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Rebate:Condition"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPromotionRebateInclusionsExclusions-ConditionInEx"
      OutValue_1: "ViewPromotionRebateInclusionsExclusions-ActionInEx"
    bindings:
      Key_0: "newConditionInEx"
      SelectionKey: "JumpTarget"
      Key_1: "newActionInEx"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "RebateCondition"
        type: "com.intershop.component.foundation.capi.condition.Condition"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "RebateAction"
        type: "com.intershop.component.foundation.capi.action.Action"
        guaranteed: true
  - id: "GetActionApplicationContext1"
    type: "pipelet"
    ref: "GetActionApplicationContext"
    bindings:
      ActionDescriptorRegistryName: "\"promotionActionDescriptorRegistry\""
      ActionRepositoryName: "\"promotionActionRepository\""
  - id: "GetActionDescriptorByID1"
    type: "pipelet"
    ref: "GetActionDescriptorByID"
    bindings:
      ActionDescriptorID: "\"FreeGiftDiscount\""
  - id: "GetConditionApplicationContext1"
    type: "pipelet"
    ref: "GetConditionApplicationContext"
    bindings:
      ConditionDescriptorRegistryName: "\"promotionConditionDescriptorRegistry\""
      ConditionRepositoryName: "\"promotionConditionRepository\""
  - id: "GetFirstElementOfIterator1"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      Iterator: "Rebate:Action"
      FirstElement: "RebateAction"
  - id: "GetFirstElementOfIterator2"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      FirstElement: "Rebate"
      Iterator: "Promotion:Rebates"
  - id: "GetPromotionByUUID2"
    type: "pipelet"
    ref: "GetPromotionByUUID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode60"
    type: "join"
  - id: "Jump7"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewPromotionActionAndCondition-Edit"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "RebateCondition"
      InValue_1: "Rebate:Condition"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/RebateActionAndCondition"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "JumpNode1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump7"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "KeyMapper1"
    into: "in"
  - from: "StartNode11"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "CreateCondition1"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "CreateCondition1"
    via: "error"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "GetConditionApplicationContext1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetFirstElementOfIterator1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "GetActionApplicationContext1"
    into: "in"
  - from: "GetPromotionByUUID2"
    via: "next"
    to: "GetFirstElementOfIterator2"
    into: "in"
  - from: "GetFirstElementOfIterator2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "JoinNode60"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "GetFirstElementOfIterator1"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode5"
    into: "in2"
  - from: "CreateAction1"
    via: "error"
    to: "EndNode4"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "CreateAction1"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "GetConditionApplicationContext1"
    via: "next"
    to: "CreateCondition1"
    into: "in"
  - from: "GetFirstElementOfIterator1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "GetActionApplicationContext1"
    via: "next"
    to: "GetActionDescriptorByID1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "GetActionDescriptorByID1"
    via: "next"
    to: "CreateAction1"
    into: "in"
  - from: "GetPromotionByUUID2"
    via: "error"
    to: "JoinNode60"
    into: "in2"
  - from: "Decision2"
    via: "no"
    to: "JoinNode60"
    into: "in1"
  - from: "Decision2"
    via: "yes"
    to: "GetPromotionByUUID2"
    into: "in"
  - from: "GetFirstElementOfIterator2"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "CallNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
