flow: "ViewProductNotification"
kind: "view"

entries:
  - id: "Start1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "CreateAlert"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "List"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "UpdateAlert"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "RemoveAlert"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "ViewAlertForm"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessUser-GetProfile"
    bindings:
      User: "CurrentUser"
  - id: "CallNode10"
    type: "call"
    ref: "ViewProductNotification-Prefix"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessUser-CheckLoggedIn"
  - id: "CallNode12"
    type: "call"
    ref: "ViewProductNotification-Prefix"
  - id: "CallNode13"
    type: "call"
    ref: "ViewProductNotification-Prefix"
  - id: "CallNode14"
    type: "call"
    ref: "ProcessProductNotification-GetNotificationByAlertUUID"
    bindings:
      Alert: "ListItem"
  - id: "CallNode15"
    type: "call"
    ref: "ProcessUser-IsProductVisibleToCurrentUser"
  - id: "CallNode16"
    type: "call"
    ref: "ProcessUser-IsProductVisibleToCurrentUser"
  - id: "CallNode17"
    type: "call"
    ref: "ProcessUser-IsProductVisibleToCurrentUser"
  - id: "CallNode2"
    type: "call"
    ref: "ViewProductNotification-Prefix"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessProductNotification-GetProduct"
    bindings:
      ProductDomain: "CurrentProductRepository:RepositoryDomain"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessProductNotification-RemoveAlert"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessProductNotification-GetProduct"
    bindings:
      ProductDomain: "CurrentProductRepository:RepositoryDomain"
  - id: "CallNode6"
    type: "call"
    ref: "ViewData-SecureForBrowserBack"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessProductNotification-GetProduct"
    bindings:
      ProductDomain: "CurrentProductRepository:RepositoryDomain"
  - id: "CallNode8"
    type: "call"
    ref: "ViewProductNotification-Prefix"
  - id: "CallNode9"
    type: "call"
    ref: "ProcessProductNotification-GetNotificationByProduct"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "AlertForm"
      FormResource: "AlertForm"
    bindings:
      Form: "AlertForm"
  - id: "CreateForm2"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "AlertForm"
      FormResource: "AlertForm"
    bindings:
      Form: "AlertForm"
  - id: "CreatePriceAlert1"
    type: "pipelet"
    ref: "CreatePriceAlert"
    bindings:
      AlertDomain: "CurrentOrganization:OwningDomain"
      AlertPrice: "AlertPrice"
      AlertProduct: "Product"
      AlertUser: "CurrentUser"
      PriceAlert: "ListItem"
  - id: "CreateStockAlert1"
    type: "pipelet"
    ref: "CreateStockAlert"
    bindings:
      AlertDomain: "CurrentOrganization:OwningDomain"
      AlertProduct: "Product"
      AlertUser: "CurrentUser"
      Alert: "ListItem"
  - id: "Decision1"
    type: "decision"
    condition: "Alert_Type"
  - id: "Decision2"
    type: "decision"
    condition: "Alert_Type"
  - id: "Decision3"
    type: "decision"
    condition: "Alert_Type"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Alert_Type"
  - id: "DecisionNode2"
    type: "decision"
    condition: "UpdateAlert"
  - id: "DecisionNode3"
    type: "decision"
    condition: "UpdateFlag"
  - id: "DecisionNode4"
    type: "decision"
    condition: "AlertUUID"
  - id: "DecisionNode5"
    type: "decision"
    condition: "ListItem"
  - id: "DecisionNode6"
    type: "decision"
    condition: "AlertUUID"
  - id: "DecisionNode7"
    type: "decision"
    condition: "AjaxRequestMarker"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProductNotification-CreateAlert"
      OutValue_1: "ViewProductNotification-UpdateAlert"
      OutValue_2: "ViewProductNotification-Login"
    bindings:
      Key_0: "submitNew"
      Key_1: "submitUpdate"
      SelectionKey: "JumpTarget"
      Key_2: "login"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "GetAlertByUUID2"
    type: "pipelet"
    ref: "GetAlertByUUID"
    bindings:
      Alert: "ListItem"
  - id: "GetAlertsByUser1"
    type: "pipelet"
    ref: "GetAlertsByUser"
    bindings:
      AlertUser: "CurrentUser"
  - id: "GetCurrencies1"
    type: "pipelet"
    ref: "GetCurrencies"
    config:
      Method: "Active Currencies"
    bindings:
      Domain: "CurrentOrganization:OrganizationDomain"
  - id: "GetCurrencies3"
    type: "pipelet"
    ref: "GetCurrencies"
    config:
      Method: "Active Currencies"
    bindings:
      Domain: "CurrentOrganization:OrganizationDomain"
  - id: "GetCurrencies4"
    type: "pipelet"
    ref: "GetCurrencies"
    config:
      Method: "Active Currencies"
    bindings:
      Domain: "CurrentOrganization:OrganizationDomain"
  - id: "GetCurrencies6"
    type: "pipelet"
    ref: "GetCurrencies"
    config:
      Method: "Active Currencies"
    bindings:
      Domain: "CurrentOrganization:OrganizationDomain"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "InteractionNode3"
    type: "interaction"
  - id: "InteractionNode4"
    type: "interaction"
  - id: "InteractionNode5"
    type: "interaction"
  - id: "InteractionNode6"
    type: "interaction"
  - id: "InteractionNode8"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewProductNotification-List"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump3"
    type: "jump"
    ref: "ViewProductNotification-List"
  - id: "Jump4"
    type: "jump"
    ref: "ViewProductNotification-List"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewPage-Start"
  - id: "JumpNode5"
    type: "jump"
    ref: "ViewProductNotification-RemoveAlert"
  - id: "JumpNode6"
    type: "jump"
    ref: "ViewUserAccount-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "CurrentRequest:PipelineDictionary"
      OutValue_1: "Dictionary"
      InValue_3: "\"systempage.account.productNotification.pagelet2-systempage.account.productNotification\""
      OutValue_3: "PageletEntryPointID"
      InValue_2: "\"comp/account/productnotification/ProductNotificationList\""
      OutValue_2: "WorkingTemplate"
  - id: "KeyMapper33"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "TargetPipeline"
      InValue_1: "\"ViewUserAccount-ShowLogin\""
      OutValue_2: "Protocol"
      InValue_2: "\"https\""
      OutValue_3: "TargetSite"
      OutValue_4: "Parameter1_Name"
      InValue_4: "\"TargetPipeline\""
      OutValue_5: "Parameter1_Value"
      InValue_5: "\"ViewProductNotification-List\""
  - id: "Pipelet1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_PRICE"
      Value: "ERROR_PRICE"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_EMailAddressInvalid"
      Value: true
      ValueType: "Dictionary Value"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "VerifyEMailAddress"
    bindings:
      EMailAddress: "AlertForm_NotificationMailAddress"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "UpdateAlert"
      Value: "\"UpdateAlert\""
  - id: "Pipelet3"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    config:
      DefaultAttributeName: "NotificationMailAddress"
      DefaultAttributeType: "String"
    bindings:
      AttributeValue: "AlertForm_NotificationMailAddress"
      ExtensibleObject: "ListItem"
      LocaleInformation: "CurrentSession:Locale"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    config:
      DefaultAttributeName: "NotificationMailAddress"
      DefaultAttributeType: "String"
    bindings:
      AttributeValue: "CurrentUser:Profile:DefaultAddress:EMail"
      ExtensibleObject: "ListItem"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "TargetURL"
      RemoveFormValues: true
  - id: "Pipelet9"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_PRICE"
      Value: "ERROR_PRICE"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_ALERT_NOT_FOUND"
      Value: true
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_ProductNotFound"
      ValueType: "Dictionary Value"
      Value: true
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewProductNotification-List"
  - id: "SetDictionaryValue5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_ProductNotFound"
      ValueType: "Dictionary Value"
      Value: true
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_ProductNotFound"
      ValueType: "Dictionary Value"
      Value: true
  - id: "SetDictionaryValue7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_ALERT_NOT_FOUND"
      Value: true
  - id: "UpdatePriceAlert1"
    type: "pipelet"
    ref: "UpdatePriceAlert"
    bindings:
      PriceAlert: "ListItem"
      Alert: "ListItem"
      AlertPrice: "AlertPrice"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "AlertForm"
  - id: "VerifyMoney1"
    type: "pipelet"
    ref: "VerifyMoney"
    bindings:
      CurrencyMnemonic: "CurrentSession:CurrencyCode"
      LocalizedString: "PriceValue"
      MoneyValue: "AlertPrice"
  - id: "VerifyMoney3"
    type: "pipelet"
    ref: "VerifyMoney"
    bindings:
      CurrencyMnemonic: "CurrentSession:CurrencyCode"
      LocalizedString: "PriceValue"
      MoneyValue: "AlertPrice"

links:
  - from: "GetAlertByUUID2"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "CallNode11"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetAlertByUUID2"
    via: "error"
    to: "SetDictionaryValue7"
    into: "in"
  - from: "SetDictionaryValue7"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "JoinNode10"
    into: "in2"
  - from: "CallNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode1"
    into: "in3"
  - from: "DecisionNode2"
    via: "yes"
    to: "ValidateForm1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "GetAlertsByUser1"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode14"
    via: "Alert"
    to: "JoinNode6"
    into: "in3"
  - from: "JoinNode4"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "VerifyMoney3"
    via: "error"
    to: "Pipelet9"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "InteractionNode5"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "VerifyMoney3"
    into: "in"
  - from: "CreateStockAlert1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "CallNode12"
    via: "next"
    to: "GetCurrencies3"
    into: "in"
  - from: "Pipelet4"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "CallNode10"
    via: "next"
    to: "GetCurrencies6"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "Pipelet10"
    via: "next"
    to: "JoinNode8"
    into: "in2"
  - from: "Pipelet9"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "Join1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "Start2"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "GetAlertsByUser1"
    via: "next"
    to: "GetCurrencies1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "InteractionNode3"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "GetCurrencies3"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Decision2"
    into: "in"
  - from: "Pipelet11"
    via: "error"
    to: "Pipelet4"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "Pipelet10"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "CreateStockAlert1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "Start3"
    via: "next"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "CreatePriceAlert1"
    via: "next"
    to: "Join2"
    into: "in3"
  - from: "Pipelet1"
    via: "next"
    to: "InteractionNode4"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "VerifyMoney1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join1"
    into: "in1"
  - from: "VerifyMoney3"
    via: "next"
    to: "CreatePriceAlert1"
    into: "in"
  - from: "Pipelet11"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "CallNode17"
    via: "NOT_VISIBLE"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "Pipelet3"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "Join5"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "CallNode1"
    via: "ERROR"
    to: "JumpNode6"
    into: "in"
  - from: "UpdatePriceAlert1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "CallNode13"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "VerifyMoney1"
    via: "next"
    to: "UpdatePriceAlert1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JumpNode5"
    into: "in"
  - from: "GetCurrencies6"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join5"
    into: "in1"
  - from: "GetCurrencies4"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "InteractionNode8"
    into: "in"
  - from: "VerifyMoney1"
    via: "error"
    to: "Pipelet1"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "InteractionNode2"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "InteractionNode6"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "CallNode14"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode4"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "CallNode9"
    via: "UNKNOWN_ALERT_TYPE"
    to: "JoinNode4"
    into: "in2"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "KeyMapper33"
    via: "next"
    to: "DecisionNode7"
    into: "in"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "ValidateForm1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CreateForm2"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "CallNode11"
    via: "NOTLOGGEDIN"
    to: "Pipelet5"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Pipelet11"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "CallNode9"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "Decision1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode16"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "error"
    to: "Jump1"
    into: "in"
  - from: "ValidateForm1"
    via: "error"
    to: "JoinNode9"
    into: "in1"
  - from: "Pipelet5"
    via: "next"
    to: "KeyMapper33"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "CallNode15"
    into: "in"
  - from: "CallNode15"
    via: "next"
    to: "GetCurrencies4"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "CallNode15"
    via: "NOT_VISIBLE"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode7"
    into: "in2"
  - from: "DecisionNode3"
    via: "no"
    to: "Jump3"
    into: "in"
  - from: "CallNode14"
    via: "ERROR_ALERT_NOT_FOUND"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode16"
    via: "next"
    to: "CreateForm2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "GetAlertByUUID2"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "Join4"
    into: "in1"
  - from: "JoinNode9"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Join4"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "CallNode17"
    into: "in"
  - from: "CallNode16"
    via: "NOT_VISIBLE"
    to: "SetDictionaryValue5"
    into: "in"
  - from: "GetCurrencies1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "SetDictionaryValue5"
    via: "next"
    to: "JoinNode9"
    into: "in2"
  - from: "CallNode17"
    via: "next"
    to: "DecisionNode5"
    into: "in"
