flow: "ViewPromotionTargetGroup"
kind: "view"

entries:
  - id: "Start10"
    name: "Back"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "ShowAll"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "ConcatenateStrings2"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "ViewPromotionTargetGroup_"
      DefaultString2: "-ShowAll"
    bindings:
      String0: "null"
      String1: "CurrentChannel:TypeCode"
      String2: "null"
      Concatenated: "ViewPromotionTargetGroup_XX-ShowAll"
  - id: "Decision2"
    type: "decision"
    condition: "PromotionUUID"
  - id: "Decision3"
    type: "decision"
    condition: "Promotion"
  - id: "End1"
    type: "end"
    strict: false
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "PromotionList"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocatorName: "null"
  - id: "Join3"
    type: "join"
  - id: "Jump5"
    type: "jump"
  - id: "Jump6"
    type: "jump"
    ref: "ViewPromotionList-ListAll"
  - id: "JumpNode1"
    type: "jump"
  - id: "Pipelet12"
    type: "pipelet"
    ref: "GetPromotionByUUID"

links:
  - from: "Decision3"
    via: "no"
    to: "Join3"
    into: "in3"
  - from: "GetPageLocator1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "ConcatenateStrings2"
    into: "in"
  - from: "ConcatenateStrings2"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Pipelet12"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "Decision2"
    via: "yes"
    to: "Pipelet12"
    into: "in"
  - from: "Pipelet12"
    via: "next"
    to: "Join3"
    into: "in2"
  - from: "Start2"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "Decision2"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join3"
    into: "in1"
  - from: "Start10"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "GetPageLocator1"
    via: "error"
    to: "Jump6"
    into: "in"
