flow: "ViewChannelMap"
kind: "view"

entries:
  - id: "Start1"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Expand"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Collapse"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "GetContentChannels"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "GetConsumerChannels"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "GetBuisnessChannels"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "GetPartnerChannels"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "GetSupplierChannels"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "GetOrgs"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "GetOrgsChannelTypes"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewChannelMap-GetOrgsChannelTypes"
  - id: "CallNode2"
    type: "call"
    ref: "ViewChannelMap-GetContentChannels"
  - id: "CallNode3"
    type: "call"
    ref: "ViewChannelMap-GetConsumerChannels"
  - id: "CallNode4"
    type: "call"
    ref: "ViewChannelMap-GetBuisnessChannels"
  - id: "CallNode5"
    type: "call"
    ref: "ViewChannelMap-GetPartnerChannels"
  - id: "CallNode6"
    type: "call"
    ref: "ViewChannelMap-GetSupplierChannels"
  - id: "CallNode7"
    type: "call"
    ref: "ViewChannelMap-GetOrgs"
  - id: "CallNode8"
    type: "call"
    ref: "ViewChannelMap-GetOrgsChannelTypes"
  - id: "Decision1"
    type: "decision"
    condition: "ExpandedChannelMap"
  - id: "Decision2"
    type: "decision"
    condition: "OrgChannels"
  - id: "DecisionNode1"
    type: "decision"
    condition: "NewOrgs"
  - id: "DecisionNode10"
    type: "decision"
    condition: "HomeInclude"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Channels"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Channels"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Channels"
  - id: "DecisionNode5"
    type: "decision"
    condition: "Channels"
  - id: "DecisionNode6"
    type: "decision"
    condition: "Channels"
  - id: "DecisionNode7"
    type: "decision"
    condition: "NewOrgIt"
  - id: "DecisionNode8"
    type: "decision"
    condition: "HomeInclude"
  - id: "DecisionNode9"
    type: "decision"
    condition: "CurrentStartNodeName"
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "EndNode5"
    type: "end"
    strict: false
  - id: "EndNode6"
    type: "end"
    strict: false
  - id: "EndNode7"
    type: "end"
    strict: false
  - id: "EndNode8"
    type: "end"
    strict: false
  - id: "ExchangeSessionObject1"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ExpandedChannelMap"
    bindings:
      LoadObject: "ExpandedChannelMap"
  - id: "ExchangeSessionObject2"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ExpandedChannelMap"
    bindings:
      LoadObject: "ExpandedChannelMap"
  - id: "ExchangeSessionObject3"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "ExpandedChannelMap"
    bindings:
      LoadObject: "ExpandedChannelMap"
      SaveObject: "ExpandedChannelMap"
  - id: "ExchangeSessionObject4"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ExpandedChannelMap"
    bindings:
      LoadObject: "ExpandedChannelMap"
  - id: "ExchangeSessionObject5"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "ExpandedChannelMap"
    bindings:
      LoadObject: "ExpandedChannelMap"
      SaveObject: "ExpandedChannelMap"
  - id: "GetRepositories1"
    type: "pipelet"
    ref: "GetRepositories"
    config:
      CustomRepositoryTypeCode: 62
    bindings:
      OrganizationDomain: "Org:Domain"
      Repositories: "Channels"
  - id: "GetRepositories2"
    type: "pipelet"
    ref: "GetRepositories"
    config:
      CustomRepositoryTypeCode: 52
    bindings:
      OrganizationDomain: "Org:Domain"
      Repositories: "Channels"
  - id: "GetRepositories3"
    type: "pipelet"
    ref: "GetRepositories"
    config:
      CustomRepositoryTypeCode: 42
    bindings:
      OrganizationDomain: "Org:Domain"
      Repositories: "Channels"
  - id: "GetRepositories4"
    type: "pipelet"
    ref: "GetRepositories"
    config:
      CustomRepositoryTypeCode: 32
    bindings:
      OrganizationDomain: "Org:Domain"
      Repositories: "Channels"
  - id: "GetRepositories5"
    type: "pipelet"
    ref: "GetRepositories"
    config:
      CustomRepositoryTypeCode: 1
    bindings:
      OrganizationDomain: "Org:Domain"
      Repositories: "Channels"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewApplication-DisplayWelcomePageKeepState"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "OrgChannels"
      OutMap: "OrgChannels"
      Value: "Channels"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Key"
      Value: 1
  - id: "Pipelet11"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "ChannelOrgs"
      Key: "OrgChannel:UUID"
      OutMap: "ChannelOrgs"
      Value: "NewOrgs"
  - id: "Pipelet12"
    type: "pipelet"
    ref: "GetOrganizations"
    bindings:
      Organizations: "NewOrgs"
      Owner: "OrgChannel:Domain"
  - id: "Pipelet13"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "OrgsChannelTypes"
      Key: "Org:UUID"
      OutMap: "OrgsChannelTypes"
      Value: "OrgChannels"
  - id: "Pipelet14"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      Iterator: "Orgs"
      Object: "CurrentOrganization"
      InVector: "null"
      Objects: "null"
      OutVector: "null"
  - id: "Pipelet15"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      InVector: "NewOrgList"
      Iterator: "NewOrgIt"
      Objects: "NewOrgs"
      OutVector: "NewOrgList"
  - id: "Pipelet16"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "NewOrgIt"
      OutValue_1: "Orgs"
  - id: "Pipelet17"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "NewOrgList"
      RemoveFormValues: false
  - id: "Pipelet18"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "NewOrgIt"
      RemoveFormValues: false
  - id: "Pipelet19"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "OrgChannels"
      RemoveFormValues: false
  - id: "Pipelet2"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "OrgChannels"
      OutMap: "OrgChannels"
      Value: "Channels"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "OrgChannels"
      OutMap: "OrgChannels"
      Value: "Channels"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "OrgChannels"
      OutMap: "OrgChannels"
      Value: "Channels"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "OrgChannels"
      OutMap: "OrgChannels"
      Value: "Channels"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Key"
      Value: 62
  - id: "Pipelet7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Key"
      Value: 52
  - id: "Pipelet8"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Key"
      Value: 42
  - id: "Pipelet9"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Key"
      Value: 32
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelMap"
      WorkingTemplate: "channel/ChannelMap"
  - id: "SortIteratorByComparator1"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingAttribute: "DisplayName"
      DefaultSortingOrder: true
    bindings:
      Iterator: "Channels"
      SortedIterator: "Channels"
  - id: "SortIteratorByComparator2"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingAttribute: "DisplayName"
      DefaultSortingOrder: true
    bindings:
      Iterator: "Channels"
      SortedIterator: "Channels"
  - id: "SortIteratorByComparator3"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingAttribute: "DisplayName"
      DefaultSortingOrder: true
    bindings:
      Iterator: "Channels"
      SortedIterator: "Channels"
  - id: "SortIteratorByComparator4"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingAttribute: "DisplayName"
      DefaultSortingOrder: true
    bindings:
      Iterator: "Channels"
      SortedIterator: "Channels"
  - id: "SortIteratorByComparator5"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingAttribute: "DisplayName"
      DefaultSortingOrder: true
    bindings:
      Iterator: "Channels"
      SortedIterator: "Channels"
  - id: "UpdateMapping1"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ExpandedChannelMap"
      Key: "ExpandedOrganizationUUID"
      OutMap: "ExpandedChannelMap"
      Value: "ExpandedOrganizationUUID"
      Keys: "null"
      Values: "null"
  - id: "UpdateMapping2"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Remove"
    bindings:
      InMap: "ExpandedChannelMap"
      Key: "ExpandedOrganizationUUID"
      OutMap: "ExpandedChannelMap"
      Value: "ExpandedOrganizationUUID"
      Keys: "null"
      Values: "null"
  - id: "UpdateMapping3"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ExpandedChannelMap"
      Key: "CurrentOrganization:UUID"
      OutMap: "ExpandedChannelMap"
      Value: "CurrentOrganization:UUID"
      Keys: "null"
      Values: "null"

links:
  - from: "Start1"
    via: "next"
    to: "ExchangeSessionObject4"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Start3"
    via: "next"
    to: "ExchangeSessionObject1"
    into: "in"
  - from: "Pipelet15"
    via: "next"
    to: "Pipelet11"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "GetRepositories1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "Pipelet19"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "GetRepositories2"
    into: "in"
  - from: "Pipelet18"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join3"
    into: "in2"
  - from: "UpdateMapping3"
    via: "next"
    to: "ExchangeSessionObject3"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "Pipelet13"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode6"
    into: "in2"
  - from: "StartNode8"
    via: "next"
    to: "Pipelet17"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "GetRepositories2"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "GetRepositories5"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "Pipelet16"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Pipelet14"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "SortIteratorByComparator1"
    into: "in"
  - from: "ExchangeSessionObject1"
    via: "next"
    to: "UpdateMapping1"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "SortIteratorByComparator5"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode7"
    via: "no"
    to: "JoinNode7"
    into: "in2"
  - from: "Start4"
    via: "next"
    to: "ExchangeSessionObject2"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "ExchangeSessionObject5"
    into: "in"
  - from: "Pipelet9"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "DecisionNode9"
    via: "no"
    to: "JumpNode2"
    into: "in"
  - from: "UpdateMapping2"
    via: "next"
    to: "Join2"
    into: "in3"
  - from: "CallNode4"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "SortIteratorByComparator2"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode5"
    into: "in2"
  - from: "LoopNode2"
    via: "do"
    to: "CallNode2"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode3"
    into: "in2"
  - from: "Decision1"
    via: "yes"
    to: "UpdateMapping3"
    into: "in"
  - from: "SortIteratorByComparator2"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode4"
    into: "in2"
  - from: "JoinNode6"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "Pipelet7"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "DecisionNode7"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "Pipelet12"
    into: "in"
  - from: "Pipelet10"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet12"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Pipelet14"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "GetRepositories3"
    into: "in"
  - from: "UpdateMapping1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "CallNode5"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "Pipelet13"
    via: "next"
    to: "Pipelet19"
    into: "in"
  - from: "ExchangeSessionObject5"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Pipelet17"
    via: "next"
    to: "Pipelet18"
    into: "in"
  - from: "GetRepositories3"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet15"
    into: "in"
  - from: "SortIteratorByComparator3"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "SortIteratorByComparator3"
    into: "in"
  - from: "ExchangeSessionObject2"
    via: "next"
    to: "UpdateMapping2"
    into: "in"
  - from: "SortIteratorByComparator4"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetRepositories1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "GetRepositories4"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "GetRepositories4"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "SortIteratorByComparator5"
    via: "next"
    to: "Pipelet10"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join4"
    into: "in3"
  - from: "DecisionNode5"
    via: "yes"
    to: "SortIteratorByComparator4"
    into: "in"
  - from: "ExchangeSessionObject3"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "CallNode7"
    via: "next"
    to: "Pipelet9"
    into: "in"
  - from: "Pipelet11"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Pipelet5"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "StartNode7"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "SortIteratorByComparator1"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "ExchangeSessionObject4"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "Pipelet16"
    into: "in"
  - from: "GetRepositories5"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "DecisionNode8"
    into: "in"
  - from: "DecisionNode10"
    via: "no"
    to: "JoinNode8"
    into: "in2"
  - from: "DecisionNode8"
    via: "no"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode9"
    via: "yes"
    to: "InteractionEnd1"
    into: "in"
  - from: "DecisionNode8"
    via: "yes"
    to: "DecisionNode10"
    into: "in"
  - from: "DecisionNode10"
    via: "yes"
    to: "DecisionNode9"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
