flow: "ViewContentProcessingWizardCreateLabelAssignment"
kind: "view"

entries:
  - id: "Start1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode14"
    name: "SelectLabel"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "GetLabelsDomain"
    mode: "private"
    strict: true
    inputs:
      - key: "ContentRepositoryUUID"
        type: "java.lang.String"
        required: true
      - key: "CurrentMasterRepository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
      - key: "CurrentOrganization"
        type: "com.intershop.component.organization.capi.Organization"
        required: false
  - id: "StartNode20"
    name: "DispatchByBreadcrumb"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "ProcessValuesInContainer"
    mode: "private"
    strict: true
    inputs:
      - key: "ContentRepositoryUUID"
        type: "java.lang.String"
        required: false
      - key: "PageableID"
        type: "java.lang.String"
        required: false
      - key: "SelectedObjects"
        type: "java.lang.String"
        required: false
      - key: "LabelUUID"
        type: "java.lang.String"
        required: false
      - key: "ContextObject"
        type: "java.lang.String"
        required: false
  - id: "StartNode4"
    name: "AddLabel"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "BackToSelectLabel"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "Finish"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "RemoveContainer"
    mode: "private"
    strict: true
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewContentProcessingWizardCreateLabelAssignment-RemoveContainer"
  - id: "CallNode10"
    type: "call"
    ref: "ViewContentProcessingWizardCreateLabelAssignment-ProcessValuesInContainer"
  - id: "CallNode13"
    type: "call"
    ref: "ProcessLabel-GetLabelsByDomain"
    bindings:
      Domain: "LabelsDomain"
  - id: "CallNode2"
    type: "call"
    ref: "ViewContentProcessingWizardCreateLabelAssignment-GetLabelsDomain"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessContentWizard-GetSelectedMenuItem"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessLabel-Create"
    bindings:
      Domain: "LabelsDomain"
      User: "CurrentUser"
  - id: "CallNode6"
    type: "call"
    ref: "ViewContentProcessingWizardCreateLabelAssignment-GetLabelsDomain"
  - id: "CallNode7"
    type: "call"
    ref: "ViewContentProcessingWizardCreateLabelAssignment-ProcessValuesInContainer"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessContentWizard-GetSelectedMenuItem"
  - id: "CallNode9"
    type: "call"
    ref: "ViewContentProcessingWizardCreateLabelAssignment-ProcessValuesInContainer"
  - id: "CreateIteratorFromPageable1"
    type: "pipelet"
    ref: "CreateIteratorFromPageable"
    bindings:
      PageableIterator: "Labels"
      ResettableIterator: "Labels"
  - id: "DecisionNode1"
    type: "decision"
    condition: "LabelUUID"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ContentRepository:RepositoryDomain:DomainID"
  - id: "DecisionNode6"
    type: "decision"
    condition: "LabelName"
  - id: "DispatchFormAction3"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "This:Finish"
      OutValue_1: "This:AddLabel"
      OutValue_2: "This:DispatchByBreadcrumb"
      OutValue_3: "This:DispatchByBreadcrumb"
    bindings:
      Key_0: "finishAssignLabels"
      Key_1: "addLabel"
      Key_2: "cancel"
      Key_3: "previous"
      SelectionKey: "JumpTarget"
  - id: "DispatchFormActionByBreadcrumb1"
    type: "pipelet"
    ref: "DispatchFormActionByBreadcrumb"
    config:
      SplitMode: "PipelineAndParameter"
    bindings:
      Key_0: "cancel"
      OutValue_0: "ApplicationState:LastListView"
      OutValue_1: "ApplicationState:LastButOneBreadcrumb"
      Key_1: "previous"
      SelectionKey: "JumpTarget"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "LabelsDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "PageableID"
        type: "java.lang.String"
        guaranteed: false
      - key: "ContentRepositoryUUID"
        type: "java.lang.String"
        guaranteed: false
      - key: "SelectedObjects"
        type: "java.lang.String"
        guaranteed: false
      - key: "LabelUUID"
        type: "java.lang.String"
        guaranteed: false
      - key: "ContextObject"
        type: "java.lang.String"
        guaranteed: false
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetRepositoryByUUID2"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      UUID: "ContentRepositoryUUID"
      Repository: "ContentRepository"
  - id: "GetValuesFromContainer1"
    type: "pipelet"
    ref: "GetValuesFromContainer"
    config:
      OverwriteBehavior: false
    bindings:
      ContainerName: "\"Container_ContentProcessingLabels\""
  - id: "InteractionEnd4"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "Error-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ProcessContentWizard-CreateProcess"
  - id: "JumpNode4"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode6"
    type: "jump"
    ref: "This:SelectLabel"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "Label:UUID"
      OutValue_1: "LabelID"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentOrganization:OrganizationDomain"
      OutValue_1: "LabelsDomain"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ContentRepository:RepositoryDomain"
      OutValue_1: "LabelsDomain"
  - id: "KeyMapper6"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "\"BatchProcessContentLabelAssignments-AssignLabel\""
      InValue_2: "\"BatchProcessContentLabelAssignments-InitAssignLabel\""
      InValue_3: "\"BatchProcessContentLabelAssignments-PostAssignLabel\""
      InValue_4: "\"MasterContent\""
      InValue_5: "\"MasterContent\""
      OutValue_1: "ProcessPipeline"
      OutValue_2: "InitPipeline"
      OutValue_3: "PostPipeline"
      OutValue_4: "JobName"
      OutValue_5: "JobNamePrefix"
  - id: "PrepareApplicationView4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "content/wizard/ContentProcessingSelectLabel"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      RemoveFormValues: true
      Key: "LabelName"
  - id: "RemoveDictionaryValue2"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      RemoveFormValues: true
      Key: "LabelDisplayName"
  - id: "RemoveValuesContainer2"
    type: "pipelet"
    ref: "RemoveValuesContainer"
    bindings:
      ContainerName: "\"Container_ContentProcessingLabels\""
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: "NoLabelName"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: "NoElements"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: "LabelExists"
  - id: "SetValuesToContainer1"
    type: "pipelet"
    ref: "SetValuesToContainer"
    bindings:
      ContainerName: "\"Container_ContentProcessingLabels\""
      DictionaryKeys: "\"ContentRepositoryUUID;PageableID;SelectedObjects;LabelUUID;ContextObject\""
  - id: "TextNode2"
    type: "text"

links:
  - from: "CallNode10"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "CreateIteratorFromPageable1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "PrepareApplicationView4"
    into: "in"
  - from: "CallNode5"
    via: "Error"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "KeyMapper6"
    into: "in"
  - from: "CreateIteratorFromPageable1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode9"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "KeyMapper3"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "KeyMapper2"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "GetLocale1"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "DispatchFormAction3"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "DispatchFormActionByBreadcrumb1"
    via: "error"
    to: "JumpNode1"
    into: "in"
  - from: "DispatchFormActionByBreadcrumb1"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "GetRepositoryByUUID2"
    via: "error"
    to: "EndNode1"
    into: "in"
  - from: "GetRepositoryByUUID2"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "GetValuesFromContainer1"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "GetValuesFromContainer1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "SetValuesToContainer1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JumpNode6"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "KeyMapper3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "KeyMapper6"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "PrepareApplicationView4"
    via: "next"
    to: "InteractionEnd4"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "RemoveDictionaryValue2"
    into: "in"
  - from: "RemoveDictionaryValue2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "RemoveValuesContainer2"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "SetValuesToContainer1"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "DispatchFormAction3"
    into: "in"
  - from: "StartNode14"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode20"
    via: "next"
    to: "DispatchFormActionByBreadcrumb1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetRepositoryByUUID2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetValuesFromContainer1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "StartNode6"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "RemoveValuesContainer2"
    into: "in"
