flow: "ViewPromotionCodeGroupTargetPromotionSelection"
kind: "view"

entries:
  - id: "Start2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Create"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "ShowAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "ParametricSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "GetUnselectablePromotions"
    mode: "private"
    strict: true
    inputs:
      - key: "Promotions"
        type: "java.util.Iterator"
        required: true
      - key: "PromotionCodeGroup"
        type: "com.intershop.component.marketing.capi.code.PromotionCodeGroup"
        required: true
  - id: "StartNode6"
    name: "Sort"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddEntryToMap1"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      OutMap: "PromotionsWithoutCodes"
      InMap: "PromotionsWithoutCodes"
      Key: "Promotion:UUID"
      Value: "Promotion"
      Keys: "PromotionsWithoutCodesKeys"
  - id: "AddEntryToMap2"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      OutMap: "AlreadyAssignedPromotions"
      InMap: "AlreadyAssignedPromotions"
      Key: "Promotion:UUID"
      Value: "Promotion"
      Keys: "AlreadyAssignedPromotionsKeys"
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      Objects: "PromotionCodeGroup:Promotions"
      OutVector: "AssignedPromotions"
      InVector: "null"
      Object: "null"
      Iterator: "AssignedPromotionsIt"
  - id: "Call1"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call7"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessPromotionSearch-ProcessListAll"
  - id: "CallNode10"
    type: "call"
    ref: "ProcessPromotionSearch-ProcessParametricSearch"
  - id: "CallNode14"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "CallNode15"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "CallNode16"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "CallNode2"
    type: "call"
    ref: "ViewPromotionCodeGroupTargetPromotionSelection-Prefix"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessPromotionCodeGroup-Assign"
  - id: "CallNode4"
    type: "call"
    ref: "ViewPromotionCodeGroupTargetPromotionSelection-GetUnselectablePromotions"
    bindings:
      PromotionsWithoutCodes: "NotSelectablePromotionsMap"
      PromotionsWithoutCodesKeys: "NotSelectablePromotionsMapKeys"
      AlreadyAssignedPromotionsKeys: "AlreadyAssignedPromotionsMapKeys"
      AlreadyAssignedPromotions: "AlreadyAssignedPromotionsMap"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessPromotion-GetPromotionDomainByChannel"
    bindings:
      Channel: "CurrentChannel"
      PromotionDomain: "Domain"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessPromotionSearch-ProcessPaging"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessPromotionSearch-ProcessSort"
  - id: "CallNode9"
    type: "call"
    ref: "ViewPromotionCodeGroupTargetPromotionSelection-Prefix"
  - id: "CheckForEmptyIterator1"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "SelectedObjectUUIDs"
  - id: "ContainsElement1"
    type: "pipelet"
    ref: "ContainsElement"
    bindings:
      Collection: "AssignedPromotions"
      Element: "Promotion"
  - id: "Decision4"
    type: "decision"
    condition: "PromotionCodeGroupID"
  - id: "Decision5"
    type: "decision"
    condition: "PromotionCodeGroup"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Promotion:CouponCodeRequired"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Promotion:UseSingleCode"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPromotionCodeGroup-Edit"
      PagingPipeline: "ViewPromotionCodeGroupTargetPromotionSelection-Paging"
      OutValue_1: "ViewPromotionCodeGroupTargetPromotionSelection-Create"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "cancel"
      Key_1: "assign"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "PromotionsWithoutCodes"
        type: "java.util.Map"
        guaranteed: false
      - key: "PromotionsWithoutCodesKeys"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "AlreadyAssignedPromotionsKeys"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "AlreadyAssignedPromotions"
        type: "java.util.Map"
        guaranteed: false
  - id: "GetPageLocator11"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "PromotionList"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocatorName: "null"
  - id: "GetPromotionByUUID1"
    type: "pipelet"
    ref: "GetPromotionByUUID"
  - id: "GetPromotionCodeGroupByID1"
    type: "pipelet"
    ref: "GetPromotionCodeGroupByID"
    bindings:
      GroupID: "PromotionCodeGroupID"
  - id: "GetPromotionCodeGroupByID3"
    type: "pipelet"
    ref: "GetPromotionCodeGroupByID"
    bindings:
      GroupID: "PromotionCodeGroupID"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode18"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump22"
    type: "jump"
    ref: "ViewPromotionCodeGroupTargetPromotionSelection-Paging"
  - id: "Jump6"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewPromotionCodeGroup-Edit"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewPromotion-Edit"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "CurrentPageNumber"
      OutValue_1: "PageNumber"
  - id: "Loop1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/PromotionCodeGroupTargetPromotionSelect"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"
  - id: "RemovePageLocator1"
    type: "pipelet"
    ref: "RemovePageLocator"
    config:
      DefaultPageLocatorName: "PromotionList"
  - id: "SetPageLocator2"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultPageLocatorName: "PromotionList"
      DefaultHandlerPipeline: "ViewPromotionCodeGroupTargetPromotions-Paging"
    bindings:
      Pageable: "Promotions"
      PageLocatorName: "null"
      HandlerPipeline: "null"

links:
  - from: "StartNode8"
    via: "next"
    to: "GetPageLocator11"
    into: "in"
  - from: "RemovePageLocator1"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode18"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode11"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetPromotionByUUID1"
    into: "in"
  - from: "GetPromotionCodeGroupByID3"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "StartNode5"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "AddEntryToMap1"
    into: "in"
  - from: "GetPromotionByUUID1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "JoinNode14"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "CallNode7"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "LoopNode2"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "SetPageLocator2"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump6"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "StartNode2"
    via: "next"
    to: "CallNode15"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "Jump22"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "JoinNode4"
    into: "in3"
  - from: "CallNode2"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "error"
    to: "KeyMapper2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "DecisionNode2"
    into: "in"
  - from: "AddEntryToMap1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "CallNode9"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "SetPageLocator2"
    into: "in"
  - from: "GetPromotionByUUID1"
    via: "error"
    to: "JoinNode2"
    into: "in3"
  - from: "GetPromotionCodeGroupByID1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "ContainsElement1"
    into: "in"
  - from: "CallNode14"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "ContainsElement1"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "ContainsElement1"
    via: "next"
    to: "AddEntryToMap2"
    into: "in"
  - from: "AddEntryToMap2"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "GetPromotionCodeGroupByID3"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Decision5"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "CheckForEmptyIterator1"
    via: "next"
    to: "GetPromotionCodeGroupByID3"
    into: "in"
  - from: "GetPageLocator11"
    via: "next"
    to: "RemovePageLocator1"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "JoinNode8"
    into: "in2"
  - from: "CallNode10"
    via: "next"
    to: "JoinNode14"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode7"
    into: "in2"
  - from: "Decision4"
    via: "no"
    to: "JoinNode18"
    into: "in1"
  - from: "Call1"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode16"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "Decision4"
    via: "yes"
    to: "CallNode6"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "GetPageLocator11"
    via: "error"
    to: "JoinNode11"
    into: "in1"
  - from: "Call7"
    via: "next"
    to: "CheckForEmptyIterator1"
    into: "in"
  - from: "Decision5"
    via: "yes"
    to: "Decision4"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Decision5"
    into: "in"
  - from: "GetPromotionCodeGroupByID1"
    via: "error"
    to: "JoinNode18"
    into: "in1"
  - from: "CallNode6"
    via: "next"
    to: "GetPromotionCodeGroupByID1"
    into: "in"
  - from: "CallNode16"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "CallNode15"
    via: "next"
    to: "CallNode10"
    into: "in"
