flow: "ViewOrderExportLineItems"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode12"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "CreateForm"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewOrderExport-Prefix"
  - id: "CallNode10"
    type: "call"
    ref: "ViewOrderExport-Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "ViewOrderExportLineItems-CreateForm"
    bindings:
      CurrentDomain: "CurrentOrganization:OrganizationDomain"
  - id: "CallNode5"
    type: "call"
    ref: "ViewOrderExportLineItems-CreateForm"
    bindings:
      CurrentDomain: "CurrentOrganization:OrganizationDomain"
  - id: "CreateForm2"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "OrderExportLineItems"
      FormResource: "OrderExport"
    bindings:
      CurrentDomain: "CurrentDomain"
      Form: "Form"
      FormAlias: "null"
      FormName: "null"
      FormResource: "null"
      Locale: "null"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "Form"
        type: "com.intershop.beehive.core.capi.webform.Form"
        guaranteed: true
      - key: "AttributeGroup"
        type: "com.intershop.component.foundation.capi.attributegroup.AttributeGroup"
        guaranteed: false
  - id: "GetAttributeGroupByID2"
    type: "pipelet"
    ref: "GetAttributeGroupByID"
    bindings:
      Domain: "CurrentDomain"
      ID: "\"ORDER_REQUIRED_ATTRIBUTES\""
      AttributeGroup: "AttributeGroup"
  - id: "InteractionNode7"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewOrderExportLineItems-Edit"
  - id: "JumpNode4"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "LoopNode3"
    type: "loop"
  - id: "MapFormToObject1"
    type: "pipelet"
    ref: "MapFormToObject"
    config:
      NameFilterType: "exclude"
      NameFilterList: "SKUs, SupplierNames"
    bindings:
      TargetObject: "Config:LineItemConditions:OrderRequiredAVs(\"orderRequiredAV_\")"
      NameFilterList: "null"
      Locale: "null"
  - id: "MapFormToObject3"
    type: "pipelet"
    ref: "MapFormToObject"
    config:
      NameFilterType: "include"
      NameFilterList: "SKUs, SupplierNames"
    bindings:
      TargetObject: "Config:LineItemConditions"
      NameFilterList: "null"
      Locale: "null"
  - id: "MapObjectToForm1"
    type: "pipelet"
    ref: "MapObjectToForm"
    config:
      NameFilterType: "include"
      NameFilterList: "SKUs, SupplierNames"
    bindings:
      SourceObject: "Config:LineItemConditions"
      Locale: "null"
      NameFilterList: "null"
  - id: "MapObjectToForm2"
    type: "pipelet"
    ref: "MapObjectToForm"
    config:
      NameFilterType: "exclude"
      NameFilterList: "SKUs, SupplierNames"
    bindings:
      SourceObject: "Config:LineItemConditions:OrderRequiredAVs(\"orderRequiredAV_\")"
      Locale: "null"
      NameFilterList: "null"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "AddFormParameterDefinition"
    config:
      Type: "java.lang.String"
      Optional: true
    bindings:
      Name: "ParameterName"
      FormatProperties: "null"
      Formatter: "null"
      MessageID: "null"
      Optional: "null"
      Type: "null"
      ValidateProperties: "null"
      Validator: "null"
  - id: "Pipelet13"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "orderRequiredAV_"
    bindings:
      Concatenated: "ParameterName"
      String1: "Descriptor:ID"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewOrderExportLineItems-Update"
      OutValue_1: "ViewOrderExportLineItems-Edit"
    bindings:
      Key_0: "update"
      SelectionKey: "JumpTarget"
      Key_1: "reset"
  - id: "PrepareApplicationView7"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "order/OrderExportLineItems"
      SelectedMenuItem: "Orders"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "Form"

links:
  - from: "Pipelet13"
    via: "next"
    to: "Pipelet10"
    into: "in"
  - from: "StartNode12"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "PrepareApplicationView7"
    into: "in"
  - from: "GetAttributeGroupByID2"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "Pipelet2"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "MapFormToObject1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "CreateForm2"
    via: "next"
    to: "GetAttributeGroupByID2"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "LoopNode3"
    via: "do"
    to: "Pipelet13"
    into: "in"
  - from: "ValidateForm1"
    via: "next"
    to: "MapFormToObject3"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "MapFormToObject3"
    via: "next"
    to: "MapFormToObject1"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "MapObjectToForm2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "ValidateForm1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "LoopNode3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "MapObjectToForm1"
    into: "in"
  - from: "PrepareApplicationView7"
    via: "next"
    to: "InteractionNode7"
    into: "in"
  - from: "GetAttributeGroupByID2"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "Pipelet10"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "MapObjectToForm1"
    via: "next"
    to: "MapObjectToForm2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CreateForm2"
    into: "in"
