flow: "ViewChangedProducts_52"
kind: "view"

entries:
  - id: "Start1"
    name: "UpdateClipboard"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start11"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start12"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Compare"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Iterator: "ParentRepositories"
      Object: "ParentRepository"
  - id: "Call1"
    type: "call"
    ref: "ViewChangedProducts_52-UpdateClipboard"
  - id: "Call16"
    type: "call"
    ref: "GetSyncProducts-ByRepositories"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessProductHistory-CompareSnapShots"
  - id: "CreatePriceDefinitionSnapShotFromProduct1"
    type: "pipelet"
    ref: "CreatePriceDefinitionSnapShotFromProduct"
    bindings:
      Product: "Product:OfferedProduct"
  - id: "CreatePriceDefinitionSnapShotFromProduct2"
    type: "pipelet"
    ref: "CreatePriceDefinitionSnapShotFromProduct"
  - id: "CreateProductIdentifierLookupHelper1"
    type: "pipelet"
    ref: "CreateProductIdentifierLookupHelper"
    config:
      LookupType: "ProductDomainLookup"
    bindings:
      ProductDomain: "CurrentProductRepository:RepositoryDomain"
  - id: "CreateProductSnapShotFromProduct1"
    type: "pipelet"
    ref: "CreateProductSnapShotFromProduct"
    bindings:
      Product: "Product:OfferedProduct"
      ProductSnapShot: "NewProductSnapShot"
  - id: "CreateProductSnapShotFromProduct2"
    type: "pipelet"
    ref: "CreateProductSnapShotFromProduct"
    bindings:
      ProductSnapShot: "OldProductSnapShot"
  - id: "Decision2"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision8"
    type: "decision"
    condition: "PageLocator"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChangedProducts_52-Paging"
      OutValue_1: "ViewSynchronization_52-Overview"
      OutValue_2: "ViewChangedProducts_52-Paging"
      PagingPipeline: "ViewChangedProducts_52-Paging"
    bindings:
      Key_0: "UpdateProductSelection"
      Key_1: "back"
      Key_2: "backFromDifferences"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
  - id: "GetClipboard1"
    type: "pipelet"
    ref: "GetClipboard"
    config:
      SetFormValues: "No"
    bindings:
      SessionRegistrationID: "RepositoryUUID"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedProductUUID"
    bindings:
      Selection: "SelectedProductUUIDIterator"
  - id: "GetFormSelection2"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "ProductUUID"
    bindings:
      Selection: "ProductUUIDIterator"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ChangedProductList"
      RestorePageLocatorDictionary: "False"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Products"
      PageableID: "PageLocator:PageableID"
  - id: "GetProductByUUID1"
    type: "pipelet"
    ref: "GetProductByUUID"
    bindings:
      ProductUUID: "ProductID"
      ProductDomain: "CurrentProductRepository:RepositoryDomain"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "Repository"
      UUID: "RepositoryUUID"
  - id: "GetRepositoryByUUID2"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "Repository"
      UUID: "RepositoryUUID"
  - id: "GetRepositoryByUUID6"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "ParentRepository"
      UUID: "RepositoryUUID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "Join18"
    type: "join"
  - id: "Join19"
    type: "join"
  - id: "Join20"
    type: "join"
  - id: "Join21"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Jump7"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump8"
    type: "jump"
    ref: "ViewChangedProducts_52-ListAll"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewChangedProducts_52-ListAll"
  - id: "KeyMapper10"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentChannel"
      OutValue_1: "Repository"
  - id: "KeyMapper9"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_2: "Repository"
      InValue_3: "ParentRepository"
      OutValue_2: "ChannelRepository"
      OutValue_3: "Repository"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "Pipelet34"
    type: "pipelet"
    ref: "GetTaxClasses"
    bindings:
      Domain: "OrganizationDomain"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/SynchronizationProductDifferences_52"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/SynchronizationProductList_52"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Products"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Products"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewChangedProducts_52-Paging"
      DefaultPageLocatorName: "ChangedProductList"
    bindings:
      Pageable: "Products"
  - id: "UpdateClipboard1"
    type: "pipelet"
    ref: "UpdateClipboard"
    config:
      StoreFormValues: "No"
    bindings:
      AllObjectUUIDs: "ProductUUIDIterator"
      SelectedObjectUUIDs: "SelectedProductUUIDIterator"
      SessionRegistrationID: "RepositoryUUID"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"

links:
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump7"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage2"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join18"
    into: "in1"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join18"
    into: "in3"
  - from: "Join7"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "Join18"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "SetPage1"
    via: "next"
    to: "Join19"
    into: "in1"
  - from: "Decision8"
    via: "no"
    to: "Join19"
    into: "in3"
  - from: "Join19"
    via: "next"
    to: "Join7"
    into: "in3"
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "GetRepositoryByUUID6"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "GetPageLocator1"
    via: "error"
    to: "Join20"
    into: "in1"
  - from: "GetPageable1"
    via: "error"
    to: "Join20"
    into: "in2"
  - from: "Join20"
    via: "next"
    to: "Jump8"
    into: "in"
  - from: "SetPageLocator1"
    via: "next"
    to: "CreateProductIdentifierLookupHelper1"
    into: "in"
  - from: "CreateProductIdentifierLookupHelper1"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "KeyMapper9"
    via: "next"
    to: "Join21"
    into: "in1"
  - from: "GetPageable1"
    via: "next"
    to: "Join21"
    into: "in3"
  - from: "Join21"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "GetFormSelection2"
    into: "in"
  - from: "Call16"
    via: "next"
    to: "KeyMapper9"
    into: "in"
  - from: "GetFormSelection2"
    via: "next"
    to: "UpdateClipboard1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "UpdateClipboard1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Start12"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Start11"
    via: "next"
    to: "GetClipboard1"
    into: "in"
  - from: "GetClipboard1"
    via: "next"
    to: "GetRepositoryByUUID6"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "GetRepositoryByUUID2"
    into: "in"
  - from: "GetRepositoryByUUID2"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "GetProductByUUID1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "Pipelet34"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "GetProductByUUID1"
    via: "next"
    to: "CreatePriceDefinitionSnapShotFromProduct2"
    into: "in"
  - from: "CreatePriceDefinitionSnapShotFromProduct2"
    via: "next"
    to: "CreateProductSnapShotFromProduct2"
    into: "in"
  - from: "CreatePriceDefinitionSnapShotFromProduct1"
    via: "next"
    to: "CreateProductSnapShotFromProduct1"
    into: "in"
  - from: "CreateProductSnapShotFromProduct2"
    via: "next"
    to: "CreatePriceDefinitionSnapShotFromProduct1"
    into: "in"
  - from: "CreateProductSnapShotFromProduct1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "Pipelet34"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "KeyMapper10"
    into: "in"
  - from: "GetProductByUUID1"
    via: "error"
    to: "JumpNode1"
    into: "in"
  - from: "KeyMapper10"
    via: "next"
    to: "Call16"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Decision8"
    into: "in"
  - from: "Decision8"
    via: "yes"
    to: "SetPage1"
    into: "in"
