flow: "ViewVariationType_32"
kind: "process"

entries:
  - id: "StartNode1"
    name: "VerifyValueRange"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode10"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "JumpToList"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "New"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewVariationType_32-VerifyValueRange"
  - id: "CallNode14"
    type: "call"
    ref: "ProcessVariationType-CreateVariationType"
  - id: "CallNode2"
    type: "call"
    ref: "ViewVariationType_32-Prefix"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessVariationType-UpdateVariationType"
  - id: "CallNode4"
    type: "call"
    ref: "ViewVariationType_32-Prefix"
  - id: "CallNode5"
    type: "call"
    ref: "ViewVariationType_32-VerifyValueRange"
  - id: "CallNode6"
    type: "call"
    ref: "ViewVariationType_32-Prefix"
  - id: "CallNode7"
    type: "call"
    ref: "ViewVariationType_32-Prefix"
  - id: "CallNode8"
    type: "call"
    ref: "ViewVariationType_32-Prefix"
  - id: "DecisionNode1"
    type: "decision"
    condition: "VariationTypeUUID"
  - id: "DecisionNode11"
    type: "decision"
    condition: "ValueRangeIterator"
  - id: "DecisionNode2"
    type: "decision"
    condition: "VariationType"
  - id: "DecisionNode3"
    type: "decision"
    condition: "VariationType"
  - id: "DecisionNode8"
    type: "decision"
    condition: "ValueType_Integer"
  - id: "DecisionNode9"
    type: "decision"
    condition: "ValueType_Integer"
  - id: "EndNode1"
    type: "end"
  - id: "EndNode3"
    type: "end"
  - id: "EndNode4"
    type: "end"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode17"
    type: "join"
  - id: "JoinNode18"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode24"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewVariationTypeList_32-ListAll"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewVariationTypeList_32-ListAll"
  - id: "JumpNode4"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode5"
    type: "jump"
  - id: "JumpNode6"
    type: "jump"
    ref: "ViewVariationType_32-Edit"
  - id: "JumpNode7"
    type: "jump"
    ref: "ViewVariationType_32-Edit"
  - id: "JumpNode8"
    type: "jump"
    ref: "ViewVariationType_32-Edit"
  - id: "LoopNode1"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetLocale"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "VariationType:ValueType"
      InValue_10: "VariationTypeForm:VariationTypeID:Value"
      InValue_4: "VariationTypeForm:AttributeName:Value"
      InValue_5: "VariationTypeForm:DisplayName:Value"
      InValue_7: "VariationTypeForm:ValueRange:Value"
      OutValue_1: "ValueType_Integer"
      OutValue_10: "VariationTypeID"
      OutValue_4: "VariationTypeAttributeName"
      OutValue_5: "VariationTypeDisplayName"
      OutValue_7: "VariationTypeValueRange"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "Pipelet12"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/NewVariationType_32"
  - id: "Pipelet13"
    type: "pipelet"
    ref: "RemoveVariationType"
  - id: "Pipelet14"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "VariationTypeForm"
  - id: "Pipelet15"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "NewVariationTypeForm"
    bindings:
      WebForm: "NewVariationTypeForm"
  - id: "Pipelet16"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ValueObjectError"
      ValueType: "Dictionary Value"
      Value: "NoValue"
  - id: "Pipelet17"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_PRODUCT_TYPE_ID"
      Value: "Exists"
  - id: "Pipelet18"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/VariationType_32"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewVariationType_32-Create"
      OutValue_1: "ViewVariationType_32-JumpToList"
      OutValue_2: "ViewVariationType_32-Update"
      OutValue_3: "ViewVariationType_32-Delete"
      OutValue_4: "ViewVariationType_32-Edit"
      OutValue_5: "ViewVariationType_32-Edit"
      OutValue_6: "ViewVariationType_32-New"
      OutValue_7: "ViewVariationType_32-Edit"
      OutValue_8: "ViewVariationType_32-Update"
    bindings:
      Key_0: "create"
      Key_1: "cancel"
      Key_2: "update"
      Key_3: "delete"
      Key_4: "confirmDelete"
      Key_5: "cancelDelete"
      Key_6: "ChangeLocaleInNew"
      Key_7: "ChangeLocale"
      Key_8: "addVariationValue"
      SelectionKey: "JumpTarget"
  - id: "Pipelet21"
    type: "pipelet"
    ref: "GetVariationTypeByUUID"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "GetVariationTypeValueData"
  - id: "Pipelet36"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "NewVariationTypeForm"
    bindings:
      WebForm: "NewVariationTypeForm"
  - id: "Pipelet37"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "NewVariationTypeForm"
  - id: "Pipelet38"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ChannelRepository:RepositoryDomain"
      InValue_10: "NewVariationTypeForm:VariationTypeID:Value"
      InValue_2: "NewVariationTypeForm:Localized:isSubmitted"
      InValue_3: "ValueType_Integer"
      InValue_4: "NewVariationTypeForm:AttributeName:Value"
      InValue_5: "NewVariationTypeForm:DisplayName:Value"
      InValue_6: "CurrentSession:Locale"
      InValue_7: "NewVariationTypeForm:ValueRange:Value"
      OutValue_1: "VariationTypeDomain"
      OutValue_10: "VariationTypeID"
      OutValue_2: "VariationTypeIsLocalized"
      OutValue_3: "VariationTypeValueType"
      OutValue_4: "VariationTypeAttributeName"
      OutValue_5: "VariationTypeDisplayName"
      OutValue_6: "ParserLocale"
      OutValue_7: "VariationTypeValueRange"
  - id: "Pipelet39"
    type: "pipelet"
    ref: "InvalidatePageLocatorPageable"
    config:
      DefaultPageLocatorName: "VariationTypeList"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "VariationTypeForm"
    bindings:
      WebForm: "VariationTypeForm"
  - id: "Pipelet40"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "ValueType_Integer"
      IntegerValue: "null"
      Locale: "null"
      LocalizedString: "NewVariationTypeForm:ValueType:Value"
      Pattern: "null"
  - id: "Pipelet41"
    type: "pipelet"
    ref: "VerifyInteger"
    config:
      MaxValue: 2147483647
      MinValue: -2147483648
    bindings:
      ErrorCode: "ValueObjectError"
      IntegerObject: "ValueObject"
      Locale: "CurrentSession:Locale"
      LocalizedString: "ValueString"
  - id: "Pipelet42"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ValueString"
      OutValue_1: "ValueObject"
  - id: "Pipelet48"
    type: "pipelet"
    ref: "CreateIteratorFromConfigValues"
    config:
      Delimiters: "|"
    bindings:
      ValuesIterator: "ValueRangeIterator"
      ValuesString: "VariationTypeValueRange"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "VariationTypeForm"
    bindings:
      WebForm: "VariationTypeForm"
  - id: "Pipelet50"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      InVector: "ValueObjectVector"
      Iterator: "ValueRangeObjects"
      Object: "ValueObject"
      OutVector: "ValueObjectVector"
  - id: "Pipelet52"
    type: "pipelet"
    ref: "VerifyDouble"
    config:
      MaxValue: "1.7976931348623157E308"
      MinValue: "4.9E-324"
    bindings:
      DoubleValue: "ValueObject"
      ErrorCode: "ValueObjectError"
      Locale: "CurrentSession:Locale"
      LocalizedString: "ValueString"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "ValueRange"
      param.1.required: true
      param.1.rule: ""
      param.2.name: "AttributeName"
      param.2.required: true
      param.2.rule: ""
      param.3.name: "VariationTypeID"
      param.3.required: true
      param.3.rule: ""
      param.4.name: "DisplayName"
      param.4.required: true
      param.4.rule: ""
      webform-id: "VariationTypeForm"
    bindings:
      WebForm: "VariationTypeForm"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "VariationTypeList"
      RestorePageLocatorDictionary: "False"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "InvalidatePageLocatorPageable"
    config:
      DefaultPageLocatorName: "VariationTypeList"
  - id: "Pipelet9"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "VariationTypeID"
      param.1.required: true
      param.1.rule: ""
      param.2.name: "DisplayName"
      param.2.required: true
      param.2.rule: ""
      param.3.name: "AttributeName"
      param.3.required: true
      param.3.rule: ""
      param.4.name: "ValueType"
      param.4.required: true
      param.4.rule: "^1|2|3$"
      param.5.name: "Localized"
      param.5.required: false
      param.5.rule: "^true$"
      param.6.name: "ValueRange"
      param.6.required: true
      param.6.rule: ""
      webform-id: "NewVariationTypeForm"
    bindings:
      WebForm: "NewVariationTypeForm"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_PRODUCT_TYPE_ID"
      Value: "Exists"

links:
  - from: "Pipelet18"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "JoinNode12"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode11"
    via: "yes"
    to: "LoopNode1"
    into: "in"
  - from: "Pipelet37"
    via: "next"
    to: "Pipelet40"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "Pipelet9"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "DecisionNode1"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "DecisionNode9"
    into: "in"
  - from: "Pipelet16"
    via: "next"
    to: "JoinNode24"
    into: "in1"
  - from: "Pipelet4"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "CallNode5"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Pipelet7"
    via: "error"
    to: "JumpNode1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode8"
    via: "no"
    to: "Pipelet42"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Pipelet48"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode18"
    via: "next"
    to: "Pipelet50"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "Pipelet18"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Pipelet12"
    into: "in"
  - from: "DecisionNode9"
    via: "no"
    to: "DecisionNode8"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet13"
    into: "in"
  - from: "Pipelet15"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "DecisionNode8"
    via: "yes"
    to: "Pipelet52"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "Pipelet36"
    via: "next"
    to: "Pipelet37"
    into: "in"
  - from: "CallNode14"
    via: "next"
    to: "Pipelet39"
    into: "in"
  - from: "Pipelet38"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "Pipelet41"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Pipelet41"
    via: "error"
    to: "JoinNode24"
    into: "in2"
  - from: "Pipelet50"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "CallNode7"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet21"
    into: "in"
  - from: "Pipelet40"
    via: "next"
    to: "Pipelet38"
    into: "in"
  - from: "Pipelet48"
    via: "next"
    to: "DecisionNode11"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode8"
    into: "in3"
  - from: "Pipelet13"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet42"
    via: "next"
    to: "JoinNode18"
    into: "in3"
  - from: "Pipelet15"
    via: "next"
    to: "Pipelet36"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "Pipelet9"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "CallNode5"
    via: "Error"
    to: "JoinNode12"
    into: "in2"
  - from: "DecisionNode9"
    via: "yes"
    to: "Pipelet41"
    into: "in"
  - from: "Pipelet52"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "CallNode8"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "Pipelet14"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "CallNode14"
    via: "ERROR"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Pipelet10"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode1"
    via: "Error"
    to: "JoinNode10"
    into: "in2"
  - from: "Pipelet2"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "Pipelet52"
    via: "error"
    to: "JoinNode17"
    into: "in2"
  - from: "Pipelet21"
    via: "next"
    to: "JoinNode8"
    into: "in2"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "Pipelet4"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "Pipelet15"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "DecisionNode11"
    via: "no"
    to: "Pipelet16"
    into: "in"
  - from: "Pipelet14"
    via: "next"
    to: "Pipelet10"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode18"
    into: "in1"
  - from: "JoinNode17"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "JoinNode24"
    via: "next"
    to: "JoinNode17"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "JumpNode7"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Pipelet17"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "Pipelet11"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Pipelet37"
    via: "error"
    to: "JoinNode9"
    into: "in2"
  - from: "Pipelet7"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "Pipelet39"
    via: "next"
    to: "JumpNode8"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "Pipelet14"
    into: "in"
  - from: "Pipelet12"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "StartNode8"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "CallNode3"
    via: "ERROR"
    to: "Pipelet17"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "Pipelet11"
    into: "in"
  - from: "StartNode10"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JumpNode6"
    into: "in"
