flow: "ViewEditing"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "InteractionNode1"
    type: "interaction"
  - id: "Text0"
    type: "text"

links:
  - from: "StartNode1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
