flow: "ViewProductUNSPSC"
kind: "view"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "SelectLevel"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "ValidateCode"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "CheckLock"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessProduct-DetermineCategoryPath"
  - id: "Call2"
    type: "call"
    ref: "ViewProductUNSPSC-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ViewProductUNSPSC-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ViewProductUNSPSC-Prefix"
  - id: "Call5"
    type: "call"
    ref: "ViewProductUNSPSC-Prefix"
  - id: "Call6"
    type: "call"
    ref: "ProcessProductUNSPSC-Start"
  - id: "Call7"
    type: "call"
    ref: "ProcessProductUNSPSC-SelectLevel"
  - id: "Call8"
    type: "call"
    ref: "ProcessProductUNSPSC-ValidateCode"
  - id: "Call9"
    type: "call"
    ref: "ProcessProductUNSPSC-Update"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessProductLock-Lookup"
    bindings:
      User: "CurrentUser"
  - id: "CallNode2"
    type: "call"
    ref: "ViewProductUNSPSC-CheckLock"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessProductLock-Check"
    bindings:
      LockingDomain: "OrganizationDomain"
      PreferenceDomain: "OrganizationDomain"
      User: "CurrentUser"
  - id: "CallNode4"
    type: "call"
    ref: "DetermineProduct-MasterRepositoryProduct"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProductUNSPSC-Update"
      OutValue_1: "ViewProductUNSPSC-Start"
    bindings:
      Key_0: "update"
      Key_1: "cancel"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "Jump3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewProductUNSPSC-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewProduct-ErrorProductNotAvailable"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewProduct-ErrorProductNotAvailable"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentMasterRepository:RepositoryDomain"
      OutValue_1: "ProductDomain"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Products"
      WorkingTemplate: "product/ProductUpdateUNSPSC"

links:
  - from: "Start1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "Call4"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "Call9"
    via: "next"
    to: "Join2"
    into: "in3"
  - from: "CallNode1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode3"
    via: "NO_LOCK"
    to: "JumpNode1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "Call6"
    via: "error-product-not-available"
    to: "JoinNode1"
    into: "in1"
  - from: "Call7"
    via: "error-product-not-available"
    to: "JoinNode1"
    into: "in1"
  - from: "Call8"
    via: "error-product-not-available"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "Call9"
    via: "error-product-not-available"
    to: "JoinNode1"
    into: "in1"
  - from: "Start2"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "CallNode4"
    via: "error-product-not-available"
    to: "JumpNode4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Call6"
    via: "next"
    to: "Join1"
    into: "in2"
