flow: "ViewOrganizationEnterpriseList"
kind: "view"

entries:
  - id: "Start2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call2"
    type: "call"
    ref: "ProcessOrganizationEnterprise-Remove"
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "Call6"
    type: "call"
    ref: "ProcessOrganizationEnterprise-ListAll"
  - id: "Call7"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call8"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Decision2"
    type: "decision"
    condition: "PageNumber"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewOrganizationEnterprise-New"
      OutValue_1: "ViewOrganizationEnterpriseList-Paging"
      OutValue_2: "ViewOrganizationEnterpriseList-Delete"
      OutValue_3: "ViewOrganizationEnterpriseList-Paging"
      PagingPipeline: "ViewOrganizationEnterpriseList-Paging"
    bindings:
      Key_0: "new"
      Key_1: "confirmDelete"
      Key_2: "delete"
      Key_3: "cancelDelete"
      SelectionKey: "JumpTarget"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      RestorePageLocatorDictionary: "False"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "EnterpriseOrganizations"
      PageableID: "PageLocator:PageableID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join3"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Jump10"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump5"
    type: "jump"
    ref: "ViewOrganizationEnterpriseList-ListAll"
  - id: "Loop1"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Enterprises"
      WorkingTemplate: "organization/OrganizationEnterpriseList.isml"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "EnterpriseOrganizations"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "EnterpriseOrganizations"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewProxyUnitList-Paging"
      DefaultPageLocatorName: "EnterpriseOrganizationList"
    bindings:
      Pageable: "EnterpriseOrganizations"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      Locale: "null"
      LocalizedString: "PageNumber"
      Pattern: "null"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump10"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "Join8"
    into: "in2"
  - from: "GetPageable1"
    via: "next"
    to: "Join7"
    into: "in2"
  - from: "Join7"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "Call4"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "SetPage2"
    into: "in"
  - from: "SetPage1"
    via: "next"
    to: "Join3"
    into: "in2"
  - from: "Decision2"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage1"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join3"
    into: "in3"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "Start7"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "Start6"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "SetPageLocator1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Loop1"
    into: "loop"
