flow: "ViewOrderExport"
kind: "view"

entries:
  - id: "Start1"
    name: "New"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "GetServices"
    mode: "private"
    strict: true
    inputs:
      - key: "ApplicationBO"
        type: "com.intershop.component.application.capi.ApplicationBO"
        required: true
  - id: "StartNode5"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "UpdateJobConfiguration"
    mode: "private"
    strict: true
    inputs:
      - key: "Form"
        type: "com.intershop.beehive.core.capi.webform.Form"
        required: true
      - key: "Config"
        type: "com.intershop.component.orderimpex.capi.impexscenario.ImpexScenario"
        required: true
  - id: "StartNode8"
    name: "Prefix"
    mode: "private"
    strict: true
    inputs:
      - key: "ConfigID"
        type: "java.lang.String"
        required: false
      - key: "ApplicationBO"
        type: "com.intershop.component.application.capi.ApplicationBO"
        required: true

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewProcessList-DeleteLogFiles"
  - id: "Call4"
    type: "call"
    ref: "This:Prefix"
  - id: "Call5"
    type: "call"
    ref: "This:Prefix"
  - id: "Call6"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode5"
    type: "call"
    ref: "ViewOrderExport-UpdateJobConfiguration"
  - id: "CallNode6"
    type: "call"
    ref: "ViewOrderExport-UpdateJobConfiguration"
  - id: "CallNode7"
    type: "call"
    ref: "ViewOrderExport-GetServices"
    bindings:
      CurrentOrganization: "CurrentOrganization"
  - id: "CallNode8"
    type: "call"
    ref: "ViewOrderExport-GetServices"
  - id: "CombineIterators1"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Concatenate Iterators"
    bindings:
      Iterator: "ServiceInstances"
      Iterator1: "OrderExportServices:Iterator"
      Iterator2: "PackingSlipServices:Iterator"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "JobConfiguration:UUID"
      String1: "\"-BatchEntries.log\""
      Concatenated: "LogFileName"
  - id: "CreateForm4"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "NewOrderExport"
      FormResource: "OrderExport"
    bindings:
      FormAlias: "null"
      FormName: "null"
      FormResource: "null"
      Locale: "null"
  - id: "CreateForm6"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "NewOrderExport"
      FormResource: "OrderExport"
    bindings:
      FormAlias: "null"
      FormName: "null"
      FormResource: "null"
      Locale: "null"
  - id: "CreateForm7"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "OrderExport"
      FormResource: "OrderExport"
    bindings:
      FormAlias: "null"
      FormName: "null"
      FormResource: "null"
      Locale: "null"
  - id: "CreateForm8"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "OrderExport"
      FormResource: "OrderExport"
    bindings:
      FormAlias: "null"
      FormName: "null"
      FormResource: "null"
      Locale: "null"
  - id: "CreateJobConfiguration2"
    type: "pipelet"
    ref: "CreateJobConfiguration"
    bindings:
      Domain: "CurrentOrganization:OrganizationDomain"
      JobConfiguration: "JobConfiguration"
      Application: "CurrentRequest:ExecutionApplication"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ConfigID"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ServiceInstances"
        type: "java.util.Iterator"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "Config"
        type: "com.intershop.component.orderimpex.capi.export.scenario.ExportScenario"
        guaranteed: true
  - id: "GetJobConfiguration3"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobDomain: "null"
      JobDomainName: "null"
      JobName: "null"
      JobUUID: "ConfigID"
  - id: "GetOrderImpexScenario1"
    type: "pipelet"
    ref: "GetOrderImpexScenario"
    bindings:
      ImpexScenarioConfig: "Config"
      ServiceConfigurationRepository: "ApplicationBO:Repository(\"ServiceConfigurationBORepository\")"
      OrderBORepository: "ApplicationBO:Extension(\"Order\"):OrderBORepositoryOfOwningRepository"
  - id: "GetOrderImpexScenario2"
    type: "pipelet"
    ref: "GetOrderImpexScenario"
    bindings:
      ImpexScenarioConfig: "Config"
      ServiceConfigurationRepository: "ApplicationBO:Repository(\"ServiceConfigurationBORepository\")"
      OrderBORepository: "ApplicationBO:Extension(\"Order\"):OrderBORepositoryOfOwningRepository"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "InteractionNode3"
    type: "interaction"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewOrderExport-Edit"
  - id: "JumpNode5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode6"
    type: "jump"
    ref: "ViewOrderExport-Edit"
  - id: "JumpNode7"
    type: "jump"
    ref: "ViewOrderProcessing-Start"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Config:JobConfiguration"
      OutValue_1: "JobConfiguration"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ServiceConfigurationRepository:Services(\"(Class)com.intershop.component.orderimpex.capi.export.order.OrderExportService\")"
      OutValue_1: "OrderExportServices"
      InValue_2: "ServiceConfigurationRepository:Services(\"(Class)com.intershop.component.orderimpex.capi.export.packingslip.PackingSlipExportService\")"
      OutValue_2: "PackingSlipServices"
  - id: "KeyMapper6"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Repository(\"ServiceConfigurationBORepository\")"
      OutValue_1: "ServiceConfigurationRepository"
  - id: "MapFormToObject2"
    type: "pipelet"
    ref: "MapFormToObject"
    config:
      NameFilterType: "exclude"
    bindings:
      TargetObject: "Config"
      NameFilterList: "null"
      Locale: "null"
  - id: "MapObjectToForm1"
    type: "pipelet"
    ref: "MapObjectToForm"
    config:
      NameFilterType: "exclude"
    bindings:
      SourceObject: "Config"
      Locale: "null"
      NameFilterList: "null"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewOrderExport-Create"
      OutValue_1: "ViewOrderProcessing-Start"
      OutValue_2: "ViewOrderExport-Update"
      OutValue_3: "ViewOrderExport-Edit"
      OutValue_4: "ViewOrderExport-Edit"
      OutValue_5: "ViewOrderExport-Delete"
      OutValue_6: "ViewOrderExport-Edit"
    bindings:
      Key_0: "create"
      SelectionKey: "JumpTarget"
      Key_1: "cancelCreate"
      Key_2: "update"
      Key_3: "confirmDelete"
      Key_4: "cancelDelete"
      Key_5: "delete"
      Key_6: "reset"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "order/NewOrderExport"
      SelectedMenuItem: "Orders"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "order/OrderExport"
      SelectedMenuItem: "Orders"
  - id: "RemoveJobConfiguration1"
    type: "pipelet"
    ref: "RemoveJobConfiguration"
  - id: "UpdateCustomAttributes1"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "LogFileDirectory"
      Attribute_1_Type: "String"
      Attribute_2_Name: "LogFileName"
      Attribute_2_Type: "String"
    bindings:
      Attribute_2_Value: "LogFileName"
      Attribute_1_Value: "\"batch/log\""
      ExtensibleObject: "JobConfiguration"
      LocaleInformation: "null"
  - id: "UpdateJobConfiguration2"
    type: "pipelet"
    ref: "UpdateJobConfiguration"
    config:
      PipelineName: "ProcessOrderExportJob"
      PipelineStartNode: "Start"
      Name: "ExportOrder_"
      EnableJob: true
    bindings:
      JobDescription: "null"
      JobDate: "null"
      JobDomain: "null"
      JobDomainName: "null"
      JobEnable: "null"
      JobInterval: "null"
      JobJavaDate: "null"
      JobName: "null"
      JobPipelineName: "null"
      JobPipelineStartNode: "null"
      JobUnit: "null"
      JobUUID: "null"
      JobServerGroup: "null"
  - id: "ValidateForm2"
    type: "pipelet"
    ref: "ValidateForm"
    config:
      Trim: true
  - id: "ValidateForm4"
    type: "pipelet"
    ref: "ValidateForm"
    config:
      Trim: true

links:
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode6"
    into: "in1"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionNode3"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JumpNode7"
    into: "in"
  - from: "CreateForm4"
    via: "next"
    to: "ValidateForm4"
    into: "in"
  - from: "CreateForm7"
    via: "next"
    to: "MapObjectToForm1"
    into: "in"
  - from: "GetOrderImpexScenario2"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "MapObjectToForm1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "StartNode8"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "CreateForm7"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "MapFormToObject2"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "ValidateForm4"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "GetOrderImpexScenario1"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "ValidateForm2"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "Start1"
    via: "next"
    to: "CreateForm6"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Call6"
    via: "NoJob"
    to: "JoinNode3"
    into: "in2"
  - from: "CreateForm8"
    via: "next"
    to: "ValidateForm2"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "UpdateCustomAttributes1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetJobConfiguration3"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "MapFormToObject2"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "UpdateCustomAttributes1"
    via: "next"
    to: "GetOrderImpexScenario2"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "ValidateForm2"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "CreateJobConfiguration2"
    via: "next"
    to: "UpdateJobConfiguration2"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "CreateForm8"
    into: "in"
  - from: "GetJobConfiguration3"
    via: "next"
    to: "GetOrderImpexScenario1"
    into: "in"
  - from: "CreateForm6"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "UpdateJobConfiguration2"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "RemoveJobConfiguration1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "JumpNode6"
    into: "in"
  - from: "RemoveJobConfiguration1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "KeyMapper3"
    via: "next"
    to: "CombineIterators1"
    into: "in"
  - from: "CombineIterators1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "KeyMapper6"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "KeyMapper6"
    into: "in"
  - from: "ValidateForm4"
    via: "next"
    to: "CreateJobConfiguration2"
    into: "in"
  - from: "GetJobConfiguration3"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "Start4"
    via: "next"
    to: "CreateForm4"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
