flow: "ViewContentSharingList"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "ListOrganization"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "GetMasterRepository"
    mode: "private"
    strict: true
    inputs:
      - key: "OrganizationUUID"
        type: "java.lang.String"
        required: true

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Object: "Organization"
      Objects: "null"
      OutVector: "OrganizationVector"
      InVector: "OrganizationVector"
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Objects: "null"
      Object: "CurrentOrganization"
      InVector: "OrganizationVector"
      Iterator: "Organizations"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode2"
    type: "call"
    ref: "ViewProcessList-CreateProcess"
  - id: "CallNode3"
    type: "call"
    ref: "This:GetMasterRepository"
    bindings:
      OrganizationUUID: "SelectedOrganizationUUID"
      MasterRepository: "SharedMasterRepository"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "CreatePageableFromIterator1"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    config:
      PageableName: "Objects"
      Pagesize: 0
    bindings:
      Iterator: "SelectedObjectUUIDs"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PageLocator"
  - id: "DecisionNode2"
    type: "decision"
    condition: "PageNumber"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "MasterRepository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        guaranteed: true
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        guaranteed: true
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "content/GetChannelsWithSharedContent"
      DefaultPageSize: 15
    bindings:
      Connection: "null"
      Parameters: "QueryParameter"
      Query: "null"
      ErrorCode: "SearchError"
      SearchResult: "ChannelsWithSharedContent"
  - id: "GetOrganization1"
    type: "pipelet"
    ref: "GetOrganization"
    config:
      Source: "PipelineDictionary"
    bindings:
      OrganizationUUID: "OrganizationUUID"
  - id: "GetOrganizationByDomain1"
    type: "pipelet"
    ref: "GetOrganizationByDomain"
    bindings:
      OrganizationDomain: "ProxyRepository:OriginalRepository:OwningDomain"
  - id: "GetRepositories1"
    type: "pipelet"
    ref: "GetRepositories"
    config:
      CustomRepositoryTypeCode: 21
      ProxyFlag: true
    bindings:
      OrganizationDomain: "MasterRepository:RepositoryDomain"
      Repositories: "ProxyRepositories"
  - id: "GetRepositories2"
    type: "pipelet"
    ref: "GetRepositories"
    config:
      ProxyFlag: false
      CustomRepositoryTypeCode: 21
    bindings:
      OrganizationDomain: "Organization:Domain"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      UUID: "SharedMasterRepositoryUUID"
      Repository: "SharedMasterRepository"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JumpNode2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewProcessList-ListAll"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Repository"
      OutValue_1: "MasterRepository"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "CurrentDomain"
      InValue_2: "CurrentDomain"
      OutValue_1: "ProcessOwningDomain"
      OutValue_2: "ProcessExecutionDomain"
      OutValue_3: "PageableID"
      InValue_3: "Pageable:ID"
      OutValue_4: "PageableName"
      InValue_4: "\"Objects\""
      OutValue_5: "ProcessPipeline"
      InValue_5: "\"ProcessRemoveContentSharing-Process\""
      OutValue_7: "JobName"
      OutValue_8: "JobNamePrefix"
      OutValue_9: "ProcessDescription"
      InValue_9: "\"Removing slot pagelet assignments and proxy repositories.\""
      InValue_7: "\"MasterContent\""
      InValue_8: "\"MasterContent\""
      InValue_10: "SelectedOrganizationUUID"
      OutValue_10: "SelectedOrganizationUUID"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_2: "CurrentDomain"
      OutValue_2: "ProcessExecutionDomain"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      OutValue_1: "InitPipeline"
      InValue_1: "\"ProcessRemoveContentSharing-Init\""
  - id: "LoopNode2"
    type: "loop"
  - id: "LoopNode3"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      PagingPipeline: "ViewContentSharingList-Paging"
      OutValue_0: "ViewContentSharingList-Paging"
      OutValue_1: "ViewContentSharingList-Paging"
      OutValue_2: "ViewContentSharingList-Delete"
      OutValue_3: "ViewContentSharing-New"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "Paging"
      Key_1: "ConfirmDelete"
      Key_2: "Delete"
      Key_3: "New"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"
  - id: "Pipelet16"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "ChannelsWithSharedContent"
      PageableID: "ContentSharingPageLocator:PageableID"
  - id: "Pipelet17"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "ChannelsWithSharedContent"
  - id: "Pipelet18"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewContentSharingList-Paging"
      DefaultPageLocatorName: "ContentSharingPageLocator"
    bindings:
      Pageable: "ChannelsWithSharedContent"
      PageLocator: "ContentSharingPageLocator"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ContentSharingPageLocator"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocator: "ContentSharingPageLocator"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "ChannelsWithSharedContent"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      RenderingType: "HTML"
      SelectedMenuItem: "ContentSharing"
      WorkingTemplate: "content/ContentSharingList"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      RenderingType: "HTML"
      SelectedMenuItem: "ContentSharing"
      WorkingTemplate: "content/ContentSharingOrganizationList"
  - id: "SetPageLocatorParameter2"
    type: "pipelet"
    ref: "SetPageLocatorParameter"
    bindings:
      PageLocator: "ContentSharingPageLocator"
      ParameterValue: "SharedMasterRepository:UUID"
      ParameterName: "\"SharedMasterRepositoryUUID\""
  - id: "UpdateDictionary1"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "MasterRepository"
      Name_02: "SortBy"
      Name_03: "SortDirection"
      Name_04: "Locale"
      Name_05: "OwningDomain"
      Name_06: "WithoutSharedContent"
    bindings:
      InDictionary: "null"
      OutDictionary: "QueryParameter"
      Value_01: "SharedMasterRepository"
      Value_02: "SortBy"
      Value_03: "SortDirection"
      Value_04: "CurrentSession:Locale"
      Value_05: "CurrentOrganization:OrganizationDomain"
      Value_06: "\"(Boolean)false\""

links:
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "Pipelet5"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "DecisionNode1"
    into: "in"
  - from: "Pipelet11"
    via: "next"
    to: "Pipelet17"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet5"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "Pipelet18"
    into: "in"
  - from: "Pipelet16"
    via: "next"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "UpdateDictionary1"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Pipelet18"
    via: "next"
    to: "SetPageLocatorParameter2"
    into: "in"
  - from: "SetPageLocatorParameter2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "Pipelet3"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "StartNode3"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "Pipelet16"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Pipelet16"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GetRepositories2"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "Pipelet11"
    via: "error"
    to: "JoinNode6"
    into: "in3"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CreatePageableFromIterator1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "GetOrganizationByDomain1"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "CallNode2"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "UpdateDictionary1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "GetRepositories1"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "GetRepositories1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "GetOrganizationByDomain1"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "LoopNode3"
    via: "do"
    to: "KeyMapper1"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "GetOrganization1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "LoopNode3"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "GetOrganization1"
    via: "next"
    to: "GetRepositories2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "KeyMapper4"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CreatePageableFromIterator1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode8"
    into: "in3"
  - from: "Pipelet17"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet11"
    into: "in"
