flow: "ViewChannelCatalogMaintenance_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewCatalog-GetCatalog"
  - id: "Call2"
    type: "call"
    ref: "ViewChannelCatalogMaintenance_52-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ViewChannelCatalogMaintenance_52-Prefix"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessCatalogMaintenance-Update"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelCatalogMaintenance_52-Update"
      OutValue_1: "ViewChannelCatalogMaintenance_52-Start"
      OutValue_2: "ViewChannelCatalogList_52-ListAll"
    bindings:
      Key_0: "apply"
      Key_1: "reset"
      Key_2: "back"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Jump1"
    type: "jump"
    ref: "ViewChannelCatalogList_52-ListAll"
  - id: "Jump6"
    type: "jump"
    ref: "ViewChannelCatalogMaintenance_52-Start"
  - id: "Jump7"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentSelectedChannel:Domain"
      OutValue_1: "CatalogOrganizationDomain"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Catalog:Root"
      OutValue_1: "Category"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelCatalogs"
      WorkingTemplate: "catalog/CatalogMaintenance_52"

links:
  - from: "Start2"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Call1"
    via: "ERROR"
    to: "Jump1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump7"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "Jump6"
    into: "in"
