flow: "ViewBrandingInstallationList_32"
kind: "view"

entries:
  - id: "Start1"
    name: "New"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Back"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "ShowSelection"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewBrandingInstallationList_32-Prefix"
  - id: "Call10"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "Call2"
    type: "call"
    ref: "ViewBrandingInstallationList_32-Prefix"
  - id: "Call5"
    type: "call"
    ref: "ViewBrandingInstallationList_32-Prefix"
  - id: "Call6"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call7"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call8"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call9"
    type: "call"
    ref: "ViewBrandingInstallationList_32-Prefix"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewBrandingInstallationList_32-New"
      OutValue_1: "ViewBrandingInstallationList_32-Delete"
      OutValue_2: "ViewBrandingInstallationList_32-Back"
      OutValue_3: "ViewBrandingInstallationList_32-Back"
      OutValue_4: "ViewBrandingInstallationList_32-ShowSelection"
      OutValue_5: "ViewBrandingInstallationList_32-ListAll"
    bindings:
      Key_0: "newInstallation"
      Key_1: "deleteInstallation"
      Key_2: "cancelInstallation"
      Key_3: "backToList"
      Key_4: "confirmDeleteInstallation"
      Key_5: "cancelDeletion"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "GetApplication1"
    type: "pipelet"
    ref: "GetApplication"
    bindings:
      Site: "ChannelRepository:Domain:Site"
      UrlIdentifier: "\"-\""
      Application: "CurrentApplication"
  - id: "GetApplications0"
    type: "pipelet"
    ref: "GetApplications"
    bindings:
      Domain: "Organization:Domain"
  - id: "GetBrandingInstallation1"
    type: "pipelet"
    ref: "GetBrandingInstallation"
  - id: "GetBrandingPackage1"
    type: "pipelet"
    ref: "GetBrandingPackage"
  - id: "GetBrandingPackage3"
    type: "pipelet"
    ref: "GetBrandingPackage"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    bindings:
      LocaleId: "LocaleID"
  - id: "GetOrganization3"
    type: "pipelet"
    ref: "GetOrganization"
    config:
      Source: "PipelineDictionary"
  - id: "InstallBrandingPackage1"
    type: "pipelet"
    ref: "InstallBrandingPackage"
    bindings:
      Site: "Organization:Domain:Site"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "JoinNode0"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump2"
    type: "jump"
    ref: "ViewBrandingInstallationList_32-ListAll"
  - id: "Jump3"
    type: "jump"
    ref: "ViewBrandingInstallationList_32-ListAll"
  - id: "Jump4"
    type: "jump"
    ref: "ViewBrandingPackageList_32-ListAll"
  - id: "Loop2"
    type: "loop"
  - id: "LoopNode0"
    type: "loop"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelORG"
      WorkingTemplate: "branding/BrandingPackageInstallations_32"
  - id: "RemoveBrandingInstallation1"
    type: "pipelet"
    ref: "RemoveBrandingInstallation"

links:
  - from: "Call10"
    via: "next"
    to: "Loop2"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "GetBrandingPackage1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Call8"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Call9"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "DispatchFormAction2"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "GetApplication1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetApplication1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetApplications0"
    via: "next"
    to: "LoopNode0"
    into: "in"
  - from: "GetBrandingInstallation1"
    via: "error"
    to: "Join6"
    into: "in1"
  - from: "GetBrandingInstallation1"
    via: "next"
    to: "RemoveBrandingInstallation1"
    into: "in"
  - from: "GetBrandingPackage1"
    via: "error"
    to: "JoinNode0"
    into: "in1"
  - from: "GetBrandingPackage1"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "GetBrandingPackage3"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "GetApplications0"
    into: "in"
  - from: "GetOrganization3"
    via: "error"
    to: "End2"
    into: "in"
  - from: "GetOrganization3"
    via: "next"
    to: "GetApplication1"
    into: "in"
  - from: "InstallBrandingPackage1"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "InstallBrandingPackage1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "GetBrandingPackage3"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "LoopNode0"
    into: "loop"
  - from: "Join6"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "JoinNode0"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Loop2"
    via: "do"
    to: "GetBrandingInstallation1"
    into: "in"
  - from: "Loop2"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "LoopNode0"
    via: "do"
    to: "InstallBrandingPackage1"
    into: "in"
  - from: "LoopNode0"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "RemoveBrandingInstallation1"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "DispatchFormAction2"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "GetOrganization3"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "Call5"
    into: "in"
