flow: "ViewAdvancedShippingOverview_52"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Overview"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "InteractionNode1"
    type: "interaction"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "advancedshipping/AdvancedShippingOverview_52"
      SelectedMenuItem: "OrderStatistics"

links:
  - from: "StartNode1"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionNode1"
    into: "in"
