flow: "ViewChannelProductReviewDetails"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Reject"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "Approve"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "ApproveReview1"
    type: "pipelet"
    ref: "ApproveReview"
    bindings:
      Approver: "CurrentUser"
      ReviewApprovalBORepository: "ReviewApprovalBORepository"
  - id: "CallNode0"
    type: "call"
    ref: "ProcessProductLock_52-Lookup"
  - id: "CallNode1"
    type: "call"
    ref: "ViewChannelProductReviewDetails-Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "ViewChannelProductReviewDetails-Prefix"
  - id: "CallNode3"
    type: "call"
    ref: "ViewChannelProductReviewDetails-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ViewChannelProductReviewDetails-Prefix"
  - id: "CallNode6"
    type: "call"
    ref: "ViewChannelProductReviewDetails-Prefix"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Review"
  - id: "DeleteReview1"
    type: "pipelet"
    ref: "DeleteReview"
    bindings:
      ReviewBORepository: "ReviewBORepository"
      Review: "Review"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelProductReviewDetails-Update"
      OutValue_1: "ViewChannelProductReviewDetails-Delete"
      OutValue_2: "ViewChannelProductReviewDetails-Approve"
      OutValue_3: "ViewChannelProductReviewDetails-Reject"
      OutValue_4: "ViewChannelProductReviewDetails-Edit"
      OutValue_5: "ViewChannelProductReviewDetails-Edit"
    bindings:
      Key_0: "update"
      Key_1: "delete"
      Key_2: "approve"
      Key_3: "reject"
      Key_4: "confirmDelete"
      Key_5: "cancelDelete"
      SelectionKey: "JumpTarget"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "RequireReviewApproval"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain:Site"
      PreferenceKey: "null"
      PreferenceDoubleValue: "null"
      Preference: "null"
      PreferenceIntValue: "null"
      PreferenceStringValue: "RequireReviewApproval"
  - id: "GetReviewByID1"
    type: "pipelet"
    ref: "GetReviewByID"
    bindings:
      ReviewBORepository: "ReviewBORepository"
      ReviewID: "ReviewID"
      Review: "Review"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "JoinNode18"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewChannelProductReviewDetails-Edit"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewChannelProductReviewList-ShowAll"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewChannelProductReviewDetails-Edit"
  - id: "JumpNode4"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode5"
    type: "jump"
    ref: "ViewChannelProductReviewDetails-Edit"
  - id: "JumpNode6"
    type: "jump"
    ref: "ViewChannelProductReviewList-ShowAll"
  - id: "KeyMapper0"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ReviewAttachedProduct:ID"
      OutValue_1: "ProductID"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Repository(\"Review\",CurrentChannel:DomainID)"
      OutValue_1: "ReviewBORepository"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Review:Extension(\"Approval\")"
      OutValue_1: "ReviewApprovalBORepository"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ReviewApprovalBORepository:Approval"
      OutValue_1: "ReviewApproval"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Review:Extension(\"Product\"):AttachedProductBO"
      OutValue_1: "ReviewAttachedProduct"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "review/ChannelProductReviewDetials"
  - id: "RejectReview1"
    type: "pipelet"
    ref: "RejectReview"
    bindings:
      Approver: "CurrentUser"
      ReviewApprovalBORepository: "ReviewApprovalBORepository"
  - id: "UpdateApprovalComment1"
    type: "pipelet"
    ref: "UpdateApprovalComment"
    bindings:
      ReviewApprovalBORepository: "ReviewApprovalBORepository"
      Approver: "CurrentUser"
      ApprovalComment: "Comment"
  - id: "UpdateApprovalComment2"
    type: "pipelet"
    ref: "UpdateApprovalComment"
    bindings:
      ReviewApprovalBORepository: "ReviewApprovalBORepository"
      Approver: "CurrentUser"
      ApprovalComment: "Comment"
  - id: "UpdateApprovalComment3"
    type: "pipelet"
    ref: "UpdateApprovalComment"
    bindings:
      ReviewApprovalBORepository: "ReviewApprovalBORepository"
      Approver: "CurrentUser"
      ApprovalComment: "Comment"

links:
  - from: "StartNode5"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "UpdateApprovalComment1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "UpdateApprovalComment1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "DeleteReview1"
    into: "in"
  - from: "GetDomainPreference1"
    via: "next"
    to: "JoinNode18"
    into: "in1"
  - from: "GetReviewByID1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "GetReviewByID1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "ApproveReview1"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "RejectReview1"
    into: "in"
  - from: "UpdateApprovalComment2"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "UpdateApprovalComment3"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "GetDomainPreference1"
    via: "error"
    to: "JoinNode18"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "JumpNode6"
    into: "in"
  - from: "ApproveReview1"
    via: "next"
    to: "UpdateApprovalComment2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "KeyMapper2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "DeleteReview1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "RejectReview1"
    via: "next"
    to: "UpdateApprovalComment3"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CallNode0"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "JoinNode18"
    via: "next"
    to: "KeyMapper0"
    into: "in"
  - from: "KeyMapper0"
    via: "next"
    to: "CallNode0"
    into: "in"
