flow: "ViewDepartmentUserWizard"
kind: "view"

entries:
  - id: "Start1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start10"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start11"
    name: "DoFinish"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Finish"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "ShowSearchResult"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "SelectUser"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "SelectRoles"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "NextStep"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "UpdateClipboard"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AssignUserToOrganizationRole1"
    type: "pipelet"
    ref: "AssignUserToOrganizationRole"
    bindings:
      OrganizationRole: "Role"
  - id: "Call1"
    type: "call"
    ref: "ViewDepartmentUserWizard-Prefix"
  - id: "Call10"
    type: "call"
    ref: "ViewDepartmentUserWizard-UpdateClipboard"
  - id: "Call2"
    type: "call"
    ref: "ViewDepartmentUserWizard-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ViewDepartmentUserWizard-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ViewDepartmentUserWizard-Prefix"
  - id: "Call5"
    type: "call"
    ref: "ViewDepartmentUserWizard-Prefix"
  - id: "Call6"
    type: "call"
    ref: "ViewDepartmentUserWizard-Prefix"
  - id: "Call8"
    type: "call"
    ref: "ProcessUserList-BySimpleSearch"
  - id: "Call9"
    type: "call"
    ref: "ViewDepartmentUserWizard-UpdateClipboard"
  - id: "CheckForEmptyIterator1"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "PrefixIterator"
  - id: "CheckForEmptyIterator2"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "SelectedRoleUUIDs"
  - id: "DeterminePageable1"
    type: "pipelet"
    ref: "DeterminePageable"
  - id: "DetermineUser1"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "UserUUID"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewDepartmentUserWizard-SelectUser"
      OutValue_1: "ViewDepartmentUserWizard-NextStep"
      OutValue_2: "ViewDepartmentUserWizard-DoFinish"
      OutValue_3: "ViewDepartmentUserWizard-ShowSearchResult"
      OutValue_4: "ViewDepartmentUsers-Start"
    bindings:
      Key_0: "find"
      Key_1: "nextStep"
      Key_2: "finish"
      Key_3: "previous"
      Key_4: "cancel"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "ExchangeSessionObject1"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "SearchResult"
    bindings:
      LoadObject: "Users"
  - id: "ExchangeSessionObject2"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "SearchResult"
    bindings:
      SaveObject: "Users"
  - id: "ExchangeSessionObject3"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "CurrentDepartment"
    bindings:
      SaveObject: "Department"
  - id: "ExchangeSessionObject4"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "CurrentDepartment"
    bindings:
      LoadObject: "Department"
  - id: "ExchangeSessionObject5"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "SelectedUsers"
    bindings:
      SaveObject: "SelectedUserUUIDs"
  - id: "ExchangeSessionObject6"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "SelectedUsers"
    bindings:
      LoadObject: "SelectedUserUUIDs"
  - id: "ExchangeSessionObject7"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "CurrentDepartment"
    bindings:
      LoadObject: "Department"
  - id: "ExchangeSessionObject8"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "CurrentDepartment"
    bindings:
      LoadObject: "Department"
  - id: "GetClipboard1"
    type: "pipelet"
    ref: "GetClipboard"
    config:
      SessionRegistrationID: "newDepUserList"
      SetFormValues: "No"
    bindings:
      UUIDIterator: "SelectedUserUUIDs"
  - id: "GetClipboard3"
    type: "pipelet"
    ref: "GetClipboard"
    config:
      SetFormValues: "No"
      SessionRegistrationID: "newDepUserList"
  - id: "GetDepartment1"
    type: "pipelet"
    ref: "GetDepartment"
    config:
      Source: "PipelineDictionary"
  - id: "GetFormSelection2"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedRole"
    bindings:
      Selection: "SelectedRoleUUIDs"
  - id: "GetFormSelection3"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "user"
    bindings:
      Selection: "AllObjectUUIDs"
  - id: "GetFormSelection4"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedUser"
    bindings:
      Selection: "SelectedObjectUUIDs"
  - id: "GetRole1"
    type: "pipelet"
    ref: "GetRole"
    bindings:
      RoleID: "RoleUUID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewDepartmentUserWizard-SelectUser"
  - id: "Jump10"
    type: "jump"
    ref: "ViewDepartmentUserWizard-SelectRoles"
  - id: "Jump11"
    type: "jump"
    ref: "ViewDepartmentUserWizard-Finish"
  - id: "Jump12"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump2"
    type: "jump"
    ref: "ViewDepartmentUsers-Start"
  - id: "Jump3"
    type: "jump"
    ref: "ViewDepartmentUserWizard-SelectUser"
  - id: "Jump4"
    type: "jump"
    ref: "ViewDepartment-List"
  - id: "Jump7"
    type: "jump"
    ref: "ViewDepartmentUserWizard-SelectRoles"
  - id: "Jump8"
    type: "jump"
    ref: "ViewDepartmentUserWizard-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "OrganizationDomain"
      OutValue_1: "UserDomain"
  - id: "ListDepartmentRoles1"
    type: "pipelet"
    ref: "ListDepartmentRoles"
  - id: "Loop1"
    type: "loop"
  - id: "Loop2"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Departments"
      WorkingTemplate: "department/DepartmentSelectRoles"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Departments"
      WorkingTemplate: "department/DepartmentSelectUsers"
  - id: "RemoveClipboard1"
    type: "pipelet"
    ref: "RemoveClipboard"
    config:
      SessionRegistrationID: "newDepUserList"
  - id: "SwitchPage1"
    type: "pipelet"
    ref: "SwitchPage"
  - id: "UpdateClipboard1"
    type: "pipelet"
    ref: "UpdateClipboard"
    config:
      SessionRegistrationID: "newDepUserList"
      StoreFormValues: "No"
    bindings:
      UUIDIterator: "PrefixIterator"

links:
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "ExchangeSessionObject2"
    into: "in"
  - from: "ExchangeSessionObject2"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "ExchangeSessionObject8"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "ExchangeSessionObject4"
    via: "next"
    to: "ListDepartmentRoles1"
    into: "in"
  - from: "ListDepartmentRoles1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "DetermineUser1"
    into: "in"
  - from: "Loop2"
    via: "do"
    to: "GetRole1"
    into: "in"
  - from: "DetermineUser1"
    via: "next"
    to: "AssignUserToOrganizationRole1"
    into: "in"
  - from: "AssignUserToOrganizationRole1"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "DeterminePageable1"
    via: "next"
    to: "SwitchPage1"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "GetRole1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Loop2"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "RemoveClipboard1"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "ExchangeSessionObject1"
    into: "in"
  - from: "DeterminePageable1"
    via: "error"
    to: "Jump1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "next"
    to: "Jump7"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "error"
    to: "Jump8"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "GetClipboard1"
    into: "in"
  - from: "GetFormSelection2"
    via: "next"
    to: "CheckForEmptyIterator2"
    into: "in"
  - from: "ExchangeSessionObject8"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "CheckForEmptyIterator2"
    via: "error"
    to: "Jump10"
    into: "in"
  - from: "CheckForEmptyIterator2"
    via: "next"
    to: "Jump11"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "GetFormSelection4"
    into: "in"
  - from: "GetFormSelection4"
    via: "next"
    to: "GetFormSelection3"
    into: "in"
  - from: "GetFormSelection3"
    via: "next"
    to: "UpdateClipboard1"
    into: "in"
  - from: "UpdateClipboard1"
    via: "next"
    to: "End3"
    into: "in"
  - from: "RemoveClipboard1"
    via: "next"
    to: "GetDepartment1"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "DeterminePageable1"
    into: "in"
  - from: "ExchangeSessionObject7"
    via: "next"
    to: "ExchangeSessionObject6"
    into: "in"
  - from: "ExchangeSessionObject6"
    via: "next"
    to: "Loop2"
    into: "in"
  - from: "SwitchPage1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "GetClipboard1"
    via: "next"
    to: "ExchangeSessionObject5"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "CheckForEmptyIterator1"
    into: "in"
  - from: "ExchangeSessionObject5"
    via: "next"
    to: "ExchangeSessionObject4"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "ExchangeSessionObject7"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Start10"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump12"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "Start11"
    via: "next"
    to: "GetFormSelection2"
    into: "in"
  - from: "ExchangeSessionObject1"
    via: "next"
    to: "GetClipboard3"
    into: "in"
  - from: "GetDepartment1"
    via: "next"
    to: "ExchangeSessionObject3"
    into: "in"
  - from: "GetClipboard3"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "GetDepartment1"
    via: "error"
    to: "Jump4"
    into: "in"
  - from: "ExchangeSessionObject3"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
