flow: "ViewUserGroupUsers_52"
kind: "view"

entries:
  - id: "Start1"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start10"
    name: "Back"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start31"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Search"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "ListSimpleSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "ParametricSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "ListParametricSearch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call5"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call7"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "CallNode0"
    type: "call"
    ref: "ProcessUserList_52-VerifyCreationDates"
  - id: "CallNode1"
    type: "call"
    ref: "ViewUserGroupUsers_52-Search"
  - id: "CallNode10"
    type: "call"
    ref: "ViewUserGroupUsers_52-ParametricSearch"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessOrganization_52-GetConsumerOrg"
  - id: "CallNode3"
    type: "call"
    ref: "ViewUserGroupUsers_52-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ViewUserGroupUsers_52-Prefix"
  - id: "CallNode5"
    type: "call"
    ref: "ViewUserGroupUsers_52-Prefix"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessUserList-List"
  - id: "CallNode61"
    type: "call"
    ref: "ProcessUserList-BySimpleSearch"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessUserList-ByParametricSearch"
  - id: "CallNode9"
    type: "call"
    ref: "ViewUserGroupUsers_52-Prefix"
  - id: "Decision1"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision2"
    type: "decision"
    condition: "UserGroupID"
  - id: "Decision3"
    type: "decision"
    condition: "UserGroup"
  - id: "Decision4"
    type: "decision"
    condition: "SearchTerm"
  - id: "DispatchFormAction11"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewUserGroupUsers_52-Paging"
      OutValue_1: "ViewUserGroupUsers_52-Delete"
      OutValue_2: "ViewUserGroupUsersSelection_52-ListAll"
      OutValue_3: "ViewUserGroupUsers_52-Paging"
      OutValue_4: "ViewUserGroupUsers_52-Back"
      OutValue_5: "ViewUserGroupUsers_52-ListSimpleSearch"
      PagingPipeline: "ViewUserGroupUsers_52-Paging"
      OutValue_6: "ViewUserGroupUsers_52-ListParametricSearch"
    bindings:
      Key_0: "confirmDelete"
      Key_1: "delete"
      Key_2: "new"
      Key_3: "cancelDelete"
      Key_4: "backToList"
      Key_5: "simpleSearch"
      Key_6: "parametricSearch"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode0"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "UserGroups"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocatorName: "null"
  - id: "GetPageLocator11"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "UserGroupUsers"
      RestorePageLocatorDictionary: "True"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      PageableID: "PageLocator:PageableID"
      Pageable: "Users"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "JoinNode0"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump21"
    type: "jump"
    ref: "ViewUserGroupUsers_52-ListAll"
  - id: "Jump5"
    type: "jump"
  - id: "Jump6"
    type: "jump"
    ref: "ViewUserGroupList_52-ListAll"
  - id: "JumpNode0"
    type: "jump"
    ref: "This:Paging"
  - id: "Loop1"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_10: "UserGroup:Domain"
      OutValue_10: "UserDomain"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Filter"
      Value: "ProcessUserList-UserGroupsFilter"
      ValueType: "Dictionary Value"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_10: "UserGroup:Domain"
      OutValue_10: "UserDomain"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "DetermineUserGroup"
    bindings:
      CurrentDomain: "Organization:OrganizationDomain:Domain"
      UserGroupID: "UserGroupID"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Filter"
      Value: "ProcessUserList-UserGroupsFilter"
      ValueType: "Dictionary Value"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "null"
      Object: "UserGroup"
      Objects: "null"
      Iterator: "UserGroups"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "SearchTerm"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "SetPageLocatorParameter"
    config:
      DefaultParameterName: "SearchTerm"
    bindings:
      ParameterName: "null"
      ParameterValue: "SearchTerm"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "RemoveUserFromOrganizationRole"
    bindings:
      OrganizationRole: "UserGroup"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "UserUUID"
  - id: "Pipelet9"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "null"
      Object: "UserGroup"
      Objects: "null"
      Iterator: "UserGroups"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelUserGroup"
      WorkingTemplate: "user/UserGroupUsers_52"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "SearchTerm"
      RemoveFormValues: true
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "SearchTerm"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Users"
  - id: "SetPage3"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Users"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewUserGroupUsers_52-Paging"
      DefaultPageLocatorName: "UserGroupUsers"
    bindings:
      HandlerPipeline: "null"
      PageLocatorName: "null"
      Pageable: "Users"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      Locale: "null"
      LocalizedString: "PageNumber"
      Pattern: "null"
      IntegerObject: "PageNumber"

links:
  - from: "Call1"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "GetPageLocator11"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Call7"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "CallNode0"
    via: "ERROR"
    to: "JoinNode0"
    into: "in1"
  - from: "CallNode0"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "CallNode10"
    via: "ERROR"
    to: "JumpNode0"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "CallNode61"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CallNode8"
    via: "ERROR"
    to: "JoinNode0"
    into: "in1"
  - from: "CallNode8"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "SetPage2"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join3"
    into: "in1"
  - from: "Decision2"
    via: "yes"
    to: "CallNode2"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Join3"
    into: "in1"
  - from: "Decision3"
    via: "yes"
    to: "Decision2"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "Decision4"
    via: "yes"
    to: "Pipelet6"
    into: "in"
  - from: "DispatchFormAction11"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "GetPageLocator11"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "GetPageLocator1"
    via: "error"
    to: "Jump6"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "GetPageable1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Join5"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "JoinNode0"
    via: "next"
    to: "EndNode0"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "Pipelet8"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "Jump21"
    into: "in"
  - from: "Pipelet10"
    via: "next"
    to: "Pipelet9"
    into: "in"
  - from: "Pipelet11"
    via: "next"
    to: "Pipelet10"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Pipelet3"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "Pipelet5"
    via: "error"
    to: "CallNode6"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "CallNode61"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "Pipelet7"
    via: "error"
    to: "Join4"
    into: "in1"
  - from: "Pipelet7"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "Pipelet8"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "Pipelet9"
    via: "next"
    to: "CallNode0"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "SetPage2"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "SetPage3"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "SetPageLocator1"
    via: "next"
    to: "Decision4"
    into: "in"
  - from: "Start10"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Start31"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction11"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "Pipelet11"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage3"
    into: "in"
