flow: "ViewPageletTemplateProperties"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode11"
    name: "ConfirmDelete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode13"
    name: "Copy"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode14"
    name: "ValidateInput"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "ConfirmUnassign"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "TemplateCallback"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewPageletProperties-IsCopyPossible"
    bindings:
      RepositoryUUID: "ContentRepository:UUID"
      PageletUUID: "Pagelet:UUID"
      Result: "IsCopyPossible"
  - id: "CallNode14"
    type: "call"
    ref: "ProcessPageletAssignments-HandlePosition"
    bindings:
      Position: "CalculatedPosition"
      Domain: "ContentRepository:RepositoryDomain"
  - id: "CallNode16"
    type: "call"
    ref: "ViewPagelet-IsTabSwitched"
    bindings:
      PageletUUID: "Pagelet:UUID"
      Flag: "IsTabSwitched"
  - id: "CallNode17"
    type: "call"
    ref: "ProcessPageletAssignments-GetPageletAssignments"
    bindings:
      ToObject: "Assignment:To"
      Domain: "Assignment:Domain"
      Pagelet: "null"
  - id: "CallNode19"
    type: "call"
    ref: "ViewPageletProperties-IsCopyPossible"
    bindings:
      RepositoryUUID: "ContentRepositoryUUID"
  - id: "CallNode2"
    type: "call"
    ref: "ViewPageletProperties-Prefix"
  - id: "CallNode22"
    type: "call"
    ref: "This:ValidateInput"
  - id: "CallNode23"
    type: "call"
    ref: "This:ValidateInput"
  - id: "CallNode3"
    type: "call"
    ref: "ViewPageletProperties-Prefix"
  - id: "CallNode36"
    type: "call"
    ref: "ProcessPageletLock-Check"
    bindings:
      LockingDomain: "ContentRepository:RepositoryDomain"
      PreferenceDomain: "ContentRepository:RepositoryDomain"
      User: "CurrentUser"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessPageletTemplate-DeleteIncludingChildren"
    bindings:
      Domain: "ContentRepository:RepositoryDomain"
  - id: "CallNode5"
    type: "call"
    ref: "ViewPagelet-GetContextObject"
    bindings:
      UUID: "ContextObject:UUID"
      Repository: "ContentRepository"
  - id: "CallNode6"
    type: "call"
    ref: "ViewPageletProperties-Prefix"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessPagelet-UpdatePageletAssignment"
    bindings:
      Active: "AssignmentFlag"
      ValidFrom: "AssignmentFrom"
      ValidTo: "AssignmentTo"
      Position: "CalculatedPosition"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessPageletAssignments-ProcessAssignmentPositioning"
    bindings:
      AssignmentPosition: "EditPagelet:AssignmentPosition:Value"
      Domain: "ContentRepository:RepositoryDomain"
      ToObject: "Assignment:To"
  - id: "CallNode9"
    type: "call"
    ref: "ProcessDate-VerifyPeriod"
    bindings:
      ValidFrom_Day: "AssignmentValidFrom_Day"
      ValidFrom_Time: "AssignmentValidFrom_Time"
      ValidTo_Day: "AssignmentValidTo_Day"
      ValidTo_Time: "AssignmentValidTo_Time"
      PeriodFlag: "AssignmentFlag"
      ValidFrom: "AssignmentFrom"
      ValidTo: "AssignmentTo"
      ErrorPeriodIncorrect: "AssignmentPeriodIncorrect"
      ErrorValidFromIncorrect: "AssignmentFromIncorrect"
      ErrorValidToIncorrect: "AssignmentToIncorrect"
  - id: "CreateWebForm4"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      webform-id: "EditPagelet"
      param.1.name: "Name"
      param.1.rule: ""
      param.1.required: true
      param.2.name: "Online"
      param.2.rule: ""
      param.2.required: false
      param.3.name: "Description"
      param.3.rule: ""
      param.3.required: false
      param.4.name: "AssignmentOnline"
      param.4.rule: ""
      param.4.required: false
      param.5.name: "AssignmentPosition"
      param.5.rule: ""
      param.5.required: false
  - id: "DecisionNode1"
    type: "decision"
    condition: "Assignment"
  - id: "DecisionNode10"
    type: "decision"
    condition: "update"
  - id: "DecisionNode12"
    type: "decision"
    condition: "Pagelet:DomainID"
  - id: "DecisionNode2"
    type: "decision"
    condition: "EditPagelet:Online:Value"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Assignment"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Assignment"
  - id: "DecisionNode5"
    type: "decision"
    condition: "IsTabSwitched"
  - id: "DecisionNode6"
    type: "decision"
    condition: "ContextPipeline"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_7: "ViewPageletTemplateProperties-Edit"
      OutValue_0: "ViewPageletTemplateProperties-Update"
      OutValue_1: "ViewPageletTemplateProperties-ConfirmDelete"
      OutValue_2: "ViewPageletTemplateProperties-Delete"
      OutValue_3: "ViewPageletTemplateProperties-Edit"
      OutValue_4: "ViewPageletTemplateProperties-Copy"
      OutValue_5: "ViewPageletTemplateProperties-ConfirmUnassign"
      OutValue_6: "ViewPageletProperties-Unassign"
    bindings:
      SelectionKey: "JumpTarget"
      Key_7: "setLocale"
      Key_0: "update"
      Key_4: "copy"
      Key_1: "confirmDelete"
      Key_2: "delete"
      Key_3: "cancel"
      Key_5: "confirmUnassign"
      Key_6: "unassign"
  - id: "DispatchFormActionByBreadcrumb1"
    type: "pipelet"
    ref: "DispatchFormActionByBreadcrumb"
    config:
      SplitMode: "PipelineAndParameter"
    bindings:
      SelectionKey: "JumpTarget"
      OutValue_0: "ApplicationState:LastListView"
      Key_0: "\"backToLastListView\""
  - id: "DispatchFormActionByBreadcrumb2"
    type: "pipelet"
    ref: "DispatchFormActionByBreadcrumb"
    config:
      SplitMode: "PipelineAndParameter"
    bindings:
      Key_0: "\"backToLastListView\""
      SelectionKey: "JumpTarget"
      OutValue_0: "ApplicationState:LastListView"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "EndNode7"
    type: "end"
    strict: false
  - id: "EndNode8"
    type: "end"
    strict: false
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Request Locale"
  - id: "GetPageletByUUID1"
    type: "pipelet"
    ref: "GetPageletByUUID"
  - id: "GetRepositoryByUUID3"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      UUID: "ContentRepositoryUUID"
      Repository: "ContentRepository"
  - id: "GetValuesFromContainer1"
    type: "pipelet"
    ref: "GetValuesFromContainer"
    config:
      OverwriteBehavior: true
    bindings:
      ContainerName: "Pagelet:UUID"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "EditPagelet"
    bindings:
      WebForm: "EditPagelet"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode15"
    type: "join"
  - id: "JoinNode17"
    type: "join"
  - id: "JoinNode18"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode21"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode10"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "This:Edit"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewPagelet-InternalView"
  - id: "JumpNode6"
    type: "jump"
    ref: "This:Edit"
  - id: "JumpNode7"
    type: "jump"
    ref: "ViewPagelet-NewCopy"
  - id: "JumpNode8"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Assignment:To"
      OutValue_1: "ContextObject"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ContentRepository:RepositoryDomain:Site"
      OutValue_1: "CurrentSite"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ContextPipeline"
      OutValue_1: "JumpTarget"
  - id: "RemoveValuesContainer2"
    type: "pipelet"
    ref: "RemoveValuesContainer"
    bindings:
      ContainerName: "PageletUUID"
  - id: "RemoveValuesContainer3"
    type: "pipelet"
    ref: "RemoveValuesContainer"
    bindings:
      ContainerName: "Pagelet:UUID"
  - id: "RemoveValuesContainer4"
    type: "pipelet"
    ref: "RemoveValuesContainer"
    bindings:
      ContainerName: "PageletUUID"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "SelectedTab"
      Value: "Properties"
      ValueType: "Dictionary Value"
  - id: "SetValuesToContainer3"
    type: "pipelet"
    ref: "SetValuesToContainer"
    bindings:
      ContainerName: "PageletUUID"
  - id: "SetValuesToContainer4"
    type: "pipelet"
    ref: "SetValuesToContainer"
    bindings:
      ContainerName: "PageletUUID"
      DictionaryKeys: "\"PageletLockedForOther\""
  - id: "UpdatePagelet1"
    type: "pipelet"
    ref: "UpdatePagelet"
    bindings:
      PageFlag: "Pagelet:Page"
      DisplayName: "EditPagelet:Name:Value"
      Author: "CurrentUser"
      UpdatedPagelet: "Pagelet"
      Description: "EditPagelet:Description:Value"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      webform-id: "EditPagelet"
      mode: "update"
    bindings:
      WebForm: "EditPagelet"
  - id: "ValidateWebForm2"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "EditPagelet"
  - id: "VerifyBoolean1"
    type: "pipelet"
    ref: "VerifyBoolean"
    bindings:
      NoneLocalizedString: "\"false\""
      BooleanValue: "OnlineFlag"
  - id: "VerifyBoolean2"
    type: "pipelet"
    ref: "VerifyBoolean"
    bindings:
      NoneLocalizedString: "EditPagelet:Online:Value"
      BooleanValue: "OnlineFlag"

links:
  - from: "DecisionNode5"
    via: "yes"
    to: "GetValuesFromContainer1"
    into: "in"
  - from: "CallNode23"
    via: "ERROR"
    to: "JoinNode21"
    into: "in2"
  - from: "KeyMapper2"
    via: "next"
    to: "GetPageletByUUID1"
    into: "in"
  - from: "JoinNode17"
    via: "next"
    to: "JoinNode13"
    into: "in1"
  - from: "VerifyBoolean2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode13"
    via: "next"
    to: "JoinNode21"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "GetValuesFromContainer1"
    via: "error"
    to: "JoinNode17"
    into: "in2"
  - from: "GetValuesFromContainer1"
    via: "next"
    to: "DecisionNode10"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "CallNode16"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "CallNode23"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode10"
    via: "yes"
    to: "CallNode23"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "RemoveValuesContainer3"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "StartNode14"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "ValidateWebForm2"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "CallNode36"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetWebForm2"
    via: "error"
    to: "JoinNode18"
    into: "in2"
  - from: "RemoveValuesContainer3"
    via: "next"
    to: "JoinNode17"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CreateWebForm4"
    via: "next"
    to: "SetValuesToContainer3"
    into: "in"
  - from: "GetPageletByUUID1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "CallNode22"
    via: "next"
    to: "CallNode36"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "VerifyBoolean2"
    into: "in"
  - from: "UpdateWebForm2"
    via: "next"
    to: "ValidateWebForm2"
    into: "in"
  - from: "GetWebForm2"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode12"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "VerifyBoolean1"
    into: "in"
  - from: "VerifyBoolean1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "VerifyBoolean2"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "RemoveValuesContainer4"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "CallNode36"
    via: "NO_LOCK"
    to: "JoinNode12"
    into: "in1"
  - from: "VerifyBoolean1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode6"
    via: "next"
    to: "CreateWebForm4"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "JoinNode7"
    into: "in3"
  - from: "StartNode13"
    via: "next"
    to: "CallNode19"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "RemoveValuesContainer2"
    via: "next"
    to: "JumpNode6"
    into: "in"
  - from: "ValidateWebForm2"
    via: "error"
    to: "JoinNode18"
    into: "in1"
  - from: "StartNode4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "SetValuesToContainer3"
    via: "next"
    to: "CallNode22"
    into: "in"
  - from: "JoinNode11"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "SetValuesToContainer4"
    into: "in"
  - from: "JoinNode15"
    via: "next"
    to: "RemoveValuesContainer2"
    into: "in"
  - from: "UpdatePagelet1"
    via: "next"
    to: "RemoveValuesContainer4"
    into: "in"
  - from: "SetValuesToContainer4"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "CallNode4"
    via: "LOCKED_FOR_OTHER"
    to: "JoinNode15"
    into: "in2"
  - from: "DecisionNode10"
    via: "no"
    to: "JoinNode13"
    into: "in2"
  - from: "DecisionNode12"
    via: "no"
    to: "JoinNode15"
    into: "in1"
  - from: "CallNode22"
    via: "ERROR"
    to: "JoinNode11"
    into: "in2"
  - from: "StartNode7"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "GetRepositoryByUUID3"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "CallNode17"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "DispatchFormActionByBreadcrumb2"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "DispatchFormActionByBreadcrumb1"
    via: "next"
    to: "JumpNode8"
    into: "in"
  - from: "GetLocale2"
    via: "next"
    to: "GetRepositoryByUUID3"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode19"
    via: "No"
    to: "DispatchFormActionByBreadcrumb1"
    into: "in"
  - from: "CallNode9"
    via: "ERROR"
    to: "JoinNode10"
    into: "in2"
  - from: "CallNode3"
    via: "next"
    to: "DecisionNode12"
    into: "in"
  - from: "DecisionNode12"
    via: "yes"
    to: "CallNode4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "DispatchFormActionByBreadcrumb2"
    into: "in"
  - from: "CallNode19"
    via: "Yes"
    to: "JumpNode7"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode6"
    into: "in2"
  - from: "DecisionNode4"
    via: "yes"
    to: "CallNode17"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "JoinNode14"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode14"
    into: "in2"
  - from: "CallNode14"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "CallNode16"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "StartNode11"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "CallNode8"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "JoinNode14"
    via: "next"
    to: "UpdatePagelet1"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "JumpNode4"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "KeyMapper3"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "JumpNode10"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "CallNode9"
    into: "in"
  - from: "JoinNode21"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode9"
    into: "in2"
  - from: "CallNode9"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode9"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "JoinNode18"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode10"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode8"
    into: "in"
