flow: "ViewProductAssignmentMapping"
kind: "view"

entries:
  - id: "Start1"
    name: "Prefix"
    mode: "private"
    strict: true
    inputs:
      - key: "ProviderID"
        type: "java.lang.String"
        required: true
  - id: "Start2"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "GetProductDataMappingRule"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductDataMappingRuleSet"
        type: "com.intershop.component.mvc.capi.mapping.ProductDataMappingRuleSet"
        required: true
      - key: "TypeCode"
        type: "java.lang.String"
        required: true
  - id: "StartNode2"
    name: "SetMappingEnabled"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductDataMappingRuleSet"
        type: "com.intershop.component.mvc.capi.mapping.ProductDataMappingRuleSet"
        required: true
      - key: "TypeCode"
        type: "java.lang.String"
        required: true
      - key: "MappingEnabledInteger"
        type: "java.lang.Integer"
        required: true
      - key: "FunctionClassName"
        type: "java.lang.String"
        required: true
  - id: "StartNode3"
    name: "VerifyMappingEnabledValue"
    mode: "private"
    strict: true
    inputs:
      - key: "MappingEnabledValue"
        type: "java.lang.String"
        required: false
  - id: "StartNode4"
    name: "SetMappingsEnabled"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductDataMappingRuleSet"
        type: "com.intershop.component.mvc.capi.mapping.ProductDataMappingRuleSet"
        required: true
      - key: "MappingEnabledInteger"
        type: "java.lang.Integer"
        required: true

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewProductAssignmentMapping-Prefix"
  - id: "Call2"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "Call3"
    type: "call"
    ref: "ProcessProductDataMappingRule-CreateRuleConstruct"
  - id: "Call5"
    type: "call"
    ref: "ViewProductAssignmentMapping-Prefix"
  - id: "CallNode1"
    type: "call"
    ref: "This:GetProductDataMappingRule"
    bindings:
      TypeCode: "\"10\""
  - id: "CallNode4"
    type: "call"
    ref: "ViewProductAssignmentMapping-GetProductDataMappingRule"
  - id: "CallNode5"
    type: "call"
    ref: "This:VerifyMappingEnabledValue"
    bindings:
      MappingEnabledValue: "MappingEnabled"
  - id: "CallNode6"
    type: "call"
    ref: "This:SetMappingsEnabled"
  - id: "CallNode7"
    type: "call"
    ref: "This:SetMappingEnabled"
    bindings:
      TypeCode: "\"10\""
      FunctionClassName: "\"com.intershop.component.mvc.capi.mapping.ProductVariationMappingRule\""
  - id: "CallNode8"
    type: "call"
    ref: "This:SetMappingEnabled"
    bindings:
      TypeCode: "\"12\""
      FunctionClassName: "\"com.intershop.component.mvc.capi.mapping.ProductRetailSetMappingRule\""
  - id: "CallNode9"
    type: "call"
    ref: "This:SetMappingEnabled"
    bindings:
      TypeCode: "\"11\""
      FunctionClassName: "\"com.intershop.component.mvc.capi.mapping.ProductBundleAssignmentMappingRule\""
  - id: "DecisionNode1"
    type: "decision"
    condition: "MappingEnabledValue"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ProductDataMappingRule"
  - id: "End1"
    type: "end"
    strict: true
    outputs:
      - key: "ProductDataMappingRuleSet"
        type: "com.intershop.component.mvc.capi.mapping.ProductDataMappingRuleSet"
        guaranteed: true
      - key: "ProvidingRepository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        guaranteed: true
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ProductDataMappingRule"
        type: "com.intershop.component.mvc.capi.mapping.ProductDataMappingRule"
        guaranteed: false
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "MappingEnabledInteger"
        type: "java.lang.Integer"
        guaranteed: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "GetFirstElementOfIterator2"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      Iterator: "ProductDataMappingRules"
      FirstElement: "ProductDataMappingRule"
  - id: "GetProductDataMappingRuleSet1"
    type: "pipelet"
    ref: "GetProductDataMappingRuleSet"
    bindings:
      DeclaringDomain: "Repository:Domain"
      ProvidingDomain: "ProvidingRepository:Domain"
  - id: "GetProductDataMappingRules2"
    type: "pipelet"
    ref: "GetProductDataMappingRules"
    bindings:
      DeclaringDomain: "ProductDataMappingRuleSet:DeclaringDomain"
      ProvidingDomain: "ProductDataMappingRuleSet:ProvidingDomain"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "ProvidingRepository"
      UUID: "ProviderID"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"(java.lang.Integer)0\""
      OutValue_1: "MappingEnabledInteger"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Syndication"
      WorkingTemplate: "syndication/ProductAssignmentMapping.isml"
  - id: "UpdateCustomAttribute3"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    bindings:
      LocaleInformation: "null"
      ExtensibleObject: "ProductDataMappingRule"
      AttributeType: "\"Integer\""
      AttributeName: "\"Enabled\""
      AttributeValue: "MappingEnabledInteger"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      Locale: "null"
      LocalizedString: "MappingEnabledValue"
      IntegerObject: "MappingEnabledInteger"
      Pattern: "null"

links:
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "CallNode5"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "GetProductDataMappingRuleSet1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "GetProductDataMappingRuleSet1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "VerifyInteger1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "UpdateCustomAttribute3"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "UpdateCustomAttribute3"
    into: "in"
  - from: "GetProductDataMappingRules2"
    via: "next"
    to: "GetFirstElementOfIterator2"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "CallNode7"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "GetFirstElementOfIterator2"
    via: "error"
    to: "EndNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "Call3"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode4"
    into: "in2"
  - from: "StartNode3"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetProductDataMappingRules2"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "GetFirstElementOfIterator2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "CallNode8"
    into: "in"
