flow: "ViewContentOverview"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "GetContentSharingChannel"
    mode: "private"
    strict: true
    inputs:
      - key: "OrganizationDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode3"
    name: "SiteNavigationBar"
    mode: "include"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "GetSelectedMenuItem"
    mode: "private"
    strict: true
    inputs:
      - key: "ApplicationState"
        type: "com.intershop.component.foundation.capi.application.ApplicationState"
        required: true
  - id: "StartNode5"
    name: "GuessContentSharingChannel"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode6"
    name: "ContentSharingChannel"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode7"
    name: "GetMasterEditingPreference"
    mode: "private"
    strict: true
    inputs:
      []

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      OutVector: "PermittedRepositories"
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      Object: "Repository"
      InVector: "PermittedRepositories"
      OutVector: "PermittedRepositories"
  - id: "CallNode1"
    type: "call"
    ref: "This:GetContentSharingChannel"
  - id: "CallNode2"
    type: "call"
    ref: "This:GuessContentSharingChannel"
  - id: "CallNode3"
    type: "call"
    ref: "This:GetContentSharingChannel"
    bindings:
      OrganizationDomain: "CurrentOrganization:OrganizationDomain"
  - id: "CallNode4"
    type: "call"
    ref: "This:GetContentSharingChannel"
    bindings:
      OrganizationDomain: "CurrentOrganization:OrganizationDomain"
  - id: "CallNode5"
    type: "call"
    ref: "ViewContentOverview-GetMasterEditingPreference"
  - id: "CallNode6"
    type: "call"
    ref: "ViewContentOverview-GetMasterEditingPreference"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ContentSharingChannelPreference"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Breadcrumb:Pipeline"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Dummy"
  - id: "DecisionNode4"
    type: "decision"
    condition: "PermittedRepositories:Size"
  - id: "DecisionNode5"
    type: "decision"
    condition: "RepositoryPermissionMap:KeySet"
  - id: "DecisionNode6"
    type: "decision"
    condition: "MasterEditingPreference"
  - id: "DecisionNode7"
    type: "decision"
    condition: "MasterEditingPreference:StringValue"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ContentSharingChannel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        guaranteed: false
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "SelectedMenuItem"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "ContentSharingChannel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        guaranteed: false
      - key: "MasterEditingEnabled"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "ContentSharingChannel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        guaranteed: false
  - id: "EndNode5"
    type: "end"
    strict: true
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "MasterEditingEnabled"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode7"
    type: "end"
    strict: true
    outputs:
      - key: "MasterEditingEnabled"
        type: "java.lang.String"
        guaranteed: false
  - id: "GetDomainByName1"
    type: "pipelet"
    ref: "GetDomainByName"
    bindings:
      DomainName: "ContentSharingChannelPreference:StringValue"
      Domain: "ContentRepositoryDomain"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "String"
    bindings:
      PreferenceDomain: "OrganizationDomain"
      PreferenceKey: "\"ContentSharingChannel\""
      Preference: "ContentSharingChannelPreference"
  - id: "GetDomainPreference2"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "String"
      DefaultPreferenceKey: "MasterPageEditing"
    bindings:
      PreferenceDomain: "CurrentOrganization:OrganizationDomain"
      Preference: "MasterEditingPreference"
  - id: "GetPermissionsByUser1"
    type: "pipelet"
    ref: "GetPermissionsByUser"
    config:
      Permission_Prefix: "SLD"
    bindings:
      AuthorizationObject: "Repository:RepositoryDomain"
      User: "CurrentUser"
      Organization: "null"
      PermissionMap: "RepositoryPermissionMap"
  - id: "GetRepositories1"
    type: "pipelet"
    ref: "GetRepositories"
    config:
      CustomRepositoryTypeCode: 52
  - id: "GetRepositoryByRepositoryDomain1"
    type: "pipelet"
    ref: "GetRepositoryByRepositoryDomain"
    bindings:
      RepositoryDomain: "ContentRepositoryDomain"
      Repository: "ContentSharingChannel"
  - id: "InteractionEnd10"
    type: "interaction"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "PermittedRepositories:First"
      OutValue_1: "ContentSharingChannel"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      User: "CurrentUser"
      Organization: "CurrentOrganization"
      OrganizationDomain: "null"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      User: "CurrentUser"
      Organization: "CurrentOrganization"
  - id: "Pipelet22"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      User: "CurrentUser"
      Organization: "CurrentOrganization"
  - id: "PrepareApplicationView10"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "content/ContentOverview"
      SelectedMenuItem: "MassDataTasks"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "SelectedMenuItem"
      Value: "MasterComponents"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "SelectedMenuItem"
      Value: "Catalogs"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "MasterEditingEnabled"
      Value: false
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "MasterEditingEnabled"
      Value: true
      ValueType: "Dictionary Value"

links:
  - from: "AddObjectToVector1"
    via: "next"
    to: "GetRepositories1"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "PrepareApplicationView10"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "CallNode3"
    via: "ERROR"
    to: "AddObjectToVector1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode4"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetDomainByName1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode3"
    via: "yes"
    to: "LoopNode1"
    into: "loop"
  - from: "DecisionNode4"
    via: "no"
    to: "CallNode6"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "KeyMapper1"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode5"
    via: "yes"
    to: "AddObjectToVector2"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode9"
    into: "in1"
  - from: "DecisionNode6"
    via: "yes"
    to: "DecisionNode7"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "JoinNode9"
    into: "in1"
  - from: "DecisionNode7"
    via: "yes"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "GetDomainByName1"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "GetDomainByName1"
    via: "next"
    to: "GetRepositoryByRepositoryDomain1"
    into: "in"
  - from: "GetDomainPreference1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "GetDomainPreference1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetDomainPreference2"
    via: "error"
    to: "JoinNode11"
    into: "in1"
  - from: "GetDomainPreference2"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "GetPermissionsByUser1"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "GetRepositories1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "GetRepositoryByRepositoryDomain1"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "GetRepositoryByRepositoryDomain1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "JoinNode11"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "JoinNode7"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "LoopNode1"
    via: "do"
    to: "DecisionNode3"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "LoopNode2"
    via: "do"
    to: "GetPermissionsByUser1"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "Pipelet22"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Pipelet2"
    via: "error"
    to: "JoinNode11"
    into: "in1"
  - from: "Pipelet2"
    via: "next"
    to: "GetDomainPreference2"
    into: "in"
  - from: "PrepareApplicationView10"
    via: "next"
    to: "InteractionEnd10"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "Pipelet22"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "Pipelet2"
    into: "in"
