flow: "ViewOrganizationEnterpriseDefinitions"
kind: "view"

entries:
  - id: "Start4"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "DefinitionList"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode14"
    name: "updateDefinitionState"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Allow"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "DefinitionGroups"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Prohibit"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "NoSelectedItem"
    mode: "public"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewOrganizationEnterpriseDefinitions-Prefix"
  - id: "CallNode10"
    type: "call"
    ref: "ViewOrganizationEnterpriseDefinitions-updateDefinitionState"
  - id: "CallNode11"
    type: "call"
    ref: "ViewOrganizationServices-AllowServiceDefinition"
  - id: "CallNode12"
    type: "call"
    ref: "ViewOrganizationServices-GetServiceGroups"
  - id: "CallNode13"
    type: "call"
    ref: "ViewOrganizationServices-ProhibitServiceDefinition"
  - id: "CallNode14"
    type: "call"
    ref: "ViewOrganizationServices-GetServiceDefinitionsOfServiceGroupX"
  - id: "CallNode17"
    type: "call"
    ref: "ViewOrganizationServices-GetCurrentServiceConfigurationRepository"
    bindings:
      OrganizationID: "OrganizationUUID"
  - id: "CallNode2"
    type: "call"
    ref: "ViewOrganizationEnterpriseDefinitions-Prefix"
  - id: "CallNode3"
    type: "call"
    ref: "ViewOrganizationEnterpriseDefinitions-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ViewOrganizationEnterpriseDefinitions-Prefix"
  - id: "CallNode5"
    type: "call"
    ref: "ViewOrganizationEnterpriseDefinitions-updateDefinitionState"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "CallNode9"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CreateStringSplitter1"
    type: "pipelet"
    ref: "CreateStringSplitter"
    config:
      Mode: "First Occurrence"
      Separator: "/"
  - id: "DecisionNode1"
    type: "decision"
    condition: "GroupID"
  - id: "DecisionNode2"
    type: "decision"
    condition: "SelectedObjectUUIDs"
  - id: "DecisionNode4"
    type: "decision"
    condition: "SelectedObjectUUIDs"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewOrganizationEnterpriseDefinitions-DefinitionGroups"
      OutValue_1: "ViewOrganizationEnterpriseDefinitions-DefinitionList"
      OutValue_2: "ViewOrganizationEnterpriseDefinitions-Allow"
      OutValue_3: "ViewOrganizationEnterpriseDefinitions-Prohibit"
    bindings:
      Key_0: "DefinitionGroups"
      Key_1: "DefinitionList"
      SelectionKey: "JumpTarget"
      Key_2: "Allow"
      Key_3: "Prohibit"
  - id: "End2"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "GetOrganization1"
    type: "pipelet"
    ref: "GetOrganization"
    config:
      Source: "PipelineDictionary"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewOrganizationEnterpriseDefinitions-DefinitionList"
  - id: "JumpNode3"
    type: "jump"
    ref: "This:DefinitionList"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewOrganizationEnterpriseDefinitions-NoSelectedItem"
  - id: "JumpNode5"
    type: "jump"
    ref: "ViewOrganizationEnterpriseDefinitions-DefinitionList"
  - id: "JumpNode6"
    type: "jump"
    ref: "ViewOrganizationEnterpriseDefinitions-NoSelectedItem"
  - id: "JumpNode7"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_2: "Splitter:getEnd(itemString)"
      OutValue_2: "ServiceDefinitionID"
      InValue_1: "Splitter:getBegin(itemString)"
      OutValue_1: "GroupID"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_2: "Splitter:getEnd(itemString)"
      OutValue_2: "itemString"
      InValue_1: "Splitter:getBegin(itemString)"
      OutValue_1: "CartridgeID"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ServiceGroupID"
      OutValue_1: "GroupID"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode6"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "organization/OrganizationEnterpriseServiceDefinitionList"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "organization/OrganizationEnterpriseServiceDefinitionGroups"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewOrganizationEnterpriseDefinitions-DefinitionGroups"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "noSelectedItems"
      Value: 1
      ValueType: "Dictionary Value"

links:
  - from: "CallNode2"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Start4"
    via: "next"
    to: "CallNode17"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JumpNode7"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "CallNode10"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "KeyMapper3"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "LoopNode6"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JumpNode6"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JumpNode4"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CreateStringSplitter1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode14"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "LoopNode6"
    via: "do"
    to: "CallNode5"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "CallNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode14"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "LoopNode6"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "SetDictionaryValue5"
    into: "in"
  - from: "SetDictionaryValue5"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "LoopNode1"
    into: "in"
  - from: "CallNode17"
    via: "next"
    to: "GetOrganization1"
    into: "in"
  - from: "GetOrganization1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "StartNode14"
    via: "next"
    to: "CreateStringSplitter1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "CallNode5"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "LoopNode6"
    into: "loop"
