flow: "ViewEmailMarketingPreferences_52"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Prefix"
    mode: "private"
    strict: true
    inputs:
      - key: "Domain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
  - id: "StartNode5"
    name: "TestConnection"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode0"
    type: "call"
  - id: "CallNode1"
    type: "call"
    ref: "ViewEmailMarketingPreferences_52-Prefix"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
  - id: "CallNode2"
    type: "call"
    ref: "ViewEmailMarketingPreferences_52-Prefix"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
  - id: "CallNode7"
    type: "call"
  - id: "CallNode8"
    type: "call"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormResource: "EmailMarketing"
      FormName: "EmailMarketingPreferencesForm"
    bindings:
      Locale: "CurrentRequest:Locale"
      Form: "EmailMarketingPreferencesForm"
  - id: "DecisionNode0"
    type: "decision"
    condition: "ActiveProviderDefinition"
  - id: "DecisionNode1"
    type: "decision"
    condition: "RUN_TEST_CONNECTION"
  - id: "DecisionNode11"
    type: "decision"
    condition: "ActivatedProviderDefinition:ProviderName"
  - id: "DecisionNode12"
    type: "decision"
    condition: "ActiveProviderDefinition"
  - id: "DecisionNode13"
    type: "decision"
    condition: "EmailMarketingPreferencesForm:Provider:Value"
  - id: "DecisionNode6"
    type: "decision"
    condition: "ActivatedProviderDefinition"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewEmailMarketingPreferences_52-Update"
      OutValue_1: "ViewEmailMarketingPreferences_52-Edit"
      OutValue_2: "ViewEmailMarketingPreferences_52-TestConnection"
      OutValue_3: "ViewEmailMarketingPreferences_52-Update"
    bindings:
      Key_0: "update"
      Key_1: "reset"
      Key_2: "test"
      Key_3: "apply"
      DefaultButton: "\"update\""
      SelectionKey: "JumpTarget"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ActiveProviderDefinition"
        type: "com.intershop.component.marketing.capi.emailmarketing.EmailMarketingProviderDefinition"
        guaranteed: false
      - key: "ProviderDefinitions"
        type: "java.util.Collection"
        guaranteed: false
      - key: "AbandonedBasketTimeout"
        type: "java.lang.Double"
        guaranteed: false
  - id: "GetAllProviderDefinitions2"
    type: "pipelet"
    ref: "GetAllProviderDefinitions"
  - id: "GetDomainPreference0"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "EmailMarketingProviderLink"
      Type: "String"
    bindings:
      PreferenceDomain: "CurrentChannel:RepositoryDomain"
      PreferenceStringValue: "EmailMarketingProviderLink"
  - id: "GetDomainPreference2"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "AbandonedBasketTimeout"
      Type: "Double"
    bindings:
      PreferenceDomain: "CurrentChannel:RepositoryDomain"
      PreferenceDoubleValue: "AbandonedBasketTimeout"
  - id: "GetProviderDefinition0"
    type: "pipelet"
    ref: "GetProviderDefinition"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
      ProviderDefinition: "ActivatedProviderDefinition"
  - id: "GetProviderDefinition2"
    type: "pipelet"
    ref: "GetProviderDefinition"
    bindings:
      ProviderDefinition: "ActiveProviderDefinition"
  - id: "InteractionNode0"
    type: "interaction"
  - id: "JoinNode0"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode15"
    type: "join"
  - id: "JoinNode16"
    type: "join"
  - id: "JoinNode17"
    type: "join"
  - id: "JoinNode19"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode21"
    type: "join"
  - id: "JoinNode22"
    type: "join"
  - id: "JoinNode23"
    type: "join"
  - id: "JoinNode24"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JumpNode0"
    type: "jump"
    ref: "ViewEmailMarketingPreferences_52-Edit"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "LookupProvider3"
    type: "pipelet"
    ref: "LookupProvider"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
  - id: "PrepareApplicationView0"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "channel/ChannelEmailMarketingPreferences_52"
      SelectedMenuItem: "ChannelDomainPreference"
  - id: "RemoveDictionaryValue0"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "ActiveProviderDefinition"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "EmailMarketingPreferencesForm"
  - id: "RemoveDomainPreference0"
    type: "pipelet"
    ref: "RemoveDomainPreference"
    bindings:
      PreferenceDomain: "CurrentChannel:RepositoryDomain"
      PreferenceKey: "\"EmailMarketingProviderLink\""
  - id: "RemoveDomainPreference4"
    type: "pipelet"
    ref: "RemoveDomainPreference"
    bindings:
      PreferenceKey: "\"AbandonedBasketTimeout\""
      PreferenceDomain: "CurrentChannel:RepositoryDomain"
  - id: "SetDictionaryValue0"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewEmailMarketingPreferences_52-Edit"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "RUN_TEST_CONNECTION"
      Value: true
      ValueType: "Dictionary Value"
  - id: "SetDomainPreference0"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "EmailMarketingProviderLink"
      Type: "String"
    bindings:
      PreferenceDomain: "CurrentChannel:RepositoryDomain"
      PreferenceStringValue: "EmailMarketingPreferencesForm:LinkToProviderTool:Value"
  - id: "SetDomainPreference2"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "AbandonedBasketTimeout"
      Type: "Double"
    bindings:
      PreferenceDomain: "CurrentChannel:RepositoryDomain"
      PreferenceDoubleValue: "EmailMarketingPreferencesForm:AbandonedBasketTimeout:Value"
  - id: "SetProvider0"
    type: "pipelet"
    ref: "SetProvider"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
      ProviderName: "EmailMarketingPreferencesForm:Provider:Value"
  - id: "SetProvider2"
    type: "pipelet"
    ref: "SetProvider"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
      ProviderName: "EmailMarketingPreferencesForm:Provider:Value"
  - id: "TestConnection1"
    type: "pipelet"
    ref: "TestConnection"
  - id: "ValidateForm0"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "EmailMarketingPreferencesForm"

links:
  - from: "CallNode0"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode14"
    into: "in1"
  - from: "CallNode7"
    via: "ERROR"
    to: "JoinNode0"
    into: "in1"
  - from: "CallNode7"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CreateForm1"
    via: "next"
    to: "ValidateForm0"
    into: "in"
  - from: "DecisionNode0"
    via: "no"
    to: "JoinNode15"
    into: "in1"
  - from: "DecisionNode0"
    via: "yes"
    to: "CallNode0"
    into: "in"
  - from: "DecisionNode11"
    via: "no"
    to: "JoinNode13"
    into: "in1"
  - from: "DecisionNode11"
    via: "yes"
    to: "CallNode7"
    into: "in"
  - from: "DecisionNode12"
    via: "no"
    to: "JoinNode13"
    into: "in1"
  - from: "DecisionNode12"
    via: "yes"
    to: "DecisionNode11"
    into: "in"
  - from: "DecisionNode13"
    via: "no"
    to: "JoinNode14"
    into: "in1"
  - from: "DecisionNode13"
    via: "yes"
    to: "JoinNode16"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "LookupProvider3"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "RemoveDictionaryValue0"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "DecisionNode12"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue0"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetAllProviderDefinitions2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "GetDomainPreference0"
    via: "error"
    to: "JoinNode15"
    into: "in1"
  - from: "GetDomainPreference0"
    via: "next"
    to: "GetDomainPreference2"
    into: "in"
  - from: "GetDomainPreference2"
    via: "error"
    to: "JoinNode24"
    into: "in1"
  - from: "GetDomainPreference2"
    via: "next"
    to: "JoinNode23"
    into: "in1"
  - from: "GetProviderDefinition0"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "GetProviderDefinition2"
    via: "next"
    to: "GetAllProviderDefinitions2"
    into: "in"
  - from: "JoinNode0"
    via: "next"
    to: "GetDomainPreference0"
    into: "in"
  - from: "JoinNode13"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode14"
    via: "next"
    to: "DecisionNode0"
    into: "in"
  - from: "JoinNode15"
    via: "next"
    to: "JoinNode24"
    into: "in1"
  - from: "JoinNode16"
    via: "next"
    to: "SetProvider2"
    into: "in"
  - from: "JoinNode17"
    via: "next"
    to: "SetProvider0"
    into: "in"
  - from: "JoinNode19"
    via: "next"
    to: "JoinNode22"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "SetDomainPreference0"
    into: "in"
  - from: "JoinNode21"
    via: "next"
    to: "JoinNode17"
    into: "in1"
  - from: "JoinNode22"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "JoinNode23"
    via: "next"
    to: "PrepareApplicationView0"
    into: "in"
  - from: "JoinNode24"
    via: "next"
    to: "JoinNode23"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "LookupProvider3"
    via: "next"
    to: "TestConnection1"
    into: "in"
  - from: "PrepareApplicationView0"
    via: "next"
    to: "InteractionNode0"
    into: "in"
  - from: "RemoveDictionaryValue0"
    via: "next"
    to: "RemoveDomainPreference0"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "JumpNode0"
    into: "in"
  - from: "RemoveDomainPreference0"
    via: "error"
    to: "JoinNode19"
    into: "in1"
  - from: "RemoveDomainPreference0"
    via: "next"
    to: "RemoveDomainPreference4"
    into: "in"
  - from: "RemoveDomainPreference4"
    via: "error"
    to: "JoinNode19"
    into: "in1"
  - from: "RemoveDomainPreference4"
    via: "next"
    to: "JoinNode22"
    into: "in1"
  - from: "SetDictionaryValue0"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "SetDomainPreference0"
    via: "error"
    to: "JoinNode21"
    into: "in1"
  - from: "SetDomainPreference0"
    via: "next"
    to: "SetDomainPreference2"
    into: "in"
  - from: "SetDomainPreference2"
    via: "error"
    to: "JoinNode21"
    into: "in1"
  - from: "SetDomainPreference2"
    via: "next"
    to: "JoinNode17"
    into: "in1"
  - from: "SetProvider0"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "SetProvider2"
    via: "next"
    to: "GetProviderDefinition0"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "GetProviderDefinition2"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "TestConnection1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "ValidateForm0"
    via: "error"
    to: "DecisionNode13"
    into: "in"
  - from: "ValidateForm0"
    via: "next"
    to: "JoinNode16"
    into: "in1"
