flow: "ViewUserGroupUsersSelection_52"
kind: "view"

entries:
  - id: "Start1"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start10"
    name: "Back"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start31"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Search"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "ListSimpleSearch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call5"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call7"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode1"
    type: "call"
    ref: "ViewUserGroupUsersSelection_52-Search"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessOrganization_52-GetConsumerOrg"
  - id: "CallNode3"
    type: "call"
    ref: "ViewUserGroupUsersSelection_52-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ViewUserGroupUsersSelection_52-Prefix"
  - id: "CallNode5"
    type: "call"
    ref: "ViewUserGroupUsersSelection_52-Prefix"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessUserList-BySimpleSearch"
  - id: "CheckForEmptyIterator1"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "UUIDIterator"
  - id: "CheckForEmptyString1"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "SearchTerm"
  - id: "Decision1"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision2"
    type: "decision"
    condition: "UserGroupID"
  - id: "Decision3"
    type: "decision"
    condition: "UserGroup"
  - id: "Decision4"
    type: "decision"
    condition: "SearchTerm"
  - id: "DispatchFormAction11"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewUserGroupUsersSelection_52-Back"
      OutValue_1: "ViewUserGroupUsersSelection_52-Create"
      OutValue_2: "ViewUserGroupUsersSelection_52-ListSimpleSearch"
      PagingPipeline: "ViewUserGroupUsersSelection_52-Paging"
    bindings:
      Key_0: "cancel"
      Key_1: "assign"
      Key_2: "simpleSearch"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "user/GetUserGroupUsersSelection"
      DefaultPageSize: 15
      Datasource: "default"
      ParameterName_01: "UserGroupDomainUUID"
      ParameterName_02: "UserGroupID"
    bindings:
      ParameterValue_01: "UserGroup:Domain:UUID"
      ParameterValue_02: "UserGroup:ID"
      SearchResult: "Users"
      PageSize: "null"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "UserGroupUsers"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocatorName: "null"
  - id: "GetPageLocator11"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "UserGroupUsersSelection"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocatorName: "null"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Users"
      PageableID: "PageLocator:PageableID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump21"
    type: "jump"
    ref: "ViewUserGroupUsers_52-ListAll"
  - id: "Jump22"
    type: "jump"
    ref: "ViewUserGroupUsersSelection_52-Paging"
  - id: "Jump5"
    type: "jump"
  - id: "Jump6"
    type: "jump"
    ref: "ViewUserGroupUsers_52-ListAll"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "CurrentPageNumber"
      OutValue_1: "PageNumber"
  - id: "Loop1"
    type: "loop"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "DetermineUserGroup"
    bindings:
      CurrentDomain: "Organization:OrganizationDomain:Domain"
      UserGroupID: "UserGroupID"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_10: "UserGroup:Domain"
      OutValue_10: "UserDomain"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "AssignUserToOrganizationRole"
    bindings:
      OrganizationRole: "UserGroup"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "CreateUserGroupMembershipLookupHelper"
    config:
      Membership: "Direct"
    bindings:
      UserGroup: "UserGroup"
      UserGroupMembershipLookupHelper: "Lookup"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "SetPageLocatorParameter"
    config:
      DefaultParameterName: "SearchTerm"
    bindings:
      ParameterName: "null"
      ParameterValue: "SearchTerm"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "UserUUID"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelUserGroup"
      WorkingTemplate: "user/UserGroupUsersSelectUser_52"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "SearchTerm"
      RemoveFormValues: true
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "SearchTerm"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Users"
  - id: "SetPage3"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Users"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewUserGroupUsersSelection_52-Paging"
      DefaultPageLocatorName: "UserGroupUsersSelection"
    bindings:
      HandlerPipeline: "null"
      PageLocatorName: "null"
      Pageable: "Users"
  - id: "UpdatePageSize1"
    type: "pipelet"
    ref: "UpdatePageSize"
    config:
      DefaultPageSize: 15
    bindings:
      PageSize: "null"
      PageableIterator: "Users"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      Locale: "null"
      LocalizedString: "PageNumber"
      Pattern: "null"

links:
  - from: "Call4"
    via: "next"
    to: "GetPageLocator11"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "DispatchFormAction11"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "SetPage3"
    via: "next"
    to: "Join5"
    into: "in2"
  - from: "Join1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "CallNode2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Join5"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "Jump21"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join5"
    into: "in3"
  - from: "GetPageLocator1"
    via: "error"
    to: "Jump6"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "GetPageLocator1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "Loop1"
    via: "do"
    to: "Pipelet8"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "Join3"
    into: "in2"
  - from: "Decision2"
    via: "no"
    to: "Join3"
    into: "in1"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction11"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "GetPageLocator11"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "Jump22"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "error"
    to: "KeyMapper2"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "CheckForEmptyIterator1"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "Decision2"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "StartNode1"
    via: "next"
    to: "CheckForEmptyString1"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "error"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "ExecutePageableQuery1"
    via: "error"
    to: "EndNode3"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "UpdatePageSize1"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "SetPage2"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "SetPageLocator1"
    via: "next"
    to: "Decision4"
    into: "in"
  - from: "Decision4"
    via: "yes"
    to: "Pipelet6"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "Join2"
    into: "in3"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "Start31"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "UpdatePageSize1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Join3"
    into: "in3"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage3"
    into: "in"
  - from: "Start10"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
