flow: "ViewSyndication_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "ProductDetails"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "SelectCatalogSource"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "SelectProductSource"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "DispatchSelectProductSource"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "DispatchSelectCatalogSource"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "GetProductLinks"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "MVCProcessProduct-Start"
  - id: "Call10"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "Call11"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "Call2"
    type: "call"
    ref: "ViewSyndication_52-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ViewSyndication_52-Prefix"
  - id: "Call4"
    type: "call"
    ref: "DetermineRepositories-ParentChannel"
  - id: "Call5"
    type: "call"
    ref: "ViewSyndication_52-Prefix"
  - id: "Call6"
    type: "call"
    ref: "ViewSyndication_52-Prefix"
  - id: "Call7"
    type: "call"
    ref: "DetermineRepositories-ParentChannel"
  - id: "Call8"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "Call9"
    type: "call"
    ref: "DetermineRepositories-ParentChannel"
  - id: "CallNode1"
    type: "call"
    ref: "ViewSyndication_52-GetProductLinks"
  - id: "CallNode2"
    type: "call"
    ref: "DetermineProduct_52-MasterRepositoryProduct"
  - id: "CallNode3"
    type: "call"
    ref: "DetermineProduct_52-ParentChannelRepositoryProduct"
  - id: "CreateProductIdentifierLookupHelper1"
    type: "pipelet"
    ref: "CreateProductIdentifierLookupHelper"
    config:
      LookupType: "ProductDomainLookup"
    bindings:
      ProductDomain: "Repository:RepositoryDomain"
  - id: "Decision1"
    type: "decision"
    condition: "Organization:TypeCode"
  - id: "Decision2"
    type: "decision"
    condition: "Organization:TypeCode"
  - id: "Decision3"
    type: "decision"
    condition: "SourceRepository"
  - id: "Decision4"
    type: "decision"
    condition: "SourceRepository"
  - id: "Decision5"
    type: "decision"
    condition: "SourceRepository"
  - id: "Decision6"
    type: "decision"
    condition: "SourceRepository"
  - id: "DecisionNode1"
    type: "decision"
    condition: "SourceRepository"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewSyndication_52-DispatchSelectProductSource"
      OutValue_1: "ViewSyndication_52-DispatchSelectCatalogSource"
      OutValue_2: "ViewSyndication_52-Start"
    bindings:
      Key_0: "selectProductSource"
      Key_1: "selectCatalogSource"
      Key_2: "cancel"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "ExecuteObjectsQuery1"
    type: "pipelet"
    ref: "ExecuteObjectsQuery"
    config:
      Datasource: "current ORM connection"
      QueryName: "product/GetOutgoingProductLinksByProductUUID"
      ParameterName_01: "Product"
    bindings:
      ParameterValue_01: "Product"
  - id: "GetAdditionalContents1"
    type: "pipelet"
    ref: "GetAdditionalContents"
    bindings:
      AdditionalContentIterator: "Additionals"
      ExtensibleObject: "Product"
  - id: "GetCurrencies1"
    type: "pipelet"
    ref: "GetCurrencies"
    config:
      Method: "Active Currencies"
    bindings:
      Domain: "OrganizationDomain"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
  - id: "GetOrganizationByDomain1"
    type: "pipelet"
    ref: "GetOrganizationByDomain"
    bindings:
      Organization: "ParentOrganization"
      OrganizationDomain: "ParentChannelRepository:OwningDomain"
  - id: "GetOrganizationByDomain2"
    type: "pipelet"
    ref: "GetOrganizationByDomain"
    bindings:
      Organization: "ParentOrganization"
      OrganizationDomain: "ParentChannelRepository:OwningDomain"
  - id: "GetSortedAttributes1"
    type: "pipelet"
    ref: "GetSortedAttributes"
    config:
      Prefix: "Attrib"
    bindings:
      AttributeNames: "CustomAttributeNames"
      AttributeValues: "CustomAttributeValues"
      ExtensibleObject: "Product"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "InteractionEnd5"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump2"
    type: "jump"
    ref: "ViewSyndicationParentChannelProducts_52-Search"
  - id: "Jump3"
    type: "jump"
    ref: "ViewSyndicationMasterProducts_52-Search"
  - id: "Jump4"
    type: "jump"
    ref: "ViewSyndicationMasterCatalogs_52-Start"
  - id: "Jump5"
    type: "jump"
    ref: "ViewSyndicationParentChannelCatalogs_52-Start"
  - id: "Jump6"
    type: "jump"
    ref: "ViewSyndication_52-SelectProductSource"
  - id: "Jump7"
    type: "jump"
    ref: "ViewSyndication_52-SelectCatalogSource"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewProduct_52-ErrorProductNotAvailable"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewProduct_52-ErrorProductNotAvailable"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ParentChannelRepository:Domain:UUID"
      OutValue_1: "SourceDomainUUID"
  - id: "KeyMapper14"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ParentChannelRepository"
      OutValue_1: "Repository"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Repository:Domain:UUID"
      OutValue_1: "SourceDomainUUID"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/SyndicationOverview_52"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/SyndicationProductDetails_52"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/SyndicationSelectCatalogSource_52"
  - id: "PrepareApplicationView4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/SyndicationSelectProductSource_52"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ContentType"
      Value: "All"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "CallNode2"
    into: "in"
  - from: "GetSortedAttributes1"
    via: "next"
    to: "GetCurrencies1"
    into: "in"
  - from: "CreateProductIdentifierLookupHelper1"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "GetAdditionalContents1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode3"
    into: "in"
  - from: "GetCurrencies1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Call9"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join1"
    into: "in3"
  - from: "Call5"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "Call7"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join2"
    into: "in3"
  - from: "Join2"
    via: "next"
    to: "PrepareApplicationView4"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "KeyMapper14"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "GetOrganizationByDomain2"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "GetOrganizationByDomain1"
    into: "in"
  - from: "GetOrganizationByDomain1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "GetOrganizationByDomain2"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "PrepareApplicationView4"
    via: "next"
    to: "InteractionEnd5"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "Decision5"
    via: "yes"
    to: "Jump3"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "Decision4"
    into: "in"
  - from: "Decision4"
    via: "yes"
    to: "Call4"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Decision5"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "Jump2"
    into: "in"
  - from: "Decision5"
    via: "no"
    to: "Jump6"
    into: "in"
  - from: "Decision6"
    via: "no"
    to: "Jump7"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "Decision6"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "ExecuteObjectsQuery1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "ExecuteObjectsQuery1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "KeyMapper14"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "GetAdditionalContents1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "CallNode1"
    via: "next"
    to: "CreateProductIdentifierLookupHelper1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "CallNode3"
    via: "error-product-not-available"
    to: "JumpNode1"
    into: "in"
  - from: "GetAdditionalContents1"
    via: "error"
    to: "Join3"
    into: "in3"
  - from: "CallNode2"
    via: "error-product-not-available"
    to: "JumpNode2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "Decision6"
    via: "yes"
    to: "Call11"
    into: "in"
  - from: "Call11"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "GetSortedAttributes1"
    into: "in"
