flow: "ViewAffiliatePartnerPrograms_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewAffiliatePartnerPrograms_52-Prefix"
  - id: "Call2"
    type: "call"
    ref: "ViewAffiliatePartnerPrograms_52-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call5"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "CreatePageableFromIterator1"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    config:
      Pagesize: 10
    bindings:
      Iterator: "UnpagedAffiliatePrograms"
      Pageable: "AffiliatePrograms"
  - id: "DeterminePageable1"
    type: "pipelet"
    ref: "DeterminePageable"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewAffiliateProgram_52-New"
      OutValue_1: "ViewAffiliatePartnerPrograms_52-Paging"
      OutValue_2: "ViewAffiliatePartnerPrograms_52-Delete"
      OutValue_3: "ViewAffiliatePartnerPrograms_52-Paging"
      OutValue_4: "ViewAffiliatePartnerList_52-ListAll"
    bindings:
      Key_0: "new"
      Key_1: "confirmDelete"
      Key_2: "delete"
      Key_3: "cancelDelete"
      Key_4: "back"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "GetAccountByOwner1"
    type: "pipelet"
    ref: "GetAccountByOwner"
    config:
      DefaultTypeCode: 50
    bindings:
      Owner: "AffiliateProgram"
      Account: "AffiliateProgramAccount"
      TypeCode: "null"
  - id: "GetAffiliatePartnerByUUID1"
    type: "pipelet"
    ref: "GetAffiliatePartnerByUUID"
  - id: "GetAffiliateProgramByUUID1"
    type: "pipelet"
    ref: "GetAffiliateProgramByUUID"
  - id: "GetAffiliatePrograms1"
    type: "pipelet"
    ref: "GetAffiliatePrograms"
    bindings:
      AffiliatePrograms: "UnpagedAffiliatePrograms"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump3"
    type: "jump"
    ref: "ViewAffiliatePartnerPrograms_52-ListAll"
  - id: "Loop1"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/AffiliatePartnerPrograms_52"
  - id: "RemoveAccount1"
    type: "pipelet"
    ref: "RemoveAccount"
    config:
      RemoveTransactions: "True"
    bindings:
      Account: "AffiliateProgramAccount"
  - id: "RemoveAffiliateProgram1"
    type: "pipelet"
    ref: "RemoveAffiliateProgram"
  - id: "RemovePromotionCodeGroupUserGroupAssignments1"
    type: "pipelet"
    ref: "RemovePromotionCodeGroupUserGroupAssignments"
    bindings:
      UserGroup: "AffiliateProgram:ProgramUserGroup"
  - id: "SwitchPage1"
    type: "pipelet"
    ref: "SwitchPage"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "CreatePageableFromIterator1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "DeterminePageable1"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "Join2"
    via: "next"
    to: "GetAffiliatePrograms1"
    into: "in"
  - from: "DeterminePageable1"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "Call1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Call2"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "DeterminePageable1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Loop1"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetAffiliateProgramByUUID1"
    into: "in"
  - from: "GetAccountByOwner1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "RemoveAffiliateProgram1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "GetAffiliateProgramByUUID1"
    via: "error"
    to: "Join3"
    into: "in3"
  - from: "SwitchPage1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "GetAccountByOwner1"
    via: "next"
    to: "RemoveAccount1"
    into: "in"
  - from: "GetAffiliateProgramByUUID1"
    via: "next"
    to: "GetAccountByOwner1"
    into: "in"
  - from: "RemoveAccount1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "RemovePromotionCodeGroupUserGroupAssignments1"
    into: "in"
  - from: "RemovePromotionCodeGroupUserGroupAssignments1"
    via: "next"
    to: "RemoveAffiliateProgram1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "SwitchPage1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "GetAffiliatePartnerByUUID1"
    into: "in"
  - from: "GetAffiliatePartnerByUUID1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "GetAffiliatePrograms1"
    via: "next"
    to: "CreatePageableFromIterator1"
    into: "in"
