flow: "ViewApplicationDetails"
kind: "process"

entries:
  - id: "Start1"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewApplicationDetails-Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "ViewApplicationDetails-Prefix"
  - id: "CheckForEmptyString2"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "DomainStatus"
  - id: "CreateWebForm2"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "ServerGroup"
      param.1.required: false
      param.1.rule: ""
      param.2.name: "HTTPS"
      param.2.required: false
      param.2.rule: "^(true|false)$"
      param.3.name: "DomainStatus"
      param.3.required: false
      param.3.rule: ""
      param.4.name: "URLRewriting"
      param.4.required: false
      webform-id: "UpdateSite"
      param.4.rule: "^(Enabled|Disabled)$"
    bindings:
      WebForm: "UpdateSite"
  - id: "DecisionNode1"
    type: "decision"
    condition: "DomainUUID"
  - id: "DecisionNode3"
    type: "decision"
    condition: "New_OrganizationHTTPS"
  - id: "DecisionNode4"
    type: "decision"
    condition: "CurrentDomain:UUID"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_3: "ViewApplicationDetails-Update"
      OutValue_5: "ViewApplicationList-Paging"
    bindings:
      Key_3: "update"
      Key_5: "backToList"
      SelectionKey: "JumpTarget"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "GetWebForm3"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "UpdateSite"
    bindings:
      WebForm: "UpdateSite"
  - id: "InteractionEnd6"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "Join3"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "Jump7"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewApplicationDetails-Edit"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewApplicationList-ListAll"
  - id: "KeyMapper7"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "UpdateSite:ServerGroup:Value"
      InValue_2: "UpdateSite:DomainStatus:Value"
      OutValue_1: "ServerGroup"
      OutValue_2: "DomainStatus"
  - id: "LoadRewriteRules1"
    type: "pipelet"
    ref: "LoadRewriteRules"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetDomainByUUID"
    bindings:
      Domain: "Site"
  - id: "Pipelet12"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "HTTPSRequired"
      Type: "String"
    bindings:
      PreferenceDomain: "Site"
      PreferenceKey: "null"
      PreferenceStringValue: "Old_OrganizationHTTPS"
      Preference: "null"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
  - id: "Pipelet13"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "HTTPSRequired"
      Type: "String"
    bindings:
      PreferenceDomain: "Site"
      PreferenceKey: "null"
      PreferenceStringValue: "New_OrganizationHTTPS"
      Preference: "null"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "HTTPSRequired"
      DefaultPreferenceValue: false
      Type: "String"
    bindings:
      PreferenceDomain: "Site"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceKey: "null"
      PreferenceStringValue: "UpdateSite:HTTPS:Value"
      PreferenceValue: "null"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "HTTPSRequired"
      Type: "String"
    bindings:
      Preference: "null"
      PreferenceDomain: "Site"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceKey: "null"
      PreferenceStringValue: "HTTPS"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "URLRewriteEnabled"
      Type: "String"
    bindings:
      Preference: "null"
      PreferenceDomain: "Site"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceKey: "null"
      PreferenceStringValue: "URLRewriting"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "URLRewriteEnabled"
      DefaultPreferenceValue: "Disabled"
      Type: "String"
    bindings:
      PreferenceDomain: "Site"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceKey: "null"
      PreferenceStringValue: "UpdateSite:URLRewriting:Value"
      PreferenceValue: "null"
  - id: "PrepareApplicationView5"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Enterprises"
      WorkingTemplate: "organization/ApplicationEdit"
  - id: "Text1"
    type: "text"
  - id: "UpdateDomain1"
    type: "pipelet"
    ref: "UpdateDomain"
    bindings:
      Domain: "Site"
      DomainDescription: "null"
      DomainDisplayName: "null"
      DomainInvalidatePageCache: "null"
      DomainPageCachingAllowed: "null"
      DomainStaticContentMaxAge: "null"
      LocaleID: "null"
  - id: "UpdateDomain2"
    type: "pipelet"
    ref: "UpdateDomain"
    bindings:
      Domain: "Site"
      DomainDescription: "null"
      DomainDisplayName: "null"
      DomainInvalidatePageCache: "null"
      DomainPageCachingAllowed: "null"
      DomainStaticContentMaxAge: "null"
      DomainStatus: "null"
      LocaleID: "null"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "UpdateSite"
    bindings:
      WebForm: "UpdateSite"
  - id: "ValidateWebForm2"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "UpdateSite"

links:
  - from: "Pipelet1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CreateWebForm2"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "GetWebForm3"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "LoadRewriteRules1"
    into: "in"
  - from: "UpdateDomain1"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "LoadRewriteRules1"
    via: "next"
    to: "Pipelet12"
    into: "in"
  - from: "ValidateWebForm2"
    via: "error"
    to: "Join3"
    into: "in2"
  - from: "PrepareApplicationView5"
    via: "next"
    to: "InteractionEnd6"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "ValidateWebForm2"
    via: "next"
    to: "KeyMapper7"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetWebForm3"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "DecisionNode1"
    via: "no"
    to: "JumpNode2"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump7"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "CheckForEmptyString2"
    via: "next"
    to: "UpdateDomain1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "CreateWebForm2"
    into: "in"
  - from: "UpdateDomain2"
    via: "next"
    to: "Join6"
    into: "in3"
  - from: "CheckForEmptyString2"
    via: "error"
    to: "UpdateDomain2"
    into: "in"
  - from: "Pipelet12"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "Pipelet13"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "GetWebForm3"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "InteractionNode2"
    into: "in"
  - from: "KeyMapper7"
    via: "next"
    to: "CheckForEmptyString2"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "PrepareApplicationView5"
    into: "in"
  - from: "Pipelet13"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "UpdateWebForm2"
    via: "next"
    to: "ValidateWebForm2"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "DecisionNode3"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode5"
    into: "in2"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode5"
    into: "in1"
