flow: "ViewPaymentMethodList_52"
kind: "view"

entries:
  - id: "Start13"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      - key: "ProductUUID"
        type: "java.lang.String"
        required: false
      - key: "ProductRefIDs"
        type: "java.lang.String"
        required: false
  - id: "StartNode1"
    name: "MoveUp"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "MoveDown"
    mode: "public"
    strict: false
    inputs:
      []

steps:
  - id: "AddEntryToMap1"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "AssignmentTypes"
      Key: "PaymentConfiguration:UUID"
      OutMap: "AssignmentTypes"
      Value: "AssignmentType"
  - id: "Call1"
    type: "call"
    ref: "ProcessPayment_52-GetPaymentMethodAssignmentType"
  - id: "CallNode1"
    type: "call"
    ref: "ViewPaymentMethodList_52-Update"
  - id: "CallNode2"
    type: "call"
    ref: "ViewPaymentMethodList_52-Update"
  - id: "DecisionNode1"
    type: "decision"
    condition: "SelectedObjectUUIDs"
  - id: "DecisionNode2"
    type: "decision"
    condition: "SelectedObjectUUIDs"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPaymentMethodList_52-MoveUp"
      OutValue_1: "ViewPaymentMethodList_52-MoveDown"
    bindings:
      Key_0: "moveUp.x"
      SelectionKey: "JumpTarget"
      Key_1: "moveDown.x"
  - id: "End13"
    type: "end"
    strict: false
  - id: "GetFormSelection5"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedObjectUUID"
    bindings:
      Selection: "SelectedObjectUUIDs"
  - id: "GetFormSelection6"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "ObjectUUID"
    bindings:
      Selection: "AllObjectUUIDs"
  - id: "GetPaymentConfigurationsByDomain1"
    type: "pipelet"
    ref: "GetPaymentConfigurationsByDomain"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewPaymentMethodList_52-ListAll"
  - id: "JumpNode2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewPaymentMethodList_52-ListAll"
  - id: "Loop1"
    type: "loop"
  - id: "MovePaymentConfigurationPositions1"
    type: "pipelet"
    ref: "MovePaymentConfigurationPositions"
    config:
      MoveDirection: "MoveUp"
    bindings:
      AssignedDomain: "CurrentChannel:RepositoryDomain"
      PaymentConfigurationUUIDs: "SortedPaymentConfigurationIterator"
  - id: "MovePaymentConfigurationPositions2"
    type: "pipelet"
    ref: "MovePaymentConfigurationPositions"
    config:
      MoveDirection: "MoveDown"
    bindings:
      AssignedDomain: "CurrentChannel:RepositoryDomain"
      PaymentConfigurationUUIDs: "SortedPaymentConfigurationIterator"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "PurchaseOrderList"
      WorkingTemplate: "payment/PaymentMethodList_52.isml"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_SELECTION_MOVE_UP"
      ValueType: "Dictionary Value"
      Value: true
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_SELECTION_MOVE_DOWN"
      ValueType: "Dictionary Value"
      Value: true
  - id: "Text1"
    type: "text"
  - id: "UpdateClipboard5"
    type: "pipelet"
    ref: "UpdateClipboard"
    config:
      SessionRegistrationID: "Clipboard"
      StoreFormValues: "No"
    bindings:
      UUIDIterator: "SortedPaymentConfigurationIterator"

links:
  - from: "Pipelet2"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "MovePaymentConfigurationPositions1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "MovePaymentConfigurationPositions2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "MovePaymentConfigurationPositions1"
    into: "in"
  - from: "MovePaymentConfigurationPositions2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetPaymentConfigurationsByDomain1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "GetFormSelection6"
    via: "next"
    to: "GetFormSelection5"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "GetFormSelection5"
    via: "next"
    to: "UpdateClipboard5"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "Start13"
    via: "next"
    to: "GetFormSelection6"
    into: "in"
  - from: "AddEntryToMap1"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "DecisionNode1"
    via: "no"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "UpdateClipboard5"
    via: "next"
    to: "End13"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "AddEntryToMap1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "Call1"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "GetPaymentConfigurationsByDomain1"
    via: "next"
    to: "Loop1"
    into: "in"
