flow: "ViewRecentlyViewedItems"
kind: "view"

entries:
  - id: "StartNode1"
    name: "ClearAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "DetermineRepositories-Current"
  - id: "CallNode2"
    type: "call"
    ref: "ViewData-SecureForBrowserBack"
  - id: "ClearAllRecentlyViewedItems1"
    type: "pipelet"
    ref: "ClearAllRecentlyViewedItems"
    bindings:
      Domain: "Repository:Domain"
  - id: "ClearAllRecentlyViewedItems2"
    type: "pipelet"
    ref: "ClearAllRecentlyViewedItems"
    bindings:
      Domain: "CurrentDomain"
  - id: "JoinNode1"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewRecentlyViewedItems-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewPage-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_3: "\"ViewRecentlyViewedItems-Start\""
      OutValue_3: "JumpTarget"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_3: "\"systempage.browsingHistory.pagelet2-systempage.browsingHistory\""
      OutValue_3: "PageletEntryPointID"

links:
  - from: "CallNode1"
    via: "ERROR"
    to: "ClearAllRecentlyViewedItems2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "ClearAllRecentlyViewedItems1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "ClearAllRecentlyViewedItems1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "ClearAllRecentlyViewedItems2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
