flow: "ViewABTestTargetGroupAffiliateSelection_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Back"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "ShowAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Search"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddUserGroupToABTestTargetGroup2"
    type: "pipelet"
    ref: "AddUserGroupToABTestTargetGroup"
    bindings:
      UserGroup: "AffiliateProgram:ProgramUserGroup"
  - id: "Call1"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call2"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call3"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call4"
    type: "call"
    ref: "ViewABTestTargetGroup_52-SearchAffiliates"
  - id: "CallNode1"
    type: "call"
    ref: "ViewABTestTargetGroupAffiliateSelection_52-Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "ViewABTestTargetGroupAffiliateSelection_52-Prefix"
  - id: "CallNode3"
    type: "call"
    ref: "ViewABTestTargetGroupAffiliateSelection_52-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ViewABTestTargetGroupAffiliateSelection_52-Search"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessTargetGroupAssignableSearches-SearchAffiliates"
  - id: "CheckForEmptyIterator1"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "UUIDIterator"
  - id: "Decision1"
    type: "decision"
    condition: "ABTest"
  - id: "Decision2"
    type: "decision"
    condition: "ABTestUUID"
  - id: "Decision3"
    type: "decision"
    condition: "PageNumber"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewABTestTargetGroup_52-ShowAll"
      OutValue_1: "ViewABTestTargetGroupAffiliateSelection_52-Create"
      PagingPipeline: "ViewABTestTargetGroupAffiliateSelection_52-Paging"
    bindings:
      Key_0: "cancel"
      Key_1: "assign"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "GetABTestByUUID1"
    type: "pipelet"
    ref: "GetABTestByUUID"
    bindings:
      UUID: "ABTestUUID"
  - id: "GetAffiliatePartnerByUUID1"
    type: "pipelet"
    ref: "GetAffiliatePartnerByUUID"
    bindings:
      AffiliatePartnerUUID: "UUID"
  - id: "GetAffiliateProgramByUUID1"
    type: "pipelet"
    ref: "GetAffiliateProgramByUUID"
    bindings:
      AffiliateProgramUUID: "UUID"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ABTestTargetGroupAffiliates"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocatorName: "null"
  - id: "GetPageLocator2"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ABTestTargetGroupAffiliateSelection"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocatorName: "null"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Affiliates"
      PageableID: "PageLocator:PageableID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewABTestTargetGroup_52-ShowAllConsumerGroup"
  - id: "Jump2"
    type: "jump"
  - id: "Jump3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump4"
    type: "jump"
    ref: "ViewABTestTargetGroupAffiliateSelection_52-Paging"
  - id: "Jump5"
    type: "jump"
    ref: "ViewABTestTargetGroup_52-ShowAllAffiliates"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "CurrentPageNumber"
      OutValue_1: "PageNumber"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentChannel:RepositoryDomain"
      OutValue_1: "AffiliateDomain"
  - id: "Loop1"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "AddUserGroupToABTestTargetGroup"
    bindings:
      UserGroup: "AffiliatePartner:PartnerUserGroup"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/ABTestTargetGroupSelectAffiliates_52"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Unpaged"
      Value: true
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Affiliates"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Affiliates"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewABTestTargetGroupAffiliateSelection_52-Paging"
      DefaultPageLocatorName: "ABTestTargetGroupAffiliateSelection"
    bindings:
      HandlerPipeline: "null"
      PageLocatorName: "null"
      Pageable: "Affiliates"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      Locale: "null"
      LocalizedString: "PageNumber"
      Pattern: "null"

links:
  - from: "GetAffiliatePartnerByUUID1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "GetAffiliateProgramByUUID1"
    via: "next"
    to: "AddUserGroupToABTestTargetGroup2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetPageLocator1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "GetPageLocator2"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "CheckForEmptyIterator1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "GetABTestByUUID1"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "GetABTestByUUID1"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "Start1"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "Join3"
    into: "in2"
  - from: "Start2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "AddUserGroupToABTestTargetGroup2"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "Decision1"
    via: "no"
    to: "Join2"
    into: "in3"
  - from: "CheckForEmptyIterator1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "Call2"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join2"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "End1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "SetPage1"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "GetAffiliatePartnerByUUID1"
    via: "error"
    to: "GetAffiliateProgramByUUID1"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "error"
    to: "KeyMapper1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetAffiliatePartnerByUUID1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "GetAffiliateProgramByUUID1"
    via: "error"
    to: "JoinNode1"
    into: "in3"
  - from: "Decision3"
    via: "no"
    to: "SetPage2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "GetPageLocator1"
    via: "error"
    to: "Jump1"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "SetPageLocator1"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "Join3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage1"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "GetPageLocator2"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Decision2"
    into: "in"
