flow: "ViewABTestGoingLiveTargetGroupAffiliateSelection_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "ShowAll"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call2"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call3"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call4"
    type: "call"
    ref: "ViewABTestGoingLiveTargetGroup_52-GetAffiliates"
  - id: "CallNode1"
    type: "call"
    ref: "ViewABTestGoingLiveTargetGroupAffiliateSelection_52-Prefix"
  - id: "CallNode15"
    type: "call"
    ref: "ViewABTestGoingLiveTargetGroup_52-GetAffiliates"
  - id: "CallNode2"
    type: "call"
    ref: "ViewABTestGoingLiveTargetGroupAffiliateSelection_52-Prefix"
  - id: "CallNode3"
    type: "call"
    ref: "ViewABTestGoingLiveTargetGroupAffiliateSelection_52-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ViewABTestTargetGroupAffiliateSelection_52-Search"
  - id: "CallNode5"
    type: "call"
    ref: "ViewABTestGoingLiveTargetGroup_52-PutAffiliatesToSession"
    bindings:
      Affiliates: "TargetGroupAffiliates"
      ABTestGroupID: "ABTestGroup:UUID"
  - id: "CallNode6"
    type: "call"
    ref: "ViewABTestGoingLiveTargetGroup_52-GetAffiliatesFromIDs"
    bindings:
      IDs: "UUIDIterator"
      Affiliates: "NewAffiliates"
  - id: "CheckForEmptyIterator1"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "UUIDIterator"
  - id: "CombineIterators1"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Concatenate Iterators and Remove Duplicates"
    bindings:
      Iterator1: "TargetGroupAffiliates"
      Iterator2: "NewAffiliates"
      Iterator: "TargetGroupAffiliates"
  - id: "Decision2"
    type: "decision"
    condition: "ABTestGroup"
  - id: "Decision3"
    type: "decision"
    condition: "PageNumber"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewABTestGoingLiveTargetGroup_52-ShowAllAffiliates"
      OutValue_1: "ViewABTestGoingLiveTargetGroupAffiliateSelection_52-Create"
      PagingPipeline: "ViewABTestGoingLiveTargetGroupAffiliateSelection_52-Paging"
    bindings:
      Key_0: "cancel"
      Key_1: "assign"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "GetABTestGroupByUUID1"
    type: "pipelet"
    ref: "GetABTestGroupByUUID"
    bindings:
      UUID: "ABTestGroupUUID"
      ABTestGroup: "ABTestGroup"
  - id: "GetPageLocator2"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ABTestGoingLiveTargetGroupAffiliateSelection"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocatorName: "null"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Affiliates"
      PageableID: "PageLocator:PageableID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "Jump3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump4"
    type: "jump"
    ref: "ViewABTestGoingLiveTargetGroupAffiliateSelection_52-Paging"
  - id: "Jump5"
    type: "jump"
    ref: "ViewABTestGoingLiveTargetGroup_52-ShowAllAffiliates"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "CurrentPageNumber"
      OutValue_1: "PageNumber"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/ABTestGoingLiveTargetGroupSelectAffiliates_52"
  - id: "PutValuesIntoPipelineDictionary1"
    type: "pipelet"
    ref: "PutValuesIntoPipelineDictionary"
    config:
      UseStaticValues: false
      key.1: "ABTest"
      value.1: "ABTestGroup:Test"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Unpaged"
      Value: true
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Affiliates"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Affiliates"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewABTestTargetGroupAffiliateSelection_52-Paging"
      DefaultPageLocatorName: "ABTestGoingLiveTargetGroupAffiliateSelection"
    bindings:
      HandlerPipeline: "null"
      PageLocatorName: "null"
      Pageable: "Affiliates"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      Locale: "null"
      LocalizedString: "PageNumber"
      Pattern: "null"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "GetABTestGroupByUUID1"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "SetPageLocator1"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "error"
    to: "KeyMapper1"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "SetPage2"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "next"
    to: "CallNode15"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "PutValuesIntoPipelineDictionary1"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "CallNode5"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join2"
    into: "in3"
  - from: "Start6"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode15"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CombineIterators1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "CheckForEmptyIterator1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "PutValuesIntoPipelineDictionary1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "GetPageable1"
    via: "error"
    to: "Join3"
    into: "in2"
  - from: "GetPageLocator2"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "GetPageLocator2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "Decision3"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "CombineIterators1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "SetPage1"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage1"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "GetABTestGroupByUUID1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "Join3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
