flow: "ViewABTestSummary_52"
kind: "view"

entries:
  - id: "Start2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Show"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "NewPromotion"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewABTestSummary_52-Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "ViewABTestGroupList_52-Search"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessCopyPromotion_52-CopyPromotion"
  - id: "Decision2"
    type: "decision"
    condition: "ABTest"
  - id: "Decision3"
    type: "decision"
    condition: "ABTestUUID"
  - id: "DispatchFormAction11"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_4: "ViewABTest_52-BackToList"
      PagingPipeline: "ViewABTestSummary_52-NewPromotion"
      DefaultPageNumberPrefix: "newPromotion_"
      OutValue_0: "ViewABTestSummary_52-Show"
    bindings:
      Key_4: "backToList"
      SelectionKey: "JumpTarget"
      PageNumberPrefix: "null"
      PageNumber: "ABTestGroupUUID"
      Key_0: "show"
  - id: "End1"
    type: "end"
    strict: false
  - id: "GetABTestByUUID1"
    type: "pipelet"
    ref: "GetABTestByUUID"
    bindings:
      UUID: "ABTestUUID"
  - id: "GetABTestGroupByUUID1"
    type: "pipelet"
    ref: "GetABTestGroupByUUID"
    bindings:
      UUID: "ABTestGroupUUID"
  - id: "GetABTestTargetGroupUserGroups1"
    type: "pipelet"
    ref: "GetABTestTargetGroupUserGroups"
    bindings:
      ABTest: "ABTestGroup:Test"
      UserGroups: "PromotionTargetGroupUserGroups"
  - id: "GetCurrencies1"
    type: "pipelet"
    ref: "GetCurrencies"
    config:
      Method: "Active Currencies"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join2"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewABTestSummary_52-Show"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ABTestGroup:Promotion"
      OutValue_1: "SourcePromotion"
      InValue_2: "\"ViewPromotionList-ListAll\""
      OutValue_2: "JumpTarget"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/ABTestSummary_52"

links:
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction11"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "GetCurrencies1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetABTestGroupByUUID1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "GetABTestTargetGroupUserGroups1"
    into: "in"
  - from: "GetCurrencies1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "GetABTestGroupByUUID1"
    via: "error"
    to: "JumpNode1"
    into: "in"
  - from: "GetABTestGroupByUUID1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "GetABTestTargetGroupUserGroups1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Join2"
    into: "in1"
  - from: "DispatchFormAction11"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join2"
    into: "in3"
  - from: "Decision3"
    via: "yes"
    to: "GetABTestByUUID1"
    into: "in"
  - from: "GetABTestByUUID1"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "Decision2"
    via: "yes"
    to: "Decision3"
    into: "in"
