flow: "ViewPageletAssignmentFilter"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Remove"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "View"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "Submit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "Cancel"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "GetPageletSearchContainers"
    mode: "private"
    strict: true
    inputs:
      - key: "UniquePageletSearchID"
        type: "java.lang.String"
        required: true
      - key: "PageFlag"
        type: "java.lang.String"
        required: true
      - key: "CurrentChannel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: false
  - id: "StartNode9"
    name: "UpdateAssignmentFilter"
    mode: "private"
    strict: true
    inputs:
      - key: "CompFilterSearchParameters"
        type: "java.util.Map"
        required: false
      - key: "CompPageFilterSearchParameters"
        type: "java.util.Map"
        required: false
      - key: "CurrentSearchParameters"
        type: "java.util.Map"
        required: false
      - key: "PageFilterSearchParameters"
        type: "java.util.Map"
        required: false
      - key: "AssignmentFilter"
        type: "com.intershop.component.foundation.capi.assignment.filter.AssignmentFilter"
        required: true
      - key: "PageFlag"
        type: "java.lang.String"
        required: true
      - key: "CurrentChannel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: false
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: true
      - key: "SearchType"
        type: "java.lang.String"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessAssignmentFilter-GetFilterConfigFromSession"
  - id: "CallNode10"
    type: "call"
    ref: "ProcessPageletSearch-GetCurrentContainerName"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessPageletSearch-GetContentRepository"
  - id: "CallNode14"
    type: "call"
    ref: "ProcessAssignmentFilter-StoreFilterConfigInSession"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessAssignmentFilter-GetFilterConfigFromSession"
  - id: "CallNode3"
    type: "call"
    ref: "ViewPageletAssignmentFilter-GetPageletSearchContainers"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessAssignmentFilter-ClearFilterConfigFromSession"
  - id: "CallNode5"
    type: "call"
    ref: "ViewPageletAssignmentFilter-UpdateAssignmentFilter"
    bindings:
      Locale: "CurrentSession:Locale"
      AssignmentFilter: "AssignmentFilterConfiguration:Filter"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessPageletSearch-PrepareContainerParameters"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessAssignmentFilter-GetFilterConfigFromSession"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessPageletSearch-GetContentRepository"
  - id: "CallNode9"
    type: "call"
    ref: "ProcessPageletSearch-PrepareAllSearchPageletTypes"
  - id: "CreateAssignmentFilter1"
    type: "pipelet"
    ref: "CreateAssignmentFilter"
  - id: "DecisionNode1"
    type: "decision"
    condition: "AssignmentFilterConfiguration:Filter"
  - id: "DecisionNode2"
    type: "decision"
    condition: "PageFlag"
  - id: "DecisionNode3"
    type: "decision"
    condition: "SearchType"
  - id: "DecisionNode4"
    type: "decision"
    condition: "PageFlag"
  - id: "DecisionNode5"
    type: "decision"
    condition: "SearchType"
  - id: "DeleteAssignmentFilter1"
    type: "pipelet"
    ref: "DeleteAssignmentFilter"
    bindings:
      AssignmentFilterConfiguration: "SelectedAssignmentFilterConf"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "This:Submit"
      OutValue_1: "This:Cancel"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "submitFilter"
      Key_1: "cancelFilter"
  - id: "DispatchFormActionByBreadcrumb1"
    type: "pipelet"
    ref: "DispatchFormActionByBreadcrumb"
    config:
      SplitMode: "PipelineAndParameter"
    bindings:
      SelectionKey: "JumpTarget"
      OutValue_0: "ApplicationState:LastListView"
      Key_0: "\"Submit\""
  - id: "DispatchFormActionByBreadcrumb2"
    type: "pipelet"
    ref: "DispatchFormActionByBreadcrumb"
    config:
      SplitMode: "PipelineAndParameter"
    bindings:
      SelectionKey: "JumpTarget"
      OutValue_0: "ApplicationState:LastBreadcrumb"
      Key_0: "\"Remove\""
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode18"
    type: "end"
    strict: true
    outputs:
      - key: "CurrentSearchParameters"
        type: "java.util.Map"
        guaranteed: false
      - key: "CompFilterSearchParameters"
        type: "java.util.Map"
        guaranteed: false
      - key: "CompPageFilterSearchParameters"
        type: "java.util.Map"
        guaranteed: false
      - key: "PageFilterSearchParameters"
        type: "java.util.Map"
        guaranteed: false
  - id: "EndNode21"
    type: "end"
    strict: true
    outputs:
      - key: "PageletSearchErrorsMap"
        type: "java.util.Map"
        guaranteed: false
  - id: "InteractionNode1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump4"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "This:View"
  - id: "JumpNode2"
    type: "jump"
  - id: "JumpNode3"
    type: "jump"
  - id: "JumpNode4"
    type: "jump"
    ref: "This:View"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "SelectedAssignmentFilterConf"
      OutValue_1: "AssignmentFilterConfiguration"
      OutValue_2: "SearchType"
      InValue_2: "\"advanced\""
  - id: "LoadPageletDefinitions1"
    type: "pipelet"
    ref: "LoadPageletDefinitions"
    config:
      DefaultType: "Component"
    bindings:
      Site: "ContentRepository:Domain:Site"
  - id: "LoadPageletDefinitions5"
    type: "pipelet"
    ref: "LoadPageletDefinitions"
    config:
      DefaultType: "Page"
    bindings:
      Site: "ContentRepository:Domain:Site"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      Dynamic: false
      WorkingTemplate: "content/assignment/filter/PageletFilter"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "StartFlag"
      Value: true
  - id: "UpdateDictionary1"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "PageFlag"
      Name_03: "Locale"
      Name_02: "ContentRepository"
      Name_05: "CurrentSearchParameters"
      Name_04: "SearchType"
    bindings:
      InDictionary: "AssignmentFilter"
      Value_02: "ContentRepository"
      Value_01: "PageFlag"
      Value_03: "Locale"
      Value_05: "CurrentSearchParameters"
      Value_04: "SearchType"
  - id: "UpdateDictionary2"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "PageFilterSearchParameters"
      Name_02: "CompFilterSearchParameters"
      Name_03: "CompPageFilterSearchParameters"
    bindings:
      InDictionary: "AssignmentFilter"
      Value_01: "PageFilterSearchParameters"
      Value_02: "CompFilterSearchParameters"
      Value_03: "CompPageFilterSearchParameters"
  - id: "UpdateDictionary3"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "NameOrContentExpression"
    bindings:
      InDictionary: "CurrentSearchParameters"
      Value_01: "NameOrContentExpression"
  - id: "VerifySearchTerm2"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowExclusions: "default"
      AllowFuzzySearch: false
      AllowSubOperator: "default"
      AllowWildcards: "default"
      DefaultOperator: "AND"
    bindings:
      UserSearchTerm: "CurrentSearchParameters:NameOrContent"
      ErrorCode: "NameError"
      SearchExpression: "NameOrContentExpression"

links:
  - from: "StartNode2"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "CallNode14"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "DispatchFormActionByBreadcrumb2"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DeleteAssignmentFilter1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "DispatchFormActionByBreadcrumb1"
    into: "in"
  - from: "DispatchFormActionByBreadcrumb1"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "CallNode2"
    via: "ERROR"
    to: "JoinNode3"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode8"
    into: "in2"
  - from: "CallNode5"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CreateAssignmentFilter1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "CreateAssignmentFilter1"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "UpdateDictionary2"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "VerifySearchTerm2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "CallNode3"
    via: "ERROR"
    to: "JumpNode4"
    into: "in"
  - from: "VerifySearchTerm2"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "StartNode6"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "UpdateDictionary1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode4"
    into: "in1"
  - from: "UpdateDictionary2"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "DecisionNode2"
    via: "yes"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode7"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "CallNode7"
    via: "ERROR"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode1"
    via: "ERROR"
    to: "JoinNode3"
    into: "in1"
  - from: "StartNode9"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "UpdateDictionary1"
    into: "in"
  - from: "CallNode6"
    via: "ERROR"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode4"
    via: "yes"
    to: "LoadPageletDefinitions5"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "LoadPageletDefinitions1"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "EndNode21"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "LoadPageletDefinitions1"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "LoadPageletDefinitions5"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "UpdateDictionary3"
    via: "next"
    to: "JoinNode7"
    into: "in3"
  - from: "VerifySearchTerm2"
    via: "next"
    to: "UpdateDictionary3"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "EndNode18"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "CallNode11"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "JumpNode1"
    into: "in"
  - from: "DeleteAssignmentFilter1"
    via: "next"
    to: "DispatchFormActionByBreadcrumb2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "DecisionNode3"
    into: "in"
