flow: "ViewPromotionTargetGroupUserSelection_52"
kind: "process"

entries:
  - id: "Start1"
    name: "ShowAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start10"
    name: "Back"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start31"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "ListSimpleSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Search"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call5"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call7"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode0"
    type: "call"
    ref: "ViewPromotionTargetGroup_52-SearchConsumers"
  - id: "CallNode1"
    type: "call"
    ref: "ViewPromotionTargetGroupUserSelection_52-Search"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessOrganization_52-GetConsumerOrg"
  - id: "CallNode29"
    type: "call"
    ref: "ProcessOrganization_52-GetConsumerOrg"
  - id: "CallNode3"
    type: "call"
    ref: "ViewPromotionTargetGroupUserSelection_52-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ViewPromotionTargetGroupUserSelection_52-Prefix"
  - id: "CallNode5"
    type: "call"
    ref: "ViewPromotionTargetGroupUserSelection_52-Prefix"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessUserList-BySimpleSearch"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessPromotion-TouchPromotion"
    bindings:
      Iterator: "UUIDIterator"
  - id: "CheckForEmptyIterator1"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "UUIDIterator"
  - id: "Decision1"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision2"
    type: "decision"
    condition: "PromotionUUID"
  - id: "Decision3"
    type: "decision"
    condition: "Promotion"
  - id: "DecisionNode1"
    type: "decision"
    condition: "User"
  - id: "DecisionNode2"
    type: "decision"
    condition: "SearchTerm"
  - id: "DispatchFormAction11"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPromotionTargetGroup_52-ShowAll"
      OutValue_1: "ViewPromotionTargetGroupUserSelection_52-Create"
      OutValue_2: "ViewPromotionTargetGroupUserSelection_52-ListSimpleSearch"
      PagingPipeline: "ViewPromotionTargetGroupUserSelection_52-Paging"
    bindings:
      Key_0: "cancel"
      Key_1: "assign"
      Key_2: "simpleSearch"
      SelectionKey: "JumpTarget"
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "PromotionTargetGroupUsers"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocatorName: "null"
  - id: "GetPageLocator11"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "PromotionTargetGroupUsersSelection"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocatorName: "null"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      PageableID: "PageLocator:PageableID"
      Pageable: "Users"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump21"
    type: "jump"
    ref: "ViewPromotionTargetGroup_52-ShowAllConsumer"
  - id: "Jump22"
    type: "jump"
    ref: "ViewPromotionTargetGroupUserSelection_52-Paging"
  - id: "Jump5"
    type: "jump"
  - id: "Jump6"
    type: "jump"
    ref: "ViewPromotionTargetGroup_52-ShowAllConsumer"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "CurrentPageNumber"
      OutValue_1: "PageNumber"
  - id: "Loop1"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "User"
      RemoveFormValues: false
  - id: "Pipelet10"
    type: "pipelet"
    ref: "SetPageLocatorParameter"
    config:
      DefaultParameterName: "SearchTerm"
    bindings:
      ParameterName: "null"
      ParameterValue: "SearchTerm"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "SearchTerm"
      RemoveFormValues: true
  - id: "Pipelet12"
    type: "pipelet"
    ref: "GetPromotionByUUID"
  - id: "Pipelet13"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_10: "Organization:OrganizationDomain:Domain"
      OutValue_10: "UserDomain"
  - id: "Pipelet14"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "SearchTerm"
  - id: "Pipelet15"
    type: "pipelet"
    ref: "UpdatePageSize"
    config:
      DefaultPageSize: 15
    bindings:
      PageSize: "null"
      PageableIterator: "Users"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Organization:Domain"
      OutValue_1: "UserDomain"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "SearchTerm"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "UserID"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "AddUserToPromotionTargetGroup"
  - id: "Pipelet9"
    type: "pipelet"
    ref: "GetRolesByDomain"
    bindings:
      DomainID: "Organization:Domain:DomainID"
  - id: "PrepareApplicationView12"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/PromotionTargetGroupSelectUsers_52"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Users"
  - id: "SetPage3"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Users"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewPromotionTargetGroupUserSelection_52-Paging"
      DefaultPageLocatorName: "PromotionTargetGroupUsersSelection"
    bindings:
      HandlerPipeline: "null"
      PageLocatorName: "null"
      Pageable: "Users"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      Locale: "null"
      LocalizedString: "PageNumber"
      Pattern: "null"
      IntegerObject: "PageNumber"

links:
  - from: "Call4"
    via: "next"
    to: "GetPageLocator11"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Call7"
    via: "next"
    to: "CheckForEmptyIterator1"
    into: "in"
  - from: "CallNode0"
    via: "next"
    to: "PrepareApplicationView12"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode29"
    via: "next"
    to: "Pipelet13"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "Pipelet15"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "Jump21"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "error"
    to: "KeyMapper2"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "SetPage2"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join3"
    into: "in1"
  - from: "Decision2"
    via: "yes"
    to: "Pipelet12"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Join3"
    into: "in1"
  - from: "Decision3"
    via: "yes"
    to: "Decision2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet8"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet10"
    into: "in"
  - from: "DispatchFormAction11"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "GetPageLocator11"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "GetPageLocator1"
    via: "error"
    to: "Jump6"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "GetPageable1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "CallNode0"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "CallNode29"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "Jump22"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "Pipelet1"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "Pipelet10"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "Pipelet11"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet12"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Pipelet13"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "Pipelet14"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "Pipelet14"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "Pipelet15"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "Pipelet9"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Pipelet7"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Pipelet9"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "Pipelet9"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "PrepareApplicationView12"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "SetPage3"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "SetPageLocator1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "Start10"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Pipelet11"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Start31"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction11"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "Pipelet14"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage3"
    into: "in"
