flow: "ViewVariationTypeList"
kind: "process"

entries:
  - id: "StartNode1"
    name: "RemoveVariationTypes"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PageNumber"
  - id: "DecisionNode2"
    type: "decision"
    condition: "PageLocator"
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      Datasource: "default"
      DefaultPageSize: 15
      QueryName: "productvariation/GetVariationTypesByDomain"
      ParameterName_01: "Domain"
    bindings:
      ParameterValue_01: "Repository:Domain"
      SearchResult: "VariationTypes"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewVariationTypeList-ListAll"
  - id: "LoopNode1"
    type: "loop"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_2: "ViewVariationType-New"
      OutValue_3: "ViewVariationTypeList-Paging"
      OutValue_4: "ViewVariationTypeList-RemoveVariationTypes"
      OutValue_5: "ViewVariationTypeList-Paging"
      PagingPipeline: "ViewVariationTypeList-Paging"
    bindings:
      Key_2: "create"
      Key_3: "confirmDelete"
      Key_4: "delete"
      Key_5: "cancelDelete"
      SelectionKey: "JumpTarget"
  - id: "Pipelet13"
    type: "pipelet"
    ref: "GetVariationTypeByUUID"
  - id: "Pipelet15"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "VariationTypes"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      Locale: "null"
      LocalizedString: "PageNumber"
      Pattern: "null"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "RemoveVariationType"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "VariationTypeList"
      RestorePageLocatorDictionary: "False"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewVariationTypeList-Paging"
      DefaultPageLocatorName: "VariationTypeList"
    bindings:
      HandlerPipeline: "null"
      PageLocatorName: "null"
      Pageable: "VariationTypes"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "VariationTypes"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "VariationTypes"
      PageableID: "PageLocator:PageableID"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "VariationTypes"
      WorkingTemplate: "product/VariationTypeList"

links:
  - from: "CallNode1"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Pipelet5"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "Pipelet13"
    via: "error"
    to: "JoinNode7"
    into: "in3"
  - from: "Pipelet2"
    via: "error"
    to: "JoinNode6"
    into: "in3"
  - from: "Pipelet6"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode5"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "Pipelet11"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Pipelet13"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "Pipelet15"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "Pipelet11"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode3"
    into: "in3"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "DecisionNode1"
    via: "no"
    to: "DecisionNode2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "Pipelet13"
    into: "in"
  - from: "Pipelet7"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode7"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "Pipelet7"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "JoinNode4"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "Pipelet15"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode4"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet6"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
