flow: "ViewProductCategoryAssignmentWizard_52"
kind: "view"

entries:
  - id: "Start1"
    name: "CategoryTree"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start10"
    name: "CatalogDetails"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start11"
    name: "CategoryDetails"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start12"
    name: "CancelAssignment"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start13"
    name: "DispatchSelectedCategoryUUID"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start14"
    name: "DispatchSelectCatalog"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Expand"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "ListCatalogs"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "PrepareProductAssignment"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "GetProduct"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "SelectCatalog"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "Collapse"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard_52-Prefix"
  - id: "Call11"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard_52-Prefix"
  - id: "Call12"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard_52-Prefix"
  - id: "Call13"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard_52-Prefix"
  - id: "Call14"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard_52-GetProduct"
  - id: "Call15"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard_52-GetProduct"
  - id: "Call16"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard_52-GetProduct"
  - id: "Call17"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard_52-GetProduct"
  - id: "Call18"
    type: "call"
    ref: "ProcessProduct-Get"
  - id: "Call2"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard_52-GetProduct"
  - id: "Call3"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard_52-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard_52-Prefix"
  - id: "Call5"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard_52-Prefix"
  - id: "Call6"
    type: "call"
    ref: "ProcessChannelCatalog_52-GetStandardCatalogs"
  - id: "Call8"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard_52-Prefix"
  - id: "Call9"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard_52-GetProduct"
  - id: "CreateIteratorForPrefix1"
    type: "pipelet"
    ref: "CreateIteratorForPrefix"
    config:
      Prefix: "ProductID"
  - id: "Decision10"
    type: "decision"
    condition: "SelectedCategoryUUID"
  - id: "Decision11"
    type: "decision"
    condition: "CatalogUUID"
  - id: "Decision3"
    type: "decision"
    condition: "ProductID"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProductCategoryAssignmentWizard_52-DispatchSelectCatalog"
      OutValue_1: "ViewProductCategoryAssignmentWizard_52-CancelAssignment"
      OutValue_2: "ViewProductCategoryAssignmentWizard_52-DispatchSelectedCategoryUUID"
      OutValue_3: "ViewProductCategoryAssignmentWizard_52-PrepareProductAssignment"
    bindings:
      Key_0: "selectCatalog"
      Key_1: "cancel"
      Key_2: "finish"
      SelectionKey: "JumpTarget"
      Key_3: "previous"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "ExchangeSessionObject1"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      SaveObject: "ExpandedCategoriesMap"
  - id: "ExchangeSessionObject2"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "ProductUUIDs"
    bindings:
      SaveObject: "PrefixIterator"
  - id: "ExchangeSessionObject3"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "ProductID"
    bindings:
      SaveObject: "ProductID"
  - id: "ExchangeSessionObject4"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ProductID"
    bindings:
      LoadObject: "ProductID"
  - id: "ExchangeSessionObject5"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "CatalogID"
    bindings:
      LoadObject: "CatalogID"
      SaveObject: "CatalogID"
  - id: "ExchangeSessionObject6"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      LoadObject: "ExpandedCategoriesMap"
  - id: "ExchangeSessionObject7"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      LoadObject: "ExpandedCategoriesMap"
  - id: "GetCatalogByUUID1"
    type: "pipelet"
    ref: "GetCatalogByUUID"
  - id: "GetCatalogByUUID2"
    type: "pipelet"
    ref: "GetCatalogByUUID"
  - id: "GetCatalogByUUID3"
    type: "pipelet"
    ref: "GetCatalogByUUID"
  - id: "GetCatalogByUUID4"
    type: "pipelet"
    ref: "GetCatalogByUUID"
  - id: "GetCatalogByUUID5"
    type: "pipelet"
    ref: "GetCatalogByUUID"
  - id: "GetCategoryByUUID1"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "CategoryUUID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "InteractionEnd4"
    type: "interaction"
  - id: "InteractionEnd5"
    type: "interaction"
  - id: "InteractionEnd6"
    type: "interaction"
  - id: "Join8"
    type: "join"
  - id: "Jump11"
    type: "jump"
    ref: "ViewProductCategoryAssignmentWizard_52-CategoryTree"
  - id: "Jump12"
    type: "jump"
    ref: "ViewProductCategoryAssignmentWizard_52-ListCatalogs"
  - id: "Jump13"
    type: "jump"
    ref: "ViewProductCategoryAssignmentWizard_52-SelectCatalog"
  - id: "Jump14"
    type: "jump"
    ref: "ViewProductCategories_52-Start"
  - id: "Jump3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump5"
    type: "jump"
    ref: "ViewProductCategoryAssignmentWizard_52-ListCatalogs"
  - id: "Jump6"
    type: "jump"
    ref: "ViewProductCategoryAssignmentWizard_52-CategoryTree"
  - id: "Jump8"
    type: "jump"
    ref: "ViewProductCategories_52-AssignSelectedProducts"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewProduct_52-ErrorProductNotAvailable"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Category"
      InValue_2: "CategoriesPath"
      OutValue_1: "JumpCategory"
      OutValue_2: "JumpPath"
      InValue_3: "CurrentProductRepository:RepositoryDomain"
      OutValue_3: "ProductDomain"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Catalog:Root:UUID"
      InValue_2: "Catalog:Id"
      OutValue_1: "CatalogCategoryID"
      OutValue_2: "CatalogID"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetProductByUUID"
    bindings:
      ProductUUID: "ProductID"
      ProductDomain: "CurrentProductRepository:RepositoryDomain"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Concatenate Iterators"
    bindings:
      Iterator: "Catalogs"
      Iterator1: "SharedStandardCatalogs"
      Iterator2: "LocalStandardCatalogs"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductCategoryAssignmentSelectCategory_52"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductCategoryAssignmentSelectCatalog_52"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductCategoryAssignmentSelectCategory_52"
  - id: "PrepareApplicationView4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductCategoryAssignmentSelectCategory_52"
  - id: "PrepareApplicationView5"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductCategoryAssignmentViewCatalogDetails_52"
  - id: "PrepareApplicationView6"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductCategoryAssignmentViewCategoryDetails_52"
  - id: "UpdateMapping1"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "Catalog:Root:UUID"
      OutMap: "ExpandedCategoriesMap"
      Value: "Catalog:Root:UUID"
  - id: "UpdateMapping2"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "CategoryUUID"
      Value: "CategoryUUID"
  - id: "UpdateMapping3"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Remove"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "CategoryUUID"
      Value: "CategoryUUID"

links:
  - from: "Start3"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "ExchangeSessionObject3"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "ExchangeSessionObject5"
    into: "in"
  - from: "ExchangeSessionObject5"
    via: "next"
    to: "Jump6"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "ExchangeSessionObject3"
    via: "next"
    to: "CreateIteratorForPrefix1"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd4"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "PrepareApplicationView4"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "ExchangeSessionObject2"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "ExchangeSessionObject6"
    via: "next"
    to: "UpdateMapping2"
    into: "in"
  - from: "UpdateMapping2"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "ExchangeSessionObject7"
    via: "next"
    to: "UpdateMapping3"
    into: "in"
  - from: "UpdateMapping3"
    via: "next"
    to: "PrepareApplicationView4"
    into: "in"
  - from: "UpdateMapping1"
    via: "next"
    to: "ExchangeSessionObject1"
    into: "in"
  - from: "ExchangeSessionObject1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "Call11"
    into: "in"
  - from: "Start10"
    via: "next"
    to: "Call12"
    into: "in"
  - from: "CreateIteratorForPrefix1"
    via: "next"
    to: "ExchangeSessionObject2"
    into: "in"
  - from: "PrepareApplicationView5"
    via: "next"
    to: "InteractionEnd6"
    into: "in"
  - from: "Start11"
    via: "next"
    to: "Call13"
    into: "in"
  - from: "PrepareApplicationView6"
    via: "next"
    to: "InteractionEnd5"
    into: "in"
  - from: "GetCategoryByUUID1"
    via: "next"
    to: "PrepareApplicationView6"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Call14"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Call15"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Call16"
    into: "in"
  - from: "Call12"
    via: "next"
    to: "Call17"
    into: "in"
  - from: "Call13"
    via: "next"
    to: "Call18"
    into: "in"
  - from: "Call18"
    via: "next"
    to: "GetCategoryByUUID1"
    into: "in"
  - from: "ExchangeSessionObject4"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Call11"
    via: "next"
    to: "GetCatalogByUUID1"
    into: "in"
  - from: "GetCatalogByUUID1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "Call14"
    via: "next"
    to: "GetCatalogByUUID2"
    into: "in"
  - from: "GetCatalogByUUID2"
    via: "next"
    to: "UpdateMapping1"
    into: "in"
  - from: "Call17"
    via: "next"
    to: "GetCatalogByUUID3"
    into: "in"
  - from: "GetCatalogByUUID3"
    via: "next"
    to: "PrepareApplicationView5"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "ExchangeSessionObject4"
    into: "in"
  - from: "Call15"
    via: "next"
    to: "GetCatalogByUUID4"
    into: "in"
  - from: "GetCatalogByUUID4"
    via: "next"
    to: "ExchangeSessionObject6"
    into: "in"
  - from: "Call16"
    via: "next"
    to: "GetCatalogByUUID5"
    into: "in"
  - from: "GetCatalogByUUID5"
    via: "next"
    to: "ExchangeSessionObject7"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Join8"
    into: "in3"
  - from: "Start6"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Decision11"
    via: "yes"
    to: "Jump13"
    into: "in"
  - from: "Decision11"
    via: "no"
    to: "Jump12"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "JumpNode1"
    into: "in"
  - from: "Start14"
    via: "next"
    to: "Decision11"
    into: "in"
  - from: "Decision10"
    via: "yes"
    to: "Jump8"
    into: "in"
  - from: "Decision10"
    via: "no"
    to: "Jump11"
    into: "in"
  - from: "Start13"
    via: "next"
    to: "Decision10"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "Jump14"
    into: "in"
  - from: "Start12"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "Join8"
    via: "next"
    to: "End3"
    into: "in"
