flow: "ViewApplicationPromotionPreferenceBudgetNotification"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      - key: "ApplicationUUID"
        type: "java.lang.String"
        required: true
  - id: "StartNode2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      - key: "ApplicationUUID"
        type: "java.lang.String"
        required: true
  - id: "StartNode3"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      - key: "ApplicationUUID"
        type: "java.lang.String"
        required: true
  - id: "StartNode4"
    name: "SetFormValues"
    mode: "private"
    strict: false
    inputs:
      - key: "ChannelRepository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
      - key: "NotificationSettings"
        type: "com.intershop.beehive.core.capi.webform.Form"
        required: true
      - key: "CurrentChannel"
        type: "java.lang.Object"
        required: true
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: true
  - id: "StartNode5"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      - key: "ApplicationUUID"
        type: "java.lang.String"
        required: true
  - id: "StartNode6"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      - key: "ApplicationUUID"
        type: "java.lang.String"
        required: true
  - id: "StartNode7"
    name: "UpdatePreferences"
    mode: "private"
    strict: false
    inputs:
      - key: "ChannelRepository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
      - key: "NotificationSettings"
        type: "com.intershop.beehive.core.capi.webform.Form"
        required: true
      - key: "CurrentChannel"
        type: "java.lang.Object"
        required: true
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: true

steps:
  - id: "AddMultipleEntriesToMap1"
    type: "pipelet"
    ref: "AddMultipleEntriesToMap"
    config:
      Mode: "OverwriteValue"
    bindings:
      Key1: "NotificationSettings:AddressEmailFrom"
      Key2: "NotificationSettings:BudgetExhaustedEmailSubject"
      Key3: "NotificationSettings:BudgetThresholdEmailSubject"
      Key4: "NotificationSettings:BudgetExhaustedEmailTemplate"
      Key5: "NotificationSettings:BudgetThresholdReachedEmailTemplate"
      Value1: "AddressEmailFrom"
      Value2: "BudgetExhaustedEmailSubject:DomainValue"
      Value3: "BudgetThresholdEmailSubject:DomainValue"
      Value4: "BudgetExhaustedEmailTemplate"
      Value5: "BudgetThresholdReachedEmailTemplate"
      OutMap: "FormParameterValuesMap"
  - id: "CallNode1"
    type: "call"
    ref: "ViewApplicationPromotionPreferenceBudgetNotification-Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "ViewApplicationPromotionPreferenceBudgetNotification-SetFormValues"
  - id: "CallNode3"
    type: "call"
    ref: "ViewApplicationPromotionPreferenceBudgetNotification-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ViewApplicationPromotionPreferenceBudgetNotification-UpdatePreferences"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "BudgetNotificationSettings"
      FormResource: "BudgetNotificationSettings"
    bindings:
      Form: "NotificationSettings"
      FormName: "null"
      FormResource: "null"
  - id: "DecisionNode5"
    type: "decision"
    condition: "ViewBudgetNotification"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
    bindings:
      Locales: "AllLocales"
  - id: "DetermineLocalizedTextByLocale1"
    type: "pipelet"
    ref: "DetermineLocalizedTextByLocale"
    bindings:
      SearchedKey: "\"promotion.budget.exhausted.email.subject\""
      LocalizationTexts: "BudgetExhaustedEmailSubjects"
  - id: "DetermineLocalizedTextByLocale2"
    type: "pipelet"
    ref: "DetermineLocalizedTextByLocale"
    bindings:
      LocalizationTexts: "BudgetThresholdEmailSubjects"
      SearchedKey: "\"promotion.budget.threshold.email.subject\""
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewApplicationPromotionPreferenceBudgetNotification-Update"
      OutValue_1: "ViewApplicationPromotionPreferenceBudgetNotification-Edit"
    bindings:
      Key_0: "apply"
      SelectionKey: "JumpTarget"
      Key_1: "setLocale"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "GetApplicationByUUID1"
    type: "pipelet"
    ref: "GetApplicationByUUID"
  - id: "GetApplicationPreference1"
    type: "pipelet"
    ref: "GetApplicationPreference"
    config:
      DefaultApplicationPreferenceKey: "BudgetNotificationEmailFrom"
      Type: "String"
      DefaultPreferenceKey: "BudgetNotificationEmailFrom"
    bindings:
      ApplicationPreferenceStringValue: "AddressEmailFrom"
      DomainPreference: "ChannelRepository:Domain"
      PreferenceStringValue: "AddressEmailFrom"
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceKey: "null"
      ApplicationPreferenceKey: "AddressEmailFrom"
  - id: "GetApplicationPreference2"
    type: "pipelet"
    ref: "GetApplicationPreference"
    config:
      DefaultApplicationPreferenceKey: "BudgetNotificationEmailTemplateExhausted"
      Type: "String"
    bindings:
      DomainPreference: "ChannelRepository:Domain"
      ApplicationPreferenceStringValue: "BudgetExhaustedEmailTemplate"
      ApplicationPreferenceKey: "null"
  - id: "GetApplicationPreference3"
    type: "pipelet"
    ref: "GetApplicationPreference"
    config:
      Type: "String"
      DefaultApplicationPreferenceKey: "BudgetNotificationEmailTemplatePercentage"
    bindings:
      DomainPreference: "ChannelRepository:Domain"
      ApplicationPreferenceStringValue: "BudgetThresholdReachedEmailTemplate"
      ApplicationPreferenceKey: "null"
  - id: "GetFirstElementOfIterator1"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      Iterator: "BudgetExhaustedEmailSubjects"
      FirstElement: "BudgetExhaustedEmailSubject"
  - id: "GetFirstElementOfIterator2"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      Iterator: "BudgetThresholdEmailSubjects"
      FirstElement: "BudgetThresholdEmailSubject"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Request Locale"
    bindings:
      Locale: "SelectedLocale"
      LocaleId: "LocaleID"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewApplicationPromotionPreferenceBudgetNotification-Edit"
  - id: "LogMessage1"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Level: "Warn"
    bindings:
      MessageParam0: "ApplicationUUID"
      MessageText: "\"Unable to find an Application with UUID {}. This will probably cause problems in the following!\""
  - id: "LogMessage2"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Level: "Warn"
    bindings:
      MessageText: "\"Something went wrong during attempt of setting budget notification form values!\""
  - id: "LogMessage3"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Level: "Warn"
    bindings:
      MessageText: "\"Some Email Notification parameter could not be updated!\""
  - id: "LogMessage5"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Level: "Warn"
    bindings:
      MessageText: "\"form validation fails!\""
  - id: "Pipelet1"
    type: "pipelet"
    ref: "CreateLocalizationContextFromApplication"
    bindings:
      LocaleInformation: "SelectedLocale"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Applications"
      WorkingTemplate: "app/ApplicationPromotionPreferences"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"
  - id: "SetApplicationPreference1"
    type: "pipelet"
    ref: "SetApplicationPreference"
    config:
      DefaultApplicationPreferenceKey: "BudgetNotificationEmailFrom"
      Type: "String"
    bindings:
      ApplicationPreferenceStringValue: "NotificationSettings:AddressEmailFrom:Value"
  - id: "SetApplicationPreference2"
    type: "pipelet"
    ref: "SetApplicationPreference"
    config:
      Type: "String"
      DefaultApplicationPreferenceKey: "BudgetNotificationEmailTemplateExhausted"
    bindings:
      ApplicationPreferenceStringValue: "NotificationSettings:BudgetExhaustedEmailTemplate:Value"
  - id: "SetApplicationPreference3"
    type: "pipelet"
    ref: "SetApplicationPreference"
    config:
      DefaultApplicationPreferenceKey: "BudgetNotificationEmailTemplatePercentage"
      Type: "String"
    bindings:
      ApplicationPreferenceStringValue: "NotificationSettings:BudgetThresholdReachedEmailTemplate:Value"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ViewBudgetNotification"
      Value: true
  - id: "SetFormParameterValues1"
    type: "pipelet"
    ref: "SetFormParameterValues"
  - id: "UpdateLocalizedText1"
    type: "pipelet"
    ref: "UpdateLocalizedText"
    config:
      DefaultApplicationPreferenceKey: "BudgetExhaustedEmailSubject"
      Type: "String"
    bindings:
      ApplicationPreferenceStringValue: "BudgetExhaustedEmailSubject"
      Key: "\"promotion.budget.exhausted.email.subject\""
      Domain: "ChannelRepository:Domain"
      DomainValue: "NotificationSettings:BudgetExhaustedEmailSubject:Value"
  - id: "UpdateLocalizedText2"
    type: "pipelet"
    ref: "UpdateLocalizedText"
    bindings:
      Key: "\"promotion.budget.threshold.email.subject\""
      Domain: "ChannelRepository:Domain"
      DomainValue: "NotificationSettings:BudgetThresholdEmailSubject:Value"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    config:
      Trim: true
    bindings:
      Form: "NotificationSettings"

links:
  - from: "StartNode2"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "StartNode5"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "GetApplicationPreference1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "JumpNode2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetApplicationPreference2"
    via: "next"
    to: "DetermineLocalizedTextByLocale1"
    into: "in"
  - from: "GetApplicationPreference3"
    via: "next"
    to: "DetermineLocalizedTextByLocale2"
    into: "in"
  - from: "GetApplicationPreference1"
    via: "next"
    to: "GetApplicationPreference2"
    into: "in"
  - from: "GetApplicationPreference1"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "GetFirstElementOfIterator1"
    via: "next"
    to: "GetApplicationPreference3"
    into: "in"
  - from: "GetApplicationPreference2"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "GetFirstElementOfIterator1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "AddMultipleEntriesToMap1"
    via: "next"
    to: "SetFormParameterValues1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "ValidateForm1"
    via: "error"
    to: "LogMessage5"
    into: "in"
  - from: "GetApplicationPreference3"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "DetermineLocalizedTextByLocale1"
    via: "next"
    to: "GetFirstElementOfIterator1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "GetFirstElementOfIterator2"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "LogMessage2"
    into: "in"
  - from: "LogMessage2"
    via: "next"
    to: "JoinNode7"
    into: "in2"
  - from: "StartNode6"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "GetApplicationByUUID1"
    into: "in"
  - from: "GetApplicationByUUID1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "GetApplicationByUUID1"
    via: "error"
    to: "LogMessage1"
    into: "in"
  - from: "LogMessage1"
    via: "next"
    to: "JoinNode8"
    into: "in2"
  - from: "SetApplicationPreference3"
    via: "error"
    to: "JoinNode9"
    into: "in2"
  - from: "CallNode4"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "StartNode7"
    via: "next"
    to: "SetApplicationPreference1"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "SetApplicationPreference2"
    via: "error"
    to: "JoinNode10"
    into: "in2"
  - from: "SetApplicationPreference1"
    via: "next"
    to: "SetApplicationPreference2"
    into: "in"
  - from: "UpdateLocalizedText1"
    via: "next"
    to: "SetApplicationPreference3"
    into: "in"
  - from: "GetFirstElementOfIterator2"
    via: "next"
    to: "AddMultipleEntriesToMap1"
    into: "in"
  - from: "SetApplicationPreference2"
    via: "next"
    to: "UpdateLocalizedText1"
    into: "in"
  - from: "SetApplicationPreference3"
    via: "next"
    to: "UpdateLocalizedText2"
    into: "in"
  - from: "SetApplicationPreference1"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "ValidateForm1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "LogMessage3"
    into: "in"
  - from: "LogMessage3"
    via: "next"
    to: "JoinNode12"
    into: "in3"
  - from: "JoinNode11"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "SetFormParameterValues1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "LogMessage5"
    via: "next"
    to: "JoinNode11"
    into: "in2"
  - from: "DetermineLocalizedTextByLocale2"
    via: "next"
    to: "GetFirstElementOfIterator2"
    into: "in"
  - from: "UpdateLocalizedText2"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "JoinNode12"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "JoinNode14"
    into: "in1"
  - from: "DecisionNode5"
    via: "no"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode14"
    into: "in3"
  - from: "JoinNode14"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "GetLocale1"
    into: "in"
