flow: "ViewPagelet_comp_attributeIndex"
kind: "view"

entries:
  - id: "StartNode5"
    name: "GetAttributeIndex"
    mode: "private"
    strict: true
    inputs:
      - key: "PageletConfigurationParameters"
        type: "java.util.Map"
        required: true

steps:
  - id: "CallNode2"
    type: "call"
    ref: "ProcessSearchBySearchIndex-GetSearchIndexQuery"
    bindings:
      DefaultQueryTerm: "\"*\""
      Domain: "CurrentOrganization:OwningDomain"
      FeatureID: "\"SFProductSearch\""
      Locale: "CurrentRequest:Locale"
  - id: "DecisionNode1"
    type: "decision"
    condition: "FilterAttributeEntries"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "AttributeIndexMap"
        type: "java.util.Map"
        guaranteed: false
  - id: "GetValuesFromRequest1"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "Application"
    bindings:
      Key: "\"CurrentOrganization\""
      Namespace: "null"
  - id: "GroupObjectsByRanges1"
    type: "pipelet"
    ref: "GroupObjectsByRanges"
    config:
      StringConverterClass: "com.intershop.sellside.application.b2c.capi.characterhandling.FilterAttributeEntryStringConverter"
    bindings:
      Objects: "FilterAttributeEntries:Iterator"
      RangeString: "PageletConfigurationParameters:indexLetters"
      Groups: "AttributeIndexMap"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "SearchIndex:FilterAttributeEntries(PageletConfigurationParameters:indexAttribute)"
      OutValue_1: "FilterAttributeEntries"

links:
  - from: "StartNode5"
    via: "next"
    to: "GetValuesFromRequest1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode3"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "GetValuesFromRequest1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetValuesFromRequest1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GroupObjectsByRanges1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "DecisionNode1"
    via: "yes"
    to: "GroupObjectsByRanges1"
    into: "in"
  - from: "GroupObjectsByRanges1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
