flow: "ViewChannelCatalogFilter"
kind: "view"

entries:
  - id: "Start1"
    name: "New"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start10"
    name: "Publish"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start11"
    name: "Back"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "UpdateCatalogFilter"
    mode: "private"
    strict: false
    inputs:
      - key: "CatalogFilter<com.intershop.component.mvc.capi.filter.CatalogFilter>"
        type: "com.intershop.component.mvc.capi.filter.CatalogFilter"
        required: false
  - id: "Start6"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "CreateWebForm"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "InvalidatePageCaches"
    mode: "private"
    strict: false
    inputs:
      - key: "CurrentChannel<java.lang.Object>"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: false
  - id: "StartNode2"
    name: "GetSites"
    mode: "private"
    strict: false
    inputs:
      - key: "CurrentChannel<java.lang.Object>"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: false

steps:
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "null"
      Object: "CurrentChannel:Domain:Site"
      Objects: "null"
      OutVector: "SiteVector"
      Iterator: "null"
  - id: "Call1"
    type: "call"
    ref: "ViewChannelCatalogFilter-Prefix"
  - id: "Call10"
    type: "call"
    ref: "ViewChannelCatalogFilter-Prefix"
  - id: "Call11"
    type: "call"
    ref: "PublishCatalogFilter-Single"
  - id: "Call12"
    type: "call"
    ref: "ViewChannelCatalogFilter-Prefix"
  - id: "Call2"
    type: "call"
    ref: "PublishCatalogFilter-InvalidatePageCaches"
  - id: "Call3"
    type: "call"
    ref: "ViewChannelCatalogFilter-UpdateCatalogFilter"
  - id: "Call4"
    type: "call"
    ref: "ViewChannelCatalogFilter-Prefix"
  - id: "Call5"
    type: "call"
    ref: "ViewChannelCatalogFilter-CreateWebForm"
  - id: "Call6"
    type: "call"
    ref: "ViewChannelCatalogFilter-CreateWebForm"
  - id: "Call7"
    type: "call"
    ref: "ViewChannelCatalogFilter-Prefix"
  - id: "Call8"
    type: "call"
    ref: "ViewChannelCatalogFilter-Prefix"
  - id: "Call9"
    type: "call"
    ref: "ViewChannelCatalogFilter-UpdateCatalogFilter"
  - id: "CallNode1"
    type: "call"
    ref: "ViewChannelCatalogFilter-InvalidatePageCaches"
  - id: "CallNode2"
    type: "call"
    ref: "ViewChannelCatalogFilter-GetSites"
  - id: "CallNode3"
    type: "call"
    ref: "ViewChannelCatalogFilter-GetSites"
  - id: "CallNode4"
    type: "call"
    ref: "ViewChannelCatalogFilter-InvalidatePageCaches"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "\"SLD_AR_\""
      String1: "CurrentChannel:TypeCode"
      String2: "\"_CATALOG_VIEWER\""
      Concatenated: "PermissionGroupID"
  - id: "CreateCatalogFilter1"
    type: "pipelet"
    ref: "CreateCatalogFilter"
    bindings:
      Filter: "CatalogFilter"
      OrganizationDomain: "CurrentChannel:Domain"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "DisplayName"
      param.1.required: true
      param.2.name: "Description"
      param.2.required: false
      param.3.name: "OnlineFlag"
      param.3.required: false
      param.4.name: "UpdateInterval"
      param.4.required: true
      webform-id: "CatalogFilterForm"
    bindings:
      WebForm: "CatalogFilterForm"
  - id: "Decision1"
    type: "decision"
    condition: "CatalogFilter"
  - id: "Decision2"
    type: "decision"
    condition: "CatalogFilterUUID"
  - id: "Decision3"
    type: "decision"
    condition: "CatalogFilter"
  - id: "DecisionNode1"
    type: "decision"
    condition: "CatalogFilter:State"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelCatalogFilter-Create"
      OutValue_1: "ViewChannelCatalogFilter-Back"
      OutValue_2: "ViewChannelCatalogFilter-Back"
      OutValue_3: "ViewChannelCatalogFilter-Update"
      OutValue_4: "ViewChannelCatalogFilter-Publish"
      OutValue_5: "ViewChannelCatalogFilter-Edit"
      OutValue_6: "ViewChannelCatalogFilter-Delete"
      OutValue_7: "ViewChannelCatalogFilter-Edit"
      OutValue_8: "ViewChannelCatalogFilter-Edit"
    bindings:
      Key_0: "create"
      Key_1: "cancelCreate"
      Key_2: "backToList"
      Key_3: "update"
      Key_4: "publish"
      Key_5: "confirmDelete"
      Key_6: "delete"
      Key_7: "reset"
      Key_8: "cancelDelete"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "GetCatalogFilter1"
    type: "pipelet"
    ref: "GetCatalogFilter"
    bindings:
      Filter: "CatalogFilter"
      FilterID: "CatalogFilterUUID"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "CatalogFilterList"
      RestorePageLocatorDictionary: "True"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "CurrentChannel"
      UUID: "ChannelID"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "CatalogFilterForm"
    bindings:
      WebForm: "CatalogFilterForm"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "CatalogFilterForm"
    bindings:
      WebForm: "CatalogFilterForm"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InvalidatePageLocatorPageable1"
    type: "pipelet"
    ref: "InvalidatePageLocatorPageable"
    config:
      DefaultPageLocatorName: "CatalogFilterList"
    bindings:
      PageLocatorName: "null"
  - id: "InvalidatePageLocatorPageable2"
    type: "pipelet"
    ref: "InvalidatePageLocatorPageable"
    config:
      DefaultPageLocatorName: "CatalogFilterList"
    bindings:
      PageLocatorName: "null"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump2"
    type: "jump"
    ref: "ViewChannelCatalogFilter-Edit"
  - id: "Jump3"
    type: "jump"
    ref: "ViewChannelCatalogFilter-Edit"
  - id: "Jump4"
    type: "jump"
    ref: "ViewChannelCatalogFilter-Edit"
  - id: "Jump5"
    type: "jump"
    ref: "ViewChannelCatalogFilterList-ListAll"
  - id: "Jump6"
    type: "jump"
    ref: "ViewChannelCatalogFilter-Back"
  - id: "Jump7"
    type: "jump"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CatalogFilter"
      InValue_2: "CurrentChannel"
      OutValue_1: "Filter"
      OutValue_2: "Repository"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CatalogFilter:State"
      OutValue_1: "OldState"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "CatalogFilters"
      WorkingTemplate: "filter/ChannelNewCatalogFilter"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "CatalogFilters"
      WorkingTemplate: "filter/ChannelCatalogFilter"
  - id: "RemoveCatalogFilter1"
    type: "pipelet"
    ref: "RemoveCatalogFilter"
    bindings:
      Filter: "CatalogFilter"
  - id: "UpdateCatalogFilter1"
    type: "pipelet"
    ref: "UpdateCatalogFilter"
    bindings:
      Description: "CatalogFilterForm:Description:Value"
      Filter: "CatalogFilter"
      Name: "CatalogFilterForm:DisplayName:Value"
      OnlineFlag: "CatalogFilterForm:OnlineFlag:Value"
      UpdateInterval: "CatalogFilterForm:UpdateInterval:Value"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "CatalogFilterForm"
    bindings:
      WebForm: "CatalogFilterForm"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "CatalogFilterForm"
    bindings:
      WebForm: "CatalogFilterForm"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "CatalogFilterForm"
  - id: "ValidateWebForm2"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "CatalogFilterForm"

links:
  - from: "Start1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "Join2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "ValidateWebForm1"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "ValidateWebForm1"
    via: "next"
    to: "CreateCatalogFilter1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "CreateCatalogFilter1"
    via: "error"
    to: "Join3"
    into: "in3"
  - from: "Call3"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "UpdateCatalogFilter1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CreateWebForm1"
    via: "next"
    to: "End3"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Join6"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Start6"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "GetCatalogFilter1"
    via: "next"
    to: "Join4"
    into: "in2"
  - from: "Start8"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "UpdateWebForm2"
    via: "next"
    to: "ValidateWebForm2"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "GetWebForm2"
    via: "error"
    to: "Join6"
    into: "in2"
  - from: "GetWebForm2"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "ValidateWebForm2"
    via: "error"
    to: "Join5"
    into: "in2"
  - from: "Call1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Decision1"
    via: "no"
    to: "Join4"
    into: "in3"
  - from: "Start10"
    via: "next"
    to: "Call12"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "GetCatalogFilter1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join4"
    into: "in1"
  - from: "Join4"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Decision2"
    into: "in"
  - from: "ValidateWebForm2"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "RemoveCatalogFilter1"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "Jump6"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Join7"
    into: "in3"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "Call11"
    into: "in"
  - from: "Call11"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Start11"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "Jump7"
    into: "in"
  - from: "GetPageLocator1"
    via: "error"
    to: "Jump5"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "InvalidatePageLocatorPageable1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "InvalidatePageLocatorPageable2"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "Call12"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "RemoveCatalogFilter1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "UpdateCatalogFilter1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode3"
    into: "in2"
  - from: "JoinNode3"
    via: "next"
    to: "InvalidatePageLocatorPageable1"
    into: "in"
  - from: "CreateCatalogFilter1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "InvalidatePageLocatorPageable2"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Call4"
    into: "in"
