flow: "ViewPageComponents"
kind: "view"

entries:
  - id: "Start2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "EditSelected"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "EditAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "New"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "StartReplication"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "SelectTarget"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "View"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "Delete"
    mode: "public"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "PagesVector"
      OutVector: "PagesVector"
      Object: "Page"
      Objects: "null"
      Iterator: "Pages"
  - id: "AddObjectToVector3"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "PageComponentsVector"
      OutVector: "PageComponentsVector"
      Object: "PageComponent"
      Objects: "null"
      Iterator: "PageComponents"
  - id: "Call2"
    type: "call"
    ref: "ProcessPageletSearch-UpdateClipboard"
    bindings:
      PageFlag: "\"false\""
  - id: "Call7"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "Call9"
    type: "call"
    ref: "ProcessBatchJob-Create"
    bindings:
      ProcessDescription: "\"Replicate Content\""
  - id: "CallNode1"
    type: "call"
    ref: "ProcessPageletSearch-GetCurrentClipboardName"
    bindings:
      PageFlag: "\"false\""
  - id: "CallNode10"
    type: "call"
    ref: "ProcessPagelet-Delete"
  - id: "CallNode13"
    type: "call"
    ref: "ProcessPageletSearch-AddError"
  - id: "CallNode14"
    type: "call"
    ref: "ProcessPageletSearch-UpdateClipboard"
  - id: "CallNode15"
    type: "call"
    ref: "Prefix-GetPipelineName"
    bindings:
      PipelineName: "\"ViewProcessList\""
      StartNode: "\"ListAll\""
  - id: "CallNode18"
    type: "call"
    ref: "ProcessReplicateObjects-GetTargetClusters"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessPageletSearch-UpdateClipboard"
    bindings:
      PageFlag: "\"false\""
  - id: "CallNode3"
    type: "call"
    ref: "ProcessPageletSearch-AddError"
    bindings:
      UniquePageletSearchID: "\"PageComponents\""
  - id: "CallNode4"
    type: "call"
    ref: "ProcessPageletSearch-UpdateClipboard"
    bindings:
      PageFlag: "\"false\""
  - id: "CallNode5"
    type: "call"
    ref: "ProcessPageletSearch-RemoveCurrentClipboard"
  - id: "CallNode7"
    type: "call"
    ref: "ViewPageletTemplatesList-CheckReplicationObjects"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessPageletSearch-GetCurrentClipboardName"
  - id: "CallNode9"
    type: "call"
    ref: "ProcessPageletLock-CheckUnlocked"
    bindings:
      CheckedUserID: "CurrentUser:ID"
  - id: "CheckForEmptyIterator1"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "SelectedPageletsUUIDIterator"
  - id: "CheckForEmptyIterator2"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "SelectedPageletsUUIDIterator"
  - id: "CreatePageableFromIterator1"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    config:
      PageableName: "PageComponents"
      Pagesize: 15
    bindings:
      Iterator: "PageComponents"
      Pageable: "PageComponents"
  - id: "CreatePageableFromIterator2"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    config:
      Pagesize: 15
    bindings:
      Iterator: "Pages"
      Pageable: "Pages"
  - id: "DecisionNode6"
    type: "decision"
    condition: "Pagelet:DomainID"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_5: "ViewPageComponents-Delete"
      OutValue_6: "ViewPageComponents-New"
      OutValue_7: "ViewPageComponents-Paging"
      PagingPipeline: "ViewPageComponents-Paging"
      OutValue_3: "ViewPageComponents-EditAll"
      OutValue_4: "ViewPageComponents-EditSelected"
      OutValue_8: "ViewPageComponents-SelectTarget"
      OutValue_1: "ViewPageComponents-StartReplication"
      OutValue_2: "ViewPageComponents-Paging"
    bindings:
      SelectionKey: "JumpTarget"
      Key_5: "delete"
      Key_6: "new"
      Key_7: "confirmDelete"
      Key_3: "editAll"
      Key_4: "editSelected"
      Key_8: "selectStagingTarget"
      Key_1: "confirmStaging"
  - id: "GetClipboard1"
    type: "pipelet"
    ref: "GetClipboard"
    config:
      SetFormValues: "No"
    bindings:
      UUIDIterator: "PageComponentUUIDs"
      SessionRegistrationID: "ClipboardName"
  - id: "GetClipboard2"
    type: "pipelet"
    ref: "GetClipboard"
    config:
      SetFormValues: "No"
    bindings:
      UUIDIterator: "SelectedPageletsUUIDIterator"
      SessionRegistrationID: "ClipboardName"
  - id: "GetClipboard3"
    type: "pipelet"
    ref: "GetClipboard"
    config:
      SetFormValues: "No"
    bindings:
      UUIDIterator: "SelectedPageletsUUIDIterator"
      SessionRegistrationID: "ClipboardName"
  - id: "GetClipboard4"
    type: "pipelet"
    ref: "GetClipboard"
    config:
      SetFormValues: "No"
    bindings:
      UUIDIterator: "SelectedPageletsUUIDIterator"
      SessionRegistrationID: "ClipboardName"
  - id: "GetPageletByUUID1"
    type: "pipelet"
    ref: "GetPageletByUUID"
    bindings:
      PageletUUID: "PageComponentUUID"
  - id: "GetPageletByUUID2"
    type: "pipelet"
    ref: "GetPageletByUUID"
    bindings:
      PageletUUID: "PageComponentUUID"
      Pagelet: "PageComponent"
  - id: "GetPageletByUUID3"
    type: "pipelet"
    ref: "GetPageletByUUID"
    bindings:
      PageletUUID: "PageUUID"
      Pagelet: "Page"
  - id: "InteractionEnd12"
    type: "interaction"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "Join7"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewComponentProcessingWizard-SelectAction"
  - id: "Jump2"
    type: "jump"
    ref: "This:Paging"
  - id: "Jump4"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump6"
    type: "jump"
    ref: "ViewComponentProcessingWizard-SelectAction"
  - id: "Jump8"
    type: "jump"
    ref: "ViewPageComponents-Paging"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewPageComponents-View"
  - id: "JumpNode15"
    type: "jump"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewPagelet-New"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "Repository:Domain"
      OutValue_1: "ProcessOwningDomain"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"All\""
      OutValue_1: "SelectedObjects"
      InValue_2: "ContentRepository:UUID"
      OutValue_2: "RepositoryUUID"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "\"ProcessReplicateObjects-Init\""
      InValue_2: "\"ProcessReplicateObjects-Process\""
      InValue_3: "\"ProcessReplicateObjects-Post\""
      InValue_4: "\"MasterContentReplication\""
      InValue_5: "\"Pages\""
      OutValue_1: "InitPipeline"
      OutValue_2: "ProcessPipeline"
      OutValue_3: "PostPipeline"
      OutValue_4: "JobName"
      OutValue_5: "PageableName"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "JobName"
      OutValue_1: "JobNamePrefix"
  - id: "KeyMapper8"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "PageComponents:ID"
      OutValue_1: "PageableID"
      InValue_2: "\"Selected\""
      OutValue_2: "SelectedObjects"
      InValue_3: "ContentRepository:UUID"
      OutValue_3: "RepositoryUUID"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "LoopNode3"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "content/PageComponents"
      SelectedMenuItem: "MasterComponents"
  - id: "PrepareApplicationView12"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ContentOverview"
      WorkingTemplate: "replication/ReplicateContentWizardSelectTarget"
  - id: "RegisterPageable2"
    type: "pipelet"
    ref: "RegisterPageable"
    bindings:
      PageableName: "\"Pages\""
      see PageableName: "Pages"
      PageableID: "PageableID"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "PageComponentsVector"
      RemoveFormValues: false
  - id: "RemoveDictionaryValue2"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "PageletUUID"
      RemoveFormValues: true
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewPageComponents-Paging"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "StartFlag"
      Value: true
  - id: "UpdateMapping1"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
      DefaultKey: "ERROR_NOTHING_SELECTED"
      DefaultValue: true
    bindings:
      OutMap: "ErrorMap"
  - id: "UpdateMapping2"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
      DefaultKey: "ERROR_NOTHING_SELECTED_TO_PUBLISH"
      DefaultValue: true
    bindings:
      OutMap: "ErrorMap"
  - id: "UpdateMapping3"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
      DefaultKey: "SHARED_OBJECT_ERROR"
      DefaultValue: true
    bindings:
      OutMap: "ErrorMap"

links:
  - from: "StartNode6"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Join7"
    into: "in3"
  - from: "Start2"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "error"
    to: "UpdateMapping1"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "GetPageletByUUID3"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "KeyMapper4"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "RemoveDictionaryValue2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Jump8"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "UpdateMapping1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "GetClipboard2"
    into: "in"
  - from: "GetClipboard2"
    via: "next"
    to: "CheckForEmptyIterator1"
    into: "in"
  - from: "GetClipboard1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "CallNode9"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode3"
    into: "in3"
  - from: "RemoveDictionaryValue2"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "LoopNode3"
    via: "next"
    to: "CreatePageableFromIterator2"
    into: "in"
  - from: "CallNode14"
    via: "next"
    to: "GetClipboard3"
    into: "in"
  - from: "CreatePageableFromIterator2"
    via: "next"
    to: "RegisterPageable2"
    into: "in"
  - from: "KeyMapper8"
    via: "next"
    to: "Jump6"
    into: "in"
  - from: "CheckForEmptyIterator2"
    via: "error"
    to: "UpdateMapping2"
    into: "in"
  - from: "AddObjectToVector3"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "StartNode3"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "RegisterPageable2"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "GetPageletByUUID2"
    into: "in"
  - from: "CallNode7"
    via: "OK"
    to: "CallNode18"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "CallNode15"
    into: "in"
  - from: "CallNode18"
    via: "next"
    to: "PrepareApplicationView12"
    into: "in"
  - from: "CallNode15"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "UpdateMapping2"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "AddObjectToVector1"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "CallNode10"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "GetClipboard4"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "JumpNode15"
    into: "in"
  - from: "CheckForEmptyIterator2"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "GetClipboard3"
    via: "next"
    to: "CheckForEmptyIterator2"
    into: "in"
  - from: "GetPageletByUUID2"
    via: "next"
    to: "AddObjectToVector3"
    into: "in"
  - from: "UpdateMapping3"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "GetClipboard4"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "CallNode7"
    via: "SharedObjectError"
    to: "UpdateMapping3"
    into: "in"
  - from: "GetPageletByUUID1"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "PrepareApplicationView12"
    via: "next"
    to: "InteractionEnd12"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "CallNode9"
    via: "LOCKED"
    to: "JoinNode8"
    into: "in3"
  - from: "LoopNode3"
    via: "do"
    to: "GetPageletByUUID3"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "GetClipboard1"
    into: "in"
  - from: "GetPageletByUUID1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "CreatePageableFromIterator1"
    via: "next"
    to: "KeyMapper8"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "CreatePageableFromIterator1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "CallNode9"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "CheckForEmptyIterator1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "GetPageletByUUID1"
    into: "in"
