flow: "ViewCatalogCategoryProductAssignment"
kind: "view"

entries:
  - id: "Start1"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "ParametricSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "Search"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "GetAssignedProducts"
    mode: "private"
    strict: true
    inputs:
      - key: "CatalogCategoryID"
        type: "java.lang.String"
        required: false
  - id: "StartNode2"
    name: "Cancel"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode23"
    name: "AssignAll"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Assign"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AssignProductToCatalogCategory2"
    type: "pipelet"
    ref: "AssignProductToCatalogCategory"
    bindings:
      Domain: "Product:Domain"
      CatalogCategory: "Category"
  - id: "CalculateInteger1"
    type: "pipelet"
    ref: "CalculateInteger"
    config:
      Operation: "+"
    bindings:
      Result: "NumberOfSelectedProducts"
      Operand1: "\"(Integer)0\""
  - id: "Call1"
    type: "call"
    ref: "ViewParametricSearch-SimpleMasterProductSearch"
  - id: "Call10"
    type: "call"
    ref: "This:GetAssignedProducts"
  - id: "Call2"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call22"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call3"
    type: "call"
    ref: "ProcessCatalog-Browse"
  - id: "Call4"
    type: "call"
    ref: "ViewParametricSearch-SearchMasterProduct"
  - id: "Call5"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call6"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call7"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call8"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "CallNode1"
    type: "call"
    ref: "ValidateWebForms-WFAdvancedSearch"
  - id: "CallNode10"
    type: "call"
    ref: "ViewProductList-StorePageLocatorParameters"
  - id: "CallNode2"
    type: "call"
    ref: "ValidateWebForms-WFSimpleSearch"
  - id: "CallNode23"
    type: "call"
    ref: "ProcessProductHistory-CreateChangeEntry"
  - id: "CallNode27"
    type: "call"
    ref: "ProcessProductHistory-UpdateChangeEntry"
  - id: "CallNode3"
    type: "call"
    ref: "ViewBrowseCatalogCategory-GetCatalog"
  - id: "CallNode38"
    type: "call"
    ref: "ProcessProductHistory-PrepareData"
  - id: "CallNode4"
    type: "call"
    ref: "ViewBrowseCatalogCategory-GetCatalog"
  - id: "CallNode44"
    type: "call"
    ref: "ProcessProductLock-CheckUnlocked"
  - id: "CallNode49"
    type: "call"
    ref: "ViewProductList-PrepareCurrentSearchType"
  - id: "CallNode5"
    type: "call"
    ref: "ViewProductList-GetServiceTypeCategories"
  - id: "CallNode52"
    type: "call"
    ref: "ViewProductList-PrepareCustomAttributesSearchMask"
    bindings:
      Domain: "OrganizationDomain"
      Locale: "CurrentRequest:Locale"
  - id: "CallNode54"
    type: "call"
    ref: "ViewProductList-SetCurrentSearchTypePageLocatorParameter"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessBatchJob-Create"
  - id: "CallNode7"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "CheckForEmptyIterator1"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "UUIDIterator"
  - id: "CreateIteratorFromPageable1"
    type: "pipelet"
    ref: "CreateIteratorFromPageable"
    bindings:
      PageableIterator: "Products"
      ResettableIterator: "CategoryProducts"
  - id: "CreateProductIdentifierLookupHelper1"
    type: "pipelet"
    ref: "CreateProductIdentifierLookupHelper"
    config:
      LookupType: "ProductDomainLookup"
    bindings:
      ProductDomain: "CurrentMasterRepository:RepositoryDomain"
  - id: "Decision1"
    type: "decision"
    condition: "PageLocator"
  - id: "Decision2"
    type: "decision"
    condition: "PageNumber"
  - id: "DecisionNode1"
    type: "decision"
    condition: "UUIDIterator"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      DefaultPageNumberPrefix: "PageSize_"
    bindings:
      PageNumber: "newPageSize"
      PageNumberPrefix: "PageSize_"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewCatalogCategoryProductAssignment-Search"
      OutValue_1: "ViewCatalogCategoryProductAssignment-ParametricSearch"
      OutValue_2: "ViewCatalogCategoryProductAssignment-Paging"
      PagingPipeline: "ViewCatalogCategoryProductAssignment-Paging"
      OutValue_3: "ViewCatalogCategoryProductAssignment-Cancel"
      OutValue_4: "ViewCatalogCategoryProductAssignment-Assign"
      OutValue_5: "ViewCatalogCategoryProductAssignment-Paging"
      OutValue_6: "ViewCatalogCategoryProductAssignment-Paging"
      OutValue_8: "ViewCatalogCategoryProductAssignment-AssignAll"
      OutValue_7: "ViewCatalogCategoryProductAssignment-Paging"
    bindings:
      Key_0: "findSimple"
      Key_1: "findParametric"
      SelectionKey: "JumpTarget"
      Key_2: "jumpToList"
      Key_3: "cancel"
      Key_4: "assignSelected"
      Key_5: "Expand"
      Key_6: "Collapse"
      Key_7: "confirmAssignAllProducts"
      Key_8: "assignAllProducts"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "Category"
        type: "com.intershop.beehive.xcs.capi.catalog.CatalogCategory"
        guaranteed: true
      - key: "CategoryProducts"
        type: "java.util.Iterator"
        guaranteed: false
  - id: "GetCategoryByUUID1"
    type: "pipelet"
    ref: "GetCategoryByUUID"
  - id: "GetCategoryByUUID2"
    type: "pipelet"
    ref: "GetCategoryByUUID"
  - id: "GetCurrencies1"
    type: "pipelet"
    ref: "GetCurrencies"
    config:
      Method: "Active Currencies"
    bindings:
      Domain: "OrganizationDomain"
  - id: "GetIteratorSize1"
    type: "pipelet"
    ref: "GetIteratorSize"
    bindings:
      Iterator: "UUIDIterator"
      Size: "NumberOfSelectedProducts"
  - id: "GetLabels2"
    type: "pipelet"
    ref: "GetLabels"
    bindings:
      Domain: "OrganizationDomain"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "CategoryProductList"
      RestorePageLocatorDictionary: "True"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Products"
      PageableID: "PageLocator:PageableID"
  - id: "GetProductByUUID1"
    type: "pipelet"
    ref: "GetProductByUUID"
    bindings:
      ProductDomain: "CurrentMasterRepository:RepositoryDomain"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump3"
    type: "jump"
    ref: "This:Search"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewBrowseCatalogCategory-Paging"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewBrowseCatalogCategory-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "This:Paging"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewBrowseCatalogCategory-Start"
  - id: "JumpNode5"
    type: "jump"
    ref: "ViewProcessList-ListAll"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CategoryProductList"
      OutValue_1: "PageLocator"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Repository:Domain"
      OutValue_1: "ProcessOwningDomain"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "\"BatchProcessProducts-AssignProductsToCategory\""
      InValue_2: "\"BatchProcessProducts-InitAssignProductsToCategory\""
      InValue_3: "\"BatchProcessProducts-PostBatch\""
      InValue_4: "\"Catalog\""
      InValue_5: "\"Catalog\""
      OutValue_1: "ProcessPipeline"
      OutValue_2: "InitPipeline"
      OutValue_3: "PostPipeline"
      OutValue_4: "JobName"
      OutValue_5: "JobNamePrefix"
  - id: "LoopNode3"
    type: "loop"
  - id: "Pipelet9"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Organization:OrganizationDomain"
      OutValue_1: "PreferenceDomain"
      InValue_2: "CurrentUser:ID"
      OutValue_2: "CheckedUserID"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Catalogs"
      WorkingTemplate: "category/CatalogCategoryProductSelection"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "PageNumber"
      RemoveFormValues: true
  - id: "RemoveDictionaryValue2"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "PageNumber"
      RemoveFormValues: true
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "DetermineRepositoriesPipeline"
      Value: "DetermineRepositories-Master"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewCatalogCategoryProductAssignment-Paging"
      ValueType: "Dictionary Value"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Products"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Products"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewCatalogCategoryProductAssignment-Paging"
      DefaultPageLocatorName: "CategoryProductList"
    bindings:
      Pageable: "Products"
      PageLocator: "CategoryProductList"
      PageLocatorName: "null"
  - id: "SetPageLocatorParameter1"
    type: "pipelet"
    ref: "SetPageLocatorParameter"
    config:
      DefaultParameterName: "CatalogCategoryID"
    bindings:
      PageLocator: "CategoryProductList"
      ParameterValue: "CatalogCategoryID"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"

links:
  - from: "SetPage2"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "GetLabels2"
    via: "next"
    to: "GetCurrencies1"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join2"
    into: "in3"
  - from: "CallNode1"
    via: "ERROR"
    to: "JoinNode2"
    into: "in3"
  - from: "Join2"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Join5"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "CallNode27"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "CallNode49"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Join3"
    into: "in2"
  - from: "CallNode2"
    via: "ERROR"
    to: "JoinNode2"
    into: "in2"
  - from: "CallNode1"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode8"
    into: "in3"
  - from: "Decision2"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "GetCategoryByUUID2"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "Join3"
    into: "in3"
  - from: "Call2"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "CreateProductIdentifierLookupHelper1"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join5"
    into: "in3"
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "DispatchFormAction2"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage2"
    into: "in"
  - from: "DispatchFormAction2"
    via: "error"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "GetPageLocator1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "SetPage1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "JoinNode10"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "GetCurrencies1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Call3"
    via: "next"
    to: "CreateIteratorFromPageable1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetCategoryByUUID2"
    into: "in"
  - from: "GetCategoryByUUID2"
    via: "error"
    to: "JumpNode2"
    into: "in"
  - from: "CreateIteratorFromPageable1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "CallNode52"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "CreateProductIdentifierLookupHelper1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "SetPage1"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Start7"
    via: "next"
    to: "Call22"
    into: "in"
  - from: "Call22"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "error"
    to: "JumpNode3"
    into: "in"
  - from: "GetProductByUUID1"
    via: "next"
    to: "CallNode44"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "next"
    to: "GetCategoryByUUID1"
    into: "in"
  - from: "CallNode52"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode23"
    via: "next"
    to: "AssignProductToCatalogCategory2"
    into: "in"
  - from: "CallNode54"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "CallNode38"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "AssignProductToCatalogCategory2"
    via: "next"
    to: "CallNode27"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetIteratorSize1"
    into: "in"
  - from: "CallNode49"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "RemoveDictionaryValue2"
    into: "in"
  - from: "RemoveDictionaryValue2"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "GetCategoryByUUID1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode44"
    via: "LOCKED"
    to: "JoinNode5"
    into: "in3"
  - from: "CallNode4"
    via: "next"
    to: "GetLabels2"
    into: "in"
  - from: "GetCategoryByUUID1"
    via: "error"
    to: "JoinNode9"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "Pipelet9"
    into: "in"
  - from: "LoopNode3"
    via: "next"
    to: "JoinNode10"
    into: "in2"
  - from: "LoopNode3"
    via: "do"
    to: "GetProductByUUID1"
    into: "in"
  - from: "SetPageLocator1"
    via: "next"
    to: "SetPageLocatorParameter1"
    into: "in"
  - from: "CallNode3"
    via: "Error"
    to: "JoinNode9"
    into: "in2"
  - from: "SetPageLocatorParameter1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "GetProductByUUID1"
    via: "error"
    to: "JoinNode11"
    into: "in3"
  - from: "CallNode44"
    via: "next"
    to: "CallNode23"
    into: "in"
  - from: "JoinNode11"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "KeyMapper1"
    via: "next"
    to: "CallNode54"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "CalculateInteger1"
    into: "in"
  - from: "CalculateInteger1"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "GetIteratorSize1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Decision1"
    into: "in"
  - from: "Pipelet9"
    via: "next"
    to: "CallNode38"
    into: "in"
  - from: "StartNode23"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "CheckForEmptyIterator1"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "DispatchFormAction2"
    via: "next"
    to: "JoinNode8"
    into: "in1"
