flow: "ViewProductHistory"
kind: "view"

entries:
  - id: "Start1"
    name: "Search"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Detail"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "JumpToList"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "DeletedProductDetails"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Restore"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Iterator: "ProductUUIDs"
      OutVector: "null"
      Object: "ProductID"
      InVector: "null"
      Objects: "null"
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Iterator: "ProductUUIDs"
      OutVector: "null"
      Object: "ProductID"
      InVector: "null"
      Objects: "null"
  - id: "Call10"
    type: "call"
    ref: "DetermineRepositories-RecycleBin"
  - id: "Call2"
    type: "call"
    ref: "ProcessProductHistory-Search"
  - id: "Call3"
    type: "call"
    ref: "ProcessRecycleBin-DeleteFromRecycleBin"
  - id: "Call4"
    type: "call"
    ref: "ProcessRecycleBin-RestoreFromRecycleBin"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessProductHistory-CompareSnapShots"
  - id: "CallNode2"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "CallNode4"
    type: "call"
    ref: "DetermineProduct-RecycleBinProduct"
  - id: "CreateProductIdentifierLookupHelper1"
    type: "pipelet"
    ref: "CreateProductIdentifierLookupHelper"
    config:
      LookupType: "ProductDomainLookup"
    bindings:
      LookupHelper: "Helper"
      ProductDomain: "CurrentMasterRepository:RepositoryDomain"
  - id: "CreateProductIdentifierLookupHelper2"
    type: "pipelet"
    ref: "CreateProductIdentifierLookupHelper"
    config:
      LookupType: "ProductDomainLookup"
    bindings:
      ProductDomain: "RecycleBin:Domain"
  - id: "CreateProductSnapShotFromSnapShotData1"
    type: "pipelet"
    ref: "CreateProductSnapShotFromSnapShotData"
    bindings:
      ProductSnapShot: "OldProductSnapShot"
      SnapShotData: "JournalEntry:OldSnapShotData"
  - id: "Decision1"
    type: "decision"
    condition: "ChangedSince"
  - id: "Decision2"
    type: "decision"
    condition: "PageLocator"
  - id: "Decision3"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision4"
    type: "decision"
    condition: "ChangeType"
  - id: "Decision5"
    type: "decision"
    condition: "ChangeType"
  - id: "DecisionNode1"
    type: "decision"
    condition: "JournalEntry:OldSnapShotData"
  - id: "DecisionNode2"
    type: "decision"
    condition: "JournalEntry:NewSnapShotData"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProductHistory-Search"
      PagingPipeline: "ViewProductHistory-Paging"
      OutValue_1: "ViewProductHistory-Restore"
      OutValue_2: "ViewProductHistory-DeletedProductDetails"
      OutValue_3: "ViewProductHistory-Delete"
      OutValue_4: "ViewProductHistory-DeletedProductDetails"
    bindings:
      Key_0: "find"
      SelectionKey: "JumpTarget"
      Key_1: "restore"
      Key_2: "delete"
      Key_3: "confirmDelete"
      Key_4: "cancelDelete"
  - id: "ExchangeSessionObject1"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "RFG_JournalEntries"
    bindings:
      TargetSessionID: "null"
      TargetSessionDomain: "null"
      SessionObjectName: "null"
      SaveObject: "JournalEntries"
      LoadObject: "PreviousJournalEntries"
  - id: "ExchangeSessionObject2"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "RFG_JournalEntries"
    bindings:
      TargetSessionID: "null"
      TargetSessionDomain: "null"
      SessionObjectName: "null"
      SaveObject: "null"
      LoadObject: "JournalEntries"
  - id: "GetCustomAttributes1"
    type: "pipelet"
    ref: "GetCustomAttributes"
    config:
      FilteredAttributes: "name;SKU;shortDescription;longDescription;supplierID;manufacturerName;manufacturerSKU;AC_*;PID_*;Attrib_*"
    bindings:
      AttributeValues: "CustomAttributes"
      ExtensibleObject: "Product"
  - id: "GetDomainPreference2"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "RecycleBinUsage"
      Type: "String"
    bindings:
      PreferenceDomain: "Organization:Domain"
      PreferenceStringValue: "RecycleBinUsage"
  - id: "GetJournalEntryByUUID1"
    type: "pipelet"
    ref: "GetJournalEntryByUUID"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ProductList"
      RestorePageLocatorDictionary: "True"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "JournalEntries"
      PageableID: "PageLocator:PageableID"
  - id: "GetRepositoryByID1"
    type: "pipelet"
    ref: "GetRepositoryByID"
    config:
      DefaultRepositoryID: "MasterRepository"
    bindings:
      Domain: "OrganizationDomain"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewProductHistory-Search"
  - id: "JumpNode2"
    type: "jump"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewProductHistory-JumpToList"
  - id: "JumpNode5"
    type: "jump"
    ref: "ViewProductHistory-JumpToList"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_SNAP_SHOT"
      Value: "NoSnapShot"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "CreateProductSnapShotFromSnapShotData"
    bindings:
      SnapShotData: "JournalEntry:NewSnapShotData"
      ProductSnapShot: "NewProductSnapShot"
  - id: "Pipelet28"
    type: "pipelet"
    ref: "GetCurrencies"
    config:
      Method: "Active Currencies"
    bindings:
      Domain: "OrganizationDomain"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_JOURNAL_ENTRY"
      Value: "JournalEntryNotFound"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ProductList"
      RestorePageLocatorDictionary: "True"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "GetTaxClasses"
    bindings:
      Domain: "OrganizationDomain"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "SetPageLocatorParameter"
    config:
      DefaultParameterName: "ChangeType"
    bindings:
      ParameterValue: "ChangeType"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "Pipelet9"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      User: "CurrentUser"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      RenderingType: "HTML"
      SelectedMenuItem: "ProductHistory"
      WorkingTemplate: "producthistory/ProductHistoryUpdated"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      RenderingType: "HTML"
      SelectedMenuItem: "ProductHistory"
      WorkingTemplate: "producthistory/ProductHistoryDeleted"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      RenderingType: "HTML"
      SelectedMenuItem: "ProductHistory"
      WorkingTemplate: "producthistory/ProductHistoryAdded"
  - id: "PrepareApplicationView4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      RenderingType: "HTML"
      SelectedMenuItem: "ProductHistory"
      WorkingTemplate: "producthistory/ProductHistoryDetail"
  - id: "PrepareApplicationView5"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "RecycleBin"
      WorkingTemplate: "producthistory/ProductHistoryDeletedProductDetails"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "DetermineRepositoriesPipeline"
      Value: "DetermineRepositories-Master"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_SEARCH"
      Value: "InvalidDate"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewProductHistory-JumpToList"
      ValueType: "Dictionary Value"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "JournalEntries"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "JournalEntries"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewProductHistory-Paging"
      DefaultPageLocatorName: "ProductList"
    bindings:
      Pageable: "JournalEntries"
  - id: "VerifyDate1"
    type: "pipelet"
    ref: "VerifyDate"
    bindings:
      Date: "changed_since"
      DatePattern: "DateFormatString"
      DateString: "ChangedSince"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "change_type"
      LocalizedString: "ChangeType"
  - id: "VerifyInteger2"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"

links:
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "VerifyDate1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Call4"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "GetRepositoryByID1"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Decision2"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "SetPage2"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "VerifyInteger2"
    into: "in"
  - from: "VerifyInteger2"
    via: "next"
    to: "SetPage1"
    into: "in"
  - from: "SetPage1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "VerifyInteger2"
    via: "error"
    to: "Join4"
    into: "in3"
  - from: "VerifyInteger1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "SetPage2"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Decision2"
    via: "no"
    to: "Join3"
    into: "in3"
  - from: "Join3"
    via: "next"
    to: "Join5"
    into: "in3"
  - from: "SetPageLocator1"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "ExchangeSessionObject2"
    into: "in"
  - from: "Call2"
    via: "ERROR"
    to: "JoinNode8"
    into: "in1"
  - from: "GetPageable1"
    via: "error"
    to: "Join6"
    into: "in2"
  - from: "GetPageLocator1"
    via: "error"
    to: "Join6"
    into: "in1"
  - from: "Pipelet11"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Join6"
    via: "next"
    to: "Join7"
    into: "in3"
  - from: "Pipelet9"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "VerifyDate1"
    via: "error"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "GetDomainPreference2"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "Join9"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "GetLocale2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "Join9"
    into: "in3"
  - from: "Decision5"
    via: "no"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "Decision5"
    via: "yes"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "Decision5"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "GetJournalEntryByUUID1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "DecisionNode2"
    into: "in"
  - from: "PrepareApplicationView4"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "Pipelet9"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "CreateProductIdentifierLookupHelper1"
    via: "next"
    to: "GetDomainPreference2"
    into: "in"
  - from: "CreateProductSnapShotFromSnapShotData1"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "CreateProductIdentifierLookupHelper1"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode7"
    into: "in1"
  - from: "CreateProductSnapShotFromSnapShotData1"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "CreateProductSnapShotFromSnapShotData1"
    into: "in"
  - from: "GetJournalEntryByUUID1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Pipelet4"
    via: "error"
    to: "JumpNode1"
    into: "in"
  - from: "Pipelet2"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "Join9"
    into: "in2"
  - from: "GetJournalEntryByUUID1"
    via: "error"
    to: "Pipelet3"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "Pipelet4"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "PrepareApplicationView4"
    into: "in"
  - from: "ExchangeSessionObject2"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "Pipelet7"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Join7"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "VerifyDate1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "VerifyInteger1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "Pipelet11"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode7"
    into: "in1"
  - from: "ExchangeSessionObject1"
    via: "error"
    to: "JoinNode8"
    into: "in2"
  - from: "Call2"
    via: "next"
    to: "ExchangeSessionObject1"
    into: "in"
  - from: "ExchangeSessionObject1"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "ExchangeSessionObject2"
    via: "error"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode4"
    into: "in2"
  - from: "CreateProductIdentifierLookupHelper2"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "CreateProductIdentifierLookupHelper2"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "GetCustomAttributes1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "PrepareApplicationView5"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Join1"
    into: "in3"
  - from: "GetCustomAttributes1"
    via: "next"
    to: "Pipelet28"
    into: "in"
  - from: "Pipelet28"
    via: "next"
    to: "PrepareApplicationView5"
    into: "in"
  - from: "Decision4"
    via: "yes"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "Decision4"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "GetRepositoryByID1"
    into: "in"
