flow: "ViewChannelProductLockingPreferences"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "InitForm"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewChannelProductLockingPreferences-InitForm"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "ProductLockingPreferencesForm"
      FormResource: "ProductLockingPreferences"
  - id: "CreateForm2"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "ProductLockingPreferencesForm"
      FormResource: "ProductLockingPreferences"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Form:ProductLockActivated:Value"
  - id: "DecisionNode3"
    type: "decision"
    condition: "ProductLockActivated"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelProductLockingPreferences-Update"
      OutValue_1: "ViewChannelProductLockingPreferences-Start"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "update"
      Key_1: "reset"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "GetDomainPreference3"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductLockTimeout"
      Type: "Integer"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceIntValue: "ProductLockTimeout"
  - id: "GetDomainPreference4"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductLockActivated"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceStringValue: "ProductLockActivated"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode15"
    type: "join"
  - id: "JoinNode16"
    type: "join"
  - id: "JoinNode17"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "CalculateInteger"
    config:
      Operand2: 60
      Operation: "*"
    bindings:
      Operand1: "Form:ProductLockTimeout:Value"
      Result: "ProductLockTimeout"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "CalculateInteger"
    config:
      Operand2: 60
      Operation: "/"
    bindings:
      Operand1: "ProductLockTimeout"
      Result: "ProductLockTimeout"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductLockActivated"
      DefaultPreferenceValue: false
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductLockActivated"
      DefaultPreferenceValue: false
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceStringValue: "\"true\""
  - id: "Pipelet9"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductLockTimeout"
      DefaultPreferenceValue: 0
      Type: "Integer"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceIntValue: "ProductLockTimeout"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "product/ChannelProductLockingPreference"
  - id: "SetDictionaryValue7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewProductLockingPreferences-Start"
  - id: "SetFormParameterValue1"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      FormParameter: "Form:ProductLockTimeout"
      Value: "ProductLockTimeout"
  - id: "SetFormParameterValue2"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      FormParameter: "Form:ProductLockActivated"
      Value: "IntProductLockActivated"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
  - id: "VerifyInteger2"
    type: "pipelet"
    ref: "VerifyInteger"
    config:
      MaxValue: 1
      MinValue: 0
    bindings:
      LocalizedString: "\"1\""
      IntegerObject: "IntProductLockActivated"
  - id: "VerifyInteger3"
    type: "pipelet"
    ref: "VerifyInteger"
    config:
      MaxValue: 1
      MinValue: 0
    bindings:
      LocalizedString: "\"0\""
      IntegerObject: "IntProductLockActivated"

links:
  - from: "ValidateForm1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "ValidateForm1"
    via: "error"
    to: "JoinNode13"
    into: "in2"
  - from: "Pipelet10"
    via: "next"
    to: "Pipelet9"
    into: "in"
  - from: "Pipelet7"
    via: "error"
    to: "JoinNode16"
    into: "in2"
  - from: "Pipelet8"
    via: "error"
    to: "JoinNode17"
    into: "in2"
  - from: "CreateForm2"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet10"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode13"
    into: "in1"
  - from: "JoinNode15"
    via: "next"
    to: "JoinNode17"
    into: "in1"
  - from: "Pipelet9"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "JoinNode16"
    via: "next"
    to: "JoinNode15"
    into: "in2"
  - from: "StartNode2"
    via: "next"
    to: "CreateForm2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Pipelet9"
    via: "error"
    to: "JoinNode16"
    into: "in1"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "SetFormParameterValue2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "SetFormParameterValue2"
    via: "next"
    to: "SetFormParameterValue1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "GetDomainPreference4"
    into: "in"
  - from: "VerifyInteger2"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "VerifyInteger2"
    via: "error"
    to: "JoinNode12"
    into: "in1"
  - from: "DecisionNode3"
    via: "no"
    to: "VerifyInteger3"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "VerifyInteger3"
    via: "error"
    to: "JoinNode11"
    into: "in2"
  - from: "VerifyInteger3"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode14"
    via: "next"
    to: "JoinNode15"
    into: "in1"
  - from: "GetDomainPreference3"
    via: "error"
    to: "JoinNode10"
    into: "in2"
  - from: "JoinNode7"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "SetDictionaryValue7"
    via: "next"
    to: "JoinNode7"
    into: "in3"
  - from: "GetDomainPreference4"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "DecisionNode3"
    via: "yes"
    to: "VerifyInteger2"
    into: "in"
  - from: "GetDomainPreference4"
    via: "next"
    to: "GetDomainPreference3"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "JoinNode12"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "SetFormParameterValue1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode11"
    via: "next"
    to: "JoinNode12"
    into: "in3"
  - from: "JoinNode13"
    via: "next"
    to: "JoinNode14"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue7"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode9"
    into: "in2"
  - from: "GetDomainPreference3"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "JoinNode17"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "Pipelet7"
    into: "in"
  - from: "Pipelet7"
    via: "next"
    to: "JoinNode14"
    into: "in2"
