flow: "ViewParametricSearchByOracle"
kind: "view"

entries:
  - id: "Start3"
    name: "PrepareSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "OfferPaging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "SimpleOfferSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "FilterConditionsByUser"
    mode: "private"
    strict: false
    inputs:
      - key: "Filters"
        type: "java.util.Iterator"
        required: false

steps:
  - id: "AddMultipleEntriesToMap1"
    type: "pipelet"
    ref: "AddMultipleEntriesToMap"
    config:
      Mode: "OverwriteValue"
    bindings:
      Key1: "\"SearchCategoryUUID\""
      Value1: "SearchCategoryUUID"
      OutMap: "GenericHandlerPipelineParams"
      Key2: "\"SortingAttribute\""
      Value2: "SortingAttribute"
      Key3: "\"SearchTerm\""
      Value3: "SearchTerm"
  - id: "Call5"
    type: "call"
    ref: "ViewParametricSearchByOracle-PrepareSearch"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessCategoryOrProductPage-DeterminePageEntryPointForSearchResults"
    bindings:
      Domain: "CurrentOrganization:OwningDomain"
  - id: "CallNode10"
    type: "call"
    ref: "ProcessCategory-Get"
    bindings:
      CatalogCategoryID: "SearchCategoryUUID"
  - id: "CallNode16"
    type: "call"
    ref: "ProcessSearchEngineAttributes-CreateRobotsNoindexNofollowMetaTag"
  - id: "CallNode17"
    type: "call"
    ref: "GetCatalogFilters-GetFiltersByUser"
    bindings:
      CatalogFilterDomain: "CurrentOrganization:OwningDomain"
      UseFallbackToEveryoneDomain: "\"true\""
      EveryoneDomain: "CurrentOrganization:OrganizationDomain"
  - id: "CallNode18"
    type: "call"
    ref: "ViewParametricSearchByOracle-FilterConditionsByUser"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessB2CProduct-GetProductBOs"
  - id: "CallNode3"
    type: "call"
    ref: "Paging-GetPageSize"
    bindings:
      Key: "\"PageSize.Search.ProductSearch\""
  - id: "CallNode4"
    type: "call"
    ref: "Paging-Update"
    bindings:
      Pageable: "Products"
      Key: "\"PageSize.Search.ProductSearch\""
  - id: "CreateOracleSearchResultNavigationList1"
    type: "pipelet"
    ref: "CreateOracleSearchResultNavigationList"
    bindings:
      HandlerPipeline: "\"ViewParametricSearch\""
  - id: "Decision2"
    type: "decision"
    condition: "SearchCategoryUUID"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      DefaultPageSize: 12
      QueryName: "product/SimpleProductSearch"
    bindings:
      SearchResult: "Products"
      Parameters: "ProductSearchParameters"
      ErrorCode: "ErrorStatus"
      PageSize: "PageSizeInteger"
  - id: "GetPageable3"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Products"
      PageableID: "PageableID"
  - id: "Join38"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewPage-Start"
  - id: "SetDictionaryValue10"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "DetermineFilterConditionsPipeline"
      Value: "ViewParametricSearch-FilterConditionsByUser"
  - id: "SetDictionaryValue7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "DetermineRepositoriesPipeline"
      Value: "DetermineRepositories-Channel"
  - id: "SetDictionaryValue9"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "OnlineFlag"
      Value: 1
  - id: "UpdateDictionary1"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "ProductDomain"
      Name_02: "LocaleInformation"
      Name_03: "NameOrID"
      Name_04: "CatalogCategory"
      Name_05: "Filters"
      Name_06: "SortOrder"
      Name_07: "SortAttribute"
      Name_08: "Currency"
      Name_09: "SortAttributeType"
    bindings:
      OutDictionary: "ProductSearchParameters"
      Value_02: "CurrentSession:Locale"
      Value_01: "CurrentOrganization:OwningDomain"
      Value_03: "SearchExpression"
      Value_04: "Category"
      Value_05: "Filters"
      Value_06: "SortOrder"
      Value_07: "SortAttribute"
      Value_08: "CurrentSession:CurrencyCode"
      Value_09: "SortAttributeType"
  - id: "VerifySearchTerm1"
    type: "pipelet"
    ref: "VerifySearchTerm"
    config:
      AllowWildcards: "Multi & Single"
      AllowFuzzySearch: false
    bindings:
      UserSearchTerm: "SearchTerm"
      ErrorCode: "ErrorStatus"

links:
  - from: "VerifySearchTerm1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode16"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "GetPageable3"
    into: "in"
  - from: "SetDictionaryValue9"
    via: "next"
    to: "SetDictionaryValue10"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "GetPageable3"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode7"
    via: "next"
    to: "CallNode18"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "CallNode10"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "VerifySearchTerm1"
    into: "in"
  - from: "VerifySearchTerm1"
    via: "next"
    to: "UpdateDictionary1"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "Join38"
    via: "next"
    to: "CallNode16"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "SetDictionaryValue7"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "JoinNode7"
    into: "in2"
  - from: "UpdateDictionary1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "CallNode3"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "Join38"
    into: "in1"
  - from: "Start7"
    via: "next"
    to: "CallNode17"
    into: "in"
  - from: "AddMultipleEntriesToMap1"
    via: "next"
    to: "CreateOracleSearchResultNavigationList1"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "SetDictionaryValue7"
    via: "next"
    to: "SetDictionaryValue9"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Join38"
    into: "in3"
  - from: "CallNode17"
    via: "next"
    to: "End1"
    into: "in"
  - from: "CallNode18"
    via: "next"
    to: "End2"
    into: "in"
  - from: "CreateOracleSearchResultNavigationList1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "SetDictionaryValue10"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "AddMultipleEntriesToMap1"
    into: "in"
  - from: "GetPageable3"
    via: "next"
    to: "CallNode4"
    into: "in"
