flow: "ViewConfigurationParameterSelectPage"
kind: "process"

entries:
  - id: "StartNode0"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "SelectPage"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "SetPage"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "GetPageTree"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode0"
    type: "call"
    ref: "This:GetPageTree"
  - id: "CallNode1"
    type: "call"
    ref: "ViewConfigurationParameters-GetConfigurationParameterCtnr"
  - id: "CallNode2"
    type: "call"
    ref: "ViewConfigurationParameters-GetValuesFromSession"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessConfigurationParameterCtnrWebForm-AddFormParameterValue"
    bindings:
      ConfigurationParameterName: "SelectedConfigurationParameterName"
      ParameterValues: "SelectedPageID"
      Site: "CurrentDomain"
  - id: "CallNode5"
    type: "call"
    ref: "This:SelectPage"
  - id: "DecisionNode0"
    type: "decision"
    condition: "SelectedPageID"
  - id: "DispatchFormAction0"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "This:SelectPage"
      OutValue_1: "This:SetPage"
      OutValue_2: "ViewConfigurationParameters-Edit"
    bindings:
      Key_0: "StartPageSelection"
      Key_1: "SetPage"
      Key_2: "CancelSelection"
      SelectionKey: "JumpTarget"
  - id: "EndNode0"
    type: "end"
    strict: false
  - id: "ExecuteObjectsQuery0"
    type: "pipelet"
    ref: "ExecuteObjectsQuery"
    config:
      QueryName: "content/GetPageletEntryPointTree"
      ParameterName_01: "ContentRepository"
      ParameterName_02: "ParentPageletEntryPoint"
      ParameterName_03: "Locale"
    bindings:
      ParameterValue_01: "ContentRepository"
      ParameterValue_02: "Parent"
      ParameterValue_03: "Locale"
      SearchResult: "PageTree"
  - id: "GetLocale0"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Request Locale"
  - id: "GetRepositoryByUUID0"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      UUID: "ContentRepositoryUUID"
      Repository: "ContentRepository"
  - id: "InteractionNode0"
    type: "interaction"
  - id: "JumpNode0"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewConfigurationParameters-Edit"
  - id: "PrepareApplicationView0"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ContentOverview"
      WorkingTemplate: "content/ConfigurationParameterSelectPage.isml"

links:
  - from: "CallNode0"
    via: "next"
    to: "PrepareApplicationView0"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "DecisionNode0"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "DecisionNode0"
    via: "no"
    to: "CallNode5"
    into: "in"
  - from: "DecisionNode0"
    via: "yes"
    to: "CallNode3"
    into: "in"
  - from: "DispatchFormAction0"
    via: "next"
    to: "JumpNode0"
    into: "in"
  - from: "ExecuteObjectsQuery0"
    via: "next"
    to: "EndNode0"
    into: "in"
  - from: "GetLocale0"
    via: "next"
    to: "GetRepositoryByUUID0"
    into: "in"
  - from: "GetRepositoryByUUID0"
    via: "next"
    to: "ExecuteObjectsQuery0"
    into: "in"
  - from: "PrepareApplicationView0"
    via: "next"
    to: "InteractionNode0"
    into: "in"
  - from: "StartNode0"
    via: "next"
    to: "DispatchFormAction0"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode0"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetLocale0"
    into: "in"
