flow: "ViewAuditItemReport"
kind: "view"

entries:
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "ValidateSearchForm"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode23"
    name: "RestoreSearchForm"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode3"
    name: "Export"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Sort"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "Reload"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "Generate"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "Search"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CalculateDate0"
    type: "pipelet"
    ref: "CalculateDate"
    config:
      CalculationMethod: "Add"
      DefaultDays: 1
    bindings:
      Date: "CurrentDate"
      Days: "null"
      Hours: "null"
      Milliseconds: "null"
      Minutes: "null"
      NonWorkingDayList: "null"
      Seconds: "null"
      CalculatedDate: "NextDay"
  - id: "CallNode0"
    type: "call"
    ref: "ProcessPaging-SetPageSize"
    bindings:
      PageSize: "PageSize"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessAuditReport-GetUsers"
  - id: "CallNode10"
    type: "call"
    ref: "ViewAuditItemReport-ValidateSearchForm"
  - id: "CallNode11"
    type: "call"
    ref: "ViewAuditItemReport-Search"
    bindings:
      PageSize: "[Enter Alias]"
      AuditItemBos: "AuditItemBOs"
  - id: "CallNode12"
    type: "call"
    ref: "ProcessAuditReport-Search"
    bindings:
      PageSize: "[Enter Alias]"
      AuditItemBos: "[Enter Alias]"
  - id: "CallNode13"
    type: "call"
    ref: "ViewAuditItemReport-Search"
    bindings:
      AuditItemBos: "[Enter Alias]"
  - id: "CallNode14"
    type: "call"
    ref: "ProcessAuditReportGetDomains-GetDomains"
    bindings:
      Channels: "AuditReportForm:Channel:Value"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessAuditReport-GetChannels"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessAuditReport-GetActionTypes"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessAuditReport-GetObjectTypes"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessPaging-PreparePage"
  - id: "CallNode7"
    type: "call"
    ref: "ViewAuditItemReport-RestoreSearchForm"
  - id: "CallNode8"
    type: "call"
    ref: "ViewAuditItemReport-RestoreSearchForm"
  - id: "CallNode9"
    type: "call"
    ref: "ViewAuditItemReport-ValidateSearchForm"
  - id: "CreateAuditItemQueryParameter2"
    type: "pipelet"
    ref: "CreateAuditItemQueryParameter"
    bindings:
      Channels: "Domains"
      ObjectTypes: "AuditReportForm:ObjectType:Value"
      UserIds: "AuditReportForm:UserID:Value"
      ActionTypes: "AuditReportForm:ActionType:Value"
      CreationDateRangeEnd: "AuditReportForm:EndDate:Value"
      CreationDateRangeStart: "AuditReportForm:StartDate:Value"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "AuditReportForm"
      FormResource: "AuditReportForm"
    bindings:
      Form: "AuditReportForm"
  - id: "CreateForm2"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "AuditReportForm"
      FormResource: "AuditReportForm"
    bindings:
      Form: "AuditReportForm"
  - id: "CreateForm5"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "AuditReportForm"
      FormResource: "AuditReportForm"
    bindings:
      Form: "AuditReportForm"
  - id: "DecisionNode1"
    type: "decision"
    condition: "CurrentChannel"
  - id: "DecisionNode10"
    type: "decision"
    condition: "AuditReportForm"
  - id: "DecisionNode2"
    type: "decision"
    condition: "PageableID"
  - id: "DispatchFormAction0"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewAuditItemReport-Generate"
      OutValue_1: "ViewAuditItemReport-Sort"
      OutValue_2: "ViewAuditItemReport-Start"
      DefaultPageNumberPrefix: "PageNumber_"
      DefaultPageSizePrefix: "PageSize_"
      PagingPipeline: "ViewAuditItemReport-Paging"
    bindings:
      Key_0: "generate"
      Key_1: "sort"
      Key_2: "start"
      SelectionKey: "JumpTarget"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "AuditReportForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        guaranteed: true
      - key: "PageLocator"
        type: "com.intershop.component.foundation.capi.paging.PageLocator"
        guaranteed: false
  - id: "EndNode5"
    type: "end"
    strict: false
  - id: "GetCurrentDate0"
    type: "pipelet"
    ref: "GetCurrentDate"
    config:
      OffsetTime: "0:0"
  - id: "GetLocale4"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Lead Locale"
    bindings:
      Locale: "SelectedLocale"
  - id: "GetPageLocator5"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "AuditItemSearch"
      RestorePageLocatorDictionary: "True"
      UsePageLocatorHistory: false
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "AuditItemBOs"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "InteractionNode3"
    type: "interaction"
  - id: "JoinNode0"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode24"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump7"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "Error-FileNotFound"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"ViewAuditItemReport-Generate\""
      InValue_2: "\"AuditItemSearch\""
      OutValue_1: "RecreatePageablePipeline"
      OutValue_2: "PageLocatorName"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"ViewAuditItemReport-Generate\""
      InValue_2: "\"AuditItemSearch\""
      OutValue_1: "RecreatePageablePipeline"
      OutValue_2: "PageLocatorName"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Pageable"
      OutValue_1: "AuditItemBOs"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "MassDataTasks"
      WorkingTemplate: "auditing/AuditReportForm"
  - id: "SetFormParameterValue0"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      FormParameter: "AuditReportForm:StartDate"
      Value: "CurrentDate"
  - id: "SetFormParameterValue1"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      FormParameter: "AuditReportForm:EndDate"
      Value: "NextDay"
  - id: "SetPageLocator2"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewAuditItemReport-Start"
      DefaultPageLocatorName: "AuditItemSearch"
    bindings:
      HandlerPipeline: "null"
      Pageable: "AuditItemBOs"
  - id: "SetPageLocatorParameter1"
    type: "pipelet"
    ref: "SetPageLocatorParameter"
    bindings:
      ParameterName: "\"AuditReportForm\""
      ParameterValue: "AuditReportForm"
  - id: "TextNode1"
    type: "text"
  - id: "UpdatePageSize0"
    type: "pipelet"
    ref: "UpdatePageSize"
    config:
      DefaultPageSize: 10
    bindings:
      PageableIterator: "AuditItemBOs"
      PageSize: "PageLocator:PageSize"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "AuditReportForm"

links:
  - from: "StartNode3"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "GetPageable1"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "CalculateDate0"
    via: "next"
    to: "SetFormParameterValue1"
    into: "in"
  - from: "CallNode0"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "CallNode10"
    via: "ERROR"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode10"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode11"
    via: "next"
    to: "UpdatePageSize0"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "InteractionNode3"
    into: "in"
  - from: "CallNode14"
    via: "next"
    to: "CreateAuditItemQueryParameter2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "CallNode0"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode8"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "CallNode9"
    via: "ERROR"
    to: "EndNode5"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "CreateAuditItemQueryParameter2"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "CreateForm2"
    via: "next"
    to: "GetCurrentDate0"
    into: "in"
  - from: "CreateForm5"
    via: "next"
    to: "JoinNode24"
    into: "in1"
  - from: "DecisionNode10"
    via: "no"
    to: "JoinNode24"
    into: "in1"
  - from: "DecisionNode10"
    via: "yes"
    to: "JoinNode7"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode2"
    into: "in"
  - from: "DispatchFormAction0"
    via: "error"
    to: "JoinNode8"
    into: "in1"
  - from: "DispatchFormAction0"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "GetCurrentDate0"
    via: "next"
    to: "SetFormParameterValue0"
    into: "in"
  - from: "GetLocale4"
    via: "next"
    to: "CreateForm2"
    into: "in"
  - from: "GetPageLocator5"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "GetPageLocator5"
    via: "next"
    to: "DecisionNode10"
    into: "in"
  - from: "JoinNode0"
    via: "next"
    to: "SetPageLocator2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "JoinNode24"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "CreateForm5"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "Jump7"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "Pipelet1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "SetFormParameterValue0"
    via: "next"
    to: "CalculateDate0"
    into: "in"
  - from: "SetFormParameterValue1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "SetPageLocator2"
    via: "next"
    to: "SetPageLocatorParameter1"
    into: "in"
  - from: "SetPageLocatorParameter1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction0"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetLocale4"
    into: "in"
  - from: "StartNode23"
    via: "next"
    to: "GetPageLocator5"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "UpdatePageSize0"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "ValidateForm1"
    via: "error"
    to: "EndNode3"
    into: "in"
  - from: "ValidateForm1"
    via: "next"
    to: "EndNode1"
    into: "in"
