flow: "ViewNotificationPreferences_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "View"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "UpdateIntervall"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "UpdateSettings"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "PerformUpdate"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "RunAgent"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CalculateDate2"
    type: "pipelet"
    ref: "CalculateDate"
    bindings:
      Date: "CurrentDate"
      Milliseconds: "SyncRecord:Interval"
      CalculatedDate: "NextStartDate"
  - id: "Call1"
    type: "call"
    ref: "ViewNotificationPreferences_52-PerformUpdate"
  - id: "Call2"
    type: "call"
    ref: "ViewNotificationPreferences_52-PerformUpdate"
  - id: "Call3"
    type: "call"
    ref: "ViewNotificationPreferences_52-UpdateIntervall"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessProductNotification-SendNotifications"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "EmailSubject"
      param.1.required: true
      param.2.name: "EmailFrom"
      param.2.required: true
      webform-id: "NotificationSettings"
      param.1.rule: ""
      param.2.rule: ""
      param.3.name: "EmailSubject"
      param.3.required: true
      param.4.name: "EmailTemplate"
      param.4.required: true
      param.5.name: "EmailDeleteTemplate"
      param.5.required: true
      param.6.name: "NotificationJobIntervall"
      param.6.required: true
      param.6.rule: "\\d+"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewNotificationPreferences_52-UpdateIntervall"
      OutValue_1: "ViewNotificationPreferences_52-UpdateSettings"
      OutValue_2: "ViewNotificationPreferences_52-RunAgent"
    bindings:
      Key_0: "updateIntervall"
      Key_1: "updateSettings"
      Key_2: "runNotificationAgent"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "GetCurrentDate0"
    type: "pipelet"
    ref: "GetCurrentDate"
    bindings:
      CurrentDate: "JobStartTime"
  - id: "GetCurrentDate1"
    type: "pipelet"
    ref: "GetCurrentDate"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductNotificationEmailFrom"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceStringValue: "ProductNotificationEmailFrom"
  - id: "GetDomainPreference2"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductNotificationEmailSubject"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceStringValue: "ProductNotificationEmailSubject"
  - id: "GetDomainPreference3"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductNotificationEmailTemplate"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceStringValue: "ProductNotificationEmailTemplate"
  - id: "GetDomainPreference7"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductNotificationEmailDeleteTemplate"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceStringValue: "ProductNotificationEmailDeleteTemplate"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "NotificationSettings"
    bindings:
      WebForm: "NotificationSettings"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "JoinNode0"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump3"
    type: "jump"
    ref: "ViewNotificationPreferences_52-View"
  - id: "Jump4"
    type: "jump"
    ref: "ViewNotificationPreferences_52-View"
  - id: "Jump5"
    type: "jump"
    ref: "ViewNotificationPreferences_52-View"
  - id: "Jump6"
    type: "jump"
    ref: "ViewNotificationPreferences_52-View"
  - id: "JumpNode2"
    type: "jump"
    ref: "Error-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "Error-Start"
  - id: "JumpNode4"
    type: "jump"
    ref: "Error-Start"
  - id: "ObtainSyncRecordContainer1"
    type: "pipelet"
    ref: "ObtainSyncRecordContainer"
    bindings:
      ExtensibleObject: "ChannelRepository:Domain"
      SynchRecordContainer: "Container"
  - id: "ObtainSyncRecordContainer2"
    type: "pipelet"
    ref: "ObtainSyncRecordContainer"
    bindings:
      ExtensibleObject: "ChannelRepository:Domain"
      SynchRecordContainer: "Container"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductNotificationEmailDeleteTemplate"
      DefaultPreferenceValue: false
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceKey: "null"
      PreferenceStringValue: "NotificationSettings_EmailDeleteTemplate"
      PreferenceValue: "null"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductNotificationEmailFrom"
      DefaultPreferenceValue: false
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceKey: "null"
      PreferenceStringValue: "NotificationSettings_EmailFrom"
      PreferenceValue: "null"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductNotificationEmailSubject"
      DefaultPreferenceValue: false
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceKey: "null"
      PreferenceStringValue: "NotificationSettings_EmailSubject"
      PreferenceValue: "null"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductNotificationEmailTemplate"
      DefaultPreferenceValue: false
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceKey: "null"
      PreferenceStringValue: "NotificationSettings_EmailTemplate"
      PreferenceValue: "null"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_EMailAddressInvalid"
      Value: true
      ValueType: "Dictionary Value"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "VerifyEMailAddress"
    bindings:
      EMailAddress: "NotificationSettings_EmailFrom"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "channel/ChannelNotificationPreferences_52"
  - id: "SetDictionaryValue0"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "TriggeredManually"
      Value: true
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewNotificationPreferences_52-View"
  - id: "UpdateSyncRecord1"
    type: "pipelet"
    ref: "UpdateSyncRecord"
    bindings:
      Interval: "FormNotificationJobIntervallMillis"
      StartTime: "NextStartDate"
      TargetObject: "Container"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "NotificationSettings"
    bindings:
      WebForm: "NotificationSettings"
  - id: "ValidateWebForm2"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "NotificationSettings"
  - id: "VerifyInteger0"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      LocalizedString: "NotificationSettings:NotificationJobIntervall:Value"
      IntegerValue: "FormNotificationJobIntervallMillis"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      LocalizedString: "NotificationSettings:NotificationJobIntervall:Value"
      IntegerValue: "FormNotificationJobIntervallMillis"

links:
  - from: "CalculateDate2"
    via: "next"
    to: "UpdateSyncRecord1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "CallNode1"
    via: "ERROR"
    to: "JumpNode4"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "Jump6"
    into: "in"
  - from: "CreateWebForm1"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetCurrentDate0"
    via: "next"
    to: "SetDictionaryValue0"
    into: "in"
  - from: "GetCurrentDate1"
    via: "next"
    to: "CalculateDate2"
    into: "in"
  - from: "GetDomainPreference1"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "GetDomainPreference1"
    via: "next"
    to: "GetDomainPreference2"
    into: "in"
  - from: "GetDomainPreference2"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "GetDomainPreference2"
    via: "next"
    to: "GetDomainPreference3"
    into: "in"
  - from: "GetDomainPreference3"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "GetDomainPreference3"
    via: "next"
    to: "GetDomainPreference7"
    into: "in"
  - from: "GetDomainPreference7"
    via: "error"
    to: "JoinNode8"
    into: "in1"
  - from: "GetDomainPreference7"
    via: "next"
    to: "ObtainSyncRecordContainer2"
    into: "in"
  - from: "GetWebForm2"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "GetWebForm2"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "ObtainSyncRecordContainer1"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode0"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "VerifyInteger0"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "ObtainSyncRecordContainer1"
    via: "next"
    to: "GetCurrentDate1"
    into: "in"
  - from: "ObtainSyncRecordContainer2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "JoinNode11"
    into: "in1"
  - from: "Pipelet1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Pipelet2"
    via: "error"
    to: "JoinNode9"
    into: "in1"
  - from: "Pipelet2"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "Pipelet4"
    via: "error"
    to: "JoinNode9"
    into: "in1"
  - from: "Pipelet4"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "Pipelet5"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "Pipelet5"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet7"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Pipelet8"
    via: "error"
    to: "Pipelet7"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "SetDictionaryValue0"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "VerifyInteger1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetCurrentDate0"
    into: "in"
  - from: "UpdateSyncRecord1"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "UpdateWebForm2"
    via: "next"
    to: "ValidateWebForm2"
    into: "in"
  - from: "ValidateWebForm2"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "ValidateWebForm2"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "VerifyInteger0"
    via: "error"
    to: "JoinNode0"
    into: "in1"
  - from: "VerifyInteger0"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "VerifyInteger1"
    via: "next"
    to: "Join1"
    into: "in1"
