flow: "ViewLandingPage"
kind: "view"

entries:
  - id: "StartNode1"
    name: "ProcessContentURL"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "ShowURL"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "DecisionNode2"
    type: "decision"
    condition: "CurrentChannel"
  - id: "DetermineLocales2"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "JoinNode7"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentDomain"
      OutValue_1: "UnitDomain"
  - id: "KeyMapper17"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentChannel:Domain:Site:Domain"
      OutValue_1: "UnitDomain"
  - id: "ResolveFilename1"
    type: "pipelet"
    ref: "ResolveFilename"
    config:
      UnitDirectory: "LANDING_PAGES_DIR"
    bindings:
      FileName: "File"
      AbsoluteFileName: "FullPath"

links:
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode7"
    into: "in3"
  - from: "JoinNode7"
    via: "next"
    to: "DetermineLocales2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "KeyMapper17"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "GetLocale2"
    via: "next"
    to: "ResolveFilename1"
    into: "in"
  - from: "DetermineLocales2"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper17"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "ResolveFilename1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "InteractionNode2"
    into: "in"
