flow: "ViewChannelPageComponentProcessingWizard"
kind: "view"

entries:
  - id: "Start1"
    name: "SelectAction"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "SelectNextStep"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "CheckLabelAction"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "AddLabel"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "SelectLabel"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessLabel-GetLabelsByDomain"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessLabel-Create"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
      User: "CurrentUser"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessLabel-GetCSVStringFromIterator"
    bindings:
      CSVIterator: "LabelIDs"
      CSVString: "LabelIDsCSVString"
  - id: "CheckForEmptyString1"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "ActionID"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "\"ViewProcessList_\""
      String2: "\"-ListAll\""
      String1: "CurrentChannel:TypeCode"
      Concatenated: "ProcessListAllPipeline"
  - id: "ConcatenateStrings4"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "\"ViewProcessList_\""
      String2: "\"-CreateProcess\""
      String1: "CurrentChannel:TypeCode"
      Concatenated: "CreateProcessPipeline"
  - id: "DecisionNode1"
    type: "decision"
    condition: "LabelID"
  - id: "DecisionNode2"
    type: "decision"
    condition: "LabelName"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelPageComponentProcessingWizard-SelectNextStep"
      OutValue_1: "ViewChannelPageComponentProcessingWizard-SelectAction"
      OutValue_2: "ViewChannelPageComponents-Paging"
      OutValue_3: "ViewChannelPageComponentProcessingWizard-SelectAction"
      OutValue_4: "ViewChannelPageComponentProcessingWizard-CheckLabelAction"
      OutValue_5: "ViewChannelPageComponentProcessingWizard-AddLabel"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "selectNextStep"
      Key_1: "actionList"
      Key_2: "cancel"
      Key_3: "selectAction"
      Key_4: "checkLabelAction"
      Key_5: "addLabel"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    bindings:
      ParameterName: "\"LabelID\""
      Selection: "LabelIDs"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "Jump10"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewChannelPageComponentProcessingWizard-SelectLabel"
  - id: "JumpNode3"
    type: "jump"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewChannelPageComponentProcessingWizard-SelectLabel"
  - id: "JumpNode5"
    type: "jump"
    ref: "ViewChannelPageComponentProcessingWizard-SelectAction"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "\"ProcessLabel-BatchProcessAssign\""
      OutValue_1: "ProcessPipeline"
      InValue_2: "\"PageComponentsAssignLabel\""
      OutValue_2: "JobName"
      InValue_3: "\"PageComponents\""
      OutValue_3: "JobNamePrefix"
  - id: "KeyMapper14"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      OutValue_1: "ProcessPipeline"
      InValue_1: "\"ProcessLabel-BatchProcessAssign\""
      OutValue_4: "JobName"
      InValue_4: "\"PageComponentsAssignLabel\""
      OutValue_5: "JobNamePrefix"
      InValue_5: "\"PageComponents\""
      InValue_6: "\"Assign Labels to Page Components\""
      OutValue_6: "ProcessDescription"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "Label:UUID"
      OutValue_1: "LabelID"
  - id: "KeyMapper6"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "LabelIDsCSVString"
      OutValue_1: "LabelID"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelStorefront"
      WorkingTemplate: "content/ChannelPageComponentProcessingSelectAction"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Products"
      WorkingTemplate: "content/ChannelAssignLabelAction"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_ACTION_NOT_SELECTED"
      Value: true
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: "LabelNameMissing"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: "LabelExists"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: "NoLabelSelected"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "StartNode5"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetFormSelection1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "KeyMapper14"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump10"
    into: "in"
  - from: "CallNode3"
    via: "Error"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetLocale1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "GetLocale1"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "KeyMapper14"
    via: "next"
    to: "KeyMapper6"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "KeyMapper6"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "ConcatenateStrings4"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "CheckForEmptyString1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "ConcatenateStrings4"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "SetDictionaryValue4"
    into: "in"
