flow: "ViewAccountAddressList"
kind: "view"

entries:
  - id: "Start1"
    name: "SetDefaultAddress"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "List"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "DeleteAddress"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "DeleteAddresses"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call2"
    type: "call"
    ref: "ProcessAddress-Remove"
  - id: "Call3"
    type: "call"
    ref: "ViewAccountAddressList-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ViewAccountAddressList-Prefix"
  - id: "Call5"
    type: "call"
    ref: "ViewAccountAddressList-Prefix"
  - id: "Call6"
    type: "call"
    ref: "ProcessAddressBook-GetUserAddresses"
  - id: "Call7"
    type: "call"
    ref: "ProcessAddress-Remove"
  - id: "Call8"
    type: "call"
    ref: "ViewAccountAddressList-Prefix"
  - id: "Call9"
    type: "call"
    ref: "ProcessAddress-SetDefaultAddress"
  - id: "Decision2"
    type: "decision"
    condition: "confirmDelete"
  - id: "DetermineUserProfile1"
    type: "pipelet"
    ref: "DetermineUserProfile"
  - id: "DetermineUserProfile2"
    type: "pipelet"
    ref: "DetermineUserProfile"
  - id: "DetermineUserProfile3"
    type: "pipelet"
    ref: "DetermineUserProfile"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewAccountAddressList-List"
      OutValue_1: "ViewAccountAddressList-List"
      OutValue_2: "ViewAccountAddress-New"
      OutValue_3: "ViewAccountAddressList-DeleteAddresses"
    bindings:
      Key_0: "cancel"
      Key_1: "confirmDelete"
      Key_2: "new"
      Key_3: "delete"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "DeleteAddress"
    bindings:
      Selection: "PrefixIterator"
  - id: "GetFormSelection2"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "DeleteAddress"
    bindings:
      Selection: "Address_UUID_Iterator"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewAccountAddressList-List"
  - id: "Jump2"
    type: "jump"
    ref: "ViewAccountAddressList-List"
  - id: "Jump3"
    type: "jump"
    ref: "ViewAccountAddressList-List"
  - id: "Jump4"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump5"
    type: "jump"
    ref: "ViewAccount-Show"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentUser"
      OutValue_1: "User"
  - id: "Loop1"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Profile"
      WorkingTemplate: "user/AccountAddressList"

links:
  - from: "Start2"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "DetermineUserProfile3"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "DetermineUserProfile2"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "DetermineUserProfile3"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "DetermineUserProfile2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Loop1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "DetermineUserProfile1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "End1"
    into: "in"
  - from: "DetermineUserProfile1"
    via: "next"
    to: "GetFormSelection2"
    into: "in"
  - from: "GetFormSelection2"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "GetFormSelection1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join1"
    into: "in3"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "Jump5"
    into: "in"
