flow: "ViewProductLinkMapping_32"
kind: "view"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewProductLinkMapping_32-Prefix"
  - id: "Call10"
    type: "call"
    ref: "ViewProductLinkMapping_32-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ProcessProductDataMappingRule-DeleteRuleConstruct"
  - id: "Call5"
    type: "call"
    ref: "ProcessProductDataMappingRule-CreateRuleConstruct"
  - id: "CheckForEmptyString1"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "ChannelID"
  - id: "Decision1"
    type: "decision"
    condition: "mappingEnabled"
  - id: "Decision2"
    type: "decision"
    condition: "ProductDataMappingRuleID"
  - id: "Decision3"
    type: "decision"
    condition: "ProductDataMappingRuleID"
  - id: "End1"
    type: "end"
    strict: false
  - id: "GetProductDataMappingRuleSet1"
    type: "pipelet"
    ref: "GetProductDataMappingRuleSet"
    bindings:
      DeclaringDomain: "CurrentChannel:RepositoryDomain"
      ProvidingDomain: "ProvidingRepository:Domain"
  - id: "GetProductDataMappingRules1"
    type: "pipelet"
    ref: "GetProductDataMappingRules"
    config:
      DefaultTypeCode: 9
    bindings:
      DeclaringDomain: "ProductDataMappingRuleSet:DeclaringDomain"
      ProvidingDomain: "ProductDataMappingRuleSet:ProvidingDomain"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "ProvidingRepository"
      UUID: "ProviderID"
  - id: "GetRepositoryByUUID2"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "CurrentSelectedChannel"
      UUID: "ChannelID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewProductLinkMapping_32-Start"
  - id: "Jump2"
    type: "jump"
    ref: "ViewProductLinkMapping_32-Start"
  - id: "Jump3"
    type: "jump"
    ref: "ViewProductLinkMapping_32-Start"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/ProductLinkMapping_32"

links:
  - from: "Start2"
    via: "next"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Jump2"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "GetProductDataMappingRules1"
    into: "in"
  - from: "GetProductDataMappingRules1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Decision1"
    via: "yes"
    to: "Decision3"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "Jump3"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Call5"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "next"
    to: "GetRepositoryByUUID2"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "GetRepositoryByUUID2"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "GetRepositoryByUUID2"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "Join2"
    via: "next"
    to: "Join3"
    into: "in3"
  - from: "CheckForEmptyString1"
    via: "error"
    to: "Join2"
    into: "in1"
  - from: "GetProductDataMappingRuleSet1"
    via: "next"
    to: "CheckForEmptyString1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "End1"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "GetProductDataMappingRuleSet1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Decision2"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "Decision2"
    via: "yes"
    to: "Call4"
    into: "in"
