flow: "ViewPageletSearchPageFilter"
kind: "view"

entries:
  - id: "Start2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "View"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Submit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Cancel"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Reset"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "StoreProductAndCategoryFilterKeys"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentContainerName"
        type: "java.lang.Object"
        required: true
      - key: "StoreContainerName"
        type: "java.lang.String"
        required: true
  - id: "StartNode6"
    name: "RemoveProductAndCategoryFilterKeys"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentContainerName"
        type: "java.lang.String"
        required: true
      - key: "StoreContainerName"
        type: "java.lang.String"
        required: true
  - id: "StartNode7"
    name: "GetProductAndCaterotyFilterKeys"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentContainerName"
        type: "java.lang.String"
        required: true
      - key: "StoreContainerName"
        type: "java.lang.String"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessPageletSearch-MoveToPageFilter"
    bindings:
      Direction: "\"forward\""
  - id: "CallNode10"
    type: "call"
    ref: "ViewPageletSearchPageFilter-StoreProductAndCategoryFilterKeys"
  - id: "CallNode11"
    type: "call"
    ref: "ViewPageletSearchPageFilter-GetProductAndCaterotyFilterKeys"
  - id: "CallNode12"
    type: "call"
    ref: "ViewPageletSearchPageFilter-GetProductAndCaterotyFilterKeys"
  - id: "CallNode13"
    type: "call"
    ref: "ViewPageletSearchPageFilter-RemoveProductAndCategoryFilterKeys"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessPageletSearch-MoveToPageFilter"
    bindings:
      Direction: "\"backward\""
  - id: "CallNode3"
    type: "call"
    ref: "ProcessPageletSearch-MoveToPageFilter"
    bindings:
      Direction: "\"backward\""
  - id: "CallNode4"
    type: "call"
    ref: "ProcessPageletSearch-GetCurrentContainerName"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessPageletSearch-GetCurrentContainerName"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessPageletSearch-GetCurrentContainerName"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessPageletSearch-MoveToPageFilter"
    bindings:
      Direction: "\"forward\""
  - id: "CallNode8"
    type: "call"
    ref: "ProcessPageletSearch-MoveToPageFilter"
    bindings:
      Direction: "\"backward\""
  - id: "CallNode9"
    type: "call"
    ref: "ProcessPageletSearch-GetCurrentContainerName"
  - id: "ConcatenateStrings11"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "CurrentContainerName"
      String1: "\"_ProductFilterParams\""
      Concatenated: "ProductFilterParamsTempKey"
  - id: "ConcatenateStrings12"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "StoreContainerName"
      String1: "\"_ProductFilterParams\""
      Concatenated: "ProductFilterParamsStoreKey"
  - id: "ConcatenateStrings13"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "CurrentContainerName"
      String1: "\"_SelectedFilterCategoryUUID\""
      Concatenated: "CategoryUUIDFilterTempKey"
  - id: "ConcatenateStrings3"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "CurrentContainerName"
      String1: "\"_ProductFilterParams\""
      Concatenated: "ProductFilterParamsKey"
  - id: "ConcatenateStrings4"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "CurrentContainerName"
      String1: "\"_SelectedFilterCategoryUUID\""
      Concatenated: "CategoryUUIDFilterKey"
  - id: "ConcatenateStrings6"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "StoreContainerName"
      String1: "\"_SelectedFilterCategoryUUID\""
      Concatenated: "CategoryUUIDFilterStoreKey"
  - id: "DecisionNode1"
    type: "decision"
    condition: "EnteringFilter"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_1: "ViewPageletSearch-Search"
      OutValue_2: "ViewPageletSearch-Paging"
      PagingPipeline: "ViewPageletSearch-Paging"
      OutValue_0: "ViewPageletSearch-Search"
      OutValue_3: "ViewPageletSearch-Paging"
      OutValue_4: "ViewPageletSearch-Paging"
      OutValue_5: "ViewPageletSearchPageFilter-Submit"
      OutValue_6: "ViewPageletSearchPageFilter-Cancel"
    bindings:
      SelectionKey: "JumpTarget"
      Key_2: "paging"
      Key_1: "find"
      Key_0: "findAdvanced"
      Key_3: "confirmDelete"
      Key_4: "cancel"
      Key_5: "submitFilter"
      Key_6: "cancelFilter"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "ProductFilterParamsTempKey"
        type: "java.lang.String"
        guaranteed: true
      - key: "CategoryUUIDFilterStoreKey"
        type: "java.lang.String"
        guaranteed: false
      - key: "CategoryUUIDFilterTempKey"
        type: "java.lang.String"
        guaranteed: false
      - key: "ProductFilterParamsStoreKey"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "ExchangeSessionObject1"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SaveObject: "null"
      SessionObjectName: "CategoryUUIDFilterKey"
  - id: "ExchangeSessionObject10"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SaveObject: "null"
      SessionObjectName: "CategoryUUIDFilterStoreKey"
  - id: "ExchangeSessionObject15"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
    bindings:
      SessionObjectName: "ProductFilterParamsTempKey"
      LoadObject: "ProductFilterParams"
  - id: "ExchangeSessionObject16"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
    bindings:
      SessionObjectName: "CategoryUUIDFilterTempKey"
      LoadObject: "SelectedCategoryUUID"
  - id: "ExchangeSessionObject2"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SaveObject: "null"
      SessionObjectName: "ProductFilterParamsKey"
  - id: "ExchangeSessionObject3"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SaveObject: "null"
      SessionObjectName: "CategoryUUIDFilterTempKey"
  - id: "ExchangeSessionObject4"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SaveObject: "null"
      SessionObjectName: "ProductFilterParamsTempKey"
  - id: "ExchangeSessionObject5"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SaveObject: "null"
      SessionObjectName: "CategoryUUIDFilterTempKey"
  - id: "ExchangeSessionObject6"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SaveObject: "null"
      SessionObjectName: "ProductFilterParamsTempKey"
  - id: "ExchangeSessionObject7"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SessionObjectName: "ProductFilterParamsStoreKey"
      SaveObject: "ProductFilterParams"
  - id: "ExchangeSessionObject8"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SessionObjectName: "CategoryUUIDFilterStoreKey"
      SaveObject: "SelectedCategoryUUID"
  - id: "ExchangeSessionObject9"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SaveObject: "null"
      SessionObjectName: "ProductFilterParamsStoreKey"
  - id: "GetValuesFromContainer1"
    type: "pipelet"
    ref: "GetValuesFromContainer"
    config:
      OverwriteBehavior: true
    bindings:
      ContainerName: "StoreContainerName"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "JoinNode2"
    type: "join"
  - id: "Jump4"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewPageletSearch-Paging"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewPageletSearch-Paging"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewPageletSearch-Paging"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "content/search/PageFilter"
      SelectedMenuItem: "MasterComponents"
  - id: "RemoveValuesContainer1"
    type: "pipelet"
    ref: "RemoveValuesContainer"
    bindings:
      ContainerName: "CurrentContainerName"
  - id: "RemoveValuesContainer2"
    type: "pipelet"
    ref: "RemoveValuesContainer"
    bindings:
      ContainerName: "StoreContainerName"
  - id: "RemoveValuesContainer8"
    type: "pipelet"
    ref: "RemoveValuesContainer"
    bindings:
      ContainerName: "CurrentContainerName"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "PageletSearch_PageFlag"
      Value: true
      ValueType: "Form Value"
  - id: "SetValuesToContainer1"
    type: "pipelet"
    ref: "SetValuesToContainer"
    bindings:
      ContainerName: "StoreContainerName"
      DictionaryKeys: "\"PageletSearch_PageFlag\""
  - id: "SetValuesToContainer2"
    type: "pipelet"
    ref: "SetValuesToContainer"
    bindings:
      ContainerName: "CurrentContainerName"

links:
  - from: "StartNode4"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "RemoveValuesContainer1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "SetValuesToContainer1"
    via: "next"
    to: "RemoveValuesContainer8"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "ExchangeSessionObject1"
    via: "next"
    to: "ExchangeSessionObject2"
    into: "in"
  - from: "ExchangeSessionObject16"
    via: "next"
    to: "ExchangeSessionObject7"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "RemoveValuesContainer2"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "ExchangeSessionObject9"
    via: "next"
    to: "ExchangeSessionObject10"
    into: "in"
  - from: "ExchangeSessionObject7"
    via: "next"
    to: "ExchangeSessionObject8"
    into: "in"
  - from: "ExchangeSessionObject3"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "RemoveValuesContainer1"
    via: "next"
    to: "ConcatenateStrings3"
    into: "in"
  - from: "ConcatenateStrings3"
    via: "next"
    to: "ConcatenateStrings4"
    into: "in"
  - from: "ConcatenateStrings4"
    via: "next"
    to: "ExchangeSessionObject1"
    into: "in"
  - from: "ExchangeSessionObject4"
    via: "next"
    to: "ExchangeSessionObject3"
    into: "in"
  - from: "ExchangeSessionObject2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "ExchangeSessionObject6"
    via: "next"
    to: "ExchangeSessionObject5"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "ExchangeSessionObject15"
    into: "in"
  - from: "ExchangeSessionObject15"
    via: "next"
    to: "ExchangeSessionObject16"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "ExchangeSessionObject6"
    into: "in"
  - from: "ExchangeSessionObject5"
    via: "next"
    to: "ExchangeSessionObject9"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "ExchangeSessionObject10"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "GetValuesFromContainer1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "JoinNode2"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode9"
    into: "in"
  - from: "GetValuesFromContainer1"
    via: "next"
    to: "SetValuesToContainer2"
    into: "in"
  - from: "SetValuesToContainer2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "RemoveValuesContainer2"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "ExchangeSessionObject8"
    via: "next"
    to: "ExchangeSessionObject4"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "SetValuesToContainer1"
    into: "in"
  - from: "RemoveValuesContainer8"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "ConcatenateStrings11"
    via: "next"
    to: "ConcatenateStrings13"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "ConcatenateStrings11"
    into: "in"
  - from: "ConcatenateStrings13"
    via: "next"
    to: "ConcatenateStrings12"
    into: "in"
  - from: "ConcatenateStrings12"
    via: "next"
    to: "ConcatenateStrings6"
    into: "in"
  - from: "ConcatenateStrings6"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "GetValuesFromContainer1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JumpNode1"
    into: "in"
