flow: "ViewPageletPropertiesAssignCampaign"
kind: "view"

entries:
  - id: "StartNode4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "JumpNode1"
    type: "jump"
    ref: "Error-Start"

links:
  - from: "StartNode4"
    via: "next"
    to: "JumpNode1"
    into: "in"
