flow: "ViewChannelCatalogList_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start23"
    name: "SortCatalogs"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "GetDisplayOptions"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "SetDisplayOptions"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "GetDisplayVariable"
    mode: "private"
    strict: true
    inputs:
      - key: "ChannelID"
        type: "java.lang.String"
        required: true
      - key: "VariableName"
        type: "java.lang.String"
        required: true
  - id: "StartNode6"
    name: "UnsortCatalogs"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "MoveCatalogsUp"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "MoveCatalogsDown"
    mode: "public"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessChannelCatalog_52-GetAuctionCatalogs"
  - id: "Call2"
    type: "call"
    ref: "ViewChannelCatalogList_52-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ProcessChannelCatalog_52-GetClassificationCatalogs"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessChannelCatalog-GetSortedStandardAndSharedCatalogs"
    bindings:
      CatalogOwningDomain: "CurrentChannel:RepositoryDomain"
  - id: "CallNode10"
    type: "call"
    ref: "This:GetDisplayVariable"
    bindings:
      VariableName: "\"T_HideLocalClassificationCatalogs_\""
      DisplayVariable: "HideLocalClassificationCatalogs"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessChannelCatalog-SortCatalogs"
  - id: "CallNode12"
    type: "call"
    ref: "This:GetDisplayVariable"
    bindings:
      VariableName: "\"T_HideLocalSystemClassificationCatalogs_\""
      DisplayVariable: "HideLocalSystemClassificationCatalogs"
  - id: "CallNode13"
    type: "call"
    ref: "This:GetDisplayVariable"
    bindings:
      VariableName: "\"T_HideSharedSystemClassificationCatalogs_\""
      DisplayVariable: "HideSharedSystemClassificationCatalogs"
  - id: "CallNode16"
    type: "call"
    ref: "ProcessChannelCatalog-MoveCatalogsUp"
  - id: "CallNode18"
    type: "call"
    ref: "ProcessChannelCatalog-MoveCatalogsDown"
  - id: "CallNode2"
    type: "call"
    ref: "This:GetDisplayVariable"
    bindings:
      VariableName: "\"T_HideSystemClassificationCatalogs_\""
      DisplayVariable: "HideSystemClassificationCatalogs"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessChannelCatalog-UnsortCatalogs"
  - id: "CallNode4"
    type: "call"
    ref: "This:GetDisplayOptions"
  - id: "CallNode5"
    type: "call"
    ref: "This:GetDisplayVariable"
    bindings:
      VariableName: "\"T_HideGeneralPagesCatalogs_\""
      DisplayVariable: "HideGeneralPagesCatalogs"
  - id: "CallNode6"
    type: "call"
    ref: "This:GetDisplayVariable"
    bindings:
      VariableName: "\"T_HideStandardCatalogs_\""
      DisplayVariable: "HideStandardCatalogs"
  - id: "CallNode7"
    type: "call"
    ref: "This:GetDisplayVariable"
    bindings:
      VariableName: "\"T_HideAuctionCatalogs_\""
      DisplayVariable: "HideAuctionCatalogs"
  - id: "CallNode8"
    type: "call"
    ref: "This:GetDisplayVariable"
    bindings:
      VariableName: "\"T_HideClassificationCatalogs_\""
      DisplayVariable: "HideClassificationCatalogs"
  - id: "CallNode9"
    type: "call"
    ref: "This:GetDisplayVariable"
    bindings:
      VariableName: "\"T_HideSharedClassificationCatalogs_\""
      DisplayVariable: "HideSharedClassificationCatalogs"
  - id: "ConcatenateStrings2"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString2: "_"
      DefaultString0: "T_"
    bindings:
      Concatenated: "DisplayChannelVariable"
      String3: "ChannelID"
      String1: "DisplayVariable"
  - id: "ConcatenateStrings6"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      Concatenated: "DisplayChannelVariable"
      String1: "ChannelID"
      String0: "VariableName"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelCatalog_52-Edit"
      OutValue_1: "ViewChannelCatalog_52-New"
      OutValue_2: "ViewChannelCatalog_52-Remove"
      OutValue_3: "ViewChannelCatalogList_52-ListAll"
      OutValue_4: "ViewChannelCatalogList_52-SortCatalogs"
      OutValue_5: "ViewChannelCatalogList_52-UnsortCatalogs"
      OutValue_6: "ViewChannelCatalogList_52-MoveCatalogsUp"
      OutValue_7: "ViewChannelCatalogList_52-MoveCatalogsDown"
    bindings:
      Key_0: "edit"
      Key_1: "create"
      Key_2: "delete"
      SelectionKey: "JumpTarget"
      Key_3: "cancel"
      Key_4: "sortCatalogs"
      Key_5: "unsortCatalogs"
      Key_6: "moveCatalogsUp.x"
      Key_7: "moveCatalogsDown.x"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "DisplayVariable"
        type: "java.lang.String"
        guaranteed: false
  - id: "ExchangeSessionObject1"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SessionObjectName: "DisplayChannelVariable"
      SaveObject: "DisplayValue"
  - id: "ExchangeSessionObject6"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
    bindings:
      SessionObjectName: "DisplayChannelVariable"
      LoadObject: "DisplayVariable"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Jump5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "This:ListAll"
  - id: "JumpNode7"
    type: "jump"
    ref: "ViewChannelCatalogList_52-ListAll"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Catalog\"):CatalogBORepository(CurrentOrganization)"
      OutValue_1: "CatalogBORepository"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelCatalogs"
      WorkingTemplate: "catalog/ChannelCatalogList_52"

links:
  - from: "Call3"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "CallNode16"
    via: "next"
    to: "JumpNode7"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "JumpNode7"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "CallNode16"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JumpNode7"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "ExchangeSessionObject1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "ConcatenateStrings2"
    into: "in"
  - from: "ConcatenateStrings2"
    via: "next"
    to: "ExchangeSessionObject1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "ConcatenateStrings6"
    into: "in"
  - from: "ConcatenateStrings6"
    via: "next"
    to: "ExchangeSessionObject6"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "CallNode18"
    via: "next"
    to: "JumpNode7"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "ExchangeSessionObject6"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Start23"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "CallNode18"
    into: "in"
