flow: "ViewCatalogExport_32"
kind: "view"

entries:
  - id: "Start2"
    name: "SelectCatalog"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Export"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "SelectClassificationCatalog"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "OverwriteFile"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "CancelOverwriteFile"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call2"
    type: "call"
    ref: "ProcessImpexJob-Create"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessImpexJob-IsFilenameTaken"
    bindings:
      Domain: "ChannelRepository:Domain"
      Filename: "CategoryExportForm:ExportFile:Value"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "ExportFile"
      param.1.required: true
      param.1.rule: "^[^.\\\\/:*?<>|\\s]([^\\\\/:*?<>|\\s]*[^.\\\\/:*?<>|\\s])?$"
      param.2.name: "CatalogDomainUUID"
      param.2.required: true
      webform-id: "CategoryExportForm"
      param.2.rule: ""
    bindings:
      WebForm: "CategoryExportConfiguration"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ExportedCatalogType"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "CategoryExportForm"
    bindings:
      WebForm: "CategoryExportForm"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "CategoryExportForm"
    bindings:
      WebForm: "CategoryExportForm"
  - id: "GetWebForm3"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "CategoryExportForm"
    bindings:
      WebForm: "CategoryExportForm"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "Jump3"
    type: "jump"
    ref: "ViewCatalogImpex_32-Status"
  - id: "JumpNode2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "CategoryExportForm_CatalogDomainUUID"
      InValue_2: "CategoryExportForm_ExportFile"
      OutValue_1: "CatalogDomainUUID"
      OutValue_2: "SelectedFile"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ChannelRepository:Domain"
      InValue_2: "ChannelRepository:Domain"
      OutValue_1: "ProcessOwningDomain"
      OutValue_2: "ProcessExecutionDomain"
      InValue_3: "CurrentApplication"
      OutValue_3: "Application"
  - id: "KeyMapper7"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "\"ProcessCatalogExport\""
      OutValue_1: "ProcessPipelineName"
      InValue_2: "\"Export\""
      OutValue_2: "ProcessPipelineStartNode"
      InValue_3: "\"ProcessCatalogImpex\""
      OutValue_3: "JobName"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewCatalogExport_32-SelectCatalog"
      OutValue_1: "ViewCatalogExport_32-Export"
      OutValue_2: "ViewCatalogImpex_32-Status"
      OutValue_3: "ViewCatalogExport_32-OverwriteFile"
      OutValue_4: "ViewCatalogExport_32-CancelOverwriteFile"
    bindings:
      Key_0: "Start"
      Key_1: "Export"
      Key_2: "Cancel"
      SelectionKey: "JumpTarget"
      Key_3: "Overwrite"
      Key_4: "CancelOverwrite"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "GetCatalogs"
    config:
      CatalogType: "Product Catalog"
      OnlineOnly: "False"
      ProxyFilter: "ON - Exclude Proxy Catalogs"
    bindings:
      Catalogs: "Catalogs"
      OrganizationDomain: "CurrentChannel:Domain"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "GetCatalogs"
    config:
      CatalogType: "Classification Catalog"
      OnlineOnly: "False"
      ProxyFilter: "ON - Exclude Proxy Catalogs"
    bindings:
      Catalogs: "Catalogs"
      OrganizationDomain: "CurrentChannel:Domain"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelImportExport"
      WorkingTemplate: "impex/CatalogExportSelectCatalog_32"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ExportedCatalogType"
      Value: "classification"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      ValueType: "Dictionary Value"
      Value: "ViewCatalogImpex_32-Status"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "FILENAME_ALREADY_IN_USE"
      Value: true
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "CategoryExportForm"
    bindings:
      WebForm: "CategoryExportForm"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "CategoryExportForm"
    bindings:
      WebForm: "CategoryExportForm"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "CategoryExportForm"
  - id: "ValidateWebForm2"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "CategoryExportForm"

links:
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "CreateWebForm1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "Join2"
    into: "in3"
  - from: "ValidateWebForm1"
    via: "error"
    to: "Join3"
    into: "in3"
  - from: "StartNode2"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "GetWebForm3"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "StartNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet3"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "Pipelet2"
    into: "in"
  - from: "KeyMapper7"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "ValidateWebForm2"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetWebForm2"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "UpdateWebForm2"
    via: "next"
    to: "ValidateWebForm2"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "KeyMapper7"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "GetWebForm2"
    via: "error"
    to: "Join2"
    into: "in1"
  - from: "ValidateWebForm2"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "StartNode4"
    via: "next"
    to: "GetWebForm3"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode3"
    via: "FILENAME_ALREADY_IN_USE"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "GetWebForm3"
    via: "error"
    to: "Join2"
    into: "in1"
  - from: "ValidateWebForm1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Join2"
    into: "in1"
