flow: "ViewCatalogImpex"
kind: "view"

entries:
  - id: "Start1"
    name: "DeleteImpexJobs"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Status"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Monitor"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "DownloadFile"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "Call2"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call3"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "Call5"
    type: "call"
    ref: "ProcessImpexJob-GetLogContent"
  - id: "Call7"
    type: "call"
    ref: "ProcessImpexJob-Delete"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessJobConfigurationSearch-Search"
  - id: "Decision1"
    type: "decision"
    condition: "ConfirmDeleteImpexJobs"
  - id: "Decision2"
    type: "decision"
    condition: "JobConfiguration:Status"
  - id: "DetermineUnit3"
    type: "pipelet"
    ref: "DetermineUnit"
    bindings:
      Unit: "UnitDomain"
      UnitName: "JobConfiguration:DomainName"
  - id: "GetBinaryFileContent2"
    type: "pipelet"
    ref: "GetBinaryFileContent"
    config:
      UnitDirectory: "IMPEX_DIR"
  - id: "GetJobConfiguration1"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "GetJobConfiguration2"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "GetJobConfiguration4"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd4"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewCatalogImpex-Status"
  - id: "Jump2"
    type: "jump"
    ref: "Error-Start"
  - id: "Jump4"
    type: "jump"
    ref: "Error-FileNotFound"
  - id: "JumpNode3"
    type: "jump"
    ref: "Error-Start"
  - id: "JumpNode5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "OrganizationDomain"
      OutValue_1: "JobDomain"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Jobs"
      OutValue_1: "ImpexJobs"
  - id: "Loop1"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewCatalogImpex-Status"
      OutValue_1: "ViewCatalogImpex-DeleteImpexJobs"
      OutValue_2: "ViewCatalogImpex-Status"
      OutValue_3: "ViewCatalogImpex-Monitor"
      OutValue_4: "ViewCatalogImpex-DownloadFile"
      OutValue_5: "ViewCatalogImport-SelectFile"
      OutValue_6: "ViewCatalogImport-SelectCSVFile"
      OutValue_7: "ViewCatalogExport-SelectCatalog"
      OutValue_8: "ViewProductImport-SelectFile"
      OutValue_9: "ViewProductImport-SelectCSVFile"
    bindings:
      Key_0: "Status"
      Key_1: "DeleteImpexJobs"
      Key_2: "ConfirmDeleteImpexJobs"
      Key_3: "Monitor"
      Key_4: "DownloadFile"
      Key_5: "CategoryImport"
      Key_6: "CategoryCSVImport"
      Key_7: "CategoryExport"
      Key_8: "ProductImport"
      Key_9: "ProductCSVImport"
      SelectionKey: "JumpTarget"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewCatalogImportFiles-BrowseDirectory"
      OutValue_1: "ViewCatalogExportFiles-BrowseDirectory"
      OutValue_2: "ViewProductAttachments-BrowseSecureDirectory"
      OutValue_3: "ViewProductExport-Search"
      OutValue_4: "ViewBMEcatImport-SelectFile"
      OutValue_5: "ViewBMEcatExport-SelectCatalog"
      OutValue_6: "ViewProductAttachments-BrowseDirectory"
      OutValue_7: "ViewVariationTypeImport-SelectFile"
      OutValue_8: "ViewVariationTypeImport-SelectCSVFile"
      OutValue_9: "ViewVariationTypeExport-ListAll"
    bindings:
      Key_0: "ImportFiles"
      Key_1: "ExportFiles"
      Key_2: "ProductAttachments"
      Key_3: "ProductExport"
      Key_4: "BMEcatImport"
      SelectionKey: "JumpTarget"
      Key_5: "BMEcatExport"
      Key_6: "ProductImages"
      Key_7: "VariationTypeImport"
      Key_8: "VariationTypeCSVImport"
      Key_9: "VariationTypeExport"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewCatalogImport-SelectClassificationCatalogFile"
      OutValue_1: "ViewCatalogExport-SelectClassificationCatalog"
      OutValue_2: "ViewScene7ImageImport-SelectFile"
      OutValue_3: "ViewImageMetadataImport-SelectFile"
      OutValue_4: "ViewImageMetadataExport-SelectConfiguration"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "ClassificationCategoryImport"
      Key_1: "ClassificationCategoryExport"
      Key_2: "Scene7ImageCSVImport"
      Key_3: "ImageMetadataImport"
      Key_4: "ImageMetadataExport"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ImportExport"
      WorkingTemplate: "impex/CatalogImpexOverview"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ImportExport"
      WorkingTemplate: "impex/CatalogImpexMonitor"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JobName"
      Value: "ProcessCatalogImpex"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "Error-Start"

links:
  - from: "StartNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetJobConfiguration1"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Call7"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Call1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "Pipelet2"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "GetJobConfiguration2"
    into: "in"
  - from: "GetJobConfiguration2"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "GetJobConfiguration2"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "error"
    to: "Join2"
    into: "in3"
  - from: "Join7"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join7"
    into: "in3"
  - from: "GetBinaryFileContent2"
    via: "next"
    to: "InteractionEnd4"
    into: "in"
  - from: "GetJobConfiguration4"
    via: "next"
    to: "DetermineUnit3"
    into: "in"
  - from: "GetJobConfiguration4"
    via: "error"
    to: "Join8"
    into: "in1"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "Join9"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "GetBinaryFileContent2"
    via: "error"
    to: "Join9"
    into: "in2"
  - from: "Join8"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "DetermineUnit3"
    via: "error"
    to: "Join8"
    into: "in2"
  - from: "Start5"
    via: "next"
    to: "GetJobConfiguration4"
    into: "in"
  - from: "DetermineUnit3"
    via: "next"
    to: "GetBinaryFileContent2"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "Call5"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "Call5"
    via: "Error"
    to: "Join5"
    into: "in2"
  - from: "Call4"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Join5"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "Pipelet2"
    via: "error"
    to: "Pipelet3"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "KeyMapper1"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "CallNode1"
    via: "Error"
    to: "Jump2"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "Decision1"
    via: "yes"
    to: "Call4"
    into: "in"
  - from: "Pipelet3"
    via: "error"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "Call3"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Decision1"
    into: "in"
