flow: "ViewPromotionTargetCodeGroupsSelection"
kind: "view"

entries:
  - id: "Start11"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Prefix"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentChannel"
        type: "java.lang.Object"
        required: false
      - key: "PromotionUUID"
        type: "java.lang.String"
        required: false
  - id: "StartNode9"
    name: "ParametricSearch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call7"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessPromotionCodeGroup-Search"
    bindings:
      Domain: "PromotionDomain"
  - id: "CallNode10"
    type: "call"
    ref: "ProcessPromotionCodeGroup-Paging"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessPromotionCodeGroup-ProcessParametricSearch"
    bindings:
      SearchTerm: "PromotionCodeGroupSearchForm:SimpleSearch:Value"
      Domain: "PromotionDomain"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessPromotionCodeGroup-Paging"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessPromotion-GetPromotionDomainByChannel"
    bindings:
      Channel: "CurrentChannel"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessPromotionCodeGroup-Assign"
  - id: "CallNode5"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode6"
    type: "call"
    ref: "ViewPromotionTargetCodeGroupsSelection-Prefix"
  - id: "CallNode7"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessPromotion-TouchPromotion"
    bindings:
      Iterator: "UUIDIterator"
  - id: "CallNode9"
    type: "call"
    ref: "This:Prefix"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "PromotionCodeGroupSearch"
      FormResource: "PromotionCodeGroupSearch"
    bindings:
      Form: "PromotionCodeGroupSearchForm"
  - id: "CreateForm2"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "PromotionCodeGroupSearch"
      FormResource: "PromotionCodeGroupSearch"
    bindings:
      Form: "PromotionCodeGroupSearchForm"
  - id: "CreateForm4"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "PromotionCodeGroupSearch"
      FormResource: "PromotionCodeGroupSearch"
    bindings:
      Form: "PromotionCodeGroupSearchForm"
  - id: "DecisionNode1"
    type: "decision"
    condition: "SelectedObjectUUIDs"
  - id: "DecisionNode2"
    type: "decision"
    condition: "PromotionCodeGroups"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      PagingPipeline: "ViewPromotionTargetCodeGroupsSelection-Paging"
      OutValue_0: "ViewPromotionCodeConfiguration-Edit"
      OutValue_1: "ViewPromotionTargetCodeGroupsSelection-Create"
    bindings:
      Key_0: "cancel"
      Key_1: "assign"
      SelectionKey: "JumpTarget"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "PromotionDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        guaranteed: true
      - key: "Promotion"
        type: "com.intershop.component.marketing.capi.rebate.Promotion"
        guaranteed: false
      - key: "AssignedPromotionCodeGroups"
        type: "java.util.Iterator"
        guaranteed: true
  - id: "GetPromotionByUUID3"
    type: "pipelet"
    ref: "GetPromotionByUUID"
  - id: "GetPromotionCodeGroupByID1"
    type: "pipelet"
    ref: "GetPromotionCodeGroupByID"
    bindings:
      Domain: "PromotionDomain"
      GroupID: "PromotionCodeGroupsUUID"
  - id: "GetPromotionCodeGroups2"
    type: "pipelet"
    ref: "GetPromotionCodeGroups"
    bindings:
      Domain: "PromotionDomain"
      PromotionCodeGroups: "AssignedPromotionCodeGroups"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump6"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewPromotionCodeConfiguration-Edit"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewPromotionTargetCodeGroupsSelection-Paging"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "CurrentPageNumber"
      InValue_10: "\"error.no_items_selected\""
      OutValue_1: "PageNumber"
      OutValue_10: "ERROR_PromotionCodeGroup"
  - id: "Loop1"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetTargetClusters"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/PromotionTargetCodeGroupSelect"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewPromotionTargetCodeGroupsSelection-ListAll"
      ValueType: "Dictionary Value"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultPageLocatorName: "PromotionCodeGroupList"
      DefaultHandlerPipeline: "ViewPromotionTargetCodeGroupsSelection-Paging"
    bindings:
      Pageable: "PromotionCodeGroups"
      PageLocatorName: "null"
      HandlerPipeline: "null"
  - id: "SetPageLocator2"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultPageLocatorName: "PromotionCodeGroupList"
      DefaultHandlerPipeline: "ViewPromotionTargetCodeGroupsSelection-Paging"
    bindings:
      Pageable: "PromotionCodeGroups"
      PageLocatorName: "null"
      HandlerPipeline: "null"
  - id: "ValidateForm2"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "PromotionCodeGroupSearchForm"

links:
  - from: "Call7"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode10"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode10"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode11"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode2"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "GetPromotionCodeGroups2"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode5"
    via: "next"
    to: "CreateForm4"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "CreateForm2"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "ValidateForm2"
    into: "in"
  - from: "CreateForm2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CreateForm4"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "KeyMapper2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "Loop1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "SetPageLocator2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetPromotionByUUID3"
    via: "error"
    to: "JoinNode8"
    into: "in1"
  - from: "GetPromotionByUUID3"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "GetPromotionCodeGroupByID1"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "GetPromotionCodeGroupByID1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "GetPromotionCodeGroups2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Jump6"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetPromotionCodeGroupByID1"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "SetPageLocator1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "SetPageLocator2"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "Start11"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetPromotionByUUID3"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "ValidateForm2"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "ValidateForm2"
    via: "next"
    to: "CallNode11"
    into: "in"
