flow: "ViewSearchIndexServices"
kind: "view"

entries:
  - id: "Start6"
    name: "ShowMore"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode11"
    type: "call"
    ref: "ProcessSearchBySearchIndex-ProcessSelectedCatalogCategory"
    bindings:
      Domain: "CurrentOrganization:OwningDomain"
  - id: "CallNode16"
    type: "call"
    ref: "ViewParametricSearchBySearchIndex-QueryIndexes"
  - id: "CallNode4"
    type: "call"
    ref: "ViewParametricSearchBySearchIndex-FilterConditionsByUser"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessSearchBySearchIndex-AddCatalogFilterCondition"
  - id: "CallNode7"
    type: "call"
    ref: "ViewParametricSearchBySearchIndex-GetIndexQueries"
  - id: "GetFilterAttribute1"
    type: "pipelet"
    ref: "GetFilterAttribute"
    bindings:
      Attribute: "SearchIndex:Configuration:AttributeByName(FilterName)"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "DisableOracleCatalogBrowsing"
      InValue_1: "\"true\""
      OutValue_2: "LimitCount"
      InValue_2: "SearchIndex:Configuration:AttributeByName(FilterName):FilterOptions:LimitCount"
      OutValue_3: "query"
      InValue_3: "SearchResult:Query"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "ErrorStatus"
      InValue_1: "\"NoSearchIndexFoundForFeature\""
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "ErrorStatus"
      InValue_1: "\"NoSearchResult\""
  - id: "TextNode6"
    type: "text"
  - id: "TextNode7"
    type: "text"

links:
  - from: "KeyMapper4"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "CallNode7"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "CallNode16"
    via: "next"
    to: "GetFilterAttribute1"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "CallNode16"
    via: "NO_SEARCHRESULT"
    to: "KeyMapper5"
    into: "in"
  - from: "CallNode7"
    via: "NO_PRODUCTINDEX"
    to: "KeyMapper4"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode4"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode8"
    into: "in3"
  - from: "GetFilterAttribute1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "CallNode6"
    via: "next"
    to: "CallNode16"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "KeyMapper3"
    into: "in"
