flow: "ViewOrderProcessing_52"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode10"
    name: "Show"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "DispatchExport"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Delete"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "RunJobs"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "DispatchStatusImport"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "ConfirmDelete"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call5"
    type: "call"
    ref: "ViewProcessList_52-DeleteLogFiles"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "CreateMappingIterator1"
    type: "pipelet"
    ref: "CreateMappingIterator"
    config:
      ObjectMapperClass: "com.intershop.component.orderimpex.internal.impexscenario.JobConfiguration2ImpexScenarioMapper"
      SkipNullElements: true
    bindings:
      SourceIterator: "JobConfigurations"
      TargetIterator: "ExportOrderConfigs"
  - id: "CreateMappingIterator2"
    type: "pipelet"
    ref: "CreateMappingIterator"
    config:
      ObjectMapperClass: "com.intershop.component.orderimpex.internal.impexscenario.JobConfiguration2ImpexScenarioMapper"
      SkipNullElements: true
    bindings:
      SourceIterator: "JobConfigurations"
      TargetIterator: "OrderStatusImports"
  - id: "DecisionNode1"
    type: "decision"
    condition: "SelectedUUIDs"
  - id: "ExecuteJob1"
    type: "pipelet"
    ref: "ExecuteJob"
    bindings:
      JobConfig: "JobConfiguration"
      CurrentUser: "null"
  - id: "GetAllJobConfigurations1"
    type: "pipelet"
    ref: "GetAllJobConfigurations"
    config:
      DefaultJobNamePrefix: "ExportOrder_"
      DefaultJobState: "None"
    bindings:
      JobConfigurations: "JobConfigurations"
      Domain: "CurrentChannel:RepositoryDomain"
  - id: "GetAllJobConfigurations2"
    type: "pipelet"
    ref: "GetAllJobConfigurations"
    config:
      DefaultJobNamePrefix: "OrderStatusImport_"
      DefaultJobState: "None"
    bindings:
      JobConfigurations: "JobConfigurations"
      Domain: "CurrentChannel:RepositoryDomain"
  - id: "GetFormSelection4"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedObjectUUID"
    bindings:
      Selection: "SelectedUUIDs"
      ParameterName: "null"
  - id: "GetJobConfiguration1"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "UUID"
      JobConfiguration: "JobConfiguration"
      JobDomain: "null"
      JobDomainName: "null"
      JobName: "null"
  - id: "GetJobConfiguration2"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "UUID"
      JobConfiguration: "JobConfiguration"
      JobDomain: "null"
      JobDomainName: "null"
      JobName: "null"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewOrderProcessing_52-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode4"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode5"
    type: "jump"
    ref: "ViewOrderProcessing_52-Start"
  - id: "JumpNode7"
    type: "jump"
    ref: "ViewOrderProcessing_52-Show"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"true\""
      OutValue_1: "missingRunSelection"
  - id: "KeyMapper6"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Repository(\"ServiceConfigurationBORepository\")"
      OutValue_1: "ServiceConfigurationRepository"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewOrderStatusImport_52-New"
      OutValue_2: "ViewOrderProcessing_52-ConfirmDelete"
      OutValue_3: "ViewOrderProcessing_52-Delete"
      OutValue_1: "ViewOrderProcessing_52-RunJobs"
      OutValue_4: "ViewOrderProcessing_52-Show"
      OutValue_5: "ViewOrderProcessing_52-Start"
    bindings:
      Key_0: "new"
      SelectionKey: "JumpTarget"
      Key_2: "confirmDelete"
      Key_1: "run"
      Key_3: "delete"
      Key_4: "cancelDelete"
      Key_5: "refresh"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewOrderExportGeneral_52-New"
      OutValue_2: "ViewOrderProcessing_52-ConfirmDelete"
      OutValue_3: "ViewOrderProcessing_52-Delete"
      OutValue_1: "ViewOrderProcessing_52-RunJobs"
      OutValue_4: "ViewOrderProcessing_52-Show"
      OutValue_5: "ViewOrderProcessing_52-Start"
    bindings:
      Key_0: "new"
      SelectionKey: "JumpTarget"
      Key_2: "confirmDelete"
      Key_1: "run"
      Key_3: "delete"
      Key_4: "cancelDelete"
      Key_5: "refresh"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "order/OrderProcessingOverview_52"
      SelectedMenuItem: "Orders"
  - id: "RemoveJobConfiguration1"
    type: "pipelet"
    ref: "RemoveJobConfiguration"
  - id: "SortIteratorByComparator1"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingOrder: true
      DefaultSortingAttribute: "Name"
    bindings:
      Comparator: "null"
      Iterator: "JobConfigurations"
      SortingAttribute: "null"
      SortingOrder: "null"
      SortedIterator: "JobConfigurations"
  - id: "SortIteratorByComparator2"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingOrder: true
      DefaultSortingAttribute: "Name"
    bindings:
      Comparator: "null"
      Iterator: "JobConfigurations"
      SortingAttribute: "null"
      SortingOrder: "null"
      SortedIterator: "JobConfigurations"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "next"
    to: "ExecuteJob1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JumpNode7"
    into: "in"
  - from: "CreateMappingIterator2"
    via: "next"
    to: "KeyMapper6"
    into: "in"
  - from: "KeyMapper6"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "GetAllJobConfigurations1"
    via: "next"
    to: "SortIteratorByComparator1"
    into: "in"
  - from: "CreateMappingIterator1"
    via: "next"
    to: "GetAllJobConfigurations2"
    into: "in"
  - from: "SortIteratorByComparator1"
    via: "next"
    to: "CreateMappingIterator1"
    into: "in"
  - from: "SortIteratorByComparator2"
    via: "next"
    to: "CreateMappingIterator2"
    into: "in"
  - from: "GetAllJobConfigurations2"
    via: "next"
    to: "SortIteratorByComparator2"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "GetJobConfiguration2"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "RemoveJobConfiguration1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "StartNode10"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "GetFormSelection4"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "GetAllJobConfigurations1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetJobConfiguration2"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "LoopNode2"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "GetJobConfiguration2"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "RemoveJobConfiguration1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "GetFormSelection4"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "LoopNode1"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "JoinNode4"
    into: "in2"
  - from: "ExecuteJob1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "StartNode2"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "KeyMapper3"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "GetJobConfiguration1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
