flow: "ViewChannelOutboundSyndicationTarget"
kind: "view"

entries:
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      - key: "SyndicationUUID"
        type: "java.lang.String"
        required: true
      - key: "LocaleId"
        type: "java.lang.String"
        required: false
      - key: "ConfirmDelete"
        type: "java.lang.String"
        required: false
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "UpdateConfig"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
  - id: "CallNode2"
    type: "call"
  - id: "CallNode3"
    type: "call"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessProductOutboundSyndication-Validate"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessProductOutboundSyndication-Validate"
  - id: "CallNode6"
    type: "call"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "Syndication:Target:ConfigPipeline"
      String1: "\"-Remove\""
      Concatenated: "RemoveConfigPipeline"
  - id: "ConcatenateStrings10"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "Syndication:Target:ProcessPipeline"
      String1: "\"-DeterminePageable\""
      Concatenated: "DeterminePageablePipeline"
  - id: "ConcatenateStrings2"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "Syndication:Target:ConfigPipeline"
      String1: "\"-Update\""
      Concatenated: "UpdateConfigPipeline"
  - id: "ConcatenateStrings3"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "Syndication:Target:ConfigPipeline"
      String1: "\"-CreateWebForm\""
      Concatenated: "CreateWebFormPipeline"
  - id: "ConcatenateStrings4"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "Syndication:Target:ConfigPipeline"
      String1: "\"-CreateWebForm\""
      Concatenated: "CreateWebFormPipeline"
  - id: "ConcatenateStrings5"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "Syndication:Target:ConfigPipeline"
      String1: "\"-Dispatch\""
      Concatenated: "JumpTarget"
  - id: "ConcatenateStrings7"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "Syndication:Target:ProcessPipeline"
      String1: "\"-Init\""
      Concatenated: "InitPipeline"
  - id: "ConcatenateStrings8"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "Syndication:Target:ProcessPipeline"
      String1: "\"-Post\""
      Concatenated: "PostPipeline"
  - id: "ConcatenateStrings9"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "Syndication:Target:ProcessPipeline"
      String1: "\"-Process\""
      Concatenated: "ProcessPipeline"
  - id: "CreateWebForm2"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "Type"
      param.1.required: true
      param.1.rule: ""
      webform-id: "SyndicationTargetForm"
    bindings:
      WebForm: "SyndicationTargetForm"
  - id: "DecisionNode1"
    type: "decision"
    condition: "SyndicationTargetForm_Type"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Syndication:Target:ConfigPipelineNull"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Syndication:Target:ConfigPipelineNull"
  - id: "DecisionNode4"
    type: "decision"
    condition: "Syndication:Target:Parameters:ftp"
  - id: "DecisionNode5"
    type: "decision"
    condition: "Syndication:Target:ConfigPipelineNull"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelOutboundSyndicationTarget-Edit"
      OutValue_1: "ViewChannelOutboundSyndicationTarget-Update"
      OutValue_2: "ViewChannelOutboundSyndicationList-Start"
      OutValue_3: "ViewChannelOutboundSyndicationTarget-UpdateConfig"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "Edit"
      Key_1: "Update"
      Key_2: "Back"
      Key_3: "UpdateConfig"
  - id: "GetSyndicationByUUID1"
    type: "pipelet"
    ref: "GetSyndicationByUUID"
  - id: "GetSyndicationByUUID2"
    type: "pipelet"
    ref: "GetSyndicationByUUID"
  - id: "GetSyndicationByUUID3"
    type: "pipelet"
    ref: "GetSyndicationByUUID"
  - id: "GetSyndicationByUUID5"
    type: "pipelet"
    ref: "GetSyndicationByUUID"
  - id: "GetSyndicationTargets1"
    type: "pipelet"
    ref: "GetSyndicationTargets"
  - id: "GetSyndicationTargets2"
    type: "pipelet"
    ref: "GetSyndicationTargets"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "SyndicationTargetForm"
    bindings:
      WebForm: "SyndicationTargetForm"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelCatalogs"
      WorkingTemplate: "syndication/ChannelOutboundSyndicationTarget"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelCatalogs"
      WorkingTemplate: "syndication/ChannelOutboundSyndicationTarget"
  - id: "UpdateCustomAttributes1"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "FTPUpload"
      Attribute_1_Type: "Integer"
    bindings:
      ExtensibleObject: "Syndication"
      Attribute_1_Value: "\"2\""
  - id: "UpdateCustomAttributes2"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "FTPUpload"
      Attribute_1_Type: "Integer"
    bindings:
      ExtensibleObject: "Syndication"
      Attribute_1_Value: "\"4\""
  - id: "UpdateCustomAttributes4"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "JobExecutionDomainID"
      Attribute_1_Type: "String"
      Attribute_10_Type: "String"
      Attribute_2_Name: "JobCreatorUserID"
      Attribute_2_Type: "String"
      Attribute_3_Name: "DeterminePageablePipeline"
      Attribute_3_Type: "String"
      Attribute_4_Name: "InitPipeline"
      Attribute_4_Type: "String"
      Attribute_5_Name: "ProcessPipeline"
      Attribute_5_Type: "String"
      Attribute_6_Type: "String"
      Attribute_6_Name: "PostPipeline"
      Attribute_7_Name: "LogEntriesTemplate"
      Attribute_7_Type: "String"
    bindings:
      Attribute_1_Value: "CurrentChannel:OwningDomain:Site:UUID"
      ExtensibleObject: "Syndication:JobConfiguration"
      Attribute_2_Value: "CurrentUser:ID"
      Attribute_3_Value: "DeterminePageablePipeline"
      Attribute_4_Value: "InitPipeline"
      Attribute_5_Value: "ProcessPipeline"
      Attribute_6_Value: "PostPipeline"
      Attribute_7_Value: "\"syndication/ChannelOutboundSyndicationLogEntries.isml\""
  - id: "UpdateSyndication2"
    type: "pipelet"
    ref: "UpdateSyndication"
    bindings:
      Description: "null"
      DisplayName: "null"
      TargetID: "SyndicationTargetForm_Type"
      Enabled: "null"
      JobConfiguration: "null"
      Locale: "null"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "SyndicationTargetForm"
    bindings:
      WebForm: "SyndicationTargetForm"
  - id: "ValidateWebForm2"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "SyndicationTargetForm"

links:
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "GetWebForm2"
    via: "next"
    to: "GetSyndicationByUUID3"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "ConcatenateStrings9"
    via: "next"
    to: "ConcatenateStrings8"
    into: "in"
  - from: "UpdateWebForm2"
    via: "next"
    to: "ValidateWebForm2"
    into: "in"
  - from: "ConcatenateStrings7"
    via: "next"
    to: "ConcatenateStrings9"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "UpdateCustomAttributes1"
    into: "in"
  - from: "UpdateCustomAttributes4"
    via: "next"
    to: "GetSyndicationTargets1"
    into: "in"
  - from: "ConcatenateStrings4"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "ConcatenateStrings5"
    via: "next"
    to: "JoinNode8"
    into: "in3"
  - from: "GetSyndicationByUUID2"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "GetSyndicationTargets1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "GetSyndicationTargets2"
    into: "in"
  - from: "GetWebForm2"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode4"
    into: "in2"
  - from: "DecisionNode1"
    via: "yes"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "ValidateWebForm2"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "UpdateSyndication2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetSyndicationByUUID1"
    into: "in"
  - from: "ConcatenateStrings2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "GetSyndicationByUUID1"
    via: "next"
    to: "ConcatenateStrings2"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode3"
    into: "in2"
  - from: "DecisionNode3"
    via: "yes"
    to: "ConcatenateStrings3"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetSyndicationByUUID3"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "ConcatenateStrings8"
    via: "next"
    to: "UpdateCustomAttributes4"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "UpdateSyndication2"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "UpdateCustomAttributes2"
    into: "in"
  - from: "UpdateCustomAttributes2"
    via: "next"
    to: "JoinNode6"
    into: "in3"
  - from: "UpdateCustomAttributes1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "ConcatenateStrings10"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "GetSyndicationTargets2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "ConcatenateStrings10"
    via: "next"
    to: "ConcatenateStrings7"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "GetSyndicationByUUID5"
    via: "next"
    to: "ConcatenateStrings5"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "ConcatenateStrings4"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "GetSyndicationByUUID5"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode7"
    into: "in2"
  - from: "CallNode6"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "ConcatenateStrings3"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "CreateWebForm2"
    into: "in"
  - from: "CreateWebForm2"
    via: "next"
    to: "GetSyndicationByUUID2"
    into: "in"
  - from: "ValidateWebForm2"
    via: "error"
    to: "JoinNode1"
    into: "in2"
