flow: "ViewSearchAction"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Redirect"
    mode: "private"
    strict: false
    inputs:
      - key: "SearchAction"
        type: "com.intershop.component.search.capi.searchaction.SearchAction"
        required: true
      - key: "CurrentOrganization"
        type: "com.intershop.component.organization.capi.Organization"
        required: false
      - key: "CurrentProductRepository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: false
  - id: "StartNode2"
    name: "RedirectToTarget"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "ProductDetailRedirect"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessB2CProduct-GetProductBOByProductUUIDOrSKU"
    bindings:
      ProductDomain: "CurrentProductRepository:Domain"
      ProductUUID: "SearchAction:RedirectTarget"
      SKU: "null"
  - id: "DecisionNode1"
    type: "decision"
    condition: "SearchAction:RedirectType"
  - id: "DecisionNode2"
    type: "decision"
    condition: "SearchAction:RedirectType"
  - id: "DecisionNode3"
    type: "decision"
    condition: "SearchAction:RedirectType"
  - id: "DecisionNode4"
    type: "decision"
    condition: "SearchAction:RedirectType"
  - id: "DecisionNode5"
    type: "decision"
    condition: "SearchAction:RedirectType"
  - id: "DecisionNode6"
    type: "decision"
    condition: "ProductBO:DefaultCatalogCategory"
  - id: "DecisionNode7"
    type: "decision"
    condition: "ProductBO"
  - id: "DetermineCatalogCategory1"
    type: "pipelet"
    ref: "DetermineCatalogCategory"
    bindings:
      CatalogCategoryID: "SearchAction:RedirectTarget"
  - id: "InteractionNode5"
    type: "interaction"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewSearchAction-RedirectToTarget"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewSearchAction-ProductDetailRedirect"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewSearchAction-RedirectToTarget"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewParametricSearch-SimpleOfferSearch"
  - id: "JumpNode5"
    type: "jump"
    ref: "ViewSearchAction-RedirectToTarget"
  - id: "JumpNode6"
    type: "jump"
    ref: "ViewSearchAction-RedirectToTarget"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      OutValue_1: "TargetPipeline"
      InValue_1: "\"ViewProduct-Start\""
      OutValue_2: "Parameter1_Name"
      InValue_2: "\"SKU\""
      OutValue_3: "Parameter1_Value"
      InValue_3: "ProductBO:SKU"
      OutValue_4: "Parameter2_Name"
      InValue_4: "\"CategoryName\""
      InValue_5: "ProductBO:DefaultCatalogCategory:Name"
      OutValue_5: "Parameter2_Value"
      InValue_6: "\"CategoryDomainName\""
      OutValue_6: "Parameter3_Name"
      OutValue_7: "Parameter3_Value"
      InValue_7: "ProductBO:DefaultCatalogCategory:Domain:DomainName"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      OutValue_1: "TargetPipeline"
      InValue_1: "\"ViewProduct-Start\""
      OutValue_2: "Parameter1_Name"
      InValue_2: "\"SKU\""
      OutValue_3: "Parameter1_Value"
      InValue_3: "ProductBO:SKU"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "SearchAction:RedirectTarget"
      OutValue_1: "TargetURL"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "SearchAction:RedirectTarget"
      OutValue_1: "RedirectSearchTerm"
  - id: "KeyMapper7"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      OutValue_1: "TargetPipeline"
      InValue_1: "\"ViewContent-Start\""
      OutValue_3: "Parameter1_Name"
      InValue_3: "\"PageletEntryPointUUID\""
      InValue_4: "SearchAction:RedirectTarget"
      OutValue_4: "Parameter1_Value"
  - id: "KeyMapper8"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      OutValue_1: "TargetPipeline"
      InValue_1: "\"ViewStandardCatalog-Browse\""
      OutValue_3: "Parameter1_Name"
      InValue_3: "\"CategoryName\""
      InValue_4: "Category:Name"
      OutValue_4: "Parameter1_Value"
      InValue_2: "\"CategoryDomainName\""
      OutValue_2: "Parameter2_Name"
      InValue_5: "Category:Domain:DomainName"
      OutValue_5: "Parameter2_Value"
  - id: "StopNode1"
    type: "stop"

links:
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "KeyMapper7"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "DecisionNode7"
    into: "in"
  - from: "KeyMapper7"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "DetermineCatalogCategory1"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "InteractionNode5"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "KeyMapper5"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "DetermineCatalogCategory1"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JumpNode6"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "DecisionNode2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "StopNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "CallNode1"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "KeyMapper3"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "KeyMapper2"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode7"
    via: "yes"
    to: "JumpNode2"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "DecisionNode4"
    into: "in"
  - from: "DetermineCatalogCategory1"
    via: "next"
    to: "KeyMapper8"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "JoinNode3"
    into: "in2"
  - from: "StartNode3"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "KeyMapper4"
    into: "in"
  - from: "KeyMapper8"
    via: "next"
    to: "JumpNode1"
    into: "in"
