flow: "ViewLocalizationImpex"
kind: "view"

entries:
  - id: "Start1"
    name: "Status"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "DeleteImpexJobs"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Monitor"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "DownloadFile"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "ValidateFileRefresh"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call2"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "Call3"
    type: "call"
    ref: "ProcessJobConfigurationSearch-Search"
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "Call5"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call7"
    type: "call"
    ref: "ProcessImpexJob-Delete"
  - id: "Decision1"
    type: "decision"
    condition: "ConfirmDeleteImpexJobs"
  - id: "DetermineUnit1"
    type: "pipelet"
    ref: "DetermineUnit"
    bindings:
      UnitName: "JobConfiguration:DomainName"
      Unit: "UnitDomain"
  - id: "GetBinaryFileContent1"
    type: "pipelet"
    ref: "GetBinaryFileContent"
    config:
      UnitDirectory: "IMPEX_DIR"
  - id: "GetJobConfiguration1"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "GetJobConfiguration2"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "GetJobConfiguration3"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "Error-FileNotFound"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump4"
    type: "jump"
    ref: "ViewLocalizationImpex-Status"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewLocalizationImport-ValidateFileRefresh"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentOrganization:Domain:Site"
      InValue_2: "\"ProcessLocalizationImpex\""
      OutValue_1: "JobDomain"
      OutValue_2: "JobName"
  - id: "KeyMapper6"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Jobs"
      OutValue_1: "ImpexJobs"
  - id: "Loop1"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewLocalizationExport-ExportToXliff"
      OutValue_1: "ViewLocalizationImpex-Status"
      OutValue_2: "ViewLocalizationImpex-DeleteImpexJobs"
      OutValue_3: "ViewLocalizationImpex-Status"
      OutValue_4: "ViewLocalizationExportFiles-BrowseDirectory"
      OutValue_5: "ViewLocalizationImport-SelectFile"
      OutValue_6: "ViewLocalizationImportFiles-BrowseDirectory"
      OutValue_7: "ViewLocalizationExport-ExportToProperties"
    bindings:
      Key_0: "LocalizationExportXliff"
      Key_1: "ConfirmDeleteImpexJobs"
      Key_2: "DeleteImpexJobs"
      Key_3: "Status"
      Key_4: "ExportFiles"
      Key_5: "LocalizationImport"
      Key_6: "ImportFiles"
      Key_7: "LocalizationExportProperties"
      SelectionKey: "JumpTarget"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Localization"
      WorkingTemplate: "localization/LocalizationImpexOverview"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Localization"
      WorkingTemplate: "localization/LocalizationImpexMonitor"

links:
  - from: "Call1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Call2"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Call3"
    via: "next"
    to: "KeyMapper6"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Decision1"
    via: "no"
    to: "Call1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Call2"
    into: "in"
  - from: "DetermineUnit1"
    via: "error"
    to: "Join4"
    into: "in1"
  - from: "DetermineUnit1"
    via: "next"
    to: "GetBinaryFileContent1"
    into: "in"
  - from: "GetBinaryFileContent1"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "GetBinaryFileContent1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "error"
    to: "Join4"
    into: "in1"
  - from: "GetJobConfiguration1"
    via: "next"
    to: "DetermineUnit1"
    into: "in"
  - from: "GetJobConfiguration2"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "GetJobConfiguration3"
    via: "error"
    to: "Join2"
    into: "in1"
  - from: "GetJobConfiguration3"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "KeyMapper5"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "KeyMapper6"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetJobConfiguration3"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "GetJobConfiguration2"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "GetJobConfiguration1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "JumpNode1"
    into: "in"
