flow: "ViewChannelSortingPreferences_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "UpdateProductPreferences"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "UpdateSubCategoryPreferences"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "UpdateCatalogPreferences"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessCatalogSorting-GetDefaultSubCategorySortingPreferences"
  - id: "Call10"
    type: "call"
    ref: "ProcessCatalogSorting-UpdateDefaultCatalogSortingPreferences"
  - id: "Call2"
    type: "call"
    ref: "ViewChannelSortingPreferences_52-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ViewChannelSortingPreferences_52-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ProcessCatalogSorting-UpdateDefaultProductSortingPreferences"
  - id: "Call5"
    type: "call"
    ref: "ProcessCatalogSorting-GetDefaultProductSortingPreferences"
  - id: "Call6"
    type: "call"
    ref: "ViewChannelSortingPreferences_52-Prefix"
  - id: "Call7"
    type: "call"
    ref: "ProcessCatalogSorting-UpdateDefaultSubCategorySortingPreferences"
  - id: "Call8"
    type: "call"
    ref: "ProcessCatalogSorting-GetDefaultCatalogSortingPreferences"
  - id: "Call9"
    type: "call"
    ref: "ViewChannelSortingPreferences_52-Prefix"
  - id: "CheckForEmptyString1"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "ProductDefaultSortingCustomValue"
  - id: "CheckForEmptyString2"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "SubCategoryDefaultSortingCustomValue"
  - id: "CheckForEmptyString3"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "CatalogDefaultSortingCustomValue"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "ProductDefaultSortingAttribute"
      param.1.required: true
      param.2.name: "ProductDefaultSortingStandardValue"
      param.2.required: false
      param.3.name: "ProductDefaultSortingCustomValue"
      param.3.required: false
      param.4.name: "ProductDefaultSortingDirection"
      param.4.required: true
      webform-id: "RegFormUpdateProductPreferences"
      param.1.rule: ""
      param.2.rule: ""
      param.3.rule: ""
      param.4.rule: ""
    bindings:
      WebForm: "RegFormUpdateProductPreferences"
  - id: "CreateWebForm2"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "SubCategoryDefaultSortingAttribute"
      param.1.required: true
      param.2.name: "SubCategoryDefaultSortingCustomValue"
      param.2.required: false
      param.3.name: "SubCategoryDefaultSortingDirection"
      param.3.required: true
      param.4.name: "SubCategoryDefaultSortingStandardValue"
      param.4.required: false
      webform-id: "RegFormUpdateSubCategoryPreferences"
      param.1.rule: ""
      param.2.rule: ""
      param.3.rule: ""
      param.4.rule: ""
    bindings:
      WebForm: "RegFormUpdateSubCategoryPreferences"
  - id: "CreateWebForm3"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "CatalogDefaultSortingAttribute"
      param.1.required: true
      param.2.name: "CatalogDefaultSortingCustomValue"
      param.2.required: false
      param.3.name: "CatalogDefaultSortingDirection"
      param.3.required: true
      param.4.name: "CatalogDefaultSortingStandardValue"
      param.4.required: false
      webform-id: "RegFormUpdateCatalogPreferences"
      param.1.rule: ""
      param.2.rule: ""
      param.3.rule: ""
      param.4.rule: ""
    bindings:
      WebForm: "RegFormUpdateCatalogPreferences"
  - id: "Decision1"
    type: "decision"
    condition: "ProductDefaultSortingAttribute"
  - id: "Decision2"
    type: "decision"
    condition: "SubCategoryDefaultSortingAttribute"
  - id: "Decision3"
    type: "decision"
    condition: "CatalogDefaultSortingAttribute"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelSortingPreferences_52-UpdateProductPreferences"
      OutValue_1: "ViewChannelSortingPreferences_52-UpdateSubCategoryPreferences"
      OutValue_2: "ViewChannelSortingPreferences_52-UpdateCatalogPreferences"
    bindings:
      Key_0: "updateProductPreferences"
      SelectionKey: "JumpTarget"
      Key_1: "updateSubCategoryPreferences"
      Key_2: "updateCatalogPreferences"
  - id: "End1"
    type: "end"
    strict: false
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "RegFormUpdateProductPreferences"
    bindings:
      WebForm: "RegFormUpdateProductPreferences"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "RegFormUpdateSubCategoryPreferences"
    bindings:
      WebForm: "RegFormUpdateSubCategoryPreferences"
  - id: "GetWebForm3"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "RegFormUpdateCatalogPreferences"
    bindings:
      WebForm: "RegFormUpdateCatalogPreferences"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewChannelSortingPreferences_52-Start"
  - id: "Jump3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump4"
    type: "jump"
    ref: "ViewChannelSortingPreferences_52-Start"
  - id: "Jump5"
    type: "jump"
    ref: "ViewChannelSortingPreferences_52-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "ChannelRepository:Domain"
      OutValue_1: "PreferenceDomain"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "RegFormUpdateProductPreferences_ProductDefaultSortingAttribute"
      InValue_2: "RegFormUpdateProductPreferences_ProductDefaultSortingDirection"
      InValue_3: "RegFormUpdateProductPreferences_ProductDefaultSortingStandardValue"
      InValue_4: "RegFormUpdateProductPreferences_ProductDefaultSortingCustomValue"
      OutValue_1: "ProductDefaultSortingAttribute"
      OutValue_2: "ProductDefaultSortingDirection"
      OutValue_3: "ProductDefaultSortingStandardValue"
      OutValue_4: "ProductDefaultSortingCustomValue"
      InValue_5: "RegFormUpdateProductPreferences_ProductSortingCustomValueType"
      OutValue_5: "ProductDefaultSortingCustomValueType"
      InValue_6: "RegFormUpdateProductPreferences_ProductSortingCustomLocalizableFlag"
      OutValue_6: "ProductSortingCustomLocalizableFlag"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "RegFormUpdateSubCategoryPreferences_SubCategoryDefaultSortingAttribute"
      InValue_2: "RegFormUpdateSubCategoryPreferences_SubCategoryDefaultSortingDirection"
      InValue_3: "RegFormUpdateSubCategoryPreferences_SubCategoryDefaultSortingStandardValue"
      InValue_4: "RegFormUpdateSubCategoryPreferences_SubCategoryDefaultSortingCustomValue"
      OutValue_1: "SubCategoryDefaultSortingAttribute"
      OutValue_2: "SubCategoryDefaultSortingDirection"
      OutValue_3: "SubCategoryDefaultSortingStandardValue"
      OutValue_4: "SubCategoryDefaultSortingCustomValue"
      InValue_5: "RegFormUpdateSubCategoryPreferences_SubCategorySortingCustomValueType"
      OutValue_5: "SubCategoryDefaultSortingCustomValueType"
      InValue_6: "RegFormUpdateSubCategoryPreferences_SubCategorySortingCustomLocalizableFlag"
      OutValue_6: "SubCategorySortingCustomLocalizableFlag"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "RegFormUpdateCatalogPreferences_CatalogDefaultSortingAttribute"
      InValue_2: "RegFormUpdateCatalogPreferences_CatalogDefaultSortingDirection"
      InValue_3: "RegFormUpdateCatalogPreferences_CatalogDefaultSortingStandardValue"
      InValue_4: "RegFormUpdateCatalogPreferences_CatalogDefaultSortingCustomValue"
      OutValue_1: "CatalogDefaultSortingAttribute"
      OutValue_2: "CatalogDefaultSortingDirection"
      OutValue_3: "CatalogDefaultSortingStandardValue"
      OutValue_4: "CatalogDefaultSortingCustomValue"
      InValue_5: "RegFormUpdateCatalogPreferences_CatalogSortingCustomValueType"
      OutValue_5: "CatalogDefaultSortingCustomValueType"
      InValue_6: "RegFormUpdateCatalogPreferences_CatalogSortingCustomLocalizableFlag"
      OutValue_6: "CatalogSortingCustomLocalizableFlag"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "channel/ChannelSortingPreferences_52"
  - id: "SetDictionaryValue9"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewChannelSortingPreferences_52-Start"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "RegFormUpdateProductPreferences"
    bindings:
      WebForm: "RegFormUpdateProductPreferences"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "RegFormUpdateSubCategoryPreferences"
    bindings:
      WebForm: "RegFormUpdateSubCategoryPreferences"
  - id: "UpdateWebForm3"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "RegFormUpdateCatalogPreferences"
    bindings:
      WebForm: "RegFormUpdateCatalogPreferences"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "RegFormUpdateProductPreferences"
  - id: "ValidateWebForm2"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "RegFormUpdateSubCategoryPreferences"
  - id: "ValidateWebForm3"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "RegFormUpdateCatalogPreferences"

links:
  - from: "CreateWebForm1"
    via: "next"
    to: "CreateWebForm2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "ValidateWebForm2"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "Call4"
    via: "ERROR"
    to: "Join1"
    into: "in2"
  - from: "Call4"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "CheckForEmptyString1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join2"
    into: "in1"
  - from: "CheckForEmptyString1"
    via: "next"
    to: "Join2"
    into: "in3"
  - from: "CheckForEmptyString3"
    via: "error"
    to: "JoinNode4"
    into: "in3"
  - from: "CheckForEmptyString1"
    via: "error"
    to: "Join5"
    into: "in2"
  - from: "Start2"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "SetDictionaryValue9"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue9"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "Join4"
    into: "in2"
  - from: "GetWebForm3"
    via: "next"
    to: "UpdateWebForm3"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "GetWebForm2"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "UpdateWebForm2"
    via: "next"
    to: "ValidateWebForm2"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "ValidateWebForm2"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetWebForm2"
    via: "error"
    to: "Join4"
    into: "in1"
  - from: "Call1"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "CheckForEmptyString2"
    into: "in"
  - from: "CheckForEmptyString2"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "CheckForEmptyString2"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "Decision2"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Call7"
    via: "ERROR"
    to: "Join1"
    into: "in1"
  - from: "Call7"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "GetWebForm3"
    into: "in"
  - from: "UpdateWebForm3"
    via: "next"
    to: "ValidateWebForm3"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "ValidateWebForm3"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "CheckForEmptyString3"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "Decision3"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "StartNode4"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "CheckForEmptyString3"
    into: "in"
  - from: "ValidateWebForm1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "CreateWebForm2"
    via: "next"
    to: "CreateWebForm3"
    into: "in"
  - from: "ValidateWebForm1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "CreateWebForm3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "ValidateWebForm3"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetWebForm3"
    via: "error"
    to: "Join4"
    into: "in1"
  - from: "Call10"
    via: "ERROR"
    to: "Join1"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
