flow: "ViewProductEditingPreferences"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "CallNode2"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "ProductShortDescriptionEditMode"
      param.1.required: false
      param.1.rule: ""
      param.2.name: "ProductLongDescriptionEditMode"
      param.2.required: false
      webform-id: "ProductEditingForm"
      param.2.rule: ""
    bindings:
      WebForm: "ProductEditingForm"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "String"
      DefaultPreferenceKey: "ProductLongDescriptionEditMode"
    bindings:
      PreferenceDomain: "Organization:Domain"
      PreferenceStringValue: "ProductLongDescriptionEditMode"
      PreferenceKey: "ProductLongDescriptionEditMode"
  - id: "GetDomainPreference2"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "String"
      DefaultPreferenceKey: "ProductShortDescriptionEditMode"
    bindings:
      PreferenceDomain: "Organization:Domain"
      PreferenceKey: "ProductShortDescriptionEditMode"
      PreferenceStringValue: "ProductShortDescriptionEditMode"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "ProductEditingForm"
    bindings:
      WebForm: "ProductEditingForm"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"plaintext\""
      OutValue_1: "ProductLongDescriptionEditMode"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "ProductShortDescriptionEditMode"
      InValue_1: "\"plaintext\""
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "ProductShortDescriptionEditMode"
      InValue_1: "ProductEditingForm_ProductShortDescriptionEditMode"
      InValue_2: "ProductEditingForm_ProductLongDescriptionEditMode"
      OutValue_2: "ProductLongDescriptionEditMode"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "product/ProductEditingPreferences"
      SelectedMenuItem: "Preferences"
  - id: "SetDomainPreference1"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductShortDescriptionEditMode"
      DefaultPreferenceValue: "\"plaintext\""
      Type: "String"
    bindings:
      PreferenceDomain: "Organization:Domain"
      PreferenceStringValue: "ProductShortDescriptionEditMode"
  - id: "SetDomainPreference2"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductLongDescriptionEditMode"
      DefaultPreferenceValue: "\"plaintext\""
      Type: "String"
    bindings:
      PreferenceDomain: "Organization:Domain"
      PreferenceStringValue: "ProductLongDescriptionEditMode"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "ProductEditingForm"
    bindings:
      WebForm: "ProductEditingForm"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "ProductEditingForm"

links:
  - from: "ValidateWebForm1"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "SetDomainPreference1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "SetDomainPreference2"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "CreateWebForm1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetWebForm1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "ValidateWebForm1"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "SetDomainPreference1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "JoinNode4"
    via: "next"
    to: "SetDomainPreference2"
    into: "in"
  - from: "SetDomainPreference2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "KeyMapper3"
    via: "next"
    to: "SetDomainPreference1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode6"
    into: "in2"
  - from: "GetDomainPreference1"
    via: "error"
    to: "KeyMapper1"
    into: "in"
  - from: "GetDomainPreference1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "GetDomainPreference2"
    into: "in"
  - from: "GetDomainPreference2"
    via: "error"
    to: "KeyMapper2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "GetDomainPreference2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "GetWebForm1"
    into: "in"
