flow: "ViewProductCategoryMapping_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call10"
    type: "call"
    ref: "ProcessProductDataMappingRule-DeleteRuleConstruct"
  - id: "Call2"
    type: "call"
    ref: "ViewProductCategoryMapping_52-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ViewProductCategoryMapping_52-Prefix"
  - id: "Call5"
    type: "call"
    ref: "ProcessProductDataMappingRule-CreateRuleConstruct"
  - id: "Decision1"
    type: "decision"
    condition: "mappingEnabled"
  - id: "Decision2"
    type: "decision"
    condition: "ProductDataMappingRuleID"
  - id: "Decision3"
    type: "decision"
    condition: "ProductDataMappingRuleID"
  - id: "End1"
    type: "end"
  - id: "GetProductDataMappingRuleSet1"
    type: "pipelet"
    ref: "GetProductDataMappingRuleSet"
    bindings:
      DeclaringDomain: "CurrentChannel:RepositoryDomain"
      ProvidingDomain: "ProvidingRepository:RepositoryDomain"
  - id: "GetProductDataMappingRules1"
    type: "pipelet"
    ref: "GetProductDataMappingRules"
    config:
      DefaultTypeCode: 3
    bindings:
      DeclaringDomain: "ProductDataMappingRuleSet:DeclaringDomain"
      ProvidingDomain: "ProductDataMappingRuleSet:ProvidingDomain"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "ProvidingRepository"
      UUID: "ProviderID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewProductCategoryMapping_52-Start"
  - id: "Jump2"
    type: "jump"
    ref: "ViewProductCategoryMapping_52-Start"
  - id: "Jump3"
    type: "jump"
    ref: "ViewProductCategoryMapping_52-Start"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/ProductCategoryMapping_52"

links:
  - from: "Start1"
    via: "next"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Jump2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "GetProductDataMappingRules1"
    into: "in"
  - from: "GetProductDataMappingRules1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Decision1"
    via: "yes"
    to: "Decision3"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Call5"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "Jump3"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "GetProductDataMappingRuleSet1"
    into: "in"
  - from: "GetProductDataMappingRuleSet1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Decision2"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "Decision2"
    via: "yes"
    to: "Call10"
    into: "in"
