flow: "ViewEditingActions"
kind: "view"

entries:
  - id: "StartNode1"
    name: "SecuredMoveAssignment"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "GetAssignmentByUUID"
    mode: "private"
    strict: true
    inputs:
      - key: "AssignmentUUID"
        type: "java.lang.String"
        required: true
  - id: "StartNode20"
    name: "SecuredMoveDown"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode21"
    name: "SecuredMoveUp"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode23"
    name: "SecuredLockPagelet"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode29"
    name: "SecuredUnlockPagelet"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessPageletAssignments-HandlePosition"
    bindings:
      Domain: "ContentRepository:RepositoryDomain"
      Position: "TargetAssignment:Position"
  - id: "CallNode2"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode21"
    type: "call"
    ref: "ProcessPageletAssignments-GetPageletAssignments"
    bindings:
      Domain: "ContentRepository:RepositoryDomain"
      ToObject: "Assignment:To"
      Pagelet: "null"
  - id: "CallNode3"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode37"
    type: "call"
    ref: "ProcessPageletLock-Lock"
    bindings:
      LockingDomain: "ContentRepository:RepositoryDomain"
      PreferenceDomain: "ContentRepository:RepositoryDomain"
      User: "CurrentUser"
  - id: "CallNode38"
    type: "call"
    ref: "ProcessPageletLock-Unlock"
    bindings:
      LockingDomain: "ContentRepository:RepositoryDomain"
      User: "CurrentUser"
  - id: "CallNode4"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessPageletAssignments-GetPageletAssignments"
    bindings:
      Domain: "ContentRepository:RepositoryDomain"
      ToObject: "Assignment:To"
      Pagelet: "null"
  - id: "CallNode6"
    type: "call"
    ref: "ViewEditingActions-GetAssignmentByUUID"
    bindings:
      AssignmentUUID: "TargetAssignmentUUID"
      Assignment: "TargetAssignment"
  - id: "CallNode7"
    type: "call"
    ref: "ViewEditingActions-GetAssignmentByUUID"
  - id: "DecisionNode14"
    type: "decision"
    condition: "PageletUUID"
  - id: "DecisionNode3"
    type: "decision"
    condition: "AssignmentUUID"
  - id: "DecisionNode4"
    type: "decision"
    condition: "PageletEntryPointAssignment"
  - id: "DecisionNode5"
    type: "decision"
    condition: "Assignment:To:UUID"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "Assignment"
        type: "com.intershop.component.pmc.capi.pagelet.assignment.PageletAssignment"
        guaranteed: true
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "GetAssignmentByUUID1"
    type: "pipelet"
    ref: "GetAssignmentByUUID"
    config:
      DefaultAssignmentLookup: "com.intershop.component.pmc.internal.pagelet.SlotPageletAssignmentLookup"
    bindings:
      UUID: "AssignmentUUID"
  - id: "GetAssignmentByUUID4"
    type: "pipelet"
    ref: "GetAssignmentByUUID"
    config:
      DefaultAssignmentLookup: "com.intershop.component.pmc.internal.pagelet.entrypoint.assignment.PageletPageletEntryPointAssignmentLookup"
    bindings:
      UUID: "AssignmentUUID"
  - id: "GetAssignmentByUUID5"
    type: "pipelet"
    ref: "GetAssignmentByUUID"
    config:
      DefaultAssignmentLookup: "com.intershop.component.pmc.internal.pagelet.template.assignment.PageletPlaceholderAssignmentLookup"
    bindings:
      UUID: "AssignmentUUID"
  - id: "GetAssignmentByUUID6"
    type: "pipelet"
    ref: "GetAssignmentByUUID"
    config:
      DefaultAssignmentLookup: "com.intershop.component.pmc.internal.pagelet.entrypoint.assignment.PageletPageletEntryPointAssignmentLookup"
    bindings:
      UUID: "AssignmentUUID"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Request Locale"
  - id: "GetPageletByUUID2"
    type: "pipelet"
    ref: "GetPageletByUUID"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      UUID: "ContentRepositoryUUID"
      Repository: "ContentRepository"
  - id: "GetRepositoryByUUID3"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      UUID: "ContentRepositoryUUID"
      Repository: "ContentRepository"
  - id: "GetSlotPageletAssignmentByUUID1"
    type: "pipelet"
    ref: "GetSlotPageletAssignmentByUUID"
    bindings:
      SlotPageletAssignmentUUID: "AssignmentUUID"
      SlotPageletAssignment: "Assignment"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "InteractionNode3"
    type: "interaction"
  - id: "InteractionNode4"
    type: "interaction"
  - id: "InteractionNode5"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode28"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode52"
    type: "join"
  - id: "JoinNode53"
    type: "join"
  - id: "JoinNode54"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "MovePositionable3"
    type: "pipelet"
    ref: "MovePositionable"
    config:
      DefaultMoveDirection: "Up"
    bindings:
      PositionableObject: "Assignment"
      SortedPositionables: "Assignments"
  - id: "MovePositionable4"
    type: "pipelet"
    ref: "MovePositionable"
    config:
      DefaultMoveDirection: "Down"
    bindings:
      PositionableObject: "Assignment"
      SortedPositionables: "Assignments"

links:
  - from: "CallNode37"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "GetAssignmentByUUID1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "GetAssignmentByUUID6"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "CallNode4"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "MovePositionable4"
    into: "in"
  - from: "CallNode21"
    via: "next"
    to: "MovePositionable3"
    into: "in"
  - from: "MovePositionable3"
    via: "next"
    to: "InteractionNode3"
    into: "in"
  - from: "MovePositionable4"
    via: "next"
    to: "InteractionNode4"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "GetAssignmentByUUID6"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "GetAssignmentByUUID1"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode38"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "GetSlotPageletAssignmentByUUID1"
    via: "next"
    to: "JoinNode53"
    into: "in1"
  - from: "GetAssignmentByUUID4"
    via: "error"
    to: "JoinNode52"
    into: "in1"
  - from: "DecisionNode14"
    via: "no"
    to: "JoinNode1"
    into: "in1"
  - from: "GetAssignmentByUUID5"
    via: "next"
    to: "JoinNode54"
    into: "in1"
  - from: "GetAssignmentByUUID4"
    via: "next"
    to: "JoinNode52"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "GetAssignmentByUUID6"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "GetAssignmentByUUID5"
    via: "error"
    to: "GetAssignmentByUUID4"
    into: "in"
  - from: "GetPageletByUUID2"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode23"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetSlotPageletAssignmentByUUID1"
    via: "error"
    to: "GetAssignmentByUUID5"
    into: "in"
  - from: "GetRepositoryByUUID3"
    via: "next"
    to: "DecisionNode14"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode28"
    into: "in1"
  - from: "GetPageletByUUID2"
    via: "next"
    to: "JoinNode28"
    into: "in1"
  - from: "JoinNode52"
    via: "next"
    to: "JoinNode54"
    into: "in1"
  - from: "JoinNode54"
    via: "next"
    to: "JoinNode53"
    into: "in1"
  - from: "DecisionNode3"
    via: "yes"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode53"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "CallNode21"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetSlotPageletAssignmentByUUID1"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode6"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "CallNode11"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "DecisionNode14"
    via: "yes"
    to: "GetPageletByUUID2"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "StartNode29"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "JoinNode28"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode3"
    via: "no"
    to: "DecisionNode4"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode37"
    into: "in"
  - from: "GetAssignmentByUUID1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "CallNode38"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "InteractionNode5"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode9"
    into: "in1"
  - from: "GetLocale2"
    via: "next"
    to: "GetRepositoryByUUID3"
    into: "in"
  - from: "StartNode21"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "StartNode20"
    via: "next"
    to: "CallNode4"
    into: "in"
