flow: "ViewParentCategory"
kind: "view"

entries:
  - id: "Start1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start10"
    name: "Tree"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Cancel"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Assign"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "Collapse"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "Expand"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CheckForEmptyString1"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "CurrentCategoryID"
  - id: "CheckForEmptyString2"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "CurrentCategoryID"
  - id: "CheckForEmptyString3"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "CurrentCategoryID"
  - id: "CheckForEmptyString4"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "CurrentCategoryID"
  - id: "Decision2"
    type: "decision"
    condition: "SelectedCategoryUUID"
  - id: "DetermineCatalogCategoriesPath1"
    type: "pipelet"
    ref: "DetermineCatalogCategoriesPath"
  - id: "DetermineCatalogCategoriesPath2"
    type: "pipelet"
    ref: "DetermineCatalogCategoriesPath"
    bindings:
      CatalogCategoryID: "ParentCategoryID"
  - id: "DetermineCatalogCategoriesPath3"
    type: "pipelet"
    ref: "DetermineCatalogCategoriesPath"
    bindings:
      CatalogCategoryID: "xxxxxx"
      Category: "ParentCategory"
  - id: "DetermineCatalogCategoriesPath4"
    type: "pipelet"
    ref: "DetermineCatalogCategoriesPath"
    bindings:
      CatalogCategoryID: "ParentCategoryID"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewParentCategory-Collapse"
      OutValue_1: "ViewParentCategory-Expand"
      OutValue_2: "ViewParentCategory-Cancel"
      OutValue_3: "ViewParentCategory-Assign"
    bindings:
      Key_0: "collpase"
      Key_1: "expand"
      Key_2: "cancel"
      Key_3: "assign"
      SelectionKey: "JumpTarget"
  - id: "ExchangeSessionObject10"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      LoadObject: "ExpandedCategoriesMap"
  - id: "ExchangeSessionObject11"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      SaveObject: "ExpandedCategoriesMap"
  - id: "ExchangeSessionObject9"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      LoadObject: "ExpandedCategoriesMap"
  - id: "GetCatalog1"
    type: "pipelet"
    ref: "GetCatalog"
  - id: "GetCatalog2"
    type: "pipelet"
    ref: "GetCatalog"
  - id: "GetCatalogByCategory1"
    type: "pipelet"
    ref: "GetCatalogByCategory"
    bindings:
      CatalogCategory: "Category"
  - id: "GetCatalogByCategory2"
    type: "pipelet"
    ref: "GetCatalogByCategory"
    bindings:
      CatalogCategory: "ParentCategory"
  - id: "GetCategoryByUUID1"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "ParentCategoryID"
  - id: "GetCategoryByUUID2"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "CurrentCategoryID"
      Category: "CurrentCategory"
  - id: "GetCategoryByUUID3"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "CurrentCategoryID"
  - id: "GetCategoryByUUID4"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "SelectedCategoryUUID"
      Category: "SelectedParentCategory"
  - id: "GetCategoryByUUID5"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "ParentCategoryID"
      Category: "ParentCategory"
  - id: "GetCategoryByUUID6"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "CurrentCategoryID"
      Category: "CurrentCategory"
  - id: "GetCategoryByUUID7"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "CurrentCategoryID"
      Category: "CurrentCategory"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "RegFormAddCategory"
    bindings:
      WebForm: "RegFormAddCategory"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "RegFormAddCategory"
    bindings:
      WebForm: "RegFormAddCategory"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "InteractionEnd4"
    type: "interaction"
  - id: "InteractionEnd5"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "JoinNode0"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewParentCategory-Tree"
  - id: "Jump10"
    type: "jump"
    ref: "ViewCatalogList-ListAll"
  - id: "Jump11"
    type: "jump"
    ref: "ViewCatalogList-ListAll"
  - id: "Jump12"
    type: "jump"
    ref: "ViewCatalogList-ListAll"
  - id: "Jump13"
    type: "jump"
    ref: "ViewCatalogList-ListAll"
  - id: "Jump2"
    type: "jump"
    ref: "ViewCatalogList-ListAll"
  - id: "Jump3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump4"
    type: "jump"
    ref: "ViewCatalogList-ListAll"
  - id: "Jump5"
    type: "jump"
    ref: "ViewCatalogList-ListAll"
  - id: "Jump7"
    type: "jump"
    ref: "ViewParentCategory-Tree"
  - id: "Jump8"
    type: "jump"
    ref: "ViewCatalogList-ListAll"
  - id: "Jump9"
    type: "jump"
    ref: "ViewCatalogList-ListAll"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CatalogCategoryID"
      OutValue_1: "CurrentCategoryID"
  - id: "Loop1"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Catalogs"
      WorkingTemplate: "category/CatalogCategory"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Catalogs"
      WorkingTemplate: "category/NewCatalogCategory"
  - id: "PrepareApplicationView4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Catalogs"
      WorkingTemplate: "category/ParentCategoryTree"
  - id: "PrepareApplicationView5"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Catalogs"
      WorkingTemplate: "category/ParentCategoryTree"
  - id: "PrepareApplicationView6"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Catalogs"
      WorkingTemplate: "category/ParentCategoryTree"
  - id: "SetDictionaryValue0"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewCatalogList-ListAll"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ParentBrowsingCancelled"
      Value: "True"
  - id: "UpdateMapping1"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Remove"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "CategoryUUID"
      Value: "CategoryUUID"
  - id: "UpdateMapping2"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "CategoryUUID"
      Value: "CategoryUUID"
  - id: "UpdateMapping3"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "Parent:Parent:Parent:UUID"
      Value: "Parent:Parent:Parent:UUID"
      OutMap: "ExpandedCategoriesMap"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "RegFormAddCategory"
    bindings:
      WebForm: "RegFormAddCategory"

links:
  - from: "CheckForEmptyString1"
    via: "error"
    to: "Join2"
    into: "in1"
  - from: "CheckForEmptyString1"
    via: "next"
    to: "GetCategoryByUUID2"
    into: "in"
  - from: "CheckForEmptyString2"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "CheckForEmptyString2"
    via: "next"
    to: "GetCategoryByUUID6"
    into: "in"
  - from: "CheckForEmptyString3"
    via: "error"
    to: "Join6"
    into: "in1"
  - from: "CheckForEmptyString3"
    via: "next"
    to: "GetCategoryByUUID7"
    into: "in"
  - from: "CheckForEmptyString4"
    via: "error"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "CheckForEmptyString4"
    via: "next"
    to: "GetCategoryByUUID3"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Jump7"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "GetCategoryByUUID4"
    into: "in"
  - from: "DetermineCatalogCategoriesPath1"
    via: "next"
    to: "CheckForEmptyString1"
    into: "in"
  - from: "DetermineCatalogCategoriesPath2"
    via: "next"
    to: "CheckForEmptyString2"
    into: "in"
  - from: "DetermineCatalogCategoriesPath3"
    via: "next"
    to: "CheckForEmptyString4"
    into: "in"
  - from: "DetermineCatalogCategoriesPath4"
    via: "next"
    to: "CheckForEmptyString3"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue0"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "ExchangeSessionObject10"
    via: "next"
    to: "UpdateMapping2"
    into: "in"
  - from: "ExchangeSessionObject11"
    via: "next"
    to: "PrepareApplicationView6"
    into: "in"
  - from: "ExchangeSessionObject9"
    via: "next"
    to: "UpdateMapping1"
    into: "in"
  - from: "GetCatalog1"
    via: "error"
    to: "Jump9"
    into: "in"
  - from: "GetCatalog1"
    via: "next"
    to: "ExchangeSessionObject10"
    into: "in"
  - from: "GetCatalog2"
    via: "error"
    to: "Jump10"
    into: "in"
  - from: "GetCatalog2"
    via: "next"
    to: "ExchangeSessionObject9"
    into: "in"
  - from: "GetCatalogByCategory1"
    via: "error"
    to: "Jump13"
    into: "in"
  - from: "GetCatalogByCategory1"
    via: "next"
    to: "DetermineCatalogCategoriesPath1"
    into: "in"
  - from: "GetCatalogByCategory2"
    via: "error"
    to: "Join9"
    into: "in1"
  - from: "GetCatalogByCategory2"
    via: "next"
    to: "DetermineCatalogCategoriesPath3"
    into: "in"
  - from: "GetCategoryByUUID1"
    via: "error"
    to: "Jump12"
    into: "in"
  - from: "GetCategoryByUUID1"
    via: "next"
    to: "GetCatalogByCategory1"
    into: "in"
  - from: "GetCategoryByUUID2"
    via: "error"
    to: "Jump11"
    into: "in"
  - from: "GetCategoryByUUID2"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "GetCategoryByUUID3"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "GetCategoryByUUID3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "GetCategoryByUUID4"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "GetCategoryByUUID4"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "GetCategoryByUUID5"
    via: "error"
    to: "Join7"
    into: "in1"
  - from: "GetCategoryByUUID5"
    via: "next"
    to: "GetCatalogByCategory2"
    into: "in"
  - from: "GetCategoryByUUID6"
    via: "error"
    to: "Jump8"
    into: "in"
  - from: "GetCategoryByUUID6"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "GetCategoryByUUID7"
    via: "error"
    to: "Jump5"
    into: "in"
  - from: "GetCategoryByUUID7"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "GetLocale1"
    via: "next"
    to: "GetCategoryByUUID5"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "GetWebForm1"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "GetWebForm2"
    via: "error"
    to: "Jump2"
    into: "in"
  - from: "GetWebForm2"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "Join4"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "GetCatalog1"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "GetCatalog2"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "Join8"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "Join9"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "JoinNode0"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "UpdateMapping3"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "ExchangeSessionObject11"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "PrepareApplicationView4"
    via: "next"
    to: "InteractionEnd4"
    into: "in"
  - from: "PrepareApplicationView5"
    via: "next"
    to: "InteractionEnd5"
    into: "in"
  - from: "PrepareApplicationView6"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "SetDictionaryValue0"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "Start10"
    via: "next"
    to: "GetCategoryByUUID1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "DetermineCatalogCategoriesPath4"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "DetermineCatalogCategoriesPath2"
    into: "in"
  - from: "UpdateMapping1"
    via: "next"
    to: "PrepareApplicationView4"
    into: "in"
  - from: "UpdateMapping2"
    via: "next"
    to: "PrepareApplicationView5"
    into: "in"
  - from: "UpdateMapping3"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "UpdateWebForm1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
