flow: "ViewBrandingPackageList_32"
kind: "view"

entries:
  - id: "Start1"
    name: "Back"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start14"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start16"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "ShowSelection"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewBrandingPackageList_32-Prefix"
  - id: "Call17"
    type: "call"
    ref: "ViewBrandingPackageList_32-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call4"
    type: "call"
    ref: "ViewBrandingPackageList_32-Prefix"
  - id: "Call5"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call6"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call7"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewBrandingPackage_32-New"
      OutValue_1: "ViewBrandingPackageList_32-Delete"
      OutValue_2: "ViewBrandingPackageList_32-Back"
      OutValue_3: "ViewBrandingPackageList_32-ShowSelection"
      OutValue_4: "ViewBrandingPackageList_32-ListAll"
    bindings:
      Key_0: "newPackage"
      Key_1: "deletePackage"
      Key_2: "backToList"
      Key_3: "confirmDeletePackage"
      Key_4: "cancelDeletion"
      SelectionKey: "JumpTarget"
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "GetBrandingPackage1"
    type: "pipelet"
    ref: "GetBrandingPackage"
  - id: "GetBrandingPackages1"
    type: "pipelet"
    ref: "GetBrandingPackages"
    bindings:
      Domain: "Organization:Domain"
  - id: "GetOrganization1"
    type: "pipelet"
    ref: "GetOrganization"
    config:
      Source: "PipelineDictionary"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewOrganizationList_32-Paging"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump5"
    type: "jump"
    ref: "ViewBrandingPackageList_32-ListAll"
  - id: "Loop1"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelORG"
      WorkingTemplate: "branding/BrandingPackageList_32"
  - id: "RemoveBrandingPackage1"
    type: "pipelet"
    ref: "RemoveBrandingPackage"

links:
  - from: "Start3"
    via: "next"
    to: "Call17"
    into: "in"
  - from: "GetBrandingPackage1"
    via: "next"
    to: "RemoveBrandingPackage1"
    into: "in"
  - from: "RemoveBrandingPackage1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "GetBrandingPackage1"
    via: "error"
    to: "Join5"
    into: "in3"
  - from: "Join5"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Loop1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Call5"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "Join1"
    via: "next"
    to: "GetBrandingPackages1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "GetOrganization1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Start14"
    via: "next"
    to: "GetOrganization1"
    into: "in"
  - from: "GetOrganization1"
    via: "error"
    to: "End3"
    into: "in"
  - from: "Call17"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "GetBrandingPackages1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Start16"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetBrandingPackage1"
    into: "in"
