flow: "ViewEmailSignup"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Subscribe"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessNewsletter-Subscribe"
    bindings:
      Domain: "CurrentOrganization:OwningDomain"
      Email: "EmailSignupForm:Email:Value"
      Locale: "CurrentRequest:Locale"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "EmailSignupForm"
      FormResource: "EmailSignup"
    bindings:
      FormAlias: "null"
      FormName: "null"
      FormResource: "null"
      Form: "EmailSignupForm"
  - id: "CreateForm2"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "EmailSignupForm"
      FormResource: "EmailSignup"
    bindings:
      FormAlias: "null"
      FormName: "null"
      FormResource: "null"
      Form: "EmailSignupForm"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewEmailSignup-Subscribe"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "signup"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "EmailSignupForm"

links:
  - from: "StartNode1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CreateForm2"
    into: "in"
  - from: "ValidateForm1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "JoinNode1"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "CallNode1"
    via: "ERROR"
    to: "JoinNode1"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "CreateForm2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CreateForm1"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "ValidateForm1"
    via: "next"
    to: "CallNode1"
    into: "in"
