flow: "ViewProductExport"
kind: "view"

entries:
  - id: "Start1"
    name: "Search"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "ParametricSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "SelectConfiguration"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Back"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Export"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "OverwriteFile"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "CancelOverwriteFile"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "Call2"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "Call3"
    type: "call"
    ref: "ProcessImpexJob-Create"
  - id: "Call4"
    type: "call"
    ref: "ViewParametricSearch-SimpleMasterProductSearch"
  - id: "Call5"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call6"
    type: "call"
    ref: "ViewParametricSearch-SearchMasterProduct"
  - id: "Call7"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call8"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode1"
    type: "call"
    ref: "ValidateWebForms-WFAdvancedSearch"
  - id: "CallNode2"
    type: "call"
    ref: "ValidateWebForms-WFSimpleSearch"
  - id: "CallNode3"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessImpexJob-IsFilenameTaken"
    bindings:
      Filename: "ProductExportForm:ExportFile:Value"
      Domain: "OrganizationDomain"
  - id: "CallNode5"
    type: "call"
    ref: "ViewProductList-GetServiceTypeCategories"
  - id: "CallNode52"
    type: "call"
    ref: "ViewProductList-PrepareCustomAttributesSearchMask"
    bindings:
      Domain: "OrganizationDomain"
      Locale: "CurrentRequest:Locale"
  - id: "CreateProductIdentifierLookupHelper1"
    type: "pipelet"
    ref: "CreateProductIdentifierLookupHelper"
    config:
      LookupType: "ProductDomainLookup"
    bindings:
      ProductDomain: "CurrentMasterRepository:RepositoryDomain"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "ExportFile"
      param.1.required: true
      param.1.rule: "^[^.\\\\/:*?<>|\\s]([^\\\\/:*?<>|\\s]*[^.\\\\/:*?<>|\\s])?$"
      param.2.required: false
      webform-id: "ProductExportForm"
    bindings:
      WebForm: "ProductExportForm"
  - id: "Decision1"
    type: "decision"
    condition: "ProductExportPageLocator"
  - id: "Decision2"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision3"
    type: "decision"
    condition: "ExportSearchResult"
  - id: "GetCurrencies1"
    type: "pipelet"
    ref: "GetCurrencies"
    config:
      Method: "Active Currencies"
    bindings:
      Domain: "OrganizationDomain"
  - id: "GetLabels1"
    type: "pipelet"
    ref: "GetLabels"
    bindings:
      Domain: "OrganizationDomain"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ProductExportPageLocator"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocator: "ProductExportPageLocator"
  - id: "GetPageLocator2"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ProductExportPageLocator"
      RestorePageLocatorDictionary: "True"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      PageableID: "ProductExportPageLocator:PageableID"
      Pageable: "Products"
  - id: "GetProducts2"
    type: "pipelet"
    ref: "GetProducts"
    bindings:
      ProductIDIterator: "UUIDIterator"
      ProductDomain: "CurrentMasterRepository:RepositoryDomain"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "ProductExportForm"
    bindings:
      WebForm: "ProductExportForm"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "ProductExportForm"
    bindings:
      WebForm: "ProductExportForm"
  - id: "GetWebForm3"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "ProductExportForm"
    bindings:
      WebForm: "ProductExportForm"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewProductExport-Search"
  - id: "Jump2"
    type: "jump"
    ref: "ViewProductExport-Search"
  - id: "Jump3"
    type: "jump"
    ref: "ViewCatalogImpex-Status"
  - id: "Jump5"
    type: "jump"
  - id: "Jump6"
    type: "jump"
    ref: "ViewCatalogImpex-Status"
  - id: "JumpNode2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "\"ProcessProductExport\""
      InValue_2: "\"Export\""
      InValue_4: "\"ProcessCatalogImpex\""
      OutValue_1: "ProcessPipelineName"
      OutValue_2: "ProcessPipelineStartNode"
      OutValue_4: "JobName"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "PageableID"
      InValue_2: "ProductExportForm_ExportFile"
      OutValue_1: "ObjectsID"
      OutValue_2: "SelectedFile"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "Products:ID"
      InValue_2: "ProductExportForm_ExportFile"
      OutValue_1: "ObjectsID"
      OutValue_2: "SelectedFile"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "OrganizationDomain"
      InValue_2: "OrganizationDomain"
      OutValue_1: "ProcessOwningDomain"
      OutValue_2: "ProcessExecutionDomain"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProductExport-Search"
      OutValue_1: "ViewProductExport-ParametricSearch"
      OutValue_2: "ViewProductExport-Paging"
      OutValue_3: "ViewProductExport-SelectConfiguration"
      OutValue_4: "ViewProductExport-Back"
      OutValue_5: "ViewCatalogImpex-Status"
      OutValue_6: "ViewProductExport-Paging"
      OutValue_7: "ViewProductExport-Paging"
      PagingPipeline: "ViewProductExport-Paging"
    bindings:
      Key_0: "findSimple"
      Key_1: "findParametric"
      Key_2: "jumpToList"
      Key_3: "SelectConfiguration"
      Key_4: "Back"
      Key_5: "Cancel"
      Key_6: "Expand"
      Key_7: "Collapse"
      SelectionKey: "JumpTarget"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProductExport-OverwriteFile"
      OutValue_1: "ViewProductExport-CancelOverwriteFile"
      PagingPipeline: "ViewProductExport-Paging"
      OutValue_2: "ViewProductExport-Export"
    bindings:
      Key_0: "Overwrite"
      Key_1: "CancelOverwrite"
      Key_2: "Export"
      SelectionKey: "JumpTarget"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ImportExport"
      WorkingTemplate: "impex/ProductExportSelectProducts"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ImportExport"
      WorkingTemplate: "impex/ProductExportSelectConfiguration"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "SearchType"
      Value: "parametric"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "SearchType"
      Value: "simple"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "FILENAME_ALREADY_IN_USE"
      Value: true
  - id: "SetDictionaryValue5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewCatalogImpex-Status"
      ValueType: "Dictionary Value"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "ProductExportPageLocator:PageNumber"
      Pageable: "Products"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Products"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewProductExport-Paging"
      DefaultPageLocatorName: "ProductExportPageLocator"
    bindings:
      Pageable: "Products"
      PageLocator: "ProductExportPageLocator"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "ProductExportForm"
    bindings:
      WebForm: "ProductExportForm"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "ProductExportForm"
    bindings:
      WebForm: "ProductExportForm"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "ProductExportForm"
  - id: "ValidateWebForm2"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "ProductExportForm"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      LocalizedString: "PageNumber"
      IntegerObject: "PageNumber"

links:
  - from: "Call1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Call4"
    via: "ERROR"
    to: "JoinNode5"
    into: "in1"
  - from: "Call4"
    via: "next"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "GetProducts2"
    into: "in"
  - from: "Call6"
    via: "ERROR"
    to: "JoinNode5"
    into: "in1"
  - from: "Call6"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "CallNode1"
    via: "ERROR"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "CallNode2"
    via: "ERROR"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CreateProductIdentifierLookupHelper1"
    into: "in"
  - from: "CallNode4"
    via: "FILENAME_ALREADY_IN_USE"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "CallNode52"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CreateProductIdentifierLookupHelper1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CreateWebForm1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Decision1"
    via: "no"
    to: "Join1"
    into: "in1"
  - from: "Decision1"
    via: "yes"
    to: "SetPage1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Decision1"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Call5"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "KeyMapper2"
    into: "in"
  - from: "GetCurrencies1"
    via: "next"
    to: "CallNode52"
    into: "in"
  - from: "GetLabels1"
    via: "next"
    to: "GetCurrencies1"
    into: "in"
  - from: "GetPageLocator1"
    via: "error"
    to: "Jump2"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "GetPageLocator2"
    via: "error"
    to: "Jump6"
    into: "in"
  - from: "GetPageLocator2"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "Jump1"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "GetProducts2"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "GetWebForm2"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "GetWebForm2"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "GetWebForm3"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "GetWebForm3"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join4"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "GetLabels1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "KeyMapper3"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "KeyMapper4"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "Pipelet2"
    via: "error"
    to: "SetDictionaryValue5"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "SetDictionaryValue5"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "SetPage1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "SetPage2"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "SetPageLocator1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Start5"
    via: "next"
    to: "GetPageLocator2"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetWebForm3"
    into: "in"
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "UpdateWebForm2"
    via: "next"
    to: "ValidateWebForm2"
    into: "in"
  - from: "ValidateWebForm1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "ValidateWebForm1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "ValidateWebForm2"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "ValidateWebForm2"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage2"
    into: "in"
