flow: "ViewChannelPageLockingPreferences"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "PageletLockTimeout"
      param.1.required: true
      webform-id: "RegFormUpdateDomainPreference"
      param.1.rule: ""
    bindings:
      WebForm: "RegFormUpdateDomainPreference"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "PageletLockTimeout"
      Type: "Integer"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceIntValue: "PageletLockTimeout"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "RegFormUpdateDomainPreference"
    bindings:
      WebForm: "RegFormUpdateDomainPreference"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "PageletLockTimeout"
      DefaultPreferenceValue: 0
      Type: "Integer"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceIntValue: "PageletLockTimeout"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "CalculateInteger"
    config:
      Operand2: 60
      Operation: "*"
    bindings:
      Operand1: "PageletLockTimeout"
      Result: "PageletLockTimeout"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "CalculateInteger"
    config:
      Operand2: 60
      Operation: "/"
    bindings:
      Operand1: "PageletLockTimeout"
      Result: "PageletLockTimeout"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "content/ChannelPageLockingPreferences"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "RegFormUpdateDomainPreference"
    bindings:
      WebForm: "RegFormUpdateDomainPreference"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "RegFormUpdateDomainPreference"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    config:
      MinValue: 0
      MaxValue: 2147483647
    bindings:
      IntegerObject: "PageletLockTimeout"
      LocalizedString: "RegFormUpdateDomainPreference_PageletLockTimeout"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "ValidateWebForm1"
    via: "next"
    to: "VerifyInteger1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "ValidateWebForm1"
    via: "error"
    to: "Join4"
    into: "in2"
  - from: "Join2"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join5"
    into: "in2"
  - from: "Pipelet1"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "Join5"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "GetDomainPreference1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Pipelet3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "GetDomainPreference1"
    via: "error"
    to: "Join2"
    into: "in3"
  - from: "Pipelet2"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "StartNode1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "CreateWebForm1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "Join3"
    into: "in2"
