flow: "ViewShippingImportFiles_52"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode10"
    name: "CopyFile"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode11"
    name: "InternalCopyFile"
    mode: "private"
    strict: true
    inputs:
      - key: "UnitDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
      - key: "TargetDirectory"
        type: "java.lang.String"
        required: true
      - key: "FileName"
        type: "java.lang.String"
        required: true
  - id: "StartNode2"
    name: "DeleteFiles"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "BrowseDirectory"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "InternalUpload"
    mode: "private"
    strict: true
    inputs:
      - key: "UnitDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true
      - key: "TargetDirectory"
        type: "java.lang.String"
        required: true
  - id: "StartNode6"
    name: "Back"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "Upload"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AcquireFileResource1"
    type: "pipelet"
    ref: "AcquireFileResource"
    config:
      DefaultTargetDirectoryPath: "shipping"
      DefaultTargetUnitDirectory: "IMPEX_SRC_DIR"
    bindings:
      TargetFileNames: "UUIDIterator"
      TargetUnitDomain: "ChannelRepository:Domain"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode5"
    type: "call"
    ref: "ViewShippingImportFiles_52-InternalCopyFile"
    bindings:
      TargetDirectory: "\"shipping\""
      UnitDomain: "CurrentChannel:RepositoryDomain"
  - id: "CallNode6"
    type: "call"
    ref: "ViewShippingImportFiles_52-InternalUpload"
    bindings:
      UnitDomain: "CurrentChannel:RepositoryDomain"
      TargetDirectory: "\"shipping\""
  - id: "CheckForExistingFiles2"
    type: "pipelet"
    ref: "CheckForExistingFiles"
    config:
      Recursive: false
      SourceDirectoryPath: "upload"
      SourceUnitDirectory: "IMPEX_DIR"
      TargetUnitDirectory: "IMPEX_SRC_DIR"
    bindings:
      Locale: "null"
      Files: "ExistingFiles"
      SourceDirectoryPath: "null"
      SourceUnitDirectory: "null"
      SourceUnitDomain: "UnitDomain"
      TargetUnitDomain: "UnitDomain"
      TargetDirectoryPath: "TargetDirectory"
      TargetUnitDirectory: "null"
  - id: "DecisionNode1"
    type: "decision"
    condition: "FileName"
  - id: "DecisionNode2"
    type: "decision"
    condition: "PageNumber"
  - id: "DecisionNode3"
    type: "decision"
    condition: "PageLocator"
  - id: "DecisionNode6"
    type: "decision"
    condition: "Paging"
  - id: "DecisionNode7"
    type: "decision"
    condition: "ExistingFiles"
  - id: "DecisionNode8"
    type: "decision"
    condition: "File:Extension"
  - id: "DecisionNode9"
    type: "decision"
    condition: "File:Size"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorCode"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "ExistingFiles"
        type: "java.util.Iterator"
        guaranteed: true
      - key: "FileName"
        type: "java.lang.Object"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorCode"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "ErrorCode"
        type: "java.lang.String"
        guaranteed: true
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode15"
    type: "join"
  - id: "JoinNode16"
    type: "join"
  - id: "JoinNode17"
    type: "join"
  - id: "JoinNode18"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "JumpNode10"
    type: "jump"
    ref: "This:Paging"
  - id: "JumpNode11"
    type: "jump"
    ref: "This:BrowseDirectory"
  - id: "JumpNode12"
    type: "jump"
    ref: "This:BrowseDirectory"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewShippingImportFiles_52-BrowseDirectory"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewShippingImportFiles_52-BrowseDirectory"
  - id: "JumpNode5"
    type: "jump"
  - id: "JumpNode6"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode7"
    type: "jump"
    ref: "Error-Start"
  - id: "JumpNode8"
    type: "jump"
    ref: "ViewShippingImportFiles_52-Paging"
  - id: "JumpNode9"
    type: "jump"
    ref: "This:BrowseDirectory"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"FileIsEmpty\""
      OutValue_1: "ErrorCode"
  - id: "LoopNode2"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OrderStatistics"
      WorkingTemplate: "impex/ShippingImportSourceFiles_52"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "ProcessMultipartRequest"
    config:
      DirectoryPath: "upload"
      MaxFileSize: 100
      UnitDirectory: "IMPEX_DIR"
    bindings:
      Files: "null"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewShippingImportFiles_52-Paging"
      DefaultPageLocatorName: "ShippingImportFilesPageLocator"
    bindings:
      Pageable: "Files"
  - id: "Pipelet12"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Files"
  - id: "Pipelet13"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Files"
      PageableID: "PageLocator:PageableID"
  - id: "Pipelet14"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewShippingImportFiles_52-BrowseDirectory"
      OutValue_1: "ViewShippingImportFiles_52-Paging"
      OutValue_2: "ViewShippingImportFiles_52-DeleteFiles"
      OutValue_4: "ViewShippingImportFiles_52-Back"
      PagingPipeline: "ViewShippingImportFiles_52-Paging"
      OutValue_3: "ViewShippingImportFiles_52-CopyFile"
    bindings:
      Key_0: "BrowseDirectory"
      Key_1: "Paging"
      Key_2: "DeleteFiles"
      Key_4: "ConfirmDeleteFiles"
      SelectionKey: "JumpTarget"
      Key_3: "CopyFile"
  - id: "Pipelet17"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"
  - id: "Pipelet18"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ShippingImportFilesPageLocator"
      RestorePageLocatorDictionary: "True"
  - id: "Pipelet19"
    type: "pipelet"
    ref: "ExtractCompressedFile"
    config:
      Overwrite: true
      Excludes: "${File.separator}"
    bindings:
      SourceUnitDomain: "UnitDomain"
      TargetUnitDomain: "UnitDomain"
      TargetUnitDirectory: "\"IMPEX_SRC_DIR\""
      TargetDirectoryPath: "TargetDirectory"
      SourceDirectoryPath: "\"upload\""
      SourceUnitDirectory: "\"IMPEX_DIR\""
  - id: "Pipelet2"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    config:
      PageableName: "Files"
      Pagesize: 10
    bindings:
      Iterator: "Directory:Files"
      Pageable: "Files"
  - id: "Pipelet23"
    type: "pipelet"
    ref: "DeleteFile"
    config:
      DefaultDirectoryPath: "upload"
      UnitDirectory: "IMPEX_DIR"
    bindings:
      FileName: "FileName"
      UnitDomain: "UnitDomain"
  - id: "Pipelet24"
    type: "pipelet"
    ref: "CopyFile"
    config:
      DefaultSourceDirectoryPath: "upload"
      DefaultSourceUnitDirectory: "IMPEX_DIR"
      DefaultTargetUnitDirectory: "IMPEX_SRC_DIR"
    bindings:
      SourceFileName: "FileName"
      SourceUnitDomain: "UnitDomain"
      TargetFileName: "FileName"
      TargetUnitDomain: "UnitDomain"
      TargetDirectoryPath: "TargetDirectory"
  - id: "Pipelet25"
    type: "pipelet"
    ref: "DeleteFile"
    config:
      DefaultDirectoryPath: "upload"
      UnitDirectory: "IMPEX_DIR"
    bindings:
      FileName: "FileName"
      UnitDomain: "UnitDomain"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "DeleteFile"
    config:
      DefaultDirectoryPath: "src/shipping"
      UnitDirectory: "IMPEX_DIR"
    bindings:
      UnitDomain: "ChannelRepository:Domain"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OrderStatistics"
      WorkingTemplate: "impex/ShippingImportSourceFiles_52"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "DeleteFile"
    config:
      DefaultDirectoryPath: "upload"
      UnitDirectory: "IMPEX_DIR"
    bindings:
      FileName: "FileName"
      UnitDomain: "ChannelRepository:Domain"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Files"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ShippingImportFilesPageLocator"
      RestorePageLocatorDictionary: "True"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "BrowseDirectory"
    config:
      DefaultDirectoryPath: "src/shipping"
      UnitDirectory: "IMPEX_DIR"
      IncludeParentDirectories: false
    bindings:
      UnitDomain: "ChannelRepository:Domain"
  - id: "Pipelet9"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      Iterator: "FileNames"
      FirstElement: "FileName"
  - id: "ReleaseFileResource1"
    type: "pipelet"
    ref: "ReleaseFileResource"
    bindings:
      CurrentProcess: "LockProcess"
  - id: "ReleaseFileResource2"
    type: "pipelet"
    ref: "ReleaseFileResource"
    bindings:
      CurrentProcess: "LockProcess"
  - id: "ResolveFilename1"
    type: "pipelet"
    ref: "ResolveFilename"
    config:
      UnitDirectory: "IMPEX_DIR"
    bindings:
      DirectoryPath: "\"upload\""
      UnitDomain: "UnitDomain"
      FileName: "FileName"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: "FileIsEmpty"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: "FileUploadError"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "Error-Start"
  - id: "VerifyZipFile1"
    type: "pipelet"
    ref: "VerifyZipFile"
    config:
      DefaultDirectoryPath: "upload"
      DefaultUnitDirectory: "IMPEX_DIR"
    bindings:
      UnitDomain: "UnitDomain"
      UnitDirectory: "null"
      DirectoryPath: "null"
      Locale: "null"
      ZipFile: "FileName"

links:
  - from: "AcquireFileResource1"
    via: "error"
    to: "JumpNode8"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "ReleaseFileResource2"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "Pipelet3"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "AcquireFileResource1"
    into: "in"
  - from: "CallNode6"
    via: "FilesAlreadyExist"
    to: "JumpNode10"
    into: "in"
  - from: "StartNode10"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet17"
    into: "in"
  - from: "Pipelet14"
    via: "error"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "Pipelet18"
    via: "error"
    to: "JumpNode3"
    into: "in"
  - from: "AcquireFileResource1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "Pipelet8"
    via: "error"
    to: "Pipelet4"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "JumpNode9"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "Pipelet13"
    via: "error"
    to: "JoinNode10"
    into: "in2"
  - from: "Pipelet11"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode6"
    into: "in3"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode2"
    into: "in3"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode9"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "LoopNode2"
    via: "next"
    to: "ReleaseFileResource2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "Pipelet14"
    into: "in"
  - from: "Pipelet17"
    via: "next"
    to: "Pipelet12"
    into: "in"
  - from: "Pipelet12"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode6"
    via: "yes"
    to: "DecisionNode1"
    into: "in"
  - from: "Pipelet17"
    via: "error"
    to: "JoinNode4"
    into: "in3"
  - from: "StartNode3"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "ReleaseFileResource1"
    via: "next"
    to: "JumpNode7"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "Pipelet13"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "Pipelet6"
    into: "in"
  - from: "Pipelet18"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode8"
    into: "in3"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "CallNode6"
    via: "Error"
    to: "JumpNode11"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "JumpNode12"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "Pipelet18"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet5"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "Pipelet11"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "Pipelet1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "DecisionNode3"
    into: "in"
  - from: "Pipelet7"
    via: "next"
    to: "Pipelet13"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode15"
    into: "in2"
  - from: "Pipelet3"
    via: "error"
    to: "ReleaseFileResource1"
    into: "in"
  - from: "DecisionNode8"
    via: "no"
    to: "JoinNode17"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "Pipelet23"
    into: "in"
  - from: "JoinNode15"
    via: "next"
    to: "Pipelet25"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "EndNode2"
    into: "in"
  - from: "StartNode11"
    via: "next"
    to: "JoinNode16"
    into: "in1"
  - from: "Pipelet19"
    via: "error"
    to: "JoinNode18"
    into: "in2"
  - from: "JoinNode17"
    via: "next"
    to: "Pipelet24"
    into: "in"
  - from: "DecisionNode9"
    via: "no"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Pipelet9"
    via: "error"
    to: "KeyMapper1"
    into: "in"
  - from: "Pipelet19"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "Pipelet7"
    via: "error"
    to: "JoinNode9"
    into: "in2"
  - from: "Pipelet10"
    via: "next"
    to: "Pipelet9"
    into: "in"
  - from: "Pipelet24"
    via: "error"
    to: "JoinNode18"
    into: "in1"
  - from: "DecisionNode9"
    via: "yes"
    to: "DecisionNode8"
    into: "in"
  - from: "Pipelet23"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "CheckForExistingFiles2"
    via: "next"
    to: "DecisionNode7"
    into: "in"
  - from: "VerifyZipFile1"
    via: "error"
    to: "JoinNode17"
    into: "in2"
  - from: "DecisionNode8"
    via: "yes"
    to: "VerifyZipFile1"
    into: "in"
  - from: "JoinNode16"
    via: "next"
    to: "ResolveFilename1"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "JoinNode16"
    into: "in2"
  - from: "StartNode1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode15"
    into: "in1"
  - from: "StartNode5"
    via: "next"
    to: "Pipelet10"
    into: "in"
  - from: "Pipelet9"
    via: "next"
    to: "CheckForExistingFiles2"
    into: "in"
  - from: "JoinNode18"
    via: "next"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "ResolveFilename1"
    via: "next"
    to: "DecisionNode9"
    into: "in"
  - from: "Pipelet10"
    via: "error"
    to: "EndNode1"
    into: "in"
  - from: "VerifyZipFile1"
    via: "next"
    to: "Pipelet19"
    into: "in"
  - from: "Pipelet25"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "Pipelet24"
    via: "next"
    to: "JoinNode7"
    into: "in3"
  - from: "Pipelet14"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "JumpNode6"
    into: "in"
