flow: "ViewPromotionCode"
kind: "view"

entries:
  - id: "StartNode1"
    name: "ShowDeactivate"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Deactivate"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "ConfirmDeactivate"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "ErrorPromotionCodesVector"
      Object: "Code"
      Iterator: "ErrorPromotionCodes"
      OutVector: "ErrorPromotionCodesVector"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessPromotionCode-Deactivate"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessPromotion-GetPromotionDomainByChannel"
    bindings:
      Channel: "CurrentChannel"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "PromotionCodeDeactivate"
      FormResource: "PromotionCodeDeactivate"
    bindings:
      Form: "PromotionCodeDeactivateForm"
  - id: "CreateForm2"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "PromotionCodeDeactivate"
      FormResource: "PromotionCodeDeactivate"
    bindings:
      Form: "PromotionCodeDeactivateForm"
  - id: "CreateForm3"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "PromotionCodeDeactivate"
      FormResource: "PromotionCodeDeactivate"
    bindings:
      Form: "PromotionCodeDeactivateForm"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPromotionCode-Deactivate"
      OutValue_2: "ViewPromotionCode-ShowDeactivate"
      OutValue_1: "ViewPromotionCode-ConfirmDeactivate"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "deactivateCodes"
      Key_1: "confirmDeactivateCodes"
      Key_2: "cancel"
  - id: "GetPromotionCodeByCode1"
    type: "pipelet"
    ref: "GetPromotionCodeByCode"
    bindings:
      Domain: "PromotionDomain"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "Jump6"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "LoopNode1"
    type: "loop"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/PromotionCodeDeactivate"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "SUCCESS_PromotionCodeDeactivate"
      Value: "\"1\""
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_PromotionCodeDeactivate"
      Value: "\"1\""
  - id: "SplitString1"
    type: "pipelet"
    ref: "SplitString"
    bindings:
      ValuesString: "PromotionCodeDeactivateForm:Codes:Value"
      Trim: "\"(Boolean)true\""
      Delimeter: "\"\\r\\n\""
  - id: "ValidateForm2"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "PromotionCodeDeactivateForm"
  - id: "ValidateForm3"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "PromotionCodeDeactivateForm"

links:
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "ValidateForm2"
    via: "next"
    to: "SplitString1"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "ValidateForm2"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "ValidateForm2"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "ValidateForm3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CreateForm3"
    via: "next"
    to: "ValidateForm3"
    into: "in"
  - from: "SplitString1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CreateForm3"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "GetPromotionCodeByCode1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "GetPromotionCodeByCode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "CreateForm2"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "GetPromotionCodeByCode1"
    via: "error"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump6"
    into: "in"
  - from: "CreateForm2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "ValidateForm3"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode3"
    into: "in1"
