flow: "ViewChannelCatalogFilterExport"
kind: "view"

entries:
  - id: "Start1"
    name: "Back"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Export"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "SelectConfiguration"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "SelectFilters"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "OverwriteFile"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "CancelOverwriteFile"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Object: "Filter"
      InVector: "FilterVector"
      OutVector: "FilterVector"
      Iterator: "CatalogFilters"
      Objects: "null"
  - id: "Call1"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call6"
    type: "call"
    ref: "ProcessImpexJob-Create"
  - id: "Call8"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "CallNode1"
    type: "call"
    ref: "GetCatalogFilters-GetEditableFilters"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessImpexJob-IsFilenameTaken"
    bindings:
      Domain: "ChannelRepository:Domain"
      Filename: "CatalogFilterExportForm:ExportFile:Value"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CreatePageableFromIterator2"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    config:
      Pagesize: 20
    bindings:
      Iterator: "CatalogFilters"
      Pageable: "CatalogFilters"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "ExportFile"
      param.1.required: true
      param.1.rule: "^[^.\\\\/:*?<>|\\s]([^\\\\/:*?<>|\\s]*[^.\\\\/:*?<>|\\s])?$"
      param.2.required: false
      webform-id: "CatalogFilterExportForm"
    bindings:
      WebForm: "CatalogFilterExportForm"
  - id: "Decision1"
    type: "decision"
    condition: "ExportAllFilters"
  - id: "Decision2"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision3"
    type: "decision"
    condition: "CatalogFilterExportPageLocator"
  - id: "DecisionNode1"
    type: "decision"
    condition: "CatalogFilters"
  - id: "DispatchFormActionByBreadcrumb1"
    type: "pipelet"
    ref: "DispatchFormActionByBreadcrumb"
    config:
      SplitMode: "PipelineAndParameter"
    bindings:
      Key_0: "Cancel"
      OutValue_0: "ApplicationState:ExitFromWizard"
      SelectionKey: "JumpTarget"
  - id: "GetCatalogFilter1"
    type: "pipelet"
    ref: "GetCatalogFilter"
    bindings:
      FilterID: "UUID"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "CatalogFilterExportPageLocator"
      RestorePageLocatorDictionary: "True"
  - id: "GetPageLocator2"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "CatalogFilterExportPageLocator"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocator: "CatalogFilterExportPageLocator"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "CatalogFilters"
      PageableID: "CatalogFilterExportPageLocator:PageableID"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "CatalogFilterExportForm"
    bindings:
      WebForm: "CatalogFilterExportForm"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "CatalogFilterExportForm"
    bindings:
      WebForm: "CatalogFilterExportForm"
  - id: "GetWebForm3"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "CatalogFilterExportForm"
    bindings:
      WebForm: "CatalogFilterExportForm"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump2"
    type: "jump"
  - id: "Jump3"
    type: "jump"
    ref: "Error-Start"
  - id: "Jump5"
    type: "jump"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode3"
    type: "jump"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ChannelRepository:Domain"
      InValue_2: "ChannelRepository:Domain"
      OutValue_1: "ProcessOwningDomain"
      OutValue_2: "ProcessExecutionDomain"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "CatalogFilters:ID"
      InValue_2: "CatalogFilterExportForm_ExportFile"
      OutValue_1: "ObjectsID"
      OutValue_2: "SelectedFile"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "PageableID"
      InValue_2: "CatalogFilterExportForm_ExportFile"
      OutValue_1: "ObjectsID"
      OutValue_2: "SelectedFile"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentChannel:RepositoryDomain"
      OutValue_1: "FilterDomain"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      OutValue_1: "ProcessPipelineName"
      InValue_1: "\"ProcessCatalogFilterExport\""
      OutValue_2: "ProcessPipelineStartNode"
      InValue_2: "\"Export\""
      InValue_3: "\"ProcessCatalogImpex\""
      OutValue_3: "JobName"
  - id: "LoopNode1"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_2: "ViewChannelCatalogFilterExport-Paging"
      OutValue_3: "ViewChannelCatalogFilterExport-SelectConfiguration"
      OutValue_4: "ViewChannelCatalogFilterExport-Export"
      OutValue_5: "ViewChannelCatalogFilterExport-Back"
      PagingPipeline: "ViewChannelCatalogFilterExport-Paging"
      OutValue_6: "ViewChannelCatalogFilterExport-OverwriteFile"
      OutValue_7: "ViewChannelCatalogFilterExport-CancelOverwriteFile"
    bindings:
      Key_2: "jumpToList"
      Key_3: "SelectConfiguration"
      Key_4: "Export"
      Key_5: "Back"
      SelectionKey: "JumpTarget"
      Key_6: "Overwrite"
      Key_7: "CancelOverwrite"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelImportExport"
      WorkingTemplate: "impex/ChannelCatalogFilterExportSelectConfiguration"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelImportExport"
      WorkingTemplate: "impex/ChannelCatalogFilterExportSelectFilters"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Value: "ApplicationState:ExitFromWizard:Pipeline"
      ValueType: "Dictionary Value"
      Name: "JumpTarget"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "FILENAME_ALREADY_IN_USE"
      Value: true
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "CatalogFilters"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "CatalogFilterExportPageLocator:PageNumber"
      Pageable: "CatalogFilters"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewChannelCatalogFilterExport-Paging"
      DefaultPageLocatorName: "CatalogFilterExportPageLocator"
    bindings:
      PageLocator: "CatalogFilterExportPageLocator"
      Pageable: "CatalogFilters"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "CatalogFilterExportForm"
    bindings:
      WebForm: "CatalogFilterExportForm"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "CatalogFilterExportForm"
    bindings:
      WebForm: "CatalogFilterExportForm"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "CatalogFilterExportForm"
  - id: "ValidateWebForm2"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "CatalogFilterExportForm"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"

links:
  - from: "DispatchFormActionByBreadcrumb1"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "Decision3"
    via: "yes"
    to: "SetPage2"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage1"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "Join6"
    into: "in3"
  - from: "GetPageable1"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "GetPageLocator2"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "KeyMapper4"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "SetPageLocator1"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Decision3"
    via: "no"
    to: "Join7"
    into: "in3"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join5"
    into: "in3"
  - from: "JoinNode2"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "SetPage1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Join6"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "GetCatalogFilter1"
    into: "in"
  - from: "GetCatalogFilter1"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "DecisionNode1"
    via: "yes"
    to: "CreatePageableFromIterator2"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Decision3"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "GetPageLocator2"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "Start5"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "Pipelet1"
    via: "error"
    to: "DispatchFormActionByBreadcrumb1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "ValidateWebForm1"
    via: "error"
    to: "JoinNode1"
    into: "in3"
  - from: "Start2"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "Join3"
    into: "in3"
  - from: "CallNode3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CreateWebForm1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode2"
    via: "FILENAME_ALREADY_IN_USE"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Call4"
    into: "in"
  - from: "CreatePageableFromIterator2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "KeyMapper1"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "Jump3"
    into: "in"
  - from: "GetWebForm3"
    via: "next"
    to: "JoinNode8"
    into: "in3"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "GetPageLocator1"
    via: "error"
    to: "JumpNode3"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "KeyMapper3"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode6"
    into: "in3"
  - from: "Start3"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "KeyMapper5"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "DispatchFormActionByBreadcrumb1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "ValidateWebForm1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "ValidateWebForm2"
    via: "next"
    to: "JoinNode7"
    into: "in3"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "UpdateWebForm2"
    via: "next"
    to: "ValidateWebForm2"
    into: "in"
  - from: "GetPageLocator2"
    via: "error"
    to: "JoinNode4"
    into: "in3"
  - from: "GetWebForm2"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "GetWebForm2"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "ValidateWebForm2"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "GetWebForm3"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "JoinNode3"
    into: "in3"
