flow: "ViewChannelShippingMethodImport"
kind: "view"

entries:
  - id: "Start1"
    name: "SelectMode"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "ValidateFileRefresh"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "ValidateFile"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Import"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode10"
    name: "CopyFile"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "SelectFile"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Cancel"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "PrepareValidation"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "VerifyForm"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "PrepareImport"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "Upload"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessImpexJob-GetLogContent"
  - id: "Call2"
    type: "call"
    ref: "ProcessImpexJob-Create"
  - id: "Call3"
    type: "call"
    ref: "ProcessImpexJob-Create"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode3"
    type: "call"
    ref: "ViewChannelShippingMethodImport-PrepareValidation"
  - id: "CallNode4"
    type: "call"
    ref: "ViewChannelShippingMethodImport-PrepareImport"
  - id: "CallNode5"
    type: "call"
    ref: "ViewShippingImportFiles_52-InternalCopyFile"
    bindings:
      TargetDirectory: "\"shipping\""
      UnitDomain: "CurrentChannel:RepositoryDomain"
  - id: "CallNode6"
    type: "call"
    ref: "ViewShippingImportFiles_52-InternalUpload"
    bindings:
      UnitDomain: "CurrentChannel:RepositoryDomain"
      TargetDirectory: "\"shipping\""
  - id: "CallNode7"
    type: "call"
    ref: "ViewChannelShippingMethodImport-VerifyForm"
  - id: "CopyFile1"
    type: "pipelet"
    ref: "CopyFile"
    config:
      DefaultSourceDirectoryPath: "temp"
      DefaultSourceUnitDirectory: "IMPEX_DIR"
      DefaultTargetUnitDirectory: "IMPEX_SRC_DIR"
    bindings:
      SourceFileName: "JobConfiguration:TempXMLFile"
      SourceUnitDomain: "CurrentChannel:Domain"
      TargetFileName: "JobConfiguration:TempXMLFile"
      TargetUnitDomain: "CurrentChannel:Domain"
  - id: "CreateForm3"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "ShippingImportForm"
      FormResource: "ShippingImport"
    bindings:
      CurrentDomain: "CurrentDomain"
      Form: "ShippingImportForm"
  - id: "Decision1"
    type: "decision"
    condition: "JobConfiguration:Status"
  - id: "Decision2"
    type: "decision"
    condition: "JobConfiguration:LastExecutionTime:Time"
  - id: "Decision3"
    type: "decision"
    condition: "JobConfiguration"
  - id: "Decision4"
    type: "decision"
    condition: "JobConfiguration:TempXMLFile"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PageLocator"
  - id: "DecisionNode2"
    type: "decision"
    condition: "PageNumber"
  - id: "DecisionNode3"
    type: "decision"
    condition: "FileName"
  - id: "DecisionNode6"
    type: "decision"
    condition: "Paging"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "GetJobConfiguration1"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "GetJobConfiguration2"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "InteractionNode3"
    type: "interaction"
  - id: "InteractionNode4"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump3"
    type: "jump"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode2"
    type: "jump"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewChannelShippingMethodImport-SelectFile"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewChannelShippingMethodImport-Paging"
  - id: "JumpNode5"
    type: "jump"
    ref: "ViewChannelShippingMethodImport-ValidateFileRefresh"
  - id: "JumpNode6"
    type: "jump"
    ref: "ViewChannelShippingMethodImport-SelectFile"
  - id: "JumpNode7"
    type: "jump"
    ref: "ViewChannelShippingMethodImport-SelectFile"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "ShippingImportForm:SelectedFile:Value"
      OutValue_1: "SelectedFile"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "JobConfiguration:SourceCount_shipping-method"
      OutValue_1: "SourceCountPPL"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ChannelRepository:Domain"
      InValue_2: "ChannelRepository:Domain"
      OutValue_1: "ProcessOwningDomain"
      OutValue_2: "ProcessExecutionDomain"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ChannelRepository:Domain"
      InValue_2: "ChannelRepository:Domain"
      OutValue_1: "ProcessOwningDomain"
      OutValue_2: "ProcessExecutionDomain"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "JobConfiguration:TempXMLFile"
      OutValue_1: "TempXMLFile"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewChannelShippingMethodImport-Paging"
      DefaultPageLocatorName: "ChannelShippingMethodImport"
    bindings:
      Pageable: "Files"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OrderStatistics"
      WorkingTemplate: "impex/ShippingMethodImportSelectMode"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ChannelShippingMethodImport"
      RestorePageLocatorDictionary: "True"
  - id: "Pipelet12"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"
  - id: "Pipelet13"
    type: "pipelet"
    ref: "BrowseDirectory"
    config:
      DefaultDirectoryPath: "src/shipping"
      UnitDirectory: "IMPEX_DIR"
    bindings:
      UnitDomain: "ChannelRepository:Domain"
  - id: "Pipelet14"
    type: "pipelet"
    ref: "DeleteFile"
    config:
      DefaultDirectoryPath: "upload"
      UnitDirectory: "IMPEX_DIR"
    bindings:
      FileName: "FileName"
      UnitDomain: "ChannelRepository:Domain"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Files"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OrderStatistics"
      WorkingTemplate: "impex/ShippingMethodImportSelectFile"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Files"
      PageableID: "PageLocator:PageableID"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Files"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    config:
      PageableName: "Files"
      Pagesize: 10
    bindings:
      Iterator: "Directory:Files"
      Pageable: "Files"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelShippingMethodImport-SelectFile"
      OutValue_1: "ViewChannelShippingMethodImport-Paging"
      OutValue_2: "ViewChannelShippingMethodImport-ValidateFile"
      OutValue_3: "ViewChannelShippingMethodImport-ValidateFileRefresh"
      OutValue_4: "ViewChannelShippingMethodImport-SelectMode"
      OutValue_5: "ViewChannelShippingMethodImport-Import"
      OutValue_6: "ViewChannelShippingMethodImport-Cancel"
      PagingPipeline: "ViewChannelShippingMethodImport-Paging"
      OutValue_7: "ViewChannelShippingMethodImport-Upload"
      OutValue_8: "ViewChannelShippingMethodImport-CopyFile"
    bindings:
      Key_0: "SelectFile"
      Key_1: "Paging"
      Key_2: "ValidateFile"
      Key_3: "ValidateFileRefresh"
      Key_4: "SelectMode"
      Key_5: "Import"
      Key_6: "Cancel"
      SelectionKey: "JumpTarget"
      Key_7: "Upload"
      Key_8: "CopyFile"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OrderStatistics"
      WorkingTemplate: "impex/ShippingMethodImportValidateFile"
  - id: "Pipelet9"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OrderStatistics"
      WorkingTemplate: "impex/ShippingMethodImportSelectFile"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ProcessPipelineName"
      Value: "ProcessShippingMethodImport"
      ValueType: "Form Value"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JobName"
      Value: "ProcessShippingImpex"
      ValueType: "Form Value"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ProcessPipelineStartNode"
      Value: "Import"
      ValueType: "Form Value"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JobDescription"
      Value: "Validates shipping methods import file."
      ValueType: "Form Value"
  - id: "SetDictionaryValue5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ProcessPipelineName"
      Value: "ProcessShippingMethodImport"
      ValueType: "Form Value"
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ProcessPipelineStartNode"
      Value: "Validate"
      ValueType: "Form Value"
  - id: "SetDictionaryValue7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JobName"
      Value: "ProcessShippingImpex"
      ValueType: "Form Value"
  - id: "SetDictionaryValue8"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JobDescription"
      Value: "Imports shipping methods."
      ValueType: "Form Value"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "ShippingImportForm"

links:
  - from: "StartNode3"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "StartNode10"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Pipelet13"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet12"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Pipelet11"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Pipelet11"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "Pipelet7"
    via: "error"
    to: "JoinNode10"
    into: "in2"
  - from: "Pipelet9"
    via: "next"
    to: "InteractionNode4"
    into: "in"
  - from: "Pipelet13"
    via: "error"
    to: "Pipelet9"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode7"
    via: "ERROR"
    to: "Join3"
    into: "in1"
  - from: "Join3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Pipelet5"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Pipelet11"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "Pipelet12"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "CallNode6"
    via: "FilesAlreadyExist"
    to: "JumpNode4"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "Pipelet13"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "Pipelet12"
    via: "error"
    to: "JoinNode2"
    into: "in3"
  - from: "Start4"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "Pipelet4"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "SetDictionaryValue5"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet5"
    into: "in"
  - from: "SetDictionaryValue5"
    via: "next"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "SetDictionaryValue7"
    into: "in"
  - from: "SetDictionaryValue7"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join5"
    into: "in1"
  - from: "Decision2"
    via: "yes"
    to: "Call1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "Pipelet10"
    into: "in"
  - from: "Pipelet10"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode5"
    into: "in3"
  - from: "Decision3"
    via: "no"
    to: "Join6"
    into: "in3"
  - from: "Call1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join5"
    into: "in2"
  - from: "Decision3"
    via: "yes"
    to: "GetJobConfiguration1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "Pipelet8"
    via: "next"
    to: "InteractionNode3"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Decision2"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "JoinNode8"
    into: "in3"
  - from: "JoinNode8"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "SetDictionaryValue8"
    into: "in"
  - from: "SetDictionaryValue8"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "GetJobConfiguration2"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "Decision4"
    via: "yes"
    to: "CopyFile1"
    into: "in"
  - from: "CopyFile1"
    via: "error"
    to: "JoinNode12"
    into: "in2"
  - from: "CallNode6"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "CallNode6"
    via: "Error"
    to: "JumpNode6"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "GetJobConfiguration2"
    via: "error"
    to: "JoinNode11"
    into: "in2"
  - from: "KeyMapper4"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CreateForm3"
    into: "in"
  - from: "CreateForm3"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "ValidateForm1"
    via: "error"
    to: "EndNode2"
    into: "in"
  - from: "ValidateForm1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "Pipelet14"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode9"
    into: "in2"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode7"
    into: "in2"
  - from: "DecisionNode6"
    via: "yes"
    to: "DecisionNode3"
    into: "in"
  - from: "Pipelet14"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode9"
    into: "in1"
  - from: "Start3"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "Pipelet7"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode10"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "Pipelet14"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "GetJobConfiguration1"
    via: "error"
    to: "Join6"
    into: "in1"
  - from: "GetJobConfiguration2"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "Decision4"
    into: "in"
  - from: "CopyFile1"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "JoinNode12"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "JumpNode7"
    into: "in"
