flow: "ViewChannelOutboundSyndicationSoqueroDataFeedConfiguration"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Update"
    mode: "private"
    strict: true
    inputs:
      - key: "Syndication"
        type: "com.intershop.component.foundation.capi.syndication.Syndication"
        required: true
      - key: "SoqueroDataFeedWebForm"
        type: "com.intershop.beehive.core.capi.request.WebForm"
        required: false
      - key: "SoqueroDataFeedWebForm_FileName"
        type: "java.lang.String"
        required: false
      - key: "SoqueroDataFeedWebForm_CompressionLevel"
        type: "java.lang.String"
        required: false
      - key: "SoqueroDataFeedWebForm_LocaleID"
        type: "java.lang.String"
        required: false
      - key: "SoqueroDataFeedWebForm_CurrencyMnemonic"
        type: "java.lang.String"
        required: false
      - key: "SoqueroDataFeedWebForm_ShippingCosts"
        type: "java.lang.String"
        required: false
      - key: "SoqueroDataFeedWebForm_LogoLink"
        type: "java.lang.String"
        required: false
  - id: "StartNode2"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Remove"
    mode: "private"
    strict: true
    inputs:
      - key: "Syndication"
        type: "com.intershop.component.foundation.capi.syndication.Syndication"
        required: true
  - id: "StartNode4"
    name: "CreateWebForm"
    mode: "private"
    strict: true
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewChannelOutboundSyndicationSoqueroDataFeedConfiguration-CreateWebForm"
  - id: "CallNode2"
    type: "call"
    ref: "ViewChannelOutboundSyndicationSoqueroDataFeedConfiguration-CreateWebForm"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessChannelOutboundSyndication-EnforceAppropriateFileExtension"
    bindings:
      CompressionLevel: "SoqueroDataFeedWebForm_CompressionLevel"
      FileName: "SoqueroDataFeedWebForm_FileName"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      webform-id: "SoqueroDataFeedWebForm"
      param.1.name: "FileName"
      param.1.rule: "^[^.\\\\/:*?<>|\\s]([^\\\\/:*?<>|\\s]*[^.\\\\/:*?<>|\\s])?$"
      param.1.required: true
      param.2.name: "CompressionLevel"
      param.2.rule: "^[0-9]$"
      param.2.required: true
      param.3.name: "LocaleID"
      param.3.rule: ""
      param.3.required: true
      param.4.name: "CurrencyMnemonic"
      param.4.rule: ""
      param.4.required: false
      param.5.name: "ShippingCosts"
      param.5.rule: ""
      param.5.required: false
      param.6.name: "LogoLink"
      param.6.rule: ""
      param.6.required: false
    bindings:
      WebForm: "SoqueroDataFeedWebForm"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "SoqueroDataFeedWebForm"
        type: "com.intershop.beehive.core.capi.request.WebForm"
        guaranteed: false
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "SoqueroDataFeedWebForm"
        type: "com.intershop.beehive.core.capi.request.WebForm"
        guaranteed: false
  - id: "GetCurrencies1"
    type: "pipelet"
    ref: "GetCurrencies"
    config:
      Method: "Active Currencies"
    bindings:
      Domain: "OrganizationDomain"
  - id: "GetSyndicationByUUID1"
    type: "pipelet"
    ref: "GetSyndicationByUUID"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "SoqueroDataFeedWebForm"
    bindings:
      WebForm: "SoqueroDataFeedWebForm"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "SoqueroDataFeedWebForm"
    bindings:
      WebForm: "SoqueroDataFeedWebForm"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "RemoveCustomAttribute1"
    type: "pipelet"
    ref: "RemoveCustomAttribute"
    bindings:
      LocaleInformation: "null"
      ExtensibleObject: "Syndication"
      AttributeName: "\"CompressionLevel\""
  - id: "RemoveCustomAttribute2"
    type: "pipelet"
    ref: "RemoveCustomAttribute"
    bindings:
      LocaleInformation: "null"
      ExtensibleObject: "Syndication"
      AttributeName: "\"LocaleID\""
  - id: "RemoveCustomAttribute3"
    type: "pipelet"
    ref: "RemoveCustomAttribute"
    bindings:
      LocaleInformation: "null"
      ExtensibleObject: "Syndication"
      AttributeName: "\"CurrencyMnemonic\""
  - id: "RemoveCustomAttribute4"
    type: "pipelet"
    ref: "RemoveCustomAttribute"
    bindings:
      LocaleInformation: "null"
      ExtensibleObject: "Syndication"
      AttributeName: "\"ShippingCosts\""
  - id: "RemoveCustomAttribute5"
    type: "pipelet"
    ref: "RemoveCustomAttribute"
    bindings:
      LocaleInformation: "null"
      ExtensibleObject: "Syndication"
      AttributeName: "\"FileName\""
  - id: "RemoveCustomAttribute6"
    type: "pipelet"
    ref: "RemoveCustomAttribute"
    bindings:
      LocaleInformation: "null"
      ExtensibleObject: "Syndication"
      AttributeName: "\"ShippingCosts\""
  - id: "RemoveWebForm1"
    type: "pipelet"
    ref: "RemoveWebForm"
    config:
      webform-id: "SoqueroDataFeedWebForm"
  - id: "UpdateCustomAttributes1"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "FileName"
      Attribute_1_Type: "String"
      Attribute_10_Name: "CompressionLevel"
      Attribute_10_Type: "String"
      Attribute_2_Name: "LocaleID"
      Attribute_2_Type: "String"
      Attribute_3_Name: "CurrencyMnemonic"
      Attribute_3_Type: "String"
      Attribute_4_Name: "ShippingCosts"
      Attribute_4_Type: "String"
      Attribute_5_Name: "LogoLink"
      Attribute_5_Type: "String"
    bindings:
      Attribute_1_Value: "SoqueroDataFeedWebForm_FileName"
      ExtensibleObject: "Syndication"
      Attribute_10_Value: "SoqueroDataFeedWebForm_CompressionLevel"
      Attribute_2_Value: "SoqueroDataFeedWebForm_LocaleID"
      Attribute_3_Value: "SoqueroDataFeedWebForm_CurrencyMnemonic"
      Attribute_4_Value: "SoqueroDataFeedWebForm_ShippingCosts"
      Attribute_5_Value: "SoqueroDataFeedWebForm_LogoLink"
  - id: "UpdateCustomAttributes5"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "FileName"
      Attribute_1_Type: "String"
    bindings:
      Attribute_1_Value: "NewFileName"
      ExtensibleObject: "Syndication"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "SoqueroDataFeedWebForm"
    bindings:
      WebForm: "SoqueroDataFeedWebForm"
  - id: "ValidateWebForm2"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "SoqueroDataFeedWebForm"

links:
  - from: "DetermineLocales1"
    via: "next"
    to: "GetCurrencies1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "RemoveWebForm1"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "CallNode2"
    into: "in"
  - from: "GetWebForm1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetSyndicationByUUID1"
    into: "in"
  - from: "UpdateCustomAttributes1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetSyndicationByUUID1"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "ValidateWebForm2"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "JoinNode3"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "RemoveWebForm1"
    via: "next"
    to: "RemoveCustomAttribute2"
    into: "in"
  - from: "UpdateWebForm2"
    via: "next"
    to: "ValidateWebForm2"
    into: "in"
  - from: "RemoveCustomAttribute4"
    via: "next"
    to: "RemoveCustomAttribute6"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "RemoveCustomAttribute1"
    via: "next"
    to: "RemoveCustomAttribute4"
    into: "in"
  - from: "ValidateWebForm2"
    via: "next"
    to: "UpdateCustomAttributes1"
    into: "in"
  - from: "RemoveCustomAttribute2"
    via: "next"
    to: "RemoveCustomAttribute3"
    into: "in"
  - from: "GetCurrencies1"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "RemoveCustomAttribute3"
    via: "next"
    to: "RemoveCustomAttribute5"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "UpdateCustomAttributes5"
    into: "in"
  - from: "RemoveCustomAttribute6"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "RemoveCustomAttribute5"
    via: "next"
    to: "RemoveCustomAttribute1"
    into: "in"
  - from: "UpdateCustomAttributes5"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "GetWebForm2"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetWebForm2"
    via: "error"
    to: "CallNode1"
    into: "in"
  - from: "CreateWebForm1"
    via: "next"
    to: "EndNode3"
    into: "in"
