flow: "ViewStatusbar"
kind: "view"

entries:
  - id: "StartNode0"
    name: "GetStatusbarParameters"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode1"
    name: "UpdateStatusbar"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode0"
    type: "call"
    ref: "ProcessTimeZones-SetSessionTimeZone"
    bindings:
      TimeZoneID: "StatusbarForm:TimeZoneID:Value"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessTimeZones-DetermineSessionTimeZoneBO"
    bindings:
      TimeZoneBO: "SelectedTimeZoneBO"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessTimeZones-IsTimeZoneSettingEnabled"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessTimeZones-GetTimeZoneBORepository"
  - id: "CreateForm0"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "Statusbar"
      FormResource: "Statusbar"
    bindings:
      Form: "StatusbarForm"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "Statusbar"
      FormResource: "Statusbar"
    bindings:
      Form: "StatusbarForm"
  - id: "EndNode0"
    type: "end"
    strict: true
    outputs:
      - key: "TimeZoneBOs"
        type: "java.util.Collection<? extends com.intershop.component.i18n.capi.timezone.TimeZoneBO>"
        guaranteed: true
      - key: "CurrentDate"
        type: "java.util.Date"
        guaranteed: false
      - key: "IsTimeZoneSettingEnabled"
        type: "java.lang.Boolean"
        guaranteed: true
      - key: "SelectedTimeZoneBO"
        type: "com.intershop.component.i18n.capi.timezone.TimeZoneBO"
        guaranteed: true
      - key: "StatusbarForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        guaranteed: true
  - id: "GetAllTimeZoneBOs0"
    type: "pipelet"
    ref: "GetAllTimeZoneBOs"
  - id: "GetCurrentDate0"
    type: "pipelet"
    ref: "GetCurrentDate"
  - id: "InteractionNode0"
    type: "interaction"
  - id: "JumpNode0"
    type: "jump"
    ref: "ViewApplication-DisplayWelcomePage"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "StatusbarForm:Referer:Value"
      InValue_2: "null"
      InValue_10: "null"
      InValue_3: "null"
      InValue_4: "null"
      InValue_5: "null"
      InValue_6: "null"
      InValue_7: "null"
      InValue_8: "null"
      InValue_9: "null"
      OutValue_1: "TargetURL"
      OutValue_10: "null"
      OutValue_3: "null"
      OutValue_2: "null"
      OutValue_4: "null"
      OutValue_9: "null"
      OutValue_8: "null"
      OutValue_7: "null"
      OutValue_6: "null"
      OutValue_5: "null"
  - id: "Text0"
    type: "text"
  - id: "ValidateForm0"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "StatusbarForm"

links:
  - from: "CallNode0"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "GetCurrentDate0"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "EndNode0"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "GetAllTimeZoneBOs0"
    into: "in"
  - from: "CreateForm0"
    via: "next"
    to: "ValidateForm0"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "GetAllTimeZoneBOs0"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetCurrentDate0"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "InteractionNode0"
    into: "in"
  - from: "StartNode0"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CreateForm0"
    into: "in"
  - from: "ValidateForm0"
    via: "error"
    to: "JumpNode0"
    into: "in"
  - from: "ValidateForm0"
    via: "next"
    to: "CallNode0"
    into: "in"
