flow: "ViewLocalizations"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Management"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Save"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "InitBranch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessLocalizations-CreateForm"
  - id: "CallNode10"
    type: "call"
    ref: "ProcessLocalizations-GetContextLocalizationRepository"
  - id: "CallNode17"
    type: "call"
    ref: "This:InitBranch"
  - id: "CallNode2"
    type: "call"
    ref: "This:InitBranch"
  - id: "CallNode3"
    type: "call"
    ref: "This:InitBranch"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessLocalizations-CreatePageable"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessLocalizations-SetPage"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessLocalizations-UpdateTexts"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessLocalizations-CreatePageable"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessLocalizations-GetLocalizationRepositories"
    bindings:
      DomainUUID: "CurrentOrganization:DomainID"
  - id: "CallNode9"
    type: "call"
    ref: "ProcessLocalizations-GetContextApp"
  - id: "DecisionNode1"
    type: "decision"
    condition: "LocalizationRepositories"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
    bindings:
      LocaleId: "search_LocaleId"
      Locale: "DefaultLocale"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode4"
    type: "jump"
    ref: "Error-Start"
  - id: "KeyMapper0"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:DefaultLocale:LocaleID"
      InValue_2: "null"
      InValue_10: "null"
      InValue_3: "null"
      InValue_4: "null"
      InValue_5: "null"
      InValue_6: "null"
      InValue_7: "null"
      InValue_9: "null"
      InValue_8: "null"
      OutValue_1: "DefaultLocale"
      OutValue_10: "null"
      OutValue_2: "null"
      OutValue_3: "null"
      OutValue_4: "null"
      OutValue_5: "null"
      OutValue_6: "null"
      OutValue_7: "null"
      OutValue_8: "null"
      OutValue_9: "null"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "PageLocator:PageNumber"
      OutValue_1: "_PageNumber"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Localization"
      WorkingTemplate: "localization/LocalizationOverview"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: 0
      OutValue_1: "PageNumber"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "LocalizationTextsLocator"
      RestorePageLocatorDictionary: "True"
      UsePageLocatorHistory: false
  - id: "Pipelet12"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      PageableID: "\"LocalizationTextsPageableID\""
      Pageable: "LocalizationTexts"
  - id: "Pipelet13"
    type: "pipelet"
    ref: "CreateLocalizationContextFromApp"
    bindings:
      App: "ContextApp"
      LocaleInformation: "Locale"
      OwningDomain: "CurrentOrganization:Domain"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "LocalizationTextsLocator"
      RestorePageLocatorDictionary: "True"
      UsePageLocatorHistory: false
  - id: "Pipelet4"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewLocalizations-Management"
      OutValue_1: "ViewLocalizations-Management"
      OutValue_2: "ViewLocalizations-Save"
      OutValue_3: "ViewLocalizations-Management"
    bindings:
      Key_0: "Apply"
      Key_1: "Find"
      Key_2: "Save"
      Key_3: "CancelUpdate"
      SelectionKey: "JumpTarget"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "FireReloadLocalizationEvent"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewLocalization-Management"
      ValueType: "Dictionary Value"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Lead Locale"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Localization"
      WorkingTemplate: "localization/LocalizationManagement"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Localization"
      WorkingTemplate: "localization/LocalizationManagement"
  - id: "ToString1"
    type: "pipelet"
    ref: "ToString"
    bindings:
      Object1: "_PageNumber"
      String1: "PageNumber"

links:
  - from: "CallNode10"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "CallNode17"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Pipelet11"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "Pipelet10"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode9"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "KeyMapper0"
    into: "in"
  - from: "GetLocale2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "KeyMapper0"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "ToString1"
    into: "in"
  - from: "Pipelet10"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "Pipelet11"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "Pipelet11"
    via: "next"
    to: "Pipelet12"
    into: "in"
  - from: "Pipelet12"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "Pipelet12"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "Pipelet13"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Pipelet2"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "Pipelet2"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "Pipelet4"
    via: "error"
    to: "Pipelet6"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "Pipelet5"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "Pipelet5"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "Pipelet7"
    via: "next"
    to: "Pipelet13"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode17"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "ToString1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
