flow: "ViewCaptchaPreferences_52"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "View"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "CreateFormAndPreferenceMap"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddEntryToMap3"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "CaptchaPreferenceMap"
      Key: "PreferenceKey"
      Value: "Preference"
      OutMap: "CaptchaPreferenceMap"
      Keys: "CaptchaPreferences"
  - id: "AddFormParameterDefinition3"
    type: "pipelet"
    ref: "AddFormParameterDefinition"
    config:
      Optional: true
      Type: "java.lang.String"
    bindings:
      Form: "CaptchaSettingsForm"
      Name: "PreferenceKey"
  - id: "CallNode1"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "This:CreateFormAndPreferenceMap"
  - id: "CallNode3"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "This:CreateFormAndPreferenceMap"
  - id: "CreateForm3"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "CaptchaSettingsForm"
      FormResource: "CaptchaSettings"
    bindings:
      Form: "CaptchaSettingsForm"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Preference"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewCaptchaPreferences_52-Update"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "updateSettings"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndSafeChangesBlock1"
    type: "pipelet"
    ref: "EndSafeChangesBlock"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "String"
    bindings:
      PreferenceDomain: "CurrentChannel:Domain"
  - id: "GetDomainPreference3"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "String"
    bindings:
      PreferenceDomain: "CurrentChannel:Domain"
  - id: "GetDomainPreferenceNamesByPreferenceGroup3"
    type: "pipelet"
    ref: "GetDomainPreferenceNamesByPreferenceGroup"
    bindings:
      PreferenceDomain: "CurrentChannel:Domain"
      PreferenceGroup: "\"CaptchaPreferences\""
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "LoopNode3"
    type: "loop"
  - id: "LoopNode4"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "channel/CaptchaPreferences_52"
  - id: "SetDictionaryValue7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewCaptchaPreferences_52-View"
  - id: "SetDomainPreference1"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      Type: "String"
      DefaultPreferenceValue: "on"
    bindings:
      PreferenceDomain: "CurrentChannel:Domain"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceStringValue: "null"
      PreferenceValue: "null"
  - id: "SetDomainPreference2"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      Type: "String"
      DefaultPreferenceValue: "off"
    bindings:
      PreferenceDomain: "CurrentChannel:Domain"
      PreferenceStringValue: "CaptchaSettingsForm:get(PreferenceKey):Value"
  - id: "SetFormParameterValue3"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      Value: "Preference:StringValue"
      FormParameter: "CaptchaSettingsForm:get(PreferenceKey)"
  - id: "StartSafeChangesBlock1"
    type: "pipelet"
    ref: "StartSafeChangesBlock"
  - id: "TextNode1"
    type: "text"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    config:
      Trim: true
    bindings:
      Form: "CaptchaSettingsForm"

links:
  - from: "SetDictionaryValue7"
    via: "next"
    to: "JoinNode8"
    into: "in3"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "ValidateForm1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "CallNode4"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "ValidateForm1"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "GetDomainPreference3"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetDomainPreference1"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "GetDomainPreference3"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "SetDomainPreference1"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "LoopNode3"
    via: "do"
    to: "SetDomainPreference2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue7"
    into: "in"
  - from: "SetDomainPreference2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "JoinNode1"
    via: "next"
    to: "SetDomainPreference1"
    into: "in"
  - from: "SetDomainPreference1"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "JoinNode2"
    via: "next"
    to: "AddEntryToMap3"
    into: "in"
  - from: "SetFormParameterValue3"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "LoopNode4"
    into: "loop"
  - from: "GetDomainPreference1"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode6"
    into: "in3"
  - from: "SetDomainPreference2"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "CallNode1"
    via: "next"
    to: "StartSafeChangesBlock1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "StartSafeChangesBlock1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "GetDomainPreferenceNamesByPreferenceGroup3"
    into: "in"
  - from: "GetDomainPreferenceNamesByPreferenceGroup3"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "EndSafeChangesBlock1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "StartNode5"
    via: "next"
    to: "CreateForm3"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "LoopNode4"
    via: "do"
    to: "GetDomainPreference3"
    into: "in"
  - from: "AddEntryToMap3"
    via: "next"
    to: "AddFormParameterDefinition3"
    into: "in"
  - from: "AddFormParameterDefinition3"
    via: "next"
    to: "SetFormParameterValue3"
    into: "in"
  - from: "CreateForm3"
    via: "next"
    to: "LoopNode4"
    into: "in"
  - from: "LoopNode4"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "EndSafeChangesBlock1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "LoopNode3"
    via: "next"
    to: "JoinNode3"
    into: "in1"
