flow: "ViewChannelPriceListUserGroupSelection"
kind: "view"

entries:
  - id: "Start1"
    name: "SelectUserGroup"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start31"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "AssignUserGroupsToPriceList"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call5"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call7"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode1"
    type: "call"
  - id: "CallNode2"
    type: "call"
  - id: "CallNode3"
    type: "call"
    ref: "ViewChannelPriceListUserGroupSelection-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ViewChannelPriceListUserGroupSelection-Prefix"
  - id: "CallNode5"
    type: "call"
    ref: "ViewChannelPriceListUserGroupSelection-Prefix"
  - id: "CallNode7"
    type: "call"
  - id: "CheckForEmptyIterator1"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "UUIDIterator"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      Concatenated: "ProcessPriceListUserGroups"
      String0: "\"ProcessPriceListUserGroups_\""
      String2: "\"-AssignUserGroupsToPriceList\""
      String1: "CurrentChannel:TypeCode"
  - id: "ConcatenateStrings2"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      Concatenated: "ProcessPriceListUserGroups"
      String0: "\"ProcessPriceListUserGroups_\""
      String2: "\"-SearchUserGroups\""
      String1: "CurrentChannel:TypeCode"
  - id: "ConcatenateStrings3"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      Concatenated: "ProcessPriceListUserGroups"
      String0: "\"ProcessPriceListUserGroups_\""
      String2: "\"-GetAssignedUserMap\""
      String1: "CurrentChannel:TypeCode"
  - id: "Decision1"
    type: "decision"
    condition: "PageNumber"
  - id: "DispatchFormAction3"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelPriceListUserGroupSelection-AssignUserGroupsToPriceList"
      PagingPipeline: "ViewChannelPriceListUserGroupSelection-Paging"
      OutValue_9: "ViewChannelPriceListUserGroups-Paging"
      OutValue_1: "ViewChannelPriceListUserGroups-Paging"
    bindings:
      Key_0: "assign"
      SelectionKey: "JumpTarget"
      Key_9: "backToList"
      Key_1: "cancel"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "GetPageLocator11"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "PriceListConsumerGroupSelection"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocatorName: "null"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "UserGroups"
      PageableID: "PageLocator:PageableID"
  - id: "GetPriceListByUUID1"
    type: "pipelet"
    ref: "GetPriceListByUUID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "Jump21"
    type: "jump"
    ref: "ViewChannelPriceListUserGroups-ListAll"
  - id: "Jump22"
    type: "jump"
    ref: "ViewChannelPriceListUserGroupSelection-Paging"
  - id: "Jump4"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "PrepareApplicationView12"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelCatalogs"
      WorkingTemplate: "pricelist/PriceListSelectUserGroups"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "UserGroups"
  - id: "SetPage3"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "UserGroups"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewChannelPriceListUserGroupSelection-Paging"
      DefaultPageLocatorName: "PriceListConsumerGroupSelection"
    bindings:
      HandlerPipeline: "null"
      PageLocatorName: "null"
      Pageable: "UserGroups"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      Locale: "null"
      LocalizedString: "PageNumber"
      Pattern: "null"

links:
  - from: "GetPageLocator11"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "SetPage2"
    via: "next"
    to: "Join5"
    into: "in3"
  - from: "SetPage3"
    via: "next"
    to: "Join5"
    into: "in2"
  - from: "Decision1"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "GetPageLocator11"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetPriceListByUUID1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "SetPage2"
    into: "in"
  - from: "SetPageLocator1"
    via: "next"
    to: "PrepareApplicationView12"
    into: "in"
  - from: "Start31"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "GetPageLocator11"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "ConcatenateStrings3"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "GetPriceListByUUID1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "ConcatenateStrings2"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "PrepareApplicationView12"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage3"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "CallNode4"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CheckForEmptyIterator1"
    via: "error"
    to: "Jump22"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "ConcatenateStrings3"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "CheckForEmptyIterator1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "Jump21"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "ConcatenateStrings2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "DispatchFormAction3"
    into: "in"
  - from: "DispatchFormAction3"
    via: "next"
    to: "Jump4"
    into: "in"
