flow: "ViewOrderStatusImportScheduling"
kind: "view"

entries:
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode2"
    type: "call"
    ref: "ProcessJobScheduling-Update"
  - id: "CallNode3"
    type: "call"
    ref: "ViewOrderStatusImport-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ViewOrderStatusImport-Prefix"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_1: "ViewOrderStatusImportScheduling-Update"
      OutValue_2: "ViewOrderStatusImportScheduling-Edit"
    bindings:
      SelectionKey: "JumpTarget"
      Key_1: "update"
      Key_2: "reset"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "Jump5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewOrderStatusImportScheduling-Edit"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Config:JobConfiguration"
      OutValue_1: "JobConfiguration"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Orders"
      WorkingTemplate: "order/OrderStatusImportScheduling"

links:
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode3"
    into: "in"
