flow: "ViewChannelInformation_32"
kind: "view"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call2"
    type: "call"
    ref: "ProcessChannelPermission-GetAccessRoles"
  - id: "Call3"
    type: "call"
    ref: "ProcessUserList-ByFilter"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessGlobalNavigationBar-GetChannelPermissions"
  - id: "CreatePageableFromIterator1"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    bindings:
      Iterator: "Organizations"
      Pageable: "Organizations"
  - id: "GetDomainByName1"
    type: "pipelet"
    ref: "GetDomainByName"
    bindings:
      DomainName: "\"SLDSystem\""
  - id: "GetOrganizations3"
    type: "pipelet"
    ref: "GetOrganizations"
    bindings:
      OrganizationType: "null"
      Owner: "Repository:RepositoryDomain"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "AccessRoles"
      InValue_2: "Repository:OwningDomain:Domain"
      OutValue_1: "UserGroups"
      OutValue_2: "UserDomain"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ChannelID"
      OutValue_1: "RepositoryUUID"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "GetChannelTypeByID"
    bindings:
      ChannelType: "RepositoryType"
      ChannelTypeID: "Repository:TypeCode"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "PartnerBO"
      WorkingTemplate: "channel/ChannelInformation_32"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Filter"
      Value: "ProcessUserList-UserGroupsFilter"
  - id: "UpdatePageSize1"
    type: "pipelet"
    ref: "UpdatePageSize"
    config:
      DefaultPageSize: 1000
    bindings:
      PageSize: "null"
      PageableIterator: "Users"

links:
  - from: "UpdatePageSize1"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "CreatePageableFromIterator1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "GetOrganizations3"
    via: "next"
    to: "GetDomainByName1"
    into: "in"
  - from: "GetDomainByName1"
    via: "next"
    to: "CreatePageableFromIterator1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "UpdatePageSize1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "GetOrganizations3"
    into: "in"
