flow: "ViewCheckoutShipping"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Review"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "ContinueCheckout"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "AdjustedEntryPoint"
    mode: "include"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode0"
    type: "call"
    ref: "ProcessCart-Calculate"
    bindings:
      Cart: "CurrentCart"
  - id: "CallNode1"
    type: "call"
    ref: "ViewCheckoutShipping-Prefix"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessShipping-ProcessGiftOptionMarkers"
  - id: "CallNode12"
    type: "call"
    ref: "ProcessShipping-CreateShippingForm"
  - id: "CallNode13"
    type: "call"
    ref: "ProcessShipping-ValidateShippingForm"
  - id: "CallNode14"
    type: "call"
    ref: "ProcessShipping-StartHook"
    bindings:
      Basket: "CurrentCart"
  - id: "CallNode15"
    type: "call"
    ref: "ProcessShipping-SetShippingMethods"
  - id: "CallNode16"
    type: "call"
    ref: "ProcessGiftingPreferences-GetGiftingPreferences"
    bindings:
      PreferenceDomain: "Repository:Domain"
  - id: "CallNode17"
    type: "call"
    ref: "ProcessCheckout-AdjustJumpStep"
  - id: "CallNode18"
    type: "call"
    ref: "FireTrackingEvents-View"
    bindings:
      PageName: "\"shipping\""
      PageType: "\"checkout\""
  - id: "CallNode2"
    type: "call"
    ref: "ViewCheckoutShipping-Prefix"
  - id: "CallNode20"
    type: "call"
    ref: "ProcessCheckout-Safe_CheckInventory"
    bindings:
      AppContext: "CurrentAppContext"
      BasketBORepository: "ApplicationBO:Extension(\"Basket\"):getBasketBORepository(CurrentOrganization)"
      Organization: "CurrentOrganization"
      PreferenceDomain: "CurrentProductRepository:Domain"
      User: "CurrentUser"
  - id: "CallNode3"
    type: "call"
    ref: "ViewCheckout-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ViewCheckoutShipping-Prefix"
  - id: "CallNode5"
    type: "call"
    ref: "ViewCheckoutShipping-Prefix"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessCheckout-DefaultSettings"
    bindings:
      Cart: "CurrentCart"
      Domain: "CurrentDomain"
      User: "CurrentUser"
  - id: "CallNode7"
    type: "call"
    ref: "ViewCheckoutShipping-Prefix"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessShipping-SetShippingMethods"
  - id: "CallNode9"
    type: "call"
    ref: "ViewData-SecureForBrowserBack"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewCheckoutShipping-ContinueCheckout"
      OutValue_1: "ViewCheckoutShipping-Update"
    bindings:
      Key_0: "continue"
      Key_1: "update"
      SelectionKey: "JumpTarget"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "Jump1"
    type: "jump"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewCheckoutGifting-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewCheckoutShipping-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewCheckoutShipping-Review"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewCheckoutPayment-Start"
  - id: "JumpNode5"
    type: "jump"
    ref: "ViewPage-Start"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "CurrentRequest:PipelineDictionary"
      InValue_3: "\"systempage.checkout.shipping.pagelet2-systempage.checkout.shipping\""
      InValue_2: "\"checkout/shipping/CheckoutShipping\""
      OutValue_1: "Dictionary"
      OutValue_3: "PageletEntryPointID"
      OutValue_2: "WorkingTemplate"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpStep"
      Value: 2
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue9"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewCheckoutShipping-Review"
  - id: "VerifyInteger2"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      LocalizedString: "\"2\""
      IntegerObject: "CurrentStep"

links:
  - from: "CallNode0"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "CallNode11"
    via: "toGiftOption"
    to: "JumpNode1"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode13"
    via: "ERROR"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode13"
    via: "next"
    to: "CallNode15"
    into: "in"
  - from: "CallNode14"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode15"
    via: "ERROR"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode15"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "CallNode16"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CallNode17"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode18"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode20"
    via: "next"
    to: "CallNode17"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "VerifyInteger2"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "CallNode0"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "JumpNode2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "CallNode20"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "SetDictionaryValue9"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "CallNode16"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "SetDictionaryValue9"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode18"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "VerifyInteger2"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "VerifyInteger2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
