flow: "ViewProductFilter"
kind: "view"

entries:
  - id: "Start1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Remove"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "New"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "Create"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "Update"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "CreateWebform"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "StartSelectCategory"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "SetCategory"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "ParametricSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "ExistsProductFilter"
    mode: "private"
    strict: true
    inputs:
      - key: "Name"
        type: "java.lang.String"
        required: true

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessProductFilter-UpdateClipboard"
  - id: "Call14"
    type: "call"
    ref: "ViewProductFilter-Prefix"
  - id: "Call16"
    type: "call"
    ref: "ProcessProductFilter-Create"
    bindings:
      Locale: "Locale"
      ID: "Form:ProductFilterID:Value"
      Domain: "ChannelRepository:Domain"
      DisplayName: "Form:ProductFilterDisplayName:Value"
      Description: "Form:ProductFilterDescription:Value"
      SQDForm: "SQDForm"
  - id: "Call17"
    type: "call"
    ref: "ViewProductFilter-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ProcessProductFilter-Remove"
  - id: "Call5"
    type: "call"
    ref: "ViewProductFilter-Prefix"
  - id: "Call7"
    type: "call"
    ref: "ViewProductFilter-Prefix"
  - id: "CallNode1"
    type: "call"
    ref: "ViewProductFilter-CreateWebform"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessProductFilter-Get"
  - id: "CallNode3"
    type: "call"
    ref: "ViewProductFilter-CreateWebform"
  - id: "CallNode4"
    type: "call"
    ref: "ViewProductFilter-CreateWebform"
  - id: "CallNode5"
    type: "call"
    ref: "ViewProductFilter-CreateWebform"
  - id: "CallNode6"
    type: "call"
    ref: "ViewProductFilter-ExistsProductFilter"
    bindings:
      Name: "Form:ProductFilterID:Value"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "SQDForm"
      FormResourceFile: "ShippingMethodForm"
      FormResource: "SearchQueryDefinition"
    bindings:
      CurrentDomain: "CurrentDomain"
      Form: "SQDForm"
  - id: "CreateForm4"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "ProductFilterForm"
      FormResourceFile: "ShippingMethodForm"
      FormResource: "ProductFilter"
    bindings:
      CurrentDomain: "CurrentDomain"
      Form: "Form"
  - id: "Decision8"
    type: "decision"
    condition: "confirmDelete"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Form:ProductFilterID:Value"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ErrorCode"
  - id: "DecisionNode3"
    type: "decision"
    condition: "ProductFilter"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProductFilterList-Paging"
      OutValue_1: "ViewProductFilter-Create"
      OutValue_2: "ViewProductFilter-Update"
      OutValue_3: "ViewProductFilter-Edit"
      OutValue_4: "ViewProductFilter-Remove"
      OutValue_6: "ViewProductFilter-Remove"
      OutValue_7: "ViewProductFilter-New"
      OutValue_9: "ViewProductFilter-StartSelectCategory"
      OutValue_8: "ViewProductFilter-SetCategory"
    bindings:
      Key_0: "backToList"
      Key_1: "create"
      Key_2: "update"
      Key_3: "cancelConfirm"
      Key_4: "delete"
      Key_6: "confirmDelete"
      Key_7: "switchLanguage"
      SelectionKey: "JumpTarget"
      Key_9: "StartSelectFilterCategory"
      Key_8: "SetCategory"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "GetLocale3"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetSearchQueryDefinition1"
    type: "pipelet"
    ref: "GetSearchQueryDefinition"
    bindings:
      SearchQueryDefinition: "ProductFilter"
      Domain: "ChannelRepository:Domain"
      UUID: "ProductFilterUUID"
  - id: "GetSearchQueryDefinition2"
    type: "pipelet"
    ref: "GetSearchQueryDefinition"
    bindings:
      SearchQueryDefinition: "ProductFilter"
      Domain: "ChannelRepository:Domain"
      UUID: "ProductFilterUUID"
  - id: "GetSearchQueryDefinition3"
    type: "pipelet"
    ref: "GetSearchQueryDefinition"
    bindings:
      SearchQueryDefinition: "ProductFilter"
      Domain: "ChannelRepository:Domain"
      UUID: "ProductFilterUUID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd4"
    type: "interaction"
  - id: "InvalidatePageLocatorPageable2"
    type: "pipelet"
    ref: "InvalidatePageLocatorPageable"
    config:
      DefaultPageLocatorName: "ProductFiltersListViewLocator"
  - id: "InvalidatePageLocatorPageable3"
    type: "pipelet"
    ref: "InvalidatePageLocatorPageable"
    config:
      DefaultPageLocatorName: "ProductFiltersListViewLocator"
  - id: "Join6"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump16"
    type: "jump"
    ref: "ViewProductFilter-Edit"
  - id: "Jump3"
    type: "jump"
    ref: "ViewProductFilterList-ListAll"
  - id: "Jump4"
    type: "jump"
    ref: "ViewProductFilter-Edit"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewProductFilter-Edit"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewProductFilter-Edit"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewProductParametricSearch-SelectCatalog"
  - id: "JumpNode5"
    type: "jump"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "\"false\""
      OutValue_1: "DivideByProxyFlag"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ProductFilter:UUID"
      OutValue_1: "ProductFilterUUID"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ProductFilters"
      WorkingTemplate: "productfilter/ProductFilter"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ProductFilters"
      WorkingTemplate: "productfilter/ProductFilter"
  - id: "PrepareSearchQueryDefinitionForm1"
    type: "pipelet"
    ref: "PrepareSearchQueryDefinitionForm"
    bindings:
      Form: "SQDForm"
      PersistentSearchQuery: "ProductFilter"
      SearchQueryDefinition: "ProductFilter"
  - id: "RemovePageLocator1"
    type: "pipelet"
    ref: "RemovePageLocator"
    config:
      DefaultPageLocatorName: "ProductList"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: "ProductFilterIDNotUnique"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ProductAssignmentMode"
      Value: "Dynamic"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewProductFilterList-ListAll"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: "ProductFilterNotCreated"
  - id: "SetDictionaryValue5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCode"
      Value: "ProductFilterIDNotUnique"
  - id: "SetFormError1"
    type: "pipelet"
    ref: "SetFormError"
    bindings:
      TargetObject: "Form:ProductFilterID"
      ErrorMsg: "\"error.required\""
  - id: "UpdateSearchQueryDefinition1"
    type: "pipelet"
    ref: "UpdateSearchQueryDefinition"
    bindings:
      Description: "Form:ProductFilterDescription:Value"
      DisplayName: "Form:ProductFilterDisplayName:Value"
      Name: "null"
      SearchQueryDefinition: "ProductFilter"
      Form: "SQDForm"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "Form"
  - id: "ValidateForm2"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "Form"
  - id: "ValidateForm3"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "SQDForm"
  - id: "ValidateForm4"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "SQDForm"

links:
  - from: "ValidateForm2"
    via: "error"
    to: "Join6"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "CreateForm4"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "ValidateForm1"
    via: "next"
    to: "ValidateForm3"
    into: "in"
  - from: "Decision8"
    via: "yes"
    to: "Jump16"
    into: "in"
  - from: "CallNode6"
    via: "Yes"
    to: "SetDictionaryValue5"
    into: "in"
  - from: "UpdateSearchQueryDefinition1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "Call1"
    via: "next"
    to: "Decision8"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "InvalidatePageLocatorPageable3"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "ValidateForm4"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "ValidateForm4"
    into: "in"
  - from: "SetFormError1"
    via: "next"
    to: "JoinNode6"
    into: "in2"
  - from: "Call17"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "GetSearchQueryDefinition2"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "GetLocale3"
    into: "in"
  - from: "CreateForm4"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Call16"
    via: "ERROR"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "GetLocale3"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "GetSearchQueryDefinition1"
    into: "in"
  - from: "GetSearchQueryDefinition3"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "ValidateForm3"
    via: "next"
    to: "UpdateSearchQueryDefinition1"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "PrepareSearchQueryDefinitionForm1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "Call17"
    into: "in"
  - from: "UpdateSearchQueryDefinition1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "GetSearchQueryDefinition1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode8"
    into: "in3"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "GetSearchQueryDefinition2"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "Call14"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "ValidateForm1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "Start8"
    via: "next"
    to: "Call14"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "ValidateForm4"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "Call16"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "RemovePageLocator1"
    into: "in"
  - from: "InvalidatePageLocatorPageable3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "ValidateForm2"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode7"
    into: "in2"
  - from: "SetDictionaryValue5"
    via: "next"
    to: "JoinNode9"
    into: "in2"
  - from: "PrepareSearchQueryDefinitionForm1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "ValidateForm2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "SetFormError1"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "StartNode4"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "RemovePageLocator1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd4"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "InvalidatePageLocatorPageable2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "Jump4"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "InvalidatePageLocatorPageable2"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "ValidateForm3"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "StartNode6"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "EndNode3"
    into: "in"
  - from: "CallNode6"
    via: "No"
    to: "Call16"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "EndNode2"
    into: "in"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "Decision8"
    via: "no"
    to: "GetSearchQueryDefinition3"
    into: "in"
