flow: "ViewChannelPermissionList"
kind: "view"

entries:
  - id: "Start1"
    name: "Error"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start10"
    name: "Back"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "UserListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "SelectType"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "MasterRoleListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "DepartmentRoleListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "Remove"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "SelectAccessRoles"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessChannelPermissionList-GetAssignedUsers"
  - id: "Call10"
    type: "call"
    ref: "ViewChannelPermissionWizard-UpdateUserClipboard"
  - id: "Call11"
    type: "call"
    ref: "ViewChannelPermissionWizard-UpdateMRClipboard"
  - id: "Call2"
    type: "call"
    ref: "ProcessPersonalizationGroup-Update"
  - id: "Call3"
    type: "call"
    ref: "ProcessChannelPermissionList-GetAccessRolesForUsers"
  - id: "Call4"
    type: "call"
    ref: "ProcessChannelPermissionList-DepartmentRoleListAll"
  - id: "Call6"
    type: "call"
    ref: "ProcessChannelPermissionList-MasterRoleListAll"
  - id: "Call9"
    type: "call"
    ref: "ProcessChannelPermissionList-Remove"
  - id: "CreateIteratorForPrefix1"
    type: "pipelet"
    ref: "CreateIteratorForPrefix"
    config:
      Prefix: "UserUUID"
  - id: "CreateIteratorForPrefix2"
    type: "pipelet"
    ref: "CreateIteratorForPrefix"
    config:
      Prefix: "RoleID"
  - id: "CreateIteratorForPrefix3"
    type: "pipelet"
    ref: "CreateIteratorForPrefix"
    config:
      Prefix: "RoleID"
  - id: "Decision1"
    type: "decision"
    condition: "PermissionType"
  - id: "Decision10"
    type: "decision"
    condition: "PermissionType"
  - id: "Decision2"
    type: "decision"
    condition: "PermissionType"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelPermissionWizard-Dispatch"
      OutValue_1: "ViewChannelPermissionList-Remove"
      OutValue_2: "ViewChannelPermissionList-SelectType"
      OutValue_3: "ViewChannelPermissionList-Back"
      OutValue_4: "ViewChannelPermissionList-SelectAccessRoles"
      OutValue_5: "ViewChannelPermissionList-UserListAll"
      OutValue_6: "ViewChannelPermissionList-MasterRoleListAll"
      OutValue_7: "ViewChannelPermissionList-DepartmentRoleListAll"
      OutValue_8: "ViewChannelPermissionList-SelectType"
    bindings:
      Key_0: "new"
      Key_1: "remove"
      Key_2: "confirmRemove"
      Key_3: "backToList"
      Key_4: "next"
      Key_5: "cancelUser"
      Key_6: "cancelDMR"
      Key_7: "cancelDR"
      Key_8: "selectType"
      SelectionKey: "JumpTarget"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ChannelList"
      RestorePageLocatorDictionary: "True"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "InteractionEnd4"
    type: "interaction"
  - id: "InteractionEnd5"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Jump14"
    type: "jump"
    ref: "ViewChannelPermissionWizard-SelectAccessRoles"
  - id: "Jump16"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump2"
    type: "jump"
    ref: "ViewChannelPermissionList-DepartmentRoleListAll"
  - id: "Jump3"
    type: "jump"
    ref: "ViewChannelPermissionList-MasterRoleListAll"
  - id: "Jump4"
    type: "jump"
    ref: "ViewChannelPermissionList-Error"
  - id: "Jump5"
    type: "jump"
    ref: "ViewChannelPermissionList-UserListAll"
  - id: "Jump6"
    type: "jump"
    ref: "ViewChannelPermissionList-Error"
  - id: "Jump7"
    type: "jump"
    ref: "ViewChannelPermissionList-SelectType"
  - id: "Jump8"
    type: "jump"
  - id: "Jump9"
    type: "jump"
    ref: "ViewChannelList-ListAll"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Channels"
      WorkingTemplate: "channel/ChannelPermissionList.isml"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Channels"
      WorkingTemplate: "channel/ChannelPermissionList.isml"
  - id: "PrepareApplicationView4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Channels"
      WorkingTemplate: "application/Error"
  - id: "PrepareApplicationView5"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Channels"
      WorkingTemplate: "channel/ChannelPermissionList.isml"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "OutVector"

links:
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "CreateIteratorForPrefix2"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "CreateIteratorForPrefix3"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "CreateIteratorForPrefix1"
    into: "in"
  - from: "CreateIteratorForPrefix1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "CreateIteratorForPrefix3"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Decision10"
    via: "yes"
    to: "Call11"
    into: "in"
  - from: "Call11"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "Join1"
    via: "next"
    to: "Jump14"
    into: "in"
  - from: "Decision10"
    via: "no"
    to: "Call10"
    into: "in"
  - from: "Call6"
    via: "ERROR"
    to: "Jump4"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump16"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "Decision10"
    into: "in"
  - from: "Start10"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "Jump8"
    into: "in"
  - from: "GetPageLocator1"
    via: "error"
    to: "Jump9"
    into: "in"
  - from: "PrepareApplicationView4"
    via: "next"
    to: "InteractionEnd5"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "PrepareApplicationView4"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "PrepareApplicationView5"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "PrepareApplicationView5"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Jump7"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Decision2"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd4"
    into: "in"
  - from: "Call4"
    via: "ERROR"
    to: "Jump6"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "CreateIteratorForPrefix2"
    into: "in"
