flow: "ViewJournalLifetimePreferences"
kind: "com.intershop.component.organization.capi.Organization"

entries:
  - id: "StartNode3"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "InitFormData"
    mode: "private"
    strict: true
    inputs:
      - key: "Organization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true
      - key: "Form"
        type: "com.intershop.beehive.core.capi.webform.Form"
        required: false
      - key: "OrganizationDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
  - id: "StartNode6"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessJournal-CleanUpJournal"
    bindings:
      Domain: "MasterRepository:RepositoryDomain"
  - id: "CallNode3"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "CallNode4"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "CallNode5"
    type: "call"
    ref: "This:InitFormData"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "JournalLifetimePreferencesForm"
      FormResource: "JournalLifetimePreferences"
  - id: "CreateForm2"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "JournalLifetimePreferencesForm"
      FormResource: "JournalLifetimePreferences"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Form:JournalState:Value"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Form:JournalLifetime:Value"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Form:JournalState:Value"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewJournalLifetimePreferences-Start"
      OutValue_1: "ViewJournalLifetimePreferences-Update"
    bindings:
      Key_0: "reset"
      Key_1: "update"
      OutValue_0: "null"
      OutValue_1: "null"
      SelectionKey: "JumpTarget"
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "GetRepository1"
    type: "pipelet"
    ref: "GetRepository"
    config:
      CustomRepositoryTypeCode: 21
      Type: "Custom Repository"
    bindings:
      Repository: "MasterRepository"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode17"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "Jump6"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Pipelet12"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "JournalState"
      Type: "Integer"
    bindings:
      PreferenceDomain: "Organization:Domain"
      PreferenceIntValue: "JournalState"
  - id: "Pipelet13"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Preferences"
      WorkingTemplate: "product/JournalLifetimePreference"
  - id: "Pipelet15"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "JournalLifetime"
      Type: "Integer"
      DefaultPreferenceValue: 24
    bindings:
      PreferenceDomain: "Organization:Domain"
      PreferenceIntValue: "Form:JournalLifetime:Value"
  - id: "Pipelet16"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "JournalState"
      DefaultPreferenceValue: 1
      Type: "Integer"
    bindings:
      PreferenceDomain: "Organization:Domain"
      PreferenceIntValue: "Form:JournalState:Value"
  - id: "Pipelet18"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "JournalLifetime"
      Type: "Integer"
    bindings:
      PreferenceDomain: "Organization:Domain"
      PreferenceIntValue: "JournalLifetime"
  - id: "SetDictionaryValue7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewJournalLifetimePreferences-Start"
  - id: "SetFormError1"
    type: "pipelet"
    ref: "SetFormError"
    bindings:
      TargetObject: "Form:JournalLifetime"
      ErrorMsg: "\"JournalLifetimeUndefined\""
  - id: "SetFormParameterValue1"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      FormParameter: "Form:JournalState"
      Value: "JournalState"
  - id: "SetFormParameterValue2"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      FormParameter: "Form:JournalLifetime"
      Value: "JournalLifetime"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"

links:
  - from: "CreateForm2"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "SetFormError1"
    into: "in"
  - from: "SetFormError1"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "GetRepository1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "JoinNode14"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode13"
    via: "next"
    to: "JoinNode12"
    into: "in3"
  - from: "DecisionNode3"
    via: "yes"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "Pipelet15"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue7"
    into: "in"
  - from: "Pipelet16"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "GetRepository1"
    into: "in"
  - from: "GetRepository1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode13"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "Jump6"
    into: "in"
  - from: "SetDictionaryValue7"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "CallNode5"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "StartNode6"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "JoinNode12"
    via: "next"
    to: "Pipelet13"
    into: "in"
  - from: "Pipelet13"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "Pipelet12"
    via: "next"
    to: "Pipelet18"
    into: "in"
  - from: "ValidateForm1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode11"
    via: "next"
    to: "SetFormParameterValue2"
    into: "in"
  - from: "Pipelet15"
    via: "error"
    to: "JoinNode13"
    into: "in2"
  - from: "Pipelet16"
    via: "error"
    to: "JoinNode14"
    into: "in1"
  - from: "CallNode4"
    via: "next"
    to: "Pipelet16"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CreateForm2"
    into: "in"
  - from: "Pipelet15"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode2"
    into: "in3"
  - from: "StartNode3"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Pipelet12"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "DecisionNode2"
    into: "in"
  - from: "Pipelet18"
    via: "error"
    to: "JoinNode17"
    into: "in2"
  - from: "Pipelet18"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "SetFormParameterValue2"
    via: "next"
    to: "SetFormParameterValue1"
    into: "in"
  - from: "Pipelet12"
    via: "error"
    to: "JoinNode17"
    into: "in1"
  - from: "JoinNode17"
    via: "next"
    to: "JoinNode11"
    into: "in2"
  - from: "SetFormParameterValue1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "ValidateForm1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode14"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode2"
    into: "in1"
