flow: "ViewReplicationGroupList_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Assign"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Select"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "List"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CheckForEmptyIterator2"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "SelectedReplicationGroups"
  - id: "CombineIterators2"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Concatenate Iterators and Remove Duplicates"
    bindings:
      Iterator: "ReplicationGroups"
      Iterator1: "SelectedReplicationGroups"
      Iterator2: "ReplicationTask:ReplicationGroups"
  - id: "CombineIterators3"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Subtract Iterators and Remove Duplicates"
    bindings:
      Iterator: "ReplicationGroups"
      Iterator1: "ReplicationTask:ReplicationGroups"
      Iterator2: "SelectedReplicationGroups"
  - id: "Decision1"
    type: "decision"
    condition: "ReplicationTask:ReplicationGroups"
  - id: "Decision5"
    type: "decision"
    condition: "ConfirmDelete"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ReplicationTask:State"
  - id: "DecisionNode3"
    type: "decision"
    condition: "ReplicationTask:State"
  - id: "GetFormSelection2"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedReplicationGroup"
    bindings:
      ParameterName: "null"
  - id: "GetFormSelection3"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedReplicationGroup"
    bindings:
      ParameterName: "null"
      Selection: "SelectedReplicationGroups"
  - id: "GetFormSelection4"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "ReplicationGroup"
    bindings:
      ParameterName: "null"
      Selection: "SelectedReplicationGroups"
  - id: "GetReplicationGroupConfiguration1"
    type: "pipelet"
    ref: "GetReplicationGroupConfiguration"
  - id: "GetReplicationGroups1"
    type: "pipelet"
    ref: "GetReplicationGroups"
    bindings:
      BusinessUnitType: "CurrentChannel:TypeCode"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewReplicationGroupList_52-List"
  - id: "Jump2"
    type: "jump"
    ref: "ViewReplicationGroupList_52-List"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewReplicationTaskList_52-List"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewReplicationTaskList_52-List"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewReplicationTaskList_52-List"
  - id: "JumpNode5"
    type: "jump"
    ref: "ViewReplicationTaskList_52-List"
  - id: "JumpNode6"
    type: "jump"
    ref: "ViewReplicationGroupList_52-Select"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "SelectedReplicationGroups"
      OutValue_1: "ReplicationGroups"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewReplicationTaskList_52-Paging"
      OutValue_1: "ViewReplicationGroupList_52-Select"
      OutValue_2: "ViewReplicationGroupList_52-Assign"
      OutValue_3: "ViewReplicationGroupList_52-List"
      OutValue_4: "ViewReplicationGroupList_52-List"
      OutValue_5: "ViewReplicationGroupList_52-Delete"
    bindings:
      Key_0: "Cancel"
      Key_1: "Select"
      Key_2: "Assign"
      Key_3: "Back"
      Key_4: "ConfirmDelete"
      Key_5: "Delete"
      SelectionKey: "JumpTarget"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "MassDataTasks"
      WorkingTemplate: "replication/ReplicationGroupList_52"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "MassDataTasks"
      WorkingTemplate: "replication/ReplicationGroupSelection_52"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "GetReplicationTaskByUUID"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "GetReplicationTaskByUUID"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "GetReplicationTaskByUUID"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "GetReplicationTaskByUUID"
  - id: "UpdateCustomAttribute1"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    config:
      DefaultAttributeName: "ReplicationGroups"
      DefaultAttributeType: "MultipleString"
    bindings:
      AttributeName: "null"
      AttributeType: "null"
      AttributeValue: "ReplicationGroups"
      ExtensibleObject: "ReplicationTask"
      LocaleInformation: "null"
  - id: "UpdateCustomAttribute2"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    config:
      DefaultAttributeName: "ReplicationGroups"
      DefaultAttributeType: "MultipleString"
    bindings:
      AttributeName: "null"
      AttributeType: "null"
      AttributeValue: "ReplicationGroups"
      ExtensibleObject: "ReplicationTask"
      LocaleInformation: "null"

links:
  - from: "Pipelet1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "GetReplicationGroups1"
    into: "in"
  - from: "CheckForEmptyIterator2"
    via: "error"
    to: "JumpNode6"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "GetFormSelection4"
    into: "in"
  - from: "Decision5"
    via: "no"
    to: "Join5"
    into: "in3"
  - from: "GetFormSelection2"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Decision5"
    via: "yes"
    to: "GetFormSelection2"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "Decision5"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "GetReplicationGroupConfiguration1"
    into: "in"
  - from: "Pipelet7"
    via: "error"
    to: "JumpNode5"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet7"
    via: "next"
    to: "GetFormSelection3"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "UpdateCustomAttribute1"
    via: "next"
    to: "Join3"
    into: "in2"
  - from: "UpdateCustomAttribute1"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "Join3"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "UpdateCustomAttribute2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "UpdateCustomAttribute2"
    via: "next"
    to: "Join4"
    into: "in2"
  - from: "UpdateCustomAttribute2"
    via: "error"
    to: "Join4"
    into: "in1"
  - from: "Pipelet2"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "GetFormSelection4"
    via: "next"
    to: "CheckForEmptyIterator2"
    into: "in"
  - from: "CombineIterators2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetFormSelection3"
    via: "next"
    to: "CombineIterators3"
    into: "in"
  - from: "CombineIterators3"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "CombineIterators2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "KeyMapper1"
    into: "in"
  - from: "CheckForEmptyIterator2"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "Join3"
    into: "in3"
  - from: "Pipelet3"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "Join4"
    into: "in3"
  - from: "GetReplicationGroups1"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "GetReplicationGroupConfiguration1"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "UpdateCustomAttribute1"
    into: "in"
  - from: "Pipelet4"
    via: "error"
    to: "JumpNode2"
    into: "in"
  - from: "Pipelet5"
    via: "error"
    to: "JumpNode3"
    into: "in"
  - from: "Pipelet6"
    via: "error"
    to: "JumpNode4"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "Pipelet5"
    into: "in"
