flow: "ViewImageMapping_32"
kind: "view"

entries:
  - id: "Start1"
    name: "GetImageMappingRules"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewImageMapping_32-Prefix"
  - id: "Call10"
    type: "call"
    ref: "ViewImageMapping_32-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ProcessProductDataMappingRule-DeleteRuleConstruct"
  - id: "Call5"
    type: "call"
    ref: "ProcessProductDataMappingRule-CreateRuleConstruct"
  - id: "CallNode1"
    type: "call"
    ref: "ViewImageMapping_32-GetImageMappingRules"
  - id: "CheckForEmptyString1"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "ChannelID"
  - id: "Decision1"
    type: "decision"
    condition: "mappingEnabled"
  - id: "Decision2"
    type: "decision"
    condition: "ProductDataMappingRuleID"
  - id: "Decision3"
    type: "decision"
    condition: "ProductDataMappingRuleID"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "GetProductDataMappingRuleSet1"
    type: "pipelet"
    ref: "GetProductDataMappingRuleSet"
    bindings:
      DeclaringDomain: "CurrentChannel:RepositoryDomain"
      ProvidingDomain: "ProvidingRepository:Domain"
  - id: "GetProductDataMappingRules1"
    type: "pipelet"
    ref: "GetProductDataMappingRules"
    bindings:
      DeclaringDomain: "ProductDataMappingRuleSet:DeclaringDomain"
      ProvidingDomain: "ProductDataMappingRuleSet:ProvidingDomain"
      ProductDataMappingRulesMap: "null"
      ProductDataMappingRules: "ProductImageDataMappingRules"
      TypeCode: "\"13\""
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "ProvidingRepository"
      UUID: "ProviderID"
  - id: "GetRepositoryByUUID2"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "CurrentSelectedChannel"
      UUID: "ChannelID"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewProductAttributeMapping_32-Start"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "FunctionClassName"
      Value: "com.intershop.component.mvc.capi.mapping.ProductImageMappingRule"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "TypeCode"
      Value: 13
      ValueType: "Dictionary Value"

links:
  - from: "Decision1"
    via: "yes"
    to: "Decision3"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "Join3"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "JoinNode1"
    into: "in1"
  - from: "Call1"
    via: "next"
    to: "GetProductDataMappingRules1"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "error"
    to: "Join2"
    into: "in1"
  - from: "Call5"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Decision2"
    via: "yes"
    to: "Call4"
    into: "in"
  - from: "GetProductDataMappingRules1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "GetRepositoryByUUID2"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "CheckForEmptyString1"
    via: "next"
    to: "GetRepositoryByUUID2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "Decision3"
    via: "no"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetRepositoryByUUID2"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "Join3"
    into: "in3"
  - from: "GetProductDataMappingRuleSet1"
    via: "next"
    to: "CheckForEmptyString1"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "GetProductDataMappingRuleSet1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Decision2"
    into: "in"
