flow: "ViewUserOrderList_52"
kind: "view"

entries:
  - id: "Start2"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "OrderSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "FixInitialState"
    mode: "include"
    strict: true
    inputs:
      - key: "OrderState"
        type: "java.lang.String"
        required: false
      - key: "OrderSearchType"
        type: "java.lang.String"
        required: false
      - key: "ApplicationBO"
        type: "com.intershop.component.application.capi.ApplicationBO"
        required: true

steps:
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      Iterator: "AllSelectedStatusIDs"
      OutVector: "AllSelectedStatusIDsVector"
  - id: "AddObjectToVector4"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      Iterator: "AllSelectedStatusIDs"
      OutVector: "AllSelectedStatusIDsVector"
      Object: "StateIDString"
      InVector: "AllSelectedStatusIDsVector"
  - id: "CallNode1"
    type: "call"
    ref: "ViewChannelUser-GetUserProfile"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessOrderSearch-Search"
    bindings:
      OrderDomain: "CurrentChannel:Domain"
      StartDate: "null"
      EndDate: "null"
      ConsumerName: "null"
      CustomerName: "null"
      OrderNumber: "null"
      PriceTotalTo: "null"
      OrderDomains: "null"
      ProductSKU: "null"
      ProductAvalibilityFlag: "null"
      OrderStateLiteral: "statusLiteral"
      SortDirection: "SortDirection"
      SortAttribute: "SortAttribute"
      OrderStates: "AllSelectedStatusIDs"
      OrderStatus: "null"
      PriceTotalFrom: "null"
      RequisitionNumber: "null"
      Buyer: "Buyer"
  - id: "CallNode3"
    type: "call"
    ref: "ViewChannelUser-GetUserProfile"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessOrderSearch-StorePageLocatorParameter"
    bindings:
      PageLocator: "OrdersPageLocator"
  - id: "CallNode5"
    type: "call"
    ref: "ViewUserOrderList_52-FixInitialState"
    bindings:
      OrderSearchType: "searchOpenOrders"
      OrderState: "statusLiteral"
  - id: "CallNode6"
    type: "call"
    ref: "ViewOrderList-GetOrderStatuses"
  - id: "Decision1"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision2"
    type: "decision"
    condition: "PageLocator"
  - id: "DecisionNode4"
    type: "decision"
    condition: "AllSelectedStatusIDs"
  - id: "DecisionNode5"
    type: "decision"
    condition: "initialVisit"
  - id: "DetermineUser1"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "USER_UUID"
      User: "Buyer"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewUserOrderList_52-OrderSearch"
      PagingPipeline: "ViewUserOrderList_52-Paging"
      OutValue_2: "ViewUserOrderList_52-OrderSearch"
      OutValue_6: "ViewUserOrderList_52-Paging"
    bindings:
      Key_0: "find"
      SelectionKey: "JumpTarget"
      DefaultButton: "find"
      Key_2: "searchOpenOrders"
      Key_6: "backToList"
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "AllSelectedStatusIDs"
        type: "java.util.Iterator"
        guaranteed: true
  - id: "GetPageLocator2"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocatorName: "Orders"
  - id: "GetPageable2"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Orders"
      PageableID: "PageLocator:PageableID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "OrderBORepository:OrderStatuses:Iterator"
      OutValue_1: "OrderStatuses"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Order\"):OrderBORepositoryOfOwningRepository"
      OutValue_1: "OrderBORepository"
  - id: "LoopNode3"
    type: "loop"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "OrderStates"
    bindings:
      Selection: "AllSelectedStatusIDs"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelUser"
      WorkingTemplate: "user/UserOrderList_52"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 1
    bindings:
      PageNumber: "PageNumberInt"
      Pageable: "Orders"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 1
    bindings:
      Pageable: "Orders"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewUserOrderList_52-Paging"
      DefaultPageLocatorName: "Orders"
    bindings:
      PageLocator: "OrdersPageLocator"
      Pageable: "Orders"
  - id: "ToString1"
    type: "pipelet"
    ref: "ToString"
    bindings:
      Object1: "OrderStatus:StateId"
      String1: "StateIDString"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumberInt"
      LocalizedString: "PageNumber"

links:
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "DetermineUser1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage1"
    into: "in"
  - from: "SetPage1"
    via: "next"
    to: "Join7"
    into: "in2"
  - from: "Decision1"
    via: "no"
    to: "Decision2"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join6"
    into: "in2"
  - from: "Join6"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join6"
    into: "in1"
  - from: "Decision2"
    via: "yes"
    to: "SetPage2"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join7"
    into: "in3"
  - from: "SetPageLocator1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "CallNode4"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "Pipelet2"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode5"
    via: "yes"
    to: "CallNode5"
    into: "in"
  - from: "GetPageLocator2"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode6"
    into: "in2"
  - from: "JoinNode6"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "LoopNode3"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "ToString1"
    via: "next"
    to: "AddObjectToVector4"
    into: "in"
  - from: "LoopNode3"
    via: "do"
    to: "ToString1"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "AddObjectToVector4"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "Join7"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "GetPageLocator2"
    via: "next"
    to: "GetPageable2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "DetermineUser1"
    into: "in"
  - from: "GetPageable2"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "CallNode3"
    via: "next"
    to: "GetPageLocator2"
    into: "in"
  - from: "GetPageable2"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "CallNode6"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
