flow: "ViewProcessList_32"
kind: "view"

entries:
  - id: "Start1"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start12"
    name: "DeleteLogFiles"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start13"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start14"
    name: "Entries"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "CreateProcess"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "ConfirmDeletion"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Statistics"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode17"
    name: "GetSelectedMenuItem"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode2"
    name: "Filter"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessBatchJob-Create"
  - id: "Call4"
    type: "call"
    ref: "ViewProcessList_32-DeleteLogFiles"
  - id: "CallNode1"
    type: "call"
    ref: "ViewProcessList_32-GetSelectedMenuItem"
  - id: "CallNode2"
    type: "call"
    ref: "ViewProcessList_32-Prefix"
  - id: "CallNode3"
    type: "call"
    ref: "ViewProcessList_32-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ViewProcessList_32-Prefix"
  - id: "CallNode5"
    type: "call"
    ref: "ViewProcessList_32-Prefix"
  - id: "CallNode6"
    type: "call"
    ref: "ViewProcessList_32-Prefix"
  - id: "CheckForEmptyString1"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "SelectedMenuItem"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "JobConfiguration:UUID"
      String1: "\"-BatchEntries.log\""
      Concatenated: "FileName"
  - id: "ConcatenateStrings2"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "JobConfiguration:UUID"
      String1: "\"-BatchEntries.log\""
      Concatenated: "FileName"
  - id: "CreatePageableFromCollection1"
    type: "pipelet"
    ref: "CreatePageableFromCollection"
    config:
      Pagesize: 20
    bindings:
      Collection: "LoggingEvents"
      Pageable: "LogEntries"
  - id: "Decision1"
    type: "decision"
    condition: "PageLocator"
  - id: "Decision2"
    type: "decision"
    condition: "PageNumber"
  - id: "DecisionNode1"
    type: "decision"
    condition: "SelectedMenuItem"
  - id: "DeleteFile3"
    type: "pipelet"
    ref: "DeleteFile"
    config:
      DefaultDirectoryPath: "../batch/log"
      UnitDirectory: "IMPEX_DIR"
    bindings:
      FileName: "FileName"
      UnitDomain: "JobConfiguration:Domain"
      DirectoryPath: "null"
      Locale: "null"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProcessList_32-Delete"
      OutValue_1: "ViewProcessList_32-ConfirmDeletion"
      OutValue_2: "ViewProcessList_32-Statistics"
      OutValue_3: "ViewProcessList_32-Entries"
      OutValue_4: "ViewProcessList_32-Paging"
      OutValue_5: "ViewProcessList_32-ListAll"
      PagingPipeline: "ViewProcessList_32-Paging"
    bindings:
      Key_0: "delete"
      Key_1: "confirmDelete"
      Key_2: "Statistics"
      Key_3: "Entries"
      Key_4: "Paging"
      Key_5: "refresh"
      SelectionKey: "JumpTarget"
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode14"
    type: "end"
    strict: true
    outputs:
      - key: "SelectedMenuItem"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "ExchangeSessionObject7"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ApplicationState"
    bindings:
      LoadObject: "ApplicationState"
  - id: "GetAllJobConfigurations2"
    type: "pipelet"
    ref: "GetAllJobConfigurations"
    config:
      DefaultJobState: "None"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
      JobConfigurations: "Processes"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "ProcessUUID"
    bindings:
      Selection: "ProcessUUIDs"
  - id: "GetFormSelection3"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "ProcessUUID"
    bindings:
      Selection: "ProcessUUIDs"
  - id: "GetJobConfiguration1"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "ProcessUUID"
  - id: "GetLogStatistics1"
    type: "pipelet"
    ref: "GetLogStatistics"
    bindings:
      StatisticsHolder: "JobConfiguration:CurrentProcess"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "LogPageLocator"
      RestorePageLocatorDictionary: "True"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "LogEntries"
      PageableID: "PageLocator:PageableID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "Join11"
    type: "join"
  - id: "Join12"
    type: "join"
  - id: "Join13"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "ViewProcessList_32-ListAll"
  - id: "Jump6"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentChannel:RepositoryDomain"
      InValue_2: "CurrentChannel:OwningDomain:Site"
      OutValue_1: "ProcessOwningDomain"
      OutValue_2: "ProcessExecutionDomain"
      InValue_3: "CurrentApplication"
      OutValue_3: "ProcessApplication"
  - id: "KeyMapper9"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      OutValue_1: "SelectedMenuItem"
      InValue_1: "ApplicationState:LastSelectedMenuItem"
  - id: "Loop1"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      RenderingType: "HTML"
      WorkingTemplate: "process/ProcessLogStatistics_32"
      Dynamic: true
  - id: "Pipelet13"
    type: "pipelet"
    ref: "GetJobConfiguration"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "GetJobConfiguration"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      RenderingType: "HTML"
      WorkingTemplate: "process/ProcessLogEntries_32"
      Dynamic: true
  - id: "Pipelet4"
    type: "pipelet"
    ref: "GetJobConfiguration"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "GetJobConfiguration"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      RenderingType: "HTML"
      WorkingTemplate: "process/ProcessList_32"
      Dynamic: true
      SelectedMenuItem: "ChannelCatalogs"
  - id: "ReadXMLLogFile1"
    type: "pipelet"
    ref: "ReadXMLLogFile"
    bindings:
      LogFileDirectory: "\"batch/log\""
      LogFileName: "FileName"
      LogFileUnit: "JobConfiguration:Domain"
  - id: "RemoveJobConfiguration1"
    type: "pipelet"
    ref: "RemoveJobConfiguration"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "LogEntries"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "LogEntries"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewContentSyndicationLog-Paging"
      DefaultPageLocatorName: "LogPageLocator"
    bindings:
      Pageable: "LogEntries"
  - id: "SortIteratorByComparator1"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingOrder: true
      DefaultSortingAttribute: "LastExecutionTime"
    bindings:
      Iterator: "Processes"
      SortedIterator: "Processes"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"

links:
  - from: "Pipelet5"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "SetPage1"
    via: "next"
    to: "Join11"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "CheckForEmptyString1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Decision1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "Pipelet1"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "KeyMapper9"
    via: "next"
    to: "EndNode14"
    into: "in"
  - from: "StartNode17"
    via: "next"
    to: "ExchangeSessionObject7"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump6"
    into: "in"
  - from: "GetPageLocator1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "ExchangeSessionObject7"
    via: "next"
    to: "KeyMapper9"
    into: "in"
  - from: "Join9"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "CreatePageableFromCollection1"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "Join12"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "Start6"
    via: "next"
    to: "GetFormSelection3"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Loop1"
    via: "do"
    to: "GetJobConfiguration1"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "SetPage1"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "DeleteFile3"
    via: "next"
    to: "End3"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "SetPageLocator1"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "Decision1"
    via: "no"
    to: "Join11"
    into: "in3"
  - from: "Start13"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "RemoveJobConfiguration1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "SetPage2"
    via: "next"
    to: "Join13"
    into: "in1"
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "Join2"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "DeleteFile3"
    via: "error"
    to: "End2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "GetLogStatistics1"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join13"
    into: "in3"
  - from: "CallNode2"
    via: "next"
    to: "GetAllJobConfigurations2"
    into: "in"
  - from: "GetFormSelection3"
    via: "next"
    to: "Join4"
    into: "in3"
  - from: "GetLogStatistics1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Join13"
    via: "next"
    to: "Join12"
    into: "in1"
  - from: "GetJobConfiguration1"
    via: "error"
    to: "Join2"
    into: "in3"
  - from: "CallNode3"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Start12"
    via: "next"
    to: "ConcatenateStrings2"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "Pipelet13"
    into: "in"
  - from: "Start14"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "Join9"
    into: "in2"
  - from: "GetPageable1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "Call4"
    via: "next"
    to: "RemoveJobConfiguration1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "Pipelet13"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "GetAllJobConfigurations2"
    via: "next"
    to: "SortIteratorByComparator1"
    into: "in"
  - from: "SortIteratorByComparator1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "ReadXMLLogFile1"
    via: "next"
    to: "CreatePageableFromCollection1"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "ReadXMLLogFile1"
    into: "in"
  - from: "ConcatenateStrings2"
    via: "next"
    to: "DeleteFile3"
    into: "in"
  - from: "Join11"
    via: "next"
    to: "Join12"
    into: "in3"
  - from: "Call1"
    via: "next"
    to: "EndNode1"
    into: "in"
