flow: "ViewProductFilterList"
kind: "view"

entries:
  - id: "Start1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Refresh"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Remove"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call10"
    type: "call"
    ref: "ProcessProductFilter-Remove"
  - id: "Call2"
    type: "call"
    ref: "ProcessProductFilter-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ViewProductFilterList-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ViewProductFilterList-Prefix"
  - id: "Call5"
    type: "call"
    ref: "ProcessProductFilter-UpdateClipboard"
  - id: "Call6"
    type: "call"
    ref: "ProcessProductFilter-UpdateClipboard"
  - id: "Call7"
    type: "call"
    ref: "ViewProductFilterList-Prefix"
  - id: "Call8"
    type: "call"
    ref: "ProcessProductFilter-RemoveClipboard"
  - id: "Call9"
    type: "call"
    ref: "ProcessProductFilter-UpdateClipboard"
  - id: "CreatePageableFromIterator1"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    config:
      Pagesize: 10
    bindings:
      Iterator: "ProductFilters"
      Pageable: "ProductFiltersPageable"
  - id: "Decision1"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision2"
    type: "decision"
    condition: "PageLocator"
  - id: "Decision3"
    type: "decision"
    condition: "confirmDelete"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProductFilterList-Remove"
      OutValue_1: "ViewProductFilterList-Remove"
      OutValue_2: "ViewProductFilterList-Paging"
      OutValue_3: "ViewProductFilter-New"
      PagingPipeline: "ViewProductFilterList-Paging"
    bindings:
      Key_0: "confirmDelete"
      Key_1: "delete"
      Key_2: "cancelConfirm"
      Key_3: "new"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ProductFiltersListViewLocator"
      RestorePageLocatorDictionary: "True"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      PageableID: "PageLocator:PageableID"
      Pageable: "ProductFiltersPageable"
  - id: "GetSearchQueryDefinition1"
    type: "pipelet"
    ref: "GetSearchQueryDefinition"
    bindings:
      Domain: "ChannelRepository:Domain"
      UUID: "ProductFilterUUID"
      SearchQueryDefinition: "ProductFilter"
  - id: "GetSearchQueryDefinitions1"
    type: "pipelet"
    ref: "GetSearchQueryDefinitions"
    bindings:
      Domain: "ChannelRepository:Domain"
      GlobalVisible: "\"(Boolean)true\""
      SearchQueryDefinitions: "ProductFilters"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InvalidatePageLocatorPageable1"
    type: "pipelet"
    ref: "InvalidatePageLocatorPageable"
    config:
      DefaultPageLocatorName: "ProductFiltersListViewLocator"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump3"
    type: "jump"
    ref: "ViewProductFilterList-Paging"
  - id: "Jump4"
    type: "jump"
    ref: "ViewProductFilterList-ListAll"
  - id: "Loop1"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ProductFilters"
      WorkingTemplate: "productfilter/ProductFilterList"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewProductFilterList-ListAll"
      ValueType: "Dictionary Value"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "IntegerPageNumber"
      Pageable: "ProductFiltersPageable"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "ProductFiltersPageable"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewProductFilterList-Paging"
      DefaultPageLocatorName: "ProductFiltersListViewLocator"
    bindings:
      Pageable: "ProductFiltersPageable"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      LocalizedString: "PageNumber"
      IntegerObject: "IntegerPageNumber"

links:
  - from: "GetSearchQueryDefinitions1"
    via: "next"
    to: "CreatePageableFromIterator1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "InvalidatePageLocatorPageable1"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Call6"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "GetPageable1"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "Call2"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "End1"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage1"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Loop1"
    via: "do"
    to: "GetSearchQueryDefinition1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Decision3"
    via: "no"
    to: "Loop1"
    into: "in"
  - from: "GetPageLocator1"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "Call7"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Decision2"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "SetPage2"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "GetSearchQueryDefinition1"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "SetPage1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "Decision2"
    via: "no"
    to: "Join6"
    into: "in1"
  - from: "Call8"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "SetPageLocator1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Decision3"
    via: "yes"
    to: "Jump3"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "GetSearchQueryDefinitions1"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join6"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join4"
    into: "in1"
  - from: "Loop1"
    via: "next"
    to: "InvalidatePageLocatorPageable1"
    into: "in"
  - from: "CreatePageableFromIterator1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Start5"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "Loop1"
    into: "loop"
