flow: "ViewOrganizationEnterpriseContactInfo"
kind: "view"

entries:
  - id: "Start1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "View"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call3"
    type: "call"
    ref: "ViewOrganizationEnterpriseContactInfo-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ViewOrganizationEnterpriseContactInfo-Prefix"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "AddressName"
      param.1.required: true
      param.10.name: "City"
      param.10.required: false
      param.11.name: "State"
      param.11.required: false
      param.12.name: "CountryCode"
      param.12.required: false
      param.13.name: "Email"
      param.13.required: false
      param.14.name: "PhoneBusiness"
      param.14.required: false
      param.15.name: "PhoneBusinessDirect"
      param.15.required: false
      param.16.name: "Fax"
      param.16.required: false
      param.17.name: "Homepage"
      param.17.required: false
      param.2.name: "Field1"
      param.2.required: false
      param.3.name: "Field2"
      param.3.required: false
      param.4.name: "Field3"
      param.4.required: false
      param.5.name: "Title"
      param.5.required: false
      param.6.name: "FirstName"
      param.6.required: false
      param.7.name: "LastName"
      param.7.required: false
      param.8.name: "Street"
      param.8.required: false
      param.9.name: "PostalCode"
      param.9.required: false
      webform-id: "UpdateContactInfo"
      param.1.rule: ""
      param.2.rule: ""
      param.3.rule: ""
      param.4.rule: ""
      param.5.rule: ""
      param.6.rule: ""
      param.7.rule: ""
      param.8.rule: ""
      param.9.rule: ""
      param.10.rule: ""
      param.11.rule: ""
      param.12.rule: ""
      param.13.rule: ""
      param.14.rule: ""
      param.15.rule: ""
      param.16.rule: ""
      param.17.rule: ""
      param.18.name: "CompanyName"
      param.18.rule: ""
      param.18.required: false
  - id: "DecisionNode1"
    type: "decision"
    condition: "UpdateContactInfo_Email"
  - id: "DetermineDefaultAddress1"
    type: "pipelet"
    ref: "DetermineDefaultAddress"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewOrganizationEnterpriseList-ListAll"
      OutValue_1: "ViewOrganizationEnterpriseContactInfo-Update"
      OutValue_2: "ViewOrganizationEnterpriseContactInfo-View"
      OutValue_3: "ViewOrganizationEnterpriseContactInfo-View"
    bindings:
      Key_0: "backToList"
      Key_1: "update"
      Key_2: "cancel"
      Key_3: "reset"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "GetAllServiceGroups1"
    type: "pipelet"
    ref: "GetAllServiceGroups"
  - id: "GetOrganization1"
    type: "pipelet"
    ref: "GetOrganization"
    config:
      Source: "PipelineDictionary"
  - id: "GetProfile1"
    type: "pipelet"
    ref: "GetProfile"
    bindings:
      ProfileID: "Organization:Domain:ProfileID"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "UpdateContactInfo"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump3"
    type: "jump"
    ref: "ViewOrganizationEnterpriseContactInfo-View"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "UpdateContactInfo_State"
      InValue_2: "UpdateContactInfo_CountryCode"
      InValue_3: "UpdateContactInfo_Email"
      InValue_4: "UpdateContactInfo_PhoneBusiness"
      InValue_5: "UpdateContactInfo_PhoneBusinessDirect"
      InValue_6: "UpdateContactInfo_Fax"
      InValue_7: "UpdateContactInfo_Homepage"
      InValue_8: "UpdateContactInfo_CompanyName"
      OutValue_1: "State"
      OutValue_2: "CountryCode"
      OutValue_3: "Email"
      OutValue_4: "PhoneBusiness"
      OutValue_5: "PhoneBusinessDirect"
      OutValue_6: "Fax"
      OutValue_7: "Homepage"
      OutValue_8: "Company"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "UpdateContactInfo_AddressName"
      InValue_10: "UpdateContactInfo_City"
      InValue_2: "UpdateContactInfo_Field1"
      InValue_3: "UpdateContactInfo_Field2"
      InValue_4: "UpdateContactInfo_Field3"
      InValue_5: "UpdateContactInfo_Title"
      InValue_6: "UpdateContactInfo_FirstName"
      InValue_7: "UpdateContactInfo_LastName"
      InValue_8: "UpdateContactInfo_Street"
      InValue_9: "UpdateContactInfo_PostalCode"
      OutValue_1: "AddressName"
      OutValue_10: "City"
      OutValue_2: "Field1"
      OutValue_3: "Field2"
      OutValue_4: "Field3"
      OutValue_5: "Title"
      OutValue_6: "FirstName"
      OutValue_7: "LastName"
      OutValue_8: "Street"
      OutValue_9: "PostalCode"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Organization"
      InValue_2: "OrganizationDomain"
      OutValue_1: "UserOrganization"
      OutValue_2: "UserOrganizationDomain"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "VerifyEMailAddress"
    bindings:
      EMailAddress: "UpdateContactInfo_Email"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_EMailAddressInvalid"
      Value: true
      ValueType: "Dictionary Value"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Enterprises"
      WorkingTemplate: "organization/OrganizationEnterpriseContactInfo"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Enterprises"
      WorkingTemplate: "organization/OrganizationEnterpriseContactInfo"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewOrganizationEnterpriseContactInfo-View"
      ValueType: "Dictionary Value"
  - id: "UpdateAddress1"
    type: "pipelet"
    ref: "UpdateAddress"
  - id: "UpdateCustomAttributes1"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "Field1"
      Attribute_1_Type: "String"
      Attribute_2_Name: "Field2"
      Attribute_2_Type: "String"
      Attribute_3_Name: "Field3"
      Attribute_3_Type: "String"
    bindings:
      Attribute_1_Value: "Field1"
      Attribute_2_Value: "Field2"
      Attribute_3_Value: "Field3"
      ExtensibleObject: "Address"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "UpdateContactInfo"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"

links:
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CreateWebForm1"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "ValidateWebForm1"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "UpdateCustomAttributes1"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "UpdateAddress1"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "Pipelet2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "GetOrganization1"
    into: "in"
  - from: "GetOrganization1"
    via: "next"
    to: "GetProfile1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "UpdateAddress1"
    via: "next"
    to: "UpdateCustomAttributes1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "Pipelet1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode2"
    into: "in1"
  - from: "ValidateWebForm1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "DetermineDefaultAddress1"
    via: "next"
    to: "GetAllServiceGroups1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "GetProfile1"
    via: "next"
    to: "DetermineDefaultAddress1"
    into: "in"
  - from: "GetProfile1"
    via: "error"
    to: "End2"
    into: "in"
  - from: "GetAllServiceGroups1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call3"
    into: "in"
