flow: "ViewChannelOutboundSyndicationAttachmentMapping"
kind: "view"

entries:
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "null"
      Objects: "null"
      Object: "Locale:LocaleID"
      Iterator: "LocaleIDs"
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "null"
      Objects: "SyndicationRule:SourceSyndicationDataDeclaration:LocaleID"
      Object: "Locale:LocaleID"
      Iterator: "LocaleIDs"
  - id: "AddObjectToVector3"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "LocaleIDVector"
      Objects: "null"
      Object: "LocaleID"
      Iterator: "LocaleIDs"
      OutVector: "LocaleIDVector"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessSyndicationRule-GetRuleSet"
    bindings:
      Name: "\"Attachments\""
  - id: "CallNode2"
    type: "call"
    ref: "ProcessSyndicationRule-GetRuleSet"
    bindings:
      Name: "\"Attachments\""
  - id: "CallNode3"
    type: "call"
    ref: "ProcessSyndicationRule-GetDataDeclarationList"
    bindings:
      Name: "\"Attachments\""
  - id: "CallNode4"
    type: "call"
    ref: "ProcessSyndicationRule-RemoveSyndicationRule"
  - id: "CreateSyndicationDataDeclaration1"
    type: "pipelet"
    ref: "CreateSyndicationDataDeclaration"
    bindings:
      Domain: "Syndication:Domain"
      DataObjectClassName: "\"com.intershop.beehive.xcs.internal.product.ProductPO\""
  - id: "CreateSyndicationRule1"
    type: "pipelet"
    ref: "CreateSyndicationRule"
    bindings:
      SyndicationRuleClass: "\"com.intershop.component.mvc.internal.syndication.mapping.AttachmentRuleProcessor\""
      Domain: "Syndication:Domain"
      SourceSyndicationDataDeclaration: "SyndicationDataDeclaration"
      TargetSyndicationDataDeclaration: "null"
  - id: "DecisionNode1"
    type: "decision"
    condition: "SyndicationRuleUUID"
  - id: "DecisionNode2"
    type: "decision"
    condition: "AttachmentMappingEnabled"
  - id: "DecisionNode3"
    type: "decision"
    condition: "SyndicationRuleUUID"
  - id: "DecisionNode4"
    type: "decision"
    condition: "CopyFlag"
  - id: "DecisionNode5"
    type: "decision"
    condition: "CopyFlag"
  - id: "DecisionNode6"
    type: "decision"
    condition: "LocaleID"
  - id: "DecisionNode7"
    type: "decision"
    condition: "LocaleIDs"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DetermineLocales2"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelOutboundSyndicationAttachmentMapping-Start"
      OutValue_1: "ViewChannelOutboundSyndicationList-Start"
      OutValue_2: "ViewChannelOutboundSyndicationAttachmentMapping-Update"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "Start"
      Key_1: "Back"
      Key_2: "Update"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
  - id: "GetSyndicationByUUID1"
    type: "pipelet"
    ref: "GetSyndicationByUUID"
  - id: "GetSyndicationByUUID2"
    type: "pipelet"
    ref: "GetSyndicationByUUID"
  - id: "GetSyndicationRuleByUUID1"
    type: "pipelet"
    ref: "GetSyndicationRuleByUUID"
  - id: "GetSyndicationRuleByUUID2"
    type: "pipelet"
    ref: "GetSyndicationRuleByUUID"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "Jump5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "LoopNode1"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/ChannelOutboundSyndicationAttachmentMapping"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/ChannelOutboundSyndicationAttachmentMapping"
  - id: "RemoveCustomAttribute1"
    type: "pipelet"
    ref: "RemoveCustomAttribute"
    bindings:
      ExtensibleObject: "SyndicationRule:SourceSyndicationDataDeclaration"
      LocaleInformation: "Locale"
      AttributeName: "\"CopyFlag\""
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "SyndicationRule"
      RemoveFormValues: false
  - id: "UpdateCustomAttribute1"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    bindings:
      LocaleInformation: "Locale"
      AttributeName: "\"CopyFlag\""
      AttributeType: "\"String\""
      AttributeValue: "CopyFlag"
      ExtensibleObject: "SyndicationRule:SourceSyndicationDataDeclaration"
  - id: "UpdateCustomAttribute2"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    bindings:
      LocaleInformation: "null"
      AttributeName: "\"LocaleID\""
      AttributeType: "\"MultipleString\""
      AttributeValue: "LocaleIDs"
      ExtensibleObject: "SyndicationRule:SourceSyndicationDataDeclaration"
  - id: "UpdateCustomAttribute3"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    bindings:
      LocaleInformation: "null"
      AttributeName: "\"LocaleID\""
      AttributeType: "\"MultipleString\""
      AttributeValue: "LocaleIDs"
      ExtensibleObject: "SyndicationDataDeclaration"
  - id: "UpdateCustomAttribute4"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    bindings:
      LocaleInformation: "Locale"
      AttributeName: "\"CopyFlag\""
      AttributeType: "\"String\""
      AttributeValue: "CopyFlag"
      ExtensibleObject: "SyndicationDataDeclaration"
  - id: "UpdateCustomAttribute5"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    bindings:
      LocaleInformation: "Locale"
      AttributeName: "\"CopyFlag\""
      AttributeType: "\"String\""
      AttributeValue: "\"false\""
      ExtensibleObject: "SyndicationDataDeclaration"
  - id: "UpdateCustomAttribute6"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    bindings:
      LocaleInformation: "Locale"
      AttributeName: "\"CopyFlag\""
      AttributeType: "\"String\""
      AttributeValue: "\"false\""
      ExtensibleObject: "SyndicationRule:SourceSyndicationDataDeclaration"
  - id: "UpdateCustomAttribute7"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    bindings:
      LocaleInformation: "null"
      AttributeName: "\"LocaleID\""
      AttributeType: "\"MultipleString\""
      AttributeValue: "LocaleIDs"
      ExtensibleObject: "SyndicationRule:SourceSyndicationDataDeclaration"

links:
  - from: "StartNode1"
    via: "next"
    to: "GetSyndicationByUUID1"
    into: "in"
  - from: "GetSyndicationByUUID2"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetSyndicationByUUID2"
    into: "in"
  - from: "DetermineLocales2"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode3"
    into: "in"
  - from: "CreateSyndicationRule1"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "CreateSyndicationDataDeclaration1"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "DecisionNode3"
    into: "in"
  - from: "GetLocale2"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CreateSyndicationDataDeclaration1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "GetSyndicationRuleByUUID2"
    into: "in"
  - from: "UpdateCustomAttribute5"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "UpdateCustomAttribute6"
    via: "next"
    to: "JoinNode4"
    into: "in2"
  - from: "JoinNode2"
    via: "next"
    to: "DetermineLocales2"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "GetSyndicationRuleByUUID1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "AddObjectToVector3"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "GetSyndicationRuleByUUID2"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "UpdateCustomAttribute2"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "UpdateCustomAttribute4"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "UpdateCustomAttribute5"
    into: "in"
  - from: "UpdateCustomAttribute4"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "UpdateCustomAttribute1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "UpdateCustomAttribute3"
    via: "next"
    to: "CreateSyndicationRule1"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "UpdateCustomAttribute3"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode5"
    via: "yes"
    to: "UpdateCustomAttribute1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "UpdateCustomAttribute6"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "UpdateCustomAttribute2"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "GetSyndicationRuleByUUID1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "CallNode4"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode5"
    into: "in3"
  - from: "LoopNode1"
    via: "do"
    to: "DecisionNode6"
    into: "in"
  - from: "AddObjectToVector3"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "GetSyndicationByUUID1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "DecisionNode7"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "UpdateCustomAttribute7"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "UpdateCustomAttribute7"
    via: "next"
    to: "RemoveCustomAttribute1"
    into: "in"
  - from: "RemoveCustomAttribute1"
    via: "next"
    to: "JoinNode6"
    into: "in2"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "DecisionNode1"
    into: "in"
