flow: "ViewReplicationProcessList"
kind: "process"

entries:
  - id: "Start1"
    name: "ListTasks"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "List"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "GetReplicationProcesses-ByState"
  - id: "CallNode0"
    type: "call"
    ref: "ViewData-SecureForBrowserBack"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "CheckForEmptyString1"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "State"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PageLocator"
  - id: "DecisionNode2"
    type: "decision"
    condition: "PageNumber"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "JoinNode0"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewReplicationTaskList-List"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "PageLocator:Dictionary:State"
      OutValue_1: "State"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewReplicationProcessWizard-New"
      OutValue_1: "ViewReplicationProcessList-List"
      OutValue_2: "ViewReplicationProcessList-Paging"
      OutValue_3: "ViewReplicationProcessList-List"
      OutValue_4: "ViewReplicationProcessList-ListTasks"
      OutValue_5: "ViewReplicationProcess-Remove"
      PagingPipeline: "ViewReplicationProcessList-Paging"
      OutValue_6: "ViewReplicationProcess-Run"
      OutValue_7: "ViewReplicationProcess-Undo"
      OutValue_8: "ViewReplicationProcess-Publish"
      OutValue_9: "ViewReplicationProcess-Rerun"
    bindings:
      Key_0: "New"
      Key_1: "Search"
      Key_2: "ConfirmDelete"
      Key_3: "Refresh"
      Key_4: "ListTasks"
      Key_5: "Delete"
      Key_6: "RunProcess"
      Key_7: "UndoProcess"
      Key_8: "PublishProcess"
      Key_9: "RerunProcess"
      SelectionKey: "JumpTarget"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ReplicationProcesses"
      WorkingTemplate: "replication/ReplicationProcessList"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewReplicationProcessList-Paging"
      DefaultPageLocatorName: "ProcessList"
    bindings:
      Pageable: "ReplicationProcesses"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "ReplicationProcesses"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ProcessList"
      RestorePageLocatorDictionary: "False"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "ReplicationProcesses"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      LocalizedString: "PageNumber"
      IntegerObject: "PageNumber"
  - id: "Pipelet9"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      PageableID: "PageLocator:PageableID"
      Pageable: "ReplicationProcesses"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "CurrentPageNumber"
      RemoveFormValues: true
  - id: "SetDictionaryValue0"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewReplicationProcessList-List"
  - id: "SetPageLocatorParameter1"
    type: "pipelet"
    ref: "SetPageLocatorParameter"
    bindings:
      ParameterName: "\"State\""
      ParameterValue: "State"

links:
  - from: "Pipelet1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet8"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "DecisionNode1"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "Pipelet9"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Pipelet3"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet7"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "Pipelet8"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "Pipelet6"
    via: "error"
    to: "Join2"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "Pipelet10"
    into: "in"
  - from: "Pipelet9"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "SetPageLocatorParameter1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Pipelet11"
    via: "next"
    to: "CheckForEmptyString1"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "next"
    to: "SetPageLocatorParameter1"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "Pipelet9"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "Pipelet11"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "Pipelet10"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "SetDictionaryValue0"
    into: "in"
  - from: "CallNode0"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode0"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "SetDictionaryValue0"
    via: "next"
    to: "CallNode0"
    into: "in"
