flow: "ViewProductVariationAttribute_32"
kind: "view"

entries:
  - id: "Start1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "New"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "CheckLock"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessProduct-DetermineCategoryPath"
  - id: "Call10"
    type: "call"
    ref: "ProcessProductVariations-DeleteAttribute"
  - id: "Call11"
    type: "call"
    ref: "ProcessProductHistory-SaveProductSnapShot"
  - id: "Call12"
    type: "call"
    ref: "ProcessProductHistory-SaveProductSnapShot"
  - id: "Call13"
    type: "call"
    ref: "ProcessProductHistory-SaveProductSnapShot"
  - id: "Call2"
    type: "call"
    ref: "ViewProductVariationAttribute_32-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ViewProductVariationAttribute_32-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ProcessProduct-Get"
  - id: "Call5"
    type: "call"
    ref: "ViewProductVariationAttribute_32-Prefix"
  - id: "Call6"
    type: "call"
    ref: "ViewProductVariationAttribute_32-Prefix"
  - id: "Call7"
    type: "call"
    ref: "ViewProductVariationAttribute_32-Prefix"
  - id: "Call8"
    type: "call"
    ref: "ProcessProductVariations-CreateAttribute"
  - id: "Call9"
    type: "call"
    ref: "ProcessProductVariations-UpdateAttribute"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessProductLock_32-Check"
  - id: "CallNode2"
    type: "call"
    ref: "ViewProductVariationAttribute_32-CheckLock"
  - id: "CallNode3"
    type: "call"
    ref: "ViewProductVariationAttribute_32-CheckLock"
  - id: "CallNode4"
    type: "call"
    ref: "ViewProductVariationAttribute_32-CheckLock"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessProductLock_32-Lookup"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "AttributeName"
      param.1.required: true
      param.2.name: "DisplayName"
      param.2.required: true
      param.3.required: true
      param.4.required: false
      webform-id: "UpdateAttribute"
      param.1.rule: ""
      param.2.rule: ""
      param.3.name: "VariationSelection"
      param.3.rule: ""
      param.4.name: "ProductAttrName"
      param.4.rule: ""
    bindings:
      WebForm: "UpdateAttribute"
  - id: "CreateWebForm2"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "AttributeName"
      param.1.required: true
      param.2.name: "DisplayName"
      param.2.required: true
      param.3.required: true
      param.4.required: false
      webform-id: "CreateAttribute"
      param.1.rule: ""
      param.2.rule: ""
      param.3.name: "VariationSelection"
      param.3.rule: ""
      param.4.name: "ProductAttrName"
      param.4.rule: ""
    bindings:
      WebForm: "CreateAttribute"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DetermineLocales2"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DetermineLocales3"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DetermineLocales4"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProductVariationAttribute_32-New"
      OutValue_1: "ViewProductVariationAttribute_32-New"
      OutValue_2: "ViewProductVariationAttribute_32-Create"
      OutValue_3: "ViewProductVariationAttribute_32-Update"
      OutValue_4: "ViewProductVariationAttribute_32-Edit"
      OutValue_5: "ViewProductVariationAttribute_32-Delete"
      OutValue_6: "ViewProductVariations_32-View"
      OutValue_7: "ViewProductVariationAttribute_32-Edit"
      OutValue_8: "ViewProductVariationAttribute_32-Edit"
    bindings:
      Key_0: "setNewLocale"
      Key_1: "newVariationAttribute"
      Key_2: "createVariationAttribute"
      Key_3: "applyVariationAttribute"
      Key_4: "setLocale"
      Key_5: "deleteVariationAttribute"
      Key_6: "back"
      Key_7: "confirmDeleteVariationAttribute"
      Key_8: "cancel"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "VariableVariationAttributeUUID"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetLocale3"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetLocale4"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetVariableVariationAttributeByUUID1"
    type: "pipelet"
    ref: "GetVariableVariationAttributeByUUID"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "UpdateAttribute"
    bindings:
      WebForm: "UpdateAttribute"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "CreateAttribute"
    bindings:
      WebForm: "CreateAttribute"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewProductVariationAttribute_32-Edit"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump3"
    type: "jump"
    ref: "ViewProductVariationAttribute_32-Edit"
  - id: "Jump5"
    type: "jump"
    ref: "ViewProduct_32-JumpToList"
  - id: "Jump6"
    type: "jump"
    ref: "ViewProductVariations_32-View"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewProductVariations_32-View"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewProduct_32-ErrorProductNotAvailable"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "VariableVariationAttribute:UUID"
      OutValue_1: "VariableVariationAttributeUUID"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CreateAttribute:AttributeName:Value"
      InValue_2: "CreateAttribute:DisplayName:Value"
      OutValue_1: "AttributeName"
      OutValue_2: "DisplayName"
      InValue_3: "CreateAttribute:ProductAttrName:Value"
      OutValue_3: "PresentationProdAttrName"
      InValue_4: "CreateAttribute:VariationSelection:Value"
      OutValue_4: "PresentationOption"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "UpdateAttribute:AttributeName:Value"
      InValue_2: "UpdateAttribute:DisplayName:Value"
      OutValue_1: "AttributeName"
      OutValue_2: "DisplayName"
      InValue_3: "UpdateAttribute:VariationSelection:Value"
      OutValue_3: "PresentationOption"
      InValue_4: "UpdateAttribute:ProductAttrName:Value"
      OutValue_4: "PresentationProdAttrName"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Selection"
      OutValue_1: "VariableVariationAttributeUUIDs"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentProductRepository:RepositoryDomain"
      OutValue_1: "ProductDomain"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductVariationAttribute_32"
  - id: "PrepareApplicationView4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/NewProductVariationAttribute_32"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_ID"
      Value: "NonUniqueID"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_ID"
      Value: "NonUniqueID"
  - id: "Touch1"
    type: "pipelet"
    ref: "Touch"
    bindings:
      Object: "Product"
  - id: "Touch2"
    type: "pipelet"
    ref: "Touch"
    bindings:
      Object: "Product"
  - id: "Touch3"
    type: "pipelet"
    ref: "Touch"
    bindings:
      Object: "Product"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "UpdateAttribute"
    bindings:
      WebForm: "UpdateAttribute"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "CreateAttribute"
    bindings:
      WebForm: "CreateAttribute"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "UpdateAttribute"
  - id: "ValidateWebForm2"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "CreateAttribute"

links:
  - from: "GetWebForm1"
    via: "error"
    to: "Join3"
    into: "in2"
  - from: "GetWebForm2"
    via: "error"
    to: "Join6"
    into: "in2"
  - from: "Call10"
    via: "next"
    to: "Touch3"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "GetLocale4"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "DetermineLocales1"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "DetermineLocales4"
    via: "next"
    to: "GetLocale3"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "ValidateWebForm2"
    via: "error"
    to: "Join7"
    into: "in2"
  - from: "Join3"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "Call8"
    via: "ERROR"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Touch1"
    via: "next"
    to: "Call12"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "GetVariableVariationAttributeByUUID1"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "ValidateWebForm1"
    via: "next"
    to: "DetermineLocales2"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "Touch1"
    into: "in"
  - from: "DetermineLocales3"
    via: "next"
    to: "GetLocale4"
    into: "in"
  - from: "GetLocale2"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "Touch2"
    via: "next"
    to: "Call11"
    into: "in"
  - from: "UpdateWebForm2"
    via: "next"
    to: "ValidateWebForm2"
    into: "in"
  - from: "GetWebForm2"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "GetLocale3"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "PrepareApplicationView4"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "Touch3"
    via: "next"
    to: "Call13"
    into: "in"
  - from: "Call9"
    via: "ERROR2"
    to: "Jump5"
    into: "in"
  - from: "Call9"
    via: "ERROR"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "DetermineLocales2"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "PrepareApplicationView4"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "GetVariableVariationAttributeByUUID1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "ValidateWebForm1"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "CreateWebForm1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "CallNode1"
    via: "NO_LOCK"
    to: "JumpNode1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Join5"
    into: "in2"
  - from: "KeyMapper2"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "Touch2"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "CreateWebForm2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Call4"
    via: "error-product-not-available"
    to: "JumpNode2"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "DetermineLocales3"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "ValidateWebForm2"
    via: "next"
    to: "DetermineLocales4"
    into: "in"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "Call11"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "CreateWebForm2"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "Call12"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Call13"
    via: "next"
    to: "Jump6"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "Call7"
    into: "in"
