flow: "ViewPromotionContentAssignment"
kind: "view"

entries:
  - id: "StartNode1"
    name: "AssignPageVariants"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode16"
    name: "AssignPageVariantsPaging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "CreateAssign"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "AssignComponents"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "AssignComponentsPaging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "DispatchPageVariantAssignment"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "DispatchComponentAssignment"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "AssignPageletPrefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "GetPageletsAssignedToPromotionOrCampaign"
    mode: "private"
    strict: true
    inputs:
      - key: "RepositoryDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewPromotionContent-Prefix"
  - id: "CallNode10"
    type: "call"
    ref: "ProcessPageletSearch-RemoveCurrentClipboard"
    bindings:
      ContentRepository: "ChannelRepository"
      UniquePageletSearchID: "\"NewPromotionComponentAssignment\""
  - id: "CallNode11"
    type: "call"
    ref: "ProcessPromotion-CreateAssignment"
    bindings:
      Repository: "ChannelRepository"
      To: "ContextObject"
  - id: "CallNode12"
    type: "call"
    ref: "ProcessPageletSearch-UpdateClipboard"
    bindings:
      ContentRepository: "ChannelRepository"
  - id: "CallNode17"
    type: "call"
    ref: "ViewPromotionContent-Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "ViewPromotionContent-Prefix"
  - id: "CallNode3"
    type: "call"
    ref: "ViewPromotionContentAssignment-GetPageletsAssignedToPromotionOrCampaign"
    bindings:
      RepositoryDomain: "ChannelRepository:Domain"
      AssignedPagelets: "PageletsAssignedToPromotion"
  - id: "CallNode4"
    type: "call"
    ref: "ViewPromotionContentAssignment-GetPageletsAssignedToPromotionOrCampaign"
    bindings:
      RepositoryDomain: "ChannelRepository:Domain"
      AssignedPagelets: "PageletsAssignedToPromotion"
  - id: "CallNode5"
    type: "call"
    ref: "ViewPromotionContentAssignment-AssignPageletPrefix"
  - id: "CallNode6"
    type: "call"
    ref: "ViewPromotionContentAssignment-AssignPageletPrefix"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessPageletSearch-UpdateClipboard"
    bindings:
      ContentRepository: "ChannelRepository"
      UniquePageletSearchID: "\"NewPromotionComponentAssignment\""
  - id: "CallNode8"
    type: "call"
    ref: "ProcessPageletSearch-UpdateClipboard"
    bindings:
      ContentRepository: "ChannelRepository"
      UniquePageletSearchID: "\"NewPromotionPageVariantAssignment\""
  - id: "CallNode9"
    type: "call"
    ref: "ProcessPageletSearch-RemoveCurrentClipboard"
    bindings:
      ContentRepository: "ChannelRepository"
      UniquePageletSearchID: "\"NewPromotionPageVariantAssignment\""
  - id: "DecisionNode0"
    type: "decision"
    condition: "Count"
  - id: "DecisionNode1"
    type: "decision"
    condition: "AssignmentType"
  - id: "DecisionNode2"
    type: "decision"
    condition: "PageletClipboard:ObjectUUIDsCount"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPromotionContentAssignment-CreateAssign"
      PagingPipeline: "ViewPromotionContentAssignment-AssignPageVariantsPaging"
      OutValue_1: "ViewPromotionContent-View"
    bindings:
      Key_0: "assign"
      Key_1: "cancel"
      SelectionKey: "JumpTarget"
  - id: "DispatchFormAction3"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPromotionContentAssignment-CreateAssign"
      PagingPipeline: "ViewPromotionContentAssignment-AssignComponentsPaging"
      OutValue_1: "ViewPromotionContent-View"
    bindings:
      Key_0: "assign"
      Key_1: "cancel"
      SelectionKey: "JumpTarget"
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "AssignedPagelets"
        type: "java.util.Iterator"
        guaranteed: false
  - id: "ExecuteCountQuery0"
    type: "pipelet"
    ref: "ExecuteCountQuery"
    config:
      ParameterName_02: "Domain"
      ParameterName_01: "Pageletuuid"
      QueryName: "marketing/GetAssignedPageletExceptABTest"
    bindings:
      ParameterValue_02: "RepositoryDomain"
      ParameterValue_01: "SelectedPageletUUID"
  - id: "ExecutePageableQuery3"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "marketing/GetAllAssignedPageletsExceptABTest"
      DefaultPageSize: 0
      ParameterName_01: "Domain"
      Datasource: "default"
    bindings:
      ParameterValue_01: "RepositoryDomain"
      SearchResult: "AssignedPagelets"
  - id: "GetPageletByUUID1"
    type: "pipelet"
    ref: "GetPageletByUUID"
    bindings:
      PageletUUID: "SelectedPageletUUID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd7"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode0"
    type: "jump"
    ref: "ViewPromotionContentAssignment-AssignComponentsPaging"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewPromotionContentAssignment-AssignPageVariantsPaging"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewPromotionContent-View"
  - id: "LoopNode0"
    type: "loop"
  - id: "LoopNode1"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "marketing/NewPromotionPageVariantAssignment"
      SelectedMenuItem: "Marketing"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "marketing/NewPromotionComponentAssignment"
      SelectedMenuItem: "Marketing"
  - id: "SetDictionaryValue0"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      ValueType: "Dictionary Value"
      Name: "ERROR_ASSIGNED_PAGELET"
      Value: "ERROR_ASSIGNED_PAGELET"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewPromotionContentAssignment-AssignComponentsPaging"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "SearchStartFlag"
      Value: true
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewPromotionContentAssignment-AssignPageVariantsPaging"
  - id: "SetValuesToContainer1"
    type: "pipelet"
    ref: "SetValuesToContainer"
    config:
      DefaultContainerName: "NewAssignmentValues"
  - id: "SetValuesToContainer4"
    type: "pipelet"
    ref: "SetValuesToContainer"
    config:
      DefaultContainerName: "NewAssignmentValues"
  - id: "SetValuesToContainer5"
    type: "pipelet"
    ref: "SetValuesToContainer"
    bindings:
      ContainerName: "ContextObjectUUID"

links:
  - from: "CallNode10"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode11"
    via: "next"
    to: "LoopNode0"
    into: "loop"
  - from: "CallNode12"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "CallNode17"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "SetValuesToContainer1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "SetValuesToContainer4"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode8"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode9"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode0"
    via: "no"
    to: "SetDictionaryValue0"
    into: "in"
  - from: "DecisionNode0"
    via: "yes"
    to: "LoopNode1"
    into: "loop"
  - from: "DecisionNode1"
    via: "no"
    to: "JumpNode0"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JumpNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "LoopNode1"
    into: "in"
  - from: "DispatchFormAction2"
    via: "error"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "DispatchFormAction2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DispatchFormAction3"
    via: "error"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "DispatchFormAction3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "ExecuteCountQuery0"
    via: "next"
    to: "DecisionNode0"
    into: "in"
  - from: "ExecutePageableQuery3"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "ExecutePageableQuery3"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "GetPageletByUUID1"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "LoopNode0"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "LoopNode0"
    via: "do"
    to: "GetPageletByUUID1"
    into: "in"
  - from: "LoopNode0"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "ExecuteCountQuery0"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd7"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "SetDictionaryValue0"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "SetValuesToContainer5"
    into: "in"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "SetValuesToContainer1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "SetValuesToContainer4"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "SetValuesToContainer5"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "StartNode16"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode17"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "DispatchFormAction2"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "DispatchFormAction3"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "ExecutePageableQuery3"
    into: "in"
