flow: "ViewOrders"
kind: "view"

entries:
  - id: "Start13"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "SimpleOrderSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Detail"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "CancelOrder"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "ConfirmCancel"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddMultipleEntriesToMap1"
    type: "pipelet"
    ref: "AddMultipleEntriesToMap"
    config:
      Mode: "OverwriteValue"
    bindings:
      OutMap: "GenericHandlerPipelineParams"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessUser-GetProfile"
    bindings:
      User: "CurrentUser"
  - id: "CallNode10"
    type: "call"
    ref: "ViewOrders-Prefix"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessUser-CheckLoggedIn"
  - id: "CallNode12"
    type: "call"
    ref: "ProcessGiftCard-OrderCanBeCanceled"
    bindings:
      Result: "OrderCanBeCancelled"
  - id: "CallNode13"
    type: "call"
    ref: "ProcessGiftCard-HasGiftCards"
    bindings:
      ProductLineItems: "OrderBO:AllProductLineItems:Iterator"
  - id: "CallNode2"
    type: "call"
    ref: "ViewOrders-Prefix"
  - id: "CallNode3"
    type: "call"
    ref: "ViewOrders-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ViewData-SecureForBrowserBack"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessOrders-CancelOrder"
    bindings:
      User: "CurrentUser"
      Organization: "CurrentOrganization"
  - id: "CallNode6"
    type: "call"
    ref: "Paging-SetPageNumber"
    bindings:
      Pageable: "SortedOrders"
  - id: "CallNode7"
    type: "call"
    ref: "Paging-GetPageableByID"
    bindings:
      Pageable: "SortedOrders"
  - id: "CallNode8"
    type: "call"
    ref: "ViewOrders-Prefix"
  - id: "CallNode9"
    type: "call"
    ref: "ViewOrders-Prefix"
  - id: "CreateNavigationList1"
    type: "pipelet"
    ref: "CreateNavigationList"
    bindings:
      ElementCount: "SortedOrders:ElementCount"
      Iterator: "SortedOrders"
      PageableID: "SortedOrders:ID"
      PageCount: "SortedOrders:PageCount"
      PageSize: "SortedOrders:PageSize"
      CurrentPage: "SortedOrders:Page"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Order:StatusStateName"
  - id: "DecisionNode2"
    type: "decision"
    condition: "OrderCanBeCancelled"
  - id: "DecisionNode3"
    type: "decision"
    condition: "CurrentUser:ID"
  - id: "DecisionNode4"
    type: "decision"
    condition: "CurrentUser:ID"
  - id: "DecisionNode5"
    type: "decision"
    condition: "GiftCardProductLineItems"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewOrders-ConfirmCancel"
      OutValue_1: "ViewOrders-CancelOrder"
      OutValue_2: "ViewOrders-Detail"
    bindings:
      Key_1: "cancelOrder"
      SelectionKey: "JumpTarget"
      Key_0: "confirmCancel"
      Key_2: "cancelCancellation"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "order/OrderSearch"
      ParameterName_01: "Buyer"
      DefaultPageSize: 5
      ParameterName_02: "OrderDomain"
      ParameterName_03: "SearchForAuctionOrders"
    bindings:
      PageSize: "null"
      Parameters: "null"
      Connection: "null"
      ParameterValue_01: "CurrentUser"
      Query: "null"
      SearchResult: "SortedOrders"
      ParameterValue_02: "CurrentOrganization:OwningDomain"
      ParameterValue_03: "\"(Boolean)false\""
  - id: "GetOrderBO1"
    type: "pipelet"
    ref: "GetOrderBO"
  - id: "GetOrderBO2"
    type: "pipelet"
    ref: "GetOrderBO"
  - id: "GetOrderByID1"
    type: "pipelet"
    ref: "GetOrderByID"
  - id: "GetOrderByID4"
    type: "pipelet"
    ref: "GetOrderByID"
  - id: "InteractionNode8"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewPage-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewOrders-Detail"
  - id: "JumpNode3"
    type: "jump"
    ref: "Error-Page"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewOrders-Detail"
  - id: "JumpNode5"
    type: "jump"
    ref: "Error-Page"
  - id: "JumpNode6"
    type: "jump"
    ref: "ViewUserAccount-Start"
  - id: "JumpNode9"
    type: "jump"
    ref: "ViewPage-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "CurrentRequest:PipelineDictionary"
      OutValue_1: "Dictionary"
      InValue_3: "\"systempage.account.orderHistory.orderDetails.pagelet2-systempage.account.orderHistory.orderDetails\""
      OutValue_3: "PageletEntryPointID"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "JumpTarget"
      InValue_1: "\"ViewOrders-Detail\""
      OutValue_2: "AdditionalParameterName1"
      InValue_2: "\"OrderID\""
      InValue_3: "OrderID"
      OutValue_3: "AdditionalParameterValue1"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Order\"):getOrderBORepository(Order)"
      OutValue_1: "OrderBORepository"
  - id: "KeyMapper33"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "TargetPipeline"
      InValue_1: "\"ViewUserAccount-ShowLogin\""
      OutValue_2: "Protocol"
      InValue_2: "\"https\""
      OutValue_3: "TargetSite"
      OutValue_4: "Parameter1_Name"
      InValue_4: "\"TargetPipeline\""
      OutValue_5: "Parameter1_Value"
      InValue_5: "\"ViewOrders-SimpleOrderSearch\""
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "HandlerPipeline"
      InValue_1: "\"ViewOrders\""
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "CurrentRequest:PipelineDictionary"
      OutValue_1: "Dictionary"
      InValue_3: "\"systempage.account.orderHistory.pagelet2-systempage.account.orderHistory\""
      OutValue_3: "PageletEntryPointID"
  - id: "KeyMapper6"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Order\"):getOrderBORepository(Order)"
      OutValue_1: "OrderBORepository"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "TargetURL"
      RemoveFormValues: true
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "CancellationStatus"
      Value: "cancellationImpossible"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "CancellationStatus"
      Value: "cancellationSuccessful"
  - id: "SetDictionaryValue5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "CancellationStatus"
      Value: "confirmCancel"

links:
  - from: "StartNode2"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "AddMultipleEntriesToMap1"
    via: "next"
    to: "CreateNavigationList1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "GetOrderBO1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "GetOrderByID4"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "KeyMapper3"
    via: "next"
    to: "GetOrderBO1"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode5"
    into: "in2"
  - from: "CallNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "JumpNode9"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CreateNavigationList1"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "DispatchFormAction2"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Start13"
    via: "next"
    to: "DispatchFormAction2"
    into: "in"
  - from: "KeyMapper33"
    via: "next"
    to: "InteractionNode8"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "CallNode7"
    via: "ERROR"
    to: "JoinNode2"
    into: "in1"
  - from: "StartNode4"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "CallNode5"
    via: "ERROR"
    to: "JoinNode4"
    into: "in2"
  - from: "CallNode5"
    via: "next"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode7"
    into: "in2"
  - from: "CallNode11"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetOrderBO2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode11"
    via: "NOTLOGGEDIN"
    to: "Pipelet1"
    into: "in"
  - from: "KeyMapper6"
    via: "next"
    to: "GetOrderBO2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "GetOrderByID4"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "GetOrderByID1"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "SetDictionaryValue5"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode5"
    via: "yes"
    to: "JoinNode8"
    into: "in2"
  - from: "CallNode1"
    via: "ERROR"
    to: "JumpNode6"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode6"
    into: "in2"
  - from: "GetOrderByID4"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "KeyMapper3"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "GetOrderByID1"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "KeyMapper6"
    into: "in"
  - from: "GetOrderByID1"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode13"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "CallNode12"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "KeyMapper33"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "AddMultipleEntriesToMap1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "SetDictionaryValue5"
    via: "next"
    to: "JumpNode4"
    into: "in"
