flow: "ViewImageTypeList_32"
kind: "view"

entries:
  - id: "Start4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Prefix"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode7"
    name: "ListSortedPostDeletion"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "ListSorted"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessPaging-SetPageNumber"
    bindings:
      Pageable: "ImageViews"
  - id: "CallNode10"
    type: "call"
    ref: "ProcessPaging-SetPageSize"
    bindings:
      Pageable: "ImageTypes"
  - id: "CallNode11"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode12"
    type: "call"
    ref: "ProcessImageType-GetAllSorted"
    bindings:
      Domain: "ImageDefinitionDomain"
  - id: "CallNode13"
    type: "call"
    ref: "ProcessImage-DetermineImageDefinitionDomain"
    bindings:
      PreferenceDomain: "CurrentChannel:Domain"
  - id: "CallNode14"
    type: "call"
    ref: "ProcessPaging-GetPageLocatorPageable"
    bindings:
      PageLocatorName: "\"ImageTypeListLocator\""
  - id: "CallNode15"
    type: "call"
    ref: "ProcessPaging-SetPageSize"
  - id: "CallNode16"
    type: "call"
    ref: "ProcessPaging-SetPageNumber"
    bindings:
      Pageable: "ImageTypes"
  - id: "CallNode17"
    type: "call"
    ref: "ProcessImageType-GetAllSorted"
    bindings:
      Domain: "ImageDefinitionDomain"
  - id: "CallNode18"
    type: "call"
    ref: "ProcessImage-DetermineImageDefinitionDomain"
    bindings:
      PreferenceDomain: "CurrentChannel:Domain"
  - id: "CallNode19"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode20"
    type: "call"
    ref: "ViewImageTypeList-DetermineOldPageSizeAndPageNumber"
  - id: "CallNode21"
    type: "call"
    ref: "ProcessImage-DetermineImageDefinitionDomain"
    bindings:
      PreferenceDomain: "CurrentChannel:Domain"
  - id: "CallNode22"
    type: "call"
    ref: "ViewImageTypeList-DetermineOldPageSizeAndPageNumber"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessImageType-Get"
    bindings:
      Domain: "ImageDefinitionDomain"
      ImageTypeBORepository: "ApplicationBO:Extension(\"Image\"):ImageTypeBORepository(ImageDefinitionDomain:UUID)"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessImageType-Delete"
  - id: "CallNode7"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode8"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode9"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewImageType_32-New"
      OutValue_1: "ViewImageTypeList_32-ListSorted"
      OutValue_2: "ViewImageTypeList_32-Delete"
      PagingPipeline: "ViewImageTypeList_32-Paging"
      OutValue_3: "ViewImageTypeList_32-ListSorted"
      DefaultPageNumberPrefix: "PageNumber_"
      DefaultPageSizePrefix: "PageSize_"
    bindings:
      Key_0: "new"
      SelectionKey: "JumpTarget"
      Key_1: "confirmDelete"
      Key_2: "delete"
      Key_3: "cancel"
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "SessionRegistrationID"
        type: "java.lang.String"
        guaranteed: true
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InvalidatePageLocatorPageable11"
    type: "pipelet"
    ref: "InvalidatePageLocatorPageable"
    config:
      DefaultPageLocatorName: "ImageTypeListLocator"
    bindings:
      PageLocatorName: "null"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "This:ListAll"
  - id: "JumpNode4"
    type: "jump"
    ref: "This:ListSortedPostDeletion"
  - id: "Loop1"
    type: "loop"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ImageManagement"
      WorkingTemplate: "image/ImageTypeList_32"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewImageTypeList_32-ListAll"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "SessionRegistrationID"
      Value: "CB_ImageTypeList"
  - id: "SetPageLocator3"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultPageLocatorName: "ImageTypeListLocator"
      DefaultHandlerPipeline: "ViewImageTypeList_32-Paging"
      UsePageLocatorHistory: false
    bindings:
      Pageable: "ImageTypes"
      HandlerPipeline: "null"
      PageLocatorName: "null"

links:
  - from: "StartNode1"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode21"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "CallNode22"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "CallNode5"
    via: "ERROR"
    to: "JoinNode3"
    into: "in2"
  - from: "StartNode5"
    via: "next"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "CallNode5"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "StartNode8"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "CallNode17"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "SetPageLocator3"
    into: "in"
  - from: "CallNode16"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "CallNode7"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "CallNode22"
    via: "next"
    to: "InvalidatePageLocatorPageable11"
    into: "in"
  - from: "CallNode19"
    via: "next"
    to: "CallNode20"
    into: "in"
  - from: "InvalidatePageLocatorPageable11"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "CallNode14"
    via: "Error"
    to: "JumpNode1"
    into: "in"
  - from: "CallNode17"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode20"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode21"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "CallNode14"
    via: "next"
    to: "CallNode15"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "CallNode18"
    into: "in"
  - from: "CallNode18"
    via: "next"
    to: "CallNode19"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "CallNode15"
    via: "next"
    to: "CallNode16"
    into: "in"
  - from: "SetPageLocator3"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "JoinNode4"
    into: "in3"
