flow: "ViewChannelOutboundSyndicationClassificationMapping"
kind: "view"

entries:
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessChannelCatalog-GetClassificationCatalogs"
    bindings:
      Locale: "CurrentSession:Locale"
      SortBy: "\"name\""
      SortDirection: "\"asc\""
  - id: "CallNode2"
    type: "call"
    ref: "ProcessSyndicationRule-GetRuleSet"
    bindings:
      Name: "\"Classifications\""
  - id: "CallNode3"
    type: "call"
    ref: "ProcessSyndicationRule-GetRuleSet"
    bindings:
      Name: "\"Classifications\""
  - id: "CallNode4"
    type: "call"
    ref: "ProcessSyndicationRule-RemoveSyndicationRule"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessSyndicationRule-GetDataDeclarationList"
    bindings:
      Name: "\"Classifications\""
  - id: "CallNode6"
    type: "call"
    ref: "ProcessChannelCatalog-GetClassificationCatalogs"
    bindings:
      SortBy: "\"name\""
      SortDirection: "\"asc\""
      Locale: "CurrentSession:Locale"
  - id: "CreateSyndicationDataDeclaration1"
    type: "pipelet"
    ref: "CreateSyndicationDataDeclaration"
    bindings:
      Domain: "Syndication:Domain"
      DataObjectClassName: "\"com.intershop.beehive.xcs.internal.product.ProductPO\""
  - id: "CreateSyndicationRule1"
    type: "pipelet"
    ref: "CreateSyndicationRule"
    bindings:
      SyndicationRuleClass: "\"com.intershop.component.mvc.internal.syndication.mapping.ClassificationRuleProcessor\""
      Domain: "Syndication:Domain"
      SourceSyndicationDataDeclaration: "SyndicationDataDeclaration"
  - id: "DecisionNode1"
    type: "decision"
    condition: "SelectedClassificationCatalogUUIDs"
  - id: "DecisionNode2"
    type: "decision"
    condition: "SyndicationRuleUUID"
  - id: "DecisionNode3"
    type: "decision"
    condition: "SyndicationRuleUUID"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_1: "ViewChannelOutboundSyndicationList-Start"
      OutValue_2: "ViewChannelOutboundSyndicationClassificationMapping-Update"
      OutValue_0: "ViewChannelOutboundSyndicationClassificationMapping-Start"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "Start"
      Key_1: "Back"
      Key_2: "Update"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedClassificationCatalogUUID"
    bindings:
      Selection: "SelectedClassificationCatalogUUIDs"
  - id: "GetSyndicationByUUID1"
    type: "pipelet"
    ref: "GetSyndicationByUUID"
  - id: "GetSyndicationByUUID3"
    type: "pipelet"
    ref: "GetSyndicationByUUID"
  - id: "GetSyndicationRuleByUUID1"
    type: "pipelet"
    ref: "GetSyndicationRuleByUUID"
  - id: "GetSyndicationRuleByUUID2"
    type: "pipelet"
    ref: "GetSyndicationRuleByUUID"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode3"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "Jump5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/ChannelOutboundSyndicationClassificationMapping"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/ChannelOutboundSyndicationClassificationMapping"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "SyndicationRule"
      RemoveFormValues: false
  - id: "UpdateCustomAttribute1"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    config:
      DefaultAttributeName: "ClassificationCatalogUUID"
      DefaultAttributeType: "MultipleString"
    bindings:
      ExtensibleObject: "SyndicationRule:SourceSyndicationDataDeclaration"
      AttributeValue: "SelectedClassificationCatalogUUIDs"
      AttributeName: "null"
      AttributeType: "null"
      LocaleInformation: "null"

links:
  - from: "CallNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetSyndicationRuleByUUID1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "UpdateCustomAttribute1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "CreateSyndicationDataDeclaration1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "DecisionNode3"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode3"
    into: "in2"
  - from: "StartNode3"
    via: "next"
    to: "GetSyndicationByUUID3"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "DecisionNode2"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionNode3"
    into: "in"
  - from: "CreateSyndicationDataDeclaration1"
    via: "next"
    to: "CreateSyndicationRule1"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetSyndicationByUUID3"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "GetSyndicationRuleByUUID1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode6"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "UpdateCustomAttribute1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "GetSyndicationRuleByUUID2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetSyndicationByUUID1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "GetSyndicationByUUID1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "GetSyndicationRuleByUUID2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CreateSyndicationRule1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
