flow: "ViewProductClassification_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Unassign"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "List"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "UpdateAssignment"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "UpdateProductAttributes"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "CheckLock"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "SelectLevel"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddEntryToMap1"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "ClassificationMappings"
      Key: "Result:ID"
      Value: "Category"
      OutMap: "ClassificationMappings"
  - id: "AssignProductToCatalogCategory2"
    type: "pipelet"
    ref: "AssignProductToCatalogCategory"
    bindings:
      Domain: "Product:Domain"
      CatalogCategory: "ClassificationCategory"
  - id: "Call1"
    type: "call"
    ref: "ProcessChannelCatalog_52-GetClassificationCatalogs"
  - id: "Call3"
    type: "call"
    ref: "ProcessProduct-DetermineCategoryPath"
  - id: "Call4"
    type: "call"
    ref: "ViewProductClassification_52-Prefix"
  - id: "Call5"
    type: "call"
    ref: "ViewProductClassification_52-Prefix"
  - id: "Call6"
    type: "call"
    ref: "ViewProductClassification_52-Prefix"
  - id: "Call7"
    type: "call"
    ref: "ViewProductClassification_52-Prefix"
  - id: "Call8"
    type: "call"
    ref: "ViewProductClassification_52-UpdateProductAttributes"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessProductLock_52-Lookup"
  - id: "CallNode2"
    type: "call"
    ref: "ViewProductClassification_52-CheckLock"
  - id: "CallNode3"
    type: "call"
    ref: "ViewProductClassification_52-CheckLock"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessProductLock_52-Lookup"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessProductLock_52-Check"
  - id: "CallNode6"
    type: "call"
    ref: "ViewProductClassification_52-UpdateAssignment"
  - id: "CallNode7"
    type: "call"
    ref: "ViewProductClassification-UpdateProductAttributes"
  - id: "Decision10"
    type: "decision"
    condition: "SharedAssignment"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ClassificationCategory"
  - id: "DecisionNode4"
    type: "decision"
    condition: "SharedAssignment"
  - id: "DetermineCatalogCategory1"
    type: "pipelet"
    ref: "DetermineCatalogCategory"
    bindings:
      CatalogCategoryID: "SelectedCategoryID"
      Category: "ClassificationCategory"
  - id: "DetermineCatalogCategory4"
    type: "pipelet"
    ref: "DetermineCatalogCategory"
    bindings:
      CatalogCategoryID: "ClassificationCategoryID"
      Category: "ExistingCategory"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProductClassification_52-Unassign"
      OutValue_1: "ViewProductClassification_52-List"
      OutValue_2: "ViewProductClassification_52-Update"
      OutValue_3: "ViewProductClassification_52-Start"
    bindings:
      Key_0: "unbind"
      Key_1: "cancel"
      Key_2: "update"
      Key_3: "reset"
      SelectionKey: "JumpTarget"
  - id: "End2"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "ExecuteObjectsQuery1"
    type: "pipelet"
    ref: "ExecuteObjectsQuery"
    config:
      QueryName: "product/GetProductClassifications"
      ParameterName_01: "Product"
    bindings:
      ParameterValue_01: "Product"
  - id: "GetCatalogByUUID1"
    type: "pipelet"
    ref: "GetCatalogByUUID"
  - id: "GetCatalogCategoryPath1"
    type: "pipelet"
    ref: "GetCatalogCategoryPath"
    bindings:
      CatalogCategoryID: "null"
      Category: "ClassificationCategory"
  - id: "GetCategoryByUUID1"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "Result:UUID"
  - id: "GetCategoryByUUID2"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "SelectedCategoryID"
      Category: "ClassificationCategory"
  - id: "GetCategoryByUUID4"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "ClassificationCategoryID"
      Category: "ClassificationCategory"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductLockActivated"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceStringValue: "ProductLockActivated"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetProductByUUID5"
    type: "pipelet"
    ref: "GetProductByUUID"
    bindings:
      ProductUUID: "ProductID"
      ProductDomain: "CurrentProductRepository:RepositoryDomain"
  - id: "GetProductType1"
    type: "pipelet"
    ref: "GetProductType"
    bindings:
      ProductTypeDomainName: "ClassificationCategory:Domain:DomainName"
      ProductTypeName: "ClassificationCategory:Name"
      ProductTypeUUID: "null"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode15"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewProductClassification_52-List"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewProductClassification_52-List"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewProduct_52-ErrorProductNotAvailable"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Catalog:Root"
      OutValue_1: "ClassificationCategory"
  - id: "LoopNode1"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductClassificationList_52"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductClassificationDetails_52"
  - id: "RemoveProductCategoryBinding1"
    type: "pipelet"
    ref: "RemoveProductCategoryBinding"
    bindings:
      CatalogCategory: "ExistingCategory"
  - id: "SortIteratorByComparator1"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    bindings:
      Iterator: "ClassificationCatalogs"
      SortingAttribute: "classificationSortAttribute"
      SortingOrder: "classificationSortOrder"
      SortedIterator: "ClassificationCatalogs"

links:
  - from: "CallNode7"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode6"
    into: "in2"
  - from: "Decision10"
    via: "no"
    to: "JoinNode6"
    into: "in1"
  - from: "Decision10"
    via: "yes"
    to: "DecisionNode4"
    into: "in"
  - from: "AssignProductToCatalogCategory2"
    via: "next"
    to: "JoinNode15"
    into: "in3"
  - from: "JoinNode6"
    via: "next"
    to: "AssignProductToCatalogCategory2"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "DetermineCatalogCategory1"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "JoinNode15"
    into: "in1"
  - from: "JoinNode15"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "DetermineCatalogCategory1"
    via: "next"
    to: "Decision10"
    into: "in"
  - from: "DetermineCatalogCategory1"
    via: "error"
    to: "JoinNode15"
    into: "in1"
  - from: "AddEntryToMap1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "Call1"
    via: "next"
    to: "SortIteratorByComparator1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "DetermineCatalogCategory4"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "ExecuteObjectsQuery1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "CallNode5"
    via: "NO_LOCK"
    to: "JumpNode1"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "KeyMapper2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode8"
    into: "in1"
  - from: "DetermineCatalogCategory4"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "DetermineCatalogCategory4"
    via: "next"
    to: "RemoveProductCategoryBinding1"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "DispatchFormAction2"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "ExecuteObjectsQuery1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "ExecuteObjectsQuery1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetCatalogByUUID1"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "GetCatalogByUUID1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetCatalogCategoryPath1"
    via: "next"
    to: "GetProductType1"
    into: "in"
  - from: "GetCategoryByUUID1"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "GetCategoryByUUID1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GetCategoryByUUID2"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "GetCategoryByUUID2"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "GetCategoryByUUID4"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "GetCategoryByUUID4"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "GetDomainPreference1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetDomainPreference1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetLocale1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "GetLocale2"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "GetProductByUUID5"
    via: "error"
    to: "JumpNode2"
    into: "in"
  - from: "GetProductByUUID5"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "GetProductType1"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "GetProductType1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "JoinNode10"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "AddEntryToMap1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "GetCatalogByUUID1"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "GetCatalogCategoryPath1"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "LoopNode1"
    via: "do"
    to: "GetCategoryByUUID1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "RemoveProductCategoryBinding1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "SortIteratorByComparator1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction2"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "GetCategoryByUUID4"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "GetProductByUUID5"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetCategoryByUUID2"
    into: "in"
