flow: "ViewProductAuctionCategoryAssignmentWizard_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Collapse"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start10"
    name: "CategoryTree"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start11"
    name: "DispatchSelectedCategoryUUID"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start12"
    name: "CancelAssignment"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start13"
    name: "CategoryDetails"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start14"
    name: "CatalogDetails"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "SelectCatalog"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "GetProduct"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "PrepareProductAssignment"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "ListCatalogs"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "Expand"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "DispatchSelectCatalog"
    mode: "public"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-GetProduct"
  - id: "Call10"
    type: "call"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-GetProduct"
  - id: "Call11"
    type: "call"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-GetProduct"
  - id: "Call12"
    type: "call"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-GetProduct"
  - id: "Call13"
    type: "call"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-GetProduct"
  - id: "Call14"
    type: "call"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-Prefix"
  - id: "Call15"
    type: "call"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-Prefix"
  - id: "Call16"
    type: "call"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-Prefix"
  - id: "Call2"
    type: "call"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-Prefix"
  - id: "Call5"
    type: "call"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-Prefix"
  - id: "Call6"
    type: "call"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-Prefix"
  - id: "Call8"
    type: "call"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-Prefix"
  - id: "Call9"
    type: "call"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-GetProduct"
  - id: "CreateIteratorForPrefix1"
    type: "pipelet"
    ref: "CreateIteratorForPrefix"
    config:
      Prefix: "ProductID"
  - id: "Decision1"
    type: "decision"
    condition: "CatalogUUID"
  - id: "Decision2"
    type: "decision"
    condition: "SelectedCategoryUUID"
  - id: "Decision6"
    type: "decision"
    condition: "ProductID"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProductAuctionCategoryAssignmentWizard_52-DispatchSelectCatalog"
      OutValue_1: "ViewProductAuctionCategoryAssignmentWizard_52-CancelAssignment"
      OutValue_2: "ViewProductAuctionCategoryAssignmentWizard_52-DispatchSelectedCategoryUUID"
    bindings:
      Key_0: "selectCatalog"
      Key_1: "cancel"
      Key_2: "finish"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "ExchangeSessionObject1"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "CatalogID"
    bindings:
      LoadObject: "CatalogID"
      SaveObject: "CatalogID"
  - id: "ExchangeSessionObject2"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ProductID"
    bindings:
      LoadObject: "ProductID"
  - id: "ExchangeSessionObject3"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "ProductID"
    bindings:
      SaveObject: "ProductID"
  - id: "ExchangeSessionObject4"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "ProductUUIDs"
    bindings:
      SaveObject: "PrefixIterator"
  - id: "ExchangeSessionObject5"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      SaveObject: "ExpandedCategoriesMap"
  - id: "ExchangeSessionObject6"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      LoadObject: "ExpandedCategoriesMap"
  - id: "ExchangeSessionObject7"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      LoadObject: "ExpandedCategoriesMap"
  - id: "GetCatalogByUUID1"
    type: "pipelet"
    ref: "GetCatalogByUUID"
  - id: "GetCatalogByUUID2"
    type: "pipelet"
    ref: "GetCatalogByUUID"
  - id: "GetCatalogByUUID3"
    type: "pipelet"
    ref: "GetCatalogByUUID"
  - id: "GetCatalogByUUID4"
    type: "pipelet"
    ref: "GetCatalogByUUID"
  - id: "GetCatalogByUUID5"
    type: "pipelet"
    ref: "GetCatalogByUUID"
  - id: "GetCatalogs1"
    type: "pipelet"
    ref: "GetCatalogs"
    config:
      CatalogType: "Custom"
      CustomCatalogType: 6
    bindings:
      OrganizationDomain: "ChannelRepository:Domain"
  - id: "GetCategoryByUUID1"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "CategoryUUID"
  - id: "GetProductByUUID1"
    type: "pipelet"
    ref: "GetProductByUUID"
    bindings:
      ProductUUID: "ProductID"
      ProductDomain: "CurrentProductRepository:RepositoryDomain"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "InteractionEnd4"
    type: "interaction"
  - id: "InteractionEnd5"
    type: "interaction"
  - id: "InteractionEnd6"
    type: "interaction"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewProductAuctionCategories_52-Start"
  - id: "Jump2"
    type: "jump"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-SelectCatalog"
  - id: "Jump3"
    type: "jump"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-ListCatalogs"
  - id: "Jump4"
    type: "jump"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-CategoryTree"
  - id: "Jump5"
    type: "jump"
    ref: "ViewProductAuctionCategories_52-AssignSelectedProducts"
  - id: "Jump7"
    type: "jump"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-CategoryTree"
  - id: "Jump8"
    type: "jump"
    ref: "ViewProductAuctionCategoryAssignmentWizard_52-ListCatalogs"
  - id: "Jump9"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Catalog:Root:UUID"
      InValue_2: "Catalog:Id"
      OutValue_1: "CatalogCategoryID"
      OutValue_2: "CatalogID"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Category"
      InValue_2: "CategoriesPath"
      OutValue_1: "JumpCategory"
      OutValue_2: "JumpPath"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductAuctionCategoryAssignmentViewCategoryDetails_52"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductAuctionCategoryAssignmentViewCatalogDetails_52"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductAuctionCategoryAssignmentSelectCategory_52"
  - id: "PrepareApplicationView4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductAuctionCategoryAssignmentSelectCategory_52"
  - id: "PrepareApplicationView5"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductAuctionCategoryAssignmentSelectCatalog_52"
  - id: "PrepareApplicationView6"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductAuctionCategoryAssignmentSelectCategory_52"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewProductAuctionCategoryAssignmentWizard_52-ListCatalogs"
  - id: "UpdateMapping1"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Remove"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "CategoryUUID"
      Value: "CategoryUUID"
  - id: "UpdateMapping2"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "CategoryUUID"
      Value: "CategoryUUID"
  - id: "UpdateMapping3"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "Catalog:Root:UUID"
      OutMap: "ExpandedCategoriesMap"
      Value: "Catalog:Root:UUID"

links:
  - from: "Start7"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "Join6"
    into: "in3"
  - from: "Decision6"
    via: "no"
    to: "Join7"
    into: "in1"
  - from: "GetProductByUUID1"
    via: "error"
    to: "Join7"
    into: "in1"
  - from: "PrepareApplicationView5"
    via: "next"
    to: "InteractionEnd6"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "ExchangeSessionObject3"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "ExchangeSessionObject1"
    into: "in"
  - from: "ExchangeSessionObject1"
    via: "next"
    to: "Jump7"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "ExchangeSessionObject3"
    via: "next"
    to: "CreateIteratorForPrefix1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "Jump9"
    into: "in"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "PrepareApplicationView6"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "PrepareApplicationView4"
    via: "next"
    to: "InteractionEnd5"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd4"
    into: "in"
  - from: "Start10"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "ExchangeSessionObject4"
    via: "next"
    to: "Jump8"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "ExchangeSessionObject6"
    via: "next"
    to: "UpdateMapping2"
    into: "in"
  - from: "UpdateMapping2"
    via: "next"
    to: "PrepareApplicationView4"
    into: "in"
  - from: "ExchangeSessionObject7"
    via: "next"
    to: "UpdateMapping1"
    into: "in"
  - from: "UpdateMapping1"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "UpdateMapping3"
    via: "next"
    to: "ExchangeSessionObject5"
    into: "in"
  - from: "ExchangeSessionObject5"
    via: "next"
    to: "PrepareApplicationView6"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call16"
    into: "in"
  - from: "Start14"
    via: "next"
    to: "Call15"
    into: "in"
  - from: "CreateIteratorForPrefix1"
    via: "next"
    to: "ExchangeSessionObject4"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Start13"
    via: "next"
    to: "Call14"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "GetCategoryByUUID1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "Call13"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "Call12"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Call11"
    into: "in"
  - from: "Call15"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "Call14"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "GetCategoryByUUID1"
    into: "in"
  - from: "ExchangeSessionObject2"
    via: "next"
    to: "Decision6"
    into: "in"
  - from: "Call16"
    via: "next"
    to: "GetCatalogByUUID5"
    into: "in"
  - from: "GetCatalogByUUID5"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "Call13"
    via: "next"
    to: "GetCatalogByUUID4"
    into: "in"
  - from: "GetCatalogByUUID4"
    via: "next"
    to: "UpdateMapping3"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "GetCatalogByUUID3"
    into: "in"
  - from: "GetCatalogByUUID3"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "Call12"
    via: "next"
    to: "GetCatalogByUUID2"
    into: "in"
  - from: "GetCatalogByUUID2"
    via: "next"
    to: "ExchangeSessionObject6"
    into: "in"
  - from: "Call11"
    via: "next"
    to: "GetCatalogByUUID1"
    into: "in"
  - from: "GetCatalogByUUID1"
    via: "next"
    to: "ExchangeSessionObject7"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "ExchangeSessionObject2"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Jump2"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Jump3"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "Jump5"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Jump4"
    into: "in"
  - from: "Start11"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Start12"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Decision6"
    via: "yes"
    to: "GetProductByUUID1"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "GetCatalogs1"
    into: "in"
  - from: "GetCatalogs1"
    via: "next"
    to: "PrepareApplicationView5"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "End2"
    into: "in"
  - from: "GetProductByUUID1"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Join6"
    via: "next"
    to: "End1"
    into: "in"
