flow: "ViewChannelPriceListExport"
kind: "view"

entries:
  - id: "Start1"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start31"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "SelectConfiguration"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Export"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Back"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "SetPriceLookup"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "OverwriteFile"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Cancel"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "CancelOverwriteFile"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "ObjectVector"
      Iterator: "Objects"
      Object: "PriceList"
      Objects: "null"
      OutVector: "ObjectVector"
  - id: "Call1"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call3"
    type: "call"
    ref: "ProcessImpexJob-Create"
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call5"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessPriceListSearch-SearchPriceListsByDomain"
    bindings:
      HideEmptyPriceLists: "\"(Boolean)true\""
      PriceListDomain: "CurrentSelectedChannel:Domain"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessImpexJob-IsFilenameTaken"
    bindings:
      Domain: "ChannelRepository:Domain"
      Filename: "ChannelPriceListExportForm:ExportFile:Value"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CreatePageableFromIterator2"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    config:
      Pagesize: 1000000
    bindings:
      Iterator: "Objects"
      Pageable: "PriceLists"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "ExportFile"
      param.1.required: true
      param.1.rule: "^[^.\\\\/:*?<>|\\s]([^\\\\/:*?<>|\\s]*[^.\\\\/:*?<>|\\s])?$"
      webform-id: "ChannelPriceListExportForm"
    bindings:
      WebForm: "ChannelPriceListExportForm"
  - id: "Decision1"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision3"
    type: "decision"
    condition: "ExportSearchResult"
  - id: "GetPageLocator11"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "PriceListChannelExport"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocatorName: "null"
  - id: "GetPageLocator2"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "PriceListChannelExport"
      RestorePageLocatorDictionary: "True"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "PriceLists"
      PageableID: "PageLocator:PageableID"
  - id: "GetPriceListByUUID1"
    type: "pipelet"
    ref: "GetPriceListByUUID"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "ChannelPriceListExportForm"
    bindings:
      WebForm: "ChannelPriceListExportForm"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "ChannelPriceListExportForm"
    bindings:
      WebForm: "ChannelPriceListExportForm"
  - id: "GetWebForm3"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "ChannelPriceListExportForm"
    bindings:
      WebForm: "ChannelPriceListExportForm"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "ViewChannelPriceListExport-Paging"
  - id: "Jump3"
    type: "jump"
  - id: "Jump5"
    type: "jump"
  - id: "JumpNode1"
    type: "jump"
  - id: "JumpNode2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "PageableID"
      InValue_2: "ChannelPriceListExportForm_ExportFile"
      OutValue_1: "ObjectsID"
      OutValue_2: "SelectedFile"
      InValue_3: "Locale:RegionalAttribute(DateTimePatternKey)"
      OutValue_3: "DateTimePattern"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "PriceLists:ID"
      InValue_2: "ChannelPriceListExportForm_ExportFile"
      OutValue_1: "ObjectsID"
      OutValue_2: "SelectedFile"
      InValue_3: "Locale:RegionalAttribute(DateTimePatternKey)"
      OutValue_3: "DateTimePattern"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ChannelRepository:Domain"
      InValue_2: "ChannelRepository:Domain"
      OutValue_1: "ProcessOwningDomain"
      OutValue_2: "ProcessExecutionDomain"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentSelectedChannel:Domain"
      OutValue_1: "PriceListDomain"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      OutValue_1: "ProcessPipelineName"
      InValue_1: "\"ProcessExport\""
      OutValue_2: "ProcessPipelineStartNode"
      InValue_2: "\"Export\""
      InValue_3: "\"ProcessCatalogImpex\""
      OutValue_3: "JobName"
  - id: "Loop2"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_1: "ViewChannelPriceListExport-ListAll"
      OutValue_2: "ViewChannelPriceListExport-Paging"
      OutValue_3: "ViewChannelPriceListExport-SelectConfiguration"
      OutValue_4: "ViewChannelPriceListExport-Export"
      OutValue_5: "ViewChannelPriceListExport-Back"
      OutValue_6: "ViewChannelPriceListExport-Cancel"
      PagingPipeline: "ViewChannelPriceListExport-Paging"
      OutValue_0: "ViewChannelPriceListExport-SetPriceLookup"
      OutValue_7: "ViewChannelPriceListExport-OverwriteFile"
      OutValue_8: "ViewChannelPriceListExport-CancelOverwriteFile"
    bindings:
      Key_1: "ListAll"
      Key_2: "jumpToList"
      Key_3: "SelectConfiguration"
      Key_4: "Export"
      Key_5: "Back"
      Key_6: "Cancel"
      SelectionKey: "JumpTarget"
      Key_0: "SetPriceLookup"
      Key_7: "Overwrite"
      Key_8: "CancelOverwrite"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelCatalogs"
      WorkingTemplate: "impex/PriceListExportSelectLists"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelImportExport"
      WorkingTemplate: "impex/ChannelPriceListExportSelectConfiguration"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "FILENAME_ALREADY_IN_USE"
      Value: true
  - id: "SetDomainPreference1"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "PriceListPriceLookUp"
      Type: "String"
      DefaultPreferenceValue: "null"
    bindings:
      PreferenceDomain: "CurrentChannel:Domain"
      PreferenceStringValue: "PriceLookUp"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceKey: "null"
      PreferenceValue: "null"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "PriceLists"
  - id: "SetPage3"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "PriceLists"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewChannelPriceListExport-Paging"
      DefaultPageLocatorName: "PriceListChannelExport"
    bindings:
      HandlerPipeline: "null"
      PageLocatorName: "null"
      Pageable: "PriceLists"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "ChannelPriceListExportForm"
    bindings:
      WebForm: "ChannelPriceListExportForm"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "ChannelPriceListExportForm"
    bindings:
      WebForm: "ChannelPriceListExportForm"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "ChannelPriceListExportForm"
  - id: "ValidateWebForm2"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "ChannelPriceListExportForm"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      Locale: "null"
      LocalizedString: "PageNumber"
      Pattern: "null"

links:
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "Join5"
    into: "in3"
  - from: "GetPageLocator2"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage3"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "SetPage2"
    into: "in"
  - from: "CallNode2"
    via: "FILENAME_ALREADY_IN_USE"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "SetPage2"
    via: "next"
    to: "Join2"
    into: "in3"
  - from: "Call4"
    via: "next"
    to: "GetPageLocator11"
    into: "in"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetPageLocator11"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "Start1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "CreateWebForm1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "Decision1"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "SetPage3"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "Join2"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "SetDomainPreference1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "ValidateWebForm1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "SetDomainPreference1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "Start31"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join2"
    into: "in1"
  - from: "Loop2"
    via: "next"
    to: "CreatePageableFromIterator2"
    into: "in"
  - from: "GetPriceListByUUID1"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "GetWebForm3"
    via: "next"
    to: "JoinNode6"
    into: "in3"
  - from: "Decision3"
    via: "no"
    to: "Call5"
    into: "in"
  - from: "CreatePageableFromIterator2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "ValidateWebForm1"
    via: "error"
    to: "JoinNode3"
    into: "in3"
  - from: "JoinNode4"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Loop2"
    into: "in"
  - from: "GetPageLocator11"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "KeyMapper3"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "SetPageLocator1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "GetPageLocator2"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "ValidateWebForm2"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "UpdateWebForm2"
    via: "next"
    to: "ValidateWebForm2"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "KeyMapper1"
    into: "in"
  - from: "Loop2"
    via: "do"
    to: "GetPriceListByUUID1"
    into: "in"
  - from: "GetWebForm2"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "GetWebForm3"
    into: "in"
  - from: "GetWebForm2"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "GetWebForm3"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "ValidateWebForm2"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "Call3"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "Pipelet1"
    via: "next"
    to: "JumpNode2"
    into: "in"
