flow: "ViewDepartmentUsers"
kind: "view"

entries:
  - id: "Start10"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start11"
    name: "DispatchUpdate"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start12"
    name: "ConfirmDelete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "UpdateUserRoles"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "EditUserRoles"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "RemoveUsers"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "UpdateClipboard"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AssignUserToOrganizationRole2"
    type: "pipelet"
    ref: "AssignUserToOrganizationRole"
    bindings:
      OrganizationRole: "Role"
  - id: "Call7"
    type: "call"
    ref: "ProcessUserList-BySimpleSearch"
  - id: "Call8"
    type: "call"
    ref: "ViewDepartmentUsers-UpdateClipboard"
  - id: "Call9"
    type: "call"
    ref: "ViewDepartmentUsers-UpdateClipboard"
  - id: "CreateIteratorForPrefix1"
    type: "pipelet"
    ref: "CreateIteratorForPrefix"
    config:
      Prefix: "SelectedRole"
    bindings:
      PrefixIterator: "SelectedRoleUUIDs"
  - id: "Decision1"
    type: "decision"
    condition: "SearchRoleID"
  - id: "Decision2"
    type: "decision"
    condition: "SearchRoleID"
  - id: "Decision3"
    type: "decision"
    condition: "Department"
  - id: "DecisionNode1"
    type: "decision"
    condition: "RemoveRolesMap:get(Role:ID)"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Roles"
  - id: "DeterminePageable1"
    type: "pipelet"
    ref: "DeterminePageable"
  - id: "DetermineUser1"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "UserUUID"
  - id: "DetermineUser2"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "UserUUID"
  - id: "DetermineUser3"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "UserUUID"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewDepartmentUsers-Start"
      OutValue_1: "ViewDepartmentUserWizard-Start"
      OutValue_2: "ViewDepartmentUsers-ConfirmDelete"
      OutValue_3: "ViewDepartmentUsers-RemoveUsers"
      OutValue_4: "ViewDepartmentUsers-Start"
      OutValue_5: "ViewDepartment-List"
    bindings:
      Key_0: "find"
      Key_1: "new"
      Key_2: "confirmDelete"
      Key_3: "delete"
      Key_4: "cancel"
      Key_5: "back"
      SelectionKey: "JumpTarget"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewDepartmentUsers-UpdateUserRoles"
      OutValue_1: "ViewDepartmentUsers-Start"
    bindings:
      Key_0: "update"
      Key_1: "cancel"
      SelectionKey: "JumpTarget"
  - id: "End4"
    type: "end"
    strict: false
  - id: "GetAssignedOrganizationRoles1"
    type: "pipelet"
    ref: "GetAssignedOrganizationRoles"
    config:
      Membership: "Direct"
  - id: "GetAssignedOrganizationRoles2"
    type: "pipelet"
    ref: "GetAssignedOrganizationRoles"
    config:
      Membership: "Direct"
  - id: "GetAssignedOrganizationRoles3"
    type: "pipelet"
    ref: "GetAssignedOrganizationRoles"
    config:
      Membership: "Direct"
    bindings:
      UserRolesSize: "null"
      UserRoles: "RemoveRoles"
      UserRolesHash: "RemoveRolesMap"
  - id: "GetClipboard1"
    type: "pipelet"
    ref: "GetClipboard"
    config:
      SessionRegistrationID: "depUserList"
      SetFormValues: "No"
    bindings:
      UUIDIterator: "SelectedUserUUIDs"
  - id: "GetDepartment1"
    type: "pipelet"
    ref: "GetDepartment"
    config:
      Source: "PipelineDictionary"
  - id: "GetDepartment2"
    type: "pipelet"
    ref: "GetDepartment"
    config:
      Source: "PipelineDictionary"
  - id: "GetDepartment3"
    type: "pipelet"
    ref: "GetDepartment"
    config:
      Source: "PipelineDictionary"
  - id: "GetDepartment4"
    type: "pipelet"
    ref: "GetDepartment"
    config:
      Source: "PipelineDictionary"
  - id: "GetDepartment5"
    type: "pipelet"
    ref: "GetDepartment"
    config:
      Source: "PipelineDictionary"
  - id: "GetFormSelection4"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedUser"
    bindings:
      Selection: "SelectedObjectUUIDs"
  - id: "GetFormSelection5"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "user"
    bindings:
      Selection: "AllObjectUUIDs"
  - id: "GetRole1"
    type: "pipelet"
    ref: "GetRole"
    bindings:
      RoleID: "SearchRoleID"
  - id: "GetRole3"
    type: "pipelet"
    ref: "GetRole"
    bindings:
      RoleID: "RoleUUID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "Jump14"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump15"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump2"
    type: "jump"
    ref: "ViewDepartmentUsers-Start"
  - id: "Jump3"
    type: "jump"
    ref: "ViewDepartment-List"
  - id: "Jump4"
    type: "jump"
    ref: "ViewDepartmentUsers-Start"
  - id: "Jump5"
    type: "jump"
    ref: "ViewDepartment-List"
  - id: "Jump6"
    type: "jump"
    ref: "ViewDepartmentUsers-Start"
  - id: "Jump9"
    type: "jump"
    ref: "ViewDepartmentUsers-Paging"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "OrganizationDomain"
      OutValue_1: "UserDomain"
  - id: "ListDepartmentRoles1"
    type: "pipelet"
    ref: "ListDepartmentRoles"
  - id: "ListDepartmentRoles2"
    type: "pipelet"
    ref: "ListDepartmentRoles"
  - id: "ListDepartmentRoles3"
    type: "pipelet"
    ref: "ListDepartmentRoles"
  - id: "ListDepartmentRoles4"
    type: "pipelet"
    ref: "ListDepartmentRoles"
  - id: "ListDepartmentRoles5"
    type: "pipelet"
    ref: "ListDepartmentRoles"
  - id: "Loop3"
    type: "loop"
  - id: "Loop4"
    type: "loop"
  - id: "Loop5"
    type: "loop"
  - id: "Loop6"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Departments"
      WorkingTemplate: "department/DepartmentUserList"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Departments"
      WorkingTemplate: "department/DepartmentUserRolesList"
  - id: "RemoveClipboard1"
    type: "pipelet"
    ref: "RemoveClipboard"
    config:
      SessionRegistrationID: "depUserList"
  - id: "RemoveUserFromOrganizationRole2"
    type: "pipelet"
    ref: "RemoveUserFromOrganizationRole"
    bindings:
      OrganizationRole: "UserRole"
  - id: "RemoveUserFromOrganizationRole3"
    type: "pipelet"
    ref: "RemoveUserFromOrganizationRole"
    bindings:
      OrganizationRole: "UserRole"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Filter"
      Value: "ProcessUserList-RoleFilter"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewDepartmentUsers-Start"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewDepartmentUsers-UpdateUserRoles"
      ValueType: "Dictionary Value"
  - id: "SwitchPage1"
    type: "pipelet"
    ref: "SwitchPage"
  - id: "UpdateClipboard1"
    type: "pipelet"
    ref: "UpdateClipboard"
    config:
      SessionRegistrationID: "depUserList"
      StoreFormValues: "No"
    bindings:
      UUIDIterator: "PrefixIterator"
  - id: "UpdateMapping1"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Remove"
    bindings:
      InMap: "RemoveRolesMap"
      Key: "Role:ID"
      Value: "null"
      OutMap: "RemoveRolesMap"
      Keys: "null"
      Values: "RemoveRoles"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "Loop4"
    via: "do"
    to: "DetermineUser3"
    into: "in"
  - from: "Loop4"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "GetDepartment3"
    via: "next"
    to: "ListDepartmentRoles5"
    into: "in"
  - from: "DetermineUser3"
    via: "next"
    to: "GetAssignedOrganizationRoles1"
    into: "in"
  - from: "GetAssignedOrganizationRoles1"
    via: "next"
    to: "Loop3"
    into: "in"
  - from: "Loop3"
    via: "do"
    to: "RemoveUserFromOrganizationRole2"
    into: "in"
  - from: "Loop3"
    via: "next"
    to: "Loop4"
    into: "loop"
  - from: "RemoveUserFromOrganizationRole2"
    via: "next"
    to: "Loop3"
    into: "loop"
  - from: "GetDepartment2"
    via: "next"
    to: "DetermineUser2"
    into: "in"
  - from: "DetermineUser2"
    via: "next"
    to: "ListDepartmentRoles3"
    into: "in"
  - from: "DeterminePageable1"
    via: "next"
    to: "SwitchPage1"
    into: "in"
  - from: "ListDepartmentRoles3"
    via: "next"
    to: "GetAssignedOrganizationRoles2"
    into: "in"
  - from: "GetAssignedOrganizationRoles2"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "GetDepartment1"
    via: "next"
    to: "DetermineUser1"
    into: "in"
  - from: "DetermineUser1"
    via: "next"
    to: "ListDepartmentRoles2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "UpdateMapping1"
    into: "in"
  - from: "UpdateMapping1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Loop5"
    via: "do"
    to: "GetRole3"
    into: "in"
  - from: "AssignUserToOrganizationRole2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "RemoveUserFromOrganizationRole3"
    via: "next"
    to: "Loop6"
    into: "loop"
  - from: "DeterminePageable1"
    via: "error"
    to: "Jump4"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Loop5"
    into: "loop"
  - from: "Loop6"
    via: "do"
    to: "RemoveUserFromOrganizationRole3"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "AssignUserToOrganizationRole2"
    into: "in"
  - from: "Loop6"
    via: "next"
    to: "Jump6"
    into: "in"
  - from: "GetAssignedOrganizationRoles3"
    via: "next"
    to: "CreateIteratorForPrefix1"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "ListDepartmentRoles4"
    into: "in"
  - from: "GetRole1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "Join2"
    into: "in1"
  - from: "GetRole1"
    via: "error"
    to: "Join5"
    into: "in2"
  - from: "Decision3"
    via: "no"
    to: "GetDepartment4"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "ListDepartmentRoles1"
    into: "in"
  - from: "Call7"
    via: "ERROR"
    to: "JoinNode2"
    into: "in2"
  - from: "Decision2"
    via: "yes"
    to: "Decision1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "GetRole1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join1"
    into: "in2"
  - from: "Decision2"
    via: "no"
    to: "Join1"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "ListDepartmentRoles1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "Join4"
    into: "in1"
  - from: "Join3"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "RemoveClipboard1"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "GetFormSelection4"
    into: "in"
  - from: "GetFormSelection4"
    via: "next"
    to: "GetFormSelection5"
    into: "in"
  - from: "GetFormSelection5"
    via: "next"
    to: "UpdateClipboard1"
    into: "in"
  - from: "UpdateClipboard1"
    via: "next"
    to: "End4"
    into: "in"
  - from: "SwitchPage1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Call8"
    via: "next"
    to: "GetDepartment5"
    into: "in"
  - from: "Start12"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "GetDepartment4"
    via: "next"
    to: "Join4"
    into: "in3"
  - from: "Call9"
    via: "next"
    to: "Jump9"
    into: "in"
  - from: "ListDepartmentRoles5"
    via: "next"
    to: "GetClipboard1"
    into: "in"
  - from: "GetClipboard1"
    via: "next"
    to: "Loop4"
    into: "in"
  - from: "Start10"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Start11"
    via: "next"
    to: "DispatchFormAction2"
    into: "in"
  - from: "DispatchFormAction2"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "Jump14"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "Join6"
    into: "in3"
  - from: "GetDepartment4"
    via: "error"
    to: "Jump5"
    into: "in"
  - from: "DispatchFormAction2"
    via: "error"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "Jump15"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "Join7"
    into: "in3"
  - from: "Start4"
    via: "next"
    to: "RemoveClipboard1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "GetDepartment3"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "GetDepartment2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "GetDepartment1"
    into: "in"
  - from: "CreateIteratorForPrefix1"
    via: "next"
    to: "Loop5"
    into: "in"
  - from: "Loop5"
    via: "next"
    to: "Loop6"
    into: "in"
  - from: "GetDepartment5"
    via: "next"
    to: "DeterminePageable1"
    into: "in"
  - from: "GetRole3"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "ListDepartmentRoles2"
    via: "next"
    to: "GetAssignedOrganizationRoles3"
    into: "in"
  - from: "ListDepartmentRoles4"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "Join3"
    into: "in3"
  - from: "Call7"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "GetDepartment5"
    via: "error"
    to: "Jump3"
    into: "in"
