flow: "ViewAuctionExtension_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "ProcessUpdate"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "View"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewAuctionExtension_52-Prefix"
  - id: "Call2"
    type: "call"
    ref: "ViewAuctionExtension_52-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ViewAuctionExtension_52-ProcessUpdate"
  - id: "Call5"
    type: "call"
    ref: "ViewAuctionExtension_52-Prefix"
  - id: "Call6"
    type: "call"
    ref: "ProcessAuction-CheckStateForUpdate"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "Mode"
      param.1.required: true
      param.2.name: "CountString"
      param.2.required: false
      param.3.name: "Duration"
      param.3.required: false
      param.4.name: "MaxExtensionTimeUnit"
      param.4.required: false
      param.5.name: "Activation"
      param.5.required: false
      param.6.name: "ClosingPeriodUnit"
      param.6.required: false
      param.7.required: false
      param.8.required: false
      webform-id: "WFAuctionExtension"
    bindings:
      WebForm: "WFAuctionExtension"
  - id: "Decision3"
    type: "decision"
    condition: "WFAuctionExtension_Mode"
  - id: "Decision4"
    type: "decision"
    condition: "WFAuctionExtension_Mode"
  - id: "Decision5"
    type: "decision"
    condition: "WFAuctionExtension_Mode"
  - id: "End1"
    type: "end"
  - id: "End2"
    type: "end"
  - id: "GetAuction1"
    type: "pipelet"
    ref: "GetAuction"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "WFAuctionExtension"
    bindings:
      WebForm: "WFAuctionExtension"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd4"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewAuctionExtension_52-View"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "WFAuctionExtension_CountString"
      OutValue_1: "CountString"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "AuctionManagement"
      WorkingTemplate: "auction/AuctionUpdateExtension_52"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "AuctionManagement"
      WorkingTemplate: "auction/AuctionViewExtension_52"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "CountString"
      Value: 0
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "CountString"
      Value: -1
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ParseErrorCount"
      Value: "trueCountString"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ParseErrorDuration"
      Value: "trueCountString"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ParseErrorActivation"
      Value: "trueCountString"
      ValueType: "Dictionary Value"
  - id: "UpdateAuction1"
    type: "pipelet"
    ref: "UpdateAuction"
    bindings:
      DisplayName: "not used"
      EndTime: "not used"
      ExtensionCount: "Count"
      Locale: "not used"
      ShortDescription: "not used"
      StartTime: "not used"
  - id: "UpdateAuctionDefinition1"
    type: "pipelet"
    ref: "UpdateAuctionDefinition"
    bindings:
      AuctionDefinition: "Auction:Definition"
      ClosingPeriod: "Activation"
      ExtensionCount: "Count"
      ExtensionTime: "Duration"
  - id: "UpdateCustomAttributes1"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "ExtensionUnit"
      Attribute_1_Type: "Integer"
      Attribute_2_Name: "ClosingPeriodUnit"
      Attribute_2_Type: "Integer"
    bindings:
      Attribute_1_Value: "WFAuctionExtension_MaxExtensionTimeUnit"
      Attribute_2_Value: "WFAuctionExtension_ClosingPeriodUnit"
      ExtensibleObject: "Auction:Definition"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "WFAuctionExtension"
    bindings:
      WebForm: "WFAuctionExtension"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "WFAuctionExtension"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "Activation"
      LocalizedString: "WFAuctionExtension_Activation"
  - id: "VerifyInteger2"
    type: "pipelet"
    ref: "VerifyInteger"
    config:
      MinValue: -1
    bindings:
      IntegerObject: "Count"
      LocalizedString: "CountString"
  - id: "VerifyInteger3"
    type: "pipelet"
    ref: "VerifyInteger"
    config:
      MinValue: 0
    bindings:
      IntegerObject: "Duration"
      LocalizedString: "WFAuctionExtension_Duration"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "ValidateWebForm1"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "Join2"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CreateWebForm1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join3"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "Join3"
    into: "in2"
  - from: "ValidateWebForm1"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "Start4"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Decision4"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "KeyMapper1"
    into: "in"
  - from: "Decision4"
    via: "yes"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "VerifyInteger2"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Join5"
    via: "next"
    to: "Join4"
    into: "in3"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "Join5"
    into: "in2"
  - from: "KeyMapper1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "VerifyInteger2"
    via: "next"
    to: "Decision5"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "End2"
    into: "in"
  - from: "VerifyInteger2"
    via: "error"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "VerifyInteger3"
    via: "error"
    to: "SetDictionaryValue5"
    into: "in"
  - from: "VerifyInteger3"
    via: "next"
    to: "VerifyInteger1"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "UpdateCustomAttributes1"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "Join6"
    into: "in3"
  - from: "VerifyInteger1"
    via: "error"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "Join7"
    into: "in2"
  - from: "SetDictionaryValue5"
    via: "next"
    to: "Join8"
    into: "in2"
  - from: "UpdateAuctionDefinition1"
    via: "next"
    to: "UpdateAuction1"
    into: "in"
  - from: "Decision5"
    via: "no"
    to: "VerifyInteger3"
    into: "in"
  - from: "Decision5"
    via: "yes"
    to: "Join9"
    into: "in1"
  - from: "Join9"
    via: "next"
    to: "UpdateAuctionDefinition1"
    into: "in"
  - from: "UpdateCustomAttributes1"
    via: "next"
    to: "Join9"
    into: "in3"
  - from: "Start5"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd4"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "UpdateAuction1"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "GetAuction1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Call6"
    via: "ERROR"
    to: "Jump1"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "GetAuction1"
    into: "in"
