flow: "ViewPromotionTargetGroupUserGroupsSelection_52"
kind: "process"

entries:
  - id: "Start1"
    name: "ShowAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start10"
    name: "Back"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start31"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Search"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call5"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call7"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode1"
    type: "call"
    ref: "ViewPromotionTargetGroupUserGroupsSelection_52-Search"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessTargetGroupAssignableSearches-SearchUserGroups"
  - id: "CallNode29"
    type: "call"
    ref: "ProcessOrganization_52-GetConsumerOrg"
  - id: "CallNode3"
    type: "call"
    ref: "ViewPromotionTargetGroupUserGroupsSelection_52-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ViewPromotionTargetGroupUserGroupsSelection_52-Prefix"
  - id: "CallNode5"
    type: "call"
    ref: "ViewPromotionTargetGroupUserGroupsSelection_52-Prefix"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessOrganization_52-GetConsumerOrg"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessPromotion-TouchPromotion"
    bindings:
      Iterator: "UUIDIterator"
  - id: "CheckForEmptyIterator1"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "UUIDIterator"
  - id: "Decision1"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision2"
    type: "decision"
    condition: "PromotionUUID"
  - id: "Decision3"
    type: "decision"
    condition: "Promotion"
  - id: "DispatchFormAction11"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPromotionTargetGroup_52-ShowAll"
      OutValue_1: "ViewPromotionTargetGroupUserGroupsSelection_52-Create"
      PagingPipeline: "ViewPromotionTargetGroupUserGroupsSelection_52-Paging"
    bindings:
      Key_0: "cancel"
      Key_1: "assign"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "PromotionTargetGroupUserGroups"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocatorName: "null"
  - id: "GetPageLocator11"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "PromotionTargetGroupUserGroupsSelection"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocatorName: "null"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "UserGroups"
      PageableID: "PageLocator:PageableID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump21"
    type: "jump"
    ref: "ViewPromotionTargetGroup_52-ShowAllConsumerGroup"
  - id: "Jump22"
    type: "jump"
    ref: "ViewPromotionTargetGroupUserGroupsSelection_52-Paging"
  - id: "Jump5"
    type: "jump"
  - id: "Jump6"
    type: "jump"
    ref: "ViewPromotionTargetGroup_52-ShowAllConsumerGroup"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Organization:OrganizationDomain:Domain"
      OutValue_1: "UserGroupDomain"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "CurrentPageNumber"
      OutValue_1: "PageNumber"
  - id: "Loop1"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetPromotionTargetGroupUserGroups"
    bindings:
      UserGroups: "TargetGroupUserGroups"
  - id: "Pipelet12"
    type: "pipelet"
    ref: "GetPromotionByUUID"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "AddUserGroupToPromotionTargetGroup"
    bindings:
      UserGroup: "UserGroup"
  - id: "Pipelet31"
    type: "pipelet"
    ref: "DetermineUserGroup"
    bindings:
      CurrentDomain: "Organization:OrganizationDomain:Domain"
      UserGroup: "UserGroup"
      UserGroupID: "UserGroupID"
  - id: "PrepareApplicationView12"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/PromotionTargetGroupSelectUserGroups_52"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "UserGroups"
  - id: "SetPage3"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "UserGroups"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewPromotionTargetGroupUserGroupsSelection_52-Paging"
      DefaultPageLocatorName: "PromotionTargetGroupUserGroupsSelection"
    bindings:
      HandlerPipeline: "null"
      PageLocatorName: "null"
      Pageable: "UserGroups"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      Locale: "null"
      LocalizedString: "PageNumber"
      Pattern: "null"

links:
  - from: "SetPage3"
    via: "next"
    to: "Join5"
    into: "in2"
  - from: "CallNode8"
    via: "next"
    to: "Jump21"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "Pipelet31"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join5"
    into: "in3"
  - from: "SetPageLocator1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Decision3"
    via: "yes"
    to: "Decision2"
    into: "in"
  - from: "Pipelet12"
    via: "next"
    to: "Join3"
    into: "in2"
  - from: "Start31"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "PrepareApplicationView12"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "Decision1"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "CheckForEmptyIterator1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Pipelet31"
    via: "error"
    to: "JoinNode2"
    into: "in3"
  - from: "JoinNode1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "CallNode29"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "error"
    to: "KeyMapper2"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "Pipelet31"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "GetPageLocator1"
    via: "error"
    to: "Jump6"
    into: "in"
  - from: "GetPageLocator11"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "Pipelet12"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "SetPage2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage3"
    into: "in"
  - from: "DispatchFormAction11"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction11"
    into: "in"
  - from: "PrepareApplicationView12"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "GetPageLocator11"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetPageable1"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "CheckForEmptyIterator1"
    via: "next"
    to: "CallNode29"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "Jump22"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Join3"
    into: "in3"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "Decision2"
    via: "no"
    to: "Join3"
    into: "in1"
  - from: "CallNode4"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "End1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Start10"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
