flow: "ViewPromotionCampaignAssignment"
kind: "view"

entries:
  - id: "Start1"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "SearchAll"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentChannel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
  - id: "StartNode2"
    name: "Prefix"
    mode: "private"
    strict: true
    inputs:
      - key: "PromotionUUID"
        type: "java.lang.String"
        required: false
  - id: "StartNode25"
    name: "RemoveFromCampaign"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode26"
    name: "AssignToCampaign"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode27"
    name: "SearchCampaigns"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call2"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call22"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "CallNode1"
    type: "call"
    ref: "ViewPromotionCampaignAssignment-SearchAll"
  - id: "CallNode2"
    type: "call"
    ref: "ViewPromotionCampaignAssignment-Prefix"
  - id: "CallNode21"
    type: "call"
    ref: "ProcessPromotionCampaignAssignments-AssignPromotionToCampaign"
  - id: "CallNode3"
    type: "call"
    ref: "ViewPromotionCampaignAssignment-Prefix"
  - id: "CallNode30"
    type: "call"
    ref: "ProcessPromotionCampaignAssignments-RemovePromotionFromCampaign"
  - id: "CallNode4"
    type: "call"
    ref: "ViewPromotionCampaignAssignment-Prefix"
  - id: "Decision1"
    type: "decision"
    condition: "PageLocator"
  - id: "Decision2"
    type: "decision"
    condition: "PageNumber"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PromotionUUID"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPromotionCampaignAssignment-AssignToCampaign"
      OutValue_1: "ViewPromotion-Edit"
    bindings:
      Key_0: "assignToCampaign"
      SelectionKey: "JumpTarget"
      Key_1: "cancel"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "Campaigns"
        type: "com.intershop.beehive.core.capi.paging.PageableIterator"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "Promotion"
        type: "com.intershop.component.marketing.capi.rebate.Promotion"
        guaranteed: true
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      DefaultPageSize: 15
      QueryName: "marketing/AdvancedCampaignSearch"
      Datasource: "default"
    bindings:
      SearchResult: "Campaigns"
      Parameters: "QueryParameters"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Lead Locale"
    bindings:
      LocaleId: "CurrentRequest:Locale:LocaleID"
      Locale: "Locale"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "CategoryProductList"
      RestorePageLocatorDictionary: "True"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Products"
      PageableID: "PageLocator:PageableID"
  - id: "GetPromotionByUUID1"
    type: "pipelet"
    ref: "GetPromotionByUUID"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode17"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "Jump3"
    type: "jump"
    ref: "This:SearchCampaigns"
  - id: "Jump7"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewPromotion-Edit"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewPromotionCampaignAssignment-SearchCampaigns"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewPromotion-Edit"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CampaignList"
      OutValue_1: "PageLocator"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/PromotionCampaignSelection"
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewPromotionCampaignAssignment-Paging"
      ValueType: "Dictionary Value"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Products"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Campaigns"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewPromotionCampaignAssignment-Paging"
      DefaultPageLocatorName: "CampaignList"
    bindings:
      Pageable: "Campaigns"
      PageLocator: "CampaignList"
      PageLocatorName: "null"
  - id: "SetPageLocatorParameter1"
    type: "pipelet"
    ref: "SetPageLocatorParameter"
    config:
      DefaultParameterName: "CatalogCategoryID"
    bindings:
      PageLocator: "CampaignList"
      ParameterValue: "PromotionUUID"
  - id: "UpdateDictionary6"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "SortBy"
      Name_02: "SortDirection"
      Name_04: "Domain"
      Name_03: "Locale"
    bindings:
      Value_01: "SortBy"
      Value_02: "SortDirection"
      OutDictionary: "QueryParameters"
      Value_04: "CurrentChannel:RepositoryDomain"
      Value_03: "Locale"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"

links:
  - from: "CallNode21"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "GetPageLocator1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "GetPageable1"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "SetPage1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "SetPageLocatorParameter1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Decision1"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage2"
    into: "in"
  - from: "SetPageLocator1"
    via: "next"
    to: "SetPageLocatorParameter1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Join5"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join2"
    into: "in3"
  - from: "Decision1"
    via: "yes"
    to: "SetPage1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join5"
    into: "in3"
  - from: "GetPageable1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "CallNode30"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "UpdateDictionary6"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "UpdateDictionary6"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "JoinNode17"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "JoinNode17"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "error"
    to: "JoinNode17"
    into: "in2"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetPromotionByUUID1"
    into: "in"
  - from: "GetPromotionByUUID1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "StartNode25"
    via: "next"
    to: "CallNode30"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "GetPromotionByUUID1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "StartNode27"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Call22"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "CallNode21"
    via: "error"
    to: "JumpNode3"
    into: "in"
  - from: "Call22"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Jump7"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "StartNode26"
    via: "next"
    to: "CallNode21"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
