flow: "ViewPageletEntryPointEditing"
kind: "view"

entries:
  - id: "StartNode13"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "InternalStart"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode23"
    name: "Lock"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode29"
    name: "Unlock"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "GetPOAssignment"
    mode: "private"
    strict: false
    inputs:
      - key: "PageletEntryPoint"
        type: "com.intershop.component.pmc.capi.pagelet.PageletEntryPoint"
        required: true
      - key: "ContentRepositoryUUID"
        type: "java.lang.String"
        required: true
  - id: "StartNode30"
    name: "CheckLock"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewPageletEntryPoint-CreateFlagName"
  - id: "CallNode2"
    type: "call"
    ref: "ViewPageletEntryPoint-Prefix"
  - id: "CallNode22"
    type: "call"
    ref: "ViewPageletEntryPoint-Prefix"
  - id: "CallNode3"
    type: "call"
    ref: "ViewPageletEntryPoint-CreateFlagName"
  - id: "CallNode36"
    type: "call"
    ref: "ViewPageletEntryPoint-Prefix"
  - id: "CallNode37"
    type: "call"
    ref: "ProcessPageletEntryPointLock-Lock"
    bindings:
      LockingDomain: "ContentRepository:RepositoryDomain"
      PreferenceDomain: "ContentRepository:RepositoryDomain"
      User: "CurrentUser"
  - id: "CallNode38"
    type: "call"
    ref: "ProcessPageletEntryPointLock-Unlock"
    bindings:
      LockingDomain: "ContentRepository:RepositoryDomain"
      User: "CurrentUser"
  - id: "CallNode6"
    type: "call"
    ref: "ViewPageletEntryPoint-Prefix"
  - id: "DecisionNode1"
    type: "decision"
    condition: "AssignmentStrategy"
  - id: "DecisionNode2"
    type: "decision"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPageletEntryPointEditing-Lock"
      OutValue_1: "ViewPageletEntryPointEditing-Unlock"
      OutValue_2: "ViewPageletEntryPointEditing-CheckLock"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "lock"
      Key_1: "unlock"
      Key_2: "checkLock"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "POAssignment"
        type: "com.intershop.component.foundation.capi.assignment.Assignment"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "ExchangeSessionObject1"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SaveObject: "\"(Boolean)true\""
      SessionObjectName: "FlagName"
  - id: "ExchangeSessionObject3"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SaveObject: "null"
      SessionObjectName: "FlagName"
  - id: "GetAssignmentStrategy1"
    type: "pipelet"
    ref: "GetAssignmentStrategy"
    config:
      FromClass: "com.intershop.component.pmc.capi.pagelet.PageletEntryPoint"
      ToClass: "com.intershop.beehive.xcs.capi.catalog.CatalogCategory"
    bindings:
      Site: "ContentRepository:RepositoryDomain:Site"
  - id: "GetAssignmentStrategy2"
    type: "pipelet"
    ref: "GetAssignmentStrategy"
    config:
      FromClass: "com.intershop.component.pmc.capi.pagelet.PageletEntryPoint"
      ToClass: "com.intershop.beehive.xcs.capi.product.Product"
    bindings:
      Site: "ContentRepository:RepositoryDomain:Site"
  - id: "GetAssignments1"
    type: "pipelet"
    ref: "GetAssignments"
    bindings:
      From: "PageletEntryPoint"
      AssignmentLookup: "AssignmentStrategy:getAssignmentLookupStrategyByFrom(PageletEntryPoint)"
      To: "null"
      Domain: "ContentRepository:RepositoryDomain"
  - id: "GetFirstElementOfIterator1"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      Iterator: "Assignments:Iterator"
      FirstElement: "POAssignment"
  - id: "GetRepositoryByUUID2"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "ContentRepository"
      UUID: "ContentRepositoryUUID"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JumpNode5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "POType"
      InValue_1: "\"Category\""
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "POType"
      InValue_1: "\"Product\""
  - id: "Pipelet3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "id"
      OutValue_1: "PageletEntryPointUUID"
      InValue_2: "RepositoryUUID"
      OutValue_2: "ContentRepositoryUUID"

links:
  - from: "JoinNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "ExchangeSessionObject3"
    into: "in"
  - from: "StartNode23"
    via: "next"
    to: "CallNode22"
    into: "in"
  - from: "ExchangeSessionObject1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode38"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode22"
    via: "next"
    to: "CallNode37"
    into: "in"
  - from: "DispatchFormAction2"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "StartNode29"
    via: "next"
    to: "CallNode36"
    into: "in"
  - from: "CallNode37"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "CallNode36"
    via: "next"
    to: "CallNode38"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "ExchangeSessionObject1"
    into: "in"
  - from: "StartNode13"
    via: "next"
    to: "DispatchFormAction2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetRepositoryByUUID2"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "DecisionNode1"
    via: "no"
    to: "GetAssignmentStrategy2"
    into: "in"
  - from: "GetRepositoryByUUID2"
    via: "next"
    to: "GetAssignmentStrategy1"
    into: "in"
  - from: "GetRepositoryByUUID2"
    via: "error"
    to: "GetAssignmentStrategy1"
    into: "in"
  - from: "GetFirstElementOfIterator1"
    via: "error"
    to: "EndNode2"
    into: "in"
  - from: "GetAssignments1"
    via: "next"
    to: "GetFirstElementOfIterator1"
    into: "in"
  - from: "StartNode30"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode3"
    into: "in3"
  - from: "GetAssignmentStrategy1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetFirstElementOfIterator1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "DecisionNode2"
    via: "yes"
    to: "KeyMapper2"
    into: "in"
  - from: "GetAssignmentStrategy2"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "KeyMapper1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "GetAssignments1"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "JoinNode6"
    into: "in3"
  - from: "ExchangeSessionObject3"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "StartNode4"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode3"
    into: "in"
