flow: "ViewAuctionList_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Cancel"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Announce"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "ProcessCancel_TSI"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "ProcessDelete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "ProcessAnnounce"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "ProcessCancel"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewAuctionList_52-Prefix"
  - id: "Call2"
    type: "call"
    ref: "ViewAuctionList_52-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ViewAuctionList_52-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ViewAuctionList_52-ProcessCancel"
  - id: "Call5"
    type: "call"
    ref: "ViewAuctionList_52-ProcessDelete"
  - id: "Call6"
    type: "call"
    ref: "ViewAuctionList_52-ProcessAnnounce"
  - id: "Call7"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "CheckForEmptyIterator1"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "AuctionBids"
  - id: "CheckForEmptyIterator2"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "AuctionBids"
  - id: "CheckForEmptyIterator3"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "AuctionItems"
  - id: "Decision1"
    type: "decision"
    condition: "SelectedAuction:State"
  - id: "Decision2"
    type: "decision"
    condition: "SelectedAuction:State"
  - id: "Decision3"
    type: "decision"
    condition: "SelectedAuction:Definition:IncrementValue:Value"
  - id: "Decision4"
    type: "decision"
    condition: "SelectedAuction:State"
  - id: "Decision5"
    type: "decision"
    condition: "SelectedAuction:State"
  - id: "Decision6"
    type: "decision"
    condition: "OldAuctionState"
  - id: "Decision7"
    type: "decision"
    condition: "OldAuctionState"
  - id: "Decision8"
    type: "decision"
    condition: "SelectedAuction:Definition:IsHidden"
  - id: "End1"
    type: "end"
  - id: "End2"
    type: "end"
  - id: "End3"
    type: "end"
  - id: "End4"
    type: "end"
  - id: "End5"
    type: "end"
  - id: "GetAuction1"
    type: "pipelet"
    ref: "GetAuction"
    bindings:
      Auction: "SelectedAuction"
      AuctionUUID: "SelectedAuctionUUID"
  - id: "GetAuction2"
    type: "pipelet"
    ref: "GetAuction"
    bindings:
      Auction: "SelectedAuction"
      AuctionUUID: "SelectedAuctionUUID"
  - id: "GetAuction3"
    type: "pipelet"
    ref: "GetAuction"
    bindings:
      Auction: "SelectedAuction"
      AuctionUUID: "SelectedAuctionUUID"
  - id: "GetAuctionBids1"
    type: "pipelet"
    ref: "GetAuctionBids"
    config:
      DefaultBidState: 4
      Mode: "Standard"
    bindings:
      Auction: "SelectedAuction"
  - id: "GetAuctionBids2"
    type: "pipelet"
    ref: "GetAuctionBids"
    config:
      DefaultBidState: 4
      Mode: "Standard"
    bindings:
      Auction: "SelectedAuction"
  - id: "GetAuctionItems1"
    type: "pipelet"
    ref: "GetAuctionItems"
    bindings:
      Auction: "SelectedAuction"
  - id: "Join1"
    type: "join"
  - id: "Join10"
    type: "join"
  - id: "Join11"
    type: "join"
  - id: "Join12"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewAuctions_52-DispatchList"
  - id: "Jump2"
    type: "jump"
    ref: "ViewAuctions_52-DispatchList"
  - id: "Jump3"
    type: "jump"
    ref: "ViewAuctions_52-DispatchList"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "SelectedAuction:State"
      OutValue_1: "OldAuctionState"
  - id: "Loop1"
    type: "loop"
  - id: "Loop2"
    type: "loop"
  - id: "Loop3"
    type: "loop"
  - id: "RemoveAuction1"
    type: "pipelet"
    ref: "RemoveAuction"
    bindings:
      Auction: "SelectedAuction"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCodeList"
      Value: "ErrorCodeDelete"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCodeList"
      Value: "ErrorCodeCancel"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorCodeList"
      Value: "ErrorCodeAnnounce"
      ValueType: "Dictionary Value"
  - id: "Text1"
    type: "text"
  - id: "Text2"
    type: "text"
  - id: "UpdateAuctionState1"
    type: "pipelet"
    ref: "UpdateAuctionState"
    config:
      DefaultAuctionState: 16
    bindings:
      Auction: "SelectedAuction"
      AuctionState: "not used"
  - id: "UpdateAuctionState2"
    type: "pipelet"
    ref: "UpdateAuctionState"
    config:
      DefaultAuctionState: 1
    bindings:
      Auction: "SelectedAuction"
      AuctionState: "not used"
  - id: "UpdateAuctionState3"
    type: "pipelet"
    ref: "UpdateAuctionState"
    config:
      DefaultAuctionState: 16
    bindings:
      Auction: "SelectedAuction"
      AuctionState: "not used"
  - id: "UpdateRunningAuctionsCounter1"
    type: "pipelet"
    ref: "UpdateRunningAuctionsCounter"
    config:
      Mode: "Decrement"
    bindings:
      Auction: "SelectedAuction"

links:
  - from: "Start2"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Loop2"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Loop3"
    into: "in"
  - from: "Loop2"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "Loop3"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetAuction1"
    into: "in"
  - from: "Loop3"
    via: "do"
    to: "GetAuction3"
    into: "in"
  - from: "Loop2"
    via: "do"
    to: "GetAuction2"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "GetAuction1"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "GetAuction1"
    via: "error"
    to: "Join1"
    into: "in3"
  - from: "GetAuction2"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "GetAuction2"
    via: "error"
    to: "Join2"
    into: "in3"
  - from: "GetAuction3"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "GetAuction3"
    via: "error"
    to: "Join3"
    into: "in3"
  - from: "Join3"
    via: "next"
    to: "Loop3"
    into: "loop"
  - from: "Join2"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "Join1"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Call4"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Call5"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Call6"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "GetAuctionBids1"
    via: "next"
    to: "CheckForEmptyIterator1"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "error"
    to: "UpdateAuctionState1"
    into: "in"
  - from: "UpdateAuctionState1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "CheckForEmptyIterator1"
    via: "next"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "End2"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "Join4"
    into: "in3"
  - from: "Start5"
    via: "next"
    to: "GetAuctionBids1"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "RemoveAuction1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Join5"
    via: "next"
    to: "End3"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Join5"
    into: "in3"
  - from: "Join6"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "GetAuctionBids2"
    via: "next"
    to: "CheckForEmptyIterator2"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Decision2"
    into: "in"
  - from: "CheckForEmptyIterator2"
    via: "next"
    to: "Join6"
    into: "in2"
  - from: "Decision2"
    via: "yes"
    to: "GetAuctionBids2"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "RemoveAuction1"
    into: "in"
  - from: "CheckForEmptyIterator2"
    via: "error"
    to: "Join7"
    into: "in2"
  - from: "Decision2"
    via: "no"
    to: "Join7"
    into: "in1"
  - from: "GetAuctionItems1"
    via: "next"
    to: "CheckForEmptyIterator3"
    into: "in"
  - from: "CheckForEmptyIterator3"
    via: "next"
    to: "Decision8"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "Join12"
    into: "in1"
  - from: "Start7"
    via: "next"
    to: "Decision5"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Join8"
    into: "in2"
  - from: "CheckForEmptyIterator3"
    via: "error"
    to: "Join8"
    into: "in1"
  - from: "Join8"
    via: "next"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "Decision4"
    via: "yes"
    to: "Join7"
    into: "in3"
  - from: "Decision1"
    via: "no"
    to: "Decision4"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "Join6"
    into: "in1"
  - from: "Decision5"
    via: "yes"
    to: "GetAuctionItems1"
    into: "in"
  - from: "Decision5"
    via: "no"
    to: "Join8"
    into: "in3"
  - from: "Join9"
    via: "next"
    to: "End4"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "Join9"
    into: "in3"
  - from: "UpdateAuctionState2"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "UpdateAuctionState3"
    into: "in"
  - from: "UpdateAuctionState3"
    via: "next"
    to: "Decision6"
    into: "in"
  - from: "Decision6"
    via: "yes"
    to: "Decision7"
    into: "in"
  - from: "Decision7"
    via: "yes"
    to: "UpdateRunningAuctionsCounter1"
    into: "in"
  - from: "UpdateRunningAuctionsCounter1"
    via: "next"
    to: "Join10"
    into: "in1"
  - from: "Join10"
    via: "next"
    to: "End5"
    into: "in"
  - from: "Decision6"
    via: "no"
    to: "Join11"
    into: "in1"
  - from: "Join11"
    via: "next"
    to: "Join10"
    into: "in3"
  - from: "Decision7"
    via: "no"
    to: "Join11"
    into: "in2"
  - from: "Decision8"
    via: "yes"
    to: "Decision3"
    into: "in"
  - from: "Join12"
    via: "next"
    to: "UpdateAuctionState2"
    into: "in"
  - from: "Decision8"
    via: "no"
    to: "Join12"
    into: "in3"
