flow: "ViewContentIncludeProcessingWizard"
kind: "view"

entries:
  - id: "Start1"
    name: "SelectAction"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "SelectNextStep"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode11"
    name: "FinishDeleteIncludes"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "BackToSelectAction"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "ProcessValuesInContainer"
    mode: "private"
    strict: true
    inputs:
      - key: "ContentRepositoryUUID"
        type: "java.lang.String"
        required: false
      - key: "IncludePageableID"
        type: "java.lang.String"
        required: false
      - key: "ActionID"
        type: "java.lang.String"
        required: false
      - key: "SelectedObjects"
        type: "java.lang.String"
        required: false
      - key: "IncludeSearchID"
        type: "java.lang.String"
        required: false
  - id: "StartNode8"
    name: "RemoveContainer"
    mode: "private"
    strict: true
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewContentIncludeProcessingWizard-RemoveContainer"
  - id: "CallNode10"
    type: "call"
    ref: "ProcessContentWizard-RemoveClipboard"
    bindings:
      UniqueSearchID: "IncludeSearchID"
  - id: "CallNode12"
    type: "call"
    ref: "ProcessContentWizard-GetSelectedMenuItem"
  - id: "CallNode2"
    type: "call"
    ref: "ViewContentIncludeProcessingWizard-ProcessValuesInContainer"
  - id: "CallNode3"
    type: "call"
    ref: "ViewContentIncludeProcessingWizard-ProcessValuesInContainer"
  - id: "CallNode4"
    type: "call"
    ref: "ViewContentIncludeProcessingWizard-RemoveContainer"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessContentWizard-GetSelectedMenuItem"
  - id: "CallNode6"
    type: "call"
    ref: "ViewContentIncludeProcessingWizard-ProcessValuesInContainer"
  - id: "CallNode7"
    type: "call"
    ref: "ViewContentIncludeProcessingWizard-RemoveContainer"
  - id: "CheckForEmptyString1"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "ActionID"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ActionID"
  - id: "DecisionNode7"
    type: "decision"
    condition: "ActionID"
  - id: "DecisionNode8"
    type: "decision"
    condition: "ActionID"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewContentIncludeProcessingWizard-SelectNextStep"
      OutValue_1: "ViewContentIncludeProcessingWizard-BackToSelectAction"
      OutValue_3: "ViewContentIncludeProcessingWizard-BackToSelectAction"
      OutValue_2: "ViewContentIncludeProcessingWizard-FinishDeleteIncludes"
    bindings:
      Key_0: "selectNextStep"
      Key_1: "backToSelectAction"
      Key_2: "deleteContentIncludes"
      Key_3: "cancelDeleteContentIncludes"
      SelectionKey: "JumpTarget"
  - id: "DispatchFormActionByBreadcrumb1"
    type: "pipelet"
    ref: "DispatchFormActionByBreadcrumb"
    config:
      SplitMode: "PipelineAndParameter"
    bindings:
      Key_0: "cancel"
      OutValue_0: "ApplicationState:LastListView"
      Key_1: "previous"
      OutValue_1: "ApplicationState:LastButOneBreadcrumb"
      SelectionKey: "JumpTarget"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ActionID"
        type: "java.lang.String"
        guaranteed: false
      - key: "IncludePageableID"
        type: "java.lang.String"
        guaranteed: false
      - key: "ContentRepositoryUUID"
        type: "java.lang.String"
        guaranteed: false
      - key: "SelectedObjects"
        type: "java.lang.String"
        guaranteed: false
      - key: "IncludeSearchID"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "GetValuesFromContainer2"
    type: "pipelet"
    ref: "GetValuesFromContainer"
    config:
      OverwriteBehavior: false
    bindings:
      ContainerName: "\"Container_IncludeProcessing\""
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "Jump10"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewContentIncludeProcessingWizard-BackToSelectAction"
  - id: "JumpNode2"
    type: "jump"
    ref: "ProcessContentWizard-CreateProcess"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewContentProcessingWizardCreateLabelAssignment-SelectLabel"
  - id: "JumpNode5"
    type: "jump"
    ref: "ViewContentIncludeProcessingWizard-BackToSelectAction"
  - id: "JumpNode6"
    type: "jump"
    ref: "Error-Start"
  - id: "JumpNode7"
    type: "jump"
    ref: "ViewContentIncludeComponentAssignmentCreationWizard-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "\"BatchProcessPageletEntryPoints-DeletePageletEntryPoints\""
      InValue_2: "\"BatchProcessPageletEntryPoints-Init\""
      InValue_3: "\"BatchProcessPageletEntryPoints-Finish\""
      InValue_4: "\"MasterContent\""
      InValue_5: "\"MasterContent\""
      OutValue_1: "ProcessPipeline"
      OutValue_2: "InitPipeline"
      OutValue_3: "PostPipeline"
      OutValue_4: "JobName"
      OutValue_5: "JobNamePrefix"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "RepositoryUUID"
      InValue_2: "UniquePageletSearchID"
      InValue_3: "PageableID"
      OutValue_1: "ContentRepositoryUUID"
      OutValue_2: "IncludeSearchID"
      OutValue_3: "IncludePageableID"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "IncludePageableID"
      OutValue_1: "PageableID"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "IncludePageableID"
      InValue_2: "\"ContentInclude\""
      OutValue_1: "PageableID"
      OutValue_2: "ContextObject"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "content/contentinclude/wizard/ContentIncludeSelectAction"
  - id: "RemoveValuesContainer1"
    type: "pipelet"
    ref: "RemoveValuesContainer"
    bindings:
      ContainerName: "\"Container_IncludeProcessing\""
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_ACTION_NOT_SELECTED"
      Value: true
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ConfirmDeleteContentIncludes"
      Value: true
      ValueType: "Dictionary Value"
  - id: "SetValuesToContainer2"
    type: "pipelet"
    ref: "SetValuesToContainer"
    bindings:
      ContainerName: "\"Container_IncludeProcessing\""
      DictionaryKeys: "\"ContentRepositoryUUID;IncludePageableID;ActionID;SelectedObjects;IncludeSearchID\""
  - id: "TextNode2"
    type: "text"

links:
  - from: "CallNode10"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CheckForEmptyString1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode5"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "next"
    to: "DecisionNode8"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JumpNode7"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JumpNode6"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "KeyMapper4"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode8"
    via: "no"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "DecisionNode8"
    via: "yes"
    to: "DecisionNode7"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "DispatchFormActionByBreadcrumb1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DispatchFormActionByBreadcrumb1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "GetValuesFromContainer2"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "GetValuesFromContainer2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "SetValuesToContainer2"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "Jump10"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "KeyMapper3"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "RemoveValuesContainer1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "SetValuesToContainer2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "StartNode11"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "GetValuesFromContainer2"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "RemoveValuesContainer1"
    into: "in"
