flow: "ViewUserDepartmentRolesWizard"
kind: "view"

entries:
  - id: "Start1"
    name: "Finish"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start10"
    name: "DoFinish"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "SelectDepartment"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "SelectDepartmentRoles"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Next"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "Expand"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "Collapse"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AssignUserToOrganizationRole1"
    type: "pipelet"
    ref: "AssignUserToOrganizationRole"
    bindings:
      OrganizationRole: "Role"
  - id: "CheckForEmptyIterator1"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "RoleUUIDs"
  - id: "Decision3"
    type: "decision"
    condition: "SelectedDepartmentUUID"
  - id: "DetermineUser1"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "UserUUID"
  - id: "DetermineUser2"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "UserUUID"
  - id: "DetermineUser3"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "UserUUID"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewUserDepartmentRolesWizard-Next"
      OutValue_1: "ViewUserDepartmentRolesWizard-DoFinish"
      OutValue_2: "ViewUserDepartmentRolesWizard-SelectDepartment"
      OutValue_3: "ViewUserDepartmentRoles-Start"
    bindings:
      Key_0: "next"
      Key_1: "finish"
      Key_2: "previous"
      Key_3: "cancel"
      SelectionKey: "JumpTarget"
  - id: "ExchangeSessionObject1"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "User"
    bindings:
      LoadObject: "User"
  - id: "ExchangeSessionObject2"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "User"
    bindings:
      LoadObject: "User"
  - id: "ExchangeSessionObject3"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "SelectedDepartment"
    bindings:
      SaveObject: "Department"
  - id: "ExchangeSessionObject4"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "User"
    bindings:
      SaveObject: "User"
  - id: "ExchangeSessionObject5"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "User"
    bindings:
      LoadObject: "User"
  - id: "ExchangeSessionObject6"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      LoadObject: "ExpandedCategoriesMap"
  - id: "ExchangeSessionObject7"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      LoadObject: "ExpandedCategoriesMap"
  - id: "ExchangeSessionObject8"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      SaveObject: "ExpandedCategoriesMap"
  - id: "GetDepartment1"
    type: "pipelet"
    ref: "GetDepartment"
    config:
      Source: "PipelineDictionary"
    bindings:
      DepartmentUUID: "SelectedDepartmentUUID"
  - id: "GetDepartments1"
    type: "pipelet"
    ref: "GetDepartments"
  - id: "GetDepartments2"
    type: "pipelet"
    ref: "GetDepartments"
  - id: "GetDepartments3"
    type: "pipelet"
    ref: "GetDepartments"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedRole"
    bindings:
      Selection: "RoleUUIDs"
  - id: "GetOrganizationByUser3"
    type: "pipelet"
    ref: "GetOrganizationByUser"
    bindings:
      User: "CurrentUser"
  - id: "GetRole1"
    type: "pipelet"
    ref: "GetRole"
    bindings:
      RoleID: "RoleUUID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "InteractionEnd4"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewUserDepartmentRoles-Start"
  - id: "Jump2"
    type: "jump"
    ref: "ViewUserDepartmentRolesWizard-SelectDepartment"
  - id: "Jump4"
    type: "jump"
    ref: "ViewUserDepartmentRolesWizard-SelectDepartmentRoles"
  - id: "Jump5"
    type: "jump"
    ref: "ViewUserDepartmentRolesWizard-SelectDepartment"
  - id: "Jump7"
    type: "jump"
    ref: "ViewUserDepartmentRolesWizard-SelectDepartmentRoles"
  - id: "Jump8"
    type: "jump"
    ref: "ViewUserDepartmentRolesWizard-Finish"
  - id: "Jump9"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "ListDepartmentRoles1"
    type: "pipelet"
    ref: "ListDepartmentRoles"
  - id: "Loop1"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Users"
      WorkingTemplate: "user/SelectDepartment"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Users"
      WorkingTemplate: "user/SelectDepartmentRole"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Users"
      WorkingTemplate: "user/SelectDepartment"
  - id: "PrepareApplicationView4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Users"
      WorkingTemplate: "user/SelectDepartment"
  - id: "UpdateMapping1"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "TreeDepartmentUUID"
      Value: "TreeDepartmentUUID"
  - id: "UpdateMapping2"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Remove"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "TreeDepartmentUUID"
      Value: "TreeDepartmentUUID"
  - id: "UpdateMapping3"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      Key: "Department:UUID"
      OutMap: "ExpandedCategoriesMap"
      Value: "Department:UUID"

links:
  - from: "ExchangeSessionObject4"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "DetermineUser1"
    via: "next"
    to: "ExchangeSessionObject4"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "ExchangeSessionObject1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "GetDepartments1"
    via: "next"
    to: "ExchangeSessionObject1"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "GetDepartment1"
    via: "next"
    to: "ExchangeSessionObject3"
    into: "in"
  - from: "ExchangeSessionObject3"
    via: "next"
    to: "ListDepartmentRoles1"
    into: "in"
  - from: "ListDepartmentRoles1"
    via: "next"
    to: "ExchangeSessionObject2"
    into: "in"
  - from: "ExchangeSessionObject2"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "GetOrganizationByUser3"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetRole1"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "GetRole1"
    via: "next"
    to: "AssignUserToOrganizationRole1"
    into: "in"
  - from: "AssignUserToOrganizationRole1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "GetRole1"
    via: "error"
    to: "Join1"
    into: "in3"
  - from: "Decision3"
    via: "yes"
    to: "Jump4"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Jump5"
    into: "in"
  - from: "ExchangeSessionObject5"
    via: "next"
    to: "GetOrganizationByUser3"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "CheckForEmptyIterator1"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "error"
    to: "Jump7"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "next"
    to: "Jump8"
    into: "in"
  - from: "ExchangeSessionObject7"
    via: "next"
    to: "UpdateMapping1"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "UpdateMapping1"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "ExchangeSessionObject6"
    via: "next"
    to: "UpdateMapping2"
    into: "in"
  - from: "PrepareApplicationView4"
    via: "next"
    to: "InteractionEnd4"
    into: "in"
  - from: "UpdateMapping2"
    via: "next"
    to: "PrepareApplicationView4"
    into: "in"
  - from: "GetDepartments2"
    via: "next"
    to: "ExchangeSessionObject7"
    into: "in"
  - from: "GetDepartments3"
    via: "next"
    to: "ExchangeSessionObject6"
    into: "in"
  - from: "DetermineUser2"
    via: "next"
    to: "GetDepartments3"
    into: "in"
  - from: "DetermineUser3"
    via: "next"
    to: "GetDepartments2"
    into: "in"
  - from: "UpdateMapping3"
    via: "next"
    to: "ExchangeSessionObject8"
    into: "in"
  - from: "ExchangeSessionObject8"
    via: "next"
    to: "GetDepartments1"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump9"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Start10"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "DetermineUser3"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "DetermineUser2"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "DetermineUser1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "UpdateMapping3"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "GetDepartment1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "ExchangeSessionObject5"
    into: "in"
