flow: "ViewProductMaintenance_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "UpdateLifecycle"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessProductHistory-SaveProductSnapShot"
  - id: "Call2"
    type: "call"
    ref: "ProcessProductMaintenance-UpdateLifecycle"
  - id: "Call4"
    type: "call"
    ref: "ViewProduct_52-CheckProductLock"
  - id: "Call5"
    type: "call"
    ref: "ProcessProductMaintenance-Update"
  - id: "Call7"
    type: "call"
    ref: "ProcessProduct-DetermineCategoryPath"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessProductLock_52-Lookup"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessProductLock_52-Check"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessProductLock_52-Check"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessProductHistory-SaveProductSnapShot"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProductMaintenance_52-Update"
      OutValue_1: "ViewProductMaintenance_52-Start"
      OutValue_2: "ViewProductList_52-Paging"
      OutValue_3: "ViewProductMaintenance_52-UpdateLifecycle"
    bindings:
      Key_0: "update"
      Key_1: "reset"
      Key_2: "back"
      SelectionKey: "JumpTarget"
      Key_3: "updatelifecycle"
  - id: "GetDomainPreference7"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductLockActivated"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceStringValue: "ProductLockActivated"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump3"
    type: "jump"
    ref: "ViewProductMaintenance_52-Start"
  - id: "Jump6"
    type: "jump"
    ref: "ViewProductMaintenance_52-Start"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductMaintenance_52"

links:
  - from: "CallNode1"
    via: "next"
    to: "GetDomainPreference7"
    into: "in"
  - from: "CallNode3"
    via: "NO_LOCK"
    to: "JoinNode1"
    into: "in3"
  - from: "Start4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "GetDomainPreference7"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "CallNode2"
    via: "NO_LOCK"
    to: "JoinNode3"
    into: "in3"
  - from: "Call1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GetDomainPreference7"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "JoinNode4"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "Jump6"
    into: "in"
