flow: "ViewProductMappingRuleSets_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call2"
    type: "call"
    ref: "ViewProductMappingRuleSets_52-Prefix"
  - id: "Call3"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "Call4"
    type: "call"
    ref: "DetermineRepositories-ParentChannel"
  - id: "Decision1"
    type: "decision"
    condition: "Organization:TypeCode"
  - id: "End1"
    type: "end"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join3"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Repository"
      OutValue_1: "MasterRepository"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/ProductMappingRuleSets_52"

links:
  - from: "KeyMapper1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Call4"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join3"
    into: "in3"
  - from: "Join3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "KeyMapper1"
    into: "in"
