flow: "ViewCategoryCategoryLinks"
kind: "view"

entries:
  - id: "Start1"
    name: "Display"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start11"
    name: "CategoryDetails"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "ExtractValuesFromIterator"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "HandleSelectedTypes"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode11"
    name: "ProcessStartPreparer"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode12"
    name: "HandsOverToCategorySelection"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode17"
    name: "MoveUpLink"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode18"
    name: "MoveDownLink"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "LinkSelectedCategories"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "RemoveLinks"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "SelectLinkType"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "ProcessDisplayPreparer"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddMultipleEntriesToMap1"
    type: "pipelet"
    ref: "AddMultipleEntriesToMap"
    config:
      Mode: "OverwriteValue"
    bindings:
      Key1: "\"CatalogCategoryID\""
      Value1: "CatalogCategoryID"
      Key4: "\"NotSelectableCategoryUUIDMap\""
      Value4: "NotLinkableCategoryUUIDMap"
      Key3: "\"SelectedLinkType\""
      Value3: "SelectedLinkType"
      Key2: "\"CatalogUUID\""
      Value2: "CatalogUUID"
      Key5: "\"AlreadySelectedCategoryUUIDMap\""
      Value5: "LinkedCategoryUUIDMap"
      OutMap: "PipelineComponentParameters"
  - id: "AddMultipleEntriesToMap2"
    type: "pipelet"
    ref: "AddMultipleEntriesToMap"
    config:
      Mode: "OverwriteValue"
    bindings:
      Key1: "\"SelectCatalogStepNo\""
      Key2: "\"SelectCategoryStepNo\""
      Value1: "\"1\""
      Value2: "\"2\""
      InMap: "PipelineComponentParameters"
      OutMap: "PipelineComponentParameters"
  - id: "AddMultipleEntriesToMap3"
    type: "pipelet"
    ref: "AddMultipleEntriesToMap"
    config:
      Mode: "OverwriteValue"
    bindings:
      InMap: "PipelineComponentParameters"
      Key1: "\"SelectedCheckboxIterator\""
      Value1: "SelectedCheckboxIterator"
      OutMap: "PipelineComponentParameters"
  - id: "AddObjectToVector3"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Object: "CatalogCategoryID"
      InVector: "null"
      Objects: "null"
      OutVector: "null"
      Iterator: "NotLinkableCategoryUUIDs"
  - id: "Call1"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "Call2"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "Call21"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call3"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode0"
    type: "call"
    ref: "ProcessCatalogCategoryLinks-CreateCategoryLinks"
    bindings:
      TypeCodeName: "SelectedLinkType"
      SourceCategoryID: "CatalogCategoryID"
      RepositoryID: "MasterRepository:UUID"
  - id: "CallNode1"
    type: "call"
    ref: "ViewCategoryCategoryLinks-ProcessDisplayPreparer"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessCatalogCategoryLinks-RemoveCategoryLinks"
  - id: "CallNode12"
    type: "call"
    ref: "ViewCategoryCategoryLinks-Prefix"
  - id: "CallNode13"
    type: "call"
    ref: "ProcessCatalogCategoryLinks-TypeCodeConfiguration"
  - id: "CallNode14"
    type: "call"
    ref: "ProcessCatalogCategoryLinks-MoveLinkPositions2"
    bindings:
      SelectedCategoryLinkUUIDs: "UUIDIterator"
      SourceCategory: "Category"
  - id: "CallNode15"
    type: "call"
    ref: "ViewCategoryCategoryLinks-Prefix"
  - id: "CallNode16"
    type: "call"
    ref: "ProcessCatalogCategoryLinks-GetLinkedCategoryIDMap"
    bindings:
      TypeCodeName: "SelectedLinkType"
      CatalogCategory: "Category"
  - id: "CallNode17"
    type: "call"
    ref: "ViewCategoryCategoryLinks-Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "ViewCategoryCategoryLinks-HandleSelectedTypes"
  - id: "CallNode25"
    type: "call"
    ref: "ProcessCatalogCategoryLinks-GetCategoryLinks2"
    bindings:
      SourceCategory: "Category"
      LinkTypeSummary: "CategoryLinkTypeSummary"
  - id: "CallNode3"
    type: "call"
    ref: "ViewCategoryCategoryLinks-ExtractValuesFromIterator"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessUtils-CreateMapFromIterator"
    bindings:
      Items: "NotLinkableCategoryUUIDs"
      OutMap: "NotLinkableCategoryUUIDMap"
  - id: "CallNode6"
    type: "call"
    ref: "ViewCategoryCategoryLinks-Prefix"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessCatalogCategoryLinks-CreateCategoryLinks"
    bindings:
      TypeCodeName: "SelectedLinkType"
      SourceCategoryID: "CatalogCategoryID"
      RepositoryID: "ChannelRepository:UUID"
  - id: "CallNode8"
    type: "call"
    ref: "ViewCategoryCategoryLinks-Prefix"
  - id: "CallNode9"
    type: "call"
    ref: "ViewCategoryCategoryLinks-Prefix"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "CategoryLinks"
    bindings:
      String1: "CategoryLinkTypeSummary:TypeCodeDefinition:Name"
      Concatenated: "CategoryLinksName"
  - id: "ConcatenateStrings3"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "\"select_\""
      String1: "checkItem"
      String2: "null"
      String3: "null"
      String4: "null"
      String5: "null"
      String6: "null"
      String7: "null"
      String8: "null"
      String9: "null"
      Concatenated: "SelectCheckItem"
  - id: "CreateIteratorForPrefix2"
    type: "pipelet"
    ref: "CreateIteratorForPrefix"
    config:
      Prefix: "select"
    bindings:
      PrefixIterator: "SelectedCheckboxIterator"
  - id: "Decision9"
    type: "decision"
    condition: "UUIDIterator"
  - id: "DecisionNode0"
    type: "decision"
    condition: "ChannelRepository:UUID"
  - id: "DecisionNode1"
    type: "decision"
    condition: "TargetCategoryIDs"
  - id: "DecisionNode2"
    type: "decision"
    condition: "TargetCategoryIDs"
  - id: "DecisionNode21"
    type: "decision"
    condition: "CurrentChannel"
  - id: "DetermineCatalogCategoriesPath1"
    type: "pipelet"
    ref: "DetermineCatalogCategoriesPath"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewCategoryCategoryLinks-SelectLinkType"
      OutValue_6: "ViewCategoryCategoryLinks-RemoveLinks"
      OutValue_7: "ViewCategoryCategoryLinks-Start"
      OutValue_1: "ViewCategoryCategoryLinks-Display"
      OutValue_3: "ViewCategoryCategoryLinks-MoveUpLink"
      OutValue_4: "ViewCategoryCategoryLinks-MoveDownLink"
      OutValue_2: "ViewCategoryCategoryLinks-HandsOverToCategorySelection"
    bindings:
      Key_0: "newCategoryLink"
      Key_6: "deleteCategoryLinks"
      Key_7: "cancelDeleteCategoryLinks"
      Key_1: "confirmCategoryLinksDelete"
      Key_2: "linkTypeSelected"
      Key_3: "moveUpLink.x"
      Key_4: "moveDownLink.x"
      SelectionKey: "JumpTarget"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode10"
    type: "end"
    strict: false
    outputs:
      - key: "CategoryLinkTypeSummaryIter"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "CategoryTypeCodeGroup"
        type: "java.lang.String"
        guaranteed: false
      - key: "CategoryTypeCodesToShow"
        type: "com.intershop.beehive.foundation.util.ResettableIterator<E>"
        guaranteed: false
      - key: "TypeCodeNames"
        type: "com.intershop.beehive.foundation.util.ResettableIterator<E>"
        guaranteed: false
      - key: "TypeCodeGroup"
        type: "java.lang.String"
        guaranteed: false
      - key: "TypeCodesToShow"
        type: "com.intershop.beehive.foundation.util.ResettableIterator<E>"
        guaranteed: false
      - key: "RepositoryDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        guaranteed: false
      - key: "Catalog"
        type: "com.intershop.component.mvc.capi.catalog.Catalog"
        guaranteed: true
      - key: "SelectedMenuItem"
        type: "java.lang.String"
        guaranteed: false
      - key: "LeadLocale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        guaranteed: false
      - key: "Locale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        guaranteed: false
      - key: "Category"
        type: "com.intershop.beehive.xcs.capi.catalog.CatalogCategory"
        guaranteed: false
      - key: "CategoriesPath"
        type: "java.util.Iterator"
        guaranteed: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "EndNode5"
    type: "end"
    strict: false
  - id: "EndNode6"
    type: "end"
    strict: false
  - id: "GetCatalogByUUID1"
    type: "pipelet"
    ref: "GetCatalogByUUID"
  - id: "GetCategoryByUUID1"
    type: "pipelet"
    ref: "GetCategoryByUUID"
  - id: "GetLocale3"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Request Locale"
  - id: "GetLocale4"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Lead Locale"
    bindings:
      Locale: "LeadLocale"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode24"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump4"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewCategoryCategoryLinks-Start"
  - id: "JumpNode10"
    type: "jump"
    ref: "ViewPipelineComponent-StartComponent"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewCategoryCategoryLinks-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "This:Display"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewCategoryLinks-CategoryDetails"
  - id: "JumpNode5"
    type: "jump"
    ref: "ViewCategoryLinks-Start"
  - id: "JumpNode6"
    type: "jump"
    ref: "ViewCategoryLinks-Display"
  - id: "JumpNode9"
    type: "jump"
    ref: "ViewCategoryCategoryLinks-Display"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"CategorySelectWizard\""
      InValue_2: "\"ViewCategorySelectWizard-PrepareCatalogAssignment\""
      InValue_3: "\"ViewCategoryCategoryLinks-LinkSelectedCategories\""
      InValue_4: "\"TargetCategoryIDs\""
      InValue_5: "\"ViewCategoryCategoryLinks-SelectLinkType\""
      InValue_6: "\"CategoryLinks\""
      OutValue_1: "PipelineComponentName"
      OutValue_2: "PipelineComponentStartPipeline"
      OutValue_3: "PipelineComponentReturnPipeline"
      OutValue_4: "PipelineComponentReturnValueName"
      OutValue_5: "PipelineComponentBackToPipeline"
      OutValue_6: "PipelineComponentCaller"
  - id: "KeyMapper16"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentChannel:RepositoryDomain"
      InValue_2: "\"ChannelCatalogs\""
      OutValue_1: "RepositoryDomain"
      OutValue_2: "SelectedMenuItem"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentMasterRepository:RepositoryDomain"
      InValue_2: "\"Catalogs\""
      OutValue_1: "RepositoryDomain"
      OutValue_2: "SelectedMenuItem"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "category/CatalogCategoryLinkTypeSelection"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "Touch"
    bindings:
      Object: "Category"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "CategoryLinkTypeSummaryIter"
  - id: "RemoveDictionaryValue2"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "CategoryLinkTypeSummaryIter"
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "moveDirection"
      Value: "moveDown"
  - id: "SetDictionaryValue8"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "moveDirection"
      Value: "moveUp"
  - id: "SetDictionaryValue9"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_SELECTION_MOVE_CATEGORY_LINKS"
      Value: true
  - id: "SetIndirectDictValue1"
    type: "pipelet"
    ref: "SetIndirectDictValue"
    bindings:
      MappedEntry: "CategoryLinks"
      KeyNameHolder: "CategoryLinksName"
  - id: "SetIndirectDictValue3"
    type: "pipelet"
    ref: "SetIndirectDictValue"
    bindings:
      KeyNameHolder: "SelectCheckItem"
      MappedEntry: "\"on\""

links:
  - from: "AddMultipleEntriesToMap1"
    via: "next"
    to: "AddMultipleEntriesToMap2"
    into: "in"
  - from: "AddMultipleEntriesToMap2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "AddMultipleEntriesToMap3"
    via: "next"
    to: "JumpNode10"
    into: "in"
  - from: "AddObjectToVector3"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "Call21"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Decision9"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "CallNode0"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode11"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "EndNode10"
    into: "in"
  - from: "CallNode14"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "CallNode15"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "CallNode16"
    via: "next"
    to: "AddObjectToVector3"
    into: "in"
  - from: "CallNode17"
    via: "next"
    to: "CallNode16"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "CallNode25"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "AddMultipleEntriesToMap3"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode8"
    via: "next"
    to: "DecisionNode0"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "Call21"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "SetIndirectDictValue1"
    into: "in"
  - from: "ConcatenateStrings3"
    via: "next"
    to: "SetIndirectDictValue3"
    into: "in"
  - from: "CreateIteratorForPrefix2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Decision9"
    via: "no"
    to: "SetDictionaryValue9"
    into: "in"
  - from: "Decision9"
    via: "yes"
    to: "CallNode14"
    into: "in"
  - from: "DecisionNode0"
    via: "no"
    to: "CallNode0"
    into: "in"
  - from: "DecisionNode0"
    via: "yes"
    to: "CallNode7"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode8"
    into: "in"
  - from: "DecisionNode21"
    via: "no"
    to: "KeyMapper2"
    into: "in"
  - from: "DecisionNode21"
    via: "yes"
    to: "KeyMapper16"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "DecisionNode1"
    into: "in"
  - from: "DetermineCatalogCategoriesPath1"
    via: "next"
    to: "DecisionNode21"
    into: "in"
  - from: "DispatchFormAction2"
    via: "error"
    to: "JumpNode1"
    into: "in"
  - from: "DispatchFormAction2"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "GetCatalogByUUID1"
    via: "next"
    to: "DetermineCatalogCategoriesPath1"
    into: "in"
  - from: "GetCategoryByUUID1"
    via: "next"
    to: "GetCatalogByUUID1"
    into: "in"
  - from: "GetLocale3"
    via: "next"
    to: "GetLocale4"
    into: "in"
  - from: "GetLocale4"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "JoinNode24"
    via: "next"
    to: "CallNode15"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "JumpNode9"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "GetLocale3"
    into: "in"
  - from: "KeyMapper16"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "AddMultipleEntriesToMap1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "LoopNode1"
    via: "do"
    to: "CallNode25"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "ConcatenateStrings3"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "RemoveDictionaryValue2"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "RemoveDictionaryValue2"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "JoinNode24"
    into: "in1"
  - from: "SetDictionaryValue8"
    via: "next"
    to: "JoinNode24"
    into: "in1"
  - from: "SetDictionaryValue9"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "SetIndirectDictValue1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "SetIndirectDictValue3"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "Start11"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "JumpNode6"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "GetCategoryByUUID1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "DispatchFormAction2"
    into: "in"
  - from: "StartNode11"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode12"
    via: "next"
    to: "CallNode17"
    into: "in"
  - from: "StartNode17"
    via: "next"
    to: "SetDictionaryValue8"
    into: "in"
  - from: "StartNode18"
    via: "next"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CreateIteratorForPrefix2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "CallNode9"
    into: "in"
