flow: "ViewChannelCatalogFilterUserGroupsSelect_52"
kind: "view"

entries:
  - id: "Start2"
    name: "Paging"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "List"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Assign"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "null"
      Object: "EveryoneUserGroup"
      Objects: "null"
      Iterator: "EveryoneUGIterator"
      OutVector: "null"
  - id: "AssignGroupToCatalogFilter1"
    type: "pipelet"
    ref: "AssignGroupToCatalogFilter"
    bindings:
      Group: "UserGroup"
      Filter: "CatalogFilter"
  - id: "Call1"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call10"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call4"
    type: "call"
    ref: "ViewChannelCatalogFilterUserGroups_52-Prefix"
  - id: "Call5"
    type: "call"
    ref: "ViewChannelCatalogFilterUserGroups_52-Prefix"
  - id: "Call8"
    type: "call"
    ref: "ViewChannelCatalogFilterUserGroups_52-Prefix"
  - id: "Call9"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode1"
    type: "call"
    ref: "ViewUserGroupList_52-Search"
  - id: "CallNode10"
    type: "call"
    ref: "ProcessPaging-SetPageNumber"
    bindings:
      Pageable: "UserGroups"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessOrganization_52-GetConsumerOrg"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessPaging-GetPageLocatorPageable"
    bindings:
      PageLocatorName: "\"CatalogFilterSelectUserGroups\""
      Pageable: "UserGroups"
  - id: "CombineIterators1"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Concatenate Iterators"
    bindings:
      Iterator1: "EveryoneUGIterator"
      Iterator2: "UserGroups"
      Iterator: "UserGroups"
  - id: "CreateIteratorFromPageable1"
    type: "pipelet"
    ref: "CreateIteratorFromPageable"
    bindings:
      PageableIterator: "UserGroups"
      ResettableIterator: "UserGroups"
  - id: "CreatePageableFromIterator1"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    config:
      PageableName: "UserGroups"
    bindings:
      Iterator: "UserGroups"
      Pageable: "UserGroups"
  - id: "DecisionNode1"
    type: "decision"
    condition: "UUIDIterator"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      PagingPipeline: "ViewChannelCatalogFilterUserGroupsSelect_52-Paging"
      OutValue_1: "ViewChannelCatalogFilterUserGroups_52-List"
      OutValue_0: "ViewChannelCatalogFilterUserGroupsSelect_52-Assign"
    bindings:
      SelectionKey: "JumpTarget"
      DefaultButton: "cancel"
      Key_0: "selectUserGroups"
      Key_1: "cancel"
  - id: "GetUserGroupByID1"
    type: "pipelet"
    ref: "GetUserGroupByID"
    bindings:
      UserGroupID: "\"Everyone\""
      Domain: "Organization:Domain"
      UserGroup: "EveryoneUserGroup"
  - id: "GetUserGroupByID2"
    type: "pipelet"
    ref: "GetUserGroupByID"
    bindings:
      UserGroupID: "SelectedUserGroupID"
      Domain: "Organization:Domain"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump3"
    type: "jump"
    ref: "ViewChannelCatalogFilterUserGroups_52-List"
  - id: "Jump4"
    type: "jump"
    ref: "ViewChannelCatalogFilterUserGroupsSelect_52-List"
  - id: "Loop2"
    type: "loop"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "CatalogFilters"
      WorkingTemplate: "filter/ChannelCatalogFilterSelectUserGroups_52"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewChannelCatalogFilterUserGroupsSelect_52-Paging"
      DefaultPageLocatorName: "CatalogFilterSelectUserGroups"
    bindings:
      Pageable: "UserGroups"

links:
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "GetUserGroupByID2"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode2"
    into: "in"
  - from: "CreateIteratorFromPageable1"
    via: "next"
    to: "GetUserGroupByID1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "AssignGroupToCatalogFilter1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode3"
    via: "Error"
    to: "JoinNode3"
    into: "in1"
  - from: "Loop2"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "GetUserGroupByID2"
    via: "next"
    to: "AssignGroupToCatalogFilter1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Loop2"
    via: "do"
    to: "GetUserGroupByID2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "SetPageLocator1"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "GetUserGroupByID1"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "CombineIterators1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Loop2"
    into: "in"
  - from: "CombineIterators1"
    via: "next"
    to: "CreatePageableFromIterator1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CreateIteratorFromPageable1"
    into: "in"
  - from: "CreatePageableFromIterator1"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "StartNode2"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "Jump4"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
