flow: "ViewAccount"
kind: "view"

entries:
  - id: "Start2"
    name: "Show"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "CheckCredentials"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call2"
    type: "call"
    ref: "ProcessUser-Update"
  - id: "CallNode1"
    type: "call"
    ref: "ViewAccount-CheckCredentials"
  - id: "CheckForEmptyString1"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "CurrentUserProfile:PreferredLocale"
  - id: "CheckForEmptyString2"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "Password"
  - id: "CheckForEmptyString4"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "OldPassword"
  - id: "CheckPassword2"
    type: "pipelet"
    ref: "CheckPassword"
    bindings:
      Password: "OldPassword"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "Login"
      param.1.required: true
      param.1.rule: ""
      param.10.name: "Fax"
      param.10.required: false
      param.10.rule: ""
      param.11.name: "Location"
      param.11.required: false
      param.11.rule: ""
      param.12.name: "PhoneMobile"
      param.12.required: false
      param.12.rule: ""
      param.13.name: "OldPassword"
      param.13.required: false
      param.13.rule: ""
      param.14.name: "Email"
      param.14.required: false
      param.14.rule: ""
      param.15.name: "LastName"
      param.15.required: true
      param.15.rule: ""
      param.16.name: "PasswordConfirmation"
      param.16.required: false
      param.16.rule: ""
      param.17.name: "Suffix"
      param.17.required: false
      param.17.rule: ""
      param.2.name: "LocaleID"
      param.2.required: false
      param.2.rule: ""
      param.3.name: "Password"
      param.3.required: false
      param.3.rule: ""
      param.4.name: "FirstName"
      param.4.required: true
      param.4.rule: ""
      param.5.name: "PhoneHome"
      param.5.required: false
      param.5.rule: ""
      param.6.name: "RoomNo"
      param.6.required: false
      param.6.rule: ""
      param.7.name: "Middle"
      param.7.required: false
      param.7.rule: ""
      param.8.name: "PhoneBusiness"
      param.8.required: false
      param.8.rule: ""
      param.9.name: "Title"
      param.9.required: false
      param.9.rule: ""
      webform-id: "RegForm"
    bindings:
      WebForm: "RegForm"
  - id: "DecisionNode1"
    type: "decision"
    condition: "RegForm:Email:Value"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Password"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "RegForm"
    bindings:
      WebForm: "RegForm"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewAccount-Show"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "RegForm:Login:Value"
      InValue_10: "RegForm:Active:Value"
      InValue_2: "RegForm:Title:Value"
      InValue_3: "RegForm:FirstName:Value"
      InValue_4: "RegForm:Middle:Value"
      InValue_5: "RegForm:LastName:Value"
      InValue_6: "RegForm:Suffix:Value"
      InValue_7: "CurrentUserProfile:DataSheet:BusinessPartnerNo"
      InValue_8: "RegForm:Password:Value"
      InValue_9: "RegForm:PasswordConfirmation:Value"
      OutValue_1: "Login"
      OutValue_10: "IsActive"
      OutValue_2: "Title"
      OutValue_3: "FirstName"
      OutValue_4: "SecondName"
      OutValue_5: "LastName"
      OutValue_6: "Suffix"
      OutValue_7: "BusinessPartnerNo"
      OutValue_8: "Password"
      OutValue_9: "PasswordConfirmation"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "RegForm:Location:Value"
      InValue_10: "RegForm:JobTitle:Value"
      InValue_2: "RegForm:RoomNo:Value"
      InValue_3: "RegForm:PhoneBusiness:Value"
      InValue_4: "RegForm:PhoneMobile:Value"
      InValue_5: "RegForm:PhoneHome:Value"
      InValue_6: "RegForm:Fax:Value"
      InValue_7: "RegForm:Email:Value"
      InValue_8: "CurrentUser"
      InValue_9: "RegForm:LocaleID:Value"
      OutValue_1: "Location"
      OutValue_10: "JobTitle"
      OutValue_2: "RoomNo"
      OutValue_3: "PhoneBusinessExt"
      OutValue_4: "PhoneMobileExt"
      OutValue_5: "PhoneHomeExt"
      OutValue_6: "FaxExt"
      OutValue_7: "Email"
      OutValue_8: "User"
      OutValue_9: "LocaleID"
  - id: "LogMessage2"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Level: "Info"
      Category: "audits"
      Marker: "audits"
    bindings:
      MessageParam0: "CurrentRequest:ServletRequest:LocalAddr"
      MessageText: "\"{} : {} : {} : Administrator Password Update - ERROR: {}\""
      MessageParam1: "CurrentOrganization:Domain:DomainName"
      MessageParam2: "CurrentUser:Profile:Credentials:Login"
      MessageParam3: "ERROR_User"
  - id: "LogMessage3"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Category: "audits"
      Marker: "audits"
      Level: "Info"
    bindings:
      MessageParam0: "CurrentRequest:ServletRequest:LocalAddr"
      MessageParam1: "CurrentOrganization:Domain:DomainName"
      MessageParam2: "CurrentUser:Profile:Credentials:Login"
      MessageText: "\"{} : {} : {} : Administrator Password Update - The password was successfully updated\""
  - id: "LogMessage4"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Level: "Info"
      Category: "audits"
      Marker: "audits"
    bindings:
      MessageParam0: "CurrentRequest:ServletRequest:LocalAddr"
      MessageText: "\"{} : {} : {} : Administrator Password Update - Failed: {}\""
      MessageParam1: "CurrentOrganization:Domain:DomainName"
      MessageParam2: "CurrentUser:Profile:Credentials:Login"
      MessageParam3: "ERROR_User"
  - id: "LogMessage5"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Level: "Info"
      Category: "audits"
      Marker: "audits"
    bindings:
      MessageParam0: "CurrentRequest:ServletRequest:LocalAddr"
      MessageText: "\"{} : {} : {} : Administrator Password Update - Failed: {}\""
      MessageParam1: "CurrentOrganization:Domain:DomainName"
      MessageParam2: "CurrentUser:Profile:Credentials:Login"
      MessageParam3: "ERROR_User"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "VerifyEMailAddress"
    bindings:
      EMailAddress: "RegForm:Email:Value"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_EMailAddressInvalid"
      Value: true
      ValueType: "Dictionary Value"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "RegForm:OldPassword:Value"
      OutValue_1: "OldPassword"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Profile"
      WorkingTemplate: "user/UpdateAccount"
  - id: "RemoveDictionaryValue2"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "Password"
      RemoveFormValues: false
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_User"
      Value: "PasswordWithoutOldPassword"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_User"
      Value: "LoginWithoutPassword"
  - id: "SetDictionaryValue7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_User"
      Value: "OldPasswordDoesNotMatch"
  - id: "SwitchLocale1"
    type: "pipelet"
    ref: "SwitchLocale"
    bindings:
      LocaleID: "Organization:Profile:PreferredLocale"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "RegForm"
    bindings:
      WebForm: "RegForm"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "RegForm"
  - id: "VerifyCredential1"
    type: "pipelet"
    ref: "VerifyCredential"
    config:
      NotEmptyOnly: true
    bindings:
      Domain: "null"
      Login: "RegForm:Login:Value"
      Password: "RegForm:Password:Value"
      CurrentLocale: "CurrentRequest:Locale"
      User: "CurrentUser"

links:
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "CheckForEmptyString4"
    via: "next"
    to: "CheckPassword2"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "LogMessage3"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "ValidateWebForm1"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "JoinNode6"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode3"
    into: "in1"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "LogMessage5"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "DecisionNode1"
    via: "no"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "CheckForEmptyString2"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "ValidateWebForm1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "VerifyCredential1"
    into: "in"
  - from: "VerifyCredential1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "CheckForEmptyString4"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "CheckForEmptyString2"
    via: "error"
    to: "RemoveDictionaryValue2"
    into: "in"
  - from: "SetDictionaryValue7"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "DetermineLocales1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "CheckPassword2"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "EndNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "Join9"
    via: "next"
    to: "CheckForEmptyString4"
    into: "in"
  - from: "VerifyCredential1"
    via: "error"
    to: "LogMessage5"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode4"
    into: "in2"
  - from: "CreateWebForm1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "RemoveDictionaryValue2"
    via: "next"
    to: "Join9"
    into: "in3"
  - from: "CheckForEmptyString2"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CheckPassword2"
    via: "error"
    to: "SetDictionaryValue7"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "error"
    to: "SwitchLocale1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Pipelet4"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "Call2"
    via: "error-update"
    to: "LogMessage2"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "Pipelet2"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "SwitchLocale1"
    via: "next"
    to: "Join4"
    into: "in3"
  - from: "Start2"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "CallNode1"
    via: "ERROR"
    to: "LogMessage4"
    into: "in"
  - from: "LogMessage4"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "LogMessage2"
    via: "next"
    to: "JoinNode6"
    into: "in2"
  - from: "LogMessage3"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "CheckForEmptyString1"
    into: "in"
