flow: "ViewPaymentMethodApplications_52"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "UpdateApplicationAssigment"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "Show"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddEntryToMap2"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "EnabledApps"
      Key: "AppID"
      OutMap: "EnabledApps"
      Value: "AppID"
  - id: "AssignPaymentConfigurationToApplication1"
    type: "pipelet"
    ref: "AssignPaymentConfigurationToApplication"
  - id: "CallNode1"
    type: "call"
    ref: "ViewPaymentMethodApplications_52-Prefix"
  - id: "CallNode14"
    type: "call"
    ref: "ViewPaymentMethodApplications_52-Prefix"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ApplicationIDs:get(Application:UUID)"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "GetApplications1"
    type: "pipelet"
    ref: "GetApplications"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
  - id: "GetApplications2"
    type: "pipelet"
    ref: "GetApplications"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
  - id: "GetFormRecord1"
    type: "pipelet"
    ref: "GetFormRecord"
    config:
      DefaultRecordID: "ApplicationID"
    bindings:
      FormRecord: "ApplicationIDs"
  - id: "GetPaymentConfigurationByUUID1"
    type: "pipelet"
    ref: "GetPaymentConfigurationByUUID"
  - id: "InteractionNode3"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPaymentMethodApplications_52-UpdateApplicationAssigment"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "setApplications"
  - id: "Pipelet10"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "PurchaseOrderList"
      WorkingTemplate: "payment/PaymentMethodApplications_52.isml"
  - id: "UnAssignPaymentConfigurationFromApplication1"
    type: "pipelet"
    ref: "UnAssignPaymentConfigurationFromApplication"

links:
  - from: "StartNode6"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "GetFormRecord1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "AssignPaymentConfigurationToApplication1"
    into: "in"
  - from: "AssignPaymentConfigurationToApplication1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode14"
    via: "next"
    to: "GetApplications1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "GetApplications2"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "DecisionNode1"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "DecisionNode1"
    via: "no"
    to: "UnAssignPaymentConfigurationFromApplication1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "GetApplications1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "UnAssignPaymentConfigurationFromApplication1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "GetPaymentConfigurationByUUID1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "GetPaymentConfigurationByUUID1"
    into: "in"
  - from: "Pipelet10"
    via: "next"
    to: "InteractionNode3"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "AddEntryToMap2"
    into: "in"
  - from: "AddEntryToMap2"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "GetApplications2"
    via: "next"
    to: "GetFormRecord1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "Pipelet10"
    into: "in"
