flow: "ViewProductDeletionPreferences"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Decision1"
    type: "decision"
    condition: "RecycleBinOfferPropagation"
  - id: "DecisionNode1"
    type: "decision"
    condition: "RecycleBinUsage"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductDeletionStrategy"
      Type: "Integer"
    bindings:
      PreferenceDomain: "OrganizationDomain"
      PreferenceIntValue: "ProductDeletionStrategyIntValue"
  - id: "GetDomainPreference5"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "RecycleBinOfferPropagation"
      Type: "String"
    bindings:
      PreferenceDomain: "Organization:Domain"
      PreferenceStringValue: "RecycleBinOfferPropagation"
  - id: "GetDomainPreference6"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "RecycleBinUsage"
      Type: "String"
    bindings:
      PreferenceDomain: "Organization:Domain"
      PreferenceStringValue: "RecycleBinUsage"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductDeletionStrategy"
      DefaultPreferenceValue: 0
      Type: "Integer"
    bindings:
      PreferenceDomain: "OrganizationDomain"
      PreferenceIntValue: "ProductDeletionStrategyIntValue"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "RecycleBinOfferPropagation"
      DefaultPreferenceValue: true
      Type: "String"
    bindings:
      PreferenceDomain: "Organization:Domain"
      PreferenceStringValue: "RecycleBinOfferPropagation"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "RecycleBinUsage"
      DefaultPreferenceValue: false
      Type: "String"
    bindings:
      PreferenceDomain: "Organization:Domain"
      PreferenceStringValue: "RecycleBinUsage"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Preferences"
      WorkingTemplate: "product/ProductDeletionPreferences"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    config:
      MinValue: 0
      MaxValue: 2
    bindings:
      IntegerObject: "ProductDeletionStrategyIntValue"
      LocalizedString: "SelectedProductDeletionStrategy"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode5"
    into: "in2"
  - from: "GetDomainPreference5"
    via: "error"
    to: "Join3"
    into: "in2"
  - from: "GetDomainPreference5"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "GetDomainPreference1"
    via: "next"
    to: "GetDomainPreference6"
    into: "in"
  - from: "GetDomainPreference6"
    via: "next"
    to: "GetDomainPreference5"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Join4"
    into: "in3"
  - from: "Pipelet4"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "Decision1"
    via: "no"
    to: "JoinNode9"
    into: "in2"
  - from: "GetDomainPreference6"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "VerifyInteger1"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "JoinNode2"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "GetDomainPreference1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "Pipelet4"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Pipelet2"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode4"
    into: "in2"
  - from: "Pipelet2"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "JoinNode4"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "VerifyInteger1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "Pipelet1"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "Join4"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
