flow: "ViewChannelConfigurationParameters"
kind: "view"

entries:
  - id: "Start9"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "RevertToInheriting"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode10"
    name: "GetConfigurationParameterCtnr"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentChannel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
  - id: "StartNode22"
    name: "View"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "Reset"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewConfigurationParameters-SaveFormParameters"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessPageletLock-Lookup"
    bindings:
      PreferenceDomain: "CurrentChannel:RepositoryDomain"
      LockingDomain: "CurrentChannel:RepositoryDomain"
      Pagelet: "ConfigurationParameterCtnr"
      User: "CurrentUser"
  - id: "CallNode13"
    type: "call"
    ref: "ViewConfigurationParameters-CleanupSession"
  - id: "CallNode14"
    type: "call"
    ref: "ViewConfigurationParameters-GetValuesFromSession"
  - id: "CallNode15"
    type: "call"
    ref: "This:GetConfigurationParameterCtnr"
  - id: "CallNode18"
    type: "call"
    ref: "ViewConfigurationParameters-Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "ViewConfigurationParameters-SaveValuesAtSession"
  - id: "CallNode20"
    type: "call"
    ref: "ViewConfigurationParameters-SaveValuesAtSession"
  - id: "CallNode23"
    type: "call"
    ref: "ViewConfigurationParameters-SaveFormParameters"
  - id: "CallNode25"
    type: "call"
    bindings:
      Site: "CurrentChannel:RepositoryDomain:Site"
  - id: "CallNode26"
    type: "call"
    ref: "ViewConfigurationParameters-Prefix"
  - id: "CallNode27"
    type: "call"
    ref: "ViewConfigurationParameters-GetContainerName"
    bindings:
      ConfigurationParameterCtnrUUID: "ConfigurationParameterCtnr:UUID"
      RepositoryUUID: "CurrentChannel:UUID"
  - id: "CallNode28"
    type: "call"
    ref: "ViewConfigurationParameters-GetContainerName"
    bindings:
      ConfigurationParameterCtnrUUID: "ConfigurationParameterCtnr:UUID"
      RepositoryUUID: "CurrentChannel:UUID"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessConfigurationParameter-RevertConfigurationParameters"
    bindings:
      ConfigurationParameterDefinitions: "ConfigurationParameterCtnr:ConfigurationParameterDefinitionCtnr(CurrentChannel:RepositoryDomain:Site):ConfigurationParameterDefinitions"
      ConfigurationParameterCtnr: "ConfigurationParameterCtnr"
  - id: "CallNode33"
    type: "call"
    ref: "ViewConfigurationParameters-CleanupSession"
  - id: "CallNode35"
    type: "call"
    ref: "ViewConfigurationParameters-CleanupSession"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessPageletLock-Check"
    bindings:
      LockingDomain: "CurrentChannel:RepositoryDomain"
      PreferenceDomain: "CurrentChannel:RepositoryDomain"
      Pagelet: "ConfigurationParameterCtnr"
      User: "CurrentUser"
  - id: "CallNode40"
    type: "call"
    ref: "ProcessPageletLock-Check"
    bindings:
      LockingDomain: "CurrentChannel:RepositoryDomain"
      PreferenceDomain: "CurrentChannel:RepositoryDomain"
      Pagelet: "ConfigurationParameterCtnr"
      User: "CurrentUser"
  - id: "CallNode44"
    type: "call"
    ref: "ProcessConfigurationParameterCtnrWebForm-CreateForm"
    bindings:
      Site: "CurrentSite"
      Context: "ContentRepository"
  - id: "CallNode5"
    type: "call"
    ref: "ViewConfigurationParameters-Prefix"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessConfigurationParameter-UpdateConfigurationParameters"
    bindings:
      ConfigurationParameterDefinitions: "ConfigurationParameterCtnr:ConfigurationParameterDefinitionCtnr(CurrentChannel:RepositoryDomain:Site):ConfigurationParameterDefinitions"
      ConfigurationParameterCtnr: "ConfigurationParameterCtnr"
      Site: "CurrentSite"
  - id: "DecisionNode21"
    type: "decision"
    condition: "ConfigurationParameterCtnr:ConfigurationParameterDefinitionCtnr(CurrentChannel:RepositoryDomain:Site):OnEditPipeline:ReferencedName"
  - id: "DispatchConfigurationParameterTypeAction1"
    type: "pipelet"
    ref: "DispatchConfigurationParameterTypeAction"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_3: "This:Edit"
      OutValue_2: "This:Update"
      OutValue_1: "This:Reset"
      OutValue_4: "This:RevertToInheriting"
    bindings:
      SelectionKey: "JumpTarget"
      Key_3: "cancelSelection"
      Key_2: "Update"
      Key_1: "Reset"
      Key_4: "RevertToInheriting"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ConfigurationParameterCtnr"
        type: "com.intershop.component.pmc.capi.pagelet.ConfigurationParameterCtnr"
        guaranteed: true
      - key: "SelectedConfigurationParameterDefinition"
        type: "com.intershop.component.pmc.capi.definition.pagelet.ConfigurationParameterDefinition"
        guaranteed: true
  - id: "EndNode5"
    type: "end"
    strict: true
  - id: "ExchangeSessionObject19"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      SessionObjectName: "SelectedConfigurationParameterName"
      ProcessMethod: "Get Object from Session"
    bindings:
      SaveObject: "null"
      SessionObjectName: "null"
      LoadObject: "SelectedConfigurationParameterName"
  - id: "ExchangeSessionObject6"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      SessionObjectName: "ConfigurationParameterCtnrUUID"
      ProcessMethod: "Get Object from Session"
    bindings:
      SaveObject: "null"
      SessionObjectName: "null"
      LoadObject: "ConfigurationParameterCtnrUUID"
  - id: "GetConfigurationParameterCtnrByUUID1"
    type: "pipelet"
    ref: "GetConfigurationParameterCtnrByUUID"
  - id: "GetFormRecord1"
    type: "pipelet"
    ref: "GetFormRecord"
    config:
      DefaultRecordID: "PreProcessingPipeline"
    bindings:
      RecordID: "null"
      FormRecord: "PreProcessingPipelinesMap"
  - id: "GetFormRecord2"
    type: "pipelet"
    ref: "GetFormRecord"
    config:
      DefaultRecordID: "ConfigurationParameter"
    bindings:
      RecordID: "null"
      FormRecord: "FormParameters"
  - id: "GetFormRecord3"
    type: "pipelet"
    ref: "GetFormRecord"
    config:
      DefaultRecordID: "TargetPipeline"
    bindings:
      RecordID: "null"
      FormRecord: "TargetPipelineMap"
  - id: "GetFormRecord4"
    type: "pipelet"
    ref: "GetFormRecord"
    config:
      DefaultRecordID: "TargetPipeline"
    bindings:
      RecordID: "null"
      FormRecord: "TargetPipelineMap"
  - id: "GetFormRecord5"
    type: "pipelet"
    ref: "GetFormRecord"
    config:
      DefaultRecordID: "ConfigurationParameter"
    bindings:
      RecordID: "null"
      FormRecord: "FormParameters"
  - id: "GetFormRecord7"
    type: "pipelet"
    ref: "GetFormRecord"
    config:
      DefaultRecordID: "TargetPipeline"
    bindings:
      RecordID: "null"
      FormRecord: "TargetPipelineMap"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetValuesFromContainer1"
    type: "pipelet"
    ref: "GetValuesFromContainer"
    config:
      OverwriteBehavior: false
  - id: "InteractionNode1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode27"
    type: "join"
  - id: "JoinNode29"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewConfigurationParameters-InvokeTargetPipeline"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ConfigurationParameterCtnr:ConfigurationParameterDefinitionCtnr(CurrentChannel:RepositoryDomain:Site):ConfigurationParameterDefinitionByName(SelectedConfigurationParameterName)"
      OutValue_1: "SelectedConfigurationParameterDefinition"
  - id: "SetValuesToContainer5"
    type: "pipelet"
    ref: "SetValuesToContainer"
    bindings:
      ContainerName: "ContainerName"
      DictionaryKeys: "\"CurrentPipelineName\""

links:
  - from: "CallNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "GetFormRecord5"
    into: "in"
  - from: "JoinNode29"
    via: "next"
    to: "GetFormRecord3"
    into: "in"
  - from: "CallNode44"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode15"
    into: "in"
  - from: "StartNode22"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "GetFormRecord5"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode29"
    into: "in1"
  - from: "JoinNode27"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "StartNode4"
    via: "next"
    to: "CallNode26"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "CallNode18"
    into: "in"
  - from: "CallNode18"
    via: "next"
    to: "DispatchConfigurationParameterTypeAction1"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "CallNode35"
    into: "in"
  - from: "DecisionNode21"
    via: "yes"
    to: "CallNode25"
    into: "in"
  - from: "CallNode27"
    via: "next"
    to: "SetValuesToContainer5"
    into: "in"
  - from: "CallNode26"
    via: "next"
    to: "CallNode40"
    into: "in"
  - from: "ExchangeSessionObject6"
    via: "next"
    to: "GetConfigurationParameterCtnrByUUID1"
    into: "in"
  - from: "CallNode40"
    via: "NO_LOCK"
    to: "JoinNode2"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode40"
    via: "next"
    to: "GetFormRecord2"
    into: "in"
  - from: "CallNode25"
    via: "next"
    to: "JoinNode27"
    into: "in1"
  - from: "DecisionNode21"
    via: "no"
    to: "JoinNode27"
    into: "in2"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode29"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "SetValuesToContainer5"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "StartNode10"
    via: "next"
    to: "ExchangeSessionObject6"
    into: "in"
  - from: "CallNode7"
    via: "Error"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode11"
    via: "next"
    to: "GetFormRecord7"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "GetLocale2"
    via: "next"
    to: "DecisionNode21"
    into: "in"
  - from: "CallNode15"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "CallNode14"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "DispatchConfigurationParameterTypeAction1"
    via: "error"
    to: "DispatchFormAction1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "CallNode28"
    via: "next"
    to: "GetValuesFromContainer1"
    into: "in"
  - from: "GetFormRecord3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "GetFormRecord4"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "GetFormRecord2"
    via: "next"
    to: "GetFormRecord1"
    into: "in"
  - from: "GetFormRecord1"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "JoinNode29"
    into: "in1"
  - from: "CallNode4"
    via: "NO_LOCK"
    to: "JoinNode1"
    into: "in2"
  - from: "ExchangeSessionObject19"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "DispatchConfigurationParameterTypeAction1"
    via: "next"
    to: "CallNode20"
    into: "in"
  - from: "GetConfigurationParameterCtnrByUUID1"
    via: "next"
    to: "ExchangeSessionObject19"
    into: "in"
  - from: "GetConfigurationParameterCtnrByUUID1"
    via: "error"
    to: "EndNode5"
    into: "in"
  - from: "CallNode20"
    via: "next"
    to: "CallNode23"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "CallNode35"
    via: "next"
    to: "CallNode28"
    into: "in"
  - from: "GetFormRecord7"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "CallNode23"
    via: "next"
    to: "JoinNode6"
    into: "in2"
  - from: "JoinNode4"
    via: "next"
    to: "CallNode27"
    into: "in"
  - from: "CallNode33"
    via: "next"
    to: "GetFormRecord4"
    into: "in"
  - from: "GetValuesFromContainer1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "GetValuesFromContainer1"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "JoinNode5"
    via: "next"
    to: "CallNode44"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "CallNode33"
    into: "in"
