flow: "ViewABTestGoingLiveAssignments_52"
kind: "view"

entries:
  - id: "Start1"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "UpdateAssignments"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "GetContents"
    mode: "private"
    strict: true
    inputs:
      - key: "ABTestGroupID"
        type: "java.lang.String"
        required: true
  - id: "StartNode3"
    name: "GetAssignedObjectsByUUIDs"
    mode: "private"
    strict: true
    inputs:
      - key: "UUIDs"
        type: "java.util.Iterator"
        required: true
  - id: "StartNode4"
    name: "PutPageletsToSession"
    mode: "private"
    strict: true
    inputs:
      - key: "Pagelets"
        type: "java.util.Iterator"
        required: true
      - key: "ABTestGroupID"
        type: "java.lang.String"
        required: true
  - id: "StartNode6"
    name: "PutPromotionsToSession"
    mode: "private"
    strict: true
    inputs:
      - key: "Promotions"
        type: "java.util.Iterator"
        required: true
      - key: "ABTestGroupID"
        type: "java.lang.String"
        required: true
  - id: "StartNode7"
    name: "RemovePromotionsFromSession"
    mode: "private"
    strict: true
    inputs:
      - key: "ABTestGroupID"
        type: "java.lang.String"
        required: true
  - id: "StartNode8"
    name: "RemovePageletsFromSession"
    mode: "private"
    strict: true
    inputs:
      - key: "ABTestGroupID"
        type: "java.lang.String"
        required: true

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "null"
      Object: "null"
      Objects: "null"
      Iterator: "Pagelets"
      OutVector: "PageletsVector"
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "PageletsVector"
      Object: "Pagelet"
      Objects: "null"
      Iterator: "Pagelets"
      OutVector: "PageletsVector"
  - id: "AddObjectToVector5"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "null"
      Object: "null"
      Objects: "null"
      Iterator: "Promotions"
      OutVector: "PromotionsVector"
  - id: "AddObjectToVector6"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "PromotionsVector"
      Object: "Promotion"
      Objects: "null"
      Iterator: "Promotions"
      OutVector: "PromotionsVector"
  - id: "CallNode1"
    type: "call"
    ref: "ViewABTestAssignments_52-GetAssignedObjects"
  - id: "CallNode2"
    type: "call"
    ref: "ViewABTestGoingLiveAssignments_52-Prefix"
  - id: "CallNode3"
    type: "call"
    ref: "ViewABTestGoingLiveAssignments_52-Prefix"
  - id: "CallNode5"
    type: "call"
    ref: "ViewABTestGoingLiveAssignments_52-GetAssignedObjectsByUUIDs"
    bindings:
      UUIDs: "UUIDIterator"
  - id: "CallNode6"
    type: "call"
    ref: "ViewABTestGoingLiveAssignments_52-PutPageletsToSession"
    bindings:
      Pagelets: "Pagelets"
      ABTestGroupID: "ABTestGroup:UUID"
  - id: "CallNode7"
    type: "call"
    ref: "ViewABTestGoingLiveAssignments_52-PutPromotionsToSession"
    bindings:
      Promotions: "Promotions"
      ABTestGroupID: "ABTestGroup:UUID"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "ABTestGoingLive_Promotions_"
    bindings:
      String1: "ABTestGroupID"
      Concatenated: "PromotionsSessionKey"
  - id: "ConcatenateStrings2"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "ABTestGoingLive_Promotions_"
    bindings:
      String1: "ABTestGroupID"
      Concatenated: "PromotionsSessionKey"
  - id: "ConcatenateStrings3"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "ABTestGoingLive_Pagelets_"
    bindings:
      String1: "ABTestGroupID"
      Concatenated: "PageletsSessionKey"
  - id: "ConcatenateStrings4"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "ABTestGoingLive_Pagelets_"
    bindings:
      String1: "ABTestGroupID"
      Concatenated: "PageletsSessionKey"
  - id: "ConcatenateStrings5"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "ABTestGoingLive_Promotions_"
    bindings:
      String1: "ABTestGroupID"
      Concatenated: "PromotionsSessionKey"
  - id: "ConcatenateStrings6"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "ABTestGoingLive_Pagelets_"
    bindings:
      String1: "ABTestGroupID"
      Concatenated: "PageletsSessionKey"
  - id: "CreateFormValuesIteratorForKey1"
    type: "pipelet"
    ref: "CreateFormValuesIteratorForKey"
    bindings:
      FormKey: "\"SelectedObjectUUID\""
      FormValuesIterator: "UUIDIterator"
  - id: "CreatePageableFromIterator1"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    bindings:
      Iterator: "PageletsIterator"
      Pageable: "Pagelets"
  - id: "CreatePageableFromIterator2"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    bindings:
      Iterator: "PromotionsIterator"
      Pageable: "Promotions"
  - id: "Decision2"
    type: "decision"
    condition: "ABTestGroup"
  - id: "DecisionNode1"
    type: "decision"
    condition: "UUIDIterator"
  - id: "DecisionNode2"
    type: "decision"
    condition: "SelectedObjectUUID"
  - id: "DecisionNode3"
    type: "decision"
    condition: "CurrentSession:getObject(PageletsSessionKey)"
  - id: "DecisionNode4"
    type: "decision"
    condition: "CurrentSession:getObject(PromotionsSessionKey)"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_1: "ViewABTestGoingLiveTargetGroup_52-ShowAll"
      OutValue_2: "ViewABTestSummary_52-Show"
      OutValue_0: "ViewABTestGoingLiveAssignments_52-UpdateAssignments"
    bindings:
      Key_0: "next"
      Key_1: "previous"
      Key_2: "cancel"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode10"
    type: "end"
    strict: true
    outputs:
      - key: "Pagelets"
        type: "java.util.Iterator"
        guaranteed: true
      - key: "Promotions"
        type: "java.util.Iterator"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "Pagelets"
        type: "com.intershop.beehive.core.capi.paging.PageableIterator"
        guaranteed: false
      - key: "Promotions"
        type: "com.intershop.beehive.core.capi.paging.PageableIterator"
        guaranteed: false
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "EndNode5"
    type: "end"
    strict: true
  - id: "EndNode6"
    type: "end"
    strict: true
  - id: "EndNode7"
    type: "end"
    strict: true
  - id: "ExchangeSessionObject1"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SaveObject: "null"
      SessionObjectName: "PromotionsSessionKey"
  - id: "ExchangeSessionObject2"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SaveObject: "null"
      SessionObjectName: "PageletsSessionKey"
  - id: "ExchangeSessionObject3"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
    bindings:
      LoadObject: "PromotionsIterator"
      SessionObjectName: "PromotionsSessionKey"
  - id: "ExchangeSessionObject4"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
    bindings:
      LoadObject: "PageletsIterator"
      SessionObjectName: "PageletsSessionKey"
  - id: "ExchangeSessionObject5"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SaveObject: "Pagelets"
      SessionObjectName: "PageletsSessionKey"
  - id: "ExchangeSessionObject6"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SaveObject: "Promotions"
      SessionObjectName: "PromotionsSessionKey"
  - id: "GetABTestGroupByUUID1"
    type: "pipelet"
    ref: "GetABTestGroupByUUID"
    bindings:
      UUID: "ABTestGroupUUID"
      ABTestGroup: "ABTestGroup"
  - id: "GetPageletByUUID1"
    type: "pipelet"
    ref: "GetPageletByUUID"
    bindings:
      PageletUUID: "UUID"
      Pagelet: "Pagelet"
  - id: "GetPromotionByUUID1"
    type: "pipelet"
    ref: "GetPromotionByUUID"
    bindings:
      PromotionUUID: "UUID"
      Promotion: "Promotion"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join2"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewABTestGoingLivePublishingPeriod_52-ListAll"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewABTestGoingLiveAssignments_52-ListAll"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ChannelRepository:Domain"
      OutValue_1: "ChannelRepositoryDomain"
      InValue_2: "ABTestGroup:UserGroup"
      OutValue_2: "UserGroup"
  - id: "LoopNode3"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/ABTestGoingLiveAssignmentsList_52"
  - id: "PutValuesIntoPipelineDictionary1"
    type: "pipelet"
    ref: "PutValuesIntoPipelineDictionary"
    config:
      UseStaticValues: false
      key.1: "ABTest"
      value.1: "ABTestGroup:Test"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "NoAssignmentError"
      ValueType: "Dictionary Value"
      Value: "True"

links:
  - from: "Decision2"
    via: "yes"
    to: "GetABTestGroupByUUID1"
    into: "in"
  - from: "AddObjectToVector6"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "LoopNode3"
    via: "next"
    to: "EndNode10"
    into: "in"
  - from: "GetPromotionByUUID1"
    via: "next"
    to: "AddObjectToVector6"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "JoinNode11"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "GetPromotionByUUID1"
    via: "error"
    to: "JoinNode8"
    into: "in1"
  - from: "AddObjectToVector2"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "LoopNode3"
    via: "do"
    to: "GetPageletByUUID1"
    into: "in"
  - from: "AddObjectToVector5"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join2"
    into: "in3"
  - from: "ExchangeSessionObject4"
    via: "next"
    to: "ExchangeSessionObject3"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "AddObjectToVector5"
    into: "in"
  - from: "GetPageletByUUID1"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "GetPageletByUUID1"
    via: "error"
    to: "GetPromotionByUUID1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "StartNode8"
    via: "next"
    to: "ConcatenateStrings6"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "ExchangeSessionObject3"
    via: "next"
    to: "CreatePageableFromIterator1"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode5"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "PutValuesIntoPipelineDictionary1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "CreatePageableFromIterator1"
    via: "next"
    to: "CreatePageableFromIterator2"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CreatePageableFromIterator2"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CreateFormValuesIteratorForKey1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "ConcatenateStrings4"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "CreateFormValuesIteratorForKey1"
    into: "in"
  - from: "ExchangeSessionObject4"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "ExchangeSessionObject3"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "ExchangeSessionObject5"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "GetABTestGroupByUUID1"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "ExchangeSessionObject6"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode10"
    into: "in2"
  - from: "StartNode6"
    via: "next"
    to: "ConcatenateStrings2"
    into: "in"
  - from: "ExchangeSessionObject5"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "ExchangeSessionObject2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "ConcatenateStrings5"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "ExchangeSessionObject6"
    via: "error"
    to: "JoinNode12"
    into: "in2"
  - from: "ExchangeSessionObject1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode12"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "PutValuesIntoPipelineDictionary1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "JoinNode11"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "ConcatenateStrings4"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "ConcatenateStrings3"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "ExchangeSessionObject4"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "ConcatenateStrings3"
    via: "next"
    to: "ExchangeSessionObject5"
    into: "in"
  - from: "ConcatenateStrings2"
    via: "next"
    to: "ExchangeSessionObject6"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "ConcatenateStrings5"
    into: "in"
  - from: "ExchangeSessionObject2"
    via: "error"
    to: "JoinNode9"
    into: "in1"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode9"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "ConcatenateStrings6"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "ExchangeSessionObject2"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "ExchangeSessionObject1"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "ExchangeSessionObject1"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
