flow: "ViewApplicationServiceEdit"
kind: "view"

entries:
  - id: "Start4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode11"
    name: "View"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode16"
    name: "Cancel"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewServices101-GetServiceRepositoryOfApplicationX"
    bindings:
      ApplicationID: "ApplicationUUID"
  - id: "CallNode2"
    type: "call"
    ref: "ViewServiceEdit-SelectLanguage"
  - id: "CallNode4"
    type: "call"
    ref: "ViewServices101-GetServiceConfigurationByID"
    bindings:
      SelectedServiceConfigurationID: "ServiceConfigurationID"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewApplicationServiceEdit-General"
      OutValue_1: "ViewApplicationServiceEdit-Configuration"
      OutValue_2: "ViewApplicationServiceEdit-SharingRules"
      OutValue_4: "ViewApplicationServiceEdit-Cancel"
      OutValue_6: "ViewApplicationServiceEdit-GeneralValidate"
      OutValue_7: "ViewApplicationServiceEdit-ConfigurationValidate"
      OutValue_8: "ViewApplicationServiceEdit-SharingRulesValidate"
      OutValue_9: "ViewApplicationServiceEdit-SharedRuleValidate"
    bindings:
      Key_0: "general"
      SelectionKey: "JumpTarget"
      Key_1: "configuration"
      Key_2: "sharingRules"
      Key_4: "cancel"
      Key_6: "GeneralValidate"
      Key_7: "ConfigurationValidate"
      Key_8: "SharingRulesValidate"
      Key_9: "SharedRuleValidate"
  - id: "GetApplicationByUUID1"
    type: "pipelet"
    ref: "GetApplicationByUUID"
  - id: "GetApplicationByUUID2"
    type: "pipelet"
    ref: "GetApplicationByUUID"
  - id: "InteractionNode3"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode6"
    type: "jump"
    ref: "ViewApplicationServiceList-Dispatch"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "service/ServicesAdministration/application/ServicesApplicationViewConfiguration"
      SelectedMenuItem: "Applications"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewApplicationServiceEdit-General"

links:
  - from: "GetApplicationByUUID2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "GetApplicationByUUID2"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "JoinNode5"
    via: "next"
    to: "JumpNode6"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "GetApplicationByUUID1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "GetApplicationByUUID1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "GetApplicationByUUID1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode11"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionNode3"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "StartNode16"
    via: "next"
    to: "GetApplicationByUUID2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
