flow: "ViewGiftingPreferences"
kind: "view"

entries:
  - id: "Start1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "View"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Apply"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode2"
    type: "call"
    ref: "ProcessGiftingPreferences-SetGiftingPreferences"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      GiftWrap_Switch: "GiftingPreferencesForm:GiftWrap_Switch:Value"
      GiftMessage_Switch: "GiftingPreferencesForm:GiftMessage_Switch:Value"
      GiftMessage_Form_MessageLength: "GiftingPreferencesForm:GiftMessage_Form_MessageLength:Value"
      PackSlipMessage_Form_MessageLength: "GiftingPreferencesForm:PackSlipMessage_Form_MessageLength:Value"
      PackSlipMessage_Switch: "GiftingPreferencesForm:PackSlipMessage_Switch:Value"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessGiftingPreferences-GetGiftingPreferences"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
  - id: "CreateForm2"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "GiftingPreferencesForm"
      FormResource: "GiftingPreferences"
    bindings:
      Form: "GiftingPreferencesForm"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewGiftingPreferences-Apply"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "updateSettings"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump3"
    type: "jump"
    ref: "Error-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewGiftingPreferences-View"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "gifting/GiftingPreferences"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "gifting/GiftingPreferences"
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewGiftingPreferences-View"
      ValueType: "Dictionary Value"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    config:
      Trim: true
    bindings:
      Form: "GiftingPreferencesForm"
  - id: "ValidateForm2"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "GiftingPreferencesForm"

links:
  - from: "Start1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "CallNode2"
    via: "ERROR"
    to: "Jump3"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "CreateForm2"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CreateForm2"
    into: "in"
  - from: "ValidateForm1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "ValidateForm1"
    via: "error"
    to: "PrepareApplicationView2"
    into: "in"
