flow: "ViewPagelet_comp_product"
kind: "view"

entries:
  - id: "StartNode1"
    name: "AttributeGroup"
    mode: "private"
    strict: true
    inputs:
      - key: "PageletConfigurationParameters"
        type: "java.util.Map"
        required: true
  - id: "StartNode2"
    name: "GetProduct"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductBO"
        type: "com.intershop.component.product.capi.ProductBO"
        required: true
  - id: "StartNode3"
    name: "EligibleShippingMethods"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductBO"
        type: "com.intershop.component.product.capi.ProductBO"
        required: true
  - id: "StartNode4"
    name: "ShippingInformation"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductBO"
        type: "com.intershop.component.product.capi.ProductBO"
        required: true
  - id: "StartNode5"
    name: "Rating"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductBO"
        type: "com.intershop.component.product.capi.ProductBO"
        required: true
  - id: "StartNode6"
    name: "GetSortedVariationProductsByAttribute"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductBO"
        type: "com.intershop.component.product.capi.ProductBO"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewProductReview-GetReviewsByAuthor"
  - id: "CallNode2"
    type: "call"
    ref: "ViewProductReview-GetCustomer"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ProductBO:ProductMaster"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Reviews"
  - id: "DecisionNode3"
    type: "decision"
    condition: "PageletConfigurationParameters:SimpleView"
  - id: "DecisionNode4"
    type: "decision"
    condition: "PageletConfigurationParameters:SimpleView"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "AttributeDescriptors"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "MaxNumberOfAttributes"
        type: "java.lang.Integer"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "Product"
        type: "com.intershop.beehive.xcs.capi.product.Product"
        guaranteed: false
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "ShippingInformation"
        type: "java.util.List<java.lang.String>"
        guaranteed: true
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "AdvancedShippingMethods"
        type: "java.util.List"
        guaranteed: true
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "MasteredProducts"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "Product"
        type: "com.intershop.beehive.xcs.capi.product.Product"
        guaranteed: false
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "ApprovedReviewsAggregatedRating"
        type: "com.intershop.component.rating.capi.AggregatedRatingBO"
        guaranteed: true
      - key: "AlreadyReviewed"
        type: "java.lang.String"
        guaranteed: false
  - id: "ExecutePageableQuery2"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "product/SortVariationProductsByAttribute"
      DefaultPageSize: 15
      ParameterName_01: "LocaleInformation"
    bindings:
      SearchResult: "MasteredProducts"
      ParameterValue_01: "CurrentSession:Locale"
  - id: "GetAggregatedRating1"
    type: "pipelet"
    ref: "GetAggregatedRating"
    config:
      StatusNames: "APPROVED"
    bindings:
      StatusNames: "null"
      AggregatedRating: "ApprovedReviewsAggregatedRating"
  - id: "GetAttributeGroupByID1"
    type: "pipelet"
    ref: "GetAttributeGroupByID"
    bindings:
      ID: "PageletConfigurationParameters:attributeGroupId"
      Domain: "Repository:Domain"
  - id: "GetEligibleShippingMethods1"
    type: "pipelet"
    ref: "GetEligibleShippingMethods"
    bindings:
      Domain: "CurrentOrganization:OwningDomain"
      List: "AdvancedShippingMethods"
  - id: "GetProductByProductRef1"
    type: "pipelet"
    ref: "GetProductByProductRef"
    bindings:
      ProductRef: "ProductBO:ProductRef"
  - id: "GetProductByUUID1"
    type: "pipelet"
    ref: "GetProductByUUID"
    bindings:
      ProductUUID: "ProductBO:ID"
      ProductDomain: "CurrentOrganization:OwningDomain"
  - id: "GetProductByUUID2"
    type: "pipelet"
    ref: "GetProductByUUID"
    bindings:
      ProductUUID: "ProductBO:ID"
      ProductDomain: "CurrentOrganization:OwningDomain"
  - id: "GetProductByUUID3"
    type: "pipelet"
    ref: "GetProductByUUID"
    bindings:
      ProductUUID: "ProductBO:ProductMaster:ID"
      ProductDomain: "CurrentOrganization:OwningDomain"
  - id: "GetProductByUUID4"
    type: "pipelet"
    ref: "GetProductByUUID"
    bindings:
      ProductUUID: "ProductBO:ID"
      ProductDomain: "CurrentOrganization:OwningDomain"
  - id: "GetShippingInformation1"
    type: "pipelet"
    ref: "GetShippingInformation"
    bindings:
      Domain: "CurrentOrganization:OwningDomain"
      Locale: "CurrentRequest:Locale"
      List: "ShippingInformation"
      CurrencyMnemonic: "CurrentRequest:CurrencyCode"
      User: "CurrentUser"
  - id: "GetValuesFromRequest1"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "Application"
    bindings:
      Key: "\"CurrentOrganization\""
      Namespace: "null"
  - id: "GetValuesFromRequest2"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "Application"
    bindings:
      Key: "\"CurrentOrganization\""
      Namespace: "null"
  - id: "GetValuesFromRequest3"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "Application"
    bindings:
      Key: "\"CurrentOrganization\""
      Namespace: "null"
  - id: "GetValuesFromRequest4"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "ApplicationRepository"
    bindings:
      Namespace: "null"
      Key: "null"
  - id: "GetValuesFromRequest5"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "Application"
    bindings:
      Key: "\"CurrentOrganization\""
      Namespace: "null"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "AttributeDescriptors"
      InValue_1: "AttributeGroup:SortedAttributeDescriptors"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ProductBO:Extension(\"Review\")"
      OutValue_1: "BusinessObjectApprovedReviewBORepository"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "AlreadyReviewed"
      Value: true
  - id: "TextNode1"
    type: "text"
  - id: "TextNode2"
    type: "text"
  - id: "UpdateDictionary1"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "Product"
      Name_02: "SortDirection"
      Name_03: "SortAttribute"
      Name_04: "LocaleInformation"
    bindings:
      Value_01: "Product"
      Value_02: "SortDirection"
      Value_03: "SortAttribute"
      Value_04: "Locale"
      OutDictionary: "Parameters"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      LocalizedString: "PageletConfigurationParameters:maxNumberOfAttributes"
      IntegerObject: "MaxNumberOfAttributes"

links:
  - from: "GetAttributeGroupByID1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetProductByProductRef1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "GetProductByProductRef1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "StartNode2"
    via: "next"
    to: "GetProductByProductRef1"
    into: "in"
  - from: "GetValuesFromRequest3"
    via: "error"
    to: "GetProductByUUID2"
    into: "in"
  - from: "GetEligibleShippingMethods1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "GetValuesFromRequest2"
    into: "in"
  - from: "GetValuesFromRequest2"
    via: "next"
    to: "GetProductByUUID1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "GetProductByUUID1"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "GetShippingInformation1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "GetProductByUUID2"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "GetProductByUUID1"
    via: "next"
    to: "GetEligibleShippingMethods1"
    into: "in"
  - from: "GetValuesFromRequest2"
    via: "error"
    to: "GetProductByUUID1"
    into: "in"
  - from: "GetProductByUUID2"
    via: "next"
    to: "GetShippingInformation1"
    into: "in"
  - from: "GetValuesFromRequest1"
    via: "error"
    to: "GetValuesFromRequest4"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "GetValuesFromRequest3"
    into: "in"
  - from: "GetValuesFromRequest3"
    via: "next"
    to: "GetProductByUUID2"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetValuesFromRequest4"
    via: "error"
    to: "GetAttributeGroupByID1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode6"
    into: "in2"
  - from: "GetProductByUUID3"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "ExecutePageableQuery2"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "ExecutePageableQuery2"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "GetProductByUUID4"
    via: "next"
    to: "JoinNode8"
    into: "in3"
  - from: "UpdateDictionary1"
    via: "next"
    to: "ExecutePageableQuery2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "GetProductByUUID4"
    into: "in"
  - from: "GetValuesFromRequest5"
    via: "error"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetProductByUUID3"
    into: "in"
  - from: "GetProductByUUID3"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "UpdateDictionary1"
    into: "in"
  - from: "GetProductByUUID4"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "GetAggregatedRating1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "GetAggregatedRating1"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetValuesFromRequest1"
    via: "next"
    to: "GetValuesFromRequest4"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode11"
    into: "in2"
  - from: "DecisionNode2"
    via: "yes"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "JoinNode10"
    into: "in3"
  - from: "DecisionNode3"
    via: "no"
    to: "DecisionNode4"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode10"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "JoinNode9"
    into: "in2"
  - from: "StartNode6"
    via: "next"
    to: "GetValuesFromRequest5"
    into: "in"
  - from: "GetAttributeGroupByID1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "GetValuesFromRequest5"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "VerifyInteger1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "GetValuesFromRequest1"
    into: "in"
  - from: "GetValuesFromRequest4"
    via: "next"
    to: "GetAttributeGroupByID1"
    into: "in"
