flow: "ViewOrderExportConditions_52"
kind: "view"

entries:
  - id: "StartNode10"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode15"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "CreateForm"
    mode: "private"
    strict: true
    inputs:
      - key: "Config"
        type: "com.intershop.component.orderimpex.capi.export.scenario.ExportScenario"
        required: true
      - key: "OrderConditions"
        type: "com.intershop.component.orderimpex.capi.export.scenario.OrderConditions"
        required: false

steps:
  - id: "CallNode1"
    type: "call"
    ref: "This:CreateForm"
    bindings:
      Config: "Config"
      OrderConditions: "Config:OrderConditions"
  - id: "CallNode10"
    type: "call"
    ref: "ViewOrderExportGeneral_52-Prefix"
  - id: "CallNode11"
    type: "call"
    ref: "ViewOrderExportGeneral_52-Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "This:CreateForm"
    bindings:
      Config: "Config"
      OrderConditions: "null"
  - id: "CreateForm2"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "OrderExportOrderConditions"
      FormResource: "OrderExport_52"
    bindings:
      CurrentDomain: "CurrentDomain"
      Form: "Form"
      FormAlias: "null"
      FormName: "null"
      FormResource: "null"
      Locale: "null"
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "Form"
        type: "com.intershop.beehive.core.capi.webform.Form"
        guaranteed: true
  - id: "GetCurrencies1"
    type: "pipelet"
    ref: "GetCurrencies"
    config:
      Method: "Active Currencies"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
  - id: "InteractionNode5"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewOrderExportConditions_52-Edit"
  - id: "JumpNode4"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "MapFormToObject2"
    type: "pipelet"
    ref: "MapFormToObject"
    config:
      NameFilterType: "exclude"
      NameFilterList: "Currency"
    bindings:
      TargetObject: "Config:OrderConditions"
      NameFilterList: "null"
      Locale: "null"
  - id: "MapObjectToForm1"
    type: "pipelet"
    ref: "MapObjectToForm"
    config:
      NameFilterType: "exclude"
      NameFilterList: "OrderStatuses,OrderLineItemStatuses,OrderPaymentStatuses,Currency"
    bindings:
      SourceObject: "Config:OrderConditions"
      Locale: "null"
      NameFilterList: "null"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewOrderExportConditions_52-Update"
      OutValue_1: "ViewOrderExportConditions_52-Edit"
    bindings:
      Key_0: "update"
      SelectionKey: "JumpTarget"
      Key_1: "reset"
  - id: "PrepareApplicationView5"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "order/OrderExportConditions_52"
      SelectedMenuItem: "Orders"
  - id: "SetFormFieldValues4"
    type: "pipelet"
    ref: "SetFormFieldValues"
    bindings:
      FormField: "Form:OrderPaymentTransactionStatuses:Field"
      SelectedValues: "OrderConditions:OrderPaymentTransactionStatuses:Statuses:Iterator"
      Values: "Config:OrderConditions:OrderPaymentTransactionStatuses:AllStatuses:Iterator"
  - id: "SetFormFieldValues5"
    type: "pipelet"
    ref: "SetFormFieldValues"
    bindings:
      FormField: "Form:OrderStatuses:Field"
      SelectedValues: "OrderConditions:OrderStatuses:Statuses:Iterator"
      Values: "Config:OrderConditions:OrderStatuses:AllStatuses:Iterator"
  - id: "SetFormFieldValues6"
    type: "pipelet"
    ref: "SetFormFieldValues"
    bindings:
      FormField: "Form:OrderLineItemStatuses:Field"
      SelectedValues: "OrderConditions:OrderLineItemStatuses:Statuses:Iterator"
      Values: "Config:OrderConditions:OrderLineItemStatuses:AllStatuses:Iterator"
  - id: "ValidateForm5"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "Form"

links:
  - from: "ValidateForm5"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "StartNode10"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "StartNode15"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "ValidateForm5"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "MapObjectToForm1"
    into: "in"
  - from: "ValidateForm5"
    via: "next"
    to: "MapFormToObject2"
    into: "in"
  - from: "MapFormToObject2"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "MapObjectToForm1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "GetCurrencies1"
    into: "in"
  - from: "SetFormFieldValues6"
    via: "next"
    to: "SetFormFieldValues4"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CreateForm2"
    into: "in"
  - from: "SetFormFieldValues4"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "GetCurrencies1"
    via: "next"
    to: "PrepareApplicationView5"
    into: "in"
  - from: "SetFormFieldValues5"
    via: "next"
    to: "SetFormFieldValues6"
    into: "in"
  - from: "CreateForm2"
    via: "next"
    to: "SetFormFieldValues5"
    into: "in"
  - from: "PrepareApplicationView5"
    via: "next"
    to: "InteractionNode5"
    into: "in"
