flow: "ViewCatalogImportFiles_32"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode10"
    name: "CopyFile"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "DeleteFiles"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "BrowseDirectory"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "Back"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "Upload"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AcquireFileResource1"
    type: "pipelet"
    ref: "AcquireFileResource"
    config:
      DefaultTargetUnitDirectory: "IMPEX_DIR"
      DefaultTargetDirectoryPath: "src/catalog"
    bindings:
      TargetFileNames: "UUIDIterator"
      TargetUnitDomain: "ChannelRepository:Domain"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode5"
    type: "call"
    ref: "ViewCatalogImportFiles-InternalCopyFile"
    bindings:
      TargetDirectory: "\"catalog\""
      UnitDomain: "CurrentChannel:RepositoryDomain"
  - id: "CallNode6"
    type: "call"
    ref: "ViewCatalogImportFiles-InternalUpload"
    bindings:
      UnitDomain: "CurrentChannel:RepositoryDomain"
      TargetDirectory: "\"catalog\""
  - id: "DecisionNode1"
    type: "decision"
    condition: "FileName"
  - id: "DecisionNode2"
    type: "decision"
    condition: "PageNumber"
  - id: "DecisionNode3"
    type: "decision"
    condition: "PageLocator"
  - id: "DecisionNode6"
    type: "decision"
    condition: "Paging"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewCatalogImportFiles_32-Paging"
  - id: "JumpNode10"
    type: "jump"
    ref: "This:Paging"
  - id: "JumpNode11"
    type: "jump"
    ref: "This:BrowseDirectory"
  - id: "JumpNode12"
    type: "jump"
    ref: "This:BrowseDirectory"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewCatalogImportFiles_32-BrowseDirectory"
  - id: "JumpNode5"
    type: "jump"
  - id: "JumpNode6"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode8"
    type: "jump"
    ref: "ViewCatalogImportFiles_32-BrowseDirectory"
  - id: "JumpNode9"
    type: "jump"
    ref: "This:BrowseDirectory"
  - id: "LoopNode2"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelImportExport"
      WorkingTemplate: "impex/CatalogImportSourceFiles_32"
  - id: "Pipelet11"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewCatalogImportFiles_32-Paging"
      DefaultPageLocatorName: "CatalogImportFilesPageLocator"
    bindings:
      Pageable: "Files"
  - id: "Pipelet12"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Files"
  - id: "Pipelet13"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Files"
      PageableID: "PageLocator:PageableID"
  - id: "Pipelet14"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewCatalogImportFiles_32-BrowseDirectory"
      OutValue_1: "ViewCatalogImportFiles_32-Paging"
      OutValue_2: "ViewCatalogImportFiles_32-DeleteFiles"
      OutValue_4: "ViewCatalogImportFiles_32-Back"
      PagingPipeline: "ViewCatalogImportFiles_32-Paging"
      OutValue_3: "ViewCatalogImportFiles_32-CopyFile"
    bindings:
      Key_0: "BrowseDirectory"
      Key_1: "Paging"
      Key_2: "DeleteFiles"
      Key_4: "ConfirmDeleteFiles"
      SelectionKey: "JumpTarget"
      Key_3: "CopyFile"
  - id: "Pipelet17"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"
  - id: "Pipelet18"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "CatalogImportFilesPageLocator"
      RestorePageLocatorDictionary: "True"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    config:
      PageableName: "Files"
      Pagesize: 10
    bindings:
      Iterator: "Directory:Files"
      Pageable: "Files"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "DeleteFile"
    config:
      DefaultDirectoryPath: "src/catalog"
      UnitDirectory: "IMPEX_DIR"
    bindings:
      UnitDomain: "ChannelRepository:Domain"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelImportExport"
      WorkingTemplate: "impex/CatalogImportSourceFiles_32"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "DeleteFile"
    config:
      DefaultDirectoryPath: "upload"
      UnitDirectory: "IMPEX_DIR"
    bindings:
      FileName: "FileName"
      UnitDomain: "CurrentChannel:Domain"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Files"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "CatalogImportFilesPageLocator"
      RestorePageLocatorDictionary: "True"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "BrowseDirectory"
    config:
      DefaultDirectoryPath: "src/catalog"
      UnitDirectory: "IMPEX_DIR"
      IncludeParentDirectories: false
    bindings:
      UnitDomain: "ChannelRepository:Domain"
  - id: "ReleaseFileResource1"
    type: "pipelet"
    ref: "ReleaseFileResource"
    bindings:
      CurrentProcess: "LockProcess"

links:
  - from: "Pipelet3"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "Pipelet18"
    via: "error"
    to: "JumpNode8"
    into: "in"
  - from: "Pipelet13"
    via: "error"
    to: "JoinNode10"
    into: "in2"
  - from: "DecisionNode3"
    via: "yes"
    to: "Pipelet6"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "Pipelet6"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Pipelet12"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Pipelet1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "Pipelet7"
    via: "error"
    to: "JoinNode9"
    into: "in2"
  - from: "StartNode6"
    via: "next"
    to: "Pipelet18"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode11"
    into: "in2"
  - from: "Pipelet4"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "Pipelet5"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "CallNode6"
    via: "next"
    to: "JumpNode9"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode6"
    via: "Error"
    to: "JumpNode11"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "StartNode10"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode6"
    into: "in3"
  - from: "CallNode6"
    via: "FilesAlreadyExist"
    to: "JumpNode10"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "JumpNode12"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "Pipelet11"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "AcquireFileResource1"
    into: "in"
  - from: "Pipelet8"
    via: "error"
    to: "Pipelet4"
    into: "in"
  - from: "AcquireFileResource1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "ReleaseFileResource1"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "Pipelet7"
    via: "next"
    to: "Pipelet13"
    into: "in"
  - from: "Pipelet17"
    via: "error"
    to: "JoinNode4"
    into: "in3"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet17"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "DecisionNode3"
    into: "in"
  - from: "Pipelet11"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet17"
    via: "next"
    to: "Pipelet12"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode2"
    into: "in3"
  - from: "Pipelet18"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Pipelet14"
    via: "next"
    to: "JumpNode6"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "Pipelet14"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "LoopNode2"
    via: "do"
    to: "Pipelet3"
    into: "in"
  - from: "AcquireFileResource1"
    via: "error"
    to: "JumpNode1"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "Pipelet13"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode1"
    into: "in1"
  - from: "LoopNode2"
    via: "next"
    to: "ReleaseFileResource1"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "Pipelet2"
    into: "in"
