flow: "ViewProductPriceMapping_32"
kind: "view"

entries:
  - id: "Start1"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "DeleteBonusPointsRule"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "MappingRules"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "New"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "CreateBonusPointsRule"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "BonusPointsMappingRules"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewProductPriceMapping-UpdateImpl"
  - id: "Call2"
    type: "call"
    ref: "ViewProductPriceMapping-DeleteImpl"
  - id: "Call7"
    type: "call"
    ref: "ViewProductPriceMapping-DeleteImpl"
  - id: "CallNode1"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode10"
    type: "call"
    ref: "ViewProductPriceMapping-NewImpl"
  - id: "CallNode11"
    type: "call"
    ref: "ViewProductPriceMapping-MappingRulesImpl"
  - id: "CallNode12"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode15"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode16"
    type: "call"
    ref: "ViewProductPriceMapping-CreateBonusPointsImpl"
  - id: "CallNode17"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode3"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode5"
    type: "call"
    ref: "ViewProductPriceMapping-StartImpl"
  - id: "CallNode6"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode7"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode8"
    type: "call"
    ref: "ViewProductPriceMapping-MappingRulesImpl"
  - id: "CallNode9"
    type: "call"
    ref: "ViewProductPriceMapping-CreateImpl"
  - id: "CreateWebForm2"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "MappingRule"
      param.1.required: false
      webform-id: "CreatePriceMappingRule"
      param.1.rule: ""
    bindings:
      WebForm: "CreatePriceMappingRule"
  - id: "Decision3"
    type: "decision"
    condition: "confirmDelete"
  - id: "DecisionNode1"
    type: "decision"
    condition: "TargetRuleCurrency"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ProductDataMappingRule:FunctionClassName"
  - id: "DecisionNode3"
    type: "decision"
    condition: "MappingRuleID"
  - id: "DecisionNode4"
    type: "decision"
    condition: "CreatePriceMappingRule:MappingRule:Value"
  - id: "DecisionNode5"
    type: "decision"
    condition: "CreatePriceMappingRule:MappingRule:Value"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProductPriceMapping_32-New"
      OutValue_1: "ViewProductPriceMapping_32-MappingRules"
      OutValue_2: "ViewProductPriceMapping_32-Create"
      OutValue_3: "ViewProductPriceMapping_32-Delete"
      OutValue_4: "ViewProductPriceMapping_32-Update"
      OutValue_5: "ViewProductPriceMapping_32-CreateBonusPointsRule"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "new"
      Key_1: "cancel"
      Key_2: "create"
      Key_3: "delete"
      Key_4: "apply"
      Key_5: "create_bonus_points_rule"
  - id: "End1"
    type: "end"
    strict: false
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "MappingRuleID"
  - id: "GetProductDataMappingRule3"
    type: "pipelet"
    ref: "GetProductDataMappingRule"
    bindings:
      ProductDataMappingRuleID: "MappingRuleID"
  - id: "GetProductDataMappingRuleSet1"
    type: "pipelet"
    ref: "GetProductDataMappingRuleSet"
    bindings:
      DeclaringDomain: "CurrentChannel:RepositoryDomain"
      ProvidingDomain: "ProvidingRepository:RepositoryDomain"
  - id: "GetProductDataMappingRules1"
    type: "pipelet"
    ref: "GetProductDataMappingRules"
    config:
      DefaultTypeCode: 4
    bindings:
      TypeCode: "null"
      DeclaringDomain: "ProductDataMappingRuleSet:DeclaringDomain"
      ProvidingDomain: "ProductDataMappingRuleSet:ProvidingDomain"
      ProductDataMappingRulesMap: "null"
      ProductDataMappingRules: "PriceMappingRules"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "ProvidingRepository"
      UUID: "ProviderID"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "CreatePriceMappingRule"
    bindings:
      WebForm: "CreatePriceMappingRule"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "InteractionEnd4"
    type: "interaction"
  - id: "InteractionEnd6"
    type: "interaction"
  - id: "InteractionEnd7"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "Jump3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump4"
    type: "jump"
    ref: "ViewProductPriceMapping_32-MappingRules"
  - id: "Jump5"
    type: "jump"
    ref: "ViewProductPriceMapping_32-MappingRules"
  - id: "Jump6"
    type: "jump"
    ref: "ViewProductPriceMapping_32-MappingRules"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewProductPriceMapping_32-BonusPointsMappingRules"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewProductPriceMapping_32-DeleteBonusPointsRule"
  - id: "JumpNode7"
    type: "jump"
    ref: "ViewProductPriceMapping_32-BonusPointsMappingRules"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/ProductPriceMappingRuleList_32"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/NewProductPriceMappingRule_32"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/NewProductBonusPointsPricesMappingRule_32"
  - id: "PrepareApplicationView4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/ProductPriceMapping_32"
  - id: "PrepareApplicationView6"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/NewProductPriceMappingRule_32"
  - id: "PrepareApplicationView7"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/NewProductGrantedBonusPointsMappingRule_32"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Value: "ViewProductPriceMapping_32-MappingRules"
      Name: "JumpTarget"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Value: "ViewProductPriceMapping_32-Start"
      Name: "JumpTarget"
      ValueType: "Dictionary Value"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "CreatePriceMappingRule"
    bindings:
      WebForm: "CreatePriceMappingRule"

links:
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "PrepareApplicationView4"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "CallNode10"
    via: "CREATION_PREPARED"
    to: "JoinNode1"
    into: "in1"
  - from: "PrepareApplicationView4"
    via: "next"
    to: "InteractionEnd4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "GetProductDataMappingRuleSet1"
    into: "in"
  - from: "GetProductDataMappingRuleSet1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "Decision3"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "CallNode17"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "JumpNode7"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "CallNode17"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode16"
    via: "CREATED"
    to: "JoinNode2"
    into: "in1"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "CallNode16"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "CallNode15"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "GetProductDataMappingRule3"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JumpNode4"
    into: "in"
  - from: "CallNode16"
    via: "CREATION_PREPARED"
    to: "PrepareApplicationView6"
    into: "in"
  - from: "GetProductDataMappingRule3"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "GetWebForm2"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "CreateWebForm2"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "GetFormSelection1"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "PrepareApplicationView6"
    via: "next"
    to: "InteractionEnd6"
    into: "in"
  - from: "CallNode15"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "CreateWebForm2"
    via: "next"
    to: "GetProductDataMappingRules1"
    into: "in"
  - from: "PrepareApplicationView7"
    via: "next"
    to: "InteractionEnd7"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "GetProductDataMappingRules1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "JoinNode2"
    into: "in2"
  - from: "UpdateWebForm2"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "PrepareApplicationView7"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "JoinNode5"
    into: "in2"
  - from: "DecisionNode3"
    via: "yes"
    to: "JoinNode3"
    into: "in2"
  - from: "JoinNode4"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "CallNode9"
    via: "CREATED"
    to: "Jump6"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "CallNode9"
    via: "CREATION_PREPARED"
    to: "JoinNode1"
    into: "in1"
