flow: "ViewChannelSharedProductChanges"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "DiscardChanges"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "GetFreightClass"
    mode: "private"
    strict: true
    inputs:
      - key: "BaseProductFreightClassID"
        type: "java.lang.String"
        required: false
      - key: "ProductFreightClassID"
        type: "java.lang.String"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessProduct-DiscardChanges"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessProductLock-Lookup"
    bindings:
      User: "CurrentUser"
  - id: "DecisionNode1"
    type: "decision"
    condition: "BaseProductFreightClassID"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelSharedProductChanges-DiscardChanges"
      OutValue_1: "ViewChannelSharedProductChanges-Start"
      OutValue_2: "ViewChannelSharedProductChanges-Start"
      OutValue_3: "ViewChannelSharedProductChanges-Start"
    bindings:
      Key_3: "cancelDelete"
      Key_2: "cancel"
      Key_1: "confirmDelete"
      Key_0: "delete"
      SelectionKey: "JumpTarget"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "FreightClass"
        type: "com.intershop.component.shipping.capi.freightclass.FreightClass"
        guaranteed: true
      - key: "BaseProductFreightClass"
        type: "com.intershop.component.shipping.capi.freightclass.FreightClass"
        guaranteed: false
  - id: "GetCurrencies1"
    type: "pipelet"
    ref: "GetCurrencies"
    config:
      Method: "Active Currencies"
    bindings:
      Domain: "OrganizationDomain"
  - id: "GetCustomAttributes1"
    type: "pipelet"
    ref: "GetCustomAttributes"
    config:
      FilteredAttributes: "name;SKU;shortDescription;longDescription;BaseUnit;RatioBasePackingUnit;DeliveryDays;EANCode;AvailabilityStatus;orderRequiredAttributes;manufacturerName;manufacturerSKU;eclass;unspsc;RunningAuctions;FreightClassID;PID_*;ReadyForShipmentMax;ReadyForShipmentMin"
    bindings:
      ExtensibleObject: "Product"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductLockActivated"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceStringValue: "ProductLockActivated"
  - id: "GetFreightClassByID1"
    type: "pipelet"
    ref: "GetFreightClassByID"
    bindings:
      ID: "ProductFreightClassID"
  - id: "GetFreightClassByID2"
    type: "pipelet"
    ref: "GetFreightClassByID"
    bindings:
      ID: "BaseProductFreightClassID"
      FreightClass: "BaseProductFreightClass"
  - id: "GetProductByUUID7"
    type: "pipelet"
    ref: "GetProductByUUID"
    bindings:
      ProductUUID: "ProductID"
      ProductDomain: "CurrentProductRepository:RepositoryDomain"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewChannelSharedProductChanges-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewProduct-ErrorProductNotAvailable"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewProduct-ErrorProductNotAvailable"
  - id: "JumpNode5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ChannelSharedProductChanges.isml"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewChannelSharedProductChanges-Start"
      ValueType: "Dictionary Value"

links:
  - from: "GetDomainPreference1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "GetProductByUUID7"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "StartNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "GetDomainPreference1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "CallNode1"
    via: "ERROR"
    to: "JumpNode2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetFreightClassByID2"
    into: "in"
  - from: "GetFreightClassByID1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GetFreightClassByID1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "GetFreightClassByID2"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetFreightClassByID2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "GetProductByUUID7"
    via: "error"
    to: "JumpNode3"
    into: "in"
  - from: "GetCustomAttributes1"
    via: "next"
    to: "GetCurrencies1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "CallNode2"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "GetProductByUUID7"
    via: "next"
    to: "GetCustomAttributes1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "GetFreightClassByID1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode4"
    into: "in2"
  - from: "GetCurrencies1"
    via: "next"
    to: "CallNode2"
    into: "in"
