flow: "ViewGiftCertificate_52"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "ManageTransactions"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Remove"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "Show"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewGiftCertificate_52-Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "ViewGiftCertificate_52-Prefix"
  - id: "CallNode3"
    type: "call"
    ref: "ViewGiftCertificate_52-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ViewGiftCertificate_52-Prefix"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessPrepareGiftCardBackOfficeView-PrepareBackOfficeDetailsView"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessGiftCard-Remove"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessGiftCard-Update"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_1: "ViewGiftCertificate_52-Show"
      OutValue_0: "ViewGiftCertificate_52-Update"
      OutValue_2: "ViewGiftCertificate_52-Remove"
      OutValue_3: "ViewGiftCertificate_52-Show"
    bindings:
      Key_1: "delete"
      Key_0: "save"
      Key_2: "deleteConfirm"
      SelectionKey: "JumpTarget"
      Key_3: "cancel"
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "GetGiftCardByID2"
    type: "pipelet"
    ref: "PrepareBackOfficeDetailsView"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
      GiftCardId: "GiftCardID"
  - id: "GetRegisteredGiftCardService1"
    type: "pipelet"
    ref: "GetRegisteredGiftCardService"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewGiftCertificateList_52-Search"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewGiftCertificate_52-Show"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentChannel:RepositoryDomain"
      OutValue_1: "Domain"
  - id: "KeyMapper6"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Repository(\"ServiceConfigurationBORepository\")"
      OutValue_1: "ServiceConfigurationBORepository"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "marketing/GiftCardTransactions_52"
      SelectedMenuItem: "Marketing"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "marketing/GiftCardDetails_52"
      SelectedMenuItem: "Marketing"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewGiftCertificate_52-Show"

links:
  - from: "StartNode1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode6"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "GetGiftCardByID2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "KeyMapper6"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "KeyMapper6"
    via: "next"
    to: "GetRegisteredGiftCardService1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "GetGiftCardByID2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "GetRegisteredGiftCardService1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "GetRegisteredGiftCardService1"
    via: "error"
    to: "EndNode3"
    into: "in"
