flow: "ViewPagelet_comp_endcaps"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Simple"
    mode: "private"
    strict: false
    inputs:
      - key: "CategoryBO"
        type: "com.intershop.component.catalog.capi.CatalogCategoryBO"
        required: false
      - key: "SearchTerm"
        type: "java.lang.String"
        required: false
  - id: "StartNode2"
    name: "RenderEndcapView"
    mode: "private"
    strict: false
    inputs:
      - key: "CurrentDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
      - key: "CategoryBO"
        type: "com.intershop.component.catalog.capi.CatalogCategoryBO"
        required: false
      - key: "SearchTerm"
        type: "java.lang.String"
        required: false
  - id: "StartNode3"
    name: "GetProducts"
    mode: "private"
    strict: true
    inputs:
      - key: "ProductFilterName"
        type: "java.lang.String"
        required: true
      - key: "EndcapScope"
        type: "java.lang.String"
        required: true
      - key: "CategoryBO"
        type: "com.intershop.component.catalog.capi.CatalogCategoryBO"
        required: false
      - key: "SearchTerm"
        type: "java.lang.String"
        required: false
  - id: "StartNode4"
    name: "RenderViewAll"
    mode: "private"
    strict: true
    inputs:
      - key: "CategoryBO"
        type: "com.intershop.component.catalog.capi.CatalogCategoryBO"
        required: false
      - key: "PageSize"
        type: "java.lang.String"
        required: false
      - key: "PageNumber"
        type: "java.lang.String"
        required: false
      - key: "EndcapMasterPageletUUID"
        type: "java.lang.String"
        required: false
      - key: "CatalogCategoryID"
        type: "java.lang.String"
        required: false
      - key: "SearchTerm"
        type: "java.lang.String"
        required: false
      - key: "SortingAttribute"
        type: "java.lang.String"
        required: false
  - id: "StartNode7"
    name: "GetMasterPageletConfiguration"
    mode: "private"
    strict: true
    inputs:
      - key: "EndcapMasterPageletUUID"
        type: "java.lang.String"
        required: true

steps:
  - id: "AddMultipleEntriesToMap1"
    type: "pipelet"
    ref: "AddMultipleEntriesToMap"
    config:
      Mode: "OverwriteValue"
    bindings:
      Key1: "\"CatalogCategoryID\""
      Value1: "Category:UUID"
      OutMap: "GenericHandlerPipelineParams"
      Value3: "SearchTerm"
      Key3: "\"SearchTerm\""
      Key2: "\"EndcapMasterPageletUUID\""
      Value2: "EndcapMasterPageletUUID"
      Key4: "\"SortingAttribute\""
      Value4: "SortingAttribute"
  - id: "CalculateInteger1"
    type: "pipelet"
    ref: "CalculateInteger"
    config:
      Operation: "+"
      Operand2: 1
    bindings:
      Result: "Page"
      Operand1: "PageNumber"
  - id: "CallNode1"
    type: "call"
    ref: "ViewPagelet_comp_endcaps-GetProducts"
    bindings:
      ProductFilterName: "PageletConfigurationParameters:predefinedFilter"
      EndcapScope: "PageletConfigurationParameters:endcapScope"
  - id: "CallNode10"
    type: "call"
    ref: "ProcessB2CProduct-GetProductBOs"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessSearchQueryDefinitionBySearchIndex-GetProducts"
    bindings:
      SearchQueryDefinitionID: "ProductFilterName"
      ProductDomain: "CurrentOrganization:OwningDomain"
      CatalogDomain: "CurrentOrganization:OwningDomain"
      CatalogCategory: "Category"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessSearchQueryDefinitionBySearchIndex-GetProducts"
    bindings:
      SearchQueryDefinitionID: "ProductFilterName"
      ProductDomain: "CurrentOrganization:OwningDomain"
      CatalogDomain: "CurrentOrganization:OwningDomain"
      Page: "Page"
      PageSize: "PageSize"
      CatalogCategory: "ContextCategory"
  - id: "CallNode5"
    type: "call"
    ref: "ViewPagelet_comp_endcaps-GetMasterPageletConfiguration"
    bindings:
      EndcapTitle: "Title"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessB2CProduct-GetProductBOs"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessChannelCatalog-GetCategoryBO"
  - id: "CallNode9"
    type: "call"
    ref: "ViewPagelet_comp_endcaps-GetProducts"
    bindings:
      ProductFilterName: "PageletConfigurationParameters:predefinedFilter"
      EndcapScope: "PageletConfigurationParameters:endcapScope"
  - id: "CreateSearchIndexCategoryNavigationList1"
    type: "pipelet"
    ref: "CreateSearchIndexCategoryNavigationList"
    bindings:
      HandlerPipeline: "\"ViewAllEndcaps\""
  - id: "DecisionNode1"
    type: "decision"
    condition: "EndcapScope"
  - id: "DecisionNode2"
    type: "decision"
    condition: "CatalogCategoryID"
  - id: "DecisionNode3"
    type: "decision"
    condition: "ConfigurationParameterMap:MaximumNumberOfProducts"
  - id: "DecisionNode4"
    type: "decision"
    condition: "PageNumber"
  - id: "DecisionNode5"
    type: "decision"
    condition: "PageSize"
  - id: "DecisionNode6"
    type: "decision"
    condition: "EndcapScope"
  - id: "DecisionNode7"
    type: "decision"
    condition: "CategoryBO"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ProductBOs"
        type: "java.util.Iterator"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "ProductBOs"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "Title"
        type: "java.lang.String"
        guaranteed: false
      - key: "CategoryBO"
        type: "com.intershop.component.catalog.capi.CatalogCategoryBO"
        guaranteed: false
      - key: "SearchTerm"
        type: "java.lang.String"
        guaranteed: false
      - key: "EndcapMasterPageletUUID"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode4"
    type: "end"
    strict: false
    outputs:
      - key: "ProductBOs"
        type: "java.util.Iterator"
        guaranteed: false
  - id: "EndNode5"
    type: "end"
    strict: true
  - id: "EndNode6"
    type: "end"
    strict: true
  - id: "EndNode7"
    type: "end"
    strict: true
    outputs:
      - key: "Title"
        type: "java.lang.String"
        guaranteed: false
      - key: "PageNumber"
        type: "java.lang.Integer"
        guaranteed: false
      - key: "PageSize"
        type: "java.lang.Integer"
        guaranteed: false
      - key: "CategoryBO"
        type: "com.intershop.component.catalog.capi.CatalogCategoryBO"
        guaranteed: false
      - key: "ProductBOs"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "ListNavigationVO"
        type: "com.intershop.sellside.application.b2c.capi.common.ListNavigationVO"
        guaranteed: true
  - id: "EndNode9"
    type: "end"
    strict: true
    outputs:
      - key: "EndcapScope"
        type: "java.lang.String"
        guaranteed: true
      - key: "EndcapTitle"
        type: "java.lang.String"
        guaranteed: false
      - key: "MaximumNumberOfProducts"
        type: "java.lang.Integer"
        guaranteed: false
      - key: "ProductFilterName"
        type: "java.lang.String"
        guaranteed: true
  - id: "GetCategoryByName1"
    type: "pipelet"
    ref: "GetCategoryByName"
    bindings:
      CategoryDomainName: "CategoryBO:DomainName"
      CategoryName: "CategoryBO:Name"
  - id: "GetCategoryByName2"
    type: "pipelet"
    ref: "GetCategoryByName"
    bindings:
      CategoryDomainName: "CategoryBO:DomainName"
      CategoryName: "CategoryBO:Name"
  - id: "GetCategoryByUUID1"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "CatalogCategoryID"
      Category: "Category"
  - id: "GetConfigurationParametersAsMap1"
    type: "pipelet"
    ref: "GetConfigurationParametersAsMap"
    config:
      UseLocaleFallback: true
    bindings:
      ConfigurationParameterCtnr: "EndcapMasterPagelet"
      Locale: "CurrentRequest:Locale"
  - id: "GetPageletByUUID1"
    type: "pipelet"
    ref: "GetPageletByUUID"
    bindings:
      PageletUUID: "EndcapMasterPageletUUID"
      Pagelet: "EndcapMasterPagelet"
  - id: "GetSearchQueryDefinition1"
    type: "pipelet"
    ref: "GetSearchQueryDefinition"
    bindings:
      Domain: "CurrentDomain"
      Name: "ProductFilterName"
  - id: "GetValuesFromRequest1"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "Application"
    bindings:
      Key: "\"CurrentOrganization\""
      Namespace: "null"
  - id: "GetValuesFromRequest2"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "Application"
    bindings:
      Key: "\"CurrentOrganization\""
      Namespace: "null"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode15"
    type: "join"
  - id: "JoinNode16"
    type: "join"
  - id: "JoinNode18"
    type: "join"
  - id: "JoinNode19"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "ContextCategory"
      InValue_1: "Category"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ConfigurationParameterMap:title"
      OutValue_1: "EndcapTitle"
      InValue_2: "ConfigurationParameterMap:endcapScope"
      OutValue_2: "EndcapScope"
      InValue_3: "ConfigurationParameterMap:predefinedFilter"
      OutValue_3: "ProductFilterName"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "PageletConfigurationParameters:title"
      OutValue_1: "Title"
      OutValue_2: "EndcapMasterPageletUUID"
      InValue_2: "Pagelet:UUID"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"(Integer)12\""
      OutValue_1: "PageSize"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"(Integer)0\""
      OutValue_1: "PageNumber"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    config:
      MinValue: 0
    bindings:
      LocalizedString: "PageNumber"
      IntegerValue: "null"
      IntegerObject: "PageNumber"
  - id: "VerifyInteger2"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "Page"
      LocalizedString: "\"1\""
  - id: "VerifyInteger3"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageSize"
      LocalizedString: "\"20\""
  - id: "VerifyInteger4"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "MaximumNumberOfProducts"
      LocalizedString: "ConfigurationParameterMap:MaximumNumberOfProducts"
      IntegerValue: "null"
  - id: "VerifyInteger5"
    type: "pipelet"
    ref: "VerifyInteger"
    config:
      MinValue: 3
    bindings:
      LocalizedString: "PageSize"
      IntegerObject: "PageSize"
      IntegerValue: "null"

links:
  - from: "StartNode1"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "VerifyInteger4"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "VerifyInteger2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "VerifyInteger2"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "GetPageletByUUID1"
    via: "error"
    to: "EndNode6"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "JoinNode8"
    into: "in2"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode19"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetSearchQueryDefinition1"
    via: "next"
    to: "GetValuesFromRequest1"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "CreateSearchIndexCategoryNavigationList1"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "GetCategoryByName1"
    via: "error"
    to: "JoinNode19"
    into: "in2"
  - from: "VerifyInteger4"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "GetValuesFromRequest1"
    via: "next"
    to: "VerifyInteger2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode3"
    via: "no"
    to: "VerifyInteger4"
    into: "in"
  - from: "CallNode3"
    via: "NO_SEARCHINDEX"
    to: "JoinNode6"
    into: "in2"
  - from: "VerifyInteger3"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "VerifyInteger3"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "EndNode9"
    into: "in"
  - from: "VerifyInteger3"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "CalculateInteger1"
    via: "next"
    to: "GetValuesFromRequest2"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "Pipelet2"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "GetCategoryByName2"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "Pipelet1"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode15"
    into: "in2"
  - from: "GetPageletByUUID1"
    via: "next"
    to: "GetConfigurationParametersAsMap1"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "AddMultipleEntriesToMap1"
    via: "next"
    to: "CreateSearchIndexCategoryNavigationList1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode9"
    into: "in1"
  - from: "CallNode11"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "CallNode11"
    via: "NO_SEARCHINDEX"
    to: "JoinNode10"
    into: "in2"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode12"
    into: "in3"
  - from: "DecisionNode5"
    via: "yes"
    to: "VerifyInteger5"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "JoinNode13"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "GetConfigurationParametersAsMap1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "GetCategoryByUUID1"
    into: "in"
  - from: "CallNode11"
    via: "ERROR"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetValuesFromRequest2"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "GetCategoryByUUID1"
    via: "error"
    to: "JoinNode9"
    into: "in2"
  - from: "GetValuesFromRequest2"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode12"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "JoinNode13"
    into: "in2"
  - from: "VerifyInteger1"
    via: "next"
    to: "JoinNode13"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "GetSearchQueryDefinition1"
    into: "in"
  - from: "JoinNode14"
    via: "next"
    to: "JoinNode11"
    into: "in2"
  - from: "VerifyInteger5"
    via: "error"
    to: "JoinNode14"
    into: "in2"
  - from: "VerifyInteger5"
    via: "next"
    to: "JoinNode14"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "CalculateInteger1"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "DecisionNode2"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode15"
    into: "in1"
  - from: "JoinNode15"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "DecisionNode7"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "GetCategoryByName2"
    via: "next"
    to: "JoinNode16"
    into: "in1"
  - from: "StartNode7"
    via: "next"
    to: "GetPageletByUUID1"
    into: "in"
  - from: "GetCategoryByName2"
    via: "error"
    to: "JoinNode18"
    into: "in2"
  - from: "JoinNode16"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "GetValuesFromRequest1"
    via: "error"
    to: "VerifyInteger2"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "JoinNode18"
    into: "in1"
  - from: "CallNode10"
    via: "next"
    to: "AddMultipleEntriesToMap1"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "JoinNode18"
    via: "next"
    to: "JoinNode16"
    into: "in2"
  - from: "JoinNode6"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "GetCategoryByUUID1"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetCategoryByName1"
    into: "in"
  - from: "GetCategoryByName1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "JoinNode19"
    via: "next"
    to: "JoinNode4"
    into: "in2"
  - from: "CallNode3"
    via: "ERROR"
    to: "JoinNode6"
    into: "in1"
