flow: "ViewProductMaintenance"
kind: "view"

entries:
  - id: "Start1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "UpdateLifecycle"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessProductHistory-SaveProductSnapShot"
  - id: "Call2"
    type: "call"
    ref: "ProcessProductMaintenance-UpdateLifecycle"
  - id: "Call4"
    type: "call"
    ref: "ProcessProductHistory-SaveProductSnapShot"
  - id: "Call5"
    type: "call"
    ref: "ProcessProductMaintenance-Update"
  - id: "CallNode1"
    type: "call"
    ref: "DetermineProduct-MasterRepositoryProduct"
  - id: "CallNode11"
    type: "call"
    ref: "DetermineProduct-MasterRepositoryProduct"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessProductLock-Lookup"
    bindings:
      User: "CurrentUser"
  - id: "CallNode3"
    type: "call"
    ref: "DetermineProduct-MasterRepositoryProduct"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessProductLock-Check"
    bindings:
      LockingDomain: "OrganizationDomain"
      PreferenceDomain: "OrganizationDomain"
      User: "CurrentUser"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessProductLock-Check"
    bindings:
      LockingDomain: "OrganizationDomain"
      PreferenceDomain: "OrganizationDomain"
      User: "CurrentUser"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessProduct-DetermineCategoryPath"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProductMaintenance-Update"
      OutValue_1: "ViewProductMaintenance-Start"
      OutValue_2: "ViewProductList-Paging"
      OutValue_3: "ViewProductMaintenance-UpdateLifecycle"
    bindings:
      Key_0: "update"
      Key_1: "reset"
      Key_2: "back"
      SelectionKey: "JumpTarget"
      Key_3: "updatelifecycle"
  - id: "GetDomainPreference7"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductLockActivated"
      Type: "String"
    bindings:
      PreferenceDomain: "OrganizationDomain"
      PreferenceStringValue: "ProductLockActivated"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump3"
    type: "jump"
    ref: "ViewProductMaintenance-Start"
  - id: "Jump6"
    type: "jump"
    ref: "ViewProductMaintenance-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewProduct-ErrorProductNotAvailable"
  - id: "JumpNode10"
    type: "jump"
    ref: "ViewProduct-ErrorProductNotAvailable"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewProduct-ErrorProductNotAvailable"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Products"
      WorkingTemplate: "product/ProductMaintenance"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewProductMaintenance-Start"
      ValueType: "Dictionary Value"

links:
  - from: "Call4"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "CallNode5"
    via: "NO_LOCK"
    to: "JoinNode1"
    into: "in3"
  - from: "CallNode1"
    via: "error-product-not-available"
    to: "JumpNode4"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Jump6"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "CallNode11"
    via: "error-product-not-available"
    to: "JumpNode10"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "GetDomainPreference7"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode3"
    via: "error-product-not-available"
    to: "JumpNode1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "GetDomainPreference7"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "CallNode2"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode4"
    via: "NO_LOCK"
    to: "JoinNode3"
    into: "in3"
  - from: "Start2"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "GetDomainPreference7"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode5"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
