flow: "ViewRuleActionConfiguration"
kind: "view"

entries:
  - id: "Start2"
    name: "DeleteActionClipboard"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "UpdateActionClipboard"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode10"
    name: "NewAction"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode11"
    name: "CreateAction"
    mode: "private"
    strict: false
    inputs:
      - key: "ActionOwner"
        type: "com.intershop.beehive.core.capi.domain.PersistentObject"
        required: true
  - id: "StartNode12"
    name: "UpdateAction"
    mode: "private"
    strict: false
    inputs:
      - key: "PromotionUUID"
        type: "java.lang.String"
        required: true
      - key: "EditActionID"
        type: "java.lang.String"
        required: true
  - id: "StartNode13"
    name: "EditAction"
    mode: "private"
    strict: false
    inputs:
      - key: "PromotionUUID"
        type: "java.lang.String"
        required: true
      - key: "EditActionID"
        type: "java.lang.String"
        required: true
  - id: "StartNode15"
    name: "RemoveAction"
    mode: "private"
    strict: false
    inputs:
      - key: "PromotionUUID"
        type: "java.lang.String"
        required: false

steps:
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      Object: "ActionDescriptor"
      Objects: "TypeActionDescriptors"
      Iterator: "TypeActionDescriptors"
  - id: "CallNode1"
    type: "call"
    ref: "ViewRuleActionConfiguration-DeleteActionClipboard"
  - id: "CallNode19"
    type: "call"
    ref: "ProcessActionConfiguration-CreateActionForm"
  - id: "CallNode22"
    type: "call"
    ref: "ProcessActionConfiguration-CreateAction"
    bindings:
      Owner: "ActionOwner"
  - id: "CallNode24"
    type: "call"
    ref: "ProcessActionConfiguration-CreateActionForm"
  - id: "CallNode25"
    type: "call"
    ref: "ProcessActionConfiguration-CreateActionForm"
  - id: "CallNode26"
    type: "call"
    ref: "ProcessActionConfiguration-UpdateConfigurationParameters"
  - id: "CallNode28"
    type: "call"
    ref: "ProcessActionConfiguration-RemoveAction"
  - id: "CallNode30"
    type: "call"
    ref: "ProcessActionConfiguration-CreateActionForm"
  - id: "DecisionNode16"
    type: "decision"
    condition: "ActionForm:Invalid"
  - id: "DecisionNode5"
    type: "decision"
    condition: "ActionDescriptor:Type"
  - id: "DecisionNode7"
    type: "decision"
    condition: "ActionForm:ActionType:ValueMissing"
  - id: "DecisionNode8"
    type: "decision"
    condition: "FormParameterValuesMap"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "GetActionByID1"
    type: "pipelet"
    ref: "GetActionByID"
    bindings:
      Action: "EditAction"
      ActionID: "EditActionID"
  - id: "GetActionByID2"
    type: "pipelet"
    ref: "GetActionByID"
    bindings:
      ActionID: "EditActionID"
      Action: "EditAction"
  - id: "GetClipboard2"
    type: "pipelet"
    ref: "GetClipboard"
    config:
      SessionRegistrationID: "Actions"
      SetFormValues: "No"
    bindings:
      UUIDIterator: "SelectedActions"
  - id: "GetFormRecord1"
    type: "pipelet"
    ref: "GetFormRecord"
    config:
      DefaultRecordID: "SelectedAction"
    bindings:
      RecordID: "null"
      FormRecord: "SelectedActions"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode15"
    type: "join"
  - id: "JoinNode16"
    type: "join"
  - id: "JoinNode17"
    type: "join"
  - id: "JoinNode29"
    type: "join"
  - id: "JoinNode32"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
  - id: "JumpNode2"
    type: "jump"
  - id: "JumpNode3"
    type: "jump"
  - id: "JumpNode4"
    type: "jump"
  - id: "JumpNode8"
    type: "jump"
  - id: "KeyMapper10"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"true\""
      OutValue_1: "ClipboardDeleted"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ActionForm"
      OutValue_1: "NewActionForm"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ActionForm"
      OutValue_1: "NewActionForm"
      OutValue_2: "ErrorCreateAction"
      InValue_2: "\"(Boolean)true\""
  - id: "LoopNode1"
    type: "loop"
  - id: "RemoveClipboard3"
    type: "pipelet"
    ref: "RemoveClipboard"
    config:
      SessionRegistrationID: "Actions"
  - id: "RemoveDictionaryValue2"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "EditAction"
  - id: "SetFormParameterValues3"
    type: "pipelet"
    ref: "SetFormParameterValues"
  - id: "SetFormParameterValues4"
    type: "pipelet"
    ref: "SetFormParameterValues"
  - id: "UpdateClipboard1"
    type: "pipelet"
    ref: "UpdateClipboard"
    config:
      SessionRegistrationID: "Actions"
      StoreFormValues: "No"
    bindings:
      AllObjectUUIDs: "SelectedActions:KeySet:Iterator"
      SelectedObjectUUIDs: "SelectedActions:KeySet:Iterator"
      Clipboard: "ActionClipboard"
  - id: "UpdateClipboard4"
    type: "pipelet"
    ref: "UpdateClipboard"
    config:
      SessionRegistrationID: "Actions"
      StoreFormValues: "No"
    bindings:
      AllObjectUUIDs: "NULL"
      SelectedObjectUUIDs: "NULL"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "ActionForm"
  - id: "ValidateForm2"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "ActionForm"

links:
  - from: "CallNode26"
    via: "next"
    to: "RemoveDictionaryValue2"
    into: "in"
  - from: "JoinNode15"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "JoinNode32"
    via: "next"
    to: "JoinNode16"
    into: "in1"
  - from: "CallNode30"
    via: "next"
    to: "DecisionNode16"
    into: "in"
  - from: "RemoveDictionaryValue2"
    via: "next"
    to: "JoinNode16"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "JumpNode8"
    into: "in"
  - from: "JoinNode13"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "SetFormParameterValues4"
    via: "next"
    to: "JoinNode17"
    into: "in2"
  - from: "KeyMapper5"
    via: "next"
    to: "JoinNode15"
    into: "in1"
  - from: "CallNode25"
    via: "next"
    to: "SetFormParameterValues4"
    into: "in"
  - from: "CallNode24"
    via: "next"
    to: "ValidateForm2"
    into: "in"
  - from: "StartNode15"
    via: "next"
    to: "GetClipboard2"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "LoopNode1"
    into: "in"
  - from: "StartNode13"
    via: "next"
    to: "GetActionByID2"
    into: "in"
  - from: "CallNode19"
    via: "next"
    to: "DecisionNode7"
    into: "in"
  - from: "DecisionNode16"
    via: "no"
    to: "JoinNode29"
    into: "in1"
  - from: "StartNode12"
    via: "next"
    to: "GetActionByID1"
    into: "in"
  - from: "DecisionNode8"
    via: "yes"
    to: "SetFormParameterValues3"
    into: "in"
  - from: "GetActionByID1"
    via: "error"
    to: "JoinNode29"
    into: "in1"
  - from: "JoinNode17"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode8"
    into: "in2"
  - from: "UpdateClipboard4"
    via: "next"
    to: "KeyMapper10"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "DecisionNode16"
    via: "yes"
    to: "ValidateForm1"
    into: "in"
  - from: "JoinNode14"
    via: "next"
    to: "CallNode22"
    into: "in"
  - from: "GetActionByID1"
    via: "next"
    to: "CallNode30"
    into: "in"
  - from: "ValidateForm1"
    via: "error"
    to: "JoinNode32"
    into: "in1"
  - from: "GetActionByID2"
    via: "next"
    to: "CallNode25"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "JoinNode11"
    into: "in2"
  - from: "Start6"
    via: "next"
    to: "GetFormRecord1"
    into: "in"
  - from: "DecisionNode8"
    via: "no"
    to: "JoinNode14"
    into: "in2"
  - from: "CallNode28"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetClipboard2"
    via: "next"
    to: "CallNode28"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "DecisionNode5"
    into: "in"
  - from: "StartNode11"
    via: "next"
    to: "CallNode24"
    into: "in"
  - from: "ValidateForm2"
    via: "next"
    to: "DecisionNode8"
    into: "in"
  - from: "JoinNode29"
    via: "next"
    to: "JoinNode32"
    into: "in1"
  - from: "AddObjectToVector2"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "KeyMapper10"
    via: "next"
    to: "End1"
    into: "in"
  - from: "CallNode22"
    via: "error"
    to: "JoinNode13"
    into: "in1"
  - from: "ValidateForm2"
    via: "error"
    to: "JoinNode13"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "CallNode22"
    via: "next"
    to: "JoinNode15"
    into: "in2"
  - from: "GetFormRecord1"
    via: "next"
    to: "UpdateClipboard1"
    into: "in"
  - from: "ValidateForm1"
    via: "next"
    to: "CallNode26"
    into: "in"
  - from: "StartNode10"
    via: "next"
    to: "CallNode19"
    into: "in"
  - from: "UpdateClipboard1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "RemoveClipboard3"
    into: "in"
  - from: "RemoveClipboard3"
    via: "next"
    to: "UpdateClipboard4"
    into: "in"
  - from: "SetFormParameterValues3"
    via: "next"
    to: "JoinNode14"
    into: "in1"
  - from: "GetActionByID2"
    via: "error"
    to: "JoinNode17"
    into: "in1"
  - from: "JoinNode16"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "AddObjectToVector2"
    into: "in"
