flow: "ViewLocalizations_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start14"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Management"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "InitBranch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Save"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessLocalizations-CreatePageable"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessLocalizations-SetPage"
  - id: "CallNode3"
    type: "call"
    ref: "This:InitBranch"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessLocalizations-UpdateTexts"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessLocalizations-CreateForm"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessLocalizations-CreatePageable"
  - id: "CallNode7"
    type: "call"
    ref: "This:InitBranch"
  - id: "CallNode8"
    type: "call"
    ref: "This:InitBranch"
  - id: "CallNode9"
    type: "call"
    ref: "ProcessLocalizations-GetContextApplication"
    bindings:
      ApplicationUUID: "ApplicationId"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewLocalizations_52-Management"
      OutValue_1: "ViewLocalizations_52-Management"
      OutValue_2: "ViewLocalizations_52-Save"
      OutValue_3: "ViewLocalizations_52-Management"
    bindings:
      Key_0: "Apply"
      Key_1: "Find"
      Key_2: "Save"
      Key_3: "cancelUpdate"
      SelectionKey: "JumpTarget"
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Lead Locale"
  - id: "GetLocale4"
    type: "pipelet"
    ref: "GetLocale"
    bindings:
      LocaleId: "ChannelDefaultLocale"
      Locale: "DefaultChannelLocale"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      RestorePageLocatorDictionary: "True"
      DefaultPageLocatorName: "LocalizationTextsLocator"
      UsePageLocatorHistory: false
  - id: "GetPageLocator2"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      RestorePageLocatorDictionary: "True"
      DefaultPageLocatorName: "LocalizationTextsLocator"
      UsePageLocatorHistory: false
  - id: "GetPageable2"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      PageableID: "\"LocalizationTextsPageableID\""
      Pageable: "LocalizationTexts"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "Jump17"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "Error-Start"
  - id: "KeyMapper0"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:DefaultLocale:LocaleID"
      InValue_10: "null"
      InValue_3: "null"
      InValue_4: "null"
      InValue_5: "null"
      InValue_6: "null"
      InValue_7: "null"
      InValue_8: "null"
      InValue_9: "null"
      InValue_2: "null"
      OutValue_1: "ChannelDefaultLocale"
      OutValue_10: "null"
      OutValue_3: "null"
      OutValue_4: "null"
      OutValue_5: "null"
      OutValue_6: "null"
      OutValue_7: "null"
      OutValue_8: "null"
      OutValue_9: "null"
      OutValue_2: "null"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"0\""
      OutValue_1: "PageNumber"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "PageLocator:PageNumber"
      OutValue_1: "_PageNumber"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "FireReloadLocalizationEvent"
    bindings:
      SiteName: "ContextApplication:Site:Domain:DomainName"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "CreateLocalizationContextFromApplication"
    bindings:
      Application: "ContextApplication"
      LocaleInformation: "Locale"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Localization"
      WorkingTemplate: "localization/LocalizationManagement_52"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Localization"
      WorkingTemplate: "localization/LocalizationOverview_52"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewLocalizations_52-Management"
      ValueType: "Dictionary Value"
  - id: "ToString1"
    type: "pipelet"
    ref: "ToString"
    bindings:
      Object1: "_PageNumber"
      String1: "PageNumber"

links:
  - from: "CallNode1"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode4"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "GetPageLocator2"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "KeyMapper0"
    into: "in"
  - from: "DispatchFormAction2"
    via: "error"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "DispatchFormAction2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "GetLocale1"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "GetLocale4"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "GetPageLocator1"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "GetPageLocator1"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "GetPageLocator2"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetPageLocator2"
    via: "next"
    to: "GetPageable2"
    into: "in"
  - from: "GetPageable2"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "GetPageable2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "Jump17"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "KeyMapper0"
    via: "next"
    to: "GetLocale4"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "KeyMapper4"
    via: "next"
    to: "ToString1"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "Pipelet1"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "Start14"
    via: "next"
    to: "DispatchFormAction2"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "ToString1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
