flow: "ViewPromotionNotes"
kind: "view"

entries:
  - id: "StartNode1"
    name: "List"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Add"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode21"
    name: "DispatchGeneral"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "ConfirmDelete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessPromotionNotes-Create"
    bindings:
      Note: "PromotionNoteForm:Note:Value"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessPromotionNotes-ListAll"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessPromotionNotes-Update"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessPromotionNotes-ProcessPaging"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "PromotionNote"
      FormResource: "PromotionNote"
    bindings:
      Form: "PromotionNoteForm"
  - id: "CreateForm2"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "PromotionNote"
      FormResource: "PromotionNote"
    bindings:
      Form: "PromotionNoteForm"
  - id: "CreateForm3"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "PromotionNote"
      FormResource: "PromotionNote"
    bindings:
      Form: "PromotionNoteForm"
  - id: "CreateForm4"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "PromotionNote"
      FormResource: "PromotionNote"
    bindings:
      Form: "PromotionNoteForm"
  - id: "CreateForm5"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "PromotionNote"
      FormResource: "PromotionNote"
    bindings:
      Form: "PromotionNoteForm"
  - id: "CreateForm6"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "PromotionNote"
      FormResource: "PromotionNote"
    bindings:
      Form: "PromotionNoteForm"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPromotionNotes-Add"
      OutValue_1: "ViewPromotionNotes-Update"
      OutValue_2: "ViewPromotionNotes-Edit"
      OutValue_3: "ViewPromotionNotes-Delete"
      OutValue_4: "ViewPromotionNotes-ConfirmDelete"
    bindings:
      Key_0: "create"
      Key_1: "update"
      SelectionKey: "JumpTarget"
      Key_2: "edit"
      Key_3: "delete"
      Key_4: "confirmDelete"
  - id: "DispatchFormAction10"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPromotionReplication-SelectTarget"
      OutValue_1: "ViewPromotion-CopyDialog"
      OutValue_2: "ViewPromotion-Edit"
    bindings:
      Key_0: "selectStagingTarget"
      SelectionKey: "JumpTarget"
      Key_1: "copyDialog"
      Key_2: "confirmDelete"
  - id: "GetPromotionByUUID1"
    type: "pipelet"
    ref: "GetPromotionByUUID"
  - id: "GetPromotionNoteByUUID1"
    type: "pipelet"
    ref: "GetPromotionNoteByUUID"
  - id: "GetPromotionNoteByUUID2"
    type: "pipelet"
    ref: "GetPromotionNoteByUUID"
    bindings:
      PromotionNote: "DeletePromotionNote"
  - id: "GetPromotionNoteByUUID3"
    type: "pipelet"
    ref: "GetPromotionNoteByUUID"
    bindings:
      PromotionNoteUUID: "DeletePromotionNoteUUID"
      PromotionNote: "DeletePromotionNote"
  - id: "GetTargetClusters1"
    type: "pipelet"
    ref: "GetTargetClusters"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "This:Edit"
  - id: "JumpNode5"
    type: "jump"
    ref: "This:List"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/PromotionNotes"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"
  - id: "RemoveORMObject1"
    type: "pipelet"
    ref: "RemoveORMObject"
    bindings:
      ORMObject: "DeletePromotionNote"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewPromotionNotes-List"
      ValueType: "Dictionary Value"
  - id: "SetFormParameterValue1"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      FormParameter: "PromotionNoteForm:Note"
      Value: "PromotionNote:Note"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "PromotionNoteForm"
  - id: "ValidateForm2"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "PromotionNoteForm"

links:
  - from: "JoinNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "GetPromotionByUUID1"
    into: "in"
  - from: "ValidateForm1"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "CreateForm6"
    via: "next"
    to: "GetPromotionNoteByUUID2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CreateForm4"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "CreateForm4"
    via: "next"
    to: "GetPromotionNoteByUUID1"
    into: "in"
  - from: "GetPromotionByUUID1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetPromotionByUUID1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "GetPromotionNoteByUUID2"
    via: "error"
    to: "JoinNode8"
    into: "in2"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "GetPromotionNoteByUUID1"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode11"
    into: "in2"
  - from: "CallNode3"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "GetPromotionNoteByUUID1"
    via: "next"
    to: "SetFormParameterValue1"
    into: "in"
  - from: "SetFormParameterValue1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "CreateForm2"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "CreateForm5"
    via: "next"
    to: "ValidateForm2"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CreateForm5"
    into: "in"
  - from: "ValidateForm2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "ValidateForm2"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "CallNode3"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CreateForm3"
    into: "in"
  - from: "GetPromotionNoteByUUID2"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "CreateForm2"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "StartNode8"
    via: "next"
    to: "GetPromotionNoteByUUID3"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "GetPromotionNoteByUUID3"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "RemoveORMObject1"
    via: "error"
    to: "JoinNode10"
    into: "in2"
  - from: "GetPromotionNoteByUUID3"
    via: "next"
    to: "RemoveORMObject1"
    into: "in"
  - from: "RemoveORMObject1"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode9"
    into: "in2"
  - from: "JoinNode11"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "StartNode21"
    via: "next"
    to: "DispatchFormAction10"
    into: "in"
  - from: "DispatchFormAction10"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "GetTargetClusters1"
    into: "in"
  - from: "GetTargetClusters1"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "GetPromotionByUUID1"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "CreateForm6"
    into: "in"
  - from: "ValidateForm1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CreateForm3"
    via: "next"
    to: "JoinNode3"
    into: "in1"
