flow: "ViewStoreFinder"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "ReloadStates"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Search"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "GetStoreFinderForm"
    mode: "private"
    strict: true
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewStoreFinder-GetStoreFinderForm"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessAddressSearch-ParametricSearch"
    bindings:
      Profile: "CurrentOrganization:Profile"
      Search_City: "StoreFinderForm:City:Value"
      Search_State: "StoreFinderForm:State:Value"
      Search_ZIP: "StoreFinderForm:PostalCode:Value"
      TypeCode: "TypeCode"
      Search_AddressNr: "\"enabled\""
      CountryCode: "StoreFinderForm:CountryCode:Value"
      Addresses: "Stores"
  - id: "CallNode5"
    type: "call"
    ref: "ViewStoreFinder-GetStoreFinderForm"
  - id: "CallNode6"
    type: "call"
    ref: "ViewStoreFinder-GetStoreFinderForm"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "StoreFinder"
      FormResource: "StoreFinder"
    bindings:
      Form: "StoreFinderForm"
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "StoreFinderForm"
        type: "com.intershop.beehive.core.capi.webform.Form"
        guaranteed: true
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewStoreFinder-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode9"
    type: "jump"
    ref: "ViewPage-Start"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "CurrentRequest:PipelineDictionary"
      InValue_3: "\"systempage.storeLocator.pagelet2-systempage.storeLocator\""
      InValue_2: "\"stores/StoreFinder\""
      OutValue_1: "Dictionary"
      OutValue_3: "PageletEntryPointID"
      OutValue_2: "WorkingTemplate"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      PagingPipeline: "ViewStoreFinder-Paging"
      OutValue_0: "ViewStoreFinder-Search"
      OutValue_1: "ViewStoreFinder-ReloadStates"
    bindings:
      Key_0: "search"
      Key_1: "reloadStates"
      SelectionKey: "JumpTarget"
  - id: "UpdatePageSize1"
    type: "pipelet"
    ref: "UpdatePageSize"
    config:
      DefaultPageSize: 0
    bindings:
      PageableIterator: "Stores"
      PageSize: "null"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "StoreFinderForm"
  - id: "ValidateForm3"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "StoreFinderForm"
  - id: "VerifyInteger2"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      LocalizedString: "\"32\""
      IntegerObject: "TypeCode"

links:
  - from: "JoinNode4"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "UpdatePageSize1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "VerifyInteger2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "VerifyInteger2"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode5"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "ValidateForm3"
    into: "in"
  - from: "ValidateForm3"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "ValidateForm3"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "ValidateForm1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "StartNode6"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "JumpNode1"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "ValidateForm1"
    via: "next"
    to: "VerifyInteger2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "JumpNode9"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "UpdatePageSize1"
    into: "in"
