flow: "ViewApplicationList"
kind: "process"

entries:
  - id: "Start2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call7"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call8"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Decision2"
    type: "decision"
    condition: "PageNumber"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      PagingPipeline: "ViewApplicationList-Paging"
    bindings:
      SelectionKey: "JumpTarget"
  - id: "ExecutePageableQuery1"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "application/GetApplicationList"
      DefaultPageSize: 10
    bindings:
      Connection: "null"
      Parameters: "null"
      ParameterValue_01: "null"
      ParameterValue_02: "null"
      ParameterValue_03: "null"
      ParameterValue_04: "null"
      ParameterValue_05: "null"
      Query: "null"
      SearchResult: "Sites"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      RestorePageLocatorDictionary: "False"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Sites"
      PageableID: "PageLocator:PageableID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join3"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Jump10"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Enterprises"
      WorkingTemplate: "organization/ApplicationList.isml"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Sites"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Sites"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewApplicationList-Paging"
      DefaultPageLocatorName: "SiteList"
    bindings:
      Pageable: "Sites"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      Locale: "null"
      LocalizedString: "PageNumber"
      Pattern: "null"

links:
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage1"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "Join8"
    into: "in2"
  - from: "SetPage1"
    via: "next"
    to: "Join3"
    into: "in2"
  - from: "SetPageLocator1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "Join7"
    into: "in2"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "Join7"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "ExecutePageableQuery1"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "Call7"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "Start7"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump10"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "SetPage2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "ExecutePageableQuery1"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join3"
    into: "in3"
  - from: "Call8"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
