flow: "ViewUserDepartmentRoles"
kind: "view"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "RemoveDepartmentRoles"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "ViewDepartmentRolesRow"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "DoConfirmDelete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "ConfirmDelete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "ViewDepartmentRolesRowDel"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Decision1"
    type: "decision"
    condition: "User"
  - id: "DetermineUser1"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "UserUUID"
  - id: "DetermineUser2"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "UserUUID"
  - id: "DetermineUser3"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "UserUUID"
  - id: "DetermineUserProfile1"
    type: "pipelet"
    ref: "DetermineUserProfile"
    bindings:
      CurrentUser: "User"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewUserDepartmentRolesWizard-Start"
      OutValue_1: "ViewUserDepartmentRoles-DoConfirmDelete"
      OutValue_2: "ViewUserDepartmentRoles-RemoveDepartmentRoles"
      OutValue_3: "ViewUserDepartmentRoles-Start"
      OutValue_4: "ViewUserList-List"
    bindings:
      Key_0: "new"
      Key_1: "confirmDelete"
      Key_2: "delete"
      Key_3: "cancel"
      Key_4: "back"
      SelectionKey: "JumpTarget"
  - id: "GetAccessibleDepartments1"
    type: "pipelet"
    ref: "GetAccessibleDepartments"
  - id: "GetAssignedOrganizationRoles1"
    type: "pipelet"
    ref: "GetAssignedOrganizationRoles"
    config:
      Membership: "Direct"
  - id: "GetClipboard1"
    type: "pipelet"
    ref: "GetClipboard"
    config:
      SessionRegistrationID: "selectedRoles"
      SetFormValues: "No"
  - id: "GetDepartment1"
    type: "pipelet"
    ref: "GetDepartment"
    config:
      Source: "PipelineDictionary"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedRole"
    bindings:
      Selection: "PrefixIterator"
  - id: "GetFormSelection2"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedRole"
    bindings:
      Selection: "RoleUUIDs"
  - id: "GetFormSelection3"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "role"
    bindings:
      Selection: "AllRoles"
  - id: "GetOrganizationByUser1"
    type: "pipelet"
    ref: "GetOrganizationByUser"
  - id: "GetOrganizationByUser2"
    type: "pipelet"
    ref: "GetOrganizationByUser"
  - id: "GetOrganizationByUser3"
    type: "pipelet"
    ref: "GetOrganizationByUser"
  - id: "GetRole1"
    type: "pipelet"
    ref: "GetRole"
    bindings:
      Role: "OrganizationRole"
      RoleID: "RoleUUID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewUserDepartmentRoles-Start"
  - id: "Jump4"
    type: "jump"
    ref: "ViewUserDepartmentRoles-ConfirmDelete"
  - id: "Jump7"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "ListDepartmentRoles1"
    type: "pipelet"
    ref: "ListDepartmentRoles"
  - id: "Loop1"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Users"
      WorkingTemplate: "user/UserDepartmentRoles"
  - id: "RemoveClipboard1"
    type: "pipelet"
    ref: "RemoveClipboard"
    config:
      SessionRegistrationID: "selectedRoles"
  - id: "RemoveUserFromOrganizationRole1"
    type: "pipelet"
    ref: "RemoveUserFromOrganizationRole"
  - id: "UpdateClipboard1"
    type: "pipelet"
    ref: "UpdateClipboard"
    config:
      SessionRegistrationID: "selectedRoles"
      StoreFormValues: "No"
    bindings:
      AllObjectUUIDs: "AllRoles"
      SelectedObjectUUIDs: "PrefixIterator"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetRole1"
    into: "in"
  - from: "DetermineUser1"
    via: "next"
    to: "GetOrganizationByUser3"
    into: "in"
  - from: "GetRole1"
    via: "next"
    to: "RemoveUserFromOrganizationRole1"
    into: "in"
  - from: "RemoveUserFromOrganizationRole1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "GetRole1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "RemoveUserFromOrganizationRole1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "Loop1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "DetermineUser3"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Join2"
    into: "in1"
  - from: "DetermineUserProfile1"
    via: "next"
    to: "GetOrganizationByUser1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "DetermineUserProfile1"
    into: "in"
  - from: "DetermineUser3"
    via: "next"
    to: "Join2"
    into: "in3"
  - from: "GetFormSelection1"
    via: "next"
    to: "GetFormSelection3"
    into: "in"
  - from: "GetOrganizationByUser3"
    via: "next"
    to: "GetFormSelection2"
    into: "in"
  - from: "GetFormSelection2"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "UpdateClipboard1"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "GetFormSelection3"
    via: "next"
    to: "UpdateClipboard1"
    into: "in"
  - from: "RemoveClipboard1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Join3"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "GetClipboard1"
    via: "next"
    to: "Join4"
    into: "in3"
  - from: "GetOrganizationByUser1"
    via: "next"
    to: "GetAccessibleDepartments1"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "DetermineUser2"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump7"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Join3"
    into: "in3"
  - from: "Start1"
    via: "next"
    to: "RemoveClipboard1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "Start6"
    via: "next"
    to: "GetClipboard1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "DetermineUser1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "GetAccessibleDepartments1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "DetermineUser2"
    via: "next"
    to: "GetOrganizationByUser2"
    into: "in"
  - from: "GetOrganizationByUser2"
    via: "next"
    to: "GetDepartment1"
    into: "in"
  - from: "GetDepartment1"
    via: "next"
    to: "ListDepartmentRoles1"
    into: "in"
  - from: "ListDepartmentRoles1"
    via: "next"
    to: "GetAssignedOrganizationRoles1"
    into: "in"
  - from: "GetAssignedOrganizationRoles1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
