flow: "ViewChannelLinkImpex"
kind: "view"

entries:
  - id: "Start1"
    name: "DownloadFile"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Monitor"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Status"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "DeleteImpexJobs"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessImpexJob-Delete"
  - id: "Call2"
    type: "call"
    ref: "ProcessJobConfigurationSearch-Search"
  - id: "Call3"
    type: "call"
    ref: "ProcessImpexJob-GetLogContent"
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "Call5"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call6"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call7"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "Decision1"
    type: "decision"
    condition: "JobConfiguration:Status"
  - id: "Decision2"
    type: "decision"
    condition: "ConfirmDeleteImpexJobs"
  - id: "DetermineUnit1"
    type: "pipelet"
    ref: "DetermineUnit"
    bindings:
      Unit: "UnitDomain"
      UnitName: "JobConfiguration:DomainName"
  - id: "GetBinaryFileContent1"
    type: "pipelet"
    ref: "GetBinaryFileContent"
    config:
      UnitDirectory: "IMPEX_DIR"
  - id: "GetJobConfiguration1"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "GetJobConfiguration2"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "GetJobConfiguration3"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "Error-FileNotFound"
  - id: "Jump2"
    type: "jump"
    ref: "Error-Start"
  - id: "Jump3"
    type: "jump"
    ref: "ViewChannelLinkImpex-Status"
  - id: "JumpNode2"
    type: "jump"
    ref: "Error-Start"
  - id: "JumpNode4"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ChannelRepository:Domain"
      OutValue_1: "JobDomain"
      InValue_2: "\"ProcessLinkImpex\""
      OutValue_2: "JobName"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Jobs"
      OutValue_1: "ImpexJobs"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"DetermineUnitError\""
      OutValue_1: "ErrorCode"
  - id: "Loop1"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelLinkImport-SelectCSVFile"
    bindings:
      Key_0: "LinkImportCSV"
      SelectionKey: "JumpTarget"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelLinkImpex-Status"
      OutValue_1: "ViewChannelLinkImpex-DeleteImpexJobs"
      OutValue_2: "ViewChannelLinkImpex-Status"
      OutValue_3: "ViewChannelLinkImpex-Monitor"
      OutValue_4: "ViewChannelLinkImpex-DownloadFile"
      OutValue_5: "ViewChannelLinkImport-SelectFile"
      OutValue_6: "ViewChannelLinks-ListAll"
      OutValue_7: "ViewChannelLinkImportFiles-BrowseDirectory"
      OutValue_9: "ViewChannelURLExport-SelectCatalog"
      OutValue_8: "ViewChannelLinkExportFiles-BrowseDirectory"
    bindings:
      Key_0: "Status"
      Key_1: "DeleteImpexJobs"
      Key_2: "ConfirmDeleteImpexJobs"
      Key_3: "Monitor"
      Key_4: "DownloadFile"
      Key_5: "LinkImport"
      SelectionKey: "JumpTarget"
      Key_6: "LinkExport"
      Key_7: "ImportFiles"
      Key_8: "ExportFiles"
      Key_9: "SelectURLExportCatalog"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "impex/ChannelLinkImpexMonitor"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "impex/ChannelLinkImpexOverview"

links:
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "Start4"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetJobConfiguration3"
    into: "in"
  - from: "GetJobConfiguration3"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Call1"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Call7"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Call2"
    via: "Error"
    to: "Jump2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "GetJobConfiguration2"
    into: "in"
  - from: "GetJobConfiguration2"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Join5"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "GetJobConfiguration3"
    via: "error"
    to: "Join5"
    into: "in3"
  - from: "Join3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join3"
    into: "in3"
  - from: "GetBinaryFileContent1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "next"
    to: "DetermineUnit1"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "error"
    to: "Join2"
    into: "in1"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "GetBinaryFileContent1"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "Join2"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "DetermineUnit1"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "Start1"
    via: "next"
    to: "GetJobConfiguration1"
    into: "in"
  - from: "DetermineUnit1"
    via: "next"
    to: "GetBinaryFileContent1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Call3"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Call3"
    via: "Error"
    to: "KeyMapper3"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Pipelet2"
    via: "error"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "GetJobConfiguration2"
    via: "error"
    to: "JumpNode2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "Call4"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Call6"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "Join6"
    into: "in3"
  - from: "Call5"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Decision2"
    into: "in"
