flow: "ViewChannelPayment"
kind: "view"

entries:
  - id: "StartNode1"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AssignPaymentService1"
    type: "pipelet"
    ref: "AssignPaymentService"
    bindings:
      AssignedDomain: "Repository:RepositoryDomain"
      Domain: "Repository:RepositoryDomain"
      PaymentServiceID: "PaymentServiceID"
  - id: "Call1"
    type: "call"
    ref: "ProcessChannel-Get"
  - id: "Call3"
    type: "call"
    ref: "ProcessChannel-Get"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "CombineIterators1"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Subtract Iterators"
    bindings:
      Iterator1: "AllObjectUUIDs"
      Iterator2: "SelectedObjectUUIDs"
      Iterator: "UnselectedUUIDs"
  - id: "CombineIterators2"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Subtract Iterators"
    bindings:
      Iterator1: "PaymentServices"
      Iterator2: "AssignedPaymentServices"
      Iterator: "NotAssignedPaymentServices"
  - id: "ExecuteCartridgePipelines1"
    type: "pipelet"
    ref: "ExecuteCartridgePipelines"
    config:
      Asynchronous: false
      PipelinePropertyName: "PaymentServiceAssignmentCreationHook"
      ProcessReversely: false
  - id: "ExecuteCartridgePipelines2"
    type: "pipelet"
    ref: "ExecuteCartridgePipelines"
    config:
      Asynchronous: false
      PipelinePropertyName: "PaymentServiceAssignmentDeletionHook"
      ProcessReversely: false
  - id: "ExecuteCartridgePipelines3"
    type: "pipelet"
    ref: "ExecuteCartridgePipelines"
    config:
      Asynchronous: false
      PipelinePropertyName: "PaymentServiceAssignmentValidationHook"
      ProcessReversely: false
  - id: "GetAssignedPaymentServices1"
    type: "pipelet"
    ref: "GetAssignedPaymentServices"
    bindings:
      AssignmentDomain: "CurrentOrganization:OrganizationDomain"
      AssignedPaymentServices: "PaymentServices"
  - id: "GetAssignedPaymentServices2"
    type: "pipelet"
    ref: "GetAssignedPaymentServices"
    bindings:
      AssignmentDomain: "Repository:RepositoryDomain"
      AssignedPaymentServices: "AssignedPaymentServices"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewChannelPayment-ListAll"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Repository:RepositoryDomain"
      OutValue_1: "PaymentServiceAssignmentDomain"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Repository:RepositoryDomain"
      OutValue_1: "PaymentServiceAssignmentDomain"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "LoopNode4"
    type: "loop"
  - id: "LoopNode5"
    type: "loop"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Channels"
      WorkingTemplate: "channel/ChannelPayment"
  - id: "SortIteratorByComparator2"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingAttribute: "ID"
      DefaultSortingOrder: true
    bindings:
      SortedIterator: "PaymentServices"
      Iterator: "PaymentServices"
      SortingAttribute: "null"
      SortingOrder: "null"
  - id: "UnassignPaymentService1"
    type: "pipelet"
    ref: "UnassignPaymentService"
    bindings:
      AssignedDomain: "Repository:RepositoryDomain"
  - id: "UpdateMapping1"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ChannelValidPaymentServices"
      OutMap: "ChannelValidPaymentServices"
  - id: "UpdateMapping3"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ChannelValidPaymentServices"
      Key: "PaymentService:ID"
      Value: "PaymentService"

links:
  - from: "StartNode2"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "ExecuteCartridgePipelines2"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "ExecuteCartridgePipelines1"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "GetAssignedPaymentServices2"
    via: "next"
    to: "SortIteratorByComparator2"
    into: "in"
  - from: "ExecuteCartridgePipelines3"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode4"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "AssignPaymentService1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "UnassignPaymentService1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "AssignPaymentService1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CombineIterators1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "CombineIterators1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "ExecuteCartridgePipelines2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "ExecuteCartridgePipelines3"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "SortIteratorByComparator2"
    via: "next"
    to: "UpdateMapping1"
    into: "in"
  - from: "LoopNode4"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "LoopNode5"
    via: "next"
    to: "CombineIterators2"
    into: "in"
  - from: "UnassignPaymentService1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "KeyMapper1"
    via: "next"
    to: "ExecuteCartridgePipelines2"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "LoopNode4"
    into: "loop"
  - from: "KeyMapper2"
    via: "next"
    to: "ExecuteCartridgePipelines1"
    into: "in"
  - from: "LoopNode4"
    via: "do"
    to: "ExecuteCartridgePipelines3"
    into: "in"
  - from: "LoopNode5"
    via: "do"
    to: "UpdateMapping3"
    into: "in"
  - from: "UpdateMapping3"
    via: "next"
    to: "LoopNode5"
    into: "loop"
  - from: "UpdateMapping1"
    via: "next"
    to: "LoopNode5"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CombineIterators2"
    via: "next"
    to: "LoopNode4"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "GetAssignedPaymentServices1"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "GetAssignedPaymentServices1"
    via: "next"
    to: "GetAssignedPaymentServices2"
    into: "in"
  - from: "ExecuteCartridgePipelines1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
