flow: "ViewABTesting"
kind: "view"

entries:
  - id: "StartNode1"
    name: "CallLogPageletViewEvents"
    mode: "private"
    strict: false
    inputs:
      - key: "TestObjectID"
        type: "java.lang.String"
        required: true
      - key: "ABTestGroupID"
        type: "java.lang.String"
        required: true
  - id: "StartNode2"
    name: "CallLogPageletClickEvents"
    mode: "public"
    strict: false
    inputs:
      - key: "ClickedABTestObjectID"
        type: "java.lang.String"
        required: true
      - key: "ClickedABTestGroupID"
        type: "java.lang.String"
        required: true
      - key: "ClickedNestedABTestClick"
        type: "java.lang.String"
        required: false

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessABTesting-LogViewEvent"
    bindings:
      TestObject: "TestObject"
      ABTestGroup: "ABTestGroup"
  - id: "GetABTestGroupByUUID1"
    type: "pipelet"
    ref: "GetABTestGroupByUUID"
    bindings:
      UUID: "ABTestGroupID"
      ABTestGroup: "ABTestGroup"
  - id: "GetPageletByUUID1"
    type: "pipelet"
    ref: "GetPageletByUUID"
    bindings:
      PageletUUID: "TestObjectID"
      Pagelet: "TestObject"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "LogABTestClickEvents1"
    type: "pipelet"
    ref: "LogABTestClickEvents"
    bindings:
      ABTestGroupID: "ClickedABTestGroupID"
      ABTestObjectID: "ClickedABTestObjectID"
      CurrentABTestGroups: "CurrentSession:Object(\"T_CurrentABTestGroupUUIDs\")"
      CurrentSession: "CurrentSession"
      CurrentUser: "CurrentUser"
      NestedABTestClicks: "ClickedNestedABTestClick"

links:
  - from: "StartNode2"
    via: "next"
    to: "LogABTestClickEvents1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "GetABTestGroupByUUID1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "GetPageletByUUID1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetABTestGroupByUUID1"
    into: "in"
  - from: "GetABTestGroupByUUID1"
    via: "next"
    to: "GetPageletByUUID1"
    into: "in"
  - from: "LogABTestClickEvents1"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "GetPageletByUUID1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
