flow: "ViewPageletExport"
kind: "view"

entries:
  - id: "StartNode1"
    name: "SetFormValues"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode12"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode13"
    name: "SelectPagelets"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode14"
    name: "GetContainerName"
    mode: "private"
    strict: true
    inputs:
      - key: "ContentRepositoryUUID"
        type: "java.lang.String"
        required: true
      - key: "PageletType"
        type: "java.lang.String"
        required: true
  - id: "StartNode15"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode16"
    name: "UpdateClipboard"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode17"
    name: "GetFormValues"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "ExportSelectedPagelets"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "GetObjects"
    mode: "private"
    strict: true
    inputs:
      - key: "PageletType"
        type: "java.lang.String"
        required: true
      - key: "UUIDs"
        type: "java.util.Iterator"
        required: true
  - id: "StartNode4"
    name: "GetPageletEntryPoints"
    mode: "private"
    strict: true
    inputs:
      - key: "UUIDs"
        type: "java.util.Iterator"
        required: true
  - id: "StartNode5"
    name: "ExportAllPagelets"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "GetPagelets"
    mode: "private"
    strict: true
    inputs:
      - key: "UUIDs"
        type: "java.util.Iterator"
        required: true

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "PageletEntryPointVector"
      Iterator: "PageletEntryPoints"
      Object: "PageletEntryPoint"
      Objects: "null"
      OutVector: "PageletEntryPointVector"
  - id: "AddObjectToVector3"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "PageletVector"
      Iterator: "Pagelets"
      Object: "Pagelet"
      Objects: "null"
      OutVector: "PageletVector"
  - id: "CallNode1"
    type: "call"
    ref: "This:UpdateClipboard"
  - id: "CallNode10"
    type: "call"
    ref: "ViewPageletExport-GetPageletEntryPoints"
    bindings:
      PageletEntryPoints: "Objects"
  - id: "CallNode11"
    type: "call"
    ref: "ViewPageletExport-GetObjects"
    bindings:
      UUIDs: "PageletClipboard:ObjectUUIDs"
  - id: "CallNode2"
    type: "call"
    ref: "This:GetContainerName"
  - id: "CallNode29"
    type: "call"
    ref: "ProcessPageletSearch-UpdateClipboard"
    bindings:
      ContentRepository: "ContentRepository"
  - id: "CallNode3"
    type: "call"
    ref: "This:GetContainerName"
  - id: "CallNode4"
    type: "call"
    ref: "This:SetFormValues"
  - id: "CallNode5"
    type: "call"
    ref: "This:UpdateClipboard"
  - id: "CallNode6"
    type: "call"
    ref: "ViewPageletContentExport-ValidateExportFileName"
  - id: "CallNode8"
    type: "call"
    ref: "ViewPageletContentExport-ValidateExportFileName"
  - id: "CallNode9"
    type: "call"
    ref: "ViewPageletExport-GetPagelets"
    bindings:
      Pagelets: "Objects"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "ContentRepositoryUUID"
      String1: "\"@\""
      Concatenated: "ContainerName"
      String2: "PageletType"
  - id: "CreatePageableFromIterator2"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    config:
      Pagesize: 1000000
    bindings:
      Iterator: "Objects"
      Pageable: "Objects"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PageletType"
  - id: "DecisionNode10"
    type: "decision"
    condition: "PageletType"
  - id: "DecisionNode2"
    type: "decision"
    condition: "PageletClipboard:ObjectUUIDsCount"
  - id: "DecisionNode3"
    type: "decision"
    condition: "PageletType"
  - id: "DecisionNode4"
    type: "decision"
    condition: "PageletType"
  - id: "DecisionNode5"
    type: "decision"
    condition: "PageletType"
  - id: "DecisionNode6"
    type: "decision"
    condition: "PageletType"
  - id: "DecisionNode7"
    type: "decision"
    condition: "PageletType"
  - id: "DecisionNode8"
    type: "decision"
    condition: "Objects"
  - id: "DecisionNode9"
    type: "decision"
    condition: "PageletType"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_1: "This:CancelExport"
      PagingPipeline: "ViewPageletExport-SelectPagelets"
      OutValue_2: "This:Previous"
      OutValue_3: "This:ExportSelectedPagelets"
      OutValue_4: "This:ExportAllPagelets"
    bindings:
      SelectionKey: "JumpTarget"
      Key_1: "CancelExport"
      Key_2: "Previous"
      Key_3: "ExportSelectedPagelets"
      Key_4: "ExportAllPagelets"
  - id: "DispatchFormActionByBreadcrumb1"
    type: "pipelet"
    ref: "DispatchFormActionByBreadcrumb"
    config:
      SplitMode: "PipelineAndParameter"
    bindings:
      Key_0: "CancelExport"
      SelectionKey: "JumpTarget"
      OutValue_0: "ApplicationState:LastListView"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode11"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "Objects"
        type: "java.util.Iterator"
        guaranteed: false
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "PageletEntryPoints"
        type: "java.util.Iterator"
        guaranteed: false
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "Pagelets"
        type: "java.util.Iterator"
        guaranteed: false
  - id: "EndNode8"
    type: "end"
    strict: true
    outputs:
      - key: "ContainerName"
        type: "java.lang.String"
        guaranteed: true
  - id: "EndNode9"
    type: "end"
    strict: false
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      PageableID: "ObjectsID"
      Pageable: "Objects"
  - id: "GetPageletByUUID1"
    type: "pipelet"
    ref: "GetPageletByUUID"
    bindings:
      Pagelet: "Pagelet"
      PageletUUID: "UUID"
  - id: "GetPageletEntryPointByUUID2"
    type: "pipelet"
    ref: "GetPageletEntryPointByUUID"
    bindings:
      PageletEntryPoint: "PageletEntryPoint"
      PageletEntryPointUUID: "UUID"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      UUID: "ContentRepositoryUUID"
      Repository: "ContentRepository"
  - id: "GetValuesFromContainer1"
    type: "pipelet"
    ref: "GetValuesFromContainer"
    config:
      OverwriteBehavior: true
    bindings:
      ContainerName: "ContainerName"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode15"
    type: "join"
  - id: "JoinNode16"
    type: "join"
  - id: "JoinNode19"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "This:SelectPagelets"
  - id: "JumpNode2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewPageletContentExport-Export"
  - id: "Loop1"
    type: "loop"
  - id: "Loop3"
    type: "loop"
  - id: "PrepareApplicationView4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "content/pagelet/PageletExport"
      SelectedMenuItem: "PageletImpex"
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewPageletExport-SelectPagelets"
  - id: "SetDictionaryValue7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "PageletSearchStartFlag"
      Value: true
  - id: "SetValuesToContainer1"
    type: "pipelet"
    ref: "SetValuesToContainer"
    bindings:
      DictionaryKeys: "\"PageletClipboard;ExportFileNameNotDefined;ExportFileNameInvalid\""

links:
  - from: "DecisionNode10"
    via: "yes"
    to: "JoinNode15"
    into: "in3"
  - from: "SetDictionaryValue7"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "GetValuesFromContainer1"
    via: "next"
    to: "EndNode9"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode19"
    into: "in3"
  - from: "JoinNode19"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "JoinNode9"
    into: "in2"
  - from: "DispatchFormAction2"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "DecisionNode1"
    via: "no"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "DecisionNode1"
    into: "in"
  - from: "DispatchFormActionByBreadcrumb1"
    via: "error"
    to: "DispatchFormAction2"
    into: "in"
  - from: "CallNode29"
    via: "next"
    to: "EndNode11"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode3"
    into: "in2"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "StartNode16"
    via: "next"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "DecisionNode7"
    into: "in"
  - from: "DecisionNode7"
    via: "yes"
    to: "JoinNode7"
    into: "in3"
  - from: "DispatchFormAction2"
    via: "error"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode12"
    into: "in3"
  - from: "StartNode12"
    via: "next"
    to: "DispatchFormActionByBreadcrumb1"
    into: "in"
  - from: "DispatchFormActionByBreadcrumb1"
    via: "next"
    to: "JoinNode19"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "StartNode15"
    via: "next"
    to: "SetDictionaryValue7"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "JoinNode7"
    into: "in1"
  - from: "StartNode13"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "JoinNode12"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "CallNode11"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "DecisionNode9"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "JoinNode16"
    into: "in2"
  - from: "StartNode17"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "DecisionNode9"
    via: "no"
    to: "DecisionNode10"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "GetValuesFromContainer1"
    into: "in"
  - from: "StartNode14"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "JoinNode16"
    into: "in1"
  - from: "DecisionNode10"
    via: "no"
    to: "DecisionNode6"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "DecisionNode8"
    into: "in"
  - from: "PrepareApplicationView4"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "DecisionNode8"
    via: "yes"
    to: "CreatePageableFromIterator2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "SetValuesToContainer1"
    into: "in"
  - from: "SetValuesToContainer1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "JoinNode11"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "DecisionNode8"
    via: "no"
    to: "JoinNode11"
    into: "in2"
  - from: "CallNode6"
    via: "OK"
    to: "CallNode5"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "JoinNode10"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode9"
    via: "yes"
    to: "JoinNode15"
    into: "in1"
  - from: "JoinNode15"
    via: "next"
    to: "JoinNode10"
    into: "in3"
  - from: "AddObjectToVector1"
    via: "next"
    to: "JoinNode13"
    into: "in1"
  - from: "StartNode5"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "JoinNode13"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "CallNode5"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "CallNode8"
    via: "Error"
    to: "JoinNode4"
    into: "in3"
  - from: "CallNode4"
    via: "next"
    to: "PrepareApplicationView4"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetPageletEntryPointByUUID2"
    into: "in"
  - from: "CallNode6"
    via: "Error"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "CreatePageableFromIterator2"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "GetPageletEntryPointByUUID2"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "CallNode8"
    via: "OK"
    to: "GetPageable1"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "JoinNode6"
    into: "in3"
  - from: "GetPageletEntryPointByUUID2"
    via: "error"
    to: "JoinNode13"
    into: "in1"
  - from: "StartNode4"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "JoinNode12"
    into: "in1"
  - from: "Loop1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "AddObjectToVector3"
    via: "next"
    to: "JoinNode14"
    into: "in1"
  - from: "Loop3"
    via: "do"
    to: "GetPageletByUUID1"
    into: "in"
  - from: "JoinNode14"
    via: "next"
    to: "Loop3"
    into: "loop"
  - from: "GetPageletByUUID1"
    via: "next"
    to: "AddObjectToVector3"
    into: "in"
  - from: "GetPageletByUUID1"
    via: "error"
    to: "JoinNode14"
    into: "in1"
  - from: "Loop3"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "Loop3"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode16"
    via: "next"
    to: "JoinNode8"
    into: "in3"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "CallNode29"
    into: "in"
