flow: "ViewChannelConfigurationParameterSelectCategory"
kind: "view"

entries:
  - id: "Start1"
    name: "Tree"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Expand"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Collapse"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode15"
    name: "SelectCatalog"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode16"
    name: "SetCategory"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewChannelConfigurationParameters-GetConfigurationParameterCtnr"
  - id: "CallNode13"
    type: "call"
    ref: "ViewConfigurationParameters-GetValuesFromSession"
  - id: "CallNode2"
    type: "call"
    ref: "ViewChannelConfigurationParameters-GetConfigurationParameterCtnr"
  - id: "CallNode21"
    type: "call"
    ref: "ProcessCatalogList-GetAllCatalogs"
    bindings:
      SortBy: "\"Name\""
      OwningDomain: "CurrentChannel:RepositoryDomain"
      Locale: "CurrentSession:Locale"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessConfigurationParameterCtnrWebForm-AddFormParameterValue"
    bindings:
      ConfigurationParameterName: "SelectedConfigurationParameterName"
      ParameterValues: "CategoryReferences"
      Site: "CurrentChannel:RepositoryDomain:Site"
  - id: "CallNode4"
    type: "call"
    ref: "ViewChannelConfigurationParameters-GetConfigurationParameterCtnr"
  - id: "CallNode5"
    type: "call"
    ref: "ViewConfigurationParameterSelectCategory-GetCategoryReference"
    bindings:
      CategoryUUID: "SelectedCategoryUUID"
  - id: "CallNode6"
    type: "call"
    ref: "ViewConfigurationParameterSelectCategory-GetCategoryReferences"
    bindings:
      CategoryUUIDs: "SelectedCategoryUUIDs"
  - id: "CallNode8"
    type: "call"
    ref: "ViewChannelConfigurationParameters-GetConfigurationParameterCtnr"
  - id: "CallNode9"
    type: "call"
    ref: "ViewChannelConfigurationParameters-GetConfigurationParameterCtnr"
  - id: "CheckForEmptyString2"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "SelectedCategoryUUID"
  - id: "DecisionNode1"
    type: "decision"
    condition: "SelectedConfigurationParameterDefinition:Multiple"
  - id: "DecisionNode2"
    type: "decision"
    condition: "SelectedCategoryUUIDs"
  - id: "DecisionNode3"
    type: "decision"
    condition: "SelectedTab"
  - id: "DecisionNode6"
    type: "decision"
    condition: "CatalogUUID"
  - id: "DetermineCatalogCategoriesPath1"
    type: "pipelet"
    ref: "DetermineCatalogCategoriesPath"
    bindings:
      CatalogCategoryID: "null"
      Category: "Catalog:Root"
  - id: "DetermineCatalogCategoriesPath3"
    type: "pipelet"
    ref: "DetermineCatalogCategoriesPath"
    bindings:
      CatalogCategoryID: "null"
      Category: "Catalog:Root"
  - id: "DetermineCatalogCategoriesPath4"
    type: "pipelet"
    ref: "DetermineCatalogCategoriesPath"
    bindings:
      CatalogCategoryID: "null"
      Category: "Catalog:Root"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "This:SelectCatalog"
      OutValue_1: "This:Tree"
      OutValue_2: "This:SetCategory"
      OutValue_3: "ViewChannelConfigurationParameters-Edit"
      OutValue_4: "ViewChannelConfigurationParameterSelectCategory-SelectCatalog"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "SelectCatalog"
      Key_1: "SelectCategory"
      Key_2: "SetCategory"
      Key_3: "CancelSelection"
      Key_4: "StartCategorySelection"
  - id: "ExchangeSessionObject1"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      SaveObject: "null"
      SessionObjectName: "null"
  - id: "ExchangeSessionObject2"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      SaveObject: "null"
      SessionObjectName: "null"
  - id: "ExchangeSessionObject3"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      SaveObject: "ExpandedCategoriesMap"
      SessionObjectName: "null"
  - id: "ExchangeSessionObject4"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      LoadObject: "ExpandedCategoriesMap"
  - id: "ExchangeSessionObject6"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      LoadObject: "ExpandedCategoriesMap"
  - id: "GetCatalogByUUID1"
    type: "pipelet"
    ref: "GetCatalogByUUID"
  - id: "GetCatalogByUUID2"
    type: "pipelet"
    ref: "GetCatalogByUUID"
  - id: "GetCatalogByUUID3"
    type: "pipelet"
    ref: "GetCatalogByUUID"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    bindings:
      ParameterName: "\"SelectedCategoryUUID\""
      Selection: "SelectedCategoryUUIDs"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd4"
    type: "interaction"
  - id: "InteractionEnd5"
    type: "interaction"
  - id: "InteractionEnd7"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump15"
    type: "jump"
    ref: "This:SelectCatalog"
  - id: "Jump3"
    type: "jump"
    ref: "This:SelectCatalog"
  - id: "Jump4"
    type: "jump"
    ref: "This:SelectCatalog"
  - id: "Jump6"
    type: "jump"
    ref: "This:SelectCatalog"
  - id: "JumpNode1"
    type: "jump"
    ref: "This:Expand"
  - id: "JumpNode6"
    type: "jump"
    ref: "This:Expand"
  - id: "JumpNode7"
    type: "jump"
    ref: "ViewChannelConfigurationParameters-Edit"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CategoryReference"
      OutValue_1: "CategoryReferences"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelCatalogs"
      WorkingTemplate: "content/ChannelConfigurationParameterSelectCatalog.isml"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelCatalogs"
      WorkingTemplate: "content/ChannelConfigurationParameterSelectCategory"
  - id: "PrepareApplicationView4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelCatalogs"
      WorkingTemplate: "content/ChannelConfigurationParameterSelectCategory.isml"
  - id: "PrepareApplicationView5"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelCatalogs"
      WorkingTemplate: "content/ChannelConfigurationParameterSelectCategory"
  - id: "PrepareApplicationView7"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ContentOverview"
      WorkingTemplate: "content/ChannelConfigurationParameterSelectCatalog.isml"
  - id: "UpdateMapping1"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      Key: "CatalogUUID"
      Value: "CatalogUUID"
      InMap: "null"
      OutMap: "ExpandedCategoriesMap"
  - id: "UpdateMapping2"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Remove"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "CategoryUUID"
      Value: "CategoryUUID"
      OutMap: "ExpandedCategoriesMap"
  - id: "UpdateMapping4"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "CategoryUUID"
      Value: "CategoryUUID"
      OutMap: "ExpandedCategoriesMap"

links:
  - from: "CallNode4"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode21"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "CheckForEmptyString2"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "PrepareApplicationView7"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetFormSelection1"
    into: "in"
  - from: "GetCatalogByUUID2"
    via: "error"
    to: "Jump4"
    into: "in"
  - from: "GetCatalogByUUID2"
    via: "next"
    to: "DetermineCatalogCategoriesPath3"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "ExchangeSessionObject1"
    into: "in"
  - from: "CheckForEmptyString2"
    via: "error"
    to: "JumpNode6"
    into: "in"
  - from: "StartNode16"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "ExchangeSessionObject4"
    via: "next"
    to: "UpdateMapping2"
    into: "in"
  - from: "ExchangeSessionObject6"
    via: "next"
    to: "UpdateMapping4"
    into: "in"
  - from: "ExchangeSessionObject1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode6"
    via: "yes"
    to: "GetCatalogByUUID1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "CheckForEmptyString2"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "StartNode15"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "UpdateMapping1"
    via: "next"
    to: "ExchangeSessionObject3"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "PrepareApplicationView7"
    via: "next"
    to: "InteractionEnd7"
    into: "in"
  - from: "DetermineCatalogCategoriesPath3"
    via: "next"
    to: "ExchangeSessionObject6"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JumpNode7"
    into: "in"
  - from: "PrepareApplicationView4"
    via: "next"
    to: "InteractionEnd5"
    into: "in"
  - from: "GetCatalogByUUID1"
    via: "next"
    to: "DetermineCatalogCategoriesPath4"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "GetCatalogByUUID3"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "ExchangeSessionObject2"
    via: "next"
    to: "UpdateMapping1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "GetCatalogByUUID1"
    via: "error"
    to: "Jump6"
    into: "in"
  - from: "UpdateMapping2"
    via: "next"
    to: "PrepareApplicationView5"
    into: "in"
  - from: "GetCatalogByUUID3"
    via: "next"
    to: "DetermineCatalogCategoriesPath1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "GetCatalogByUUID2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "GetCatalogByUUID3"
    via: "error"
    to: "Jump15"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "CallNode21"
    into: "in"
  - from: "ExchangeSessionObject3"
    via: "next"
    to: "PrepareApplicationView4"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "DetermineCatalogCategoriesPath4"
    via: "next"
    to: "ExchangeSessionObject2"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd4"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JumpNode1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "Jump3"
    into: "in"
  - from: "DetermineCatalogCategoriesPath1"
    via: "next"
    to: "ExchangeSessionObject4"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "CallNode6"
    into: "in"
  - from: "UpdateMapping4"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "PrepareApplicationView5"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
