flow: "ViewSellerOrder"
kind: "view"

entries:
  - id: "Start1"
    name: "ShowGiftcards"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start11"
    name: "ShowLineItemDelivery"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start17"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "ShowPromotions"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "ShowLineItemDetail"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "ShowBundledItem"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "ShowHistory"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "FindByNumber"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "ConcatenateStrings3"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "ViewSellerOrder_"
      DefaultString2: "-"
    bindings:
      String1: "Repository:TypeCode"
      Concatenated: "JumpTarget"
      String3: "CurrentStartNodeName"
  - id: "CreateProductIdentifierLookupHelper4"
    type: "pipelet"
    ref: "CreateProductIdentifierLookupHelper"
    config:
      DefaultFactoryName: "com.intershop.beehive.bts.internal.orderprocess.BundledProductLineItemPO"
      LookupType: "FactoryLookup"
    bindings:
      FactoryName: "not used"
  - id: "DetermineOrderByID2"
    type: "pipelet"
    ref: "DetermineOrderByID"
    config:
      CurrentUserOnly: false
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_7: "ViewSellerOrder-ShowBundledItem"
      OutValue_8: "ViewSellerOrder-ShowLineItemDetail"
    bindings:
      SelectionKey: "JumpTarget"
      Key_7: "backBundledItem"
      Key_8: "backItem"
  - id: "GetBundledProductLineItemByUUID1"
    type: "pipelet"
    ref: "GetBundledProductLineItemByUUID"
    bindings:
      BundledProductLineItem: "LineItem"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      UUID: "ChannelID1"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump11"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump7"
    type: "jump"
    ref: "ViewSellerOrder-FindByNumber"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewOrderList-OrderSearch"
  - id: "JumpNode2"
    type: "jump"
  - id: "PrepareApplicationView4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "PurchaseOrderList"
      WorkingTemplate: "order/LineItemBundledItem"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewOrderList-OrderSearch"

links:
  - from: "StartNode2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "CreateProductIdentifierLookupHelper4"
    via: "next"
    to: "PrepareApplicationView4"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode6"
    into: "in3"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "Start17"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Start11"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "DetermineOrderByID2"
    via: "next"
    to: "GetBundledProductLineItemByUUID1"
    into: "in"
  - from: "ConcatenateStrings3"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "error"
    to: "JumpNode1"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "ConcatenateStrings3"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump11"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Start2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DetermineOrderByID2"
    via: "error"
    to: "Jump7"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "Start5"
    via: "next"
    to: "DetermineOrderByID2"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "PrepareApplicationView4"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "GetBundledProductLineItemByUUID1"
    via: "next"
    to: "CreateProductIdentifierLookupHelper4"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
