flow: "ViewViewContextAssignments"
kind: "view"

entries:
  - id: "Start6"
    name: "UpdateClipboard"
    mode: "private"
    strict: true
    inputs:
      - key: "SelectedPageletEntryPointUUID"
        type: "java.lang.String[]"
        required: false
      - key: "AllPageletEntryPointUUIDs"
        type: "java.lang.String[]"
        required: false
      - key: "ViewContextUUID"
        type: "java.lang.String"
        required: true
      - key: "ContextType"
        type: "java.lang.String"
        required: true
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode11"
    name: "ConfirmDelete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "GetViewContextAssignmentsClipboardName"
    mode: "private"
    strict: true
    inputs:
      - key: "ViewContextUUID"
        type: "java.lang.String"
        required: true
      - key: "ContextType"
        type: "java.lang.String"
        required: true
  - id: "StartNode3"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "TemplateCallback"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Initialize"
    mode: "private"
    strict: true
    inputs:
      - key: "ViewContextUUID"
        type: "java.lang.String"
        required: true
      - key: "ContextType"
        type: "java.lang.String"
        required: true
  - id: "StartNode9"
    name: "GetViewContextAssignmentsContainerName"
    mode: "private"
    strict: true
    inputs:
      - key: "ViewContextUUID"
        type: "java.lang.String"
        required: true
      - key: "ContextType"
        type: "java.lang.String"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewViewContextAssignments-UpdateClipboard"
  - id: "CallNode10"
    type: "call"
    ref: "ViewViewContextAssignments-GetViewContextAssignmentsContainerName"
    bindings:
      ViewContextUUID: "ViewContext:UUID"
  - id: "CallNode11"
    type: "call"
    ref: "ViewViewContextAssignments-GetViewContextAssignmentsClipboardName"
  - id: "CallNode12"
    type: "call"
    ref: "ViewViewContextAssignments-GetViewContextAssignmentsClipboardName"
    bindings:
      ViewContextUUID: "ViewContext:UUID"
  - id: "CallNode13"
    type: "call"
    ref: "ViewViewContextAssignments-GetViewContextAssignmentsContainerName"
  - id: "CallNode2"
    type: "call"
    ref: "ViewViewContextAssignments-Initialize"
  - id: "CallNode3"
    type: "call"
    ref: "ViewViewContext-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessPageletEntryPoint-DeletePageletEntryPoint"
    bindings:
      Domain: "ContentRepository:RepositoryDomain"
      Site: "ContentRepository:RepositoryDomain:Site"
  - id: "CallNode5"
    type: "call"
    ref: "ViewViewContextAssignments-GetViewContextAssignmentsContainerName"
  - id: "CallNode6"
    type: "call"
    ref: "ViewViewContextAssignments-Initialize"
  - id: "CallNode7"
    type: "call"
    ref: "ViewViewContext-Prefix"
  - id: "CallNode8"
    type: "call"
    ref: "ViewViewContextAssignments-GetViewContextAssignmentsClipboardName"
  - id: "CallNode9"
    type: "call"
    ref: "ViewViewContextAssignments-GetViewContextAssignmentsClipboardName"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "ViewContextAssignmentsClipboard"
    bindings:
      String1: "\"_\""
      String0: "\"ViewContextAssignmentsClipboard\""
      String2: "ViewContextUUID"
      String3: "\"_\""
      String4: "ContextType"
      Concatenated: "ViewContextAssignmentsClipboardName"
  - id: "ConcatenateStrings2"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "ViewContextAssignmentsContainer"
    bindings:
      String1: "\"_\""
      String0: "\"ViewContextAssignmentsContainer\""
      String2: "ViewContextUUID"
      String3: "\"_\""
      String4: "ContextType"
      Concatenated: "ViewContextAssignmentsContainerName"
  - id: "DecisionNode3"
    type: "decision"
    condition: "PageletEntryPoint:DomainID"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewViewContextAssignments-ConfirmDelete"
      OutValue_2: "ViewViewContext-View"
      OutValue_1: "ViewViewContextAssignments-Delete"
    bindings:
      Key_0: "confirmDelete"
      Key_1: "delete"
      Key_2: "cancel"
      SelectionKey: "JumpTarget"
  - id: "End2"
    type: "end"
    strict: true
    outputs:
      - key: "SelectedPageletEntryPointsUUIDIterator"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "PageletEntryPointsUUIDIterator"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "PageletEntryPointClipboard"
        type: "com.intershop.component.foundation.capi.clipboard.Clipboard"
        guaranteed: false
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "ViewContextAssignmentsClipboardName"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: true
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "ViewContextAssignmentsContainerName"
        type: "java.lang.String"
        guaranteed: false
  - id: "GetClipboard1"
    type: "pipelet"
    ref: "GetClipboard"
    config:
      SetFormValues: "No"
      SessionRegistrationID: "PageletEntryPointClipboard"
    bindings:
      SessionRegistrationID: "ViewContextAssignmentsClipboardName"
      UUIDIterator: "PageletEntryPointUUIDs"
  - id: "GetClipboard2"
    type: "pipelet"
    ref: "GetClipboard"
    config:
      SetFormValues: "No"
      SessionRegistrationID: "PageletEntryPointClipboard"
    bindings:
      SessionRegistrationID: "ViewContextAssignmentsClipboardName"
      UUIDIterator: "PageletEntryPointUUIDs"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedPageletEntryPointUUID"
    bindings:
      Selection: "SelectedPageletEntryPointsUUIDIterator"
  - id: "GetFormSelection3"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "AllPageletEntryPointUUIDs"
    bindings:
      Selection: "PageletEntryPointsUUIDIterator"
  - id: "GetPageletEntryPointByUUID1"
    type: "pipelet"
    ref: "GetPageletEntryPointByUUID"
  - id: "GetValuesFromContainer1"
    type: "pipelet"
    ref: "GetValuesFromContainer"
    config:
      OverwriteBehavior: true
    bindings:
      ContainerName: "ViewContextAssignmentsContainerName"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewViewContext-InternalView"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewViewContext-InternalView"
  - id: "JumpNode5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "LoopNode1"
    type: "loop"
  - id: "RemoveClipboard1"
    type: "pipelet"
    ref: "RemoveClipboard"
    config:
      SessionRegistrationID: "PageletEntryPointClipboard"
  - id: "RemoveDictionaryValue2"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "PageletEntryPoint"
  - id: "RemoveValuesContainer2"
    type: "pipelet"
    ref: "RemoveValuesContainer"
    bindings:
      ContainerName: "ViewContextAssignmentsContainerName"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "SelectedTab"
      Value: "Assignments"
  - id: "SetValuesToContainer1"
    type: "pipelet"
    ref: "SetValuesToContainer"
    bindings:
      ContainerName: "ViewContextAssignmentsContainerName"
  - id: "UpdateClipboard1"
    type: "pipelet"
    ref: "UpdateClipboard"
    config:
      StoreFormValues: "No"
      SessionRegistrationID: "PageletEntryPointClipboard"
    bindings:
      AllObjectUUIDs: "PageletEntryPointsUUIDIterator"
      SelectedObjectUUIDs: "SelectedPageletEntryPointsUUIDIterator"
      SessionRegistrationID: "ViewContextAssignmentsClipboardName"
      Clipboard: "PageletEntryPointClipboard"

links:
  - from: "CallNode10"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "RemoveValuesContainer2"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "GetValuesFromContainer1"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "RemoveDictionaryValue2"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "SetValuesToContainer1"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "UpdateClipboard1"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "GetClipboard1"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "ConcatenateStrings2"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode3"
    via: "yes"
    to: "CallNode4"
    into: "in"
  - from: "DispatchFormAction2"
    via: "next"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "GetClipboard1"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "GetClipboard2"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "GetFormSelection3"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "GetFormSelection3"
    into: "in"
  - from: "GetPageletEntryPointByUUID1"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "GetPageletEntryPointByUUID1"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "GetValuesFromContainer1"
    via: "error"
    to: "EndNode3"
    into: "in"
  - from: "GetValuesFromContainer1"
    via: "next"
    to: "GetClipboard2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "LoopNode1"
    via: "do"
    to: "GetPageletEntryPointByUUID1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "RemoveClipboard1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "RemoveDictionaryValue2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "RemoveValuesContainer2"
    via: "next"
    to: "RemoveClipboard1"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "SetValuesToContainer1"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "StartNode11"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DispatchFormAction2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "ConcatenateStrings2"
    into: "in"
  - from: "UpdateClipboard1"
    via: "next"
    to: "End2"
    into: "in"
