flow: "ViewPromotionRebate"
kind: "view"

entries:
  - id: "StartNode1"
    name: "DeleteRebate"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "MoveUpRebate"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "MoveDownRebate"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "GetPromotionAndRebate"
    mode: "private"
    strict: true
    inputs:
      - key: "PromotionUUID"
        type: "java.lang.String"
        required: false
      - key: "RebateID"
        type: "java.lang.String"
        required: false
  - id: "StartNode6"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "CreateRebate"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "CopyRebate"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "This:GetPromotionAndRebate"
  - id: "CallNode10"
    type: "call"
    ref: "This:GetPromotionAndRebate"
    bindings:
      Rebate: "SourceRebate"
  - id: "CallNode2"
    type: "call"
    ref: "This:GetPromotionAndRebate"
    bindings:
      Rebate: "Rebate"
  - id: "CallNode3"
    type: "call"
    ref: "This:GetPromotionAndRebate"
    bindings:
      Rebate: "Rebate"
  - id: "CallNode9"
    type: "call"
    ref: "This:GetPromotionAndRebate"
    bindings:
      Rebate: "SourceRebate"
  - id: "CreateRebate1"
    type: "pipelet"
    ref: "CreateRebate"
    bindings:
      Domain: "Promotion:Domain"
  - id: "CreateRebate2"
    type: "pipelet"
    ref: "CreateRebate"
    config:
      CopyRebate: true
    bindings:
      Domain: "Promotion:Domain"
  - id: "DecisionNode3"
    type: "decision"
    condition: "RebateID"
  - id: "DispatchFormAction5"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPromotionRebate-CopyRebate"
      OutValue_1: "ViewPromotionRebate-CreateRebate"
      OutValue_2: "ViewPromotionRebate-DeleteRebate"
      OutValue_3: "ViewPromotionRebate-MoveUpRebate"
      OutValue_4: "ViewPromotionRebate-MoveDownRebate"
    bindings:
      Key_0: "copyRebate"
      Key_1: "createRebate"
      Key_2: "deleteRebate"
      SelectionKey: "JumpTarget"
      Key_3: "moveUpRebate"
      Key_4: "moveDownRebate"
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "Promotion"
        type: "com.intershop.component.marketing.capi.rebate.Promotion"
        guaranteed: false
      - key: "Rebate"
        type: "com.intershop.component.marketing.capi.rebate.Rebate"
        guaranteed: false
  - id: "GetFirstElementOfIterator1"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      Iterator: "Promotion:Rebates"
      FirstElement: "Rebate"
  - id: "GetPromotionByUUID1"
    type: "pipelet"
    ref: "GetPromotionByUUID"
  - id: "GetRebateByUUID2"
    type: "pipelet"
    ref: "GetRebateByUUID"
    bindings:
      RebateUUID: "RebateID"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewPromotionDiscountRules-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewPromotionDiscountRules-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode5"
    type: "jump"
    ref: "ViewPromotionDiscountRules-Start"
  - id: "JumpNode6"
    type: "jump"
    ref: "ViewPromotionDiscountRules-Start"
  - id: "JumpNode7"
    type: "jump"
    ref: "ViewPromotionDiscountRules-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Rebate:Promotion"
      OutValue_1: "Promotion"
  - id: "MoveRebate1"
    type: "pipelet"
    ref: "MoveRebate"
    config:
      Direction: "Up"
  - id: "MoveRebate2"
    type: "pipelet"
    ref: "MoveRebate"
    config:
      Direction: "Down"
  - id: "RemoveRebate1"
    type: "pipelet"
    ref: "RemoveRebate"
  - id: "SetDictionaryValue5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewPromotionDiscountRules-Start"
      ValueType: "Dictionary Value"

links:
  - from: "CreateRebate2"
    via: "error"
    to: "JumpNode6"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "DispatchFormAction5"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "GetRebateByUUID2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "GetPromotionByUUID1"
    via: "next"
    to: "GetFirstElementOfIterator1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "GetFirstElementOfIterator1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "GetPromotionByUUID1"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "StartNode5"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "GetRebateByUUID2"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "StartNode8"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode3"
    via: "yes"
    to: "GetRebateByUUID2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "GetPromotionByUUID1"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode1"
    into: "in1"
  - from: "GetFirstElementOfIterator1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "RemoveRebate1"
    into: "in"
  - from: "RemoveRebate1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "RemoveRebate1"
    via: "error"
    to: "JumpNode1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "MoveRebate1"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "CreateRebate2"
    into: "in"
  - from: "MoveRebate1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "MoveRebate2"
    into: "in"
  - from: "MoveRebate2"
    via: "next"
    to: "JumpNode7"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "DispatchFormAction5"
    via: "error"
    to: "SetDictionaryValue5"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "SetDictionaryValue5"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "CreateRebate1"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "CreateRebate2"
    via: "next"
    to: "JumpNode6"
    into: "in"
  - from: "CreateRebate1"
    via: "error"
    to: "JumpNode5"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "CreateRebate1"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "DispatchFormAction5"
    into: "in"
