flow: "ViewPagelet_comp_navigation"
kind: "view"

entries:
  - id: "StartNode1"
    name: "SimpleDropNav"
    mode: "private"
    strict: true
    inputs:
      - key: "PageletConfigurationParameters"
        type: "java.util.Map"
        required: true
  - id: "StartNode2"
    name: "DrillDown"
    mode: "private"
    strict: true
    inputs:
      - key: "CategoryBO"
        type: "com.intershop.component.catalog.capi.CatalogCategoryBO"
        required: true
  - id: "StartNode3"
    name: "SimpleNavigationBar"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode4"
    name: "AdvancedDropNav"
    mode: "private"
    strict: true
    inputs:
      - key: "PageletConfigurationParameters"
        type: "java.util.Map"
        required: true
  - id: "StartNode5"
    name: "MainNavigationCategoryList"
    mode: "private"
    strict: true
    inputs:
      - key: "CategoryBO"
        type: "com.intershop.component.catalog.capi.CatalogCategoryBO"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessChannelCatalog-GetSortedStandardAndSharedCatalogs"
    bindings:
      CatalogDomain: "Repository:Domain"
      StandardCatalogBOs: "RootCategoryBOs"
  - id: "CallNode2"
    type: "call"
    ref: "DetermineRepositories-Channel"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "CurrentOrganization"
        type: "com.intershop.component.organization.capi.Organization"
        guaranteed: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "AuctionCatalogs"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "CurrentOrganization"
        type: "com.intershop.component.organization.capi.Organization"
        guaranteed: true
      - key: "RootCategoryBOs"
        type: "java.util.Collection"
        guaranteed: false
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "CurrentOrganization"
        type: "com.intershop.component.organization.capi.Organization"
        guaranteed: false
      - key: "CategoryBO"
        type: "com.intershop.component.catalog.capi.CatalogCategoryBO"
        guaranteed: true
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "CurrentOrganization"
        type: "com.intershop.component.organization.capi.Organization"
        guaranteed: true
      - key: "CategoryBO"
        type: "com.intershop.component.catalog.capi.CatalogCategoryBO"
        guaranteed: true
  - id: "EndNode6"
    type: "end"
    strict: true
    outputs:
      - key: "CurrentOrganization"
        type: "com.intershop.component.organization.capi.Organization"
        guaranteed: true
      - key: "CategoryBO"
        type: "com.intershop.component.catalog.capi.CatalogCategoryBO"
        guaranteed: true
  - id: "GetValuesFromRequest1"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "Application"
    bindings:
      Key: "\"CurrentOrganization\""
      Namespace: "null"
  - id: "GetValuesFromRequest2"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "Application"
    bindings:
      Key: "\"CurrentOrganization\""
      Namespace: "null"
  - id: "GetValuesFromRequest3"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "Application"
    bindings:
      Key: "\"CurrentOrganization\""
      Namespace: "null"
  - id: "GetValuesFromRequest4"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "Application"
    bindings:
      Key: "\"CurrentOrganization\""
      Namespace: "null"
  - id: "GetValuesFromRequest5"
    type: "pipelet"
    ref: "GetValuesFromRequest"
    config:
      Namespace: "Application"
    bindings:
      Key: "\"CurrentOrganization\""
      Namespace: "null"
  - id: "JoinNode1"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "PageletConfigurationParameters:category"
      OutValue_1: "CategoryBO"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "PageletConfigurationParameters:category"
      OutValue_1: "CategoryBO"

links:
  - from: "GetValuesFromRequest2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "GetValuesFromRequest1"
    via: "error"
    to: "CallNode2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetValuesFromRequest2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetValuesFromRequest3"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "GetValuesFromRequest5"
    into: "in"
  - from: "GetValuesFromRequest5"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "GetValuesFromRequest4"
    via: "error"
    to: "KeyMapper1"
    into: "in"
  - from: "GetValuesFromRequest3"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "GetValuesFromRequest4"
    into: "in"
  - from: "GetValuesFromRequest5"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "GetValuesFromRequest2"
    via: "error"
    to: "KeyMapper2"
    into: "in"
  - from: "GetValuesFromRequest3"
    via: "error"
    to: "EndNode1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "GetValuesFromRequest4"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetValuesFromRequest1"
    into: "in"
  - from: "GetValuesFromRequest1"
    via: "next"
    to: "CallNode2"
    into: "in"
