flow: "ViewCatalogChannelList"
kind: "view"

entries:
  - id: "Start1"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Refresh"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Prefix"
    mode: "private"
    strict: true
    inputs:
      - key: "CatalogUUID"
        type: "java.lang.String"
        required: true

steps:
  - id: "Call3"
    type: "call"
    ref: "This:Prefix"
  - id: "Call5"
    type: "call"
    ref: "This:Prefix"
  - id: "Call6"
    type: "call"
    ref: "ProcessCatalogChannel-RemoveClipboard"
  - id: "Call7"
    type: "call"
    ref: "ProcessCatalogChannel-UpdateClipboard"
  - id: "Call8"
    type: "call"
    ref: "ProcessCatalogChannel-Sort"
  - id: "End1"
    type: "end"
    strict: true
    outputs:
      - key: "Catalog"
        type: "com.intershop.component.mvc.capi.catalog.Catalog"
        guaranteed: true
  - id: "GetCatalogByUUID1"
    type: "pipelet"
    ref: "GetCatalogByUUID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join3"
    type: "join"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "catalog/GetChannelsBySharedCatalog"
      ParameterName_01: "Catalog"
      Datasource: "default"
      DefaultPageSize: 100
    bindings:
      ParameterValue_01: "Catalog"
      SearchResult: "AssignedChannels"
      PageSize: "null"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Catalogs"
      WorkingTemplate: "catalog/CatalogChannelList.isml"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Join3"
    into: "in2"
  - from: "Pipelet2"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "GetCatalogByUUID1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "GetCatalogByUUID1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Join3"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Call7"
    into: "in"
