flow: "ViewChannelLinkExport"
kind: "view"

entries:
  - id: "Start1"
    name: "GroupStart"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start10"
    name: "FindLinksByGroup"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "LinkStart"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "LinkConfiguration"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "GroupConfiguration"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "GetShortLinkIteratorByLinkList"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "GetShortLinkIteratorByGroupList"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "ShortLinkVector"
      Object: "ShortLink"
      Iterator: "ShortLinks"
      OutVector: "ShortLinkVector"
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "ShortLinkVector"
      Object: "ShortLink"
      Iterator: "ShortLinks"
      OutVector: "ShortLinkVector"
  - id: "AddObjectToVector3"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Object: "null"
      Objects: "null"
      InVector: "null"
      Iterator: "ShortLinks"
      OutVector: "null"
  - id: "Call1"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "Call10"
    type: "call"
    ref: "ViewChannelLinkExport-Prefix"
  - id: "Call11"
    type: "call"
    ref: "ViewChannelLinkExport-GetShortLinkIteratorByGroupList"
  - id: "Call2"
    type: "call"
    ref: "ViewChannelLinkExport-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ViewChannelLinkExport-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ViewChannelLinkExport-GetShortLinkIteratorByLinkList"
  - id: "Call5"
    type: "call"
    ref: "ProcessImpexJob-Create"
  - id: "Call7"
    type: "call"
    ref: "ViewChannelLinkExport-Prefix"
  - id: "Call8"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "Call9"
    type: "call"
    ref: "ViewChannelLinkExport-FindLinksByGroup"
  - id: "CreateDirectory1"
    type: "pipelet"
    ref: "CreateDirectory"
    config:
      DefaultDirectoryName: "shortlink"
      DefaultDirectoryPath: "export"
      UnitDirectory: "IMPEX_DIR"
    bindings:
      UnitDomain: "Channel:Domain"
  - id: "CreateDirectory2"
    type: "pipelet"
    ref: "CreateDirectory"
    config:
      DefaultDirectoryName: "shortlink"
      DefaultDirectoryPath: "export"
      UnitDirectory: "IMPEX_DIR"
    bindings:
      UnitDomain: "Channel:Domain"
  - id: "CreatePageableFromIterator1"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    config:
      Pagesize: 0
      PageableName: "ShortLinkExportPageable"
    bindings:
      Iterator: "ShortLinks"
      Pageable: "ShortLinksPageable"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "ExportFile"
      param.1.required: true
      param.1.rule: "^[^.\\\\/:*?<>|\\s]([^\\\\/:*?<>|\\s]*[^.\\\\/:*?<>|\\s])?$"
      webform-id: "LinkGroupExportForm"
    bindings:
      WebForm: "LinkGroupExportForm"
  - id: "CreateWebForm2"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "ExportFile"
      param.1.required: true
      param.1.rule: "^[^.\\\\/:*?<>|\\s]([^\\\\/:*?<>|\\s]*[^.\\\\/:*?<>|\\s])?$"
      webform-id: "ShortLinkExportForm"
    bindings:
      WebForm: "ShortLinkExportForm"
  - id: "DecisionNode1"
    type: "decision"
    condition: "XMLExport"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ShortLinks"
  - id: "End10"
    type: "end"
    strict: false
  - id: "End11"
    type: "end"
    strict: false
  - id: "End12"
    type: "end"
    strict: false
  - id: "End7"
    type: "end"
    strict: false
  - id: "ExecuteObjectsQuery2"
    type: "pipelet"
    ref: "ExecuteObjectsQuery"
    config:
      QueryName: "link/GetShortLinks"
      ParameterName_01: "GroupID"
      Datasource: "current ORM connection"
      ParameterName_05: "DomainID"
    bindings:
      ParameterValue_01: "LinkGroup:UUID"
      ParameterValue_05: "ChannelRepository:Domain:Site:DomainID"
      SearchResult: "ShortLinksByGroup"
  - id: "GetCurrentDate2"
    type: "pipelet"
    ref: "GetCurrentDate"
  - id: "GetLinkGroupByUUID1"
    type: "pipelet"
    ref: "GetLinkGroupByUUID"
  - id: "GetShortLinkByUUID1"
    type: "pipelet"
    ref: "GetShortLinkByUUID"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "ShortLinkExportForm"
    bindings:
      WebForm: "ShortLinkExportForm"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "LinkGroupExportForm"
    bindings:
      WebForm: "LinkGroupExportForm"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "Join10"
    type: "join"
  - id: "Join12"
    type: "join"
  - id: "Join13"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "Jump3"
    type: "jump"
    ref: "ViewChannelLinkImpex-Status"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "\"LinkCSVExport.isml\""
      OutValue_1: "ExportTemplate"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "\"LinkXMLExport.isml\""
      OutValue_1: "ExportTemplate"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ChannelRepository"
      OutValue_1: "Channel"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ChannelRepository:Domain"
      InValue_2: "ChannelRepository:Domain"
      OutValue_1: "ProcessOwningDomain"
      OutValue_2: "ProcessExecutionDomain"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "ShortLinksPageable:ID"
      InValue_3: "\"shortlink\""
      InValue_4: "\"Export Links\""
      InValue_5: "\"ProcessLinkImpex\""
      InValue_6: "\"ProcessLinkExport\""
      InValue_7: "\"Export\""
      InValue_8: "CurrentOrganization:UUID"
      InValue_10: "\"inputDateTimePattern\""
      OutValue_1: "PageableID"
      OutValue_3: "ExportDirectory"
      OutValue_4: "JobDescription"
      OutValue_5: "JobName"
      OutValue_6: "ProcessPipelineName"
      OutValue_7: "ProcessPipelineStartNode"
      OutValue_8: "CurrentOrganizationUUID"
      OutValue_10: "DateTimePatternKey"
  - id: "KeyMapper6"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "ShortLinkExportForm:ExportFile:Value"
      OutValue_1: "SelectedFile"
  - id: "KeyMapper7"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "LinkGroupExportForm:ExportFile:Value"
      OutValue_1: "SelectedFile"
  - id: "Loop1"
    type: "loop"
  - id: "Loop2"
    type: "loop"
  - id: "Loop3"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelLinks-Paging"
      OutValue_1: "ViewChannelLinkGroups-Paging"
      OutValue_2: "ViewChannelLinkExport-LinkStart"
      OutValue_3: "ViewChannelLinkExport-GroupStart"
    bindings:
      Key_0: "CancelLinkExport"
      Key_1: "CancelGroupExport"
      Key_2: "StartLinkExport"
      Key_3: "StartGroupExport"
      SelectionKey: "JumpTarget"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "link/ChannelLinkExportConfiguration"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "link/ChannelGroupExportConfiguration"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "ShortLinkExportForm"
    bindings:
      WebForm: "ShortLinkExportForm"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "LinkGroupExportForm"
    bindings:
      WebForm: "LinkGroupExportForm"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "ShortLinkExportForm"
  - id: "ValidateWebForm2"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "LinkGroupExportForm"

links:
  - from: "AddObjectToVector1"
    via: "next"
    to: "Join10"
    into: "in1"
  - from: "AddObjectToVector2"
    via: "next"
    to: "Loop3"
    into: "loop"
  - from: "AddObjectToVector3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Call10"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "Call11"
    via: "next"
    to: "KeyMapper7"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Join13"
    into: "in1"
  - from: "Call3"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Call4"
    via: "next"
    to: "KeyMapper6"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "Loop2"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "Loop3"
    into: "in"
  - from: "CreateDirectory1"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "CreateDirectory2"
    via: "next"
    to: "GetCurrentDate2"
    into: "in"
  - from: "CreatePageableFromIterator1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CreateWebForm1"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "CreateWebForm2"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "KeyMapper1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "KeyMapper2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "AddObjectToVector3"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "JoinNode2"
    into: "in1"
  - from: "ExecuteObjectsQuery2"
    via: "next"
    to: "End12"
    into: "in"
  - from: "GetCurrentDate2"
    via: "next"
    to: "Call11"
    into: "in"
  - from: "GetLinkGroupByUUID1"
    via: "error"
    to: "Join12"
    into: "in1"
  - from: "GetLinkGroupByUUID1"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "GetShortLinkByUUID1"
    via: "error"
    to: "Join10"
    into: "in1"
  - from: "GetShortLinkByUUID1"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "Join13"
    into: "in1"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "GetWebForm2"
    via: "error"
    to: "Join3"
    into: "in1"
  - from: "GetWebForm2"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "Join10"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Join12"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "Join13"
    via: "next"
    to: "CreateWebForm2"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "CreatePageableFromIterator1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "KeyMapper3"
    via: "next"
    to: "End7"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "KeyMapper6"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "KeyMapper7"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetShortLinkByUUID1"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "End10"
    into: "in"
  - from: "Loop2"
    via: "do"
    to: "GetLinkGroupByUUID1"
    into: "in"
  - from: "Loop2"
    via: "next"
    to: "End11"
    into: "in"
  - from: "Loop3"
    via: "do"
    to: "AddObjectToVector2"
    into: "in"
  - from: "Loop3"
    via: "next"
    to: "Join12"
    into: "in1"
  - from: "Pipelet1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "Start10"
    via: "next"
    to: "ExecuteObjectsQuery2"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "UpdateWebForm2"
    via: "next"
    to: "ValidateWebForm2"
    into: "in"
  - from: "ValidateWebForm1"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "ValidateWebForm1"
    via: "next"
    to: "CreateDirectory1"
    into: "in"
  - from: "ValidateWebForm2"
    via: "error"
    to: "Join7"
    into: "in1"
  - from: "ValidateWebForm2"
    via: "next"
    to: "CreateDirectory2"
    into: "in"
