flow: "ViewProductUNSPSC_32"
kind: "view"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "SelectLevel"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "ValidateCode"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "CheckLock"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessProduct-DetermineCategoryPath"
  - id: "Call2"
    type: "call"
    ref: "ViewProductUNSPSC_32-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ViewProductUNSPSC_32-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ViewProductUNSPSC_32-Prefix"
  - id: "Call5"
    type: "call"
    ref: "ViewProductUNSPSC_32-Prefix"
  - id: "Call6"
    type: "call"
    ref: "ProcessProductUNSPSC-Start"
  - id: "Call7"
    type: "call"
    ref: "ProcessProductUNSPSC-SelectLevel"
  - id: "Call8"
    type: "call"
    ref: "ProcessProductUNSPSC-ValidateCode"
  - id: "Call9"
    type: "call"
    ref: "ProcessProductUNSPSC-Update"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessProductLock_32-Check"
  - id: "CallNode2"
    type: "call"
    ref: "ViewProductUNSPSC_32-CheckLock"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessProductLock_32-Lookup"
  - id: "CheckForEmptyString1"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "ChannelID"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProductUNSPSC_32-Update"
    bindings:
      Key_0: "update"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "CurrentSelectedChannel"
      UUID: "ChannelID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "Jump3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewProductUNSPSC_32-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewProduct_32-ErrorProductNotAvailable"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentProductRepository:RepositoryDomain"
      OutValue_1: "ProductDomain"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "product/ProductUpdateUNSPSC_32"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Value: "ViewProductUNSPSC_32-Start"
      Name: "JumpTarget"
      ValueType: "Dictionary Value"

links:
  - from: "Start1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "Call9"
    via: "next"
    to: "Join2"
    into: "in3"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "next"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "GetRepositoryByUUID1"
    via: "error"
    to: "Join4"
    into: "in2"
  - from: "Join4"
    via: "next"
    to: "Join3"
    into: "in3"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "error"
    to: "Join4"
    into: "in1"
  - from: "Call1"
    via: "next"
    to: "CheckForEmptyString1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "CallNode1"
    via: "NO_LOCK"
    to: "JumpNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Call6"
    via: "error-product-not-available"
    to: "JoinNode1"
    into: "in1"
  - from: "Call7"
    via: "error-product-not-available"
    to: "JoinNode1"
    into: "in1"
  - from: "Call8"
    via: "error-product-not-available"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "Call9"
    via: "error-product-not-available"
    to: "JoinNode1"
    into: "in1"
  - from: "Start5"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Call6"
    via: "next"
    to: "Join1"
    into: "in2"
