flow: "ViewPageSetParentWizard"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Finish"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode12"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "InitPageTree"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode20"
    name: "DispatchByBreadcrumb"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "ProcessValuesInContainer"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewPageProcessingWizard-ProcessValuesInContainer"
  - id: "CallNode10"
    type: "call"
    ref: "ProcessContentWizard-GetSelectedMenuItem"
  - id: "CallNode12"
    type: "call"
    ref: "ViewPageSetParentWizard-InitPageTree"
  - id: "CallNode15"
    type: "call"
    ref: "ViewPageSetParentWizard-ProcessValuesInContainer"
  - id: "CallNode2"
    type: "call"
    ref: "ViewPageSetParentWizard-ProcessValuesInContainer"
  - id: "CallNode23"
    type: "call"
    ref: "ViewContentPageTree-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessContentWizard-GetSelectedMenuItem"
  - id: "DecisionNode1"
    type: "decision"
    condition: "SelectedPageUUID"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_2: "ViewPageSetParentWizard-DispatchByBreadcrumb"
      OutValue_0: "ViewPageSetParentWizard-Finish"
      OutValue_1: "ViewPageSetParentWizard-DispatchByBreadcrumb"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "finish"
      Key_1: "previous"
      Key_2: "cancel"
  - id: "DispatchFormActionByBreadcrumb1"
    type: "pipelet"
    ref: "DispatchFormActionByBreadcrumb"
    config:
      SplitMode: "PipelineAndParameter"
    bindings:
      Key_0: "cancel"
      SelectionKey: "JumpTarget"
      OutValue_0: "ApplicationState:LastListView"
      OutValue_1: "ApplicationState:LastButOneBreadcrumb"
      Key_1: "previous"
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "InteractionNode2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode19"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "ProcessContentWizard-CreateProcess"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "\"BatchProcessPageletEntryPoints-SetParent\""
      OutValue_1: "ProcessPipeline"
      InValue_2: "\"BatchProcessPageletEntryPoints-Init\""
      OutValue_2: "InitPipeline"
      InValue_3: "\"BatchProcessPageletEntryPoints-Finish\""
      OutValue_3: "PostPipeline"
      InValue_4: "\"MasterContent\""
      OutValue_4: "JobName"
      InValue_5: "\"MasterContent\""
      OutValue_5: "JobNamePrefix"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "PagePageableID"
      OutValue_1: "PageableID"
      InValue_2: "SelectedPageUUID"
      OutValue_2: "SelectedParentUUID"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "\"ViewPageSetParentWizard-Start\""
      OutValue_1: "ContextPipeline"
      InValue_2: "ContentRepositoryUUID"
      OutValue_2: "ContentRepositoryUUID"
      InValue_3: "ParentSelectionTarget"
      OutValue_3: "ParentSelectionTarget"
      InValue_4: "PageletEntryPointUUID"
      OutValue_4: "PageletEntryPointUUID"
  - id: "PrepareApplicationView4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "content/pageletentrypoint/wizard/PageletEntryPointSetParent"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ErrorNoPageSelected"
      Value: true
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewPageSetParentWizard-Start"
      ValueType: "Dictionary Value"
  - id: "SetValuesToContainer1"
    type: "pipelet"
    ref: "SetValuesToContainer"
    config:
      DefaultContainerName: "ContentPageTree"

links:
  - from: "StartNode2"
    via: "next"
    to: "CallNode23"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "CallNode15"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "SetValuesToContainer1"
    into: "in"
  - from: "CallNode23"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "JoinNode19"
    into: "in3"
  - from: "StartNode9"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "DispatchFormAction2"
    via: "next"
    to: "JoinNode19"
    into: "in1"
  - from: "StartNode20"
    via: "next"
    to: "DispatchFormActionByBreadcrumb1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "DispatchFormAction2"
    via: "error"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "PrepareApplicationView4"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "JoinNode19"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "StartNode12"
    via: "next"
    to: "DispatchFormAction2"
    into: "in"
  - from: "CallNode15"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "SetValuesToContainer1"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "PrepareApplicationView4"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DispatchFormActionByBreadcrumb1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "SetDictionaryValue1"
    into: "in"
