flow: "ViewConfigurationParameterSelectProduct"
kind: "view"

entries:
  - id: "Start9"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode13"
    name: "SetProduct"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Search"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "ParametricSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ValidateWebForms-WFAdvancedSearch"
  - id: "Call2"
    type: "call"
    ref: "ValidateWebForms-WFSimpleSearch"
  - id: "Call3"
    type: "call"
    ref: "ViewParametricSearch-SimpleMasterProductSearch"
  - id: "Call6"
    type: "call"
    ref: "ViewParametricSearch-SearchMasterProduct"
  - id: "CallNode1"
    type: "call"
    ref: "ViewConfigurationParameters-GetConfigurationParameterCtnr"
  - id: "CallNode10"
    type: "call"
    ref: "ViewProductList-StorePageLocatorParameters"
  - id: "CallNode13"
    type: "call"
    ref: "ViewConfigurationParameters-GetValuesFromSession"
  - id: "CallNode2"
    type: "call"
    ref: "ViewConfigurationParameters-GetConfigurationParameterCtnr"
  - id: "CallNode3"
    type: "call"
    ref: "ViewConfigurationParameters-GetConfigurationParameterCtnr"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessConfigurationParameterCtnrWebForm-AddFormParameterValue"
    bindings:
      ConfigurationParameterName: "SelectedConfigurationParameterName"
      ParameterValues: "ProductReference"
      Site: "CurrentDomain"
  - id: "CallNode49"
    type: "call"
    ref: "ViewProductList-PrepareCurrentSearchType"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode52"
    type: "call"
    ref: "ViewProductList-PrepareSearchMask"
  - id: "CallNode54"
    type: "call"
    ref: "ViewProductList-SetCurrentSearchTypePageLocatorParameter"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessClipboard-UpdateWithFormValues"
  - id: "CallNode8"
    type: "call"
    ref: "ViewConfigurationParameters-GetConfigurationParameterCtnr"
  - id: "CheckForEmptyString2"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "ProductReference"
  - id: "CreateProductIdentifierLookupHelper1"
    type: "pipelet"
    ref: "CreateProductIdentifierLookupHelper"
    config:
      DefaultFactoryName: "com.intershop.beehive.xcs.internal.product.ProductPO"
  - id: "Decision1"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision2"
    type: "decision"
    condition: "PageLocator"
  - id: "DecisionNode1"
    type: "decision"
    condition: "SelectedConfigurationParameterDefinition:Multiple"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ProductReference"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "This:Paging"
      OutValue_1: "This:Search"
      OutValue_2: "This:AdvancedSearch"
      OutValue_3: "This:SetProduct"
      PagingPipeline: "ViewConfigurationParameterSelectProduct-Paging"
      OutValue_4: "ViewConfigurationParameters-Edit"
      OutValue_5: "This:Search"
      OutValue_6: "ViewConfigurationParameterSelectProduct-ParametricSearch"
      OutValue_7: "ViewConfigurationParameterSelectProduct-Search"
    bindings:
      SelectionKey: "JumpTarget"
      Key_1: "Search"
      Key_2: "AdvancedSearch"
      Key_3: "SetProduct"
      Key_0: "Paging"
      Key_4: "CancelSelection"
      Key_5: "findSimple"
      Key_6: "findParametric"
      Key_7: "StartProductSelection"
  - id: "GetCurrencies1"
    type: "pipelet"
    ref: "GetCurrencies"
    config:
      Method: "Active Currencies"
    bindings:
      Domain: "OrganizationDomain"
  - id: "GetLabels1"
    type: "pipelet"
    ref: "GetLabels"
    bindings:
      Domain: "OrganizationDomain"
  - id: "GetPageLocator2"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      RestorePageLocatorDictionary: "True"
      DefaultPageLocatorName: "ConfigurationParameterProductList"
  - id: "GetPageable2"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Products"
      PageableID: "PageLocator:PageableID"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewConfigurationParameterSelectProduct-Paging"
  - id: "JumpNode6"
    type: "jump"
    ref: "ViewConfigurationParameterSelectProduct-Paging"
  - id: "JumpNode7"
    type: "jump"
    ref: "ViewConfigurationParameters-Edit"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Clipboard:ObjectUUIDs"
      OutValue_1: "ProductReference"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "MasterComponents"
      WorkingTemplate: "content/ConfigurationParameterSelectProduct"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 1
    bindings:
      PageNumber: "PageNumberInt"
      Pageable: "Products"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Products"
      PageNumber: "PageLocator:PageNumber"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewConfigurationParameterSelectProduct-Paging"
      DefaultPageLocatorName: "ConfigurationParameterProductList"
    bindings:
      Pageable: "Products"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumberInt"
      LocalizedString: "PageNumber"

links:
  - from: "StartNode3"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Call1"
    via: "ERROR"
    to: "JoinNode14"
    into: "in1"
  - from: "StartNode7"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "GetPageLocator2"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "JoinNode12"
    into: "in3"
  - from: "Call2"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "SetPage1"
    via: "next"
    to: "Join7"
    into: "in2"
  - from: "GetPageable2"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "Call2"
    via: "ERROR"
    to: "JoinNode14"
    into: "in2"
  - from: "GetPageable2"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "CallNode3"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "JoinNode12"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "JoinNode9"
    into: "in2"
  - from: "JoinNode9"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "CallNode54"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage1"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join6"
    into: "in1"
  - from: "CallNode13"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode5"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "JoinNode14"
    via: "next"
    to: "JoinNode13"
    into: "in3"
  - from: "CreateProductIdentifierLookupHelper1"
    via: "next"
    to: "JoinNode13"
    into: "in1"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join6"
    into: "in2"
  - from: "Decision2"
    via: "yes"
    to: "SetPage2"
    into: "in"
  - from: "GetPageLocator2"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "Decision1"
    via: "no"
    to: "Decision2"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "JoinNode13"
    via: "next"
    to: "GetLabels1"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join7"
    into: "in3"
  - from: "CheckForEmptyString2"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "DecisionNode1"
    via: "no"
    to: "CheckForEmptyString2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode12"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "JumpNode7"
    into: "in"
  - from: "CheckForEmptyString2"
    via: "error"
    to: "JumpNode6"
    into: "in"
  - from: "StartNode13"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "SetPageLocator1"
    via: "next"
    to: "CallNode54"
    into: "in"
  - from: "GetLabels1"
    via: "next"
    to: "GetCurrencies1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "CallNode49"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetCurrencies1"
    via: "next"
    to: "CallNode52"
    into: "in"
  - from: "CallNode52"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "CallNode49"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "CreateProductIdentifierLookupHelper1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JumpNode1"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "GetPageLocator2"
    via: "next"
    to: "GetPageable2"
    into: "in"
