flow: "ViewBrandingPackageList_52"
kind: "view"

entries:
  - id: "Start1"
    name: "ShowSelection"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start14"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start16"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddEntryToMap1"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "Installations"
      Key: "BrandingPackage:UUID"
      Value: "BrandingInstallations"
      OutMap: "Installations"
  - id: "AddEntryToMap2"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "Installations"
      Key: "BrandingPackage:UUID"
      Value: "BrandingInstallations"
      OutMap: "Installations"
  - id: "Call1"
    type: "call"
    ref: "ViewBrandingPackageList_52-Prefix"
  - id: "Call17"
    type: "call"
    ref: "ViewBrandingPackageList_52-Prefix"
  - id: "Call2"
    type: "call"
    ref: "ViewBrandingPackageList_52-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call5"
    type: "call"
    ref: "ViewBrandingPackageList_52-Prefix"
  - id: "Call6"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessOrganization_52-GetConsumerOrg"
  - id: "CallNode4"
    type: "call"
    ref: "ViewBrandingPackage_52-DeleteBrandingPackage"
    bindings:
      ERROR_DeleteBrandingPackage: "ERROR_BrandingPackageList"
  - id: "Decision3"
    type: "decision"
    condition: "PageLocator"
  - id: "Decision4"
    type: "decision"
    condition: "DetailsPageNumber"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewBrandingPackage_52-New"
      OutValue_1: "ViewBrandingPackageList_52-Delete"
      OutValue_2: "ViewBrandingPackageList_52-ListAll"
      OutValue_3: "ViewBrandingPackageList_52-ShowSelection"
      OutValue_4: "ViewBrandingPackageList_52-ListAll"
    bindings:
      Key_0: "newPackage"
      Key_1: "deletePackage"
      Key_2: "backToList"
      Key_3: "confirmDeletePackage"
      Key_4: "cancelDeletion"
      SelectionKey: "JumpTarget"
  - id: "End3"
    type: "end"
    strict: false
  - id: "GetApplicationState1"
    type: "pipelet"
    ref: "GetApplicationState"
  - id: "GetBrandingInstallations1"
    type: "pipelet"
    ref: "GetBrandingInstallations"
    bindings:
      Unit: "Organization:OrganizationDomain"
      Package: "BrandingPackage"
  - id: "GetBrandingInstallations2"
    type: "pipelet"
    ref: "GetBrandingInstallations"
    bindings:
      Site: "CurrentRequest:ChannelSite"
      Unit: "Organization:OrganizationDomain"
      Package: "BrandingPackage"
  - id: "GetBrandingPackages1"
    type: "pipelet"
    ref: "GetBrandingPackages"
    bindings:
      Domain: "Organization:OrganizationDomain"
  - id: "GetBrandingPackages2"
    type: "pipelet"
    ref: "GetBrandingPackages"
    bindings:
      Domain: "Organization:OrganizationDomain"
  - id: "GetFirstElementOfIterator1"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      Iterator: "AppsPageable"
      FirstElement: "App"
  - id: "GetPageable2"
    type: "pipelet"
    ref: "GetPageable"
    config:
      DefaultPageableID: "\"AppsListBranding_Pageable\""
    bindings:
      PageableID: "PageLocator:PageableID"
      Pageable: "AppsPageable"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "Join4"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode34"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode41"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump5"
    type: "jump"
    ref: "ViewBrandingPackageList_52-ListAll"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewChannelApps-RestorePage"
  - id: "KeyMapper16"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "DetailsPageNumber"
      OutValue_1: "PageNumber"
      InValue_2: "Application:UUID"
      OutValue_2: "ApplicationUUID"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"ViewChannelApps-List\""
      OutValue_1: "JumpTarget"
  - id: "Loop1"
    type: "loop"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode4"
    type: "loop"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "GetApplicationByUUID"
    bindings:
      ApplicationID: "ApplicationUUID"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "AppBrandingPager"
      RestorePageLocatorDictionary: "False"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewBrandingPackageList_52-Paging"
      DefaultPageLocatorName: "AppBrandingPager"
    bindings:
      Pageable: "AppsPageable"
  - id: "Pipelet9"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "AppsPageable"
      PageableID: "\"AppsListBranding_Pageable\""
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Application"
      WorkingTemplate: "branding/BrandingPackageList_52"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Application"
      WorkingTemplate: "branding/BrandingPackageList_52"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "AppsPageable"
  - id: "SetPage4"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      Pageable: "AppsPageable"
  - id: "SetPageLocator2"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewBrandingPackageList_52-Paging"
      DefaultPageLocatorName: "AppBrandingPager"
    bindings:
      Pageable: "AppsPageable"
  - id: "VerifyInteger2"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "DetailsPageNumber"

links:
  - from: "Start3"
    via: "next"
    to: "Call17"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GetApplicationState1"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode34"
    via: "next"
    to: "GetPageable2"
    into: "in"
  - from: "LoopNode4"
    via: "do"
    to: "GetBrandingInstallations2"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "JoinNode9"
    into: "in3"
  - from: "GetApplicationState1"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "VerifyInteger2"
    via: "error"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "GetBrandingInstallations2"
    via: "next"
    to: "AddEntryToMap2"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "CallNode4"
    into: "in"
  - from: "Start14"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "Call3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "GetBrandingPackages1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "CallNode4"
    via: "ERROR"
    to: "JoinNode3"
    into: "in2"
  - from: "Pipelet2"
    via: "error"
    to: "KeyMapper3"
    into: "in"
  - from: "GetFirstElementOfIterator1"
    via: "next"
    to: "KeyMapper16"
    into: "in"
  - from: "GetBrandingPackages2"
    via: "next"
    to: "LoopNode4"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "GetBrandingInstallations1"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "GetBrandingInstallations1"
    via: "next"
    to: "AddEntryToMap1"
    into: "in"
  - from: "AddEntryToMap1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "Call17"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "GetBrandingPackages1"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "End3"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "GetBrandingPackages2"
    into: "in"
  - from: "AddEntryToMap2"
    via: "next"
    to: "LoopNode4"
    into: "loop"
  - from: "StartNode9"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "LoopNode4"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "SetPage1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "SetPage4"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "Decision3"
    via: "no"
    to: "Join4"
    into: "in3"
  - from: "Call1"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "GetFirstElementOfIterator1"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "JoinNode41"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "GetPageable2"
    via: "next"
    to: "Decision4"
    into: "in"
  - from: "Pipelet9"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "Decision3"
    into: "in"
  - from: "VerifyInteger2"
    via: "next"
    to: "SetPage4"
    into: "in"
  - from: "SetPageLocator2"
    via: "next"
    to: "GetFirstElementOfIterator1"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "SetPageLocator2"
    into: "in"
  - from: "Decision4"
    via: "yes"
    to: "VerifyInteger2"
    into: "in"
  - from: "Start16"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode8"
    into: "in2"
  - from: "Pipelet6"
    via: "next"
    to: "JoinNode34"
    into: "in1"
  - from: "KeyMapper16"
    via: "next"
    to: "GetApplicationState1"
    into: "in"
  - from: "Pipelet6"
    via: "error"
    to: "Pipelet9"
    into: "in"
  - from: "Pipelet9"
    via: "error"
    to: "JoinNode41"
    into: "in2"
  - from: "Pipelet7"
    via: "next"
    to: "JoinNode34"
    into: "in1"
  - from: "Decision3"
    via: "yes"
    to: "SetPage1"
    into: "in"
  - from: "GetPageable2"
    via: "error"
    to: "JoinNode41"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "JumpNode4"
    into: "in"
