flow: "ViewCheckoutAddresses"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Review"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode14"
    name: "ContinueCheckout"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode16"
    name: "ChangeAddressForm"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode17"
    name: "ProcessCheckoutRegisterUserSimple"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "ViewRegisterUserSimpleHook"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode21"
    name: "ViewRegisterUserSimple"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode22"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode25"
    name: "RemoveAndAddToWishlistRestrictedPLI"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode26"
    name: "RemoveRestrictedPLI"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode27"
    name: "AdjustedEntryPoint"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "RemoveRestrictedWarrantyPLI"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewCheckoutAddresses-Prefix"
  - id: "CallNode12"
    type: "call"
    ref: "ProcessCheckout-DefaultSettings"
    bindings:
      Cart: "CurrentCart"
      Domain: "CurrentDomain"
      User: "CurrentUser"
  - id: "CallNode17"
    type: "call"
    ref: "ProcessCheckout-AdjustJumpStep"
  - id: "CallNode19"
    type: "call"
    ref: "ProcessWebforms-CreateAddressForm"
    bindings:
      FormName: "\"address\""
      FormAlias: "formType"
      Dictionary: "CurrentRequest:PipelineDictionary"
      Form: "AddressForm"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessCart-GetCurrentCart"
    bindings:
      User: "CurrentUser"
      Organization: "CurrentOrganization"
      BasketBORepository: "ApplicationBO:Repository(\"BasketBORepository\")"
  - id: "CallNode25"
    type: "call"
    ref: "ProcessPromotionCodeForBasket-ValidateAllPromotionCodesFromBasket"
    bindings:
      Organization: "CurrentOrganization"
      Requisition: "CurrentCart"
      Consumer: "CurrentUser"
      ValidationTime: "CurrentSession:CreationTime"
      ApplicationID: "CurrentAppContext:Variables:Application:UUID"
  - id: "CallNode3"
    type: "call"
    ref: "ViewCheckout-Prefix"
  - id: "CallNode35"
    type: "call"
    ref: "ProcessUserAccount-RegisterUser"
    bindings:
      Login: "RegisterUserForm:Login:Value"
      Password: "RegisterUserForm:Password:Value"
      Email: "RegisterUserForm:Email:Value"
      PasswordConfirmation: "RegisterUserForm:RetypedPassword:Value"
      Organization: "CurrentOrganization"
  - id: "CallNode38"
    type: "call"
    ref: "ProcessLogin-LoginUser"
    bindings:
      Login: "RegisterUserForm:Login:Value"
      Password: "RegisterUserForm:Password:Value"
  - id: "CallNode46"
    type: "call"
    ref: "ProcessCheckoutAddresses-GetRegistrationForm"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessCart-Calculate"
    bindings:
      Cart: "CurrentCart"
      BasketBO: "CurrentCartBO"
  - id: "CallNode51"
    type: "call"
    ref: "ViewCheckoutAddresses-Prefix"
  - id: "CallNode52"
    type: "call"
    ref: "ProcessCheckoutAddresses-GetRegistrationForm"
  - id: "CallNode53"
    type: "call"
    ref: "ViewCheckoutAddresses-Prefix"
  - id: "CallNode58"
    type: "call"
    ref: "ProcessCart-RemoveProductLineItem"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessCheckoutAddresses-SetAsShippingAddress"
    bindings:
      AddressID: "CurrentCartBO:InvoiceToAddress:ID"
      CurrentCart: "CurrentCart"
  - id: "CallNode60"
    type: "call"
    ref: "ProcessUserGroups-GetCurrentUserUserGroups"
  - id: "CallNode61"
    type: "call"
    ref: "ViewCheckoutAddresses-Prefix"
  - id: "CallNode9"
    type: "call"
    ref: "ProcessCheckoutAddresses-CheckDefaultSettings"
    bindings:
      Cart: "CurrentCart"
  - id: "CheckUserLoggedIn4"
    type: "pipelet"
    ref: "CheckUserLoggedIn"
  - id: "DecisionNode0"
    type: "decision"
    condition: "CurrentCartBO:InvoiceToAddress"
  - id: "DecisionNode1"
    type: "decision"
    condition: "CurrentCartBO:InvoiceToAddress"
  - id: "DecisionNode16"
    type: "decision"
    condition: "formType"
  - id: "DecisionNode2"
    type: "decision"
    condition: "CurrentCart:ProductLineItemsCount"
  - id: "DecisionNode3"
    type: "decision"
    condition: "CurrentCartBO:MultipleShippments"
  - id: "DecisionNode4"
    type: "decision"
    condition: "CurrentCartBO:ShipToAddressesSet"
  - id: "DecisionNode5"
    type: "decision"
    condition: "newaddress"
  - id: "DecisionNode6"
    type: "decision"
    condition: "newaddress"
  - id: "DispatchFormAction0"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewCheckoutMultipleAddresses-ApplyMultipleShipToAddresses"
    bindings:
      Key_0: "applyMultipleShipToAddresses"
      SelectionKey: "JumpTarget"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_9: "ViewCheckoutMultipleAddresses-SelectMultipleShipToAddresses"
      OutValue_8: "ViewCheckoutMultipleAddresses-MultipleShipping"
      OutValue_7: "ViewCheckoutAddressBook-AddNewAddress"
      OutValue_6: "ViewCheckoutAddressBook-UpdateAddress"
      OutValue_5: "ViewCheckoutAddressBook-AddNewAddress"
      OutValue_4: "ViewCheckoutAddressBook-DeleteAddress"
      OutValue_3: "ViewCheckoutAddresses-ContinueCheckout"
      OutValue_2: "ViewCheckoutNewCustomerAddress-LoginUser"
      OutValue_1: "ViewCheckoutNewCustomerAddress-AddAddresses"
      OutValue_0: "ViewCheckoutAddresses-RemoveRestrictedPLI"
    bindings:
      Key_9: "selectMultipleShipToAddresses"
      Key_8: "multipleShipping"
      Key_7: "addAndSelectAsBilling"
      Key_6: "updateAddress"
      Key_5: "addNewBilling"
      Key_4: "delete"
      Key_3: "skip"
      Key_2: "signIn"
      Key_1: "continue"
      Key_0: "removeRestrictedPLI"
      SelectionKey: "JumpTarget"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndSafeChangesBlock1"
    type: "pipelet"
    ref: "EndSafeChangesBlock"
  - id: "FillForm1"
    type: "pipelet"
    ref: "FillForm"
    bindings:
      Form: "AddressForm"
  - id: "GetDomainPreference3"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "BasketEmailOptIn"
      Type: "String"
    bindings:
      PreferenceDomain: "CurrentOrganization:OrganizationDomain"
      PreferenceStringValue: "BasketEmailOptIn"
  - id: "InteractionNode5"
    type: "interaction"
  - id: "InteractionNode6"
    type: "interaction"
  - id: "JoinNode0"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode13"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode25"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode31"
    type: "join"
  - id: "JoinNode33"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump1"
    type: "jump"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewCheckoutAddresses-ViewRegisterUserSimpleHook"
  - id: "JumpNode10"
    type: "jump"
    ref: "ViewCheckoutShipping-Start"
  - id: "JumpNode11"
    type: "jump"
    ref: "ViewCheckoutAddressBook-EditAddress"
  - id: "JumpNode12"
    type: "jump"
    ref: "ViewCheckoutMultipleAddresses-SelectMultipleShipToAddresses"
  - id: "JumpNode13"
    type: "jump"
    ref: "ViewCheckoutAddressBook-EditAddress"
  - id: "JumpNode16"
    type: "jump"
    ref: "ViewCheckoutAddresses-Start"
  - id: "JumpNode19"
    type: "jump"
    ref: "ViewCheckoutAddresses-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewCheckoutAddresses-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewCheckoutAddresses-ViewRegisterUserSimpleHook"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewPage-Start"
  - id: "JumpNode5"
    type: "jump"
    ref: "ViewCheckoutAddresses-Start"
  - id: "JumpNode6"
    type: "jump"
    ref: "ViewCart-View"
  - id: "JumpNode8"
    type: "jump"
    ref: "ViewCheckoutNewCustomerAddress-NewAddresses"
  - id: "JumpNode9"
    type: "jump"
    ref: "Redirect-Start"
  - id: "KeyMapper0"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "ApplicationBO:App:NamedObject(\"salutationEnumerationKeyProvider\")"
      OutValue_1: "SalutationEnumerationKeyProvider"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "CurrentRequest:PipelineDictionary"
      InValue_3: "\"systempage.checkout.address.pagelet2-systempage.checkout.address\""
      InValue_2: "\"account/CheckoutCreateSimple\""
      OutValue_1: "Dictionary"
      OutValue_3: "PageletEntryPointID"
      OutValue_2: "WorkingTemplate"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpStep"
      Value: 1
      ValueType: "Dictionary Value"
  - id: "RemoveWarrantyLineItem1"
    type: "pipelet"
    ref: "RemoveWarrantyLineItem"
    bindings:
      ProductLineItem: "CurrentCartBO:PliByID(ProductLineItemUUID)"
  - id: "SetDictionaryValue5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "BasketEmailOptIn"
      Value: "'no'"
  - id: "SetFormParameterValue1"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      FormParameter: "AddressForm:State"
      Value: "\"\""
  - id: "StartSafeChangesBlock1"
    type: "pipelet"
    ref: "StartSafeChangesBlock"
  - id: "TextNode2"
    type: "text"
  - id: "ValidateForm6"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "RegisterUserForm"
  - id: "VerifyInteger2"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      LocalizedString: "\"1\""
      IntegerObject: "CurrentStep"

links:
  - from: "CallNode12"
    via: "next"
    to: "JoinNode13"
    into: "in1"
  - from: "CallNode17"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode19"
    via: "next"
    to: "FillForm1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "CallNode25"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "RemoveWarrantyLineItem1"
    into: "in"
  - from: "CallNode35"
    via: "ERROR"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode35"
    via: "next"
    to: "CallNode38"
    into: "in"
  - from: "CallNode38"
    via: "ERROR"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode38"
    via: "next"
    to: "JumpNode9"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "GetDomainPreference3"
    into: "in"
  - from: "CallNode46"
    via: "next"
    to: "ValidateForm6"
    into: "in"
  - from: "CallNode51"
    via: "next"
    to: "CheckUserLoggedIn4"
    into: "in"
  - from: "CallNode52"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "CallNode53"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "CallNode58"
    via: "next"
    to: "JumpNode16"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "CallNode60"
    via: "next"
    to: "CallNode25"
    into: "in"
  - from: "CallNode61"
    via: "next"
    to: "JoinNode25"
    into: "in1"
  - from: "CallNode6"
    via: "next"
    to: "EndSafeChangesBlock1"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "JumpNode13"
    into: "in"
  - from: "CheckUserLoggedIn4"
    via: "error"
    to: "CallNode60"
    into: "in"
  - from: "CheckUserLoggedIn4"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode0"
    via: "no"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode0"
    via: "yes"
    to: "JoinNode0"
    into: "in1"
  - from: "DecisionNode16"
    via: "no"
    to: "InteractionNode5"
    into: "in"
  - from: "DecisionNode16"
    via: "yes"
    to: "CallNode19"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "StartSafeChangesBlock1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode0"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "JumpNode6"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "JumpNode5"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JumpNode11"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "JumpNode12"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "DecisionNode0"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode5"
    via: "yes"
    to: "Jump1"
    into: "in"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode6"
    via: "yes"
    to: "CallNode17"
    into: "in"
  - from: "DispatchFormAction0"
    via: "error"
    to: "JoinNode8"
    into: "in1"
  - from: "DispatchFormAction0"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "error"
    to: "DispatchFormAction0"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "EndSafeChangesBlock1"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "FillForm1"
    via: "next"
    to: "SetFormParameterValue1"
    into: "in"
  - from: "GetDomainPreference3"
    via: "error"
    to: "SetDictionaryValue5"
    into: "in"
  - from: "GetDomainPreference3"
    via: "next"
    to: "JoinNode31"
    into: "in1"
  - from: "JoinNode0"
    via: "next"
    to: "JumpNode8"
    into: "in"
  - from: "JoinNode13"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode25"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "JoinNode31"
    via: "next"
    to: "VerifyInteger2"
    into: "in"
  - from: "JoinNode33"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JumpNode10"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode25"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "KeyMapper0"
    via: "next"
    to: "InteractionNode6"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode13"
    into: "in1"
  - from: "RemoveWarrantyLineItem1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "SetDictionaryValue5"
    via: "next"
    to: "JoinNode31"
    into: "in1"
  - from: "SetFormParameterValue1"
    via: "next"
    to: "KeyMapper0"
    into: "in"
  - from: "StartNode14"
    via: "next"
    to: "CallNode51"
    into: "in"
  - from: "StartNode16"
    via: "next"
    to: "DecisionNode16"
    into: "in"
  - from: "StartNode17"
    via: "next"
    to: "CallNode46"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode53"
    into: "in"
  - from: "StartNode21"
    via: "next"
    to: "CallNode52"
    into: "in"
  - from: "StartNode22"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode25"
    via: "next"
    to: "JumpNode19"
    into: "in"
  - from: "StartNode26"
    via: "next"
    to: "CallNode58"
    into: "in"
  - from: "StartNode27"
    via: "next"
    to: "CallNode61"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartSafeChangesBlock1"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "ValidateForm6"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "ValidateForm6"
    via: "next"
    to: "CallNode35"
    into: "in"
  - from: "VerifyInteger2"
    via: "error"
    to: "JoinNode33"
    into: "in1"
  - from: "VerifyInteger2"
    via: "next"
    to: "JoinNode33"
    into: "in1"
