flow: "ViewChannelUserAddressList"
kind: "view"

entries:
  - id: "Start1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "DeleteAddresses"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "DeleteAddress"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "List"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "SetDefaultAddress"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "ConfirmDeletion"
    mode: "public"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessAddress-SetDefaultAddress"
  - id: "Call2"
    type: "call"
    ref: "ViewChannelUserAddressList-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ProcessAddress-Remove"
  - id: "Call4"
    type: "call"
    ref: "ProcessAddressBook-GetUserAddresses"
  - id: "Call5"
    type: "call"
    ref: "ViewChannelUserAddressList-Prefix"
  - id: "Call6"
    type: "call"
    ref: "ViewChannelUserAddressList-Prefix"
  - id: "Call7"
    type: "call"
    ref: "ProcessAddress-Remove"
  - id: "Call8"
    type: "call"
    ref: "ViewChannelUserAddressList-Prefix"
  - id: "CallNode22"
    type: "call"
  - id: "ConcatenateStrings2"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "\"ProcessOrganization_\""
      String1: "CurrentChannel:TypeCode"
      String2: "\"-Get\""
      Concatenated: "GetOrganization"
  - id: "DetermineUser1"
    type: "pipelet"
    ref: "DetermineUser"
    bindings:
      UserID: "USER_UUID"
  - id: "DetermineUserProfile1"
    type: "pipelet"
    ref: "DetermineUserProfile"
    bindings:
      CurrentUser: "User"
  - id: "DetermineUserProfile2"
    type: "pipelet"
    ref: "DetermineUserProfile"
    bindings:
      CurrentUser: "User"
  - id: "DetermineUserProfile3"
    type: "pipelet"
    ref: "DetermineUserProfile"
    bindings:
      CurrentUser: "User"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelUserAddress-New"
      OutValue_1: "ViewChannelUserAddressList-ConfirmDeletion"
      OutValue_2: "ViewChannelUserAddressList-DeleteAddresses"
      OutValue_3: "ViewChannelUserAddressList-List"
      OutValue_4: "ViewChannelUserList-List"
    bindings:
      Key_0: "new"
      Key_1: "confirmDelete"
      Key_2: "delete"
      Key_3: "cancel"
      Key_4: "back"
      SelectionKey: "JumpTarget"
  - id: "End2"
    type: "end"
    strict: false
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "DeleteAddress"
    bindings:
      Selection: "Address_UUID_Iterator"
  - id: "GetFormSelection3"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "DeleteAddress"
    bindings:
      Selection: "PrefixIterator"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Jump6"
    type: "jump"
    ref: "ViewChannelUserAddressList-List"
  - id: "Jump7"
    type: "jump"
    ref: "ViewChannelUserAddressList-List"
  - id: "Jump8"
    type: "jump"
    ref: "ViewChannelUserAddressList-List"
  - id: "Jump9"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Loop1"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelUser"
      WorkingTemplate: "user/ChannelUserAddressList"
  - id: "SortIteratorByComparator2"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingOrder: true
      ComparatorClassName: "com.intershop.beehive.core.internal.profile.BasicAddressComparator"
    bindings:
      Iterator: "Profile:AddressBook:Address"
      SortedIterator: "SortedAddresses"

links:
  - from: "Start5"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Call5"
    via: "next"
    to: "DetermineUserProfile1"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "DetermineUserProfile2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "Call7"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Loop1"
    via: "next"
    to: "Jump8"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "DetermineUserProfile3"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "DetermineUser1"
    into: "in"
  - from: "DetermineUser1"
    via: "next"
    to: "ConcatenateStrings2"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DetermineUserProfile3"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump9"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "GetFormSelection3"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "Start7"
    via: "next"
    to: "GetFormSelection3"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "SortIteratorByComparator2"
    into: "in"
  - from: "SortIteratorByComparator2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CallNode22"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Jump7"
    into: "in"
  - from: "ConcatenateStrings2"
    via: "next"
    to: "CallNode22"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "DetermineUserProfile1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "DetermineUserProfile2"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Jump6"
    into: "in"
