flow: "ViewGiftCertificatePreferences_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "View"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Update"
    mode: "public"
    strict: false
    inputs:
      []

steps:
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "EmailSubject"
      param.1.required: true
      param.2.name: "EmailTemplate"
      param.2.required: true
      param.3.name: "EmailFrom"
      param.3.required: true
      param.3.rule: "^([0-9,a-z,A-Z]+)([.,_,-]([0-9,a-z,A-Z]+))*[@]([0-9,a-z,A-Z]+)([.,_,-]([0-9,a-z,A-Z]+))*[.]([a-z,A-Z]){2,3}([a-z,A-Z])?$"
      webform-id: "GiftCertificateWebForm"
      param.1.rule: ""
      param.2.rule: ""
    bindings:
      WebForm: "GiftCertificateWebForm"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_1: "ViewGiftCertificatePreferences_52-Update"
      OutValue_3: "ViewDomainPreference_52-Start"
    bindings:
      Key_1: "updateSettings"
      Key_3: "backToPrefs"
      SelectionKey: "JumpTarget"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "GiftCertificateEmailFrom"
      Type: "String"
    bindings:
      PreferenceStringValue: "GiftCertificateEmailFrom"
      PreferenceDomain: "ChannelRepository:Domain"
  - id: "GetDomainPreference2"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "GiftCertificateEmailSubject"
      Type: "String"
    bindings:
      PreferenceStringValue: "GiftCertificateEmailSubject"
      PreferenceDomain: "ChannelRepository:Domain"
  - id: "GetDomainPreference3"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "GiftCertificateEmailTemplate"
      Type: "String"
    bindings:
      PreferenceStringValue: "GiftCertificateEmailTemplate"
      PreferenceDomain: "ChannelRepository:Domain"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "GiftCertificateWebForm"
    bindings:
      WebForm: "GiftCertificateWebForm"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "Join5"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewGiftCertificatePreferences_52-View"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "GiftCertificateEmailFrom"
      OutValue_1: "GiftCertificateWebForm_EmailFrom"
      OutValue_2: "GiftCertificateWebForm_EmailSubject"
      OutValue_3: "GiftCertificateWebForm_EmailTemplate"
      InValue_3: "GiftCertificateEmailTemplate"
      InValue_2: "GiftCertificateEmailSubject"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "GiftCertificateEmailFrom"
      DefaultPreferenceValue: false
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceKey: "null"
      PreferenceStringValue: "GiftCertificateWebForm_EmailFrom"
      PreferenceValue: "null"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "GiftCertificateEmailSubject"
      DefaultPreferenceValue: false
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceKey: "null"
      PreferenceStringValue: "GiftCertificateWebForm_EmailSubject"
      PreferenceValue: "null"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "GiftCertificateEmailTemplate"
      DefaultPreferenceValue: false
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceKey: "null"
      PreferenceStringValue: "GiftCertificateWebForm_EmailTemplate"
      PreferenceValue: "null"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "channel/ChannelGiftCertificatePreferences_52"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "channel/ChannelGiftCertificatePreferences_52"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewGiftCertificatePreferences_52-View"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "GiftCertificateWebForm"
    bindings:
      WebForm: "GiftCertificateWebForm"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "GiftCertificateWebForm"
    bindings:
      WebForm: "GiftCertificateWebForm"
  - id: "ValidateWebForm2"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "GiftCertificateWebForm"

links:
  - from: "Start1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "GetWebForm2"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "Pipelet2"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "GetDomainPreference2"
    via: "next"
    to: "JoinNode9"
    into: "in3"
  - from: "UpdateWebForm1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "CreateWebForm1"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "GetDomainPreference3"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode10"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "GetDomainPreference3"
    into: "in"
  - from: "GetDomainPreference1"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "GetDomainPreference2"
    into: "in"
  - from: "GetDomainPreference3"
    via: "next"
    to: "JoinNode10"
    into: "in3"
  - from: "Pipelet5"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "GetDomainPreference2"
    via: "error"
    to: "JoinNode9"
    into: "in1"
  - from: "ValidateWebForm2"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "Pipelet4"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "UpdateWebForm2"
    via: "next"
    to: "ValidateWebForm2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "ValidateWebForm2"
    via: "error"
    to: "Join5"
    into: "in2"
  - from: "GetWebForm2"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "GetDomainPreference1"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "KeyMapper1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
