flow: "ViewHelpDesk"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "ViewCategory"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "ViewArticle"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "FireViewEvent"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "ViewFAQ"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "Render-StartInternal"
    bindings:
      Pagelet: "Pagelet"
  - id: "CallNode2"
    type: "call"
    ref: "ViewHelpDesk-FireViewEvent"
  - id: "CallNode3"
    type: "call"
    ref: "ViewHelpDesk-FireViewEvent"
  - id: "CallNode4"
    type: "call"
    ref: "FireTrackingEvents-View"
    bindings:
      PageName: "\"helpdesk\""
      PageType: "\"general\""
  - id: "DecisionNode1"
    type: "decision"
    condition: "category"
  - id: "DecisionNode3"
    type: "decision"
    condition: "article"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewHelpDesk-ViewFAQ"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "selectfaqtopic"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "GetFirstHelpdeskArticle1"
    type: "pipelet"
    ref: "GetFirstHelpdeskArticle"
  - id: "GetPageletById1"
    type: "pipelet"
    ref: "GetPageletById"
    bindings:
      Domain: "CurrentOrganization:OwningDomain"
      PageletId: "category"
      Pagelet: "CategoryPagelet"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "Jump1"
    type: "jump"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewPage-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      OutValue_1: "PageletEntryPointID"
      InValue_1: "\"systempage.helpdesk.index.pagelet2-systempage.helpdesk.index\""
      OutValue_2: "Dictionary"
      InValue_2: "CurrentRequest:PipelineDictionary"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "category"
      OutValue_1: "categoryid"
      InValue_2: "HelpdeskArticle:Id"
      OutValue_2: "articleid"
      InValue_3: "CategoryPagelet"
      OutValue_3: "Pagelet"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "category"
      OutValue_1: "categoryid"
      InValue_2: "article"
      OutValue_2: "articleid"
      InValue_3: "CategoryPagelet"
      OutValue_3: "Pagelet"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetPageletById"
    bindings:
      Domain: "CurrentOrganization:OwningDomain"
      PageletId: "articleid"
      Pagelet: "SubPagelet"

links:
  - from: "StartNode9"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "JoinNode4"
    into: "in2"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode6"
    into: "in3"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "GetPageletById1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "StartNode6"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "GetPageletById1"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "CallNode3"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "KeyMapper4"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "GetFirstHelpdeskArticle1"
    into: "in"
  - from: "GetFirstHelpdeskArticle1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetPageletById1"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "StartNode4"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "GetFirstHelpdeskArticle1"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "JoinNode3"
    via: "next"
    to: "CallNode3"
    into: "in"
