flow: "ViewChannelOutboundSyndicationLinkMapping"
kind: "view"

entries:
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessSyndicationRule-GetRuleSet"
    bindings:
      Name: "\"Links\""
  - id: "CallNode2"
    type: "call"
    ref: "ProcessSyndicationRule-GetRuleSet"
    bindings:
      Name: "\"Links\""
  - id: "CallNode3"
    type: "call"
    ref: "ProcessSyndicationRule-GetDataDeclarationList"
    bindings:
      Name: "\"Links\""
  - id: "CallNode4"
    type: "call"
    ref: "ProcessSyndicationRule-RemoveSyndicationRule"
  - id: "CreateSyndicationDataDeclaration1"
    type: "pipelet"
    ref: "CreateSyndicationDataDeclaration"
    bindings:
      Domain: "Syndication:Domain"
      DataObjectClassName: "\"com.intershop.beehive.xcs.internal.product.ProductPO\""
  - id: "CreateSyndicationRule1"
    type: "pipelet"
    ref: "CreateSyndicationRule"
    bindings:
      SyndicationRuleClass: "\"com.intershop.component.mvc.internal.syndication.ProductLinkRuleProcessorImpl\""
      Domain: "Syndication:Domain"
      SourceSyndicationDataDeclaration: "SyndicationDataDeclaration"
  - id: "DecisionNode1"
    type: "decision"
    condition: "LinkMappingEnabled"
  - id: "DecisionNode2"
    type: "decision"
    condition: "SyndicationRuleUUID"
  - id: "DecisionNode3"
    type: "decision"
    condition: "SyndicationRuleUUID"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelOutboundSyndicationLinkMapping-Start"
      OutValue_1: "ViewChannelOutboundSyndicationList-Start"
      OutValue_2: "ViewChannelOutboundSyndicationLinkMapping-Update"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "Start"
      Key_1: "Back"
      Key_2: "Update"
  - id: "GetSyndicationByUUID1"
    type: "pipelet"
    ref: "GetSyndicationByUUID"
  - id: "GetSyndicationByUUID2"
    type: "pipelet"
    ref: "GetSyndicationByUUID"
  - id: "GetSyndicationRuleByUUID2"
    type: "pipelet"
    ref: "GetSyndicationRuleByUUID"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "Jump5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/ChannelOutboundSyndicationLinkMapping"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/ChannelOutboundSyndicationLinkMapping"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "SyndicationRule"
      RemoveFormValues: false

links:
  - from: "CallNode2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "CallNode3"
    into: "in"
  - from: "CreateSyndicationRule1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CreateSyndicationDataDeclaration1"
    via: "next"
    to: "CreateSyndicationRule1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CreateSyndicationDataDeclaration1"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "DecisionNode1"
    via: "no"
    to: "DecisionNode3"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "CallNode4"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "GetSyndicationRuleByUUID2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "GetSyndicationRuleByUUID2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetSyndicationByUUID1"
    into: "in"
  - from: "GetSyndicationByUUID1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "GetSyndicationByUUID2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetSyndicationByUUID2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
