flow: "ViewProductCategoryAssignmentWizard"
kind: "view"

entries:
  - id: "Start1"
    name: "CategoryTree"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start10"
    name: "CatalogDetails"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start11"
    name: "CategoryDetails"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start12"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start13"
    name: "Cancel"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start14"
    name: "Finish"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Expand"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "ListCatalogs"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "PrepareProductAssignment"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "DoSelectCatalog"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "GetProduct"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "SelectCatalog"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "Collapse"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard-Prefix"
  - id: "Call10"
    type: "call"
    ref: "ProcessProduct-DetermineCategoryPath"
  - id: "Call11"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard-Prefix"
  - id: "Call12"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard-Prefix"
  - id: "Call13"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard-Prefix"
  - id: "Call14"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard-GetProduct"
  - id: "Call15"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard-GetProduct"
  - id: "Call16"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard-GetProduct"
  - id: "Call17"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard-GetProduct"
  - id: "Call18"
    type: "call"
    ref: "ProcessProduct-Get"
  - id: "Call2"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard-GetProduct"
  - id: "Call3"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard-Prefix"
  - id: "Call5"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard-Prefix"
  - id: "Call6"
    type: "call"
    ref: "ProcessCatalogList-GetStandardCatalogs"
  - id: "Call7"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard-GetProduct"
  - id: "Call8"
    type: "call"
    ref: "ViewProductCategoryAssignmentWizard-Prefix"
  - id: "CombineIterators1"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Concatenate Iterators"
    bindings:
      Iterator1: "SharedStandardCatalogs"
      Iterator2: "LocalStandardCatalogs"
      Iterator: "Catalogs"
  - id: "CreateIteratorForPrefix1"
    type: "pipelet"
    ref: "CreateIteratorForPrefix"
    config:
      Prefix: "ProductID"
  - id: "Decision2"
    type: "decision"
    condition: "SelectedCategoryUUID"
  - id: "Decision3"
    type: "decision"
    condition: "ProductID"
  - id: "Decision7"
    type: "decision"
    condition: "CatalogID"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProductCategoryAssignmentWizard-DoSelectCatalog"
      OutValue_1: "ViewProductCategoryAssignmentWizard-Cancel"
      OutValue_2: "ViewProductCategoryAssignmentWizard-Finish"
      OutValue_3: "ViewProductCategoryAssignmentWizard-ListCatalogs"
    bindings:
      Key_0: "selectCatalog"
      Key_1: "cancel"
      Key_2: "finish"
      Key_3: "previous"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "ExchangeSessionObject1"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      SaveObject: "ExpandedCategoriesMap"
  - id: "ExchangeSessionObject2"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "ProductUUIDs"
    bindings:
      SaveObject: "PrefixIterator"
  - id: "ExchangeSessionObject3"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "ProductID"
    bindings:
      SaveObject: "ProductID"
  - id: "ExchangeSessionObject4"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ProductID"
    bindings:
      LoadObject: "ProductID"
  - id: "ExchangeSessionObject5"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "CatalogID"
    bindings:
      LoadObject: "CatalogID"
      SaveObject: "CatalogID"
  - id: "ExchangeSessionObject6"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      LoadObject: "ExpandedCategoriesMap"
  - id: "ExchangeSessionObject7"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      LoadObject: "ExpandedCategoriesMap"
  - id: "GetCatalog1"
    type: "pipelet"
    ref: "GetCatalog"
  - id: "GetCatalog2"
    type: "pipelet"
    ref: "GetCatalog"
  - id: "GetCatalog3"
    type: "pipelet"
    ref: "GetCatalog"
  - id: "GetCatalog4"
    type: "pipelet"
    ref: "GetCatalog"
  - id: "GetCatalog5"
    type: "pipelet"
    ref: "GetCatalog"
  - id: "GetCategoryByUUID1"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "CategoryUUID"
  - id: "GetProductByUUID1"
    type: "pipelet"
    ref: "GetProductByUUID"
    bindings:
      ProductUUID: "ProductID"
      ProductDomain: "CurrentMasterRepository:RepositoryDomain"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "InteractionEnd4"
    type: "interaction"
  - id: "InteractionEnd5"
    type: "interaction"
  - id: "InteractionEnd6"
    type: "interaction"
  - id: "Join8"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewProductCategories-AssignSelectedProducts"
  - id: "Jump10"
    type: "jump"
    ref: "ViewProductCategoryAssignmentWizard-ListCatalogs"
  - id: "Jump2"
    type: "jump"
    ref: "ViewProductCategoryAssignmentWizard-CategoryTree"
  - id: "Jump3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump4"
    type: "jump"
    ref: "ViewProductCategoryAssignmentWizard-SelectCatalog"
  - id: "Jump5"
    type: "jump"
    ref: "ViewProductCategoryAssignmentWizard-ListCatalogs"
  - id: "Jump6"
    type: "jump"
    ref: "ViewProductCategoryAssignmentWizard-CategoryTree"
  - id: "Jump9"
    type: "jump"
    ref: "ViewProductCategories-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewProduct-ErrorProductNotAvailable"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Category"
      InValue_2: "CategoriesPath"
      OutValue_1: "JumpCategory"
      OutValue_2: "JumpCategoriesPath"
      InValue_3: "CurrentMasterRepository:RepositoryDomain"
      OutValue_3: "ProductDomain"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Catalog:Root:UUID"
      InValue_2: "Catalog:Id"
      OutValue_1: "CatalogCategoryID"
      OutValue_2: "CatalogID"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Products"
      WorkingTemplate: "product/ProductCategoryAssignmentSelectCategory"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Products"
      WorkingTemplate: "product/ProductCategoryAssignmentSelectCatalog"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Products"
      WorkingTemplate: "product/ProductCategoryAssignmentSelectCategory"
  - id: "PrepareApplicationView4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Products"
      WorkingTemplate: "product/ProductCategoryAssignmentSelectCategory"
  - id: "PrepareApplicationView5"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Products"
      WorkingTemplate: "product/ProductCategoryAssignmentViewCatalogDetails"
  - id: "PrepareApplicationView6"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Products"
      WorkingTemplate: "product/ProductCategoryAssignmentViewCategoryDetails"
  - id: "UpdateMapping1"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "Catalog:Root:UUID"
      OutMap: "ExpandedCategoriesMap"
      Value: "Catalog:Root:UUID"
  - id: "UpdateMapping2"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "CategoryUUID"
      Value: "CategoryUUID"
  - id: "UpdateMapping3"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Remove"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "CategoryUUID"
      Value: "CategoryUUID"

links:
  - from: "Start3"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "ExchangeSessionObject3"
    into: "in"
  - from: "GetCatalog2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "ExchangeSessionObject5"
    into: "in"
  - from: "ExchangeSessionObject5"
    via: "next"
    to: "Jump6"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "Decision7"
    via: "yes"
    to: "Jump4"
    into: "in"
  - from: "Decision7"
    via: "no"
    to: "Jump10"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "ExchangeSessionObject3"
    via: "next"
    to: "CreateIteratorForPrefix1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd4"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "PrepareApplicationView4"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "ExchangeSessionObject6"
    via: "next"
    to: "UpdateMapping2"
    into: "in"
  - from: "UpdateMapping2"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "ExchangeSessionObject7"
    via: "next"
    to: "UpdateMapping3"
    into: "in"
  - from: "UpdateMapping3"
    via: "next"
    to: "PrepareApplicationView4"
    into: "in"
  - from: "ExchangeSessionObject2"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "GetCatalog1"
    via: "next"
    to: "ExchangeSessionObject6"
    into: "in"
  - from: "GetCatalog3"
    via: "next"
    to: "ExchangeSessionObject7"
    into: "in"
  - from: "GetCatalog4"
    via: "next"
    to: "UpdateMapping1"
    into: "in"
  - from: "UpdateMapping1"
    via: "next"
    to: "ExchangeSessionObject1"
    into: "in"
  - from: "ExchangeSessionObject1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "Jump1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Jump2"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Jump9"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "Call11"
    into: "in"
  - from: "Call11"
    via: "next"
    to: "GetCatalog2"
    into: "in"
  - from: "CreateIteratorForPrefix1"
    via: "next"
    to: "ExchangeSessionObject2"
    into: "in"
  - from: "Start10"
    via: "next"
    to: "Call12"
    into: "in"
  - from: "PrepareApplicationView5"
    via: "next"
    to: "InteractionEnd6"
    into: "in"
  - from: "GetCatalog5"
    via: "next"
    to: "PrepareApplicationView5"
    into: "in"
  - from: "Start11"
    via: "next"
    to: "Call13"
    into: "in"
  - from: "PrepareApplicationView6"
    via: "next"
    to: "InteractionEnd5"
    into: "in"
  - from: "GetCategoryByUUID1"
    via: "next"
    to: "PrepareApplicationView6"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Call14"
    into: "in"
  - from: "Call14"
    via: "next"
    to: "GetCatalog4"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Call15"
    into: "in"
  - from: "Call15"
    via: "next"
    to: "GetCatalog1"
    into: "in"
  - from: "ExchangeSessionObject4"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Call16"
    into: "in"
  - from: "Call16"
    via: "next"
    to: "GetCatalog3"
    into: "in"
  - from: "Call12"
    via: "next"
    to: "Call17"
    into: "in"
  - from: "Call13"
    via: "next"
    to: "Call18"
    into: "in"
  - from: "Call18"
    via: "next"
    to: "GetCategoryByUUID1"
    into: "in"
  - from: "Call17"
    via: "next"
    to: "GetCatalog5"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Join8"
    into: "in3"
  - from: "KeyMapper1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "ExchangeSessionObject4"
    into: "in"
  - from: "Start12"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Start13"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Start14"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "Decision7"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "GetProductByUUID1"
    into: "in"
  - from: "GetProductByUUID1"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "Call6"
    via: "next"
    to: "CombineIterators1"
    into: "in"
  - from: "CombineIterators1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "End3"
    into: "in"
  - from: "GetProductByUUID1"
    via: "error"
    to: "JumpNode1"
    into: "in"
