flow: "ViewAuctionPreferences_52"
kind: "view"

entries:
  - id: "Start1"
    name: "VerifyPreferenceValues"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "UpdatePreferenceValues"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "GetPreferenceValues"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewAuctionPreferences_52-VerifyPreferenceValues"
  - id: "Call2"
    type: "call"
    ref: "ViewAuctionPreferences_52-UpdatePreferenceValues"
  - id: "Call3"
    type: "call"
    ref: "ViewAuctionPreferences_52-GetPreferenceValues"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "BidCancelPolicy"
      param.1.required: true
      param.1.rule: "\\d"
      param.2.name: "HiddenAuctionBidPolicy"
      param.2.required: true
      param.2.rule: "\\d"
      param.3.name: "BidAgentPolicy"
      param.3.required: true
      param.3.rule: "\\d"
      param.4.name: "AuctionItemPolicy"
      param.4.required: true
      param.4.rule: "\\d"
      param.5.name: "LimitedBidCancelPeriod"
      param.5.required: true
      param.5.rule: "\\d"
      param.6.name: "BidCancelPeriod"
      param.6.required: true
      param.6.rule: "\\d"
      webform-id: "RegFormUpdateAuctionPreference"
    bindings:
      WebForm: "RegFormUpdateAuctionPreference"
  - id: "End1"
    type: "end"
  - id: "End2"
    type: "end"
  - id: "End3"
    type: "end"
  - id: "End4"
    type: "end"
  - id: "End5"
    type: "end"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "BidAgentPolicy"
      Type: "Integer"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceIntValue: "BidAgentPolicy"
  - id: "GetDomainPreference2"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "HiddenAuctionBidPolicy"
      Type: "Integer"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceIntValue: "HiddenAuctionBidPolicy"
  - id: "GetDomainPreference3"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "AuctionItemPolicy"
      Type: "Integer"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceIntValue: "AuctionItemPolicy"
  - id: "GetDomainPreference4"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "BidCancelPolicy"
      Type: "Integer"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceIntValue: "BidCancelPolicy"
  - id: "GetDomainPreference5"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "LimitedBidCancelPeriod"
      Type: "Integer"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceIntValue: "LimitedBidCancelPeriod"
  - id: "GetDomainPreference6"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "BidCancelPeriod"
      Type: "Integer"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceIntValue: "BidCancelPeriod"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "RegFormUpdateAuctionPreference"
    bindings:
      WebForm: "RegFormUpdateAuctionPreference"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join10"
    type: "join"
  - id: "Join11"
    type: "join"
  - id: "Join12"
    type: "join"
  - id: "Join13"
    type: "join"
  - id: "Join14"
    type: "join"
  - id: "Join15"
    type: "join"
  - id: "Join16"
    type: "join"
  - id: "Join17"
    type: "join"
  - id: "Join18"
    type: "join"
  - id: "Join19"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join20"
    type: "join"
  - id: "Join21"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "BidAgentPolicy"
      DefaultPreferenceValue: 0
      Type: "Integer"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceIntValue: "BidAgentPolicy"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "AuctionItemPolicy"
      DefaultPreferenceValue: 0
      Type: "Integer"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceIntValue: "AuctionItemPolicy"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "HiddenAuctionBidPolicy"
      DefaultPreferenceValue: 0
      Type: "Integer"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceIntValue: "HiddenAuctionBidPolicy"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "BidCancelPolicy"
      DefaultPreferenceValue: 1
      Type: "Integer"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceIntValue: "BidCancelPolicy"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "channel/ChannelAuctionPreference_52"
  - id: "SetDomainPreference1"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "LimitedBidCancelPeriod"
      DefaultPreferenceValue: 12
      Type: "Integer"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceIntValue: "LimitedBidCancelPeriod"
  - id: "SetDomainPreference2"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "BidCancelPeriod"
      DefaultPreferenceValue: 1
      Type: "Integer"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceIntValue: "BidCancelPeriod"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "RegFormUpdateAuctionPreference"
    bindings:
      WebForm: "RegFormUpdateAuctionPreference"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "RegFormUpdateAuctionPreference"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "BidAgentPolicy"
      LocalizedString: "RegFormUpdateAuctionPreference_BidAgentPolicy"
  - id: "VerifyInteger2"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "HiddenAuctionBidPolicy"
      LocalizedString: "RegFormUpdateAuctionPreference_HiddenAuctionBidPolicy"
  - id: "VerifyInteger3"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "AuctionItemPolicy"
      LocalizedString: "RegFormUpdateAuctionPreference_AuctionItemPolicy"
  - id: "VerifyInteger4"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "BidCancelPolicy"
      LocalizedString: "RegFormUpdateAuctionPreference_BidCancelPolicy"
  - id: "VerifyInteger5"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "LimitedBidCancelPeriod"
      LocalizedString: "RegFormUpdateAuctionPreference_LimitedBidCancelPeriod"
  - id: "VerifyInteger6"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "BidCancelPeriod"
      LocalizedString: "RegFormUpdateAuctionPreference_BidCancelPeriod"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "CreateWebForm1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "Join4"
    into: "in2"
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "ValidateWebForm1"
    via: "error"
    to: "Join3"
    into: "in2"
  - from: "Join2"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Join5"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "VerifyInteger1"
    into: "in"
  - from: "ValidateWebForm1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "VerifyInteger2"
    into: "in"
  - from: "VerifyInteger2"
    via: "next"
    to: "VerifyInteger3"
    into: "in"
  - from: "VerifyInteger3"
    via: "next"
    to: "VerifyInteger4"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join9"
    into: "in1"
  - from: "VerifyInteger4"
    via: "error"
    to: "Join7"
    into: "in2"
  - from: "Join8"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "VerifyInteger3"
    via: "error"
    to: "Join8"
    into: "in2"
  - from: "Join9"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "VerifyInteger2"
    via: "error"
    to: "Join9"
    into: "in2"
  - from: "Start2"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "Join13"
    into: "in1"
  - from: "Join10"
    via: "next"
    to: "Join20"
    into: "in1"
  - from: "Join11"
    via: "next"
    to: "Join10"
    into: "in1"
  - from: "Pipelet4"
    via: "error"
    to: "Join11"
    into: "in2"
  - from: "Join12"
    via: "next"
    to: "Join11"
    into: "in1"
  - from: "Pipelet2"
    via: "error"
    to: "Join12"
    into: "in2"
  - from: "Join13"
    via: "next"
    to: "Join12"
    into: "in1"
  - from: "Pipelet3"
    via: "error"
    to: "Join13"
    into: "in2"
  - from: "Start3"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "GetDomainPreference1"
    via: "next"
    to: "GetDomainPreference2"
    into: "in"
  - from: "GetDomainPreference2"
    via: "next"
    to: "GetDomainPreference3"
    into: "in"
  - from: "GetDomainPreference3"
    via: "next"
    to: "GetDomainPreference4"
    into: "in"
  - from: "GetDomainPreference1"
    via: "error"
    to: "Join17"
    into: "in1"
  - from: "Join15"
    via: "next"
    to: "Join14"
    into: "in1"
  - from: "GetDomainPreference4"
    via: "error"
    to: "Join15"
    into: "in2"
  - from: "Join16"
    via: "next"
    to: "Join15"
    into: "in1"
  - from: "GetDomainPreference3"
    via: "error"
    to: "Join16"
    into: "in2"
  - from: "Join17"
    via: "next"
    to: "Join16"
    into: "in1"
  - from: "GetDomainPreference2"
    via: "error"
    to: "Join17"
    into: "in2"
  - from: "Call1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Call1"
    via: "ERROR"
    to: "Join2"
    into: "in2"
  - from: "Call2"
    via: "ERROR"
    to: "Join1"
    into: "in2"
  - from: "Join1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Join5"
    into: "in3"
  - from: "Join18"
    via: "next"
    to: "End5"
    into: "in"
  - from: "Join14"
    via: "next"
    to: "Join21"
    into: "in1"
  - from: "Join7"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Pipelet4"
    via: "next"
    to: "SetDomainPreference1"
    into: "in"
  - from: "GetDomainPreference4"
    via: "next"
    to: "GetDomainPreference5"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "Join19"
    into: "in1"
  - from: "VerifyInteger5"
    via: "error"
    to: "Join6"
    into: "in2"
  - from: "Join19"
    via: "next"
    to: "End2"
    into: "in"
  - from: "VerifyInteger6"
    via: "error"
    to: "Join19"
    into: "in2"
  - from: "VerifyInteger4"
    via: "next"
    to: "VerifyInteger5"
    into: "in"
  - from: "VerifyInteger5"
    via: "next"
    to: "VerifyInteger6"
    into: "in"
  - from: "VerifyInteger6"
    via: "next"
    to: "End1"
    into: "in"
  - from: "SetDomainPreference1"
    via: "next"
    to: "SetDomainPreference2"
    into: "in"
  - from: "SetDomainPreference2"
    via: "next"
    to: "End3"
    into: "in"
  - from: "SetDomainPreference1"
    via: "error"
    to: "Join10"
    into: "in2"
  - from: "Join20"
    via: "next"
    to: "End4"
    into: "in"
  - from: "SetDomainPreference2"
    via: "error"
    to: "Join20"
    into: "in2"
  - from: "GetDomainPreference5"
    via: "next"
    to: "GetDomainPreference6"
    into: "in"
  - from: "GetDomainPreference6"
    via: "next"
    to: "Join18"
    into: "in1"
  - from: "GetDomainPreference5"
    via: "error"
    to: "Join14"
    into: "in2"
  - from: "Join21"
    via: "next"
    to: "Join18"
    into: "in3"
  - from: "GetDomainPreference6"
    via: "error"
    to: "Join21"
    into: "in2"
