flow: "ViewOrganizationServices"
kind: "view"

entries:
  - id: "StartNode2"
    name: "GetCurrentServiceConfigurationRepository"
    mode: "private"
    strict: false
    inputs:
      - key: "OrganizationUUID"
        type: "java.lang.String"
        required: true
  - id: "StartNode22"
    name: "GetServiceGroups"
    mode: "private"
    strict: false
    inputs:
      - key: "ServiceConfigurationRepository"
        type: "com.intershop.component.service.capi.assignment.ServiceInstantiable"
        required: true
  - id: "StartNode29"
    name: "GetServiceDefinitionsOfServiceGroupX"
    mode: "private"
    strict: false
    inputs:
      - key: "GroupID"
        type: "java.lang.String"
        required: true
      - key: "ServiceConfigurationRepository"
        type: "com.intershop.component.service.capi.assignment.ServiceInstantiable"
        required: true
  - id: "StartNode3"
    name: "AllowServiceDefinition"
    mode: "private"
    strict: false
    inputs:
      - key: "ServiceConfigurationRepository"
        type: "com.intershop.component.service.capi.assignment.ServiceInstantiable"
        required: true
      - key: "ServiceDefinitionID"
        type: "java.lang.String"
        required: true
      - key: "CartridgeID"
        type: "java.lang.String"
        required: true
  - id: "StartNode30"
    name: "GetServiceConfigurationRepositoryByApplication"
    mode: "private"
    strict: false
    inputs:
      - key: "ApplicationBO"
        type: "com.intershop.component.application.capi.ApplicationBO"
        required: true
      - key: "OrganizationUUID"
        type: "java.lang.String"
        required: true
  - id: "StartNode4"
    name: "ProhibitServiceDefinition"
    mode: "private"
    strict: false
    inputs:
      - key: "ServiceConfigurationRepository"
        type: "com.intershop.component.service.capi.assignment.ServiceInstantiable"
        required: true
      - key: "ServiceDefinitionID"
        type: "java.lang.String"
        required: true
      - key: "CartridgeID"
        type: "java.lang.String"
        required: true

steps:
  - id: "AllowServiceDefinitionByOrganisationUUID1"
    type: "pipelet"
    ref: "AllowServiceDefinitionByOrganisationUUID"
    bindings:
      ServiceInstantiable: "ServiceConfigurationRepository"
      ServiceDefinition: "ServiceDefinition"
  - id: "CreateServiceDefinitionMap2"
    type: "pipelet"
    ref: "CreateServiceDefinitionMap"
  - id: "CreateServiceGroupList2"
    type: "pipelet"
    ref: "CreateServiceGroupList"
    bindings:
      SingleServiceGroup: "ServiceGroup"
  - id: "DecisionNode14"
    type: "decision"
    condition: "ServiceGroupIDs"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ServiceGroupList"
        type: "java.util.ArrayList<com.intershop.component.service.capi.service.ServiceGroup>"
        guaranteed: false
  - id: "EndNode10"
    type: "end"
    strict: true
  - id: "EndNode45"
    type: "end"
    strict: true
    outputs:
      - key: "ServiceGroupList"
        type: "java.util.ArrayList<com.intershop.component.service.capi.service.ServiceGroup>"
        guaranteed: false
  - id: "EndNode46"
    type: "end"
    strict: true
  - id: "EndNode47"
    type: "end"
    strict: true
    outputs:
      - key: "GroupedServiceDefinitions"
        type: "com.intershop.sellside.system.capi.service.ServiceDefinitionHelper"
        guaranteed: true
      - key: "ServiceGroup"
        type: "com.intershop.component.service.capi.service.ServiceGroup"
        guaranteed: true
  - id: "EndNode48"
    type: "end"
    strict: true
  - id: "EndNode49"
    type: "end"
    strict: true
    outputs:
      - key: "ServiceConfigurationRepository"
        type: "com.intershop.component.service.capi.service.ServiceConfigurationBORepository"
        guaranteed: true
  - id: "EndNode8"
    type: "end"
    strict: true
  - id: "GetApplicationBO1"
    type: "pipelet"
    ref: "GetApplicationBO"
  - id: "GetOrganizationServiceRepository1"
    type: "pipelet"
    ref: "GetOrganizationServiceRepository"
    bindings:
      OrganizationBO: "OrganizationBO"
  - id: "GetServiceDefinitionByID1"
    type: "pipelet"
    ref: "GetServiceDefinitionByID"
    bindings:
      cartridgeID: "CartridgeID"
      serviceDefinitionID: "ServiceDefinitionID"
  - id: "GetServiceDefinitionByID2"
    type: "pipelet"
    ref: "GetServiceDefinitionByID"
    bindings:
      cartridgeID: "CartridgeID"
      serviceDefinitionID: "ServiceDefinitionID"
  - id: "GetServiceDefinitions1"
    type: "pipelet"
    ref: "GetServiceDefinitions"
    bindings:
      GroupID: "GroupID"
      ServiceDefinitions: "ServiceDefinitions"
  - id: "GetServiceDefinitions2"
    type: "pipelet"
    ref: "GetServiceDefinitions"
    bindings:
      GroupID: "GroupID"
      ServiceDefinitions: "AllowedServiceDefinitions"
      ServiceInstantiable: "ServiceConfigurationRepository"
  - id: "GetServiceGroupByID4"
    type: "pipelet"
    ref: "GetServiceGroupByID"
    bindings:
      GroupID: "SingleGroupID"
      ServiceGroup: "ServiceGroup"
  - id: "GetServiceGroupByID5"
    type: "pipelet"
    ref: "GetServiceGroupByID"
    bindings:
      GroupID: "GroupID"
      ServiceGroup: "ServiceGroup"
  - id: "GetServiceGroups4"
    type: "pipelet"
    ref: "GetServiceGroups"
    bindings:
      ServiceGroupIDs: "ServiceGroupIDs"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewOrganizationServices-GetServiceConfigurationRepositoryByApplication"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_2: "OrganizationBORepository:OrganizationBOByID(OrganizationUUID)"
      OutValue_2: "OrganizationBO"
  - id: "KeyMapper6"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_2: "ApplicationBO:Repository(\"OrganizationBORepository\")"
      OutValue_2: "OrganizationBORepository"
  - id: "LoopNode4"
    type: "loop"
  - id: "ProhibitServiceDefinitionByOrganisationUUID1"
    type: "pipelet"
    ref: "ProhibitServiceDefinitionByOrganisationUUID"
    bindings:
      ServiceInstantiable: "ServiceConfigurationRepository"
      ServiceDefinition: "ServiceDefinition"

links:
  - from: "GetServiceGroupByID5"
    via: "next"
    to: "GetServiceDefinitions2"
    into: "in"
  - from: "LoopNode4"
    via: "next"
    to: "EndNode45"
    into: "in"
  - from: "StartNode22"
    via: "next"
    to: "GetServiceGroups4"
    into: "in"
  - from: "CreateServiceGroupList2"
    via: "next"
    to: "LoopNode4"
    into: "loop"
  - from: "StartNode2"
    via: "next"
    to: "GetApplicationBO1"
    into: "in"
  - from: "DecisionNode14"
    via: "yes"
    to: "LoopNode4"
    into: "in"
  - from: "GetApplicationBO1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "DecisionNode14"
    via: "no"
    to: "EndNode48"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "GetOrganizationServiceRepository1"
    into: "in"
  - from: "GetOrganizationServiceRepository1"
    via: "next"
    to: "EndNode49"
    into: "in"
  - from: "GetServiceDefinitions2"
    via: "next"
    to: "GetServiceDefinitions1"
    into: "in"
  - from: "KeyMapper6"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetServiceDefinitionByID2"
    into: "in"
  - from: "LoopNode4"
    via: "do"
    to: "GetServiceGroupByID4"
    into: "in"
  - from: "StartNode30"
    via: "next"
    to: "KeyMapper6"
    into: "in"
  - from: "GetServiceDefinitions1"
    via: "next"
    to: "CreateServiceDefinitionMap2"
    into: "in"
  - from: "AllowServiceDefinitionByOrganisationUUID1"
    via: "next"
    to: "EndNode8"
    into: "in"
  - from: "ProhibitServiceDefinitionByOrganisationUUID1"
    via: "next"
    to: "EndNode10"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "GetServiceDefinitionByID1"
    into: "in"
  - from: "GetServiceDefinitionByID1"
    via: "next"
    to: "ProhibitServiceDefinitionByOrganisationUUID1"
    into: "in"
  - from: "GetServiceDefinitionByID2"
    via: "next"
    to: "AllowServiceDefinitionByOrganisationUUID1"
    into: "in"
  - from: "CreateServiceDefinitionMap2"
    via: "next"
    to: "EndNode47"
    into: "in"
  - from: "StartNode29"
    via: "next"
    to: "GetServiceGroupByID5"
    into: "in"
  - from: "GetServiceGroupByID4"
    via: "error"
    to: "EndNode1"
    into: "in"
  - from: "GetServiceGroups4"
    via: "next"
    to: "DecisionNode14"
    into: "in"
  - from: "GetServiceGroupByID4"
    via: "next"
    to: "CreateServiceGroupList2"
    into: "in"
  - from: "GetServiceGroupByID5"
    via: "error"
    to: "EndNode46"
    into: "in"
