flow: "ViewPromotionRebateMessage"
kind: "view"

entries:
  - id: "Start1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start10"
    name: "GetLocales"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start11"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "UpdatePromotion"
    mode: "private"
    strict: true
    inputs:
      - key: "ExternalDetailsURL"
        type: "java.lang.String"
        required: true
      - key: "UseExternalURL"
        type: "java.lang.Boolean"
        required: true
      - key: "Icon"
        type: "java.lang.String"
        required: true
      - key: "Title"
        type: "java.lang.String"
        required: true
      - key: "LongTitle"
        type: "java.lang.String"
        required: true
      - key: "RuleDescription"
        type: "java.lang.String"
        required: true
      - key: "LegalContentMessage"
        type: "java.lang.String"
        required: true
      - key: "SelectedLocale"
        type: "com.intershop.beehive.core.capi.localization.LocaleInformation"
        required: true
      - key: "Promotion"
        type: "com.intershop.beehive.core.capi.domain.ExtensibleObject"
        required: true
      - key: "LocaleId"
        type: "java.lang.String"
        required: true
      - key: "DisableMessages"
        type: "java.lang.Boolean"
        required: true
  - id: "StartNode3"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddMultipleEntriesToMap1"
    type: "pipelet"
    ref: "AddMultipleEntriesToMap"
    config:
      Mode: "OverwriteValue"
      ValueSeparatorChar: ","
    bindings:
      InMap: "FormParameters"
      OutMap: "FormParameters"
      Value1: "Promotion:AttributeValue(\"LongTitle\",SelectedLocale):TextValue"
      Value2: "Promotion:AttributeValue(\"ConditionalProductDescription\",SelectedLocale):TextValue"
      Value3: "Promotion:AttributeValue(\"DiscountedProductDescription\",SelectedLocale):TextValue"
      Value4: "Promotion:AttributeValue(\"RuleDescription\",SelectedLocale):TextValue"
      Value5: "Promotion:AttributeValue(\"LegalContentMessage\",SelectedLocale):TextValue"
      Key1: "PromotionMessagingForm:LongTitle"
      Key2: "PromotionMessagingForm:ConditionalProductDescription"
      Key3: "PromotionMessagingForm:DiscountedProductDescription"
      Key4: "PromotionMessagingForm:RuleDescription"
      Key5: "PromotionMessagingForm:LegalContentMessage"
  - id: "AddMultipleEntriesToMap3"
    type: "pipelet"
    ref: "AddMultipleEntriesToMap"
    config:
      Mode: "OverwriteValue"
      ValueSeparatorChar: ","
    bindings:
      InMap: "FormParameters"
      OutMap: "FormParameters"
      Key1: "PromotionMessagingForm:DisableMessages"
      Value1: "Promotion:AttributeValue(\"DisableMessages\"):BooleanValue"
  - id: "AddMultipleEntriesToMap4"
    type: "pipelet"
    ref: "AddMultipleEntriesToMap"
    config:
      Mode: "OverwriteValue"
      ValueSeparatorChar: ","
    bindings:
      InMap: "FormParameters"
      OutMap: "FormParameters"
      Value3: "Promotion:AttributeValue(\"DetailsAsPopup\",SelectedLocale):BooleanValue"
      Key3: "PromotionMessagingForm:DetailsAsPopup"
      Key1: "PromotionMessagingForm:ExternalDetailsURL"
      Key2: "PromotionMessagingForm:UseExternalURL"
      Value1: "Promotion:AttributeValue(\"ExternalDetailsURL\",SelectedLocale):StringValue"
      Value2: "Promotion:AttributeValue(\"UseExternalURL\",SelectedLocale):BooleanValue"
      Key4: "PromotionMessagingForm:Icon"
      Value4: "Promotion:AttributeValue(\"Icon\",SelectedLocale):TextValue"
      Key5: "PromotionMessagingForm:Title"
      Value5: "Promotion:AttributeValue(\"Title\",SelectedLocale):TextValue"
  - id: "Call2"
    type: "call"
    ref: "This:Prefix"
  - id: "Call3"
    type: "call"
    ref: "This:GetLocales"
  - id: "CallNode1"
    type: "call"
    ref: "ViewPromotionRebateMessage-Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "ViewPromotionRebateMessage-UpdatePromotion"
    bindings:
      ConditionalProductDescription: "PromotionMessagingForm:ConditionalProductDescription:Value"
      DiscountedProductDescription: "PromotionMessagingForm:DiscountedProductDescription:Value"
      Icon: "PromotionMessagingForm:Icon:Value"
      LegalContentMessage: "PromotionMessagingForm:LegalContentMessage:Value"
      LongTitle: "PromotionMessagingForm:LongTitle:Value"
      RuleDescription: "PromotionMessagingForm:RuleDescription:Value"
      Title: "PromotionMessagingForm:Title:Value"
      ExternalDetailsURL: "PromotionMessagingForm:ExternalDetailsURL:Value"
      UseExternalURL: "PromotionMessagingForm:UseExternalURL:Value"
      LocaleId: "LocaleID"
      DisableMessages: "PromotionMessagingForm:DisableMessages:Value"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessPromotion-TouchPromotion"
    bindings:
      Iterator: "Promotion:Rebates"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "PromotionMessaging"
      FormResource: "PromotionMessaging"
    bindings:
      Form: "PromotionMessagingForm"
  - id: "CreateForm3"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "PromotionMessaging"
      FormResource: "PromotionMessaging"
    bindings:
      Form: "PromotionMessagingForm"
  - id: "CreateIteratorFromConfigValues1"
    type: "pipelet"
    ref: "CreateIteratorFromConfigValues"
    config:
      Delimiters: ","
      Values: "UseExternalURL,ExternalDetailsURL,Icon,Title,LongTitle,ConditionalProductDescription,DiscountedProductDescription,RuleDescription,LegalContentMessage,DisableMessages"
    bindings:
      ValuesString: "null"
      ValuesIterator: "AVNames"
  - id: "Decision2"
    type: "decision"
    condition: "PromotionUUID"
  - id: "Decision6"
    type: "decision"
    condition: "UpdateLocale"
  - id: "DecisionNode1"
    type: "decision"
    condition: "AVName"
  - id: "DecisionNode2"
    type: "decision"
    condition: "AVValue"
  - id: "DecisionNode3"
    type: "decision"
    condition: "AVName"
  - id: "DecisionNode4"
    type: "decision"
    condition: "AVName"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
    bindings:
      Locales: "AllLocales"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPromotionRebateMessage-Update"
      OutValue_1: "ViewPromotionRebateMessage-Edit"
      OutValue_2: "ViewPromotionRebateMessage-Edit"
      OutValue_3: "ViewPromotionReplication-SelectTarget"
      OutValue_4: "ViewPromotion-CopyDialog"
      OutValue_5: "ViewPromotion-Edit"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "update"
      Key_1: "setLocale"
      Key_2: "edit"
      Key_3: "selectStagingTarget"
      Key_4: "copyDialog"
      Key_5: "confirmDelete"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End5"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: true
  - id: "GetIndirectDictValue1"
    type: "pipelet"
    ref: "GetIndirectDictValue"
    bindings:
      KeyNameHolder: "AVName"
      MappedEntry: "AVValue"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
    bindings:
      Locale: "SelectedLocale"
      LocaleId: "LocaleID"
  - id: "GetLocale4"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetPromotionByUUID2"
    type: "pipelet"
    ref: "GetPromotionByUUID"
  - id: "GetTargetClusters1"
    type: "pipelet"
    ref: "GetTargetClusters"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode20"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "Jump6"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"Boolean\""
      OutValue_1: "AVType"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "UpdateLocale"
      OutValue_1: "SelectedLocale"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Locale"
      OutValue_1: "LocaleInformation"
      InValue_2: "\"Text\""
      OutValue_2: "AVType"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Locale"
      OutValue_1: "LocaleInformation"
      InValue_2: "\"Boolean\""
      OutValue_2: "AVType"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Locale"
      OutValue_1: "LocaleInformation"
      InValue_2: "\"String\""
      OutValue_2: "AVType"
  - id: "LoopNode1"
    type: "loop"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/PromotionMessaging"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"
  - id: "RemoveCustomAttribute2"
    type: "pipelet"
    ref: "RemoveCustomAttribute"
    bindings:
      AttributeName: "AVName"
      ExtensibleObject: "Promotion"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "LocaleInformation"
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewPromotionRebateMessage-Edit"
      ValueType: "Dictionary Value"
  - id: "SetFormParameterValues2"
    type: "pipelet"
    ref: "SetFormParameterValues"
    bindings:
      FormParameterValuesMap: "FormParameters"
  - id: "UpdateCustomAttribute2"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    bindings:
      ExtensibleObject: "Promotion"
      AttributeName: "AVName"
      AttributeType: "AVType"
      AttributeValue: "AVValue"
  - id: "ValidateForm2"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "PromotionMessagingForm"

links:
  - from: "Start11"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "GetPromotionByUUID2"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "DecisionNode2"
    via: "no"
    to: "UpdateCustomAttribute2"
    into: "in"
  - from: "UpdateCustomAttribute2"
    via: "next"
    to: "JoinNode20"
    into: "in3"
  - from: "RemoveCustomAttribute2"
    via: "next"
    to: "JoinNode20"
    into: "in1"
  - from: "JoinNode20"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "UpdateCustomAttribute2"
    via: "error"
    to: "JoinNode20"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join1"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "GetPromotionByUUID2"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "ValidateForm2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "SetFormParameterValues2"
    via: "next"
    to: "JoinNode10"
    into: "in3"
  - from: "Decision2"
    via: "yes"
    to: "GetPromotionByUUID2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetLocale4"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CreateForm3"
    into: "in"
  - from: "GetLocale4"
    via: "next"
    to: "CreateIteratorFromConfigValues1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "KeyMapper5"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "KeyMapper4"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "KeyMapper3"
    into: "in"
  - from: "GetIndirectDictValue1"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "KeyMapper4"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode4"
    via: "no"
    to: "DecisionNode1"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode4"
    via: "yes"
    to: "KeyMapper1"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "AddMultipleEntriesToMap3"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "Join7"
    into: "in3"
  - from: "AddMultipleEntriesToMap3"
    via: "next"
    to: "AddMultipleEntriesToMap1"
    into: "in"
  - from: "AddMultipleEntriesToMap4"
    via: "next"
    to: "SetFormParameterValues2"
    into: "in"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "AddMultipleEntriesToMap1"
    via: "next"
    to: "AddMultipleEntriesToMap4"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CreateIteratorFromConfigValues1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "Jump6"
    into: "in"
  - from: "JoinNode10"
    via: "next"
    to: "GetTargetClusters1"
    into: "in"
  - from: "GetTargetClusters1"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "Start10"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "CreateForm3"
    via: "next"
    to: "ValidateForm2"
    into: "in"
  - from: "GetLocale2"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "DetermineLocales1"
    via: "next"
    to: "Decision6"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "End5"
    into: "in"
  - from: "Decision6"
    via: "yes"
    to: "GetLocale2"
    into: "in"
  - from: "Decision6"
    via: "no"
    to: "KeyMapper2"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "End1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "ValidateForm2"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "LoopNode1"
    via: "do"
    to: "GetIndirectDictValue1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "RemoveCustomAttribute2"
    into: "in"
