flow: "ViewProductEditing"
kind: "view"

entries:
  - id: "StartNode1"
    name: "BackOffice"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "ViewProduct_"
      DefaultString2: "-Edit"
    bindings:
      String1: "ContentRepository:TypeCode"
      Concatenated: "EditingPipeline"
  - id: "CreateProductIdentifierLookupHelper1"
    type: "pipelet"
    ref: "CreateProductIdentifierLookupHelper"
    config:
      LookupType: "ProductDomainLookup"
    bindings:
      LookupHelper: "Helper"
      ProductDomain: "ContentRepository:RepositoryDomain"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ContentRepository:TypeCode"
  - id: "GetDomainByUUID1"
    type: "pipelet"
    ref: "GetDomainByUUID"
    bindings:
      Domain: "ProductDomain"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Request Locale"
  - id: "GetProductByUUID1"
    type: "pipelet"
    ref: "GetProductByUUID"
  - id: "GetRepositoryByUUID2"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      UUID: "ContentRepositoryUUID"
      Repository: "ContentRepository"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "JumpNode1"
    type: "jump"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewProduct-Edit"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "id"
      OutValue_1: "ProductUUID"
      InValue_2: "domainId"
      OutValue_2: "DomainUUID"

links:
  - from: "StartNode2"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JumpNode2"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "GetDomainByUUID1"
    via: "next"
    to: "GetProductByUUID1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "GetProductByUUID1"
    via: "next"
    to: "CreateProductIdentifierLookupHelper1"
    into: "in"
  - from: "GetRepositoryByUUID2"
    via: "next"
    to: "GetDomainByUUID1"
    into: "in"
  - from: "GetLocale2"
    via: "next"
    to: "GetRepositoryByUUID2"
    into: "in"
  - from: "CreateProductIdentifierLookupHelper1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "ConcatenateStrings1"
    into: "in"
