flow: "ViewGiftCertificates"
kind: "view"

entries:
  - id: "StartNode1"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: true
    inputs:
      - key: "SKU"
        type: "java.lang.String"
        required: true
      - key: "PLIID"
        type: "java.lang.String"
        required: false
      - key: "ApplicationBO"
        type: "com.intershop.component.application.capi.ApplicationBO"
        required: true
      - key: "CurrentProductRepository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: true
      - key: "CurrentOrganization"
        type: "com.intershop.component.organization.capi.Organization"
        required: true
      - key: "GiftCertificateForm_RecipientEmail"
        type: "java.lang.String"
        required: true
      - key: "GiftCertificateForm_RecipientName"
        type: "java.lang.String"
        required: true
      - key: "GiftCertificateForm_UserEmail"
        type: "java.lang.String"
        required: true
      - key: "GiftCertificateForm_UserName"
        type: "java.lang.String"
        required: true
      - key: "GiftCertificateForm_Greeting"
        type: "java.lang.String"
        required: true
  - id: "StartNode3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "UpdateGiftCertificateForm"
    mode: "private"
    strict: false
    inputs:
      - key: "SKU"
        type: "java.lang.String"
        required: true
      - key: "PLIID"
        type: "java.lang.String"
        required: true
  - id: "StartNode6"
    name: "ViewGiftCertificateForm"
    mode: "private"
    strict: false
    inputs:
      - key: "SKU"
        type: "java.lang.String"
        required: true
      - key: "PLIID"
        type: "java.lang.String"
        required: false

steps:
  - id: "AddEntryToMap10"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      Key: "GiftCertificateForm:RecipientName:QualifiedName"
      Value: "GiftCertificateForm:RecipientName:Value"
      InMap: "GiftCertificateFormParams"
      OutMap: "GiftCertificateFormParams"
  - id: "AddEntryToMap11"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      Key: "GiftCertificateForm:RecipientEmail:QualifiedName"
      Value: "GiftCertificateForm:RecipientEmail:Value"
      InMap: "GiftCertificateFormParams"
      OutMap: "GiftCertificateFormParams"
  - id: "AddEntryToMap12"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      Key: "GiftCertificateForm:UserName:QualifiedName"
      Value: "GiftCertificateForm:UserName:Value"
      InMap: "GiftCertificateFormParams"
      OutMap: "GiftCertificateFormParams"
  - id: "AddEntryToMap6"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "GiftCardParameters"
      Key: "\"GIFTCARD_RecipientEmail\""
      Value: "StaticAddress:EMail"
      OutMap: "GiftCardParameters"
  - id: "AddEntryToMap7"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "GiftCardParameters"
      Key: "\"GIFTCARD_RecipientName\""
      Value: "StaticAddress:FirstName"
      OutMap: "GiftCardParameters"
  - id: "AddEntryToMap8"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      Key: "GiftCertificateForm:UserEmail:QualifiedName"
      Value: "GiftCertificateForm:UserEmail:Value"
      InMap: "GiftCertificateFormParams"
      OutMap: "GiftCertificateFormParams"
  - id: "AddEntryToMap9"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      Key: "GiftCertificateForm:Greeting:QualifiedName"
      Value: "GiftCertificateForm:Greeting:Value"
      InMap: "GiftCertificateFormParams"
      OutMap: "GiftCertificateFormParams"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessCart-GetCurrentCart"
    bindings:
      Organization: "CurrentOrganization"
      User: "CurrentUser"
      BasketBORepository: "ApplicationBO:Extension(\"Basket\"):getBasketBORepository(CurrentOrganization)"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessUser-CheckLoggedIn"
  - id: "CallNode2"
    type: "call"
    ref: "ViewGiftCertificates-Update"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessCart-GetCurrentCart"
    bindings:
      Organization: "CurrentOrganization"
      User: "CurrentUser"
      BasketBORepository: "ApplicationBO:Extension(\"Basket\"):getBasketBORepository(CurrentOrganization)"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessUser-IsProductVisibleToCurrentUser"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessUser-IsProductVisibleToCurrentUser"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "GiftCertificateForm"
      FormResource: "GiftCertificateForm"
    bindings:
      FormAlias: "GiftCertificateForm"
      FormName: "GiftCertificateForm"
      FormResource: "GiftCertificateForm"
      Form: "GiftCertificateForm"
  - id: "CreateForm3"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "GiftCertificateForm"
      FormResource: "GiftCertificateForm"
    bindings:
      FormAlias: "GiftCertificateForm"
      FormName: "GiftCertificateForm"
      FormResource: "GiftCertificateForm"
      Form: "GiftCertificateForm"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PLIID"
  - id: "DecisionNode2"
    type: "decision"
    condition: "PLIID"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewGiftCertificates-UpdateGiftCertificateForm"
    bindings:
      Key_0: "addProduct"
      SelectionKey: "JumpTarget"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "GiftCertificateFormParams"
        type: "java.util.Map"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
  - id: "GetBasketProductLineItemBO1"
    type: "pipelet"
    ref: "GetBasketProductLineItemBO"
    bindings:
      BasketBO: "CurrentCartBO"
  - id: "GetBasketProductLineItemBO2"
    type: "pipelet"
    ref: "GetBasketProductLineItemBO"
    bindings:
      BasketBO: "CurrentCartBO"
  - id: "GetCurrencies2"
    type: "pipelet"
    ref: "GetCurrencies"
    config:
      Method: "Active Currencies"
    bindings:
      Domain: "CurrentOrganization:OrganizationDomain"
  - id: "GetCurrencies4"
    type: "pipelet"
    ref: "GetCurrencies"
    config:
      Method: "Active Currencies"
    bindings:
      Domain: "CurrentOrganization:OrganizationDomain"
  - id: "GetCustomAttributes1"
    type: "pipelet"
    ref: "GetCustomAttributes"
    bindings:
      ExtensibleObject: "ProductLineItem"
      AttributeValuesMap: "GiftCardParameters"
  - id: "GetLineItemByUUID1"
    type: "pipelet"
    ref: "GetLineItemByUUID"
    bindings:
      LineItemUUID: "PLIID"
      LineItem: "ProductLineItem"
  - id: "GetLineItemByUUID2"
    type: "pipelet"
    ref: "GetLineItemByUUID"
    bindings:
      LineItemUUID: "PLIID"
      LineItem: "ProductLineItem"
  - id: "GetProductBOBySKU1"
    type: "pipelet"
    ref: "GetProductBOBySKU"
    bindings:
      Domain: "CurrentProductRepository:RepositoryDomain"
      ProductBORepository: "ApplicationBO:Extension(\"Product\"):getProductBORepository(CurrentProductRepository:RepositoryDomain:UUID)"
  - id: "GetProductBOBySKU3"
    type: "pipelet"
    ref: "GetProductBOBySKU"
    bindings:
      Domain: "CurrentProductRepository:RepositoryDomain"
      ProductBORepository: "ApplicationBO:Extension(\"Product\"):getProductBORepository(CurrentProductRepository:RepositoryDomain:UUID)"
  - id: "GetRegisteredGiftCardService1"
    type: "pipelet"
    ref: "GetRegisteredGiftCardService"
    bindings:
      Domain: "CurrentOrganization:OwningDomain"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "InteractionNode3"
    type: "interaction"
  - id: "InteractionNode4"
    type: "interaction"
  - id: "InteractionNode5"
    type: "interaction"
  - id: "InteractionNode8"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
  - id: "JumpNode2"
    type: "jump"
    ref: "Error-ProductNotFound"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewCart-View"
  - id: "JumpNode7"
    type: "jump"
    ref: "Error-ProductNotFound"
  - id: "JumpNode9"
    type: "jump"
    ref: "ViewPage-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "BasketProductLineItemBO:Product"
      OutValue_1: "ProductBO"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "GiftCertificateFormParams"
      OutValue_1: "GiftCardParameters"
  - id: "KeyMapper31"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "BasketProductLineItemBO:Product"
      OutValue_1: "ProductBO"
  - id: "KeyMapper33"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"ViewUserAccount-ShowLogin\""
      InValue_2: "\"https\""
      InValue_4: "\"TargetPipeline\""
      InValue_5: "\"ViewGiftCertificates-ListAll\""
      OutValue_1: "TargetPipeline"
      OutValue_2: "Protocol"
      OutValue_3: "TargetSite"
      OutValue_4: "Parameter1_Name"
      OutValue_5: "Parameter1_Value"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "CurrentRequest:PipelineDictionary"
      InValue_3: "\"systempage.account.giftCertificates.pagelet2-systempage.account.giftCertificates\""
      InValue_2: "\"comp/account/giftcertificates/GiftCertificateList\""
      OutValue_1: "Dictionary"
      OutValue_3: "PageletEntryPointID"
      OutValue_2: "WorkingTemplate"
  - id: "KeyMapper6"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Repository(\"ServiceConfigurationBORepository\")"
      OutValue_1: "ServiceConfigurationBORepository"
  - id: "PrepareUserAccountViewOfGiftCards1"
    type: "pipelet"
    ref: "PrepareUserAccountViewOfGiftCards"
    bindings:
      GiftCardServiceID: "GiftCardService:ServiceID"
      Domain: "CurrentOrganization:OwningDomain"
  - id: "RemoveDictionaryValue0"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "TargetURL"
      RemoveFormValues: true
  - id: "ResolveStaticAddress1"
    type: "pipelet"
    ref: "ResolveStaticAddress"
    bindings:
      StaticAddressID: "ProductLineItem:ShipToAddressID"
  - id: "ResolveStaticAddress2"
    type: "pipelet"
    ref: "ResolveStaticAddress"
    bindings:
      StaticAddressID: "ProductLineItem:ShipToAddressID"
  - id: "UpdateCustomAttributes2"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "GIFTCARD_SenderName"
      Attribute_1_Type: "String"
      Attribute_2_Name: "GIFTCARD_SenderEmail"
      Attribute_2_Type: "String"
      Attribute_3_Name: "GIFTCARD_GreetingMessage"
      Attribute_3_Type: "Text"
    bindings:
      Attribute_1_Value: "GiftCardParameters:get(\"GiftCertificateForm_UserName\")"
      Attribute_2_Value: "GiftCardParameters:get(\"GiftCertificateForm_UserEmail\")"
      Attribute_3_Value: "GiftCardParameters:get(\"GiftCertificateForm_Greeting\")"
      ExtensibleObject: "ProductLineItem"
  - id: "UpdateStaticAddress1"
    type: "pipelet"
    ref: "UpdateStaticAddress"
    bindings:
      Email: "GiftCardParameters:get(\"GiftCertificateForm_RecipientEmail\")"
      FirstName: "GiftCardParameters:get(\"GiftCertificateForm_RecipientName\")"
      Address: "StaticAddress"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "GiftCertificateForm"

links:
  - from: "AddEntryToMap10"
    via: "next"
    to: "AddEntryToMap8"
    into: "in"
  - from: "AddEntryToMap11"
    via: "next"
    to: "AddEntryToMap10"
    into: "in"
  - from: "AddEntryToMap12"
    via: "next"
    to: "AddEntryToMap9"
    into: "in"
  - from: "AddEntryToMap6"
    via: "next"
    to: "AddEntryToMap7"
    into: "in"
  - from: "AddEntryToMap7"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "AddEntryToMap8"
    via: "next"
    to: "AddEntryToMap12"
    into: "in"
  - from: "AddEntryToMap9"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "CallNode11"
    via: "NOTLOGGEDIN"
    to: "RemoveDictionaryValue0"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "KeyMapper6"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "GetBasketProductLineItemBO2"
    into: "in"
  - from: "CallNode2"
    via: "INVALID GC FORM"
    to: "InteractionNode2"
    into: "in"
  - from: "CallNode2"
    via: "VALID GC FORM"
    to: "InteractionNode3"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "GetBasketProductLineItemBO1"
    into: "in"
  - from: "CallNode4"
    via: "NOT_VISIBLE"
    to: "JoinNode7"
    into: "in1"
  - from: "CallNode4"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode5"
    via: "NOT_VISIBLE"
    to: "JoinNode8"
    into: "in1"
  - from: "CallNode5"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CreateForm1"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "CreateForm3"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "GetProductBOBySKU3"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode3"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "GetProductBOBySKU1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "CallNode1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "JumpNode3"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "GetBasketProductLineItemBO1"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "GetBasketProductLineItemBO1"
    via: "next"
    to: "KeyMapper31"
    into: "in"
  - from: "GetBasketProductLineItemBO2"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "GetBasketProductLineItemBO2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "GetCurrencies2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "GetCurrencies4"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "GetCustomAttributes1"
    via: "next"
    to: "ResolveStaticAddress1"
    into: "in"
  - from: "GetLineItemByUUID1"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "GetLineItemByUUID1"
    via: "next"
    to: "GetCustomAttributes1"
    into: "in"
  - from: "GetLineItemByUUID2"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "GetLineItemByUUID2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "GetProductBOBySKU1"
    via: "error"
    to: "JoinNode8"
    into: "in1"
  - from: "GetProductBOBySKU1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "GetProductBOBySKU3"
    via: "error"
    to: "JoinNode7"
    into: "in1"
  - from: "GetProductBOBySKU3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "GetRegisteredGiftCardService1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "GetRegisteredGiftCardService1"
    via: "next"
    to: "PrepareUserAccountViewOfGiftCards1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "InteractionNode4"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "GetCurrencies2"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "GetCurrencies4"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "InteractionNode5"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JumpNode7"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "GetLineItemByUUID2"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "ResolveStaticAddress2"
    into: "in"
  - from: "KeyMapper31"
    via: "next"
    to: "GetLineItemByUUID1"
    into: "in"
  - from: "KeyMapper33"
    via: "next"
    to: "InteractionNode8"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "JumpNode9"
    into: "in"
  - from: "KeyMapper6"
    via: "next"
    to: "GetRegisteredGiftCardService1"
    into: "in"
  - from: "PrepareUserAccountViewOfGiftCards1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "PrepareUserAccountViewOfGiftCards1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "RemoveDictionaryValue0"
    via: "next"
    to: "KeyMapper33"
    into: "in"
  - from: "ResolveStaticAddress1"
    via: "next"
    to: "AddEntryToMap6"
    into: "in"
  - from: "ResolveStaticAddress2"
    via: "next"
    to: "UpdateCustomAttributes2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CreateForm3"
    into: "in"
  - from: "UpdateCustomAttributes2"
    via: "next"
    to: "UpdateStaticAddress1"
    into: "in"
  - from: "UpdateStaticAddress1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "ValidateForm1"
    via: "error"
    to: "EndNode3"
    into: "in"
  - from: "ValidateForm1"
    via: "next"
    to: "AddEntryToMap11"
    into: "in"
