flow: "ViewPagelet_comp_account_wishlist"
kind: "process"

entries:
  - id: "StartNode2"
    name: "GetWishlistBORepository"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode3"
    name: "GetWishlistSettings"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode4"
    name: "GetSearchForm"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "GetTargetWishlistBO"
    mode: "private"
    strict: true
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "DetermineOrganizations-Current"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessUser-CheckLoggedIn"
  - id: "CallNode2"
    type: "call"
    ref: "ViewPagelet_comp_account_wishlist-GetWishlistBORepository"
  - id: "CallNode3"
    type: "call"
    ref: "ViewPagelet_comp_account_wishlist-GetWishlistBORepository"
  - id: "CallNode4"
    type: "call"
    ref: "Prefix-DetermineApplication"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "WishlistSearchForm"
      FormResource: "WishlistSearchForm"
    bindings:
      Form: "WishlistSearchForm"
  - id: "DecisionNode1"
    type: "decision"
    condition: "WishlistSearchForm"
  - id: "DecisionNode15"
    type: "decision"
    condition: "UsePreferredWishlist"
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "WishlistBORepository"
        type: "com.intershop.component.wishlist.capi.WishlistBORepository"
        guaranteed: true
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "UsePreferredWishlist"
        type: "java.lang.Boolean"
        guaranteed: true
      - key: "PreferredWishlistBO"
        type: "com.intershop.component.wishlist.capi.WishlistBO"
        guaranteed: false
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "WishlistSearchForm"
        type: "com.intershop.beehive.core.capi.request.WebForm"
        guaranteed: false
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "WishlistBO"
        type: "com.intershop.component.wishlist.capi.WishlistBO"
        guaranteed: false
  - id: "GetCustomerBO2"
    type: "pipelet"
    ref: "GetCustomerBO"
    bindings:
      CustomerID: "CurrentUser:ID"
  - id: "GetPreferredWishlistBO1"
    type: "pipelet"
    ref: "GetPreferredWishlistBO"
    bindings:
      Wishlist: "PreferredWishlistBO"
  - id: "GetPreferredWishlistBO4"
    type: "pipelet"
    ref: "GetPreferredWishlistBO"
    bindings:
      Wishlist: "WishlistBO"
  - id: "GetUsePreferredWishlist1"
    type: "pipelet"
    ref: "GetUsePreferredWishlist"
  - id: "GetUsePreferredWishlist2"
    type: "pipelet"
    ref: "GetUsePreferredWishlist"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode22"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "KeyMapper12"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Customer\"):CustomerBORepository(CurrentOrganization)"
      OutValue_1: "CustomerBORepository"
  - id: "KeyMapper13"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CustomerBO:Extension(\"Wishlist\")"
      OutValue_1: "WishlistBORepository"

links:
  - from: "GetUsePreferredWishlist1"
    via: "next"
    to: "GetPreferredWishlistBO1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "GetCustomerBO2"
    via: "next"
    to: "KeyMapper13"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "KeyMapper12"
    via: "next"
    to: "GetCustomerBO2"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "KeyMapper12"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "KeyMapper13"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "JoinNode22"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "GetUsePreferredWishlist1"
    into: "in"
  - from: "GetPreferredWishlistBO1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "DecisionNode15"
    via: "yes"
    to: "GetPreferredWishlistBO4"
    into: "in"
  - from: "GetUsePreferredWishlist2"
    via: "next"
    to: "DecisionNode15"
    into: "in"
  - from: "GetPreferredWishlistBO4"
    via: "next"
    to: "JoinNode22"
    into: "in1"
  - from: "DecisionNode15"
    via: "no"
    to: "JoinNode22"
    into: "in2"
  - from: "CallNode3"
    via: "next"
    to: "GetUsePreferredWishlist2"
    into: "in"
  - from: "CallNode11"
    via: "NOTLOGGEDIN"
    to: "JoinNode3"
    into: "in2"
  - from: "StartNode5"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "CreateForm1"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode2"
    into: "in1"
