flow: "ViewCampaignReplication"
kind: "view"

entries:
  - id: "StartNode19"
    name: "SelectTarget"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode20"
    name: "StartReplication"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector4"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Object: "Campaign"
      InVector: "Campaigns"
      OutVector: "Campaigns"
      Iterator: "CampaignsIterator"
  - id: "CallNode10"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "CallNode27"
    type: "call"
  - id: "CallNode28"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "ConcatenateStrings2"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "\"ViewProcessList_\""
      String2: "\"-CreateProcess\""
      String1: "CurrentChannel:TypeCode"
      Concatenated: "CreateProcessPipeline"
  - id: "ConcatenateStrings3"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "\"ViewProcessList_\""
      String2: "\"-ListAll\""
      String1: "CurrentChannel:TypeCode"
      Concatenated: "ListAllProcessPipeline"
  - id: "CreatePageableFromIterator1"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    bindings:
      Iterator: "CampaignsIterator"
      Pageable: "SelectedObjects"
  - id: "DecisionNode8"
    type: "decision"
    condition: "CurrentChannel"
  - id: "GetPersistentObjectByUUID4"
    type: "pipelet"
    ref: "GetPersistentObjectByUUID"
    config:
      PersistentObjectPOClass: "com.intershop.component.marketing.internal.campaign.CampaignPO"
    bindings:
      UUID: "CampaignUUID"
      PersistentObject: "Campaign"
  - id: "GetTargetClusters1"
    type: "pipelet"
    ref: "GetTargetClusters"
  - id: "InteractionEnd12"
    type: "interaction"
  - id: "JoinNode5"
    type: "join"
  - id: "JumpNode10"
    type: "jump"
  - id: "JumpNode11"
    type: "jump"
    ref: "ViewCampaignList_52-Paging"
  - id: "JumpNode9"
    type: "jump"
    ref: "ViewProcessList-CreateProcess"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "\"ProcessReplicateObjects-Init\""
      InValue_2: "\"ProcessReplicateObjects-Process\""
      InValue_3: "\"ProcessReplicateObjects-Post\""
      InValue_4: "\"Marketing_ReplicatePromotions\""
      InValue_5: "\"SelectedObjects\""
      OutValue_1: "InitPipeline"
      OutValue_2: "ProcessPipeline"
      OutValue_3: "PostPipeline"
      OutValue_4: "JobName"
      OutValue_5: "PageableName"
      InValue_6: "SelectedObjects:ID"
      OutValue_6: "PageableID"
  - id: "LoopNode2"
    type: "loop"
  - id: "Pipelet13"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "UUIDIterator"
  - id: "PrepareApplicationView12"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "replication/ReplicateCampaignsWizardSelectTarget"
  - id: "RegisterPageable1"
    type: "pipelet"
    ref: "RegisterPageable"
    bindings:
      PageableName: "\"SelectedObjects\""
      see PageableName: "SelectedObjects"
      PageableID: "SelectedObjects:ID"

links:
  - from: "CreatePageableFromIterator1"
    via: "next"
    to: "RegisterPageable1"
    into: "in"
  - from: "DecisionNode8"
    via: "yes"
    to: "ConcatenateStrings2"
    into: "in"
  - from: "ConcatenateStrings2"
    via: "next"
    to: "ConcatenateStrings3"
    into: "in"
  - from: "Pipelet13"
    via: "error"
    to: "JumpNode11"
    into: "in"
  - from: "GetTargetClusters1"
    via: "next"
    to: "PrepareApplicationView12"
    into: "in"
  - from: "DecisionNode8"
    via: "no"
    to: "JumpNode9"
    into: "in"
  - from: "GetPersistentObjectByUUID4"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode28"
    via: "next"
    to: "Pipelet13"
    into: "in"
  - from: "AddObjectToVector4"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode27"
    via: "next"
    to: "JumpNode10"
    into: "in"
  - from: "ConcatenateStrings3"
    via: "next"
    to: "CallNode27"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "LoopNode2"
    via: "next"
    to: "CreatePageableFromIterator1"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "GetPersistentObjectByUUID4"
    into: "in"
  - from: "StartNode20"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "RegisterPageable1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "PrepareApplicationView12"
    via: "next"
    to: "InteractionEnd12"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "DecisionNode8"
    into: "in"
  - from: "StartNode19"
    via: "next"
    to: "CallNode28"
    into: "in"
  - from: "GetPersistentObjectByUUID4"
    via: "next"
    to: "AddObjectToVector4"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "Pipelet13"
    via: "next"
    to: "GetTargetClusters1"
    into: "in"
