flow: "ViewViewContext"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode14"
    name: "LookupViewContextLock"
    mode: "private"
    strict: true
    inputs:
      - key: "PreferenceDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
      - key: "LockingDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
      - key: "ViewContext"
        type: "com.intershop.component.pmc.capi.viewcontext.ViewContext"
        required: true
  - id: "StartNode15"
    name: "IsTabSwitched"
    mode: "private"
    strict: true
    inputs:
      - key: "ObjectUUID"
        type: "java.lang.String"
        required: true
  - id: "StartNode2"
    name: "View"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode23"
    name: "Lock"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode29"
    name: "Unlock"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "New"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode30"
    name: "CheckLock"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "InternalView"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "TemplateCallback"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "CreateFlagName"
    mode: "private"
    strict: true
    inputs:
      - key: "ObjectUUID"
        type: "java.lang.String"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewViewContext-Prefix"
  - id: "CallNode11"
    type: "call"
    ref: "ViewPageletEntryPointAssignments-GetSessionObjectNameForGetPipeline"
    bindings:
      ContentRepositoryUUID: "ContentRepository:UUID"
  - id: "CallNode19"
    type: "call"
    ref: "ProcessPageletEntryPointLock-Lookup"
    bindings:
      User: "CurrentUser"
      PageletEntryPoint: "ViewContext"
      PageletEntryPointLockedForMe: "ViewContextLockedForMe"
      PageletEntryPointLockOwner: "ViewContextLockOwner"
      PageletEntryPointLockLifetime: "ViewContextLockLifetime"
      PageletEntryPointLocking: "ViewContextLocking"
      PageletEntryPointLockExpirationDate: "ViewContextLockExpirationDate"
      PageletEntryPointLockedForOther: "ViewContextLockedForOther"
      PageletEntryPointLockCreationDate: "ViewContextLockCreationDate"
  - id: "CallNode2"
    type: "call"
    ref: "ViewViewContext-Prefix"
  - id: "CallNode21"
    type: "call"
    ref: "This:CreateFlagName"
  - id: "CallNode22"
    type: "call"
    ref: "ViewPageletEntryPointAssignments-DetermineGetPipeline"
    bindings:
      ContextObject: "ViewContext"
  - id: "CallNode3"
    type: "call"
    ref: "ViewViewContext-Prefix"
  - id: "CallNode36"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode37"
    type: "call"
    ref: "ProcessPageletEntryPointLock-Lock"
    bindings:
      LockingDomain: "ContentRepository:RepositoryDomain"
      PreferenceDomain: "ContentRepository:RepositoryDomain"
      User: "CurrentUser"
      PageletEntryPoint: "ViewContext"
  - id: "CallNode38"
    type: "call"
    ref: "ProcessPageletEntryPointLock-Unlock"
    bindings:
      LockingDomain: "ContentRepository:RepositoryDomain"
      User: "CurrentUser"
      PageletEntryPoint: "ViewContext"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessViewContext-Create"
    bindings:
      Domain: "ContentRepository:RepositoryDomain"
      ID: "ViewContextForm:Id:Value"
      Description: "ViewContextForm:Description:Value"
      DisplayName: "ViewContextForm:DisplayName:Value"
  - id: "CallNode5"
    type: "call"
    ref: "This:CreateFlagName"
    bindings:
      ObjectUUID: "ViewContextUUID"
  - id: "CallNode6"
    type: "call"
    ref: "ViewViewContext-IsTabSwitched"
    bindings:
      ObjectUUID: "ViewContext:UUID"
  - id: "CallNode7"
    type: "call"
    ref: "This:Prefix"
  - id: "ConcatenateStrings5"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "ObjectTabSwitched@"
    bindings:
      String1: "ObjectUUID"
      Concatenated: "FlagName"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "ViewContext"
      FormResource: "ViewContext"
    bindings:
      Form: "ViewContextForm"
  - id: "CreateForm5"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "ViewContext"
      FormResource: "ViewContext"
    bindings:
      Form: "ViewContextForm"
  - id: "DecisionNode1"
    type: "decision"
    condition: "IsTabSwitched"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ViewContextUUID"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DetermineLocales2"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewViewContext-Create"
      OutValue_2: "ViewViewContext-View"
      OutValue_1: "ViewViewContext-Update"
      OutValue_3: "ViewViewContext-Lock"
      OutValue_4: "ViewViewContext-Unlock"
      OutValue_5: "ViewViewContext-CheckLock"
      OutValue_6: "ViewViewContext-New"
    bindings:
      Key_0: "create"
      Key_1: "cancel"
      Key_2: "setLocale"
      Key_3: "lock"
      Key_4: "unlock"
      Key_5: "checkLock"
      Key_6: "setLocaleForNew"
      SelectionKey: "JumpTarget"
  - id: "DispatchFormActionByBreadcrumb1"
    type: "pipelet"
    ref: "DispatchFormActionByBreadcrumb"
    config:
      SplitMode: "PipelineAndParameter"
    bindings:
      Key_0: "cancel"
      OutValue_0: "ApplicationState:LastListView"
      OutValue_1: "ApplicationState:LastButOneBreadcrumb"
      Key_1: "back"
      SelectionKey: "JumpTarget"
  - id: "DispatchFormActionByBreadcrumb5"
    type: "pipelet"
    ref: "DispatchFormActionByBreadcrumb"
    config:
      SplitMode: "PipelineAndParameter"
    bindings:
      Key_0: "\"backToLastBreadcrumb\""
      OutValue_0: "ApplicationState:LastBreadcrumb"
      SelectionKey: "JumpTarget"
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "ViewContextLockCreationDate"
        type: "java.util.Date"
        guaranteed: false
      - key: "ViewContextLockedForOther"
        type: "java.lang.String"
        guaranteed: false
      - key: "ViewContextLockedForMe"
        type: "java.lang.String"
        guaranteed: false
      - key: "ViewContextLockExpirationDate"
        type: "java.util.Date"
        guaranteed: false
      - key: "ViewContextLockLifetime"
        type: "java.lang.Integer"
        guaranteed: false
      - key: "ViewContextLocking"
        type: "java.lang.String"
        guaranteed: false
      - key: "ViewContextLockOwner"
        type: "com.intershop.beehive.core.capi.user.User"
        guaranteed: false
      - key: "Resource"
        type: "com.intershop.beehive.core.capi.locking.Resource"
        guaranteed: false
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "FlagName"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode6"
    type: "end"
    strict: false
  - id: "EndNode9"
    type: "end"
    strict: true
    outputs:
      - key: "Flag"
        type: "java.lang.Object"
        guaranteed: true
  - id: "ExchangeSessionObject3"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SessionObjectName: "FlagName"
      SaveObject: "\"(Boolean)true\""
  - id: "ExchangeSessionObject4"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SaveObject: "GetPipeline"
      SessionObjectName: "SessionObjectNameForGetPipeline"
  - id: "ExchangeSessionObject5"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
    bindings:
      SessionObjectName: "FlagName"
      LoadObject: "Flag"
  - id: "ExchangeSessionObject6"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SessionObjectName: "FlagName"
      SaveObject: "null"
  - id: "FillForm0"
    type: "pipelet"
    ref: "FillForm"
    bindings:
      Form: "ViewContextForm"
  - id: "GetContextObjectRelationByQualifiedName1"
    type: "pipelet"
    ref: "GetContextObjectRelationByQualifiedName"
    bindings:
      Site: "ContentRepository:RepositoryDomain:Site"
      QualifiedName: "ViewContextForm:DefinitionQualifiedName:Value"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Request Locale"
  - id: "GetRepositoryByUUID0"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      UUID: "ContentRepositoryUUID"
      Repository: "ContentRepository"
  - id: "GetValuesFromContainer2"
    type: "pipelet"
    ref: "GetValuesFromContainer"
    config:
      OverwriteBehavior: true
    bindings:
      ContainerName: "ViewContext:UUID"
  - id: "GetViewContextByUUID2"
    type: "pipelet"
    ref: "GetViewContextByUUID"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "JoinNode0"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode40"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewViewContext-InternalView"
  - id: "JumpNode10"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "content/viewcontext/NewViewContext"
      SelectedMenuItem: "ContentOverview"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "content/viewcontext/ViewContext"
      SelectedMenuItem: "ContentOverview"
  - id: "RemoveValuesContainer1"
    type: "pipelet"
    ref: "RemoveValuesContainer"
    bindings:
      ContainerName: "ViewContext:UUID"
  - id: "SetFormError1"
    type: "pipelet"
    ref: "SetFormError"
    bindings:
      ErrorMsg: "\"error.ViewContextAlreadyExists\""
      TargetObject: "ViewContextForm:Id"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "ViewContextForm"

links:
  - from: "CallNode11"
    via: "next"
    to: "ExchangeSessionObject4"
    into: "in"
  - from: "CallNode19"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CreateForm5"
    into: "in"
  - from: "CallNode21"
    via: "next"
    to: "ExchangeSessionObject5"
    into: "in"
  - from: "CallNode22"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "CallNode36"
    via: "next"
    to: "CallNode38"
    into: "in"
  - from: "CallNode37"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "CallNode38"
    via: "next"
    to: "JoinNode40"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode4"
    via: "ERROR"
    to: "SetFormError1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "ExchangeSessionObject3"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "CallNode37"
    into: "in"
  - from: "ConcatenateStrings5"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "CreateForm5"
    via: "next"
    to: "FillForm0"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "RemoveValuesContainer1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetValuesFromContainer2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "GetViewContextByUUID2"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "DetermineLocales2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DispatchFormActionByBreadcrumb1"
    via: "error"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormActionByBreadcrumb1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DispatchFormActionByBreadcrumb5"
    via: "next"
    to: "JumpNode10"
    into: "in"
  - from: "ExchangeSessionObject3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "ExchangeSessionObject4"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "ExchangeSessionObject5"
    via: "next"
    to: "ExchangeSessionObject6"
    into: "in"
  - from: "ExchangeSessionObject6"
    via: "next"
    to: "EndNode9"
    into: "in"
  - from: "FillForm0"
    via: "next"
    to: "JoinNode0"
    into: "in1"
  - from: "GetContextObjectRelationByQualifiedName1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "GetContextObjectRelationByQualifiedName1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "GetLocale2"
    via: "next"
    to: "GetRepositoryByUUID0"
    into: "in"
  - from: "GetRepositoryByUUID0"
    via: "error"
    to: "JoinNode9"
    into: "in1"
  - from: "GetRepositoryByUUID0"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "GetValuesFromContainer2"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "GetValuesFromContainer2"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "GetViewContextByUUID2"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode0"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode10"
    via: "next"
    to: "DispatchFormActionByBreadcrumb5"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "DetermineLocales2"
    into: "in"
  - from: "JoinNode40"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "CallNode22"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionNode2"
    into: "in"
  - from: "RemoveValuesContainer1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "SetFormError1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "StartNode14"
    via: "next"
    to: "CallNode19"
    into: "in"
  - from: "StartNode15"
    via: "next"
    to: "CallNode21"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "DispatchFormActionByBreadcrumb1"
    into: "in"
  - from: "StartNode23"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "StartNode29"
    via: "next"
    to: "CallNode36"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "StartNode30"
    via: "next"
    to: "JoinNode40"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "StartNode7"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "ConcatenateStrings5"
    into: "in"
  - from: "ValidateForm1"
    via: "error"
    to: "JoinNode0"
    into: "in1"
  - from: "ValidateForm1"
    via: "next"
    to: "GetContextObjectRelationByQualifiedName1"
    into: "in"
