flow: "ViewOrderNotificationPreferences_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "View"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "OrderNotificationSettingsForm"
      FormResource: "OrderNotificationSettings"
    bindings:
      CurrentDomain: "CurrentDomain"
      Form: "OrderNotificationSettingsForm"
  - id: "CreateForm2"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "OrderNotificationSettingsForm"
      FormResource: "OrderNotificationSettings"
    bindings:
      CurrentDomain: "CurrentDomain"
      Form: "OrderNotificationSettingsForm"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_1: "ViewOrderNotificationPreferences_52-Update"
      OutValue_3: "ViewDomainPreference_52-Start"
    bindings:
      Key_1: "updateSettings"
      Key_3: "backToPrefs"
      SelectionKey: "JumpTarget"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "OrderNotificationEmailFrom"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceStringValue: "OrderNotificationEmailFrom"
  - id: "GetDomainPreference2"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "OrderNotificationEmailSubject"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceStringValue: "OrderNotificationEmailSubject"
  - id: "GetDomainPreference3"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "OrderNotificationEmailTemplate"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceStringValue: "OrderNotificationEmailTemplate"
  - id: "GetDomainPreference4"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "OrderNotificationSendNotification"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceStringValue: "OrderNotificationSendNotification"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionNode0"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewOrderNotificationPreferences_52-View"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "OrderNotificationSendNotification"
      DefaultPreferenceValue: "no"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceKey: "null"
      PreferenceStringValue: "OrderNotificationSettingsForm_SendNotification"
      PreferenceValue: "null"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "OrderNotificationEmailFrom"
      DefaultPreferenceValue: false
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceKey: "null"
      PreferenceStringValue: "OrderNotificationSettingsForm_EmailFrom"
      PreferenceValue: "null"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "OrderNotificationEmailSubject"
      DefaultPreferenceValue: false
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceKey: "null"
      PreferenceStringValue: "OrderNotificationSettingsForm_EmailSubject"
      PreferenceValue: "null"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "OrderNotificationEmailTemplate"
      DefaultPreferenceValue: false
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceKey: "null"
      PreferenceStringValue: "OrderNotificationSettingsForm_EmailTemplate"
      PreferenceValue: "null"
  - id: "PrepareApplicationView0"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "channel/OrderNotificationPreferences_52"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "channel/OrderNotificationPreferences_52"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewOrderNotificationPreferences_52-View"
  - id: "SetFormParameterValue0"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      Value: "OrderNotificationEmailFrom"
      FormParameter: "OrderNotificationSettingsForm:EmailFrom"
  - id: "SetFormParameterValue1"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      Value: "OrderNotificationEmailSubject"
      FormParameter: "OrderNotificationSettingsForm:EmailSubject"
  - id: "SetFormParameterValue2"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      Value: "OrderNotificationEmailTemplate"
      FormParameter: "OrderNotificationSettingsForm:EmailTemplate"
  - id: "SetFormParameterValue3"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      Value: "OrderNotificationSendNotification"
      FormParameter: "OrderNotificationSettingsForm:SendNotification"
  - id: "SetFormParameterValue4"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      Value: "OrderNotificationSettingsForm_SendNotification"
      FormParameter: "OrderNotificationSettingsForm:SendNotification"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "OrderNotificationSettingsForm"

links:
  - from: "CreateForm1"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "CreateForm2"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "GetDomainPreference1"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "GetDomainPreference1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "GetDomainPreference2"
    via: "error"
    to: "JoinNode9"
    into: "in1"
  - from: "GetDomainPreference2"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "GetDomainPreference3"
    via: "error"
    to: "JoinNode10"
    into: "in1"
  - from: "GetDomainPreference3"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "GetDomainPreference4"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetDomainPreference4"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode10"
    via: "next"
    to: "SetFormParameterValue2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "SetFormParameterValue3"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "SetFormParameterValue0"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "SetFormParameterValue1"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Pipelet2"
    via: "error"
    to: "JoinNode6"
    into: "in1"
  - from: "Pipelet2"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "Pipelet4"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "Pipelet4"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "Pipelet5"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "Pipelet5"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "PrepareApplicationView0"
    via: "next"
    to: "InteractionNode0"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "SetFormParameterValue0"
    via: "next"
    to: "GetDomainPreference2"
    into: "in"
  - from: "SetFormParameterValue1"
    via: "next"
    to: "GetDomainPreference3"
    into: "in"
  - from: "SetFormParameterValue2"
    via: "next"
    to: "GetDomainPreference4"
    into: "in"
  - from: "SetFormParameterValue3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "SetFormParameterValue4"
    via: "next"
    to: "PrepareApplicationView0"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "CreateForm2"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "ValidateForm1"
    via: "error"
    to: "SetFormParameterValue4"
    into: "in"
  - from: "ValidateForm1"
    via: "next"
    to: "Pipelet2"
    into: "in"
