flow: "ViewChannelCatalogCustomAttributes_52"
kind: "view"

entries:
  - id: "Start14"
    name: "DispatchCA"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "ManageCA"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "ConfirmDeleteCA"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "DeleteCA"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "CreateCA"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "UpdateCA"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "PagingCA"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "UpdateMCA"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "ResetMCA"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewCatalog-GetCatalog"
  - id: "CallNode1"
    type: "call"
    ref: "ViewChannelCatalogCustomAttributes_52-Prefix"
  - id: "CallNode10"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode11"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode12"
    type: "call"
    ref: "ViewChannelCatalogCustomAttributes_52-Prefix"
  - id: "CallNode13"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode14"
    type: "call"
    ref: "ProcessCustomAttributes-GetPageable"
  - id: "CallNode15"
    type: "call"
    ref: "ProcessCustomAttributes-CreatePageable"
  - id: "CallNode16"
    type: "call"
    ref: "ProcessCustomAttributes-SetPage"
  - id: "CallNode17"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "CallNode18"
    type: "call"
    ref: "ViewChannelCatalogCustomAttributes_52-Prefix"
  - id: "CallNode19"
    type: "call"
    ref: "ProcessSearchEngineAttributes-CreateCategorytMetaTags"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessCustomAttributes-Remove"
  - id: "CallNode20"
    type: "call"
    ref: "ViewChannelCatalogCustomAttributes_52-Prefix"
  - id: "CallNode21"
    type: "call"
    ref: "ProcessPreviewApplication-GetPreferredPreviewApplication"
    bindings:
      BackofficeApplicationBO: "ApplicationBO"
      ChannelRepository: "CurrentChannel"
      User: "CurrentUser"
      ApplicationBO: "TargetApplicationBO"
  - id: "CallNode29"
    type: "call"
    ref: "ProcessSearchEngineAttributes-UpdateSearchEngineAttributes"
    bindings:
      ExtensibleObject: "Category"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessCustomAttributes-Create"
  - id: "CallNode4"
    type: "call"
    ref: "ViewChannelCatalogCustomAttributes_52-Prefix"
  - id: "CallNode5"
    type: "call"
    ref: "ViewChannelCatalogCustomAttributes_52-Prefix"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "CallNode7"
    type: "call"
    ref: "ViewChannelCatalogCustomAttributes_52-Prefix"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessCustomAttributes-Update"
  - id: "CallNode9"
    type: "call"
    ref: "ViewChannelCatalogCustomAttributes_52-Prefix"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelCatalogCustomAttributes_52-CreateCA"
      OutValue_1: "ViewChannelCatalogCustomAttributes_52-UpdateCA"
      OutValue_2: "ViewChannelCatalogCustomAttributes_52-ConfirmDeleteCA"
      OutValue_3: "ViewChannelCatalogCustomAttributes_52-DeleteCA"
      OutValue_4: "ViewChannelCatalogCustomAttributes_52-PagingCA"
      OutValue_5: "ViewChannelCatalogList_52-ListAll"
      PagingPipeline: "ViewChannelCatalogCustomAttributes_52-PagingCA"
      OutValue_6: "ViewChannelCatalogCustomAttributes_52-ManageCA"
      OutValue_7: "ViewChannelCatalogCustomAttributes_52-UpdateMCA"
      OutValue_8: "ViewChannelCatalogCustomAttributes_52-ResetMCA"
    bindings:
      Key_0: "CreateCA"
      Key_1: "UpdateCA"
      Key_2: "ConfirmDeleteCA"
      Key_3: "DeleteCA"
      Key_4: "CancelDeleteCA"
      Key_5: "backToList"
      SelectionKey: "JumpTarget"
      Key_6: "ManageCA"
      Key_7: "UpdateMCA"
      Key_8: "ResetMCA"
  - id: "End1"
    type: "end"
    strict: false
  - id: "GetApplicationByUUID1"
    type: "pipelet"
    ref: "GetApplicationByUUID"
    bindings:
      ApplicationUUID: "TargetApplicationBO:ID"
      Application: "TargetApplication"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewChannelCatalogList_52-ListAll"
  - id: "Jump17"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewChannelCatalogCustomAttributes_52-ManageCA"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewChannelCatalogCustomAttributes_52-PagingCA"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewChannelCatalogCustomAttributes_52-PagingCA"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentChannel:Domain"
      OutValue_1: "CatalogOrganizationDomain"
      InValue_2: "CurrentProductRepository:RepositoryDomain"
      OutValue_2: "ProductDomain"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Category"
      OutValue_1: "ExtensibleObject"
      InValue_2: "CurrentChannel:Domain:Site:Domain:DomainName"
      OutValue_2: "DomainName"
  - id: "KeyMapper7"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Category"
      OutValue_1: "ExtensibleObject"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Catalog:Root"
      OutValue_1: "Category"
  - id: "Pipelet15"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "UUIDIterator"
      OutValue_1: "CustomAttributeNames"
      InValue_2: "Catalog"
      OutValue_2: "ExtensibleObject"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "InvalidatePageLocatorPageable"
    config:
      DefaultPageLocatorName: "AttributesLocator"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "GetCustomAttributes"
    config:
      FilteredAttributes: "META_*;displayName;shortDescription;PRODUCT_SORTING_*;SUBCATEGORY_SORTING_*;ShowInMenu;ClassificationType"
    bindings:
      ExtensibleObject: "Catalog"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Catalog"
      OutValue_1: "ExtensibleObject"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Catalog"
      OutValue_1: "ExtensibleObject"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Catalog"
      OutValue_1: "ExtensibleObject"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelCatalogs"
      WorkingTemplate: "catalog/CatalogCustomAttributes_52"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "MetaTitleGenerate"
      Value: "automatic"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "MetaDescriptionGenerate"
      Value: "automatic"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "MetaKeywordsGenerate"
      Value: "automatic"
      ValueType: "Dictionary Value"

links:
  - from: "CallNode16"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode9"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "CallNode14"
    via: "ERROR"
    to: "JoinNode1"
    into: "in2"
  - from: "CallNode14"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "Call1"
    via: "ERROR"
    to: "Jump1"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "CallNode17"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode17"
    via: "next"
    to: "JoinNode4"
    into: "in2"
  - from: "StartNode4"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "Start14"
    via: "next"
    to: "DispatchFormAction2"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "Pipelet15"
    into: "in"
  - from: "DispatchFormAction2"
    via: "next"
    to: "Jump17"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "CallNode15"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Pipelet7"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "Pipelet15"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "CallNode16"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "CallNode15"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "Pipelet6"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "StartNode5"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "KeyMapper7"
    via: "next"
    to: "CallNode29"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "CallNode19"
    into: "in"
  - from: "CallNode19"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "KeyMapper7"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "CallNode20"
    into: "in"
  - from: "CallNode29"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "CallNode21"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "CallNode18"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "CallNode18"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "CallNode21"
    via: "next"
    to: "GetApplicationByUUID1"
    into: "in"
  - from: "GetApplicationByUUID1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GetApplicationByUUID1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "JoinNode3"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "CallNode20"
    via: "next"
    to: "JoinNode2"
    into: "in1"
