flow: "ViewImageViewList_32"
kind: "view"

entries:
  - id: "Start1"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "SetPrimaryImageViewFlag"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "DetermineOldPageSizeAndPageNumber"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode4"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Prefix"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode6"
    name: "ListSorted"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "ListSortedPostDeletion"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode10"
    type: "call"
    ref: "ProcessImageView-CheckIsPrimaryViewSeleted"
    bindings:
      Domain: "CurrentChannel:Domain"
  - id: "CallNode11"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode12"
    type: "call"
    ref: "ProcessImageView-GetOrganizationPrimaryViewID"
    bindings:
      Domain: "ImageDefinitionDomain"
  - id: "CallNode13"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode14"
    type: "call"
    ref: "ProcessPaging-GetPageLocatorPageable"
    bindings:
      PageLocatorName: "\"ImageViewListLocator\""
  - id: "CallNode16"
    type: "call"
    ref: "ProcessPaging-SetPageSize"
    bindings:
      Pageable: "ImageViews"
  - id: "CallNode17"
    type: "call"
    ref: "ViewImageViewList_32-DetermineOldPageSizeAndPageNumber"
  - id: "CallNode18"
    type: "call"
    ref: "ProcessImage-DetermineImageDefinitionDomain"
    bindings:
      PreferenceDomain: "CurrentChannel:Domain"
  - id: "CallNode19"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode2"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode20"
    type: "call"
    ref: "ViewImageViewList_32-DetermineOldPageSizeAndPageNumber"
  - id: "CallNode21"
    type: "call"
    ref: "ProcessPaging-SetPageSize"
  - id: "CallNode22"
    type: "call"
    ref: "ProcessImage-DetermineImageDefinitionDomain"
    bindings:
      PreferenceDomain: "CurrentChannel:Domain"
  - id: "CallNode23"
    type: "call"
    ref: "ProcessImageView-GetAllSorted"
    bindings:
      Domain: "ImageDefinitionDomain"
  - id: "CallNode24"
    type: "call"
    ref: "ProcessPaging-SetPageNumber"
    bindings:
      Pageable: "ImageViews"
  - id: "CallNode25"
    type: "call"
    ref: "ProcessImage-DetermineImageDefinitionDomain"
    bindings:
      PreferenceDomain: "CurrentChannel:Domain"
  - id: "CallNode26"
    type: "call"
    ref: "ProcessImage-DetermineImageDefinitionDomain"
    bindings:
      PreferenceDomain: "CurrentChannel:Domain"
  - id: "CallNode27"
    type: "call"
    ref: "ProcessImage-DetermineImageDefinitionDomain"
    bindings:
      PreferenceDomain: "CurrentChannel:Domain"
  - id: "CallNode28"
    type: "call"
    ref: "ProcessImageView-GetAllSorted"
    bindings:
      Domain: "ImageDefinitionDomain"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessImageView-SetPrimaryImageViewID"
    bindings:
      Domain: "ImageDefinitionDomain"
      ImageViewID: "PrimaryImageViewID"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessImageView-Get"
    bindings:
      Domain: "CurrentChannel:Domain"
      ImageViewBORepository: "ApplicationBO:Extension(\"Image\"):ImageViewBORepository(CurrentChannel:RepositoryDomain:UUID)"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessImageView-Delete"
    bindings:
      Domain: "ImageDefinitionDomain"
  - id: "CallNode7"
    type: "call"
    ref: "ProcessPaging-SetPageNumber"
    bindings:
      Pageable: "ImageViews"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessImageView-CheckIsPrimaryViewSeleted"
    bindings:
      Domain: "ImageDefinitionDomain"
  - id: "CallNode9"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PrimaryImageViewID"
  - id: "DecisionNode2"
    type: "decision"
    condition: "confirmDelete"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewImageView_32-New"
      OutValue_1: "ViewImageViewList_32-SetPrimaryImageViewFlag"
      OutValue_2: "ViewImageViewList_32-ListSorted"
      OutValue_3: "ViewImageViewList_32-Delete"
      OutValue_4: "ViewImageViewList_32-ListSorted"
      PagingPipeline: "ViewImageViewList_32-Paging"
      DefaultPageNumberPrefix: "PageNumber_"
      DefaultPageSizePrefix: "PageSize_"
    bindings:
      Key_0: "new"
      SelectionKey: "JumpTarget"
      Key_1: "apply"
      Key_2: "confirmDelete"
      Key_3: "delete"
      Key_4: "cancel"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "PageSize"
        type: "java.lang.String"
        guaranteed: false
      - key: "PageNumber"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "SessionRegistrationID"
        type: "java.lang.String"
        guaranteed: true
  - id: "GetPageLocator3"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      RestorePageLocatorDictionary: "False"
      UsePageLocatorHistory: false
      DefaultPageLocatorName: "ImageViewListLocator"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InvalidatePageLocatorPageable11"
    type: "pipelet"
    ref: "InvalidatePageLocatorPageable"
    config:
      DefaultPageLocatorName: "ImageViewListLocator"
    bindings:
      PageLocatorName: "null"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewImageViewList_32-ListSorted"
  - id: "JumpNode2"
    type: "jump"
    ref: "This:ListSortedPostDeletion"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewImageViewList_32-ListAll"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "PageLocator:PageSize"
      OutValue_1: "PageSize"
      InValue_2: "PageLocator:PageNumber"
      OutValue_2: "PageNumber"
  - id: "Loop1"
    type: "loop"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ImageManagement"
      WorkingTemplate: "image/ImageViewList_32"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewImageViewList_32-ListAll"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "SessionRegistrationID"
      Value: "CB_ImageViewList"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultPageLocatorName: "ImageViewListLocator"
      DefaultHandlerPipeline: "ViewImageViewList_32-Paging"
      UsePageLocatorHistory: false
    bindings:
      Pageable: "ImageViews"
      HandlerPipeline: "null"
      PageLocatorName: "null"
  - id: "ToString1"
    type: "pipelet"
    ref: "ToString"
    bindings:
      Object1: "PageSize"
      String1: "PageSize"
      Object10: "PageNumber"
      String10: "PageNumber"
  - id: "VerifyBoolean1"
    type: "pipelet"
    ref: "VerifyBoolean"
    bindings:
      NoneLocalizedString: "\"true\""
      BooleanValue: "PrimaryImageViewFlag"

links:
  - from: "Pipelet8"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "ToString1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "CallNode26"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "CallNode17"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "CallNode8"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "CallNode17"
    via: "next"
    to: "InvalidatePageLocatorPageable11"
    into: "in"
  - from: "GetPageLocator3"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetPageLocator3"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GetPageLocator3"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "Loop1"
    via: "do"
    to: "CallNode5"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "CallNode28"
    into: "in"
  - from: "VerifyBoolean1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode28"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode8"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode14"
    via: "next"
    to: "CallNode21"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "CallNode16"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode3"
    into: "in2"
  - from: "Start4"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode25"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "CallNode21"
    via: "next"
    to: "CallNode24"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "CallNode23"
    into: "in"
  - from: "CallNode5"
    via: "ERROR"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "VerifyBoolean1"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "InvalidatePageLocatorPageable11"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "CallNode22"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode20"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode6"
    into: "in2"
  - from: "VerifyBoolean1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "JoinNode2"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "SetPageLocator1"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "CallNode27"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "CallNode12"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode14"
    via: "Error"
    to: "JumpNode3"
    into: "in"
  - from: "CallNode23"
    via: "next"
    to: "CallNode16"
    into: "in"
  - from: "CallNode24"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "CallNode19"
    via: "next"
    to: "CallNode20"
    into: "in"
  - from: "ToString1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "CallNode18"
    into: "in"
  - from: "CallNode18"
    via: "next"
    to: "CallNode19"
    into: "in"
  - from: "CallNode22"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "CallNode25"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode26"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode27"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "JoinNode8"
    into: "in3"
