flow: "ViewImpex"
kind: "view"

entries:
  - id: "Start1"
    name: "DownloadFile"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Monitor"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "DeleteImpexJobs"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessImpexJob-Delete"
  - id: "Call2"
    type: "call"
    ref: "ProcessJobConfigurationSearch-Search"
  - id: "Call3"
    type: "call"
    ref: "ProcessImpexJob-GetLogContent"
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "Call5"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call6"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call7"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "Call8"
    type: "call"
    ref: "ProcessJobConfigurationSearch-Search"
  - id: "CombineIterators1"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Concatenate Iterators"
    bindings:
      Iterator1: "ImpexJobsCatalog"
      Iterator2: "ImpexJobsShipping"
      Iterator: "ImpexJobs"
  - id: "Decision1"
    type: "decision"
    condition: "JobConfiguration:Status"
  - id: "Decision2"
    type: "decision"
    condition: "ConfirmDeleteImpexJobs"
  - id: "DetermineUnit1"
    type: "pipelet"
    ref: "DetermineUnit"
    bindings:
      Unit: "UnitDomain"
      UnitName: "JobConfiguration:DomainName"
  - id: "GetBinaryFileContent1"
    type: "pipelet"
    ref: "GetBinaryFileContent"
    config:
      UnitDirectory: "IMPEX_DIR"
  - id: "GetJobConfiguration1"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "GetJobConfiguration2"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "GetJobConfiguration3"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "JobConfigurationUUID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "Error-FileNotFound"
  - id: "Jump2"
    type: "jump"
    ref: "Error-Start"
  - id: "Jump3"
    type: "jump"
    ref: "ViewImpex-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "Error-Start"
  - id: "JumpNode4"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentOrganization:Domain"
      OutValue_1: "JobDomain"
      InValue_2: "\"ProcessCatalogImpex\""
      OutValue_2: "JobName"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Jobs"
      OutValue_1: "ImpexJobsShipping"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentOrganization:Domain"
      OutValue_1: "JobDomain"
      InValue_2: "\"ProcessShippingImpex\""
      OutValue_2: "JobName"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Jobs"
      OutValue_1: "ImpexJobsCatalog"
  - id: "Loop1"
    type: "loop"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewImpex-Start"
      OutValue_1: "ViewCatalogImport-SelectFile"
      OutValue_2: "ViewCatalogExport-SelectCatalog"
      OutValue_3: "ViewCatalogImportFiles-BrowseDirectory"
      OutValue_4: "ViewCatalogExportFiles-BrowseDirectory"
      OutValue_5: "ViewImpex-Start"
      OutValue_6: "ViewImpex-DeleteImpexJobs"
      OutValue_7: "ViewPostalDataImport-SelectFile"
      OutValue_8: "ViewPostalDataExport-SelectConfiguration"
    bindings:
      Key_0: "Refresh"
      SelectionKey: "JumpTarget"
      Key_1: "CategoryImport"
      Key_2: "CategoryExport"
      Key_3: "ImportFiles"
      Key_4: "ExportFiles"
      Key_5: "ConfirmDeleteImpexJobs"
      Key_6: "DeleteImpexJobs"
      Key_7: "PostalDataImport"
      Key_8: "PostalDataExport"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Import & Export"
      WorkingTemplate: "impex/CatalogImpexMonitor"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Import & Export"
      WorkingTemplate: "impex/ImpexOverview"

links:
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "Join6"
    into: "in3"
  - from: "Join5"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "CombineIterators1"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Loop1"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "GetJobConfiguration3"
    via: "error"
    to: "Join5"
    into: "in3"
  - from: "Loop1"
    via: "do"
    to: "GetJobConfiguration3"
    into: "in"
  - from: "GetJobConfiguration3"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Decision1"
    via: "yes"
    to: "Call3"
    into: "in"
  - from: "GetJobConfiguration2"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "GetJobConfiguration2"
    via: "error"
    to: "Join4"
    into: "in1"
  - from: "Call3"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Decision1"
    via: "no"
    to: "Join3"
    into: "in3"
  - from: "Join4"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Call3"
    via: "Error"
    to: "Join4"
    into: "in2"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "GetJobConfiguration2"
    into: "in"
  - from: "DetermineUnit1"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "GetJobConfiguration1"
    via: "next"
    to: "DetermineUnit1"
    into: "in"
  - from: "DetermineUnit1"
    via: "next"
    to: "GetBinaryFileContent1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "GetJobConfiguration1"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "error"
    to: "Join2"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "GetBinaryFileContent1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "GetBinaryFileContent1"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "KeyMapper3"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "Call8"
    via: "Error"
    to: "Jump2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CombineIterators1"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Decision2"
    via: "no"
    to: "Call6"
    into: "in"
  - from: "Call2"
    via: "Error"
    to: "JoinNode1"
    into: "in2"
  - from: "Start3"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "Call4"
    into: "in"
