flow: "ViewSecurityPreferences_32"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "InteractionNode1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewSecurityPreferences_32-Edit"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "HTTPSRequired"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:RepositoryDomain:Site"
      PreferenceKey: "null"
      PreferenceStringValue: "OrganizationHTTPS"
      Preference: "null"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "channel/SecurityPreferences_32"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      webform-id: "PreferenceForm"
      param.1.name: "HTTPS"
      param.1.rule: "^(true|false)$"
      param.1.required: false
  - id: "Pipelet5"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "PreferenceForm"
    bindings:
      WebForm: "PreferenceForm"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      webform-id: "PreferenceForm"
      mode: "update"
    bindings:
      WebForm: "PreferenceForm"
  - id: "Pipelet7"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "PreferenceForm"
  - id: "Pipelet8"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "HTTPSRequired"
      DefaultPreferenceValue: false
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:RepositoryDomain:Site"
      PreferenceDoubleValue: "null"
      PreferenceIntValue: "null"
      PreferenceKey: "null"
      PreferenceStringValue: "PreferenceForm:HTTPS:Value"
      PreferenceValue: "null"

links:
  - from: "Pipelet4"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "Pipelet7"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "Pipelet8"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet5"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "Pipelet7"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "Pipelet7"
    via: "next"
    to: "Pipelet8"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "Pipelet4"
    into: "in"
