flow: "ViewBrandingPackage_52"
kind: "view"

entries:
  - id: "Start1"
    name: "New"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Upload"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "Install"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "ConfirmDelete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "DeleteBrandingPackage"
    mode: "private"
    strict: true
    inputs:
      - key: "BrandingPackageUUID"
        type: "java.lang.String"
        required: true

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewBrandingPackage_52-Prefix"
  - id: "Call2"
    type: "call"
    ref: "ViewBrandingPackage_52-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ViewBrandingPackage_52-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ViewBrandingPackage_52-Prefix"
  - id: "Call5"
    type: "call"
    ref: "ViewBrandingPackage_52-Prefix"
  - id: "Call6"
    type: "call"
    ref: "ViewBrandingPackage_52-Prefix"
  - id: "Call7"
    type: "call"
    ref: "ViewBrandingPackage_52-Prefix"
  - id: "CallNode1"
    type: "call"
    ref: "This:DeleteBrandingPackage"
  - id: "CreateBrandingPackage1"
    type: "pipelet"
    ref: "CreateBrandingPackage"
    bindings:
      Archive: "File"
      Domain: "Organization:Domain"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "Name"
      param.1.required: true
      param.2.name: "Description"
      param.2.required: false
      param.3.name: "File"
      param.3.required: false
      webform-id: "BrandingPackageForm"
  - id: "CreateWebForm2"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "Name"
      param.1.required: true
      param.2.name: "Description"
      param.2.required: false
      param.3.required: false
      webform-id: "BrandingPackageForm"
    bindings:
      WebForm: "BrandingPackageForm"
  - id: "Decision1"
    type: "decision"
    condition: "File"
  - id: "DecisionNode1"
    type: "decision"
    condition: "ErrorCode"
  - id: "DecisionNode5"
    type: "decision"
    condition: "InstalledInOtherApp"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewBrandingPackage_52-Create"
      OutValue_1: "ViewBrandingPackageList_52-ListAll"
      OutValue_2: "ViewBrandingPackageList_52-ListAll"
      OutValue_3: "ViewBrandingPackage_52-Update"
      OutValue_4: "ViewBrandingPackageList_52-ListAll"
      OutValue_5: "ViewBrandingPackage_52-ConfirmDelete"
      OutValue_7: "ViewBrandingPackage_52-Edit"
      OutValue_6: "ViewBrandingPackage_52-Delete"
    bindings:
      Key_0: "applyNewPackage"
      Key_1: "cancelNewPackage"
      Key_2: "backToList"
      Key_3: "applyUpdatePackage"
      Key_4: "cancelUpdatePackage"
      SelectionKey: "JumpTarget"
      Key_5: "deleteConfirm"
      Key_6: "delete"
      Key_7: "cancelDelete"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: true
  - id: "EndNode2"
    type: "end"
    strict: true
    outputs:
      - key: "ERROR_DeleteBrandingPackage"
        type: "java.lang.String"
        guaranteed: true
  - id: "GetBrandingPackage1"
    type: "pipelet"
    ref: "GetBrandingPackage"
  - id: "GetBrandingPackage3"
    type: "pipelet"
    ref: "GetBrandingPackage"
  - id: "GetBrandingPackage4"
    type: "pipelet"
    ref: "GetBrandingPackage"
  - id: "GetBrandingPackage5"
    type: "pipelet"
    ref: "GetBrandingPackage"
  - id: "GetOrganization1"
    type: "pipelet"
    ref: "GetOrganization"
    config:
      Source: "PipelineDictionary"
  - id: "GetOrganization3"
    type: "pipelet"
    ref: "GetOrganization"
    config:
      Source: "PipelineDictionary"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "BrandingPackageForm"
    bindings:
      WebForm: "BrandingPackageForm"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "BrandingPackageForm"
    bindings:
      WebForm: "BrandingPackageForm"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "Join10"
    type: "join"
  - id: "Join11"
    type: "join"
  - id: "Join12"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump2"
    type: "jump"
    ref: "ViewBrandingPackageList_52-ListAll"
  - id: "Jump3"
    type: "jump"
    ref: "ViewBrandingPackage_52-Dispatch"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewBrandingPackage_52-Create"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewBrandingPackageList_52-ListAll"
  - id: "JumpNode3"
    type: "jump"
    ref: "This:Edit"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      Iterator: "Files"
      FirstElement: "File"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "GetApplicationByUUID"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Application"
      WorkingTemplate: "branding/NewBrandingPackage_52"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Application"
      WorkingTemplate: "branding/BrandingPackage_52"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelStorefront"
      WorkingTemplate: "branding/BrandingPackageInstallations_52"
  - id: "ProcessMultipartRequest1"
    type: "pipelet"
    ref: "ProcessMultipartRequest"
    config:
      MaxFileSize: 100
      UnitDirectory: "STATIC_CONTENT_DIR"
    bindings:
      UnitDomain: "Organization:Domain"
  - id: "RemoveBrandingPackage2"
    type: "pipelet"
    ref: "RemoveBrandingPackage"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_FILE_IS_MISSING"
      Value: true
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ERROR_FILE_NOT_UPLOADED"
      Value: true
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "InstalledInOtherApp"
      ValueType: "Dictionary Value"
      Value: false
  - id: "SetDictionaryValue8"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Value: "app.Error.CanNotDeleteBrandingPackage"
      Name: "ERROR_DeleteBrandingPackage"
  - id: "UpdateBrandingPackage1"
    type: "pipelet"
    ref: "UpdateBrandingPackage"
    bindings:
      DisplayName: "BrandingPackageForm:Name:Value"
      Locale: "CurrentLocale"
      ShortDescription: "BrandingPackageForm:Description:Value"
  - id: "UpdateBrandingPackage2"
    type: "pipelet"
    ref: "UpdateBrandingPackage"
    bindings:
      DisplayName: "BrandingPackageForm:Name:Value"
      Locale: "CurrentLocale"
      ShortDescription: "BrandingPackageForm:Description:Value"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "BrandingPackageForm"
    bindings:
      WebForm: "BrandingPackageForm"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "BrandingPackageForm"
    bindings:
      WebForm: "BrandingPackageForm"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "BrandingPackageForm"
  - id: "ValidateWebForm2"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "BrandingPackageForm"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "ValidateWebForm1"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "RemoveBrandingPackage2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "ValidateWebForm1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "CreateBrandingPackage1"
    via: "error"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "CreateBrandingPackage1"
    via: "next"
    to: "UpdateBrandingPackage1"
    into: "in"
  - from: "ProcessMultipartRequest1"
    via: "error"
    to: "JumpNode1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "Join5"
    into: "in2"
  - from: "ProcessMultipartRequest1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Pipelet1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "Start3"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "CreateWebForm1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Start5"
    via: "next"
    to: "GetOrganization1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "Join5"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetOrganization1"
    via: "error"
    to: "JoinNode1"
    into: "in3"
  - from: "Call1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "CreateWebForm2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "DispatchFormAction2"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "GetBrandingPackage4"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CreateWebForm2"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "ValidateWebForm2"
    via: "next"
    to: "GetBrandingPackage1"
    into: "in"
  - from: "GetBrandingPackage1"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "GetBrandingPackage1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "Start7"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "GetBrandingPackage4"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "Start4"
    via: "next"
    to: "GetOrganization3"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "Join10"
    into: "in1"
  - from: "GetWebForm2"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "UpdateWebForm2"
    via: "next"
    to: "ValidateWebForm2"
    into: "in"
  - from: "ValidateWebForm2"
    via: "error"
    to: "Join8"
    into: "in2"
  - from: "GetWebForm2"
    via: "error"
    to: "Join7"
    into: "in2"
  - from: "Call6"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "Join10"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "UpdateBrandingPackage2"
    via: "next"
    to: "Join10"
    into: "in2"
  - from: "Call5"
    via: "next"
    to: "GetBrandingPackage3"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "GetOrganization3"
    via: "error"
    to: "End2"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "GetBrandingPackage3"
    via: "next"
    to: "Join11"
    into: "in1"
  - from: "GetBrandingPackage3"
    via: "error"
    to: "Join11"
    into: "in3"
  - from: "Join11"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "CreateBrandingPackage1"
    into: "in"
  - from: "Join12"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Decision1"
    via: "no"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Join12"
    into: "in2"
  - from: "GetOrganization1"
    via: "next"
    to: "ProcessMultipartRequest1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetWebForm1"
    into: "in"
  - from: "UpdateBrandingPackage1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "Join3"
    into: "in2"
  - from: "DispatchFormAction2"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "GetOrganization3"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "Join8"
    via: "next"
    to: "GetBrandingPackage4"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "UpdateBrandingPackage2"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "CallNode1"
    via: "ERROR"
    to: "JumpNode3"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "End1"
    into: "in"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetBrandingPackage5"
    into: "in"
  - from: "GetBrandingPackage5"
    via: "error"
    to: "JoinNode7"
    into: "in2"
  - from: "GetBrandingPackage5"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode7"
    via: "next"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Join12"
    into: "in1"
  - from: "SetDictionaryValue8"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "RemoveBrandingPackage2"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "SetDictionaryValue8"
    into: "in"
