flow: "ViewReplicationProcess"
kind: "process"

entries:
  - id: "Start1"
    name: "Remove"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "View"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Run"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Rerun"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Publish"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "Undo"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call2"
    type: "call"
    ref: "TriggerReplicationProcess-Start"
  - id: "Call3"
    type: "call"
    ref: "TriggerReplicationProcess-CreateAndStart"
  - id: "Call4"
    type: "call"
    ref: "TriggerReplicationProcess-CreateAndStart"
  - id: "Call5"
    type: "call"
    ref: "TriggerReplicationProcess-CreateAndStart"
  - id: "CheckStateChangeAllowed1"
    type: "pipelet"
    ref: "CheckStateChangeAllowed"
  - id: "CheckStateChangeAllowed2"
    type: "pipelet"
    ref: "CheckStateChangeAllowed"
  - id: "CheckStateChangeAllowed3"
    type: "pipelet"
    ref: "CheckStateChangeAllowed"
  - id: "CheckStateChangeAllowed4"
    type: "pipelet"
    ref: "CheckStateChangeAllowed"
  - id: "Decision1"
    type: "decision"
    condition: "ReplicationProcess:State"
  - id: "GetReplicationGroupConfiguration1"
    type: "pipelet"
    ref: "GetReplicationGroupConfiguration"
  - id: "GetReplicationProcessByUUID1"
    type: "pipelet"
    ref: "GetReplicationProcessByUUID"
    bindings:
      UUID: "ReplicationProcessUUID"
  - id: "GetReplicationProcessByUUID2"
    type: "pipelet"
    ref: "GetReplicationProcessByUUID"
    bindings:
      UUID: "ReplicationProcessUUID"
  - id: "GetReplicationProcessByUUID3"
    type: "pipelet"
    ref: "GetReplicationProcessByUUID"
    bindings:
      UUID: "ReplicationProcessUUID"
  - id: "GetReplicationProcessByUUID4"
    type: "pipelet"
    ref: "GetReplicationProcessByUUID"
    bindings:
      UUID: "ReplicationProcessUUID"
  - id: "GetReplicationProcessByUUID5"
    type: "pipelet"
    ref: "GetReplicationProcessByUUID"
    bindings:
      UUID: "ReplicationProcessUUID"
  - id: "GetReplicationProcessByUUID6"
    type: "pipelet"
    ref: "GetReplicationProcessByUUID"
    bindings:
      UUID: "ReplicationProcessUUID"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewReplicationProcessList-List"
  - id: "Jump2"
    type: "jump"
    ref: "ViewReplicationProcessList-List"
  - id: "Jump3"
    type: "jump"
    ref: "ViewReplicationProcessList-List"
  - id: "Jump4"
    type: "jump"
    ref: "ViewReplicationProcessList-List"
  - id: "Jump5"
    type: "jump"
    ref: "ViewReplicationProcessList-List"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ReplicationProcess:Type"
      OutValue_1: "StagingProcessMode"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"Publication\""
      OutValue_1: "StagingProcessMode"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"Undo\""
      OutValue_1: "StagingProcessMode"
  - id: "Loop1"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewReplicationProcessList-Paging"
      OutValue_1: "ViewReplicationProcess-View"
    bindings:
      Key_0: "Cancel"
      Key_1: "Refresh"
      SelectionKey: "JumpTarget"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ReplicationProcesses"
      WorkingTemplate: "replication/ReplicationProcessDetails"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "RunProcess"
      OutValue_1: "ReplicationProcessUUID"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "RerunProcess"
      OutValue_1: "ReplicationProcessUUID"
  - id: "Pipelet5"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "PublishProcess"
      OutValue_1: "ReplicationProcessUUID"
  - id: "Pipelet6"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "UndoProcess"
      OutValue_1: "ReplicationProcessUUID"
  - id: "RemoveReplicationProcess1"
    type: "pipelet"
    ref: "RemoveReplicationProcess"

links:
  - from: "StartNode2"
    via: "next"
    to: "GetReplicationProcessByUUID1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "GetReplicationProcessByUUID2"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "RemoveReplicationProcess1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Decision1"
    via: "yes"
    to: "RemoveReplicationProcess1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "GetReplicationProcessByUUID2"
    via: "error"
    to: "Join2"
    into: "in1"
  - from: "Decision1"
    via: "no"
    to: "Join2"
    into: "in2"
  - from: "GetReplicationProcessByUUID3"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode4"
    via: "next"
    to: "CheckStateChangeAllowed2"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "GetReplicationProcessByUUID3"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetReplicationProcessByUUID1"
    via: "next"
    to: "GetReplicationGroupConfiguration1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "GetReplicationProcessByUUID4"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GetReplicationGroupConfiguration1"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CheckStateChangeAllowed1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "CheckStateChangeAllowed2"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "CheckStateChangeAllowed3"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "GetReplicationProcessByUUID5"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "StartNode5"
    via: "next"
    to: "CheckStateChangeAllowed3"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "CheckStateChangeAllowed4"
    via: "next"
    to: "Pipelet6"
    into: "in"
  - from: "GetReplicationProcessByUUID5"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "KeyMapper3"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "GetReplicationProcessByUUID6"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "JoinNode4"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CheckStateChangeAllowed4"
    into: "in"
  - from: "GetReplicationProcessByUUID6"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "CheckStateChangeAllowed1"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "GetReplicationProcessByUUID3"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "GetReplicationProcessByUUID4"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "GetReplicationProcessByUUID5"
    into: "in"
  - from: "Pipelet6"
    via: "next"
    to: "GetReplicationProcessByUUID6"
    into: "in"
  - from: "GetReplicationProcessByUUID4"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "Start1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Loop1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetReplicationProcessByUUID2"
    into: "in"
