flow: "ViewProductLinks_52"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Display"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewProductLinks-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewProductLinks-Display"

links:
  - from: "StartNode2"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "JumpNode1"
    into: "in"
