flow: "ViewPaymentHistory"
kind: "view"

entries:
  - id: "StartNode1"
    name: "GetPaymentTransactionBO"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode10"
    name: "PaymentReauthorize"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode11"
    name: "PaymentCancel"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode12"
    name: "PaymentRefund"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "ShowPaymentHistory"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "PaymentReduce"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "PaymentCapture"
    mode: "public"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewPaymentHistory-GetPaymentTransactionBO"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PaymentTransactionBO:ID"
  - id: "DecisionNode5"
    type: "decision"
    condition: "PaymentService:Capabilities:isPaymentHistorySupported"
  - id: "DispatchFormAction4"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPaymentHistory-PaymentCapture"
      OutValue_1: "ViewPaymentHistory-PaymentCancel"
      OutValue_2: "ViewPaymentHistory-PaymentRefund"
      OutValue_3: "ViewPaymentHistory-PaymentReauthorize"
      OutValue_4: "ViewPaymentHistory-PaymentReduce"
    bindings:
      Key_0: "capture"
      Key_1: "cancel"
      Key_2: "refund"
      Key_3: "reauthorize"
      SelectionKey: "JumpTarget"
      Key_4: "reduce"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "GetOrderBO2"
    type: "pipelet"
    ref: "GetOrderBO"
  - id: "GetOrderByID6"
    type: "pipelet"
    ref: "GetOrderByID"
    bindings:
      OrderIDs: "null"
      OrderRefID: "null"
      OrderRefIDs: "null"
      Orders: "null"
  - id: "GetPaymentTransactionByUUID1"
    type: "pipelet"
    ref: "GetPaymentTransactionByUUID"
  - id: "GetPaymentTransactionByUUID2"
    type: "pipelet"
    ref: "GetPaymentTransactionByUUID"
  - id: "GetPaymentTransactionByUUID3"
    type: "pipelet"
    ref: "GetPaymentTransactionByUUID"
  - id: "GetPaymentTransactionByUUID4"
    type: "pipelet"
    ref: "GetPaymentTransactionByUUID"
  - id: "GetPaymentTransactionByUUID5"
    type: "pipelet"
    ref: "GetPaymentTransactionByUUID"
  - id: "GetPaymentTransactionByUUID6"
    type: "pipelet"
    ref: "GetPaymentTransactionByUUID"
    bindings:
      PaymentTransaction: "PaymentTransaction"
  - id: "InteractionEnd10"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode16"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode22"
    type: "join"
  - id: "JoinNode24"
    type: "join"
  - id: "JoinNode25"
    type: "join"
  - id: "JoinNode28"
    type: "join"
  - id: "JoinNode29"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode30"
    type: "join"
  - id: "Jump18"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump20"
    type: "jump"
    ref: "ViewPaymentHistory-ShowPaymentHistory"
  - id: "Jump21"
    type: "jump"
    ref: "ViewPaymentHistory-ShowPaymentHistory"
  - id: "Jump22"
    type: "jump"
    ref: "ViewPaymentHistory-ShowPaymentHistory"
  - id: "Jump23"
    type: "jump"
    ref: "ViewPaymentHistory-ShowPaymentHistory"
  - id: "Jump24"
    type: "jump"
    ref: "ViewPaymentHistory-ShowPaymentHistory"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "PaymentTransaction:PaymentService"
      OutValue_1: "PaymentService"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Order\"):getOrderBORepository(Order)"
      OutValue_1: "OrderBORepository"
  - id: "LogMessage1"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Category: "audits"
      Level: "Info"
      Marker: "audits"
    bindings:
      MessageParam0: "CurrentRequest:ServletRequest:LocalAddr"
      MessageParam1: "CurrentOrganization:Domain:DomainName"
      MessageParam2: "CurrentUser:Profile:Credentials:Login"
      MessageText: "\"{} : {} : {} : Payment Action - Payment Cancellation: {}; Payment Service ID: {}\""
      MessageParam3: "CancelError"
      MessageParam4: "PaymentTransaction:PaymentService:ID"
  - id: "LogMessage10"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Category: "audits"
      Level: "Info"
      Marker: "audits"
    bindings:
      MessageParam0: "CurrentRequest:ServletRequest:LocalAddr"
      MessageParam1: "CurrentOrganization:Domain:DomainName"
      MessageParam2: "CurrentUser:Profile:Credentials:Login"
      MessageText: "\"{} : {} : {} : Payment Action - Money Verification ERROR: {}; Payment Service ID: {}\""
      MessageParam3: "ErrorCode"
      MessageParam4: "PaymentTransaction:PaymentService:ID"
  - id: "LogMessage11"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Category: "audits"
      Level: "Info"
      Marker: "audits"
    bindings:
      MessageParam0: "CurrentRequest:ServletRequest:LocalAddr"
      MessageParam1: "CurrentOrganization:Domain:DomainName"
      MessageParam2: "CurrentUser:Profile:Credentials:Login"
      MessageText: "\"{} : {} : {} : Payment Action - Payment Reduced; Payment Result - {}\""
      MessageParam3: "ReduceResult"
  - id: "LogMessage12"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Category: "audits"
      Level: "Info"
      Marker: "audits"
    bindings:
      MessageParam0: "CurrentRequest:ServletRequest:LocalAddr"
      MessageParam1: "CurrentOrganization:Domain:DomainName"
      MessageParam2: "CurrentUser:Profile:Credentials:Login"
      MessageText: "\"{} : {} : {} : Payment Action - Payment Reduce: {}; Payment Service ID: {}\""
      MessageParam3: "ReduceError"
      MessageParam4: "PaymentTransaction:PaymentService:ID"
  - id: "LogMessage2"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Category: "audits"
      Level: "Info"
      Marker: "audits"
    bindings:
      MessageParam0: "CurrentRequest:ServletRequest:LocalAddr"
      MessageParam1: "CurrentOrganization:Domain:DomainName"
      MessageParam2: "CurrentUser:Profile:Credentials:Login"
      MessageText: "\"{} : {} : {} : Payment Action - Payment Reauthorized; Payment Result - {}\""
      MessageParam3: "AuthorizationResult"
  - id: "LogMessage3"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Category: "audits"
      Level: "Info"
      Marker: "audits"
    bindings:
      MessageParam0: "CurrentRequest:ServletRequest:LocalAddr"
      MessageParam1: "CurrentOrganization:Domain:DomainName"
      MessageParam2: "CurrentUser:Profile:Credentials:Login"
      MessageText: "\"{} : {} : {} : Payment Action - Payment Reauthorization: {}; Payment Service ID: {}\""
      MessageParam3: "AuthorizationError"
      MessageParam4: "PaymentTransaction:PaymentService:ID"
  - id: "LogMessage4"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Category: "audits"
      Level: "Info"
      Marker: "audits"
    bindings:
      MessageParam0: "CurrentRequest:ServletRequest:LocalAddr"
      MessageParam1: "CurrentOrganization:Domain:DomainName"
      MessageParam2: "CurrentUser:Profile:Credentials:Login"
      MessageText: "\"{} : {} : {} : Payment Action - Payment Captured; Payment Result - {}\""
      MessageParam3: "CaptureResult"
  - id: "LogMessage5"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Category: "audits"
      Level: "Info"
      Marker: "audits"
    bindings:
      MessageParam0: "CurrentRequest:ServletRequest:LocalAddr"
      MessageParam1: "CurrentOrganization:Domain:DomainName"
      MessageParam2: "CurrentUser:Profile:Credentials:Login"
      MessageText: "\"{} : {} : {} : Payment Action - Payment Capture: {}; Payment Service ID: {}\""
      MessageParam3: "CaptureError"
      MessageParam4: "PaymentTransaction:PaymentService:ID"
  - id: "LogMessage6"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Category: "audits"
      Level: "Info"
      Marker: "audits"
    bindings:
      MessageParam0: "CurrentRequest:ServletRequest:LocalAddr"
      MessageParam1: "CurrentOrganization:Domain:DomainName"
      MessageParam2: "CurrentUser:Profile:Credentials:Login"
      MessageText: "\"{} : {} : {} : Payment Action - Payment Refund; Payment Result - {}\""
      MessageParam3: "RefundResult"
  - id: "LogMessage7"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Category: "audits"
      Level: "Info"
      Marker: "audits"
    bindings:
      MessageParam0: "CurrentRequest:ServletRequest:LocalAddr"
      MessageParam1: "CurrentOrganization:Domain:DomainName"
      MessageParam2: "CurrentUser:Profile:Credentials:Login"
      MessageText: "\"{} : {} : {} : Payment Action - Payment Cancelled; Payment Result - {}\""
      MessageParam3: "CancelResult"
  - id: "LogMessage8"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Category: "audits"
      Level: "Info"
      Marker: "audits"
    bindings:
      MessageParam0: "CurrentRequest:ServletRequest:LocalAddr"
      MessageParam2: "CurrentUser:Profile:Credentials:Login"
      MessageText: "\"{} : {} : {} : Payment Action - Payment Refund: {}; Payment Service ID: {}\""
      MessageParam3: "RefundError"
      MessageParam4: "PaymentTransaction:PaymentService:ID"
      MessageParam1: "CurrentOrganization:Domain:DomainName"
  - id: "LogMessage9"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Category: "audits"
      Level: "Info"
      Marker: "audits"
    bindings:
      MessageParam0: "CurrentRequest:ServletRequest:LocalAddr"
      MessageParam1: "CurrentOrganization:Domain:DomainName"
      MessageParam2: "CurrentUser:Profile:Credentials:Login"
      MessageText: "\"{} : {} : {} : Payment Action - Money Verification ERROR: {}; Payment Service ID: {}\""
      MessageParam3: "ErrorCode"
      MessageParam4: "PaymentTransaction:PaymentService:ID"
  - id: "LoopNode1"
    type: "loop"
  - id: "PrepareApplicationView9"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "order/PaymentHistory.isml"
      Dynamic: false
      SelectedMenuItem: "Orders"
  - id: "PrepareViewBackofficeHistory1"
    type: "pipelet"
    ref: "PrepareViewBackofficeHistory"
    config:
      ContextPipeline: "ViewPaymentHistory-ShowPaymentHistory"
    bindings:
      PaymentTransaction: "PaymentTransaction"
  - id: "ProcessPaymentAuthorization1"
    type: "pipelet"
    ref: "ProcessPaymentAuthorization"
  - id: "ProcessPaymentCancel2"
    type: "pipelet"
    ref: "ProcessPaymentCancel"
  - id: "ProcessPaymentCapture2"
    type: "pipelet"
    ref: "ProcessPaymentCapture"
  - id: "ProcessPaymentReduce1"
    type: "pipelet"
    ref: "ProcessPaymentReduce"
    bindings:
      AmountToReduce: "MoneyValue"
  - id: "ProcessPaymentRefund1"
    type: "pipelet"
    ref: "ProcessPaymentRefund"
    bindings:
      OrderNo: "PaymentTransaction:Order:DocumentNo"
      RefundAmount: "MoneyValue"
  - id: "VerifyMoney1"
    type: "pipelet"
    ref: "VerifyMoney"
    config:
      MinValue: 0
    bindings:
      LocalizedString: "RefundAmount"
      CurrencyMnemonic: "PaymentTransaction:Amount:CurrencyMnemonic"
      ErrorCode: "RefundAmountErrorCode"
  - id: "VerifyMoney2"
    type: "pipelet"
    ref: "VerifyMoney"
    config:
      MinValue: 0
    bindings:
      LocalizedString: "AmountToReduce"
      CurrencyMnemonic: "PaymentTransaction:Amount:CurrencyMnemonic"
      ErrorCode: "ReduceAmountErrorCode"

links:
  - from: "StartNode4"
    via: "next"
    to: "GetOrderByID6"
    into: "in"
  - from: "VerifyMoney1"
    via: "error"
    to: "LogMessage9"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "JoinNode30"
    into: "in2"
  - from: "ProcessPaymentAuthorization1"
    via: "error"
    to: "LogMessage3"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "PrepareViewBackofficeHistory1"
    into: "in"
  - from: "PrepareViewBackofficeHistory1"
    via: "error"
    to: "JoinNode30"
    into: "in1"
  - from: "PrepareApplicationView9"
    via: "next"
    to: "InteractionEnd10"
    into: "in"
  - from: "PrepareViewBackofficeHistory1"
    via: "next"
    to: "JoinNode29"
    into: "in1"
  - from: "StartNode7"
    via: "next"
    to: "DispatchFormAction4"
    into: "in"
  - from: "VerifyMoney2"
    via: "error"
    to: "LogMessage10"
    into: "in"
  - from: "GetOrderBO2"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "JoinNode29"
    via: "next"
    to: "PrepareApplicationView9"
    into: "in"
  - from: "ProcessPaymentCapture2"
    via: "next"
    to: "LogMessage4"
    into: "in"
  - from: "StartNode12"
    via: "next"
    to: "GetPaymentTransactionByUUID4"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "GetPaymentTransactionByUUID2"
    into: "in"
  - from: "LogMessage4"
    via: "next"
    to: "JoinNode16"
    into: "in1"
  - from: "StartNode10"
    via: "next"
    to: "GetPaymentTransactionByUUID5"
    into: "in"
  - from: "ProcessPaymentRefund1"
    via: "error"
    to: "LogMessage8"
    into: "in"
  - from: "GetPaymentTransactionByUUID1"
    via: "next"
    to: "VerifyMoney2"
    into: "in"
  - from: "LogMessage12"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "LogMessage2"
    via: "next"
    to: "JoinNode24"
    into: "in1"
  - from: "GetPaymentTransactionByUUID4"
    via: "next"
    to: "VerifyMoney1"
    into: "in"
  - from: "StartNode11"
    via: "next"
    to: "GetPaymentTransactionByUUID3"
    into: "in"
  - from: "JoinNode28"
    via: "next"
    to: "Jump23"
    into: "in"
  - from: "StartNode8"
    via: "next"
    to: "GetPaymentTransactionByUUID1"
    into: "in"
  - from: "GetPaymentTransactionByUUID5"
    via: "next"
    to: "ProcessPaymentAuthorization1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode28"
    into: "in1"
  - from: "LogMessage5"
    via: "next"
    to: "JoinNode16"
    into: "in1"
  - from: "VerifyMoney1"
    via: "next"
    to: "ProcessPaymentRefund1"
    into: "in"
  - from: "ProcessPaymentCancel2"
    via: "next"
    to: "LogMessage7"
    into: "in"
  - from: "LogMessage1"
    via: "next"
    to: "JoinNode22"
    into: "in1"
  - from: "ProcessPaymentAuthorization1"
    via: "next"
    to: "LogMessage2"
    into: "in"
  - from: "LogMessage3"
    via: "next"
    to: "JoinNode24"
    into: "in1"
  - from: "GetPaymentTransactionByUUID6"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "ProcessPaymentRefund1"
    via: "next"
    to: "LogMessage6"
    into: "in"
  - from: "JoinNode16"
    via: "next"
    to: "Jump21"
    into: "in"
  - from: "JoinNode22"
    via: "next"
    to: "Jump22"
    into: "in"
  - from: "LogMessage9"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "LogMessage8"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode25"
    into: "in1"
  - from: "LogMessage10"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "ProcessPaymentReduce1"
    via: "error"
    to: "LogMessage12"
    into: "in"
  - from: "JoinNode24"
    via: "next"
    to: "Jump20"
    into: "in"
  - from: "LogMessage7"
    via: "next"
    to: "JoinNode22"
    into: "in1"
  - from: "ProcessPaymentCapture2"
    via: "error"
    to: "LogMessage5"
    into: "in"
  - from: "JoinNode25"
    via: "next"
    to: "Jump24"
    into: "in"
  - from: "ProcessPaymentReduce1"
    via: "next"
    to: "LogMessage11"
    into: "in"
  - from: "LogMessage6"
    via: "next"
    to: "JoinNode25"
    into: "in1"
  - from: "GetOrderByID6"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "GetPaymentTransactionByUUID6"
    into: "in"
  - from: "GetPaymentTransactionByUUID3"
    via: "next"
    to: "ProcessPaymentCancel2"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "DecisionNode1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "DecisionNode1"
    via: "no"
    to: "LoopNode1"
    into: "loop"
  - from: "JoinNode30"
    via: "next"
    to: "JoinNode29"
    into: "in2"
  - from: "GetPaymentTransactionByUUID2"
    via: "next"
    to: "ProcessPaymentCapture2"
    into: "in"
  - from: "LogMessage11"
    via: "next"
    to: "JoinNode28"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "GetOrderBO2"
    into: "in"
  - from: "VerifyMoney2"
    via: "next"
    to: "ProcessPaymentReduce1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "ProcessPaymentCancel2"
    via: "error"
    to: "LogMessage1"
    into: "in"
  - from: "DispatchFormAction4"
    via: "next"
    to: "Jump18"
    into: "in"
