flow: "ViewReplicateProducts"
kind: "view"

entries:
  - id: "StartNode1"
    name: "SelectTarget"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "StartReplication"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewProcessList-CreateProcess"
  - id: "CallNode6"
    type: "call"
  - id: "ConcatenateStrings2"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "\"ViewProcessList_\""
      String2: "\"-CreateProcess\""
      String1: "CurrentChannel:TypeCode"
      Concatenated: "CreateProcessPipeline"
  - id: "ConcatenateStrings3"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      String0: "\"ViewProcessList_\""
      String2: "\"-ListAll\""
      String1: "CurrentChannel:TypeCode"
      Concatenated: "ListAllPipeline"
  - id: "DecisionNode1"
    type: "decision"
    condition: "CurrentChannel"
  - id: "GetTargetCluster1"
    type: "pipelet"
    ref: "GetTargetCluster"
  - id: "GetTargetClusters1"
    type: "pipelet"
    ref: "GetTargetClusters"
  - id: "InteractionEnd12"
    type: "interaction"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewProcessList-ListAll"
  - id: "JumpNode3"
    type: "jump"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "\"ProcessReplicateObjects-Init\""
      InValue_2: "\"ProcessReplicateObjects-Process\""
      InValue_3: "\"ProcessReplicateObjects-Post\""
      InValue_4: "\"Catalog_ReplicateProducts\""
      InValue_5: "\"Objects\""
      OutValue_1: "InitPipeline"
      OutValue_2: "ProcessPipeline"
      OutValue_3: "PostPipeline"
      OutValue_4: "JobName"
      OutValue_5: "PageableName"
  - id: "PrepareApplicationView12"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelProducts"
      WorkingTemplate: "replication/ReplicateProductsWizardSelectTarget"

links:
  - from: "PrepareApplicationView12"
    via: "next"
    to: "InteractionEnd12"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "ConcatenateStrings2"
    via: "next"
    to: "ConcatenateStrings3"
    into: "in"
  - from: "GetTargetClusters1"
    via: "next"
    to: "PrepareApplicationView12"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetTargetClusters1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetTargetCluster1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "ConcatenateStrings2"
    into: "in"
  - from: "ConcatenateStrings3"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetTargetCluster1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
