flow: "ViewSearchIndexFilterCategoryAssignment"
kind: "view"

entries:
  - id: "StartNode18"
    name: "AssignCategories"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "DynamicTree"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddEntryToMap1"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      Key: "aCategory:UUID"
      Value: "AssignmentFlag"
      OutMap: "selectedCategoriesMap"
      InMap: "selectedCategoriesMap"
  - id: "AssignCategoryToFilterAttribute1"
    type: "pipelet"
    ref: "AssignCategoryToFilterAttribute"
    bindings:
      CatalogId: "Catalog:Id"
      CategoryName: "SelectedCategory:Name"
      Domain: "Catalog:OwningDomain"
      CategoryDomain: "SelectedCategory:Domain"
  - id: "CallNode14"
    type: "call"
    ref: "ViewSearchIndexFilters-GetAssignedCategories"
  - id: "CallNode24"
    type: "call"
    ref: "ViewSearchIndexFilters-FilterAttributePrefix"
  - id: "CallNode51"
    type: "call"
    ref: "ProcessSearchIndex-GetIndex"
    bindings:
      Domain: "CurrentChannel:Domain"
  - id: "CallNode7"
    type: "call"
    ref: "ViewSearchIndexFilterCategoryWizard-Prefix"
  - id: "CallNode8"
    type: "call"
    ref: "ViewSearchIndexFilterCategoryWizard-GetStandardCatalogs"
  - id: "CreateFormValuesIteratorForKey1"
    type: "pipelet"
    ref: "CreateFormValuesIteratorForKey"
    bindings:
      FormKey: "\"tree\""
      FormValuesIterator: "SelectedCategoryUUIDs"
  - id: "DecisionNode1"
    type: "decision"
    condition: "tree"
  - id: "DispatchFormAction3"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_1: "ViewSearchIndexFilterCategoryAssignment-AssignCategories"
      OutValue_0: "ViewSearchIndexFilterCategoryAssignment-DynamicTree"
      OutValue_2: "ViewSearchIndexFilters-EditFilterAttribute"
      OutValue_3: "ViewSearchIndexFilters-ConfirmRemoveCategoryAssignments"
      OutValue_4: "ViewSearchIndexFilters-RemoveCategoryAssignments"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "assignCategoryByTree"
      Key_1: "assignCategories"
      Key_2: "cancelSelectCategories"
      Key_3: "confirmUnassignCategory"
      Key_4: "unassignCategory"
  - id: "GetCategoryByUUID4"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "SelectedCategoryUUID"
      Category: "SelectedCategory"
  - id: "GetPropertyValue1"
    type: "pipelet"
    ref: "GetPropertyValue"
    config:
      PropertyName: "intershop.cartridges.bc_mvc.searchindex.filterCategoryAssignment.directLookup"
      PropertyType: "Global"
      DefaultPropertyValue: false
    bindings:
      PropertyValue: "directLookup"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JumpNode11"
    type: "jump"
    ref: "ViewSearchIndexFilters-EditFilterAttribute"
  - id: "JumpNode13"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper61"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "SearchIndex:Configuration:getAttributeByName(AttributeName)"
      OutValue_1: "FilterAttribute"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode10"
    type: "loop"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Concatenate Iterators"
    bindings:
      Iterator: "Catalogs"
      Iterator1: "SharedStandardCatalogs"
      Iterator2: "LocalStandardCatalogs"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "MassDataTasks"
      WorkingTemplate: "searchindex/SearchIndexFilterAssignmentByTree"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewSearchIndexFilters-EditFilterAttribute"
      ValueType: "Dictionary Value"
  - id: "UnassignAllCategoriesFromFilterAttribute1"
    type: "pipelet"
    ref: "UnassignAllCategoriesFromFilterAttribute"
  - id: "UpdateSearchIndexConfiguration10"
    type: "pipelet"
    ref: "UpdateSearchIndexConfiguration"
    bindings:
      SearchFeatureID: "null"
      QueryStopWords: "null"
      Locale: "null"
      Online: "null"
      LastIndexStartTime: "null"
      Description: "null"
      Attributes: "null"
      StopWords: "null"
      Synonyms: "null"
      Tuning: "null"
  - id: "VerifyBoolean2"
    type: "pipelet"
    ref: "VerifyBoolean"
    bindings:
      NoneLocalizedString: "\"true\""
      BooleanValue: "AssignmentFlag"

links:
  - from: "KeyMapper61"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "AddEntryToMap1"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "CallNode51"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "CreateFormValuesIteratorForKey1"
    into: "in"
  - from: "CreateFormValuesIteratorForKey1"
    via: "next"
    to: "LoopNode10"
    into: "in"
  - from: "GetCategoryByUUID4"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "LoopNode10"
    via: "next"
    to: "UpdateSearchIndexConfiguration10"
    into: "in"
  - from: "AddEntryToMap1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "GetCategoryByUUID4"
    via: "next"
    to: "AssignCategoryToFilterAttribute1"
    into: "in"
  - from: "CallNode24"
    via: "next"
    to: "UnassignAllCategoriesFromFilterAttribute1"
    into: "in"
  - from: "AssignCategoryToFilterAttribute1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode4"
    into: "in2"
  - from: "StartNode2"
    via: "next"
    to: "DispatchFormAction3"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "GetPropertyValue1"
    into: "in"
  - from: "GetPropertyValue1"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "StartNode18"
    via: "next"
    to: "CallNode24"
    into: "in"
  - from: "DispatchFormAction3"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode14"
    via: "next"
    to: "VerifyBoolean2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "LoopNode10"
    into: "loop"
  - from: "UpdateSearchIndexConfiguration10"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "JumpNode11"
    into: "in"
  - from: "LoopNode10"
    via: "do"
    to: "GetCategoryByUUID4"
    into: "in"
  - from: "DispatchFormAction3"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "UnassignAllCategoriesFromFilterAttribute1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JumpNode13"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "CallNode51"
    via: "next"
    to: "KeyMapper61"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "VerifyBoolean2"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "Pipelet3"
    into: "in"
