flow: "ViewContentPreferences"
kind: "view"

entries:
  - id: "Start1"
    name: "ChannelList"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "SelectChannel"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "GetTypeCodes"
    mode: "private"
    strict: true
    inputs:
      - key: "TypeCodes"
        type: "java.lang.String"
        required: false
  - id: "StartNode4"
    name: "GetContentSharingChannel"
    mode: "private"
    strict: true
    inputs:
      - key: "OrganizationDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      Object: "IntegerObject"
      InVector: "TypeCodeVector"
      OutVector: "TypeCodeVector"
      Iterator: "TypeCodeIterator"
      Objects: "null"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessStorefrontEditing-GetContentSharingChannel"
  - id: "CallNode2"
    type: "call"
    ref: "This:GetTypeCodes"
    bindings:
      TypeCodes: "\"42;52\""
  - id: "CreateIteratorFromConfigValues1"
    type: "pipelet"
    ref: "CreateIteratorFromConfigValues"
    config:
      Delimiters: ";"
    bindings:
      ValuesString: "TypeCodes"
      ValuesIterator: "TypeCodeStringIterator"
  - id: "Decision1"
    type: "decision"
    condition: "PageNumber"
  - id: "DecisionNode1"
    type: "decision"
    condition: "SelectedChannelDomainName"
  - id: "DecisionNode2"
    type: "decision"
    condition: "MasterPageEditing_Switch"
  - id: "DecisionNode3"
    type: "decision"
    condition: "ReadonlyIfFuture_Switch"
  - id: "DecisionNode6"
    type: "decision"
    condition: "TypeCodes"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewContentPreferences-Start"
      OutValue_1: "ViewContentPreferences-ChannelList"
      OutValue_2: "ViewContentPreferences-Paging"
      PagingPipeline: "ViewContentPreferences-Paging"
      OutValue_3: "ViewContentPreferences-Start"
      OutValue_4: "ViewContentPreferences-SelectChannel"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "Start"
      Key_1: "ChannelList"
      Key_2: "Paging"
      Key_3: "Cancel"
      Key_4: "SelectChannel"
  - id: "EndNode1"
    type: "end"
    strict: true
    outputs:
      - key: "ContentSharingChannel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        guaranteed: false
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "TypeCodeIterator"
        type: "java.util.Iterator"
        guaranteed: false
  - id: "ExecutePageableQuery2"
    type: "pipelet"
    ref: "ExecutePageableQuery"
    config:
      QueryName: "repository/GetRepositoriesByOwningDomain"
      DefaultPageSize: 15
    bindings:
      Query: "null"
      Connection: "null"
      PageSize: "null"
      SearchResult: "Repositories"
      Parameters: "QueryParameters"
      ErrorCode: "SearchExecutionError"
  - id: "GetChannelTypes1"
    type: "pipelet"
    ref: "GetChannelTypes"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "String"
    bindings:
      PreferenceDomain: "OrganizationDomain"
      PreferenceKey: "\"ContentSharingChannel\""
      Preference: "ContentSharingChannelPreference"
  - id: "GetDomainPreference2"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "String"
      DefaultPreferenceKey: "MasterPageEditing"
    bindings:
      PreferenceDomain: "OrganizationDomain"
      Preference: "MasterPageEditinglPreference"
  - id: "GetDomainPreference3"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "MasterPageEditing"
      Type: "String"
    bindings:
      PreferenceDomain: "OrganizationDomain"
      PreferenceStringValue: "PreviousMasterPageEditingValue"
  - id: "GetDomainPreference4"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "String"
      DefaultPreferenceKey: "SFEReadonlyIfFuture"
    bindings:
      PreferenceDomain: "OrganizationDomain"
      Preference: "ReadonlyIfFuturePreference"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      RestorePageLocatorDictionary: "True"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Repositories"
      PageableID: "PageLocator:PageableID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode14"
    type: "join"
  - id: "JoinNode15"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump6"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "This:Paging"
  - id: "LoopNode1"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      RenderingType: "HTML"
      SelectedMenuItem: "ContentPreferences"
      WorkingTemplate: "content/ContentPreferences"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ContentPreferences"
      WorkingTemplate: "content/ChannelSelectionPreference"
  - id: "SetDomainPreference1"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      Type: "String"
    bindings:
      PreferenceDomain: "OrganizationDomain"
      PreferenceStringValue: "SelectedChannelDomainName"
      PreferenceKey: "\"ContentSharingChannel\""
  - id: "SetDomainPreference2"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      Type: "String"
      DefaultPreferenceKey: "MasterPageEditing"
    bindings:
      PreferenceDomain: "OrganizationDomain"
      PreferenceStringValue: "MasterPageEditing_Switch"
  - id: "SetDomainPreference3"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      Type: "String"
      DefaultPreferenceKey: "MasterPageEditing"
      DefaultPreferenceValue: true
    bindings:
      PreferenceDomain: "OrganizationDomain"
  - id: "SetDomainPreference4"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      Type: "String"
      DefaultPreferenceKey: "SFEReadonlyIfFuture"
    bindings:
      PreferenceDomain: "OrganizationDomain"
      PreferenceStringValue: "ReadonlyIfFuture_Switch"
  - id: "SetDomainPreference5"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      Type: "String"
      DefaultPreferenceKey: "SFEReadonlyIfFuture"
      DefaultPreferenceValue: false
    bindings:
      PreferenceDomain: "OrganizationDomain"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Repositories"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Repositories"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewContentPreferences-Paging"
      DefaultPageLocatorName: "ChannelList"
    bindings:
      Pageable: "Repositories"
  - id: "UpdateDictionary3"
    type: "pipelet"
    ref: "UpdateDictionary"
    config:
      Name_01: "OwningDomain"
      Name_02: "TypeCodes"
      Name_03: "SortBy"
      Name_04: "SortDirection"
      Name_05: "Locale"
    bindings:
      Value_01: "OrganizationDomain"
      InDictionary: "null"
      OutDictionary: "QueryParameters"
      Value_02: "TypeCodeIterator"
      Value_03: "SortBy"
      Value_04: "SortDirection"
      Value_05: "CurrentSession:Locale"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      Locale: "null"
      LocalizedString: "PageNumber"
      Pattern: "null"
  - id: "VerifyInteger2"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      LocalizedString: "TypeCodeString"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "ExecutePageableQuery2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "SetPageLocator1"
    via: "next"
    to: "GetChannelTypes1"
    into: "in"
  - from: "DispatchFormAction2"
    via: "next"
    to: "Jump6"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "Join5"
    into: "in2"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage1"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "SetPage2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "SetDomainPreference2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "SetPage1"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "Start2"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "GetChannelTypes1"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "GetDomainPreference1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "GetDomainPreference2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "SetDomainPreference1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "GetPageable1"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "SetDomainPreference1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode3"
    via: "yes"
    to: "SetDomainPreference4"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "UpdateDictionary3"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "VerifyInteger2"
    via: "error"
    to: "JoinNode14"
    into: "in2"
  - from: "AddObjectToVector1"
    via: "next"
    to: "JoinNode14"
    into: "in1"
  - from: "DecisionNode6"
    via: "no"
    to: "JoinNode15"
    into: "in2"
  - from: "StartNode3"
    via: "next"
    to: "DecisionNode6"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "VerifyInteger2"
    into: "in"
  - from: "GetDomainPreference1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode14"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "JoinNode15"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "CreateIteratorFromConfigValues1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "DecisionNode6"
    via: "yes"
    to: "CreateIteratorFromConfigValues1"
    into: "in"
  - from: "VerifyInteger2"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "JoinNode15"
    into: "in1"
  - from: "UpdateDictionary3"
    via: "next"
    to: "ExecutePageableQuery2"
    into: "in"
  - from: "SetDomainPreference3"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "DecisionNode2"
    via: "yes"
    to: "SetDomainPreference2"
    into: "in"
  - from: "SetDomainPreference3"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "SetDomainPreference3"
    into: "in"
  - from: "SetDomainPreference2"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "GetDomainPreference4"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "GetDomainPreference2"
    into: "in"
  - from: "GetDomainPreference2"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "GetDomainPreference4"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "GetDomainPreference3"
    into: "in"
  - from: "GetDomainPreference3"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "GetDomainPreference4"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "JoinNode6"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "DispatchFormAction2"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "SetDomainPreference5"
    into: "in"
  - from: "SetDomainPreference5"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "SetDomainPreference4"
    via: "error"
    to: "JoinNode8"
    into: "in2"
  - from: "SetDomainPreference5"
    via: "error"
    to: "JoinNode8"
    into: "in1"
  - from: "SetDomainPreference4"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join1"
    into: "in1"
