flow: "ViewPageletEntryPoint"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode11"
    name: "ConfirmDelete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode14"
    name: "LookupPEPLock"
    mode: "private"
    strict: false
    inputs:
      - key: "PreferenceDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
      - key: "PageletEntryPoint"
        type: "com.intershop.beehive.core.capi.domain.PersistentObject"
        required: false
      - key: "LockingDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
  - id: "StartNode15"
    name: "IsTabSwitched"
    mode: "private"
    strict: true
    inputs:
      - key: "PageletEntryPointUUID"
        type: "java.lang.String"
        required: true
  - id: "StartNode17"
    name: "GetSelectedMenuItem"
    mode: "private"
    strict: true
    inputs:
      []
  - id: "StartNode2"
    name: "InternalView"
    mode: "include"
    strict: false
    inputs:
      []
  - id: "StartNode23"
    name: "Lock"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode29"
    name: "Unlock"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "CreateFlagName"
    mode: "private"
    strict: true
    inputs:
      - key: "PageletEntryPointUUID"
        type: "java.lang.String"
        required: true
  - id: "StartNode30"
    name: "CheckLock"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "View"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "UpdateConstraints"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "SetLocale"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "SimpleViewTemplateCallback"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode15"
    type: "call"
    ref: "ProcessPageletConstraints-GetPageletConstraintCtnr"
    bindings:
      ContextObject: "PageletEntryPoint"
      Domain: "ContentRepository:RepositoryDomain"
  - id: "CallNode16"
    type: "call"
    ref: "ViewPageletEntryPoint-IsTabSwitched"
    bindings:
      PageletEntryPointUUID: "PageletEntryPoint:UUID"
      Flag: "IsTabSwitched"
  - id: "CallNode19"
    type: "call"
    ref: "ProcessPageletEntryPointLock-Lookup"
    bindings:
      User: "CurrentUser"
  - id: "CallNode2"
    type: "call"
    ref: "This:CreateFlagName"
  - id: "CallNode21"
    type: "call"
    ref: "This:CreateFlagName"
  - id: "CallNode22"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode27"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode28"
    type: "call"
    ref: "ProcessPageletConstraints-UpdatePageletConstraintCtnr"
    bindings:
      TargetObject: "PageletEntryPoint"
      Domain: "ContentRepository:RepositoryDomain"
  - id: "CallNode3"
    type: "call"
    ref: "This:CreateFlagName"
  - id: "CallNode36"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode37"
    type: "call"
    ref: "ProcessPageletEntryPointLock-Lock"
    bindings:
      LockingDomain: "ContentRepository:RepositoryDomain"
      PreferenceDomain: "ContentRepository:RepositoryDomain"
      User: "CurrentUser"
  - id: "CallNode38"
    type: "call"
    ref: "ProcessPageletEntryPointLock-Unlock"
    bindings:
      LockingDomain: "ContentRepository:RepositoryDomain"
      User: "CurrentUser"
  - id: "CallNode4"
    type: "call"
    ref: "This:GetSelectedMenuItem"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessPageletEntryPointLock-Check"
    bindings:
      User: "CurrentUser"
      LockingDomain: "ContentRepository:RepositoryDomain"
      PreferenceDomain: "ContentRepository:RepositoryDomain"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessPageletEntryPoint-DeletePageletEntryPoint"
    bindings:
      Domain: "ContentRepository:RepositoryDomain"
      Site: "ContentRepository:RepositoryDomain:Site"
  - id: "CallNode8"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode9"
    type: "call"
    ref: "ProcessPageletLock-Check"
    bindings:
      LockingDomain: "ContentRepository:RepositoryDomain"
      PreferenceDomain: "ContentRepository:RepositoryDomain"
      User: "CurrentUser"
      Pagelet: "PageletEntryPoint"
  - id: "ConcatenateStrings5"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString0: "PageletEntryPointViewTabSwitched@"
    bindings:
      String1: "PageletEntryPointUUID"
      Concatenated: "FlagName"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PageletEntryPointUUID"
  - id: "DecisionNode5"
    type: "decision"
    condition: "IsTabSwitched"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DetermineLocales2"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPageletEntryPoint-CheckLock"
      OutValue_1: "ViewPageletEntryPoint-Lock"
      OutValue_2: "ViewPageletEntryPoint-Unlock"
      OutValue_3: "ViewPageletEntryPoint-UpdateConstraints"
      OutValue_4: "ViewPageletEntryPoint-SetLocale"
      OutValue_5: "ViewPageletEntryPoint-ConfirmDelete"
      OutValue_6: "ViewPageletEntryPoint-Delete"
      OutValue_7: "ViewPageletEntryPoint-View"
    bindings:
      Key_0: "checkLock"
      Key_1: "lock"
      Key_2: "unlock"
      Key_3: "updateConstraints"
      Key_4: "setLocale"
      Key_5: "confirmDelete"
      Key_6: "delete"
      Key_7: "cancel"
      SelectionKey: "JumpTarget"
  - id: "DispatchFormActionByBreadcrumb2"
    type: "pipelet"
    ref: "DispatchFormActionByBreadcrumb"
    config:
      SplitMode: "PipelineAndParameter"
    bindings:
      Key_0: "\"backToLastListView\""
      OutValue_0: "ApplicationState:LastListView"
      SelectionKey: "JumpTarget"
  - id: "DispatchFormActionByBreadcrumb5"
    type: "pipelet"
    ref: "DispatchFormActionByBreadcrumb"
    config:
      SplitMode: "PipelineAndParameter"
    bindings:
      Key_0: "\"backToLastBreadcrumb\""
      OutValue_0: "ApplicationState:LastBreadcrumb"
      SelectionKey: "JumpTarget"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode14"
    type: "end"
    strict: true
    outputs:
      - key: "SelectedMenuItem"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "FlagName"
        type: "java.lang.String"
        guaranteed: false
  - id: "EndNode6"
    type: "end"
    strict: false
  - id: "EndNode9"
    type: "end"
    strict: true
    outputs:
      - key: "Flag"
        type: "java.lang.Object"
        guaranteed: true
      - key: "Locales"
        type: "java.util.Iterator"
        guaranteed: true
  - id: "ExchangeSessionObject1"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SaveObject: "\"(Boolean)true\""
      SessionObjectName: "FlagName"
  - id: "ExchangeSessionObject2"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SaveObject: "null"
      SessionObjectName: "FlagName"
  - id: "ExchangeSessionObject5"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
    bindings:
      SessionObjectName: "FlagName"
      LoadObject: "Flag"
  - id: "ExchangeSessionObject6"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SessionObjectName: "FlagName"
      SaveObject: "null"
  - id: "ExchangeSessionObject7"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ApplicationState"
    bindings:
      LoadObject: "ApplicationState"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Request Locale"
  - id: "GetPageletEntryPointByUUID1"
    type: "pipelet"
    ref: "GetPageletEntryPointByUUID"
    bindings:
      PageletEntryPointUUID: "PageletEntryPointUUID"
  - id: "GetRepositoryByUUID2"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      UUID: "ContentRepositoryUUID"
      Repository: "ContentRepository"
  - id: "GetValuesFromContainer1"
    type: "pipelet"
    ref: "GetValuesFromContainer"
    config:
      OverwriteBehavior: true
    bindings:
      ContainerName: "PageletEntryPoint:UUID"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode17"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode40"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JumpNode10"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewPageletEntryPoint-View"
  - id: "JumpNode3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewPageletEntryPoint-InternalView"
  - id: "JumpNode5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode6"
    type: "jump"
    ref: "ViewPageletEntryPoint-View"
  - id: "KeyMapper9"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Dictionary Value"
    bindings:
      InValue_1: "ApplicationState:LastSelectedMenuItem"
      OutValue_1: "SelectedMenuItem"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "content/pageletentrypoint/PageletEntryPoint"
  - id: "PutValuesIntoPipelineDictionary1"
    type: "pipelet"
    ref: "PutValuesIntoPipelineDictionary"
    config:
      key.1: "SelectedTab"
      value.1: "\"Constraints\""
  - id: "RemoveValuesContainer2"
    type: "pipelet"
    ref: "RemoveValuesContainer"
    bindings:
      ContainerName: "PageletEntryPointUUID"
  - id: "RemoveValuesContainer3"
    type: "pipelet"
    ref: "RemoveValuesContainer"
    bindings:
      ContainerName: "PageletEntryPoint:UUID"
  - id: "SetValuesToContainer2"
    type: "pipelet"
    ref: "SetValuesToContainer"
    bindings:
      ContainerName: "PageletEntryPointUUID"

links:
  - from: "CallNode15"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode16"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "CallNode19"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode15"
    into: "in"
  - from: "CallNode21"
    via: "next"
    to: "ExchangeSessionObject5"
    into: "in"
  - from: "CallNode22"
    via: "next"
    to: "CallNode37"
    into: "in"
  - from: "CallNode27"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode28"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "ExchangeSessionObject1"
    into: "in"
  - from: "CallNode36"
    via: "next"
    to: "CallNode38"
    into: "in"
  - from: "CallNode37"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode38"
    via: "next"
    to: "JoinNode40"
    into: "in1"
  - from: "CallNode3"
    via: "next"
    to: "ExchangeSessionObject2"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CallNode5"
    via: "NO_LOCK"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode5"
    via: "next"
    to: "CallNode28"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "DispatchFormActionByBreadcrumb2"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "CallNode9"
    via: "NO_LOCK"
    to: "RemoveValuesContainer2"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "ConcatenateStrings5"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode2"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "GetPageletEntryPointByUUID1"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "RemoveValuesContainer3"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "GetValuesFromContainer1"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "EndNode9"
    into: "in"
  - from: "DetermineLocales2"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "DispatchFormAction2"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "DispatchFormActionByBreadcrumb2"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "DispatchFormActionByBreadcrumb5"
    via: "next"
    to: "JumpNode10"
    into: "in"
  - from: "ExchangeSessionObject1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "ExchangeSessionObject2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "ExchangeSessionObject5"
    via: "next"
    to: "ExchangeSessionObject6"
    into: "in"
  - from: "ExchangeSessionObject6"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "ExchangeSessionObject7"
    via: "next"
    to: "KeyMapper9"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "GetRepositoryByUUID2"
    into: "in"
  - from: "GetPageletEntryPointByUUID1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "GetPageletEntryPointByUUID1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetRepositoryByUUID2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetValuesFromContainer1"
    via: "error"
    to: "JoinNode17"
    into: "in1"
  - from: "GetValuesFromContainer1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode17"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "JoinNode40"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "DispatchFormActionByBreadcrumb5"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "PutValuesIntoPipelineDictionary1"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "DetermineLocales2"
    into: "in"
  - from: "KeyMapper9"
    via: "next"
    to: "EndNode14"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "PutValuesIntoPipelineDictionary1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "RemoveValuesContainer2"
    via: "next"
    to: "JumpNode6"
    into: "in"
  - from: "RemoveValuesContainer3"
    via: "next"
    to: "JoinNode17"
    into: "in1"
  - from: "SetValuesToContainer2"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "StartNode11"
    via: "next"
    to: "SetValuesToContainer2"
    into: "in"
  - from: "StartNode14"
    via: "next"
    to: "CallNode19"
    into: "in"
  - from: "StartNode15"
    via: "next"
    to: "CallNode21"
    into: "in"
  - from: "StartNode17"
    via: "next"
    to: "ExchangeSessionObject7"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "StartNode23"
    via: "next"
    to: "CallNode22"
    into: "in"
  - from: "StartNode29"
    via: "next"
    to: "CallNode36"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "StartNode30"
    via: "next"
    to: "JoinNode40"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "ConcatenateStrings5"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "DispatchFormAction2"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode27"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "StartNode8"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "CallNode16"
    into: "in"
