flow: "ViewChannelOutboundSyndicationAttributeGroupMapping"
kind: "view"

entries:
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "AttributeGroupDetails"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessSyndicationRule-GetRuleSet"
    bindings:
      Name: "\"AttributeGroups\""
  - id: "CallNode2"
    type: "call"
    ref: "ProcessSyndicationRule-GetRuleSet"
    bindings:
      Name: "\"AttributeGroups\""
  - id: "CallNode3"
    type: "call"
    ref: "ProcessSyndicationRule-GetDataDeclarationList"
    bindings:
      Name: "\"AttributeGroups\""
  - id: "CallNode4"
    type: "call"
    ref: "ProcessSyndicationRule-RemoveSyndicationRule"
  - id: "CreateSyndicationDataDeclaration1"
    type: "pipelet"
    ref: "CreateSyndicationDataDeclaration"
    bindings:
      Domain: "Syndication:Domain"
      DataObjectClassName: "\"com.intershop.beehive.xcs.internal.product.ProductPO\""
  - id: "CreateSyndicationRule1"
    type: "pipelet"
    ref: "CreateSyndicationRule"
    bindings:
      SyndicationRuleClass: "\"com.intershop.component.mvc.internal.syndication.mapping.AttributeGroupsRuleProcessor\""
      Domain: "Syndication:Domain"
      SourceSyndicationDataDeclaration: "SyndicationDataDeclaration"
  - id: "DecisionNode1"
    type: "decision"
    condition: "SelectedAttributeGroupUUIDs"
  - id: "DecisionNode2"
    type: "decision"
    condition: "SyndicationRuleUUID"
  - id: "DecisionNode3"
    type: "decision"
    condition: "SyndicationRuleUUID"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelOutboundSyndicationAttributeGroupMapping-Start"
      OutValue_1: "ViewChannelOutboundSyndicationList-Start"
      OutValue_2: "ViewChannelOutboundSyndicationAttributeGroupMapping-Start"
      OutValue_3: "ViewChannelOutboundSyndicationAttributeGroupMapping-AttributeGroupDetails"
      OutValue_4: "ViewChannelOutboundSyndicationAttributeGroupMapping-Update"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "Start"
      Key_1: "Back"
      Key_2: "BackToList"
      Key_3: "AttributeGroupDetails"
      Key_4: "Update"
  - id: "GetAttributeGroupByUUID1"
    type: "pipelet"
    ref: "GetAttributeGroupByUUID"
    bindings:
      UUID: "AttributeGroupUUID"
  - id: "GetAttributeGroups1"
    type: "pipelet"
    ref: "GetAttributeGroups"
    bindings:
      Domain: "CurrentChannel:Domain"
      TypeCode: "\"(Integer)0\""
  - id: "GetAttributeGroups2"
    type: "pipelet"
    ref: "GetAttributeGroups"
    bindings:
      Domain: "CurrentChannel:Domain"
      TypeCode: "\"(Integer)0\""
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedAttributeGroupUUID"
    bindings:
      Selection: "SelectedAttributeGroupUUIDs"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Request Locale"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Request Locale"
  - id: "GetSyndicationByUUID1"
    type: "pipelet"
    ref: "GetSyndicationByUUID"
  - id: "GetSyndicationByUUID2"
    type: "pipelet"
    ref: "GetSyndicationByUUID"
  - id: "GetSyndicationByUUID3"
    type: "pipelet"
    ref: "GetSyndicationByUUID"
  - id: "GetSyndicationRuleByUUID1"
    type: "pipelet"
    ref: "GetSyndicationRuleByUUID"
  - id: "GetSyndicationRuleByUUID2"
    type: "pipelet"
    ref: "GetSyndicationRuleByUUID"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "InteractionNode2"
    type: "interaction"
  - id: "InteractionNode3"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "Jump5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/ChannelOutboundSyndicationAttributeGroupMapping"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/ChannelOutboundSyndicationAttributeGroupDetails"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/ChannelOutboundSyndicationAttributeGroupMapping"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "SyndicationRule"
      RemoveFormValues: false
  - id: "UpdateCustomAttribute1"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    config:
      DefaultAttributeName: "AttributeGroupUUID"
      DefaultAttributeType: "MultipleString"
    bindings:
      AttributeValue: "SelectedAttributeGroupUUIDs"
      ExtensibleObject: "SyndicationRule:SourceSyndicationDataDeclaration"

links:
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetSyndicationByUUID2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "GetAttributeGroups1"
    into: "in"
  - from: "GetSyndicationByUUID3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "GetSyndicationByUUID3"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "DecisionNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "GetSyndicationRuleByUUID1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "CreateSyndicationDataDeclaration1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionNode3"
    into: "in"
  - from: "GetAttributeGroups1"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "CreateSyndicationRule1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "GetSyndicationRuleByUUID1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "UpdateCustomAttribute1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "DecisionNode3"
    into: "in"
  - from: "CreateSyndicationDataDeclaration1"
    via: "next"
    to: "CreateSyndicationRule1"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "GetSyndicationRuleByUUID2"
    into: "in"
  - from: "GetSyndicationRuleByUUID2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetSyndicationByUUID1"
    into: "in"
  - from: "UpdateCustomAttribute1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "GetAttributeGroups2"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode3"
    into: "in2"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "GetAttributeGroups2"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "GetLocale2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "GetSyndicationByUUID1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "GetSyndicationByUUID2"
    via: "next"
    to: "GetAttributeGroupByUUID1"
    into: "in"
  - from: "GetAttributeGroupByUUID1"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionNode2"
    into: "in"
