flow: "ViewPageCache_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "GetChannelSite"
    mode: "private"
    strict: false
    inputs:
      - key: "ChannelRepository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: false
      - key: "SiteDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: false
  - id: "Start4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Invalidate"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewPageCache_52-GetChannelSite"
  - id: "Call2"
    type: "call"
    ref: "ViewPageCache_52-GetChannelSite"
  - id: "Call3"
    type: "call"
    ref: "ViewPageCache_52-GetChannelSite"
  - id: "CreateIteratorFromConfigValues1"
    type: "pipelet"
    ref: "CreateIteratorFromConfigValues"
    config:
      Delimiters: "|"
    bindings:
      ValuesString: "InvalidationKeywords"
      ValuesIterator: "Keywords"
  - id: "Decision1"
    type: "decision"
    condition: "DomainPageCachingAllowed"
  - id: "Decision2"
    type: "decision"
    condition: "DomainPageCachingAllowed"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPageCache_52-Invalidate"
      OutValue_1: "ViewPageCache_52-Update"
      OutValue_2: "ViewChannelCatalogOverview_52-Show"
    bindings:
      Key_0: "Invalidate"
      Key_1: "OK"
      Key_2: "Cancel"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "PagecacheKeywordProcessing"
      Type: "String"
    bindings:
      PreferenceDomain: "SiteDomain"
      PreferenceStringValue: "DomainPageCacheKeywordProcessingEnabled"
  - id: "GetDomainPreference4"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "PagecacheIndexing"
      Type: "String"
    bindings:
      PreferenceDomain: "SiteDomain"
      PreferenceStringValue: "DomainPageCacheIndexingEnabled"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InvalidatePageCache1"
    type: "pipelet"
    ref: "InvalidatePageCache"
    bindings:
      Site: "SiteDomain"
  - id: "Join2"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewPageCache_52-Start"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump3"
    type: "jump"
    ref: "ViewPageCache_52-Start"
  - id: "Jump5"
    type: "jump"
    ref: "ViewPageCache_52-Invalidate"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ChannelRepository:RepositoryDomain:Site"
      OutValue_1: "SiteDomain"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"InvalidIntegerMaxAge\""
      OutValue_1: "ErrorInvalidMaxAge"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "catalog/PageCache_52"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "DomainPageCachingAllowed"
      Value: false
      ValueType: "Form Value"
  - id: "SetDomainPreference1"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "PagecacheKeywordProcessing"
      DefaultPreferenceValue: "Disabled"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:RepositoryDomain:Site"
      PreferenceValue: "DomainPageCacheKeywordProcessingEnabled"
  - id: "SetDomainPreference4"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      DefaultPreferenceKey: "PagecacheIndexing"
      DefaultPreferenceValue: "Disabled"
      Type: "String"
    bindings:
      PreferenceDomain: "ChannelRepository:RepositoryDomain:Site"
      PreferenceValue: "DomainPageCacheIndexingEnabled"
  - id: "ToString1"
    type: "pipelet"
    ref: "ToString"
    bindings:
      Object1: "MaxAge"
      String1: "StringMaxAge"
  - id: "UpdateDomain1"
    type: "pipelet"
    ref: "UpdateDomain"
    bindings:
      Domain: "SiteDomain"
      DomainDescription: "null"
      DomainDisplayName: "null"
      DomainInvalidatePageCache: "null"
      DomainStaticContentMaxAge: "StringMaxAge"
      DomainStatus: "null"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    config:
      MinValue: 0
    bindings:
      Locale: "null"
      LocalizedString: "DomainStaticContentMaxAge"
      Pattern: "null"
      IntegerValue: "MaxAge"

links:
  - from: "Call1"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "VerifyInteger1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "CreateIteratorFromConfigValues1"
    into: "in"
  - from: "CreateIteratorFromConfigValues1"
    via: "next"
    to: "InvalidatePageCache1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join2"
    into: "in1"
  - from: "Decision1"
    via: "yes"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Jump5"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "SetDomainPreference1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "GetDomainPreference1"
    via: "error"
    to: "GetDomainPreference4"
    into: "in"
  - from: "GetDomainPreference1"
    via: "next"
    to: "GetDomainPreference4"
    into: "in"
  - from: "GetDomainPreference4"
    via: "error"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "GetDomainPreference4"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "InvalidatePageCache1"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "UpdateDomain1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "SetDomainPreference1"
    via: "error"
    to: "SetDomainPreference4"
    into: "in"
  - from: "SetDomainPreference1"
    via: "next"
    to: "SetDomainPreference4"
    into: "in"
  - from: "SetDomainPreference4"
    via: "error"
    to: "Jump1"
    into: "in"
  - from: "SetDomainPreference4"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "ToString1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "UpdateDomain1"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "KeyMapper2"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "ToString1"
    into: "in"
