flow: "ViewPromotionExportList"
kind: "view"

entries:
  - id: "Start1"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Run"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "BrowseDirectory1"
    type: "pipelet"
    ref: "BrowseDirectory"
    config:
      DefaultDirectoryPath: "export/promotions"
      UnitDirectory: "IMPEX_DIR"
    bindings:
      UnitDomain: "ChannelRepository:Domain"
      Directory: "ExportDirectory"
  - id: "Call1"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call2"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "Call3"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "Call4"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode1"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "This:Prefix"
  - id: "CreatePageableFromIterator1"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    config:
      PageableName: "PromotionExports"
      Pagesize: 15
    bindings:
      Iterator: "PromotionExports"
      Pageable: "PromotionExports"
  - id: "Decision1"
    type: "decision"
    condition: "PageLocator"
  - id: "Decision2"
    type: "decision"
    condition: "PageNumber"
  - id: "DecisionNode1"
    type: "decision"
    condition: "UUIDIterator"
  - id: "DecisionNode5"
    type: "decision"
    condition: "CurrentChannel"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPromotionExportList-ListAll"
      OutValue_1: "ViewPromotionExportList-Paging"
      OutValue_2: "ViewPromotionExportList-Delete"
      OutValue_3: "ViewPromotionExportList-Paging"
      PagingPipeline: "ViewPromotionExportList-Paging"
      OutValue_4: "ViewPromotionExport-New"
      OutValue_5: "ViewPromotionExportList-Run"
      OutValue_6: "ViewPromotionExportList-Paging"
    bindings:
      Key_0: "Start"
      Key_1: "Paging"
      Key_2: "Delete"
      Key_3: "ConfirmDelete"
      SelectionKey: "JumpTarget"
      Key_4: "New"
      Key_5: "Run"
      Key_6: "Refresh"
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "ExecuteJob1"
    type: "pipelet"
    ref: "ExecuteJob"
    bindings:
      JobConfiguration: "JobConfiguration"
  - id: "GetAllJobConfigurations1"
    type: "pipelet"
    ref: "GetAllJobConfigurations"
    config:
      DefaultJobNamePrefix: "Promotion"
      DefaultJobState: "None"
    bindings:
      Domain: "CurrentSelectedChannel:Domain"
      JobConfigurations: "PromotionExports"
  - id: "GetJobConfiguration1"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "ExportUUID"
  - id: "GetJobConfiguration2"
    type: "pipelet"
    ref: "GetJobConfiguration"
    bindings:
      JobUUID: "ExportUUID"
      JobConfiguration: "PromotionExport"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Request Locale"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "PromotionExportPageLocator"
      RestorePageLocatorDictionary: "True"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "PromotionExports"
      PageableID: "PageLocator:PageableID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump7"
    type: "jump"
    ref: "This:ListAll"
  - id: "JumpNode2"
    type: "jump"
    ref: "This:Paging"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentDomain"
      OutValue_1: "UnitDomain"
  - id: "KeyMapper17"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentChannel:Domain:Site:Domain"
      OutValue_1: "UnitDomain"
  - id: "Loop1"
    type: "loop"
  - id: "Loop2"
    type: "loop"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      RenderingType: "HTML"
      SelectedMenuItem: "Marketing"
      WorkingTemplate: "marketing/PromotionExportList"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "SelectedObjectUUIDs"
      RemoveFormValues: true
  - id: "RemoveDictionaryValue2"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      Key: "SelectedObjectUUID"
      RemoveFormValues: true
  - id: "RemoveJobConfiguration1"
    type: "pipelet"
    ref: "RemoveJobConfiguration"
    bindings:
      JobConfiguration: "PromotionExport"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Value: "True"
      Name: "noTargetSelected"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "PromotionExports"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "PromotionExports"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewPromotionExportList-Paging"
      DefaultPageLocatorName: "PromotionExportPageLocator"
    bindings:
      Pageable: "PromotionExports"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"

links:
  - from: "Start5"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Join6"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Start1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "Decision1"
    via: "yes"
    to: "SetPage1"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "SetPage1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "GetPageable1"
    via: "error"
    to: "Join4"
    into: "in2"
  - from: "Call3"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "Call4"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "Decision1"
    via: "no"
    to: "Join2"
    into: "in3"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join6"
    into: "in3"
  - from: "Join5"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "CreatePageableFromIterator1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "RemoveDictionaryValue2"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Decision1"
    into: "in"
  - from: "GetPageLocator1"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "CallNode2"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "GetAllJobConfigurations1"
    via: "next"
    to: "CreatePageableFromIterator1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "GetJobConfiguration2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetJobConfiguration2"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "RemoveJobConfiguration1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Start2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage2"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Join3"
    into: "in3"
  - from: "Join3"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "JoinNode9"
    into: "in3"
  - from: "KeyMapper17"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "DecisionNode5"
    via: "no"
    to: "KeyMapper1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "KeyMapper17"
    into: "in"
  - from: "GetAllJobConfigurations1"
    via: "error"
    to: "Join5"
    into: "in1"
  - from: "Loop1"
    via: "next"
    to: "Jump7"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Start6"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "SetPageLocator1"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "BrowseDirectory1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "GetPageable1"
    via: "next"
    to: "Join5"
    into: "in2"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "RemoveDictionaryValue2"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode3"
    into: "in2"
  - from: "Call2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "Loop2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Loop2"
    via: "do"
    to: "GetJobConfiguration1"
    into: "in"
  - from: "Loop2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GetJobConfiguration1"
    via: "next"
    to: "ExecuteJob1"
    into: "in"
  - from: "GetJobConfiguration1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "GetJobConfiguration2"
    via: "next"
    to: "RemoveJobConfiguration1"
    into: "in"
  - from: "ExecuteJob1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "JoinNode3"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "BrowseDirectory1"
    into: "in"
  - from: "BrowseDirectory1"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "JoinNode5"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "GetAllJobConfigurations1"
    into: "in"
