flow: "ViewProductStatistics"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "StartUpdate"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewProductStatistics-Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "UpdateObjectStatisticsRealtime-UpdateAsync"
  - id: "CallNode3"
    type: "call"
    ref: "ViewProductStatistics-Prefix"
  - id: "CallNode4"
    type: "call"
    ref: "UpdateObjectStatisticsRealtime-GetResource"
  - id: "DecisionNode2"
    type: "decision"
    condition: "ObjectStatisticsGroup"
  - id: "DecisionNode4"
    type: "decision"
    condition: "SelectCurrencyMnemonic"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "GetCurrencies1"
    type: "pipelet"
    ref: "GetCurrencies"
    config:
      Method: "Active Currencies"
  - id: "GetCurrency3"
    type: "pipelet"
    ref: "GetCurrency"
    bindings:
      Mnemonic: "SelectCurrencyMnemonic"
  - id: "GetCurrency4"
    type: "pipelet"
    ref: "GetCurrency"
    bindings:
      Mnemonic: "CurrentSession:CurrencyCode"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
  - id: "GetObjectStatisticsGroup1"
    type: "pipelet"
    ref: "GetObjectStatisticsGroup"
    config:
      GroupName: "Product"
    bindings:
      ObjectDomain: "ObjectDomain"
      ObjectStatisticsGroup: "ObjectStatisticsGroup"
  - id: "GetObjectStatisticsGroup2"
    type: "pipelet"
    ref: "GetObjectStatisticsGroup"
  - id: "GetStagingSystemType1"
    type: "pipelet"
    ref: "GetStagingSystemType"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentMasterRepository:RepositoryDomain"
      OutValue_1: "ObjectDomain"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ProductStatistics"
      WorkingTemplate: "objectstatistics/ProductStatistics"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Refresh"
      ValueType: "Dictionary Value"
      Value: true

links:
  - from: "JoinNode8"
    via: "next"
    to: "GetCurrencies1"
    into: "in"
  - from: "GetObjectStatisticsGroup2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "GetObjectStatisticsGroup1"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "GetObjectStatisticsGroup1"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "CallNode3"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode4"
    via: "Running"
    to: "JoinNode2"
    into: "in2"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "GetObjectStatisticsGroup2"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "GetStagingSystemType1"
    into: "in"
  - from: "GetStagingSystemType1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "GetCurrencies1"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "GetCurrency3"
    via: "next"
    to: "JoinNode8"
    into: "in3"
  - from: "DecisionNode4"
    via: "no"
    to: "GetCurrency4"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "CallNode4"
    into: "in"
  - from: "GetCurrency4"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode4"
    via: "yes"
    to: "GetCurrency3"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode3"
    into: "in2"
