flow: "ViewChannelServiceList"
kind: "view"

entries:
  - id: "Start4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode11"
    name: "Activate"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Add"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Enable"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Disable"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "List"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "GetListSelections"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode8"
    name: "confirmDelete"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "Deactivate"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewServiceList-GetListSelections"
  - id: "CallNode10"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "CallNode11"
    type: "call"
    ref: "ViewServices101-GetCurrentServiceConfigurationRepository"
  - id: "CallNode12"
    type: "call"
    ref: "ViewServices101-EnableServiceConfiguration"
  - id: "CallNode13"
    type: "call"
    ref: "ViewServices101-DisableServiceConfiguration"
  - id: "CallNode14"
    type: "call"
    ref: "ViewChannelServiceList-GetListSelections"
  - id: "CallNode15"
    type: "call"
    ref: "ViewServices101-GetCurrentServiceConfigurationRepository"
  - id: "CallNode16"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode17"
    type: "call"
    ref: "ViewChannelServiceList-GetListSelections"
  - id: "CallNode18"
    type: "call"
    ref: "ViewServices101-GetCurrentServiceConfigurationRepository"
  - id: "CallNode19"
    type: "call"
    ref: "ViewServices101-ActivateServiceConfiguration"
  - id: "CallNode2"
    type: "call"
    ref: "ViewServiceList-GetListSelections"
  - id: "CallNode22"
    type: "call"
    ref: "ViewServices101-DeactivateServiceConfiguration"
  - id: "CallNode23"
    type: "call"
    ref: "ViewServices101-GetCurrentServiceConfigurationRepository"
  - id: "CallNode28"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "CallNode3"
    type: "call"
    ref: "ViewServiceList-GetListSelections"
  - id: "CallNode4"
    type: "call"
    ref: "ViewServices101-DeleteServiceConfiguration"
    bindings:
      ServiceConfigurationID: "SelectedServiceConfigurationID"
  - id: "CallNode5"
    type: "call"
    ref: "ViewServiceList-GetListSelections"
  - id: "CallNode6"
    type: "call"
    ref: "ViewServices101-GetCurrentServiceConfigurationRepository"
  - id: "CallNode7"
    type: "call"
    ref: "ViewServices101-GetServiceGroupsAndConfigurations"
  - id: "CallNode8"
    type: "call"
    ref: "ViewServices101-GetCurrentServiceConfigurationRepository"
  - id: "CallNode9"
    type: "call"
    ref: "ProcessClipboard-DeleteAllEntries"
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "ServiceConfigurationSharedListForm"
      FormResource: "ServiceConfigurationListFormRessource"
    bindings:
      Form: "ServiceConfigurationSharedListForm"
  - id: "CreateForm2"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "ServiceConfigurationListForm"
      FormResource: "ServiceConfigurationListFormRessource"
    bindings:
      Form: "ServiceConfigurationListForm"
  - id: "CreateForm3"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "ServiceConfigurationListForm"
      FormResource: "ServiceConfigurationListFormRessource"
    bindings:
      Form: "ServiceConfigurationListForm"
  - id: "CreateForm4"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "ServiceConfigurationListForm"
      FormResource: "ServiceConfigurationListFormRessource"
    bindings:
      Form: "ServiceConfigurationListForm"
  - id: "CreateForm5"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "ServiceConfigurationListForm"
      FormResource: "ServiceConfigurationListFormRessource"
    bindings:
      Form: "ServiceConfigurationListForm"
  - id: "CreateForm6"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "ServiceConfigurationSharedListForm"
      FormResource: "ServiceConfigurationListFormRessource"
    bindings:
      Form: "ServiceConfigurationSharedListForm"
  - id: "CreateForm7"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "ServiceConfigurationListForm"
      FormResource: "ServiceConfigurationListFormRessource"
    bindings:
      Form: "ServiceConfigurationListForm"
  - id: "DecisionNode3"
    type: "decision"
    condition: "SelectedObjectUUIDs"
  - id: "DecisionNode4"
    type: "decision"
    condition: "ServiceConfigurationListType"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelServiceList-Add"
      OutValue_1: "ViewChannelServiceList-confirmDelete"
      OutValue_2: "ViewChannelServiceList-Activate"
      OutValue_3: "ViewChannelServiceList-Deactivate"
      OutValue_4: "ViewChannelServiceList-Delete"
      OutValue_5: "ViewChannelServiceList-Enable"
      OutValue_6: "ViewChannelServiceList-Disable"
    bindings:
      Key_0: "add"
      SelectionKey: "JumpTarget"
      Key_1: "confirmDelete"
      Key_2: "activate"
      Key_3: "deactivate"
      Key_4: "delete"
      Key_5: "enable"
      Key_6: "disable"
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
  - id: "InteractionNode4"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "ViewChannelServiceList-List"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewChannelServiceList-List"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewChannelServiceList-List"
  - id: "JumpNode5"
    type: "jump"
    ref: "ViewChannelServiceList-List"
  - id: "JumpNode6"
    type: "jump"
    ref: "ViewChannelServiceList-List"
  - id: "JumpNode7"
    type: "jump"
    ref: "ViewChannelServiceList-List"
  - id: "JumpNode8"
    type: "jump"
    ref: "ViewChannelServiceList-List"
  - id: "JumpNode9"
    type: "jump"
    ref: "ViewChannelServiceList-List"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "LoopNode3"
    type: "loop"
  - id: "LoopNode5"
    type: "loop"
  - id: "LoopNode6"
    type: "loop"
  - id: "PrepareApplicationView8"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "service/ServicesAdministration/ChannelServiceConfigurationsList"
      SelectedMenuItem: "Services"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewChannelServiceList-List"
  - id: "SetDictionaryValue10"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "noSelectedItems"
      Value: 1
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue11"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "noSelectedSharedItems"
      Value: 1
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "confirmDelete"
      Value: true
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewChannelServiceNewWizard-SetDefinition"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "showBtnSharedConfigure"
      Value: true
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "showBtnSharedView"
      Value: true
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "SelectedMenuItem"
      Value: "Services"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "ServiceConfigurationSharedListForm"
  - id: "ValidateForm2"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "ServiceConfigurationListForm"
  - id: "ValidateForm3"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "ServiceConfigurationListForm"
  - id: "ValidateForm4"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "ServiceConfigurationListForm"
  - id: "ValidateForm5"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "ServiceConfigurationSharedListForm"
  - id: "ValidateForm6"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "ServiceConfigurationListForm"

links:
  - from: "Start4"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CreateForm4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "CreateForm3"
    via: "next"
    to: "ValidateForm2"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "CallNode12"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "CallNode15"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "CallNode4"
    into: "in"
  - from: "CallNode15"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "CreateForm2"
    via: "next"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "CreateForm5"
    via: "next"
    to: "ValidateForm4"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "LoopNode1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "ValidateForm2"
    via: "error"
    to: "JumpNode2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "ValidateForm5"
    via: "next"
    to: "CreateForm5"
    into: "in"
  - from: "ValidateForm4"
    via: "next"
    to: "CallNode23"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "JumpNode5"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "ValidateForm4"
    via: "error"
    to: "JumpNode7"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CreateForm3"
    into: "in"
  - from: "CreateForm4"
    via: "next"
    to: "ValidateForm3"
    into: "in"
  - from: "ValidateForm3"
    via: "error"
    to: "JumpNode3"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "StartNode8"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "ValidateForm1"
    via: "next"
    to: "CreateForm7"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "ValidateForm6"
    via: "error"
    to: "JumpNode8"
    into: "in"
  - from: "CreateForm7"
    via: "next"
    to: "ValidateForm6"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "ValidateForm2"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "CallNode9"
    via: "next"
    to: "CallNode11"
    into: "in"
  - from: "CallNode11"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "LoopNode3"
    via: "next"
    to: "JumpNode6"
    into: "in"
  - from: "LoopNode3"
    via: "do"
    to: "CallNode13"
    into: "in"
  - from: "ValidateForm3"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "SetDictionaryValue7"
    into: "in"
  - from: "CallNode19"
    via: "next"
    to: "LoopNode6"
    into: "loop"
  - from: "SetDictionaryValue7"
    via: "next"
    to: "PrepareApplicationView8"
    into: "in"
  - from: "ValidateForm1"
    via: "error"
    to: "JumpNode8"
    into: "in"
  - from: "CallNode14"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "ValidateForm6"
    via: "next"
    to: "CallNode18"
    into: "in"
  - from: "CallNode28"
    via: "next"
    to: "JumpNode9"
    into: "in"
  - from: "LoopNode6"
    via: "next"
    to: "CallNode28"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "PrepareApplicationView8"
    via: "next"
    to: "InteractionNode4"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "CallNode17"
    via: "next"
    to: "CreateForm6"
    into: "in"
  - from: "LoopNode6"
    via: "do"
    to: "CallNode19"
    into: "in"
  - from: "CreateForm6"
    via: "next"
    to: "ValidateForm5"
    into: "in"
  - from: "CallNode18"
    via: "next"
    to: "LoopNode5"
    into: "in"
  - from: "StartNode11"
    via: "next"
    to: "CallNode17"
    into: "in"
  - from: "LoopNode5"
    via: "next"
    to: "CallNode28"
    into: "in"
  - from: "StartNode9"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "LoopNode5"
    via: "do"
    to: "CallNode22"
    into: "in"
  - from: "CallNode22"
    via: "next"
    to: "LoopNode5"
    into: "loop"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "CallNode23"
    via: "next"
    to: "LoopNode6"
    into: "in"
  - from: "ValidateForm5"
    via: "error"
    to: "JumpNode7"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "CreateForm2"
    into: "in"
  - from: "CallNode16"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "SetDictionaryValue10"
    via: "next"
    to: "JoinNode5"
    into: "in3"
  - from: "DecisionNode3"
    via: "yes"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode3"
    via: "no"
    to: "DecisionNode4"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "CallNode16"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "SetDictionaryValue11"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "SetDictionaryValue10"
    into: "in"
  - from: "SetDictionaryValue11"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode3"
    into: "in"
