flow: "ViewChannelCatalogList_32"
kind: "view"

entries:
  - id: "Start1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "GetDisplayOptions"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "SetDisplayOptions"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "GetDisplayVariable"
    mode: "private"
    strict: true
    inputs:
      - key: "ChannelID"
        type: "java.lang.String"
        required: true
      - key: "VariableName"
        type: "java.lang.String"
        required: true

steps:
  - id: "Call2"
    type: "call"
    ref: "ViewChannelCatalogList_32-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ProcessChannelCatalog_32-GetClassificationCatalogs"
  - id: "Call4"
    type: "call"
    ref: "ProcessChannelCatalog_32-GetStandardCatalogs"
  - id: "CallNode1"
    type: "call"
    ref: "This:GetDisplayVariable"
    bindings:
      VariableName: "\"T_HideSharedStandardCatalogs_\""
      DisplayVariable: "HideSharedStandardCatalogs"
  - id: "CallNode10"
    type: "call"
    ref: "This:GetDisplayVariable"
    bindings:
      VariableName: "\"T_HideLocalClassificationCatalogs_\""
      DisplayVariable: "HideLocalClassificationCatalogs"
  - id: "CallNode12"
    type: "call"
    ref: "This:GetDisplayVariable"
    bindings:
      VariableName: "\"T_HideLocalSystemClassificationCatalogs_\""
      DisplayVariable: "HideLocalSystemClassificationCatalogs"
  - id: "CallNode13"
    type: "call"
    ref: "This:GetDisplayVariable"
    bindings:
      VariableName: "\"T_HideSharedSystemClassificationCatalogs_\""
      DisplayVariable: "HideSharedSystemClassificationCatalogs"
  - id: "CallNode2"
    type: "call"
    ref: "This:GetDisplayVariable"
    bindings:
      VariableName: "\"T_HideLocalStandardCatalogs_\""
      DisplayVariable: "HideLocalStandardCatalogs"
  - id: "CallNode3"
    type: "call"
    ref: "This:GetDisplayOptions"
  - id: "CallNode4"
    type: "call"
    ref: "This:GetDisplayVariable"
    bindings:
      VariableName: "\"T_HideSystemClassificationCatalogs_\""
      DisplayVariable: "HideSystemClassificationCatalogs"
  - id: "CallNode6"
    type: "call"
    ref: "This:GetDisplayVariable"
    bindings:
      VariableName: "\"T_HideStandardCatalogs_\""
      DisplayVariable: "HideStandardCatalogs"
  - id: "CallNode8"
    type: "call"
    ref: "This:GetDisplayVariable"
    bindings:
      VariableName: "\"T_HideClassificationCatalogs_\""
      DisplayVariable: "HideClassificationCatalogs"
  - id: "CallNode9"
    type: "call"
    ref: "This:GetDisplayVariable"
    bindings:
      VariableName: "\"T_HideSharedClassificationCatalogs_\""
      DisplayVariable: "HideSharedClassificationCatalogs"
  - id: "ConcatenateStrings1"
    type: "pipelet"
    ref: "ConcatenateStrings"
    config:
      DefaultString2: "_"
      DefaultString0: "T_"
    bindings:
      Concatenated: "DisplayChannelVariable"
      String3: "ChannelID"
      String1: "DisplayVariable"
  - id: "ConcatenateStrings6"
    type: "pipelet"
    ref: "ConcatenateStrings"
    bindings:
      Concatenated: "DisplayChannelVariable"
      String1: "ChannelID"
      String0: "VariableName"
  - id: "Decision1"
    type: "decision"
    condition: "ChannelID"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelCatalog_32-Edit"
      OutValue_1: "ViewChannelCatalog_32-New"
      OutValue_2: "ViewChannelCatalog_32-Remove"
    bindings:
      Key_0: "edit"
      Key_1: "create"
      Key_2: "delete"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: true
    outputs:
      - key: "DisplayVariable"
        type: "java.lang.String"
        guaranteed: false
  - id: "ExchangeSessionObject1"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
    bindings:
      SessionObjectName: "DisplayChannelVariable"
      SaveObject: "DisplayValue"
  - id: "ExchangeSessionObject6"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
    bindings:
      SessionObjectName: "DisplayChannelVariable"
      LoadObject: "DisplayVariable"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "CurrentSelectedChannel"
      UUID: "ChannelID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "Jump5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "This:ListAll"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelCatalogs"
      WorkingTemplate: "catalog/ChannelCatalogList_32"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      ValueType: "Dictionary Value"
      Value: "ViewChannelCatalogList_32-ListAll"

links:
  - from: "Start1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "Decision1"
    via: "no"
    to: "Join1"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode8"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "ExchangeSessionObject6"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "ConcatenateStrings6"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "ExchangeSessionObject1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "ConcatenateStrings1"
    via: "next"
    to: "ExchangeSessionObject1"
    into: "in"
  - from: "ConcatenateStrings6"
    via: "next"
    to: "ExchangeSessionObject6"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "Call4"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "ConcatenateStrings1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Join1"
    via: "next"
    to: "Join2"
    into: "in3"
