flow: "ViewPromotionPreferenceTypePriorities"
kind: "view"

entries:
  - id: "Start5"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Edit"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "MoveDown"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "MoveUp"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessClipboard-Update"
    bindings:
      ProductRefIDs: "SelectedObjectUUIDIterator"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "DecisionNode1"
    type: "decision"
    condition: "SelectedObjectUUIDs"
  - id: "DispatchFormAction4"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPromotionPreferenceTypePriorities-MoveUp"
      OutValue_1: "ViewPromotionPreferenceTypePriorities-MoveDown"
    bindings:
      Key_0: "moveup.x"
      SelectionKey: "JumpTarget"
      Key_1: "movedown.x"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "Jump3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Repository(\"PromotionBORepository\"):PromotionActionPriorityHandler:SortedDescriptorsByPriority"
      OutValue_1: "ActionDescriptors"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Repository(\"PromotionBORepository\"):PromotionActionPriorityHandler"
      OutValue_1: "PromotionActionPriorityHandler"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Repository(\"PromotionBORepository\"):PromotionActionPriorityHandler:SortedDescriptorsByPriority"
      OutValue_1: "ActionDescriptors"
  - id: "MovePosition1"
    type: "pipelet"
    ref: "MovePromotionActionDescriptorPosition"
    config:
      Direction: "UP"
    bindings:
      SelectedElements: "SelectedObjectUUIDs"
      ResultList: "ActionDescriptors"
      List: "ActionDescriptors"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "marketing/PromotionPreferenceTypePriorities"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Direction"
      Value: "UP"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Direction"
      Value: "DOWN"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "SelectionEmpty"
      Value: true
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewPromotionPreferenceTypePriorities-Edit"
      ValueType: "Dictionary Value"
  - id: "UpdatePromotionActionPriority1"
    type: "pipelet"
    ref: "UpdatePromotionActionPriority"
    bindings:
      PromotionActionPriorityHandler: "ApplicationBO:Repository(\"PromotionBORepository\"):PromotionActionPriorityHandler"

links:
  - from: "DispatchFormAction4"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "KeyMapper3"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "StartNode2"
    via: "next"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "MovePosition1"
    into: "in"
  - from: "MovePosition1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "UpdatePromotionActionPriority1"
    into: "in"
  - from: "SetDictionaryValue5"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "JoinNode4"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "DispatchFormAction4"
    via: "error"
    to: "SetDictionaryValue5"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "DispatchFormAction4"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "UpdatePromotionActionPriority1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "StartNode3"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
