flow: "ViewProductAttributeGroupMapping"
kind: "view"

entries:
  - id: "Start1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "ShowAttributeGroupDetails"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddEntryToMap1"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "SelectedAttributeGroupUUIDMap"
      Key: "AttributeGroupUUID"
      OutMap: "SelectedAttributeGroupUUIDMap"
      Value: "AttributeGroupUUID"
  - id: "Call1"
    type: "call"
    ref: "ProcessProductDataMappingRule-CreateRuleConstruct"
  - id: "Call13"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "Call2"
    type: "call"
    ref: "ProcessProductDataMappingRule-DeleteRuleConstruct"
  - id: "Call3"
    type: "call"
    ref: "ViewProductAttributeMapping-Prefix"
  - id: "Call4"
    type: "call"
    ref: "ViewProductAttributeMapping-Prefix"
  - id: "Call8"
    type: "call"
    ref: "ViewProductAttributeMapping-Prefix"
  - id: "Decision1"
    type: "decision"
    condition: "ProductDataMappingRuleID"
  - id: "Decision2"
    type: "decision"
    condition: "SelectedAttributeGroupUUIDs"
  - id: "Decision3"
    type: "decision"
    condition: "ProductDataMappingRuleID"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProductAttributeGroupMapping-Update"
      OutValue_1: "ViewProductAttributeGroupMapping-Start"
    bindings:
      Key_0: "Update"
      Key_1: "BackToGroupList"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "GetAttributeGroupByUUID1"
    type: "pipelet"
    ref: "GetAttributeGroupByUUID"
    bindings:
      UUID: "AttributeGroupUUID"
  - id: "GetAttributeGroups1"
    type: "pipelet"
    ref: "GetAttributeGroups"
    bindings:
      Domain: "ProvidingRepository:Domain"
      TypeCode: "\"(Integer)0\""
  - id: "GetFirstElementOfIterator1"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      FirstElement: "ProductDataMappingRule"
      Iterator: "ProductDataMappingRules"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedAttributeGroupUUID"
    bindings:
      Selection: "SelectedAttributeGroupUUIDs"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Request Locale"
  - id: "GetProductDataMappingRule1"
    type: "pipelet"
    ref: "GetProductDataMappingRule"
    bindings:
      ProductDataMappingRuleID: "ProductDataMappingRuleID"
  - id: "GetProductDataMappingRuleSet1"
    type: "pipelet"
    ref: "GetProductDataMappingRuleSet"
    bindings:
      DeclaringDomain: "Repository:Domain"
      ProvidingDomain: "ProvidingRepository:Domain"
  - id: "GetProductDataMappingRules1"
    type: "pipelet"
    ref: "GetProductDataMappingRules"
    config:
      DefaultTypeCode: 7
    bindings:
      DeclaringDomain: "ProductDataMappingRuleSet:DeclaringDomain"
      ProvidingDomain: "ProductDataMappingRuleSet:ProvidingDomain"
      TypeCode: "null"
  - id: "GetRepositoryByUUID1"
    type: "pipelet"
    ref: "GetRepositoryByUUID"
    bindings:
      Repository: "ProvidingRepository"
      UUID: "ProviderID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump2"
    type: "jump"
    ref: "ViewProductAttributeGroupMapping-Start"
  - id: "Loop1"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Syndication"
      WorkingTemplate: "syndication/ProductAttributeGroupDetails"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Syndication"
      WorkingTemplate: "syndication/ProductAttributeGroupMapping"
  - id: "UpdateCustomAttribute1"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    config:
      DefaultAttributeName: "AttributeGroupUUIDs"
      DefaultAttributeType: "MultipleString"
    bindings:
      AttributeValue: "SelectedAttributeGroupUUIDs"
      ExtensibleObject: "ProductDataMappingRule"

links:
  - from: "Start7"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "GetProductDataMappingRules1"
    into: "in"
  - from: "GetAttributeGroups1"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "DispatchFormAction2"
    into: "in"
  - from: "DispatchFormAction2"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "GetProductDataMappingRules1"
    via: "next"
    to: "GetFirstElementOfIterator1"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "GetAttributeGroups1"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "Decision1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Decision3"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Call1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "GetProductDataMappingRule1"
    into: "in"
  - from: "GetProductDataMappingRule1"
    via: "next"
    to: "Join4"
    into: "in3"
  - from: "Call1"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "Decision3"
    via: "no"
    to: "Call2"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "Join5"
    into: "in1"
  - from: "Call13"
    via: "next"
    to: "GetProductDataMappingRuleSet1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "Join5"
    into: "in3"
  - from: "Join6"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "Join6"
    into: "in3"
  - from: "Join4"
    via: "next"
    to: "UpdateCustomAttribute1"
    into: "in"
  - from: "UpdateCustomAttribute1"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "GetFirstElementOfIterator1"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "AddEntryToMap1"
    into: "in"
  - from: "AddEntryToMap1"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Loop1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "GetFirstElementOfIterator1"
    via: "error"
    to: "Join3"
    into: "in3"
  - from: "Start6"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "GetAttributeGroupByUUID1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "GetAttributeGroupByUUID1"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "Join7"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "GetAttributeGroupByUUID1"
    via: "error"
    to: "Join7"
    into: "in3"
  - from: "Call4"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "GetRepositoryByUUID1"
    into: "in"
  - from: "GetRepositoryByUUID1"
    via: "next"
    to: "Call13"
    into: "in"
  - from: "GetProductDataMappingRuleSet1"
    via: "next"
    to: "End1"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
