flow: "ViewLocalizationExport"
kind: "view"

entries:
  - id: "Start2"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "SearchLocale"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "SelectConfiguration"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Export"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "ExportToXliff"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "SelectApp"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "ExportToProperties"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddEntryToMap1"
    type: "pipelet"
    ref: "AddEntryToMap"
    bindings:
      InMap: "LocalesMap"
      Key: "ModifiedLocaleHolder"
      Value: "LocaleID"
      OutMap: "LocalesMap"
  - id: "Call1"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessLocalizations-GetLocalizationRepositories"
    bindings:
      DomainUUID: "CurrentOrganization:DomainID"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessClipboard-Get"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessLocalizations-GetLocalizationRepositories"
    bindings:
      DomainUUID: "CurrentOrganization:DomainID"
  - id: "CallNode8"
    type: "call"
    ref: "ProcessImpexJob-Create"
  - id: "CallNode9"
    type: "call"
    ref: "ProcessLocalizations-GetContextApp"
  - id: "CreateModifiedLocale1"
    type: "pipelet"
    ref: "CreateModifiedLocale"
    bindings:
      TargetLocaleID: "LocaleID"
      ModifiedTargetID: "FormRecord:ModifiedLocaleID"
  - id: "CreatePageableFromIterator2"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    config:
      Pagesize: 1000000
    bindings:
      Iterator: "LocalesMap:KeySet:Iterator"
      Pageable: "LocalesToExport"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "ExportFileName"
      param.1.required: true
      param.1.rule: "^[^.\\\\/:*?<>|\\s]([^\\\\/:*?<>|\\s]*[^.\\\\/:*?<>|\\s])?$"
      webform-id: "LocalizationExportForm"
      param.2.name: "CharacterSet"
      param.2.rule: "^[^.\\\\/:*?<>|\\s]([^\\\\/:*?<>|\\s]*[^.\\\\/:*?<>|\\s])?$"
      param.2.required: true
      param.3.name: "ExportSourceLanguage"
      param.3.rule: "^[^.\\\\/:*?|\\s]([^\\\\/:*?|\\s]*[^.\\\\/:*?|\\s])?$"
      param.3.required: true
    bindings:
      WebForm: "LocalizationExportForm"
  - id: "DecisionNode1"
    type: "decision"
    condition: "UUIDIterator"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewLocalizationExport-SelectConfiguration"
      OutValue_1: "ViewLocalizationExport-Export"
      OutValue_2: "ViewLocalizationImpex-Status"
      OutValue_3: "ViewLocalizationExport-SearchLocale"
      OutValue_4: "ViewLocalizationExport-SelectApp"
      OutValue_5: "ViewLocalizationExport-SelectExportFileFormat"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "SelectConfiguration"
      Key_1: "LocalizationExport"
      Key_2: "Cancel"
      Key_3: "SearchLocale"
      Key_4: "SelectApp"
      Key_5: "SelectExportFileFormat"
  - id: "GetFormRecord1"
    type: "pipelet"
    ref: "GetFormRecord"
    bindings:
      RecordID: "LocaleID"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "LocalizationExportForm"
    bindings:
      WebForm: "LocalizationExportForm"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "Jump4"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewLocalizationImpex-Status"
  - id: "JumpNode2"
    type: "jump"
    ref: "This:SelectApp"
  - id: "JumpNode3"
    type: "jump"
    ref: "Error-Start"
  - id: "JumpNode4"
    type: "jump"
    ref: "This:SelectApp"
  - id: "KeyMapper10"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      OutValue_1: "JobDescription"
      InValue_1: "\"Export Localizations\""
      InValue_2: "\"ProcessLocalizationImpex\""
      OutValue_2: "JobPipelineName"
      InValue_3: "\"Export\""
      OutValue_3: "JobPipelineStartNode"
      InValue_4: "\"ProcessLocalizationImpex\""
      OutValue_4: "JobName"
      InValue_5: "\"ProcessLocalizationImpex\""
      OutValue_5: "ProcessPipelineName"
      OutValue_6: "ProcessPipelineStartNode"
      InValue_6: "\"Export\""
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "LocalesToExport:ID"
      OutValue_1: "PageableID"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentOrganization:Domain:Site"
      InValue_2: "CurrentOrganization:Domain:Site"
      OutValue_1: "ProcessOwningDomain"
      OutValue_2: "ProcessExecutionDomain"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "CurrentOrganization:Domain:Site:UUID"
      OutValue_1: "LocalizationDomainUUID"
      OutValue_2: "SelectedFile"
      InValue_2: "LocalizationExportForm_ExportFileName"
      InValue_3: "\"localization\""
      OutValue_3: "ExportDirectory"
      InValue_4: "LocalizationContextSerial"
      OutValue_4: "LocalizationContextSerial"
  - id: "LoopNode2"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "localization/LocalizationExportSelectApp"
      SelectedMenuItem: "Localization"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "CreateLocalizationContextFromApp"
    bindings:
      App: "ContextApp"
      OwningDomain: "CurrentOrganization:Domain"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "SerializeToString"
    bindings:
      SerializeObject: "LocalizationContext"
      SerializedValue: "LocalizationContextSerial"
  - id: "Pipelet4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "ExportFileFormat"
      InValue_1: "\"xliff\""
  - id: "Pipelet5"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"properties\""
      OutValue_1: "ExportFileFormat"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Localization"
      WorkingTemplate: "localization/LocalizationExportConfiguration"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Localization"
      WorkingTemplate: "localization/LocalizationExportSearchLocale"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "LocalizationExportForm"
    bindings:
      WebForm: "LocalizationExportForm"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "LocalizationExportForm"

links:
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "CreateWebForm1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode1"
    into: "in3"
  - from: "StartNode3"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "ValidateWebForm1"
    via: "error"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "Call1"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "StartNode2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CreateModifiedLocale1"
    via: "next"
    to: "AddEntryToMap1"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "ValidateWebForm1"
    via: "next"
    to: "KeyMapper10"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "AddEntryToMap1"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "LoopNode2"
    via: "do"
    to: "GetFormRecord1"
    into: "in"
  - from: "GetFormRecord1"
    via: "next"
    to: "CreateModifiedLocale1"
    into: "in"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "Start2"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "CreateWebForm1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "Pipelet4"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CreatePageableFromIterator2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "DetermineLocales1"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "Pipelet4"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "KeyMapper3"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "KeyMapper10"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet3"
    via: "error"
    to: "JumpNode3"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "Pipelet5"
    into: "in"
  - from: "Pipelet5"
    via: "next"
    to: "JumpNode4"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "CreatePageableFromIterator2"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "CallNode8"
    into: "in"
