flow: "ViewPageComponentLabelAction"
kind: "view"

entries:
  - id: "Start5"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "ConfirmAction"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "ConfigureAction"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "ConfigureActionParameters"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "ExecuteAction"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddParameterDefinitionToWebForm2"
    type: "pipelet"
    ref: "AddParameterDefinitionToWebForm"
    config:
      param.1.name: "OnlineFlag"
      param.1.required: true
      param.2.name: "ValidFrom_Day"
      param.2.required: false
      param.3.name: "ValidFrom_Time"
      param.4.name: "ValidTo_Day"
      param.5.name: "ValidTo_Time"
      param.5.required: false
      param.4.required: false
      param.3.required: false
      param.6.name: "DatePattern"
      param.6.required: false
    bindings:
      WebForm: "ActionParameterForm"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessLabel-GetActionTemplateByUUID"
    bindings:
      ActionTemplateUUID: "ActionParameterForm_SelectedActionID"
  - id: "CallNode12"
    type: "call"
    ref: "ViewLabel-Prefix"
  - id: "CallNode18"
    type: "call"
    ref: "ProcessPaging-SetPageNumber"
    bindings:
      Pageable: "FilteredLabelAssignments"
  - id: "CallNode2"
    type: "call"
    ref: "ViewPageComponentLabelAction-ConfigureActionParameters"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessDate-VerifyPeriod"
    bindings:
      PeriodFlag: "ActionParameterForm_OnlineFlag"
      DatePattern: "ActionParameterForm_DatePattern"
      ValidFrom_Day: "ActionParameterForm_ValidFrom_Day"
      ValidFrom_Time: "ActionParameterForm_ValidFrom_Time"
      ValidTo_Day: "ActionParameterForm_ValidTo_Day"
      ValidTo_Time: "ActionParameterForm_ValidTo_Time"
  - id: "CallNode4"
    type: "call"
    ref: "ViewPageComponentLabelAction-ConfigureActionParameters"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessDate-ConvertPeriodToString"
    bindings:
      ValidFromDate: "ValidFrom"
      ValidToDate: "ValidTo"
      ValidToString: "ValidToString"
      ValidFromString: "ValidFromString"
  - id: "CallNode6"
    type: "call"
    ref: "ProcessLabel-GetFilteredLabelAssignments"
  - id: "DecisionNode2"
    type: "decision"
    condition: "CurrentChannel"
  - id: "DispatchFormAction2"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewPageComponentLabelAction-ConfirmAction"
      OutValue_1: "ViewLabelAction-SelectAction"
      OutValue_2: "ViewPageComponentLabelAction-ExecuteAction"
      OutValue_3: "ViewLabelAction-ConfigureAction"
      OutValue_4: "ViewLabelAction-SelectAction"
    bindings:
      SelectionKey: "JumpTarget"
      OutValue_4: "ApplicationState:ExitFromWizard:Pipeline"
      Key_0: "confirmAction"
      Key_1: "cancelAction"
      Key_2: "executeAction"
      Key_3: "configureAction"
      Key_4: "selectAction"
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "GetWebForm5"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "ActionParameterForm"
    bindings:
      WebForm: "ActionParameterForm"
  - id: "InteractionEnd4"
    type: "interaction"
  - id: "InteractionEnd6"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "Jump3"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewPageComponentLabelAction-ConfigureAction"
  - id: "JumpNode4"
    type: "jump"
    ref: "ViewLabelAction-ExecuteAction"
  - id: "JumpNode5"
    type: "jump"
    ref: "ViewChannelLabelAction-ExecuteAction"
  - id: "PrepareApplicationView4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "MassDataTasks"
      WorkingTemplate: "labeling/LabelConfigurePageComponentAction"
  - id: "PrepareApplicationView6"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Label"
      WorkingTemplate: "labeling/LabelConfirmPageComponentAction"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ObjectType"
      Value: "Pagelet"
      ValueType: "Dictionary Value"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ActionParameterTemplate"
      Value: "labeling/inc/PageComponentActionParameters"
  - id: "SetPageLocator2"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewChannelLabelItems-Paging"
      DefaultPageLocatorName: "FilteredLabelAssignments"
    bindings:
      Pageable: "FilteredLabelAssignments"
      HandlerPipeline: "null"
      PageLocatorName: "null"
  - id: "UpdatePageSize3"
    type: "pipelet"
    ref: "UpdatePageSize"
    config:
      DefaultPageSize: 15
    bindings:
      PageableIterator: "FilteredLabelAssignments"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "ActionParameterForm"
    bindings:
      WebForm: "ActionParameterForm"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "ActionParameterForm"

links:
  - from: "PrepareApplicationView4"
    via: "next"
    to: "InteractionEnd4"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "UpdatePageSize3"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "SetPageLocator2"
    via: "next"
    to: "PrepareApplicationView6"
    into: "in"
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "ValidateWebForm1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "GetWebForm5"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "AddParameterDefinitionToWebForm2"
    into: "in"
  - from: "AddParameterDefinitionToWebForm2"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "CallNode3"
    via: "ERROR"
    to: "JoinNode1"
    into: "in2"
  - from: "StartNode3"
    via: "next"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "ValidateWebForm1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "PrepareApplicationView4"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JumpNode3"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "DispatchFormAction2"
    into: "in"
  - from: "PrepareApplicationView6"
    via: "next"
    to: "InteractionEnd6"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "JumpNode5"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JumpNode4"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DispatchFormAction2"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "GetWebForm5"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "UpdatePageSize3"
    via: "next"
    to: "CallNode18"
    into: "in"
  - from: "CallNode18"
    via: "next"
    to: "SetPageLocator2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode12"
    into: "in"
