flow: "ViewProductRecommDataFeedGeneral"
kind: "view"

entries:
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "New"
    mode: "private"
    strict: false
    inputs:
      - key: "LocaleId"
        type: "java.lang.String"
        required: false
  - id: "StartNode1"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      - key: "SyndicationUUID"
        type: "java.lang.String"
        required: true
      - key: "LocaleId"
        type: "java.lang.String"
        required: false
      - key: "ConfirmDelete"
        type: "java.lang.String"
        required: false
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Delete"
    mode: "private"
    strict: false
    inputs:
      - key: "SyndicationUUID"
        type: "java.lang.String"
        required: false

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ProcessRecommendationServices-GetActiveRecommServices"
    bindings:
      Domain: "CurrentChannel:Domain"
  - id: "CallNode12"
    type: "call"
  - id: "CallNode2"
    type: "call"
  - id: "CallNode9"
    type: "call"
  - id: "CreateJobConfiguration3"
    type: "pipelet"
    ref: "CreateJobConfiguration"
    bindings:
      Domain: "CurrentChannel:RepositoryDomain"
  - id: "CreateWebForm2"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "DataFeedName"
      param.1.required: true
      param.1.rule: "^[^\\s].*$"
      param.2.name: "Enabled"
      param.2.required: false
      param.2.rule: ""
      param.3.name: "Description"
      param.3.required: false
      webform-id: "ProductRecommendationForm"
      param.3.rule: ""
    bindings:
      WebForm: "ProductRecommendationForm"
  - id: "DecisionNode1"
    type: "decision"
    condition: "JobUUID"
  - id: "DecisionNode12"
    type: "decision"
    condition: "RecommendationService:Capabilities:BODataFeedUpdateParamPipeline"
  - id: "DecisionNode2"
    type: "decision"
    condition: "RecommendationService:Capabilities:BODataFeedPrepareParamPipeline"
  - id: "DecisionNode3"
    type: "decision"
    condition: "ProductRecommendationForm_Enabled"
  - id: "DecisionNode9"
    type: "decision"
    condition: "RecommendationService:Capabilities:BODataFeedValidateParamPipeline"
  - id: "DetermineLocales3"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewProductRecommDataFeedGeneral-New"
      OutValue_1: "ViewProductRecommDataFeedGeneral-Update"
      OutValue_2: "ViewProductRecommDataFeedGeneral-Edit"
      OutValue_3: "ViewProductRecommDataFeedGeneral-Update"
      OutValue_4: "ViewProductRecommDataFeedGeneral-Edit"
      OutValue_5: "ViewProductRecommDataFeedGeneral-Delete"
      OutValue_6: "ViewProductRecommDataFeedList-Start"
      OutValue_7: "ViewProductRecommDataFeedList-Start"
      OutValue_8: "ViewProductRecommDataFeedGeneral-Edit"
      OutValue_9: "ViewProductRecommDataFeedGeneral-New"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "New"
      Key_1: "Create"
      Key_2: "Edit"
      Key_3: "Update"
      Key_4: "ConfirmDelete"
      Key_5: "Delete"
      Key_6: "Back"
      Key_7: "Cancel"
      Key_8: "SetLocaleEdit"
      Key_9: "SetLocaleNew"
  - id: "GetJobConfiguration2"
    type: "pipelet"
    ref: "GetJobConfiguration"
  - id: "GetJobConfiguration3"
    type: "pipelet"
    ref: "GetJobConfiguration"
  - id: "GetJobConfiguration5"
    type: "pipelet"
    ref: "GetJobConfiguration"
  - id: "GetLocale4"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetLocale5"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Session Locale"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "ProductRecommendationForm"
    bindings:
      WebForm: "ProductRecommendationForm"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "ViewProductRecommDataFeedGeneral-Edit"
  - id: "Jump5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewProductRecommDataFeedList-Start"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      OutValue_1: "JobUUID"
      InValue_1: "JobConfiguration:UUID"
      InValue_2: "\"True\""
      OutValue_2: "HaveBeenCreated"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetServiceByID"
    bindings:
      ServiceID: "RecommendationServiceID"
      Service: "RecommendationService"
  - id: "Pipelet2"
    type: "pipelet"
    ref: "GetCustomAttributes"
    config:
      InclusionAttributes: "ExportType"
    bindings:
      ExtensibleObject: "JobConfiguration"
      AttributeValuesMap: "JobConfigMap"
  - id: "Pipelet3"
    type: "pipelet"
    ref: "GetServiceByID"
    bindings:
      ServiceID: "JobConfigMap:ExportType:StringValue"
      Service: "RecommendationService"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/ProductRecommDataFeedGeneral"
  - id: "RemoveJobConfiguration1"
    type: "pipelet"
    ref: "RemoveJobConfiguration"
  - id: "SetDictionaryValue7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ProductRecommendationForm_Enabled"
      Value: false
      ValueType: "Form Value"
  - id: "UpdateCustomAttribute1"
    type: "pipelet"
    ref: "UpdateCustomAttribute"
    config:
      DefaultAttributeName: "LocalizedDescription"
      DefaultAttributeType: "String"
    bindings:
      ExtensibleObject: "JobConfiguration"
      AttributeValue: "ProductRecommendationForm_Description"
      LocaleInformation: "Locale"
  - id: "UpdateCustomAttributes1"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "DataFeedName"
      Attribute_1_Type: "String"
      Attribute_2_Type: "String"
      Attribute_10_Type: "String"
      Attribute_10_Name: "ExportType"
      Attribute_3_Type: "String"
      Attribute_2_Name: "ChannelID"
      Attribute_3_Name: "DomainName"
      Attribute_4_Name: "ExportLocaleID"
      Attribute_4_Type: "String"
    bindings:
      ExtensibleObject: "JobConfiguration"
      Attribute_1_Value: "ProductRecommendationForm_DataFeedName"
      Attribute_10_Value: "RecommendationService:ID"
      Attribute_2_Value: "ChannelID"
      Attribute_3_Value: "CurrentChannel:RepositoryDomain:DomainName"
      Attribute_4_Value: "Locale:LocaleID"
  - id: "UpdateJobConfiguration1"
    type: "pipelet"
    ref: "UpdateJobConfiguration"
    config:
      EnableJob: false
      Interval: 1
      Name: "ProductRecomendation"
      PipelineStartNode: "Start"
      Unit: "Years"
    bindings:
      JobDescription: "ProductRecommendationForm_Description"
      JobDate: "null"
      JobDomain: "null"
      JobDomainName: "null"
      JobEnable: "ProductRecommendationForm_Enabled"
      JobInterval: "null"
      JobJavaDate: "null"
      JobName: "null"
      JobUnit: "null"
      JobUUID: "null"
      JobPipelineName: "RecommendationService:Capabilities:BODataFeedJobPipelineName"
      JobPipelineStartNode: "RecommendationService:Capabilities:BODataFeedJobPipelineStartNode"
  - id: "UpdateWebForm2"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "ProductRecommendationForm"
    bindings:
      WebForm: "ProductRecommendationForm"
  - id: "ValidateWebForm2"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "ProductRecommendationForm"
  - id: "VerifyBoolean3"
    type: "pipelet"
    ref: "VerifyBoolean"
    bindings:
      BooleanValue: "Enabled"
      NoneLocalizedString: "ProductRecommendationForm_Enabled"

links:
  - from: "GetJobConfiguration2"
    via: "error"
    to: "CreateJobConfiguration3"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode9"
    via: "yes"
    to: "CallNode9"
    into: "in"
  - from: "VerifyBoolean3"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "CallNode12"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "CallNode9"
    via: "ERROR"
    to: "JoinNode6"
    into: "in1"
  - from: "DecisionNode12"
    via: "no"
    to: "Jump2"
    into: "in"
  - from: "UpdateCustomAttributes1"
    via: "next"
    to: "UpdateCustomAttribute1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "GetJobConfiguration3"
    via: "next"
    to: "RemoveJobConfiguration1"
    into: "in"
  - from: "DetermineLocales3"
    via: "next"
    to: "GetLocale5"
    into: "in"
  - from: "ValidateWebForm2"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "StartNode3"
    via: "next"
    to: "GetJobConfiguration3"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "SetDictionaryValue7"
    into: "in"
  - from: "UpdateJobConfiguration1"
    via: "next"
    to: "UpdateCustomAttributes1"
    into: "in"
  - from: "ValidateWebForm2"
    via: "next"
    to: "VerifyBoolean3"
    into: "in"
  - from: "GetLocale5"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "RemoveJobConfiguration1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "GetWebForm2"
    via: "next"
    to: "UpdateWebForm2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "DecisionNode9"
    into: "in"
  - from: "GetWebForm2"
    via: "error"
    to: "JoinNode5"
    into: "in2"
  - from: "GetJobConfiguration5"
    via: "next"
    to: "Pipelet2"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "UpdateJobConfiguration1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "DetermineLocales3"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "CreateWebForm2"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode3"
    into: "in1"
  - from: "CreateWebForm2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "SetDictionaryValue7"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "UpdateWebForm2"
    via: "next"
    to: "ValidateWebForm2"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "JoinNode3"
    via: "next"
    to: "GetLocale4"
    into: "in"
  - from: "Pipelet2"
    via: "next"
    to: "Pipelet3"
    into: "in"
  - from: "CreateJobConfiguration3"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "Pipelet3"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "GetLocale4"
    via: "next"
    to: "GetJobConfiguration2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetJobConfiguration5"
    into: "in"
  - from: "DecisionNode9"
    via: "no"
    to: "JoinNode7"
    into: "in2"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "CallNode2"
    into: "in"
  - from: "GetJobConfiguration2"
    via: "next"
    to: "UpdateJobConfiguration1"
    into: "in"
  - from: "UpdateCustomAttribute1"
    via: "next"
    to: "DecisionNode12"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "JoinNode4"
    into: "in1"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DecisionNode12"
    via: "yes"
    to: "CallNode12"
    into: "in"
