flow: "ViewWarrantyPreferences"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "View"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Apply"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "WarrantyPreferences"
      FormResource: "WarrantyPreferences"
    bindings:
      Form: "Form"
  - id: "CreateForm2"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "WarrantyPreferences"
      FormResource: "WarrantyPreferences"
    bindings:
      Form: "Form"
  - id: "DecisionNode1"
    type: "decision"
    condition: "Form:Enabled:Value"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Enabled"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewWarrantyPreferences-Apply"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "updateSettings"
  - id: "GetDomainPreference9"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "String"
      DefaultPreferenceKey: "WarrantyEnabled"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      PreferenceStringValue: "Enabled"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "warranty/WarrantyPreferences"
  - id: "SetDictionaryValue9"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewWarrantyPreferences-View"
      ValueType: "Dictionary Value"
  - id: "SetDomainPreference1"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      Type: "String"
      DefaultPreferenceKey: "WarrantyEnabled"
      DefaultPreferenceValue: false
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
  - id: "SetDomainPreference2"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      Type: "String"
      DefaultPreferenceKey: "WarrantyEnabled"
      DefaultPreferenceValue: true
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
  - id: "SetFormParameterValue1"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      FormParameter: "Form:Enabled"
      Value: "\"(Boolean)true\""
  - id: "SetFormParameterValue2"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      FormParameter: "Form:Enabled"
      Value: "\"(Boolean)true\""
  - id: "SetFormParameterValue3"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      FormParameter: "Form:Enabled"
      Value: "\"(Boolean)false\""
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    config:
      Trim: true
    bindings:
      Form: "Form"

links:
  - from: "SetDictionaryValue9"
    via: "next"
    to: "JoinNode8"
    into: "in3"
  - from: "DecisionNode2"
    via: "no"
    to: "SetFormParameterValue3"
    into: "in"
  - from: "SetFormParameterValue1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "CreateForm2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "SetDomainPreference1"
    into: "in"
  - from: "SetFormParameterValue2"
    via: "next"
    to: "JoinNode7"
    into: "in2"
  - from: "JoinNode2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "SetDomainPreference2"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JoinNode2"
    into: "in3"
  - from: "SetDomainPreference1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "ValidateForm1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "SetDomainPreference2"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "DecisionNode1"
    via: "yes"
    to: "SetDomainPreference2"
    into: "in"
  - from: "SetDomainPreference1"
    via: "error"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode4"
    into: "in2"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "JoinNode6"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "GetDomainPreference9"
    via: "error"
    to: "SetFormParameterValue2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "SetFormParameterValue1"
    into: "in"
  - from: "SetFormParameterValue3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue9"
    into: "in"
  - from: "JoinNode8"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "GetDomainPreference9"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "GetDomainPreference9"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "CreateForm2"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "ValidateForm1"
    via: "error"
    to: "JoinNode5"
    into: "in2"
