flow: "ViewContentPreferences_52"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "View"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Apply"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "PreviewSettings"
      FormResource: "PreviewSettings"
    bindings:
      Form: "PreviewSettingsForm"
  - id: "CreateForm2"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "PreviewSettings"
      FormResource: "PreviewSettings"
    bindings:
      Form: "PreviewSettingsForm"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PreviewSettingsForm:ReadonlyIfFuture:Value"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewContentPreferences_52-Apply"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "updateSettings"
  - id: "GetDomainPreference1"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      Type: "String"
      DefaultPreferenceKey: "SFEReadonlyIfFuture"
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
      Preference: "ReadonlyIfFuturePreference"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelDomainPreference"
      WorkingTemplate: "channel/ChannelPreviewSettings_52"
  - id: "SetDictionaryValue9"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewContentPreferences_52-View"
      ValueType: "Dictionary Value"
  - id: "SetDomainPreference1"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      Type: "String"
      DefaultPreferenceKey: "SFEReadonlyIfFuture"
      DefaultPreferenceValue: false
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
  - id: "SetDomainPreference4"
    type: "pipelet"
    ref: "SetDomainPreference"
    config:
      Type: "String"
      DefaultPreferenceKey: "SFEReadonlyIfFuture"
      DefaultPreferenceValue: true
    bindings:
      PreferenceDomain: "ChannelRepository:Domain"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    config:
      Trim: true
    bindings:
      Form: "PreviewSettingsForm"

links:
  - from: "JoinNode8"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "SetDomainPreference1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "SetDomainPreference4"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "ValidateForm1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "GetDomainPreference1"
    into: "in"
  - from: "ValidateForm1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "SetDomainPreference4"
    into: "in"
  - from: "SetDomainPreference1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "SetDomainPreference4"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetDomainPreference1"
    via: "error"
    to: "JoinNode3"
    into: "in2"
  - from: "SetDictionaryValue9"
    via: "next"
    to: "JoinNode8"
    into: "in3"
  - from: "GetDomainPreference1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "SetDomainPreference1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue9"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CreateForm2"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "CreateForm2"
    into: "in"
