flow: "ViewParametricSearch"
kind: "process"

entries:
  - id: "Start1"
    name: "SimpleParentChannelProductSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "SearchMasterProduct"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "SimpleMasterProductSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "SimpleChannelProductSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "SearchChannelProduct"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "SearchParentChannelProduct"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "SimpleProductSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "SearchProduct"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "DetermineRepository"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "AdvancedSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "SimpleSearch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessProductSearch-SimpleSearchInCategory"
    bindings:
      NameOrID: "ExpNameOrID"
      ProductDomain: "SearchRepository:Domain"
  - id: "Call10"
    type: "call"
    ref: "ProcessProductSearch-SimpleSearch"
    bindings:
      NameOrID: "ExpNameOrID"
      ProductDomain: "SearchRepository:Domain"
  - id: "Call13"
    type: "call"
  - id: "Call9"
    type: "call"
    ref: "ProcessProductSearch-ParametricSearch"
    bindings:
      ProductDomain: "SearchRepository:Domain"
      SortDirection: "SortDirection"
      ProductSearchParameters: "AdvancedSearchParameters"
  - id: "CallNode1"
    type: "call"
    ref: "ViewParametricSearch-AdvancedSearch"
  - id: "CallNode10"
    type: "call"
    ref: "ViewParametricSearch-SimpleSearch"
  - id: "CallNode2"
    type: "call"
    ref: "ViewParametricSearch-SimpleSearch"
  - id: "CallNode3"
    type: "call"
    ref: "ViewParametricSearch-DetermineRepository"
  - id: "CallNode4"
    type: "call"
    ref: "ViewParametricSearch-DetermineRepository"
  - id: "CallNode5"
    type: "call"
    ref: "ViewParametricSearch-AdvancedSearch"
  - id: "CallNode6"
    type: "call"
    ref: "ViewParametricSearch-SimpleSearch"
  - id: "CallNode7"
    type: "call"
    ref: "ViewParametricSearch-AdvancedSearch"
  - id: "CallNode8"
    type: "call"
    ref: "ViewParametricSearch-SimpleSearch"
  - id: "CallNode9"
    type: "call"
    ref: "ViewParametricSearch-AdvancedSearch"
  - id: "DecisionNode1"
    type: "decision"
    condition: "CatalogCategory"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End10"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "End5"
    type: "end"
    strict: false
  - id: "End6"
    type: "end"
    strict: false
  - id: "End7"
    type: "end"
    strict: false
  - id: "End8"
    type: "end"
    strict: false
  - id: "End9"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "EndNode3"
    type: "end"
    strict: false
  - id: "GetFirstElementOfIterator1"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      Iterator: "Repositories"
      FirstElement: "SearchRepository"
  - id: "JoinNode1"
    type: "join"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "DetermineRepositoriesPipeline"
      Value: "DetermineRepositories-Master"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "DetermineRepositoriesPipeline"
      Value: "DetermineRepositories-Master"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "DetermineRepositoriesPipeline"
      Value: "DetermineRepositories-SelectedChannel"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "DetermineRepositoriesPipeline"
      Value: "DetermineRepositories-SelectedChannel"
  - id: "SetDictionaryValue5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "DetermineRepositoriesPipeline"
      Value: "DetermineRepositories-ParentChannel"
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "DetermineRepositoriesPipeline"
      Value: "DetermineRepositories-ParentChannel"
  - id: "SetDictionaryValue8"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "DetermineRepositoriesPipeline"
      Value: "DetermineRepositories-ByUUID"
  - id: "SetDictionaryValue9"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "DetermineRepositoriesPipeline"
      Value: "DetermineRepositories-ByUUID"

links:
  - from: "SetDictionaryValue1"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "Call13"
    via: "next"
    to: "GetFirstElementOfIterator1"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "End4"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "End3"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "End3"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "End4"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "SetDictionaryValue5"
    into: "in"
  - from: "CallNode6"
    via: "ERROR"
    to: "End5"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "End2"
    into: "in"
  - from: "CallNode8"
    via: "ERROR"
    to: "End9"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "End1"
    into: "in"
  - from: "SetDictionaryValue5"
    via: "next"
    to: "CallNode8"
    into: "in"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "SetDictionaryValue9"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "SetDictionaryValue8"
    into: "in"
  - from: "SetDictionaryValue8"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "SetDictionaryValue9"
    into: "in"
  - from: "CallNode9"
    via: "ERROR"
    to: "End10"
    into: "in"
  - from: "CallNode7"
    via: "ERROR"
    to: "End9"
    into: "in"
  - from: "GetFirstElementOfIterator1"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode10"
    via: "ERROR"
    to: "End10"
    into: "in"
  - from: "GetFirstElementOfIterator1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Call9"
    via: "ERROR"
    to: "End6"
    into: "in"
  - from: "Call10"
    via: "ERROR"
    to: "End7"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "CallNode1"
    via: "ERROR"
    to: "End8"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode2"
    via: "ERROR"
    to: "End8"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "End1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "Call10"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "Call1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "Call1"
    via: "ERROR"
    to: "End7"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "Call13"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "EndNode3"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "CallNode5"
    via: "ERROR"
    to: "End5"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
