flow: "ViewChannelOutboundSyndicationIDMapping"
kind: "view"

entries:
  - id: "Start3"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector1"
    type: "pipelet"
    ref: "AddObjectToVector"
    bindings:
      InVector: "Vector"
      Iterator: "SelectedRules"
      Object: "FormRecord:RuleID"
      OutVector: "Vector"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessSyndicationRule-GetDataDeclarationList"
    bindings:
      Name: "\"ProductIdentifier\""
  - id: "CallNode2"
    type: "call"
    ref: "ProcessSyndicationRule-GetRuleSet"
    bindings:
      Name: "\"ProductIdentifier\""
  - id: "CallNode3"
    type: "call"
    ref: "ProcessSyndicationRule-GetRuleSet"
    bindings:
      Name: "\"ProductIdentifier\""
  - id: "CombineIterators1"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Subtract Iterators"
    bindings:
      Iterator: "ToBeDeleted"
      Iterator1: "AllRules"
      Iterator2: "SelectedRules"
  - id: "CreateSyndicationDataDeclaration1"
    type: "pipelet"
    ref: "CreateSyndicationDataDeclaration"
    bindings:
      Domain: "Syndication:Domain"
      DataObjectClassName: "\"com.intershop.beehive.xcs.internal.product.ProductPO\""
  - id: "CreateSyndicationRule1"
    type: "pipelet"
    ref: "CreateSyndicationRule"
    bindings:
      SyndicationRuleClass: "\"com.intershop.component.mvc.internal.syndication.mapping.ProductIdentifierMappingRule\""
      Domain: "Syndication:Domain"
      SourceSyndicationDataDeclaration: "SyndicationDataDeclaration"
  - id: "Decision1"
    type: "decision"
    condition: "SelectedRules"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Rule:UUID"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelOutboundSyndicationIDMapping-Start"
      OutValue_1: "ViewChannelOutboundSyndicationIDMapping-Update"
      OutValue_2: "ViewChannelOutboundSyndicationList-Start"
    bindings:
      SelectionKey: "JumpTarget"
      Key_0: "Start"
      Key_1: "Apply"
      Key_2: "Back"
  - id: "GetFormRecord1"
    type: "pipelet"
    ref: "GetFormRecord"
    config:
      DefaultRecordID: "Prefix"
    bindings:
      RecordID: "Prefix"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "RuleID"
    bindings:
      Selection: "AllRules"
  - id: "GetFormSelection2"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "ProductIdentifierType"
  - id: "GetSyndicationByUUID1"
    type: "pipelet"
    ref: "GetSyndicationByUUID"
  - id: "GetSyndicationByUUID2"
    type: "pipelet"
    ref: "GetSyndicationByUUID"
  - id: "GetSyndicationRuleByUUID1"
    type: "pipelet"
    ref: "GetSyndicationRuleByUUID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join3"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "Jump5"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewChannelOutboundSyndicationIDMapping-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "AllRules"
      OutValue_1: "ToBeDeleted"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "LoopNode3"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/ChannelOutboundSyndicationIDMapping"
  - id: "RemoveSyndicationRule1"
    type: "pipelet"
    ref: "RemoveSyndicationRule"
  - id: "UpdateCustomAttributes1"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "IdentifierPrefix"
      Attribute_1_Type: "String"
      Attribute_2_Name: "IdentifierSuffix"
      Attribute_2_Type: "String"
    bindings:
      ExtensibleObject: "Rule:SourceSyndicationDataDeclaration"
      Attribute_1_Value: "FormRecord:IdentifierPrefix"
      Attribute_2_Value: "FormRecord:IdentifierSuffix"
  - id: "UpdateCustomAttributes2"
    type: "pipelet"
    ref: "UpdateCustomAttributes"
    config:
      Attribute_1_Name: "IdentifierType"
      Attribute_1_Type: "String"
      Attribute_2_Name: "IdentifierPrefix"
      Attribute_2_Type: "String"
      Attribute_3_Name: "IdentifierSuffix"
      Attribute_3_Type: "String"
    bindings:
      ExtensibleObject: "SyndicationDataDeclaration"
      Attribute_1_Value: "FormRecord:IdentifierType"
      Attribute_2_Value: "FormRecord:IdentifierPrefix"
      Attribute_3_Value: "FormRecord:IdentifierSuffix"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "GetFormRecord1"
    via: "next"
    to: "AddObjectToVector1"
    into: "in"
  - from: "AddObjectToVector1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "LoopNode2"
    into: "loop"
  - from: "DecisionNode2"
    via: "yes"
    to: "UpdateCustomAttributes1"
    into: "in"
  - from: "UpdateCustomAttributes2"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "CreateSyndicationRule1"
    via: "next"
    to: "UpdateCustomAttributes2"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "UpdateCustomAttributes1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "GetFormSelection2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetSyndicationByUUID1"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "CreateSyndicationDataDeclaration1"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "DecisionNode2"
    into: "in"
  - from: "CreateSyndicationDataDeclaration1"
    via: "next"
    to: "CreateSyndicationRule1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "CombineIterators1"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Decision1"
    via: "yes"
    to: "CombineIterators1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Join3"
    into: "in3"
  - from: "Decision1"
    via: "no"
    to: "KeyMapper1"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "GetSyndicationByUUID1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "LoopNode3"
    via: "do"
    to: "GetSyndicationRuleByUUID1"
    into: "in"
  - from: "RemoveSyndicationRule1"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "LoopNode3"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "GetSyndicationRuleByUUID1"
    via: "next"
    to: "RemoveSyndicationRule1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "GetSyndicationByUUID2"
    into: "in"
  - from: "GetSyndicationByUUID2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "GetFormSelection2"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "GetFormRecord1"
    into: "in"
