flow: "ViewPagelet_comp_recentlyviewed"
kind: "view"

entries:
  - id: "StartNode4"
    name: "ViewItems"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentDomain"
        type: "com.intershop.beehive.core.capi.domain.Domain"
        required: true

steps:
  - id: "CallNode1"
    type: "call"
    ref: "DetermineOrganizations-Current"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessRecentlyViewedItems-GetAllTrackedItemsForDomain"
    bindings:
      Domain: "Repository:Domain"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessRecentlyViewedItems-GetAllTrackedItemsForDomain"
    bindings:
      Domain: "CurrentDomain"
  - id: "EndNode4"
    type: "end"
    strict: true
    outputs:
      - key: "KeywordSearches"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "Categories"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "Products"
        type: "java.util.Iterator"
        guaranteed: false
      - key: "EncryptRecentlyViewedItemsData"
        type: "java.lang.Boolean"
        guaranteed: false
      - key: "ProductBOs"
        type: "java.util.Collection<com.intershop.component.product.capi.ProductBO>"
        guaranteed: false
      - key: "CategoryBOs"
        type: "java.util.Collection<com.intershop.component.catalog.capi.CatalogCategoryBO>"
        guaranteed: false
  - id: "GetApplicationBO2"
    type: "pipelet"
    ref: "GetApplicationBO"
  - id: "GetRepositoryByRepositoryDomain1"
    type: "pipelet"
    ref: "GetRepositoryByRepositoryDomain"
    bindings:
      RepositoryDomain: "CurrentOrganization:OwningDomain"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Catalog\"):CatalogBORepository(CurrentOrganization)"
      OutValue_1: "CatalogBORepository"
      InValue_2: "ApplicationBO:Extension(\"Product\"):getProductBORepository(CurrentDomain:UUID)"
      OutValue_2: "ProductBORepository"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Product\"):getProductBORepository(Repository:Domain:UUID)"
      OutValue_1: "ProductBORepository"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Product\"):getProductBORepository(CurrentDomain:UUID)"
      OutValue_1: "ProductBORepository"
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "Error_ApplicationContext"
      Value: "OrganizationNotFound"

links:
  - from: "CallNode1"
    via: "ERROR"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "GetApplicationBO2"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "GetRepositoryByRepositoryDomain1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "GetRepositoryByRepositoryDomain1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "GetApplicationBO2"
    into: "in"
  - from: "GetRepositoryByRepositoryDomain1"
    via: "error"
    to: "KeyMapper3"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "JoinNode1"
    via: "next"
    to: "EndNode4"
    into: "in"
