flow: "ViewProductContent"
kind: "view"

entries:
  - id: "Start1"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode7"
    name: "ListPageletEntryPoints"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call12"
    type: "call"
    ref: "ProcessProduct-Get"
  - id: "Call3"
    type: "call"
    ref: "ProcessProduct-DetermineCategoryPath"
  - id: "CallNode10"
    type: "call"
    ref: "ProcessProductLock-Lock"
    bindings:
      PreferenceDomain: "OrganizationDomain"
      LockingDomain: "OrganizationDomain"
      User: "CurrentUser"
  - id: "CallNode2"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessProductLock-Lookup"
    bindings:
      User: "CurrentUser"
  - id: "DecisionNode14"
    type: "decision"
    condition: "ProductLockActivated"
  - id: "EndNode2"
    type: "end"
    strict: false
  - id: "GetDomainPreference10"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "ProductLockActivated"
      Type: "String"
    bindings:
      PreferenceDomain: "OrganizationDomain"
      PreferenceStringValue: "ProductLockActivated"
  - id: "GetLocale2"
    type: "pipelet"
    ref: "GetLocale"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode30"
    type: "join"
  - id: "Jump9"
    type: "jump"
    ref: "ViewProduct-ErrorProductNotAvailable"
  - id: "KeyMapper13"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentMasterRepository:RepositoryDomain"
      OutValue_1: "ProductDomain"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Products"
      WorkingTemplate: "product/ProductPageletEntryPoints"

links:
  - from: "Call12"
    via: "next"
    to: "GetDomainPreference10"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "StartNode7"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "JoinNode30"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "DecisionNode14"
    via: "no"
    to: "JoinNode30"
    into: "in2"
  - from: "GetDomainPreference10"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "CallNode10"
    via: "next"
    to: "JoinNode30"
    into: "in1"
  - from: "DecisionNode14"
    via: "yes"
    to: "CallNode10"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "GetLocale2"
    via: "next"
    to: "EndNode2"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "KeyMapper13"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "GetLocale2"
    into: "in"
  - from: "GetDomainPreference10"
    via: "next"
    to: "DecisionNode14"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "Call12"
    via: "error-product-not-available"
    to: "Jump9"
    into: "in"
  - from: "KeyMapper13"
    via: "next"
    to: "Call12"
    into: "in"
