flow: "ViewUserExport"
kind: "view"

entries:
  - id: "Start1"
    name: "Back"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start10"
    name: "UpdateClipboard"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start11"
    name: "ParametricSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "SelectConfiguration"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Export"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "SimpleSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "GetClipboard"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "List"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "DeleteClipboard"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Forbid Duplicates"
    bindings:
      InVector: "ObjectVector"
      Iterator: "Objects"
      Object: "User"
      Objects: "null"
      OutVector: "ObjectVector"
  - id: "Call1"
    type: "call"
    ref: "ViewUserExport-Prefix"
  - id: "Call10"
    type: "call"
    ref: "ProcessUserList-BySimpleSearch"
  - id: "Call11"
    type: "call"
    ref: "ViewUserExport-Prefix"
  - id: "Call12"
    type: "call"
    ref: "ProcessUserList-List"
  - id: "Call13"
    type: "call"
    ref: "ViewUserExport-GetClipboard"
  - id: "Call14"
    type: "call"
    ref: "ViewUserExport-GetClipboard"
  - id: "Call2"
    type: "call"
    ref: "ViewUserExport-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ViewUserExport-UpdateClipboard"
  - id: "Call5"
    type: "call"
    ref: "ProcessImpexJob-Create"
  - id: "Call6"
    type: "call"
    ref: "ViewUserExport-GetClipboard"
  - id: "Call7"
    type: "call"
    ref: "ViewUserExport-UpdateClipboard"
  - id: "Call8"
    type: "call"
    ref: "ProcessUserList-ByParametricSearch"
  - id: "Call9"
    type: "call"
    ref: "ViewUserExport-Prefix"
  - id: "CallNode1"
    type: "call"
    ref: "ViewUserExport-DeleteClipboard"
  - id: "CallNode2"
    type: "call"
    ref: "ViewUserExport-DeleteClipboard"
  - id: "CallNode3"
    type: "call"
    ref: "ViewUserExport-DeleteClipboard"
  - id: "CreatePageableFromIterator2"
    type: "pipelet"
    ref: "CreatePageableFromIterator"
    config:
      Pagesize: 1000000
    bindings:
      Iterator: "Objects"
      Pageable: "Users"
  - id: "CreateWebForm1"
    type: "pipelet"
    ref: "CreateWebForm"
    config:
      param.1.name: "ExportFile"
      param.1.required: true
      param.1.rule: "^[^.\\\\/:*?<>|\\s]([^\\\\/:*?<>|\\s]*[^.\\\\/:*?<>|\\s])?$"
      param.2.required: false
      webform-id: "UserExportForm"
    bindings:
      WebForm: "UserExportForm"
  - id: "Decision1"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision2"
    type: "decision"
    condition: "UserExportPageLocator"
  - id: "Decision4"
    type: "decision"
    condition: "ExportSearchResult"
  - id: "DecisionNode1"
    type: "decision"
    condition: "UUIDIterator"
  - id: "DetermineUser2"
    type: "pipelet"
    ref: "DetermineUser"
  - id: "DispatchFormActionByBreadcrumb1"
    type: "pipelet"
    ref: "DispatchFormActionByBreadcrumb"
    config:
      SplitMode: "PipelineAndParameter"
    bindings:
      OutValue_0: "ApplicationState:ExitFromWizard"
      Key_0: "Cancel"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "End3"
    type: "end"
    strict: false
  - id: "End4"
    type: "end"
    strict: false
  - id: "End6"
    type: "end"
    strict: false
  - id: "FilterRolesByPrefix1"
    type: "pipelet"
    ref: "FilterRolesByPrefix"
    config:
      FilterPrefix1: "SLD_AR_"
    bindings:
      FilteredRoles: "AccessRoles"
      SourceRoles: "DomainRoles"
  - id: "GetClipboard2"
    type: "pipelet"
    ref: "GetClipboard"
    config:
      SessionRegistrationID: "UserExportList"
      SetFormValues: "No"
  - id: "GetFormSelection5"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedObjectUUID"
    bindings:
      Selection: "SelectedObjectUUIDs"
  - id: "GetFormSelection6"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "ObjectUUID"
    bindings:
      Selection: "AllObjectUUIDs"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "UserExportPageLocator"
      RestorePageLocatorDictionary: "True"
  - id: "GetPageLocator2"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      RestorePageLocatorDictionary: "True"
      DefaultPageLocatorName: "UserExportPageLocator"
    bindings:
      PageLocator: "UserExportPageLocator"
  - id: "GetPageable2"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Users"
      PageableID: "UserExportPageLocator:PageableID"
  - id: "GetRolesByDomain1"
    type: "pipelet"
    ref: "GetRolesByDomain"
    bindings:
      DomainID: "Organization:DomainID"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "UserExportForm"
    bindings:
      WebForm: "UserExportForm"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "Jump1"
    type: "jump"
  - id: "Jump2"
    type: "jump"
    ref: "ViewOrganizationImpex-Status"
  - id: "Jump5"
    type: "jump"
    ref: "ViewOrganizationImpex-Status"
  - id: "JumpNode1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewUserExport-SelectConfiguration"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "PageableID"
      InValue_2: "UserExportForm_ExportFile"
      OutValue_1: "ObjectsID"
      OutValue_2: "SelectedFile"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "Users:ID"
      InValue_2: "UserExportForm_ExportFile"
      OutValue_1: "ObjectsID"
      OutValue_2: "SelectedFile"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "OrganizationDomain"
      OutValue_1: "UserDomain"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "OrganizationDomain"
      InValue_2: "OrganizationDomain"
      OutValue_1: "ProcessOwningDomain"
      OutValue_2: "ProcessExecutionDomain"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      OutValue_1: "ProcessPipelineName"
      InValue_1: "\"ProcessUserExport\""
      OutValue_2: "ProcessPipelineStartNode"
      InValue_2: "\"Export\""
      InValue_4: "\"ProcessUserImpex\""
      OutValue_4: "JobName"
  - id: "Loop2"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewUserExport-SimpleSearch"
      OutValue_1: "ViewUserExport-ParametricSearch"
      OutValue_2: "ViewUserExport-Paging"
      OutValue_3: "ViewUserExport-SelectConfiguration"
      OutValue_4: "ViewUserExport-Export"
      OutValue_5: "ViewUserExport-Back"
      PagingPipeline: "ViewUserExport-Paging"
    bindings:
      Key_0: "simpleSearch"
      Key_1: "parametricSearch"
      Key_2: "Paging"
      Key_3: "SelectConfiguration"
      Key_4: "Export"
      Key_5: "Back"
      SelectionKey: "JumpTarget"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OrganizationImpex"
      WorkingTemplate: "impex/UserExportSelectConfiguration"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OrganizationImpex"
      WorkingTemplate: "impex/UserExportSelectUsers"
  - id: "RemoveClipboard2"
    type: "pipelet"
    ref: "RemoveClipboard"
    config:
      SessionRegistrationID: "UserExportList"
  - id: "RemoveDictionaryValue1"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      RemoveFormValues: true
      Key: "SelectedObjectUUID"
  - id: "RemoveDictionaryValue2"
    type: "pipelet"
    ref: "RemoveDictionaryValue"
    config:
      RemoveFormValues: true
      Key: "ObjectUUID"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ExportDomainRefs"
      ValueType: "Form Value"
      Value: true
  - id: "SetDictionaryValue7"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewOrganizationImpex-Status"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 1
    bindings:
      PageNumber: "PageNumberInt"
      Pageable: "Users"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 1
    bindings:
      Pageable: "Users"
      PageNumber: "PageNumberInt"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewUserExport-Paging"
      DefaultPageLocatorName: "UserExportPageLocator"
    bindings:
      PageLocator: "UserExportPageLocator"
      Pageable: "Users"
  - id: "UpdateClipboard2"
    type: "pipelet"
    ref: "UpdateClipboard"
    config:
      SessionRegistrationID: "Clipboard"
      StoreFormValues: "No"
    bindings:
      AllObjectUUIDs: "NULL"
      SelectedObjectUUIDs: "NULL"
  - id: "UpdateClipboard5"
    type: "pipelet"
    ref: "UpdateClipboard"
    config:
      SessionRegistrationID: "UserExportList"
      StoreFormValues: "No"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "UserExportForm"
    bindings:
      WebForm: "UserExportForm"
  - id: "ValidateWebForm1"
    type: "pipelet"
    ref: "ValidateWebForm"
    bindings:
      WebForm: "UserExportForm"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumberInt"
      LocalizedString: "PageNumber"
  - id: "VerifyInteger2"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumberInt"
      LocalizedString: "UserExportPageLocator:CurrentPageNumber"

links:
  - from: "Call6"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "GetRolesByDomain1"
    into: "in"
  - from: "GetClipboard2"
    via: "next"
    to: "End4"
    into: "in"
  - from: "GetRolesByDomain1"
    via: "next"
    to: "FilterRolesByPrefix1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "DispatchFormActionByBreadcrumb1"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "StartNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "Pipelet1"
    via: "error"
    to: "DispatchFormActionByBreadcrumb1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "GetPageLocator1"
    via: "error"
    to: "Jump2"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "FilterRolesByPrefix1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "GetFormSelection6"
    via: "next"
    to: "GetFormSelection5"
    into: "in"
  - from: "GetFormSelection5"
    via: "next"
    to: "UpdateClipboard5"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "GetClipboard2"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "GetPageLocator2"
    into: "in"
  - from: "Join9"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "Loop2"
    into: "in"
  - from: "VerifyInteger2"
    via: "error"
    to: "Join9"
    into: "in1"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage1"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Call12"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "Start7"
    via: "next"
    to: "Call11"
    into: "in"
  - from: "VerifyInteger2"
    via: "next"
    to: "SetPage2"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "GetPageable2"
    via: "next"
    to: "JoinNode6"
    into: "in2"
  - from: "Call10"
    via: "ERROR"
    to: "JoinNode1"
    into: "in3"
  - from: "DecisionNode1"
    via: "no"
    to: "JumpNode3"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join9"
    into: "in2"
  - from: "Call12"
    via: "ERROR"
    to: "JoinNode1"
    into: "in1"
  - from: "SetPage1"
    via: "next"
    to: "Join3"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "SetPageLocator1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "Call8"
    via: "ERROR"
    to: "JoinNode1"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "UpdateWebForm1"
    via: "next"
    to: "ValidateWebForm1"
    into: "in"
  - from: "SetDictionaryValue7"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "CreateWebForm1"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "Start3"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "CreateWebForm1"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "ValidateWebForm1"
    via: "next"
    to: "Decision4"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "Call6"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "KeyMapper2"
    via: "next"
    to: "Join8"
    into: "in3"
  - from: "Start11"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "Decision4"
    via: "yes"
    to: "KeyMapper1"
    into: "in"
  - from: "Loop2"
    via: "do"
    to: "DetermineUser2"
    into: "in"
  - from: "DetermineUser2"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "Loop2"
    into: "loop"
  - from: "Loop2"
    via: "next"
    to: "CreatePageableFromIterator2"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "CreatePageableFromIterator2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "Start10"
    via: "next"
    to: "GetFormSelection6"
    into: "in"
  - from: "ValidateWebForm1"
    via: "error"
    to: "Call13"
    into: "in"
  - from: "Call13"
    via: "next"
    to: "Join7"
    into: "in3"
  - from: "GetWebForm1"
    via: "error"
    to: "Call14"
    into: "in"
  - from: "Call14"
    via: "next"
    to: "Join6"
    into: "in3"
  - from: "RemoveClipboard2"
    via: "next"
    to: "UpdateClipboard2"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join3"
    into: "in3"
  - from: "Call2"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Decision2"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "UpdateClipboard5"
    via: "next"
    to: "End6"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "Call11"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "RemoveClipboard2"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "UpdateClipboard2"
    via: "next"
    to: "RemoveDictionaryValue1"
    into: "in"
  - from: "GetPageable2"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "Decision2"
    via: "yes"
    to: "VerifyInteger2"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "Call12"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "GetRolesByDomain1"
    via: "error"
    to: "End3"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "GetPageLocator2"
    via: "next"
    to: "GetPageable2"
    into: "in"
  - from: "RemoveDictionaryValue1"
    via: "next"
    to: "RemoveDictionaryValue2"
    into: "in"
  - from: "Call10"
    via: "next"
    to: "Join2"
    into: "in2"
  - from: "RemoveDictionaryValue2"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join9"
    into: "in1"
  - from: "KeyMapper5"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "DispatchFormActionByBreadcrumb1"
    via: "error"
    to: "SetDictionaryValue7"
    into: "in"
