flow: "ViewOrderList_52"
kind: "view"

entries:
  - id: "Start2"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "OrderSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "FixInitialState"
    mode: "include"
    strict: true
    inputs:
      - key: "OrderState"
        type: "java.lang.String"
        required: false
      - key: "OrderSearchType"
        type: "java.lang.String"
        required: false
      - key: "ApplicationBO"
        type: "com.intershop.component.application.capi.ApplicationBO"
        required: true
  - id: "StartNode4"
    name: "Sort"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AddObjectToVector2"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      Iterator: "AllSelectedStatusIDs"
      OutVector: "AllSelectedStatusIDsVector"
  - id: "AddObjectToVector4"
    type: "pipelet"
    ref: "AddObjectToVector"
    config:
      Mode: "Allow Duplicates"
    bindings:
      Iterator: "AllSelectedStatusIDs"
      OutVector: "AllSelectedStatusIDsVector"
      Object: "StateIDString"
      InVector: "AllSelectedStatusIDsVector"
  - id: "Call1"
    type: "call"
    ref: "ValidateWebForms-WFAdvancedOrderSearch"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessOrderSearch-Search"
    bindings:
      OrderDomain: "CurrentChannel:Domain"
      StartDate: "CreationDateFrom"
      EndDate: "CreationDateTo"
      ConsumerName: "WFAdvancedSearch_CustomerName"
      CustomerName: "null"
      OrderNumber: "WFAdvancedSearch_DocumentNo"
      PriceTotalTo: "PriceTotalTo"
      OrderDomains: "null"
      PriceTotalFrom: "PriceTotalFrom"
      ProductSKU: "WFAdvancedSearch_ProductSKU"
      ProductAvalibilityFlag: "WFAdvancedSearch_Available"
      OrderStateLiteral: "statusLiteral"
      SortDirection: "SortDirection"
      SortAttribute: "SortAttribute"
      OrderStates: "AllSelectedStatusIDs"
  - id: "CallNode2"
    type: "call"
    ref: "ViewOrderList-GetOrderStatuses"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessOrderSearch-StorePageLocatorParameter"
    bindings:
      PageLocator: "OrdersPageLocator"
  - id: "CallNode5"
    type: "call"
    ref: "ViewOrderList_52-FixInitialState"
    bindings:
      OrderSearchType: "searchOpenOrders"
      OrderState: "statusLiteral"
  - id: "Decision1"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision2"
    type: "decision"
    condition: "OrdersPageLocator"
  - id: "DecisionNode1"
    type: "decision"
    condition: "initialVisit"
  - id: "DecisionNode2"
    type: "decision"
    condition: "AllSelectedStatusIDs"
  - id: "DecisionNode3"
    type: "decision"
    condition: "OrderStates"
  - id: "DecisionNode4"
    type: "decision"
    condition: "PageSize"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewOrderList_52-OrderSearch"
      OutValue_3: "ViewGiftCertificates_52-Edit"
      PagingPipeline: "ViewOrderList_52-Paging"
      OutValue_2: "ViewOrderList_52-Paging"
      OutValue_6: "ViewOrderList_52-Paging"
    bindings:
      Key_0: "find"
      SelectionKey: "JumpTarget"
      Key_3: "showGiftCertificate"
      Key_2: "switchSearchMask"
      Key_6: "backToList"
  - id: "EndNode5"
    type: "end"
    strict: true
    outputs:
      - key: "AllSelectedStatusIDs"
        type: "java.util.Iterator"
        guaranteed: true
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      RestorePageLocatorDictionary: "True"
      DefaultPageLocatorName: "OrdersPageLocator"
    bindings:
      PageLocator: "OrdersPageLocator"
  - id: "GetPageLocator2"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      RestorePageLocatorDictionary: "True"
      DefaultPageLocatorName: "OrdersPageLocator"
    bindings:
      PageLocator: "OrdersPageLocator"
  - id: "GetPageable2"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Orders"
      PageableID: "OrdersPageLocator:PageableID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "OrderBORepository:OrderStatuses:Iterator"
      OutValue_1: "OrderStatuses"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Order\"):OrderBORepositoryOfOwningRepository"
      OutValue_1: "OrderBORepository"
  - id: "LoopNode3"
    type: "loop"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "OrderStates"
    bindings:
      Selection: "AllSelectedStatusIDs"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "PurchaseOrderList"
      WorkingTemplate: "order/OrderList_52"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "PurchaseOrderList"
      WorkingTemplate: "order/OrderOverview_52"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 1
    bindings:
      PageNumber: "PageNumberInt"
      Pageable: "Orders"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      Pageable: "Orders"
      PageNumber: "PageNumberInt"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewOrderList_52-Paging"
      DefaultPageLocatorName: "OrdersPageLocator"
    bindings:
      PageLocator: "OrdersPageLocator"
      Pageable: "Orders"
  - id: "ToString1"
    type: "pipelet"
    ref: "ToString"
    bindings:
      Object1: "OrderStatus:StateId"
      String1: "StateIDString"
  - id: "UpdatePageSize1"
    type: "pipelet"
    ref: "UpdatePageSize"
    config:
      DefaultPageSize: 15
    bindings:
      PageSize: "PageSize"
      PageableIterator: "Orders"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumberInt"
      LocalizedString: "PageNumber"
  - id: "VerifyInteger2"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumberInt"
      LocalizedString: "OrdersPageLocator:CurrentPageNumber"
  - id: "VerifyInteger3"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      LocalizedString: "PageSize"
      IntegerObject: "PageSize"

links:
  - from: "StartNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "GetPageable2"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "VerifyInteger2"
    via: "next"
    to: "SetPage2"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage1"
    into: "in"
  - from: "SetPage1"
    via: "next"
    to: "Join7"
    into: "in2"
  - from: "Decision1"
    via: "no"
    to: "Decision2"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join6"
    into: "in2"
  - from: "Join6"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "Start6"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Join6"
    into: "in1"
  - from: "Decision2"
    via: "yes"
    to: "VerifyInteger2"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join7"
    into: "in3"
  - from: "VerifyInteger3"
    via: "error"
    to: "JoinNode9"
    into: "in2"
  - from: "CallNode2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "DecisionNode4"
    via: "yes"
    to: "VerifyInteger3"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode1"
    into: "in2"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode5"
    into: "in2"
  - from: "VerifyInteger2"
    via: "error"
    to: "Join6"
    into: "in1"
  - from: "DecisionNode4"
    via: "no"
    to: "JoinNode9"
    into: "in1"
  - from: "Pipelet1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "Pipelet1"
    into: "in"
  - from: "SetPageLocator1"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode5"
    into: "in"
  - from: "UpdatePageSize1"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "VerifyInteger3"
    via: "next"
    to: "UpdatePageSize1"
    into: "in"
  - from: "GetPageLocator2"
    via: "error"
    to: "Join1"
    into: "in1"
  - from: "JoinNode9"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "DecisionNode3"
    via: "yes"
    to: "JoinNode5"
    into: "in1"
  - from: "DecisionNode3"
    via: "no"
    to: "DecisionNode1"
    into: "in"
  - from: "Call1"
    via: "ERROR"
    to: "JoinNode3"
    into: "in1"
  - from: "CallNode4"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "AddObjectToVector2"
    into: "in"
  - from: "AddObjectToVector2"
    via: "next"
    to: "LoopNode3"
    into: "in"
  - from: "LoopNode3"
    via: "next"
    to: "EndNode5"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "GetPageLocator2"
    via: "next"
    to: "GetPageable2"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "GetPageLocator2"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "GetPageLocator1"
    via: "error"
    to: "JoinNode8"
    into: "in1"
  - from: "ToString1"
    via: "next"
    to: "AddObjectToVector4"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "LoopNode3"
    via: "do"
    to: "ToString1"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "GetPageLocator1"
    via: "next"
    to: "JoinNode8"
    into: "in2"
  - from: "AddObjectToVector4"
    via: "next"
    to: "LoopNode3"
    into: "loop"
  - from: "StartNode2"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "GetPageable2"
    via: "error"
    to: "Join1"
    into: "in2"
  - from: "Call1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "JoinNode4"
    into: "in3"
