flow: "ViewPageProductAssignmentFilter"
kind: "view"

entries:
  - id: "Start1"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "ParametricSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "Search"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode10"
    name: "GetCurrentRepository"
    mode: "private"
    strict: true
    inputs:
      - key: "CurrentChannel"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        required: false
  - id: "StartNode11"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Create"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode3"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Remove"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Submit"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "Cancel"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewParametricSearch-SimpleProductSearch"
  - id: "Call4"
    type: "call"
    ref: "ViewParametricSearch-SearchProduct"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessAssignmentFilter-GetFilterConfigFromSession"
  - id: "CallNode10"
    type: "call"
    ref: "ViewPageProductAssignmentFilter-Prefix"
  - id: "CallNode12"
    type: "call"
    ref: "ViewPageProductAssignmentFilter-Prefix"
  - id: "CallNode13"
    type: "call"
    ref: "ValidateWebForms-WFAdvancedSearch"
  - id: "CallNode14"
    type: "call"
    ref: "ProcessAssignmentFilter-StoreFilterConfigInSession"
    bindings:
      AssignmentFilterConfiguration: "SelectedAssignmentFilterConf"
  - id: "CallNode2"
    type: "call"
    ref: "ViewProductList-PrepareSearchMask"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessAssignmentFilter-GetFilterConfigFromSession"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessAssignmentFilter-ClearFilterConfigFromSession"
  - id: "CallNode5"
    type: "call"
    ref: "ValidateWebForms-WFAdvancedSearch"
  - id: "CallNode6"
    type: "call"
    ref: "ValidateWebForms-WFSimpleSearch"
  - id: "CallNode8"
    type: "call"
    ref: "DetermineRepositories-Master"
  - id: "CallNode9"
    type: "call"
    ref: "ViewPageProductAssignmentFilter-GetCurrentRepository"
  - id: "CreateAssignmentFilter1"
    type: "pipelet"
    ref: "CreateAssignmentFilter"
  - id: "CreateProductIdentifierLookupHelper1"
    type: "pipelet"
    ref: "CreateProductIdentifierLookupHelper"
    config:
      LookupType: "ProductDomainLookup"
    bindings:
      ProductDomain: "CurrentMasterRepository:RepositoryDomain"
  - id: "Decision1"
    type: "decision"
    condition: "PageLocator"
  - id: "Decision2"
    type: "decision"
    condition: "PageNumber"
  - id: "DecisionNode1"
    type: "decision"
    condition: "AssignmentFilterConfiguration:Filter"
  - id: "DecisionNode4"
    type: "decision"
    condition: "CurrentChannel"
  - id: "DeleteAssignmentFilter1"
    type: "pipelet"
    ref: "DeleteAssignmentFilter"
    bindings:
      AssignmentFilterConfiguration: "SelectedAssignmentFilterConf"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "This:Search"
      OutValue_1: "This:ParametricSearch"
      OutValue_2: "This:Paging"
      OutValue_3: "This:Submit"
      OutValue_4: "This:Cancel"
    bindings:
      Key_0: "findSimple"
      Key_1: "findParametric"
      Key_2: "paging"
      Key_3: "submitFilter"
      Key_4: "cancelFilter"
      SelectionKey: "JumpTarget"
  - id: "DispatchFormActionByBreadcrumb1"
    type: "pipelet"
    ref: "DispatchFormActionByBreadcrumb"
    config:
      SplitMode: "PipelineAndParameter"
    bindings:
      SelectionKey: "JumpTarget"
      OutValue_0: "ApplicationState:LastListView"
      Key_0: "\"Submit\""
  - id: "DispatchFormActionByBreadcrumb2"
    type: "pipelet"
    ref: "DispatchFormActionByBreadcrumb"
    config:
      SplitMode: "PipelineAndParameter"
    bindings:
      SelectionKey: "JumpTarget"
      OutValue_0: "ApplicationState:LastBreadcrumb"
      Key_0: "\"Remove\""
  - id: "EndNode4"
    type: "end"
    strict: false
  - id: "EndNode7"
    type: "end"
    strict: true
    outputs:
      - key: "Repository"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        guaranteed: true
      - key: "RepositoryUUID"
        type: "com.intershop.component.mvc.capi.catalog.Repository"
        guaranteed: true
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "ProductList"
      RestorePageLocatorDictionary: "True"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Products"
      PageableID: "PageLocator:PageableID"
  - id: "InteractionNode1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "Jump3"
    type: "jump"
    ref: "This:Search"
  - id: "Jump4"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode1"
    type: "jump"
  - id: "JumpNode2"
    type: "jump"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentChannel"
      OutValue_1: "Repository"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Repository:UUID"
      OutValue_1: "RepositoryUUID"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      WorkingTemplate: "content/assignment/filter/ProductFilter"
      SelectedMenuItem: "MasterComponents"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "SearchType"
      Value: "parametric"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Products"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Products"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewPageProductAssignmentFilter-Paging"
      DefaultPageLocatorName: "ProductList"
    bindings:
      Pageable: "Products"
      PageLocatorName: "null"
  - id: "UpdateAssignmentFilter1"
    type: "pipelet"
    ref: "UpdateAssignmentFilter"
    bindings:
      ParametersMap: "AdvancedSearchParameters"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"

links:
  - from: "StartNode1"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "CallNode6"
    via: "ERROR"
    to: "JoinNode2"
    into: "in2"
  - from: "Call1"
    via: "next"
    to: "JoinNode6"
    into: "in2"
  - from: "CreateProductIdentifierLookupHelper1"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "JoinNode5"
    into: "in1"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage2"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Decision2"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "SetPage1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump4"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "JoinNode6"
    via: "next"
    to: "Decision2"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "Decision1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Join5"
    into: "in3"
  - from: "CallNode5"
    via: "ERROR"
    to: "JoinNode2"
    into: "in3"
  - from: "Join2"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "SetPage1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Call4"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode3"
    via: "ERROR"
    to: "JoinNode3"
    into: "in1"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JoinNode1"
    into: "in2"
  - from: "JoinNode1"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "DispatchFormActionByBreadcrumb1"
    into: "in"
  - from: "JoinNode4"
    via: "next"
    to: "Jump3"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "CallNode1"
    via: "ERROR"
    to: "JoinNode3"
    into: "in1"
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "GetPageLocator1"
    via: "error"
    to: "JoinNode4"
    into: "in2"
  - from: "GetPageable1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionNode1"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode5"
    via: "next"
    to: "CallNode13"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "CallNode14"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DeleteAssignmentFilter1"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "CallNode14"
    into: "in"
  - from: "DispatchFormActionByBreadcrumb2"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "DeleteAssignmentFilter1"
    via: "next"
    to: "DispatchFormActionByBreadcrumb2"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "StartNode3"
    via: "next"
    to: "JoinNode7"
    into: "in3"
  - from: "CreateAssignmentFilter1"
    via: "next"
    to: "JoinNode8"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "CreateAssignmentFilter1"
    into: "in"
  - from: "CallNode13"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode8"
    into: "in2"
  - from: "UpdateAssignmentFilter1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "JoinNode8"
    via: "next"
    to: "UpdateAssignmentFilter1"
    into: "in"
  - from: "JoinNode9"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "DispatchFormActionByBreadcrumb1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "DecisionNode4"
    via: "no"
    to: "CallNode8"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "EndNode7"
    into: "in"
  - from: "StartNode10"
    via: "next"
    to: "DecisionNode4"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "DecisionNode4"
    via: "yes"
    to: "KeyMapper2"
    into: "in"
  - from: "CallNode8"
    via: "next"
    to: "JoinNode9"
    into: "in3"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join2"
    into: "in3"
  - from: "StartNode11"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "EndNode4"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "CallNode5"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "CallNode13"
    via: "ERROR"
    to: "JoinNode5"
    into: "in1"
  - from: "SetPageLocator1"
    via: "next"
    to: "CreateProductIdentifierLookupHelper1"
    into: "in"
