flow: "ViewSellerOrder_52"
kind: "view"

entries:
  - id: "Start10"
    name: "ShowLineItemDetail"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start11"
    name: "ShowLineItemDelivery"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start13"
    name: "FindByNumber"
    mode: "public"
    strict: false
    inputs:
      []
  - id: "Start15"
    name: "ShowPromotions"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start17"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start18"
    name: "ShowGiftcards"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "PrepareLIStates"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "ShowBundledItem"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "ShowHistory"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode9"
    name: "RemoveRevenue"
    mode: "private"
    strict: true
    inputs:
      - key: "Order"
        type: "com.intershop.beehive.bts.capi.orderprocess.fulfillment.Order"
        required: false

steps:
  - id: "Call2"
    type: "call"
    ref: "ViewSellerOrder_52-PrepareLIStates"
  - id: "Call8"
    type: "call"
    ref: "ViewSellerOrder_52-PrepareLIStates"
  - id: "CallNode1"
    type: "call"
    ref: "ProcessRebateServiceLineItems-PrepareBasketRebatesView"
  - id: "CallNode12"
    type: "call"
    ref: "OrderStatusTracking-GetTrackingEntriesByOrder"
  - id: "CreateProductIdentifierLookupHelper1"
    type: "pipelet"
    ref: "CreateProductIdentifierLookupHelper"
    config:
      DefaultFactoryName: "com.intershop.beehive.bts.internal.orderprocess.LineItemPO"
      LookupType: "FactoryLookup"
  - id: "CreateProductIdentifierLookupHelper4"
    type: "pipelet"
    ref: "CreateProductIdentifierLookupHelper"
    config:
      DefaultFactoryName: "com.intershop.beehive.bts.internal.orderprocess.BundledProductLineItemPO"
      LookupType: "FactoryLookup"
    bindings:
      FactoryName: "not used"
  - id: "DecisionNode7"
    type: "decision"
    condition: "Order:AffiliatePartnerAccountID"
  - id: "DecisionNode8"
    type: "decision"
    condition: "Order:AffiliateProgramAccountID"
  - id: "DetermineOrderByID2"
    type: "pipelet"
    ref: "DetermineOrderByID"
    config:
      CurrentUserOnly: false
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_7: "ViewSellerOrder_52-ShowBundledItem"
      OutValue_8: "ViewSellerOrder_52-ShowLineItemDetail"
    bindings:
      SelectionKey: "JumpTarget"
      Key_7: "backBundledItem"
      Key_8: "backItem"
  - id: "End2"
    type: "end"
    strict: false
  - id: "EndNode6"
    type: "end"
    strict: false
  - id: "GetAccountByUUID1"
    type: "pipelet"
    ref: "GetAccountByUUID"
    bindings:
      AccountUUID: "Order:AffiliatePartnerAccountID"
  - id: "GetAccountByUUID2"
    type: "pipelet"
    ref: "GetAccountByUUID"
    bindings:
      AccountUUID: "Order:AffiliateProgramAccountID"
  - id: "GetAccountTransactionByUUID1"
    type: "pipelet"
    ref: "GetAccountTransactionByUUID"
    bindings:
      AccountTransactionUUID: "Order:AffiliatePartnerTransactionID"
  - id: "GetBundledProductLineItemByUUID1"
    type: "pipelet"
    ref: "GetBundledProductLineItemByUUID"
    bindings:
      BundledProductLineItem: "LineItem"
  - id: "GetDomainPreference3"
    type: "pipelet"
    ref: "GetDomainPreference"
    config:
      DefaultPreferenceKey: "TaxationPolicy"
      Type: "Integer"
    bindings:
      PreferenceDomain: "Order:Domain"
      PreferenceIntValue: "TaxationPolicy"
  - id: "GetOrderBO1"
    type: "pipelet"
    ref: "GetOrderBO"
  - id: "GetOrderBO3"
    type: "pipelet"
    ref: "GetOrderBO"
  - id: "GetOrderBO4"
    type: "pipelet"
    ref: "GetOrderBO"
  - id: "GetOrderBO5"
    type: "pipelet"
    ref: "GetOrderBO"
  - id: "GetOrderBO7"
    type: "pipelet"
    ref: "GetOrderBO"
  - id: "GetOrderByID1"
    type: "pipelet"
    ref: "GetOrderByID"
  - id: "GetOrderByID2"
    type: "pipelet"
    ref: "GetOrderByID"
  - id: "GetOrderByID5"
    type: "pipelet"
    ref: "GetOrderByID"
    bindings:
      OrderIDs: "null"
      OrderRefID: "null"
      OrderRefIDs: "null"
      Orders: "null"
  - id: "GetOrderByID6"
    type: "pipelet"
    ref: "GetOrderByID"
  - id: "GetOrderByID7"
    type: "pipelet"
    ref: "GetOrderByID"
  - id: "GetOrderByID8"
    type: "pipelet"
    ref: "GetOrderByID"
  - id: "GetOrderStateDefinitions1"
    type: "pipelet"
    ref: "GetOrderStateDefinitions"
    config:
      OrderStateGroup: "OrderStatus"
    bindings:
      StateDefinitionMap: "OrderStatesMap"
  - id: "GetOrderStateDefinitions2"
    type: "pipelet"
    ref: "GetOrderStateDefinitions"
    config:
      OrderStateGroup: "OrderShippingStatus"
    bindings:
      StateDefinitionMap: "OrderShippingStatesMap"
  - id: "GetOrderStateDefinitions3"
    type: "pipelet"
    ref: "GetOrderStateDefinitions"
    config:
      OrderStateGroup: "OrderPaymentStatus"
    bindings:
      StateDefinitionMap: "OrderPaymentStatesMap"
  - id: "GetOrderStateDefinitions4"
    type: "pipelet"
    ref: "GetOrderStateDefinitions"
    config:
      OrderStateGroup: "OrderExportStatus"
    bindings:
      StateDefinitionMap: "OrderExportStatesMap"
  - id: "GetOrderStateDefinitions5"
    type: "pipelet"
    ref: "GetOrderStateDefinitions"
    config:
      OrderStateGroup: "SellerOrderProductLineItemStatus"
    bindings:
      StateDefinitionMap: "PLIStatesMap"
  - id: "GetProductLineItemBO2"
    type: "pipelet"
    ref: "GetOrderProductLineItemBO"
    bindings:
      OrderBO: "OrderBO"
      PLIID: "LineItemUUID"
      ProductLineItemBO: "LineItem"
      OrderProductLineItemBO: "LineItem"
  - id: "GetProductLineItemBO3"
    type: "pipelet"
    ref: "GetOrderProductLineItemBO"
    bindings:
      OrderBO: "OrderBO"
      PLIID: "LineItemUUID"
      ProductLineItemBO: "LineItem"
      OrderProductLineItemBO: "LineItem"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "InteractionEnd4"
    type: "interaction"
  - id: "InteractionEnd5"
    type: "interaction"
  - id: "InteractionEnd6"
    type: "interaction"
  - id: "InteractionEnd7"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode31"
    type: "join"
  - id: "JoinNode32"
    type: "join"
  - id: "JoinNode33"
    type: "join"
  - id: "JoinNode34"
    type: "join"
  - id: "JoinNode35"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewSellerOrder_52-FindByNumber"
  - id: "Jump11"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump12"
    type: "jump"
    ref: "ViewSellerOrder_52-FindByNumber"
  - id: "Jump2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump7"
    type: "jump"
    ref: "ViewSellerOrder_52-FindByNumber"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Order\"):getOrderBORepository(Order)"
      OutValue_1: "OrderBORepository"
  - id: "KeyMapper13"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "\"ViewSellerOrder_52-FindByNumber\""
      OutValue_1: "JumpTarget"
      OutValue_2: "AdditionalParameterName1"
      InValue_2: "\"OrderID\""
      OutValue_3: "AdditionalParameterValue1"
      InValue_3: "OrderID"
      InValue_4: "\"OrderChannelID\""
      InValue_5: "OrderChannelID"
      OutValue_4: "AdditionalParameterName2"
      OutValue_5: "AdditionalParameterValue2"
      InValue_6: "\"historyStatus\""
      InValue_7: "historyStatus"
      OutValue_6: "AdditionalParameterName3"
      OutValue_7: "AdditionalParameterValue3"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Order\"):getOrderBORepository(Order)"
      OutValue_1: "OrderBORepository"
  - id: "KeyMapper3"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Order\"):getOrderBORepository(Order)"
      OutValue_1: "OrderBORepository"
  - id: "KeyMapper4"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Order\"):getOrderBORepository(Order)"
      OutValue_1: "OrderBORepository"
  - id: "KeyMapper5"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "ApplicationBO:Extension(\"Order\"):getOrderBORepository(Order)"
      OutValue_1: "OrderBORepository"
  - id: "Pipelet1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Order"
      OutValue_1: "CurrentBasket"
      InValue_2: "Order"
      OutValue_2: "Requisition"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "PurchaseOrderList"
      WorkingTemplate: "order/OrderDetails_52"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "PurchaseOrderList"
      WorkingTemplate: "order/LineItemDetails_52"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "PurchaseOrderList"
      WorkingTemplate: "order/OrderHistory_52"
  - id: "PrepareApplicationView4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "PurchaseOrderList"
      WorkingTemplate: "order/LineItemBundledItem_52"
  - id: "PrepareApplicationView5"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "PurchaseOrderList"
      WorkingTemplate: "order/LineItemDelivery_52"
  - id: "PrepareApplicationView6"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "PurchaseOrderList"
      WorkingTemplate: "order/OrderPromotions_52"
  - id: "PrepareApplicationView7"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "PurchaseOrderList"
      WorkingTemplate: "order/OrderPaymentOverview_52"
  - id: "PrepareLineItemStates1"
    type: "pipelet"
    ref: "PrepareLineItemStates"
    config:
      StateGroup: "SellerOrderProductLineItemStatus"
      StateGroup2: "SellerOrderProductLineItemStatus"
      StatusType: "Status2"
      StatusType2: "Status2"
  - id: "PrepareLineItemStatusDependency1"
    type: "pipelet"
    ref: "PrepareLineItemStatusDependency"
    config:
      NextStates: "SHIPPED"
      Status: "SHIPPED"
  - id: "PrepareLineItemStatusDependency2"
    type: "pipelet"
    ref: "PrepareLineItemStatusDependency"
    config:
      NextStates: "PARTSHIPPED;SHIPPED"
      Status: "PARTSHIPPED"
  - id: "PrepareLineItemStatusDependency3"
    type: "pipelet"
    ref: "PrepareLineItemStatusDependency"
    config:
      NextStates: "REJECTED"
      Status: "REJECTED"
  - id: "PrepareLineItemStatusDependency4"
    type: "pipelet"
    ref: "PrepareLineItemStatusDependency"
    config:
      NextStates: "CONFIRMED;PARTSHIPPED;SHIPPED"
      Status: "CONFIRMED"
  - id: "PrepareLineItemStatusDependency5"
    type: "pipelet"
    ref: "PrepareLineItemStatusDependency"
    config:
      NextStates: "NEW;CONFIRMED;REJECTED"
      Status: "NEW"
  - id: "PrepareLineItemStatusDependency6"
    type: "pipelet"
    ref: "PrepareLineItemStatusDependency"
    config:
      NextStates: "CANCELLED"
      Status: "CANCELLED"
  - id: "PrepareLineItemStatusDependency7"
    type: "pipelet"
    ref: "PrepareLineItemStatusDependency"
    config:
      NextStates: "PARTDELIVERED"
      Status: "PARTDELIVERED"
  - id: "PrepareLineItemStatusDependency8"
    type: "pipelet"
    ref: "PrepareLineItemStatusDependency"
    config:
      NextStates: "DELIVERED"
      Status: "DELIVERED"
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewOrderList_52-OrderSearch"
  - id: "UnbindAccountTransaction1"
    type: "pipelet"
    ref: "UnbindAccountTransaction"
  - id: "UnbindAccountTransaction2"
    type: "pipelet"
    ref: "UnbindAccountTransaction"

links:
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "Start10"
    via: "next"
    to: "GetOrderByID2"
    into: "in"
  - from: "Start13"
    via: "next"
    to: "KeyMapper13"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "CreateProductIdentifierLookupHelper1"
    via: "next"
    to: "GetDomainPreference3"
    into: "in"
  - from: "KeyMapper13"
    via: "next"
    to: "GetOrderByID1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "CreateProductIdentifierLookupHelper1"
    into: "in"
  - from: "Pipelet1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "GetProductLineItemBO2"
    via: "error"
    to: "Jump1"
    into: "in"
  - from: "GetDomainPreference3"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "GetDomainPreference3"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "GetOrderByID1"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Start17"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Pipelet1"
    into: "in"
  - from: "GetOrderBO5"
    via: "next"
    to: "GetProductLineItemBO2"
    into: "in"
  - from: "GetOrderBO1"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Start11"
    via: "next"
    to: "GetOrderByID7"
    into: "in"
  - from: "DetermineOrderByID2"
    via: "error"
    to: "Jump7"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump11"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "GetOrderBO1"
    into: "in"
  - from: "PrepareApplicationView4"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd4"
    into: "in"
  - from: "GetOrderStateDefinitions1"
    via: "next"
    to: "GetOrderStateDefinitions2"
    into: "in"
  - from: "GetOrderStateDefinitions2"
    via: "next"
    to: "GetOrderStateDefinitions3"
    into: "in"
  - from: "GetOrderByID5"
    via: "next"
    to: "CallNode12"
    into: "in"
  - from: "GetOrderByID2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "CallNode12"
    via: "next"
    to: "GetOrderStateDefinitions1"
    into: "in"
  - from: "GetOrderStateDefinitions4"
    via: "next"
    to: "GetOrderStateDefinitions5"
    into: "in"
  - from: "GetOrderStateDefinitions5"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "GetOrderByID5"
    into: "in"
  - from: "GetProductLineItemBO3"
    via: "next"
    to: "PrepareApplicationView5"
    into: "in"
  - from: "PrepareApplicationView5"
    via: "next"
    to: "InteractionEnd5"
    into: "in"
  - from: "GetProductLineItemBO3"
    via: "error"
    to: "Jump12"
    into: "in"
  - from: "PrepareLineItemStatusDependency5"
    via: "next"
    to: "PrepareLineItemStatusDependency4"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "GetOrderBO5"
    into: "in"
  - from: "GetBundledProductLineItemByUUID1"
    via: "next"
    to: "CreateProductIdentifierLookupHelper4"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "DetermineOrderByID2"
    into: "in"
  - from: "DetermineOrderByID2"
    via: "next"
    to: "GetBundledProductLineItemByUUID1"
    into: "in"
  - from: "PrepareApplicationView7"
    via: "next"
    to: "InteractionEnd7"
    into: "in"
  - from: "PrepareApplicationView6"
    via: "next"
    to: "InteractionEnd6"
    into: "in"
  - from: "GetOrderBO3"
    via: "next"
    to: "PrepareApplicationView6"
    into: "in"
  - from: "GetOrderByID7"
    via: "next"
    to: "KeyMapper3"
    into: "in"
  - from: "Start18"
    via: "next"
    to: "GetOrderByID8"
    into: "in"
  - from: "Start15"
    via: "next"
    to: "GetOrderByID6"
    into: "in"
  - from: "GetOrderBO4"
    via: "next"
    to: "PrepareApplicationView7"
    into: "in"
  - from: "KeyMapper3"
    via: "next"
    to: "GetOrderBO7"
    into: "in"
  - from: "GetOrderByID6"
    via: "next"
    to: "KeyMapper4"
    into: "in"
  - from: "KeyMapper4"
    via: "next"
    to: "GetOrderBO3"
    into: "in"
  - from: "GetOrderByID8"
    via: "next"
    to: "KeyMapper5"
    into: "in"
  - from: "KeyMapper5"
    via: "next"
    to: "GetOrderBO4"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "Jump2"
    into: "in"
  - from: "GetAccountTransactionByUUID1"
    via: "error"
    to: "JoinNode35"
    into: "in2"
  - from: "DecisionNode8"
    via: "yes"
    to: "GetAccountByUUID2"
    into: "in"
  - from: "GetAccountByUUID1"
    via: "next"
    to: "GetAccountTransactionByUUID1"
    into: "in"
  - from: "DecisionNode8"
    via: "no"
    to: "JoinNode32"
    into: "in2"
  - from: "DecisionNode7"
    via: "yes"
    to: "GetAccountByUUID1"
    into: "in"
  - from: "GetAccountByUUID2"
    via: "error"
    to: "JoinNode34"
    into: "in2"
  - from: "GetAccountTransactionByUUID1"
    via: "next"
    to: "UnbindAccountTransaction1"
    into: "in"
  - from: "DecisionNode7"
    via: "no"
    to: "JoinNode33"
    into: "in1"
  - from: "JoinNode33"
    via: "next"
    to: "JoinNode35"
    into: "in1"
  - from: "JoinNode32"
    via: "next"
    to: "JoinNode34"
    into: "in1"
  - from: "GetAccountByUUID1"
    via: "error"
    to: "JoinNode33"
    into: "in2"
  - from: "PrepareLineItemStatusDependency4"
    via: "next"
    to: "PrepareLineItemStatusDependency3"
    into: "in"
  - from: "CreateProductIdentifierLookupHelper4"
    via: "next"
    to: "PrepareApplicationView4"
    into: "in"
  - from: "JoinNode35"
    via: "next"
    to: "JoinNode32"
    into: "in1"
  - from: "UnbindAccountTransaction2"
    via: "next"
    to: "JoinNode31"
    into: "in1"
  - from: "StartNode9"
    via: "next"
    to: "DecisionNode7"
    into: "in"
  - from: "UnbindAccountTransaction1"
    via: "next"
    to: "DecisionNode8"
    into: "in"
  - from: "JoinNode31"
    via: "next"
    to: "EndNode6"
    into: "in"
  - from: "JoinNode34"
    via: "next"
    to: "JoinNode31"
    into: "in2"
  - from: "GetAccountByUUID2"
    via: "next"
    to: "UnbindAccountTransaction2"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Call8"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "PrepareLineItemStatusDependency3"
    via: "next"
    to: "PrepareLineItemStatusDependency2"
    into: "in"
  - from: "PrepareLineItemStatusDependency2"
    via: "next"
    to: "PrepareLineItemStatusDependency1"
    into: "in"
  - from: "PrepareLineItemStates1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "GetOrderStateDefinitions3"
    via: "next"
    to: "GetOrderStateDefinitions4"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "PrepareLineItemStatusDependency5"
    into: "in"
  - from: "GetOrderBO7"
    via: "next"
    to: "GetProductLineItemBO3"
    into: "in"
  - from: "PrepareLineItemStatusDependency1"
    via: "next"
    to: "PrepareLineItemStatusDependency6"
    into: "in"
  - from: "PrepareLineItemStatusDependency6"
    via: "next"
    to: "PrepareLineItemStatusDependency7"
    into: "in"
  - from: "PrepareLineItemStatusDependency7"
    via: "next"
    to: "PrepareLineItemStatusDependency8"
    into: "in"
  - from: "PrepareLineItemStatusDependency8"
    via: "next"
    to: "PrepareLineItemStates1"
    into: "in"
  - from: "GetProductLineItemBO2"
    via: "next"
    to: "Call8"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "SetDictionaryValue3"
    into: "in"
