flow: "ViewSyndicationMasterProducts_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Search"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "AssignDirect"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "UpdateClipboard"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "ParametricSearch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "CreateProcess"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ProcessSyndication-Assign"
  - id: "Call10"
    type: "call"
    ref: "ViewParametricSearch-DetermineRepository"
  - id: "Call2"
    type: "call"
    ref: "ViewSyndicationMasterProducts_52-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ViewParametricSearch-SearchMasterProduct"
  - id: "Call4"
    type: "call"
    ref: "ViewSyndicationMasterProducts_52-UpdateClipboard"
  - id: "Call5"
    type: "call"
    ref: "ViewSyndicationMasterProducts_52-Prefix"
  - id: "Call6"
    type: "call"
    ref: "ViewParametricSearch-SimpleMasterProductSearch"
  - id: "Call7"
    type: "call"
    ref: "ViewSyndicationMasterProducts_52-Prefix"
  - id: "Call8"
    type: "call"
    ref: "ViewSyndicationMasterProducts_52-UpdateClipboard"
  - id: "Call9"
    type: "call"
    ref: "ViewSyndicationMasterProducts_52-Prefix"
  - id: "CallNode1"
    type: "call"
    ref: "ValidateWebForms-WFSimpleSearch"
  - id: "CallNode10"
    type: "call"
    ref: "ViewProductList-StorePageLocatorParameters"
  - id: "CallNode2"
    type: "call"
    ref: "ValidateWebForms-WFAdvancedSearch"
  - id: "CallNode29"
    type: "call"
    ref: "ViewProductList-GetServiceTypeCategories"
  - id: "CallNode3"
    type: "call"
    ref: "ViewProcessList_52-CreateProcess"
  - id: "CallNode52"
    type: "call"
    ref: "ViewProductList-PrepareCustomAttributesSearchMask"
    bindings:
      Domain: "OrganizationDomain"
      Locale: "CurrentRequest:Locale"
  - id: "CallNode53"
    type: "call"
    ref: "ViewProductList-PrepareCurrentSearchType"
  - id: "CallNode54"
    type: "call"
    ref: "ViewProductList-SetCurrentSearchTypePageLocatorParameter"
  - id: "CheckForEmptyIterator1"
    type: "pipelet"
    ref: "CheckForEmptyIterator"
    bindings:
      FilledIterator: "Products"
  - id: "CreateProductIdentifierLookupHelper1"
    type: "pipelet"
    ref: "CreateProductIdentifierLookupHelper"
    config:
      LookupType: "ProductDomainLookup"
    bindings:
      ProductDomain: "SearchRepository:RepositoryDomain"
  - id: "Decision1"
    type: "decision"
    condition: "assign"
  - id: "Decision2"
    type: "decision"
    condition: "ContextPipeline"
  - id: "Decision3"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision4"
    type: "decision"
    condition: "PageLocator"
  - id: "DecisionNode0"
    type: "decision"
    condition: "SearchType"
  - id: "DecisionNode1"
    type: "decision"
    condition: "SearchType"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewSyndicationMasterProducts_52-Paging"
      OutValue_1: "ViewSyndicationMasterProducts_52-Search"
      OutValue_2: "ViewSyndicationMasterProducts_52-Paging"
      OutValue_3: "ViewSyndicationMasterProducts_52-CreateProcess"
      OutValue_4: "ViewSyndication_52-SelectProductSource"
      PagingPipeline: "ViewSyndicationMasterProducts_52-Paging"
      OutValue_5: "ViewSyndicationMasterProducts_52-Search"
      OutValue_6: "ViewSyndicationMasterProducts_52-ParametricSearch"
      OutValue_7: "ViewSyndicationMasterProducts_52-Paging"
      OutValue_8: "ViewSyndication_52-Start"
    bindings:
      Key_0: "ShowAssignAllConfirmation"
      Key_1: "Search"
      Key_2: "CancelAssignAll"
      Key_3: "StartAssignAll"
      Key_4: "back"
      Key_5: "findSimple"
      Key_6: "findParametric"
      Key_7: "jumpToList"
      Key_8: "cancel"
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "End2"
    type: "end"
    strict: false
  - id: "GetClipboard1"
    type: "pipelet"
    ref: "GetClipboard"
    config:
      SessionRegistrationID: "Products"
      SetFormValues: "No"
  - id: "GetCurrencies1"
    type: "pipelet"
    ref: "GetCurrencies"
    config:
      Method: "Active Currencies"
    bindings:
      Domain: "OrganizationDomain"
  - id: "GetFormSelection1"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "ProductUUID"
    bindings:
      Selection: "ProductUUIDIterator"
  - id: "GetFormSelection2"
    type: "pipelet"
    ref: "GetFormSelection"
    config:
      DefaultParameterName: "SelectedProductUUID"
    bindings:
      Selection: "SelectedProductUUIDIterator"
  - id: "GetLabels1"
    type: "pipelet"
    ref: "GetLabels"
    bindings:
      Domain: "CurrentChannel:Domain"
  - id: "GetOffersBySupplierProducts2"
    type: "pipelet"
    ref: "GetOffersBySupplierProducts"
    bindings:
      OfferRepositoryDomain: "CurrentSelectedChannel:Domain"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "SyndicationProductList"
      RestorePageLocatorDictionary: "True"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      PageableID: "PageLocator:PageableID"
      Pageable: "Products"
  - id: "GetProducts1"
    type: "pipelet"
    ref: "GetBaseProducts"
    bindings:
      ProductIDIterator: "UUIDIterator"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "JoinNode0"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "Jump1"
    type: "jump"
    ref: "ViewSyndicationMasterProducts_52-Search"
  - id: "Jump5"
    type: "jump"
    ref: "ViewProcessList_52-ListAll"
  - id: "Jump7"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode0"
    type: "jump"
    ref: "ViewSyndicationMasterProducts_52-ParametricSearch"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CurrentSelectedChannel"
      OutValue_1: "Repository"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    config:
      ValueType: "Form Value"
    bindings:
      InValue_1: "\"BatchProcessSyndication-Initialize\""
      InValue_2: "\"BatchProcessSyndication-Syndicate\""
      InValue_3: "\"BatchProcessSyndication-Finish\""
      InValue_4: "\"Catalog\""
      InValue_5: "\"Catalog\""
      OutValue_5: "JobNamePrefix"
      OutValue_1: "InitPipeline"
      OutValue_2: "ProcessPipeline"
      OutValue_3: "PostPipeline"
      OutValue_4: "JobName"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelSyndication"
      WorkingTemplate: "syndication/MasterProductList_52"
  - id: "RemoveClipboard1"
    type: "pipelet"
    ref: "RemoveClipboard"
    config:
      SessionRegistrationID: "Products"
  - id: "RemoveClipboard2"
    type: "pipelet"
    ref: "RemoveClipboard"
    config:
      SessionRegistrationID: "Products"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "OnlineFlag"
      Value: 1
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "OnlineFlag"
      Value: 1
  - id: "SetDictionaryValue3"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "DetermineRepositoriesPipeline"
      Value: "DetermineRepositories-Master"
  - id: "SetDictionaryValue4"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewSyndicationMasterProducts_52-Paging"
  - id: "SetDictionaryValue5"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewSyndication_52-Start"
  - id: "SetDictionaryValue6"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "JumpTarget"
      Value: "ViewSyndicationMasterProducts_52-AssignDirect"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Products"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Products"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultHandlerPipeline: "ViewSyndicationMasterProducts_52-Paging"
      DefaultPageLocatorName: "SyndicationProductList"
    bindings:
      Pageable: "Products"
  - id: "UpdateClipboard1"
    type: "pipelet"
    ref: "UpdateClipboard"
    config:
      SessionRegistrationID: "Products"
      StoreFormValues: "No"
    bindings:
      AllObjectUUIDs: "ProductUUIDIterator"
      SelectedObjectUUIDs: "SelectedProductUUIDIterator"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      LocalizedString: "PageNumber"
      IntegerObject: "PageNumber"

links:
  - from: "Call10"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Call1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "GetClipboard1"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Call4"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "Call4"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Call7"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "Call8"
    via: "next"
    to: "SetDictionaryValue6"
    into: "in"
  - from: "Call9"
    via: "next"
    to: "RemoveClipboard2"
    into: "in"
  - from: "CallNode10"
    via: "next"
    to: "CreateProductIdentifierLookupHelper1"
    into: "in"
  - from: "CallNode1"
    via: "ERROR"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode1"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "CallNode29"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "CallNode2"
    via: "ERROR"
    to: "JoinNode2"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "CallNode3"
    via: "next"
    to: "Jump5"
    into: "in"
  - from: "CallNode52"
    via: "next"
    to: "CallNode29"
    into: "in"
  - from: "CallNode53"
    via: "next"
    to: "CheckForEmptyIterator1"
    into: "in"
  - from: "CallNode54"
    via: "next"
    to: "CallNode10"
    into: "in"
  - from: "CheckForEmptyIterator1"
    via: "error"
    to: "JoinNode2"
    into: "in1"
  - from: "CheckForEmptyIterator1"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "CreateProductIdentifierLookupHelper1"
    via: "next"
    to: "GetOffersBySupplierProducts2"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Call8"
    into: "in"
  - from: "Decision2"
    via: "no"
    to: "SetDictionaryValue5"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "SetDictionaryValue4"
    into: "in"
  - from: "Decision3"
    via: "no"
    to: "Decision4"
    into: "in"
  - from: "Decision3"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "Join1"
    into: "in1"
  - from: "Decision4"
    via: "yes"
    to: "SetPage1"
    into: "in"
  - from: "DecisionNode0"
    via: "no"
    to: "JoinNode0"
    into: "in1"
  - from: "DecisionNode0"
    via: "yes"
    to: "JumpNode0"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode0"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "DecisionNode0"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "Decision2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GetClipboard1"
    via: "next"
    to: "GetProducts1"
    into: "in"
  - from: "GetCurrencies1"
    via: "next"
    to: "CallNode52"
    into: "in"
  - from: "GetFormSelection1"
    via: "next"
    to: "UpdateClipboard1"
    into: "in"
  - from: "GetFormSelection2"
    via: "next"
    to: "GetFormSelection1"
    into: "in"
  - from: "GetLabels1"
    via: "next"
    to: "GetCurrencies1"
    into: "in"
  - from: "GetOffersBySupplierProducts2"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "GetPageLocator1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "GetPageable1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "GetPageable1"
    via: "next"
    to: "SetDictionaryValue3"
    into: "in"
  - from: "GetProducts1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "Join2"
    via: "next"
    to: "RemoveClipboard1"
    into: "in"
  - from: "Join3"
    via: "next"
    to: "CallNode53"
    into: "in"
  - from: "Join6"
    via: "next"
    to: "GetLabels1"
    into: "in"
  - from: "Join7"
    via: "next"
    to: "SetPageLocator1"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "JoinNode0"
    via: "next"
    to: "Jump1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "JoinNode3"
    via: "next"
    to: "Jump7"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "KeyMapper2"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "RemoveClipboard1"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "RemoveClipboard2"
    via: "next"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "SetDictionaryValue3"
    via: "next"
    to: "Call10"
    into: "in"
  - from: "SetDictionaryValue4"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "SetDictionaryValue5"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "SetDictionaryValue6"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "SetPage1"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "SetPage2"
    via: "next"
    to: "Join8"
    into: "in1"
  - from: "SetPageLocator1"
    via: "next"
    to: "CallNode54"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Start4"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Start5"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "GetFormSelection2"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "Call9"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "UpdateClipboard1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join8"
    into: "in1"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage2"
    into: "in"
