flow: "ViewPromotionCode_52"
kind: "view"

entries:
  - id: "Start2"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "Show"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Paging"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode4"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode5"
    name: "Sort"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode6"
    name: "ParametricSearch"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "CallNode1"
    type: "call"
    ref: "ViewPromotionCode_52-Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "ProcessPromotion-GetPromotionDomainByChannel"
    bindings:
      Channel: "CurrentChannel"
      PromotionDomain: "Domain"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessPromotion-GetPromotionDomainByChannel"
    bindings:
      Channel: "CurrentChannel"
      PromotionDomain: "Domain"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessPromotionCode_52-ProcessParametricConsumerSearch"
    bindings:
      SearchTerm: "PromotionCodeConsumerSearchForm:SearchTerm:Value"
  - id: "CallNode5"
    type: "call"
    ref: "ProcessPromotionCode_52-ProcessParametricConsumerSearch"
  - id: "CallNode6"
    type: "call"
    ref: "ViewPromotionCode_52-Prefix"
  - id: "CallNode7"
    type: "call"
    ref: "This:Prefix"
  - id: "CallNode9"
    type: "call"
    ref: "This:Prefix"
  - id: "CreateForm3"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "PromotionCodeConsumerSearch"
      FormResource: "PromotionCodeConsumerSearch"
    bindings:
      Form: "PromotionCodeConsumerSearchForm"
  - id: "CreateForm5"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormResource: "PromotionCodeConsumerSearch"
      FormName: "PromotionCodeConsumerSearch"
    bindings:
      Form: "PromotionCodeConsumerSearchForm"
  - id: "Decision1"
    type: "decision"
    condition: "PromotionCode"
  - id: "Decision2"
    type: "decision"
    condition: "PromotionCodeGroupID"
  - id: "Decision3"
    type: "decision"
    condition: "PromotionCodeGroup"
  - id: "Decision4"
    type: "decision"
    condition: "Code"
  - id: "Decision5"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision6"
    type: "decision"
    condition: "PageNumber"
  - id: "Decision7"
    type: "decision"
    condition: "PageNumber"
  - id: "DecisionNode1"
    type: "decision"
    condition: "PromotionCode:OrderCount"
  - id: "DecisionNode2"
    type: "decision"
    condition: "Consumers"
  - id: "DecisionNode3"
    type: "decision"
    condition: "Consumers"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      PagingPipeline: "ViewPromotionCode_52-Paging"
    bindings:
      SelectionKey: "JumpTarget"
  - id: "End1"
    type: "end"
    strict: false
  - id: "EndNode1"
    type: "end"
    strict: false
  - id: "ExchangeSessionObject1"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "PromotionCodeConsumerSearchForm"
    bindings:
      SaveObject: "PromotionCodeConsumerSearchForm"
  - id: "ExchangeSessionObject2"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "PromotionCodeConsumerSearchForm"
    bindings:
      SaveObject: "PromotionCodeConsumerSearchForm"
  - id: "ExchangeSessionObject3"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "PromotionCodeConsumerSearchForm"
    bindings:
      LoadObject: "PromotionCodeConsumerSearchForm"
  - id: "ExchangeSessionObject4"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "PromotionCodeConsumerSearchForm"
    bindings:
      LoadObject: "PromotionCodeConsumerSearchForm"
  - id: "GetPageLocator1"
    type: "pipelet"
    ref: "GetPageLocator"
    config:
      DefaultPageLocatorName: "PromotionCodeConsumersPageLocator"
      RestorePageLocatorDictionary: "True"
    bindings:
      PageLocatorName: "null"
  - id: "GetPageable1"
    type: "pipelet"
    ref: "GetPageable"
    bindings:
      Pageable: "Consumers"
      PageableID: "PageLocator:PageableID"
  - id: "GetPromotionCodeByCode1"
    type: "pipelet"
    ref: "GetPromotionCodeByCode"
  - id: "GetPromotionCodeGroupByID1"
    type: "pipelet"
    ref: "GetPromotionCodeGroupByID"
    bindings:
      GroupID: "PromotionCodeGroupID"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join5"
    type: "join"
  - id: "Join6"
    type: "join"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode10"
    type: "join"
  - id: "JoinNode11"
    type: "join"
  - id: "JoinNode12"
    type: "join"
  - id: "JoinNode15"
    type: "join"
  - id: "JoinNode16"
    type: "join"
  - id: "JoinNode17"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode5"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JoinNode8"
    type: "join"
  - id: "JoinNode9"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewPromotionCode_52-Show"
  - id: "JumpNode2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/PromotionCode_52"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/PromotionCode_52"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "OnlineMarketing"
      WorkingTemplate: "marketing/PromotionCode_52"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"
  - id: "SetPage1"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Consumers"
  - id: "SetPage2"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Consumers"
  - id: "SetPage3"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Consumers"
  - id: "SetPage4"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Consumers"
  - id: "SetPage5"
    type: "pipelet"
    ref: "SetPage"
    config:
      DefaultPageNumber: 0
    bindings:
      PageNumber: "PageLocator:PageNumber"
      Pageable: "Consumers"
  - id: "SetPage6"
    type: "pipelet"
    ref: "SetPage"
    bindings:
      Pageable: "Consumers"
  - id: "SetPageLocator1"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultPageLocatorName: "PromotionCodeConsumersPageLocator"
      DefaultHandlerPipeline: "ViewPromotionCode_52-Paging"
    bindings:
      Pageable: "Consumers"
      PageLocatorName: "null"
      HandlerPipeline: "null"
  - id: "SetPageLocator2"
    type: "pipelet"
    ref: "SetPageLocator"
    config:
      DefaultPageLocatorName: "PromotionCodeConsumersPageLocator"
      DefaultHandlerPipeline: "ViewPromotionCode_52-Paging"
    bindings:
      Pageable: "Consumers"
      PageLocatorName: "null"
      HandlerPipeline: "null"
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "PromotionCodeConsumerSearchForm"
  - id: "VerifyInteger1"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"
      Locale: "null"
      Pattern: "null"
  - id: "VerifyInteger2"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"
      Locale: "null"
      Pattern: "null"
  - id: "VerifyInteger3"
    type: "pipelet"
    ref: "VerifyInteger"
    bindings:
      IntegerObject: "PageNumber"
      LocalizedString: "PageNumber"
      Locale: "null"
      Pattern: "null"

links:
  - from: "JoinNode10"
    via: "next"
    to: "JoinNode7"
    into: "in3"
  - from: "CallNode6"
    via: "Failed"
    to: "JoinNode11"
    into: "in3"
  - from: "JoinNode4"
    via: "next"
    to: "EndNode1"
    into: "in"
  - from: "Decision6"
    via: "no"
    to: "SetPage2"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode9"
    into: "in2"
  - from: "ExchangeSessionObject1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "GetPageable1"
    via: "next"
    to: "Decision6"
    into: "in"
  - from: "SetPage5"
    via: "next"
    to: "Join4"
    into: "in3"
  - from: "JoinNode2"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Join5"
    via: "next"
    to: "Join6"
    into: "in1"
  - from: "CallNode2"
    via: "next"
    to: "GetPromotionCodeByCode1"
    into: "in"
  - from: "JoinNode12"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "JoinNode8"
    into: "in2"
  - from: "CallNode3"
    via: "next"
    to: "GetPromotionCodeGroupByID1"
    into: "in"
  - from: "SetPage2"
    via: "next"
    to: "Join6"
    into: "in3"
  - from: "Join6"
    via: "next"
    to: "JoinNode11"
    into: "in1"
  - from: "JoinNode11"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "CallNode9"
    via: "next"
    to: "CreateForm3"
    into: "in"
  - from: "CallNode5"
    via: "next"
    to: "DecisionNode3"
    into: "in"
  - from: "JoinNode5"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "DecisionNode1"
    via: "yes"
    to: "CallNode5"
    into: "in"
  - from: "DecisionNode3"
    via: "no"
    to: "JoinNode10"
    into: "in2"
  - from: "VerifyInteger2"
    via: "next"
    to: "SetPage1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "DecisionNode2"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Decision3"
    into: "in"
  - from: "JoinNode7"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "StartNode4"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "Decision4"
    via: "no"
    to: "JoinNode5"
    into: "in1"
  - from: "GetPageable1"
    via: "error"
    to: "JoinNode12"
    into: "in2"
  - from: "ValidateForm1"
    via: "error"
    to: "JoinNode6"
    into: "in2"
  - from: "GetPageLocator1"
    via: "next"
    to: "GetPageable1"
    into: "in"
  - from: "GetPromotionCodeByCode1"
    via: "error"
    to: "JoinNode4"
    into: "in1"
  - from: "Decision3"
    via: "yes"
    to: "Decision2"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "End1"
    into: "in"
  - from: "Decision6"
    via: "yes"
    to: "VerifyInteger2"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "Decision4"
    into: "in"
  - from: "VerifyInteger2"
    via: "error"
    to: "Join5"
    into: "in3"
  - from: "ExchangeSessionObject3"
    via: "next"
    to: "GetPageLocator1"
    into: "in"
  - from: "ValidateForm1"
    via: "next"
    to: "JoinNode6"
    into: "in1"
  - from: "Decision2"
    via: "no"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode2"
    via: "next"
    to: "CallNode6"
    into: "in"
  - from: "CallNode1"
    via: "Failed"
    to: "JoinNode8"
    into: "in1"
  - from: "GetPromotionCodeByCode1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "DecisionNode3"
    via: "yes"
    to: "SetPageLocator1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "JoinNode3"
    into: "in2"
  - from: "CallNode1"
    via: "next"
    to: "CreateForm5"
    into: "in"
  - from: "Decision7"
    via: "no"
    to: "SetPage5"
    into: "in"
  - from: "CallNode6"
    via: "next"
    to: "ExchangeSessionObject3"
    into: "in"
  - from: "Decision4"
    via: "yes"
    to: "CallNode2"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "JoinNode7"
    into: "in1"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "JoinNode6"
    via: "next"
    to: "ExchangeSessionObject2"
    into: "in"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "StartNode6"
    via: "next"
    to: "CallNode9"
    into: "in"
  - from: "SetPage1"
    via: "next"
    to: "Join5"
    into: "in1"
  - from: "Decision3"
    via: "no"
    to: "JoinNode2"
    into: "in2"
  - from: "JoinNode8"
    via: "next"
    to: "JoinNode10"
    into: "in1"
  - from: "GetPageLocator1"
    via: "error"
    to: "JoinNode12"
    into: "in1"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode5"
    into: "in2"
  - from: "CreateForm3"
    via: "next"
    to: "ValidateForm1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "GetPromotionCodeGroupByID1"
    via: "error"
    to: "JoinNode1"
    into: "in1"
  - from: "CreateForm5"
    via: "next"
    to: "ExchangeSessionObject1"
    into: "in"
  - from: "ExchangeSessionObject4"
    via: "next"
    to: "JoinNode16"
    into: "in3"
  - from: "GetPromotionCodeGroupByID1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Join3"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "SetPage6"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "VerifyInteger3"
    via: "next"
    to: "SetPage6"
    into: "in"
  - from: "VerifyInteger3"
    via: "error"
    to: "Join3"
    into: "in3"
  - from: "Decision7"
    via: "yes"
    to: "VerifyInteger3"
    into: "in"
  - from: "SetPageLocator2"
    via: "next"
    to: "Decision7"
    into: "in"
  - from: "SetPage3"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "SetPage4"
    via: "next"
    to: "Join1"
    into: "in3"
  - from: "Decision5"
    via: "yes"
    to: "VerifyInteger1"
    into: "in"
  - from: "Join2"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "DecisionNode2"
    via: "yes"
    to: "SetPageLocator2"
    into: "in"
  - from: "VerifyInteger1"
    via: "error"
    to: "Join2"
    into: "in3"
  - from: "VerifyInteger1"
    via: "next"
    to: "SetPage3"
    into: "in"
  - from: "Decision5"
    via: "no"
    to: "SetPage4"
    into: "in"
  - from: "SetPageLocator1"
    via: "next"
    to: "Decision5"
    into: "in"
  - from: "StartNode5"
    via: "next"
    to: "CallNode7"
    into: "in"
  - from: "CallNode7"
    via: "next"
    to: "ExchangeSessionObject4"
    into: "in"
  - from: "CallNode9"
    via: "Failed"
    to: "JoinNode15"
    into: "in1"
  - from: "CallNode7"
    via: "Failed"
    to: "JoinNode15"
    into: "in1"
  - from: "ExchangeSessionObject2"
    via: "next"
    to: "JoinNode16"
    into: "in1"
  - from: "JoinNode16"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "Decision2"
    via: "yes"
    to: "CallNode3"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "JoinNode17"
    into: "in1"
  - from: "JoinNode17"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "JoinNode15"
    via: "next"
    to: "JoinNode9"
    into: "in1"
  - from: "JoinNode9"
    via: "next"
    to: "JoinNode17"
    into: "in3"
