flow: "ViewChannelParentCategory_52"
kind: "view"

entries:
  - id: "Start1"
    name: "Tree"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start2"
    name: "Expand"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start3"
    name: "Collapse"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start5"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start6"
    name: "Assign"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start7"
    name: "Cancel"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start8"
    name: "Dispatch"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "Start9"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "Call1"
    type: "call"
    ref: "ViewChannelParentCategory_52-Prefix"
  - id: "Call2"
    type: "call"
    ref: "ViewChannelParentCategory_52-Prefix"
  - id: "Call3"
    type: "call"
    ref: "ViewChannelParentCategory_52-Prefix"
  - id: "Call5"
    type: "call"
    ref: "ViewChannelParentCategory_52-Prefix"
  - id: "Call6"
    type: "call"
    ref: "ViewChannelParentCategory_52-Prefix"
  - id: "Call7"
    type: "call"
    ref: "ViewChannelParentCategory_52-Prefix"
  - id: "CheckForEmptyString1"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "CurrentCategoryID"
  - id: "CheckForEmptyString2"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "CurrentCategoryID"
  - id: "CheckForEmptyString3"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "CurrentCategoryID"
  - id: "CheckForEmptyString4"
    type: "pipelet"
    ref: "CheckForEmptyString"
    bindings:
      FilledString: "CurrentCategoryID"
  - id: "Decision1"
    type: "decision"
    condition: "SelectedCategoryUUID"
  - id: "DetermineCatalogCategoriesPath1"
    type: "pipelet"
    ref: "DetermineCatalogCategoriesPath"
    bindings:
      CatalogCategoryID: "ParentCategoryID"
  - id: "DetermineCatalogCategoriesPath2"
    type: "pipelet"
    ref: "DetermineCatalogCategoriesPath"
    bindings:
      CatalogCategoryID: "xxxxxx"
      Category: "ParentCategory"
  - id: "DetermineCatalogCategoriesPath3"
    type: "pipelet"
    ref: "DetermineCatalogCategoriesPath"
    bindings:
      CatalogCategoryID: "ParentCategoryID"
  - id: "DetermineCatalogCategoriesPath4"
    type: "pipelet"
    ref: "DetermineCatalogCategoriesPath"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewChannelParentCategory_52-Assign"
      OutValue_1: "ViewChannelParentCategory_52-Collapse"
      OutValue_2: "ViewChannelParentCategory_52-Expand"
      OutValue_3: "ViewChannelParentCategory_52-Cancel"
    bindings:
      Key_0: "assign"
      Key_1: "collpase"
      Key_2: "expand"
      Key_3: "cancel"
      SelectionKey: "JumpTarget"
  - id: "End2"
    type: "end"
    strict: false
  - id: "ExchangeSessionObject1"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Put Object to Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      SaveObject: "ExpandedCategoriesMap"
  - id: "ExchangeSessionObject2"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      LoadObject: "ExpandedCategoriesMap"
  - id: "ExchangeSessionObject3"
    type: "pipelet"
    ref: "ExchangeSessionObject"
    config:
      ProcessMethod: "Get Object from Session"
      SessionObjectName: "ExpandedCategoriesMap"
    bindings:
      LoadObject: "ExpandedCategoriesMap"
  - id: "GetCatalog1"
    type: "pipelet"
    ref: "GetCatalog"
    bindings:
      OrganizationDomain: "CurrentSelectedChannel:Domain"
  - id: "GetCatalog2"
    type: "pipelet"
    ref: "GetCatalog"
    bindings:
      OrganizationDomain: "CurrentSelectedChannel:Domain"
  - id: "GetCatalog3"
    type: "pipelet"
    ref: "GetCatalog"
    bindings:
      OrganizationDomain: "CurrentSelectedChannel:Domain"
  - id: "GetCatalogByCategory1"
    type: "pipelet"
    ref: "GetCatalogByCategory"
    bindings:
      CatalogCategory: "Category"
  - id: "GetCategoryByUUID1"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "ParentCategoryID"
  - id: "GetCategoryByUUID2"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "CurrentCategoryID"
      Category: "CurrentCategory"
  - id: "GetCategoryByUUID3"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "CurrentCategoryID"
  - id: "GetCategoryByUUID4"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "SelectedCategoryUUID"
      Category: "SelectedParentCategory"
  - id: "GetCategoryByUUID5"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "ParentCategoryID"
      Category: "ParentCategory"
  - id: "GetCategoryByUUID6"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "CurrentCategoryID"
      Category: "CurrentCategory"
  - id: "GetCategoryByUUID7"
    type: "pipelet"
    ref: "GetCategoryByUUID"
    bindings:
      CatalogCategoryID: "CurrentCategoryID"
      Category: "CurrentCategory"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
  - id: "GetWebForm1"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "RegFormAddCategory"
    bindings:
      WebForm: "RegFormAddCategory"
  - id: "GetWebForm2"
    type: "pipelet"
    ref: "GetWebForm"
    config:
      webform-id: "RegFormAddCategory"
    bindings:
      WebForm: "RegFormAddCategory"
  - id: "InteractionEnd1"
    type: "interaction"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "InteractionEnd3"
    type: "interaction"
  - id: "InteractionEnd4"
    type: "interaction"
  - id: "Join1"
    type: "join"
  - id: "Join10"
    type: "join"
  - id: "Join2"
    type: "join"
  - id: "Join3"
    type: "join"
  - id: "Join4"
    type: "join"
  - id: "Join7"
    type: "join"
  - id: "Join8"
    type: "join"
  - id: "Join9"
    type: "join"
  - id: "Jump10"
    type: "jump"
    ref: "ViewChannelCatalogList_52-ListAll"
  - id: "Jump11"
    type: "jump"
    ref: "ViewChannelParentCategory_52-Tree"
  - id: "Jump12"
    type: "jump"
    ref: "ViewChannelCatalogList_52-ListAll"
  - id: "Jump13"
    type: "jump"
    ref: "ViewChannelCatalogList_52-ListAll"
  - id: "Jump14"
    type: "jump"
    ref: "ViewChannelCatalogList_52-ListAll"
  - id: "Jump15"
    type: "jump"
    ref: "ViewChannelCatalogList_52-ListAll"
  - id: "Jump4"
    type: "jump"
    ref: "ViewChannelCatalogList_52-ListAll"
  - id: "Jump5"
    type: "jump"
    ref: "ViewChannelCatalogList_52-ListAll"
  - id: "Jump6"
    type: "jump"
    ref: "ViewChannelParentCategory_52-Tree"
  - id: "Jump7"
    type: "jump"
    ref: "ViewChannelCatalogList_52-ListAll"
  - id: "Jump8"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "Jump9"
    type: "jump"
    ref: "ViewChannelCatalogList_52-ListAll"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "CatalogCategoryID"
      OutValue_1: "CurrentCategoryID"
  - id: "LoadPageletDefinitions2"
    type: "pipelet"
    ref: "LoadPageletDefinitions"
    config:
      DefaultType: "Page"
    bindings:
      Site: "CurrentChannel:Domain:Site"
  - id: "Loop1"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelCatalogs"
      WorkingTemplate: "category/ChannelCatalogCategory_52"
  - id: "PrepareApplicationView2"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelCatalogs"
      WorkingTemplate: "category/ChannelParentCategoryTree_52"
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelCatalogs"
      WorkingTemplate: "category/ChannelParentCategoryTree_52"
  - id: "PrepareApplicationView4"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelCatalogs"
      WorkingTemplate: "category/ChannelParentCategoryTree_52"
  - id: "PrepareApplicationView5"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "ChannelCatalogs"
      WorkingTemplate: "category/NewChannelCatalogCategory_52"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ParentBrowsingCancelled"
      Value: "True"
  - id: "UpdateMapping1"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "Parent:Parent:Parent:UUID"
      OutMap: "ExpandedCategoriesMap"
      Value: "Parent:Parent:Parent:UUID"
  - id: "UpdateMapping2"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Add"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "CategoryUUID"
      Value: "CategoryUUID"
  - id: "UpdateMapping3"
    type: "pipelet"
    ref: "UpdateMapping"
    config:
      Mode: "Remove"
    bindings:
      InMap: "ExpandedCategoriesMap"
      Key: "CategoryUUID"
      Value: "CategoryUUID"
  - id: "UpdateWebForm1"
    type: "pipelet"
    ref: "UpdateWebForm"
    config:
      mode: "update"
      webform-id: "RegFormAddCategory"
    bindings:
      WebForm: "RegFormAddCategory"

links:
  - from: "Start5"
    via: "next"
    to: "Call5"
    into: "in"
  - from: "LoadPageletDefinitions2"
    via: "next"
    to: "CheckForEmptyString4"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "Jump8"
    into: "in"
  - from: "PrepareApplicationView5"
    via: "next"
    to: "Join7"
    into: "in3"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "Join7"
    into: "in1"
  - from: "GetWebForm1"
    via: "next"
    to: "UpdateWebForm1"
    into: "in"
  - from: "Join1"
    via: "next"
    to: "GetWebForm2"
    into: "in"
  - from: "Start7"
    via: "next"
    to: "Call6"
    into: "in"
  - from: "GetWebForm1"
    via: "error"
    to: "Jump10"
    into: "in"
  - from: "GetWebForm2"
    via: "error"
    to: "Join8"
    into: "in2"
  - from: "GetCategoryByUUID4"
    via: "error"
    to: "Join8"
    into: "in1"
  - from: "Join7"
    via: "next"
    to: "InteractionEnd4"
    into: "in"
  - from: "GetCategoryByUUID4"
    via: "next"
    to: "Join1"
    into: "in1"
  - from: "GetCategoryByUUID3"
    via: "error"
    to: "Join10"
    into: "in2"
  - from: "Join2"
    via: "next"
    to: "Join10"
    into: "in1"
  - from: "GetCategoryByUUID5"
    via: "next"
    to: "DetermineCatalogCategoriesPath2"
    into: "in"
  - from: "Join10"
    via: "next"
    to: "Jump9"
    into: "in"
  - from: "Start6"
    via: "next"
    to: "Call7"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "Join1"
    into: "in2"
  - from: "DetermineLocales1"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "GetLocale1"
    via: "next"
    to: "GetCategoryByUUID5"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "Jump11"
    into: "in"
  - from: "PrepareApplicationView2"
    via: "next"
    to: "InteractionEnd3"
    into: "in"
  - from: "ExchangeSessionObject1"
    via: "next"
    to: "PrepareApplicationView2"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd1"
    into: "in"
  - from: "PrepareApplicationView4"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "GetCategoryByUUID1"
    via: "next"
    to: "GetCatalogByCategory1"
    into: "in"
  - from: "GetCatalogByCategory1"
    via: "next"
    to: "DetermineCatalogCategoriesPath4"
    into: "in"
  - from: "Start1"
    via: "next"
    to: "Call1"
    into: "in"
  - from: "Loop1"
    via: "do"
    to: "UpdateMapping1"
    into: "in"
  - from: "GetCatalog1"
    via: "next"
    to: "ExchangeSessionObject3"
    into: "in"
  - from: "GetCatalog2"
    via: "next"
    to: "ExchangeSessionObject2"
    into: "in"
  - from: "ExchangeSessionObject2"
    via: "next"
    to: "UpdateMapping2"
    into: "in"
  - from: "UpdateMapping2"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "ExchangeSessionObject3"
    via: "next"
    to: "UpdateMapping3"
    into: "in"
  - from: "UpdateMapping3"
    via: "next"
    to: "PrepareApplicationView4"
    into: "in"
  - from: "UpdateWebForm1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "GetWebForm2"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "Decision1"
    via: "no"
    to: "Jump6"
    into: "in"
  - from: "Start2"
    via: "next"
    to: "Call2"
    into: "in"
  - from: "Decision1"
    via: "yes"
    to: "GetCategoryByUUID4"
    into: "in"
  - from: "Join9"
    via: "next"
    to: "Loop1"
    into: "in"
  - from: "GetCategoryByUUID2"
    via: "next"
    to: "Join9"
    into: "in1"
  - from: "UpdateMapping1"
    via: "next"
    to: "Loop1"
    into: "loop"
  - from: "Loop1"
    via: "next"
    to: "ExchangeSessionObject1"
    into: "in"
  - from: "GetCategoryByUUID6"
    via: "next"
    to: "Join4"
    into: "in1"
  - from: "GetCategoryByUUID7"
    via: "next"
    to: "Join3"
    into: "in1"
  - from: "Join3"
    via: "next"
    to: "GetCatalog1"
    into: "in"
  - from: "Join4"
    via: "next"
    to: "GetCatalog2"
    into: "in"
  - from: "DetermineCatalogCategoriesPath4"
    via: "next"
    to: "CheckForEmptyString1"
    into: "in"
  - from: "Start3"
    via: "next"
    to: "Call3"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "next"
    to: "GetCategoryByUUID2"
    into: "in"
  - from: "CheckForEmptyString1"
    via: "error"
    to: "Join9"
    into: "in3"
  - from: "DetermineCatalogCategoriesPath1"
    via: "next"
    to: "CheckForEmptyString3"
    into: "in"
  - from: "CheckForEmptyString3"
    via: "next"
    to: "GetCategoryByUUID7"
    into: "in"
  - from: "CheckForEmptyString2"
    via: "next"
    to: "GetCategoryByUUID6"
    into: "in"
  - from: "DetermineCatalogCategoriesPath3"
    via: "next"
    to: "CheckForEmptyString2"
    into: "in"
  - from: "CheckForEmptyString2"
    via: "error"
    to: "Join4"
    into: "in3"
  - from: "CheckForEmptyString3"
    via: "error"
    to: "Join3"
    into: "in3"
  - from: "DetermineCatalogCategoriesPath2"
    via: "next"
    to: "LoadPageletDefinitions2"
    into: "in"
  - from: "CheckForEmptyString4"
    via: "next"
    to: "GetCategoryByUUID3"
    into: "in"
  - from: "Start8"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "CheckForEmptyString4"
    via: "error"
    to: "PrepareApplicationView5"
    into: "in"
  - from: "Join8"
    via: "next"
    to: "Join2"
    into: "in1"
  - from: "GetCategoryByUUID5"
    via: "error"
    to: "Join2"
    into: "in2"
  - from: "GetCategoryByUUID7"
    via: "error"
    to: "Jump7"
    into: "in"
  - from: "GetCategoryByUUID6"
    via: "error"
    to: "Jump5"
    into: "in"
  - from: "GetCatalog2"
    via: "error"
    to: "Jump4"
    into: "in"
  - from: "GetCatalog1"
    via: "error"
    to: "Jump15"
    into: "in"
  - from: "GetCategoryByUUID2"
    via: "error"
    to: "Jump14"
    into: "in"
  - from: "GetCatalogByCategory1"
    via: "error"
    to: "Jump12"
    into: "in"
  - from: "GetCategoryByUUID1"
    via: "error"
    to: "Jump13"
    into: "in"
  - from: "GetCategoryByUUID3"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "Call1"
    via: "next"
    to: "GetCategoryByUUID1"
    into: "in"
  - from: "Call2"
    via: "next"
    to: "DetermineCatalogCategoriesPath3"
    into: "in"
  - from: "Call3"
    via: "next"
    to: "DetermineCatalogCategoriesPath1"
    into: "in"
  - from: "Call5"
    via: "next"
    to: "GetWebForm1"
    into: "in"
  - from: "Call7"
    via: "next"
    to: "Decision1"
    into: "in"
  - from: "Call6"
    via: "next"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "GetCatalog3"
    via: "next"
    to: "End2"
    into: "in"
  - from: "Start9"
    via: "next"
    to: "GetCatalog3"
    into: "in"
