flow: "ViewOrganizationEnterprisePayment"
kind: "view"

entries:
  - id: "Start4"
    name: "Prefix"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode1"
    name: "ListAll"
    mode: "private"
    strict: false
    inputs:
      []
  - id: "StartNode2"
    name: "Update"
    mode: "private"
    strict: false
    inputs:
      []

steps:
  - id: "AssignPaymentService1"
    type: "pipelet"
    ref: "AssignPaymentService"
    bindings:
      AssignedDomain: "Organization:OrganizationDomain"
      Domain: "Organization:OrganizationDomain"
  - id: "CallNode1"
    type: "call"
    ref: "ViewOrganizationEnterprisePayment-Prefix"
  - id: "CallNode2"
    type: "call"
    ref: "ViewOrganizationEnterprisePayment-Prefix"
  - id: "CallNode3"
    type: "call"
    ref: "ProcessClipboard-Update"
  - id: "CallNode4"
    type: "call"
    ref: "ProcessClipboard-Delete"
  - id: "CombineIterators1"
    type: "pipelet"
    ref: "CombineIterators"
    config:
      ProcessMethod: "Subtract Iterators"
    bindings:
      Iterator1: "AllObjectUUIDs"
      Iterator2: "SelectedObjectUUIDs"
      Iterator: "UnselectedUUIDs"
  - id: "End2"
    type: "end"
    strict: false
  - id: "ExecuteCartridgePipelines1"
    type: "pipelet"
    ref: "ExecuteCartridgePipelines"
    config:
      Asynchronous: false
      PipelinePropertyName: "PaymentServiceAssignmentCreationHook"
      ProcessReversely: false
  - id: "ExecuteCartridgePipelines2"
    type: "pipelet"
    ref: "ExecuteCartridgePipelines"
    config:
      Asynchronous: false
      PipelinePropertyName: "PaymentServiceAssignmentDeletionHook"
      ProcessReversely: false
  - id: "GetAllPaymentServices1"
    type: "pipelet"
    ref: "GetAllPaymentServices"
  - id: "GetAllServiceGroups1"
    type: "pipelet"
    ref: "GetAllServiceGroups"
  - id: "GetAssignedPaymentServices1"
    type: "pipelet"
    ref: "GetAssignedPaymentServices"
    bindings:
      AssignmentDomain: "Organization:OrganizationDomain"
      AssignedPaymentServices: "AssignedPaymentServices"
  - id: "GetOrganization1"
    type: "pipelet"
    ref: "GetOrganization"
    config:
      Source: "PipelineDictionary"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewOrganizationEnterprisePayment-ListAll"
  - id: "KeyMapper1"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Organization:OrganizationDomain"
      OutValue_1: "PaymentServiceAssignmentDomain"
  - id: "KeyMapper2"
    type: "pipelet"
    ref: "KeyMapper"
    bindings:
      InValue_1: "Organization:OrganizationDomain"
      OutValue_1: "PaymentServiceAssignmentDomain"
  - id: "LoopNode1"
    type: "loop"
  - id: "LoopNode2"
    type: "loop"
  - id: "PrepareApplicationView1"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Enterprises"
      WorkingTemplate: "organization/OrganizationEnterprisePayment"
  - id: "SortIteratorByComparator2"
    type: "pipelet"
    ref: "SortIteratorByComparator"
    config:
      DefaultSortingAttribute: "ID"
      DefaultSortingOrder: true
    bindings:
      SortedIterator: "PaymentServices"
      Iterator: "PaymentServices"
      SortingAttribute: "null"
      SortingOrder: "null"
  - id: "UnassignPaymentService1"
    type: "pipelet"
    ref: "UnassignPaymentService"
    bindings:
      AssignedDomain: "Organization:OrganizationDomain"

links:
  - from: "GetOrganization1"
    via: "next"
    to: "GetAllServiceGroups1"
    into: "in"
  - from: "CallNode2"
    via: "next"
    to: "CallNode4"
    into: "in"
  - from: "SortIteratorByComparator2"
    via: "next"
    to: "PrepareApplicationView1"
    into: "in"
  - from: "LoopNode2"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "GetAllServiceGroups1"
    via: "next"
    to: "End2"
    into: "in"
  - from: "ExecuteCartridgePipelines2"
    via: "error"
    to: "JoinNode1"
    into: "in2"
  - from: "CallNode3"
    via: "next"
    to: "CombineIterators1"
    into: "in"
  - from: "CombineIterators1"
    via: "next"
    to: "LoopNode1"
    into: "in"
  - from: "LoopNode1"
    via: "do"
    to: "AssignPaymentService1"
    into: "in"
  - from: "LoopNode2"
    via: "do"
    to: "UnassignPaymentService1"
    into: "in"
  - from: "ExecuteCartridgePipelines1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "Start4"
    via: "next"
    to: "GetOrganization1"
    into: "in"
  - from: "LoopNode1"
    via: "next"
    to: "LoopNode2"
    into: "in"
  - from: "KeyMapper1"
    via: "next"
    to: "ExecuteCartridgePipelines2"
    into: "in"
  - from: "ExecuteCartridgePipelines2"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "UnassignPaymentService1"
    via: "next"
    to: "KeyMapper1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "LoopNode2"
    into: "loop"
  - from: "KeyMapper2"
    via: "next"
    to: "ExecuteCartridgePipelines1"
    into: "in"
  - from: "ExecuteCartridgePipelines1"
    via: "error"
    to: "JoinNode2"
    into: "in2"
  - from: "AssignPaymentService1"
    via: "next"
    to: "KeyMapper2"
    into: "in"
  - from: "JoinNode2"
    via: "next"
    to: "LoopNode1"
    into: "loop"
  - from: "StartNode1"
    via: "next"
    to: "CallNode1"
    into: "in"
  - from: "CallNode1"
    via: "next"
    to: "GetAllPaymentServices1"
    into: "in"
  - from: "GetAllPaymentServices1"
    via: "next"
    to: "GetAssignedPaymentServices1"
    into: "in"
  - from: "PrepareApplicationView1"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "CallNode4"
    via: "next"
    to: "CallNode3"
    into: "in"
  - from: "StartNode2"
    via: "next"
    to: "CallNode2"
    into: "in"
  - from: "GetAssignedPaymentServices1"
    via: "next"
    to: "SortIteratorByComparator2"
    into: "in"
