flow: "ViewApplicationPromotionPreferenceLegalContentMessage"
kind: "view"

entries:
  - id: "StartNode1"
    name: "Start"
    mode: "private"
    strict: false
    inputs:
      - key: "ApplicationUUID"
        type: "java.lang.String"
        required: true
  - id: "StartNode2"
    name: "Edit"
    mode: "private"
    strict: false
    inputs:
      - key: "ApplicationUUID"
        type: "java.lang.String"
        required: true
  - id: "StartNode3"
    name: "DispatchLegalContentMessage"
    mode: "private"
    strict: false
    inputs:
      - key: "ApplicationUUID"
        type: "java.lang.String"
        required: true

steps:
  - id: "CreateForm1"
    type: "pipelet"
    ref: "CreateForm"
    config:
      FormName: "LegalContentMessage"
      FormResource: "LegalContentMessage"
    bindings:
      Form: "LegalContentMessageForm"
  - id: "CreateLocalizationContextFromApplication1"
    type: "pipelet"
    ref: "CreateLocalizationContextFromApplication"
    bindings:
      LocaleInformation: "SelectedLocale"
  - id: "DecisionNode1"
    type: "decision"
    condition: "setLocale"
  - id: "DecisionNode2"
    type: "decision"
    condition: "apply"
  - id: "DecisionNode5"
    type: "decision"
    condition: "ViewLegalContentMessage"
  - id: "DetermineLocales1"
    type: "pipelet"
    ref: "DetermineLocales"
    bindings:
      Locales: "AllLocales"
  - id: "DetermineLocalizedTextByLocale1"
    type: "pipelet"
    ref: "DetermineLocalizedTextByLocale"
    bindings:
      SearchedKey: "\"promotion.message.legalcontent\""
      LocalizationTexts: "LegalContentMessages"
  - id: "DispatchFormAction1"
    type: "pipelet"
    ref: "DispatchFormAction"
    config:
      OutValue_0: "ViewApplicationPromotionPreferenceLegalContentMessage-Edit"
      OutValue_1: "ViewApplicationPromotionPreferenceLegalContentMessage-Edit"
    bindings:
      Key_0: "apply"
      Key_1: "setLocale"
      SelectionKey: "JumpTarget"
  - id: "GetApplicationByUUID1"
    type: "pipelet"
    ref: "GetApplicationByUUID"
  - id: "GetFirstElementOfIterator1"
    type: "pipelet"
    ref: "GetFirstElementOfIterator"
    bindings:
      Iterator: "LegalContentMessages"
      FirstElement: "LegalContentMessage"
  - id: "GetLocale1"
    type: "pipelet"
    ref: "GetLocale"
    config:
      LocaleFallback: "Request Locale"
    bindings:
      LocaleId: "LocaleID"
      Locale: "SelectedLocale"
  - id: "InteractionEnd2"
    type: "interaction"
  - id: "JoinNode1"
    type: "join"
  - id: "JoinNode2"
    type: "join"
  - id: "JoinNode3"
    type: "join"
  - id: "JoinNode4"
    type: "join"
  - id: "JoinNode6"
    type: "join"
  - id: "JoinNode7"
    type: "join"
  - id: "JumpNode1"
    type: "jump"
    ref: "ViewApplicationPreferences-ApplicationPreferenceError"
  - id: "JumpNode2"
    type: "jump"
    ref: "SecureJump-Start"
  - id: "JumpNode3"
    type: "jump"
    ref: "ViewApplicationPromotionPreferenceLegalContentMessage-Start"
  - id: "LogMessage1"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Level: "Warn"
    bindings:
      MessageParam0: "LegalContentMessages"
      MessageText: "\"Warning: The iterator 'LegalContentMessages' is empty\""
  - id: "LogMessage2"
    type: "pipelet"
    ref: "LogMessage"
    config:
      Level: "Warn"
    bindings:
      MessageParam0: "LegalContentMessageForm"
      MessageText: "\"Validation of the 'LegalContentMessageForm' failed!\""
  - id: "PrepareApplicationView3"
    type: "pipelet"
    ref: "PrepareApplicationView"
    config:
      SelectedMenuItem: "Applications"
      WorkingTemplate: "app/ApplicationPromotionPreferences"
    bindings:
      WorkingTemplateSuffix: "CurrentChannel:TypeCode"
  - id: "SetDictionaryValue1"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ApplicationPreferenceError"
      Value: "The application cannot be found"
  - id: "SetDictionaryValue2"
    type: "pipelet"
    ref: "SetDictionaryValue"
    config:
      Name: "ViewLegalContentMessage"
      Value: true
  - id: "SetFormParameterValue1"
    type: "pipelet"
    ref: "SetFormParameterValue"
    bindings:
      FormParameter: "LegalContentMessageForm:LegalMessage"
      Value: "LegalContentMessage:DomainValue"
  - id: "TextNode1"
    type: "text"
  - id: "UpdateLocalizedText1"
    type: "pipelet"
    ref: "UpdateLocalizedText"
    bindings:
      Domain: "ChannelRepository:Domain"
      DomainValue: "LegalContentMessageForm:LegalMessage:Value"
      Key: "\"promotion.message.legalcontent\""
  - id: "ValidateForm1"
    type: "pipelet"
    ref: "ValidateForm"
    bindings:
      Form: "LegalContentMessageForm"

links:
  - from: "StartNode2"
    via: "next"
    to: "JoinNode2"
    into: "in2"
  - from: "GetFirstElementOfIterator1"
    via: "next"
    to: "SetFormParameterValue1"
    into: "in"
  - from: "LogMessage2"
    via: "next"
    to: "JoinNode4"
    into: "in3"
  - from: "LogMessage1"
    via: "next"
    to: "JoinNode1"
    into: "in3"
  - from: "DetermineLocales1"
    via: "next"
    to: "DecisionNode5"
    into: "in"
  - from: "SetFormParameterValue1"
    via: "next"
    to: "JoinNode1"
    into: "in1"
  - from: "StartNode1"
    via: "next"
    to: "JoinNode2"
    into: "in1"
  - from: "JoinNode2"
    via: "next"
    to: "GetApplicationByUUID1"
    into: "in"
  - from: "StartNode3"
    via: "next"
    to: "DispatchFormAction1"
    into: "in"
  - from: "JoinNode1"
    via: "next"
    to: "JoinNode3"
    into: "in1"
  - from: "GetFirstElementOfIterator1"
    via: "error"
    to: "LogMessage1"
    into: "in"
  - from: "DispatchFormAction1"
    via: "next"
    to: "JumpNode2"
    into: "in"
  - from: "DispatchFormAction1"
    via: "error"
    to: "JumpNode3"
    into: "in"
  - from: "JoinNode3"
    via: "next"
    to: "DetermineLocales1"
    into: "in"
  - from: "UpdateLocalizedText1"
    via: "next"
    to: "JoinNode4"
    into: "in1"
  - from: "JoinNode4"
    via: "next"
    to: "JoinNode3"
    into: "in3"
  - from: "ValidateForm1"
    via: "error"
    to: "LogMessage2"
    into: "in"
  - from: "CreateLocalizationContextFromApplication1"
    via: "next"
    to: "DecisionNode1"
    into: "in"
  - from: "ValidateForm1"
    via: "next"
    to: "UpdateLocalizedText1"
    into: "in"
  - from: "DecisionNode1"
    via: "yes"
    to: "JoinNode6"
    into: "in1"
  - from: "GetApplicationByUUID1"
    via: "error"
    to: "SetDictionaryValue1"
    into: "in"
  - from: "DecisionNode2"
    via: "yes"
    to: "ValidateForm1"
    into: "in"
  - from: "DecisionNode2"
    via: "no"
    to: "JoinNode6"
    into: "in3"
  - from: "JoinNode6"
    via: "next"
    to: "DetermineLocalizedTextByLocale1"
    into: "in"
  - from: "DecisionNode1"
    via: "no"
    to: "DecisionNode2"
    into: "in"
  - from: "PrepareApplicationView3"
    via: "next"
    to: "InteractionEnd2"
    into: "in"
  - from: "DecisionNode5"
    via: "yes"
    to: "JoinNode7"
    into: "in1"
  - from: "GetLocale1"
    via: "next"
    to: "CreateLocalizationContextFromApplication1"
    into: "in"
  - from: "DecisionNode5"
    via: "no"
    to: "SetDictionaryValue2"
    into: "in"
  - from: "SetDictionaryValue2"
    via: "next"
    to: "JoinNode7"
    into: "in3"
  - from: "JoinNode7"
    via: "next"
    to: "PrepareApplicationView3"
    into: "in"
  - from: "GetApplicationByUUID1"
    via: "next"
    to: "CreateForm1"
    into: "in"
  - from: "SetDictionaryValue1"
    via: "next"
    to: "JumpNode1"
    into: "in"
  - from: "CreateForm1"
    via: "next"
    to: "GetLocale1"
    into: "in"
  - from: "DetermineLocalizedTextByLocale1"
    via: "next"
    to: "GetFirstElementOfIterator1"
    into: "in"
